### ISSUE TITLE
Patch descriptions

### ISSUE THREAD

**Issue by oSumAtrIX** [revanced/revanced-patches#1]
Patches should have metadata like description or friendly names for the manager

**Comment by CuloArdido** [comment]
Maybe something like [PHPDoc](http://phpdocu.sourceforge.net/howto.php) could be used in patches?

**Comment by ArjixWasTaken** [comment]
> Maybe something like [PHPDoc](http://phpdocu.sourceforge.net/howto.php) could be used in patches?

Comment docs are only useful for code analysis tools. Besides, work is already being done to add metadata, I guess this issue was just not updated.

**Comment by Lucaskyy** [comment]
This issue will be closed when #2 is merged.
