### ISSUE TITLE
feat(patch): Turn off incognito auto-disable

### ISSUE THREAD

**Issue by TurtleBarrel** [ReVanced/revanced-patches#1007]
### Application

YouTube ReVanced

### Issue

If you leave the app for too long (somewhere around 1 hour or 1.5 hours, not sure) while it is in incognito, when you return, incognito mode turns off. This happens even if you are listening to a long video or playlist (in the app) in the background the entire time (with the app closed). This is a purposeful feature; when you return it tells you that incognito mode was turned off due to inactivity.

### Patch

The patch would remove (or provide a toggleable option to remove) this feature, so that you can leave the app playing a video in the background and come back without incognito disabling. Ideally it would also prevent incognito from automatically disabling even if there's no video playing in the background.

### Motivation

Sometimes when you want to watch a long video or playlist without affecting your suggestions, you use incognito. With single videos it's not too much of an issue since you can easily remove it from your history, which prevents it from affecting your recommended videos. However, if it's a long playlist (say, a long soundtrack), you currently have to either not open the app if you leave it playing in the background for too long, or open the app, remove the current video from the history, re-enable incognito, find the playlist again, and find the video you were at, which is very inconvenient.

Additionally, if you had shuffled the playlist, it leads to having to repeat whatever videos you had listened to, since you have to reshuffle it when you get back into incognito.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
