### ISSUE TITLE
Unable to Patch Reddit

### ISSUE THREAD

**Issue by DeMoN100** [revanced/revanced-patches#1008]
### Type

Error while patching

### Bug description

pops up after patching.

### Steps to reproduce

Patch reddit app select all patches then click patch.

### Relevant log output

```shell
App not installed as package conflicts with an existing package.
```

### Screenshots or videos

![Screenshot_20221109-015313_Package installer](https://user-images.githubusercontent.com/8564572/200759878-342a4fe4-c846-47b7-bf2d-282de98236bf.jpg)

### Solution

I thought you didn't have to uninstall app to install a patched one. The patched one dissapears if you uninstall the app.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Uninstall the existing app.

**Comment by DeMoN100** [comment]
Don't close without providing a solution your app doesn't work. Also further testing other apps don't patch either. Tiktok when you try to patch it skips every patch because it thing its already applied then same thing as above screenshot.

**Comment by Ushie** [comment]
He provided a solution, P.S. this belongs in the ReVanced Manager repository, not patches

**Comment by DeMoN100** [comment]
> He provided a solution, P.S. this belongs in the ReVanced Manager repository, not patches

That comment wasn't thete before tried thag by uninstalling the app while the patcher was up saying do you want to install the app. After doing it this way the patched app just crashes on start.
