### ISSUE TITLE
Unable to Patch Any App.

### ISSUE THREAD

**Issue by DeMoN100** [revanced/revanced-patches#1009]
### Type

Error while patching

### Bug description

pops up after patching.

### Steps to reproduce

Patch rany app select all patches then click patch.

### Relevant log output

```shell
App not installed as package conflicts with an existing package.
```

### Screenshots or videos

![Screenshot_20221109-015313_Package installer](https://user-images.githubusercontent.com/8564572/200763937-67d0525b-122e-4bb8-a24f-c4161acd5691.jpg)

### Solution

Fix the problem and don't close without an answer your app has a problem & closing without response shows you don't know what to do and are just hiding the real issue.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Ushie** [comment]
Patch the app, stay in the installer screne but don't click install, uninstall reddit, come back to the app & install

**Comment by Ushie** [comment]
Or use APK from storage which is the preferred way nevertheless

**Comment by DeMoN100** [comment]
> Patch the app, stay in the installer screne but don't click install, uninstall reddit, come back to the app & install

doesn't work app just crashes as far as reddit goes. I tried with tiktok same thing only when trying to patch tiktop the app skips every patch because it says its already applied even though it does nothing

**Comment by Ushie** [comment]
> > Patch the app, stay in the installer screne but don't click install, uninstall reddit, come back to the app & install
> 
> doesn't work app just crashes as far as reddit goes. I tried with tiktok same thing only when trying to patch tiktop the app skips every patch because it says its already applied even though it does nothing

Try patching with full APK from APKMirror

**Comment by DeMoN100** [comment]
Kinda weird you need the app from apk mirror to patch. Which I tried the patches don't even come up when you select the app from storage.

**Comment by oSumAtrIX** [comment]
APKMirror is not ReVanced. It is your responsibility to source the APK and not our concern. If the APK does not work, we can‘t do anything against that.

**Comment by DeMoN100** [comment]
> APKMirror is not ReVanced. It is your responsibility to source the APK and not our concern. If the APK does not work, we can‘t do anything against that.

he was talking about the tiktop app. Also its your responsibility to keep your service working. Just like luckypatchers you should keep your custom patches up to date with the latest versions from the playstore. If you can't do that then the app is misleading and decrepid since it doesn't work with latest versions and only older ones which may force you to update anyways.

**Comment by oSumAtrIX** [comment]
> he was talking about the tiktop app

Neither is TikTok ReVanced. Idk wym.

**Comment by DeMoN100** [comment]
> > he was talking about the tiktop app
> 
> Neither is TikTok ReVanced. Idk wym.
> 
> > Also its your responsibility to keep your service working
> 
> I already said what is necessary to fix the issue. Anything beyond that is not my concern anymore and your responsibility to deal with.
> 
> The patches are up to date and working.

What he mean't was to download an apk from apkmirror hes not talking about your patches or the revanced manager.

Also the patches don't work if they did I wouldn't be creating an issue here now would I? I already shown you reddit doesn't work you can download thr playstore version yourself and try it. I also told you about tiktok patches just get skipped over thats an app issue now il show you.

https://user-images.githubusercontent.com/8564572/200888281-a3a0d6a7-b2cb-4556-ace3-fc39b19d8f9d.mp4

**Comment by oSumAtrIX** [comment]
> What he mean't was to download an apk from apkmirror hes not talking about your patches or the revanced manager.

Please see my original comment:

> APKMirror is not ReVanced. It is your responsibility to source the APK and not our concern. If the APK does not work, we can‘t do anything against that.

> Also the patches don't work if they did I wouldn't be creating an issue here now would I?

The patches do work as previously mentioned. You are patching and installing the split base apk installed on your device. You are supposed to split a full apk as you was told to.

**Comment by DeMoN100** [comment]
its not a split application what do you mean? Its full from the play store theres no additional downloads in the app.

**Comment by oSumAtrIX** [comment]
Apps from the Play Store are split apk files.
