### ISSUE TITLE
(patch):  modify action buttons

### ISSUE THREAD

**Issue by VICTOR-KENES** [revanced/revanced-patches#1012]
### Application

Please modify action buttons , hide create button , hide clip button , hide thank you button , they are all together with one key , bring these three separate functions

1 : hide create button

2 : hide clip button

3 : hide thank you button

### Issue

solution bring these commands separate not all together , bring them separate

### Patch

stock buttons

### Motivation

this way it is easier to use and will please everyone

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by OxrxL** [comment]
@oSumAtrIX what you decided about ByteBuffer implementation?

**Comment by VICTOR-KENES** [comment]
I haven't used it yet
