### ISSUE TITLE
Preferred video quality

### ISSUE THREAD

**Issue by Smart123s** [revanced/revanced-patches#102]
Add support for setting a default video quality. This was available in the original Vanced project.

![image](https://user-images.githubusercontent.com/28480228/177011713-8dd5c0be-e73a-4f83-9782-8574686c3e2b.png)

**Comment by bogadana** [comment]
wrong place and has been suggested multiple times and is in the works

**Comment by Smart123s** [comment]
Sorry, didn't realize there was a seperate repo for ideas.

Original: https://github.com/revanced/revanced-suggestions/discussions/221
https://github.com/revanced/revanced-suggestions/discussions/252
https://github.com/revanced/revanced-suggestions/discussions/259
