### ISSUE TITLE
bug: Progress bar leaves a lining in full screen

### ISSUE THREAD

**Issue by amit-katyal** [revanced/revanced-patches#1020]
### Type

Cosmetic

### Bug description

The progress bar of video in full screen leaves a black lining at the position of progress bar.

### Steps to reproduce

Step 1. Play any video
Step 2. Double tap to go forward or backward. Sometimes merely tapping to reveal player buttons also causes the issue.
Step 3. Move the progress bar around
Step 4. Observe the lining at the position of progress bar

### Relevant log output

```shell
Debugging patch excluded
```

### Screenshots or videos

https://user-images.githubusercontent.com/89385446/201340693-ecdf6213-dc84-46b1-8c4d-5e47ae616a3e.mp4

### Solution

Clearing app data or reinstallation of app.

### Additional context

I reinstalled the app yesterday and the bug went away. But today it came back again. I'm not sure what causes it in specific. I've tried to turn off sponsorblock (from settings, not excluding the patch), still the bug is there.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Do not force dark mode on the app in your phone settings.

**Comment by amit-katyal** [comment]
It's already off. Still the same issue.

https://user-images.githubusercontent.com/89385446/201353505-963702df-d722-4cb6-a602-8693e98e4db3.mp4

**Comment by oSumAtrIX** [comment]
Please record patching the app. Find the patch which causes the issue as well and report back with it.

**Comment by oSumAtrIX** [comment]
Please try [this](https://github.com/revanced/revanced-patches/issues/1020#issuecomment-1311716944) as suggested.

**Comment by amit-katyal** [comment]
Here it is.

Uploading 22-11-11-22-16-27.mp4…

**Comment by amit-katyal** [comment]
Here it is.

https://user-images.githubusercontent.com/89385446/201390688-1a8b963b-7f72-463b-b9c3-82f429279b24.mp4

**Comment by Plut0nio** [comment]
I have this issue as well, even after disabling/hiding fullscreen panels. (YT version 17.45.36, patches version 2.141.0)

**Comment by amit-katyal** [comment]
I'm not facing the issue anymore actually. So I closed it. I'm v17.45.36 patches v2.140.0

I'll reopen it. If you're still facing the issue.

**Comment by oSumAtrIX** [comment]
@FrosT2k5 Please try [this](https://github.com/revanced/revanced-patches/issues/1020#issuecomment-1311906820) as suggested.

**Comment by Plut0nio** [comment]
> @FrosT2k5 Please try [this](https://github.com/revanced/revanced-patches/issues/1020#issuecomment-1311906820) as suggested.

I also tried that when I attempted to fix this, but I still have the issue, even with fullscreen panels disabled. Should I use an older patch version?

According to xkritical#8195 on the Discord, this is apparently an issue with the stock YT app and not with ReVanced, so idk if that would even actually fix it.

**Comment by Kalpataru6** [comment]
I'm also facing this same problem.. And I can confirm the stock youtube all also have the same bug.. When I requested for a patch to hide it osu told me it is a bug of youtube and I should request youtube team

**Comment by Sculas** [comment]
Was this issue fixed or not? I'm still having this issue as well and I don't even have the option to force dark mode on YT in my phone settings.

**Comment by oSumAtrIX** [comment]
> Was this issue fixed or not? I'm still having this issue as well and I don't even have the option to force dark mode on YT in my phone settings.

I suggest trying [this](https://github.com/revanced/revanced-patches/issues/1020#issuecomment-1345544176).

**Comment by Sculas** [comment]
Then don't close the issue as **completed**?

**Comment by oSumAtrIX** [comment]
> Then don't close the issue as **completed** if the problem still exists?

What i suggested is not an implication of that it is not completed. Please make sure you [read the issue fully](https://github.com/revanced/revanced-patches/issues/1020#issuecomment-1345577472).

**Comment by FrosT2k5** [comment]
If someone still has this issue. I patched newer version of youtube with newer patches and it was fixed, I recommend to do the same.

**Comment by Kalpataru6** [comment]
I'm still on the older version but the issue just disappeared automatically.. People really did not like this so youtube removed it.
