### ISSUE TITLE
feat(patch): Prepend the filename of downloaded videos with the username of the creator

### ISSUE THREAD

**Issue by powerfulsaber** [revanced/revanced-patches#1033]
### Application

TikTok.

### Issue

Due to the download patch removing watermarks, it makes it difficult to track down who the original creator was. 

### Patch

Prepend the filename of downloaded videos with the username of the creator.

I'd suggest changing the filename format to something like "{username}_{current date & time}" as it might go over its character limit if the username is too long when alongside the default naming scheme.

### Motivation

If a user ever forgets who the creator was, they can simply look at its filename. This would allow watermarkless videos to hold a reference to the creator without their tag in the actual video

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Its closed as a duplicate.
