### ISSUE TITLE
feat(patch): bypass the Google Play purchase menu in games

### ISSUE THREAD

**Issue by TroubleDog54** [revanced/revanced-patches#1035]
### Application

The patch would be for most if not all mobile games that have a shop with items to buy with real-world money. 

### Issue

Most people don't want to spend money on cheap, ad-filled mobile games that try to squeeze every penny out of you. Some games basically require you to spend money to progress anywhere, and it would be super-nice to have the option to jump forward a bit or to speed up progression. 

### Patch

The patch wouldn't work on online games like Call of Duty Mobile or Among Us, as that would ruin the experience for other players. Instead, it would work only on single-player/offline games like Idle Miner or Egg Inc. Instead of "buying" the item, like opening the Google Play purchase menu, it would add the times straight to the game. For example, in Idle Miner, you can buy "super cash", the main currency in the shop. If you clicked on the $159.99 price to buy 25,000 super cash (which is ridiculous), instead of opening the buy menu, it would just add the super cash to your balance. 

In short, it would bypass the Google Play purchase menu and trick the game into thinking the purchase succeeded. 

### Motivation

The feeling of just getting into a game, just for it to force you to purchase something to continue progression sucks. It can lead to spending problems and is generally a bad practice. It isn't wrong to support game developers, but nowadays, many choose the path of most monetisation. Apart from supporting game devs, there is no point in making an in-app purchase or watching hundreds of ads to save up to purchase one item that speeds up the game by 0.1%. I think it would be nice to have the option available. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Matty003** [comment]
Omg🙄

**Comment by Matty003** [comment]
Not possible to mod different types of **GAMES** or apps as  types/number of checks `varies` from one app to another.

**Comment by JavierFlores09** [comment]
Have you tried using LuckyPatcher instead? It's quite literally what you are looking for. I'd find hard for revanced-patcher to do the same due to its nature to have app-specific patches
