### ISSUE TITLE
YouTube : New UI & Old UI

### ISSUE THREAD

**Issue by ankur-raikwar** [revanced/revanced-patches#1036]
### Type

Cosmetic

### Bug description

**Bug :**

YouTube switching between Old UI and New UI after quitting and starting app again.

### Steps to reproduce

1. Open YouTube
2. Play a Video and check for UI "new or old"
3. After quitting UI change to _old_ or _new_ upon starting app again.
4. Vice Verse

### Relevant log output

```shell
YouTube OldUI and New UI inconsistency
```

### Screenshots or videos

![Screenshot_2022-11-13-18-26-13-86_64ef5fc2000c1caa954c114bb372e1d5](https://user-images.githubusercontent.com/3439247/201522915-b61dff14-ade9-498e-ae6e-716bd66db699.jpg)
![Screenshot_2022-11-13-18-24-22-14_64ef5fc2000c1caa954c114bb372e1d5](https://user-images.githubusercontent.com/3439247/201522917-646af1ab-3d2b-497b-b217-263dcda703be.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Not a bug/Intended by YouTube.
