### ISSUE TITLE
revanced playback speed rests to 2x

### ISSUE THREAD

**Issue by iamashwin99** [revanced/revanced-patches#1039]
### Application

YouTube 

### Issue

The playback rests back to 2x when playing a new video if the previous video playback speed is set to something greater than 2x.

### Patch

Maybe a patch like` remember-playback-speed` could be brought up to fix this ?

### Motivation

It's annoying to change speed to say 2.5x after every video 

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [x] I filled out all of the requested information in this issue properly.

**Comment by iamashwin99** [comment]
Is this not worth Implementing?

**Comment by oSumAtrIX** [comment]
Acknowledgements not met.

**Comment by iamashwin99** [comment]
The only other issue I found that was similar to this is https://github.com/revanced/revanced-patches/issues/905 , however this is really not what I'm requesting. My issues is essentially what is described also here: https://www.reddit.com/r/revancedapp/comments/y1id8o/videos_rewind_playback_speed_above_2x_resets_back/

**Comment by oSumAtrIX** [comment]
https://github.com/revanced/revanced-patches/issues/556
