### ISSUE TITLE
Remove explore button on homescreen

### ISSUE THREAD

**Issue by 11xjas** [revanced/revanced-patches#1044]
### Application

YouTube ReVanced

### Issue

![Screenshot_20221114-124301_YouTube](https://user-images.githubusercontent.com/93155066/201598100-74680c8a-4106-429d-963a-b35b97c6178b.jpg)

### Patch

Patch to remove the shorts button on homescreen below premium bar.

![Uploading Screenshot_20221114-124301_YouTube.jpg…]()

### Motivation

Please make it as a option in revanced setting.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by johnconner122** [comment]
It explore button not shorts button.

**Comment by 11xjas** [comment]
> That's not a shorts button, it just opens a navigation menu.

Oouch. My bad
