### ISSUE TITLE
YouTube/Name(without 'Custom Branding')

### ISSUE THREAD

**Issue by arghya339** [revanced/revanced-patches#1051]
### Type

Other

### Bug description

![IMG_20221115_162734](https://user-images.githubusercontent.com/118043691/201904488-58bebadb-aabf-4207-9a63-fc0f2fb89ce4.jpg)

When you patch YouTube without 'Custom Branding' integration YouTube ReVanced name only YouTube.
![Screenshot_2022-11-15-16-26-28-534_com mi android globallauncher](https://user-images.githubusercontent.com/118043691/201904585-df4fc9d3-f96a-4c34-944d-458a34bf913a.jpg)
But, when you patch YouTube Music without 'Custom Branding' it's name YT Music ReVanced.
![Screenshot_2022-11-15-16-28-26-801_com mi android globallauncher](https://user-images.githubusercontent.com/118043691/201905035-6d10f23a-ed53-4aa8-a551-3866c7063d81.jpg)
*When you come back launcher you can see two YouTube, you don't think which is YouTube ReVanced & which is YouTube...(without 'Custom Branding')

### Steps to reproduce

Please ReName='YouTube ReVanced' when Patching YouTube without 'Custom Branding'

### Relevant log output

```shell
NA
```

### Screenshots or videos

![Uploading Screenshot_2022-11-15-16-26-28-534_com.mi.android.globallauncher.jpg…]()

### Solution

Please Fix YouTube ReVanced Patches Bug when Patching YouTube..

### Additional context

NA

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Not a bug, YT Music does not have a custom branding patch.

**Comment by arghya339** [comment]
> Not a bug, YT Music does not have a custom branding patch.

YT Music doesn't have a Custom Branding But it's name YT Music ReVanced.
When you patch YouTube & unselect Custom Branding it's name YouTube?

**Comment by arghya339** [comment]
Sir, Please Rename YouTube ReVanced (without Custom Branding). Sorry for disturbance...

**Comment by oSumAtrIX** [comment]
Dupe of #913.

**Comment by AMSAMSAMSAMS** [comment]
> > Not a bug, YT Music does not have a custom branding patch.
> 
> YT Music doesn't have a Custom Branding But it's name YT Music ReVanced. When you patch YouTube & unselect Custom Branding it's name YouTube?

It's intended for **without custom branding**.
Just disable the original YT.
