### ISSUE TITLE
feat(youtube): Improve patch descriptions

### ISSUE THREAD

**Issue by egscodes** [ReVanced/revanced-patches#1054]
### Application

Youtube

### Issue

Some of the patches add a toggle but in the description they don't mention it, they just say it removes stuff

### Patch

Description should say "Adds a toggle that ____" (or any variation depending on the context)

This is a list of some of the patches that i use that have a toggle but don't mention them, there's probably more but i don't want to repatch my current apk just to test

- Client spoof (i think)
- Disable auto caption
- Disable shorts on startup
- Disable zoom haptics
- Downloads
- Hdr auto brightness
- Hide album cards
- Hide Artist card
- Hide autoplay button
- Hide breaking news shelf
- Hide create button
- Hide crowdfunding box
- Hide short button
- Hide watch in vr
- hide watermark
- minimized playback
- old quality layout
- open links externally
- seekbar tapping
- spoof app version

### Motivation

It will make it easy to know what adds a toggle and what simply just works.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by KobeW50** [comment]
I'd like to PR for this (and https://github.com/ReVanced/revanced-patches/issues/2515)

I think a good wording would be `Adds option(s) to...`

I'm not sure if this should be added to every patch that has options. Some patches are essentially necessary and shouldn't be disabled, such as the `Client spoof` patch. And some have no downside of being enabled (and don't even need a toggle), such as the `Video ads` and `Bypass URL redirects` patches.

**Comment by oSumAtrIX** [comment]
As long as you are consistent in wording and terminology, repetition shouldn't be a problem
