### ISSUE TITLE
bug: <Revanced app - video doesn't continue where from i left it> 

### ISSUE THREAD

**Issue by saver711** [revanced/revanced-patches#1055]
### Type

Error at runtime

### Bug description

Video doesn't continue where from i left it
It starts fromthe beginning again

### Steps to reproduce

Null

### Relevant log output

```shell
Null
```

### Screenshots or videos

![IMG_20221116_134847](https://user-images.githubusercontent.com/28202010/202173240-d3acb2d6-6d86-4f8b-9b91-0f151883dd3d.jpg)
![IMG_20221116_134943](https://user-images.githubusercontent.com/28202010/202173260-909a8a11-e2c6-4107-8892-3400bebeca3e.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Happens in the unpatched app as well.

**Comment by saver711** [comment]
@oSumAtrIX 
i don't understand
what do u mean exactly by unpached app?
if u mean the original YT, no it doesn't happen

**Comment by oSumAtrIX** [comment]
https://user-images.githubusercontent.com/13122796/202182855-33fcb95e-9d4e-4a8b-80fe-84c720d6ab94.mp4

Same for the patched app.
