### ISSUE TITLE
feat(patch): MicroG Support for more Google Apps

### ISSUE THREAD

**Issue by Stale-1** [ReVanced/revanced-patches#1055]
### Application

Google Chrome
Google Keep Notes
Google Drive
Google One
Google Photos
Google Lens
Google Slide and Etc

### Issue

GSpace have ads and consumes a lot of ram.
GBox is not optimized for most Google Apps yet
MicroG Support for more Google Apps will make it easier to use Google Services on Huawei. 

### Patch

MicroG Support for Google Apps aside from Youtube and Youtube Music. 

### Motivation

When Google was removed from Huawei the cost of their phones plummeted so it becomes quite affordable for a lot of people in developing countries.
Although GSpace and Gbox exist now alot of huawei users in developing countries have low end phones which is very laggy using a virtual space.

Having a MicroG Supported Google Apps instead of a Virtual Space will make things smoother specially for students who use Google Services in a Huawei Phone.

(This happened before GSpace and Gbox were created) 
During the covid lockdown a lot of students in the PH who use Huawei Phones/Tables cannot attend online classes and they were forced to take Learning Modules and self study.
Recently, due to the heatwave and the rive of covid cases the government is considering going back to online classes.
*Huawei users can use GBox and GSpace now but it is very laggy for low end phones. 

### RE:

https://github.com/revanced/revanced-patches/issues/2144

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Meghdut-Mandal** [comment]
How do you do this in a Virtual Space?
