### ISSUE TITLE
Fake the APK version

### ISSUE THREAD

**Issue by marcussacana** [revanced/revanced-patches#1059]
### Application

YouTube and YouTube Music

### Issue

Google seems a bit mad with Vanced YouTube clients, therefore I noticed it silently ignoring my auto update settings and updating the YouTube.

### Patch

I propose a patch that fakes the YouTube client version to a custom one, that will require the patch to prompt the user the fake version, then may need changes in the manager as well.
Alternatively this can be implemented as a generic revanced manager feature instead a YouTube patch.

### Motivation

It's very troublesome reinstall the old app and repeat the patching process every time that the Google tries to update it

### Acknowledgements

- [x] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
MicroG patch renames the PKG name.

**Comment by marcussacana** [comment]
> MicroG patch renames the PKG name.

I'm trying use the root version

**Comment by oSumAtrIX** [comment]
The root variant mounts over the app, disabling updates for the app in the playstore works.

**Comment by marcussacana** [comment]
> The root variant mounts over the app, disabling updates for the app in the playstore works.

Disabling the entire play store works as I described in the issue, the play store is ignoring my auto update settings

**Comment by marcussacana** [comment]
If someone face the same issue that me, since the Revanced don't give a fuck, I solved the problem by using HideMyApplist module, and with that I hide my youtube and youtube music from the playstore, and now is everything working :)
