### ISSUE TITLE
feat(Office Docs) - `Splash Screen Duration Reduction`  and `Remove Ads` for OfficeDocs 

### ISSUE THREAD

**Issue by Vipin2003** [ReVanced/revanced-patches#106]
### Feature description

I'm here for requesting a patch for [Office Docs](https://play.google.com/store/apps/details?id=documents.excel.word.office&hl=en_US&pli=1) which will remove no-ads and also reduce the time on splash screen during opening. As it takes around 10-15 seconds on splash screen.

It is also noticed by one of our revanced contributer.
https://github.com/ReVanced/revanced-patches-template/issues/108

### Motivation

Will enhance the app usage and it will be good for those who use this app and tried off with ads in the app.

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by johnconner122** [comment]
Ok, it happens if app is trying to load ad after splash screen and if you are using adblocker(dns or any other), splash screen takes too long. Seems to be some google thing. Don't know why.🤷
