### ISSUE TITLE
Nyx Music Player

### ISSUE THREAD

**Issue by BrilliantlyEducated** [revanced/revanced-patches#1062]
### Type

Error while patching

### Bug description

broken patch

### Steps to reproduce

use ReVanced Manager and try to patch it

### Relevant log output

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Executing all patches
Executing 'unlock-pro' of type: bytecode
unlock-pro failed.
Error:
kotlin.Unit
unlock-pro failed.
Error:
kotlin.Unit
Repacking patched apk
Not compiling resources because resource patching is not required
Creating new dex file
Writing modified dex files
Finished!
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Please include versions of ReVanced Manager and the app you patch.

**Comment by BrilliantlyEducated** [comment]
ReVanced Manager version 0.0.40
Nyx Music Player version 2.2.5

**Comment by oSumAtrIX** [comment]
Please share the logs of the ReVanced Manager.

**Comment by BrilliantlyEducated** [comment]
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Executing all patches
Executing 'unlock-pro' of type: bytecode
unlock-pro failed.
Error:
kotlin.Unit
unlock-pro failed.
Error:
kotlin.Unit
Repacking patched apk
Not compiling resources because resource patching is not required
Creating new dex file
Writing modified dex files
Finished!

**Comment by oSumAtrIX** [comment]
There is logs in the settings you can share. Please do so.

**Comment by BrilliantlyEducated** [comment]
[logs_from_revanced_manager.log](https://github.com/revanced/revanced-patches/files/10036162/logs_from_revanced_manager.log)

**Comment by oSumAtrIX** [comment]
These are the logs from the patcher screen, please send the requested logs.

**Comment by BrilliantlyEducated** [comment]
[logs_from_revanced_manager.log](https://github.com/revanced/revanced-patches/files/10036269/logs_from_revanced_manager.log)

**Comment by ThaRealJozef** [comment]
Same issue here

**Comment by kazimmt** [comment]
[revanced-manager_logcat_20221126214943699028.log](https://github.com/revanced/revanced-patches/files/10096564/revanced-manager_logcat_20221126214943699028.log)


@oSumAtrIX

**Comment by FineFindus** [comment]
The manager had a new release, which should fix this bug. Please check if the bug still persists and close the issue if it's fixed.

**Comment by kazimmt** [comment]
> The manager had a new release, which should fix this bug. Please check if the bug still persists and close the issue if it's fixed.

Seems working
