### ISSUE TITLE
ReVanced site

### ISSUE THREAD

**Issue by Nizami20052022** [revanced/revanced-patches#1064]
### Application

ReVanced

### Issue

https://revanced.io/
Is this site official?

### Patch

.

### Motivation

.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Canny1913** [comment]
No.
