### ISSUE TITLE
feat(patch): Youtube "Download" buttons ability to trigger custom downloader

### ISSUE THREAD

**Issue by tmcappsph** [revanced/revanced-patches#1071]
### Application

Youtube

### Issue

Download buttons across the app cannot trigger the same functionality (usage of custom downloader).

![Screenshot_2022-11-19-05-26-18-42_64ef5fc2000c1caa954c114bb372e1d5](https://user-images.githubusercontent.com/89440514/202832721-af23ee24-c60d-4a21-8cf5-2386838f49db.jpg)
![Screenshot_2022-11-19-05-26-36-63_64ef5fc2000c1caa954c114bb372e1d5](https://user-images.githubusercontent.com/89440514/202832723-d0d9718a-26bf-4667-9256-08bf86c65147.jpg)

### Patch

Add a setting and ability to overwrite the default "Download" buttons across the app to trigger the custom downloader instead of the default behavior.

### Motivation

- Download buttons across the app will/can do the same thing.
- Users with no premium account will want to use a custom downloader for all their downloads (e.g. NewPipe)
- Make it easier to download in videos list with a custom downloader (instead of using share and selecting the downloader)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by SodaWithoutSparkles** [comment]
#757
