### ISSUE TITLE
bug: save to playlist overlay 

### ISSUE THREAD

**Issue by rsaurav12** [revanced/revanced-patches#1073]
### Type

Other

### Bug description

![IMG_20221119_171125](https://user-images.githubusercontent.com/53332518/202849365-bbc1dd6c-7342-4c96-8746-83d9929247c3.jpg)
Save to playlist overlay is missed placed.

### Steps to reproduce

-

### Relevant log output

```shell
-
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Disable all patches until the error is gone, respond back which one caused it.
