### ISSUE TITLE
Limit Distraction

### ISSUE THREAD

**Issue by missyraja** [revanced/revanced-patches#1078]
### Application

YouTube 

### Issue

Right now when you are viewing a video on YouTube there is an option to hide comments which reduces the distraction. It would be nice to also remove video suggestions below the player to limit distractions.

### Patch

Right now when you are viewing a video on YouTube there is an option to hide comments which reduces the distraction. It would be nice to also remove video suggestions below the player to limit distractions.

### Motivation

Helps in reducing unwanted interaction and reduces destruction from the video you are currently watching 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
You can do this with the new custom filter in the general ads settings page. As an example you can put "thumbnail.eml"  there. Kepp in mind, if you put something too simple there you can break the app and will have to reset its data. To find how to block stuff you can enable debugging in the Miscellaneous settings and search grep for "LithoFilter" in logcat.
