### ISSUE TITLE
Further ad patches cleanup

### ISSUE THREAD

**Issue by OxrxL** [revanced/revanced-patches#108]
Reel reference can be removed from this patch: https://github.com/revanced/revanced-patches/blob/main/src/main/kotlin/app/revanced/patches/youtube/ad/general/bytecode/patch/GeneralBytecodeAdsPatch.kt

because has been moved to litho.

**Comment by OxrxL** [comment]
@oSumAtrIX

**Comment by TheJeterLP** [comment]
> @oSumAtrIX 

No need to ping Team members, we will see it :)

**Comment by OxrxL** [comment]
> > @oSumAtrIX
> 
> No need to ping Team members, we will see it :)

Sorry. I did this as a result of a private conversation (related to the the issue) with the aformentioned team member.

**Comment by OxrxL** [comment]
https://github.com/revanced/revanced-patches/pull/641

**Comment by OxrxL** [comment]
Closed because the patch is still useful (the component is still visible, and can be hidden).
