### ISSUE TITLE
bug: YouTube Revanced App is crashing while switching Accounts

### ISSUE THREAD

**Issue by udoxi** [revanced/revanced-patches#1081]
### Type

Error at runtime

### Bug description

YouTube Revanced App is crashing while switching accounts and also crashing at first start-up.

YouTube Revanced `17.43.36`

Patch version `v2.115.0`

Patching logs attached
[revanced-manager_patcher_20221121080749045954.log](https://github.com/revanced/revanced-patches/files/10053295/revanced-manager_patcher_20221121080749045954.log)

### Steps to reproduce

While switching accounts 

### Relevant log output

[error.txt](https://github.com/revanced/revanced-patches/files/10064726/error.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/115417493/202963068-b64d283e-1681-4d58-ae34-5e6e5514f165.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Please use logcat to include logs from the crash. Use `grep AndroidRuntime` for that.

**Comment by oSumAtrIX** [comment]
You can capture logs on device.

**Comment by pungorandras** [comment]
--------- beginning of crash
11-21 22:32:11.954 30355 30355 E AndroidRuntime: FATAL EXCEPTION: main
11-21 22:32:11.954 30355 30355 E AndroidRuntime: Process: app.revanced.android.youtube, PID: 30355
11-21 22:32:11.954 30355 30355 E AndroidRuntime: java.lang.VerifyError: Verifier rejected class aaao: void aaao.h(aaag, aaaf, java.util.List, long, long, boolean) failed to verify: void aaao.h(aaag, aaaf, java.util.List, long, long, boolean): [0xAF] invalid use of move-result* (declaration of 'aaao' appears in base.apk)
11-21 22:32:11.954 30355 30355 E AndroidRuntime: 	at aaam.c(PG:5)
11-21 22:32:11.954 30355 30355 E AndroidRuntime: 	at ese.run(PG:160)
11-21 22:32:11.954 30355 30355 E AndroidRuntime: 	at tma.run(PG:7)
11-21 22:32:11.954 30355 30355 E AndroidRuntime: 	at ocy.run(PG:5)
11-21 22:32:11.954 30355 30355 E AndroidRuntime: 	at odc.run(PG:23)
11-21 22:32:11.954 30355 30355 E AndroidRuntime: 	at nlt.run(PG:6)
11-21 22:32:11.954 30355 30355 E AndroidRuntime: 	at nlt.run(PG:33)
11-21 22:32:11.954 30355 30355 E AndroidRuntime: 	at com.google.android.apps.youtube.embeddedplayer.service.jar.client.s.run(PG:15)
11-21 22:32:11.954 30355 30355 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
11-21 22:32:11.954 30355 30393 I android.youtub: Rejecting re-init on previously-failed class java.lang.Class<aaao>: java.lang.VerifyError: Verifier rejected class aaao: void aaao.h(aaag, aaaf, java.util.List, long, long, boolean) failed to verify: void aaao.h(aaag, aaaf, java.util.List, long, long, boolean): [0xAF] invalid use of move-result* (declaration of 'aaao' appears in base.apk)
11-21 22:32:11.954 30355 30393 I android.youtub: (Throwable with no stack trace)
11-21 22:32:11.954  4158 28663 D GmsAuthProvider: Call from app.revanced.android.youtube
11-21 22:32:11.955  4386  4604 E OOMEventManager: oom event not support this pkg, dismiss this!
11-21 22:32:11.955 30355 30393 E ErrorLoggingExecutor: Uncaught exception from runnable
11-21 22:32:11.955 30355 30393 E ErrorLoggingExecutor: java.lang.VerifyError: Verifier rejected class aaao: void aaao.h(aaag, aaaf, java.util.List, long, long, boolean) failed to verify: void aaao.h(aaag, aaaf, java.util.List, long, long, boolean): [0xAF] invalid use of move-result* (declaration of 'aaao' appears in base.apk)
11-21 22:32:11.955 30355 30393 E ErrorLoggingExecutor: 	at aaam.c(PG:5)
11-21 22:32:11.955 30355 30393 E ErrorLoggingExecutor: 	at ese.run(PG:160)
11-21 22:32:11.955 30355 30393 E ErrorLoggingExecutor: 	at tma.run(PG:7)
11-21 22:32:11.955 30355 30393 E ErrorLoggingExecutor: 	at ocy.run(PG:5)
11-21 22:32:11.955 30355 30393 E ErrorLoggingExecutor: 	at odc.run(PG:23)
11-21 22:32:11.955 30355 30393 E ErrorLoggingExecutor: 	at nlt.run(PG:6)
11-21 22:32:11.955 30355 30393 E ErrorLoggingExecutor: 	at nlt.run(PG:33)
11-21 22:32:11.955 30355 30393 E ErrorLoggingExecutor: 	at com.google.android.apps.youtube.embeddedplayer.service.jar.client.s.run(PG:15)
11-21 22:32:11.955 30355 30393 E ErrorLoggingExecutor: 	at java.lang.Thread.run(Thread.java:1012)
11-21 22:32:11.955 30355 30393 E ErrorLoggingExecutor: Uncaught exception from runnable
11-21 22:32:11.955 30355 30393 E ErrorLoggingExecutor: java.lang.VerifyError: Verifier rejected class aaao: void aaao.h(aaag, aaaf, java.util.List, long, long, boolean) failed to verify: void aaao.h(aaag, aaaf, java.util.List, long, long, boolean): [0xAF] invalid use of move-result* (declaration of 'aaao' appears in base.apk)
11-21 22:32:11.955 30355 30393 E ErrorLoggingExecutor: 	at aaam.c(PG:5)
11-21 22:32:11.955 30355 30393 E ErrorLoggingExecutor: 	at ese.run(PG:160)
11-21 22:32:11.955 30355 30393 E ErrorLoggingExecutor: 	at tma.run(PG:7)
11-21 22:32:11.955 30355 30393 E ErrorLoggingExecutor: 	at ocy.run(PG:5)
11-21 22:32:11.955 30355 30393 E ErrorLoggingExecutor: 	at odc.run(PG:23)
11-21 22:32:11.955 30355 30393 E ErrorLoggingExecutor: 	at nlt.run(PG:6)
11-21 22:32:11.955 30355 30393 E ErrorLoggingExecutor: 	at nlt.run(PG:33)
11-21 22:32:11.955 30355 30393 E ErrorLoggingExecutor: 	at com.google.android.apps.youtube.embeddedplayer.service.jar.client.s.run(PG:15)
11-21 22:32:11.955 30355 30393 E ErrorLoggingExecutor: 	at java.lang.Thread.run(Thread.java:1012)

**Comment by pungorandras** [comment]
[error.txt](https://github.com/revanced/revanced-patches/files/10060799/error.txt)

**Comment by oSumAtrIX** [comment]
Should be fixed with a436663e7755fc714c735df626d39bbd94f83dbb. I am not sure though why.

**Comment by rohan2000github** [comment]
> Should be fixed with [a436663](https://github.com/revanced/revanced-patches/commit/a436663e7755fc714c735df626d39bbd94f83dbb). I am not sure though why.

Not fixed

**Comment by oSumAtrIX** [comment]
https://user-images.githubusercontent.com/13122796/203473063-868abed2-3bdb-45d1-a47b-394cd8a9cd13.mp4

**Comment by rohan2000github** [comment]
> Record_2022-11-23-06-11-06.mp4
I have posted a video on issue created by the same person. You can see there.
