### ISSUE TITLE
Remove Next/Previous button in player

### ISSUE THREAD

**Issue by 11xjas** [revanced/revanced-patches#1083]
### Application

YouTube

### Issue

(With reference to one of the reddit posts)

In my personal opinion, I have never used this next/previous button feature. Tbh i found this annoying. Most of the time I press that button by mistake. So, it'd be cool if we able to disable that.

### Patch

Patch to remove Next/previous video in video player.

### Motivation

![Screenshot_20221121-211935_Instagram](https://user-images.githubusercontent.com/93155066/203100291-a34915c0-676e-4217-a3ae-d369c22a3685.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by ILoveOpenSourceAppications** [comment]
This has been implemented. Can be closed now.
