### ISSUE TITLE
feat(patch): Remove Flightradar24 ads

### ISSUE THREAD

**Issue by sebm253** [ReVanced/revanced-patches#1086]
### Application

Flightradar24

### Issue

The Flightradar24 app is filled with ads everywhere.

### Patch

The patch should remove ads everywhere - top of the screen, flight information, airport arrivals/departures, popup ads.

### Motivation

As I mentioned above, the app has ads almost everywhere. Every couple of minutes, you also get a 5-second-timeout popup ad. Please take a look at the screenshots below to see just where the ads are (probably not all of the places):

<details>
<summary>At the top of the screen</summary>

![image](https://user-images.githubusercontent.com/42180891/234934624-0f93e1e1-209e-416b-8d3a-bfc1dc787aed.png)
</details>
<details>
<summary>In flight information - 1/2</summary>

![image](https://user-images.githubusercontent.com/42180891/234934751-7c5cc02a-e708-4c25-b471-d17f7b041f65.png)
</details>
<details>
<summary>In flight information - 2/2</summary>

![image](https://user-images.githubusercontent.com/42180891/234934809-07ef3ea3-e09f-4317-8fed-9cf3396952a5.png)
</details>

<details>
<summary>In airport info</summary>

![image](https://user-images.githubusercontent.com/42180891/234935005-67e78858-ccfb-4f7e-a166-c25d0751631a.png)
</details>

<details>
<summary>In airport info - arrivals</summary>

![image](https://user-images.githubusercontent.com/42180891/234935135-93c4037d-f0df-44b6-bf39-b1b27a5ee723.png)
</details>

<details>
<summary>In airport info - departures</summary>

![image](https://user-images.githubusercontent.com/42180891/234935219-a5f20527-e35a-4f6e-b1d8-b4c677cba19f.png)
</details>

<details>
<summary>In airport info - on ground</summary>

![image](https://user-images.githubusercontent.com/42180891/234935286-61df4686-837e-4440-ac03-879d6c2c1d47.png)
</details>

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
