### ISSUE TITLE
feat(patch): Unlock PRO - Repainter

### ISSUE THREAD

**Issue by diegonogaretti** [ReVanced/revanced-patches#1086]
### Application

Repainter

### Issue

We have a patch which unlocks pro features of IconPack Studio. Please make one for Repainter too

### Patch

Unlock PRO features of Repainter

### Motivation

Repainter is the ultimate customization app for Material You

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by SrujanGajul** [comment]
Could you please provide the link to the app?

**Comment by Hx2-code** [comment]
https://play.google.com/store/apps/details?id=dev.kdrag0n.dyntheme

**Comment by diegonogaretti** [comment]
Here it is

**Comment by SrujanGajul** [comment]
Sorry for the late reply, I somehow missed to look at the reply. I have looked at the app but I got to know that it only works on Android 12 and up. I don't have any device with Android 12 running. Will try to run and test in AVD's.

**Comment by diegonogaretti** [comment]
> Sorry for the late reply, I somehow missed to look at the reply. I have looked at the app but I got to know that it only works on Android 12 and up. I don't have any device with Android 12 running. Will try to run and test in AVD's.

I can do tests for you if you need. Just let me know how and what to test!

**Comment by diegonogaretti** [comment]
> Sorry for the late reply, I somehow missed to look at the reply. I have looked at the app but I got to know that it only works on Android 12 and up. I don't have any device with Android 12 running. Will try to run and test in AVD's.

Hi there
For some reasons this issue doesn't appear when searched between open ones but it's still there. Let me know if you need tests!

**Comment by oSumAtrIX** [comment]
Closing according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#%EF%B8%8F-guidelines-for-requesting-or-contributing-patches). Thanks anyways.
