### ISSUE TITLE
Client spoof 0.0.1 causes skipping videos in playlists

### ISSUE THREAD

**Issue by Windows200000** [revanced/revanced-patches#1093]
### Type

Error at runtime

### Bug description

When "Fix video playback issues" is enabled and a playlist is played, the app sometimes skips through multiple videos after either clicking a video in said playlist or after autoplay plays the next video.

### Steps to reproduce

1. Apply Client spoof to YouTube
2. Enable "Fix video playback issues" in settings
3. Play a video in a playlist

### Relevant log output

```shell
The YouTube app does not have an accessible log to my knowledge.
```

### Solution

Disable "Fix video playback issues"

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [x] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Client spoof does not affect this. It is a known side-effect of the playback fix.
