### ISSUE TITLE
feat(patch): Add mods for spotify TV

### ISSUE THREAD

**Issue by A-74** [ReVanced/revanced-patches#1102]
### Application

Spotify TV 

### Issue

Although you can use spotify normal app on TV it's alot cumbersome and take lot of space and keeps a cache history which will eventually fill up storage and need to clear them manually from android/data/com.spotify.music folder.
SO PLEASE HELP!

### Patch

   1.No ads(visual and video)
   2.Premium features(if you can...like unlimited skips,remove force shuffle and unlock spotify connect)
   3.hide premium navbar(already have in spotify android app can't you integrate it to the TV app)
4.disable capture restriction (same as before!)

### Motivation

To have less cumbersome TV suitable spotify TV mod with no ads!

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Please split this issue into seperate ones. Closing according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#%EF%B8%8F-guidelines-for-requesting-or-contributing-patches). Thanks anyways.
