### ISSUE TITLE
Improve patcher error message when integration.apk is missing

### ISSUE THREAD

**Issue by LisousEinaiKyrios** [revanced/revanced-patches#1106]
### Type

Cosmetic

### Bug description

if you try to patch and forget to include an integration apk, it gives an error message of:
`Integrations have not been merged yet. This patch can not succeed without merging the integrations.`

The language here is a bit confusing, since "can not succeed without merging the integrations" sounds like the user needs to make a Git merge or do some other unknown action.

Instead the error should describe how to fix the problem.  Maybe something like :
`patch requires merging with an integration apk, but no integration files were found.  Must use patcher with -m flag`

### Steps to reproduce

Use patcher for any patch requiring integrations, but forget to include -m flag.

### Relevant log output

```shell
SEVERE: settings failed: app.revanced.patcher.patch.PatchResultError: 'settings' depends on 'integrations' but the following error was raised: Integrations have not been merged yet. This patch can not succeed without merging the integrations.
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
You want the error message to mention to -m flag, but the patches have nothing to do with the CLI. It says "merge", because that is what should happen before patching. The error message can mention "Integrations class not found" but this is just nitpicking at this point. If you care, open a PR regarding this.
