### ISSUE TITLE
YouTube crash - GeneralAdsPatch  - No static method hideReelView

### ISSUE THREAD

**Issue by LisousEinaiKyrios** [revanced/revanced-patches#1107]
### Type

Error at runtime

### Bug description

Seeing an occasional crash in YouTube ReVanced.  Error log says:

`NoSuchMethodError: No static method hideReelView(Landroid/view/View;)V in class Lapp/revanced/integrations/patches/GeneralAdsPatch`

### Steps to reproduce

Patched using default settings
YouTube: 17.45.36
ReVanced patches: v2.121.0

### Relevant log output

```shell
AndroidRuntime: java.lang.NoSuchMethodError: No static method hideReelView(Landroid/view/View;)V in class Lapp/revanced/integrations/patches/GeneralAdsPatch; or its super classes (declaration of 'app.revanced.integrations.patches.GeneralAdsPatch' appears in /data/app/~~D_9erMWP3Ej9jvyXUSDM5Q==/app.revanced.android.youtube-1G2sGlSHgu2a6tJX1JAfsA==/base.apk!classes5.dex)
AndroidRuntime: 	at kqr.<init>(PG:3)
AndroidRuntime: 	at knu.t(PG:1)
AndroidRuntime: 	at erd.d(PG:66)
AndroidRuntime: 	at erd.a(PG:46)
AndroidRuntime: 	at acku.e(PG:5)
AndroidRuntime: 	at acmm.x(PG:3)
AndroidRuntime: 	at eec.g(PG:3)
AndroidRuntime: 	at nr.mP(PG:1)
AndroidRuntime: 	at od.p(PG:79)
AndroidRuntime: 	at mo.b(PG:6)
AndroidRuntime: 	at mo.run(PG:33)
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Update the integrations.
