### ISSUE TITLE
feat(patch): Unlock Premium features in org.totschnig.myexpenses

### ISSUE THREAD

**Issue by UA-Archiver** [revanced/revanced-patches#1113]
### Application

Package Name - org.totschnig.myexpenses
Google Play Link - https://play.google.com/store/apps/details?id=org.totschnig.myexpenses
GitHub Repo - https://github.com/mtotschnig/MyExpenses

### Issue

Unlock Premium Features
Remove Ads (on Google Play Variant,, there are none on the FDroid Version)

### Patch

The Unlock Premium Features, patch can bypass the requirement by either 

- breaking the free uses (of Premium Features) counter in the app 
- removing the Premium Subscription checker

### Motivation

Many useful features of the application are locked behind a subscription paywall (for all features) or a one-time purchase (per feature)
The features include ->

- No Ads
- Charts
- Splitting Transactions
- Removal of account limit
- Importing CSV
- Syncing to cloud for backups
 and so on

Editing of the code via patches should be easier as the application is open source on GitHub

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by FineFindus** [comment]
Why not create a fork to remove it? Would be easier than creating a patch.

**Comment by oSumAtrIX** [comment]
Probably the publicly distributed app contains an api key at build time.
