### ISSUE TITLE
bug: On Andoroid 11 or Above Back Gesture on YouTube ReVanced is not working as expected.

### ISSUE THREAD

**Issue by AdishSagarawat** [revanced/revanced-patches#1123]
### Type

Other

### Bug description

Back Gesture is not working as expected while shift from fullscreen player to a mini player or while watching a video in quick playback (idk whats its called)

Please see the attached screenrecordings.

### Steps to reproduce

Case 1;
Open Youtube Revanced
Play any video 
Use Back Gesture to switch to mini Player
Try Using Back Gesture again

Case 2
Open YouTube ReVanced
Wait for quick playback
Try Using Back Gesture 

### Relevant log output

```shell
.
```

### Screenshots or videos

https://user-images.githubusercontent.com/69076256/204100181-9424e0ad-336a-4393-967f-781fe93649f8.mp4

https://user-images.githubusercontent.com/69076256/204100222-e61019d0-b621-4ed3-80f5-aa01de63536b.mp4

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by AdishSagarawat** [comment]
@oSumAtrIX This issue is still not solved.
Why closed it?

**Comment by reisxd** [comment]
> @oSumAtrIX This issue is still not solved.
> Why closed it?

Duplicate.
