### ISSUE TITLE
bug: Automatic Playback Not Working in Google Feed Card (aka discover) and Play Store

### ISSUE THREAD

**Issue by AdishSagarawat** [revanced/revanced-patches#1126]
### Type

Other

### Bug description

While scrolling in the Feed automatic playback doesn't work and YouTube ReVanced Crashes (Am using ReVanced Root)
It tries to play the video but RV Crashes.

Also,
While Playing a video in Play Store YT RV Crashes and automatic playback is not working there too.

Please see the attached videos"

### Steps to reproduce

Case 1:
Swipe Left on Home Screen and Scroll
YouTUbe will crash while trying to autoplay and it will also fail when you click on the video.

Case 2
Search Chess on Playstore
Open the top most listed application
While using original YT the video will automatically play after few seconds
But in RV its not playing 
Now,
Click on the video 
YT RV Crashes 

### Relevant log output

```shell
.
```

### Screenshots or videos

https://user-images.githubusercontent.com/69076256/204100663-62f3e1f5-0c85-4363-91de-c7c4ff8b3b1d.mp4

https://user-images.githubusercontent.com/69076256/204100887-ed58c08e-61a3-4dfa-b029-ef6271c071c4.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by SodaWithoutSparkles** [comment]
It seems that those apps are hard-coded to call com.google.youtube so unless you root and install revanced as that package, or patch those apps as well, it would not be possible

Its just my guess tho

**Comment by YouSummoner** [comment]
Nopee, that's an error in the rooted version too, annoying...

**Comment by oSumAtrIX** [comment]
@YouSummoner please record the following:

1. Uninstall the ReVanced Manager
2. Uninstall the patched YouTube app
3. Install the latest ReVanced Manager
4. Patch & install YouTube with root
5. Show issue

Additionally attach error logs via logcat.

**Comment by YouSummoner** [comment]
It's started working in rooted version now.
