### ISSUE TITLE
feat(patch): RAM Cleanup

### ISSUE THREAD

**Issue by KazKaz90** [revanced/revanced-patches#1128]
### Application

RAM Cleanup (com.kosajun.easymemorycleaner)
https://play.google.com/store/apps/details?id=com.kosajun.easymemorycleaner

### Issue

The app have Premium and Ads

### Patch

Unlock Premium and Remove the Ads

### Motivation

It's a great app for cleaning the RAM, and it works unlike other "RAM Cleaning" apps on the PlayStore

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Android handles RAM quite well, you are not supposed to touch it at all.

**Comment by SodaWithoutSparkles** [comment]
If you were to touch it, use your OS pre-installed software

**Comment by KazKaz90** [comment]
Ok then sorry
