### ISSUE TITLE
[Feature Request] Add SponsorBlock integration

### ISSUE THREAD

**Issue by Nolij** [revanced/revanced-patches#113]
Many of us used Vanced for SponsorBlock. It'd be nice to get that back as part of ReVanced.

**Comment by bogadana** [comment]
wrong place and it's being worked on

**Comment by Nolij** [comment]
> wrong place and it's being worked on

Apologies. For future reference, what would have been the right place had this not already been in the works?

**Comment by bogadana** [comment]
org discussions page https://github.com/orgs/revanced/discussions
