### ISSUE TITLE
feat(patch):  TickTick premium 

### ISSUE THREAD

**Issue by 0bscureJ** [ReVanced/revanced-patches#1132]
### Application

Tick Tick

### Issue

Unlock premium features

### Patch

Unlocking all premium features in the TickTick app like using their built in calendar feature,  setting a duration of tasks, etc. 

### Motivation

It's a very useful feature for the app. 

### Acknowledgements

- [x] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by ILoveOpenSourceApplications** [comment]
#1028 isn't the unlock-premium patch but just an unlock-themes patch which bypasses the premium account requirement right. So can't this also be looked into and done by somebody who unlocks premium functionalities. Like @nik2143 if you can?

**Comment by Ansh4011** [comment]
@0bscureJ @ILoveOpenSourceApplications Not relevant to Revanced in particular but here's something you both might want to check out- https://github.com/Ansh4011/Ticktick-Windows-Cracked
Don't hesitate to star it 😄.

**Comment by Ansh4011** [comment]
Also, I would love to have premium features of Ticktick on android as well, especially when it's by Revanced.

**Comment by oSumAtrIX** [comment]
Closing according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#%EF%B8%8F-guidelines-for-requesting-or-contributing-patches). Thanks anyways.

**Comment by Gr-Nobel** [comment]
@ILoveOpenSourceApplications do you have the the on your pc

**Comment by ILoveOpenSourceApplications** [comment]
> @ILoveOpenSourceApplications do you have the the on your pc

I don't quite understand what you're talking about.
