### ISSUE TITLE
feat(patch): long press back to exit app

### ISSUE THREAD

**Issue by ANi1XO** [revanced/revanced-patches#1134]
### Application

A long press back triggers app exit or add a button (perhaps replacing the cast button since it's useless to exit app).

### Issue

Press back to exit not working will be solved

### Patch

Currently facing issue in which general ads make it impossible to exit app by pressing back so either make it soo a long press back triggers app exit or add a button (perhaps replacing the cast button since it's useless) to exit the app.

### Motivation

YouTube is trying to make this app problematic, the lack of this small feature makes it so that my new users feel uneasy because they have formed an habit to just pressing back to exit the app. I wish the experience was homogeneous between the original and modded app.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by ANi1XO** [comment]
I don't know if this feature is implement-able, but it would be nice to have a work around for the issue I mentioned.

**Comment by oSumAtrIX** [comment]
A similar & faster usable feature already exists which is called home button.
