### ISSUE TITLE
feat(YouTube): Block crowdfunding tag in video subtitle

### ISSUE THREAD

**Issue by Domiiniik** [ReVanced/revanced-patches#1141]
### Application

Youtube

### Issue

Additionally disable distracting green crowdfunding tag from showing in videos in addition to box in "Remove Crowdfunding box" Patch.

### Patch

Patch should remove this tag from the videos:
![Screenshot_20230417_194918_YouTube](https://user-images.githubusercontent.com/30195961/232573271-2d97271f-1a77-4f62-8935-6406a50750af.jpg)
![Screenshot_20230417_194900_YouTube](https://user-images.githubusercontent.com/30195961/232568517-ce84d041-ae2c-489f-a3a6-246e1cbfcdba.jpg)

### Motivation

Prevents user from distraction by removing described element visibility in feed as well as in Video Player.
+ User most likely doesn't care&doesn't want to see crowdfunding tag if he opted in to disable crowdfunding box anyway and taking into consideration that there are no other green UI elements in the video player it makes the tag distracting as mentioned above.

+Dealing with this would probably be not a lot of work when it comes to patch development anyways, but I'd be a nice addition to complete for the overall removal of "crowdfunding" related elements in the UI to give even cleaner UI experience that reVanced already provides anyways. :)

Offtopic: On provided screenshot reference you can also see "Hide action buttons Patch glitching out as reported in an issue by other user, its a pretty common issue since the beginning of this Patch existence and would be nice to finally give this Patch some love, have this fixed as well as have "Hide create,clip and thanks buttons" split to match the rest. It's the little ironing out things that matters now that the patches selection is rich.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Perry-God** [comment]
Are there any updates regarding adding the queue feature?

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!

**Comment by anonymousik** [comment]
https://www.reddit.com/r/revancedapp/comments/1grfg6e/revanced_queue_patch_by_nieznany_nikomu/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

**Comment by oSumAtrIX** [comment]
This looks like autogenerated code. It does not remotely work, thanks regardless
