### ISSUE TITLE
feat(patch): Force enable auto captions

### ISSUE THREAD

**Issue by Rysanlos** [ReVanced/revanced-patches#1143]
### Application

Youtube Revanced

### Issue

When browsing Youtube feed or youtube latest subbed videos, the auto captions are not showing, I must to click on the CC button for each video I'm watching (on the feed the button in top right of the video, next to the mute button, but on the latest subbed videos feed, it's not there, you must open the video). For normal captions it's working as it should.

(Disable auto captions setting is unchecked and captions is enabled on my phone settings).
![Screenshot_20230417-010208](https://user-images.githubusercontent.com/22010386/232466614-575706a2-f065-4842-a632-11ffe3d35d0b.png)

### Patch

The patch will be the opposite of disable auto captions patch:
For each videos that have auto captions available, it should be enabled by default so we don't have to click on CC every time we are watching a video on the feeds and when we open the video.

### Motivation

The normal captions are already force enabled by default, why not do the same for auto captions?
Force disable auto captions is a thing, force enable should be too.
Also accessibility is very important for me, I'm a deaf people and I watch videos a lot without sound.
On vanced it was working this way, I switched to revanced recently and I'm feeling like I'm losing an important feature.

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by erikk333** [comment]
Why is this closed
