### ISSUE TITLE
feat(patch): 'Copy Link with Time Stamp' button

### ISSUE THREAD

**Issue by bizzar721** [revanced/revanced-patches#1143]
### Application

YouTube

### Issue

This will streamline the process of creating a link with a timestamp to a specific point in a video. Right now, you must either convert the desired time to seconds and manually ammend the link, or open the video in a browser, viewed as desktop, to have the option to copy with timestamp.

### Patch

Vanced had an option to have an overlay button that would "copy with timestamp" at that specific point of the video.

### Motivation

It is a 'quality of life' patch that would tremendously streamline the way a timestamped link is shared.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
#531
