### ISSUE TITLE
Proximity bug

### ISSUE THREAD

**Issue by skiely** [revanced/revanced-patches#1144]
### Type

Other

### Bug description

v17.45.36 has a proximity bug.

### Steps to reproduce

Turn your phone from portrait to landscape & the screen will not turn most of the time. 

### Relevant log output

```shell
Blah
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [ ] I have written a short but informative title.
- [ ] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Not reproducible. Include proper reproduction steps and a video.

**Comment by skiely** [comment]
Ok keep using a faulty apk 👍🏻

**Comment by Enzycal** [comment]
Just updated from the previous supported version of YouTube to the latest one and can confirm that it won't go to landscape / fullscreen when rotating the phone. It does work occasionally.
