### ISSUE TITLE
bug: Spotify instantly crashing on opening

### ISSUE THREAD

**Issue by thaynos** [revanced/revanced-patches#1148]
### Type

Error at runtime

### Bug description

literally the title

### Steps to reproduce

patch with all settings with latest spotify from play store
open app
it crashes

### Relevant log output

```shell
idk how to find vlogs for this app
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [ ] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Reproduction steps are not enough.

**Comment by thaynos** [comment]
> Reproduction steps are not enough.

ive updated it now although its pretty straight forward

**Comment by oSumAtrIX** [comment]
You are using a split apk file and were warned in doing so in the ReVanced Manager application. You need a full apk until split support is finished.

**Comment by thaynos** [comment]
How to find the full apk? I can't find it online or on apkmirror
