### ISSUE TITLE
Playback in feed breaks in youtube

### ISSUE THREAD

**Issue by clawyf** [revanced/revanced-patches#1153]
### Type

Other

### Bug description

After using the app, the feature to have videos play while you scroll home/subscriptions just quits working and they become thumbnails again

I tried force closing the app and clearing cache, I even tried disabling and enabling the setting, but for some reason what fixed it was setting it to wifi only and then back to enabled

### Steps to reproduce

Have the setting enabled in youtube's general settings and just wait for it to stop working properly

### Relevant log output

```shell
I don't have any logs for this
```

### Screenshots or videos

![Screenshot_20221129-095053~2](https://user-images.githubusercontent.com/30278765/204593515-e071fc2b-9e39-4e6e-980a-cfa489ca08ed.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Please attach logs via logcat. Grep AndroidRuntime. Reproductions steps do not work.

**Comment by clawyf** [comment]
> Please attach logs via logcat. Grep AndroidRuntime. Reproductions steps do not work.

I really don't have the ability to do that right now, but it's heavily related to playing videos

I can always get the feature to break if I tap on one of the videos and start watching then go back to the home screen and scroll again. When I do all the same things on the unmodded youtube app it works fine

**Comment by emyaqin** [comment]
Does it rooted or non-rooted version of ReVanced? Cause I don't have any problem with the rooted one

**Comment by clawyf** [comment]
> Is it rooted or non-rooted version of ReVanced? Cause I don't have any problem with the rooted one

Non root

**Comment by clawyf** [comment]
Mentioned elsewhere, but audio breaks often in feed even when the videos do attempt to play. Even after updating to latest, this is the first video in feed and the only one that works with the feature, and yet audio options just do not work at all
![Screenshot_20221206-035853~2.png](https://user-images.githubusercontent.com/30278765/205893889-eed01e36-6fe9-4a35-8db6-525c55c6cdb6.png)

**Comment by TommyDeCortez** [comment]
I have the same problem. This error is caused by the patch Fix video playback issues. When the patch is disabled, everything works properly.

**Comment by oSumAtrIX** [comment]
> I have the same problem. This error is caused by the patch Fix video playback issues. When the patch is disabled, everything works properly.

Yeah, this can be fixed relatively easy by checking, if the video is not playing in the video player.

**Comment by clawyf** [comment]
> I have the same problem. This error is caused by the patch Fix video playback issues. When the patch is disabled, everything works properly.

That makes sense. Kinda weird that it's enabled by default when it's so buggy

**Comment by oSumAtrIX** [comment]
It is disabled by default.

**Comment by clawyf** [comment]
> It is disabled by default.

Was it? I don't remember enabling it, other than having the patch. I guess I could be wrong

**Comment by oSumAtrIX** [comment]
Yes, it is disabled by default.

**Comment by clawwwie** [comment]
I seem to be having this issue again, but only in the subscriptions menu and not in the home screen

Videos will play in feed, but only play muted in the home menu and lack the control to mute/unmute. Everything works as expected in the home page
