### ISSUE TITLE
Community post comments crash and cannot be interacted with (youtube)

### ISSUE THREAD

**Issue by clawwwie** [revanced/revanced-patches#1154]
### Type

Other

### Bug description

When opening the comments section yesterday on a community post, the entire thing was just unresponsive. The only button that worked was the close button, and I couldn't scroll through them or tap anything

Closing it and opening it again also did nothing, I had to force the app closed

### Steps to reproduce

No idea how this happened specifically, but tap on the comments section and try to interact with them

### Relevant log output

```shell
I don't have any logs for this
```

### Screenshots or videos

![Screenshot_20221128-222424~2](https://user-images.githubusercontent.com/30278765/204594512-99026151-f27c-4f6b-becf-30ccd485a56e.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by ILoveOpenSourceApplications** [comment]
No other reports and no details given. So closing for now.
