### ISSUE TITLE
Auto rotate breaks and keeps the player in portrait mode (youtube)

### ISSUE THREAD

**Issue by clawyf** [revanced/revanced-patches#1155]
### Type

Other

### Bug description

After using the app for several hours, eventually auto rotate stops doing anything and I have to manually enter landscape mode in videos or force close the app in order to get it to work again

### Steps to reproduce

Unfortunately this seems pretty random and I don't know the cause of it. But you just use the app and eventually it stops for me

### Relevant log output

```shell
No logs for this
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
This is not a ReVanced issue.

**Comment by MarcoTurra** [comment]
Sorry just to know. Is ita an Android problem?
Because i noticed that ios seems better and smarter. Anyway YouTube revanced in my experience is worst than others apps

**Comment by oSumAtrIX** [comment]
Again, not a ReVanced issue.
