### ISSUE TITLE
Audio on in-feed videos

### ISSUE THREAD

**Issue by clawyf** [revanced/revanced-patches#1156]
### Application

Youtube revanced

### Issue

When playing videos in-feed, you have to rely on captions and not audio

### Patch

What vanced did, just have an audio toggle over each video to play sound

### Motivation

This is a feature that has already been available and it would suck to not have access to it in the app

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by emyaqin** [comment]
Isn't this the vanilla's feature that also exist in ReVanced?

**Comment by clawyf** [comment]
> Isn't this the vanilla's feature that also exist in ReVanced?

You know what, you're 100% right. Revanced is just so buggy that it usually doesn't work at all

**Comment by oSumAtrIX** [comment]
Not a ReVanced issue. All videos preview on the patched app.

**Comment by clawyf** [comment]
> Not a ReVanced issue. All videos preview on the patched app.

It absolutely is a revanced issue. The app has major problems with in feed playing and it's absurd

None of this happens in vanced or youtube proper

**Comment by clawyf** [comment]
> No, it is not:
> 
> https://user-images.githubusercontent.com/13122796/206037234-0ad9d38f-4d99-471a-b626-de8602222a74.mp4
> 
> 

Doesn't mean it's not a revanced issue, just that it's an issue with revanced that doesn't affect all devices/users
I'm pretty confident there is something going wrong in revanced specifically

**Comment by oSumAtrIX** [comment]
In that case you have to be able to name the patch which allegedly causes your issue. Start with including the bare minimum of patches and find out which one causes it, report back which one it is according to you.
