### ISSUE TITLE
pip mode for youtube

### ISSUE THREAD

**Issue by lever1209** [revanced/revanced-patches#1161]
### Application

youtube 

### Issue

 locking the phone, visiting other apps, etc, stops video playback 

### Patch

pip mode, a small window that can be dragged around on top of other windows while youtube is not selected

### Motivation

allows background playback of youtube videos

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by emyaqin** [comment]
What? This is literally the reason why ReVanced and Vanced even exist in the first place.

**Comment by lever1209** [comment]
well if im here requesting it obviously something went wrong and it isnt functioning properly

**Comment by oSumAtrIX** [comment]
If something went wrong, you open a bug report not a feature request.

**Comment by emyaqin** [comment]
> well if im here requesting it obviously something went wrong and it isnt functioning properly

That's a bug, not a feature to be requested. Try to repatch your app with the recommended version of YouTube before think it as a bug

**Comment by lever1209** [comment]
and i wasnt aware it was already a feature, so why would i submit a bug report for a feature that i thought didnt exist, anyway, ill take a deeper look and submit a bug report if its still broken
