### ISSUE TITLE
feat(patch): Remove YouTube's Home Button

### ISSUE THREAD

**Issue by abbysheksaini** [revanced/revanced-patches#1163]
### Application

YouTube

### Issue

For those who only want to see their subscribed channel, and don't want youtube to recommend videos. Moreover for those who wants to de-addicts themselves of endless scroll on youtube home page.

### Patch

A patch to hide home button, similar to hide shorts button and hide create button.

### Motivation

There are many people who wants to de-addicts themselves of endless scroll on social media apps. For this they can deactivate Instagram & other social media apps but can't stop using YouTube due to its other helpful content.

To solve this problem we should allow Youtube app to only show the content which we want. i.e. Only Subscription & Library Tab.

For that 3 things were needed

Hide Create button (Available)
Hide Shorts button (Available)
Hide Home Button (Not Available)

This would also help the user who are using Newpipe & Libretube, just for this purpose. (as their UI is not as good as original Youtube App)

![20221201_020649](https://user-images.githubusercontent.com/77360929/204903268-1d90fdcc-63aa-4361-befd-4cd1a7c31418.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by thegravity98** [comment]
This

**Comment by elvinup** [comment]
Yes please this is literally what would make newpipe and other clients obsolete in my eyes. just having the option would be great

**Comment by Slowloris01** [comment]
Any update on this

**Comment by Bassani-Paulo** [comment]
As a youtube addicted myself, I am willing to work on it if no one will. I have experience in making apps in kotlin, however, I never worked in modifying an existing proprietary app. Can one of the moderators help me to get started? Is there a guide to become a contributor?

**Comment by oSumAtrIX** [comment]
@Bassani-Paulo Yes, you can find related docs in the [revanced-documentation](https://github.com/revanced/revanced-documentation) repository.

**Comment by SuperPuttar** [comment]
Looking forward for this feature.❤️

**Comment by ILoveOpenSourceApplications** [comment]
#776

**Comment by sharpsteelsoftware1** [comment]
Was this completed? How do we access it in Revanced

**Comment by oSumAtrIX** [comment]
It's a duplicate as written above

**Comment by sharpsteelsoftware1** [comment]
I am sorry I'm getting lost with GitHub's use interface. Which is the current open discussion for this issue? I keep clicking the links and going in circles. Thank you.

**Comment by oSumAtrIX** [comment]
It is completed, you can find it in the default patches selection and in the YouTube apps settings

**Comment by sharpsteelsoftware1** [comment]
It hides the Home tab, but when I open the patched app, it is still showing me home feed recommended videos. Is that how this is intended to work?

**Comment by oSumAtrIX** [comment]
Yes, the patch hides the home tab

**Comment by sharpsteelsoftware1** [comment]
OK, so this still does not stop YouTube from pushing their recommended videos when you first open the app?

The tab is hidden, but when I open the patched YouTube, I see the nauseating home recommended videos to my device. I am not sure how useful this feature is if it only hides the tab but does not prevent the home page from appearing when you first open the app.

**Comment by oSumAtrIX** [comment]
You can either click on another tab or register a shortcut to open the tabs in your launcher

**Comment by sharpsteelsoftware1** [comment]
OK thanks. Is the shortcut done by patching with "export all activities" and then finding the activity in my launcher (in this case, Nova Pro)?

**Comment by HypeMaxers** [comment]
https://github.com/revanced/revanced-patches/assets/41132838/01095a3e-7d27-4a17-b56e-4608df1b6241

Ignore my internet connection. This should work for you

**Comment by sharpsteelsoftware1** [comment]
Fantastic!! The combination of hiding the tab and using the subscriptions shortcut is a stellar solution. I believe 100% of YouTube's intrusive recommendations and practices are now removed from my device. Thank you for everybody who is involved to help remove corporate tyranny from our lives.
