### ISSUE TITLE
feat(patch): Open links directly - add support for 17.36.37

### ISSUE THREAD

**Issue by philklc** [revanced/revanced-patches#1170]
### Application

YouTube

### Issue

The majority of patches still support 17.36.37 which still has the old YouTube UI, instead of the new bubble buttons UI. This is the odd patch out that for 17.36.xx, only supports 17.36.39 and not 17.36.37.

### Patch

The same open links directly patch, with support for 17.36.37.

### Motivation

Many people don't like the new UI and would like to stay with the old UI for as long as possible.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
You should use older patches then, support is dropped for old versions at some time but you can always try to patch them regardless
