### ISSUE TITLE
feat(patch): Unlock VSCO X / Membership

### ISSUE THREAD

**Issue by rodrigoswz** [revanced/revanced-patches#1174]
### Application

VSCO
https://play.google.com/store/apps/details?id=com.vsco.cam

### Issue

Unlock premium features

### Patch

VSCO X / Membership
https://vsco.co/vsco/journal/introducing-vsco-x

### Motivation

Unlock all presents and tools of this photo editor app

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by redphx** [comment]
Done #2168
