### ISSUE TITLE
bug: Reddit Promoted Ads displays as of 2022.44.0 Update

### ISSUE THREAD

**Issue by RoonMoonlight** [revanced/revanced-patches#1177]
### Type

Other

### Bug description

The Promoted Ads now displays again since 2022.44.0 update.

### Steps to reproduce

1. Patch with above setting
2. Install Patched Reddit
3. Launch app then look at home screen
4. The Promoted Ads now displays

### Relevant log output

```shell
None. Don't even know how to even use logcat. If necessary please let me know how to do it then I will update this issue comment
```

### Screenshots or videos

I made patch with the following settings:
![Screenshot_20221202_110851](https://user-images.githubusercontent.com/25527589/205198621-84600e56-ca81-48ca-beb6-4617137b5ee8.jpg)

After patching and installing the Promoted Ads now appears:
![Screenshot_20221202_105804_Reddit](https://user-images.githubusercontent.com/25527589/205198978-c9f3788b-7b1f-426d-801b-bb3f3db8201c.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by mrmouss** [comment]
I can confirm this bug on 2022.44.0, works fine on 2022.43.0

**Comment by SCP-017** [comment]
@RoonMoonlight 

It is because the patch doesn't apply in 2022.44.0 and up or the current patch doesn't support that version yet.

![Screenshot_2022-12-10-19-21-01-652_org bromite bromite](https://user-images.githubusercontent.com/112224835/206852423-39660dcf-6c8b-46e9-bfcc-a0b5903089af.jpg)

In the screenshot above, I've selected the two patches but it didn't applied during the patch process.

**Comment by ThePillarist** [comment]
2022.45.0 has the same issue.

**Comment by mrmouss** [comment]
Developer seems to be offline. I reached out to him on discord but he doesn't seem active anymore.

**Comment by mrmouss** [comment]
> 2022.45.0 has the same issue.
> 
> Edit: don't know why this was listed as spam, I took the time to test patching the newest reddit version apk and it has the same problem? Was trying to be helpful.

My comment was also flagged as spam and all I said was: "I can confirm this bug on 2022.44.0, works fine on 2022.43.0"

**Comment by matrixzone** [comment]
I have the same issue with Reddit patch.
