### ISSUE TITLE
Patch Request: Button to add shorts to playlists

### ISSUE THREAD

**Issue by eltithecoder** [revanced/revanced-patches#1179]
### Application

Youtube App

### Issue

Sometimes you just want to save a short to watch later, but Youtube doesn't offer this in an easy way. Instead you have to check the history, press the 3 dots, then add it somewhere.

### Patch

It would come very in handy to have a button to add a short to a playlist. It could stay on the right with the other buttons such as like dislike etc, or maybe it can be shown after you click the 3 dots on the top right corner.

### Motivation

This is a feature that would help users save time and make the experience with the app better in general.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
#1101
