### ISSUE TITLE
Tiktok: sim-spoof failed

### ISSUE THREAD

**Issue by frrrrrits** [revanced/revanced-patches#1183]
### Type

Error while patching

### Bug description

sim spoof failed
tiktok version: v27.1.3
manager version: 0.0.43
android 9

### Steps to reproduce

patching

### Relevant log output

```shell
12-02 23:55:39.177 26362  4019 W System.err: app.revanced.patcher.patch.PatchResultError
12-02 23:55:39.177 26362  4019 W System.err: 	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:340)
12-02 23:55:39.177 26362  4019 W System.err: 	at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:36)
12-02 23:55:39.177 26362  4019 W System.err: 	at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:356)
12-02 23:55:39.177 26362  4019 W System.err: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
12-02 23:55:39.177 26362  4019 W System.err: 	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
12-02 23:55:39.177 26362  4019 W System.err: 	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$20(MainActivity.kt:327)
12-02 23:55:39.177 26362  4019 W System.err: 	at app.revanced.manager.flutter.MainActivity.$r8$lambda$VzOqgSVOualTn6WBlAKw3muxHF8(Unknown Source:0)
12-02 23:55:39.177 26362  4019 W System.err: 	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda13.run(Unknown Source:24)
12-02 23:55:39.177 26362  4019 W System.err: 	at java.lang.Thread.run(Thread.java:764)
12-02 23:55:39.178 26362  4019 W System.err: Caused by: java.lang.NullPointerException
12-02 23:55:39.178 26362  4019 W System.err: 	at app.revanced.patches.tiktok.misc.spoof.sim.patch.SpoofSimPatch.execute(SpoofSimPatch.kt:88)
12-02 23:55:39.178 26362  4019 W System.err: 	at app.revanced.patches.tiktok.misc.spoof.sim.patch.SpoofSimPatch.execute(SpoofSimPatch.kt:26)
12-02 23:55:39.178 26362  4019 W System.err: 	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:336)
12-02 23:55:39.178 26362  4019 W System.err: 	... 8 more
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by KazKaz90** [comment]
Try using `com.ss.android.ugc.trill` TikTok

**Comment by frrrrrits** [comment]
> Try using `com.ss.android.ugc.trill` TikTok

yes is it

**Comment by SCP-017** [comment]
@frrrrrits 

Maybe it's a Manager Bug.
Sim Spoof worked on me.

![Screenshot_2022-12-03-23-09-42-335_org bromite bromite](https://user-images.githubusercontent.com/112224835/205447797-9b88903e-290a-4ebf-af48-f3c7adfbe5ea.jpg)

**Comment by KazKaz90** [comment]
> > Try using `com.ss.android.ugc.trill` TikTok
> 
> yes is it, anyone working?

Yeah worked for me when I tried patching `com.ss.android.ugc.trill` 27.2.1

**Comment by SCP-017** [comment]
> > > Try using `com.ss.android.ugc.trill` TikTok
> > 
> > 
> > yes is it, anyone working?
> 
> Yeah worked for me when I tried patching `com.ss.android.ugc.trill` 27.2.1

Working the same on `com.zhiliaoapp.musically`.

**Comment by frrrrrits** [comment]
> 

yeah working on this version ok then
