### ISSUE TITLE
Twitter crashes when i reboot my phone.

### ISSUE THREAD

**Issue by sertchan** [revanced/revanced-patches#1184]
### Type

Error at runtime

### Bug description

After i install twitter revanced with revanced manager like 2 weeks ago bug happens when i reboot my phone and an interesting point bug happens even stock twitter which i install from PlayStore. 

Pre Reboot:
![Screenshot_20221202-221155](https://user-images.githubusercontent.com/53477192/205368899-71e71c8b-d8bd-4ec7-bfd7-fa97e476baf6.png)
![Screenshot_20221202-221200_Twitter](https://user-images.githubusercontent.com/53477192/205368906-e8900660-b654-4bb4-8a39-be162c9dcf04.png)

Post Reboot:
![Screenshot_20221202-221300_Settings](https://user-images.githubusercontent.com/53477192/205368839-d616594a-4f2a-4313-9a1f-3cd77cf83cf1.png)
![Screenshot_20221202-221305](https://user-images.githubusercontent.com/53477192/205369014-e413e841-2c12-4271-9fd2-54acd1753f45.png)

Then app crashes. After 3-4 seconds with no response.

### Steps to reproduce

In my situation just install app from Playstore or download and install it from any apk website. Patch it with revanced pathces or don't even touch to apk it doesn't metter.

### Relevant log output

```shell
Unfortunately, i dont know how to get logs (which is useful for you) from this app. So you tell me.
```

### Acknowledgements

- [x] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
You patched and installed a split apk instead of mounting it. Please use a full APK.
