### ISSUE TITLE
feat(YouTube): Disable ambient mode by default patch

### ISSUE THREAD

**Issue by HeroGalak** [revanced/revanced-patches#1186]
### Application

YouTube

### Issue

Every time I install ReVanced I would like to save time and disable ambient mode by default without going into video player settings.

### Patch

The patch should only put to OFF ambient mode.

### Motivation

Already explained in issue section

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
You are not supposed to uninstall the app. Therefore you don't need to turn off ambient mode.
