### ISSUE TITLE
bug: YouTube - hide info cards patch always hides infocards (even if hideinfo cards is not enabled in ReVanced settings)

### ISSUE THREAD

**Issue by LisoUseInAIKyrios** [revanced/revanced-patches#1187]
### Type

Cosmetic

### Bug description

If using the hideinfocards patch, then infocards are always hidden -- even if "hide info-cards" is turned off in ReVanced settings.

### Steps to reproduce

- patch YouTube with default patches (which includes "hide-info-cards" patch)
- Launch ReVanced YouTube, navigate to ReVanced settings, and ensure "Hide info-cards" is switched off
-  watch any video with infocards, such as [https://www.youtube.com/watch?v=qiVqicC8sIA](https://github.com/revanced/revanced-patches/issues/url))
- an infocard should be seen at 5s, but no infocard is shown.

**Comment by Matty003** [comment]
#623

**Comment by oSumAtrIX** [comment]
These are closed, the issue is up to date.

**Comment by LisoUseInAIKyrios** [comment]
Until the issue is fixed, maybe change the patch so it is not included in patching by default?

At least that way the user has to manually pick the patch for inclusion in ReVanced Manager.  

Because currently, users get the patch by default and then after installation there is no way of turning it off.

**Comment by oSumAtrIX** [comment]
Or just fix the invalid switch setting name. Probably a typo. It's the same effort as makong it exclude by default.
