### ISSUE TITLE
feat(patch): Replace Shorts button at the bottom with search button at the top

### ISSUE THREAD

**Issue by d3EyedRaven** [revanced/revanced-patches#1193]
### Application

YouTube ReVanced

### Issue

Search button by default is at the top, where it's harder to reach, and almost all people here don't use shorts button, so shorts button should be replaced by the search. 

### Patch

There is a patch that disables short button, but it would be very handy if it's replaced by search button from the top. just visually a  search icon should be added and tapping it navigates to normal search function.

### Motivation

It'd be super useful for literally all of us, because the shorts button is replaced by the search which is at the top bar where it's harder to reach.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by MKRhere** [comment]
I was looking for a request for removing shorts button, but this is even better ^

**Comment by oSumAtrIX** [comment]
#1341
