### ISSUE TITLE
feat(patch): Sort by Oldest in channels 

### ISSUE THREAD

**Issue by KyleBroflowski** [revanced/revanced-patches#1200]
### Application

Youtube recently rolled out the update which limited sorting by oldest

### Issue

It's hard to binge channels with large number of videos. 

### Patch

Enable the sort option to sort by oldest in addition to options to sort by newest and sort by popular as before. 

### Motivation

The same still works in old vanced app meaning the support for that feature isn't completely gone.

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
#636
