### ISSUE TITLE
bug: In certain devices, gesture volume goes up to 150, instead of 15.

### ISSUE THREAD

**Issue by d3EyedRaven** [revanced/revanced-patches#1202]
### Type

Other

### Bug description

On certain devices (I have Redmi Note 10 Pro), the volume with gestures enabled goes up to level 150 instead of 15. The drag speed is also same as level 15, so in one drag maximum volume I can change is 30. That's 5 full drags to change from min to max volume and max to min.

### Steps to reproduce

1. Enable gesture for brightness and volume

2. Use volume gesture to increase or decrease volume

3. Instead going through level 0 through 15, it goes 0 through 15 with same slow drag speed.

### Relevant log output

```shell
sorry not available
```

### Solution

Currently it's 100 levels for brightness with high drag sensitivity, and 15 levels for volume with low drag sensitivity.

I think it's fair to do 30 levels of brightness and volume in all devices, as in MX Player, (or 100 as in VLC Android) for the same drag sensitivity.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by SodaWithoutSparkles** [comment]
Unable to replicate the volume goes up to 150 issue. Currently on:

- POCO X4 GT
- MIUI 13
- Android 12
- Revanced YT 17.45.36
- Manager 0.0.43
- Patches 2.137.1

**Comment by oSumAtrIX** [comment]
This depends on your phone

**Comment by d3EyedRaven** [comment]
@SodaWithoutSparkles 

done
Redmi Note 10 Pro
all configuration same as yours.
thread of other user with same issue: https://www.reddit.com/r/revancedapp/comments/z0vzul/it_takes_around_7_to_8_swipes_to_increase_volume/

https://user-images.githubusercontent.com/71594081/205683314-e953d214-fcc2-4652-9fc3-076724b52619.mp4

**Comment by d3EyedRaven** [comment]
Hi @SodaWithoutSparkles 
Link to first video: https://youtu.be/rz1Ad5Yizbk

New video that's fully landscape: https://youtu.be/iZnLZFRylbs
https://user-images.githubusercontent.com/71594081/205692614-5b95501a-da88-491c-975e-180b554dde7e.mp4

As @oSumAtrIX mentioned, my phone has indeed that many steps for volume i.e. 150, however i couldn't found solution to that.

Is this possible?
> I think it's fair to do same levels of brightness and volume in all devices, 30 as in MX Player, or 100 as in VLC Android for the same swiping sensitivity.

**Comment by SodaWithoutSparkles** [comment]
ok. does using the OG youtube, (with the same version,) has this problem as well?

I dont think theres any way for a android phone to have volume over 15. Thats certainly abnormal. Maybe it will be converted from 0-150 to 0-15 scale? 

Can OP also monitor the volume by the system volume meter? Press volume once, then swipe the volume, observe if the bar changes as well. But be quick, the bar would disappear in less than 3 seconds

**Comment by d3EyedRaven** [comment]
pressing volume button changes the volume using 0-15 scale. swiping changes the volume using 0-150 scale.

at one point i had just kept the volume swiping off just because of low swiping sensitivity.

this problem only occurs in revanced youtube. None other application.

update: I just tried vanced youtube using vanced manager, it had same issue, but at least swiping sensitivity is fast, same brightness swipe. had to swipe once or twice to get to max volume instead of six swipes at revanced. 
i alsotried turning miui optimizations off like vanced manager asked me to, it didn't help.

**Comment by maghuro** [comment]
Didn't happened on my Xiaomi 10T pro, and now it's happening in my 12T pro - 150 steps to boost volume, even if pressing the volume buttons!

Is there something I have to change? I can't find anything.

**Comment by SodaWithoutSparkles** [comment]
@oSumAtrIX it does depends on the phone, but the user just sees the 0-15 UI. They dont see the 0-150 UI in anywhere except revanced/old-vanced. Maybe a workaround can be installed, like IF the range is 0-150, then jump for 10 units at once instead of 1

**Comment by LemonadeG** [comment]
Same problem on Poco F3 using MIUI 13

**Comment by LaundryHamper** [comment]
I also have this issue. My phone is a Xiaomi Redmi Note 10 Pro (_...2 Alpha HD Remaster & Knuckles: The Lost Levels_), so it isn't a device-specific issue, it's specific to MiUI, and it's an issue which can be accounted for and avoided by the application. Whatever way volume control was implemented in Vanced resulted in the normal 0-15 scale on this same phone. ReVanced has the 0-150 scale, but only when the video is playing in fullscreen.

Reddit is Fun also has this issue, but again only when a video is fullscreen.

Vimeo does not have this issue, even when fullscreen.

It probably has something to do with Xiaomi wanting MiUI's floating volume sliders to appear infinitely scalable like those on the iPhone.

On top of how annoying to use this makes the swipe gesture, it takes slightly more than eight seconds to go from one end of the scale to the other holding down the volume button, which isn't great if you need your phone to shut up in a hurry.

**Comment by SodaWithoutSparkles** [comment]
@LaundryHamper Can you try executing `termux-volume` in termux? You probably need termux:api as well.

https://f-droid.org/packages/com.termux
https://f-droid.org/packages/com.termux.api

if the packages are missing, install them as prompted.

Example output:
```
[
  {
    "stream": "call",
    "volume": 11,
    "max_volume": 11
  },
  {
    "stream": "system",
    "volume": 8,
    "max_volume": 15
  },
  {
    "stream": "ring",
    "volume": 8,
    "max_volume": 15
  },
  {
    "stream": "music",
    "volume": 9,
    "max_volume": 15
  },
  {
    "stream": "alarm",
    "volume": 10,
    "max_volume": 15
  },
  {
    "stream": "notification",
    "volume": 8,
    "max_volume": 15
  }
]
```

**Comment by dev0nizer** [comment]
Looks like a Xiaomi related bug, my device is Xiaomi Pad 6 and I'm facing the same issue
Also, the status of the issue is "closed", but there is no solution :(

**Comment by SodaWithoutSparkles** [comment]
@dev0nizer try the termux thing i mentioned above. Wanna get some more insights

**Comment by dev0nizer** [comment]
@SodaWithoutSparkles apologies for the late response
```
[
  {
    "stream": "call",
    "volume": 8,
    "max_volume": 11
  },
  {
    "stream": "system",
    "volume": 10,
    "max_volume": 15
  },
  {
    "stream": "ring",
    "volume": 10,
    "max_volume": 15
  },
  {
    "stream": "music",
    "volume": 75,
    "max_volume": 150
  },
  {
    "stream": "alarm",
    "volume": 12,
    "max_volume": 15
  },
  {
    "stream": "notification",
    "volume": 10,
    "max_volume": 15
  }
```

**Comment by dev0nizer** [comment]
@SodaWithoutSparkles changing volume with buttons is also extremely slow (I need to hold the "volume down" button for 3-4 seconds to change the volume from 150 to 0), so it would be great to have a scale control for both buttons and swipe gestures, or implement some other fix

**Comment by clicky6** [comment]
Any module or hack which can make the the volume steps that are currently 15 on my device in Revanced to 100 or 150?
