### ISSUE TITLE
Request: bring back sort by oldest 

### ISSUE THREAD

**Issue by eclipsek20** [revanced/revanced-patches#1204]
### Application

Youtube 

### Issue

Youtube removed the sort by oldest feature 

### Patch

The bring back of the sort by oldest button 

### Motivation

It's an old and memorable feature 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by SodaWithoutSparkles** [comment]
#636
