### ISSUE TITLE
feat(YouTube): DeArrow / Clickbait Remover

### ISSUE THREAD

**Issue by scientiac** [ReVanced/revanced-patches#1208]
### Application

YouTube

### Issue

- People being fooled by the creators.
- People spending very long hours on YouTube.

### Patch

The feature is this add-on:
[Clickbait Remover browser extension](https://addons.mozilla.org/en-US/firefox/addon/clickbait-remover-for-youtube/)

### Motivation

- Reduces YouTube addiction and Increases the chances of getting a good YouTube Video. 
- Also reduces YouTube consumption by making everything look not as pretty as it should look in the thumbnail.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by chixPL** [comment]
I'd recommend integrating [DeArrow](https://dearrow.ajay.app/) instead. It allows people to crowdsource an image or a screenshow from a video that actually matters. Plus it can force proper capitalization on video titles.

**Comment by fillwithjoy1** [comment]
> DeArrow is made by the creator of Sponsorblock.
> 
> Because the DeArrown API call would be asynchronous, this would require figuring out how to change Litho components after they are created and displayed.
> 
> Changing the thumbnail image might be possible without too much fuss, but changing the text after layout may be difficult.

Can you replace a video on the layout by another generated video layout that has the fetched info from DeArrow?

**Comment by fillwithjoy1** [comment]
> > Can you replace a video on the layout by another generated video layout that has the fetched info from DeArrow?
> 
> What do you mean change the video? Do you mean change the video thumbnail?
> 
> I spent some time looking for the code that handles the thumbnail generation, but I only found dead legacy code ImageView code that isn't used (I would estimate 80% of YouTube is unused legacy code). Layout inspector doesn't help because it only shows the thumbnail is litho component host (and doesn't reveal any more info). More research is needed.

Yes, literally that. Is it not possible to load "cards" of each video without their images, and asynchronously fetch images before finally updating the "card" with the right thumbnail?

**Comment by oSumAtrIX** [comment]
YouTube works almost entirely through ProtoBuf. Everything is streamed through a common port.

**Comment by fillwithjoy1** [comment]
Hmmm, can we block the main thread temporarily to fetch the DeArrow content, and if no response is occured after 5 secs (customizable), then we show the original video/thumbnail. Yes, this will make the app feel _slightly_ slower, and may even give the impression that the network is bad, but could this be implemented?

**Comment by oSumAtrIX** [comment]
The problem is not the implementation. The problem is to find the real places that can be modified.

**Comment by oSumAtrIX** [comment]
DeArrow probably allows passing a list of ids and receiving a list of thumbnails and titles. Implementation is a second-order issue. The main issue is that we have to find where it loads the thumbnails and titles.

**Comment by fillwithjoy1** [comment]
> 

Oh my bad I said the wrong things. You know how when you open YouTube, it loads the videos asynchronously, can we modify the loading code to include fetching full data from dearrow within x seconds?

**Comment by oSumAtrIX** [comment]
Technically possible yes.

**Comment by oSumAtrIX** [comment]
The buffer is consumed by specific methods that read a number of bytes at a time and parse it. These methods can be hooked so that the index is captured they read from the buffer. Since you know at which index the link appears in you can determine which method reads it from the buffer.

**Comment by chixPL** [comment]
LibreTube will soon able to support DeArrow, so that means it is possible to do it.

**Comment by eclipsek20** [comment]
> LibreTube is built from the ground up and has the Luxury of designing everything itself.  It is not a patch for an obfuscated app released by another company.
> 
> While technically anything is possible with patching, it always falls into: "ok but how difficult is it to actually do that?"

Yes it's difficult but that's life. If the team works hard enough on it, the end result will work 😃

**Comment by ajayyy** [comment]
Patching and dealing with existing interfaces is hard. There is a reason the browser extension took me almost 6 months to develop from when I started! Edge cases can turn into rabbit holes...

**Comment by oSumAtrIX** [comment]
> Handling these failure cases makes the patch more complicated because additional changes are needed so it can fallback to using the original thumbnail url (I currently do not have any fallback logic implemented).

If you hook the string parameter, can you not passthrough it?

**Comment by oSumAtrIX** [comment]
> and generate the thumbnails locally using FFMPEG

This is way beyond what is necessary for us. Depending on if you can simply passthrough the hooked string parameter using the existing service, it shouldn't cause any issues. I have no details about your implementation, so I can not say for sure though.

**Comment by ajayyy** [comment]
Generating thumbnails for the first time can take multiple seconds. Doing it server side allows most requests to have been pre-rendered and stored which isn't possible if done on the client side.

**Comment by ajayyy** [comment]
What if my thumbnail cache returned a 301 redirect on failure to the original thumbnail. Would that get handled properly?

**Comment by oSumAtrIX** [comment]
Otherwise, the patch could download the headers only (to check for 404) for maximum performance before passing the URL to YouTube.

**Comment by oSumAtrIX** [comment]
@LisoUseInAIKyrios It may be a good idea to open issues regarding DeArrow in their respective repositories so they are correctly trackable and link them here. This way, the maintainer doesn't have to track this here.

**Comment by ajayyy** [comment]
Do you know the original thumbnail url ahead of time. As in, can it be provided as a parameter, or does the DeArrow server have to craft it

**Comment by ajayyy** [comment]
Added

https://dearrow-thumb.ajay.app/api/v1/getThumbnail?videoID=R2oD1ZHNMFE&redirectUrl=https://i.ytimg.com/vi_webp/R2oD1ZHNMFE/hq720.webp

https://dearrow-thumb.ajay.app/api/v1/getThumbnail?videoID=SomeWrongID&redirectUrl=https://i.ytimg.com/vi_webp/R2oD1ZHNMFE/hq720.webp

**Comment by YT-Advanced** [comment]
> Perfect! It works as expected 

How about the title, it is quite hard to modify, I think

**Comment by GeekCornerGH** [comment]
@LisoUseInAIKyrios Would titles be included in the DeArrow patch?

**Comment by reisxd** [comment]
Well, I'm pretty sure this would run very badly for non-flagship phones, like mine. Also, this'd require to add a huge model to the patched application and run it locally, which the performance can vary for each device. Running it on a local PC could also most likely give bad results, and who would want to even keep their PC on just for AI thumbnails? And as you said, a paid API is not something we could do.

**Comment by enderprism** [comment]
DeArrow includes a non-clickbait title feature, that doesn't have a Revanced patch. Also note that the current clickbait replacer can't fetch community DeArrow thumbnail, which is what I use (I don't like the auto-generated thumbnails). Are these features planned?

**Comment by fillwithjoy1** [comment]
uhh why we using stable diffusion? sounds like a bad idea? battery drain? Anyways, retrieve the server thumbnails and titles if a dearrow title and thumbnail exists instead

**Comment by enderprism** [comment]
wdym
i’m just asking if there is an option for this planned (fine-tune options instead of a global dearrow toggle would be nice)
we could put a warning in the app next to the toggle so users know about the eventual battery drain and network usage

**Comment by fillwithjoy1** [comment]
> wdym i’m just asking if there is an option for this planned (fine-tune options instead of a global dearrow toggle would be nice) we could put a warning in the app next to the toggle so users know about the eventual battery drain and network usage

there really isn't a network/battery drainage using DeArrow, since its masked by YouTube itself requiring more power to decode the video frames and network for downloading the video itself. At most DeArrow isn't going to skyrocket one's network usage anyways.

**Comment by Zero-G-Sys** [comment]
This needs an option for only showing the community submitted DeArrow thumbnail, otherwise fallback to the original. The auto generated ones are most of the time quite bad.
Maybe asking the DeArrow dev to put a parameter in the api path to not return a thumb if there isn't an user submitted one

**Comment by oSumAtrIX** [comment]
@Zero-G-Sys https://github.com/ReVanced/revanced-patches/pull/3378/files#diff-ecead68b5f5e43a0b307e4e1691735553c18edecc876b85df2a9fd61dd88bee5R5

**Comment by fillwithjoy1** [comment]
Are there any ways to get modified titles working at all?

Sent with Shortwave <https://www.shortwave.com?utm_medium=email&utm_content=signature&utm_source=am95c2luZ2guanMxQGdtYWlsLmNvbQ==>
