### ISSUE TITLE
fix: fenster-swipe-controls

### ISSUE THREAD

**Issue by EXAM454** [revanced/revanced-patches#121]
# Issue

- [x] Brightness control
- [x] Fullscreen overlay blocking underlying controls (Such as the skip button, double-tap to seek, hold to seak)

# Solution

Proxy-pass certain touch events such as double-tap to the underlying control

**Comment by TheJeterLP** [comment]
Yes I've already seen that too. Downgrade patches for now.

**Comment by PabloGirol** [comment]
Also if you press and hold, while you swipe left or right you can seek the video into a specific time, that gets blocked too!

**Comment by shadow578** [comment]
Hi, currently working out a fix for this. 
but i don't understand what you mean with `Brightness control`, could you please elaborate further?

**Comment by EXAM454** [comment]
> Hi, currently working out a fix for this. but i don't understand what you mean with `Brightness control`, could you please elaborate further?

change brighness with swipe is not working. just overlay.
