### ISSUE TITLE
Will ReVanced be shut down?

### ISSUE THREAD

**Issue by Dertyiula** [revanced/revanced-patches#1213]
### Application

ReVanced

### Issue

I understand that ReVanced relies on a patching system.After patching ReVanced, a complete APK is generated.The only difference between this and Vanced is that it is generated after patching the APK.Again, this is against YouTube's rules.

### Patch

Above is everything.

### Motivation

I think we should think carefully.You have changed your Existing YouTube again.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
That would depend on DMCA 1201 after the acceptable use policy by GitHub.

**Comment by Dertyiula** [comment]
Did I not understand?

**Comment by Canny1913** [comment]
> Did I not understand?
> 
> Will ReVanced be shut down?

He gave you the answer.

**Comment by oSumAtrIX** [comment]
It depends on GitHub's Acceptable Use policy and on DMCA 1201.
