### ISSUE TITLE
feat(patch): Vanced MicroG outdated

### ISSUE THREAD

**Issue by aryaoffixial** [revanced/revanced-patches#1217]
### Application

com.google.android.gms 
GitHub:microG/GmsCore

### Issue

For security reasons updating apps are important. Vanced microG stores our google login data. Add option to patch new microG without worries.

### Patch

Lightweight same like vanced Micro but up to date

### Motivation

Security reasons. Privacy and security is important.
Thank you for patches💓

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by reisxd** [comment]
microG also doesn't get updated frequently, so not required.

**Comment by oSumAtrIX** [comment]
It is open source, no patch is required.
