### ISSUE TITLE
Some tiktok patches are failing

### ISSUE THREAD

**Issue by bceez** [revanced/revanced-patches#1223]
### Type

Error while patching

### Bug description

Patches are failing with tiktok version 27.3.1

### Steps to reproduce

-Install Latest Tiktok version from apkmirror
-Patch version 27.3.1 with the Revanced manager

### Relevant log output

```shell
.
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [ ] I filled out all of the requested information in this issue properly.

**Comment by bceez** [comment]
Forgot to attach logs

**Comment by oSumAtrIX** [comment]
Your device has insufficient RAM to patch the app.

**Comment by bceez** [comment]
It only happens when i try to patch 27.3.1 any other version works. And i have 4gb ram
