### ISSUE TITLE
feat(patch): Playing Shorts as normal videos

### ISSUE THREAD

**Issue by kryptobolt200528** [ReVanced/revanced-patches#1223]
### Application

Youtube 

### Issue

The default shorts player is just disgusting,you can't rewind or double tap to seek.

### Patch

The patch would be to force the youtube videos to play in the normal player,this can be done by replacing the normal short link https://youtube.com/shorts/xyz..
with
https://youtube.com/watch?v=xyz..
or https://youtu.be/xyz..
This can again be provided as a toggle under the layout menu.

### Motivation

I am pretty sure that a sizeable amount of people who watch shorts would want to play them in the normal youtube player

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by rgstoian** [comment]
I'm seeing this as competed, but I haven't found any patch that would match this behaviour. Is it implemented?

**Comment by oSumAtrIX** [comment]
https://github.com/ReVanced/revanced-patches/issues/1800
