### ISSUE TITLE
premium-heading does not have a settings entry

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [revanced/revanced-patches#1224]
### Type

Other

### Bug description

`premium-heading` does not have a settings entry, unlike other similar layout-modifying patches

### Steps to reproduce

1. Patch YT with `premium-heading` settings
2. Notice that you cannot disable the premium heading at runtime, unlike most of the other patches

### Relevant log output

```shell
N/A
```

### Solution

Add a settings option

### Additional context

Or this should be filed as a patch request?

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Canny1913** [comment]
The current design of the patch doesn't allow a switch to be implemented.
