### ISSUE TITLE
AMOLED dark theme enables itself after a restart even when disabled from patches

### ISSUE THREAD

**Issue by alesimula** [revanced/revanced-patches#1225]
### Type

Cosmetic

### Bug description

Even when the "custom theme" option is disabled in settings, it will still enable itself after closing restarting the app

### Steps to reproduce

1. Open the app for the first time, it will have gray background
2. Close the app
3. Open the app again, it will have pitch black background

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by alesimula** [comment]
EDIT: my bad, I just noticed that vanilla YouTube now does the same... It would be nice to have an option to switch between themes though

**Comment by oSumAtrIX** [comment]
YouTube by default is almost amoled now. This is not caused by the theme patch.

**Comment by alesimula** [comment]
@oSumAtrIX sorry but how do I do that, I've been searching for that option but couldn't find it (yes a re-patched it with custom theme turned on)

**Comment by CnC-Robert** [comment]
> @oSumAtrIX sorry but how do I do that, I've been searching for that option but couldn't find it (yes a re-patched it with custom theme turned on)

You can only do it with the cli currently

**Comment by oSumAtrIX** [comment]
Because the ReVanced Manager does not support patch options yet, you have to use the CLI.
