### ISSUE TITLE
feat(patch): Re-add the Trending button back

### ISSUE THREAD

**Issue by Primiman** [revanced/revanced-patches#1226]
### Application

YouTube ReVanced 

### Issue

There's no Trending shortcut at the bottom of the screen, like there used to be as YouTube developers got rid of it.

### Patch

Add a patch that re-adds the Trending button on YT ReVanced.

### Motivation

I figured many other users are missing the button, as it's nice to browse and see what's new every once in a while.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
#835

**Comment by Primiman** [comment]
How? Closed but no solved? There's no chip.

**Comment by oSumAtrIX** [comment]
https://user-images.githubusercontent.com/13122796/206455340-c39c2b17-6a38-44f1-b10c-3b174dde2047.mp4
