### ISSUE TITLE
Change the download service.

### ISSUE THREAD

**Issue by Dertyiula** [revanced/revanced-patches#1230]
### Application

YouTube

### Issue

Do not use NewPipe for download service.

### Patch

https://github.com/JunkFood02/Seal

### Motivation

This app is designed by Material You and is a video downloader for android.It has many functions.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
NewPipe has many functions to. Simply switch to any other app in the settings.
