### ISSUE TITLE
ReVanced

### ISSUE THREAD

**Issue by Dertyiula** [revanced/revanced-patches#1239]
### Application

Has ReVanced been discontinued?

### Issue

.

### Patch

.

### Motivation

.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Canny1913** [comment]
No.

**Comment by Dertyiula** [comment]
What about the information on Twitter?

Has the DMCA issue been resolved?

**Comment by Dertyiula** [comment]
ReVanced will be for life.

**Comment by Canny1913** [comment]
> What about the information on Twitter?
> 
> Has the DMCA issue been resolved?

Repo got reinstated. We asked some questions to GitHub and currently waiting for response.

**Comment by Dertyiula** [comment]
You will inform me.

**Comment by Canny1913** [comment]
> You will inform me.

Join the discord server.

**Comment by Dertyiula** [comment]
Where do you correspond?
