### ISSUE TITLE
swipe controls patch not working correctly.

### ISSUE THREAD

**Issue by Itroublve** [revanced/revanced-patches#124]
> Fullscreen overlay blocking underlying controls (Such as the skip button, double-tap to seek, hold to seak)

Is still not solved as I'm still experiencing it with a certain area to the sides.

Swipe controls don't always trigger, triggers after several attempts. When it works I tried removing finger and swiping again and it seems to not work then.
@shadow578

**Comment by Aunali321** [comment]
The brightness value change when swiping horizontally(it shouldn't). I can also no longer pause the video. the menu does not show up at all and i cant skip forwards or backwards.

**Comment by shadow578** [comment]
> Fullscreen overlay blocking underlying controls (Such as the skip button, double-tap to seek, hold to seak)

yes, this is a issue with the old implementation, will be fixed by https://github.com/revanced/revanced-integrations/pull/64 too


> Swipe controls don't always trigger, triggers after several attempts. When it works I tried removing finger and swiping again and it seems to not work then.

(i believe) you have to long-press to enable swiping first. If that's not the issue, we'd have to try to reproduce with the rewrite
