### ISSUE TITLE
feat(patch): Hide thin time-bar in full screen

### ISSUE THREAD

**Issue by Kalpataru6** [revanced/revanced-patches#1240]
### Application

Youtube

### Issue

A thin black timeline bar from full screen

### Patch

For some days a very thin black timeline bar is appearing in videos and it is annoying and distracting.. I have checked the official YouTube and this is also present in it.. So I'm requesting to make a patch that can hide that thin bar from videos in full screen.. 
Here is screenshot
https://media.discordapp.net/attachments/952946952348270626/1051495147986223125/Screenshot_2022-12-11-19-15-54-311_app.revanced.android.youtube.jpg

### Motivation

It is distracting and annoying.. That's a great motivation I think.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
This is not a feature request. Please consult YouTube for a bugfix.
