### ISSUE TITLE
bug: YouTube doesn't close with back gesture 

### ISSUE THREAD

**Issue by JanB97** [revanced/revanced-patches#1244]
### Type

Error at runtime

### Bug description

Revanced YouTube doesn't close while using the back button.

### Steps to reproduce

Use revanced manager to patch the YouTube app, open Revanced YouTube, use back gesture -> app won't close

### Relevant log output

```shell
Don't know what is relevant/ how to get it.
```

### Screenshots or videos

![Screenshot_20221212-001929](https://user-images.githubusercontent.com/7881168/206935015-d607a170-83e2-4649-9630-6824f7b07c0c.png)
Patches applied.

### Solution

No idea, unfortunately.

### Additional context

Using a Nothing Phone (1) with Nothing OS 1.1.7 -> Android 12.

It is working on my Huawei Tablet with Harmony OS 2.0

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
#1097
