### ISSUE TITLE
feat(patch): Instagram (Ads, Hide Reels, & More)

### ISSUE THREAD

**Issue by juniorjacob** [revanced/revanced-patches#1246]
### Application

Instagram
- com.instagram.android
- https://play.google.com/store/apps/details?id=com.instagram.android&gl=US
- [https://https://www.instagram.com/.](Website)

### Issue

- Sponsorships (ads)
- Suggested Posts
- Suggested Reels
- Hide Reels button
- Tracking spoofer
- Reminder to stop scrolling (optional)

### Patch

I would like for the patch to remove store ads, suggested posts, and suggested reels from the home page. I'd also like the patch to allow hiding the Reels button in the app, spoof tracking data, and remind the person to stop scrolling after some time. I don't believe all of these to be made at once, or expect any of this to be all that well thought out originally, but would like to have them in the future.

### Useful Links
- https://github.com/gusarov/InstagramAdKiller
- https://github.com/TremendoX/UnclutterIG

### Motivation

I personally use my Instagram exclusively to remind myself of new clothing releases from Instagram-exclusive (or as close to) brands that create fantastic clothing. Unfortunately, I get confused with their clothes, which are well made, handcrafted, and inspired, with resellers from Instagram's sponsored advertisements. I hate this, these clothes are terrible and ruin the view of what I actually want to see. Besides I and many others don't need sponsorships in our lives, we have enough posts, stories, and reels, from the creators we follow and just want to catch up with them. Please allow me and many others to simply check up on what's new, and move on.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
#553

**Comment by oSumAtrIX** [comment]
The links you sent seem to hook on ART bytecode level via Xposed, but they are quite old. Instagram should be using react native currently, which is why you would need ti implement a react native patch inside a resource patch. Confirm if Instagram is react native.
