### ISSUE TITLE
bug: YT Hide watch in VR gets reverted when switching to Incognito.

### ISSUE THREAD

**Issue by fosam** [revanced/revanced-patches#1247]
### Type

Other

### Bug description

When `Hide watch in VR` is enabled, it works fine until Incognito mode is enabled where Hide watch in VR option appears again for some reason.

### Steps to reproduce

Settings ---> ReVanced ---> Layout ---> Enable Hide watch in VR.

Then switch to Incognito mode, play a video, and notice the option down in the bottom.

### Relevant log output

```shell
Will be provided if needed.
```

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
#964

**Comment by fosam** [comment]
It's very strange, i searched and i didn't find anything:

![image](https://user-images.githubusercontent.com/52612348/206940391-387b1281-4aef-4b19-a545-0b03d98e6fee.png)

Are there any other ways to find related issues before opening one?

**Comment by oSumAtrIX** [comment]
You filtered for closed issues. #964 is open.

**Comment by fosam** [comment]
Do you use Github everyday? - it doesn't matter, if there was any results, it would show a number in both, open and closed icons. regardless of the filtering:

![image](https://user-images.githubusercontent.com/52612348/206940995-e96ccf8e-d7e0-4954-b2c7-15c4953540b2.png)

**Comment by oSumAtrIX** [comment]
Your question does not matter to this. You should consult GitHub for this issue.
