### ISSUE TITLE
BTTV Android

### ISSUE THREAD

**Issue by albertopasqualetto** [ReVanced/revanced-patches#1255]
### Application

BTTV Android

### Issue

Same patches as Twitch

### Patch

Same patches as Twitch

### Motivation

It is the same as original Twitch, but with some enhancements, so it should support the same patches.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by ggtylerr** [comment]
TBH it'd be better to have a BTTV / FZ / whatever patch for the twitch app, rather than the other way around. I do think the BTTV app should be supported in some way though, like how the original vanced app is supported.

**Comment by einekratzekatze** [comment]
What needs to happen that someone works on this?

**Comment by albertopasqualetto** [comment]
I think that this app's patch is no longer needed since there is Purple TV now.
Consider closing this issue.

**Comment by einekratzekatze** [comment]
> I think that this app's patch is no longer needed since there is Purple TV now.
> Consider closing this issue.

PurpleTV?

**Comment by albertopasqualetto** [comment]
> PurpleTV?

Yes, [their Discord](https://discord.gg/DkjMM4ThhG).

**Comment by albertopasqualetto** [comment]
@einekratzekatze 
Ehm, it was open source, now their gitlab is open only to their subscribers.

**Comment by ggtylerr** [comment]
> @einekratzekatze 
> Ehm, it was open source, now their gitlab is open only to their subscribers.

That's not open source... but yeah, while it has merit as a FOSS alternative (and one which utilizes patches instead of full mods), it's definitely a lower priority. I wouldn't suggest closing for this reason though, moreso because #1318 exists.

**Comment by oSumAtrIX** [comment]
Wrong repository: https://github.com/bttv-android/bttv

**Comment by einekratzekatze** [comment]
> Wrong repository: https://github.com/bttv-android/bttv

What do you mean?

**Comment by oSumAtrIX** [comment]
You are requesting a feature for BTTV: https://github.com/bttv-android/bttv

**Comment by einekratzekatze** [comment]
> You are requesting a feature for BTTV: https://github.com/bttv-android/bttv

No, this Issue is about providing an adblocker patch for BTTV, as BTTV doesnt want it for some stupid reason and we already have adblockers for normal twitch.

**Comment by ggtylerr** [comment]
> You are requesting a feature for BTTV: https://github.com/bttv-android/bttv

1. The app I was referring to was PurpleTV, which was the app being talked about and referenced in the replies before mine.
2. As @einekratzekatze said, BTTV has chosen not to add an adblocker.

**Comment by oSumAtrIX** [comment]
The issue title is Bttv, and if BTTV has chosen not to add an adblocker, you can fork it.
