### ISSUE TITLE
bug: YouTube progress bar weird

### ISSUE THREAD

**Issue by KoleckOLP** [revanced/revanced-patches#1257]
### Type

Cosmetic

### Bug description

in fullscreen youtube playback progress bar draws on screen as a black line.

in portrait the progress bar is not red but white

### Steps to reproduce

install youtube revanced start it and close it
than after some time start it again and play a video
progress bar in portrait is white
and in fullscreen there is a black line.

### Relevant log output

```shell
I don't know what logs to get and how.
```

### Screenshots or videos

![Screenshot_2022-12-12-22-33-15-881_app revanced android youtube~2](https://user-images.githubusercontent.com/22729896/207160045-11778560-9097-4003-980f-58b7af766af6.jpg)

### Additional context

my apk was build using: https://github.com/reisxd/revanced-builder
the apk name is `ReVanced-YouTube-v17.45.36-cli_v2.16.1-patches_v2.142.0.apk`
and this should be the list of patches that I used 
Youtube Patches
```
"disable-startup-shorts-player",
"remove-player-button-background",
"sponsorblock",
"return-youtube-dislike",
"theme",
"custom-branding",
"old-quality-layout",
"general-ads",
"video-ads",
"downloads",
"seekbar-tapping",
"settings",
"open-links-directly",
"microg-support",
"client-spoof",
"minimized-playback",
"custom-video-speed",
"remember-video-quality",
"hdr-auto-brightness"
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
#1020
