### ISSUE TITLE
YouTube crashes randomly while playing a video (Issue reopened)

### ISSUE THREAD

**Issue by HeroGalak** [revanced/revanced-patches#1259]
### Type

Error while patching

### Bug description

Issue already reported [here](https://github.com/revanced/revanced-patches/issues/1210)

### Steps to reproduce

//

### Relevant log output

```shell
//
```

### Screenshots or videos

//

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [ ] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
No steps to reproduce.
