### ISSUE TITLE
Add DMCA request form to this repo

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [revanced/revanced-patches#1263]
### Application

This repo

### Issue

A while ago someone used DMCA to takedown this repo. If this repo had a DMCA request form, I think they would try to use it first instead of filing the request directly to GitHub, taking down this repo quickly

### Patch

Add a DMCA request template in the issue section, then add a link to that template somewhere in the README 

Upon receiving such a request we should immediately take down the associated patch, mention in the README that the patch was removed by DMCA, and release that updated version within 3 days after the request was made

### Motivation

Make sure we have some time to react before this repo is banned by DMCA, causing a headache for many users

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
GitHub first sends a takedown notice to which 24H are given to react on. Instead of a form, a contact email should be added.
