### ISSUE TITLE
YouTube Queue

### ISSUE THREAD

**Issue by BrandgrandRealMe** [ReVanced/revanced-patches#1266]
### Application

YouTube

### Issue

The website has a Queue you can make but the app doesn't .

### Patch

Make a way to create a Queue in the app.

### Motivation

I miss having the queue when I am on mobile. It's a useful tool!

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Lamby777** [comment]
How is this relevant to the crowdfunding banner?

**Comment by oSumAtrIX** [comment]
It isn't, issues were transfered to another repo, breaking cross links.

**Comment by hyperYoko** [comment]
can you link the correct repo then?
