### ISSUE TITLE
feat(patch): add download button to playlists

### ISSUE THREAD

**Issue by soredake** [revanced/revanced-patches#1269]
### Application

YouTube

### Issue

Seal for example supports downloading playlists, so it will be convenient to have download button in playlists.

### Patch

Have download button in playlists.

### Motivation

It will save time for those who want to download playlist's.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Click on "share playlist", then share to seal.

**Comment by soredake** [comment]
@oSumAtrIX it requires me to press on share button, scroll (cause i can't pin seal to top in share menu) and then press again. Having button will simplify this to one press.
