### ISSUE TITLE
swipe-controls patch disables pinch to zoom to full extent

### ISSUE THREAD

**Issue by jonas-hurst** [revanced/revanced-patches#127]
I have noticed that the fenster-swipe-controls patch makes it impossible to pinch to zoom to full display extent.
I used patches release 2.9.4

**Reproduce:**
1. Use a phone that has a screen aspect ration > 16:9 (e.g. 18:9)
2. use fenster-swipe-controls patch
3. open a video with 16:9 aspect ratio
4. switch to full-screen view
5. pinch to view the video on the entire phone screen (without black areas left and right)

**Expected behaviour**
Video zooms to cover entire screen

**Actual behaviour**
Nothing happens

**Comment by shadow578** [comment]
will be fixed by https://github.com/revanced/revanced-integrations/pull/64
