### ISSUE TITLE
feat: youtube age restriction bypass

### ISSUE THREAD

**Issue by yonggamer** [ReVanced/revanced-patches#127]
### Feature description

A simple patch to bypass YouTube's age verification, disable content warnings and watch age restricted videos without having to sign in!

### Motivation

i want to access age-restricted videos from YouTube anonymously

### Acknowledgements

- [ ] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by fillwithjoy1** [comment]
uh #64 doesn't actually add any new features, so i dont get why this was closed. I'm voting for this to be re-opened

**Comment by oSumAtrIX** [comment]
Acknowledgements not met.

**Comment by fillwithjoy1** [comment]
> Acknowledgements not met.

dafuq, this is the earliest issue of age restriction. If there's an earlier issue of this please link to it.

**Comment by fillwithjoy1** [comment]
![image](https://github.com/ReVanced/revanced-patches/assets/29514446/55232d2b-5756-4476-a769-530c88c8c786)
What do you mean? The acknowledgement "its not a duplicate" cannot be met if I made an issue which by your standards would invalidate it. Therefore the earliest issue is then referenced to as to prevent a deadlock. Again as I said, if you can find an earlier issue of this age restriction bypass, I encourage you to link it and we can get this feature added.

**Comment by oSumAtrIX** [comment]
As I have previously explained multiple times now and been ignored, this issue does not meet the acknowledgements by being a duplicate. https://github.com/ReVanced/revanced-patches/issues/1516. This is my last warning to not polite our issues

**Comment by fillwithjoy1** [comment]
Now see this, how can anyone make a new issue about this as it's a duplicate of #127 and #1516. I don't understand why you feel the need to threaten anyone who wants to see change in something new

**Comment by oSumAtrIX** [comment]
@fillwithjoy1 Duplicate issues will be closed as part of the acknowledgements not being met.
