### ISSUE TITLE
feat(patch): Hide Shorts shelf in Homefeed indefinitely 

### ISSUE THREAD

**Issue by Xtremis77** [revanced/revanced-patches#1275]
### Application

YouTube

### Issue

Hide the Shorts shelf from the Homefeed.

### Patch

It is possible to hide this shelf for 30 days using a desktop browser. The idea is to have a patch to make this permanent (there is probably a check for this setting in the code, perhaps its just a matter of patching that check so the 30 days never expire). This could map to a setting that turns this on or off.

### Motivation

Some people don't like Shorts on their Homefeed, as they are distracting. This patch would be a good way to hide them permanently.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Already a feature.

**Comment by Xtremis77** [comment]
Thanks for the reply, would it be possible to give some more information? I activated both the Shorts related settings ("hide shorts" and "hide shorts button") and I still could see shorts in my Homefeed. Only after I disable them through a desktop browser they stopped showing. If it's supposed to be working with either of these two settings, for me it wasn't working. 
Thank you.

**Comment by Xtremis77** [comment]
> Already a feature.

Thanks for the reply, would it be possible to give some more information? I activated both the Shorts related settings ("hide shorts" and "hide shorts button") and I still could see shorts in my Homefeed. Only after I disable them through a desktop browser they stopped showing. If it's supposed to be working with either of these two settings, for me it wasn't working. 
Thank you.

**Comment by oSumAtrIX** [comment]
I can't say what you are doing wrong, sorry.

**Comment by Xtremis77** [comment]
> I can't say what you are doing wrong, sorry.

But if you say it's a feature, does it mean one of these settings should remove shorts from the Homefeed? I just want to understand what you mean, I'll troubleshooting from there. Thanks
