### ISSUE TITLE
swipe-controls takes too much control over brightness

### ISSUE THREAD

**Issue by jonas-hurst** [revanced/revanced-patches#128]
In my opinion, this patch overrides the system's brightness control way more than it should.
I used patches release 2.9.4

**Reproduce:**
1. use fenster-swipe-controls patch
2. open a video
3. switch to full-screen view -> Video starts playing with system's brightness setting
4. swipe upwards on left side of phone screen to change brightness -> overrides the system's brightness (as it should)

**Observed behaviour**
When exiting full screen, exiting the video, or even when exiting the app (with video continuing to play in popup window), brightness control is not given back to the system, brightness can only be changed when going back into a video on full screen and adjusting brightness via swiping.

Brightness control is only given back to the system when ReVanced is closed entirely, or when the popup-window with the video is closed.

**Expected behaviour**
Better behaviour would be to only override system brightness when the video is played in full screen, and give back brightness control to the system as soon as user exits fullscreen

**Comment by shadow578** [comment]
will be fixed by https://github.com/revanced/revanced-integrations/pull/64
