### ISSUE TITLE
bug: <Youtube Building issue>

### ISSUE THREAD

**Issue by Parsa307** [revanced/revanced-patches#1280]
### Type

Error while patching

### Bug description

Can't Bulid Youtube Revanced

### Steps to reproduce

step 1 use reisxd builder step 2 run the revanced builder step 3 revanced builder automatically download revanced cli and revanced-integrations and revanced patches and microg step 4 upload apk or click youtube to automatically download apk

### Relevant log output

```shell
i don't have log sorry please build youtube and see the error
```

### Solution

There It's No Solution

### Additional context

please fix this

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
reisxd builder is not from us, please open an issue in their repo.

**Comment by Parsa307** [comment]
> reisxd builder is not from us, please open an issue in their repo.

ok
