### ISSUE TITLE
feat(patch): (Youtube Revanced) Option to set which page Youtube Revanced opens when first opening the app

### ISSUE THREAD

**Issue by 32423d** [revanced/revanced-patches#1292]
### Application

Youtube Revanced 

### Issue

There is currently no way to set Youtube Revanced to open any other page other than the "Home" page when first opening the app.

### Patch

The feature I am requesting is for Youtube Revanced to have the option to set which page for it to open when you first open the app. For example, this option would allow users to set Youtube Revanced to first open the "Subscriptions" page instead of the "Home" page.

### Motivation

Quality of life changes for the application.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Implied by #1163.
