### ISSUE TITLE
Permanent Shuffle & Permanent Repeat (Discontinued Vanced YouTube Music feature)

### ISSUE THREAD

**Issue by hi-im-karma** [ReVanced/revanced-patches#1295]
### Application

YouTube Music Revanced Extended

### Issue

Permanent Shuffle and Permanent Repeat were features added by the Vanced team for the discontinued YouTube Music Vanced.

### Patch

Permanent Shuffle and Permanent Repeat were features added by the Vanced team for the discontinued YouTube Music Vanced. 

![Screenshot_20221217-221100183 (1)](https://user-images.githubusercontent.com/73917917/208269409-e3b9bb10-216b-4f2d-8f8d-1cc88d84da81.png)

![Screenshot_20221218-002227115 (1).png](https://user-images.githubusercontent.com/73917917/208269598-7d0576f9-c7f0-40b3-8935-2cce390f48d1.png)

You don't have to tap those icons over and over again, because it remembers with every new song/video you play even when closing the app or rebooting phone. I have YTM Vanced installed with German language so I don't know the exact English translation. But basically once taping any of those icons it would remember the next time you play a song/video in YTM Vanced.

### Motivation

Less taping those icons and therefore much more enjoyable YTM experience.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Bceez** [comment]
This has been implemented, This issue can be closed
