### ISSUE TITLE
Twitch crashing on startup with Android 13

### ISSUE THREAD

**Issue by Detlev1** [revanced/revanced-patches#1296]
### Type

Error at runtime

### Bug description

The twitch app crashes on startup. I am using Android 13 pixel experience but I have also seen the same issue on the discord with a pixel 7 pro running Android 13.

### Steps to reproduce

1. Patch the latest version of twitch
2. Install (root or normal doesn't matter)
3. Open and login
4. It loads normally for a split second and crashes

### Relevant log output

```shell
-
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by IoIxD** [comment]
The log that was not provided
https://media.discordapp.net/attachments/680549525902983194/1053818737767223365/Screenshot_20221217-163638.png

**Comment by oSumAtrIX** [comment]
This log has nothing to do with the exception.

**Comment by IoIxD** [comment]
well thats what i get upon launching the app, so i guess it crashes with no error.

**Comment by oSumAtrIX** [comment]
That is not possible.

**Comment by IoIxD** [comment]
![video](https://media.discordapp.net/attachments/680549525902983194/1053821504233668658/screen-20221217-1648322.mp4)

**Comment by IoIxD** [comment]
The patches work on the previous version of the app, indicating that the update on December 3rd broke things.

**Comment by IoIxD** [comment]
...nevermind, on the previous version of the app it launches but the app crashes upon entering a stream. Once again, no error.

**Comment by ybph** [comment]
Android 11 also crash too

**Comment by Poopooracoocoo** [comment]
On version 14.3.2 with block audio ads, block embedded ads and video ads, I see Twitch crash when opening a stream. The crash stops occuring  when I disable embedded ad blocking. I'm on Android 11 and patched it 20 minutes ago using RV Manager.

**Comment by Detlev1** [comment]
Could it be that twitch implemented some form of mechanism to block modified versions of the app. I tried to install Twitch mod a modified version of twitch having roughly the same features as the patches but basing on a much older version of twitch. In there I was blocked from signing in (update your android version) and the original twitch app didn't lauch anymore, even though this worked before and these are two separate apps that shouldn't be able to interact with each other. The crash the original app produced looked roughly like this but with the twitch logo replaced with an information emoji and crashing a split second after entering the app.

**Comment by oSumAtrIX** [comment]
@Detlev1 no

**Comment by xCryptic** [comment]
I get the same issue. but after unchecking "remove embedded ads" it stopped crashing, so that seems to be the cause

**Comment by Joshix-1** [comment]
The errors I get when I enable these options:
```
12-31 01:31:57.023 19149 19379 E AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
12-31 01:31:57.023 19149 19379 E AndroidRuntime: Process: tv.twitch.android.app, PID: 19149
12-31 01:31:57.023 19149 19379 E AndroidRuntime: java.lang.IllegalAccessError: Field 'kotlin.ranges.IntProgressionIterator.hasNext' is inaccessible to class 'app.revanced.twitch.adblock.TTVLolService' (declaration of 'app.revanced.twitch.adblock.TTVLolService' appears in base.apk!classes9.dex)
12-31 01:31:57.023 19149 19379 E AndroidRuntime: 	at app.revanced.twitch.adblock.TTVLolService.generateSessionId(TTVLolService.kt:35)
12-31 01:31:57.023 19149 19379 E AndroidRuntime: 	at app.revanced.twitch.adblock.TTVLolService.nextQuery(TTVLolService.kt:1)
12-31 01:31:57.023 19149 19379 E AndroidRuntime: 	at app.revanced.twitch.adblock.TTVLolService.rewriteHlsRequest(TTVLolService.kt:25)
12-31 01:31:57.023 19149 19379 E AndroidRuntime: 	at app.revanced.twitch.api.RequestInterceptor.intercept(RequestInterceptor.kt:99)
12-31 01:31:57.023 19149 19379 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
12-31 01:31:57.023 19149 19379 E AndroidRuntime: 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
12-31 01:31:57.023 19149 19379 E AndroidRuntime: 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
12-31 01:31:57.023 19149 19379 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-31 01:31:57.023 19149 19379 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-31 01:31:57.023 19149 19379 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:920)
```
```
12-31 01:32:57.423 20155 20444 E AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
12-31 01:32:57.423 20155 20444 E AndroidRuntime: Process: tv.twitch.android.app, PID: 20155
12-31 01:32:57.423 20155 20444 E AndroidRuntime: java.lang.IllegalAccessError: Illegal class access ('app.revanced.twitch.adblock.PurpleAdblockService' attempting to access 'kotlin.collections.MapsKt__MapsJVMKt') in attempt to invoke static method int kotlin.collections.MapsKt__MapsJVMKt.mapCapacity(int) (declaration of 'app.revanced.twitch.adblock.PurpleAdblockService' appears in base.apk!classes9.dex)
12-31 01:32:57.423 20155 20444 E AndroidRuntime: 	at app.revanced.twitch.adblock.PurpleAdblockService.<init>(PurpleAdblockService.kt:31)
12-31 01:32:57.423 20155 20444 E AndroidRuntime: 	at app.revanced.twitch.api.RequestInterceptor.updateActiveService(RequestInterceptor.kt:51)
12-31 01:32:57.423 20155 20444 E AndroidRuntime: 	at app.revanced.twitch.api.RequestInterceptor.intercept(RequestInterceptor.kt:88)
12-31 01:32:57.423 20155 20444 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
12-31 01:32:57.423 20155 20444 E AndroidRuntime: 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
12-31 01:32:57.423 20155 20444 E AndroidRuntime: 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
12-31 01:32:57.423 20155 20444 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-31 01:32:57.423 20155 20444 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-31 01:32:57.423 20155 20444 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:920)
```
