### ISSUE TITLE
Netflix

### ISSUE THREAD

**Issue by Fidannyan** [revanced/revanced-patches#1310]
### Application

Netflix

### Issue

The Netflix app needs a patch to run for free

### Patch

Run the Netflix app for free.

### Motivation

I watch a lot of movies on Netflix.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by reisxd** [comment]
Not everything is client-sided. Also, possible dupe.

**Comment by KazKaz90** [comment]
Use [CloudStream](https://github.com/recloudstream/cloudstream)

**Comment by SCP-017** [comment]
I hope this patch will be available soon...

**Comment by DananaBanana** [comment]
This is impossible, without a proper login you can't access any of the data on Netflix. You could try using an app such as CloudStream 3, pretty much every Netflix title will be there, alongside other streaming services.

**Comment by adarshsingh87** [comment]
There's a discussion section on the org page for suggestions and patch request.

**Comment by oSumAtrIX** [comment]
Server side limitation.

**Comment by Fidannyan** [comment]
What do you mean?
