### ISSUE TITLE
bug: YouTube error 'settings' failed to resolved ThemeSetterAppFingerprint

### ISSUE THREAD

**Issue by hyoretsu** [revanced/revanced-patches#1316]
### Type

Error while patching

### Bug description

revanced/revanced-manager#614

### Steps to reproduce

Try to patch latest YouTube version.

### Relevant log output

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Deleting existing resource cache directory
Decoding resources
Applied client-spoof
Applied custom-branding
Failed to apply custom-video-buffer: 'custom-video-buffer' depends on 'settings' but the following error was raised: Failed to resolve ThemeSetterAppFingerprint
Applied custom-video-speed
Failed to apply debugging: 'debugging' depends on 'settings' but the following error was raised: 'settings' did not succeed previously
Failed to apply disable-startup-shorts-player: 'disable-startup-shorts-player' depends on 'settings' but the following error was raised: 'settings' did not succeed previously
Failed to apply downloads: 'downloads' depends on 'downloads-resource-patch' but the following error was raised: 'downloads-resource-patch' depends on 'settings' but the following error was raised: 'settings' did not succeed previously
Failed to apply general-ads: 'general-ads' depends on 'GeneralAdsResourcePatch' but the following error was raised: 'GeneralAdsResourcePatch' depends on 'settings' but the following error was raised: 'settings' did not succeed previously
Failed to apply hdr-auto-brightness: 'hdr-auto-brightness' depends on 'settings' but the following error was raised: 'settings' did not succeed previously
Applied hide-my-mix
Failed to apply hide-watermark: 'hide-watermark' depends on 'settings' but the following error was raised: 'settings' did not succeed previously
Failed to apply open-links-directly: 'open-links-directly' depends on 'settings' but the following error was raised: 'settings' did not succeed previously
Applied predictive-back-gesture
Failed to apply premium-heading: The file /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-SMNXKW/cache/res/drawable-xxxhdpi/yt_premium_wordmark_header_light.png does not exist in the resources. Therefore, this patch can not succeed.
Failed to apply remember-video-quality: 'remember-video-quality' depends on 'settings' but the following error was raised: 'settings' did not succeed previously
Failed to apply return-youtube-dislike: 'return-youtube-dislike' depends on 'return-youtube-dislike-resource-patch' but the following error was raised: 'return-youtube-dislike-resource-patch' depends on 'settings' but the following error was raised: 'settings' did not succeed previously
Failed to apply settings: 'settings' did not succeed previously
Failed to apply sponsorblock: 'sponsorblock' depends on 'sponsorblock-resource-patch' but the following error was raised: 'sponsorblock-resource-patch' depends on 'settings' but the following error was raised: 'settings' did not succeed previously
Failed to apply video-ads: 'video-ads' depends on 'settings' but the following error was raised: 'settings' did not succeed previously
Repacking patched apk
Compiling resources
Writing modified dex files
Finished!
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by hyoretsu** [comment]
How do I fix that then? I'm using the latest version of ReVanced Manager (v0.0.52) and they said it wasn't related to it.

**Comment by hyoretsu** [comment]
I first installed it some 3 hours ago. I used "reset patches" and made sure the tag from "Select patches" was saying v2.146.0 (latest version). I saw the fix commit mentioned in the patch notes for this version, but the error still persists.

**Comment by mkujer** [comment]
> I first installed it some 3 hours ago. I used "reset patches" and made sure the tag from "Select patches" was saying v2.146.0 (latest version). I saw the fix commit mentioned in the patch notes for this version, but the error still persists.
> 
> I'll try from CLI to see if I also get it.

Hi, 
Hope you got it working yet.
The solution for me was to clear Cache/Dalvik
inside of TWRP Manager. The application seem to have been outdated even if re-installed many times.

**Comment by AndreiMiculita** [comment]
I installed the app in the past hour, for the first time ever. Still having this issue.

**Comment by B10Reaper** [comment]
So what's the solution? I keep getting my bug report closed and directed here, only to find no solution. I have no root for it to enable/disable, and uninstalling didn't help. Am I missing it?

**Comment by oSumAtrIX** [comment]
@B10Reaper #1332 is still open/your issue is a dupe.

**Comment by B10Reaper** [comment]
> @B10Reaper #1332 is still open/your issue is a dupe.

It says closed, is that not what that means? 

For some reason, patching the APK from apkmirror.com rarher than the app after installation goes just fine, no issues. I have no idea why, but there we go, if anyone else has issues.

**Comment by Ushie** [comment]
> It says closed

Yes, **this** issue is closed, because it is a duplicate

the original issue is #1332, you can move there
