### ISSUE TITLE
bug: Timeline ads still showing even after applying patch

### ISSUE THREAD

**Issue by Kalpataru6** [revanced/revanced-patches#1319]
### Type

Other

### Bug description

I tried to patch twitter and uses the latest version of twitter i.e 9.69 and still there is timeline ads.. So again I tried with 9.68 version thinking the older version will work but still timeline ads are showing.

### Steps to reproduce

Patch twitter with timeline-ads patch in both 9.69 version and 9.68 version.

### Relevant log output

```shell
I don't have
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
#352
