### ISSUE TITLE
Autogenerated list of patches for `README.md`

### ISSUE THREAD

**Issue by bogadana** [revanced/revanced-patches#132]
I intend to create a method which would generate a table like this one

|        Name        |                                       Description                                      | Latest supported version |
|:------------------:|:--------------------------------------------------------------------------------------:|:------------------------:|
| Microg support     | Patch to allow YouTube ReVanced to run without root and under a different package name | 17.25.34                 |
| Old quality layout | Enable the original quality flyout menu.                                               | 17.25.34                 |

But:
1. Where to put it?
2. How to run it? (gradle task?)
3. How to get information about the patches, PatchBundle class from patcher requires an existing jar file
4. Modifications to the table?

**Comment by oSumAtrIX** [comment]
1. The README should consist out of the standard sections of a heading, description, build instructions and meta such as your table. A good generator is [readme.so](https://readme.so). We will need to be consistent in the README across the organization.
2.  A gradle task can generate the new table on publish.
3. I am not sure yet.
4.
| 💊 Patch | 📜 Description | 🎯 Target package | 🏹 Target package version |
|:-:|:-:|:-:|:-:|
| Microg Support | Patch to allow YouTube ReVanced to run without root and under a different package name. | `com.google.android.youtube` | 17.25.34
| Old Quality Layout | Enable the original quality flyout menu. | `com.google.android.youtube` | 17.25.34

**Comment by jobhax25** [comment]
Would the wiki page be good for this? and the readme would send you to check out the page?

**Comment by oSumAtrIX** [comment]
The wiki page should not contain anything specific for a patch
