### ISSUE TITLE
feat(patch): Niagara Launcher Pro

### ISSUE THREAD

**Issue by K4Z3R0** [ReVanced/revanced-patches#1321]
### Application

[Niagara Launcher](https://play.google.com/store/apps/details?id=bitpit.launcher)

### Issue

Pro Lifetime

### Patch

Unlocks the Pro Lifetime

### Motivation

Without a doubt, the best launcher has a minimal yet stunning and sleek design, and it is incredibly efficient.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by venkat2305** [comment]
It would be great if someone work on this

**Comment by TroubleDog54** [comment]
This would be a great patch to add

**Comment by flame-0** [comment]
A patch to block these [trackers](https://i.imgur.com/x2CDh8A.png) too.

**Comment by TeaEndsAcronyms** [comment]
Hoping for this patch!

**Comment by oSumAtrIX** [comment]
Closing according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#%EF%B8%8F-guidelines-for-requesting-or-contributing-patches). Thanks anyways.
