### ISSUE TITLE
feat(patch): Block YouTube Premium ad buttom of music videos

### ISSUE THREAD

**Issue by MuhammetEminCakir** [revanced/revanced-patches#1348]
### Application

YouTube 

### Issue

YouTube Premium ad buttom of music videos

### Patch

Can you block YouTube Premium ad buttom of music videos. It's only appear music videos like this:
![IMG_20221222_211630](https://user-images.githubusercontent.com/64583157/209199968-60147ded-869d-428f-8061-e72ec7dcc612.jpg)

### Motivation

It is an annoying ad.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
> It is an annoying ad.

Not sure how it is annoying, I did not even notice it.
