### ISSUE TITLE
Skips videos automatically that are in playlist

### ISSUE THREAD

**Issue by Theo010110** [revanced/revanced-patches#1349]
### Type

Error at runtime

### Bug description

It happens whenever theres a video running that's included in a playlist. If I now want to start another video in the same playlist, the video gets skipped and then the next video gets skipped and so on. This results in a chain of skips where a video tries to load while getting skipped in the same second. 
If I close the video (or the process of loading the next video), wait a few seconds and then start a new video it works normaly. This only lasts for this one video though. Opening another video or finishing the video (where Youtube will then play the next video in the playlist) results in the same bug as before.

### Steps to reproduce

1. Open a video in a playlist
2. Try to open a different Video in the same playlist
3. "Skip-loop" should be happening
4. Close the video (or the process of loading the next video in the loop) and wait for a second
5. Tap a video and it should be playing normaly now

Environment: Samsung Galaxy s22 with Android 13 and OneUI 5.0, Revanced installed through the manager

### Relevant log output

```shell
N/A
```

### Additional context

I tried doing the same on the stock Youtube app with the same version as the revanved app and the bug wasn't there.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
#1206.
