### ISSUE TITLE
Seekbar disappears after switch to landscape and portrait

### ISSUE THREAD

**Issue by shivanshkverma** [revanced/revanced-patches#135]
https://user-images.githubusercontent.com/15206857/177997277-ded36c4a-9b4a-43e5-bb0b-4b854deed5ba.mp4

Patch v2.10.1
CLI: v2.3.2
Integrations: v0.21.8
Youtube: 17.25.34
Variant: Non-root
Used .apk (full, not extracted from .apkm)
Command used: java -jar revanced-cli.jar -a youtube.apk -m app-release-unsigned.apk -o revanced.apk -d DEVICENAME -b revanced-patches.jar -e premium-heading -e custom-branding -e fenster-swipe-controls -e disable-fullscreen-panels
Java: ZuluJDK 17

**Comment by TheJeterLP** [comment]
I cannot reproduce this.

**Comment by shivanshkverma** [comment]
> I cannot reproduce this.

Okay that's weird then, I can reproduce this every time I do this.

**Comment by TheJeterLP** [comment]
That is very weird. Can you try on a different device? It looks like you are using a modded android version

**Comment by TheJeterLP** [comment]
Also it looks kinda weird when the phone rotates because the video is not being put in Fullscreen mode. So that is probably an issue on your side
