### ISSUE TITLE
Application saturation

### ISSUE THREAD

**Issue by Fidannyan** [revanced/revanced-patches#1354]
### Application

ReVanced

### Issue

Option to increase App saturation for LCD screens.We can see videos and application more colorfully.

### Patch

Option to increase the saturation of the application.

### Motivation

People who use LCD will see Amoled.😍

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
The `theme` patch applies amoled by default.

**Comment by Fidannyan** [comment]
You did not understand me, I mean the color saturation of the application.

**Comment by oSumAtrIX** [comment]
Your motivation said

>People who use LCD will see Amoled

This is not how color works, the patch sets it to black, you can not saturate black to an even blacker black.
