### ISSUE TITLE
bug: Twitter ad blocker not working on newer twitter versions 

### ISSUE THREAD

**Issue by daveout** [revanced/revanced-patches#1361]
### Bug description

The ReVanced Manager's twitter patching page says the patch is recommended for *any* version. however latest twitter builds after patching end up corrupted and crashing. 

The latest twitter version that I tested and worked fine was v9.63.0-release.0

Solutions:
1) Update the AdBlock patch to work with newer versions
2) Meanwhile, set twitter "v9.63.0-release.0" as recommended version for patching in the manager instead of "any version".

(By the way thank you guys so much for all the work put on this amazing project.🤍)

**Comment by oSumAtrIX** [comment]
#1290

**Comment by daveout** [comment]
Notice how I:
1) Install the latest version
2) Patch it
3) Uninstall the stock version
4) Install patched version directly from the app then from the exported apk
5) The app crashes

Is it just me? Could it be my phone?
Im using Android 12 on Samsung M32

[Xrecorder Edited 24122022 161414.webm](https://user-images.githubusercontent.com/54579499/209454229-bdca491b-a31f-440e-a1ef-227986637b70.webm)

**Comment by oSumAtrIX** [comment]
Its a duplicate.

**Comment by daveout** [comment]
Im not sure. The person on the other thread is able to run the app and log in. I'm unable to do that.

**Comment by oSumAtrIX** [comment]
You are using a split apk file which is offtopic to #1361.

**Comment by daveout** [comment]
Oh I see.  So the problem was downloading Twitter from the Google Play Store, is that it? I downloaded the latest apk from another source and it worked.
