### ISSUE TITLE
bug: <title> twitch newest patch crash

### ISSUE THREAD

**Issue by kevin01523** [revanced/revanced-patches#1364]
### Type

Error at runtime

### Bug description

Twitch ttv lol new patch just crashes the twitch app as i click on any Livestream that i follow also the AdBlock doesn't work anymore or at least barely works.

### Steps to reproduce

Log in. Click any live stream
App closes/crash

### Relevant log output

```shell
N/A
```

### Additional context

P. S. The newer patch is is the only one causing a crash tested on two different devices and both crash. Also tried that i only enable that single patch 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
#1296
