### ISSUE TITLE
Twitch crashing for block embedded patch

### ISSUE THREAD

**Issue by Senkix1** [revanced/revanced-patches#1368]
### Type

Error at runtime

### Bug description

The Twitch app crashes when opening a livestream while the option "block embedded video ads" is enabled.
*It doesn't happen in offline streams*

### Steps to reproduce

1. Go to settings and select the block embedded video ads
2. Enable any of the two options (TTV LOL PROXY Or PurpleAdBlock proxy)
3. Try to enter to any livestream

### Relevant log output

```shell
...
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
#1296
