### ISSUE TITLE
feat(patch): Remember video playback speed

### ISSUE THREAD

**Issue by yantingLiu** [revanced/revanced-patches#1374]
### Application

Youtube

### Issue

Remember the video playback speed

### Patch

Added option to remember video playback speed

### Motivation

 I am used to playing videos at 2x speed. Every time I open a video, I need to manually adjust it, which is inconvenient

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
#811
