### ISSUE TITLE
feat(patch): Separate the functions of the Headphone and X buttons in the PiP player

### ISSUE THREAD

**Issue by Kobewaxman** [revanced/revanced-patches#1376]
### Application

YouTube ReVanced 

### Issue

If background playback is set to "Headphones or external speaker" then if you are using PiP mode and press the headphone button it does not continue playing in the background. Rather, it closes the video just as if you were to press the X button. 
(And although users can partially hide the PiP player by shoving into the side of the screen it still is annoying and it doesn't continue backround playback when the screen is turned off.)

And if backround playback is set to "Always on" then pressing the X button only hides the PiP but it does not close the video, which is what the headphone button should be for.

### Patch

A patch that separates the functions of the X and headphone buttons in the PiP player, regardless of whether you have backround playback set to "Always on", "Headphones or external speakers", or "Off".

The X button in the PiP player will pause and close the video. The headphone button in the PiP player will hide the video but allow it to continue playing in the background.

### Motivation

With this patch users can seamlessly choose whether to have the video continue playing in the backround without needing to go into settings to change their preferences.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Can you record the issue? I do not quite get what the problem is. Pressing `X` or the headphones icon in the PiP floating window works as expected.

**Comment by Kobewaxman** [comment]
I apologize, it does work as intended when Backround playback is set to "Always on" (as you likely experienced in your test).

However the issue remains when it is set to "Headphones or external speakers", or when set to "Off".

The patch (or perhaps bug fix) would make it so that the buttons in the PiP player always work like they do when Background playback is set to "Always on".

I'm new to github and it doesn't seem to let me add the 30 second screen recording so here is a link to the video on my google drive. https://drive.google.com/file/d/12CTZSiLCDLpD74NfHlDLvpkmonxRQft6/view?usp=drivesdk

**Comment by ILoveOpenSourceApplications** [comment]
Are you still facing this issue  @Kobewaxman ?

**Comment by Kobewaxman** [comment]
> Are you still facing this issue  @Kobewaxman ?

@ILoveOpenSourceApplications 
I have switched to Revanced Extended for a long while. I haven't used the based Revanced since then so I don't know.
