### ISSUE TITLE
feat(youtube/theme): color splash screen with background color

### ISSUE THREAD

**Issue by ghost** [revanced/revanced-patches#1377]
### Application

This patch makes possible to change the color of the splash screen to match the chosen custom color.

### Issue

It is currently not possible to apply custom colors to the splash screen.

### Patch

To apply the patch you need to follow these 4 steps:

1) Add the following new line in the file ```attrs.xml```:
    - ```<attr name="splashScreenColor" format="color" />``` 

2) Add the following new lines in the file ```/values/style.xml```:
    - ```<item name="splashScreenColor">@color/yt_black1</item>```  --->  after the line ```<style name="Base.Theme.YouTube.Launcher.Dark" parent="@style/Base.Theme.YouTube.Launcher">```
    - ```<item name="splashScreenColor">@color/yt_white1</item>```  --->  after the line ```<style name="Base.Theme.YouTube.Launcher.Light" parent="@style/Base.Theme.YouTube.Launcher">```

3) Add the following new line in the file ```/values-v31/style.xml```:
    - ```<item name="android:windowSplashScreenBackground">?attr/splashScreenColor</item>```  --->  after the line ```<style name="Base.Theme.YouTube.Launcher" parent="@style/Theme.AppCompat.DayNight.NoActionBar">```

4) Replace the following line in the files ```/drawable/quantum_launchscreen_youtube.xml``` and ```/drawable-sw600dp/quantum_launchscreen_youtube.xml```:
    - ```<item android:drawable="?android:colorBackground" />``` with ```<item android:drawable="?attr/splashScreenColor" />```

### Motivation

This patch is an improvement on the currently existing ```Theme``` patch.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by 0xrxL** [comment]
@LisoUseInAIKyrios I saw some changes related to XML resources on your PRs.

Do you think you can implement this correctly? I had some trouble with my PR.

**Comment by LisoUseInAIKyrios** [comment]
If I get some time I might look at it.  I don't have an Android 11/12 device to try on, but I could use the android simulator.

**Comment by 0xrxL** [comment]
> If I get some time I might look at it. I don't have an Android 11/12 device to try on, but I could use the android simulator.

It's an already done and tested patch 
so you don't strictly need an emulator.

You just ensure to follow the above described steps. 👍

P.S: Thanks for answer anyway.

**Comment by ILoveOpenSourceApplications** [comment]
Why is this labelled as a bug? Shouldn't it be a patch-request/feature -request?

**Comment by oSumAtrIX** [comment]
Yes, it is staged in dev.
