### ISSUE TITLE
feat(patch): Set default brightness for all videos

### ISSUE THREAD

**Issue by GasparGT11** [revanced/revanced-patches#1379]
### Application

YouTube Revanced

### Issue

Everytime I see a video I have to increase the brightness manually.

### Patch

It would be great if we have an option to set a default percentage of brightness, just like resolution and speed.

### Motivation

Some devices tend to lower the brightness of the videos for "safety". I'm pretty sure this is a problem that lots of people has.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Simply change the brightness of your phone.
