### ISSUE TITLE
YouTube Playlist Autoskipping

### ISSUE THREAD

**Issue by HunterAPI** [revanced/revanced-patches#1383]
### Type

Error at runtime

### Bug description

Playlists start skipping to the next video in the post randomly and stop after a random amount of skips.

### Steps to reproduce

Click on a playlist and skip through it.

### Relevant log output

```shell
I'm not sure what to put here.
```

### Screenshots or videos

![Screenshot_20221228_150059](https://user-images.githubusercontent.com/70922563/209866069-bf58a269-5abb-4dd5-8344-0acd8a4c7e17.png)

### Solution

Couldn't find any solution. But you can sometimes close the player and select the video for the playlist you wanna watch and it might work.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
#1206

**Comment by HunterAPI** [comment]
> #1206

Thanks

**Comment by Sunny-Shani** [comment]
Is this problem solved now?

**Comment by Ushie** [comment]
https://github.com/revanced/revanced-patches/issues/1206#issuecomment-1337291187

**Comment by Sunny-Shani** [comment]
> [#1206 (comment)](https://github.com/revanced/revanced-patches/issues/1206#issuecomment-1337291187)

Thanks
