### ISSUE TITLE
feat(patch): 

### ISSUE THREAD

**Issue by ExpertNugget** [revanced/revanced-patches#1386]
### Application

com.google.android.youtube

### Issue

Skip non music segments

### Patch

sponsorblock addition to block non-music segments 

### Motivation

saves people from the (in my opinion) the worst thing about youtube music over other music platforms, the "official video" having non music segments that if your only listening are rather annoying

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [ ] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by NeeRaj-2401** [comment]
Already exists

![Screenshot_2022-12-29-17-52-38-69_d11ae654701a5fadb313ea6fa9a6836f](https://user-images.githubusercontent.com/88180887/209950638-baa6cd9d-a998-4ad7-9090-a9c28e69aaca.jpg)

**Comment by ExpertNugget** [comment]
Sorry I meant to put this for youtube music not standard youtube
