### ISSUE TITLE
feat(patch): 

### ISSUE THREAD

**Issue by ExpertNugget** [revanced/revanced-patches#1390]
### Application

com.google.android.apps.youtube.music

### Issue

Skip non music segments

### Patch

sponsorblock addition to block non-music segments 

### Motivation

saves people from the (in my opinion) the worst thing about youtube music over other music platforms, the "official video" having non music segments that if your only listening are rather annoying

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [x] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
There is no SponsorBlock patch for YouTube Music. Also acknowledgements not met.

**Comment by ExpertNugget** [comment]
That's why I want a patch for it??? Isn't this what this thing is for

**Comment by ExpertNugget** [comment]
Ima just make another issue if
