### ISSUE TITLE
feat(patch): Disable title auto translation 

### ISSUE THREAD

**Issue by MrEd88** [revanced/revanced-patches#1392]
### Application

Youtube

### Issue

Sometimes YouTube decides to autotranslate video titles even when you have dual languages configured in your account. 

### Patch

Add an option to disable automatic translation of titles.  

### Motivation

No workaround available and it has been an issue for long time. Hope this could be possible.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by SodaWithoutSparkles** [comment]
This is quite useful, especially when YT translation sucks and the translated title is not even a valid sentence. How did I know? I translated the badly translated sentence back to english word for word.

**Comment by Animan8000** [comment]
I would like to see this feature too. It's annoying to see poorly auto-translated titles and descriptions even tho you wanna read stuff in English.

**Comment by oSumAtrIX** [comment]
#874

**Comment by SodaWithoutSparkles** [comment]
@oSumAtrIX maybe closing as not planned? It is duplicate of another issue, but it has not been solved yet

**Comment by oSumAtrIX** [comment]
Not planned != duplicate. See [this](https://github.com/revanced/revanced-patches/issues/1851#issuecomment-1496493993)

**Comment by SodaWithoutSparkles** [comment]
> Not planned != duplicate. See [this](https://github.com/revanced/revanced-patches/issues/1851#issuecomment-1496493993)

You can use the keyword "Duplicate of" to mark as duplicate

![Screenshot_2023-04-05-21-52-09-387_com.github.android-edit.jpg](https://user-images.githubusercontent.com/64138578/230101566-e84f4b96-85ba-4a83-a3f8-3f9f9323eef8.jpg)

**Comment by oSumAtrIX** [comment]
Still doesn't make it not planned. I disagree with GitHub's choice of words here.

**Comment by SodaWithoutSparkles** [comment]
> Still doesn't make it not planned. I disagree with GitHub's choice of words here.

But thats the standard. I think the best practice would be closing as not planned with a comment of "Duplicate of ____". Thats what the button supposed to mean.

**Comment by oSumAtrIX** [comment]
I disagree with the standard, then. GitHub's choice of words here is unfitting.
