### ISSUE TITLE
feat(patch): Bring back the sort from oldest option

### ISSUE THREAD

**Issue by Th3V1son** [revanced/revanced-patches#1393]
### Application

YouTube

### Issue

YouTube in their new design decided to remove the option to sort videos from oldest to newest.

### Patch

Add a button to sort the videos from oldest to newest as the old drop down style won't really fit the new design.

### Motivation

If you simply search "youtube sort from oldest" in Google you can find many people being frustrated about this design change.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
#1200
