### ISSUE TITLE
feat(patch): Automatic voice translation from Yandex

### ISSUE THREAD

**Issue by dansoftware** [revanced/revanced-patches#1398]
### Application

YouTube ReVanced

### Issue

Automatic voice translation to Russian language from Yandex: https://github.com/ilyhalight/voice-over-translation

### Patch

A button during playback to enable the automatic voice translation.

### Motivation

Russian speaking users will have an ability to watch videos on foreign languages that do not have Russian audio track or subtitles.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Multiple voice tracks is gonna come to YouTube natively.

**Comment by dansoftware** [comment]
This is not about the multiple voice tracks but about translation of an audio from multiple languages to Russian on fly. This is an automatic synchronous translation based on a neural network.

**Comment by oSumAtrIX** [comment]
Such a thing does not even exist to begin with, let alone synced to time. Audio tracks is your best bet

**Comment by dansoftware** [comment]
This thing do exist really. There are multiple plugins with open source code for multiple web browsers. You can find an appropriate link in my original message. They use an API to communicate with the neural network for automatic synchronous translation.

**Comment by oSumAtrIX** [comment]
Then this should be implemented as a seperate system wide application and not just Youtube

**Comment by dansoftware** [comment]
May be. But the neural network was created for automatic synchronous translation of YouTube first of all. And it does it quite well.
