### ISSUE TITLE
bug: Failed to apply (patch): '(patch)' depends on 'settings', but the following error was raised: 'settings' did not succed previously

### ISSUE THREAD

**Issue by GoboSnack** [revanced/revanced-patches#1406]
### Type

Error while patching

### Bug description

Certain patches (ex. 'general-ads') will not work and report "Failed to apply (patch): '(patch)' depends on 'settings', but the following error was raised: 'settings' did not succeed previously". There is not 'settings' patch available. No root

### Steps to reproduce

Step 1. Select patches (ex. 'general-ads')
Step 2.  Tap 'Patch'
Step 3. Error will show in log

### Relevant log output

```shell
Failed to apply 'video-ads': 'video-ads' depends on 'settings' but the following error was raised: 'settings' did not succeed previously
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
#1332.
