### ISSUE TITLE
Removal of navigation panel (HOME LIBRARY etc) while watching SHORTS 

### ISSUE THREAD

**Issue by AanooBeta** [revanced/revanced-patches#1418]
### Application

YouTube revanced 

### Issue

It's not useful like Alot but I think it makes shorts user interface exquisite. Basically removal of this:
![Screenshot_20230102-151041](https://user-images.githubusercontent.com/108539997/210218797-f7dfd85e-614a-468c-82b3-9efa327816b6.jpg)

### Patch

Removal of navigation panel as you saw above I don't see anyone using it. Mostly people just use back gesture or click on back button seeing this annoying navigation thing is irritating I think it shouldn't be that hard and it might make watching shorts experience a bit better

### Motivation

People are gonna try this and love it for real after removing it. It looks like this:
![Screenshot_20221224-193202](https://user-images.githubusercontent.com/108539997/210219060-2866afef-5c3d-45b3-9f1b-de4c8e67f817.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by ILoveOpenSourceApplications** [comment]
#694
