### ISSUE TITLE
feat: reddit app: open links in external browser

### ISSUE THREAD

**Issue by abunasar** [ReVanced/revanced-patches#142]
### Feature description

Links should open in external browser on phone such as firefox/Google etc.

Reddit forcefully removed this feature for better tracking and also removed the sharing button. E.g when you click on an article link, it opens within reddit browser and there is no way to share that article or copy it's url.

### Motivation

Because if you like to share a news or an article url with someone there is no way to do it, reddit also removed the sharing button.

### Acknowledgements

- [ ] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by abunasar** [comment]
> https://github.com/ReVanced/revanced-patches-template/issues/1180

How is that issue in any way related to the request I submitted?

**Comment by oSumAtrIX** [comment]
https://github.com/ReVanced/revanced-patches/issues/1180
