### ISSUE TITLE
bug: <Ads appear in YouTube search results>

### ISSUE THREAD

**Issue by DotPixel0** [revanced/revanced-patches#1425]
### Type

Error at runtime

### Bug description

came up when i searched on youtube
Unrelated but it didn't appear in ReVancedExtended

### Steps to reproduce

Search on YouTube and display results

### Relevant log output

```shell
I'm sorry
there is no log
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [ ] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Reproduction steps insufficient
