### ISSUE TITLE
Disable PIP in YouTube Shorts Page

### ISSUE THREAD

**Issue by thisisshihan** [revanced/revanced-patches#1426]
### Application

YouTube

### Issue

Unusable YouTube Shorts PIP
![Screenshot_20230104_181722_One UI Home](https://user-images.githubusercontent.com/38727829/210535475-b15286a6-1d0a-44e0-9eb3-fad1a6bbcc65.jpg)

### Patch

When going from YouTube Shorts page to home screen it trigger PIP for Shorts but it won't work please make a patch to disable this.

### Motivation

It will solve the problem of tapping close button on YouTube Shorts PIP

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by SodaWithoutSparkles** [comment]
https://github.com/revanced/revanced-integrations/commit/1dd84a37851359143140d1d1df664c3eab680fa7

**Comment by ILoveOpenSourceApplications** [comment]
> [revanced/revanced-integrations@1dd84a3](https://github.com/revanced/revanced-integrations/commit/1dd84a37851359143140d1d1df664c3eab680fa7)

But if we disable minimised playback, wouldn't we lose pip for normal yt videos as well. Which isn't optimal of a solution is it now? Correct me if I'm wrong.

**Comment by oSumAtrIX** [comment]
PiP is only disabled for shorts.

**Comment by ILoveOpenSourceApplications** [comment]
> PiP is only disabled for shorts.

But that's not the result I'm getting. If I have minimized playback on, I have the old shorts pip. If I turn it off, I lose pip entirely. That's why the initial question.

**Comment by SodaWithoutSparkles** [comment]
@oSumAtrIX seems like there's a typo in the comments of commit 1dd84a3 mentioned above. In PlayerTyoe.kt line 54, did you mean **whether** instead of _weather_?

**Comment by ILoveOpenSourceApplications** [comment]
> @oSumAtrIX seems like there's a typo in the comments of commit 1dd84a3 mentioned above. In PlayerTyoe.kt line 54, did you mean **whether** instead of _weather_?

It's already mentioned in [1dd84a3](https://github.com/revanced/revanced-integrations/commit/1dd84a37851359143140d1d1df664c3eab680fa7). Btw, @SodaWithoutSparkles are you not having this issue?

**Comment by oSumAtrIX** [comment]
> > PiP is only disabled for shorts.
> 
> But that's not the result I'm getting. If I have minimized playback on, I have the old shorts pip. If I turn it off, I lose pip entirely. That's why the initial question.

I don't know what you mean, PiP is disabled for shorts like in normal YT but enabled for normal videos

**Comment by ILoveOpenSourceApplications** [comment]
> I don't know what you mean, PiP is disabled for shorts like in normal YT but enabled for normal videos

![IMG-20230228-WA0001](https://user-images.githubusercontent.com/117499019/221930727-e38c3444-a046-48ef-827d-c639c77bea44.jpg)
How it is currently.

**Comment by ILoveOpenSourceApplications** [comment]
> Try closing ReVanced, and restarting it fresh. Then open a Short, and switch apps. The short should stop playing, and it should not appear minimized as seen in the screenshot.

Okay this is working. But that's a workaround and not how this should be functioning. If we minimize the app when playing a shorts, the app shouldn't go into pip at all but that isn't the case here. Currently it's either stop playing the short but stays as a pip or it's like how it used to be, which is playing a shorts as pip with all the buttons.
