### ISSUE TITLE
feat(patch): YouTube for Android TV

### ISSUE THREAD

**Issue by DotPixel0** [revanced/revanced-patches#1428]
### Application

YouTube for Android TV
https://play.google.com/store/apps/details?id=com.google.android.youtube.tv

### Issue

Features like YouTube ReVanced
( especially removing ads )

### Patch

sorry
I'm using a translation tool
I do not know the meaning, so I leave it blank

### Motivation

Because SmartTube･SmartTubeNext doesn't look good
Because SmartTube･SmartTubeNext does not respond appropriately

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
#559

**Comment by oSumAtrIX** [comment]
Your motivation should go towards SmartTubeNext.

**Comment by beevk** [comment]
While SmartTubeNext is nice, it has a completely different UI and the recommendations are not similar (at least not for me). So supporting Youtube TV as well would be awesome in my view.

**Comment by reisxd** [comment]
> While SmartTubeNext is nice, it has a completely different UI and the recommendations are not similar (at least not for me). So supporting Youtube TV as well would be awesome in my view.

YouTube TV is not the same as patching a normal app. YT ATV is just a web application and it uses Cobalt which is a Chromium fork and is optimized for lower end devices and Cobalt does not have injecting code.

**Comment by oSumAtrIX** [comment]
@beevk In that case suggest a better UI for SmartTubeNext in their repo.

**Comment by venkat2305** [comment]
> > While SmartTubeNext is nice, it has a completely different UI and the recommendations are not similar (at least not for me). So supporting Youtube TV as well would be awesome in my view.
> 
> YouTube TV is not the same as patching a normal app. YT ATV is just a web application and it uses Cobalt which is a Chromium fork and is optimized for lower end devices and Cobalt does not have injecting code.

Asking this out of curiosity, how did you know it was implemented like that in YouTube TV.

**Comment by oSumAtrIX** [comment]
By reversing the app.
