### ISSUE TITLE
feat(patch): Option to set default initial view when launching the app

### ISSUE THREAD

**Issue by diegonogaretti** [revanced/revanced-patches#1429]
### Application

YouTube

### Issue

Set a default initial view when launching the app

### Patch

Allow user to set a default initial view when launching the app like setting it to the subscriptions tab instead of the home tab for example

### Motivation

I think we spend most of the time in the subscriptions tab or searching a specific video

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
#1284
