### ISSUE TITLE
bug: Back button doesn't minimize video

### ISSUE THREAD

**Issue by asdsadsaasd12312132** [revanced/revanced-patches#1435]
### Type

Error at runtime

### Bug description

When I am in fullscreen, the back button does not minimize the video. The back button does nothing.

### Steps to reproduce

Go fullscreen on a video and press back

### Relevant log output

```shell
Don't have
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Disable patches until the error is gone & try on the unpatched app

**Comment by Domiiniik** [comment]
Can confirm the issue, if you quit the app within the use of back button PIP mode won't trigger like (it should?) AND like it does with home button. >(Somebody with premium acc and an unpatched YT app needs to check how it works there)<

**Comment by asdsadsaasd12312132** [comment]
I realized it was because Youtube changed the behaviour of the back button to exit fullscreen by rotating the screen to portrait mode and it was doing nothing for me because I locked my phone in landscape mode. The back button used to minimize the video to the bottom right of the screen. Is it possible to get this behaviour again?

**Comment by oSumAtrIX** [comment]
Seems like it isn't an issue with ReVanced then.
