### ISSUE TITLE
feat(patch): Hiding ads, blaze post, and sponsored post on the Tumblr

### ISSUE THREAD

**Issue by LadyHaywood** [ReVanced/revanced-patches#1437]
### Application

[Tumblr app](https://play.google.com/store/apps/details?id=com.tumblr&hl=en_US&gl=US&pli=1)

### Issue

The way tumblr have added different types of ads to their app is getting annoying. It seems like there are 4 types of post that will be forced on the dash as well as regular ads showing up more than actual post.

### Patch

Hide ads
Hide blaze post
Hide sponsored post
Hide sponsored header

### Motivation

The other tumblr clients on android aren't very good, updated, or they work mostly as a viewer. I miss actually seeing content and reblogs from people I follow.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by starchyunderscore** [comment]
+1, I haven't found any tumblr clients that are actually useable so far. I would also like to see a video downloading patch if possible.

**Comment by pixiekat** [comment]
I don't know if this would be considered out of scope or what not, but it would be nice to integrate a bit of [Xkit ](https://github.com/AprilSylph/XKit-Rewritten) into a Revanced patch to include the functionality in the app too:.

**Comment by oSumAtrIX** [comment]
Open issues for every one of the requests.
