### ISSUE TITLE
fix: display codename for patch names

### ISSUE THREAD

**Issue by oSumAtrIX** [revanced/revanced-patches#144]
# 🐞 Issue

Currently, the `README` shows a display name for the patches. 

# ❗ Solution

Instead, the code name should be used.  Proposal:

---

### List of patches

| 💊 Codename | 📜 Description | 🎯 Target Package | 🏹 Target Version |
|:--------:|:--------------:|:-----------------:|:-----------------:|
|`code-name`|Short but descriptiive description about the patch.|`package.name`| 00.00.00 |

---

# ❓ Motivation

Displaying the formatted name leaves the user with no option to know which code name to use when required.

# ⚠ Additional context

The proposal will get rid of the display name decreasing user friendliness.

**Comment by Sculas** [comment]
I suppose this is alright for now. But your statement
> The proposal will get rid of the display name decreasing user friendliness.

is very wrong. We need a `@DisplayName("...")` annotation for user-friendly names. The current approach is wrong.

**Comment by oSumAtrIX** [comment]
User friendly names can be generated from the code names by getting rid of the `-` and casing the first character.

**Comment by Sculas** [comment]
That is the wrong approach as I just said.

**Comment by oSumAtrIX** [comment]
Please open an issue on the `patcher` repository
