### ISSUE TITLE
Revanced crash exiting - investigating

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [revanced/revanced-patches#1443]
### Type

Error at runtime

### Bug description

Revanced crashed exited with patch 2.153.0

### Steps to reproduce

1. Patch YT 17.49.37 with patches 2.153.0, latest manager
2. Install the app, it works normally
3. Play a video, it works normally
4. In sponsorblock settings, enter a string of character as your private ID
5. Exit revanced, kill it in settings
6. Open revanced again, notice that it flashed and exited

### Relevant log output

```shell
N/A
```

### Solution

Revert to last version...? I suppose its commit https://github.com/revanced/revanced-patches/commit/cde45fca769eddea64072f13f836d46560a4a89a or https://github.com/revanced/revanced-patches/commit/9bd42ec1a1b54b103cd2550211515acdaf90e9de as it still crashed even if I disabled `remember-playback-rate`

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by SodaWithoutSparkles** [comment]
This issue affects everyone that has the SB private ID set in previous versions and updated to patch 2.153.0. This would result in the app not being able to open at all, so you cannot delete the private ID. You will have to clear all of revanced youtube data

**Comment by oSumAtrIX** [comment]
Exclude step 4, check again.

**Comment by SodaWithoutSparkles** [comment]
Theres still a issue. Step 4 is not significant

**Comment by SodaWithoutSparkles** [comment]
Is there a way we can pin versions? I want to revert to version 2.152.0

**Comment by SodaWithoutSparkles** [comment]
I am trying to patch without remember-quality-patch. Will update accordingly

**Comment by SodaWithoutSparkles** [comment]
Update: simplified steps: delete step 4, remember video quality and remember playback rate are not significant, it would crash with or without them

**Comment by SodaWithoutSparkles** [comment]
Now trying to patch without remember quality, rate and without SB

**Comment by oSumAtrIX** [comment]
I have found the issue, please wait until its fixed.

**Comment by SodaWithoutSparkles** [comment]
What's the issue?
-----
New findings: With all 3 patches removed it was fine. I found out that I accidentally patched the last exported apk. Will test again

**Comment by SodaWithoutSparkles** [comment]
Will try using experimental mode to use new integration

**Comment by SodaWithoutSparkles** [comment]
@oSumAtrIX it seems that the patch failed to build

**Comment by webzeroacs** [comment]
The problem still occurs.

**Comment by SodaWithoutSparkles** [comment]
@oSumAtrIX please re-open this issue. The problem is not fixed yet

**Comment by oSumAtrIX** [comment]
Open a new issue, include logs.

**Comment by SodaWithoutSparkles** [comment]
How to collect said logs?

**Comment by SodaWithoutSparkles** [comment]
@oSumAtrIX #1444

**Comment by SodaWithoutSparkles** [comment]
Solution found in #1444
