### ISSUE TITLE
feat(patch): (Youtube) Toggle to enable/Disable Auto brightness for Swipe Gestures

### ISSUE THREAD

**Issue by fedonr** [ReVanced/revanced-patches#1445]
### Application

I would like to make a suggestion for a patch to get a toggle in Settings > Swipe Gestures (Youtube) to allow user to disable the Auto Brightness in Swipe gesture.

### Issue

For people like use who stream videos in dark, swiping down takes us to Auto instead of making it 0. That's the one of core reason we use Revanced Extended. So if that can be implemented Revanced would be my default goto.

### Patch

A toggle in Settings to Enable/Disable Auto Brightness in Swipe Gestures.

### Motivation

It's more about the comfort for people streaming vidoes in Dark

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by pmsobrado** [comment]
Any updates on this? Will it be implemented? Or is it not going to happen?

Thanks.

**Comment by NicolasPL64** [comment]
Still wondering the same. It's such an easy implementation but we're not getting any feedback
