### ISSUE TITLE
bug: "Your Data in YouTube" does not show the corresponding overview

### ISSUE THREAD

**Issue by akn01** [revanced/revanced-patches#1446]
### Type

Other

### Bug description

When I click on "Your Data in YouTube" in the settings, only the settings menu minimizes without opening the corresponding overview.

Reinstalling MicroG and Revanced did not bring any success. Also I was not able to change the selection I made (open with "Google Settings"). Maybe "open with MicroG" would have worked? Where could this be changed again?

Everything works fine in the original app.

### Steps to reproduce

I had previously installed the latest version 17.49.37 and went to "Your Data in YouTube". As far as I remember, a selection dialog then appeared asking which app to continue with. On the left side it said something about "Google Settings" and on the right side something about "MircoG". I had selected "Google Settings" and since then nothing happens when I select "Your Data in Youtube" or even "Help and Feedback" in the settings menu.

### Relevant log output

```shell
none
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
https://user-images.githubusercontent.com/13122796/211156169-888cb24b-1c52-407b-955b-ce448cc5e380.mp4

**Comment by akn01** [comment]
> Record_2023-01-07-15-38-35.mp4

I can't see any information here.
