### ISSUE TITLE
YouTube Music: Android Auto Blocked

### ISSUE THREAD

**Issue by Spark-NV** [revanced/revanced-patches#1451]
### Type

Error at runtime

### Bug description

Android Auto GUI is blocked and just says " Upgrade to music premium to access this feature"

Using the phone to select a track works and plays threw the vehicle headunit and/or can use voice assistant to tell it to play a track but no selection is available in the car.

### Steps to reproduce

Install YouTube Music 5.36.51
Patch apk using manager app
Connect phone to car
Select YouTube Music inside Android Auto.

### Relevant log output

```shell
Not sure what logs would be useful here as this seems to be a bug that needs a special patch created for?
```

### Screenshots or videos

![IMG20230107222811](https://user-images.githubusercontent.com/38028193/211182034-e18300fa-bd38-4a3f-9d9a-78c2bc889e9c.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
#619
