### ISSUE TITLE
feat: Youtube Nonstop

### ISSUE THREAD

**Issue by Yusei-StarDust** [ReVanced/revanced-patches#146]
### Feature description

auto skip the pop-up notification "Video paused. Continue watching?"  like the namesake chrome extension.

### Motivation

the notification will interrupt the video play and it is really annoying. I think this feature will strongly enhance the user experience.

### Acknowledgements

- [ ] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by erikk333** [comment]
Force enable auto captions is not the same issue as video paused continue watching

**Comment by hack3rmann** [comment]
There's no good reason to mark this feature as "not planned".

This prompt (also known as "Video paused. Continue watching?") is extremely annoying. It also appears in the music app for some reason. The music stops every 15-30 minutes when the player is open.

I really think this feature is worth implementing.
