### ISSUE TITLE
Unlock Photomath plus features

### ISSUE THREAD

**Issue by HeroGalak** [revanced/revanced-patches#1461]
### Application

[Photomath](https://play.google.com/store/apps/details?id=com.microblink.photomath) 

### Issue

Unlock Photomath plus features

### Patch

The patch should unlock in-depth explanations and animated tutorials.

### Motivation

Photomath plus provides in-depth explanations when solving math problems. Would be extremely useful during study.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by ILoveOpenSourceApplications** [comment]
It's implemented in #1633.

**Comment by oSumAtrIX** [comment]
@Exorcism0666 #1669
