### ISSUE TITLE
sponsorblock chapter

### ISSUE THREAD

**Issue by venkat2305** [revanced/revanced-patches#1466]
### Application

Youtube

### Issue

sponsor block has chapter support also. it would be great if it was implemented

### Patch

a patch to show the sponsor block chapters as normal chapters on the progress bar and chapter list 
![image](https://user-images.githubusercontent.com/55329452/211614122-51839728-a347-4885-b3fb-295ef55ce7d1.png)

### Motivation

it improves user experience

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
#692
