### ISSUE TITLE
bug: Google Assistant won't open YouTube Revanced

### ISSUE THREAD

**Issue by anil-al** [revanced/revanced-patches#1470]
### Type

Other

### Bug description

Even though links are set to open in Revanced from device settings, Assistant continues to open the regular when a link regarding YouTube is wanted. If the regular disabled, asisstant just doesn't do anything.

### Steps to reproduce

Open Google Assistant.
Give command for a YouTube video.
Wait for the regular YouTube to open.

### Relevant log output

```shell
-
```

### Solution

Not found any.
Open links in this app setting doesn't change anything.
Disabling doesn't.

### Additional context

Tab S8+, Tab S7 FE
Android 13
Last patch version.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by reisxd** [comment]
Most likely this won't get fixed. Probably because the og YT package name is hardcoded to assistant.

**Comment by anil-al** [comment]
> Most likely this won't get fixed. Probably because the og YT package name is hardcoded to assistant.

I suspected that. Can't we manipulate the system to recognise YouTube Revanced package name differently or something like that?

**Comment by oSumAtrIX** [comment]
Yes
