### ISSUE TITLE
feat(YouTube): Hide feed videos less than x minutes

### ISSUE THREAD

**Issue by shivanshvermak** [ReVanced/revanced-patches#1473]
### Application

YouTube

### Issue

This patch should give option to hide videos that are less than x minutes in feed.

### Patch

There can be an option in settings that can be edited and like ads, videos can be hidden. I don't know if it's possible or not though. 

### Motivation

Well, shorts and videos less than 1 minute or 2 minute contribute significantly towards binging or being on YouTube for a long time. Disabling shorts have greatly benefited me personality to reduce time spent in mindless scrolling. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
#3139
