### ISSUE TITLE
feat(patch): hue essentials premium unlocking

### ISSUE THREAD

**Issue by Joelsuperstar** [ReVanced/revanced-patches#1473]
### Application

Hue essentials is an app where you use smart lighting. I personally use it for the Philips Hue lights but it works on some other brands also. Especially if later the protocool matter will be used more. 

### Issue

There are quite a lot of premium functions included. Which cost a lot of money if you sum them all up.

Most of those premium functions are entertainment based for setting a scene for example. A disco that moves on the music.

But also automation and some control features are locked into premium. Also the multiple bridge one is also locked in with premium. And all those features cost quite a lot of money to unlock.. But are verry handy. There are some premium unlocked apps on the Internet but those don't update verry often. 

### Patch

Can all those paid functions be unlocked with a patch? So that you can use all those functions without paying a lot of money. 

### Motivation

More and more people are getting smart lighting. Hue essentials is an app that has a lot of features and is quite fast in starting. Some features aren't even included in the main Philips hue app. But it really cost a lot of money to unlock everything. It is I think the most used app outside of the main Philips hue app. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Closing according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#%EF%B8%8F-guidelines-for-requesting-or-contributing-patches). Thanks anyways.
