### ISSUE TITLE
feat(patch): 9GAG App Ads blocking patch

### ISSUE THREAD

**Issue by CrypticCus** [revanced/revanced-patches#1478]
### Application

Can we add support for 9gag app to remove ads? thanks!

### Issue

9gag banner ads, postlike ads and popup ads

### Patch

I want patch to remove ads...

### Motivation

Premium feature can't be even purchased for 2 years.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
#650

**Comment by CrypticCus** [comment]
Will it be done?
