### ISSUE TITLE
feat(patch): Instagram ads and some features blocking

### ISSUE THREAD

**Issue by CrypticCus** [revanced/revanced-patches#1479]
### Application

Can we add support for removing ads in instagram? also need ability to hide status updates completely, shop and explore and reals tabs too.

### Issue

I need ads to be gone from instagram and some other tabs too.

### Patch

I need patch to let me control what i want to hide.

### Motivation

Instagram is getting annoying because of idiot promoted content

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by reisxd** [comment]
Dupe issue.

**Comment by CrypticCus** [comment]
Any progress?
