### ISSUE TITLE
feat(patch): YouTube for Android TV

### ISSUE THREAD

**Issue by ghost** [ReVanced/revanced-patches#1486]
### Application

YouTube for Android TV
https://play.google.com/store/apps/details?id=com.google.android.youtube.tv

### Issue

Features like YouTube ReVanced
( especially removing ads )

### Patch

sorry
I'm using a translation tool
I do not know the meaning, so I leave it blank

### Motivation

Because SmartTube･SmartTubeNext doesn't look good
Because SmartTube･SmartTubeNext does not respond appropriately

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Julmik647** [comment]
Info for developers: beacuse YouTube TV is web app, you can make WebView app that uses [this userscripts](https://github.com/reisxd/TizenTube/tree/main/mods). It's possible and [Better Xcloud app](https://better-xcloud.github.io/android/) is an example.
