### ISSUE TITLE
Crashes after Fullscreen

### ISSUE THREAD

**Issue by Stackedstudio** [revanced/revanced-patches#149]
# 🐞 Crashes after 2-3 seconds of video fullscreen

# ⚙ All the versions after 17.25.34 does the same on fullscreen any video.

# 🛠 Might be due to a issue in the Revanced Builder.

# Device : Oneplus 9 Pro running Android 12 (Oxygen OS) - Not Rooted

**Comment by TheJeterLP** [comment]
Cannot reproduce. ReVanced builder is not from us, ask for support from the developer of that.

**Comment by Stackedstudio** [comment]
did not knew about that, sorry for bothering! but I wonder how do I fix the issue of fullscreen crash?
Also where do I get the apks in github officially? can't find them in any repo.

**Comment by TheJeterLP** [comment]
> did not knew about that, sorry for bothering! but I wonder how do I fix the issue of fullscreen crash? Also where do I get the apks in github officially? can't find them in any repo.

We don't provide any because we are not allowed to due to legal reasons. You should read the docs at https://github.com/revanced/revanced-documentation to see how to build ReVanced yourself the proper way.
