### ISSUE TITLE
bug: Remove Screenshot restrictions patch killing reddit app

### ISSUE THREAD

**Issue by selfmusing** [revanced/revanced-patches#1490]
### Type

Other

### Bug description

I successfully patched Reddit -2023.1.0 via revanced builder by reisxd
But App crashed if i try to login.
Crashlog : java.lang.NoClassDefFoundError: Failed resolution of: Lapp/revanced/all/screenshot/removerestriction/RemoveScreenshotRestrictionPatch;
Seems like this patch - Remove-screenshot-restriction Patch causing it

### Steps to reproduce

Patch reddit 2023.1.0 with Remove-screenshot-restriction patch

### Relevant log output

```shell
java.lang.NoClassDefFoundError: Failed resolution of: Lapp/revanced/all/screenshot/removerestriction/RemoveScreenshotRestrictionPatch;
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Use official tools.

**Comment by selfmusing** [comment]
> Use official tools.

💀 getting the same issue even after patching it via revanced manager

**Comment by oSumAtrIX** [comment]
Please open a new issue.
