### ISSUE TITLE
bug: <Reddit shows Ads in Reddit Post's comments section>

### ISSUE THREAD

**Issue by aravind-alpha07** [revanced/revanced-patches#1493]
### Type

Other

### Bug description

Patching with Latest Reddit Version 23.01.0 shows ads in Post's comments section.I attached some screenshots below. In previous versions I hadn't faced such ads or issues.

### Steps to reproduce

Ads in Post's comments sections.

### Relevant log output

```shell
No logs
```

### Screenshots or videos

![Screenshot_2023-01-15-08-27-55-622_com reddit frontpage](https://user-images.githubusercontent.com/93417425/212533275-7f2f248d-05d7-4005-bfa8-0d98e1981fd6.png)
![Screenshot_2023-01-15-14-42-24-024_com reddit frontpage](https://user-images.githubusercontent.com/93417425/212533277-4982db68-3a03-4af0-a73b-74a11615b2c3.png)
![Screenshot_2023-01-15-14-53-56-894_com miui securitycenter](https://user-images.githubusercontent.com/93417425/212533278-d1848fd3-2ba7-4a8c-9349-5d18ab30d6aa.png)

### Additional context

Ads in reddit post's comments section 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Solved by [revanced/revanced-patches] Pull request opened: #1495 fix(Reddit): remove ads patch - specify last version that works correctly
