### ISSUE TITLE
Re twitter Ads continue to show

### ISSUE THREAD

**Issue by Azazil3203** [revanced/revanced-patches#1498]
### Type

Error at runtime

### Bug description

Re twitter I did a clean install of the latest version but I keep seeing ads. 

### Steps to reproduce

Re twitter 

### Relevant log output

```shell
I don't know how to do it.
```

### Screenshots or videos

![Screenshot_20230115_200151_Twitter](https://user-images.githubusercontent.com/96293520/212555384-01d50aeb-109d-477f-b420-27d30fcf1e0b.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Azazil3203** [comment]
Re twitter 9.71 version

**Comment by Azazil3203** [comment]
![Screenshot_20230115_201216_Twitter](https://user-images.githubusercontent.com/96293520/212556171-faae67da-8720-4c52-a7c6-7460bfe8440e.jpg)

**Comment by oSumAtrIX** [comment]
#1290
