### ISSUE TITLE
problem: `hdr-max-brightness` Patch broken with latest swipe-controls rewrite

### ISSUE THREAD

**Issue by TheJeterLP** [revanced/revanced-patches#150]
# 🐞 Issue
Auto setting the brightness to 100% for HDR videos no longer works. 

# ⚙ Reproduce
Build ReVanced using the currently available latest versions. 

# 🛠 Solution
Further debugging

**Comment by shadow578** [comment]
Seems like it interacts with the `swipe-controls` patch in a way i didn't notice while rewriting that one. 
Will work on a fix asap

**Comment by oSumAtrIX** [comment]
Please mind, the patches should not conflict each other if possible. Create a dependency patch which handles the stuff which `swipe-controls` and `hdr-max-brightness` does. The dependency can then simply feature an `addHook(to)` method which both oatches can call independently, while the dependency manages how it inserts the hook to the required method.
