### ISSUE TITLE
bug: Lot of errors applying patches

### ISSUE THREAD

**Issue by thk34** [revanced/revanced-patches#1500]
### Type

Error while patching

### Bug description

Hello,
I recently tried to "mod" youtube with revanced and a lot of errors occured, i think i didn't made any mistake.

(yt-mod.apk is the "vanilla" 17.49.37 youtube apk)

(I don't speak english fluently)

### Steps to reproduce

the youtube apk is from [https://www.apkmirror.com/apk/google-inc/youtube/youtube-17-49-37-release/youtube-17-49-37-2-android-apk-download/](url)

Azul Zulu version:
17.0.5+8
Azul Zulu: 17.38.21
for Ubuntu	Architecture: x86 64-bit	java package: JDK

My laptop's configuration:
Laptop with i5-10300H, 16go ram and an RTX 2060 (the laptop version)

### Relevant log output

```shell
https://pastebin.com/6j1M8k6d
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
You forgot to merge the integrations as the error log already explains.

**Comment by thk34** [comment]
> You forgot to merge the integrations as the error log already explains.

How do can I do it?

**Comment by oSumAtrIX** [comment]
Check the docs in the revanced-cli repo.

**Comment by thk34** [comment]
> Check the docs in the revanced-cli repo.

Ty I realised i forgot the -m vanced-integrations-0.93.0.apk
when i added it everything succeeded
