### ISSUE TITLE
App Crash: YouTube Music crashes when adding device files to playlist

### ISSUE THREAD

**Issue by introversialscalpel** [revanced/revanced-patches#1503]
### Type

Error at runtime

### Bug description

I tried adding my device files via yt music app into playlists but as soon as i tap on that option, the app crashes.

### Steps to reproduce

1. go to library
2. tap library icon again
3. go to device files option
4. choose any music file there to add to you playlist
5. app crashes

### Relevant log output

```shell
Using recommended options for patch as it is
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Please include crash logs with logcat.

**Comment by introversialscalpel** [comment]
i didn't save the log file but it's same as #1502 issue i created except that this time i didn't select the predictive back gesture while patching

**Comment by oSumAtrIX** [comment]
These are the logs at patching. Crash logs are required.

**Comment by introversialscalpel** [comment]
![Screenshot_20230116-025412_Device care](https://user-images.githubusercontent.com/102604664/212568058-b9acc5f0-4814-4d0a-af21-a9e8297bd72f.jpg)

**Comment by introversialscalpel** [comment]
also, i tried the same steps with original app v5.39.52, and there were no such errors there

**Comment by introversialscalpel** [comment]
I resolved the issue by unselecting the screenshot restriction patch
