### ISSUE TITLE
feat(patch): change seekbar color

### ISSUE THREAD

**Issue by Kotletka89** [revanced/revanced-patches#1516]
### Application

YouTube 

### Issue

YouTube recently changed seekbar color
![Screenshot_2023-01-15-17-01-11-507_app revanced android youtube](https://user-images.githubusercontent.com/101099776/213217939-1b7d6e97-2ebb-464e-8012-1be5f885ab69.jpg)

### Patch

Change it back to red color

### Motivation

I don't like it

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Already implemented.

**Comment by Kotletka89** [comment]
> Already implemented.

How to do that? What's the name of the patch?

**Comment by oSumAtrIX** [comment]
It's controlled by the theme patch.

**Comment by Kotletka89** [comment]
how to work with this theme patch? any instruction or something please?
