### ISSUE TITLE
bug: YouTube: videos not loading

### ISSUE THREAD

**Issue by rezackacz** [revanced/revanced-patches#1517]
### Type

Error at runtime

### Bug description

Any video I click on doesn't load, the circle just keeps spinning. Tried reinstalling, upgrading to latest recommended version, clearing cache, nothing helps. Original Youtube works. Version 17.49.37.

### Steps to reproduce

Step 1. Use YT ReVanced ver. 17.49.37, patched w/ all recommended patches.
Step 2. Try playing any video.

### Relevant log output

```shell
no logs
```

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by JulianKarhof** [comment]
I have the same issue. Why is this marked as completed?

**Comment by EhabxAlaa** [comment]
It happens to me too, but after a lot of testing, it seems like it only happens with my main account but any other account works just fine , what is crazy is that my account works just fine with the normal YouTube app, to sum up: my account doesn't work with ReVanced but works with YouTube app
