### ISSUE TITLE
feat(YouTube Music): Disable album art on the lock screen background

### ISSUE THREAD

**Issue by MasterIO02** [ReVanced/revanced-patches#1519]
### Application

YouTube Music

### Issue

This patch would allow users to disable the album art on the lockscreen background

### Patch

On Android 11, the system-wide option to disable the album art on the lockscreen has been removed. It is dependent on the application to show it or not (and on the Android flavor, OxygenOS for example has it forced enabled for every application if the application does not have a toggle, so any thumbnail in the media control would go to the lockscreen). YouTube Music does not include a toggle to disable this functionality, so this patch could add a toggle to disable this feature, or just straight-up disable it.

### Motivation

Album arts are generally in very low quality and zoomed-in, so they spoil the lockscreen background.
Some musics have NSFW album arts, which users would not like to see when unlocking their phone.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by lucidusdev** [comment]
I get it patched and works fine, but I know nothing about Revanced patches.
Hope some dev. can make a proper patch.

in classes2.dex aonr.smali, at the end of 

`.method private final j()Lhe;`

skip the albumart part.

```
   const-string v2, "android.media.metadata.ALBUM"

    invoke-virtual {v1, v2, v0}, Lhe;->e(Ljava/lang/String;Ljava/lang/String;)V

    :cond_0
    iget-object v0, p0, Laonr;->h:Laomy;

    iget-object v0, v0, Laomy;->r:Landroid/graphics/Bitmap;

    #if-eqz v0, :cond_1
    #change to goto
    goto :cond_1

    const-string v2, "android.media.metadata.ALBUM_ART"

    invoke-virtual {v1, v2, v0}, Lhe;->b(Ljava/lang/String;Landroid/graphics/Bitmap;)V

    :cond_1
    iget-object v0, p0, Laonr;->k:Laons;

    iget-object v2, p0, Laonr;->h:Laomy;

    invoke-interface {v0, v1, v2}, Laons;->f(Lhe;Laomy;)V

    return-object v1
.end method
```

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!

**Comment by MasterIO02** [comment]
bruh, why not make a "low priority" label instead? what's the need for clearing out old issues without resolving them? you can just leave them open and wait for someone to make a PR

**Comment by oSumAtrIX** [comment]
The issue is not deleted. If anyone cares they can make a PR as stated. As we don't plan it anymore, the issue is closed for us.
