### ISSUE TITLE
An option to open links externally in YouTube ReVanced

### ISSUE THREAD

**Issue by Shane9248** [revanced/revanced-patches#1520]
### Application

YouTube ReVanced

### Issue

![Screenshot_20230119-154906~2](https://user-images.githubusercontent.com/83491863/213443227-d16aaa52-e434-4039-9077-7608bc48bd69.png)
This pic is from the Twitter Settings which allows links to open externally

![Screenshot_20230119-171152~2](https://user-images.githubusercontent.com/83491863/213443361-e8c8d91e-4ca1-4ac5-99c1-c989f0c6ddf0.png)
This pic is from the Facebook Settings which allows links to open externally

https://user-images.githubusercontent.com/83491863/213443859-07e3c292-596e-4e56-9aba-089bff068b70.mp4
In this video it shows how links only open in the 'in app browser' and how the 'Open By Default' links is enabled

https://user-images.githubusercontent.com/83491863/213444065-6e3013cd-1b0c-401f-8efe-bb0f7bfdee93.mp4
In this video it shows how the links inside Facebook open externally in the app and not in the 'in app browser' as it supposed to be

### Patch

YouTube doesn't allow links to open externally so when we open links of apps like Twitter, Instagram, Facebook they open in the 'in app browser' instead of the specific app itself ..so if possible it will be real handy

### Motivation

It makes the UX easily accessible and updated 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by sawankumarbundelkhandi** [comment]
@oSumAtrIX this is completed by https://github.com/revanced/revanced-patches/pull/1524 and can be closed.

**Comment by Shane9248** [comment]
> @oSumAtrIX this is completed by https://github.com/revanced/revanced-patches/pull/1524 and can be closed.

is it tho ? because the links are still opening in the 'in app browser' for me

**Comment by sawankumarbundelkhandi** [comment]
I just tested it with a link in the description of a video and it's opening fine within youtube as chrome custom tabs.

Have you checked if the patch is enabled in your settings @Shane9248?

**Comment by Shane9248** [comment]
> I just tested it with a link in the description of a video and it's opening fine within youtube as chrome custom tabs.
> 
> Have you checked if the patch is enabled in your settings @Shane9248?

yeah sorry i deleted the comment...but what i meant was that the links do not open in the specific app itself like twitter facebook but yes can confirm they do open externally tho

**Comment by oSumAtrIX** [comment]
Thanks for small triage @sawankumarbundelkhandi

**Comment by sawankumarbundelkhandi** [comment]
have you checked those (facebook, twitter) app settings if the defaults are enabled or not?

check this - https://support.google.com/android/thread/14738946/how-do-i-open-links-in-other-apps?hl=en

**Comment by Shane9248** [comment]
> @Shane9248 Have you checked those (facebook, twitter) app settings if the defaults are enabled or not?
> 
> check this - https://support.google.com/android/thread/14738946/how-do-i-open-links-in-other-apps?hl=en

yes i have done that ..for all apps except youtube it opens in app

https://user-images.githubusercontent.com/83491863/215350821-dc153e8b-8522-4736-9e7c-8914946ada89.mp4

in this video it shows how links inside Facebook opens in app

https://user-images.githubusercontent.com/83491863/215350876-32455f06-cf19-4839-b166-7ba63f94931d.mp4

here it shows how links still doesn't open in app

**Comment by oSumAtrIX** [comment]
This issue is only for YouTube, for other apps please open a separate issue

**Comment by Shane9248** [comment]
> This issue is only for YouTube, for other apps please open a separate issue

yes this is inside YouTube...as it doesn't opens its links in the app...but nvm it's fine..👍🏻 i appreciate ur work

**Comment by sawankumarbundelkhandi** [comment]
how about this patch @Shane9248 is it enabled? It will remove the Youtube redirect that get's append into the URL, so that the apps can handle their own redirect links. I am not sure also what's wrong.

![image](https://user-images.githubusercontent.com/10863510/215351381-13dc956c-b4fc-46e7-9864-57214ced2b6c.png)

**Comment by Shane9248** [comment]
> how about this patch @Shane9248 is it enabled? It will remove the Youtube redirect that get's append into the URL, so that the apps can handle their own redirect links. I am not sure also what's wrong.
> 
> ![image](https://user-images.githubusercontent.com/10863510/215351381-13dc956c-b4fc-46e7-9864-57214ced2b6c.png)
> 

yes i tried both turning it on and off but it's still the same

**Comment by sawankumarbundelkhandi** [comment]
I am not sure of the issue then. I don't use social networking apps so i can't test it. I tested it with Spotify and it's just working fine.
