### ISSUE TITLE
Videos doesn't load anymore 

### ISSUE THREAD

**Issue by EhabxAlaa** [revanced/revanced-patches#1521]
### Type

Error at runtime

### Bug description

For more than 2 days now videos stopped loading while using YouTube revanced, i searched more into the issue and found that this only happens with my main account on YouTube revanced but not the normal app, something i noticed too is that videos happy only 3 quality options, which are 144,360,720, i noticed the same issues closed without a reply so i don't know if you are working to fix this or what

### Steps to reproduce

Try to open any video using YouTube revanced and it won't load, only with my main account though, incognito and other accounts work

### Relevant log output

```shell
No logs
```

### Additional context

Please provide me with a reply as I don't want to go back to normal YouTube app or use another account 

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by reisxd** [comment]
Duplicate issue.

**Comment by EhabxAlaa** [comment]
> Duplicate issue.

But it was closed while not being solved, and i wanted to provide extra information to when it happens

**Comment by oSumAtrIX** [comment]
Reopened #981

**Comment by Ushie** [comment]
> and ARE YOU WORKING ON FIXING IT?

kindly piss off

**Comment by EhabxAlaa** [comment]
> > and ARE YOU WORKING ON FIXING IT?
> 
> kindly piss off

Thanks for your respectable reply, i was just trying to know if you i should wait and expect this to be solved or give up and make a new account, sorry for bothering you

**Comment by oSumAtrIX** [comment]
He wasnt wrong, i dont think he was disrespectful intentionally, rather wanted to emphasise the last part lol

**Comment by oSumAtrIX** [comment]
> Thanks for your respectable reply, i was just trying to know if you i should wait and expect this to be solved or give up and make a new account, sorry for bothering you

We cant predict the future

**Comment by Ushie** [comment]
> @Ushie He wasnt wrong, i dont think he was disrespectful intentionally, rather wanted to emphasise the last part lol

I see, @ehabxalaa sorry!

**Comment by EhabxAlaa** [comment]
> > Thanks for your respectable reply, i was just trying to know if you i should wait and expect this to be solved or give up and make a new account, sorry for bothering you
> 
> We cant predict the future

Sure, sorry for my comment, I didn't mean to be disrespectful, i just wanted to  receive a reply longer than a few words

**Comment by EhabxAlaa** [comment]
> > @Ushie He wasnt wrong, i dont think he was disrespectful intentionally, rather wanted to emphasise the last part lol
> 
> I see, @EhabxAlaa sorry!

No problem it was a bad comment on my end too, i am not paying anything for this service so I can't complain

**Comment by EhabxAlaa** [comment]
> 
The app works just fine now with my account, thank you guys so much for whatever you did that made it work❤️

**Comment by EhabxAlaa** [comment]
The issue is back again 😢
