### ISSUE TITLE
feat(patch):  YouTube music useless in canada

### ISSUE THREAD

**Issue by DownWithSafe** [revanced/revanced-patches#1528]
### Application

YouTube music

### Issue

I live in Canada and here YouTube music doesn't let you play a selected song. It only lets you make a radio station from that song and the station will not even have the selected song in it. 

### Patch

Fool YouTube into thinking other countries are in the United States so we can select individual songs and not just start a radio station.

### Motivation

YouTube music Vance is useless in Canada at the moment. YouTube Vance works great in Canada but revanced is having this problem.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Not possible without a VPN.

**Comment by KobeW50** [comment]
> Not possible without a VPN.

What about spoofing the app version to 4.27.xx?

Should I open a request if there isnt one already?

**Comment by oSumAtrIX** [comment]
Sure
