### ISSUE TITLE
feat(YouTube): Disable "Sign in to TV" pop-up 

### ISSUE THREAD

**Issue by spaceduck8** [ReVanced/revanced-patches#1531]
### Application

YouTube

### Issue

YouTube app shows a pop-up asking to sign-in to smart TV, there is currently no way to disable it.

### Patch

Ideally stop the YouTube app from detecting TVs on the same network. Disable local network access for the entire app if possible. It might be using the public IP and linking the devices together so that might not be a working solution. 

### Motivation

Stop accidentally signing into home TV. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!

**Comment by UmBottesWillen** [comment]
I'd like to bump this request. I don't like the idea of the YT app searching the connected wifi for TVs it can connect to. I'd like to request at least a toggle where you can disable this behavior.

**Comment by UmBottesWillen** [comment]
> If anyone runs into this and your other devices never connect to your tv (such as apple airplay or android casting), then you can change your home router settings and add the tv to the router DMZ settings. Then the tv will isolated from the rest of the network devices and the "connect to tv" prompt will be no more.
> 
> A simpler solution is to create a wifi guest network and use the tv on that. The router must allow creating isolated guest networks. A guest network still allows device to tv connections by temporarily joining your phone/device the guest network where the tv is then discoverable.

That requires me to have control over the router, which more often than not, is not the case.

**Comment by UmBottesWillen** [comment]
> I don't know over which protocol the TV is communicating however it's probably easy to disable once known

If you mean to say that I could stop the TV from searching for YT clients, instead of stopping the YT app from looking for TVs, I'd rather have the latter than to hope I can reign in the TV. Assuming I even have access to the TV/router.

**Comment by VorgonBattlecruiser** [comment]
my router does not have that function and whenever my mother uses her tv i have to be extremely careful not to stream my content accidentally on her tv. this is really annoying and ruins the fun of watching youtube.

**Comment by UmBottesWillen** [comment]
Will this patch merely disable the UI or will it disable the discovery feature including the network component?
