### ISSUE TITLE
feat(patch): Clip Studio Paint unlock Pro/Ex

### ISSUE THREAD

**Issue by Mattis142** [ReVanced/revanced-patches#1533]
### Application

Clip Studio Paint: jp.co.celsys.clipstudiopaint.galaxystore, jp.co.celsys.clipstudiopaint.googleplay

### Issue

This patch would allow users to use pro features without having to subscribe 

### Patch

The Patch would bypass restrictions that require you to pay for the app and unlock the EX subscription tier's features

### Motivation

As an artist I really like CSP however it makes me mad that rather than having ads in free tier they limit you to an hour a day, also you cannot buy a lifetime subscription for mobile either

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [x] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Closing according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#%EF%B8%8F-guidelines-for-requesting-or-contributing-patches). Thanks anyways.
