### ISSUE TITLE
feat(patch): Hotstar app unlock premium and location restrictions.

### ISSUE THREAD

**Issue by W1zardK1ng** [revanced/revanced-patches#1535]
### Application

Hotstar (https://play.google.com/store/apps/details?id=in.startv.hotstar)
Disney+Hotstar is a video streaming app for the best of live sports, TV shows and movies. 

### Issue

Remove ads, unlock premium features and unlock geo location restrictions.

### Patch

Hotstar app comes with 2 premium plans but even in that one plan still gives ads while watching the content.
The highest premium is the only one which allow users to unlock some shows and removes ads completely.
Would like to have a patch with can unlock the premium features and removes ads completely.
Also Hotstar does not work outside India unless we use and vpn server in india. So unblocking the geo restriction will be a huge use case for users.

### Motivation

Hotstar is one of the most used streaming app in India for sports and movies, having these patches will benefit users who residing in india and abroad.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Unblocking geolocation won't be possible without a VPN, premium features are likely clientside and ads are probably served off the stream.

**Comment by sayyid5416** [comment]
@oSumAtrIX Removing ads should be possible as there are many mods which have removed ads. I don't want premium features but "hide ads" should be possible.

**Comment by oSumAtrIX** [comment]
Send a link to one

**Comment by sayyid5416** [comment]
@oSumAtrIX There are many I've not tried myself due to precaution (may contain malware or cryptominers).

But many people who tried reports that mod works.
