### ISSUE TITLE
bug: Share Button Missing mostly in Live Streaming Videos

### ISSUE THREAD

**Issue by giwrgosmant** [revanced/revanced-patches#1538]
### Type

Other

### Bug description

Share Button Missing mostly in Live Streaming Videos when you change any Hide Buttons options or if you restart couple of times the app without change anything.
I've also made a report on support channel at Discord [here](https://discord.com/channels/952946952348270622/1066903908003356752).
Seems similar issue with [this](https://discord.com/channels/952946952348270622/1048057412919246918/1048057412919246918).

### Steps to reproduce

1. Open ReVanced.
2. Enable Hide Download Button for example in Settings.
3. Check this [video](https://www.youtube.com/watch?v=iBEB5nB64u8&feature=youtu.be).  There is no share button.

### Relevant log output

```shell
-
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
#767
