### ISSUE TITLE
feat(YouTube): Copy description and comments, video titles etc.

### ISSUE THREAD

**Issue by venkat2305** [ReVanced/revanced-patches#1538]
### Application

YouTube 

### Issue

Makes it easier to copy the text in YouTube app

### Patch

Ability to copy any text will be very helpful

### Motivation

Makes it easier to copy the text in YouTube app

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by kairusds** [comment]
Is it also possible to make them have a translate button too like in comments?

**Comment by oSumAtrIX** [comment]
@kairusds  https://github.com/ReVanced/revanced-patches/issues/1153

**Comment by issssse** [comment]
Yes, please implement this! It is a huge flaw in youtube and would make life so much easier. Right now, you would either have to screenshot and use text recognition, or copy link into browser, open desktop mode and find the relevant comment/description/title. Simply put, it's a big pain in the ass.

**Comment by kairusds** [comment]
As of v19.04.37, you can copy texts on the description now so there's no need for this patch anymore.

**Comment by SodaWithoutSparkles** [comment]
> As of v19.04.37, you can copy texts on the description now so there's no need for this patch anymore.

This patch isnt limited to descriptions. This patch is also extended to comments and titles.

**Comment by oSumAtrIX** [comment]
Closing the issue as it turns out that copying text from a screen is possible via third party apps with ease.

**Comment by SodaWithoutSparkles** [comment]
> Closing the issue as it turns out that copying text from a screen is possible via third party apps with ease. 

Please name such apps.

Also does that differ from using OCR? If so, OCRs may not be accurate, especially when dealing with CJK languages.

**Comment by oSumAtrIX** [comment]
You will find plenty on Google searching for text selection apps, not OCR.

**Comment by SodaWithoutSparkles** [comment]
> You will find plenty on Google searching for text selection apps, not OCR, pick one 

Please name one of these apps such that I could test. None of the 7 ones I found by seaeching "text selection apps" support copying in-app. 

Using accessibility settings is not acceptable as this could cause privacy concerns and will cause other secure apps (e.g. banks) stopps working.

**Comment by oSumAtrIX** [comment]
This is an issue tracker and not a place to discuss available apps. Here is one using accessibility services which given your position in this circumstance will be more than acceptable: https://play.google.com/store/apps/details?id=com.camel.corp.universalcopy

If you have Luxus problems, feel free to open a PR
