### ISSUE TITLE
feat(patch): Poweramp - patch to unlock full version 

### ISSUE THREAD

**Issue by devel161** [ReVanced/revanced-patches#1544]
### Application

Poweramp:https://play.google.com/store/apps/details?id=com.maxmpz.audioplayer

### Issue

Poweramp Trial Version has limited features 

### Patch

A patch to unlock full version 

### Motivation

Poweramp is the best music player out there.it would be great for all users.(sorry for my bad English. English is not my first language)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Tekkno303** [comment]
Yes. Poweramp is the Best Music Player. I would also like to patch Poweramp in revanced manager.
