### ISSUE TITLE
feat(patch): Problem with PIP mode in Revanced

### ISSUE THREAD

**Issue by Vipin2003** [revanced/revanced-patches#1561]
### Application

Youtube

### Issue

There is a issue with PIP is that when using PIP in original YT, shorts doesn't go in PIP mode. Only videos go in PIP. But In Revanced, after enabling pip shorts also go in pip mode. Dev's said that it is Google problem but it is not there in original YT. See the clip :

https://user-images.githubusercontent.com/93650504/215328144-eb7c529b-5cd6-4616-ab44-2950b87b984a.mp4

### Patch

Need a patch to solve this issue.

### Motivation

Solve a big problem bcoz we have to first close the shorts tab, then YT.

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
#1426
