### ISSUE TITLE
feat(patch): Change seekbar color to whatever you want, using hex codes

### ISSUE THREAD

**Issue by n1cKz1** [revanced/revanced-patches#1563]
### Application

YouTube

### Issue

Well ever since YT changed the seekbar color to white (and then RV changed it back to red), I've had an idea for a patch that would satisfy every user's style of customization, especially for those of us who use the Enhancer for YT extension on desktop.

### Patch

My idea is an option that allows the user to change the seekbar color, by inputting the hex code of their color of choice.

### Motivation

This would be a great option when it comes to customization. I'm aware this can probably already be done by changing the Theme patch myself, but the average user obviously doesn't know how to do that and it would take a lot of time, so an option to do it directly from the settings would be a welcome addition.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Already possible with the theme patch. Set the hex in the option of the patch. Currently only possible via the CLI
