### ISSUE TITLE
bug: External app crashing when trying to play in-app/embedded video

### ISSUE THREAD

**Issue by yousie642** [revanced/revanced-patches#1574]
### Type

Error at runtime

### Bug description

When using Relay for Reddit, or any app that can play youtube videos in an embedded player within the app, the app crashes. I believe the app is trying to use the Youtube Android Player API to open an embedded player https://developers.google.com/youtube/android/player

Original Vanced used to have a similar issue, but was fixed by Vanced Extended, which is discontinued.

### Steps to reproduce

Step 1. Patch Youtube using ReVanced Manager (root)
Step 2. Install Relay for Reddit
Step 3. Open Relay for Reddit and tap on the thumbnail for post that links to a youtube video (youtube links will have a red mark in the bottom right corner of the thumbnail)
Step 4. Embedded youtube player will start loading, and then Relay for Reddit will crash

### Relevant log output

```shell
I'm sorry. I don't know how to capture logs. I tried to run that command in Terminal Emulator, but nothing happened.
```

### Screenshots or videos

https://user-images.githubusercontent.com/43191177/215829864-cdba2bae-1ac4-4609-926b-4540ca8f631f.mp4

### Additional context

Pixel 5a
Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Moving to https://github.com/revanced/revanced-patches/issues/2091
