### ISSUE TITLE
bug: Bump Patch Version for YT Music 

### ISSUE THREAD

**Issue by ILoveOpenSourceAppications** [revanced/revanced-patches#1584]
### Type

Error while patching

### Bug description

Even though the patch has been updated for version 5.41.50, it still hasn't reflected in the manager.

### Steps to reproduce

Just select the YT Music version and it'll say that the recommended version is still 5.39.52.

### Relevant log output

```shell
Nil
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
This is not a bug. The ReVanced Manager app recommends the version which most patches are compatible with. You can ignore the recommendation and patch a higher version regardless, but not all patches might be compatible if you do not follow the recommendation. In any case, this does not concern this repository.

**Comment by ILoveOpenSourceAppications** [comment]
What I meant is similar to that of #1585. It's not that I don't know I can patch whichever app version ignoring the recommended version.

**Comment by oSumAtrIX** [comment]
It's still not a bug.

**Comment by ILoveOpenSourceAppications** [comment]
It may not look like a bug from the team's side. But to the normal eye, where the patch release says it has bumped patch comparability to 5.41.50 and is not seen as such when trying to install that app, it seems to be like a bug.

**Comment by oSumAtrIX** [comment]
That is a case for the front facing app which is the ReVanced Manager app. The CLI for example simply lists all compatible versions. The ReVanced Manager app only shows the recommended one.
