### ISSUE TITLE
bug: YouTube Music patches' target versions are not up-to-date

### ISSUE THREAD

**Issue by theRookieCoder** [revanced/revanced-patches#1585]
### Type

Cosmetic

### Bug description

The [YouTube Music patches](https://github.com/revanced/revanced-patches#-comgoogleandroidappsyoutubemusic) section has not been updated to the latest supported version in tandem with #1551.

### Steps to reproduce

1. Go to [YouTube Music's patches section](https://github.com/revanced/revanced-patches#-comgoogleandroidappsyoutubemusic)
2. Notice that the target versions have not been updated, despite the [latest release](https://github.com/revanced/revanced-patches/releases/tag/v2.159.0)'s changelog mentioning a bump.

### Solution

Update these target versions to `5.41.50`

### Acknowledgements

- [x] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by kazimmt** [comment]
Because `hide-get-premium` still not compatible with 5.41.50

**Comment by theRookieCoder** [comment]
Why shouldn't everything else that works be updated then?

**Comment by oSumAtrIX** [comment]
Everything else that works has been updated.
