### ISSUE TITLE
bug: Predicitive Back Gesture Patch not working?

### ISSUE THREAD

**Issue by GitExploraa** [revanced/revanced-patches#1586]
### Type

Error at runtime

### Bug description

is the predicitive back gesture patch there just for show? cause it didnt work in all the apps i tried it on (mainly youtube, spotify and twitter), anyone got an idea please
im on Android 13, One Ui 5.0 btw, latest january update

### Steps to reproduce

1.choose said patch when modding the apk
2. install resulting apk
3. test it and then notice that its not working as it should

### Relevant log output

```shell
unecessary
```

### Solution

Make the patch functionnal, if not possible it should be just removed

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Not all apps will adequately support it. It is excluded by default for that reason.

**Comment by GitExploraa** [comment]
> Not all apps will adequately support it. It is excluded by default for that reason.

well the description should at least say that, cause what i have seen no app does support it (correct me if im wrong, and let me know which apps do, please)

**Comment by oSumAtrIX** [comment]
Some apps support it.

**Comment by GitExploraa** [comment]
I actually tried with an newer version of Twitter and it worked there, but there should be a list saying which apps it works on and which ones it doesnt with

**Comment by oSumAtrIX** [comment]
By design, patches which are not constrained on apps are geared towards working with all apps. It is futile to make them universal and then provide a list of apps it works with, because the patch could've been constrained to them to begin with.
