### ISSUE TITLE
feat(patch): fast-forward during silence

### ISSUE THREAD

**Issue by jopejoe1** [revanced/revanced-patches#1591]
### Application

Youtube

### Issue

Unnecessary long pauses between sections in videos.

### Patch

An option in the settings menu that enables the skiping of sections of videos that don't have any sound in them.

### Motivation

Saving some time by skipping the empty sections of videos.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Exists in the `sponsorblock` patch.

**Comment by jopejoe1** [comment]
> Exists in the `sponsorblock` patch.

Not what i meant what i meant is somthing thats skips over awkward pauses in the middle of a section where people are talking this should be similar to the fast-forward during silence option in new pipe.

**Comment by oSumAtrIX** [comment]
Superseded by #1815.
