### ISSUE TITLE
feat(patch): Fix cut off of 4:3 video

### ISSUE THREAD

**Issue by tesmite** [revanced/revanced-patches#1593]
### Application

YouTube

### Issue

In the old YouTube application, the aspect ratio of the video area was fixed at 16:9, but in the current version of the YouTube application, it changes according to the size of each video.
However, when the aspect ratio is other than 16:9, the video is cut off to 16:9 when scrolling through the under video section or opening the comments section.
Old version (16.20.35)
![Screenshot_20230208-092621](https://user-images.githubusercontent.com/111569199/217399424-8721bc07-0e2f-4358-b33e-315282736bfa.png)
Current version (18.03.36)
![Screenshot_20230208-092827](https://user-images.githubusercontent.com/111569199/217399569-1531fccb-2fe8-4d51-a55d-d3a8fe5aaac5.png)

### Patch

Fix the aspect ratio of the video area to 16:9 like the old version of YouTube.
Or, the video area should not be narrowed by scrolling, except when the video is extremely vertical.

### Motivation

Cutting off a part of a video is detrimental to the value of the video, and it is inconvenient to check important information (subtitles, explanations, etc.) in the cut-off area while viewing the comment section.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
#952

**Comment by tesmite** [comment]
> #952
The issue you present is mainly related to adjusting the aspect ratio of the video to the device when the aspect ratio of the video and the device do not match when displayed in full screen, which is different from this issue.

**Comment by oSumAtrIX** [comment]
https://github.com/revanced/revanced-patches/issues/1038

**Comment by tesmite** [comment]
> #1038
That issue is a allow apps to correct aspect ratios in videos with incorrect aspect (e.g., a 16:9 video encoded as 4:3 with a vertical orientation or black borders at the top and bottom).
If you implement an option to convert 4:3 videos to 16:9 size (with black borders on the left and right) as one of the options, this could be one of the solutions, but I don't think we are talking about the same problem.

**Comment by oSumAtrIX** [comment]
In that case, open a superseeding issue which covers all of said related issues or add yours to one of them.
