### ISSUE TITLE
YouTube: Always choose in which playlist to save the video

### ISSUE THREAD

**Issue by HeroGalak** [revanced/revanced-patches#1594]
### Application

YouTube

### Issue

Every time you click on save button, YouTube will save the video in the last playlist you choose.
In this way the user can't decide the playlist before saving the video.

So the user has to click also the button "Change" on the notification below in order to decide the playlist.

Panel the patch should always show:
![Screenshot_20230208_225523_YouTube](https://user-images.githubusercontent.com/69464248/217660381-8d372505-06a6-4f75-a746-f7764a4591a1.jpg)

### Patch

The patch should force YouTube to show the playlists panel every time the save button is clicked (so for every video).

### Motivation

When save button is clicked for the first time the video is saved in the last playlist chosen. This behaviour mess up the user's playlists very often.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by madgoatz** [comment]
you can press and hold the save button on the first click to see the option to select the playlist you want to save to
