### ISSUE TITLE
feat(patch): Unlock full version of Symfonium

### ISSUE THREAD

**Issue by gandbg** [ReVanced/revanced-patches#1601]
### Application

[Symfonium](https://symfonium.app/), [app.symfonik.music.player](https://play.google.com/store/apps/details?id=app.symfonik.music.player)

### Issue

Unlock the full, non time-bombed, version

### Patch

A patch that makes it so that when you click on the *purchase* button, the application activates automatically with the need for a payment

### Motivation

Symfonium is a moderately popular music player supporting a multitude of sources (local and remote) and a lot a features.
With this patch, anyone who finds it useful can use it.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Trived4real** [comment]
Bro what happened? Did you get the modded version ?

**Comment by isyuricunha** [comment]
> Bro what happened? Did you get the modded version ?

No.
