### ISSUE TITLE
feat(patch): Hide View Products Banner

### ISSUE THREAD

**Issue by ILoveOpenSourceAppications** [revanced/revanced-patches#1605]
### Application

YouTube 

### Issue

The products banner still appears even with the latest patches of Revanced.

### Patch

Import the hide view products banner from RVX as it seems to resolve the issue at the moment.
![Screenshot_20230210-225222~2](https://user-images.githubusercontent.com/117499019/218156907-8b507a1a-175e-4245-87d1-957031d5225d.png)

### Motivation

Same as above.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Please include an image of the banner

**Comment by ILoveOpenSourceAppications** [comment]
Is this the same one as implemented in patch version 2.161.0 (youtube/general-ads: hide pill to view products)?

**Comment by oSumAtrIX** [comment]
Yes. Banner is wrong, it's a pill.

**Comment by ILoveOpenSourceAppications** [comment]
But it's still showing up though.
![IMG-20230211-WA0005~2](https://user-images.githubusercontent.com/117499019/218264118-c4805af2-7e25-4f37-89b5-05b332186a4e.jpg)

**Comment by ILoveOpenSourceAppications** [comment]
> Yes. Banner is wrong, it's a pill.

By pill, did you mean the one that showed up on the bottom left of the video?

**Comment by oSumAtrIX** [comment]
Maybe `Popup` should be used here to refer to it?

**Comment by ILoveOpenSourceAppications** [comment]
> Maybe `Popup` should be used here to refer to it?
> 
> > We're there any modifications made to the patch or was it an exact replica?
> 
> It is an exact replica. Consider [this](https://github.com/revanced/revanced-integrations/pull/317/commits/7225bc3c48b2d8f94d21b5481e37d78a26f49544).

Well, I doubt calling it a pop-up is accurate as it's there even without clicking, with a drop down option on its side. But yeah I guess this new commit is accurate. Will confirm after the patch is pushed and I update using it.

**Comment by ILoveOpenSourceAppications** [comment]
Since the issue still exists, shouldn't the issue be reopened and closed only after a proper fix has been released?

**Comment by oSumAtrIX** [comment]
No, the feature is implemented.

**Comment by ILoveOpenSourceAppications** [comment]
But the feature implemented hasn't resolved the issue mentioned in the first place though. Will this be further refined by any chance?

**Comment by oSumAtrIX** [comment]
It should, check [this](https://github.com/revanced/revanced-patches/issues/1605#issuecomment-1426799599).

**Comment by ILoveOpenSourceAppications** [comment]
Okay.
