### ISSUE TITLE
problem: `old-quality-layout`

### ISSUE THREAD

**Issue by anyz0** [revanced/revanced-patches#162]
## 🐞 Issue

patch old quality layout doesn't work

**Comment by oSumAtrIX** [comment]
Please open a proper issue.

**Comment by anyz0** [comment]
i build with default patch but, quality layout still shown as new layout

**Comment by tzuyu18** [comment]
I have this issue on my android 12 device but not on my android 10. Maybe an android version issue. Thanks for all the efforts of mods!
