### ISSUE TITLE
feat(YouTube): Playback Speed button, drag slider, double-tap zones

### ISSUE THREAD

**Issue by Coldblackice** [ReVanced/revanced-patches#1620]
### Application

YouTube (com.google.android.youtube)

### Issue

Currently, **Playback-Speed** control requires jumping into sub menus, necessitating multiple screen taps each time a speed change up or down or default is desired.

On desktops, keyboard shortcuts "<” and ">" change playback speed on the fly, but obviously this isn't practical on mobile devices.

### Patch

To more quickly and directly change a video's playback speed, it would be fantastic if any of the following could be implemented:

- **_Playback-Speed button_** added to on-video controls (👍, 👎, etc)
- **_Playback-Speed drag-slider_** (like volume and brightness sliders)
- **_Playback-Speed double-tap zones_**, double-tapping the top of a video increases speed, the bottom area decreases

A fine-grained speed scale wouldn't be necessary, even merely sliding between default .5x--1x--1.5x--2x would be phenomenal.

### Motivation

**Reason**: 

This patch would provide quick, direct access for a user to change playback-speed on the fly -- because some parts of a video might not be ideal at 2x, like technical explanations, while other parts could use a speed bump.

This optional patch for changing playback-speed via an on-video button, or drag-slider, or double-tap would cut out the need for multiple screen taps + sub menus each time a user wants to change speeds.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by mizoru** [comment]
Really want for this to be created

**Comment by Bluscream** [comment]
This is no longer needed since grayjay exists now
