### ISSUE TITLE
bug: ads return. Using the latest manager, patcher and recommend YouTube 

### ISSUE THREAD

**Issue by hanswurst31** [revanced/revanced-patches#1620]
### Type

Other

### Bug description

Ada

### Steps to reproduce

Standart install

### Relevant log output

```shell
Non
```

### Acknowledgements

- [x] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [ ] I filled out all of the requested information in this issue properly.

**Comment by CnC-Robert** [comment]
Provide more info
