### ISSUE TITLE
feat(patch): path YouTube to show and play resolution higher than 1080p. 

### ISSUE THREAD

**Issue by Anonymous2716** [revanced/revanced-patches#1626]
### Application

YouTube.

### Issue

On some devices YouTube app doesn't show resolution higher than 1080p . even tho the device can play media on higher resolution. Maybe spoof some info for it and show options for higher res on videos that has higher resolution and play.

### Patch

I currently do not know exactly which info to spoof.

### Motivation

YouTube app restricts video resolution up to 1080p even tho the device can play in higher resolution videos .(the device screen resolution might not be 4k or near). Therefore it would be great to watch videos in higher resolution.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
If the device screen resolution is not higher than that, it is unnecessary to increase the resolution of the video.

**Comment by Anonymous2716** [comment]
@oSumAtrIX its not 4k but its higher than 1080p and there are other resolutions too between 4k and 1080p (1440p).

Off topic but Also I was thinking if revanced can add 720 normal resolution alongside 720p60hz like I can on newpipe.

**Comment by oSumAtrIX** [comment]
If your phone supports the resolution, YouTube should show it to you as well if the video is available in that resolution.

**Comment by Anonymous2716** [comment]
My device can play smoothly but YouTube doesnt show the options. Its always up to 1080p. And yes the video is higher than 1090p. Thanks.

**Comment by oSumAtrIX** [comment]
What device do you have?

**Comment by Anonymous2716** [comment]
Phone.

**Comment by oSumAtrIX** [comment]
This is insufficient information.

**Comment by Anonymous2716** [comment]
Its mt6757cd I believe and screen height is ~1920.

**Comment by oSumAtrIX** [comment]
Your phone is capable of displaying 1080p at max (1920x1080) which matches what YouTube gives you as max resolution.
