### ISSUE TITLE
Unlock Squid premium

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [ReVanced/revanced-patches#1628]
### Application

Squid, a note-taking app
https://play.google.com/store/apps/details?id=com.steadfastinnovation.android.projectpapyrus

### Issue

Some very useful features are behind paywall, like PDF import and different styled paper

### Patch

Unlock premium

### Motivation

This could be very useful for people who are using this app to take notes. And potentially reducing the use of physical paper, so it it more eco-friendly

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Closing according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#%EF%B8%8F-guidelines-for-requesting-or-contributing-patches). Thanks anyways.
