### ISSUE TITLE
feat(patch): Twitch 3rd Party Emote Integration 

### ISSUE THREAD

**Issue by BanthaFood** [revanced/revanced-patches#1632]
### Application

Twitch

### Issue

Integration of 3rd party Emotes

### Patch

Implementation of add-ons like 7TV and co to have 3rd party emotes in the stock twitch app.

### Motivation

Emotes are a vital part of the twitch community. Normally you'd use browser extensions, 3rd party chat programs or something similar, but this patch would mean a more integrated experience if you can just see the emotes as emotes and not as text in the patched twitch app.

(I have skimmed through the other patch requests and didn't find a similar issue like mine, might have missed it tho since I didn't completely read every single one)

### Acknowledgements

- [x] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
#1124

**Comment by oSumAtrIX** [comment]
#1318
