### ISSUE TITLE
feat(patch): YT - Disable swiping down to exit fullscreen gesture

### ISSUE THREAD

**Issue by kyoforkshomebrews** [revanced/revanced-patches#1636]
### Application

YouTube

### Issue

I often accidentally exit fullscreen when I just want to go to the quick settings to change something.

### Patch

Just a simple patch that disables this.

### Motivation

I think this probably is an annoyance for not just me but other people as well.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Not sure how this happens. You simply "tap" instead of swipe.

**Comment by kyoforkshomebrews** [comment]
maybe I worded it weirdly, I mean swiping down the status bar.

**Comment by oSumAtrIX** [comment]
The phone adds a "safe space" to swipe from the top. I'll open this issue if it shows demand.
