### ISSUE TITLE
Patch Request: Duolingo (premium)

### ISSUE THREAD

**Issue by clawwwie** [ReVanced/revanced-patches#1637]
### Application

Duolingo
https://www.apkmirror.com/apk/duolingo/duolingo-duolingo/

### Issue

Duolingo has premium features, which are all client side and can be modded in. However, mods that do this are increasingly out of date and don't fix some of the annoying popups duo gives its users

### Patch

-Enable premium features
-Disable popups such as update notifications, friend notifications, reward/streak notifications
-disabled the popups in timed challenges that try to gut users for in-app currency (they can currently be swiped away due to an oversight and allow lessons to continue, so disabling them entirely could work?)

### Motivation

Duolingo's mobile app is basically notoriously ad ridden. That alone makes it fit in line with reddit and twitter, also sites that have mods to remove premium feature paywalls
It's super popular as far as language learning services go, but accessing APK mods is not easy at all

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by ThatOneCalculator** [comment]
It's a shame this was discontinued. Any plans to bring it back?

**Comment by oSumAtrIX** [comment]
Refer to https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#%EF%B8%8F-guidelines-for-requesting-or-contributing-patches
