### ISSUE TITLE
Old layout for video quality settings doesn't work on YouTube 17.26.35 + stats for nerds are active by default (don't work)

### ISSUE THREAD

**Issue by HeroGalak** [revanced/revanced-patches#164]
I built youtube revanced using: cli v2.3.3 ; patches v2.12.0 ; youtube v17.26.35 (apkmirror bundle). For some reason the old layout for video quality settings is not restored by the patch + stats for nerds are active by default (even if you go to settings you can't disable them).

This is an issue i just reported on https://discord.com/channels/952946952348270622/996402844129304707

Screeshot:
![demonstration](https://user-images.githubusercontent.com/69464248/178501604-d0120719-40e1-45ff-a942-e84d42c48948.jpg)

**Comment by OxrxL** [comment]
Yeah...I can repro this on my custom client too.

Could be a bug from Google (especially the one of stats for nerds).

**Comment by oSumAtrIX** [comment]
>  If not, patch older compatible versions and check when it is fixed

You forgot this.

**Comment by HeroGalak** [comment]
When I return home I'm going to do it

**Comment by HeroGalak** [comment]
I patched version 17.25.34 with no results, then with version 17.24.35 the problem seems to be solved

Version 17.25.34 (no results):
![image](https://user-images.githubusercontent.com/69464248/178565485-8db05fe9-6129-4543-8875-747e0fa58c1c.png)

Version 17.24.35 (solved):
![image](https://user-images.githubusercontent.com/69464248/178565587-455f0b48-5a16-4dc2-946b-d47c33ff2392.png)
