### ISSUE TITLE
bug: In certain devices, gesture volume goes up to 150, instead of 15.

### ISSUE THREAD

**Issue by d3EyedRaven** [ReVanced/revanced-patches#1646]
### Type

Other

### Bug description

On certain devices (I have Redmi Note 10 Pro), the volume with gestures enabled goes up to level 150 instead of 15. The drag speed is also same as level 15, so in one drag maximum volume I can change is 30. That's 5 full drags to change from min to max volume and max to min.

### Steps to reproduce

1. Enable gesture for brightness and volume

2. Use volume gesture to increase or decrease volume

3. Instead going through level 0 through 15, it goes 0 through 15 with same slow drag speed.

### Relevant log output

```shell
sorry not available
```

### Solution

Currently it's 100 levels for brightness with high drag sensitivity, and 15 levels for volume with low drag sensitivity.

I think it's fair to do 30 levels of brightness and volume in all devices, as in MX Player, (or 100 as in VLC Android) for the same drag sensitivity.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Youngei402tw** [comment]
I am still having this issue, I had a poco f6 pro

**Comment by Youngei402tw** [comment]
This issue should not be closed, the issue still excist, and the pushed commit has a wrong reference to this issue, the pushed commit is about twitter not youtube...

**Comment by Dinesh6252** [comment]
Same issue on my Oneplus 12
