### ISSUE TITLE
feat(patch): App Ops Unlock Premium 

### ISSUE THREAD

**Issue by DraconicNEO** [ReVanced/revanced-patches#1647]
### Application

App Ops
https://play.google.com/store/apps/details?id=rikka.appops

### Issue

Remove paywall from app functionality on sorting by permission, changing default behaviors for new apps, setting a template, and backing up current permissions.

### Patch

The patch should unlock the premium features stated above and allow the user to use them, even on a device without Google Play services.

### Motivation

App Ops is a very useful tool for modifying low-level permissions of Android apps and being able to deny permissions without the apps complaining or knowing that they were denied.

In the current state the app is very much crippled and would benefit from having these features unlocked and the paywall removed, as there is no free alternative to this app that still currently works on later Android versions.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Closing according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#%EF%B8%8F-guidelines-for-requesting-or-contributing-patches). Thanks anyways.
