### ISSUE TITLE
feat(patch):  Restore to YouTube settings

### ISSUE THREAD

**Issue by Qaz-7** [revanced/revanced-patches#1648]
### Application

YouTube

### Issue

Restore button to return to YouTube settings.Reset the settings in the Layout section to the default YouTube settings

### Patch

YouTube settings have been changed by default in the ReVanced app.There should be a function to reset other settings except ads thanks to this button, the settings on the player and home page will return to the default view

### Motivation

Disabling these settings one by one becomes annoying.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by ILoveOpenSourceApplications** [comment]
You can exclude the unnecessary patches and avoid this situation in the first place?

**Comment by oSumAtrIX** [comment]
You can reset the app settings. A function to just reset the layout settings is too specific and unpractical
