### ISSUE TITLE
bug(YouTube - Signature spoofing): Some clips do not start playback at the correct start time

### ISSUE THREAD

**Issue by LadyHaywood** [ReVanced/revanced-patches#165]
### Bug description

When spoof app signature is on playback is normal but clips will start from the beginning of the video. Turning spoofing off will fix clips playback but normal videos will stop playing after awhile as if it's trying to load.

I'm using the most recent supported app and had patched everything with the app manager.

### Solution

Fixing clips playback while spoof is enabled

### Additional context

I did see someone talk about something similar where their videos would stop but their audio kept playing. While my problem has the video stop completely I still I tried using the older spoof options that was suggested in the layout settings but I still have the same problem.

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by LadyHaywood** [comment]
> I think this issue was recently fixed?

Using current supported YouTube and repatched everything just to make sure, I'm still having this problem with clips.

**Comment by oSumAtrIX** [comment]
Please send reproduction steps

**Comment by YT-Advanced** [comment]
@LisoUseInAIKyrios In my side, Clips in Your Clips parameter start with `kAIB` and we already have a fix for it 🤔 Can you debug and check the parameter too

**Comment by oSumAtrIX** [comment]
Is this issue still occuring?
