### ISSUE TITLE
feat: use Android SDK instead of Java 17 for patches

### ISSUE THREAD

**Issue by Canny1913** [ReVanced/revanced-patches#1651]
### Application

N/A

### Issue

N/A

### Patch

N/A

### Motivation

N/A

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
The correct implementation would imply Kotlin Multiplatform. Though, CLI is never really run in the Android environment to begin with, it makes no sense, like it does for libraries
