### ISSUE TITLE
feat(patch): hide Instagram stories ads

### ISSUE THREAD

**Issue by Maremelows** [revanced/revanced-patches#1653]
### Application

Instagram

### Issue

Ads in stories on Instagram

### Patch

Hide ads in stories on Instagram

### Motivation

The Instagram application is a widely used application worldwide, and the increasing number of advertisements in this application day by day is becoming annoying for users using the application, and this annoying situation will disappear thanks to this patch I recommend.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
#1652
