### ISSUE TITLE
fix(patch): make `hide-views-stats` patch compatible with latest versions

### ISSUE THREAD

**Issue by kazimmt** [revanced/revanced-patches#1654]
### Application

Twitter

### Issue

`Hide-views-stats` fails in latest versions.

### Patch

`hide-views-stats` hides the post views stats from Twitter

### Motivation

All other patches are compatible with all twitter versions. I know all patches are independent, but it's a request to make `hide-views-patches` compatible with latest twitter versions for example: 9.75.0-release.0, 9.76.0-release.0 & upcoming 9.77.0-release.0

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
RE: d984bdc8b17dea127880b696ee1bed1503762707

**Comment by kazimmt** [comment]
> RE: [d984bdc](https://github.com/revanced/revanced-patches/commit/d984bdc8b17dea127880b696ee1bed1503762707)

It'll make it compatible with 9.71.0-release.0 not the latest version. 
This patch works with 9.71.0 from beginning.

**Comment by oSumAtrIX** [comment]
The patch is constrained to that version, it's neither a bug nor a patch request. When the PR is merged this issue will be closed.

**Comment by yujinlin0224** [comment]
search feature in twitter 9.71.0 is not working now, I am compelled to use the newest of Twitter to make search feature functional, please make this patch compatible with newest of twitter (9.95.0) so I can use twitter with this patch without losing search feature

**Comment by kazimmt** [comment]
> search feature in twitter 9.71.0 is not working now, I am compelled to use the newest of Twitter to make search feature functional, please make this patch compatible with newest of twitter (9.95.0) so I can use twitter with this patch without losing search feature

This issue is already closed.
Create a new issue.
