### ISSUE TITLE
feat(patch): Adobe Photoshop Express without Adobe Account

### ISSUE THREAD

**Issue by anxiouslelimo** [revanced/revanced-patches#1655]
### Application

Adobe Photoshop Express (https://play.google.com/store/apps/details?id=com.adobe.psmobile&hl=en_US&gl=US)

### Issue

Photoshop express requires users to sign in with adobe id or google account to use the application.

### Patch

Adobe Account Bypass to bypass sign in

### Motivation

Adobe Photoshop Express is a good image editor but the forced requirement to sign in/create account is a serious privacy concern with adobe data collection and usage policies.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
#2468
