### ISSUE TITLE
`Bypass-URI-redirect` patch is broken after latest patches

### ISSUE THREAD

**Issue by johnconner122** [revanced/revanced-patches#1657]
### Type

Error at runtime

### Bug description

Open a video, go to discription, click a link, youtube.com/redirect will appear. Even though it should be bypassed! 

### Steps to reproduce

Step 1: Go to revanced settings ->MISC->turn on Bypass-URI-redirect, if not already
Step 2: Open a video, go to discription, click a link, youtube.com/redirect will appear. 

### Relevant log output

```shell
Null
```

### Screenshots or videos

![Screenshot_2023-02-22-17-45-27-222_com brave browser](https://user-images.githubusercontent.com/107796137/220623458-e0070d14-e19b-45bf-a67f-42c61daf9ec6.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Patch is subject for removal due to lack of usecase/motivation why it even exists in the first place
