### ISSUE TITLE
problem: `swipe control patch bug`

### ISSUE THREAD

**Issue by Divivats** [revanced/revanced-patches#166]
## 🐞 Issue

if you use swipe control patch and exclude the full screen panel patch then the comments won't scroll in full screen.

## ⚙ Reproduce

This video shows the bug.

https://user-images.githubusercontent.com/108374606/178543721-9247a6c4-11ef-41cc-8ffa-bbf33ceb2dde.mp4

**Comment by anyz0** [comment]
then disable swipe-control

**Comment by Divivats** [comment]
> then disable swipe-control

That would work obviously but i am just trying to let the developers know about the bug.
Would be better if the bug is fixed😊

**Comment by shadow578** [comment]
seems like swipe-controls (wrongfully) 'steals' the scroll event from the fullscreen engagement panel. 
Should be a pretty easy fix, just have to adjust the active zones for swipes a bit when the panel's active. 

I'll be working on a fix asap


> Would be better if the bug is fixed😊

absolutely

**Comment by Divivats** [comment]
> seems like swipe-controls (wrongfully) 'steals' the scroll event from the fullscreen engagement panel. Should be a pretty easy fix, just have to adjust the active zones for swipes a bit when the panel's active.
> 
> I'll be working on a fix asap
> 
> > Would be better if the bug is fixed😊
> 
> absolutely

Thanks a lot 🥰🥰
