### ISSUE TITLE
feat(patch): FilmoraHD

### ISSUE THREAD

**Issue by AMSAMSAMSAMS** [ReVanced/revanced-patches#1661]
### Application

https://play.google.com/store/apps/details?id=com.wondershare.filmora&hl=en&gl=US

### Issue

Unlock the premium/pro version.

### Patch

Just unlock the premium/pro version. The cloud feature is unpatchable as it's server sided, but no matter as we can save the work offline just fine.

### Motivation

This is the best video editor app for Android. The other apps is just too hard to use. Beside, this app can sync the work with the PC version & phone version (mod apk available out there).

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Closing according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#%EF%B8%8F-guidelines-for-requesting-or-contributing-patches). Thanks anyways.
