### ISSUE TITLE
Photomath error: Missing required components

### ISSUE THREAD

**Issue by stepanzak** [revanced/revanced-patches#1669]
### Type

Error at runtime

### Bug description

When I patch Photomath v8.19.0 from Play Store and install it, it throws an error saying:

_Installation failed

The app Photomath is missing required components and must be reinstalled from the Google Play Store._

### Steps to reproduce

Download Photomath from Play Store.
Patch it with only _unlock pro_ patch.
Open it.
Error.

### Relevant log output

```shell
.
```

### Screenshots or videos

![Screenshot_20230224-134345](https://user-images.githubusercontent.com/99094176/221183418-b0668abd-719e-481e-abff-19df14ba8bf8.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
You need a full apk

**Comment by stepanzak** [comment]
Thank you.
Can you please point me to where can I download it?
I looked at APK mirror and it isn't there.
I don't know any other safe sites.

**Comment by oSumAtrIX** [comment]
You will have to source it yourself, ReVanced doesn't provide APKs

**Comment by GGORG0** [comment]
I have the exact same problem on 8.20.0 and after 2 hours of searching I still wasn't able to find anything that works. Well, what should I be even searching for (if the patch even works on 8.20.0)?
