### ISSUE TITLE
feat(patch): YouTube Music, enable A11+ persistent media player when app is closed

### ISSUE THREAD

**Issue by Ciancy28** [revanced/revanced-patches#1670]
### Application

YouTube Music

### Issue

YouTube Music Premium enables the Android 11+ persistent media player when the app is closed, this doesen't currently happen with ReVanced Music.  

### Patch

The patch should enable the Android 11+ persistent media player, allowing playback to resume. even when the app is closed.

### Motivation

It would add a useful feature that is currently available on YouTube Music Premium but missing on ReVanced.   

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by ILoveOpenSourceApplications** [comment]
Can you share an image of what this A11+ persistent media player is?

**Comment by Ciancy28** [comment]
![photo_2023-02-24_17-02-54](https://user-images.githubusercontent.com/77066322/221227072-54f55fc5-c689-40bf-a377-4e3e2fa42b9f.jpg)

This is how it looks on Android 13 with Spotify.   
When you close YTM Premium/Spotify, the media player remains in the notification shade, and you can resume playback by pressing the play button, this doesen't happen in revanced.

**Comment by Ciancy28** [comment]
> Have you tried/used this said feature with YT Music premium?

No, because I don't have a YT Premium subscription.

**Comment by ILoveOpenSourceApplications** [comment]
> > Have you tried/used this said feature with YT Music premium?
> 
> No, because I don't have a YT Premium subscription.

Then how come you believed such a feature existed with premium?

**Comment by oSumAtrIX** [comment]
Motivation is insufficient, you can open the app and play your music
