### ISSUE TITLE
bug: Twitter - Failed to apply "hide-ads".

### ISSUE THREAD

**Issue by togetg** [revanced/revanced-patches#1673]
### Type

Error while patching

### Bug description

I get an error when trying to apply the "hide-ads" patch to Twitter.

### Steps to reproduce

Twitter app version is v9.71.0-release.0
Android 13

### Relevant log output

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding Androidanifest.xml only
because resources are not needed
Failed to apply hide-ads: 'hide-
ads' depends on 'json-hook' but
the following error was raised:
Could not find integrations
Repacking patched apk
Not compiling resources because
resource patching is not required
Writing modified dex files
```

### Screenshots or videos

![Screenshot_20230225_094659](https://user-images.githubusercontent.com/18244518/221326367-d6215cd4-70c8-46f3-bfdb-3c96587d6f88.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
#1658
