### ISSUE TITLE
feat: Restore the built-in Call Recording feature on the Google Phone app

### ISSUE THREAD

**Issue by mina-gaid** [ReVanced/revanced-patches#168]
### Feature description

Develop and release a patch that restores the built-in call recording feature on the official Google Phone app, where this feature is locked/hidden by Google due to regional regulations. This patch should allow users to access and use the phone recording feature regardless of their region using the Google Phone app.

The functionality already exists on the Google Phone app but is now locked/hidden in certain regions or devices, as per the official documentation: 
https://support.google.com/phoneapp/answer/9803950?hl=en

Certain markets, such as India, still have access to the Call Recording feature.

The Pixel line up offered Call Recording via the Google Phone app until it was removed (hidden/locked) following an update.

Attached - Screenshot of call recording on the Google Phone app before it was removed:

![google-phone-call-recording-xda-1](https://github.com/ReVanced/revanced-patches/assets/15611727/8a9354aa-1ef8-441e-8e49-b4f0978b5acf)

### Motivation

Many users require access to their device’s built-in call recording feature for legitimate purposes. However, due to regional regulations, some OEMs lock this feature, limiting the user’s ability to fully utilize their device. By enabling this feature, we can improve the user experience by adding comprehensive control over our devices.

On some devices, such as OnePlus, the call recoding feature can be unlocked via an ADB Command (Non-Root). However, this doesn't work on all phones, such as the Pixel range because every OEM has their own modified version of the stock Android phone app. By specifically patching the official Google phone app, all Android users can be catered for regardless of device because the app is available to download on the Play store - and more often than not, it's most people's default choice.

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by Pheggas** [comment]
> @mina-gaid call recording can be enable easily if u have this XML file. If rooted copy to product/etc/permission. And check.
> 
> https://dumps.tadiphone.dev/dumps/redmi/sky/-/blob/missi_phone_global-user-13-TKQ1.221114.001-V14.0.5.0.TMWINXM-release-keys/product/etc/permissions/com.google.android.apps.dialer.call_recording_audio.xml
> 
> Demerit of Googledialer is call announce. Which need patch
> 
> Revanced patch idea also good. Let's wait for dev to add this feature

Is there a way for non-rooted devices?

**Comment by mina-gaid** [comment]
@Pheggas Nope, and the XML option is both tedious and temporary.
That's why I'm requesting a patch for this.

**Comment by validcube** [comment]
Is this really possible, isn't the permission required for call recording locked behind a system permission called `CAPTURE_AUDIO_OUTPUT`?

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
