### ISSUE TITLE
feat(patch):  add ytdlnis to pre-added downloaders.

### ISSUE THREAD

**Issue by soymadip** [revanced/revanced-patches#1683]
### Application

Youtube

### Issue

There is a new client for ytdlp. 

### Patch

There's a new yt-dlp client for Android :- [ytdlnis](https://github.com/deniscerri/ytdlnis) 

Package name :-  com.deniscerri.ytdl

It will be so good if this is added to pre-added downloaders under Revanced settings> overlay settings> downloader settings.

### Motivation

If this app is added to pre-added downloaders, users can have more options. 

And then dev of the app can find more motivation to make the app better. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Motivation does not make sense, users already have the option to chose any package of choice.

**Comment by soymadip** [comment]
> Motivation does not make sense, users already have the option to chose any package of choice.

Yeah, but more choice is better 😅
It's way easier to press a button than manually entering the package name 😅

**Comment by oSumAtrIX** [comment]
Doesn't virtually add any benefit, it should be agnostic to any package and adding predefined packages is the contrary.
