### ISSUE TITLE
bug: (YT) Hide create, clip and thanks buttons option also hides share button under videos with a live chat button

### ISSUE THREAD

**Issue by n1cKz1** [revanced/revanced-patches#1687]
### Type

Error at runtime

### Bug description

If you only select the option "Hide create, clip and thanks buttons" in Hide action buttons and then go to a video that has a Live chat button under it, the share button will also be removed.

### Steps to reproduce

Step 1. Enable "Hide create, clip and thanks buttons" option
Step 2. Go to a video that was live streamed and therefore has a Live chat button, like this one: https://www.youtube.com/watch?v=f_PM1rKGBXE
Step 3. The share button is gone along with the create, clip and thanks ones.

### Relevant log output

```shell
-
```

### Screenshots or videos

Before enabling:
![before](https://user-images.githubusercontent.com/107653639/221876057-6daae451-5063-4268-a3a0-0f4f02b24d06.jpg)
After enabling:
![after](https://user-images.githubusercontent.com/107653639/221876200-76cee971-b3fd-47e0-9ad6-3ec0cdc18f63.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
#1538
