### ISSUE TITLE
feat(patch): Disable Zoom not working

### ISSUE THREAD

**Issue by LAMBORGUINI** [revanced/revanced-patches#1688]
### Application

YouTube ReVanced 18.03.36 Patch 164

### Issue

correction

### Patch

Disable Zoom fix , because there is an error in the patch

### Motivation

because there is an error in the patch

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by ILoveOpenSourceApplications** [comment]
Can you clarify on what the issue you are facing?

**Comment by ILoveOpenSourceApplications** [comment]
@LAMBORGUINI if you don't share further information, we can't resolve whatever the issue you're facing.

**Comment by LAMBORGUINI** [comment]
only thing I can share is making a video and showing that the zoom is still working, even activated for it not to work, this activated for the Zoom to work

https://user-images.githubusercontent.com/125999493/222192064-ecf6b819-d049-4701-aa13-b5cd53152ef2.mp4

**Comment by ILoveOpenSourceApplications** [comment]
So you want a patch to disable the zoom-in functionality in video?

**Comment by LAMBORGUINI** [comment]
we already have this Patch , Hactic Zoom , but it is not working we deactivate it and the zoom continues

**Comment by ILoveOpenSourceApplications** [comment]
> we already have this Patch , Haptico Zoom , but it is not working we deactivate it and the zoom It is continues

Disable zoom haptics doesn't remove the zoom functionality, it removes the haptic feedback one receives when zooming in and out of a video.

**Comment by LAMBORGUINI** [comment]
Ha got it What's it for now then, So we don't have Patch to disable this Zoom

**Comment by LAMBORGUINI** [comment]
I will open a patch request for this

**Comment by ILoveOpenSourceApplications** [comment]
Okay
