### ISSUE TITLE
problem: `general-ads` toggles

### ISSUE THREAD

**Issue by OxrxL** [revanced/revanced-patches#169]
## 🐞 Issue

Some general ads patches don't have a settings toggle, but just a direct setvisibility reference.

## 🛠 Solution

Change setvisibility with a reference to a dedicated method inside settings.

## ⚠ Additional context

https://github.com/revanced/revanced-patches/blob/main/src/main/kotlin/app/revanced/patches/youtube/ad/general/bytecode/patch/GeneralBytecodeAdsPatch.kt

**Comment by oSumAtrIX** [comment]
Please explain your issue.
