### ISSUE TITLE
Twitter Patch (Problem)

### ISSUE THREAD

**Issue by Exorcism0666** [revanced/revanced-patches#1691]
### Type

Error while patching

### Bug description

Some patches are not applied with the new Twitter update.

### Steps to reproduce

Step 1. Download the latest apk Twitter from APKMirror

Step 2. Choose the following patches "Hide Ads", "Monochrome Icon", "Dynamic color" and "Hide Recommended Users"

Step 3. Patch the apk and normally the error should appear.

Android: 12
Realme 8

### Relevant log output

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Deleting existing resource cache directory
Decoding resources
Applied dynamic-color
Failed to apply hide-ads: 'hide-ads' depends on 'json-hook' but the following error was raised: Could not find integrations.
Failed to apply hide-recommended-users: 'hide-recommended-users' depends on 'json-hook' but the following error was raised: 'json-hook' did not succeed previously
Applied monochrome-icon
Repacking patched apk
Compiling resources
Writing modified dex files
Finished!
```

### Screenshots or videos

![Screenshot_2023-03-01-09-58-25-58_a85b47aaa863e3bc831e16d29c27a79c](https://user-images.githubusercontent.com/46537034/222092666-1c081e93-b724-4159-9e7d-f7f47262befc.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by clawwwie** [comment]
I've been noticing the same issue

**Comment by Hikarikun42** [comment]
i got this error 

`[builder] SEVERE: hide-ads failed:
[builder] app.revanced.patcher.patch.PatchResultError: 'hide-ads' depends on 'json-hook' but the following error was raised: Could not find integrations.
[builder] at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:311)
[builder] at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:37) at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:355) at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127) at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:83) at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:20) at app.revanced.cli.command.MainCommand.run(MainCommand.kt:152) at picocli.CommandLine.executeUserObject(CommandLine.java:2026) at picocli.CommandLine.access$1500(CommandLine.java:148)
[builder] at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461) at picocli.CommandLine$RunLast.handle(CommandLine.java:2453) at picocli.CommandLine$RunLast.handle(CommandLine.java:2415) at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273) at picocli.CommandLine$RunLast.execute(CommandLine.java:2417) at picocli.CommandLine.execute(CommandLine.java:2170) at app.revanced.cli.main.MainKt.main(Main.kt:7)
[builder] SEVERE: hide-recommended-users failed:
[builder] app.revanced.patcher.patch.PatchResultError: 'hide-recommended-users' depends on 'json-hook' but the following error was raised: 'json-hook' did not succeed previously at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:311) at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:37) at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:355)
[builder] at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127) at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:83) at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:20) at app.revanced.cli.command.MainCommand.run(MainCommand.kt:152) at picocli.CommandLine.executeUserObject(CommandLine.java:2026) at picocli.CommandLine.access$1500(CommandLine.java:148) at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461) at picocli.CommandLine$RunLast.handle(CommandLine.java:2453) at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
[builder] at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273) at picocli.CommandLine$RunLast.execute(CommandLine.java:2417) at picocli.CommandLine.execute(CommandLine.java:2170) at app.revanced.cli.main.MainKt.main(Main.kt:7)`
