### ISSUE TITLE
Playlists + Ambient Mode

### ISSUE THREAD

**Issue by VioletStorm** [revanced/revanced-patches#1697]
### Type

Other

### Bug description

Unable to have both ambient mode and playlists available at the same time when patched. After patching, playlists disappear. To fix, I enable version spoofing. However this causes ambient mode to disappear. Both playlists and ambient mode work at the same time on unpatched YouTube.

I am on the latest compatible version of everything at the time of this report, and am patching via root.

### Steps to reproduce

1 Patch YouTube
2 Try to have both playlists and ambient mode available at once

### Relevant log output

```shell
N/A
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by ILoveOpenSourceApplications** [comment]
Can you share the list of patches?

**Comment by VioletStorm** [comment]
![Screenshot_20230303-034028.png](https://user-images.githubusercontent.com/54405427/222672896-dc73e115-2988-429f-b544-603f094f7dd8.png)

**Comment by ILoveOpenSourceApplications** [comment]
If you enable spoof app version obviously you'll be loosing ambient mode, as the app believes it's running a version which came before ambient mode was a thing. So no surprise there. But the playlist part is what I'm confused here.

**Comment by ILoveOpenSourceApplications** [comment]
In the patch list, I only see 1 patch that can cause some issues but I don't know whether it'll solve yours, but can you try repatching without "Predictive Back Gesture" included.

**Comment by VioletStorm** [comment]
> In the patch list, I only see 1 patch that can cause some issues but I don't know whether it'll solve yours, but can you try repatching without "Predictive Back Gesture" included.

I'll try and report back to you soon

**Comment by VioletStorm** [comment]
> In the patch list, I only see 1 patch that can cause some issues but I don't know whether it'll solve yours, but can you try repatching without "Predictive Back Gesture" included.

I've removed the patch but playlists still refuse to show without enabling spoof
![Screenshot_20230303-041244_YouTube.png](https://user-images.githubusercontent.com/54405427/222680261-d699c52d-cbbf-4c34-9bb1-14a58a6e117a.png)

**Comment by ILoveOpenSourceApplications** [comment]
Can you try with minimal patches at first like just general ads and video ads and see if it's still there.

**Comment by clawwwie** [comment]
Completely unrelated to ambient mode, playlists are broken for me too
