### ISSUE TITLE
Not loading on both old YouTube Vanced and new ReVanced, was last night with same app versions

### ISSUE THREAD

**Issue by PeterKW** [revanced/revanced-patches#1703]
### Type

Error at runtime

### Bug description

I will put the screenshots of version numbers etc. in the comments

### Steps to reproduce

.

### Relevant log output

```shell
.
```

### Screenshots or videos

![Screenshot_20230304-170400.png](https://user-images.githubusercontent.com/13779157/222919397-409276ce-79a1-458e-a816-d01d70e6d277.png)

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [ ] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Insufficient information provided

**Comment by PeterKW** [comment]
Please don't close my bug report! I don't know what other information I need to give? I don't understand what's happening with the app but I can't use it at the moment.

What information can I provide?

**Comment by oSumAtrIX** [comment]
The issue template asked for reproduction steps

**Comment by PeterKW** [comment]
I don't know how to reproduce it.  Vanced logged in says an error occurred, and ReVanced says I don't have any accounts when I do?

**Comment by oSumAtrIX** [comment]
Remove all applications related to ReVanced and reproduce the issue, report back all steps in detail

**Comment by oSumAtrIX** [comment]
As @LisoUseInAIKyrios assumed, it could be related to MicroG, reinstall it.

**Comment by PeterKW** [comment]
Thank you all very much! Is this the best version do you think? https://github.com/TeamVanced/VancedMicroG/releases/tag/v0.2.24.220220-220220001
