### ISSUE TITLE
AdGuard

### ISSUE THREAD

**Issue by ghost** [ReVanced/revanced-patches#1704]
### Application

AdGuard

### Issue

Using AdGuard pro features.

### Patch

AdGuard premium features can be used.

### Motivation

Because this ad blocker is used a lot.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Bread-Ch4n** [comment]
Would be awesome to have this patch since the free version doesnt let u add ur own lists by url and some are vlocked behind pro.
