### ISSUE TITLE
feat(patch): [Reddit] Disable in App Browser 

### ISSUE THREAD

**Issue by 2latemc** [revanced/revanced-patches#1706]
### Application

Disabling the in App Browser of reddit

### Issue

Reddit has a really annoying in App browser, you could disable this with older versions of reddit, but now it is impossible to disable this. It's also really annoying, because you cannot copy links.

### Patch

A feature to just open links in the default browser.

### Motivation

This feature would be so helpful and would save everyone much pain. Everyone who has used reddit probably knows what I am talking about

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
#780

**Comment by j9d3it** [comment]
Hello, this is still an issue on the latest version, there is no option to open links in external browsers. Can this be reopened and a patch implemented? Now with third-party apps going away this would be a great feature to have.
