### ISSUE TITLE
feat(patch): MicroG

### ISSUE THREAD

**Issue by Qaz-7** [revanced/revanced-patches#1708]
### Application

YouTube

### Issue

https://github.com/inotia00/VancedMicroG
This project has been closed.Will there be an updated MicroG?
We need MicroG to run ReVanced

### Patch

Will there be a new MicroG project?

### Motivation

😔

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
The `microg-support` patch depends on [Vanced MicroG](https://github.com/TeamVanced/VancedMicroG).

**Comment by oSumAtrIX** [comment]
Vanced MicroG currently works perfectly fine. If there is a need for a fork, it will be done via upstream [GmsCore](https://github.com/microg/GmsCore).
