### ISSUE TITLE
feat(patch): Hide-(WhateverTheseAre)-Under-Videos

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [revanced/revanced-patches#1710]
### Application

YouTube 

### Issue

These "supposed thingy" under videos shows multiple things now. It's the products that are mentioned in the videos, it can be chapters that are auto generated and key moments. Who knows what more they'll include in this small thingy.

Products:
![221582265-a5b41f33-9bb1-4756-802b-6f209954374b](https://user-images.githubusercontent.com/117499019/223070183-a991f080-8446-45ad-9c10-d4cce7bbe969.png)

Chapters:
![Screenshot_20230306-143832~2](https://user-images.githubusercontent.com/117499019/223070283-181c0b1b-bd2b-4b6c-9a90-cd9b2fc23c34.png)

Key Moments:
![Screenshot_20230306-143849~2](https://user-images.githubusercontent.com/117499019/223070370-179f0a5e-fc8e-4914-a548-4edc4ede3fdc.png)

### Patch

A patch which would just disable this thingy irrespective of whatever it shows. (I'm calling it so as I can't classify whether it's a banner or a pop-up or a whatever)

### Motivation

It's usage seems pretty insignificant. Unless
1. One wants to know what all the products used in the video are.
2. One strictly want to jump into a video without even playing in the first place.
3. Key moments isn't a thing that should be there in all videos and only depending on the contents.
4. For whatever the future holds from YouTube.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Please use the debugging patch and enable debug logging. Use the command `logcat | grep GeneralAds | grep Unblocked`. Reload the patch so that these components are rendered, and respond with the log output.

**Comment by ILoveOpenSourceApplications** [comment]
I don't have a system at my disposal atm to run adb, so any Android app alternative recommendations?

**Comment by oSumAtrIX** [comment]
You can use logcat on Android.

**Comment by ILoveOpenSourceApplications** [comment]
Can you guide me how to, I'm kinda lost without a system.

**Comment by oSumAtrIX** [comment]
[This](https://github.com/MasterDevX/Termux-ADB) might be helpful.

**Comment by ILoveOpenSourceApplications** [comment]
I got adb installed via termux, now how do I capture the logs you require

**Comment by ILoveOpenSourceApplications** [comment]
> Please use the debugging patch and enable debug logging. Use the command `logcat | grep GeneralAds | grep Unblocked`. Reload the patch so that these components are rendered, and respond with the log output.

What does "reload the patch" here mean?

**Comment by oSumAtrIX** [comment]
I meant reload the *page*.

**Comment by ILoveOpenSourceApplications** [comment]
When I run "logcat | grep GeneralAds | grep Unblocked" as it is, I'm not seeing any log data in the list.

**Comment by ILoveOpenSourceApplications** [comment]
Am I supposed to run a second command to capture the log ?

**Comment by ILoveOpenSourceApplications** [comment]
So, logcat | grep GeneralAds
Then logcat | grep Unblocked?

**Comment by ILoveOpenSourceApplications** [comment]
I know I'm bothering you with this, but I can't find any articles or videos which can guide me related to this matter. So if you can point me towards one, I'll try my best to follow the introductions in it.

**Comment by oSumAtrIX** [comment]
I believe this is a matter which can be solved faster if I can reproduce this issue on my end. Unfortunately, my account does not get these ads which is why I would need access to an account to be able to fix it. Reach out to me at osumatrix@revanced.app, if you want to help in that regard.

**Comment by ILoveOpenSourceApplications** [comment]
Giving an access to the account which has this issue so you can run the log and see right?

**Comment by oSumAtrIX** [comment]
Yes.

**Comment by ILoveOpenSourceApplications** [comment]
For some reason this issue has disappeared from the account. So closing this as it's no longer present.
