### ISSUE TITLE
No Restrictions 

### ISSUE THREAD

**Issue by BrandgrandRealMe** [revanced/revanced-patches#1720]
### Application

YouTube 

### Issue

I hate restricted mode being forced 

### Patch

A patch that stops YouTube from being redirected to restricted  YouTube (cause my schools wifi does this) And bypasses "this video is age restricted"

### Motivation

It helps people not be bothered with restricted mode

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
#1378
