### ISSUE TITLE
feat(patch): Hide Subscriptions button on paused Shorts

### ISSUE THREAD

**Issue by StopUsingOutdatedCrap** [ReVanced/revanced-patches#1722]
### Application

Youtube

### Issue

When you pause a Short, there is a "Subscriptions" button that shows up at the top left side of the screen.
The problem is that when trying to continue a Short, you can accidentally hit that button instead, causing a new Short to pop up and play.

This can be quite annoying.

### Patch

A patch that makes that button impossible to appear (Hiding it).

### Motivation

Such a patch would allow ReVanced users to more comfortably use Shorts by allowing them to continue playing a Short without having to pay attention to not accidentally hit that button and start a new Short.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
For me it shows up the entire time, it's very small and hard to hit when playing or pausing.

**Comment by n1cKz1** [comment]
I know this is a relatively old issue, but for any potential future patch the litho component name is "button.eml" under the parent "shorts_paused_state.eml". (shorts_paused_state.eml|c68951e54dfd690f|ContainerType|ContainerType|button.eml)

**Comment by n1cKz1** [comment]
I got a notification and had to check. Is this supposed to be implemented in latest patches release? If so, the button still shows up for me, no toggle to hide it in settings either
