### ISSUE TITLE
bug: Youtube Shorts player getting stuck

### ISSUE THREAD

**Issue by StopUsingOutdatedCrap** [revanced/revanced-patches#1724]
### Type

Other

### Bug description

When watching a bunch of Shorts, seemingly randomly when swiping to the next Short, the Shorts "player" gets stuck, not playing the Short, even when trying to pause and unpause it again, it refuses to play.
Even swiping to the previous or next Short does not fix it (Even the previous Short that just ran fine is now also stuck).
Only closing Shorts completely and reopening them (By for example clicking on a Short on the Home screen) fixes it.

### Steps to reproduce

Watch a bunch of shorts?

### Relevant log output

```shell
There is no crash
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
I was able to reproduce this instantly on the unpatched app as well, seems like a YouTube bug
