### ISSUE TITLE
feat(YouTube): Add rewind and fast forward buttons to lock screen

### ISSUE THREAD

**Issue by CanYouJustWorkPlease** [ReVanced/revanced-patches#1726]
### Application

Youtube ReVanced

### Issue

Hi! First of all, thank you for creating this! You are awesome!

There is no way to rewind or fast forward while at the lock screen using touch. Currently, at the lock screen, you can only play/pause, skip to next video and skip to previous video using touch.

There is no way to rewind or fast forward using a gamepad while a video is playing in the next 3 modes:

1. Video is playing and is open in ReVanced interface.
2. Video is playing at lock screen.
3. Video is playing while the screen is turned off.

The gamepad's rewind/fast forward buttons seem to work with other apps, so it's not an issue with hardware.
[This ](https://v3.hamiltonbuhl.com/hammanual/Universal%20VR%20Remote%20Controller-Manual-d10.pdf)is the gamepad that I've used:
<p align="center">
<img src="https://user-images.githubusercontent.com/73692469/203363398-45e2a1ef-d1a8-457f-8fdd-2a802436053d.jpg" width="75" height="200">
</p>
Currently, in any of the 3 modes, using a gamepad, it's only possible to play/pause, skip to next video and skip to previous video.

I've checked this out on:

Phone: Huawei P40 lite E
Android: 10
YouTube ReVanced: 17.43.36
ReVanced Manager: 0.0.40

### Patch

It would be nice to have at the lock screen 2 more buttons, among the 3 other buttons mentioned above. The two buttons should consist in one for rewind and one for fast forward.

Also, it would be nice if rewind and fast forward would work when:
1. Video is playing and is open in ReVanced interface.
2. Video is playing at lock screen.
3. Video is playing while the screen is turned off.

The same 3 modes as described at "Issues".

Thank you!

### Motivation

While listening to audiobooks I find myself drifting away into my thoughts, and when I return back to reality I have to rewind since I've missed out all what's been said in the meantime. 

The problem is that I do this a lot, since I like imagining what's happening in the books, and I have to turn on the screen, unlock it and then rewind, which is getting really tedious, especially since I'm doing this most of the time before sleep.

Also, lately I've tried using a gamepad with ReVanced, through bluetooth, to control how the audiobooks/other videos play, but I've noticed that there's no way I can control rewind/fast forward while the screen is turned on, turned off or at lock screen, even though the gamepad's rewind/fast forward buttons work with other apps. If which it would work it would make things a way lot easier.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
