### ISSUE TITLE
feat(patch) AI mirror

### ISSUE THREAD

**Issue by YashjitPal** [revanced/revanced-patches#1728]
### Application

Ai Mirror

### Issue

The premium paid feature for free. 

Note: This is a newly released app

### Patch

Watermark removal
Unlocked assets
Ads gone

### Motivation

Because it's a very useful app and it's features are amazing

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Every app is somewhat useful, that's not really a motivation

**Comment by YashjitPal** [comment]
> Every app is somewhat useful, that's not really a motivation 

This is in short disappointment
