### ISSUE TITLE
feat(patch): Unlock PRO - Repainter

### ISSUE THREAD

**Issue by diegonogaretti** [ReVanced/revanced-patches#1730]
### Application

Repainter

### Issue

We have a patch which unlocks pro features of IconPack Studio. Please make one for Repainter too

### Patch

Unlock PRO features of Repainter

### Motivation

Repainter is the ultimate customization app for Material You

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by khaled-0** [comment]
this is needed more as the app got taken down and license verification is no longer working
