### ISSUE TITLE
feat(YouTube): Add/Restore annotations for older videos that support the feature

### ISSUE THREAD

**Issue by JustaRandomUser12** [ReVanced/revanced-patches#1731]
### Application

YouTube

### Issue

Around 2008, YouTube added a feature to their website known as "Annotations", allowing for users to display shortcuts, information, and more on top of their video using the Annotations Editor. In 2019, however, YouTube shut down the entire feature as to replace it with End Screens and Cards. 

While End Screens and Cards are useful, annotations were just better, due to unlimited control as to how you wanted to display your shortcuts. Many old videos supported Annotations, and many were ruined when Annotations were removed.

However, an extension was created around 2019 called "**[Annotations Restored](https://github.com/isaackd/AnnotationsRestored)**", which aims to bring annotation support back to YouTube for the videos that support it. Like **[SponsorBlock](https://github.com/ajayyy/SponsorBlock)** or **[RYD](https://github.com/Anarios/return-youtube-dislike)**, I hope that this extension could somehow be turned in to a patch and added to the main YouTube app. There are a few issues, however, such as how Annotations were never added to the mobile YouTube app (but could _maybe_ be added, seeing as how SponsorBlock is original too).

Nevertheless, I hope this patch request can be considered, and I hope that annotations could _maybe_ be added in the future!

### Patch

Patch to add/restore YouTube Annotations to old videos that support it

### Motivation

Video without Annotations (Lifeless):
https://www.youtube.com/watch?v=kuNixp-wvWM

Video with Annotations (Not Lifeless):
https://www.youtube.com/watch?v=fbuVW1QbX1k

### Acknowledgements

- [x] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
