### ISSUE TITLE
feat(patch): raw youtube search results

### ISSUE THREAD

**Issue by castdrian** [revanced/revanced-patches#1731]
### Application

YouTube

### Issue

The YouTube client does not render search results like they are returned by the api, it instead meddles around with all the bloat you get like "For You", "Could be Interesting", Shorts etc... it also likes to ignore displaying tiny channels or videos with tiny amounts of views (no matter what sorting option is selected), whilst the api actually returns all those entries.

### Patch

Ideally it should not be a persistent setting, as sometimes you would want to have the ML modified search results, but rather a toggle in the results top bar akin to the "Unwatched" and "Recently Watched" pills that you can select, which will then reload the view with the results as they are returned.

### Motivation

There is a chromium extension for web that unbloats the search results, and for Android you can use NewPipe to achieve the same result, but it would be nice to have a toggle in the search UI that allows you to just browse the raw search results

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
I don't know what you mean by raw search results. This is returned by the API:

![Screenshot_2023-03-11-13-58-09-68_64ef5fc2000c1caa954c114bb372e1d5](https://user-images.githubusercontent.com/13122796/224485900-7e36ea89-a860-460d-934d-0d54b4d304c4.jpg)

**Comment by castdrian** [comment]
make call to the data api it will not return all this crap
![Screenshot_20230311_152220_YouTube](https://user-images.githubusercontent.com/22133246/224490492-d7cec3d8-dac2-4b41-b7df-db135792295b.jpg)

**Comment by oSumAtrIX** [comment]
https://github.com/revanced/revanced-patches/issues/1660
