### ISSUE TITLE
question: twrp flashable build

### ISSUE THREAD

**Issue by MondayNitro** [revanced/revanced-patches#1733]
### Application

is it possible to have twrp flashable revanced builds?

### Issue

in earlier days of vanced, we had a vanced apk (you cannot install this vanced apk like normal apk) and a twrp installer zip within which you could paste the vanced apk and flash it in recovery. twrp vanced had a clear advantage in that no microg was needed and also there was no need to install a separate stock youtube from playstore(root method). **_is it possible currently to have twrp revanced builds? since i remember we did not have twrp builds of vanced since version 14.21.54_**

### Patch

not a patch, i couldnt find the question tag, sorry :(

### Motivation

twrp builds removed the mount filure/error inconvenience where stock youtube replaces root build of revanced, and did not need microg as well

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
ReVanced does not provide patched apps.
