### ISSUE TITLE
Promoted ad in Twitter comment section & search.

### ISSUE THREAD

**Issue by 11xjas** [ReVanced/revanced-patches#1733]
### Application

Twitter

### Issue

As the subject says, there are few promoted ad content in trending search page and also in comment section.

### Patch

Patch request to block promoted content in comment section and trending search page.

### Motivation

 
![Screenshot_20221120-235210_Twitter](https://user-images.githubusercontent.com/93155066/202919176-9a44348b-056c-424e-8da1-9ca91d36a6c0.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Moving to #286
