### ISSUE TITLE
YouTube Queue

### ISSUE THREAD

**Issue by BrandgrandRealMe** [revanced/revanced-patches#1735]
### Application

YouTube

### Issue

The website has a Queue you can make but the app doesn't .

### Patch

Make a way to create a Queue in the app.

### Motivation

I miss having the queue when I am on mobile. It's a useful tool!

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
#1141

**Comment by GalaxyVOID** [comment]
This is a bit different since the feature is here, but it needs premium to use. The other requests requested for the feature to be implemented

**Comment by Lamby777** [comment]
#1141 is still locked (literally 1984), so I'll just say it here...

Not sure how you guys write these patches, but just wanted to say the "add to queue" feature is free on the web version of YouTube. If the queue is managed server-side, you guys might still be able to use the web version's API instead or something.
