### ISSUE TITLE
ReVanced site

### ISSUE THREAD

**Issue by ghost** [ReVanced/revanced-patches#1743]
### Application

ReVanced

### Issue

https://revanced.io/
https://www.ryzn.site/revanced.html
https://revanced.net/
Is this site official?

### Patch

.

### Motivation

.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by vancedyou** [comment]
Best revanced site on [youtube vanced ](https://vancedyoutub.org/)
