### ISSUE TITLE
bug(youtube/video-speed): do not apply default video playback speed when watching live streams

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [revanced/revanced-patches#1744]
### Type

Error at runtime

### Bug description

Using remember playback rate when watching livestreams will cause the livestream to buffer

### Steps to reproduce

1. Watch any video that is not a livestream
2. Set the playback rate to something ridiculous (5x)
3. Exit that video
4. Watch a livestream such as [this](https://youtu.be/jfKfPfyJRdk) 
5. Buffering will happen in less than 2 minutes even if you have good connection
6. Repeat from step 1 but choose something normal like 2x, observe that the issue still happens but slower
7. the latency row in stats for nerds will give more information

### Relevant log output

```shell
Not relevant: this is a logic issue
```

### Solution

When clicking to the livestream, reset to 1x speed, but do not force 1x the entire time, as people may want to catch on from behind with higher playback rate

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by SodaWithoutSparkles** [comment]
@philklc Your approach is better.

**Comment by HunterAPI** [comment]
Can this patch also have the ability to disable the custom playback speed for videos that are songs? Maybe with a prompt at the start for the video like asking if you'd like to play the video at 1x if it detects it as a song.

**Comment by oSumAtrIX** [comment]
They should be combined, essentially the same feature: "Disable for specific video categories".

**Comment by HunterAPI** [comment]
There's a YouTube feature where you tap and hold the video and it changes the playback speed to 2x with a label in the middle saying "Playing at 2x speed" until you let go. There should also be an option to set a custom speed for the "fast forward".

**Comment by m-sundman** [comment]
> They should be combined, essentially the same feature: "Disable for specific video categories".

No, this ticket is not about disabling the custom speed for the live video. It's about disabling the custom speed **while watching live**. This is not a video category, but a playback state.

**Comment by oSumAtrIX** [comment]
The category is livestream.

**Comment by YT-Advanced** [comment]
@oSumAtrIX @LisoUseInAIKyrios For livestream, you can use videocpn instead of videoidhook to check if a video is livestream or not.

**Comment by oSumAtrIX** [comment]
Please give detailed information, cryptic messages like this are difficult to understand.

**Comment by YT-Advanced** [comment]
> Please give detailed information, cryptic messages like this are difficult to understand.

By default, Revanced use videoidhook to check, when new video open, it called Playback Speed Patch to notify that new video loaded. But it mean livestream video will be applied default playback speed too. To solve this problem, you should use videocpn (check the commit below) because only normal video be called when use videocpn

https://github.com/inotia00/revanced-patches/commit/78e86a192b883c2d57ffcd82da8bb1b8e56ae1d4

**Comment by m-sundman** [comment]
> The category is livestream.

No. Read again. Just because a video is "livestream" doesn't mean that we don't want to use the default speed. We still want to use the default speed even for livestream videos. However, we want to use normal playback speed when we are watching live. You can watch a livestream live or not live. Do you see the difference between a "livestream video" and "watching live"?

**Comment by oSumAtrIX** [comment]
@m-sundman This is exactly the issue described in #1744

> Using remember playback rate when watching livestreams will cause the livestream to buffer

And the solution you describe is described in #1744

> When clicking to the livestream, reset to 1x speed, but do not force 1x the entire time, as people may want to catch on from behind with higher playback rate

**Comment by SodaWithoutSparkles** [comment]
What @m-sundman is describing is another solution to the same issue.

Lets clarify the terms a bit. 

- Normal video: videos that are uploaded
- livestreams: videos that have their length extended every second
- watching live: watching livestreams very close to real-time
- stream recaps: videos that youtube autonatically generate from completed livestreams

------

Using "remember playback speed" on livestreams does not automatically make it buffer. Suppose the situation is like this: a stream started 2 hrs ago, and i now watch it, with playback speed defaulted to 2x by the patch.

Now there are 5 seconds left (youtube will consider a short enough buffer to be "watching live") and i play at 2x, so i will catch-up in 2.5 seconds. Then because the buffer is too short, it wait for a new segment, hence the buffer.

So the solution (1) is not to apply the 2x speed and leave it at the 5 seconds.

But the downside is i have to manaully change the speed back to 2x if i wanna watch the livestream record from 2hrs ago. 

------

Hence the solution (2) sundman proposed: Don't apply the 2x speed automatically if clicked on a livestream, check if i am watching it live first. If so, don't apply the 2x speed. When I go back to watch the 2hrs that i missed, it should apply the 2x speed as it won't have any buffering issues. Essentially, if timestamp of the livestream decreased, playback speed should be applied (2x), until buffer nearly runs out (i.e. Watching live), then the patch should kick in once again to make the playback speed be 1x to avoid the buffer.

------

Solution 2 is obviously more complicated, but it has a higher degree of automation, and i agree that it is better (https://github.com/ReVanced/revanced-patches/issues/1744#issuecomment-1515992595).

**Comment by m-sundman** [comment]
> And the solution you describe is described in #1744
> 
> > When clicking to the livestream, reset to 1x speed, but do not force 1x the entire time, as people may want to catch on from behind with higher playback rate

Yes, the proposed solution is the same as I'm describing. He's literally saying that it should NOT force 1x just because it's a livestream, but only when actually watching live (i.e., at the very end of the livestream while that's being appended to).

> Solution 2 is obviously more complicated, but it has a higher degree of automation, and i agree that it is better

Is it that much more complicated, tho? I mean, the player obviously knows when it's live, and when it's playing the past of the livestream, because of that little red dot that lights up whenever it's playing live. So why not just force 1x speed whenever that little dot turns red, and then go pack to the chosen speed when the dot turns grey again? No complications needed, really.

**Comment by oSumAtrIX** [comment]
It is complicated to implement is what he is referring to.

**Comment by SodaWithoutSparkles** [comment]
I do mean it is more complicated to implement. For solution 1 only a simple check has to be implemented. For solution 2 a new logic flow has to be created. The following is some pseudocode i imagined.

Solution 1
```
...

if(isLiveStream(video)):
  # do nothing
  return

...
```

Solution 2
```
...

func handleNotLive():
  setPlaybackSpeed(default)
  return
func handleLive()
  setPlaybackSpeed(1.0)
  return
addListener(timestampDecrease, handleNotLive)
addListener(videoAtLive, handleLive)

...
```

**Comment by oSumAtrIX** [comment]
You contradict yourself though because you say you do not mean the implementation is more complicated while showing that the implementation is more complicated.

**Comment by m-sundman** [comment]
> I do mean it is more complicated to implement.

Your solution 2 is not **that much** more complicated than your solution 1 (which is actually wrong, since that "# do nothing" should actually be "setPlaybackSpeed(1.0)"). It's very insignificantly more complicated.

Also, I'm pretty sure that's how youtube normally operates, is it not? At least it's how vanced used to work. I always use higher speed, and it always used to switch to 1x when I caught up to live. Only fairly recently have I encountered this problem where it tries to use the higher speed despite being live, and it's really, really annoying.

**Comment by oSumAtrIX** [comment]
@m-sundman I don't think you can asses the implementation difficulty at all, otherwise I suggest to open a PR in case you want to

**Comment by SodaWithoutSparkles** [comment]
> You contradict yourself though because you say you do not mean the implementation is more complicated while showing that the implementation is more complicated.

Read again...

> I **do** mean it is more complicated to implement.

**Comment by oSumAtrIX** [comment]
I already know, the comment was marked as hidden for that reason before you commented.

**Comment by m-sundman** [comment]
> I don't think you can asses the implementation difficulty at all, otherwise I suggest to open a PR in case you want to

I can perfectly well assess the pseudocode in @SodaWithoutSparkles comment https://github.com/ReVanced/revanced-patches/issues/1744#issuecomment-1692419864 and as for assessing the real code I never attempted it, but if you'd read what I write, as I've asked repeatedly, you'd notice that I **asked** if it really is _that much more_ complicated, considering it's youtube's default behavior (AFAIK), and seems to have existing signal/listener connection points where it might be easy to integrate.
And why are you being so hostile anyway?

**Comment by oSumAtrIX** [comment]
The pseudocode does not reflect the implementation difficulty. I am not trying to sound hostile if that looks like I do.

**Comment by m-sundman** [comment]
https://github.com/ReVanced/revanced-patches/blob/main/src/main/kotlin/app/revanced/patches/youtube/video/speed/remember/patch/RememberPlaybackSpeedPatch.kt
Is this the file in question?
At least at first glance it's not apparent to me exactly how it works.

**Comment by Voruos** [comment]
So there is no fix till now? Will be waiting...
