### ISSUE TITLE
feat(TikTok): Material you / dark theme to

### ISSUE THREAD

**Issue by ardx812** [ReVanced/revanced-patches#1744]
### Application

com.zhiliaoapp.musically

### Issue

The app itself only has one theme which is the light mode. 

### Patch

Bring a material you theming, if not possible, a dark mode.

### Motivation

Because the default theming is unpleasant and also hurts the eye a lot and also It doesn't fit any other android app.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Dark mode is available in latest version, which the patches in the linked PR now support.

**Comment by oSumAtrIX** [comment]
Thats unrelated to this issue
