### ISSUE TITLE
bug: Videos stop playing and you have to restart them

### ISSUE THREAD

**Issue by Ukiuki23** [revanced/revanced-patches#1753]
### Type

Error while patching

### Bug description

When you play videos they play for a while and then the video stops, it turns black and beggins an endless buffering. The only way for the video to continue is leaving the video and playing it again.

### Steps to reproduce

Step 1 open  a video

### Relevant log output

```shell
No log output
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by kazimmt** [comment]
Patch YT with latest patches.
It'll fix buffer issue.

**Comment by Patient6038** [comment]
I'm on revanced version 18.05.40 and Im getting this issue

**Comment by Patient6038** [comment]
I tried using the latest patch with just default patches and I still have this issue.
