### ISSUE TITLE
feat(patch): Wallet Unlock Premium

### ISSUE THREAD

**Issue by iamargelh** [revanced/revanced-patches#1769]
### Application

https://play.google.com/store/apps/details?id=com.droid4you.application.wallet

### Issue

Export option to PDF, and Excel is exclusively for Premium users.
I would like to export my expenses.

### Patch

Premium Features Unlock 

### Motivation

It's a useful app, one of the most valorated on the store.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by iamargelh** [comment]
Something I don't find in the actual financial apps that revanced patch, is how you can do a revalance an account, if the app says I have 20$ but somehow I didn't record for 2 or 3 days I really have 37.62$, I don't want to do the maths to rebalance my account, so the app allows you to do that kind of things. UI comforts me as well. I'm from LATAM, so Lifetime Premium is something I can't buy.

**Comment by oSumAtrIX** [comment]
With the amount of patch requests, the motivation for this patch is insufficient 
, thanks anyways.
