### ISSUE TITLE
feat(patch): Always 120hz (youtube)

### ISSUE THREAD

**Issue by Reiayanami24** [revanced/revanced-patches#1780]
### Application

Youtube

### Issue

The ability to force an app wide 120hz

### Patch

While watching a video, to be able to keep a device's 120hz active.

When a video is in mini mode, be able to keep 120hz active.

While browsing the YouTube app, to be able to keep 120hz active.

### Motivation

It seems youtube made a regression, or at least on my device.  On YouTube 15.05.54 I was able to run the YouTube at at always 120hz but now that I'm using YouTube 18.05.40, I've discovered that as soon as I open a video, my refresh rate tanks to 60hz, making the whole app feel extremely sluggish.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Iirc this is controlled by the phone/manufactor, when have you tried the old YouTube version?

**Comment by Reiayanami24** [comment]
> Iirc this is controlled by the phone/manufactor, when have you tried the old YouTube version?

It was about 3 days ago.  I was using Youtube 15.05.54 Vanced.  I got the "youtube there was a problem with the server 404" and could not fix the issue.  I tried restarting my phone.  I tried reinstalling that version of revanced.  I replicated the issue with youtube vanilla 15.05.54.  Sadly it's not a vanced specific problem.

**Comment by kryptobolt200528** [comment]
if you really need the 120Hz you might wanna try using ytvanced 17.03.38

**Comment by Reiayanami24** [comment]
> if you really need the 120Hz you might wanna try using ytvanced 17.03.38

Thanks, I'll give that a try. 
I've been looking around to see what may be able to fix my issue and I stumbled upon this article that uses "setedit" app to try to force 120hz.  Although it didn't work for me, I realized I was able to force the setedit app itself to 120hz, so maybe it could be used for revanced? (https://www.guidingtech.com/how-to-force-high-refresh-rate-on-all-android-apps/).  If this code could be forced into youtube vanced perhaps it'd be able to force the app to constantly run 120hz.

**Comment by proxykingdev** [comment]
most videos are 24 and 60 fps. really isn't a need for 120 on YouTube wide. by default app runs on 120 on supported devices until you play a video. 

![Screenshot_2023-03-30-12-37-09-75_64ef5fc2000c1caa954c114bb372e1d5](https://user-images.githubusercontent.com/109734850/228750534-40b54492-fda9-47ad-b22b-3239eb99c132.jpg)

![Screenshot_2023-03-30-12-37-15-62_64ef5fc2000c1caa954c114bb372e1d5](https://user-images.githubusercontent.com/109734850/228750629-05dcae35-1f47-494f-adb7-59dbd1c1d1c0.jpg)

**Comment by Reiayanami24** [comment]
> most videos are 24 and 60 fps. really isn't a need for 120 on YouTube wide. by default app runs on 120 on supported devices until you play a video.
> 
> ![Screenshot_2023-03-30-12-37-09-75_64ef5fc2000c1caa954c114bb372e1d5](https://user-images.githubusercontent.com/109734850/228750534-40b54492-fda9-47ad-b22b-3239eb99c132.jpg)
> 
> ![Screenshot_2023-03-30-12-37-15-62_64ef5fc2000c1caa954c114bb372e1d5](https://user-images.githubusercontent.com/109734850/228750629-05dcae35-1f47-494f-adb7-59dbd1c1d1c0.jpg)

Unfortunately on my device it refuses to run at 120hz.  I was hoping to force it to run at 120hz.  Yes, videos run at 60hz, but while viewing a YT video, I also tend to scroll through the YT app which feels sluggish when ran at 60hz vs 120hz.  When no video is running the app will run at 120hz though.  Probably a device specific issue.  But nonetheless was hoping there'd be a patch for this issue.

**Comment by kairusds** [comment]
/

> > most videos are 24 and 60 fps. really isn't a need for 120 on YouTube wide. by default app runs on 120 on supported devices until you play a video.
> > ![Screenshot_2023-03-30-12-37-09-75_64ef5fc2000c1caa954c114bb372e1d5](https://user-images.githubusercontent.com/109734850/228750534-40b54492-fda9-47ad-b22b-3239eb99c132.jpg)
> > ![Screenshot_2023-03-30-12-37-15-62_64ef5fc2000c1caa954c114bb372e1d5](https://user-images.githubusercontent.com/109734850/228750629-05dcae35-1f47-494f-adb7-59dbd1c1d1c0.jpg)
> 
> Unfortunately on my device it refuses to run at 120hz. I was hoping to force it to run at 120hz. Yes, videos run at 60hz, but while viewing a YT video, I also tend to scroll through the YT app which feels sluggish when ran at 60hz vs 120hz. When no video is running the app will run at 120hz though. Probably a device specific issue. But nonetheless was hoping there'd be a patch for this issue.

that's a hardware and software limitation, phones don't have the same screens as desktop monitors does so this isn't possible to achieve on most phones without the proper screen panel
