### ISSUE TITLE
feat(patch): Make Gapps to use Vanced MicroG

### ISSUE THREAD

**Issue by cheadrian** [ReVanced/revanced-patches#1784]
### Application

Google Maps, Google News, Google Play, GMail and others apps made by Google.

### Issue

Huawei don't support native Gapps anymore, so this way it could enable it's users to use, at least, some of the Google Apps native on device.

### Patch

Simple patch other Google apps to use Vanced MicroG, like in the case of the Youtube.

### Motivation

Lack of GMS for Huawei.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by pogobanane** [comment]
requesting to reopen. Would you accept a contribution of a universal patch to "use vanced microg instead of standard google play services"? Afaik users can then choose to apply this patch to whatever app they want.

**Comment by oSumAtrIX** [comment]
@pogobanane the issue is a duplicate of https://github.com/ReVanced/revanced-patches/issues/1583
