### ISSUE TITLE
feat(patch): Sort Videos by oldest first

### ISSUE THREAD

**Issue by rustokomuska** [revanced/revanced-patches#1785]
### Application

Youtube Revanced

### Issue

Sort videos on a channel by oldest

### Patch

when viewing a channel, allow users to sort from the oldest videos first

### Motivation

Original Youtube vanced still had the feature and it was a needless removal

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
#1200
