### ISSUE TITLE
bug: Sometimes Youtube Short is loading forever

### ISSUE THREAD

**Issue by trmdi** [revanced/revanced-patches#1787]
### Type

Error at runtime

### Bug description

Sometimes Youtube Short shows loading forever, until you swipe up and down the same video. After that, it works normally.

When testing the original Youtube, the first time you see a short, it displays a text like "Click on the video to watch" and only plays after that. Maybe this relates to the bug?

The bug can be reproduced randomly after several hours.

**Comment by oSumAtrIX** [comment]
This also happens on the unpatched app

**Comment by trmdi** [comment]
> This also happens on the unpatched app

Yes but the thing is the original app askes the user to click on the video while revanced app only shows the loading icon without any text. It's hard to understand what's happening.

**Comment by oSumAtrIX** [comment]
I was able to reproduce the loading without the text on the unpatched app

**Comment by trmdi** [comment]
Ah you are right, I just confirm that.
