### ISSUE TITLE
feat(youtube/general-ads): hide-product-you-might-like in search

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [revanced/revanced-patches#1788]
### Application

YouTube 

### Issue

When you search for a specific product, in the search results there's a "products you might like" section which shows all the site and prices related to the product. 

![Screenshot_20230321-202445](https://user-images.githubusercontent.com/117499019/226647846-1de8bb95-3187-4fda-9c39-e7886732259f.png)

Upon pressing the drop down arrow:
![Screenshot_20230321-202457~2](https://user-images.githubusercontent.com/117499019/226647941-fc7aa832-25cd-4d1c-bd30-3606a8f02e28.png)

### Patch

A patch to hide this from the search, similar to hiding web results from the search.

### Motivation

I believe a similar patch is already present and also this is an ad promotion or web search result and so it's better hidden.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
This doesn't show up for me. You can find the component name using the debug option and logging

**Comment by ILoveOpenSourceApplications** [comment]
You need to scroll down in the search a bit after searching a specific product inorder to see this.

**Comment by ILoveOpenSourceApplications** [comment]
Can you search for a smartphone just like I did and see if it reproduces?

**Comment by oSumAtrIX** [comment]
Enable debug logging in the settings, use logcat and grep for "GeneralAds". Then render the ad by scrolling through the feed and it'll log names

**Comment by ILoveOpenSourceApplications** [comment]
I don't have a system for this process though.

**Comment by ILoveOpenSourceApplications** [comment]
Can you try to replicate this issue with a VPN or something on your side?

**Comment by ILoveOpenSourceApplications** [comment]
Hey @oSumAtrIX, I have my system with me now and can run adb. Can you provide a good source so I can run the necessary commands to capture the logs?

**Comment by ILoveOpenSourceApplications** [comment]
[logcat.txt](https://github.com/revanced/revanced-patches/files/11185801/logcat.txt)
Is this what that's necessary?

**Comment by oSumAtrIX** [comment]
Only send the relevant logged line.

**Comment by ILoveOpenSourceApplications** [comment]
May I ask how I do that?

**Comment by oSumAtrIX** [comment]
Once you render the ad, it'll log the relevant line.

**Comment by ILoveOpenSourceApplications** [comment]
Just copy that part only?

**Comment by oSumAtrIX** [comment]
Yeah, only that part is relevant.

**Comment by ILoveOpenSourceApplications** [comment]
[logcat.docx](https://github.com/revanced/revanced-patches/files/11185953/logcat.docx)
I hope this is satisfactory.

**Comment by oSumAtrIX** [comment]
I can not view this file. Please send in plaintext or a .log/.txt file.

**Comment by ILoveOpenSourceApplications** [comment]
[logcat.txt](https://github.com/revanced/revanced-patches/files/11185959/logcat.txt)
Now?

**Comment by oSumAtrIX** [comment]
The file contains over hundrets line of code, whereas a single one is relevant, please filter for it

**Comment by ILoveOpenSourceApplications** [comment]
[logcat 1.txt](https://github.com/revanced/revanced-patches/files/11185996/logcat.1.txt)

**Comment by ILoveOpenSourceApplications** [comment]
I sorted through the list and picked a few codes addressed as product_detail, product_offer, shopping_flagging & offer_box.

**Comment by oSumAtrIX** [comment]
Can you send the lines where you picked them up?

**Comment by ILoveOpenSourceApplications** [comment]
04-09 21:38:55.735 30294 30445 D revanced: GeneralAdsPatch: Unblocked (ID: null): product_details_unit.eml|675a06fc3702f4ab|CellType|product_details_unit_inner.eml|55f5e838d58ee90f|ContainerType|ContainerType|ContainerType|image_carousel.eml|84df4659c2ac3e4c|ContainerType|
04-09 21:38:55.740 30294 30445 D revanced: GeneralAdsPatch: Unblocked (ID: null): product_details_unit.eml|675a06fc3702f4ab|CellType|product_details_unit_inner.eml|55f5e838d58ee90f|ContainerType|ContainerType|ContainerType|ContainerType|ContainerType|ContainerType|ContainerType|share_button.eml|101691ddbcd35151|ContainerType|icon_button.eml|7378c659c6674e05|ContainerType|ContainerType|ImageType|
04-09 21:52:49.533 30294 30294 D revanced: GeneralAdsPatch: Unblocked (ID: null): product_details_card.eml|5ad874f57ae6714d|product_details_card_slots.eml|125685225f172d06|CellType|ContainerType|ContainerType|ContainerType|product_image.eml|fe74c8e800fb2fd3|ContainerType|
04-09 21:54:36.219 30294 30444 D revanced: GeneralAdsPatch: Unblocked (ID: null): product_details_unit.eml|675a06fc3702f4ab|CellType|product_details_unit_inner.eml|55f5e838d58ee90f|ContainerType|ContainerType|ContainerType|ContainerType|product_variant_options.eml|3b527ab17221ce78|ContainerType|ContainerType|ContainerType|TextType|
04-09 21:38:55.746 30294 30445 D revanced: GeneralAdsPatch: Unblocked (ID: null): product_details_unit.eml|675a06fc3702f4ab|CellType|product_details_unit_inner.eml|55f5e838d58ee90f|ContainerType|ContainerType|ContainerType|ContainerType|ContainerType|ContainerType|ContainerType|product_rating.eml|578f66de16ead32b|ContainerType|ImageType|
04-09 21:38:55.738 30294 30444 D revanced: GeneralAdsPatch: Unblocked (ID: null): product_offers_root.eml|1a2891a0d6010a48|CellType|
04-09 21:38:55.739 30294 30444 D revanced: GeneralAdsPatch: Unblocked (ID: null): product_offers_root.eml|1a2891a0d6010a48|CellType|product_offers.eml|b9a9a7c6a54c438f|ContainerType|
04-09 21:38:55.740 30294 30444 D revanced: GeneralAdsPatch: Unblocked (ID: null): product_offers_root.eml|1a2891a0d6010a48|CellType|product_offers.eml|b9a9a7c6a54c438f|ContainerType|ContainerType|ContainerType|ImageType|
04-09 21:38:41.175 30294 30445 D revanced: GeneralAdsPatch: Unblocked (ID: shopping_flagging.eml|358877f61d521676): shopping_flagging.eml|358877f61d521676|CellType|
04-09 21:38:41.176 30294 30445 D revanced: GeneralAdsPatch: Unblocked (ID: null): shopping_flagging.eml|358877f61d521676|CellType|ContainerType|
04-09 21:38:41.176 30294 30445 D revanced: GeneralAdsPatch: Unblocked (ID: null): shopping_flagging.eml|358877f61d521676|CellType|ContainerType|ImageType|
04-09 21:38:41.176 30294 30445 D revanced: GeneralAdsPatch: Unblocked (ID: null): shopping_flagging.eml|358877f61d521676|CellType|ContainerType|TextType|
04-09 21:38:55.715 30294 30444 D revanced: GeneralAdsPatch: Unblocked (ID: null): offer_box_root.eml|d7fc5637d245cffc|CellType|offer_box.eml|3b31d86ca26472b8|ContainerType|ContainerType|ContainerType|ContainerType|ContainerType|
04-09 21:38:55.715 30294 30444 D revanced: GeneralAdsPatch: Unblocked (ID: null): offer_box_root.eml|d7fc5637d245cffc|CellType|offer_box.eml|3b31d86ca26472b8|ContainerType|ContainerType|ContainerType|ContainerType|ContainerType|ImageType|
04-09 21:38:55.716 30294 30444 D revanced: GeneralAdsPatch: Unblocked (ID: null): offer_box_root.eml|d7fc5637d245cffc|CellType|offer_box.eml|3b31d86ca26472b8|ContainerType|ContainerType|ContainerType|ContainerType|TextType|

**Comment by ILoveOpenSourceApplications** [comment]
Is this what you asked for?

**Comment by oSumAtrIX** [comment]
Looks good, try adding `product_details` to the custom filter. Then check if the ad is gone. Make sure by grepping the logs for `product_details`. If you see the logs, but no ads, it was blocked.

**Comment by ILoveOpenSourceApplications** [comment]
Okay, adding product_details to custom filter does remove the ad from search.

**Comment by oSumAtrIX** [comment]
Looks good, if possible, please PR this filter in integrations repo.

**Comment by ILoveOpenSourceApplications** [comment]
I have no knowledge other than that adding product_details in custom filter can fix this issue. So imo someone familiar with PR should be doing it.

**Comment by ILoveOpenSourceApplications** [comment]
Thanks.
