### ISSUE TITLE
Video preview settings

### ISSUE THREAD

**Issue by antikovt** [revanced/revanced-patches#1790]
### Application

YouTube

### Issue

After a certain update, the video preview feature was reworked. The playback now starts much faster, almost immediately as the thumbnail is on screen, and there are features to enable sound and subtitles. This has proven to be largely annoying, because the previewed videos litter the user's video history. Also, when scrolling searched videos, the sound plays automatically and there is no way to disable it.

### Patch

The patch should provide different options for the video preview, for example:
> Disable the preview completely
> Always force sound
> Always preview without sound
> Always force subtitles
> Etc.

For me, personally, the most important feature would be previewing without sound at all times, even in a search.

### Motivation

It's a fix for a feature many would consider annoying.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
#1749
