### ISSUE TITLE
feat(patch): Poweramp Music Player App

### ISSUE THREAD

**Issue by max5354** [revanced/revanced-patches#1791]
### Application

It will be great if you make patch for poweramp music player app. There is an lot of music player but poweramp is just on another level...it's audio quality also on another level. So it will be great if you make patch for poweramp. Cause poweramp is time limited trial and it will expire after 15 days....there is an lot of telegram mods channels and site that provides poweramp premium/ mod. But trust me none of them working properly means it doesn't matter from which site we download modded poweramp . It will always expires after 15 days...and after 15 days we need to reinstall that's very irritating that's why i am requesting here. So plz make patch for poweramp so we can use poweramp premium for free

### Issue

If you patch Latest version of poweramp than it will great for us. Means we can use poweramp premium for free

### Patch

Also poweramp latest version is 957. So it will be great if you make patch/premium of poweramp 957.

### Motivation

There are lots of poweramp users. And just like you made patch for yt. It will be great if you make patch also for poweramp.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
#1342
