### ISSUE TITLE
feat(patch): 

### ISSUE THREAD

**Issue by github08100192477** [revanced/revanced-patches#1792]
### Application

Re insta

### Issue

No issue 

### Patch

Add a downloading button 

### Motivation

It will be fun having a download button in re insta

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [ ] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by ILoveOpenSourceApplications** [comment]
Is Re Insta a seperate application or do you just mean Instagram itself? If not can you provide link for Re Insta.

**Comment by github08100192477** [comment]
No re insta is a new application which was patched by chirag who is the admin of telegram rvx group. He gave the link to this place so we can report new features to be added to the rvx Instagram

**Comment by github08100192477** [comment]
This is the link
https://devuploads.com/ixb7aj8oiqds

**Comment by oSumAtrIX** [comment]
Don't send unknown executables
