### ISSUE TITLE
feat(patch): TikTok InBuilt Region Changer

### ISSUE THREAD

**Issue by SCPF-Bot** [ReVanced/revanced-patches#1797]
### Application

TikTok

### Issue

As I can see on the TikTok, the videos in the feed are only limited to the region you were in so sometimes the people got bored of the same content or videos in their own region.

### Patch

I hope there will be an option or feature that can change the current region to a different ones.

### Motivation

I suggested this patch so we can also see the different TikTok contents from other regions.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Not sure but there's a sim region changer, that should be doing exactly that
