### ISSUE TITLE
feat(patch): Parcels unlock premium options

### ISSUE THREAD

**Issue by jont4** [revanced/revanced-patches#1797]
### Application

This is a app to track packages from many stores and postal services.
https://play.google.com/store/apps/details?id=com.brightstripe.parcels

### Issue

You need to subscribe a premium subscription to activate package status notifications and remove ads. 

### Patch

Unlock notifications 

### Motivation

This is a good app to track packages 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
There's free alternatives with better rating:
![image](https://user-images.githubusercontent.com/13122796/227638217-bc45ccee-0deb-48a5-99ff-91f63eb2ad81.png)

Motivation is insufficient. Most apps are great.

**Comment by Ushie** [comment]
https://play.google.com/store/apps/details?id=com.shopify.arrive

**Comment by jont4** [comment]
> ![image](https://user-images.githubusercontent.com/13122796/227638217-bc45ccee-0deb-48a5-99ff-91f63eb2ad81.png)

I've tried most of them.

**Comment by jont4** [comment]
> https://play.google.com/store/apps/details?id=com.shopify.arrive

thx, seems interesting. I'll try
