### ISSUE TITLE
feat(patch): Ads removal and Premium unlock 

### ISSUE THREAD

**Issue by introversialscalpel** [revanced/revanced-patches#1802]
### Application

Chess.com
[Chess](https://play.google.com/store/apps/details?id=com.chess) 

### Issue

The game has lots of features including lessons and videos for studying chess moves besides just playing.

### Patch

Removal of ads in the game (although they are blocked if adguard for android is in use) and premium unlock because most of the lessons are locked behind a hefty paywall.

### Motivation

Its a great game to play for the mind and has a huge amount of people playing it. But not everyone can pay for such good lessons to learn chess.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Features are controlled by the server, not the client.
