### ISSUE TITLE
feat(patch): Playing Shorts as normal videos

### ISSUE THREAD

**Issue by kryptobolt200528** [revanced/revanced-patches#1805]
### Application

Youtube 

### Issue

The default shorts player is just disgusting,you can't rewind or double tap to seek.

### Patch

The patch would be to force the youtube videos to play in the normal player,this can be done by replacing the normal short link https://youtube.com/shorts/xyz..
with
https://youtube.com/watch?v=xyz..
or https://youtu.be/xyz..
This can again be provided as a toggle under the layout menu.

### Motivation

I am pretty sure that a sizeable amount of people who watch shorts would want to play them in the normal youtube player

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by reisxd** [comment]
#969
