### ISSUE TITLE
feat(patch): block ads on story and download button for reels and stories(own and others)

### ISSUE THREAD

**Issue by iamthelara** [revanced/revanced-patches#1806]
### Application

You do not ads on stories bar but When You flip to next story you will see ads.
Add a download button for reels and stories of own story and other stories.

### Issue

Block ads on stories. On Storyline ads doesn't show but when you watch a story and when you flip to next story the  you can see ads.

### Patch

idk😄

### Motivation

Because It is necessary for making instagram perfect and ad free

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
https://github.com/revanced/revanced-patches/issues/1652
