### ISSUE TITLE
feat(windy): windy.com app premium patch 

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [revanced/revanced-patches#1807]
### Application

[windy.com app](https://play.google.com/store/apps/details?id=com.windyty.android), aka "red windy"

### Issue

Some features that was free is now behind the premium paywall. For example, 11 day forcast, 12h weather radar and satellite imagery, etc.

* this app is not the same as the windy.app app requested before. The windy.app app is also known as "blue windy".

### Patch

Unlock premium or unlock the features that were available before.

### Motivation

Windy.com app is a weather forcasting app that is used by many people. It features a smooth UI 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
API will be locked on server side, can not be unlocked client side

**Comment by SodaWithoutSparkles** [comment]
@oSumAtrIX it was not. Someone else managed to patch it. [this](https://modyolo.com/windy-com.html) is an example. [this](https://gomodapk.com/windy-com/) might be another example. If you revert to old versions you can still access it.

**Comment by oSumAtrIX** [comment]
I am not sure if these links work. Have you tried them.

**Comment by SodaWithoutSparkles** [comment]
I have tried the first one. You may also try to lookup previous versions, like those from approx. 3 months before.

**Comment by SodaWithoutSparkles** [comment]
@oSumAtrIX consider re-opening this issue?
