### ISSUE TITLE
feat(patch): default option for add to library(save)

### ISSUE THREAD

**Issue by kanishk-upadhyay** [revanced/revanced-patches#1808]
### Application

youtube

### Issue

when I'm watching a video but want to quickly add it to my watch later playlist, i have to click on save them click on save again then uncheck the playlist which my video got saved to and then select watch later and then done and believe me this is a very frustrating process

### Patch

add an option to set a default playlist for the save button. it would be either default which means the video would be saved in the playlist youtube usually saves it to or to choose a playlist so then the saved button saves the video in the selected playlist. it could be a toggle and then a drop-down menu or a drop-down menu alone where default is at the top

### Motivation

it saves from the hassle to change the playlist everytime when a video gets saved to an unintended one

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
You can hold down on the button which opens the playlist menu.
