### ISSUE TITLE
bug(youtube): Hide cast button patches even if patch not selected

### ISSUE THREAD

**Issue by Royal2000H** [revanced/revanced-patches#1811]
### Type

Error at runtime

### Bug description

In ReVanced Manager, for Youtube, whether or not you select "Hide Cast Button" patch, it gets applied. When you open your patched Youtube, it shows up in Youtube ReVanced settings.

### Steps to reproduce

Step 1: Open ReVanced Manager
Step 2: Select YouTube 18.05.40
Step 3: Only select microG patch
Step 4: Patch and install
Step 5: Open your patched Youtube, go to settings > ReVanced
You should now see that there is still a Layout > Hide Cast Button setting (it does indeed toggle and hide the Cast button)

### Relevant log output

```shell
N/A
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
`microg-support` patch depends on it, that's why it gets included.
