### ISSUE TITLE
feat(patch): 

### ISSUE THREAD

**Issue by joshuak91** [revanced/revanced-patches#1814]
### Application

Re insta

### Issue

No issue 

### Patch

Add monet theming for re insta 

### Motivation

It will be a really cool reason for a lot of people to use re insta 

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [ ] I have written a short but informative title.
- [ ] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
#1652
