### ISSUE TITLE
bug: patched twitter crashes due to missing resources

### ISSUE THREAD

**Issue by PranavPurwar** [revanced/revanced-patches#1817]
### Type

Error at runtime

### Bug description

I tried to patch twitter v9.81.1-release.0 (29811000) with Dynamic Color and Hide Ads plugin 

### Steps to reproduce

Try to patch twitter with dynamic color and hide ads plugin

### Relevant log output

```shell
can't send log as text, log is in the image
```

### Screenshots or videos

![twitter crash](https://user-images.githubusercontent.com/75154889/228618476-aa84b5b5-3f1b-4965-b988-d873f347b08f.jpg)
![Screenshot_2023-03-29-22-49-20-357_com pluscubed matlog](https://user-images.githubusercontent.com/75154889/228619147-15735881-b73f-4142-a9d1-8badb3ce6487.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
You are patching and installing a split apk, but you have to patch and install a full apk, or mount with root.

**Comment by PranavPurwar** [comment]
> You are patching and installing a split apk, but you have to patch and install a full apk, or mount with root.

I'm patching latest twitter APK file, instead of from installed apps

**Comment by oSumAtrIX** [comment]
Please record that process
