### ISSUE TITLE
feat: remember auto repeat setting in `autorepeat-by-default` patch instead of never turning it off

### ISSUE THREAD

**Issue by casual-coderr** [revanced/revanced-patches#182]
## 🐞 Issue

Whenever you play any video, the video loops even when the setting is turned off.

## ⚙ Reproduce

Built using
Revanced Cli 2.5.3
Revacnced pached 2.13.4
Revanced Integrations 0.24

**Comment by TheJeterLP** [comment]
Exclude the auto-repeat patch.

**Comment by TheJeterLP** [comment]
> IMO this is anti-user. What the patch should do is remember the state. So if you toggle it on, it will stay on, if you toggle it off, it will stay off. Simply adding an integrations method to remember the setting would be enough.

That's not what thatoarch is for. It clearly says "autorepeat-by-default" and that's exactly what it does. It's toggleable over the setting in the future, also that's why it's excluded by default

**Comment by oSumAtrIX** [comment]
> That's not what that patch is for. It clearly says "autorepeat-by-default"

The patch itself is anti-user then. A necessary QoL feature for this patch is required which is that if you toggle it on, it stays on, if you toggle it off, it stays off. (See how you skip the part where you have to toggle it on or off in the settings, which would be the same step?)

**Comment by oSumAtrIX** [comment]
Also this is how it works on YT Desktop.

**Comment by oSumAtrIX** [comment]
I would propose to rename it then `toggle-autorepeat` or `persist-autorepeat-settings-choice`

**Comment by TheJeterLP** [comment]
> > That's not what that patch is for. It clearly says "autorepeat-by-default"
> 
> The patch itself is anti-user then. A necessary QoL feature for this patch is required which is that if you toggle it on, it stays on, if you toggle it off, it stays off. (See how you skip the part where you have to toggle it on or off in the settings, which would be the same step?)

We can implement that yes. I just did what vanced did without changing anything as for the usage. But we could for sure change it.

**Comment by erez669** [comment]
not understand from docs how to disable it

**Comment by TheJeterLP** [comment]
> not understand from docs how to disable it

Then wait until the manager is done. ReVanced is currently not targeted to you then

**Comment by ILoveOpenSourceApplications** [comment]
This issue is fixed. Closing it now.
