### ISSUE TITLE
[YouTube]stop/mute autoplay in feed

### ISSUE THREAD

**Issue by Windows200000** [revanced/revanced-patches#1822]
### Application

YouTube

### Issue

When you search, some videos start playing automatically with sound on. This can cause signs to be played from your phone just by making a search. 

### Patch

When enabled, the patch should either mute videos that play automatically, or stop them from playing all together. 

### Motivation

Vidéos playing with sound automatically can annoy other people around you, or catch you off guard if you don't want others to know what you just searched. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by ILoveOpenSourceApplications** [comment]
YouTube already has a setting for this. It's called playback in feeds under General settings.

**Comment by oSumAtrIX** [comment]
https://github.com/revanced/revanced-patches/issues/1752
