### ISSUE TITLE
feat(patch): YouTube to use androidx emoji2 maven repo library

### ISSUE THREAD

**Issue by idontveapc** [revanced/revanced-patches#1830]
### Application

# YOUTUBE

### Issue

i get tofu.

### Patch

depeneency emoji2 library for androidx(Android cross versions compatibility) from jetpack or maven.

> **latest version>>**
https://mvnrepository.com/artifact/androidx.emoji2/emoji2/1.4.0-alpha01
               ```codes and everything ^↑^```

### Motivation

emojisss!!!

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by reisxd** [comment]
...?

**Comment by idontveapc** [comment]
why they closed it’s not completed?!
### “issue”
the tofu is 􏿾 displayed.

###### requested dependency would display the missing emoji from the `char sequence` number

### weird request??!
as YouTube isn't texting app it doesn't have ```emoji.compat(androidx)``` but people there use emojis of all kind, so i want it :[

**Comment by idontveapc** [comment]
why they closed it’s not completed?!
### “issue”
the tofu is 􏿾 displayed.

##### requested dependency would display the missing emoji from the `char sequence` number```(a number they give to any emoji character)```

### weird request??!
as YouTube isn't a texting app it doesn't have ```emoji.compat(androidx)``` but people there use emojis of all kind, so i want it :[

**Comment by oSumAtrIX** [comment]
The issue is not properly filled with required information.

**Comment by idontveapc** [comment]
the issue is tofu **`(􏿾)`** is displayed when an emoji or any character -_of any language(s)_- is missing from the list of system fonts.

noto fonts-_for characters/letters of any language(s)_ mostly has the characters that can a person type in any language be. and then emojis font, they update every year and android software update... you know it.


###### the thing i wanted

android had and has something -*on their android studio*- for the app and even game devs what they called it like `compat` as `emoji compat` or `appcompat` -*for cross android versions app compatibility.*- where the latest android version's features could've been made available to past android versions.

they now changed the project, that is called now **jetpack.** the version used goes like androidx.`(the compatibility devs wanted)`... the emojis compatibility feature is like **androidx.emoji_emoji.version** & **androidx.emoji2_emoji2.version**.

**Comment by idontveapc** [comment]
the issue is tofu **`(􏿾)`** is displayed when an emoji or any character -_of any language(s)_- is missing from the list of system fonts.

noto fonts-_for characters/letters of any language(s)_ mostly has the characters that can a person type in any language be. and then emojis font, they update every year and android software update... you know it.


###### the thing i wanted

android had and has something -*on their android studio*- for the app and even game devs what they called it like `compat` as `emoji compat` or `appcompat` -*for cross android versions app compatibility.*- where the latest android version's features could've been made available to past android versions.

they now changed the project, that is called now **jetpack.** the version used goes like androidx.``(the compatibility devs wanted)``... the emojis compatibility feature is like **androidx.emoji_emoji.version** & **androidx.emoji2_emoji2.version**.

**Comment by oSumAtrIX** [comment]
It is unclear what you are trying to say here.
