### ISSUE TITLE
feat(patch): 

### ISSUE THREAD

**Issue by PROMIT05** [revanced/revanced-patches#1836]
### Application

POWERAMP MUSIC PLAYER
https://play.google.com/store/apps/details?id=com.maxmpz.audioplayer

### Issue

In App Purchase 

### Patch

This app give Free trial for 14 day..
Make it parmanent 

### Motivation

Best Music Player i have ever use

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [ ] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
#1791
