### ISSUE TITLE
feat(patch): update patch(es) for My Expenses app

### ISSUE THREAD

**Issue by Govind-Rajulu** [revanced/revanced-patches#1837]
### Application

[My Expenses app](https://play.google.com/store/apps/details?id=org.totschnig.myexpenses) 

### Issue

The app is updated to 3.5.3 whereas the patch supports only 3.4.9. Tried patching the latest version but eventually fails.

### Patch

Update patches or compatibility to latest version. 
Periodic updates atleast once a month would be great.

### Motivation

Since the app is expenses manager. It does a great job and the developer updates once a month or so. What I expect is, this project by you people should not be stopped. This one is useful not only for me but also for many others.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
You can use the latest version the patch supports.
