### ISSUE TITLE
feat(patch):  need all revanced patches supported apps list

### ISSUE THREAD

**Issue by Govind-Rajulu** [revanced/revanced-patches#1838]
### Application

Snapchat and many other apps

### Issue

The patches list shows app that the available app patches. Whereas it's said that the patches support many other non-mentioned apps. If that's true.. kindly add the same.

### Patch

Add a section as unstable/experimental if the apps may or may not work at times. Also is it possible for us to try pre-release patches via manager. If yes, how to confirm the same.

### Motivation

I have been following the revanced project since you people began working on. Even though I don't know to code. I still find your project useful. I would like to help from the non-coding/implementation side

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
The list in the README file is complete
