### ISSUE TITLE
feat(patch): More options to declutter and make instagram healthier

### ISSUE THREAD

**Issue by allyradomski** [revanced/revanced-patches#1840]
### Application

Instagram

### Issue

This patch should allow more control on what content is shown on Instagram. I want to be able to configure the app to make my experience with the app healthier. I cannot easily move away from it as I use it to promote my art and use it to talk to people and make connections on it.

### Patch

I'll use a bullet point list to make my ideas clearer.

- Ability to remove/hide buttons on the bottom bar, such as Explore, Create Story and Reels. Perhaps hidden buttons have to be accessed through the hamburger button.
- Ability to hide the "Suggested for you" section
- Ability to only show posts from those you follow
- Ability to disable read receipts from yourself
- Ability to disable seeing read receipts from others
- Ability to hide suggested/popular search terms
- Whitelist or blacklist hashtags from appearing in explore, example: whitelisting #cats
- Ability to hide the story views

### Motivation

My motivation for this patch request is to create a configurable and healthier social media experience for those that use Instagram. I'm trying to reduce the anxiety and compulsions involved with it. 

There's overlap between my patch request and https://github.com/revanced/revanced-patches/issues/1246 but I am offering more options that I'd like to have within the app.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Please add your points to #1652.
