### ISSUE TITLE
feat(patch): Patch for hotstar screenshot restrictions.

### ISSUE THREAD

**Issue by manishloshali** [revanced/revanced-patches#1841]
### Application

Hotstar

### Issue

Patch for hotstar that removes screenshot restrictions. I have already tried 'experimental universal patches support' but that cashes app

### Patch

Remove Screenshot Restriction

### Motivation

it will be easier to take screenshot and mirror.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
It's a streaming app and any modification will cause unintended side effects, the motivation does not suffice
