### ISSUE TITLE
Cinexplore Premium and More customization 

### ISSUE THREAD

**Issue by BrandgrandRealMe** [revanced/revanced-patches#1845]
### Application

Cinexplore

### Issue

Adds / no customization 

### Patch

Premium features + More customization

### Motivation

I hate ads and Cinexplore has them.

I want to add custom link/app for the watch thing

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Insufficient motivation provided.

**Comment by BrandgrandRealMe** [comment]
Ok

**Comment by BrandgrandRealMe** [comment]
I updated the info
