### ISSUE TITLE
Able to connect to Nest speakers without YouTube music subscription 

### ISSUE THREAD

**Issue by wolf-yuan-6115** [revanced/revanced-patches#1848]
### Application

YouTube music

### Issue

YouTube music needs a subscription to connect to Nest speakers (Which is ridiculous)

> Note: When I'm trying to open an issue at here, YouTube music didn't show that "Connect to Nest" banner, I'll post a screenshot when it shows that banner.

### Patch

Able to connect to Nest speaker without a subscription.

### Motivation

Everyone hate YouTube subscription service, and they don't even include YouTube music premium in YouTube premium!

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
This is likely controlled through the server
