### ISSUE TITLE
feat(patch): flar2.homebutton Button Mapper

### ISSUE THREAD

**Issue by thrame** [revanced/revanced-patches#1849]
### Application

Button Mapper: Remap your keys
https://play.google.com/store/apps/details?id=flar2.homebutton

### Issue

Unlock the pro features such as:

- Broadcast intents (PRO)
- Run scripts (PRO)
-  Choose custom keycode (root and PRO)
- Root command (root and PRO)

### Patch

See above

### Motivation

The patch allows everyone to remap their buttons on their phone/ tv

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
That is not a motivation to create a patch for, thanks anyways

**Comment by thrame** [comment]
Most importantly for me it'd allow me to remap a button to run a command using Google Assistant, but thanks
