### ISSUE TITLE
feat(patch): com.instagram.android: Remove `igshid` from Share URL

### ISSUE THREAD

**Issue by stdedos** [revanced/revanced-patches#1851]
### Application

com.instagram.android

### Issue

Remove `igshid` from Share URL

### Patch

Remove `igshid` from Share URL

### Motivation

`igshid` is probably some ig tracking. "Probably not necessary".

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
What is igshid

**Comment by oSumAtrIX** [comment]
A query parameter? Not really necessary to remove

**Comment by stdedos** [comment]
Well - _nothing is really necessary_.
I thought suggestions were welcome.

At least close it properly: Not planned 🙏

**Comment by oSumAtrIX** [comment]
Suggestions are welcome, this is a request as the label on this issue suggests and a request can be denied. The motivation for denial is the lack of motivation provided in the issue. As the amount of requests rise, the threshold for acceptance rises too. I disagree with GitHub's choice of saying "Closed as unplanned" as it suggests the wrong message than this issue was closed with. GitHub should allo closing with custom reasons for example.

**Comment by stdedos** [comment]
> GitHub should allow closing with custom reasons for example.

Yeah, I disagree with Github too 😕

However, they have this:
![image](https://user-images.githubusercontent.com/133706/229901388-713e5e5a-8dbe-430c-8f42-45e1c16419ca.png)

and then ofc custom labels could fine-tune the reasoning.

But at least that gives an extra state to a boolean open/closed state.

**Comment by oSumAtrIX** [comment]
This side-info is not seen:

![image](https://user-images.githubusercontent.com/13122796/229943724-b4477f26-3192-4247-8ea9-5c849281b226.png)

For that reason, it doesn't really add any benefit.

**Comment by SodaWithoutSparkles** [comment]
Github actually has guides on marking as duplicates: 
https://docs.github.com/en/issues/tracking-your-work-with-issues/marking-issues-or-pull-requests-as-a-duplicate

https://docs.github.com/en/get-started/writing-on-github/working-with-saved-replies/about-saved-replies

**Comment by oSumAtrIX** [comment]
Marking as duplicate has nothing to do with closing an issue.
