### ISSUE TITLE
feat(YouTube): Allow selecting video codec and other advanced audio / video format options

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [ReVanced/revanced-patches#1853]
### Application

Youtube

### Issue

Currently there is only a simple quality selection menu, which can only select quality, but not codec nor framerate

### Patch

provide more choices to user. For example, from 1080p60 to 1080p60, vp9, 5.0Mbit, similar to that of SmartTube. `remember-quality` should also be able to remember the spectific quality, framerate, codec. As theres more formats available, if `remember-quality` could change to order the priority of different qualities, then it would be nice.

```
1080p30, vp9, 2.26Mbit, HDR
1080p30, avc, 5.07Mbit
1080p30, av1, 2.22Mbit
720p30, vp9, 0.91Mbit
720p30, avc, 0.95Mbit
720p30, av1, 1.1Mbit
...
```

### Motivation

- codec selection
    - not all codec are created equal
    - some device handle one codec better than others
    - _can choose **not** to enable HDR_ (depends on server)
- can choose 30fps instead of 60fps
    - some phone might not have 60fps+ screens
    - less battery usage
    - less data usage
- possibly solve the following issues: 
    - ReVanced/revanced-patches-template#1877
    - ReVanced/revanced-patches-template#1909 
    - ReVanced/revanced-patches-template#1950 
    - ReVanced/revanced-patches-template#2104
    - All further issues on (not) prioritize/force X codec

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [x] I filled out all of the requested information in this issue properly.

**Comment by SodaWithoutSparkles** [comment]
This might be unintentionally implemented by the half-complete spoof patch? spoofing as older ios version/android testsuite blocks certain types of format, but it is obviously not the ideal solution.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!

**Comment by VaelophisNyx** [comment]
Well that blows
