### ISSUE TITLE
feat(patch): Dark mode for android, tiktok

### ISSUE THREAD

**Issue by Sept1-c** [revanced/revanced-patches#1855]
### Application

tiktok

### Issue

tiktok only has an option to turn on dark mode for the ios app, would be great if there was a patch for it to work on android too

### Patch

just makes tiktok dark mode and easier on eyes

### Motivation

dark mode is probably the most loved feature in any app

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [ ] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
#1061
