### ISSUE TITLE
feat(patch): Return Youtube Comment Translation

### ISSUE THREAD

**Issue by fortissimo247** [revanced/revanced-patches#1856]
### Application

Youtube (com.google.android.youtube)

### Issue

Youtube has comment translation feature, but if i watch a lot of videos in a certain language, I can't use no longer translation feature for that language.

I'm using Korean but they don't give me translation button for English or Japanese because I watched videos of that languages.

![youtube comment translation](https://user-images.githubusercontent.com/125655800/230086399-8cad0b54-733f-43ed-aa1b-714506f266e4.jpg)

in this screenshot, "translate to korean (my language)" doesn't appear in first comment (japanese)
but it appear in second comment (language that I don't know)

### Patch

I hope youtube does not stop providing a Japanese comment translation function just because I watched a few Japanese videos.

I want patch that always showing "translate to [my language]" option if the comment is not my language.

### Motivation

I searched this issue in korean biggest community, and I saw many people are bothered by same reason (missing translation).
Most people who watch videos from other countries will probably feel uncomfortable with this.
This feature will be very useful for them.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [x] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Black-StellarSpectrum** [comment]
Also it'd be nice if the coment would be automatically translated with undo translate as a option!

**Comment by oSumAtrIX** [comment]
Superseded by #1903.
