### ISSUE TITLE
feat(patch): Unlock Elevate premium version 

### ISSUE THREAD

**Issue by EhabxAlaa** [revanced/revanced-patches#1865]
### Application

Elevate 

### Issue

Elevate is heavily restricted without the premium version so i need a patch to unlock it

### Patch

Unlocks premium version 

### Motivation

The app is really nice as it helps you develop your skills but is fun at the same time, so getting the full experience for those who can't afford it would be amazing 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Insufficient motivation.  Most apps are nice.

**Comment by EhabxAlaa** [comment]
> Insufficient motivation. Most apps are nice.

What exactly does most apps are nice mean??!

**Comment by oSumAtrIX** [comment]
Basically you used the motivation for this patch request, that this app is nice, though most apps are nice, so it's not really convincing.

**Comment by EhabxAlaa** [comment]
> Basically you used the motivation for this patch request, that this app is nice, though most apps are nice, so it's not really convincing.

Ok, then what type of motivation are you looking for to consider the app worthy of a patch, like what other things the app that got patches like(tiktok, Twitter, Instagram, and some non famous apps too) got that this app doesn't have? I am curious to know so i can request more "efficiently".

**Comment by oSumAtrIX** [comment]
Some patches were PRed, they weren't really requests and required a motivation. The motivation has to justify the request, we have many requests here and the threshold rises the more there are. Just saying the app is nice doesn't really make this request stand out or justify any necessity.

**Comment by EhabxAlaa** [comment]
Just an extra note: i have no idea how to  patch an app like this, does it take an hour or a month to do, does it require you to pay for the app or not, so I don't want to keep requesting hard things for no return in your side , you are amazing enough to work Revanced, just want more information on  what to request and what not to request

**Comment by EhabxAlaa** [comment]
> It depends, sometimes patches can take months just to find a line of code which is relevant for the patch, sometimes it's minutes work, but still tedious enough, because it includes developing and testing the patches. In any case, a patch request is still a request and the motivation field is for the maintainer to decide weather to keep it or not.

Sure, thanks for replying, i really appreciate the work you guys do , keep it up😄
