### ISSUE TITLE
bug(youtube/sponsorblock): autoplay button in wrong location

### ISSUE THREAD

**Issue by InakiArzalluz** [revanced/revanced-patches#1866]
### Type

Cosmetic

### Bug description

The autoplay button is overlapping with the config button inside the player, rendering the config button unclickable. It's present in both portrait and landscape mode.

### Steps to reproduce

Using release v2.168.0-dev.6 or newer:
 1. Patch Youtube including 'sponsorblock' and 'microg-support'.
 2. Open a video.
 3. Try to change the video resolution.

 autoplay and config buttons are overlapping.

### Relevant log output

```shell
.
```

### Screenshots or videos

![20230406_023020](https://user-images.githubusercontent.com/65030772/230471903-77ee6be7-535a-440c-8c9e-4d1cc69ecc8a.jpg)

### Additional context

_Tested only under Android 8.1.0 (Samsung Experience 9.5), non-root_
#### The bug is present if:
+ Sponsoblock patch was applied, even if it's currently disabled.
#### The bug isn't present if:
 + sponsorblock patch wasn't applied
 + release v2.168.0-dev.4 (or older) was used to patch youtube

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Is YouTube not > Android 8

**Comment by InakiArzalluz** [comment]
No, youtube is 8.0+ (At least v18.05.40 and v18.08.37)

**Comment by oSumAtrIX** [comment]
Decrease font size/increase display size check if that does anything.

**Comment by InakiArzalluz** [comment]
> How is the autoplay button shown? I have not seen that before.

This is how it looks when release v2.168.0-dev.4 (or older) is used.
![20230406_023037](https://user-images.githubusercontent.com/65030772/230482152-17bf87af-bb84-45f3-8150-85777966ad46.jpg)

**Comment by oSumAtrIX** [comment]
Is this issue regarding the latest dev releases?

**Comment by oSumAtrIX** [comment]
I am unsure how this can happen, adding the button happens by adding it in a XML file where you specify to which existing button it should align to from what direction.

**Comment by InakiArzalluz** [comment]
> Decrease font size/increase display size check if that does anything.

Just checked that, and they still overlap regardless of the display/font size.
