### ISSUE TITLE
feat: Option to Block Recommendations

### ISSUE THREAD

**Issue by rodhfr** [revanced/revanced-patches#1867]
### Type

Functionality

### Issue

On the computer it is possible to use extensions to neutralize youtube recommendations and increase focus, it would be nice to have this option also on a mobile device integrated on revanced.

### Feature

Option in the menu to block Youtube recommendations

### Motivation

I've been using Revanced for a few months now and loving the design, thanks! I would really appreciate it if there was an option to block Youtube recommendations as I study through it and the algorithm sometimes is quite distracting.

**Comment by oSumAtrIX** [comment]
Duplicate of #776.
