### ISSUE TITLE
bug: <Buffering on live stream>

### ISSUE THREAD

**Issue by itzaritrik** [revanced/revanced-patches#1869]
### Type

Other

### Bug description

When i watch live stream on youtube.Youtube is buffering a lot😑. Not buffering when watching normal video.Only buffering when watching live
stream. Please someone help me to how can I fix it! 🙏👀

### Steps to reproduce

Go to this link ( https://revanced.io/#download-apk )and download general version of revanced (
0.0.57) 

### Relevant log output

```shell
.
```

### Screenshots or videos

![Screenshot_2023-04-06-13-31-16-980_app revanced android youtube](https://user-images.githubusercontent.com/108151774/230576979-45c31834-f7ab-49bd-abf5-c80900bcbb81.jpg)

### Additional context

Tested only under Android 10 (Miui Global 12.5.1), non-root

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by itzaritrik** [comment]
> ReVanced.io is not our site.

 So which of your website can you give me the link of your website and what will be the solution to this problem?

**Comment by oSumAtrIX** [comment]
[revanced.app](revanced.app] is our site.

**Comment by itzaritrik** [comment]
okey!🖤

**Comment by itzaritrik** [comment]
> [revanced.app](revanced.app) is our site. 

okey!🖤
