### ISSUE TITLE
feat(patch): is failing to hide , share create , clip , thank

### ISSUE THREAD

**Issue by LAMBORGUINI** [revanced/revanced-patches#1871]
### Application

Youtube revanced

### Issue

correção

### Patch

YouTube Revanced , options hide share create clip thank is crashing is not hiding sometimes Hides sometimes not

### Motivation

so that the problem can be corrected

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
https://github.com/revanced/revanced-patches/issues/1863
