### ISSUE TITLE
(again) emoji2 <it's almost like a patch or update!>

### ISSUE THREAD

**Issue by idontveapc** [revanced/revanced-patches#1872]
### Application

youtube

### Issue

the emojis!&(+$@;-

all the android apps use androidx but not all emoji or emoji2 library, this is where youtube does too but it's outdated.

### Patch

in the apk you must, go to> classes.dex> androidx> emoji(this must be >> emoji2 --an updated library--).

### Motivation

for old android version users.

>> previously first tagged not planned and you removed it, now go check yourself. original apk won't, so it must be patched.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [ ] I have written a short but informative title.
- [ ] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Please open a properly formated issue.
