### ISSUE TITLE
feat(patch): properly formatted issue

### ISSUE THREAD

**Issue by idontveapc** [revanced/revanced-patches#1877]
### Application

youtube

## THE ISSUE
 outdated androidx emoji library, check yourself, go as i said in **patch↓↓↓** I don't know if you can change the apk?! it's dex file, youtube devs ain't care?

if you still not sure go to developer.android.com and search emoji2.

### Patch

in the apk you must, go to> classes.dex> androidx> emoji(this must be >> emoji2 --an updated library--).

### Motivation

?

### previously

>> **/ closed**

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [ ] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Please  use proper title and fill out everything else requested properly, I still don't know what this issue is about.
