### ISSUE TITLE
Question: Can these shorts be made to look like the normal ones.

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [revanced/revanced-patches#1878]
### Application

YouTube 

### Issue

In this account, for some reason the shorts show up in this weird manner and doesn't seem to change and go back to the way it should be. I've seen it pop-up once like how it should be. But it's back to being wierd.

How it looks like:
![IMG-20230410-WA0002](https://user-images.githubusercontent.com/117499019/230794859-29c87ddd-020e-4c9b-8a9e-7d47faafa483.jpg)

### Patch

I don't know if a patch is possible as it's related to the account and not ReVanced or the YouTube app.

### Motivation

I would be really happy to find a solution of some sort to resolve this issue if I come across one.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
If the question is on, if they can be made to look like the normal ones, the answer would be yes.

**Comment by ILoveOpenSourceApplications** [comment]
Really. Can you elaborate on how to do that? Is a patch necessary or do I have to do something else?

**Comment by oSumAtrIX** [comment]
Yes, a patch would be necessary. You can also try spoofing the app version via the existing patch.

**Comment by ILoveOpenSourceApplications** [comment]
Tried that but that didn't help. It still showed up as in the picture even after spoofing the app.

**Comment by oSumAtrIX** [comment]
Check the unpatched app.

**Comment by ILoveOpenSourceApplications** [comment]
It's there also.

**Comment by oSumAtrIX** [comment]
Then a patch is necessary to modify anything.

**Comment by ILoveOpenSourceApplications** [comment]
Then I guess I'll reopen this as a patch request and hope for a fix.

**Comment by oSumAtrIX** [comment]
I don't see any issue to fix.

**Comment by ILoveOpenSourceApplications** [comment]
Given that the shorts appear differently than normal and takes up more space in the homepage can be considered an issue to be fixed right?

**Comment by oSumAtrIX** [comment]
It's not a bug, at least not from ReVanced, if you consider it an issue you should open one on YouTube's end.

**Comment by ILoveOpenSourceApplications** [comment]
> ### Patch
> I don't know if a patch is possible as it's related to the account and not ReVanced or the YouTube app.

I have mentioned that in my post and have a clear idea that the issue not related to ReVanced. Like in the OP I was simply hoping for a solution, if any available, to revert how the shorts UI looks.

**Comment by oSumAtrIX** [comment]
Shorts should've been looking like this for a long time. This UI I have only seen when browsing a channels shorts.

**Comment by ILoveOpenSourceApplications** [comment]
Yeah, it should be looking like this when viewing the shorts section inside a channel. But in the homepage also? That's not normal.

**Comment by oSumAtrIX** [comment]
I haven't seen them on the homepage like that, only in the channels.

**Comment by ILoveOpenSourceApplications** [comment]
The issue I have reported is present on the homepage.

**Comment by oSumAtrIX** [comment]
I recommend consulting YouTube support in that casey if you think it's a bug.

**Comment by ILoveOpenSourceApplications** [comment]
I'm also considering that. But I wonder how long and in what way the response will be from the official YouTube team.

**Comment by oSumAtrIX** [comment]
Likely shorter than here.

**Comment by ILoveOpenSourceApplications** [comment]
Will try that and see how they respond. Depending upon that I may open an issue here. Thanks for the replies.
