### ISSUE TITLE
feat(patch): Highest video resolution limit

### ISSUE THREAD

**Issue by Mimicthis** [revanced/revanced-patches#1883]
### Application

YouTube Revanced. 

### Issue

YouTube is bringing a limit to resolution and bitrate to the basic users, only premium users will get the best quality.

Link: 

### Patch

This parch should bring this to Revanced. 

### Motivation

It would allow best video quality to all users. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
This is locked behind the API.
