### ISSUE TITLE
bug: Motion sense is not working in YouTube Music

### ISSUE THREAD

**Issue by NicolaSpadari** [revanced/revanced-patches#1885]
### Type

Error at runtime

### Bug description

For the Pixel 4 folks out there, we have a sensor called "Motion Sense" (or Soli) for gestures.
Currently the official app supports that, and other music apps too, but when using Revanced Youtube Music it just doesn't work in the app.

### Steps to reproduce

- Install any patched version of the app on a Pixel 4/XL
- Press Play

The statusbar should glow to indicate that the gestures are enable, but it doesn't, and the gestures wont work.

### Relevant log output

```shell
No log available.
```

### Solution

Add a patch or restore the code that enables Motion Sense

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
This is likely due to the package name change and not fixable through YouTube only. Either you have to use the original package name (by not applying the microg-support patch) or you have to modify the Pixel app in order to enable motion sense for the changed package.
