### ISSUE TITLE
feat(patch): Show comments hidden by youtube profanity(?) filter

### ISSUE THREAD

**Issue by Daruyami** [revanced/revanced-patches#1892]
### Application

YouTube ReVanced

### Issue

Some comments and replies when sorted by "Top" are hidden. When sorting by "Newest" no comments seem to be hidden, only for sorting by "Top".

### Patch

Option to unhide these hidden comments and replies. An option in settings, or another button for sorting would be great!

I have no idea how it's programmed but it may be just a single boolean to check, or maybe the sorting by "Top" and by "Newest" use different *comment pools*?

### Motivation

On hobbyist channels, some of these hidden comments might contain useful information and no profanity yet still get hidden for unknown reasons. 
Hiding comments can be considered a type of censorship. I want to have an option to see them **without** sorting by "Newest" and then having to scroll through thousands of comments to find the ones I was looking for.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Daruyami** [comment]
@oSumAtrIX "locked"? There isn't a single instance of this word in my issue. Please explain what *you* mean.

**Comment by oSumAtrIX** [comment]
Hidden*

**Comment by Daruyami** [comment]
Oh okay, here is one of the most annoying examples I've encountered:

On youtube video: https://youtu.be/iq6hbY_fzYg
The first comment when sorted by "Best", some of the replies are hidden, and magically appear when sorted by "Newest":

Example 1:
newest: 
![image](https://user-images.githubusercontent.com/67425425/232324523-edcad1db-9245-4eac-91c7-72f1f8a7d0f8.png)
best: 
![image](https://user-images.githubusercontent.com/67425425/232324542-96bb3080-3812-4305-9f8d-7a9eb18c2e12.png)
(3 replies from the user "OX TX" are missing)

Example 2:
newest:
![image](https://user-images.githubusercontent.com/67425425/232324553-11fabbde-5a45-49d9-8ef4-ebd25d936273.png)
best:
![image](https://user-images.githubusercontent.com/67425425/232324572-7e88fd50-a7ae-4026-aa23-61e9b8d3c93e.png)

(replies between two of my ones (daruyami) are missing)


Here is a screenshot of the entire replies section when sorted by "Newest": ![image](https://media.discordapp.net/attachments/770377533458874398/1097184429786550454/Screenshot_20230416-173732116.png)

And here is a screenshot of the entire replies section when sorted by "Best": ![image](https://media.discordapp.net/attachments/770377533458874398/1097184449294250114/Screenshot_20230416-173853101.png)

Sorry for quite an annoying example to read through but its the only one I could find in this instant.

**Comment by oSumAtrIX** [comment]
This is likely what the API returns and not a client side issue. If the API only returns these entries, there's nothing to do about it, you should report this issue to YouTube.

**Comment by Daruyami** [comment]
You mean that there are separate API calls for these two types of sorting (meaning that the sorting is done on the server)?

**Comment by oSumAtrIX** [comment]
Of course

**Comment by Daruyami** [comment]
That's disappointing.
Also this is most likely a *feature* and not a bug so I doubt reporting this issue to YouTube would help in anyway.
Anyways, thanks for your time!

**Comment by oSumAtrIX** [comment]
I don't think sorting involves hiding and therefore it should be a bug.
