### ISSUE TITLE
bug: Actions TikTok in TikTok do not work

### ISSUE THREAD

**Issue by grahamgrieb** [revanced/revanced-patches#1894]
### Type

Error at runtime

### Bug description

Liking, Saving, and Following do not actually work for the past few months. You can click the buttons, but the actions do not save. I believe this also affects the watch history, as it does not remember what videos you have seen so the same videos will pop up multiple times.

### Steps to reproduce

Interact with a video and it will not save

### Relevant log output

```shell
N/A
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Reproduction steps are not working.

**Comment by sanjeevstunner** [comment]
This happens to me too. 

### Steps to reproduce 
 - Like or follow the video or creator, and it shows that you liked followed (in for you page)
 - Close the app
 - Reopen and visit your profile page or the profile page of the creator you followed, there wont be anything that you liked or followed 

Also, messaging isn't working as well

**Comment by sanjeevstunner** [comment]
> Reproduction steps are not working.

Bro plox check my reply

**Comment by oSumAtrIX** [comment]
Please open a new issue and appropriately fill in everything requested.

**Comment by sanjeevstunner** [comment]
> Please open a new issue and appropriately fill in everything requested.

Sure 👍
