### ISSUE TITLE
feat(patch): tiktok auto start from saved videos

### ISSUE THREAD

**Issue by nabildroid** [revanced/revanced-patches#1895]
### Application

tiktok

### Issue

tiktok is addictive because how the "for you" works but it can serve as great tool to learn new things and for someone to brainwash himself into doing good thing 
if the saved videos in tiktok opens up the moment the app lunches we can ensure we are learning and memorizing instead of the never-ending stream of new videos 

also if you can randomize those videos that would be greate

### Patch

tiktok startup from the saved videos not from "for you"

### Motivation

if i have 100 useful saved videos i can within 1 month memorize them and possibly work by them
but having a stream of new videos the app becomes more like consuming my energy instead of me consuming useful information

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Not sure why you would want that when you can simply go to your saved videos after opening the app.

**Comment by nabildroid** [comment]
going to the "saved section" is like you VS "for you"
most of the time I failed that war, the motive is not to fight in the first place

**Comment by oSumAtrIX** [comment]
If addiction is your problem, you should treat it professionally not ask for workarounds.

**Comment by nabildroid** [comment]
I think you never used Tiktok, by saying "addiction" not in a literal way but more of TikTok is useless because of the wasted time in "for you"
I guess, this repo is welcoming entertainment and helping all types of people
for anyone that belongs to my category, my workaround is simply adding a shortcut of TikTok notification (press and hold on the app icon) in the home screen and remove the main app icon (if your launcher allows)
this way you are more in control and the app opens up in notification and you can move to the saved section

**Comment by oSumAtrIX** [comment]
Yeah I have never used TikTok, though I don't see why you can't just go to the "Saved" page after opening the app.
