### ISSUE TITLE
feat(patch):  indefinite buffering on yt ReVanced in a specific time stamp

### ISSUE THREAD

**Issue by Therockstar777** [revanced/revanced-patches#1897]
### Application

Indefinite buffering on YT ReVanced on a specific timestamp on the version 18.05.40 for the few days...had this issue b4 also on the version 18.03.36 but the latest version 18.05.40 fixed it 

### Issue

Indefinite buffering on YT ReVanced on a specific timestamp on the version 18.05.40

### Patch

Get a new version of YT ReVanced to fix this issue 

### Motivation

This issue is from INDIA .. this is should be considered bcoz i have been a long time user of ReVanced and had recommended to others as well the they have liked the app.... and I hope ReVanced will FIX it SOON 

### Acknowledgements

- [x] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
#1890

**Comment by Therockstar777** [comment]
Can i know the latest 2.168 patch ??

**Comment by Therockstar777** [comment]
I mean which version of ReVanced YT ???
18.05.40 or the latest non recommended one ???

**Comment by Therockstar777** [comment]
There is no recommended version available as of now

**Comment by Therockstar777** [comment]
In the builder right??

**Comment by Therockstar777** [comment]
![image](https://user-images.githubusercontent.com/127512365/231963942-b6c83c2d-b6b2-42b8-acc6-3b45838fa150.png)
There is no recommended version in the builder

**Comment by Therockstar777** [comment]
Click on continue... even in the phone manger it is showing the same we cannot patch it newly 
![image](https://user-images.githubusercontent.com/127512365/231969458-98a4e558-5697-42ad-bead-69b60554d334.png)

**Comment by Therockstar777** [comment]
I had downloaded it in the morning to patch it again but can't do so

**Comment by Therockstar777** [comment]
Unae to patch it using it official tevanced manager
![Screenshot_20230414-125615](https://user-images.githubusercontent.com/127512365/231973548-76b5d712-fb88-4eb9-b8ea-02848a41577d.jpg)

**Comment by imaperson1060** [comment]
> ![image](https://user-images.githubusercontent.com/127512365/231966690-26e32079-03ab-4e3d-969c-082fe1f4eec1.png)
> 
> There is no recommended version in the builder

You can get it from ApkMirror (https://www.apkmirror.com/apk/google-inc/youtube/youtube-18-05-40-release)
I also made a PR with page navigation for Revanced Builder (https://github.com/reisxd/revanced-builder/pull/686) so hopefully it will be added to the next release
