### ISSUE TITLE
feat(patch): Block videos and channels 

### ISSUE THREAD

**Issue by Abdullah-07** [ReVanced/revanced-patches#1899]
### Application

YouTube 

### Issue

Complete block option for cringe and unhealthy videos and channels. 

### Patch

If there is an option to block channels and videos even from search it would be very helpful and it would save a lot of time from being spent watching cringe content in headlessness. 

### Motivation

It will help much in reducing unproductive content and make YouTube a more better place for people who seek to learn something out of it. As you know this kind of fullish content is somehow more appealing or attention seeking and it will be worth to block it. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by spectrolit** [comment]
> Dupe of https://github.com/orgs/revanced/discussions/472 then.

the link not working

**Comment by oSumAtrIX** [comment]
#1104
