### ISSUE TITLE
bug: WARNING: Skipping hide-get-premium: Incompatible with version 5.41.50.

### ISSUE THREAD

**Issue by AMSAMSAMSAMS** [revanced/revanced-patches#1899]
### Type

Error while patching

### Bug description

WARNING: Skipping hide-get-premium: Incompatible with version 5.41.50. This patch is only compatible with version com.google.android.apps.youtube.music: 5.14.53, 5.16.51, 5.17.51, 5.21.52, 5.22.54, 5.23.50, 5.25.51, 5.25.52, 5.26.52, 5.27.51, 5.28.52, 5.29.52, 5.31.50, 5.34.51, 5.36.51, 5.38.53, 5.39.52.

But this version IS supported on previous patch... Strange...

### Steps to reproduce

CLI: v2.20.1
Patches: v2.168.0
Integrations: v0.102.0

### Relevant log output

```shell
INFO: Reading dex files 
INFO: Decoding AndroidManifest.xml only, because resources are not needed 
INFO: Merging revanced-integrations-0.102.0.apk 
INFO: Skipping compact-header: Excluded by default 
INFO: Skipping export-all-activities: Excluded by default 
WARNING: Skipping hide-get-premium: Incompatible with version 5.41.50. This patch is only compatible with version com.google.android.apps.youtube.music: 5.14.53, 5.16.51, 5.17.51, 5.21.52, 5.22.54, 5.23.50, 5.25.51, 5.25.52, 5.26.52, 5.27.51, 5.28.52, 5.29.52, 5.31.50, 5.34.51, 5.36.51, 5.38.53, 5.39.52 
INFO: Skipping predictive-back-gesture: Excluded by default 
INFO: Skipping remove-screenshot-restriction: Excluded by default 
INFO: Skipping spoof-wifi-connection: Excluded by default 
INFO: Deleting existing resource cache directory 
INFO: Decoding resources 
INFO: background-play succeeded 
INFO: codecs-unlock succeeded 
INFO: exclusive-audio-playback succeeded 
INFO: minimized-playback-music succeeded 
INFO: music-microg-support succeeded 
INFO: music-video-ads succeeded 
INFO: tasteBuilder-remover succeeded 
INFO: upgrade-button-remover succeeded 
INFO: Compiling resources 
INFO: Writing modified dex files 
INFO: Aligning com.google.android.apps.youtube.music_5.41.50-54150240_minAPI21(arm64-v8a)(nodpi)_apkmirror.com.apk to ReMusic_aligned.apk 
INFO: Signing ReMusic_aligned.apk to ReMusic_signed.apk 
INFO: Found existing keystore: ReMusic.keystore 
INFO: Cleaned up cache directory 
INFO: Finished
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Masamune3210** [comment]
.....patches change. Just because a previous version of a patch has support does not mean future versions having the same support is guaranteed

**Comment by oSumAtrIX** [comment]
You are patching a version the patch isn't targeting.
