### ISSUE TITLE
bug(youtube/spoof-app-version): can't always exit the app using the back button

### ISSUE THREAD

**Issue by OnlYKai** [ReVanced/revanced-patches#1900]
### Type

Other

### Bug description

Unable to exit YouTube ReVanced with the back button, when Spoof app version is enabled.

Haven't tested with other apps, since i only use YouTube ReVanced. I tried YouTube version 17.49.37 and 18.05.40, both have the same issue.

### Steps to reproduce

1. Enable Spoof app version in YouTube ReVanced
2. Restart the app (maybe the app has to be closed for some while. You can see that spoof app version is "fully applied", when wide searchbar isn't round anymore (see screenshots below). That's when the bug appears (doesn't have anything to do with wide searchbar tho, it's only an indicator).)
3. Try to exit the app by pressing the back button (Shouldn't work at that point. Sometimes it randomly works if you spam it, but 99% it doesn't)

Spoof app version Enabled:
![NOT round (spoofed app version)](https://user-images.githubusercontent.com/67548894/232014487-7a0ff010-729f-459c-b5f7-73c3581549e0.jpg)

Spoof app version Disabled:
![round (NOT spoofed app version)](https://user-images.githubusercontent.com/67548894/232014727-a250a0d3-cff0-4f34-85e4-e2bbe66a683b.jpg)

### Relevant log output

```shell
.
```

### Acknowledgements

- [x] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by OnlYKai** [comment]
I don't use predictive-back-gesture. And like i said the wide search often doesn't change immediately, I don't know why that is tho. Maybe close the app, wait 30 minutes and open it again, that's what i experienced.

**Comment by oSumAtrIX** [comment]
I have spoofed the app to an older version and it worked just fine.
