### ISSUE TITLE
feat(patch): Implement a dark theme with moderate brightness like Vanced.

### ISSUE THREAD

**Issue by creeper-0910** [revanced/revanced-patches#1906]
### Application

Youtube

### Issue

Youtube

### Patch

I liked the Vanced dark theme, but the Revanced theme is too dark for me.
I am sorry to trouble you, but I would appreciate it if you could implement a theme with just the right darkness like Vanced.

### Motivation

I just loved this theme...

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by ILoveOpenSourceApplications** [comment]
Then use the stock YouTube dark theme perhaps as it's not as dark as the ReVanced theme. Have you tried it?

**Comment by creeper-0910** [comment]
> Then use the stock YouTube dark theme perhaps as it's not as dark as the ReVanced theme. Have you tried it?

Sorry, I didn't try that.
Do I just remove the Themes patch?

**Comment by ILoveOpenSourceApplications** [comment]
Yes.

**Comment by oSumAtrIX** [comment]
Or use the patches options via the CLI to chose any background color.

**Comment by creeper-0910** [comment]
> Or use the patches options via the CLI to chose any background color.

I wasn't aware that there was such a setting...
Thanks for letting me know!
