### ISSUE TITLE
feat(patch): Remove ads from Facebook app.

### ISSUE THREAD

**Issue by mrf090** [revanced/revanced-patches#1915]
### Application

Facebook

### Issue

Remove Ads!

### Patch

Remove all ads

### Motivation

Facebook App ads are most annoying.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
#1893

**Comment by badawoll** [comment]
This issue probably has the actual Facebook app in mind, whereas #1893 is for Facebook Messenger.

_The commit message on that patch is misleading, and I didn't realize that when I was writing it. Sorry about that_ :grimacing:

**Comment by oSumAtrIX** [comment]
Is Facebook even Dalvik?

**Comment by badawoll** [comment]
React Native.

**Comment by oSumAtrIX** [comment]
ReVanced patches Dalvik, not react native.

**Comment by quyleanh** [comment]
> ReVanced patches Dalvik, not react native.

So basically there will be no patch for Facebook, right?

**Comment by oSumAtrIX** [comment]
There already is.
