### ISSUE TITLE
feat(patch): Add "Auto" in the Old video quality menu

### ISSUE THREAD

**Issue by emowpee** [revanced/revanced-patches#1917]
### Application

Youtube

### Issue

When I have a bad wifi/cellular connection, I still want the best resolution I can get.

It would provide a solution for having to trial and error every resolution without reverting to the new quality menu.

### Patch

Adding "Auto" as an option under the OLD quality menu

### Motivation

Will provide more flexibility while using the OLD quality menu for cases of poor internet connection. Would also lessen steps just to have the "Auto" resolution accessible.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Disable the patch that skips the new menu. This should suffice.
