### ISSUE TITLE
bug: (youtube/seekbar-tapping) Tapping on the seekbar doesn't work properly

### ISSUE THREAD

**Issue by karamanliev** [ReVanced/revanced-patches#1919]
### Type

Cosmetic

### Bug description

I am not sure if I understand correctly but when seekbar tapping is enabled shouldn't I be able to seek the video by just tapping somewhere on the bar? Currently tapping does nothing more than haptics and if I want to seek the video I should swipe on the bar or tap-hold on the video itself and swipe.

### Steps to reproduce

Step 1: Open Revanced
Step 2: Enable seekbar tapping from Interaction submenu
Step 3: Play a random video
Step 4: tap on the seekbar
Step 5: nothing happens, only haptics

### Relevant log output

```shell
not needed, no errors
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by karamanliev** [comment]
> Please attach a recording.

Here's the [recording (gdrive)](https://drive.google.com/file/d/1rnYqbvFb18zvusJYR3ZjqIdvxg2FLreB/view?usp=sharing).

**Comment by oSumAtrIX** [comment]
What about other YouTube videos?

**Comment by karamanliev** [comment]
The video doesn't matter, it's the same on every one.

**Comment by oSumAtrIX** [comment]
Please attach a detailed and complete recording of the following: 

![image](https://user-images.githubusercontent.com/13122796/232910013-4cab8c71-29fa-48cf-a03c-c92372889d10.png)

Also include a showcase of the issue in the same video.
