### ISSUE TITLE
bug: videos stop completely after a certain time 

### ISSUE THREAD

**Issue by MelukHa** [revanced/revanced-patches#1920]
### Type

Error at runtime

### Bug description

Trying to watch any video on a patched youtube client longer than ~30s (depends on network speed, I got 49s, 39s and 45s on 3 different networks) is not possible, after that time the video stops playing/loading. You can stop the video, start it again where you stopped it but it stops again after that time. 

### Steps to reproduce

1. Install youtube 18.05.40
2. Install ReVanced manager 0.0.57
3. Try to watch any video
4. The bug occurs about 45s after starting the video 

### Relevant log output

```shell
no relevant log
```

### Additional context

Youtube v18.05.40
ReVanced manager v0.0.57
Android 12
Redmi note 10 pro (MIUI global 13.0.16) (not rooted)

Tried to uninstall both client and manager, reinstalled them and repatched the client but nothing changed

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
#356
