### ISSUE TITLE
bug: youtube devices without rotation black bars

### ISSUE THREAD

**Issue by MichaelDavidGK** [revanced/revanced-patches#1928]
### Type

Error at runtime

### Bug description

On devices that doesn't have rotation such as some tablets, TVs, connected monitors it switches to small mobile view when you go back from fullscreen video leaving black bars on left and right

### Steps to reproduce

1) Open any video
2) Close it
3) Enjoy black bars on left and right with insanely small mobile like UI

### Relevant log output

```shell
Unavailable
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
#1752

**Comment by MichaelDavidGK** [comment]
Unrelated, it's about home behaviour, not video
Happens with both spoof enabled and disabled

> #1752

**Comment by oSumAtrIX** [comment]
Add screenshots, no clue what you are attempting to describe here

**Comment by MichaelDavidGK** [comment]
![InFrame_1682004471347](https://user-images.githubusercontent.com/39009683/233414478-f5ec963e-9c7b-4343-961d-781c2a369fa4.jpg)

I cannot do it till 25th as I just left for train and I'm gonna be abroad. 

However this shows more or less what shows up when you close video/go back to home from video

> Add screenshots, no clue what you are attempting to describe here

**Comment by oSumAtrIX** [comment]
I don't know what I see here. Why is this white?

**Comment by oSumAtrIX** [comment]
Ah the black bars, you are sourcing wrong APK file with wrong DPI.

**Comment by MichaelDavidGK** [comment]
> Ah the black bars, you are sourcing wrong APK file with wrong DPI.

It's nodpi version

**Comment by MichaelDavidGK** [comment]
Also this happens only when closing video, at start it is as it should be and covers whole screen

**Comment by oSumAtrIX** [comment]
Try installing the APK unpatched.

**Comment by MichaelDavidGK** [comment]
> Try installing the APK unpatched.

This will have to wait till 25th, I will let you know when I do then
