### ISSUE TITLE
feat(patch): Force the app to always use the opus 251 audio codec

### ISSUE THREAD

**Issue by Ghost-Miner** [revanced/revanced-patches#1929]
### Application

YouTube

### Issue

Some time ago the youtube app started randomly changing the audio coded to 249 opus which sounds utterly horrible as it's nothing but compression artifacts.
I think this was supposed to be something the app does when it thinks the connection is too slow, but 99% of time it does it for no reason.
The only ways to get it back to playing the normal (high quality audio) is to either load a different resolution or by reopening the video.

They way i know it changes the code is by looking at the debug overlay where it changes the audio format from 251 opus to 249 opus.

### Patch

Force the app to never change its audio format/codec. (Opus 251 in all higher resolutions)

### Motivation

It's really annoying especially if it happens while listening to music where the song just become a mess of random compression artifacts.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by SodaWithoutSparkles** [comment]
https://github.com/revanced/revanced-patches/issues/909
