### ISSUE TITLE
"interaction Window" doesn't appear at the right place

### ISSUE THREAD

**Issue by EhabxAlaa** [revanced/revanced-patches#1945]
### Type

Error at runtime

### Bug description

This issue is only related to the tablet version, which only happened like a week ago by its own (without any update to the app or patches) and it is that this window appear at the wrong place, some examples are provided below but it happens with all " : " buttons 

### Steps to reproduce

Click on any " : " button and you will find that the window apears at top left regardless of where it should appear 

### Relevant log output

```shell
No log
```

### Screenshots or videos

![Screenshot_20230416-172909](https://user-images.githubusercontent.com/120474122/233701850-cf8894ed-196b-4b84-9127-8131652db15b.jpg)

![IMG_20230416_173645](https://user-images.githubusercontent.com/120474122/233702460-c8e7f822-3a47-4815-9680-06ebba0b249d.jpg)

### Additional context

This bug is extremely annoying so please try to fix it asap, it only happens in ReVanced btw

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Masamune3210** [comment]
I really wish people would stop putting asap in their reports. The devs owe you nothing and do it as a side-project usually. Insisting on a time schedule isn't going to end well

**Comment by EhabxAlaa** [comment]
> I really wish people would stop putting asap in their reports. The devs owe you nothing and do it as a side-project usually. Insisting on a time schedule isn't going to end well

Well, this bug is really annoying so i just asked them to prioritize it , and i think i asked kindly i am really appreciative of their work and i don't think i requested it like if "they owe me something" and at the end it won't change that they can reglect or delay the fix

**Comment by oSumAtrIX** [comment]
Check the stock unpatched app (same version).

**Comment by EhabxAlaa** [comment]
> Check the stock unpatched app (same version).

Doesn't happen to stock app for any version only revanced

**Comment by EhabxAlaa** [comment]
I checked version 18.05.40 and 18.08.37 and it is fine for both of them

**Comment by oSumAtrIX** [comment]
Exclude patches from the patching process until the error is gone, and report back which one causes it.

**Comment by EhabxAlaa** [comment]
> Exclude patches from the patching process until the error is gone, and report back which one causes it.

Any suggestions for what patches may cause it? as trying excluding every single patch will take me three weeks lol

**Comment by EhabxAlaa** [comment]
> Exclude patches from the patching process until the error is gone, and report back which one causes it.

Any suggestions for what patches may cause it? as trying excluding every single patch will take me three weeks lol

**Comment by oSumAtrIX** [comment]
You can do a binary search that would find the problematic patch in log(patchesCount) time in the fastest way possible.

**Comment by EhabxAlaa** [comment]
> You can do a binary search that would find the problematic patch in log(patchesCount) time in the fastest way possible.

I don't know why you thought i would understand that, can you please explain what you mean better? If it is difficult then don't explain 🙂

**Comment by oSumAtrIX** [comment]
> I don't know why you thought I would understand that

CS students should be aware of binary search:

![image](https://user-images.githubusercontent.com/13122796/233747624-c3a1b0c8-c761-4ba0-8bfa-af9aef1b3fad.png)

Say you have a list of patches. Exclude half of them; if the issue persists, the problematic patch is in the other half. Proceed to do the same to that half.

**Comment by EhabxAlaa** [comment]
> > I don't know why you thought I would understand that
> 
> CS students should be aware of binary search:
> 
> ![image](https://user-images.githubusercontent.com/13122796/233747624-c3a1b0c8-c761-4ba0-8bfa-af9aef1b3fad.png)
> 
> Say you have a list of patches. Exclude half of them; if the issue persists, the problematic patch is in the other half. Proceed to do the same to that half.

Nope they haven't taught as that yet lol, but i was actually don't that now without understanding it , i narrowed the patches to 8 and will continue testing

**Comment by EhabxAlaa** [comment]
It is one of these since the apk patched with them still have the issue
![Uploading Screenshot_2023-04-22-01-21-04-575_app.revanced.manager.flutter.jpg…]()

**Comment by oSumAtrIX** [comment]
Please reupload the image.

**Comment by EhabxAlaa** [comment]
![Uploading Screenshot_2023-04-22-01-21-04-575_app.revanced.manager.flutter.jpg…]()

**Comment by EhabxAlaa** [comment]
![Screenshot_2023-04-22-01-21-04-575_app revanced manager flutter](https://user-images.githubusercontent.com/120474122/233748249-4e4f243c-f9f0-46ec-ae55-a281e3654c92.jpg)

**Comment by oSumAtrIX** [comment]
Narrow down even more.

**Comment by EhabxAlaa** [comment]
> Narrow down even more.

Still exists with these 4
![Screenshot_2023-04-22-01-38-35-417_app revanced manager flutter](https://user-images.githubusercontent.com/120474122/233749254-f5673148-b7e7-41e4-b5b4-2cfee9f8f7b4.jpg)

**Comment by EhabxAlaa** [comment]
It is probably the spoof one then, i will try again only it and microG

**Comment by EhabxAlaa** [comment]
Somehow it still exists only microg patch

**Comment by oSumAtrIX** [comment]
In that case it is a stock issue.

**Comment by EhabxAlaa** [comment]
> In that case it is a stock issue.

But i tested stock and it is fine🥲

**Comment by EhabxAlaa** [comment]
Will test it again

**Comment by EhabxAlaa** [comment]
Yeah stock is perfectly fine, i am not an idiot nor am i lying, the stock version has no issue and the patched one with only MicroG patch has the issue

**Comment by EhabxAlaa** [comment]
I said before that this issue happened without any change in anything, slept with ReVanced fine and woke up without updating anything and the issue apeared , but it can't be from YouTube side as stock as perfectly fine, i have no idea what it could be then

**Comment by EhabxAlaa** [comment]
Actually it does exist now on stock YouTube somehow, i swear i tested it multiple times and it was fine

**Comment by EhabxAlaa** [comment]
Sorry for too many comments but i can confirm that stock is fine , can you test it yourself or ask someone with any tablet and see if you can figure out the issue? Appreciate your help

**Comment by oSumAtrIX** [comment]
Did you install the __same__ apk you are patching without patching it and did you check if it happens there?

**Comment by EhabxAlaa** [comment]
> Did you install the **same** apk you are patching without patching it and did you check if it happens there?

You mean patch without even MicroG support patch or what exactly?

**Comment by EhabxAlaa** [comment]
The apps i have are Stock V 18.08.37 downloaded from apkmirror and the patched V 18.08.37 one with only MicroG support patch, do you want anything different?

**Comment by EhabxAlaa** [comment]
The stock actually rarly have the same issue i have no idea how this happens i am starting to lose my mind , five times i open it and it is fine and one time it has the issue

**Comment by EhabxAlaa** [comment]
Now it always has the issue,so maybe stock doesn't have it for the first few times you open it and then it starts to have the issue , but the patched one always has it ( this may be wrong but that is what i understood)

**Comment by EhabxAlaa** [comment]
I tried updating to the latest google play version and the issue exists, so does that mean it is YouTube thing? At least reply to this last comment

**Comment by oSumAtrIX** [comment]
If it happens in the unpatched app, as originally assumed, yes.

**Comment by EhabxAlaa** [comment]
> If it happens in the unpatched app, as originally assumed, yes.

I am really sorry for wasting your time and it is a YouTube issue , but i really didn't know since it only happened after like the fifth time i open it , i feel like a dummy now lol

**Comment by oSumAtrIX** [comment]
All good, happens.

**Comment by oSumAtrIX** [comment]
No, it is an upstream issue and unrelated to ReVanced.

**Comment by EhabxAlaa** [comment]
> No, it is an upstream issue and unrelated to ReVanced.

I know i was asking you if you know a way to contact google to fix it , not you guys

**Comment by oSumAtrIX** [comment]
![Screenshot_2023-05-17-20-04-18-26_4d38fce200f96aeac5e860e739312e76](https://github.com/revanced/revanced-patches/assets/13122796/d3f4d2cc-af11-41b1-b0ee-ac5633620c7d)
