### ISSUE TITLE
"Theme" patch have a lot of visibility issues 

### ISSUE THREAD

**Issue by EhabxAlaa** [revanced/revanced-patches#1950]
### Type

Error at runtime

### Bug description

Like button is not appearing for mobile (this issue exists since the start of revanced and it wasn't fixed somehow) , also the subscribe menu and reply menu have wrong background color, there are screenshots below to further illustrate the issue

### Steps to reproduce

1) Have "Theme"  patch
2) you get many button visibility issues and wrong background colors

### Relevant log output

```shell
No logs
```

### Screenshots or videos

In the first screenshot the like button is clicked 
![SAVE_20230422_242323](https://user-images.githubusercontent.com/120474122/233743398-e854c611-2edb-4386-b17d-d0b21065483b.jpg)

In this one it isn't clicked (but it is hard to notice the difference)
![SAVE_20230422_242519](https://user-images.githubusercontent.com/120474122/233743499-065ffd8f-fda7-4fcb-9d40-3237276b9423.jpg)

It is also not displayed correctly here at the "Quick actions in full screen" 
![SAVE_20230422_242955](https://user-images.githubusercontent.com/120474122/233743899-47fafb75-cfd6-40f3-8572-07c690ca5a21.jpg)
 
The second part is wrong background colors like in the following screenshots
![IMG_20230422_001337](https://user-images.githubusercontent.com/120474122/233743995-ddfe8d92-3090-44bd-9094-350b649d94b6.jpg)

![IMG_20230422_001532](https://user-images.githubusercontent.com/120474122/233744035-da2fdb04-07d6-4e41-a11a-d9f16a778bcf.jpg)

### Additional context

This whole patch requires improvements as most icons or buttons get that( "like button layout issue" or whatever you want to call it lol) but the difference is that they are temporary and doesn't always have problems 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
This is not caused by the theme patch but your OS.

**Comment by EhabxAlaa** [comment]
> This is not caused by the theme patch but your OS.

Are you sure? As stock YouTube doesn't has these issues (for real this time lol) ,i am using a Xiaomi device, is there is anything i can do?

**Comment by EhabxAlaa** [comment]
> This is not caused by the theme patch but your OS.

Yup it is not the theme patch, even after removing it i still have the same issue, but stock is fine so how is that? What exactly made the interface on revanced like these but stock not?

**Comment by oSumAtrIX** [comment]
Because your device treats the app differently

**Comment by EhabxAlaa** [comment]
> Because your device treats the app differently

Can you please consider Opening the issue again with different title and content ( i will change them)? My sister has the same issue too with her "different phone"  so maybe it could be fixed on your side , i know it is not related to the theme patch but it is related to revanced, i will be very glad if you could try to fix it if possible, Thanks in advance
