### ISSUE TITLE
feat(YouTube): Option to not auto-play the next video in playlists

### ISSUE THREAD

**Issue by NicolasFLM** [ReVanced/revanced-patches#1951]
### Application

Youtube

### Issue

When watching videos normally you can use the autoplay toggle button to prevent videos from playing automatically just fine, but in playlists the autoplay button dissapears and you can't prevent the videos from playing automatically. (Sorry for my bad english).

### Patch

The ability to prevent videos from autoplaying in playlists.

### Motivation

Just a extra option that i think would be neat to have.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by SodaWithoutSparkles** [comment]
It would be nice to configure by playlist. 

For example, you would want the "music" playlist to autoplay but not the "watch later" playlist.

**Comment by rbits0** [comment]
This is a very important feature for me. It's the number one reason why I don't like watching YouTube on my phone. When I watch a video in my Watch Later, and say the video after it is 3 hours long and I'm partway through it, when I finish the first video it will send me back to the start of the second video and I lose my progress in the video and I don't know where I'm up to.

I have a [tampermonkey script](https://greasyfork.org/en/scripts/481929-youtube-playlist-autoplay-button) to fix this on my computer. I'm tempted to write a patch myself but I don't know how to write Revanced patches.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!

**Comment by Jen-Ari** [comment]
I would really like to see this feature implemented as well, there are a lot of users who hates the Autoplay in playlists (me included). Quick googling confirms it.
It would be nice to make at least a global setting, like for the normal autoplay. Or just disable it as well, if the global setting is disabled.
