### ISSUE TITLE
feat(patch): Ability to change the placement of the download button in Youtube

### ISSUE THREAD

**Issue by Hokyps** [ReVanced/revanced-patches#1958]
### Application

YouTube 

### Issue

I'm sure I'm not the only one that feels uncomfortable with the current position of the download button.

### Patch

Is it possible to implement an option that let us choose the placement of the download button?
I feel like using "the real" download option that Youtube provides would be great!

Just for the record, NO sarcasm in my writing.

Cheers!

![Screenshot_20221010-141529_YouTube](https://user-images.githubusercontent.com/111386632/194949574-b1f0d3a5-cb12-4e86-baac-fd687cf2a1a0.jpg)

### Motivation

I think this little change would bring a next to premium/stock experience when downloading.

### Acknowledgements

- [x] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by KobeW50** [comment]
@oSumAtrIX you can link this issue to close from your recent commit
