### ISSUE TITLE
tracking: make all patches toggleable with settings patch & integrations 

### ISSUE THREAD

**Issue by TheJeterLP** [revanced/revanced-patches#197]
See the two regarding PRs:
- https://github.com/revanced/revanced-patches/pull/202
- https://github.com/revanced/revanced-integrations/pull/87

## 🐞 Issue

Some patches, for ex disable-fullscreen-panels do not call the integrations to check for a setting. This needs to be changed in order to prepare for the addition of in-app settings. 

## ❗ Solution

Create patch classes in Integrations, create settings in the SettingsEnum class and call the methods there to actually do stuff. (For example hiding views like in disable-fullscreen-panels) 

## ❓ Motivation

Consistency for all patches.

**Comment by OxrxL** [comment]
Related to this too:

https://github.com/revanced/revanced-patches/issues/169
