### ISSUE TITLE
feat(patch): Shorts layout editing

### ISSUE THREAD

**Issue by Mimicthis** [revanced/revanced-patches#1971]
### Application

YouTube Revanced. 

### Issue

Please add a way to remove Remix from
stories and icon to give money to the short
maker.

### Patch

I don't know what to write here. 

### Motivation

It would free up the space 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
It won't give money to the short maker

**Comment by oSumAtrIX** [comment]
Please open a new issue with all requested fields properly filled.
