### ISSUE TITLE
feat(patch): Option to remove download button from the video interface 

### ISSUE THREAD

**Issue by Mimicthis** [revanced/revanced-patches#1979]
### Application

YouTube Revanced. 

### Issue

Please add an option to remove download button from the video interface. 

### Patch

I don't know what to write here. 

### Motivation

It would free up space. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Already available.
