### ISSUE TITLE
feat(patch): please add black mode to playlists bar

### ISSUE THREAD

**Issue by Mimicthis** [revanced/revanced-patches#1982]
### Application

YouTube Revanced. 

### Issue

Playlists mode doesn't have a black mode but dark/grey. 

### Patch

Not sure what to write here. 

### Motivation

It would help balance the whole app theme. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Checked and it's the color the theme patch sets, correctly amoled black by default.
