### ISSUE TITLE
"Copy video link" button overlapped with the audio description button

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [revanced/revanced-patches#1983]
### Type

Cosmetic

### Bug description

"Copy video link" button overlapped with the audio description button

### Steps to reproduce

1. Watch [this video](https://youtu.be/1otF0N6surM) 
2. notice that the buttons are overlapping

### Relevant log output

```shell
N/A
```

### Screenshots or videos

![Screenshot_2023-04-26-17-30-11-177_app revanced android youtube-edit](https://user-images.githubusercontent.com/64138578/234534237-b6194863-6a26-4278-99dd-ecdb4476b529.jpg)
![Screenshot_2023-04-26-17-27-55-564_app revanced android youtube-edit](https://user-images.githubusercontent.com/64138578/234534246-98336bc5-9e34-444e-b195-9b2d0a7d86b9.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
#387

**Comment by SodaWithoutSparkles** [comment]
@oSumAtrIX They are not even the same buttons. Aprat from "overlapping" nothing was the same.

Or do you want a central thread like sig spoof side effects for all button overlapps?

**Comment by oSumAtrIX** [comment]
Its the same issue regardless of not being the same button.

**Comment by SodaWithoutSparkles** [comment]
> Its the same issue regardless of not being the same button.

WDYM? Same issue of not checking if there are overlapps? They did not even collide with the same youtube side buttons. What if there is a video with both VR and audio tracks?

**Comment by oSumAtrIX** [comment]
As I said, the issue is the same regardless of the buttons not being the same.

**Comment by SodaWithoutSparkles** [comment]
> As I said, the issue is the same regardless of the buttons not being the same.

You have explained nothing.

**Comment by oSumAtrIX** [comment]
I don't know what there is to explain. The issue is for both "Overlapping buttons".
