### ISSUE TITLE
Change package name failed.

### ISSUE THREAD

**Issue by bartoszek** [revanced/revanced-patches#1996]
### Type

Error while patching

### Bug description

Invalid package name error when applying change package name patch.

### Steps to reproduce

Run revanced manager and start patcher for YouTube 18.15.40

### Relevant log output

```shell
...
```

### Screenshots or videos

![Screenshot_20230427-192843](https://user-images.githubusercontent.com/1213348/234943745-0a052814-cced-44e4-9d56-7fad0e2cd404.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Linus789** [comment]
You didn’t set the new package name, which seems to be requirement right now. And it is not possible, to change the package name via the ReVanced Manager because patch options haven’t been implemented yet.

**Comment by bartoszek** [comment]
>  ... it is not possible, to change the package name via the ReVanced Manager because patch options haven’t been implemented yet.
Any road map to which version would implement the feature or tough luck for the gui users.

**Comment by oSumAtrIX** [comment]
No ETA yet.

**Comment by MorgothRB** [comment]
Unfortunately this makes revanced manager useless for non-root users who have YouTube preinstalled as we need to have a different package name for YouTube revanced.
Is there any way to make this patch use a default package name (app.revanced.android.youtube, just like before the change) to get back the previous behaviour?

**Comment by oSumAtrIX** [comment]
This patch is not intended specifically for YouTube and is excluded by default.

**Comment by MorgothRB** [comment]
> This patch is not intended specifically for YouTube and is excluded by default.

Before this patch was introduced YouTube automatically got a new package name which is not possible anymore, Wether you activate this patch or not. so it's now impossible to create a non-root YouTube with revanced manager.

**Comment by oSumAtrIX** [comment]
YouTube gets a new package name through the patch that enables Vanced MicroG support.

**Comment by MorgothRB** [comment]
> YouTube gets a new package name through the patch that enables Vanced MicroG support.

I just saw that the microg patch had been removed from my patch selection. Thanks and sorry for confusion.

**Comment by abrahammurciano** [comment]
> You didn’t set the new package name, which seems to be requirement right now. And it is not possible, to change the package name via the ReVanced Manager because patch options haven’t been implemented yet.

How is one supposed to set a package name? How does this work?

**Comment by oSumAtrIX** [comment]
Fixed
