### ISSUE TITLE
Unhook - Subscriptions Feed as Homepage & Removing Recommendations Under Video Being Played

### ISSUE THREAD

**Issue by matt873** [revanced/revanced-patches#1997]
### Application

YouTube

### Issue

Both Newpipe & Libretube have an option to make subscriptions feed as homepage: also an option to remove video recommendations under current video being played, just like **YouTube Unhook Extension**. Although the above mentioned clients and YouTube Official app are two very different things, if implemented, this option will help people enjoy distraction free experience who just want to watch videos from their subscriptions only. It will be a great feature in the official YouTube app because alternative clients have flaws and bugs

### Patch

![Screenshot_2023-04-27-02-09-45-199_com google android youtube_1](https://user-images.githubusercontent.com/108935493/234957548-ce841629-4256-42b4-b320-621478f2dd8d.jpg)

![Screenshot_2023-04-27-02-10-16-339_com google android youtube_1](https://user-images.githubusercontent.com/108935493/234957692-64211cf3-e7f6-4d5d-ad37-98b239fdb238.jpg)

![Screenshot_2023-04-27-01-45-17-057_org schabi newpipe](https://user-images.githubusercontent.com/108935493/234959305-f596b641-0a9b-4806-a0ee-8f1083beccb0.jpg)

### Motivation

It will help people avoid being distracted by the YouTube algorithm when they want to watch videos from their subscriptions only.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
#1867
