### ISSUE TITLE
bug: microg patch disables root installer

### ISSUE THREAD

**Issue by Martinligabue** [revanced/revanced-patches#2001]
### Type

Other

### Bug description

User session installer fails when installing yt microg version, root installer works, but from the app is disabled

### Steps to reproduce

use microg patch
click "install as root"

### Relevant log output

```shell
no crash, just blocked by app
```

### Solution

let users use root install if they really want to

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
This is not a patch issue
