### ISSUE TITLE
bug: autoplay is enabled by default in incognito mode

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [revanced/revanced-patches#2006]
### Type

Error at runtime

### Bug description

The autoplay function is enabled by deault in incognito mode, even when the autoplay button is hidden. There's no way to turn it off unless you go through the long process of:
1. Disabling "hide autoplay button"
2. Restart
3. Go to incognito mode
4. Disable autoplay
5. Undo step 1
6. Restart yet again

### Steps to reproduce

1. Patch with latest stable patch (2.171.0)
2. Remove all data of revanced YT (Warning: this will clear configs)
3. Watch a video, skip to the last 10 seconds or so
4. let the video finish, notice that the video just ends
5. turn on incognito mode
6. repeat step 3
7. notice that the autoplay function is enabled

### Relevant log output

```shell
N/A
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
I am not sure how this is a bug. Autoplay is enabled by default on YouTube and you included the patch that hides the autoplay button to hide it.

**Comment by SodaWithoutSparkles** [comment]
This is a bug because this is not the behaviour on non-incognito. When you don't enable incognito, even when you installed fresh, the autoplay wont kick in. 

The bug is the inconsistant behaviour between incognito and normal mode in default settings

**Comment by oSumAtrIX** [comment]
For me autoplay is enabled by default on YouTube on a fresh install

**Comment by SodaWithoutSparkles** [comment]
Ok then.
