### ISSUE TITLE
bug: signature spoofing enabled when it is not needed

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [revanced/revanced-patches#2007]
### Type

Error at runtime

### Bug description

Signature spoofing is enabled in Revanced settings by default. But sometimes you don't actually need to spoof the signature and you can still watch normally, so it is causing unneccessary side effects as mentioned in #

### Steps to reproduce

1. Patch with 2.171.0
2. Notice that signature spoofing is enabled by default
3. disable it under Revanced settings > misc 
4. watch a video
5. if you cannot watch the video, you will not need to spoof the signature

### Relevant log output

```shell
N/A
```

### Solution

When spoofing is enabled, check periodically/on new video is played/on app launch if you can still watch the video without spoofing signature. 

There should be an option to disable this behaviour. For example, a switch called "disable auto-spoofing check" with description "Determine if spoofing is needed automatically" or "Follow manual config [ below | above ]" depending on the state of the toggle.

### Additional context

Spoofing will be enabled when needed, but not disabled when not needed...?

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
It is enabled by default because many if not most people have this issue.

**Comment by trmdi** [comment]
> It is enabled by default because many, if not most, people have this issue. Also, you included it at patch time.

Many user use the prebuilt apk from automated script like j-hc's one which select all patches from revanced. And some of them has problems with that patch. Is this a valid usecase?

**Comment by oSumAtrIX** [comment]
How unofficial tools operate is not within our reach. The user should be able to choose what to include or not include. Some patches depend on others, so even if you don't include a patch but another, it may depend on it and force include it. In any case, some patches might be required, such as the `client-spoof` patch when you use the `vanced-microg-support` patch for YouTube.

**Comment by SodaWithoutSparkles** [comment]
Now the argument of "it was included by the user at patch time" does not stand.

**Comment by oSumAtrIX** [comment]
It does. When you include a patch, it can depend on others, so checking a patch, basically checks others too
