### ISSUE TITLE
bug: Youtube non-stop loading after 0:59 second

### ISSUE THREAD

**Issue by amitraviverma** [revanced/revanced-patches#2027]
### Type

Error at runtime

### Bug description

I have patched youtube successfully, but i don't know the problem exactly but after installing patched revanced youtube. every youtube videos gets stuck after 0:59 seconds and non-stop reloading. even my internet connection is perfectly fine, no issue.
i can watch these videos on brave without any issue, it just happening with patched youtube (revanced) only.
i can't completely uninstall main youtube app so i have disabled original youtube. using revanced only.

### Steps to reproduce

Step 1: installed revanced youtube.
Step 2: play any videos.
Step 3: every video gets stuck on 0:59 seconds and showing buffering infinitely.
Step 4: I tried on 3 different mobiles and all having the same issue.
Step 5: all those devices have 3 separate accounts, so this isn't account related issue too.

### Relevant log output

```shell
i dont know how to generate runtime from my mobile.
```

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
#1818

**Comment by amitraviverma** [comment]
i just noticed i was not using "spoof signature" patch
I patched new one with "spoof signature" patch
now its working completely fine

**Comment by IDLEGLANCE** [comment]
> 

i have the exact same problem but if i use spoof signature patch and start my youtube-r app i have a gray screen and cant do anything
