### ISSUE TITLE
feat(patch): Youtube Music Package Name To Default

### ISSUE THREAD

**Issue by CrypticCus** [revanced/revanced-patches#2032]
### Application

Youtube  Music

### Issue

Youtube Music have "vanced" in title, when installed. can't be set to default as youtube itself.

### Patch

Fix the normal patch to use normal name.

### Motivation

Make it like youtube itself that can be seen as original name.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Vanced is in the title because ReVanced is in the title.

**Comment by Shockshwat** [comment]
Custom Branding Patch doesnt exist for YT music yet.
