### ISSUE TITLE
feat(patch): Youtube, Chat message menu, add "Go To Channel" button

### ISSUE THREAD

**Issue by 0o120** [revanced/revanced-patches#2033]
### Application

Youtube

### Issue

Youtube used to have it where if you tapped on a users chat message, it would bring up the menu that had a button that let you go to the users channel. As of now it only has the "block" or "report user" buttons. I think moderators have the option to go to the users channel, but it should be a feature for everyone.

### Patch

Add "Go to Channel" button to the menu that pops up when tapping a chat users message. That way you can browse to that chat users channel page.

### Motivation

Brings back an old feature that youtube chat used to have. Allows for checking a channel in the event a person clones someone in chat, so you can verify it's the legitimate person. Just allows anyone to check someones channel for no reason at all.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Julius8900** [comment]
idk how you came with this idea but YouTube chats were removed loooong ago
https://support.google.com/youtube/thread/12446824?hl=en

**Comment by 0o120** [comment]
> idk how you came with this idea but YouTube chats were removed loooong ago https://support.google.com/youtube/thread/12446824?hl=en

What? I'm obviously talking about Youtube Live Chats.

**Comment by Julius8900** [comment]
> > idk how you came with this idea but YouTube chats were removed loooong ago https://support.google.com/youtube/thread/12446824?hl=en
> 
> What? I'm obviously talking about Youtube Live Chats.

Then you should have said "YouTube Live Chats" instead. People would mostly understand the old "Chats" feature which was used for DMing channels.

**Comment by 0o120** [comment]
> > > idk how you came with this idea but YouTube chats were removed loooong ago https://support.google.com/youtube/thread/12446824?hl=en
> > 
> > 
> > What? I'm obviously talking about Youtube Live Chats.
> 
> Then you should have said "YouTube Live Chats" instead. People would mostly understand the old "Chats" feature which was used for DMing channels.

You have got to be trolling at this point. Why would I request a feature for "Youtube Direct Messaging" when it hasn't existed for years. Use your brain.

**Comment by oSumAtrIX** [comment]
@0o120 He has an absolutely valid point; I was closing this issue for reasons he mentioned before you wrote it's about live chat.
