### ISSUE TITLE
feat(TikTok): Download video file name and metadata

### ISSUE THREAD

**Issue by Leseratte10** [ReVanced/revanced-patches#2035]
### Application

TikTok / `com.zhiliaoapp.musically`

### Issue

Right now, when I download a TikTok video, the video gets saved without any metadata. The file name is a 32-character random looking string, and there's no metadata inside the file, that means, going "back" from a downloaded file to the source TikTok is hard / impossible. 

### Patch

Ideally I would like to see two things, but I don't know if that is easily possible: 

A) Instead of having that random byte string as file name, put the uploader's name and the video ID into the file name. For example, for the (nonexistant example) TikTok at `https://www.tiktok.com/@example_user/video/1234567890123456789`, make the file name "TikTok - example_user - 1234567890123456789.mp4" so that if I have that downloaded file on my phone or computer, I can use the file name to determine the URL to that TikTok. 

B) The MP4 video format (and almost all other video formats) support a bunch of metadata like title, author, comment, and so on. If possible - but I don't know if it is, it's probably too difficult - it would be cool if that metadata (uploader, video ID, upload date, description/hashtags, full URL to the TikTok, ...) would be added into the video file metadata so the information can still be extracted if the file gets renamed later. 

### Motivation

Right now when you download TikTok posts, the files all have a pretty meaningless file name. Given a downloaded mp4 file, there is no way (or at least I don't know any way) to ever "find" that TikTok on the TikTok webpage or in the app again, or to find out anything (uploader, description, comments, ...) about the video. 

If the video ID (and if possible, the uploader name) were included in the video file name (or, even better, in the MP4 metadata), then everyone can recreate the tiktok.com URL for the given video and re-visit it on the webpage or in the TikTok app. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
