### ISSUE TITLE
Show which patch can be disabled in app

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [revanced/revanced-patches#2040]
### Application

Youtube (music)

### Issue

Not all patch can be disabled in-app. The patch description should say if it could be disabled in settings

### Patch

All current patches

### Motivation

Save time repatching

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
The description should describe the patch not provide any additional side information.
