### ISSUE TITLE
feat(youtube/navigation-buttons): Allow to switch Home with Subscriptions button

### ISSUE THREAD

**Issue by diegonogaretti** [revanced/revanced-patches#2049]
### Application

YouTube

### Issue

navigation-buttons patch is a really nice feature but I think it doesn't make much sense to allow us to disable Home button while still loading Home screen on startup

### Patch

I would like to ask an option to either change the default loading screen on startup or allow us to switch Home with Subscriptions button. In both cases we would be able to start YouTube directly on the Subscriptions screen

### Motivation

I think it doesn't make much sense to allow us to disable Home button while still loading Home screen on startup. I Also think we spend more time on the Subscriptions screen than the Home screen

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by sim0nschneider** [comment]
I think this is a good Idea, as it makes it possible for a user to only focus on what they are subscribed to!
I would love this feature!

**Comment by oSumAtrIX** [comment]
https://github.com/revanced/revanced-patches/issues/2139
