### ISSUE TITLE
feat(patch): 

### ISSUE THREAD

**Issue by Maremelows** [revanced/revanced-patches#2055]
### Application

Twitch

### Issue

As a new feature to the twitch application shared on the channel, broadcasters open the broadcast replay only for subscribers. Will there be a feature that can remove that restriction?

### Patch

Removing Subscriber restrictions on some content on Twitch channels

### Motivation

We can remove the ads by patching the app, but we can't watch the broadcast replays because they are exclusive to subscribers.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [ ] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
If it is only for subscribers, it's server-side.
