### ISSUE TITLE
Ads randomly shown on tablet UI

### ISSUE THREAD

**Issue by Joomsy** [revanced/revanced-patches#206]
## 🐞 Issue

Banner ads are still sometimes visible on the home page of the tablet UI.

![SmartSelect_20220718-221808](https://user-images.githubusercontent.com/103767404/179664930-c4e271f4-ed5e-4f6f-b3f7-221d294bee0f.jpg)

## ⚙ Reproduce

Android 12 on Samsung Galaxy Tab S7

Pull-down refresh a couple of times on the home page to see an ad. They don't always show.

**Comment by TheNoFace** [comment]
Galaxy Tab S6 Lite on android 12 shows general ads on main screen and player UI.

**Comment by OxrxL** [comment]
There are 2 new ads type here:

The first posted by the creator of this thread and the second posted by oSum.

The first is not based on Litho and should be enough easy to remove, but it's shown on my device just 1 time every 100 (more or less) homepage reload and it's difficult to work on it.

The second is related to video results and it'a based on Litho. So it's just a new template to discover.

**Comment by Joomsy** [comment]
> and player UI.

Can confirm. It's very rare for me, but I do see one at the top of the suggestion list every once in a while. Screenshots are available in [#244](https://github.com/revanced/revanced-patches/issues/244) for reference.

**Comment by cyanwolfg** [comment]
Using last releases i don't see ads on tablet UI someone can confirm same?
I check on 2 different tablets.

**Comment by sir-harlekin** [comment]
Sill having those ads on Samsung Galaxy Tab A7 (with a very recent own build).

**Comment by Joomsy** [comment]
> Using last releases i don't see ads on tablet UI someone can confirm same? I check on 2 different tablets.

What model(s)? It's starting to look like a problem with Samsung devices specifically.

**Comment by cyanwolfg** [comment]
I'm sorry ads still there, I see less because my location on VPN, but ads still present.

**Comment by SilraGH** [comment]
I'm seeing the same behavior on a Galaxy Tab S5e.

However, I can only reproduce the issue while the tablet is turned to landscape mode (or has landscape mode forced). When it is held in portrait mode, there are no advertisements.

**Comment by Joomsy** [comment]
I'm a little late to report back on this, but it seems that the latest patches have finally fixed this. Should probably wait to hear from others, but I've refreshed the home page 20 times without seeing the first ad. I'm assuming #765 took care of this, so hopefully others are having similar results.
