### ISSUE TITLE
feat(patch): 17.03.38 version spoof

### ISSUE THREAD

**Issue by Ave-Lucifer** [revanced/revanced-patches#2061]
### Application

YouTube

### Issue

Vanced is breaking and users moving to ReVanced could keep the same version they already had.

### Patch

Add 17.03.38 spoof app version target

### Motivation

For Vanced users switching to ReVanced to keep the same exact version they already had, making it look and feel just like Vanced did.  Some users are reluctant to switch to ReVanced and this could help make the transition easier for them.

### Acknowledgements

- [x] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by reisxd** [comment]
Already exists.

**Comment by oSumAtrIX** [comment]
A couple versions are present you can spoof the version too. Chose the nearest available to Vanced for identical experience.
