### ISSUE TITLE
feat(patch): Comment spoiler removal (Litho)

### ISSUE THREAD

**Issue by 0xrxL** [revanced/revanced-patches#2063]
### Application

This patch hides the first preview comment below each video, on the "comments" button.

### Issue

Sometimes these type of comments making content spoilers.

### Patch

Add the following component name to the Litho list:

- <b>carousel_item</>

### Motivation

As has already been said: this preview comment could annoy the user in various ways.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by 0xrxL** [comment]
<img width="178" alt="Immagine 2023-05-03 085949" src="https://user-images.githubusercontent.com/127248639/235851340-4d622753-d142-48a2-9e00-fc0d6c2980e3.png">

**Comment by oSumAtrIX** [comment]
A toggle for this already exists.

**Comment by 0xrxL** [comment]
> A toggle for this already exists.

This component name is missing here: https://github.com/revanced/revanced-integrations/blob/main/app/src/main/java/app/revanced/integrations/patches/GeneralAdsPatch.java

**Comment by oSumAtrIX** [comment]
It is present here https://github.com/revanced/revanced-integrations/blob/main/app/src/main/java/app/revanced/integrations/patches/CommentsPatch.java

**Comment by 0xrxL** [comment]
> It is present here https://github.com/revanced/revanced-integrations/blob/main/app/src/main/java/app/revanced/integrations/patches/CommentsPatch.java

Oh...sorry. I did not see it.

Thanks for info.
