### ISSUE TITLE
feat(patch): Unlock premium Shimeji.

### ISSUE THREAD

**Issue by frrrrrits** [revanced/revanced-patches#2064]
### Application

AppName: `Shimeji - Anime Character`
PackageName: `com.funme.shimeji`
Current Version: `4.0.4.2`

### Issue

Not premium user.

### Patch

Unlock all Premium.

### Motivation

1. It's a cool apps showing a sticker/pet floating in the screen but we're not able to show more than 2 pet if not **premium user**.

2. We're don't have much access to stickers animations if not **premium users**.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [x] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Many apps are cool and paid, I don't see why this one should be patched from the given motivation.
