### ISSUE TITLE
bug: YouTube: "Hide create button" does nothing when using "Switch create with notifications button"

### ISSUE THREAD

**Issue by drobotk** [revanced/revanced-patches#2070]
### Type

Cosmetic

### Bug description

Title says it all I think. The recently added patch for switching create and notifications buttons around makes it so hiding the create button doesn't work. When they are not switched places, the create button can be hidden.

### Steps to reproduce

1. Enable "Hide create button" and "Switch create with notifications button" in Revanced/Layout/Navigation button settings
2. Go back to home page, both buttons should be visible: notifications on the nav bar and create button up top.

### Relevant log output

```shell
Not sure about this
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
That is not really a bug. The create button is hidden so enabling the switch to hide it does nothing, at max the setting can be disabled.

**Comment by drobotk** [comment]
I think I don't understand. So there is no way to hide the create button (camera icon) when using "Switch create with notifications button"?

**Comment by oSumAtrIX** [comment]
No, only the create button.
