### ISSUE TITLE
feat(patch): WearOS YT Music Patches

### ISSUE THREAD

**Issue by defaultkid99** [ReVanced/revanced-patches#2071]
### Application

YouTube Music for WearOS

### Issue

YouTube Music does not work on WearOS unless you have premium.

### Patch

Bring usability to the app for non premium users.

### Motivation

This patch would be valuable to people who want to listen to music on their watch.

### Acknowledgements

- [x] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Bobby306** [comment]
Any chance on adding the patch and using the vanced micro g mentioned above? (This is literally development related for a patch that doesn't exist, not spam. If its not going to be considered, close this feature request

**Comment by oSumAtrIX** [comment]
CLosing due to being too nieche.

**Comment by kaxlabs** [comment]
It's not really that niche; especially with Google Podcasts shutting down and a lot more funding going towards YouTube Music to replace it.

**Comment by oSumAtrIX** [comment]
YouTube music can be run on your phone and controlled over a smart watch. This is nieche.

**Comment by kaxlabs** [comment]
If you're working in a job that has a no phone policy, native media controls on a watch are unreliable and don't allow you to select what to listen to.

**Comment by Bobby306** [comment]
> If you're working in a job that has a no phone policy, native media controls on a watch are unreliable and don't allow you to select what to listen to.

This is kinda where I was going with it. But oh well
