### ISSUE TITLE
feat: Disabled patches by default

### ISSUE THREAD

**Issue by q1k** [revanced/revanced-patches#2073]
### Application

Is there a way to have all the patches disabled by default?
The patches are enabled by default, I'd like them to be unchecked (have the unpatched behavior active by default).

### Motivation

It's easier to enable a few options after the fact instead of disable many.
Especially useful when sharing the apk and others might want only a few features such as background play or no ads or w/e.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by EhabxAlaa** [comment]
There is a "none" button at the top beside the default or recommended patches button

**Comment by oSumAtrIX** [comment]
This will not happen, some patches you need to toggle on, some off.

**Comment by EhabxAlaa** [comment]
> > This will not happen, some patches you need to toggle on, some off.
> 
> So no way to have them disabled by default after installing revanced yt?

Why would you include them if you want to have them off by default? Your request isn't that practical for my understanding
