### ISSUE TITLE
Add toggles for patches that are missing toggles

### ISSUE THREAD

**Issue by Kobewaxman** [revanced/revanced-patches#2080]
### Application

YT ReVanced 

### Issue

Some patches cannot be disabled once someone has included it when they patched the app.

Patches that have this issue are:

`hide player overlay`
`custom video speed`
`premium heading`
`custom branding`
`theme`

### Patch

Have a toggle for these 5 patches in the YT ReVanced settings. I understand that some of them may not be worth the effort of adding a toggle for.

`hide player overlay` = Layout settings
`custom video speed` = Miscellaneous settings
`premium heading` = Layout or Miscellaneous
`custom branding`= Miscellaneous 
`theme` = Miscellaneous or Layout

### Motivation

Many users just want to use the recommended/default patches so that they don't need to read and understand what all of them do. They want to trust that selecting the default patches will not do anything that they don't like and make them stuck with it.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Toggles don't exist because of limitations, otherwise, they would exist.
