### ISSUE TITLE
bug: Brightness when viewing hdr videos is reset to auto

### ISSUE THREAD

**Issue by bozander** [ReVanced/revanced-patches#2081]
### Type

Other

### Bug description

when you turn on the HDR video, the brightness is reset to auto, that is, for example: you open the video with a swipe, you change the brightness (it changes) and after a second (sometimes even during the "setup") it returns to its original position "Auto" (checkboxes for adjusting the brightness are checked in the settings and volume with swipes). Normal videos without HDR work fine, brightness settings are not reset.

### Steps to reproduce

Step 1. Launch Youtube Revanced
Step. 2. Enable swipe control for brightness in Revanced settings.
Step. 3. Start hdr video
Step. 4. Adjust the brightness level with a swipe.

### Relevant log output

```shell
Missing
```

### Solution

Not found

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by the-red-dk** [comment]
> Not a bug. You can disable auto HDR brightness in settings.

I tried it, but it's not fixing the issue tho,
i tried enabling and disabling and enabling it again, yet it doesn't work
