### ISSUE TITLE
bug: Submitting SponsorBlock new Segment at end video not work

### ISSUE THREAD

**Issue by iBasim** [revanced/revanced-patches#2082]
### Type

Error at runtime

### Bug description

There probelm with SponsorBlock
when you submit new Endcards/Credits is not submitted!!

server is work and private ID is Set
and i can submitted new Intermission/Intro Animation without any problems.

So The problem in Submit Endcards/Credits Segment. or in Submit any new Segments at End of any Videos

### Steps to reproduce

1-Submit New Segment at end Video
2-set time for beginning and the end at end Video.
3-After checking the clip, click Submit
4-No message will be shown Tell you a segment submitted successfully, and Segment will not be Submitting.

### Relevant log output

```shell
none
```

### Screenshots or videos

https://user-images.githubusercontent.com/57762287/236450861-bcae06fc-eace-4d21-a7b9-03cc39fef8d4.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by iBasim** [comment]
> Are you waiting long enough for the segment to submit?
> Yes, and I tried on many Videos. It is impossible to Submit a new segment if it is at the end of the video.

And you can try for yourself, you will not be able to Submit a new Segment for the end of the video
https://youtu.be/2qy32lslLKo

You will notice at the beginning of the Video that there is a Segment, and I submitted it successfully.

> It always shows a toast after the segment is submitted. If an error occurs, it will display the error. Verify that `Settings -> ReVanced -> Misc -> Debug -> Show toast on ReVanced error` is turned on.
> 
> Use a computer and adb, and post your ReVanced logs.

Unfortunately, at the moment I do not have a computer.

**Comment by oSumAtrIX** [comment]
Closing for now as this seems like a user error. Open again when it is confirmed to be an issue.

**Comment by iBasim** [comment]
> I just tried, and I was able to create a new end segments successful, and the new segment showed up after refreshing the video.
> 
> Verify you have not turned off `Show toast on ReVanced error`.
> 
> Verify you are using the latest ReVanced patches as well.

Are you sure that you submitted Segment and it succeeded for Endcards/Credits, because I did not see that there was a skipping Segment at the end of the Video.

**Comment by iBasim** [comment]
The problem persists. I also reinstalled revanced, and it is of no any fix, but this message appears
![Screenshot_20230505_200423_com android gallery3d](https://user-images.githubusercontent.com/57762287/236521479-8dcbb73e-a5ca-4ec1-b3f7-4afaadfe727e.png)
