### ISSUE TITLE
Icons in splash screen aren't of good quality.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [revanced/revanced-patches#2083]
### Type

Cosmetic

### Bug description

Icons of both ReVanced YouTube & ReVanced YT Music on splash screen aren't of good quality.

### Steps to reproduce

Step 1. Just open ReVanced and notice the splash screen closely.

### Relevant log output

```shell
Hehe, it's a cosmetic issue.
```

### Screenshots or videos

![Screenshot_2023-05-05-15-58-34-88_d11ae654701a5fadb313ea6fa9a6836f](https://user-images.githubusercontent.com/91815107/236486377-de2cfafc-6ca5-44c9-86c0-2f5de3e27f85.jpg)
![Screenshot_2023-05-05-15-58-42-15_0ee52a21b47f2484ca705d66bfb85bda](https://user-images.githubusercontent.com/91815107/236486418-a816e107-d1f0-4bca-b46f-a8ca9202e4f2.jpg)

### Additional context

Please make them high quality.
By the way, I use 360 dp as smallest width (it's default on Realme 7 Pro).

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Unofficial patches
