### ISSUE TITLE
feat(patch): 

### ISSUE THREAD

**Issue by Liddellious** [revanced/revanced-patches#2084]
### Application

Twitter

### Issue

The "for you" tab is always suggesting the worst type of content (sometimes even gore or animal abuse), and no actual relevant content.

### Patch

I could really use a patch that removes the "for you" tab so I could permanently stay on the "following" tab.

### Motivation

It would remove irrelevant and harmful content.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
You can simply switch to the other tabs.
