### ISSUE TITLE
problem: `sponsorblock` patch submit ui shows placeholders

### ISSUE THREAD

**Issue by Patriarch9307** [revanced/revanced-patches#209]
## 🐞 Issue
The submitting dialogs such as marking segment and manually editing segment shows placeholder values instead of actual strings in patches 2.20.0 and integrations 0.27.3

Manually edit segment:
![](https://i.imgur.com/LkqIg9V.png)

New Segment mark:
![](https://i.imgur.com/VLC5LVi.png)

## ⚙ Reproduce

open any video and try to submit a segment

**Comment by oSumAtrIX** [comment]
Can not reproduce: 

![image](https://user-images.githubusercontent.com/13122796/179952404-c553a72b-f51c-43ab-a8e7-94244b0ee35d.png)

@TheJeterLP what about you?

**Comment by Sculas** [comment]
> I should also mention that this is root based installation.

That is the cause.
Tracking issue: https://github.com/revanced/revanced-patcher/issues/73

**Comment by AroPix** [comment]
I use the root version too and i can replicate that issue. Everything else (patches) is working fine except the translation of the sponsorblock strings.

**Comment by GeekCornerGH** [comment]
the only thing I get is in toast when submitting segment, or voting

**Comment by TheJeterLP** [comment]
I can reproduce that on freshly build non-root version too somehow

**Comment by TheJeterLP** [comment]
![Uploading Screenshot_2022-07-26-18-25-46-68_64ef5fc2000c1caa954c114bb372e1d5.jpg…]()

**Comment by TheJeterLP** [comment]
![Screenshot_2022-07-26-18-25-46-68_64ef5fc2000c1caa954c114bb372e1d5](https://user-images.githubusercontent.com/3790121/181059998-0e427135-c363-48fb-881b-3a37856f6b0b.jpg)

**Comment by anil-al** [comment]
I also see the placeholders in a **non-root** device.
![Screenshot_20220728-152444](https://user-images.githubusercontent.com/101948963/181504692-2d1d7d3e-7125-4616-a358-d6dac71f2fa3.png)
![Screenshot_20220728-152511](https://user-images.githubusercontent.com/101948963/181504700-e1ddae60-0ba9-4a8e-a8fe-d0f46828f9ad.png)
![Screenshot_20220728-152527](https://user-images.githubusercontent.com/101948963/181504703-8b3f3a06-70c6-4393-a7c3-cd50d8f0195a.png)

**Comment by TheJeterLP** [comment]
Fixed
