### ISSUE TITLE
feat(YouTube): Disable HDR video quality

### ISSUE THREAD

**Issue by Porobu** [ReVanced/revanced-patches#2092]
### Application

Youtube

### Issue

When watching HDR videos on youtube the phone (POCO X3 NFC) will switch the screen to a "night light" like color scheme washing out the video (and phones) colors

### Patch

I´d like to see a patch that makes YT serve the standard video

### Motivation

Playing HDR is very annoying at least on my phone (possibly more models affected) cause it washes out the colors and they look completely unnatural

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Julienraptor01** [comment]
This indeed would be great, also for people who have limited bandwidth/data as HDR vids can easily take way more space
![Screenshot_20231228_145732_PowerTube.png](https://github.com/ReVanced/revanced-patches/assets/49841713/1653b5af-5f8f-4d1b-9a17-ba119f200bcc)

**Comment by TrapStoner** [comment]
I would like for this option to be brought back please, hdr videos are very very washed out on my phone. Also for some people it would save on bandwidth.

**Comment by oSumAtrIX** [comment]
#1125
