### ISSUE TITLE
feat(patch): hide seen indicator in facebook messenger conversations

### ISSUE THREAD

**Issue by flame-0** [ReVanced/revanced-patches#2097]
### Application

Facebook Messenger

### Issue

Currently, when a user views a message, a seen indicator appears in the conversation thread, which can make users feel obligated to respond immediately and can be intrusive for those who prefer to take their time before responding.

### Patch

The patch would hide the seen indicator in conversations, allowing users to view messages without notifying the sender that the message has been seen.

### Motivation

This patch request should be considered because it respects the privacy and autonomy of users. Users should have the option to view messages without feeling pressured to respond immediately. Hiding the seen indicator would provide users with the freedom to take their time and respond at their convenience, which would enhance the overall user experience.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Closing in favour of #2653
