### ISSUE TITLE
YouTube: allow selecting text in video description and comments 

### ISSUE THREAD

**Issue by matrixik** [revanced/revanced-patches#2102]
### Application

YouTube 

### Issue

It's impossible to select text in video description and comments. When you click anywhere on comment it's opening box for writing reply.

### Patch

I would like to be able to select description and comment text like normal text (selecting only one word or many). Replying could still be possible by clicking small comment icon 🗨️ on the right of the thumb down icon 👎. Or long hold comment could go into copying text. There could be also option to copy whole comment text in 3 dots icon (now I can see only option to report comment there).

### Motivation

Sometimes there are some useful information in description or comments like long book/video/whatever name. Sometimes comments have some useful info that I would like to copy and put into notes (quite frequent under programming videos).
Previously I was opening this video in mobile browser and copy text there but looks like they also blocked this now...

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
#1350

**Comment by matrixik** [comment]
Strange that searching did not show this other issue, thank you for pointing it to me @oSumAtrIX
