### ISSUE TITLE
feat(patch): Hide stories separately 

### ISSUE THREAD

**Issue by Mimicthis** [revanced/revanced-patches#2109]
### Application

YouTube Revanced. 

### Issue

Stories are only hidden by activating the " Hide shorts " setting, there should be a separate switch to only hide stories. 

### Patch

This patch shluld include a switch to only hide stories. 

### Motivation

It would allow shorts enyoyers option to see shorts but not stories. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Poopooracoocoo** [comment]
YouTube Stories are going away on June 26, 2023. "Starting on 6/26/2023 the option to create a new YouTube Story will no longer be available. Stories that are already live on that date will expire 7 days after they were originally shared."
[Source](https://9to5google.com/2023/05/25/youtube-stories-end/) 

A patch for this won't be necessary soon enough :)

**Comment by oSumAtrIX** [comment]
Closing early
