### ISSUE TITLE
problem: Stats for nerd are visible by default

### ISSUE THREAD

**Issue by HeroGalak** [revanced/revanced-patches#211]
## 🐞 Issue

In video settings of YouTube 17.27.39 stats for nerd are visible by default but don't work

## ⚙ Reproduce

Build YT v17.27.39 with old-quality-layout patch

## ⚠ Additional context

YT built with latest versions of CLI, patches and integrations

**Comment by oSumAtrIX** [comment]
This is a YouTube issue. Check stock YouTube.
