### ISSUE TITLE
feat(youtube): add a seekbar to rewind and fast forward shorts

### ISSUE THREAD

**Issue by UltraHDR** [revanced/revanced-patches#2110]
### Application

com.google.android.youtube

### Issue

Not able to rewind/forward a video

### Patch

Something similar to https://github.com/revanced/revanced-patches/blob/main/src/main/kotlin/app/revanced/patches/tiktok/interaction/seekbar/patch/ShowSeekbarPatch.kt for YouTube

### Motivation

Shows progress bar for all video

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by 0xrxL** [comment]
There's already on iOS version, so I guess there will be soon ported on Android too.

**Comment by oSumAtrIX** [comment]
Send the link to the source code of the iOS version that enables it please.

**Comment by oSumAtrIX** [comment]
#491
