### ISSUE TITLE
feat(patch): fix YouTube bug: Quitting the app after opening Autoplay settings resets some General settings.

### ISSUE THREAD

**Issue by pressRtowin** [revanced/revanced-patches#2120]
### Application

YouTube

#### Note: this is not a _bug report_ as the issue exists on stock YouTube. This is a _feature request_ to patch the undesired behavior (if possible) 

See title. `Zoom to fill screen` does not seem to be affected but both `Double-tap to seek` and `Enable stats for nerds` are. I have not tested other settings.

To reproduce:
1. Open ReVanced.
2. Change affected settings in `General`.
3. Resume normal operation of YouTube.
4. At any point during normal operation, open the `Autoplay` tab in settings.
5. Fully close YouTube.
6. Open YouTube.
7. Check `General` settings and see that some settings have been reset.

### Patch

Fix the above behavior. All settings should be persistent regardless of menus opened.

### Motivation

It fixes a very annoying issue with YouTube.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
If this is an issue with YouTube, it's their responsibility to fix it

**Comment by oSumAtrIX** [comment]
No, we don't have access to the code, YouTube does. It is not a "quick fix" for us because we would need to make the efforts to reverse engineer the app, figure out the source of the issue and develop a patch that fixes it unlike Google simply pushing the fix as they should because it's an issue on their end. We are not YouTube tech support. The patch request is unreasonable.

**Comment by oSumAtrIX** [comment]
Looking at the code/Reversing it already implies that the fix is not quick, the sentence is contradicting therefore.

**Comment by oSumAtrIX** [comment]
This issue remains a patch request which is our decision to dismiss. The request is unreasonable as previously explained.
