### ISSUE TITLE
Download Video in Youtube(Revanced)

### ISSUE THREAD

**Issue by Emanuele-1998** [revanced/revanced-patches#2122]
### Application

Youtube 

### Issue

Patch for download video

### Patch

I would like to download the videos without also installing NewPipe to download them

Example:

https://postimg.cc/nXktsnyD/be15e414

### Motivation

Downloading videos directly from Revanced with the patch saves time and space without installing NewPipe

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Newpipe or any other downloader does not consume nearly as much space as a video you download & it does not save any additional time.

**Comment by Emanuele-1998** [comment]
> Newpipe or any other downloader does not consume nearly as much space as a video you download & it does not save any additional time.

ok but it could be useful to integrate to have everything more complete, like the same thing then the background also supports it NewPipe why then integrate it into Revanced?

**Comment by Emanuele-1998** [comment]
> Newpipe or any other downloader does not consume nearly as much space as a video you download & it does not save any additional time.

ok but it could be useful to integrate to have everything more complete.
