### ISSUE TITLE
Dark mode for TikTok

### ISSUE THREAD

**Issue by LostCat123** [ReVanced/revanced-patches#2143]
### Application

TikTok

### Issue

Idk

### Patch

Dark mode for TikTok 

### Motivation

Reduce eye damage

**Comment by ThatOneOcto** [comment]
why do you keep referencing that pr on all tiktok dark mode requests when the two have absolutely zero correlation

**Comment by Ushie** [comment]
This issue was transferred in a migration of the patches repository, the reference is just messed up post-migration
