### ISSUE TITLE
bug: Tasker: Need to purchase the app

### ISSUE THREAD

**Issue by Stale-1** [revanced/revanced-patches#2145]
### Type

Other

### Bug description

The Patch for Tasker will work for a while but after a Day or Two it will get detected.

### Steps to reproduce

Patch Tasker to unlock Trial, after a day or two it will say trial expired.

Tasker Trial is 7 days but it will say Trial Already over even though it should not be over yet. 

### Relevant log output

```shell
Dont think its necessary for this bug.
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
#1408
