### ISSUE TITLE
bug: shorts tile showing at bottom 

### ISSUE THREAD

**Issue by kanishk-upadhyay** [revanced/revanced-patches#2147]
### Type

Cosmetic

### Bug description

the shorts and create tile are showing at the bottom even when hide shorts shelf is turned kn

### Steps to reproduce

opening the revanced app

### Relevant log output

```shell
shorts tile is present
```

### Screenshots or videos

![Screenshot_2023-05-14-13-56-29-35_d11ae654701a5fadb313ea6fa9a6836f](https://github.com/revanced/revanced-patches/assets/66172350/ee4e2973-aa94-414f-9972-1adce192ce35)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
The shelf is not the same as the button. The Shorts shelf is hidden correctly.

**Comment by trlkly** [comment]
To disable the Shorts tile, click your avatar in the top right, and go to  Settings > ReVanced > Layout > Navigation button settings > Hide shorts button. 


It took me a bit to find it, too.
