### ISSUE TITLE
bug: Opening links, the video starts in a minimised window

### ISSUE THREAD

**Issue by szabolcs5757** [revanced/revanced-patches#2148]
### Type

Error at runtime

### Bug description

When I open a YouTube video from any external sources with the app not running in the background, the video starts in minimised window at the bottom of the screen. Everything else is black and unresponsive except the back arrow button on the top left corner. After clicking on it, I can open the minimised video and watch it full screen.

### Steps to reproduce

1. Open any external YouTube link

I'm on a non-rooted Huawei P30, EMUI 12.0.0, Android 10. I'm using the latest YouTube version (18.16.37), but
this has happened with every single version I've tried. 
Latest MicroG from inotia00

### Relevant log output

```shell
.
```

### Screenshots or videos

![Screenshot_20230514_124346_app revanced android youtube](https://github.com/revanced/revanced-patches/assets/127993162/0aeba742-c6e4-4474-9ace-6e1558468249)

### Solution

The problem can be fixed by logging in with a google account

### Additional context

This affects other users as well
[Reddit post](https://www.reddit.com/r/revancedapp/comments/10rlzaw/all_youtube_links_open_in_mini_player/?utm_source=share&utm_medium=android_app&utm_name=androidcss&utm_term=1&utm_content=share_button) 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
You are not logged in, log in.

**Comment by MoneyAllDay** [comment]
I have the exact same issue and I'm using the proper [Vanced MicroG](https://github.com/TeamVanced/VancedMicroG/releases).

So the only way to fix this is to login?
I would prefer to use the app without login in.

**Comment by szabolcs5757** [comment]
I tried replacing the microG with the recommended one but it did not solve the problem. Even on a new phone, the problem persist. I ended up creating a disposable Gmail account and I use revanced with it. That way the problem is fixed and I don't risk my main Gmail account.

**Comment by MoneyAllDay** [comment]
@oSumAtrIX Is this something that can't be fixed without login in?

Only tagging you because more people seem to be having this issue.

**Comment by oSumAtrIX** [comment]
This is not an issue with ReVanced but YouTube

**Comment by Emonkyni** [comment]
I have this issue. It is NOT happening with unpatched YouTube, only with the patched /revanced version.

**Comment by oSumAtrIX** [comment]
It happens in the unpatched app in the same situation which is when you are logged out.

**Comment by Emonkyni** [comment]
> It happens in the unpatched app in the same situation which is when you are logged out.

Thank you
