### ISSUE TITLE
feat(reddit): option to open videos and links in external browser

### ISSUE THREAD

**Issue by egscodes** [revanced/revanced-patches#2153]
### Application

Reddit

### Issue

The option for old/different video player
the option to open links in external apps

### Patch

simply the video player that's "tictoc" themed is horrible i miss the video player from old versions (example 2021.23.0 i downgraded but post tend to take forever to load, idk if thats my wifi problem or reddit)

Also noticed that they removed the option to open links in external browser... 

### Motivation

video player is ugly and external browser is probably better

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by soymadip** [comment]
Yeah the external browser patch would be so helpful

**Comment by SodaWithoutSparkles** [comment]
I just hate that reddit removed the functionality to open links externally. Not only is this a massive security risk (in-app browsers can inject whatever they like, such as arbitrary JS, to the page), this also removes the ability to copy links. 

I was able to use "Copy links to clipboard" as url handler to, well, copy links to clipboard. But now i have to copy the whole comment and select out the part that i actually need. 

For example, lets say a comments links to a forum page that requires login to view. Doing so using the in-app browser has a major security risk of potentially getting your login cookie stolen. So the only option would be to copy the whole comment, paste it somewhere, select the url that you need, then paste it into a browser, which may or may not need to be redirected to an app. But that could be done via sth like link-sheet or "Open with" url handler in 2 clicks: Click the link, and click the browser/app to open it.
