### ISSUE TITLE
feat(patch): facebook

### ISSUE THREAD

**Issue by egscodes** [revanced/revanced-patches#2154]
### Application

Facebook & Facebook lite?

### Issue

Removing ads, dating, adding video progressbar/seekbar tapping to Reels, adding external browser

### Patch

facebook has ads everywhere, in the main screen, videos, popup in videos(basically 5 sec forzed ads),reels,etc.

For dating it just keeps appearing even though i don't care to use it... 

For progress bar/seekbar tapping not all reels have it and the ones that do seem to be rare (i think they even removed them in latest updates...)

for browser facebook just doesn't  have the option to open links in external browser...

### Motivation

Adds are annoying, dating is useless if you wish to not use it and annoying by default, for reels having to rewatch a video just to go to a x point is a pain..., for external browser the browser just feels like data farming and i just hate it 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
#702
