### ISSUE TITLE
bug: `FullscreenPanelsPatch` crash when you open PiP or put the video in background

### ISSUE THREAD

**Issue by MrPurple666** [revanced/revanced-patches#216]
## 🐞 Issue

Revanced crashes when you try to open Revanced
via PiP mode or try to set it to "audio-only" mode via PiP.

## ⚙ Reproduce

Put Revanced in PiP mode and try to open it to return to Revanced or set it to "audio-only" via PiP.

If needed here is a system generated crash log:
[Crash log](https://paste.crdroid.net/QBPMTe) 

## ⚠ Additional context

My setup to build Revanced was:
Cli: 2.6.0
Integrations: 0.28.0
Patches: 2.20.4

**Comment by bogadana** [comment]
get integrations 27.4, 28 is a mistake

**Comment by MrPurple666** [comment]
> 

Thank you very much.
Fixed in integrations 0.27.4
