### ISSUE TITLE
Remove addictive features from Instagram 

### ISSUE THREAD

**Issue by lu4p** [revanced/revanced-patches#2164]
### Application

Instagram

### Issue

I just want to see the content of people I follow on Instagram, but Instagram hooks you in at every opportunity with extra suggested content. This leads to me wasting too much time on Instagram.

### Patch

- remove suggested posts from the home tab
- remove suggested reels from the home tab
- remove all suggested content from the search tab
- disable the reels tab
- remove ads from stories

### Motivation

Save people from mindlessly scrolling Instagram.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
https://github.com/revanced/revanced-patches/issues/1652
