### ISSUE TITLE
bug (youtube): Crashes multiple times on launch.

### ISSUE THREAD

**Issue by nicco1690** [revanced/revanced-patches#2165]
### Type

Error at runtime

### Bug description

After installing the Revanced Manager, enabling experimental patches for the MicroG patch to be used (my phone is non-rooted), selecting the YouTube APK (latest from Play Store as of yesterday, May 14th), then keeping the default patches and toggling the MicroG patch, then patching the app (successfully, but there are dependancy errors in the log) and installing it, it does not open. Instead, Android reports that it keeps crashing frequently. 

### Steps to reproduce

1. Download the YouTube app from the Google Play Store.
2. Use an APK ripper to rip the app's APK to an accessible folder.
3. Install and open the Revanced Manager (latest release from GitHub)
4. Enable Experimental Patches Support from the app's Settings tab
5. Select the YouTube APK in the Patches section
6. Apply the following patches: Custom Branding, Disable Zoom Haptics, Enable Debugging, Hide Cast Button, Hide Plaher Buttons, Premium Heading, Theme, Vanced MicroG Support
7. Patch the APK
8. Install and open the APK
9. The app should now crash on startup, as seen in the attached video

### Relevant log output

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Deleting existing resource cache directory
Decoding resources
Applied custom-branding
Failed to apply disable-zoom-haptics: 'disable-zoom-haptics' depends on 'settings' but the following error was raised: Failed to resolve ThemeSetterAppFingerprint
Failed to apply enable-debugging: 'enable-debugging' depends on 'settings' but the following error was raised: 'settings' did not succeed previously
Failed to apply hide-cast-button: 'hide-cast-button' depends on 'settings' but the following error was raised: 'settings' did not succeed previously
Failed to apply hide-player-buttons: 'hide-player-buttons' depends on 'settings' but the following error was raised: 'settings' did not succeed previously
Failed to apply premium-heading: The file /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-HQNMJD/cache/res/drawable-xxxhdpi/yt_premium_wordmark_header_light.png does not exist in the resources. Therefore, this patch can not succeed.
Failed to apply theme: 'theme' depends on 'ThemeResourcePatch' but the following error was raised: 'ThemeResourcePatch' depends on 'settings' but the following error was raised: 'settings' did not succeed previously
Failed to apply vanced-microg-support: 'vanced-microg-support' depends on 'hide-cast-button' but the following error was raised: 'hide-cast-button' depends on 'settings' but the following error was raised: 'settings' did not succeed previously
Repacking patched apk
Compiling resources
Writing modified dex files
Finished!
```

### Screenshots or videos

https://github.com/revanced/revanced-patches/assets/78063037/6dd93883-c660-4d25-99a9-8974e34fafcf

### Solution

Not applicable

### Additional context

My phone is not rooted
My phone is a Galaxy A70
My phone is running the latest available Android 11 and OneUI 3.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Step 4 is your issue.

**Comment by nicco1690** [comment]
So I can't run it at all without root then? That's unfortunate.

**Comment by oSumAtrIX** [comment]
Root has nothing to do with selecting patches incompatible with the APK you select.

**Comment by Kobewaxman** [comment]
> So I can't run it at all without root then? That's unfortunate.

Download and install the recommended yt apk, which is 18.16.37

https://www.apkmirror.com/apk/google-inc/youtube/youtube-18-16-37-release/youtube-18-16-37-2-android-apk-download/
