### ISSUE TITLE
feat(YouTube): Remove the annoying auto pauze & are you still watching notification

### ISSUE THREAD

**Issue by Ryujin9610** [ReVanced/revanced-patches#2166]
### Type

Functionality

### Issue

After a while the "are you still watching" onscreen notification pops up and after while if you dont respond it auto pauzes.

### Feature

Removing the annoying thing. Or atleast make a toggleable thing for it in settings.

### Motivation

Because the current "feature" is annoying and useless

**Comment by bigyihsuan** [comment]
> Duplicate of another issue

Which issue is this a dup of?

**Comment by oSumAtrIX** [comment]
https://github.com/ReVanced/revanced-patches/issues?q=still+watching
