### ISSUE TITLE
problem: `Youtube Music compiled for non-root doesn't get installed`

### ISSUE THREAD

**Issue by redskulmirror23** [revanced/revanced-patches#217]
## 🐞 Issue

YouTube music apk compiled with every patch applied just fails to install for some reason. The package is correct. When tried installing un-modded apk, it installs fine. As soon as one is compiled with revanced patches, it fails to install. Might be bacuse of the same package name as original YouTube Music.

## ⚙ Reproduce
Just compile the apk and try to install normally. Doesn't work

**Comment by Canny1913** [comment]
Because the music-microg-support patch is incomplete.
