### ISSUE TITLE
bug: Twitter Patch Problem

### ISSUE THREAD

**Issue by Exorcism0666** [revanced/revanced-patches#2181]
### Type

Error while patching

### Bug description

Some patches are not applied on the latest stable version of Twitter.

### Steps to reproduce

Step 1. Download the latest release (Stable) of Twitter on APKMirror.

Step 2. Activate the following patches: Dynamic color, Export all activities, Hide ads, Hide recommended User.

Step 3. There will be an error regarding the "hide-ads" and "hide-recommended-users" patch.

(sorry for my bad english)

### Relevant log output

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Deleting existing resource cache directory
Decoding resources
Applied dynamic-color
Applied export-all-activities
Failed to apply hide-ads: 'hide-ads' depends on 'json-hook' but the following error was raised: Unexpected integrations.
Failed to apply hide-recommended-users: 'hide-recommended-users' depends on 'json-hook' but the following error was raised: 'json-hook' did not succeed previously
Repacking patched apk
Compiling resources
Writing modified dex files
Finished!
Installing patched file using nonroot method
Installed!
```

### Screenshots or videos

![Screenshot_2023-05-10-07-48-25-63_a85b47aaa863e3bc831e16d29c27a79c](https://github.com/revanced/revanced-patches/assets/46537034/b91ab0c8-0c0a-470e-bec2-15265247a4c3)

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
https://github.com/revanced/revanced-patches/issues/1981
