### ISSUE TITLE
feat(patch): Unlock Premium for Transcriber (for WhatsApp)

### ISSUE THREAD

**Issue by Patendo** [revanced/revanced-patches#2183]
### Application

Transcriber for WhatsApp

### Issue

The app wastes a lot of time with intentionally long animations, menus, and ads, which can only be disabled by paying too high a monthly fee. 

### Patch

The patch should unlock Premium, which disables ads and skips annoying menus.

### Motivation

Very many people use WhatsApp and receive voice messages from friends and acquaintances, which can only be listened to with headphones or out loud. Transcriber for WhatsApp converts the audio to text, so you can read the audio as text on the go. More than 5 million people have already downloaded the app from the Google Playstore. Unfortunately, using the app is plagued by deliberate delays and lots of ads that can only be removed by paying a disproportionately high monthly fee. That's why I think that after Revanced's other apps have already received a premium patch, this one would also be an enrichment for many people.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Patendo** [comment]
The same could be said for the app Yuka or Photomath and still I think the premium patch was a good idea with these apps. Unlike the two apps, Transcriber for WhatsApp, for example, costs 5€ per month in Germany. Photomath, for comparison, costs less per month in an annual subscription. There is also a lack of alternatives that can do the same. I don't see an urgent need, but I do see a target group that would like to see such a patch, including myself.

**Comment by oSumAtrIX** [comment]
These were PRed, or the issue was present when there weren't this many requests for patches, the more requests for patches, the better the motivation has to be.

**Comment by Patendo** [comment]
Okay, I see. My only argument would just be the too high price for the few (forcing) features, just like YouTube Premium. Does this app go on a waiting list and is processed when fewer requests arrive or is a patch of this app basically rejected?

**Comment by oSumAtrIX** [comment]
Currently, it is being rejected because it lacks proper motivation on why it should be patched, after all its a patch request, it doesn't prevent anyone of actually featuring a patch for it though.
