### ISSUE TITLE
feat(patch): Duplicate File Fixer - Remover (Unlock All Features)

### ISSUE THREAD

**Issue by Stale-1** [revanced/revanced-patches#2185]
### Application

Duplicate File Fixer - Remover
by Systweak Softwares
https://play.google.com/store/apps/details?id=com.duplicatefilefixer

### Issue

The Features of the App is Restricted.

### Patch

Unlock the all the Features of the App. Especially, the "Scan Similar Photos".

### Motivation

Duplicate File Fixer is a very useful tool. It helps the user find duplicate files and easily delete it.
One of the best Feature of the app is the "Similar Image Detection" which detects not just the same photos but also the similar ones.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
There are multiple apps with the same feature and are free and most apps are useful.

**Comment by Stale-1** [comment]
> There are multiple apps with the same feature and are free and most apps are useful.

I have tried many apps but this app is the only app that have "Similar Photos Detection".

Most duplicate file finder apps can only detect exact files but not similar photos.
