### ISSUE TITLE
feat(patch):  Youtube Playlist Length 

### ISSUE THREAD

**Issue by eslam69** [revanced/revanced-patches#2189]
### Application

Youtube

### Issue

Adding the total length of a playlist below the playlist description field would be a great enhancement. It would provide a convenient way for users to quickly assess the overall duration of the playlist.

### Patch

Many browser extensions provide playlist statistics, including total duration, average duration, and total duration for 1.5x playback speed. However, simply displaying the total duration of all videos would suffice, and this statistic could be conveniently shown beneath the playlist description field. Calculating these stats can be achieved by iterating through the video metadata using the YouTube API.

### Motivation

It provides a rapid summary of the playlist's size, particularly crucial for larger ones, which is valuable information for tutorial playlists.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by EhabxAlaa** [comment]
> The total duration does not add any valuable information, I don't know how it is useful

Not the Author but i think it does provide value especially for trying to estimate how much time will it take you to finish that course (playlist), so i do sum the videos time by myself when needed , it does not provide value for all content but it does for others , hopefully you consider it again

**Comment by oSumAtrIX** [comment]
If you look at a course, you can estimate the average duration by looking at the individual times, it takes a couple seconds.

**Comment by AhmedKhaled8** [comment]
> The total duration does not add any valuable information, I don't know how it is useful

I respectfully disagree with this feature being invaluable. The total length of a playlist can provide multiple information and observations accurately for multiple aims. Why let the user multiply the number of videos by the average time calculated also by observing the time of around 5 videos which provides an inaccurate assumption that all videos in the playlist all around the same duration range which is not true for almost all types of playlists except those collecting videos of a TV series? I'd highly suggest reconsidering it.

**Comment by oSumAtrIX** [comment]
> The total length of a playlist can provide multiple information and observations accurately for multiple aims

Please list them.

> Why let the user multiply the number of videos by the average time calculated

Because it takes a hot second. From the following screenshot, I can instantly say, that the playlist takes around 3-4h :
![image](https://github.com/revanced/revanced-patches/assets/13122796/713bfd9d-2dcb-4d8d-9f32-47d913adce2a)

**Comment by AhmedKhaled8** [comment]
> > The total length of a playlist can provide multiple information and observations accurately for multiple aims
> 
> Please list them.
> 

Sure, it's useful to accurately allocate time in your schedule to finish the playlist in one take or multiple. Also, it's useful to approximately determine how much quota you may need or use to watch or download the playlist.

> > Why let the user multiply the number of videos by the average time calculated
> 
> Because it takes a hot second. From the following screenshot, I can instantly say, that the playlist takes around 3-4h : ![image](https://user-images.githubusercontent.com/13122796/239658218-713bfd9d-2dcb-4d8d-9f32-47d913adce2a.png)

Here, you provided a playlist of 5 videos which for people with good maths takes a second to tell how much time the playlist does take. Can you tell me what is the total time of the playlist shown in the picture I attached with this comment which has over 100 videos given the same sample of 5 videos?

![image](https://github.com/revanced/revanced-patches/assets/43890722/2c9764d9-3aa5-4d19-bb3c-0a3f79eaae19)

**Comment by oSumAtrIX** [comment]
> Sure, it's useful to accurately allocate time in your schedule to finish the playlist in one take or multiple. Also, it's useful to approximately determine how much internet quota you may need or use to watch or download the playlist.

Both are doable by estimating the approximate duration of a playlist.

> Can you tell me what is the total time of the playlist shown in the picture I attached with this comment which has over 100 videos given the same sample of 5 videos?

By considering a small sample of the videos, I can assume the average video length is 10m. Multiply by 101 videos, and you have the approximate length. Since the playlist contains 101 videos, being off by an hour wouldn't make a huge difference.

**Comment by EhabxAlaa** [comment]
> > Can you tell me what is the total time of the playlist shown in the picture I attached with this comment which has over 100 videos given the same sample of 5 videos?
> 
> By considering a small sample of the videos, I can assume the average video length is 10m. Multiply by 101 videos, and you have the approximate length. Since the playlist contains 101 videos, being off by an hour wouldn't make a huge difference.

Just open the issue again and let someone else work on it if possible , if you find it useless, you can see that a lot of other people don't agree, so please consider it again even for the far future
 sorry for asking again i am probably too annoying by now 🙂
