### ISSUE TITLE
YouTube Music Revanced Root support for Arm V7 architecture 

### ISSUE THREAD

**Issue by Fa3l** [revanced/revanced-patches#219]
## 🐞 Issue

The problem is that the root version of YouTube Music doesn't support Android phones with Arm V7 architecture and with that I can't use it and several people can't either

## ❗ Solution

The solution would be to create a version of the YouTube Music Revanced root patches for Arm V7 architecture

## ❓ Motivation

this addition would be very good for the project as many people still use Android phones with Arm V7 architecture and with the integration of this idea many people could use the application and also the old YouTube vanced supported this architecture

**Comment by reisxd** [comment]
You need to patch the APK thats for the armv7 arch.

**Comment by oSumAtrIX** [comment]
What is the error you get.
