### ISSUE TITLE
feat(patch): 

### ISSUE THREAD

**Issue by AdityaAnand99** [revanced/revanced-patches#2193]
### Application

SVPlayer 
https://play.google.com/store/apps/details?id=com.svpteam.svp

### Issue

Please unlock the pro version of SVPlayer.

### Patch

A patch that would unlock the features included in the "Pro" version of it.

### Motivation

SVPlayer is probably the only video player on Android that plays 30FPS video as a 60 FPS one, on the fly. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
A quick play store search revealed numerous other apps that do the same thing, therefore the motivation is insufficient.
