### ISSUE TITLE
Black screen on playing Twitter videos 

### ISSUE THREAD

**Issue by Mohammedibrahim15** [revanced/revanced-patches#2202]
### Type

Other

### Bug description

Whenever I patch Twitter with only Hide ads patch i found that almost 90% of videos cannot be played showing only black screen. this occurs with any version of twitter and with any method of patching ( CLI. Revanced manager and revanced builder)

### Steps to reproduce

Download twitter
Patch with hide-ads patch

### Relevant log output

```shell
java -jar revanced-cli-2.21.2-dev.2-all.jar -c -a Twitter.apk -o RevancedTwitter.apk -b revanced-patches-2.174.0-dev.36.jar -m revanced-integrations-0.108.0-dev.22.apk -e dynamic-color -e hide-recommended-users -e hide-views-stats
INFO: Reading dex files
INFO: Decoding AndroidManifest.xml only, because resources are not needed
INFO: Skipping change-package-name: Excluded by default
INFO: Skipping dynamic-color: Manually excluded
INFO: Skipping enable-android-debugging: Excluded by default
INFO: Skipping export-all-activities: Excluded by default
INFO: Skipping hide-recommended-users: Manually excluded
WARNING: Skipping hide-views-stats: Incompatible with version 9.89.0-release.1. This patch is only compatible with com.twitter.android: 9.69.1-release.0, 9.71.0-release.0
INFO: Skipping predictive-back-gesture: Excluded by default
INFO: Skipping remove-screenshot-restriction: Excluded by default
INFO: Skipping spoof-wifi-connection: Excluded by default
INFO: Merging revanced-integrations-0.108.0-dev.22.apk
INFO: hide-ads succeeded
INFO: Not compiling resources because resource patching is not required
INFO: Writing modified dex files
INFO: Aligning Twitter.apk to RevancedTwitter_aligned.apk
INFO: Signing RevancedTwitter_aligned.apk to RevancedTwitter_signed.apk
INFO: Copying RevancedTwitter_signed.apk to RevancedTwitter.apk
INFO: Failed to clean up cache directory
INFO: Finished
```

### Screenshots or videos

![photo_1_2023-05-20_11-50-55](https://github.com/revanced/revanced-patches/assets/130897201/ef831972-18ba-4ccd-9a84-034283a976ea)
this is the black screen that appears on playing any videos

### Solution

.

### Additional context

.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Some debug logs are printed when ads are hidden, grep for them and check what is printed when you open a video for playback.

**Comment by Mohammedibrahim15** [comment]
where can I find these debug logs?

**Comment by oSumAtrIX** [comment]
Via logcat

**Comment by Mohammedibrahim15** [comment]
I have deleted app cash and now everything is fine and this problem have been solved
