### ISSUE TITLE
[REQUEST] Add patch to unlock Niagara Pro!

### ISSUE THREAD

**Issue by TeaEndsAcronyms** [revanced/revanced-patches#2203]
### Application

Niagara launcher.

### Issue

A lot of things in Niagara launcher are pay-walled, and it's very annoying.
I don't want to pay to make a widget that shows the weather. And since you guys have a patch for nova prime, It would be amazing to have it for Niagara Pro. This would allow for more customizations!

### Patch

A patch that would unlock Niagara Pro features.

### Motivation

A lot of things in Niagara launcher are pay-walled, and it's very annoying.
I don't want to pay to make a widget that shows the weather. And since you guys have a patch for nova prime, It would be amazing to have it for Niagara Pro. (I just copy+pasted the things I said in the issues section lol)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
#1321
