### ISSUE TITLE
feat(patch): Trakt `unlock pro`

### ISSUE THREAD

**Issue by YashjitPal** [revanced/revanced-patches#2204]
### Application

The application is called trakt. This application is used for taking movies and slides that we watch.

### Issue

Recently Trakt got an android application. Unfortunately the new application had some limitations for free users. They have premium features like add blocking, personal list creation, and more. 

### Patch

The issue which I want a patch for is specially blocking the ads. Are are the most annoying thing that. Irritates is the most.

### Motivation

Trakt is a very popular service for the purposes mentioned before. It's not only the trakt app but there are many other apps that run on Trakt accounts even before the release of Trakt app. So it would be a wide decision to patch this app.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by johnconner122** [comment]
What is app's package name? or original website link?

**Comment by YashjitPal** [comment]
> What is app's package name? or original website link?

trakt.tv

**Comment by johnconner122** [comment]
Keep looking at the following URL:

- https://github.com/revanced/revanced-patches/releases/tag/v2.173.0

If new version releases, it'll be available in features. Then you can use `revanced-manager` to patch the app.
