### ISSUE TITLE
feat(patch): 

### ISSUE THREAD

**Issue by AdityaAnand99** [revanced/revanced-patches#2207]
### Application

Adobe Lightroom

### Issue

Unlock the premium features in Lightroom. 

### Patch

Unlock premium features like magic eraser, fix and adjust perspective, make enhancements to specific areas of the photo and not the whole picture, etc.

### Motivation

Adobe Photoshop is arguably the most powerful photo editing app on Android and probably the only app besides 'Google photo premium' to have the "magic eraser" tool.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [ ] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by AdityaAnand99** [comment]
I'm sorry, I don't understand. What does it mean by "closed this as completed"? I'm very new to all github, so sorry if I made any mistakes.

**Comment by oSumAtrIX** [comment]
Acknowledgement was not met.

**Comment by AdityaAnand99** [comment]
Oh! I'm really sorry. Should I make a new post?

**Comment by kazimmt** [comment]
Edit the title of the Post

**Comment by oSumAtrIX** [comment]
> Oh! I'm really sorry. Should I make a new post?

Sure

**Comment by AdityaAnand99** [comment]
Thanks! Btw, I couldn't really find an alternative to SVPlayer. Could you maybe suggest something?
