### ISSUE TITLE
feat(patch): ReInstagram

### ISSUE THREAD

**Issue by AdishSagarawat** [revanced/revanced-patches#2217]
### Application

Instragram - by Meta

### Issue

Disabling ads in Instagram.

### Patch

Allow downloading posts and stories, other features and options etc.

### Motivation

Because ads on instagram makes me really distracted.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by johnconner122** [comment]
![Screenshot_2023-05-21-14-55-16-865-edit_com brave browser](https://github.com/revanced/revanced-patches/assets/107796137/97caf8e9-7320-4f2f-a77f-21c301072f02)



As far as other features are concerned, there is already patch request: #1652
