### ISSUE TITLE
feat(patch):Youtube - More In-Player Buttons for Better UI

### ISSUE THREAD

**Issue by Stale-1** [revanced/revanced-patches#2219]
### Application

Youtube

### Issue

Need to open Flyout Menu everytime I want to change speed, caption, video quality and/or audio track.

### Patch

![Screenshot_20230521_171532](https://github.com/revanced/revanced-patches/assets/74855954/5aa4c44d-45ad-4025-a17a-a5b2316d22b3)

* Add Speed Button In-Player
* Add Caption Selection Button In-Player
* Add Audio Track Selection Button In-Player
* Add Video Quality Selection Button In-Player

### Motivation

1) Makes the UI Better and Convenient by reducing the number of Taps/Clicks to change a Caption/Video Quality/Audio Track.

2) The reason why people still enable the Old FlyOut Menu is because of the Hassle. With this Feature people wouldn't need the Old Flyout Menu. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Unofficial patches
