### ISSUE TITLE
feat(patch): Youtube DNS Restricted Mode disabler

### ISSUE THREAD

**Issue by EnderNon** [revanced/revanced-patches#2220]
### Application

Youtube

### Issue

Youtube DNS Restricted Mode

### Patch

Youtube app has a function where, if you set CNAME dns and add restrict.youtube.com or restrictmoderate.com then it will force restricted mode on any devices connected to that wifi. it would be a nice toggle feature to be able to disable this functionality and force restricted mode to always off,on the device. 

### Motivation

often coffee shops etc. will have this functionality while also having slow wifi, so it's absolutely not a good idea to then connect to a vpn to circumvent this. additionally, the connection will often stop working entirely if you try to change settings to static and set it to google dns. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Nikhilsinha666** [comment]
Yes "force safesearch" is extension for chrome which offers it

**Comment by EnderNon** [comment]
> @EnderNon try setting your DNS server to 8.8.8.8, or try using [Nebulo](https://github.com/Ch4t4r/Nebulo) to change your DNS server. If that works to bypass then there's little reason to create and maintain a patch for this as the patch will simply do exactly the same.

as i noted, for an incredibly strange reason, if you use a custom dns there stops being any data being sent **at all**. Maybe it's just a thing where I live. I haven't tried using nebulo though, if that works I'll close this issue page

**Comment by oSumAtrIX** [comment]
@LisoUseInAIKyrios's point is valid, you can use any other DNS
