### ISSUE TITLE
feat(Facebook Messenger): Allow sending files of any type

### ISSUE THREAD

**Issue by n1cKz1** [ReVanced/revanced-patches#2228]
### Application

Facebook Messenger

### Issue

While on desktop, you can send any type of file you want on messenger simply by dragging or just using the "Attach a file" option. This is not the case for mobile, where you are limited to images, videos and voice/audio clips. This is really annoying and inconvenient since instead of just sending a file directly, you'll have to upload it somewhere else and send the link to the recipient.

### Patch

This patch would add an "Attach a file" button under the 4 dot menu in the chat screen. Or if that can't be done for whatever reason, simply making all files shareable with messenger would be sufficient.

### Motivation

Convenience

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Closing in favour of #2653
