### ISSUE TITLE
Make comments visible even in restricted mode is turned on

### ISSUE THREAD

**Issue by Nikhilsinha666** [revanced/revanced-patches#2233]
### Application

I want to stop watching inappropriate videos because I follow a no fap lifestyle. 🚫🔞 To ensure this, I use restricted mode or a third-party DNS service that enforces YouTube's restricted mode for my entire device. However, when restricted mode is enabled, I'm unable to view comments even on good and clean videos. 😔 I'm unsure why YouTube implements this restriction.

I only want to filter out explicit videos while keeping the comments visible. Because I am a teenager, I need comments, as they can be informative, provide timestamps ⏰⌨️, and offer various other things. 📝🆒 I'm not a child anymore who who should not see comment as well. However, when I turn on the restricted mode to filter explicit and inappropriate content, comments also disappear, even from good videos. 😥🚷 

### Issue

Why we are not allowed to see comments in restricted mode even in good videos? 

### Patch

So can you people divide the YouTube Restricted Mode into two levels: one is the medium level, and the other is the strict level? 🎥🚫🔒 

In the medium level restricted mode, if someone turns it on, all explicit and inappropriate content will be removed from YouTube, but comments will remain visible. 👀🚫🔞 Currently, when the restricted mode is enabled, comments along with adult explicit and inappropriate content are removed in the current version of YouTube. 😔🙅‍♂️ 
Which I don't like.

So, please divide the restricted mode into two levels: the medium level I explained earlier, and 

 

in the strict mode, I would prefer not to see comments or access any bad videos, similar to the current restricted mode option on YouTube.

 Therefore, I request the YouTube revanced team, specifically the founder of YouTube revanced, to address this issue and introduce two levels of restricted mode: medium and strict. 

By incorporating these changes, it would greatly benefit individuals who face the same problem. 🙌 It would also be helpful to include emojis to enhance the user experience. 😄🌟"

### Motivation

Teenagers should have the freedom to see comments in restricted mode; they are not children anymore who are not allowed to see comments or explicit inappropriate adult content. Nor are they adults who can watch anything, including adult videos. We are currently in a phase where we shouldn't watch adult videos, but we can still see comments. However, when we turn on restricted mode on YouTube, the comments disappear as well. This causes me to miss out on timestamps, useful information, and a way to communicate effectively. This feature is also beneficial for those who follow the 'no fap' practice." 🚫📺👶🙈😊

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Restricted mode is a server side content filter and filters potentially mature content, thus comments.
