### ISSUE TITLE
feat(patch): A patch to set Accepted-language/Preferred Language on Samsung Internet

### ISSUE THREAD

**Issue by trmdi** [revanced/revanced-patches#2237]
### Application

Samsung Internet.

### Issue

It does not let the user change the Preferred language like other browsers so some websites would be displayed in wrong languages.

### Patch

This patch should add a new setting that let the user change it.

### Motivation

This is a really good browser with the best dark mode on Android.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Other browsers do and have better support of dark mode

**Comment by trmdi** [comment]
Can you suggest one?

**Comment by oSumAtrIX** [comment]
Firefox, Kiwi and many more

**Comment by trmdi** [comment]
> Firefox, Kiwi and many more

I tried all of them. Not better. Probably you haven't used Samsung Internet. Give it a try you will love it.

**Comment by oSumAtrIX** [comment]
They do because they can use dark reader which has explicit rules for theming pages

**Comment by Stale-1** [comment]
> > Firefox, Kiwi and many more
> 
> I tried all of them. Not better. Probably you haven't used Samsung Internet. Give it a try you will love it.

Edge and Opera have Accounts for Synchronization of other devices. I actually use Opera Browser, Norway is known for Strict Privacy laws unlike Microsoft which is a US Company.

**Comment by trmdi** [comment]
> > > Firefox, Kiwi and many more
> > 
> > 
> > I tried all of them. Not better. Probably you haven't used Samsung Internet. Give it a try you will love it.
> 
> Edge and Opera have Accounts for Synchronization of other devices. I actually use Opera Browser, Norway is known for Strict Privacy laws unlike Microsoft which is a US Company.

Edge doesn't have the dark mode and adblocker.
Opera's built-in adblocker is too bad compared to Samsung Internet's Adguard.

**Comment by trmdi** [comment]
> Yeah i love using Samsung browser too with its amazing AdBlock and amoled dark mode and other amazing futures, and as for your issue if you have a Samsung device you can use an extension to translate pages to your desired language

Unfortunately I don't use the Samsung phone, and I know many guys also do that. I tried to make a FR to Samsung a long time ago but didn't succeed. :(

**Comment by HypeMaxers** [comment]
> Edge doesn't have the dark mode and adblocker. Opera's built-in adblocker is too bad compared to Samsung Internet's Adguard.
Use kiwi / Firefox with ublock origin. That's all you'll ever need. 
Kiwi supports the extensions in the chrome webstore.
Firefox has a preset number of extensions, however you could use the nightly build which allows you to use the desktop extensions.

**Comment by vairag22** [comment]
**ONLY USE OPEN-SOURCE BROWSERS**

There are 2 options:
- Firefox-based Browsers: Better privacy and extension support
- Chromium-based Browsers: Better security and performance

Most commercial browsers such as Samsung Internet, Opera are Chromium-based but they are closed-source.

If want to use a FF-based browser then I recommend [**Mull**](https://divestos.org/pages/our_apps#mull) `FDroid, GitHub`
or if you want to use a Chromium-based browser then I recommend [**Brave**](https://github.com/brave/brave-browser) `PlayStore, GitHub`

Brave by default isn't very privacy-friendly so you'll need to change some settings. 
>Use kiwi / Firefox with ublock origin. That's all you'll ever need.
>Kiwi supports the extensions in the chrome webstore.

Kiwi is open-source for namesake. It has a sketchy track record - [blocks ad-block extensions on some addresses](https://github.com/kiwibrowser/src/blob/2b8388091c71e442910a21ada3d97ae8bc1845d3/extensions/renderer/extension_injection_host.cc#L56), has ads on homepage, forwards searches for commision, etc.
> use Opera Browser, Norway is known for Strict Privacy laws unlike Microsoft which is a US Company.

Opera is owned by a Chinese corporation.
> Firefox has a preset number of extensions, however you could use the nightly build which allows you to use the desktop extensions.

No need to use Nigthly build, just add your own Custom Add-on Collection, [here's instructions](https://www.ghacks.net/2022/10/20/firefox-beta-for-android-now-supports-custom-add-on-collections/). For extensions I suggest you checkout [arkenfoxjs' recommendations](https://github.com/arkenfox/user.js/wiki/4.1-Extensions).

> Edge and Opera have Accounts for Synchronization of other devices.

So do Brave and FF-based browsers. FF-based browsers implement Firefox Sync via FF Account, so sync is cross-compatible with all FF-based browsers. Brave uses Sync Chain which doesn't require any account but there is no cross-compatibility with other Chromium-based browsers. In both cases data is E2E encrypted.

**Comment by EhabxAlaa** [comment]
> **ONLY USE OPEN-SOURCE BROWSERS**
> 
> There are 2 options:
> 
> * Firefox-based Browsers: Better privacy and extension support
> * Chromium-based Browsers: Better security and performance
> 
> Most commercial browsers such as Samsung Internet, Opera are Chromium-based but they are closed-source.
> 
> If want to use a FF-based browser then I recommend [**Mull**](https://divestos.org/pages/our_apps#mull) `FDroid, GitHub` or if you want to use a Chromium-based browser then I recommend [**Brave**](https://github.com/brave/brave-browser) `PlayStore, GitHub`
> 
> Brave by default isn't very privacy-friendly so you'll need to change some settings.
> 
> > Use kiwi / Firefox with ublock origin. That's all you'll ever need.
> > Kiwi supports the extensions in the chrome webstore.
> 
> Kiwi is open-source for namesake. It has a sketchy track record - [blocks ad-block extensions on some addresses](https://github.com/kiwibrowser/src/blob/2b8388091c71e442910a21ada3d97ae8bc1845d3/extensions/renderer/extension_injection_host.cc#L56), has ads on homepage, forwards searches for commision, etc.
> 
> > use Opera Browser, Norway is known for Strict Privacy laws unlike Microsoft which is a US Company.
> 
> Opera is owned by a Chinese corporation.
> 
> > Firefox has a preset number of extensions, however you could use the nightly build which allows you to use the desktop extensions.
> 
> No need to use Nigthly build, just add your own Custom Add-on Collection, [here's instructions](https://www.ghacks.net/2022/10/20/firefox-beta-for-android-now-supports-custom-add-on-collections/). For extensions I suggest you checkout [arkenfoxjs' recommendations](https://github.com/arkenfox/user.js/wiki/4.1-Extensions).
> 
> > Edge and Opera have Accounts for Synchronization of other devices.
> 
> So do Brave and FF-based browsers. FF-based browsers implement Firefox Sync via FF Account, so sync is cross-compatible with all FF-based browsers. Brave uses Sync Chain which doesn't require any account but there is no cross-compatibility with other Chromium-based browsers. In both cases data is E2E encrypted.

Samsung browser is the best doesn't matter if it is open or close source
