### ISSUE TITLE
Consolidate the Hide Get Premium patch into the General Ads patch

### ISSUE THREAD

**Issue by KobeW50** [revanced/revanced-patches#2239]
### Application

YT ReVanced 

### Issue

2 issues:

1) The Hide Get Premium patch is separate from the General Ads patch.

2) The Hide YouTube Premium Advertisement toggle is within the layout settings instead of the Ads settings.

### Patch

Combine the Hide Get Premium patch into the General ads patch, and move the toggle from the Layout settings to the General ads settings.

### Motivation

Makes things more organized.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by SodaWithoutSparkles** [comment]
Technically premium ad is a type of ad, and therefore should be in ads
