### ISSUE TITLE
bug: Failed to apply Change packet name : no package name provided 

### ISSUE THREAD

**Issue by Emorejas** [revanced/revanced-patches#2241]
### Type

Error while patching

### Bug description

Found it while trying to patch, happens everytime (used different APKs)

### Steps to reproduce

Download yt APK
Try to patch it 
Boom error 

### Relevant log output

```shell
https://cdn.discordapp.com/attachments/847945023508840548/1111029397101744200/revanced-manager_patcher_20230524223334143595.log
That's my log data
```

### Screenshots or videos

![Screenshot_2023-05-24-22-21-44-239_app revanced manager flutter](https://github.com/revanced/revanced-patches/assets/67527660/efeba6e5-842a-4fd6-9cf7-ffde1caade1f)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Stale-1** [comment]
> ### Type
> Error while patching
> 
> ### Bug description
> Found it while trying to patch, happens everytime (used different APKs)
> 
> ### Steps to reproduce
> Download yt APK Try to patch it Boom error
> 
> ### Relevant log output
> ```shell
> https://cdn.discordapp.com/attachments/847945023508840548/1111029397101744200/revanced-manager_patcher_20230524223334143595.log
> That's my log data
> ```
> 
> ### Screenshots or videos
> ![Screenshot_2023-05-24-22-21-44-239_app revanced manager flutter](https://user-images.githubusercontent.com/67527660/240734179-efeba6e5-842a-4fd6-9cf7-ffde1caade1f.jpg)
> 
> ### Solution
> _No response_
> 
> ### Additional context
> _No response_
> 
> ### Acknowledgements
> * [x]  I have searched the existing issues and this is a new and no duplicate or related to another open issue.
> * [x]  I have written a short but informative title.
> * [x]  I filled out all of the requested information in this issue properly.

That is not a bug, I think the patch is for CLI not for the GUI that you are using. 

So the only patch you need to change the package name is "MicroG Support" Patch which automatically changes the package name.

**Comment by oSumAtrIX** [comment]
Update ReVanced Manager to latest version.
