### ISSUE TITLE
bug(youtube/old-quality-layout): old quality menu enabled, but still shows new quality menu

### ISSUE THREAD

**Issue by Rikysonic** [revanced/revanced-patches#2250]
### Type

Error at runtime

### Bug description

Enabling the old quality menu in settings still shows the new quality menu.

### Steps to reproduce

- Patch with old-quality-layout
- The new quality layout is still shown

### Relevant log output

```shell
N/A
```

### Screenshots or videos

![Screenshot_20230525-091503561](https://github.com/revanced/revanced-patches/assets/56199646/06684a6f-6af5-4884-a6f5-38a06a5a1aef)
![Screenshot_20230525-091525689](https://github.com/revanced/revanced-patches/assets/56199646/0eb55aa1-3e85-493c-b724-f102af5e6071)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Rikysonic** [comment]
Oh, you're absolutely right! Incognito mode makes the old menu appear normally.

**Comment by 0xrxL** [comment]
> It's almost surely an A/B test by YouTube, where some accounts get changes before others.
> 
> You can try one or more of the following and confirm if the patch starts working again:
> 
> * use incognito mode
> * log into a different YouTube account
> * clear application data
> * use a vpn

If I'm not mistaken this A/B test has been going on for months, in fact I had seen a same bug report in 2022.

**Comment by 0xrxL** [comment]
Yeah...I was not wrong:

https://github.com/revanced/revanced-patches/issues/1325

**Comment by Rikysonic** [comment]
I'll close it, thx for the info guys

**Comment by SodaWithoutSparkles** [comment]
Wait a second, why does your toggle button look like this? Are you using ReVanced Extended?

**Comment by Rikysonic** [comment]
Nono, it's due to the custom ROM - NusantaraProject A10!
![Screenshot_20230525-124938990](https://github.com/revanced/revanced-patches/assets/56199646/6b272842-d93d-4956-bb00-a5aeed9c8228)

**Comment by inotia00** [comment]
Yeah.. this is an A/B test (version affected: YouTube v18.19.xx+)
The quality selection menu has been moved to litho elements in the new layout: `quick_quality_sheet_content.eml-js`

Current `old-quality-layout` patch implements it via `ListView.performItemClick`, but this method is no longer available for new layouts

Just as the new quality selection layout was applied to all users in [YouTube v17.25.34](https://github.com/revanced/revanced-patches/commit/2497425c9f11b8b14c861c2f0f34ff47bdbfac53) in the past, it is highly likely that it will be applied to all users in the near future

**Comment by inotia00** [comment]
update
==
The new quality layout now appears to be applied to all users.

Affected version is YouTube v18.22.xx+

If you spoof v18.21.xx or earlier with the `spoof-app-version` patch, you will still see the old quality layout

The quality layout moved from `android.widget.ListView` to `com.facebook.litho.ComponentHost`, but fortunately I was able to partially reverse the lithoView.

I'll mention it again when the patch is finished.
