### ISSUE TITLE
bug(youtube/theme): splash screen not working as expected

### ISSUE THREAD

**Issue by PalmDevs** [revanced/revanced-patches#2253]
### Type

Cosmetic

### Bug description

With the `theme` patch applied to the YouTube application, its splash screen's background will be black even if you're using light mode. ~~The YouTube icon will also not animate~~ (Not an issue with ReVanced).

I can confirm that this doesn't happen on <2.174.0 patches releases and I consider this unintended.

### Steps to reproduce

1. Download and install ReVanced Manager (or ReVanced CLI)
2. Patch YouTube with the `theme` patch
3. Launch the patched YouTube application and observe the splash screen

### Relevant log output

```shell
(none, not related to the issue)
```

### Screenshots or videos

https://github.com/revanced/revanced-patches/assets/67689562/dd2f4ef8-d064-4b4b-b805-b5fbfac0d655

### Solution

Don't use the `theme` patch (for now).

0xrxL suggested to use a dynamic color, not a static color as the default option for the `theme` patch.

### Additional context

I've seen some users complaining about this issue on the Discord server and I am experiencing this issue as well.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by 0xrxL** [comment]
1) the splash screen is not animated because Google has removed the previous one and is currently A/B testing a new one not yet available (but unlockable with an already found patch). You can also mix both with the following result:

https://github.com/revanced/revanced-patches/assets/127248639/7e808a99-376d-48dc-9ee8-9a0bea15cc9f



2) About the color not following the theme, just use a dynamic color in the file ```/drawable/quantum_launchscreen.xml```

**Comment by PalmDevs** [comment]
> 1) the splash screen is not animated because Google has removed the previous one and is currently testing a new one not yet publicly available (but unlockable with an already found patch). You can also mix both with the following result:
> 
> https://github.com/revanced/revanced-patches/assets/127248639/7e808a99-376d-48dc-9ee8-9a0bea15cc9f
> 
> 
> 
> 2) About the color not following the theme, just use a dynamic color in the file ```/drawable/quantum_launchscreen.xml```

2. This doesn't happen on older versions of patches. Is this intended?

**Comment by PalmDevs** [comment]
So, it's not a ReVanced issue. I see.

**Comment by 0xrxL** [comment]
> So, it's not a ReVanced issue. I see.
> 
> However, I would still recommend setting the default value of the `splashScreenBackgroundColor` option (in the `theme` patch, of course) to be `?android:colorBackground` _(or whatever the default value is)_. (cc. @oSumAtrIX)

It's a ReVanced issue instead, leave the issue opened.

oSum used a static color instead of a dynamic one, on the xml file that I previously described.

**Comment by PalmDevs** [comment]
Closed by #2319.
