### ISSUE TITLE
bug: CandyLink VPN - cannot select individual servers

### ISSUE THREAD

**Issue by Stale-1** [ReVanced/revanced-patches#2263]
### Type

Other

### Bug description

![IMG_20230526_030846](https://github.com/revanced/revanced-patches/assets/74855954/4b4de5d1-d229-42ea-a092-379641a751c9)

Whenever I try to select a Specific Server it always say No Servers Found. You can only connect using "Auto Select".

Let us say the autoselect connects you to France Server. Disconnect the vpn then connect again but this time not autoselect. Select France specifically and it will say no servers found. 

Tried it with other servers, same result. You cannot connect to specific server. 

### Steps to reproduce

Step 1) After Patching CandyLink VPN, I install itm
Step 2) Connect to a Specific Server and it will alway say "No Servers Found"
Step 3) Connect again but this time choose "Auto Select"
Let's say it connects to France, Disconnect the VPN. 
Step 4) Select France and it will say "No Servers Found" even though you just connected there.

### Relevant log output

```shell
Don't think its necessary.
```

### Screenshots or videos

![IMG_20230526_030846](https://github.com/revanced/revanced-patches/assets/74855954/6d371549-13a6-4d3f-a233-1bb4f5d36e15)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by tobix88** [comment]
Same problem here. It's a bug with the Unlock Pro Patch because on the normal app, if you haven't bought premium, only auto connect is available.

**Comment by oSumAtrIX** [comment]
Closing according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#%EF%B8%8F-guidelines-for-requesting-or-contributing-patches). Thanks anyways.
