### ISSUE TITLE
feat: ReVanced MicroG for NonRoot

### ISSUE THREAD

**Issue by shadow578** [ReVanced/revanced-patches#2265]
### Type

Other

### Issue

currently, revanced uses the microG fork from old vanced for nonroot installs.
That fork is (imho) a mess and will probably not get updates anymore (also because it's a mess).

### Feature

basically a fork of microG for use with revanced, kinda like old vanced did it.
This would also have the advantage of not using old vanced's wonky fork

### Motivation

- get updates from upstream microG
- package name of revanced microG could be changed to something less stupid (currently it's `com.mgoogle.android.gms`, could be changed to `app.revanced.android.gms`)
- replace wonky vanced codebase with something less bad

### Additional context

as common with my issues, i've already laid the groundwork for this. see https://github.com/shadow578/GmsCore.

**Comment by KobeW50** [comment]
Can this be closed now?

**Comment by masterflitzer** [comment]
well is it implemented?

**Comment by KobeW50** [comment]
> well is it implemented?

If I'm understanding this feature request correctly, then yes.

ReVanced now has a fork of GmsCore (aka MicroG) which can be used by setting the patch option for the `GmsCore support` patch to `app.revanced`.

**Comment by masterflitzer** [comment]
does it work without root? meaning i can uninstall vanced microg, install revanced gmscore and patch the latest version of the app?

**Comment by KobeW50** [comment]
> does it work without root? meaning i can uninstall vanced microg, install revanced gmscore and patch the latest version of the app?

Yes, as long as you change the patch option for the GmsCore support patch. However, Vanced MicroG is still recommended and the default for YT and YT Music.

**Comment by masterflitzer** [comment]
> > does it work without root? meaning i can uninstall vanced microg, install revanced gmscore and patch the latest version of the app?
> 
> Yes, as long as you change the patch option for the GmsCore support patch. However, Vanced MicroG is still recommended and the default for YT and YT Music.

cool stuff, if i understand correctly the issue is then completed
