### ISSUE TITLE
bug: the shorts button no longer hides

### ISSUE THREAD

**Issue by apernouille** [revanced/revanced-patches#2265]
### Type

Cosmetic

### Bug description

Since the latest updates, the "hide-shorts-components" module no longer makes the shorts button disappear on the YouTube application bottom bar. The other patches on the shorts player work perfectly. 

### Steps to reproduce

Step 1. Install YouTube ReVanced from this link : https://github.com/apernouille/revanced-magisk-module/releases/tag/25
Step 2. Enable "Hide shorts" in Settings > ReVanced > Layout > Shorts components
Step 3. Restart the app

### Relevant log output

```shell
Don't think it's necessary.
```

### Solution

Rollback some changes? It worked perfectly before.

### Additional context

Enabled patches :
- hide-shorts-components
- disable-shorts-on-startup
- video-speed
- disable-auto-captions
- return-youtube-dislike
- sponsorblock

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Hiding shorts hides shorts, not the button in the navigation bar.

**Comment by apernouille** [comment]
But this patch used to do exactly that! Can't we do it now?

**Comment by oSumAtrIX** [comment]
No, the patch has never used to do that, you can hide the button using the navigation bar patch.
