### ISSUE TITLE
feat: Move the Video settings above the Misc settings

### ISSUE THREAD

**Issue by KobeW50** [revanced/revanced-patches#2266]
### Application

YT ReVanced 

### Issue

The settings look disorderly because the Miscellaneous menu is not at the bottom.

### Patch

Swap the places of the video and Miscellaneous settings menu.

![Screenshot_20230525_162001](https://github.com/revanced/revanced-patches/assets/84587632/83f83568-89f9-4afc-a541-7db899c0a592)

### Motivation

It will make the settings menu look nicer.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Everything is intentionally sorted alphabetically, without removing alphabetic sorting this won't be possible.
