### ISSUE TITLE
feat(patch): stats.fm

### ISSUE THREAD

**Issue by Luwis13** [revanced/revanced-patches#2270]
### Application

Stats.fm it's initially a website and also has a mobile app. Please patch the mobile app of it.

### Issue

Stats.fm plus which implies the "import lifetime history" and many more.

### Patch

This patch should make the stats.fm functional as plus user. I don't know if it's kinda server side. But this popular service needs a patch. I don't also even know if you guys can do it but I'll request you to atleast try to patch it.

### Motivation

I've to say a lot here. First of all there are lot of sub reddits and request pages for people requesting it to get patched for premium or plus features. There is a super high need of it to get patched and there are a lot of users who forcefully have to pay to use it. Even I've seent his on my own eyes. It would be super great if this application is patched. It will open a great possibility to Spotify users.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Theres enough demand for any kind of application, doesn't matter this has priority.
