### ISSUE TITLE
Changing Homepage to Subscriptions

### ISSUE THREAD

**Issue by matt873** [revanced/revanced-patches#2273]
### Application

Youtube

### Issue

Please add an option for changing the Homepage to Subscriptions in the navigation settings. The option is already present in revanced extended but revanced extended has some issues and is not quite stable, so many people don't want to use revanced extended. It would be nice to have that option in revanced itself.

### Patch

Some screenshots just for demonstration are attached below:
![Screenshot_20230526-151601_1](https://github.com/revanced/revanced-patches/assets/108935493/755fdc13-9329-429d-ac05-f365342d4872)
![Screenshot_20230526-151545](https://github.com/revanced/revanced-patches/assets/108935493/ce5ef5f8-7c02-49ee-964b-58027d48fd2d)

### Motivation

It will be helpful for those who don't want to watch YouTube-recommended videos and want to watch videos only from their subscriptions.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
https://github.com/revanced/revanced-patches/issues/2139

**Comment by sharpsteelsoftware1** [comment]
Is this still under development?
