### ISSUE TITLE
feat: (YouTube Music) Force enable audio playback during phone call

### ISSUE THREAD

**Issue by zetaPRIME** [revanced/revanced-patches#2279]
### Application

YouTube Music

### Issue

Attempting to play music during a phone call emits no audio for no discernible reason; this does not occur with the normal YouTube app.

### Patch

Enable audio playback during phone call if you resume playback, matching YouTube app behavior.

### Motivation

I'm most likely not alone in wanting to be able to listen to music in the background while on a call with someone. iOS allows it, and I can think of no reason for it not to be possible on Android, especially when the sister app already does it.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Call mode reduces audio quality, thus it has no real benefit in terms of listening music.

**Comment by zetaPRIME** [comment]
The problem is that the app refuses to play audio during a call. I want to be able to play my music while also being on the line with someone, such as when I'm out on a walk.

**Comment by oSumAtrIX** [comment]
In that case you can use YouTube to play your music playlist.

**Comment by zetaPRIME** [comment]
What I want to listen to is my own *uploaded* music, which doesn't exist on the YouTube app, only through the Music one. The part that used to be Google Play Music.

**Comment by Julius8900** [comment]
> What I want to listen to is my own *uploaded* music, which doesn't exist on the YouTube app, only through the Music one. The part that used to be Google Play Music.

There are many other music apps you can try.

**Comment by zetaPRIME** [comment]
None of them can access the albums I've already uploaded to this one service, and I don't exactly have the spoons to figure out if there's anything else comparable that both lets me keep my own music in the cloud and doesn't inexplicably refuse to play anything if I happen to be on a call.
