### ISSUE TITLE
feat: hide-community-posts patch 

### ISSUE THREAD

**Issue by nanomoeamezao** [revanced/revanced-patches#228]
## 🐞 Issue

There is no option to hide all community posts in subscriptions page. 

## ❗ Solution

Add a patch to hide all community posts.

## ❓ Motivation

I liked that feature a lot in vanced. Also my sub feed is so full of them.

**Comment by TheJeterLP** [comment]
Duplication of https://github.com/orgs/revanced/discussions/135
