### ISSUE TITLE
feat(patch): YouTube remote control support with landscape rotation lock

### ISSUE THREAD

**Issue by origamiofficial** [revanced/revanced-patches#2280]
### Application

YouTube
(com.google.android.youtube)

### Issue

Existing YT ReVanced can already be used after emulating the cursor as it doesn't support remote control but it is hard to use and scroll. After having this patch we can use the YT Phone app on Android TV with remote control. As we know:

_YouTube TV is not the same as patching a normal app. YT ATV is just a web application and it uses Cobalt which is a Chromium fork and is optimized for lower end devices and Cobalt does not have injecting code._
_Originally posted by @reisxd in https://github.com/revanced/revanced-patches/issues/1428#issuecomment-1372053823_

Also if the rotation is locked in landscape mode then this app will be the best choice for ATV too just like for phones. Yes, there is an app called "SmartTubeNext" but its UI & recommendations are the worst & the dev won't do anything regarding that:

_Compared to SmartTube's UI, Stock Youtube and YT Kids are far ahead. However, we'd need someone who's skilled and willing to dedicate enough time and energy into making it. And into maintaining it longterm (incl. new features, bug fixes).
https://github.com/yuliskov/SmartTubeNext#q-can-you-make-smarttubenext-look-like-the-original-app_

### Patch

The app rotation should be locked in landscape mode and we can use the app via remote control.

### Motivation

* As ATVs doesn't have a touch screen so can be operated through remote
* Best choice as YT client for ATVs
* Easy to use and convenient
* Adfree alternative to (com.google.android.youtube.tv) & (com.amazon.firetv.youtube)
* SmartTubeNext UI doesn't look good
* SmartTubeNext recommendations are the worst

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
> SmartTubeNext recommendations are the worst

The YouTube algorithm makes recommendations equivalent to the app's, and the UI does the job as well as YouTube and doesn't lack any critical functionality. The best choice for ATV remains SmartTubeNext, not the Android YouTube app.
