### ISSUE TITLE
bug(youtube): YouTube crashes when opened from Google Discover

### ISSUE THREAD

**Issue by cyberboh** [revanced/revanced-patches#2282]
### Type

Error at runtime

### Bug description

Whenever i access google discover, yt crashes. 
Yt videos on google discver won't playing

### Steps to reproduce

1. Install YT patched (rooted) , im using j-hc builder `https://github.com/j-hc/revanced-magisk-module`
2. Swipe right to access google discover
3. Scroll down it, and yt will crashes, yt videos on google discover won't playing

### Relevant log output

```shell
--------- beginning of crash
05-27 08:38:03.199 23880 23880 E AndroidRuntime: FATAL EXCEPTION: main
05-27 08:38:03.199 23880 23880 E AndroidRuntime: Process: com.google.android.youtube.player, PID: 23880
05-27 08:38:03.199 23880 23880 E AndroidRuntime: java.lang.ExceptionInInitializerError
05-27 08:38:03.199 23880 23880 E AndroidRuntime: 	at app.revanced.integrations.settings.SettingsEnum.<init>(SettingsEnum.java:394)
05-27 08:38:03.199 23880 23880 E AndroidRuntime: 	at app.revanced.integrations.settings.SettingsEnum.<clinit>(SettingsEnum.java:35)
05-27 08:38:03.199 23880 23880 E AndroidRuntime: 	at app.revanced.integrations.patches.TabletMiniPlayerOverridePatch.getTabletMiniPlayerOverride(TabletMiniPlayerOverridePatch.java:8)
05-27 08:38:03.199 23880 23880 E AndroidRuntime: 	at vff.aI(PG:1)
05-27 08:38:03.199 23880 23880 E AndroidRuntime: 	at yri.J(PG:5)
05-27 08:38:03.199 23880 23880 E AndroidRuntime: 	at yri.a(PG:21)
05-27 08:38:03.199 23880 23880 E AndroidRuntime: 	at atou.a(PG:1)
05-27 08:38:03.199 23880 23880 E AndroidRuntime: 	at mri.a(PG:7)
05-27 08:38:03.199 23880 23880 E AndroidRuntime: 	at mqf.run(PG:40)
05-27 08:38:03.199 23880 23880 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:942)
05-27 08:38:03.199 23880 23880 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
05-27 08:38:03.199 23880 23880 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
05-27 08:38:03.199 23880 23880 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
05-27 08:38:03.199 23880 23880 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7925)
05-27 08:38:03.199 23880 23880 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-27 08:38:03.199 23880 23880 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
05-27 08:38:03.199 23880 23880 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
05-27 08:38:03.199 23880 23880 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean app.revanced.integrations.settings.SettingsEnum.getBoolean()' on a null object reference
05-27 08:38:03.199 23880 23880 E AndroidRuntime: 	at app.revanced.integrations.utils.LogHelper.printException(LogHelper.java:128)
05-27 08:38:03.199 23880 23880 E AndroidRuntime: 	at app.revanced.integrations.utils.LogHelper.printException(LogHelper.java:98)
05-27 08:38:03.199 23880 23880 E AndroidRuntime: 	at app.revanced.integrations.utils.ReVancedUtils.getContext(ReVancedUtils.java:159)
05-27 08:38:03.199 23880 23880 E AndroidRuntime: 	at app.revanced.integrations.settings.SharedPrefCategory.<init>(SharedPrefCategory.java:36)
05-27 08:38:03.199 23880 23880 E AndroidRuntime: 	at app.revanced.integrations.settings.SharedPrefCategory.<clinit>(SharedPrefCategory.java:24)
05-27 08:38:03.199 23880 23880 E AndroidRuntime: 	... 17 more
```

### Screenshots or videos

![Screenshoot](https://github.com/revanced/revanced-patches/assets/99109969/d54de69b-8994-4041-ba80-03861816ffbb)

### Additional context

Integrations: revanced-integrations-0.109.0-dev.1.apk
Patches: revanced-patches-2.175.0-dev.7.jar

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by cyberboh** [comment]
> #1574
> 
> Issue was fixed with patches 2.174.0

if it fixed earlier, why newer patches still contains bug?
revanced-patches-2.175.0-dev.7.jar should contains fixes from 2.174.0

**Comment by cyberboh** [comment]
> I'm trying to reproduce now using a rooted android studio emulator, but I cannot find any videos under the discover tab of the Google app.
> 
> Maybe there's a settings that needs to be enabled? Or are you accessing the discover tab somewhere outside the Google app?

There's no specific settings for it, its just yt video, basically it will show in google discover randomly. or you can "Youtube" as your interest in google discover.

**Comment by cyberboh** [comment]
> This should fix the issue, but I cannot reproduce so I cannot verify: https://github.com/LisoUseInAIKyrios/revanced-patches/tree/embedded_player_fix
> 
> @cyberboh if you can patching the app using the command line tool, then I can post this fix and you can try on your device to verify.

Where i can download the fix? i'll try to patch it

**Comment by cyberboh** [comment]
> [here it is](https://ufile.io/kefamsj0)
> 
> And use the [dev integrations](https://github.com/revanced/revanced-integrations/releases/download/v0.109.0-dev.3/revanced-integrations-0.109.0-dev.3.apk)

stucked here
![image](https://github.com/revanced/revanced-patches/assets/99109969/f0ba8061-e70b-4e4f-b22e-66d1ec722ce7)

how much time it takes?

**Comment by Subbarao6338** [comment]
Vsco not installed on redmi note 7 pro. Fix it

**Comment by Subbarao6338** [comment]
Please also add patches for following if possible :

1. True caller - gold
2. Remini - premium
3. Foxit pdf editor - premium
4. Inshort video editor - pro

**Comment by cyberboh** [comment]
> It should take 1-2 minutes for everything.

i'm waiting for 1 hour, no luck.
then i remove `--mount `parameter, now its processing
![image](https://github.com/revanced/revanced-patches/assets/99109969/d59aebea-25a4-454c-a053-efc3e0a03cee)

so. there's something wrong with `--mount`

**Comment by cyberboh** [comment]
error occured:
```
INFO: Installing without mounting
se.vidstige.jadb.JadbException: Could not install revanced.apk: Failure [INSTALL_FAILED_UPDATE_INCOMPATIBLE: Existing package com.google.android.youtube signatures do not match newer version; ignoring!]

        at se.vidstige.jadb.managers.PackageManager.verifyOperation(PackageManager.java:43)
        at se.vidstige.jadb.managers.PackageManager.install(PackageManager.java:61)
        at se.vidstige.jadb.managers.PackageManager.install(PackageManager.java:65)
        at app.revanced.utils.adb.Adb.deploy$revanced_cli(Adb.kt:35)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:202)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
        
```
        but with --mount, it can not be patched

**Comment by oSumAtrIX** [comment]
Your issue is unrelated to #2282.

**Comment by cyberboh** [comment]
@LisoUseInAIKyrios Hello, sorry to make you waiting so long, finally i managed how to install it with mount. Actually we need rom that suppot natively `Rooted debugging` and lineageos has it (maybe roms based on lineage, such as crdroid also has this feature). My previous rom rooted with magisk, its stucked though.

![Screenshot_](https://github.com/revanced/revanced-patches/assets/99109969/6d91b617-323b-4c8c-b937-866944b273d4)

This is the log:

`E:\ANDROID\TestRevanced>java -jar revanced-cli.jar -a youtube.apk -c -o revanced.apk -b patches.jar -m integrations.apk -d 438c21fa --mount -e vanced-microg-support
INFO: Reading dex files
INFO: Decoding AndroidManifest.xml only, because resources are not needed
INFO: Skipping change-package-name: Excluded by default
INFO: Skipping custom-video-buffer: Excluded by default
INFO: Skipping enable-android-debugging: Excluded by default
INFO: Skipping export-all-activities: Excluded by default
INFO: Skipping predictive-back-gesture: Excluded by default
INFO: Skipping remove-player-controls-background: Excluded by default
INFO: Skipping remove-screen-capture-restriction: Excluded by default
INFO: Skipping remove-screenshot-restriction: Excluded by default
INFO: Skipping spoof-wifi-connection: Excluded by default
INFO: Skipping vanced-microg-support: Manually excluded
INFO: Merging integrations.apk
INFO: Deleting existing resource cache directory
INFO: Decoding resources
INFO: always-autorepeat succeeded
INFO: client-spoof succeeded
INFO: comments succeeded
INFO: copy-video-url succeeded
INFO: custom-branding succeeded
INFO: disable-auto-captions succeeded
INFO: disable-fullscreen-panels succeeded
INFO: disable-player-popup-panels succeeded
INFO: disable-shorts-on-startup succeeded
INFO: disable-zoom-haptics succeeded
INFO: enable-debugging succeeded
INFO: external-downloads succeeded
INFO: hdr-auto-brightness succeeded
INFO: hide-ads succeeded
INFO: hide-album-cards succeeded
INFO: hide-artist-card succeeded
INFO: hide-autoplay-button succeeded
INFO: hide-breaking-news-shelf succeeded
INFO: hide-captions-button succeeded
INFO: hide-cast-button succeeded
INFO: hide-crowdfunding-box succeeded
INFO: hide-email-address succeeded
INFO: hide-endscreen-cards succeeded
INFO: hide-filter-bar succeeded
INFO: hide-floating-microphone-button succeeded
INFO: hide-info-cards succeeded
INFO: hide-load-more-button succeeded
INFO: hide-player-buttons succeeded
INFO: hide-player-overlay succeeded
INFO: hide-seekbar succeeded
INFO: hide-shorts-components succeeded
INFO: hide-timestamp succeeded
INFO: hide-video-action-buttons succeeded
INFO: hide-watch-in-vr succeeded
INFO: hide-watermark succeeded
INFO: minimized-playback succeeded
INFO: navigation-buttons succeeded
INFO: old-quality-layout succeeded
INFO: open-links-externally succeeded
INFO: premium-heading succeeded
INFO: remember-video-quality succeeded
INFO: return-youtube-dislike succeeded
INFO: seekbar-tapping succeeded
INFO: sponsorblock succeeded
INFO: spoof-app-version succeeded
INFO: swipe-controls succeeded
INFO: tablet-mini-player succeeded
INFO: theme succeeded
INFO: video-ads succeeded
INFO: video-speed succeeded
INFO: wide-searchbar succeeded
INFO: Compiling resources
INFO: Writing modified dex files
INFO: Aligning youtube.apk to revanced_aligned.apk
INFO: Copying revanced_aligned.apk to revanced.apk
INFO: Failed to clean up cache directory
INFO: Installing by mounting
05-28 07:44:43.440 12929 12929 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
05-28 07:44:43.443 12929 12929 I AndroidRuntime: Using default boot image
05-28 07:44:43.443 12929 12929 I AndroidRuntime: Leaving lock profiling enabled
05-28 07:44:43.539 12929 12929 D AndroidRuntime: Calling main entry com.android.commands.content.Content
05-28 07:44:43.545 12929 12929 D AndroidRuntime: Shutting down VM
05-28 07:44:43.967 12968 12968 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
05-28 07:44:43.970 12968 12968 I AndroidRuntime: Using default boot image
05-28 07:44:43.970 12968 12968 I AndroidRuntime: Leaving lock profiling enabled
05-28 07:44:44.073 12968 12968 D AndroidRuntime: Calling main entry com.android.commands.content.Content
05-28 07:44:44.083 12968 12968 D AndroidRuntime: Shutting down VM
05-28 07:44:45.051 13108 13108 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
05-28 07:44:45.054 13108 13108 I AndroidRuntime: Using default boot image
05-28 07:44:45.054 13108 13108 I AndroidRuntime: Leaving lock profiling enabled
05-28 07:44:45.129 13108 13108 D AndroidRuntime: Calling main entry com.android.commands.content.Content
05-28 07:44:45.136 13108 13108 D AndroidRuntime: Shutting down VM
05-28 07:44:46.163 13183 13183 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
05-28 07:44:46.167 13183 13183 I AndroidRuntime: Using default boot image
05-28 07:44:46.167 13183 13183 I AndroidRuntime: Leaving lock profiling enabled
05-28 07:44:46.259 13183 13183 D AndroidRuntime: Calling main entry com.android.commands.content.Content
05-28 07:44:46.269 13183 13183 D AndroidRuntime: Shutting down VM
05-28 07:44:47.247 13232 13232 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
05-28 07:44:47.250 13232 13232 I AndroidRuntime: Using default boot image
05-28 07:44:47.250 13232 13232 I AndroidRuntime: Leaving lock profiling enabled
05-28 07:44:47.351 13232 13232 D AndroidRuntime: Calling main entry com.android.commands.content.Content
05-28 07:44:47.357 13232 13232 D AndroidRuntime: Shutting down VM
05-28 07:44:48.351 13280 13280 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
05-28 07:44:48.354 13280 13280 I AndroidRuntime: Using default boot image
05-28 07:44:48.354 13280 13280 I AndroidRuntime: Leaving lock profiling enabled
05-28 07:44:48.450 13280 13280 D AndroidRuntime: Calling main entry com.android.commands.content.Content
05-28 07:44:48.460 13280 13280 D AndroidRuntime: Shutting down VM
05-28 07:44:49.488 13301 13301 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
05-28 07:44:49.490 13301 13301 I AndroidRuntime: Using default boot image
05-28 07:44:49.490 13301 13301 I AndroidRuntime: Leaving lock profiling enabled
05-28 07:44:49.586 13301 13301 D AndroidRuntime: Calling main entry com.android.commands.content.Content
05-28 07:44:49.594 13301 13301 D AndroidRuntime: Shutting down VM
05-28 07:44:50.590 13334 13334 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
05-28 07:44:50.593 13334 13334 I AndroidRuntime: Using default boot image
05-28 07:44:50.593 13334 13334 I AndroidRuntime: Leaving lock profiling enabled
05-28 07:44:50.673 13334 13334 D AndroidRuntime: Calling main entry com.android.commands.content.Content
05-28 07:44:50.680 13334 13334 D AndroidRuntime: Shutting down VM
05-28 07:44:51.692 13364 13364 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
05-28 07:44:51.700 13364 13364 I AndroidRuntime: Using default boot image
05-28 07:44:51.700 13364 13364 I AndroidRuntime: Leaving lock profiling enabled
05-28 07:44:51.794 13364 13364 D AndroidRuntime: Calling main entry com.android.commands.content.Content
05-28 07:44:51.803 13364 13364 D AndroidRuntime: Shutting down VM
05-28 07:44:52.808 13384 13384 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
05-28 07:44:52.815 13384 13384 I AndroidRuntime: Using default boot image
05-28 07:44:52.815 13384 13384 I AndroidRuntime: Leaving lock profiling enabled
05-28 07:44:52.920 13384 13384 D AndroidRuntime: Calling main entry com.android.commands.content.Content
05-28 07:44:52.930 13384 13384 D AndroidRuntime: Shutting down VM
05-28 07:44:53.909 13404 13404 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
05-28 07:44:53.912 13404 13404 I AndroidRuntime: Using default boot image
05-28 07:44:53.912 13404 13404 I AndroidRuntime: Leaving lock profiling enabled
05-28 07:44:54.016 13404 13404 D AndroidRuntime: Calling main entry com.android.commands.content.Content
05-28 07:44:54.027 13404 13404 D AndroidRuntime: Shutting down VM
05-28 07:44:55.008 13429 13429 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
05-28 07:44:55.011 13429 13429 I AndroidRuntime: Using default boot image
05-28 07:44:55.011 13429 13429 I AndroidRuntime: Leaving lock profiling enabled
05-28 07:44:55.113 13429 13429 D AndroidRuntime: Calling main entry com.android.commands.content.Content
05-28 07:44:55.123 13429 13429 D AndroidRuntime: Shutting down VM
05-28 07:44:56.125 13452 13452 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
05-28 07:44:56.129 13452 13452 I AndroidRuntime: Using default boot image
05-28 07:44:56.129 13452 13452 I AndroidRuntime: Leaving lock profiling enabled
05-28 07:44:56.228 13452 13452 D AndroidRuntime: Calling main entry com.android.commands.content.Content
05-28 07:44:57.246 13480 13480 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
05-28 07:44:57.254 13480 13480 I AndroidRuntime: Using default boot image
05-28 07:44:57.254 13480 13480 I AndroidRuntime: Leaving lock profiling enabled
05-28 07:44:57.356 13480 13480 D AndroidRuntime: Calling main entry com.android.commands.content.Content
05-28 07:44:57.367 13480 13480 D AndroidRuntime: Shutting down VM
05-28 07:44:58.349 13500 13500 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
05-28 07:44:58.351 13500 13500 I AndroidRuntime: Using default boot image
05-28 07:44:58.351 13500 13500 I AndroidRuntime: Leaving lock profiling enabled
05-28 07:44:58.450 13500 13500 D AndroidRuntime: Calling main entry com.android.commands.content.Content
05-28 07:44:58.458 13500 13500 D AndroidRuntime: Shutting down VM
05-28 07:44:59.467 13520 13520 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
05-28 07:44:59.475 13520 13520 I AndroidRuntime: Using default boot image
05-28 07:44:59.475 13520 13520 I AndroidRuntime: Leaving lock profiling enabled
05-28 07:44:59.577 13520 13520 D AndroidRuntime: Calling main entry com.android.commands.content.Content
05-28 07:44:59.586 13520 13520 D AndroidRuntime: Shutting down VM
05-28 07:45:00.577 13547 13547 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
05-28 07:45:00.580 13547 13547 I AndroidRuntime: Using default boot image
05-28 07:45:00.580 13547 13547 I AndroidRuntime: Leaving lock profiling enabled
05-28 07:45:00.677 13547 13547 D AndroidRuntime: Calling main entry com.android.commands.content.Content
05-28 07:45:00.687 13547 13547 D AndroidRuntime: Shutting down VM
05-28 07:45:01.664 13577 13577 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
05-28 07:45:01.672 13577 13577 I AndroidRuntime: Using default boot image
05-28 07:45:01.672 13577 13577 I AndroidRuntime: Leaving lock profiling enabled
05-28 07:45:01.760 13577 13577 D AndroidRuntime: Calling main entry com.android.commands.content.Content
05-28 07:45:01.772 13577 13577 D AndroidRuntime: Shutting down VM
05-28 07:45:02.738 13620 13620 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
05-28 07:45:02.742 13620 13620 I AndroidRuntime: Using default boot image
05-28 07:45:02.742 13620 13620 I AndroidRuntime: Leaving lock profiling enabled
05-28 07:45:02.825 13620 13620 D AndroidRuntime: Calling main entry com.android.commands.content.Content
05-28 07:45:02.834 13620 13620 D AndroidRuntime: Shutting down VM
05-28 07:45:03.847 13761 13761 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
05-28 07:45:03.850 13761 13761 I AndroidRuntime: Using default boot image
05-28 07:45:03.850 13761 13761 I AndroidRuntime: Leaving lock profiling enabled
05-28 07:45:03.937 13761 13761 D AndroidRuntime: Calling main entry com.android.commands.content.Content
05-28 07:45:03.947 13761 13761 D AndroidRuntime: Shutting down VM
05-28 07:45:04.988 13815 13815 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
05-28 07:45:05.000 13815 13815 I AndroidRuntime: Using default boot image
05-28 07:45:05.000 13815 13815 I AndroidRuntime: Leaving lock profiling enabled
05-28 07:45:05.095 13815 13815 D AndroidRuntime: Calling main entry com.android.commands.content.Content
05-28 07:45:05.105 13815 13815 D AndroidRuntime: Shutting down VM
05-28 07:45:06.100 13836 13836 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
05-28 07:45:06.109 13836 13836 I AndroidRuntime: Using default boot image
05-28 07:45:06.109 13836 13836 I AndroidRuntime: Leaving lock profiling enabled
05-28 07:45:06.198 13836 13836 D AndroidRuntime: Calling main entry com.android.commands.content.Content
05-28 07:45:06.207 13836 13836 D AndroidRuntime: Shutting down VM
05-28 07:45:07.208 13858 13858 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
05-28 07:45:07.212 13858 13858 I AndroidRuntime: Using default boot image
05-28 07:45:07.212 13858 13858 I AndroidRuntime: Leaving lock profiling enabled
05-28 07:45:07.302 13858 13858 D AndroidRuntime: Calling main entry com.android.commands.content.Content
05-28 07:45:07.311 13858 13858 D AndroidRuntime: Shutting down VM
05-28 07:45:08.336 13912 13912 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
05-28 07:45:08.339 13912 13912 I AndroidRuntime: Using default boot image
05-28 07:45:08.339 13912 13912 I AndroidRuntime: Leaving lock profiling enabled
05-28 07:45:08.426 13912 13912 D AndroidRuntime: Calling main entry com.android.commands.content.Content
05-28 07:45:08.432 13912 13912 D AndroidRuntime: Shutting down VM
05-28 07:45:09.463 13934 13934 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
05-28 07:45:09.467 13934 13934 I AndroidRuntime: Using default boot image
05-28 07:45:09.467 13934 13934 I AndroidRuntime: Leaving lock profiling enabled
05-28 07:45:09.572 13934 13934 D AndroidRuntime: Calling main entry com.android.commands.content.Content
05-28 07:45:09.585 13934 13934 D AndroidRuntime: Shutting down VM
05-28 07:45:10.565 13954 13954 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
05-28 07:45:10.569 13954 13954 I AndroidRuntime: Using default boot image
05-28 07:45:10.569 13954 13954 I AndroidRuntime: Leaving lock profiling enabled
05-28 07:45:10.675 13954 13954 D AndroidRuntime: Calling main entry com.android.commands.content.Content
05-28 07:45:10.685 13954 13954 D AndroidRuntime: Shutting down VM
05-28 07:45:11.684 13976 13976 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
05-28 07:45:11.688 13976 13976 I AndroidRuntime: Using default boot image
05-28 07:45:11.688 13976 13976 I AndroidRuntime: Leaving lock profiling enabled
05-28 07:45:11.789 13976 13976 D AndroidRuntime: Calling main entry com.android.commands.content.Content
05-28 07:45:11.802 13976 13976 D AndroidRuntime: Shutting down VM
05-28 07:45:12.789 13996 13996 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
05-28 07:45:12.791 13996 13996 I AndroidRuntime: Using default boot image
05-28 07:45:12.791 13996 13996 I AndroidRuntime: Leaving lock profiling enabled
05-28 07:45:12.888 13996 13996 D AndroidRuntime: Calling main entry com.android.commands.content.Content
05-28 07:45:12.899 13996 13996 D AndroidRuntime: Shutting down VM
05-28 07:45:13.910 14017 14017 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
05-28 07:45:13.913 14017 14017 I AndroidRuntime: Using default boot image
05-28 07:45:13.913 14017 14017 I AndroidRuntime: Leaving lock profiling enabled

E:\ANDROID\TestRevanced>`

i don't know why its spammed by `AndroidRuntime` error. I need to `CTRL+C` to stopped it. But yeah, your patches works flawlessly. And i can play yt videos on google discover.
Here for the proof:


https://github.com/revanced/revanced-patches/assets/99109969/8e685c4a-8035-4479-9acd-1fd295934c36

**Comment by teddyramu** [comment]
> [here it is](https://ufile.io/kefamsj0)
> 
> And use the [dev integrations](https://github.com/revanced/revanced-integrations/releases/download/v0.109.0-dev.3/revanced-integrations-0.109.0-dev.3.apk)

Btw your fix worked on Google feed ps but in 

> [here it is](https://ufile.io/kefamsj0)
> 
> And use the [dev integrations](https://github.com/revanced/revanced-integrations/releases/download/v0.109.0-dev.3/revanced-integrations-0.109.0-dev.3.apk)

This patch is working on Google feed, Playstore embedded videos.
But it's still crashing in relay reddit app and syncforreddit apps and it throws this error
![Screenshot_20230528-095547629](https://github.com/revanced/revanced-patches/assets/85507534/ec95c42e-624d-4d95-8020-e1062916d72b)

**Comment by cyberboh** [comment]
> > i don't know why its spammed by AndroidRuntime error.
> 
> It spams if YouTube is still running in the background on the device. Close YouTube and it'll finish on the first attempt.

Got it.
If you don't mind, please push your patches to revanced patches, so i can include it in yt magisk module. :))

**Comment by teddyramu** [comment]
> @teddyramu nevermind I found the crash logs myself
> 
> @cyberboh Will merge the fix soon

Thank you, built magisk module with your patches it's working without crashes even in reddit apps.

**Comment by teddyramu** [comment]
> > > i don't know why its spammed by AndroidRuntime error.
> > 
> > 
> > It spams if YouTube is still running in the background on the device. Close YouTube and it'll finish on the first attempt.
> 
> Got it. If you don't mind, please push your patches to revanced patches, so i can include it in yt magisk module. :))

You can include now also by adding custom repo and running workflow like below.
[Check this Config and repo](https://github.com/teddyramu/revanced-magisk-module-mar/blob/48c8efe23c22437fc61452b26703e09413b1c058/config.toml#L19)
