### ISSUE TITLE
feat: option to place youtube's search button in the bottom navigation bar

### ISSUE THREAD

**Issue by AdityaAnand99** [revanced/revanced-patches#2284]
### Application

YouTube revanced

### Issue

With screens getting bigger, it getting difficult to access the UI elements at the top of the screen with one hand, YouTube's search button being one of them. It is very annoying having to reach out to the top of the screen with your thumb each time you want to search something in YouTube, which for me personally is at least a dozen times a day. 
![Screenshots_2023-05-27-14-19-48](https://github.com/revanced/revanced-patches/assets/49330608/98fc9bd5-a46b-461f-90ed-0d8af8a42078)

### Patch

Option to place the search button in the bottom navigation bar, alongside the 'home', 'subscriptions', and 'library' buttons, instead of at the top, just like the ones in 'spotify' or 'Instagram'.
![Screenshot_20230527-140205~2](https://github.com/revanced/revanced-patches/assets/49330608/ea36af74-7d0e-42e8-b475-7ff154007c66)
![Screenshot_20230527-140228~2](https://github.com/revanced/revanced-patches/assets/49330608/2b7727fc-d9ec-413e-947f-e7e6736aa596)

### Motivation

To make it easier to search in YouTube when using the phone with one hand. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
#1341
