### ISSUE TITLE
feat: download media

### ISSUE THREAD

**Issue by Subbarao6338** [revanced/revanced-patches#2285]
### Application

Instagram 

### Issue

Download media

### Patch

Download media from posts, status, reels, igtv, profile pictures.
Custom download location.
Download button beside save button for faster download.

### Motivation

Download media from posts, status, reels, igtv, profile pictures.

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
#1652
