### ISSUE TITLE
feat: Switch to ytdlnis for downloading videos 

### ISSUE THREAD

**Issue by SameenAhnaf** [revanced/revanced-patches#2289]
### Application

YouTube 

### Issue

Use a better downloader app for videos.

### Patch

[ytdlnis](https://github.com/deniscerri/ytdlnis) is an Android app dedicated for downloading YouTube videos. For the purpose of downloading videos, it's something that will likely to bring a lot more advanced features like omitting Sponsorblock segments, seperate videos by chapters, schedule downloads and so on.

It's kinda weird to let users use a competitor app to fulfill the purpose of your own app. Also, Newpipe app is likely to be built in a different repo. See: https://github.com/TeamNewPipe/NewPipe/discussions/10118

### Motivation

Let users have a more reliable and immersive experience while downloading videos.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by reisxd** [comment]
You can already change the downloader package name yourself.
