### ISSUE TITLE
feat: organize applications into individual tables in docs

### ISSUE THREAD

**Issue by afnzmn** [revanced/revanced-patches#229]
## 🐞 Issue

The current README will get messy as more patches get added over time.

## ❗ Solution

Organize the README by giving each apps their own table.

## ❓ Motivation

h

## ⚠ Additional context

# ReVanced Patches

🧩 Official patches by ReVanced

# List of available patches

### 📺 YouTube `com.google.android.youtube` 
<details open>

| 💊 Patch | 📜 Description | 🏹 Target Version |
|:--------:|:--------------:|:-----------------:|
| `swipe-controls` | Adds volume and brightness swipe controls. | 17.28.34 |
| `seekbar-tapping` | Enables tap-to-seek on the seekbar of the video player. | 17.28.34 |
| `minimized-playback` | Enables minimized and background playback. | 17.28.34 |
| `amoled` | Enables pure black theme. | 17.28.34 |
| `disable-create-button` | Hides the create button in the navigation bar. | 17.28.34 |
| `hide-cast-button` | Hides the cast button in the video player. | all |
| `return-youtube-dislike` | Shows the dislike count of videos using the Return YouTube Dislike API. | 17.28.34 |
| `hide-autoplay-button` | Hides the autoplay button in the video player. | 17.28.34 |
| `premium-heading` | Shows premium branding on the home screen. | all |
| `custom-branding` | Changes the YouTube launcher icon to be ReVanced's. | all |
| `disable-fullscreen-panels` | Disables video description and comments panel in fullscreen view. | 17.28.34 |
| `old-quality-layout` | Enables the original quality flyout menu. | 17.28.34 |
| `hide-shorts-button` | Hides the shorts button on the navigation bar. | 17.28.34 |
| `hide-watermark` | Hides creator's watermarks on videos. | 17.28.34 |
| `sponsorblock` | Integrate SponsorBlock. | 17.28.34 |
| `enable-wide-searchbar` | Replaces the search icon with a wide search bar. This will hide the YouTube logo when active. | 17.28.34 |
| `force-vp9-codec` | Forces the VP9 codec for videos. | 17.28.34 |
| `always-autorepeat` | Always repeats the playing video again. | 17.28.34 |
| `microg-support` | Allows YouTube ReVanced to run without root and under a different package name with Vanced MicroG | 17.28.34 |
| `enable-debugging` | Enables app debugging by patching the manifest file. | all |
| `custom-playback-speed` | Adds more video playback speed options. | 17.28.34 |
| `hdr-auto-brightness` | Makes the brightness of HDR videos follow the system default.| 17.28.34 |
| `video-ads` | Removes ads in the video player. | 17.28.34 |
| `general-ads` | Removes general ads. | 17.28.34 |
| `hide-infocard-suggestions` | Hides infocards in videos. | 17.28.34 |
</details>

### 🎧 YouTube Music `com.google.android.apps.youtube.music` 
<details open>

| 💊 Patch | 📜 Description | 🏹 Target Version |
|:--------:|:--------------:|:-----------------:|
| `minimized-playback-music` | Enables minimized playback on Kids music. | 5.14.53 |
| `tasteBuilder-remover` | Removes the "Tell us which artists you like" card from the home screen. | 5.14.53 |
| `hide-get-premium` | Removes all "Get Premium" evidences from the avatar menu. | 5.14.53 |
| `compact-header` | Hides the music category bar at the top of the homepage. | 5.14.53 |
| `upgrade-button-remover` | Removes the upgrade tab from the pivot bar. | 5.14.53 |
| `background-play` | Enables playing music in the background. | 5.14.53 |
| `music-video-ads` | Removes ads in the music player. | 5.14.53 |
| `codecs-unlock` | Adds more audio codec options. The new audio codecs usually result in better audio quality. | 5.14.53 |
| `exclusive-audio-playback` | Enables the option to play music without video. | 5.14.53 |
</details>

### 🐦 Twitter `com.twitter.android` 
<details open>

| 💊 Patch | 📜 Description | 🏹 Target Version |
|:--------:|:--------------:|:-----------------:|
| `timeline-ads` | Removes ads from the Twitter timeline. | all |
</details>

**Comment by oSumAtrIX** [comment]
Because ReVanced is app agnostic, giving packages their own package specific icon is not possible.

**Comment by Sculas** [comment]
^ and application name/title. We only know the package name.

**Comment by bogadana** [comment]
Very nice

**Comment by bogadana** [comment]
done https://github.com/revanced/revanced-patches/pull/230
