### ISSUE TITLE
bug(youtube): Shorts component are not hidden

### ISSUE THREAD

**Issue by foo-mr** [revanced/revanced-patches#2292]
### Type

Other

### Bug description

Shorts components are not hidden even it's enabled. 

### Steps to reproduce

Enable Hide Shorts in Shorts Components and restart.
Shorts are still available in the Main Page in app. 

### Relevant log output

```shell
None
```

### Screenshots or videos

![image](https://github.com/revanced/revanced-patches/assets/86838308/ea264fb6-61d6-4da7-ba26-d066cb8eb8fb)
![image](https://github.com/revanced/revanced-patches/assets/86838308/66996904-e97c-4805-9d4b-313dd948048a)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
![IMG_20230528_034708](https://github.com/revanced/revanced-patches/assets/13122796/657ee357-bc96-4501-991f-fabc861d64c6)

Report back with the filter that works

**Comment by foo-mr** [comment]
shorts_video_cell.eml

**Comment by oSumAtrIX** [comment]
Looks good, can you send the entire path builder string?

**Comment by foo-mr** [comment]
> 

I'm not sure how to find that. 
Here's the thing I get from logcat

`revanced: AdsFilter: Unfiltered (ID: null): shorts_video_cell.eml|164f16da346276a7|CellType|ContainerType|shorts_video_item.eml|78260e522d41d8b|ContainerType|ContainerType|ImageType|`
