### ISSUE TITLE
feat: A download fuction for Youtube Stories & Community Posts

### ISSUE THREAD

**Issue by Snaider1** [revanced/revanced-patches#2293]
### Application

Youtube Revanced

### Issue

Not an issue, but a request to make Youtube Revanced even more powerful.

### Patch

1) For Stories:
Some kind of way to download the stories, because one can't access them through the liked videos playlist, even if one did press the like button, for they are temporal videos which get deleted at the moment they reach 7 days of being uploaded.

The current "easiest way" I know to download stories is using the prompt commands of yt-dlp.

2) For Community Posts:
A button or long-press function to download images, gifs, and images from polls.

The current, and only way to "save" posts without using browsers, is to take screenshots of them, which don't work for gifs or vote polls, because polls images are tiny and polls don't support the zoom gesture.

### Motivation

- I think it would be great to see first-ever features like these ones.
- I have seen that many would like these two features, because I tried to find user-friendly ways to do both on mobile, but it was impossible.
- These two would be (as said above) user-friendly features so one doesn't have to exit the app and go for the desktop version of youtube in a browser, in case of posts, and use yt-dlp in case of stories, everything would be done from the app.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
[#download stories](https://github.com/revanced/revanced-patches/issues/1909)
