### ISSUE TITLE
feat(patch): Oto Music Player

### ISSUE THREAD

**Issue by Luwis13** [revanced/revanced-patches#2294]
### Application

Oto music player. It's an android app which can be downloaded from the playstore and is very helpful. I don't know the package name but this is the link: https://play.google.com/store/apps/details?id=com.piyush.music

### Issue

The issues are: the premium features including 1) separate artists (by using ',' and ';'), Themes, and many more which are only available for pro users

### Patch

The patch should fix the premium features and make it available for free to the non paid users as it's open source.

### Motivation

I don't actually know what to put in the "motivation" section but yeah it's a very good app and is the best offline music player that's near perfect even in its free form and its gonna boost the perfection of best offline music player if the patches are applied to it. It would be helpful for users to gain what they can't as the feature which separates the artists is a very good feature and is missing in most of the music players. I hope it gets patched.
Thank You.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by YashjitPal** [comment]
I also want this feature fr. Well idk the music player Hut the features listed are great...

**Comment by oSumAtrIX** [comment]
Alternative apps with the same features exist for free.
