### ISSUE TITLE
feat: Clean description tab under videos

### ISSUE THREAD

**Issue by Jakenevada** [revanced/revanced-patches#2297]
### Application

Youtube:Revanced

### Issue

Alot of useless clutter
![343730494_612655814147273_7001738249940445626_n](https://github.com/revanced/revanced-patches/assets/132659424/48bb9c51-7972-41d3-b621-222dd8803fd4)

### Patch

I would like to ask for adding options for removing components of description tab such as transcription ang game tab

### Motivation

Cleaner UI

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
They don't obstruct the description

**Comment by Jakenevada** [comment]
By this i meant for description tab to like in older versions just having a writen description
