### ISSUE TITLE
feat: Option for removal of your films in libary tab

### ISSUE THREAD

**Issue by Jakenevada** [revanced/revanced-patches#2298]
### Application

Youtube:Revanced

### Issue

Cleaner UI (Who buys videos on youtube ?)
![343722202_815147729945063_7152858284900551310_n](https://github.com/revanced/revanced-patches/assets/132659424/56b51f31-fdc1-428f-884c-d119cce3c7ca)

### Patch

I have wanted to ask for option to remove this two buttons resulting in more clean libary tab

### Motivation

Cleaner UI

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
These don't obstruct anything and needn't be removed.

**Comment by Jakenevada** [comment]
I wanted to suggest an option to hide them or maybe relocate them under the playlist tab
