### ISSUE TITLE
bug(YouTube - Hide captions button): Caption button is not hidden

### ISSUE THREAD

**Issue by LisoUseInAIKyrios** [ReVanced/revanced-patches#23]
### Bug description

The closed caption button can now show up as a litho component (litho id: `captions_button.eml-js-canary`):

![original](https://github.com/ReVanced/revanced-patches/assets/118716522/01daf424-9709-4d4d-b6b5-8a66c23e9adf)

But if this is hidden using a litho filter patch, the ReVanced overlay buttons do not layout correctly:

![filtered](https://github.com/ReVanced/revanced-patches/assets/118716522/7457c29c-82c7-4ac5-8643-4ccfc2bc9a5b)

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by ILoveOpenSourceApplications** [comment]
@LisoUseInAIKyrios, is this issue relevant now?

**Comment by oSumAtrIX** [comment]
The issue is stale, closing until anyone mentions it
