### ISSUE TITLE
Force specific format

### ISSUE THREAD

**Issue by isolation365** [ReVanced/revanced-patches#2307]
### Type

Functionality

### Issue

Unable to play videos due to vp9 codec is being used even when not forced.

### Feature

Is it possible to add a section where user can force specific format like only use **[AVC+M4A]** to play videos.

### Motivation

.

**Comment by KatayR** [comment]
> I think VP9 was removed recently from YouTube Android.
> 
> For the request if more control over video format, closing this issue in favor of [#909](https://github.com/ReVanced/revanced-patches/issues/909)

Nope
![Image](https://github.com/user-attachments/assets/27700877-767b-4a6e-917f-1fde9b3be1d0)
