### ISSUE TITLE
feat: Twitter Monet Theme

### ISSUE THREAD

**Issue by alok1nanda** [ReVanced/revanced-patches#231]
### Feature description

Monet Theme Patch for Twitter.I know we already have one but Not just for Twitter Blue but for the whole app.

### Motivation

Would be in sync with other Dynamic Themed Apps.

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by IndusAryan** [comment]
@alok1nanda 
https://github.com/crimera/piko/pull/211
https://github.com/crimera/piko/pull/109

https://t.me/pikopatches
