### ISSUE TITLE
bug(youtube): video stops playing after 3-5 minutes of background playback when device screen is locked

### ISSUE THREAD

**Issue by HexBleh** [ReVanced/revanced-patches#2313]
### Type

Error at runtime

### Bug description

Whenever a video is played in the background with the phone locked , after 3-5 minutes the video will stop and begin buffering indefinitely. Once the phone is unlocked , the problem subsides.

### Steps to reproduce

1. Open YT Revanced 
2. Play a ~10 video 
3. Lock phone
4. After 3-5 minutes , the video will begin buffering indefinitely until the phone is unlocked once again

### Relevant log output

```shell
Can forward any relevant files to whoever needs them , message me on Telegram @HexBleh or on Discord HexBleh#5175
```

### Screenshots or videos

Github isnt accepting my video recording of the installation process , so if youd like that or any additional files that may be helpful feel free to message me on Telegram @HexBleh or on Discord @ HexBleh#5175

### Additional context

I am using a Samsung Galaxy Zflip 4 on Android 13 

I have already updated my Revanced Manager , MicroG , and chose the reccomended version number of the Youtube apk that was suggested within the manager. 

Ive followed all standard installation procedures and even deleted EVERYTHING starting all the way over from square one with absolutely no luck. 

Ive also followed the DontKillMyApp guide to ensure the issue wasnt related to any battery or optimization settings 

3 other Yt Revanced users also claimed they have been experiencing this issue lately from within the discord group.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
> It sounds like a side effect of signature spoofing.
> 
> You can try turning off signature spoofing (under Settings -> ReVanced -> Misc), but it probably will fail because it's needed for most users.
> 
> Can also try turning off video pip (under Settings -> General) and see if that changes anything.

I believe its rather an issue with the patch not spoofing when playing in background. Iirc we added some filters when spoofing should happen, probably this is what prevents spoofing to be applied when in background play

**Comment by Qanaden** [comment]
> > I believe its rather an issue with the patch not spoofing when playing in background. Iirc we added some filters when spoofing should happen, probably this is what prevents spoofing to be applied when in background play
> 
> Previously the spoof was selectively turned on based on the PlayerType setting. So if the PlayerType was `NONE` it would not spoof.
> 
> But with the current patch, all videos (except Shorts) are spoofed.  The only check is if if the video is a home feed autoplay (which uses a slightly different spoofed value to fix the subtitles).  
> 
> @HexBleh I cannot reproduce the problem when playing with the screen locked.  I tried both locking the screen while inside YouTube, and exiting to PIP mode then locking the screen.  Both times it continuing to play ok well past 5 minutes.  Try switching to background play (going to PIP mode) before locking the screen, and try leaving the PIP visible and try hiding it (tap the headphone icon in the PIP).  Also try reproducing using stock YouTube and see if the same problem occurs.  

I've had this same issue for awhile I was referenced here by someone in the revanced extended subreddit I tried the PIP method to see if that would fix the issue I started a video went into PIP tapped the headphone icon to hide it and turned the screen off it played for 7 minutes before I turned it on again. Normally it would only play for about 3 minutes or less this is with the app open not in PIP mode.

**Comment by Qanaden** [comment]
> > > I believe its rather an issue with the patch not spoofing when playing in background. Iirc we added some filters when spoofing should happen, probably this is what prevents spoofing to be applied when in background play
> > 
> > Previously the spoof was selectively turned on based on the PlayerType setting. So if the PlayerType was `NONE` it would not spoof.
> > 
> > But with the current patch, all videos (except Shorts) are spoofed.  The only check is if if the video is a home feed autoplay (which uses a slightly different spoofed value to fix the subtitles).  
> > 
> > @HexBleh I cannot reproduce the problem when playing with the screen locked.  I tried both locking the screen while inside YouTube, and exiting to PIP mode then locking the screen.  Both times it continuing to play ok well past 5 minutes.  Try switching to background play (going to PIP mode) before locking the screen, and try leaving the PIP visible and try hiding it (tap the headphone icon in the PIP).  Also try reproducing using stock YouTube and see if the same problem occurs.  
> 
> I've had this same issue for awhile I was referenced here by someone in the revanced extended subreddit I tried the PIP method to see if that would fix the issue I started a video went into PIP tapped the headphone icon to hide it and turned the screen off it played for 7 minutes before I turned it on again. Normally it would only play for about 3 minutes or less this is with the app open not in PIP mode.

After testing a bit more I've found the issue persists even when in PIP the video will run longer than if it were open in the app and you turn the screen off without going into PIP so that's something at least. I'm using a Galaxy S23 Ultra running android 13.

**Comment by Qanaden** [comment]
> I don't think this is a ReVanced issue, and it strongly sounds like the device is 'optimizing' the battery.
> 
> If anyone has the issue, they can try stock YouTube and see if the problem persists (it probably will show the same behavior).
> 
> dontkillmyapp.com lists Samsung as the worst for aggressive battery optimizations, and says Samsung devices can now kill foreground apps as well (which would explain this bug report).
> 
> Can apply the instructions on dontkillmyapp.com to both ReVanced and MicroG, and it should help but may not completely fix the 

It may not be a revanced specific issue but I've had it happen on revanced as well as revanced extended. I've already followed every step on dontkillmyapp I've turned off every single battery optimization and data saver setting there is so idk what to say about that part.

**Comment by Qanaden** [comment]
> > It may not be a revanced specific issue but I've had it happen on revanced as well as revanced extended. I've already followed every step on dontkillmyapp I've turned off every single battery optimization and data saver setting there is so idk what to say about that part.
> 
> But does it happen with stock YouTube?
> 
> Dontkillmyapp says Samsung devices can now kill foreground apps, and there doesn't appear to be any 100% fix for Samsung devices.
> 

I don't have premium so I don't think I'm able to test the issue with stock YouTube unfortunately. now if there's somehow a way to do this I'll test it but I doubt it. Honestly it doesn't surprise me considering how anti consumer Samsung is

**Comment by oSumAtrIX** [comment]
@LisoUseInAIKyrios It may very well be the spoof client patch. YouTube may be playing the video differently when it is in background and thus the hook does not replace the protobuf field

**Comment by oSumAtrIX** [comment]
Closing, once requested info is present please reopen.
