### ISSUE TITLE
feat: [YT Music] change miniplayer shuffle button to dislike button

### ISSUE THREAD

**Issue by AEYCEN** [ReVanced/revanced-patches#233]
### Feature description

**Target Application**
YouTube Music i.e. `com.google.android.apps.youtube.music`

**Issue**
No ability to easily influence the algorithm from the mini player. Currently, the dislike button has been replaced by a shuffle button.

**Patch**

- Modifying the music player displayed in the notification menu and on the lock screen. 
- [ ] Replacing the shuffle button with a dislike button in the same location.
- [ ] It should be implemented as an option in the settings menu, where you can decide with a simple slider if you want to have the shuffle button or the dislike button.

---

> Current ReVanced Miniplayer (with shuffle button):

![YT Music](https://github.com/ReVanced/revanced-patches/assets/114836625/3b5c474b-1075-4fd9-8359-ef401981f46b)

> Old Vanced Miniplayer (with dislike button):

![YT Music Vanced](https://github.com/ReVanced/revanced-patches/assets/114836625/cf96be42-874a-4a15-9f9c-72bb1fd8dbfa)

### Motivation

This change would allow users like me, who rely on the algorithm to find new good music, to provide direct feedback through the mini player when we dislike a song or similar content, which is currently not possible. The goal is to bring back a feature from the original Vanced design. 

**Summary**
1. Restoring the like and dislike buttons in the mini player enhances the user experience by providing more control over the content they are listening to.
2. The dislike button allows users to provide valuable feedback to the algorithm, improving content recommendations.
3. Bringing back familiar features from the old design maintains consistency for long-time users ("Continuing the
legacy of Vanced")
4. Having essential playback controls readily available in the mini player makes it more convenient to manage music without navigating to the main app.

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, if anyone comes across this feature request, they are free to PR it. Thanks for the feature request!
