### ISSUE TITLE
clien spoof settings auto enabled 

### ISSUE THREAD

**Issue by adarshsingh87** [revanced/revanced-patches#2333]
### Type

Error at runtime

### Bug description

I am having play back issues on YT with client spood enabled, so i turn that off in the settings only for it to be auto enabled in few mins which is STUPID. 

I then proceeded to build a new app without the client spoof patch only for nothing to change.

I understand that playback issues with client spoof enable might be a me issue but the app shouldn't auto enable when i specifically disabled it.

yt apk v18.19.35

### Steps to reproduce

Step 1: Patch a YT apk with client spoof patch applied
Step2: disable client spoof setting from the revanced settings page
Step 3: start playing a video

### Relevant log output

```shell
NA
```

### Solution

Remove the auto enabling of client spoof setting. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by adarshsingh87** [comment]
![Screenshot_20230531_204149.jpg](https://github.com/revanced/revanced-patches/assets/56337250/7475ae3c-4992-4ce5-a5d4-bf9e5419ee4a)

Playback issue starts after this toast appears.

**Comment by adarshsingh87** [comment]
Fyi, Issue also persists even if the client spoof and spood app version patches arent applied

**Comment by adarshsingh87** [comment]
https://drive.google.com/file/d/1J7YyJNNppi9Aoadqoz5Yb3JtUlEJ_C7i/view?usp=sharing

**Comment by adarshsingh87** [comment]
I think the patch results in playback issues can be a me thing, the real issue is the patch getting auto enabled.

**Comment by adarshsingh87** [comment]
But for the amount of time it's inactive everything is buffering fine, once the message comes up the issues start. Maybe there's in the implementation of the patch then.

**Comment by oSumAtrIX** [comment]
> [drive.google.com/file/d/1J7YyJNNppi9Aoadqoz5Yb3JtUlEJ_C7i/view?usp=sharing](https://drive.google.com/file/d/1J7YyJNNppi9Aoadqoz5Yb3JtUlEJ_C7i/view?usp=sharing)

Please record the steps exactly:

1. Open app
2. Enable spoof in settings
3. Play a video
4. Show issue

**Comment by johnconner122** [comment]
> But for the amount of time it's inactive everything is buffering fine, once the message comes up the issues start. Maybe there's in the implementation of the patch then.

You have to close the video player, and play the video again for it to take effect.
