### ISSUE TITLE
bug(TikTok): Show seekbar patch doesn't work

### ISSUE THREAD

**Issue by TheJeterLP** [ReVanced/revanced-patches#2338]
### Type

Error at runtime

### Bug description

Version 29.7.4
Seekbar patch does apply without errors, but seekbar is not shown on videos.

### Steps to reproduce

Download TikTok APK 29.7.4 patch with revanced manager, install, test

### Relevant log output

```shell
No log output
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by kazimmt** [comment]
It shows seekbar when video is paused.
Needs to improve the patch.

**Comment by kazimmt** [comment]
@d4rkk3y can you please fix this patch also?

**Comment by kazimmt** [comment]
@d4rkk3y the issue is back with TikTok 30.6.xx again

& 
i got a report that show seekbar works only on **For you** tab, it doesn't works on **Following** (Unable to test it bcz I don't have a TikTok account)

**Comment by oSumAtrIX** [comment]
Open an issue.
