### ISSUE TITLE
feat: iFunny Ad, Tracker, & Cryptominer Removal

### ISSUE THREAD

**Issue by xdevilkillx** [revanced/revanced-patches#2339]
### Application

iFunny

### Issue

Annoying and invasive ADs, Trackers, and Cryptominers that can cause phone to overheat, slow down, crash, steal data, etc.

### Patch

Removal of built-in and online ADs, Trackers, and Cryptominers.

### Motivation

All of the iFunny community would appreciate it greatly. (The Android community anyways) and you may receive more support/donations.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
iFunny does not have crypto miners and ifunny trackers aren't harmful.

**Comment by xdevilkillx** [comment]
And what of the ads?

**Comment by oSumAtrIX** [comment]
Create a new issue.
