### ISSUE TITLE
bug: Twitch "AdBlocking proxy services fail"

### ISSUE THREAD

**Issue by BeeingSerious** [revanced/revanced-patches#2341]
### Type

Other

### Bug description

Founded on Twitch Revanced app v.14.6.1 (Recommended) patched with v.2.174, by playing any stream, services used for adblocking (TTV.LOL and PurpleAdBlocker) are failing, ads are showing up.

### Steps to reproduce

Open the patched app, select a stream and found a popup notification saying "TTV.LOL proxy server is unavaliable. Ads may show".

### Relevant log output

```shell
"TTV.LOL proxy server is unavaliable. Ads may show"
```

### Solution

May be change the used proxies.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
TTV.LOL proxy server is temporarily unavaliable
