### ISSUE TITLE
bug: The youtube app go to pip mood when pressing the download button

### ISSUE THREAD

**Issue by V7Q6** [revanced/revanced-patches#2351]
### Type

Other

### Bug description

When I try to use the quick download button with seal the app go to pip mood 

I told seal support about it and they said they can nor do anything about it

https://github.com/revanced/revanced-patches/assets/120672796/017e68fc-a095-4dbd-8078-074d82e9fba2

### Steps to reproduce

1- Choos seal as a downloader 
2- when downloading choos the quick download button 

### Relevant log output

```shell
.
```

### Screenshots or videos

https://github.com/revanced/revanced-patches/assets/120672796/ad4a75c7-10b2-4f60-bbe9-89fe7553b562

### Additional context

Seal support also said It's not only in seal

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Click on share then select Seal. Check if this happens then too

**Comment by V7Q6** [comment]
I did both 

https://github.com/revanced/revanced-patches/assets/120672796/a8449607-b764-4b9c-b1e7-b2932ee6c3c5

It still start the pip mood

**Comment by oSumAtrIX** [comment]
Check if this issue occurs on the unpatched app. Make sure to have PiP enabled, as well as using the share menu.

**Comment by V7Q6** [comment]
I cleared the cash and tried other sharing methods and it's still the same


I also tried the original YouTube app and the same thing happen 

https://github.com/revanced/revanced-patches/assets/120672796/ede61e40-8468-48a7-a396-3252f285b0e0

**Comment by oSumAtrIX** [comment]
Then this is not an issue with ReVanced
