### ISSUE TITLE
feat: `save to playlist`button unlock

### ISSUE THREAD

**Issue by ghost** [ReVanced/revanced-patches#2352]
## 🐞 Issue

On videos marked "for kids" (which can be common videos too, but marked by the creator as such, just to turn off comments), save to playlist button is (uselessly) disabled, to make it compliant with the COPPA law.

## ❗ Solution

Find the litho object related to this button and unlock it.

## ❓ Motivation

Because I never seen as such stupid (and annoying) limitation.

## ⚠ Additional context

Despite this limitation, these videos can still be added to a playlist with 3-dots menu outside the player.

**Comment by 19MisterX98** [comment]
So, uh, is there a patch for this cause I can't find it and the issue got closed?
