### ISSUE TITLE
feat: ReChrome

### ISSUE THREAD

**Issue by AdishSagarawat** [revanced/revanced-patches#2355]
### Application

Google Chrome !

### Issue

I am tired of seeing ads.

### Patch

The most demanded, enabling blocking ads in chrome.

### Motivation

Because chrome is chrome

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [ ] I filled out all of the requested information in this issue properly.

**Comment by Julius8900** [comment]
You can simply solve this issue by installing AdGuard on your phone.

**Comment by reisxd** [comment]
Acknowledgements not met.

**Comment by AdishSagarawat** [comment]
@Julius8900 it's paid, eat's up battery and yeah of course ! PRIVACY (?)

**Comment by Julius8900** [comment]
Then use Brave

**Comment by Ushie** [comment]
> @Julius8900 it's paid, eat's up battery and yeah of course ! PRIVACY (?)

Use AdGuard private DNS then

**Comment by Ushie** [comment]
> @Julius8900 it's paid, eat's up battery and yeah of course ! PRIVACY (?)

Use AdGuard private DNS then

**Comment by oSumAtrIX** [comment]
Kiwi can block ads with UBlockOrigin

**Comment by AdishSagarawat** [comment]
@oSumAtrIX Yeah, but I want sync across devices, especially between computer and phone.
And yeah, all the passwords and bookmarks along with sync will blow away if I use KiWi. 

And I also know that Firefox is also there but I doesn't meets my productivity needs.

Thanks
Regards, 
Adish

**Comment by Ushie** [comment]
AdGuard DNS will work well in your case

By the way, by patching Chrome you won't be able to login to your Google account, so it'd hinder your sync eitherway

**Comment by oSumAtrIX** [comment]
@AdishSagarawat Sync extensions exist.

**Comment by CnC-Robert** [comment]
> @Julius8900 it's paid, eat's up battery and yeah of course ! PRIVACY (?)

why are you using google chrome if you want privacy

**Comment by SodaWithoutSparkles** [comment]
1. Use DNS-based blockers like Pi-hole or adguard
2. Use firefox w/ ublock origin plugin, which does not spy on you (at least not to the same degree as chrome)
3. Use other browsers like brave with in-built adblocking functionality 
4. Use kiwi browser w/ ublock origin

You shouldnt be saving passwords in browsers anyway, use a password manager. Password stored in browsers, if synced to a desktop, are not protected/encrypted. They are stored in a predictable location. Malware can steal them easily.
