### ISSUE TITLE
feat(fr24): premium functions / remove client-side restrictions

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [revanced/revanced-patches#2356]
### Application

Flight radar 24
https://play.google.com/store/apps/details?id=com.flightradar24free

### Issue

Some functions are hidden behind the paywall, such as different map types, ability to show multiple text labels, ATC boundaries, etc

### Patch

Enable premium / allow above functions. Best approach would be to enable premium client-side. If not, at least the "multiple text labels" can be enabled client-side. If possible, enabling "ATC boundaries" would.be nice, but i am not sure if the data is there yet.

Tdata are there, for example, all text labels can be enabled individually, but cannot be enabled at the same time. So it is obviously client side restrictions.

### Motivation

This app is frequently used to track flights, has over 50M installs 

Note that this is different from #1994 to just remove ads. Ads can already be removed by DNS-based blockers like pi-hole. This is also different from #1301 as we are not trying to break server-side restrictions. This request is to remove client-side restrictions on text labels and etc.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Are those client side features?

**Comment by SodaWithoutSparkles** [comment]
I am not sure about gold/silver premium feature can be released client-side. For example, i am not sure if client side already have the necessary data to display ATC boundary. BUT, i am absolutely sure that the information for text labels are already there. You can indeed select each of the information separately. So the data is there, you just cant select multiple of them simultaneously.

![video](https://cdn.discordapp.com/attachments/1110761986477785139/1114888733242695740/Screenrecorder-2023-06-04-20-08-34-990.mp4)

**Comment by SodaWithoutSparkles** [comment]
I am not sure about gold/silver premium feature can be released client-side. For example, i am not sure if client side already have the necessary data to display ATC boundary. BUT, i am absolutely sure that the information for text labels are already there. You can indeed select each of the information separately. So the data is there, you just cant select multiple of them simultaneously.

![Screenshot_2023-06-04-20-10-56-225_com.mixplorer.jpg](https://github.com/revanced/revanced-patches/assets/64138578/1d5847cc-572c-406b-8997-436e4f9cb784)

![video](https://cdn.discordapp.com/attachments/1110761986477785139/1114888733242695740/Screenrecorder-2023-06-04-20-08-34-990.mp4)

**Comment by SodaWithoutSparkles** [comment]
It does seem that there are cracks that unlock premium. [Example](https://deskrush.com/flightradar24-mod-apk/)

I may try to run that in a VM later

**Comment by oSumAtrIX** [comment]
In that case, open a separate issue for the client-side features and remove the server side features from the issue.

**Comment by SodaWithoutSparkles** [comment]
> In that case, open a separate issue for the client-side features and remove the server side features from the issue.

@oSumAtrIX 
I am trying to run the cracked apk in an VM. If it can be done by the cracked apk, then those features are client-side. If so, can you re-open this issue?

**Comment by oSumAtrIX** [comment]
Which features?

**Comment by SodaWithoutSparkles** [comment]
The ATC boundaries, airspeed, etc functions. 

Anyway, i wasnt able to get the cracked apk working in an online malware anysis sandbox. Might try with virtualbox later, but in the meantime, i will open another issue on those client-side restrictions.

BTW, cant revanced spoof google play subscription check?
