### ISSUE TITLE
Suggestion: Light Mode for YT Music (Material You if Possible)

### ISSUE THREAD

**Issue by Brubhubedits** [revanced/revanced-patches#2362]
### Application

YouTube Music ReVanced/Extended

### Issue

YouTube Music only has the default dark background and it gets very boring and inconsistent with the rest of my phone. 

### Patch

Suggestion: Light Mode for YT Music (with Material You if possible)
This would literally be perfect for me since I use dynamic themes based on time of day. If the colour scheme of the app could be light and match the song or just be light that would be the 🐐

### Motivation

It means that YouTube Music will have one less inconsistency and makes it finally more usable for me. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by dpthegrey** [comment]
I'd love to see light mode too, using a dark mode app in sunlight makes device overheat and sometimes there is warning of unable to charge device that is bad

**Comment by Julius8900** [comment]
[#1567](https://github.com/revanced/revanced-patches/issues/1567)
