### ISSUE TITLE
fix(youtube/video-speed): add optional mod with smaller video-speed increment. For more comfortable controlling of video speed.

### ISSUE THREAD

**Issue by DulaBula** [revanced/revanced-patches#2372]
### Application

YouTube

### Issue

Gives us a more accurate and comfortable video speed setting. Possibility to choose the speed increment. Or at least the optional mode in the settings with an increment of 0.05.

### Patch

Now the increment is 0.25. This is a lot and does not allow us to fine-tune the speed. It is desirable to let the user choose the value of the increment himself. Or at least give us an option in the settings with an increment of 0.05.

### Motivation

There are many talking videos on YouTube. Many are too slow. Especially educational videos. But the acceleration at 1.25 is often too strong. Therefore, it turns out that a more precise setting of the video speed with a smaller increment is needed. At least 0.05 would be enough.

In the SmartTube application for androidTV, the increment is 0.05. And it's great. We need the same option for a smartphone.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
You can set any speed in the settings.
