### ISSUE TITLE
feat: MyFitnessPal ads and premium features

### ISSUE THREAD

**Issue by eiqnepm** [ReVanced/revanced-patches#2380]
### Application

https://play.google.com/store/apps/details?id=com.myfitnesspal.android

### Issue

MyFitnessPal is littered with ads and lots of features are locked behind a paywall which requires Google services

### Patch

Remove ads and enable premium features, useful for those who are unable to subscribe due to lacking Google services

### Motivation

MyFitnessPal is the number one app for keeping a healthy diet, scanning barcodes is a premium feature that is very convenient and saves lots of time, unfortunately you cannot access these features without Google services.

Modified packages do exist which solves these issues, however they lack transparency which is a huge security concern

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
I just checked, the app is not the number one. Regardless of that theres alternative apps with no such ads

**Comment by eiqnepm** [comment]
> I just checked, the app is not the number one. Regardless of that theres alternative apps with no such ads

What over calorie counter has over one-hundred million downloads?

Also other apps might have the same functionality, however their databases are useless due to their relatively tiny user bases.

**Comment by oSumAtrIX** [comment]
Download count does not implicate being the number one app and other apps have big enough databases.

**Comment by jellie-bean** [comment]
Request: reopen this request

There are no other apps with nearly enough in their databases. This is by far the biggest. Also this reason for closing makes no sense. You could say this about any app eg. There are other video watching apps than YouTube but it has the most videos, there are other language learning apps than duolingo. Yet there are still patches for those.

Also, for this app (my fitness pal) detailed nutrition info is hidden behind pay wall so not useful for trying to gain muscle and look at protein etc.

**Comment by eiqnepm** [comment]
Agreed

**Comment by oSumAtrIX** [comment]
> Also, for this app (my fitness pal) detailed nutrition info is hidden behind pay wall 

This is a server side locked feature and won't be able to be unlocked

**Comment by oSumAtrIX** [comment]
Any source of claim?

**Comment by eiqnepm** [comment]
> Any source of claim?

> Modified packages do exist which solves these issues, however they lack transparency which is a huge security concern

As I mentioned, modified packages for MyFitnessPal exist, after testing in a virtual machine, they do in fact work as advertised, all premium features function, however due to being prebuilt packages, I do not trust them to not have anything malicious added, so I do not use them on my phone. I believe this is exactly why ReVanced was created, to provide end users the ability to modify the packages themselves will full transparency.

**Comment by oSumAtrIX** [comment]
Closing according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#%EF%B8%8F-guidelines-for-requesting-or-contributing-patches). Thanks anyways.
