### ISSUE TITLE
bug: youtube's "hide sound button" in "disable shorts components" does not work

### ISSUE THREAD

**Issue by Matszwe02** [ReVanced/revanced-patches#2381]
### Type

Cosmetic

### Bug description

after enabling these options, nothing changes.

### Steps to reproduce

enable "hide sound button" and "hide info panel"
go to shorts
see nothing changed

### Relevant log output

```shell
couldn't run
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
There is no such thing as "hide sound button"

**Comment by Matszwe02** [comment]
> There is no such thing as "hide sound button"

![image](https://github.com/revanced/revanced-patches/assets/49353902/babd6dd3-3844-4f9d-a600-506d7b28b810)

**Comment by oSumAtrIX** [comment]
On the other hand, the sound "button" is actually not working

**Comment by Matszwe02** [comment]
> The info panel rarely shows up. It only appears in shorts about the 2020 virus, and possibly shows wikipedia links in other videos.
> 
> So the hide info panels switch might appears to do nothing, only because the info panel was not present to begin with. But the setting does work.

thx, revanced button's descriptions are not clear about what does a button change, I thought it was the top icons (camera, back arrow, magnifying galss and 3 dots)

**Comment by n1cKz1** [comment]
For now, sound button can be hidden by filtering this string:

reel_pivot_button.eml
