### ISSUE TITLE
feat: change-oauth-client-id for Infinity for Reddit

### ISSUE THREAD

**Issue by tabtomi8** [revanced/revanced-patches#2404]
### Application

Infinity for Reddit
[Github](https://github.com/Docile-Alligator/Infinity-For-Reddit)

### Issue

Reddit's new API limit
https://www.reddit.com/r/revancedapp/comments/147breu/use_sync_for_reddit_after_june_12_with_the_latest/

### Patch

change-oauth-client-id

### Motivation

Because many people would like to use this app too after July 1st.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Any reason for Boost over Sync for Reddit?

**Comment by tabtomi8** [comment]
Infinity (not Boost) has been translated to more languages, and I like its look more than Sync.

**Comment by oSumAtrIX** [comment]
Where can I see a list of both apps translations? Sync is highly customizable in terms of looks, besides being personal preference and not a motivation to patch.

![Screenshot_2023-06-12-17-27-40-77_f9dbdf549e278560a5aae87a7709be13](https://github.com/revanced/revanced-patches/assets/13122796/c1692d5b-c3fa-405b-b860-804d6cbc5698)

![Screenshot_2023-06-12-17-27-53-43_4927e44eb8e73beb00f2a6e86c844bff](https://github.com/revanced/revanced-patches/assets/13122796/944a04c9-cdea-4b6e-b197-b5e51092eca5)

**Comment by tabtomi8** [comment]
For infinity: https://poeditor.com/join/project?hash=b2IRyfaJv6

I couldn't find if Sync has been translated to other languages

**Comment by Turhvjbufv** [comment]
And sync has trackers and is not open source unlike infinity

**Comment by tabtomi8** [comment]
> > For infinity: https://poeditor.com/join/project?hash=b2IRyfaJv6
> > 
> > I couldn't find if Sync has been translated to other languages
> 
> Then how can you say it has more?
> 

I misspoke. I was meant to say, Infinity has been translated to other languages, Sync is only English. 
Also, Infinity is open-source, unlike Sync

**Comment by tabtomi8** [comment]
> Sorry but since the r/revanced is private, could anyone tell me what is it about? Thank you.

> Sorry but since the r/revanced is private, could anyone tell me what is it about? Thank you.

> Sorry but since the r/revanced is private, could anyone tell me what is it about? Thank you.

Revanced developers made a patch for Sync for Reddit, where you can add your own reddit 'API key' (oauth client id).

**Comment by oSumAtrIX** [comment]
If infinity is open source, it does not need a patch

**Comment by Turhvjbufv** [comment]
Yeah but we have no idea how to do it ourselves so we ask you if you could please do that

**Comment by tabtomi8** [comment]
One more thing, Sync will be [shut down](https://cc.bingj.com/cache.aspx?q=sync+reddit+shut+down&d=2459394201883&mkt=en-WW&setlang=en-US&w=BdyXpcRnjpW6JH1ycF2Iphm1YKyHI89g) on June 30th, [Infinity will not](https://www.reddit.com/r/Infinity_For_Reddit/comments/147bhsg/the_future_of_infinity/). And since Sync is closed source, with no future updates, it will make the app obsolete.

> The project will remain open-source, no matter if Infinity is sustainable or not, but the code related to Google Play billing and API key will not be published on GitHub. This means that the code on GitHub and my own machine will be slightly different and if you build Infinity yourself, you will not see a subscription page. F-Droid's Infinity will be removed since the repository on GitHub will not contain my API key anymore and that makes it unusable. Infinity's GitHub release page will not be closed and all the upcoming versions (they are the same as Google Play's) will still be published there.

**Comment by oSumAtrIX** [comment]
The app will be obsolete once it stops working

**Comment by E0697** [comment]
I believe the current patch needs to consider this:
https://www.reddit.com/r/Infinity_For_Reddit/comments/14c7v84/if_you_want_to_use_your_own_api_key/
