### ISSUE TITLE
feat(syncforreddit): add support for pro version 

### ISSUE THREAD

**Issue by y-voigt** [revanced/revanced-patches#2406]
### Application

Sync for Reddit Pro

### Issue

Revanced patches are not available for the [Pro](https://play.google.com/store/apps/details?id=com.laurencedawson.reddit_sync.pro)-version of the Sync for Reddit app.

### Patch

Add compatibility for Pro-version (com.laurencedawson.reddit_sync.pro)

### Motivation

Make patches available for Pro-users of the app.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by SodaWithoutSparkles** [comment]
Can this be closed by the latest release?

**Comment by oSumAtrIX** [comment]
The dev package name is not present

**Comment by oSumAtrIX** [comment]
Considering, it is useless, as the dev version only receives updates earlier, but Sync is discontinued

**Comment by thx1e** [comment]
Could you add support for v19/v19 pro ?  None of the patches seems to be compatible.

**Comment by oSumAtrIX** [comment]
Why should the old one be supported?

**Comment by thx1e** [comment]
Different UI, it has been reworked on 20+

**Comment by oSumAtrIX** [comment]
> Not for us who actually bought the separate Dev version to support the developer

Where is the use? As I explained the dev version receives updates earlier, but there's no further updates anyways

**Comment by ja3h** [comment]
> Where is the use? As I explained the dev version receives updates earlier, but there's no further updates anyways

For those who only bought and had Dev installed it would be easier. 
But I just backed up from Dev and restored the backup in the free version of Sync, then patched with ReVanced Manager so it doesn't matter.

**Comment by oSumAtrIX** [comment]
> For those who only bought and had Dev installed it would be easier.

You can install the regular app the same way.
