### ISSUE TITLE
bug: Can't run change-oauth-client-id for Sync

### ISSUE THREAD

**Issue by noobking4000** [revanced/revanced-patches#2407]
### Type

Error while patching

### Bug description

I have installed the latest version of the manager/patches, and downloaded the latest version of sync for reddit. When I try to patch using my client ID I get the error "Failed to apply change-oauth-client-id"
File is stored in my SD card base folder

If I move the txt file to my Internal Storage I get an error "EACCES (Permession denied)"

The revanced manager has no restrictions on storage reading or deleting in the app info

### Steps to reproduce

Download Sync from APKmirror (ver 23.05.03)
Get client ID and save it as reddit_client_id_revanced.txt
Save it in SD card or Internal Storage
Try and patch Sync with change-oauth-client-id

### Relevant log output

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Deleting existing resource cache directory
Decoding resources
Failed to apply change-oauth-client-id: In order to use this patch, you need to provide a client ID.
You can do this by creating a file at /storage/emulated/0/reddit_client_id_revanced.txt with the client ID as its content.
Alternatively, you can provide the client ID using patch options.

You can get your client ID from https://www.reddit.com/prefs/apps.
The application type has to be "installed app" and the redirect URI has to be set to "http://redditsync/auth"
Failed to apply change-package-name: No package name provided
Applied disable-ads
Applied enable-android-debugging
Applied export-all-activities
Applied predictive-back-gesture
Applied remove-screen-capture-restriction
Applied remove-screenshot-restriction
Applied spoof-wifi-connection
Repacking patched apk
Compiling resources
Writing modified dex files
Finished!
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by reisxd** [comment]
Update your manager and give storage access

**Comment by noobking4000** [comment]
Manager has been updated today, is on version 1.3.5

All Storage permissions are set to Allowed
![Screenshot_20230612-122946_Permission controller](https://github.com/revanced/revanced-patches/assets/63563160/b9796479-528e-4145-9751-813410440dcf)

![Screenshot_20230612-122958_Permission controller](https://github.com/revanced/revanced-patches/assets/63563160/f13b5234-b1d8-47c7-a476-9fe36dca7d23)

**Comment by noobking4000** [comment]
> Tried resetting the app data?

Yep that sorted it, thanks
