### ISSUE TITLE
feat(Youtube): Remember playback speed is always active despite is disabled

### ISSUE THREAD

**Issue by HeroGalak** [revanced/revanced-patches#2409]
### Type

Other

### Bug description

Title self explanatory

### Steps to reproduce

Disable remember playback speed in settings.
Open a video and change speed
Then open another video and the speed is not set to default x1 as it should be.

### Relevant log output

```shell
//
```

### Additional context

The bug is present both with a registered account and in incognito mode

Using recommended YT version with latest patches

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
You disabled it to remember the 1x speed

**Comment by HeroGalak** [comment]
Default speed is set to x1.
Remember playback speed is disabled.

So if the speed is changed in player menu it should default to x1 every time a video is opened.

But this does not happen.
If changed, the speed remains the same throughout other videos.

I checked, and the speed is resetted to x1 only by reopening the app

**Comment by HeroGalak** [comment]
> Or are you referring to it remembering the playback speed, if a new video is opened from the videos shown below the current video?  (Open a video, change playback speed, scroll down the current video, open a new video from the player)?
> 
> If so, this is the behavior of stock YouTube.  Try unpatched YouTube and you'll see.

Ok it seems that the speed is reset only when the player is closed.

**Comment by oSumAtrIX** [comment]
I think expected behavior is the following:

1. Disable "remember video speed"
2. Video A plays on 1x
3. Set speed to 2x
4. Video B still plays on 1x

But what actually happens, is that 4. changes to 2x, thus "remembering" the speed even though it shouldn't. The patch is meant to remember throughout sessions of the app, so if you toggle on remember, it remembers EVEN when you exit the app.
