### ISSUE TITLE
feat: set downloader package name automatically if only one downloader is found during first app startup

### ISSUE THREAD

**Issue by soredake** [revanced/revanced-patches#2410]
### Application

YouTube

### Issue

Right now if you have only one downloader installed (seal, for example) you will need to set downloader name manually.

### Patch

It would be nice if revanced youtube can set downloader package name automatically if only one downloader is found during first app startup.

### Motivation

Less actions from user if only one downloader is installed during first startup.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
What if I create a new downloader privately, ReVanced can't be aware of that, this is not possible to do

**Comment by soredake** [comment]
> What if I create a new downloader privately, ReVanced can't be aware of that, this is not possible to do

I don't understand how is this related, having list of at least public downloaders is better than nothing.

**Comment by oSumAtrIX** [comment]
The downloads patch should ideally be generic to any downloader so that it remains unopinionated. Most people have no downloader present, as for why the present package acts as an initial starting point for them.

**Comment by SodaWithoutSparkles** [comment]
> The downloads patch should ideally be generic to any downloader.

So why newpipe was the default then? 

Should **ideally** be generic, but this world is not ideal.

**Comment by oSumAtrIX** [comment]
@SodaWithoutSparkles 

> So why newpipe was the default then?

That is explained in the message you quoted:

> Most people have no downloader present, as for why the present package acts as an initial starting point for them.

@soredake 

> And how is my proposal prevents it? No downloader installed -> set nothing/newpipe, only Seal installed -> set seal. Setting newpipe by default even if it is not installed is OPINIONATED, i'd say.

As previously explained:

> What if I create a new downloader privately, ReVanced can't be aware of that, this is not possible to do

**Comment by oSumAtrIX** [comment]
Because ideally, no package should be present just like @SodaWithoutSparkles said:

> Should ideally be generic

**Comment by SodaWithoutSparkles** [comment]
> Because ideally, no package should be present just like @SodaWithoutSparkles said:
> 
> > Should ideally be generic

But you missed the point. My point is "The world is not ideal"

**Comment by oSumAtrIX** [comment]
Point remains though, that ideally it should be generic.

**Comment by SodaWithoutSparkles** [comment]
@oSumAtrIX what makes newpipe more generic than others?

**Comment by oSumAtrIX** [comment]
It doesn't, quoting you:

> Should ideally be generic, but this world is not ideal.

The reason why it exists is as already previously mentioned twice:

> Most people have no downloader present, as for why the present package acts as an initial starting point for them.

**Comment by soredake** [comment]
I don't think setting downloader that might not be installed for many people is better than setting *actually* installed downloader.
