### ISSUE TITLE
feat: show create button and notification button

### ISSUE THREAD

**Issue by NoEnd-yt** [revanced/revanced-patches#2412]
### Application

YouTube ReVanced

### Issue

Title says it all. There is no current way to show the create and the notifications buttons at the same time, it's either one or another. I don't like replacing the notifications tab with the subscriptions tab because it doesn't support adding videos to the watchlist and doesn't have community posts.
Would there be a way to show those 2 buttons at the same time?

### Patch

The patch would allow to toggle the notifications button, allowing users to have both the create and the notifications button at the same time.

### Motivation

It would allow users to have both the create and the notifications button at the same time.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
The notification button shows in the original place if you don't swap it. From then on, you can disable hiding the create button

**Comment by NoEnd-yt** [comment]
Doesn't work.
![Screenshot_20230613_021939.png](https://github.com/revanced/revanced-patches/assets/76617157/52a4eaba-8159-4f70-baa0-0405f1593ef2)

![Screenshot_20230613_022004.png](https://github.com/revanced/revanced-patches/assets/76617157/93786570-ff1a-4f0b-b621-298ef594d26f)

**Comment by oSumAtrIX** [comment]
![Screenshot_2023-06-13-02-28-59-95_f9ee0578fe1cc94de7482bd41accb329](https://github.com/revanced/revanced-patches/assets/13122796/4b4bd1ad-d471-458c-aa07-4beebd58ccd8)
