### ISSUE TITLE
Twitter bug: <title>

### ISSUE THREAD

**Issue by Pakshal9114** [revanced/revanced-patches#242]
### Type

Cosmetic

### Bug description

Twitter reply section shows promoted tweets

### Steps to reproduce

Don't know 

### Relevant log output

```shell
Don't have
```

### Screenshots or videos

![SPOILER_IMG_20220727_142048_452](https://user-images.githubusercontent.com/102651194/181240150-3389f8ff-ba8d-4665-b9d2-0418a32bb2fa.jpg)
Bug not blocking ads

### Solution

Unknown

**Comment by oSumAtrIX** [comment]
The Twitter patch description says it blocks ads in the timeline.

**Comment by aliafshany** [comment]
I got the same exact issue.
Also, this happened on TwiFucker module on xposed too.
