### ISSUE TITLE
bug: hide ads for reddit 

### ISSUE THREAD

**Issue by vasile-coste** [revanced/revanced-patches#2425]
### Type

Cosmetic

### Bug description

The latest version of hide-ads for reddit hides more than just the ads. For instance it hides the custom feed groups(it only shows the option to create a new custom feed), after 20 to 30 posts in home it stops loading new posts.

I've posted a few images to show how the home and custom feed looks on non-patched app. On the patched app the 2 custom feed groups are missing.

### Steps to reproduce

Patch the latest or previous version of reddit with hide-ads, install the app, try to browse the custom feed - here you must have at least one custom feed to notice that it doesn't shows up. Same for home scroll, after 20-30 posts it won't load any 

### Relevant log output

```shell
Sorry, I don't have any
```

### Screenshots or videos

![Screenshot_20230614_223632_Reddit](https://github.com/revanced/revanced-patches/assets/17108452/62dd6a3f-60b6-45b3-9658-e681068ba828)
![Screenshot_20230614_223619_Reddit](https://github.com/revanced/revanced-patches/assets/17108452/bd73266d-d4e6-418c-87d3-843f491896a4)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by KyaBamba** [comment]
I think it also hides your own comments. Could you check what happens when you go to your profile and then to "comments"?

**Comment by vasile-coste** [comment]
> I think it also hides your own comments. Could you check what happens when you go to your profile and then to "comments"?

Yes, the comments are gone too

**Comment by oSumAtrIX** [comment]
@Blatzar Looks like the filters are too aggressive, any clue about that?

**Comment by oSumAtrIX** [comment]
@Blatzar try the latest revision

**Comment by Blatzar** [comment]
@oSumAtrIX 
Im very certain this refactor broke it
https://github.com/revanced/revanced-integrations/pull/419/commits/83167b8061a557d79aa58f16cae6a79a31db9966

See how you continue if it is not an ILink, the original code added if it was an ILink
