### ISSUE TITLE
feat:(Photomath) Dark mode

### ISSUE THREAD

**Issue by EhabxAlaa** [revanced/revanced-patches#2428]
### Application

Photomath 

### Issue

The app doesn't have any dark mode and it's white is very annoying especially in the history tab

### Patch

Add a dark mode , preferably amoled black if possible 

### Motivation

Dark mode is good and white mode is bad XD

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [x] I have written a short but informative title.
- [ ] I filled out all of the requested information in this issue properly.

**Comment by EhabxAlaa** [comment]
Why? What was missing, do i have to write too many lines of why white mode hurts my eyes? And dark mode looks better?!

**Comment by oSumAtrIX** [comment]
This is a math application not a video player
