### ISSUE TITLE
feat(patch): Google Recorder porting for non-Pixel phones

### ISSUE THREAD

**Issue by ignamiranda** [revanced/revanced-patches#2430]
### Application

Google Recorder

### Issue

Google Recorder is exclusive to pixel phones despite being able to run on other Android phones with some modifications.

### Patch

The patch would bypass Google's integrity check and remove any Pixel dependencies.

I'm not sure if this technique still works but this could be somewhere to start: https://github.com/Xmader/google-recorder

### Motivation

It would bring a useful app to the broader Android userbase.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by udiNur** [comment]
Do we have any working solution on this?
