### ISSUE TITLE
feat: (YouTube) hide breaking news shelf (component name included)

### ISSUE THREAD

**Issue by n1cKz1** [revanced/revanced-patches#2433]
### Application

YouTube

### Issue

Not sure if it's already supposed to be hidden, but breaking news shelf appears on homepage for me as of today.
![Screenshot_2023-06-16-00-25-00-224_app revanced android youtube](https://github.com/revanced/revanced-patches/assets/107653639/fe850352-af62-44c3-a467-c3058ed53675)

### Patch

Remove this component (already tested with custom filter): 
horizontal_video_shelf.eml

### Motivation

They are annoying and ruin the homepage

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
`horizontal_video_shelf.eml` blocks playlists. We could add this but there's that limitation with the filter.

**Comment by n1cKz1** [comment]
Well that sucks. No other way to block this particular shelf?

**Comment by oSumAtrIX** [comment]
Actually there is lol, how did I not think about checking the parent. Can you send the full pathBuilder string?

**Comment by n1cKz1** [comment]
Sweet. Would this suffice?

Searching (ID: null, Buffer-size: 2240): horizontal_video_shelf.eml|6a7ef4e2b5c05b0b|CellType|horizontal_shelf.eml|1f659f33672b7c64|ContainerType|CollectionType|video_card.eml|116f19c3af06c258|CellType|video_card_content.eml|a845ff293c60285|ContainerType|ContainerType|ContainerType|metadata.eml|26a145fe3a306252|metadata_content.eml|cbd6762dbe981a7c|ContainerType|ContainerType|

**Comment by oSumAtrIX** [comment]
Unfortunately there is no parent, so this is not doable. Additional checks for the current view would be necessary

**Comment by n1cKz1** [comment]
Sadge. Guess i'll have to settle with clicking not interested everytime i see it on the homepage for now.

**Comment by n1cKz1** [comment]
I tried looking into it a lil bit, and blocking this particular section seems to do the job. Doesn't look like it's affecting playlists either, although i could be wrong, i'll test it some more.
horizontal_video_shelf.eml|6a7ef4e2b5c05b0b|CellType|horizontal_shelf.eml|1f659f33672b7c64

**Comment by n1cKz1** [comment]
The section "1f659f33672b7c64" is seemingly reserved for breaking news playlists and is always consistent, so this string is what did the job for me:

horizontal_video_shelf.eml|6a7ef4e2b5c05b0b|CellType|horizontal_shelf.eml|1f659f33672b7c64

blocking just the video cards won't do because it will still show an empty "breaking news" shelf

**Comment by n1cKz1** [comment]
Will do. I'll let you know in the near future

**Comment by raniesantos** [comment]
Hello gentlemen.
May I know if any alternative was found or is this another feature that's basically dead?

**Comment by RustyLovecraft** [comment]
@n1cKz1 I tried your custom filter and it appears to have no effect on removing the breaking news shelf.
