### ISSUE TITLE
bug: YouTube like and loading images are messed up

### ISSUE THREAD

**Issue by Ayayayayaka** [ReVanced/revanced-patches#2434]
### Bug description

I used the latest patcher and recommended YouTube version. 
![Screenshot_2023-12-13-18-39-46-725_app revanced android youtube](https://github.com/ReVanced/revanced-patches/assets/153704437/c98a48bb-d84e-42c6-adf1-30851a4d76a9)
![Screenshot_2023-12-13-11-41-46-889_app revanced android youtube-edit](https://github.com/ReVanced/revanced-patches/assets/153704437/70103008-699d-4b1a-b4cd-2ff82f07eb23)
![Screenshot_2023-12-13-11-36-17-411_app revanced android youtube](https://github.com/ReVanced/revanced-patches/assets/153704437/5c1f0b02-979c-41f7-953e-903c5b9a9e38)

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Restart the app

**Comment by Ayayayayaka** [comment]
Did not work
Clear app data that thing

**Comment by oSumAtrIX** [comment]
Restart, not clear app data

**Comment by Ayayayayaka** [comment]
How do I restart

**Comment by Ayayayayaka** [comment]
Yes miui from. Change default theme at where

**Comment by Ayayayayaka** [comment]
Did not work
Also it was fine when I did the patch when suggested version was 18.45.41
I redid it since I wanted to add no resume short on start up

**Comment by oSumAtrIX** [comment]
Record the following in one take:

1. Uninstall the patched app
2. Close and open ReVanced Manager
3. Showcase all settings
4. Patch and install
5. Open the patched app and close it
6. Open it again and show the issue

**Comment by Ayayayayaka** [comment]
![IMG_20231215_112042](https://github.com/ReVanced/revanced-patches/assets/153704437/9d730bea-7862-4069-874c-ee6cf34db3d8)
![Screenshot_2023-12-15-11-20-12-982_app revanced android youtube](https://github.com/ReVanced/revanced-patches/assets/153704437/86c87f16-43d7-4aaf-87c3-d15113d129fb)
![Screenshot_2023-12-15-11-19-54-442_app revanced android youtube](https://github.com/ReVanced/revanced-patches/assets/153704437/84a038ef-2dec-4821-88bc-946adb671a9b)
![Screenshot_2023-12-15-11-17-22-067_app revanced manager flutter](https://github.com/ReVanced/revanced-patches/assets/153704437/baccba1e-31b7-4716-a889-fb15f567a4eb)

**Comment by oSumAtrIX** [comment]
Open a new issue for RYD and follow the steps I sent for the other issue correctly please.

**Comment by oSumAtrIX** [comment]
To show settings of ReVanced Manager

**Comment by Ayayayayaka** [comment]
![Screenshot_2023-12-15-16-52-36-259_app revanced manager flutter](https://github.com/ReVanced/revanced-patches/assets/153704437/7a14ea1f-a843-45b3-934b-f01a3eeb166a)
![Screenshot_2023-12-15-16-52-34-086_app revanced manager flutter](https://github.com/ReVanced/revanced-patches/assets/153704437/3fc96b7a-46a8-4ea9-947b-702d20e94778)
![Screenshot_2023-12-15-16-52-26-761_app revanced manager flutter](https://github.com/ReVanced/revanced-patches/assets/153704437/71b85412-d796-410c-9e19-5fda7f447bfa)
![Screenshot_2023-12-15-16-52-22-146_app revanced manager flutter](https://github.com/ReVanced/revanced-patches/assets/153704437/4ff209dd-c2f3-4b20-9ab1-5d27cea551f6)
