### ISSUE TITLE
feat: (youtube) add loop button in the video player controls

### ISSUE THREAD

**Issue by BOY0038v2** [revanced/revanced-patches#2435]
### Application

Youtube

### Issue

i would like to have the loop button in the video player menu just like in YT Vanced, because it's very inconvenient to toggle loop through the flyout menu.

### Patch

i would like to have the loop button in the video player menu just like in YT Vanced, because it's very inconvenient to toggle loop through the flyout menu.

### Motivation

i would like to have the loop button in the video player menu just like in YT Vanced, because it's very inconvenient to toggle loop through the flyout menu.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by johnconner122** [comment]
I think `always-autorepeat` patch does that.

**Comment by oSumAtrIX** [comment]
#1891

**Comment by lampham7** [comment]
Good job, just close all feature requests without reason, so helpful!

**Comment by lampham7** [comment]
> #1891

Good job, just close all feature requests without reason, so helpful!
