### ISSUE TITLE
bug: Long-form tweets not displaying in full

### ISSUE THREAD

**Issue by j7e** [revanced/revanced-patches#2437]
### Type

Error at runtime

### Bug description

Long-form tweets in patched Twitter do not display as expected. In the timeline, after the 280 (?) character limit, they are appended with an https://twitter.com/i/web/status/[some number] link to the tweet (e.g. https://twitter.com/i/web/status/1669508927283941376). The same occurs when viewing the individual tweet, which the unpatched Twitter app would normally display the full text and without the link.

Tapping the link can either loop back to opening the tweet in the patched Twitter app or in a browser, where the tweet renders in full, as expected.

### Steps to reproduce

1. Open Twitter.
2. Scroll the timeline until you find a long-form tweet.

### Relevant log output

```shell
No crash log.
```

### Screenshots or videos

![Timeline view](https://github.com/revanced/revanced-patches/assets/43884657/72e14c93-680a-40cc-879e-6c3ba9cbb3f5)
![Tweet view](https://github.com/revanced/revanced-patches/assets/43884657/cd94b70e-144f-42a4-955e-6f9d4d52d835)

### Additional context

Device: Samsung Galaxy A40 
Android version: 11
Twitter version: 9.71.0-release.0 (nodpi)
ReVanced Manager version: 1.3.5

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Unable to reproduce on the latest version of Twitter, are you up to date?

**Comment by j7e** [comment]
> Unable to reproduce on the latest version of Twitter, are you up to date?

Sorry, I forgot to add version details to my post. I've added them under Additional context:

Device: Samsung Galaxy A40 
Android version: 11
Twitter version: 9.71.0-release.0 (nodpi)
ReVanced Manager version: 1.3.5

It isn't the latest version of Twitter, but I used the one currently suggested in ReVanced Manager.

**Comment by oSumAtrIX** [comment]
That explains why you can't use the new feature of Twitter. You need to use a later version
