### ISSUE TITLE
feat (YouTube): Premium Header + Wide Search Bar appearing simultaneously.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [ReVanced/revanced-patches#2438]
### Feature description

It is requested please add a feature where "Premium Header" and "Wide Search Bar" appear simultaneously side-by-side.
![Screenshot_2023-12-15-09-13-11-09_f22faf49515899f9781ec174a4d85388](https://github.com/ReVanced/revanced-patches/assets/91815107/4cef129d-9ad1-4c30-9a3b-eaa7ffeff690)
![Screenshot_2023-12-15-09-14-57-69_f22faf49515899f9781ec174a4d85388](https://github.com/ReVanced/revanced-patches/assets/91815107/e37e397f-985b-4bb7-beea-8e60f6d8cbf2)

### Motivation

1.) After the introduction of You tab, space has increased on the top header. So, both Premium Header & Wide Search bar can be occupied.

2.) Search button is a basic feature, so it should have a bigger bar without compromising on the Premium Header.

Thank you.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
The wide search bar has a functional purpose unlike the header. Chose either

**Comment by Aryan-Chauhan** [comment]
> The wide search bar has a functional purpose unlike the header. Chose either

Still doesn't explain why cosmetic features & functional features cannot exist side-by-side.

There's no rule like that in ReVanced docs.

Waiting for member's reply.

**Comment by oSumAtrIX** [comment]
They can, its simply not worth the effort. Feel free to implement the patch and pull request it
