### ISSUE TITLE
YT ReVanced crashes when searching for an artist while spoofed to 16.0x.xx

### ISSUE THREAD

**Issue by KobeW50** [revanced/revanced-patches#2440]
### Type

Error at runtime

### Bug description

If you are spoofed to 16.0x.xx and search for an artist, the app crashes before the search results are displayed.

I tested this after disabling all of the layout toggles and without the custom filter and it still crashes.

I tested 16.08.35, and 16.01.35. It did not crash on 17.01.35.

### Steps to reproduce

Spoof to 16.08.35

Search for Shawn Mendes or Alec Benjamin (these are the 2 that I tested)

App crashes.

### Relevant log output

```shell
NA
```

### Additional context

Another user also tested this and reported the same issue. Normally this wouldn't be such a big deal because few people would use such an old version, but now that spoofing to 16.0x.xx can fix the [new buffer issue](https://github.com/revanced/revanced-patches/issues/2432), more people will be spoofing and having this issue.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Check on the actual app with that version. If it happens there, it's an upstream bug

**Comment by KobeW50** [comment]
After a lot of testing, I narrowed down the issue to be either the Hide album cards patch or the Hide artist card patch (unsurprisingly).

The issue still occurs whether these are toggled on or off.

Do I need ADB to get the logs?

**Comment by KobeW50** [comment]
[log.txt](https://github.com/revanced/revanced-patches/files/11782498/log.txt)

I hope I did everything correctly. I began the log and opened YT RV while it was spoofed to 16.08.35. Then searched for an artist and it crashed. then I searched for "music" and it didn't crash. Then I searched for a different artist and it crashed. I then used `ctrl + c` to stop the logging.

**Comment by oSumAtrIX** [comment]
The following exception is thrown:

`java.lang.NoSuchMethodError: No static method hideAlbumCards(Landroid/view/View;)V in class Lapp/revanced/integrations/patches/HideAlbumCardsPatch;`

**Comment by oSumAtrIX** [comment]
A fix has been pushed and is staged in the `dev` branch: `https://github.com/revanced/revanced-patches/commit/0dbffaae7d6dcb7050a9ea6e3c771839bcfdfbe1`
