### ISSUE TITLE
bug (youtube/hide mix playlists): The new Hide mix playlists do not work

### ISSUE THREAD

**Issue by KobeW50** [revanced/revanced-patches#2441]
### Type

Error at runtime

### Bug description

My YT Revanced was patched after patches version 2.176.0 and Integrations. 0.110.0 were released.

The playlists are not hidden even when the toggle is enabled.

### Steps to reproduce

Enable the Hide Mix Playlists toggle in layout settings.

Search for a music artist (such as Shawn Mendes) or a large YouTube channel.

Scroll and see that the mix playlist is shown.

### Relevant log output

```shell
NA
```

### Screenshots or videos

https://github.com/revanced/revanced-patches/assets/84587632/9a192fa7-849f-49ff-a65f-39b0b26ed027

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by johnconner122** [comment]
@oSumAtrIX https://github.com/inotia00/revanced-patches/blob/39029bae096f1a3427d3d779712ef88e2aac3c27/src/main/kotlin/app/revanced/patches/youtube/general/mixplaylists/patch/MixPlaylistsPatch.kt#L61
