### ISSUE TITLE
bug:  Unable to exit full screen video with back button 

### ISSUE THREAD

**Issue by fraps34** [revanced/revanced-patches#2442]
### Type

Error while patching

### Bug description

Hi, back button does not work while watching youtube full screen video on android car screen. It works in settings in other parts, I can exit the full screen video with the back button in the original youtube application. But none of the revanced versions can exit the full screen with the back button.

it was working fine on old youtube vanced versions.

Device:

https://i0.shbdn.com/photos/48/26/84/x5_1098482684te1.jpg

Px5 android 10 hct4 rom

### Steps to reproduce

yes

### Relevant log output

```shell
yes
```

### Screenshots or videos

yes

### Solution

yes

### Additional context

yes

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by fraps34** [comment]
https://i0.shbdn.com/photos/48/26/84/x5_1098482684te1.jpg

Px5 android 10 hct4 rom

**Comment by oSumAtrIX** [comment]
Exclude patches until the error is gone. Report back which one caused it.

**Comment by fraps34** [comment]
> If you have not yet, try reproducing on unpatched YouTube 18.19.35 (same version as ReVanced).
> 
> The issue may be version specific.

I downloaded and installed the latest version without installing any patches. The problem still persists, no version of revanced can exit full screen video with backspace. It works fine in the original version.

**Comment by fraps34** [comment]
> 



> 18.19.35



> You installed unpatched 18.19.35, and was the problem present with it or was the problem not present?

Yes, I installed 18.19.35 without patch and the problem still persists. I've tried all versions and they all have issues.

**Comment by fraps34** [comment]
> If the problem is present in unpatch 18.19.35, then it's a bug with YouTube itself.

There is no problem with the original youtube versions. Revanced is problematic.

**Comment by fraps34** [comment]
My English is not good, I may have expressed it wrong. I would appreciate if the friends who developed the Revanced application deal with this problem.

**Comment by oSumAtrIX** [comment]
Closing as the issue was present in upstream.

**Comment by fraps34** [comment]
> Closing as the issue was present in upstream.

The error mentioned in the stream is not the same as the error in the topic I opened. Please make the issue clear and let's wait for the issue to be resolved.

**Comment by oSumAtrIX** [comment]
No stream was posted above. I don't know what you mean.

**Comment by fraps34** [comment]
> No stream was posted above. I don't know what you mean.

I took a video of the problem.

https://www.youtube.com/watch?v=XTa4LAbNKdA

**Comment by oSumAtrIX** [comment]
Try excluding patches until the error is gone. Report back which patch causes it

**Comment by fraps34** [comment]
> Try excluding patches until the error is gone. Report back which patch causes it

Default , 0 applied patches
