### ISSUE TITLE
bug: `reddit.news` patch doesn't work

### ISSUE THREAD

**Issue by brian6932** [ReVanced/revanced-patches#2443]
### Bug description

https://github.com/ReVanced/revanced-patches-template/pull/2491#issuecomment-1837414042
`reddit.news` won't patch, but `free.reddit.news` patches fine. It patches without any errors, but doesn't seem to use the CID. Starting the app results in `Failed to load content` (both APKs are on version `10.2.40`, and have auto updates disabled).

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [ ] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Reproduction steps missing & Logs section removed manually

**Comment by brian6932** [comment]
There are no errors...

**Comment by brian6932** [comment]
I'm not sure what more you want me to do

**Comment by brian6932** [comment]
No longer works on `reddit.news` either.
