### ISSUE TITLE
feat: Custom filters for X (Twitter) and Reddit

### ISSUE THREAD

**Issue by chadchadchadchadchad** [ReVanced/revanced-patches#2444]
### Feature description

Basically just like the custom filter feature in Revanced YouTube. Hiding elements by adding component path builder string.

### Motivation

The importance of it is the same as in YouTube. Many people would love to hide specific elements in the apps like the "for you" tab in X (Twitter). In addition, it would make Revanced X (Twitter) and Reddit more attractive, because there is currently only the hide ads patch (besides 1 or 2 patches). 

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by johnconner122** [comment]
YouTube uses LithoUI which can be filtered through custom filter, Reddit and Twitter don't use Litho.

**Comment by chadchadchadchadchad** [comment]
> YouTube uses LithoUI which can be filtered through custom filter, Reddit and Twitter don't use Litho.

Bruh 😭 fml. Is there really no other way?

**Comment by oSumAtrIX** [comment]
The motivation already is satisfied with existing open issues
