### ISSUE TITLE
bug: Videos that i watch don't go into the history of videos

### ISSUE THREAD

**Issue by P13rlU** [revanced/revanced-patches#2445]
### Type

Bug? In-App

### Bug description

every videos that i watch does not show in history, idk why, idk how, but it seems like i did not watch them. this happens for every type of video (normal video, short, live) it doesn't show in history. 
Right now in my history there are only the videos that i watch on pc.
In the patches i don't have any spoofs

### Steps to reproduce

idk it just happened one day

### Relevant log output

```shell
.
```

### Screenshots or videos

![photo_2023-06-18_12-02-26](https://github.com/revanced/revanced-patches/assets/67976483/7d827843-aa20-4586-ae1e-513960ac0695)
![photo_2023-06-18_12-02-23](https://github.com/revanced/revanced-patches/assets/67976483/671454d1-b626-4cdb-a838-6dba878a762c)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by HypeMaxers** [comment]
Are you using an adblocker like adaway or adguard? If so whitelist s.youtube.com. If that doesn't work whitelist *.youtube.com

**Comment by HypeMaxers** [comment]
> Patch again and include `client-spoof`

Looks like they're rooted so they don't need that

**Comment by P13rlU** [comment]
> Are you using an adblocker like adaway or adguard? If so whitelist s.youtube.com. If that doesn't work whitelist *.youtube.com

YES!
Thanks man

**Comment by HypeMaxers** [comment]
> > Are you using an adblocker like adaway or adguard? If so whitelist s.youtube.com. If that doesn't work whitelist *.youtube.com
> 
> YES! Thanks man

If it worked kindly close your issue since this isn't a revanced bug
