### ISSUE TITLE
Feature Request: DeArrow integration

### ISSUE THREAD

**Issue by Fateussy** [revanced/revanced-patches#2447]
### Application

Youtube Revanced

### Issue

Clickbait and ridiculous thumbnails.

### Patch

[DeArrow](https://dearrow.ajay.app/) is a crowdsourcing browser extension for [Chrome](https://chrome.google.com/webstore/detail/dearrow-better-titles-and/enamippconapkdmgfgjchkhakpfinmaj) and [Firefox](https://addons.mozilla.org/firefox/addon/dearrow) made by the same people behind [Sponserblock](https://sponsor.ajay.app/).

### Motivation

 [DeArrow](https://dearrow.ajay.app/) allows for better titles and thumbnails without getting blasted with big arrows, ridiculous faces, and clickbait. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
#1208

**Comment by Fateussy** [comment]
DeArrow does Crowdfunding and Clickbait remover does not.

**Comment by oSumAtrIX** [comment]
The feature request is the same

**Comment by ajayyy** [comment]
It is not the same. Clickbait remover replaces thumbnails with the autogenerated ones YouTube provides

DeArrow replaces titles and thumbnails with submissions from users

**Comment by Fateussy** [comment]
Will the other project be implemented or DeArrow?

**Comment by oSumAtrIX** [comment]
@ajayyy 

The feature request is the same:

![image](https://github.com/revanced/revanced-patches/assets/13122796/3735478f-d58b-4eb0-8302-1411b9046e1a)

Add a comment under it mentioning DeArrow if you like.

**Comment by TIPWARE** [comment]
> @ajayyy
> 
> The feature request is the same:
> 
> ![image](https://user-images.githubusercontent.com/13122796/246671457-3735478f-d58b-4eb0-8302-1411b9046e1a.png)
> 
> Add a comment under it mentioning DeArrow if you like.

Could have at least added a link to the issue instead of a screenshot😊

https://github.com/revanced/revanced-patches/issues/1208
