### ISSUE TITLE
feat: change naming convention of patches

### ISSUE THREAD

**Issue by oSumAtrIX** [ReVanced/revanced-patches#2448]
## About

RE: https://github.com/revanced/revanced-patches/issues/2090#issuecomment-1596204402

## Solution

- Name patches `Like This` or `Some patch` instead of `like-this` or `some-patch`.
- This will require changing how ReVanced CLI and ReVanced Manager have to parse the patch names. 
- The documentation about patches should be updated to reflect the change of convention

**Comment by ILoveOpenSourceApplications** [comment]
Can this issue consider changes in description of some of the patches which are having inconsistencies. For example most `hide-patches` have their description starting either "hides whatever" according to the their respective patch names. But this is not followed throughout, like in the case of `hide-ads`, the description is "Removes general ads." and for `hide-player-buttons`and `hide-video-action-buttons` the descriptions are "Adds the option to hide video player previous and next buttons." and "Adds the options to hide action buttons under a video."
Then there's `enable-debugging` and it's description is "Adds debugging options." whereas `minimized-playback` description is "Enables minimized and background playback."
There are other cases as well which I won't be listing here. But if needed I can go through and list them, but I hope what I meant is clear. Do let me know whether this can be considered along with this issue or whether I should open a new one.

**Comment by oSumAtrIX** [comment]
A seperate issue should be opened for that.

**Comment by ILoveOpenSourceApplications** [comment]
Okay, will do that then.

**Comment by oSumAtrIX** [comment]
I think naming should happen without regard to where the patches are used.

Currently, `@Name` is using `names-like-this` because of regard to ReVanced CLI, but ReVanced Patches has no relation to ReVanced CLI, which is why it shouldn't be named `like-this` with the motivation to satisfy ReVanced CLI. Instead, ReVanced CLI has a relation to ReVanced Patches and thus should take the initiative to parse the CLI input to compare to the patch names.

If ReVanced CLI expects the user to input a patch name, then it can use the constrain only to accept inputs such as `names-like-this`. By that constraint, ReVanced CLI would transform `@Name`.

**Comment by PalmDevs** [comment]
> If ReVanced CLI expects the user to input a patch name, then it can use the constrain only to accept inputs such as `names-like-this`. By that constraint, ReVanced CLI would transform `@Name`.

I agree with this. It's easier to transform `This kind of name` or `This Kind Of Name` to `this-kind-of-name`, but it's not the same otherwise. Current issue with the frontend is it needs a dictionary to properly capitalize words like `vr` to `VR` (instead of `Vr`).
