### ISSUE TITLE
feat: Support of YouTube Version 17.28.35

### ISSUE THREAD

**Issue by anil-al** [revanced/revanced-patches#245]
### Type

Functionality

### Issue

This version was passed in patches, so in patching gives it the incompatiblity error.

### Feature

-

### Motivation

-

**Comment by oSumAtrIX** [comment]
Please formulate a proper issue, I don't understand you

**Comment by anil-al** [comment]
> Please formulate a proper issue, I don't understand you
Is my English that bad? :) Support for version 17.28.35 is skipped without a reason in patches, therefore, one cannot patch that version.
![Screenshot_20220728-154520_Samsung Internet](https://user-images.githubusercontent.com/101948963/181509059-f1fded00-db1a-41a7-b191-d6f5f00c0580.png)

**Comment by oSumAtrIX** [comment]
Use --experimental.

**Comment by anil-al** [comment]
> Use --experimental.

I have already used it but for the sake of other users, shouldn't that be supported as well?

**Comment by oSumAtrIX** [comment]
We target the latest version, this one has not been tested yet.

**Comment by anil-al** [comment]
> We target the latest version, this one has not been tested yet.

But this is not the latest version, after 17.28.**34**, supported version has directly skipped to 17.**29**.34. That's an minor update for bug fixes so, if 17.28.34 works fine, this can also do just fine.

**Comment by oSumAtrIX** [comment]
Before minor updates also affected patches, they have to be tested before we add it as a supported version. Use the --experimental option.

**Comment by TheJeterLP** [comment]
We can't add support for every minor version. Use --experimental or stick to the newest.
