### ISSUE TITLE
feat (youtubemusic): remove suggested version

### ISSUE THREAD

**Issue by Julius8900** [revanced/revanced-patches#2450]
### Application

YouTube Music

### Issue

The suggested version for YouTube Music.

### Patch

All the default (recommended) patches work fine with newer versions of YouTube Music. Tried it with versions 5.40+. The patch process finished without errors or warnings.

### Motivation

The recommended version is 5.39.52, which is quite old (from mid January). Because the newer versions are patched and work perfectly fine, I consider that there no longer needs to be a version constraint for the patches.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
What about `hide-get-premium`?

**Comment by Julius8900** [comment]
> What about `hide-get-premium`?

It did apply without issues.

**Comment by Julius8900** [comment]
> > What about `hide-get-premium`?
> 
> It did apply without issues.

Here is my try with version 6.06.52. Default (recommended patches) + `compact-header` patch.

![Screenshot_2023-06-19-06-15-30-508_app.revanced.manager.flutter.jpg](https://github.com/revanced/revanced-patches/assets/124190185/047148e1-0df5-4ea2-bea7-ada6aa71a68c)

![Screenshot_2023-06-19-06-16-28-227_app.revanced.manager.flutter.jpg](https://github.com/revanced/revanced-patches/assets/124190185/338e378c-b762-4cfc-ad53-0077b184990d)

It did install and work perfectly fine.
