### ISSUE TITLE
bug: Sync Pro crashes on launch after initial setup

### ISSUE THREAD

**Issue by coolyc3** [revanced/revanced-patches#2455]
### Type

Error at runtime

### Bug description

The Sync Pro patch change-oauth-client-id runs successfully. However after patching and installing, the app runs its initial setup but crashes after that.

### Steps to reproduce

1. Patch Sync Pro with change-oauth-client-id
2. Install patched app and run through initial setup
3. App will crash on launch

### Relevant log output

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Applied change-oauth-client-id
Repacking patched apk
Not compiling resources because resource patching is not required
Writing modified dex files
Finished!
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Your APK file that you patch is broken

**Comment by coolyc3** [comment]
> Your APK file that you patch is broken

I am using a completely fresh installed version from the google play store that launches. Should I be doing anything different?

**Comment by oSumAtrIX** [comment]
You need a full APK file, not a split from play store.

**Comment by droans** [comment]
How would this work for Sync Pro? There is no APK for it on APKMirror since it's a paid app.

**Comment by oSumAtrIX** [comment]
You have to source the APK yourself. Where you find it isn't really a task for ReVanced at this point.
