### ISSUE TITLE
feat(patch): Youtube

### ISSUE THREAD

**Issue by Luwis13** [revanced/revanced-patches#2459]
### Application

Youtube

### Issue

It shows that I need YouTube premium to use the "add to queue".

### Patch

Patch the add to queue feature.

### Motivation

Most of the premium features are available but sadly this new feature isn't. So I'd like to request you to patch the new "Add to Queue" premium youtube feature

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [ ] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Julius8900** [comment]
#1141
