### ISSUE TITLE
Make the premium play next in queue option available

### ISSUE THREAD

**Issue by KyleBroflowski** [revanced/revanced-patches#2460]
### Application

youtube

### Issue

One of the major features missing on the android youtube experience is the play next in queue option as in desktop.
It helps make a temporary playlist for quick usage. 

### Patch

Make the premium play next in queue option patch on youtube revanced.

### Motivation

Youtube revanced and newpipe

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Julius8900** [comment]
#1141
