### ISSUE TITLE
feat(YouTube): Patch to unlock "Play next in queue" premium feature

### ISSUE THREAD

**Issue by HeroGalak** [revanced/revanced-patches#2467]
### Application

Youtube

### Issue

Unlock premium option to add the video to queue
![Screenshot_20230622_134709_YouTube](https://github.com/revanced/revanced-patches/assets/69464248/526ecd2d-807e-4622-a11b-779d5a18df91)

### Patch

Title self explanatory

### Motivation

Make free another useful premium feature

### Acknowledgements

- [x] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [x] I have written a short but informative title.
- [x] I filled out all of the requested information in this issue properly.

**Comment by thebestnom** [comment]
I think it's a different issue because it's exist feature to unlock instead of adding a completly new feature

Also adding the ability to hide can also be great in the same issue

**Comment by Julius8900** [comment]
It's the same thing. You ask for a feature that was already asked numerous of times.
