### ISSUE TITLE
feat: Unlock Premium Features of Adobe Products

### ISSUE THREAD

**Issue by anxiouslelimo** [revanced/revanced-patches#2469]
### Application

Photoshop Express Photo Editor (https://play.google.com/store/apps/details?id=com.adobe.psmobile)
Lightroom Photo & Video Editor (https://play.google.com/store/apps/details?id=com.adobe.lrmobile)

### Issue

Unavailable premium features.

### Patch

Patch should be able to unlock non server side premium features.

### Motivation

Both these apps are one stop solution for all the photo and video editing needs in android. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by kazimmt** [comment]
#2208

**Comment by oSumAtrIX** [comment]
Open a new issue for the other app.
