### ISSUE TITLE
bug: Shorts can't be hidden/blocked

### ISSUE THREAD

**Issue by arminolat** [revanced/revanced-patches#2474]
### Type

Other

### Bug description

Hi everyone!

I've been using Revanced for some time now, but lately I can't block shorts at all. Usually I don't have shorts at all in my app, but starting about a month ago I started getting shorts in every second row of the app. I tried using the regular patches to block shorts and hide them but they don't appear to be working at all.
I'm just wondering if I may have missed some basic steps while patching the app or if this is indeed a bug so I uploaded the video of the patches I selected, the patching process, and me using the app.

Any help would be much appreciated!

### Steps to reproduce

1. Patch the app
2. Open the YouTube app and shorts appear in several rows

### Relevant log output

```shell
N/A
```

### Screenshots or videos

https://youtube.com/shorts/txgemVlgZg0?feature=share3

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by arminolat** [comment]
For whatever reason, it doesn't work on one of my phones, but does on others. I'm assuming it's a MIUI issue and not a Revanced one.

**Comment by KobeW50** [comment]
> For whatever reason, it doesn't work on one of my phones, but does on others. I'm assuming it's a MIUI issue and not a Revanced one.

You likely have outdated patches or the wrong patches. You can go to the discord if you need assistance.
