### ISSUE TITLE
bug: Yuka Premium features like offline database or search for products doesn't work

### ISSUE THREAD

**Issue by Miltora** [ReVanced/revanced-patches#2478]
### Type

Error at runtime

### Bug description

If I patch Yuka, after signing in, it shows that you're premium user, but if I try the premium features like download the offline database or search for products without scanning, it doesn't work.

### Steps to reproduce

Step 1: Patch Yuka V 3.9 and install
Step 2: Sign in
Step 3: disable and enable Offline mode

### Relevant log output

```shell
do I have to usb debug?
```

### Screenshots or videos

![Screenshot_20230623-130858](https://github.com/revanced/revanced-patches/assets/79868191/708a247b-906c-4681-ba50-dbc77dba901c)
![Screenshot_20230623-130842](https://github.com/revanced/revanced-patches/assets/79868191/6ce3f139-d45a-4c98-b4ce-b85c36ee6832)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by nik2143** [comment]
Search don't work because it is checked by server

**Comment by Miltora** [comment]
and the offline database?

**Comment by oSumAtrIX** [comment]
Closing according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#%EF%B8%8F-guidelines-for-requesting-or-contributing-patches). Thanks anyways.
