### ISSUE TITLE
feat: Shadow TikTok Following

### ISSUE THREAD

**Issue by Be2iz** [revanced/revanced-patches#2482]
### Application

TikTok

### Issue

It's an additional feature to the existing mods for anticipated users who aren't going to create a user and password in that application.

### Patch

Create a local list for keeping certain favorite accounts to follow, with an option for import and export.

### Motivation

Make yourself less exposed to social media apps.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by SodaWithoutSparkles** [comment]
Suggestion: use throwaway emails to register, or rss feed, or third-party clients

**Comment by SodaWithoutSparkles** [comment]
I am not quite into tiktok so idk of any 3rd party clients. I was thinking something like the relationship between NewPipe and YouTube, where "shadow following" as you described exist.

As for RSS feeds, you may want to take a look at the YT video linked. https://youtu.be/_7LTwnAaQ3k

Anyway, these are kinda out of topic so here is probably not a good place to discuss about rss and 3rd party tiktok clients. Welcome to the discord server tho, you can find the link to it at revanced github profile.
