### ISSUE TITLE
feat(patch): Social Blade

### ISSUE THREAD

**Issue by SinchanBanerjee-tech** [revanced/revanced-patches#2484]
### Application

How about adding "Social Blade" support in upcoming update of RVX?

### Issue

The direct integration of Social Blade with YT app via RVX, would let people get their desired information about a perticular channel or a perticular video, without digging into any complicated process.

### Patch

Social Blade is service that gives numerous statistics about a handle on various social media platforms, including YouTube. One of the most trusted and legitimate statistics that someone can find on internet.

### Motivation

I think I already wrote it in the "Issue" section.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
This is not RVX.

**Comment by SinchanBanerjee-tech** [comment]
> This is not RVX, open an issue in the correct place

They themselves gave me the link & said to submit a feat(patch). Forget the "RVX" word and please consider implementating it on ReVanced.

**Comment by oSumAtrIX** [comment]
> would let people get their desired information about a perticular channel or a perticular video, without digging into any complicated process.

There i no complicated process in visiting the social blade website for statistics.
