### ISSUE TITLE
feat: `hide-launcher-icon` patch for ReVanced GmsCore

### ISSUE THREAD

**Issue by kazimmt** [revanced/revanced-patches#2489]
### Application

app.revanced.android.gms

### Issue

Want to hide ReVanced GmsCore from Launcher icon

### Patch

Name: Hide Launcher Icon
Description: Hides the icon of ReVanced GmsCore from Launcher

Also adds a string to hide/unhide it (like vanced MicroG)

### Motivation

GmsCore is not the app we will open regularly. For signin, we can alternatively use other apps that uses ReVanced GmsCore. So it can be an option to hide launcher icon for ReVanced GmsCore.

& all os doesn't have an app hide option. So `hide-launcher-icon` patch may help to hide ReVanced GmsCore icon from Launcher

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Use a launcher that can hide icons. You can also remove it from the desktop.
