### ISSUE TITLE
feat: Unlock Premium - Photoshop Express Photo Editor 

### ISSUE THREAD

**Issue by anxiouslelimo** [ReVanced/revanced-patches#2490]
### Application

Photoshop Express Photo Editor (https://play.google.com/store/apps/details?id=com.adobe.psmobile)

### Issue

Unavailable premium features.

### Patch

Patch should be able to unlock non server side premium features.

### Motivation

Photoshop Express Photo Editor is one of the best photo editing apps for android.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Closing according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#%EF%B8%8F-guidelines-for-requesting-or-contributing-patches). Thanks anyways.
