### ISSUE TITLE
Swipe menu in full screen video

### ISSUE THREAD

**Issue by Jakenevada** [revanced/revanced-patches#2494]
### Application

Youtube:ReVanced

### Issue

Feature that includes the same functions we can do in non fullscreen mode

### Patch

Option to remove the swipe up for this menu to pop up

### Motivation

Same features as in non fullscreen mode and possibility for accidental swipe showing this menu.
![355987035_1316367052421093_1873909433021575416_n](https://github.com/revanced/revanced-patches/assets/132659424/7b666b78-b346-4e7f-a20b-977a3dcbd846)

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
#2310

**Comment by Jakenevada** [comment]
Sorry my ass cant search
