### ISSUE TITLE
Cohesiveness patch for under video/post filter option

### ISSUE THREAD

**Issue by Jakenevada** [revanced/revanced-patches#2495]
### Application

Youtube:ReVanced

### Issue

Cohesiveness fix so both of options will look the same (By that i mean that both filtering options will look like the second screenshot)

### Patch

Solution 1 : Add patch/option for ability to have the icon of sorting of screenshot 2 in video comment section.
Solution 1 : Add option in filter patch to remove those buttons entirely
![2](https://github.com/revanced/revanced-patches/assets/132659424/7482fea3-3757-4b3e-b1a7-720ac8598908)
![3](https://github.com/revanced/revanced-patches/assets/132659424/21f189f5-e904-4b57-b57a-c44196bd8f2f)

### Motivation

Improves cohesiveness.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
There is no use in this patch. The way these buttons are currently is fine.
