### ISSUE TITLE
bug: Sync for Reddit (Dev) edition not available for patching.

### ISSUE THREAD

**Issue by hempires47** [revanced/revanced-patches#2502]
### Type

Other

### Bug description

Sync for Reddit patches include options for normal Sync and Sync Pro, but NOT Sync Dev (the one I own lol)

### Steps to reproduce

Download Sync for Reddit (Dev) version
open manager
no patches available.

### Relevant log output

```shell
n/a
```

### Screenshots or videos

n/a

### Solution

the person who made this patch told me on reddit that the fix is a line of code with the dev edition also.

### Additional context

n/a

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
There is no difference between dev and pro

**Comment by hempires47** [comment]
> There is no difference between dev and pro

App wise? Yeah no difference outside of the apk being named differently and therefore not being found by the manager.

I'd rather not purchase pro while I already have the Dev version.
Here's the app version and apk name
![Screenshot_20230626-111139_Settings](https://github.com/revanced/revanced-patches/assets/48775687/ca63e331-44e3-4d8e-b8f8-bd543b875a33)

Here is manager saying I don't have sync installed.
![Screenshot_20230626-111156_ReVanced Manager](https://github.com/revanced/revanced-patches/assets/48775687/f870bdd0-cf6f-4ccb-a1d0-9695a3ed0670)

So could you please add the extra line of code or tell me how to do it myself?

**Comment by oSumAtrIX** [comment]
You can PR it to the @Compatibility annotation for the Sync patch

**Comment by hempires47** [comment]
honestly not sure how to do that i'm afraid
