### ISSUE TITLE
feat (YouTube): Ability to hide redundant text in Settings page.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [ReVanced/revanced-patches#2504]
### Feature description

In the Settings page, only 4 useful options are there (RV Settings, GmsCore Settings, RYD Settings & SB Settings). 

The remaining are just redundant text and nobody even opens them.

So, please add the ability to hide them.

If you cannot put it on priority right now, at least keep the issue open please.
![ResizedImage_2023-12-17_08-43-43_7041](https://github.com/ReVanced/revanced-patches/assets/91815107/04f76e60-c634-4edd-b8b6-de171b7b9f9e)

### Motivation

Explained in Feature Description section.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
No proper reason not to hide them. It does not obstruct anything considerably to hide.

**Comment by Aryan-Chauhan** [comment]
> No proper reason not to hide them. It does not obstruct anything considerably to hide.

User has to scroll all the way down to access useful settings.

"Useless on top, Useful on bottom".

Summarized in one line.

**Comment by oSumAtrIX** [comment]
You don't visit the settings often enough for moving your thumb once to be problematic.

**Comment by Aryan-Chauhan** [comment]
Any chance of reconsidering?

Alternatively, can I request making these settings accessible in You tab, so user doesn't have to open YT stock settings:

RV Settings
GmsCore Settings
RYD Settings
SB Settings

**Comment by oSumAtrIX** [comment]
As previously explained, you don't configure the settings enough often for this to be considered.

**Comment by Aryan-Chauhan** [comment]
I do and I'm sure there are others.

What about making important settings accessible from You tab?

**Comment by Aryan-Chauhan** [comment]
ReVanced has already removed/hid/improved various annoying stuff of stock YT app. So, why not make it even better by adding this feature?

Additionally, someone interested could make a PR.
