### ISSUE TITLE
bug: YouTube and YouTube Music app keeps buffering

### ISSUE THREAD

**Issue by kairusds** [ReVanced/revanced-patches#2505]
### Bug description

I've noticed that both the YouTube and YouTube Music android apps keep buffering a certain amount of time, and I'm not certain if it's caused by the patches or just the vanilla clients itself.

### Additional context

A quick search shows that it's also affecting other users and not just revanced so I'm really not certain if this is just an issue on Google's end.

![IMG_20231217_171003](https://github.com/ReVanced/revanced-patches/assets/32636532/1f47fc9f-d812-4198-adb3-0f4a9d32f29b)
![IMG_20231217_170945](https://github.com/ReVanced/revanced-patches/assets/32636532/4a09525a-468f-4d30-a472-d2ee10a6f9cc)

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Reopen if not an issue with upstream

**Comment by kairusds** [comment]
> But playback is still working, yes?
> 
> Try the stock the app. Google likely changed the buffer size for some or for all users.

Yes, it's working. Tested on the web, mobile webapp and stock android app, still the same but NewPipe doesn't seem to be affected.

**Comment by oSumAtrIX** [comment]
Follow this and report back 
![Screenshot_20231217-111112](https://github.com/ReVanced/revanced-patches/assets/13122796/655b139c-de6c-437f-95fd-46b67972881d)

**Comment by kairusds** [comment]
> Follow this and report back ![Screenshot_20231217-111112](https://private-user-images.githubusercontent.com/13122796/291055118-655b139c-de6c-437f-95fd-46b67972881d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4MDgyMzEsIm5iZiI6MTcwMjgwNzkzMSwicGF0aCI6Ii8xMzEyMjc5Ni8yOTEwNTUxMTgtNjU1YjEzOWMtZGU2Yy00MzdmLTk1ZmQtNDZiNjc5NzI4ODFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE3VDEwMTIxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5NTZlYzg0MGIwZmUxNTlkZTMxYzIwZTk2NWUxMmM0NTM5YmM0YWZiZTJhZWM3MjIwMjNjYTMxYTA1NTZkZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uFD-_YXnCSvQj0lxOUebK5rTY9K0fIWsVjd7sjWwrro)

I have already done that and it's still the same result. And as I said, NewPipe doesn't seem to be affected at the very least, I'm not sure why.

**Comment by oSumAtrIX** [comment]
@LisoUseInAIKyrios is correct, I misunderstood the comment
