### ISSUE TITLE
bug: Twitch revanced - ads showing on subscribed channels 

### ISSUE THREAD

**Issue by LetsPlayNintendoITA2023** [revanced/revanced-patches#2509]
### Type

Other

### Bug description

Ads show up on channels i am subscribed to

### Steps to reproduce

Open app
Join a channel you are subscribed to
Wait for an ad to show up

### Relevant log output

```shell
There is no log as there is no error
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Reproduction steps are insufficient.

**Comment by LetsPlayNintendoITA2023** [comment]
I intalled the patches reccomanded to me by the launcher over the latest version. Went to a channel i am not subbed to. No ads. Went to a chan i am subbed to. I saw ads. Not much else to reproduce

**Comment by oSumAtrIX** [comment]
Open a proper issue that shows images. I can't help you with "I just installed and doesn't work".

**Comment by LetsPlayNintendoITA2023** [comment]
What images do you want me to post?  A channel showing ads ? How would that help If that's what normally happens

**Comment by oSumAtrIX** [comment]
If an ad shows up, the proxy was not able to skip it for you. Not much that can be done here.
