### ISSUE TITLE
bug: twitch revamped channels with ads give network error. Subbed ones play ads

### ISSUE THREAD

**Issue by LetsPlayNintendoITA2023** [revanced/revanced-patches#2510]
### Type

Error at runtime

### Bug description

On channel that have ads they don't play and I get network error
Ads show up on channels i am subscribed to

### Steps to reproduce

Patch latest twitch with default patches
Launch app
Login
Open a channel you are not subbed to. Ads don't play and get a network error
Open a channel you are subbed to. Ads play instead of being blocked by the sub.

### Relevant log output

```shell
Shown in video
```

### Screenshots or videos

https://github.com/revanced/revanced-patches/assets/137847553/b5db6738-7668-4edd-ba6a-e4593a5277cb

### Acknowledgements

- [x] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [x] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
check if the proxy used in the settings is live

**Comment by LetsPlayNintendoITA2023** [comment]
> check if the proxy used in the settings is live. And you misspelled ReVanced.

**Comment by LetsPlayNintendoITA2023** [comment]
Ttv lol it doesn't give error the purple one it says it's not available. Then there is disabled.

**Comment by oSumAtrIX** [comment]
Then ttv lol probably is down, reopen in couple days when not
