### ISSUE TITLE
Patch to disable Google Play Store update notifications for patched apps.

### ISSUE THREAD

**Issue by randomcloudswings** [ReVanced/revanced-patches#2510]
### Feature description

A way to disable Google Play Store update notifications for previously patched apps.

### Motivation

Patched apps show on update app list of Play Store. And when app is updated it shows app update failed and the notification just stays there on the list.

Any way to prevent play Store to ignore the updates of patched apps.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
This is a feature in Android
