### ISSUE TITLE
feat: view Instagram content inline Twitter timeline

### ISSUE THREAD

**Issue by Be2iz** [revanced/revanced-patches#2517]
### Application

Twitter

### Issue

Instagram content require user to leave Twitter app.

### Patch

In Twitter would be great to utilize iganony.io within it.

### Motivation

Improve UI/UX by integration of iganony.io service.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
https://github.com/revanced/revanced-patches/issues/1652

**Comment by bennett-sh** [comment]
I think this shouldn't be closed in favor of #1652 because the patch is for the Twitter application and not for Instagram.

**Comment by oSumAtrIX** [comment]
Twitter is Twitter, and Instagram is Instagram. This is not a merge fest. If you want to see, Instagram content use the Instagram app.
