### ISSUE TITLE
feat: Various additions to the YouTube Android Interface if possible

### ISSUE THREAD

**Issue by SunSea88** [ReVanced/revanced-patches#2518]
### Feature description

Hello,

Do you think that it's possible to add these following new options for enhanced comfort on YouTube Android please ?

1 Expand automatically the broadcast date, the video description, the long comments under video and the long community posts like this script on YouTube PC
-> greasyfork.org/fr/scripts/446954-youtube-expand-description-and-long-comments-show-all-the-replies

2 Show again the Username in comments, community posts... instead of User ID Handle with @ like this script on YouTube PC
-> greasyfork.org/fr/scripts/468740-restore-youtube-username-from-handle-to-custom

3 Hide the Most Replayed section in the videos like with uBlockOrigin on YouTube PC
-> droidwin.com/how-to-disable-youtube-most-replayed-feature

4 Hide the videos that are in our private or public playlists in the YouTube Homepage like this script on YouTube PC
-> greasyfork.org/fr/scripts/474300-hide-videos-that-are-in-playlist

5 Review all videos, lives, premieres, shorts from a Channel in one place like when everything was in the "Videos" tab only ; Very useful to know what has been posted online in order like this script on YouTube PC
-> greasyfork.org/fr/scripts/454215-bring-back-youtube-channel-playlists

6 Put the Timestamps back in the livechat like on YouTube PC

I don't know if these ideas has already been mentioned here before, but if so I apologize for that.

Thank you in advance

### Motivation

Improve a little more the comfort for everyone on YouTube Android 😃

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Please separate this issue into a feature request per issue.
