### ISSUE TITLE
bug: Patched Infinity for Reddit Trending page broken

### ISSUE THREAD

**Issue by the9655a** [ReVanced/revanced-patches#2520]
### Bug description

Latest version of Infinity for Reddit patched (v6.5.6) has the trending page stuck on old trending titles and not displaying current trending content from reddit.

**Steps to reproduce:**
(or simply follow the steps in [this guide](https://docs.google.com/document/d/1wHvqQwCYdJrQg4BKlGIVDLksPN0KpOnJWniT6PbZSrI/))
1. Download the latest version of revanced manager.
2. Download the latest version of Infinity for Reddit from APKMirror (v6.5.6)
3. Select all the patches available (spoof client and remove subscription page)
4. Install and login to your reddit account
5. Check the trending page and it should look like this, which is trending content from months ago:

![image](https://github.com/ReVanced/revanced-patches/assets/149513282/86a84b5e-c841-4498-86da-75017d8df3e2)

### Additional context

This issue has been going on for around 2-3 months now. After switching from patched 6.1.1 to the latest version 6.5.6 to see if the issue persisted on newer versions, the problem is still there. So currently all you see is trending headlines from 2-3 months ago. It hasn't changed since. There also doesn't seem to be any issues relating to this on the official infinity GitHub repo, so I assume it has to be a revanced specific issue, although I am happy to open an issue there if needed.

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Check on the unpatched app

**Comment by the9655a** [comment]
I tried unpatched 6.1.1, thats the newest version without the subscription page. The issue is still there, but it could be because its old. It's not ideal but should I try on the newest version and pay?

**Comment by oSumAtrIX** [comment]
Sounds like an issue with Infinity, reopen unless not
