### ISSUE TITLE
bug: "Settings" patch not working on TikTok (com.zhiliaoapp.musically)

### ISSUE THREAD

**Issue by TRINCETT** [revanced/revanced-patches#2520]
### Type

Error while patching

### Bug description

At the time of patching tiktok the app cannot implement the "Settings" patch and an error appears that says 
(hardcoded offset change.
Failed to apply settings: 'settings' did not succeed)

So, Without the settings patch you can't use the downloads patch.

I tried it in the tiktok versions:

- 30.2.1
- 30.1.3
- 30.0.3

Also i'm using the lastest manager version: 1.3.6

(Also, if you try to patch the 30.0.3 version, sometimes the app can crash)

### Steps to reproduce

Step One: Download one of the versions mentioned above

Step two: select the Downloads and Show Seekbar patches (these are the ones I was trying to install, although selecting the recommended patches didn't work either)

Step three: Patch and see how it doesn't work 😭

### Relevant log output

```shell
Same as the screenshot.
```

### Screenshots or videos

![Screenshot_20230627_202733](https://github.com/revanced/revanced-patches/assets/93570862/bca5e3d2-d3aa-4da6-8bd5-661e4fdfe4c9)

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
#2426
