### ISSUE TITLE
bug(YouTube - Spoof app version): Shorts do not play and shows "video not available"

### ISSUE THREAD

**Issue by LisoUseInAIKyrios** [ReVanced/revanced-patches#2521]
### Bug description

When spoofing to 16.x or 17.x versions, the first Short opened can fail to load and shows an error message.  Swiping to the next Short plays correctly, and swiping back to the first Short also works correctly.  Sometimes the Shorts player can also show the Short halfway off screen.

If this issue shows up, all Shorts opened in the future will have the same issue and restarting the app/device does not fix it.

Clearing the app data does temporarily fix it, but eventually the problem returns.

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
I don't think it's worth looking into the issue. Spoofing the app version comes with its problems naturally and once this version shuts down in the API the issue would also be irrelevant.
