### ISSUE TITLE
feat: Add temporary playlist 

### ISSUE THREAD

**Issue by Tucker6742** [revanced/revanced-patches#2521]
### Application

Youtube

### Issue

When users have multiple video that they are interested in now but might be not at a later time, there isn't a choice for making a temporary playlist to group all those video together. 

### Patch

Make a temporary playlist choice that could be similar to TV queue playlist when you cast to TV, it will stay there as long as you created the playlist and keep the app open. When you close the app it will be removed just like when you disconnect from TV. You also has a choice to make temporary playlist as a new playlist for your account.

### Motivation

There are "Watch later playlist" available now but it's still very limited in functionality. You can't remove all video from that playlist all at once, and some video that you add there may not be interesting to you at a later time so you have to manually remove it one by one
Adding temporary playlist option can make an user keep a list of video that they would like to watch for now, and if they decide to close it then they are probably not interested in those video anymore so you can remove that playlist.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
#1735
