### ISSUE TITLE
feat: Remove compatible version for Meme Generator (com.zombodroid.MemeGenerator)

### ISSUE THREAD

**Issue by VaiCaDep0893** [revanced/revanced-patches#2522]
### Application

Meme Generator (com.zombodroid.MemeGenerator)

### Issue

Remove compatible version for Meme Generator

### Patch

Unlock pro should work on all versions. I applied the patch on the latest version and it works

### Motivation

Since it works on the latest version, the compatible versions should be removed so people don't have to use an old version anymore.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
This isn't really a patch request, you can patch any version, the compatibility constraint is just a suggestion.

**Comment by VaiCaDep0893** [comment]
I don't even know coding
