### ISSUE TITLE
feat: GmsCore support

### ISSUE THREAD

**Issue by yonggamer** [ReVanced/revanced-patches#2523]
### Feature description

open Google Chrome if not instaled

### Motivation

unclear if shutdown immediately after open the app without a massage

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by KobeW50** [comment]
This already exists for YouTube. For YT Music this hasn't existed even for Vanced MicroG Support

**Comment by yonggamer** [comment]
I think v3.1.0 lost it

**Comment by KobeW50** [comment]
It works for me whether the vendor is set to Vanced or ReVanced. You can submit a bug report if it doesn't work.

**Comment by yonggamer** [comment]
app crash for me on
18.32.39
18.38.44
18.45.43

**Comment by KobeW50** [comment]
Open a new issue, with a detailed bug report.

**Comment by yonggamer** [comment]
works now on Samsung Internet Browser
(com.sec.android.app.sbrowser)
not Google Chrome(com.android.chrome)
