### ISSUE TITLE
YouTube : pause playback when locking screen, when background playbaxk is on

### ISSUE THREAD

**Issue by Matszwe02** [ReVanced/revanced-patches#2524]
### Feature description

I want to have a background playback, but I want to pause my videos by locking my phone screen. Add an option to pause playback when locking screen, to manually resume it when needed 

### Motivation

I went to quickly stop playing my video with just hitting the power button 

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [ ] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
This is not a motivation
