### ISSUE TITLE
Upgrade trakt.tv patch for latest version 1.2.1

### ISSUE THREAD

**Issue by adripo** [ReVanced/revanced-patches#2525]
### Feature description

Upgrade 'unlock pro' patch to work with latest version 1.2.1

### Motivation

New features added in the app

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by adripo** [comment]
I tried to use the patch for v1.1.1 but login is not working after patch.

**Comment by oSumAtrIX** [comment]
Closing according to contribution guidelines

**Comment by adripo** [comment]
Hi @oSumAtrIX, may I know what is the problem with my request please?

**Comment by lluni** [comment]
Hey, would it be acceptable to request changing the patch / adding a new one to block the ads in the app? Those were previously a byproduct of the `Unlock pro` patch, but according to the guidelines, a new dedicated `Block ads` patch should be allowed.
