### ISSUE TITLE
bug: Sync unable to open Imgur album URLs

### ISSUE THREAD

**Issue by Murabitos** [ReVanced/revanced-patches#2527]
### Bug description

Sync is unable to open Imgur albums but is able to open non-albums. I spoke with taku in Discord and he confirmed it is an issue.

After 10 seconds or so, Sync stops trying to open it and no matter what I've moved on to in the app it forces open an internal browser with the URL.

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
This is a bug caused by Sync not ReVanced

**Comment by raf-42** [comment]
> This is a bug caused by Sync not ReVanced

Correct, but given that Sync is sadly not being updated anymore, is there a chance it might be fixed via a ReVanced patch? Akin to how y'all are kindly adding in a patch for the /s/ links issues (#2650). Or might this fare better as a feature request?

Regardless, the work being done here is immensely appreciated.

**Comment by PaidThaFossToBeDaBoss** [comment]
> ### Bug description
> Sync is unable to open Imgur albums but is able to open non-albums. I spoke with taku in Discord and he confirmed it is an issue.
> 
> After 10 seconds or so, Sync stops trying to open it and no matter what I've moved on to in the app it forces open an internal browser with the URL.
> 
> ### Error logs
> _No response_
> 
> ### Solution
> _No response_
> 
> ### Additional context
> _No response_
> 
> ### Acknowledgements
> * [x]  This issue is not a duplicate of an existing bug report.
> * [x]  I have chosen an appropriate title.
> * [x]  All requested information has been provided properly.

For the time being you can download imgur viewer form the [Playstore](https://play.google.com/store/apps/details?id=com.ensoft.imgurviewer)
Set up sync so it doesn't open imgur album links and the this app handle them. The app integrates with Sync. Here's a [screen recording](https://streamable.com/e73ymj) of how it ends up looking like.
