### ISSUE TITLE
bug: Sync unable to open redgifs links that are images

### ISSUE THREAD

**Issue by Murabitos** [ReVanced/revanced-patches#2528]
### Bug description

Sync is unable to open redgifs that are images. It is able to open redgifs that are actually videos with no issues.

When trying to open redgifs that are images, it says "ERROR CONNECTING TO REDGIFS".

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
This is a bug by Sync and caused by it being discontinued not ReVanced
