### ISSUE TITLE
feat: Is s.o. on it to re-enable the function to install apps via Total Commander?

### ISSUE THREAD

**Issue by DigitArier** [ReVanced/revanced-patches#2530]
### Feature description

Hi everyone, 
I was wondering if anyone is looking into being able to install apps again via Total Commander.  Google imposed strange restrictions that the developer had to remove this feature from the app completely.  Since then I've been using a version that was still able to do this, but I changed the signature via LuckyPatcher so that Total Commander is no longer suggested for an update.  Of course, the constant development passes me by.  Apart from any security gaps that may be closed.

([com.ghisler.android.TotalCommander](https://play.google.com/store/apps/details?id=com.ghisler.android.TotalCommander))

Thanks for feedback 

### Motivation

- that's one of the main features
- it's s.th. that what a file explorer should be able to do I guess

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
I dont know what you mean. Installing apps is a feature of Android.

**Comment by DigitArier** [comment]
> @DigitArier use full standalone installer here or use it's plugin https://www.ghisler.ch/board/viewtopic.php?t=76644

Well, i've missed that one I guess. thank you very much @cyberboh 🤩
