### ISSUE TITLE
feat: TikTok feed filter additions: Hide Sponsored & Hide Paid Partnership

### ISSUE THREAD

**Issue by Murabitos** [ReVanced/revanced-patches#2533]
### Feature description

The current "Remove feed ads" only seems to remove one type of visible ads. The "Sponsored" posts and "Paid Partnership" posts are a nuisance and the user experience would be better without them.
![Screenshot_20231221_145033_TikTok](https://github.com/ReVanced/revanced-patches/assets/1791523/c7bb0f3d-022b-4c43-832b-b48a2120b527)
![Screenshot_20231221_145726_TikTok](https://github.com/ReVanced/revanced-patches/assets/1791523/d8ad2818-e41b-424a-ab6a-e5e323fc559c)

### Motivation

It should be added because they are, in my eyes, types of ads that are currently not blockable. The user experience will be enhanced with their removal. 

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Please open a bug report instead.
