### ISSUE TITLE
bug: TikTok filter feed "Remove feed ads" does not remove "Sponsored" and "Paid Partnership" posts

### ISSUE THREAD

**Issue by Murabitos** [ReVanced/revanced-patches#2534]
### Bug description

The current "Remove feed ads" only seems to remove one type of visible ads. The "Sponsored" posts and "Paid Partnership" posts are a nuisance and the user experience would be better without them.
![Screenshot_20231221_145033_TikTok](https://github.com/ReVanced/revanced-patches/assets/1791523/4006fee2-9867-45aa-8973-60fcb0fcd494)
![Screenshot_20231221_145726_TikTok](https://github.com/ReVanced/revanced-patches/assets/1791523/6d3baf8a-7cb9-46eb-9146-b1908ab14dee)

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by Murabitos** [comment]
Upon further review, it doesn't seem to be blocking any types of ads altogether. I am seeing the ones that sometimes pop up when opening the app as well.

**Comment by Murabitos** [comment]
> > Upon further review, it doesn't seem to be blocking any types of ads altogether. I am seeing the ones that sometimes pop up when opening the app as well.
> 
> any screenshots of this ads?

![Screenshot_20231223_170508_TikTok](https://github.com/ReVanced/revanced-patches/assets/1791523/c04ce1fe-462c-43b7-9615-6ed5e5cb351b)

**Comment by Murabitos** [comment]
> > > > Upon further review, it doesn't seem to be blocking any types of ads altogether. I am seeing the ones that sometimes pop up when opening the app as well.
> > > 
> > > 
> > > any screenshots of this ads?
> > 
> > 
> > ![Screenshot_20231223_170508_TikTok](https://private-user-images.githubusercontent.com/1791523/292652458-c04ce1fe-462c-43b7-9615-6ed5e5cb351b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzODk5NDgsIm5iZiI6MTcwMzM4OTY0OCwicGF0aCI6Ii8xNzkxNTIzLzI5MjY1MjQ1OC1jMDRjZTFmZS00NjJjLTQzYjctOTYxNS02ZWQ1ZTVjYjM1MWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjRUMDM0NzI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGE3ODAyNmU0MDVlYTQxMjZhNjM3MDk0NjFlNDUxYWY3MTgwNjdlZjZlMTI0YjIzZTZhMTdlODQ1ZDAzYzJmMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.sBP6nS2W3eFHHPGzmH_BNgnNjfsULeDANUMgt83Yb-U)
> 
> which tiktok pkg name is this? `com.ss.android.ugc.trill` or `com.zhiliaoapp.musically`?

I'm not sure where to find that. I used the PC patcher and it gave me "PATCHED_TikTok.apk".

**Comment by oSumAtrIX** [comment]
You are using unofficial tools. Reopen using official tools such as ReVanced CLI or ReVanced Manager.

**Comment by Murabitos** [comment]
I'm not sure I understand. I was under the impression that I patched it with ReVanced CLI. What should I do at this point?

**Comment by oSumAtrIX** [comment]
You can use [ReVanced CLI](https://github.com/ReVanced/revanced-cli) or [ReVanced Manager](https://revanced.app)

**Comment by oSumAtrIX** [comment]
Please be specific and also explain what you mean by "especially"

**Comment by oSumAtrIX** [comment]
Please open a new issue

**Comment by CoolCooler0** [comment]
I always get an ad when opening the app. Patched with the Revanced Manager.

**Comment by CoolCooler0** [comment]
![Screenshot_20240120_091842_TikTok](https://github.com/ReVanced/revanced-patches/assets/136742821/eaeafb6a-852c-4c5d-9c53-73e16eb0d815)
