### ISSUE TITLE
feat (YouTube): Remove "[Channel name] viewers also watch this channel" description

### ISSUE THREAD

**Issue by risbi0** [ReVanced/revanced-patches#2535]
### Feature description

An example of what it looks like, from this SO post: https://stackoverflow.com/questions/57122898/some-viewers-also-watch-this-youtube-channel

I think this is just unnecessary information that wastes screen space. This can be a layout toggle if you argue otherwise, as long as I can hide it in my end.

### Motivation

- To remove unnecessary information
- To avoid wasting screen space

### Acknowledgements

- [ ] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by KobeW50** [comment]
inotia00 recently released a patch for this on his fork.

Here is [his integration of the feature](https://github.com/inotia00/revanced-integrations/commit/afd7ab663316adc39c491b2d270386ce91db78f3) in case it helps.

**Comment by oSumAtrIX** [comment]
https://github.com/ReVanced/revanced-patches/issues/6
