### ISSUE TITLE
bug (YouTube): Watch History missing on tablet

### ISSUE THREAD

**Issue by j1elo** [ReVanced/revanced-patches#2536]
### Bug description

The History section of the "You" page does not show up on the tablet layout of the app. However, it does show up on the phone.

Steps to reproduce:

* Install patched YouTube.
* Login (with MicroG).
* On the bottop of the app, tap "You".
* The user page shows up, with buttons such as "Switch account", "Google Account", and "Turn on Incognito". Below, "Playlists" shows up too, with the account's playlists. **On the phone, "History" also shows up with a list of the watched videos. On the tablet, "History" doesn't show up at all.**

More details:

* Tested with a clean install (no settings changed from defaults) on both tablet and phone.
* The network and the devices don't have any kind of ad-blocker such as AdGuard.
* DNS servers are also not blocking anything, they are the default from the ISP.
* In the Google account, YouTube History is enabled, and under "Subsettings", "Include the YouTube videos you watch" is enabled.

Thanks a lot for this app and for all the effort it takes to make it... I only hope to help make it a tiny bit better.

Merry Christmas!

### Error logs

```shell
$ logcat | grep -E 'AndroidRuntime|YouTube|Gms'


Nothing relevant seems to appear in the log.
```

### Additional context

Version info:

* YouTube v18.45.43, patched on a PC with `revanced-cli`.
* Vanced MicroG v0.2.24.220220
* revanced-cli v4.3.0
* revanced-integrations v1.0.0
* revanced-patches v3.1.0

Command used for patching:

```sh
java -jar revanced-cli-*.jar patch \
    --patch-bundle revanced-patches-*.jar \
    --merge revanced-integrations-*.apk \
    --purge \
    com.google.android.youtube_*.apk
```

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Follow this and report back:
![image](https://github.com/ReVanced/revanced-patches/assets/13122796/8d55b74d-0191-4c78-8f0c-11045298c99e)

**Comment by j1elo** [comment]
Update: I've seen some reports of vanilla YouTube app users, complaining about the same. The "You" screen that I have, looks exactly like this ([source](https://www.reddit.com/r/iPadPro/comments/17fm95z/where_is_the_history_tab_in_the_new_youtube_app/)):

![no-history-tab](https://github.com/ReVanced/revanced-patches/assets/1824582/d846d84d-7135-4550-8ae2-3fe86f5fbecc)

So... is this a choice made by Google itself? In that case, is it possible to override it with ReVanced and bring back the "History" pane for tablet screens?

**Comment by oSumAtrIX** [comment]
In this case it is not an issue by ReVanced.

**Comment by j1elo** [comment]
FIXED: This issue doesn't happen if "Enable tablet layout" is enabled.

So for anyone that maybe happens to have the same issue and finds this:

you need to go to Settings > ReVanced > Layout, and turn "Enable tablet layout" ON.

**Comment by j1elo** [comment]
Checked. And no, excluding "Enable tablet layout" does not fix this issue nor https://github.com/ReVanced/revanced-patches/issues/2538 or https://github.com/ReVanced/revanced-patches/issues/2537.

All 3 happen if "Enable tablet layout" patch is not included, or not enabled.

**Comment by oSumAtrIX** [comment]
Figure out which patch causes it and report back:

![image](https://github.com/ReVanced/revanced-patches/assets/13122796/c8a6bf82-3dee-4c21-a784-f6e3ae5f2c71)
