### ISSUE TITLE
bug: Trakt `unlock pro` not working with version 1.1.1

### ISSUE THREAD

**Issue by adripo** [revanced/revanced-patches#2540]
### Type

Other

### Bug description

`unlock pro` patch not working with trakt version 1.1.1
All the VIP banners and features are not unlocked anymore. 

### Steps to reproduce

- Apply patch
- install patched app
- patch not applied

### Relevant log output

```shell
-
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by johnconner122** [comment]
Patch app
Sign in
Close app completely
Open and you should have pro unlocked.
