### ISSUE TITLE
Youtube Music patch app crash

### ISSUE THREAD

**Issue by JugaramZa** [revanced/revanced-patches#2541]
### Type

Other

### Bug description

After youtube apk patched and installed on opening the app crashes

### Steps to reproduce

Same problem on youtube app

### Relevant log output

```shell
can't provide log as the crash itself not provided the log
```

### Screenshots or videos

https://github.com/revanced/revanced-patches/assets/138093550/4397ae6b-c089-489c-8401-8b177ca6a583

### Solution

Device: Samsung galaxy F23 5G

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [ ] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Invalid reproduction steps.

**Comment by JugaramZa** [comment]
wow

**Comment by KobeW50** [comment]
> wow

You may not have vanced microh installed.

**Comment by JugaramZa** [comment]
> > wow
> 
> You may not have vanced microg installed.

can you share download link pls

**Comment by KobeW50** [comment]
> > > wow
> > 
> > You may not have vanced microg installed.
> 
> can you share download link pls

https://github.com/TeamVanced/VancedMicroG/releases/tag/v0.2.24.220220-220220001

**Comment by JugaramZa** [comment]
> > > > wow
> > > 
> > > 
> > > You may not have vanced microg installed.
> > 
> > 
> > can you share download link pls
> 
> https://github.com/TeamVanced/VancedMicroG/releases/tag/v0.2.24.220220-220220001

thanks a lot
