### ISSUE TITLE
Can't patch multiple Reddit apps? 

### ISSUE THREAD

**Issue by mvevitsis** [revanced/revanced-patches#2543]
### Type

Other

### Bug description

If they are looking for the same txt file but require different callback urls, how are we supposed to patch multiple Reddit apps? 

### Steps to reproduce

Patch more than one Reddit client

### Relevant log output

```shell
N/a
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Firstival, why are you using multiple Reddit clients. Second, you can do that by using multiple client ids. One for each client
