### ISSUE TITLE
feat:  patch for Logging out in Youtube 

### ISSUE THREAD

**Issue by cvhere** [revanced/revanced-patches#2544]
### Application

Youtube

### Issue

Youtube by default uses google account which is already used in different application. There is neither  logout option nor  to skip the account.

### Patch

There are two options. Whatever is easier & simple to implement

1).  Provide logout a button to log out user account.
2). Provide a specific to not to use any google accounts.

### Motivation

I don't want Youtube to use my google account. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by reisxd** [comment]
You can log out from your device's settings. Go to the Accounts section and find your email with the Vanced MicroG logo.

**Comment by cvhere** [comment]
I am installing patched version as Root and I have not installed Vanced MicroG.  I am using android vanillla version with mircroG. I don't want patched outube to use google credentials from Microg accounts.
