### ISSUE TITLE
feat: Sponsorblock (non-music) to work on audio tracks in music application

### ISSUE THREAD

**Issue by ColeSpringer** [ReVanced/revanced-patches#2544]
### Feature description

Currently sponsorblock only works with videos in the youtube music app. However, the audio (song) tracks on YouTube can also have non-music sections. In the browser, on both youtube.com and music.youtube.com, marked segments are skipped. Having this feature on the app for songs (video already works) would be appreciated.

### Motivation

Adds functionality already present in browser version of sponsorblock that improves the user experience.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Open a new issue that clarifies that. The original issue nowhere mentions what you really want

**Comment by oSumAtrIX** [comment]
This is effectively a feature request to add SponsorBlock to YouTube Music. Please open an issue that simply states that

**Comment by YT-Advanced** [comment]
> Hmm you're right. I guess what I was seeing was just some weird functionality in the app that skips forward in the video portion when you switch from song to video and that just so happened to be the portion that was marked as non-music for that video. So that just made me think sponsorblock was implemented.

Maybe you are using Revanced Extended ?
