### ISSUE TITLE
bug: Patching aborted because of map initialized fingerprint?

### ISSUE THREAD

**Issue by aritbhat** [revanced/revanced-patches#2545]
### Type

Error while patching

### Bug description

Steps followed:
Uninstalled updates
Downloaded recommended version 18.19.35
Installed said update 
Tried patching recommended patches
Bug found:
![Screenshot_20230701_113433](https://github.com/revanced/revanced-patches/assets/27761968/9e7d42bc-03a6-498d-b909-c4abcc57f43f)

### Steps to reproduce

Please follow description steps

### Relevant log output

```shell
Unfortunately unable to copy logs so attached ss
```

### Screenshots or videos

![Screenshot_20230701_113433](https://github.com/revanced/revanced-patches/assets/27761968/982d6070-b1ba-41f1-b1ab-c3829c83a409)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by aritbhat** [comment]
Logs

Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
An error occurred! Aborted
Error:
app.revanced.patcher.patch.PatchResultError: Map already initialized
	at app.revanced.patcher.fingerprint.method.impl.MethodFingerprint$Companion.initializeFingerprintResolutionLookupMaps$revanced_patcher(MethodFingerprint.kt:102)
	at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:348)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-20(MainActivity.kt:326)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$Rd-IpIH_jmxD15EWmBEFM-jtGsk(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda13.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
![Screenshot_20230701_114131](https://github.com/revanced/revanced-patches/assets/27761968/fdb10395-e79a-4f20-821a-a0b281d94259)
![Screenshot_20230701_114144](https://github.com/revanced/revanced-patches/assets/27761968/180df6dc-ccdd-4e0d-b190-c5d1480fbc30)

**Comment by Mohamed-Aziz-Mhadhbi** [comment]
It appears that the error is occurring within the MainActivity class. It could be related to the integration of the patching library or some custom code specific to your application.

Here are some general steps you can try to resolve the issue:

1. Ensure that you have the latest version of Flutter and all its dependencies installed. You can use the flutter upgrade command to update Flutter to the latest stable version.

2. Double-check that you have followed the correct setup instructions for integrating the patching library into your Flutter project. Make sure you have added the necessary dependencies and configurations according to the library's documentation.

3. Verify that you are using compatible versions of the patching library and other related dependencies. Incompatibilities between different libraries or versions can sometimes lead to errors.

**Comment by r-ook** [comment]
@LisoUseInAIKyrios Thank you, you saved all my hair from being pulled out.  Now as a separate issue I just need to figure out how to overcome the "package not installed due to conflict with an existing package" error.

**Comment by r-ook** [comment]
> Uninstall the existing target app, then manager can probably install the patched app correctly.

That's exactly what I tried and it worked.  Thank you for replying so fast anyways!

**Comment by oSumAtrIX** [comment]
This is a ReVanced Manager issue. Has to update

**Comment by aritbhat3** [comment]
That worked, thanks all for this prompt solution.

**Comment by maozdemir** [comment]
> It appears that the error is occurring within the MainActivity class. It could be related to the integration of the patching library or some custom code specific to your application.
> 
> Here are some general steps you can try to resolve the issue:
> 
> 1. Ensure that you have the latest version of Flutter and all its dependencies installed. You can use the flutter upgrade command to update Flutter to the latest stable version.
> 2. Double-check that you have followed the correct setup instructions for integrating the patching library into your Flutter project. Make sure you have added the necessary dependencies and configurations according to the library's documentation.
> 3. Verify that you are using compatible versions of the patching library and other related dependencies. Incompatibilities between different libraries or versions can sometimes lead to errors.

please don't bring chatgpt into this.
