### ISSUE TITLE
feat(Bluecoins): Unlock premium

### ISSUE THREAD

**Issue by OmarNamis** [ReVanced/revanced-patches#2546]
### Application
**Name:** Bluecoins Finance & Budget
**Description:** App for expense tracking, budget and money management.
**Link:** [Google Play](https://play.google.com/store/apps/details?id=com.rammigsoftware.bluecoins&hl=en&gl=US)

### Patch
- Unlock premium features.

### Motivation

Unlocking premium features to allow using them without making a purchase.
Premium is unlocked by a simple in-app purchase, so I think it should be easy to patch.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by johnconner122** [comment]
Not possible due to [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#%EF%B8%8F-guidelines-for-requesting-or-contributing-patches).
