### ISSUE TITLE
bug(YouTube): suggested videos endscreen shows up even when toggled off

### ISSUE THREAD

**Issue by NBruderman** [ReVanced/revanced-patches#2547]
### Bug description

It the last few days, I noticed that the suggested vidoes endscreen began to appear again, although it's been toggled off.

To produce:
Enter a video, go to few seconds before the end and let it play. The endscreen will show up, even when toggled off in settings.

Happens on the latest patches with Youtube version 18.45.43, with the default patch list applied.

![Screenshot_20231227-215445](https://github.com/ReVanced/revanced-patches/assets/6445601/f050fe46-bde3-4e6c-83bc-71ac43336880)

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
I am unable to reproduce. Leaving open for anyone else to reproduce

**Comment by NBruderman** [comment]
> I am unable to reproduce. Leaving open for anyone else to reproduce

The exact conditions I got it with are:
1. Non-spoofed youtube
2. No sponsorblock segment at the end of the video
3. You need to go to few seconds before the end of the video (around 10), and let it play until the end.

If you go straight to the end, or a sponsorblock segment is present, the issue won't show up.

**Comment by oSumAtrIX** [comment]
Can reproduce going back around 10 seconds.
