### ISSUE TITLE
bug: Sponsorblock not turning off from settings page

### ISSUE THREAD

**Issue by decipher3114** [revanced/revanced-patches#255]
### Type

Other

### Bug description

Sponsorblock can't be turned off from settings page. Fix it plz

### Steps to reproduce

Turn off Sponsorblock.
Go back
enter Sponsorblock again.
It turns back on.

### Relevant log output

```shell
<No logs>
```

### Solution

Fix it XD

**Comment by TheJeterLP** [comment]
Fixed in new integrations build. Will be ready in a few minutes
