### ISSUE TITLE
bug: when trying to reply to someone, the reply box keeps closing and opening

### ISSUE THREAD

**Issue by xXRealXxx** [revanced/revanced-patches#2552]
### Type

Error at runtime

### Bug description

When I try to reply to someone, Revanced glitches out and the reply box keeps opening and closing like if my sensor was broken (it's not). This makes replying impossible. This only happens if I try to reply to another, specific reply, where the @username is in the reply by default. 
This doesn't happen on the stock Youtube app version 18.19.35.

### Steps to reproduce

- Open the reply section of a comment (short or regular video, doesn't matter)
- Try to reply to a specific user, not the original comment. 
- See the bug for yourself. 

### Relevant log output

```shell
No crash
```

### Screenshots or videos

https://github.com/revanced/revanced-patches/assets/79064982/5fd0d905-445f-4491-b52c-9f594d1c3719

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by johnconner122** [comment]
This happened to me while `spoof-app-version` was enabled, try turning it off.

**Comment by xXRealXxx** [comment]
> This happened to me while `spoof-app-version` was enabled, try turning it off.

For some reason, without doing anything, this bug stopped happening, even though it happened non stop for like a month now. At first, changing my keyboard didn't fix it, but after running the logcat command in Termux, the issue stopped happening. Not sure why this happened though, but now I can't test your fix :/

**Comment by xXRealXxx** [comment]
Deleting app data fixed this issue (it started happening again)
