### ISSUE TITLE
feat(YouTube) : Expand automatically the broadcast date, the video description, the long comments under video and the long community posts

### ISSUE THREAD

**Issue by SunSea88** [ReVanced/revanced-patches#2555]
### Feature description

Expand automatically the broadcast date, the video description, the long comments under video and the long community posts like this script on YouTube PC
-> greasyfork.org/fr/scripts/446954-youtube-expand-description-and-long-comments-show-all-the-replies

### Motivation

Improve a little more the comfort for everyone on YouTube Android 😃

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Not all posts are interesting so the additional gain of comfort is way too minimal. You can manually expand it.
