### ISSUE TITLE
feat(YouTube) : Show again the Username in comments, community posts

### ISSUE THREAD

**Issue by SunSea88** [ReVanced/revanced-patches#2556]
### Feature description

Show again the Username in comments, community posts... instead of User ID Handle with @ like this script on YouTube PC
-> greasyfork.org/fr/scripts/468740-restore-youtube-username-from-handle-to-custom

### Motivation

Improve a little more the comfort for everyone on YouTube Android 😃

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Don't see how this generic motivation applies to this feature

**Comment by YT-Advanced** [comment]
> Don't see how this generic motivation applies to this feature

This feature should enhance user experience due to the default Youtube username is too bad, it just the handle name + some random letter.

**Comment by oSumAtrIX** [comment]
User experience remains unaffected
