### ISSUE TITLE
feat(YouTube) : Hide the Most Replayed section in the videos

### ISSUE THREAD

**Issue by SunSea88** [ReVanced/revanced-patches#2557]
### Feature description

Hide the Most Replayed section in the videos like with uBlockOrigin on YouTube PC
-> droidwin.com/how-to-disable-youtube-most-replayed-feature

### Motivation

Improve a little more the comfort for everyone on YouTube Android 😃

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
The motivation doesnt apply to the request
