### ISSUE TITLE
feat(YouTube) : Hide the videos that are in our private or public playlists in the YouTube Homepage

### ISSUE THREAD

**Issue by SunSea88** [ReVanced/revanced-patches#2558]
### Feature description

Hide the videos that are in our private or public playlists in the YouTube Homepage like this script on YouTube PC
-> greasyfork.org/fr/scripts/474300-hide-videos-that-are-in-playlist

### Motivation

Improve a little more the comfort for everyone on YouTube Android 😃

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Don't see why you would hide the videos.
