### ISSUE TITLE
feat(YouTube) : Review all videos, lives, premieres, shorts from a Channel in one place

### ISSUE THREAD

**Issue by SunSea88** [ReVanced/revanced-patches#2559]
### Feature description

Review all videos, lives, premieres, shorts from a Channel in one place like when everything was in the "Videos" tab only ; Very useful to know what has been posted online in order like this script on YouTube PC
-> greasyfork.org/fr/scripts/454215-bring-back-youtube-channel-playlists

### Motivation

Improve a little more the comfort for everyone on YouTube Android 😃

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
You can see a channels content on the channel page
