### ISSUE TITLE
feat: Spoof Twitter client identifier

### ISSUE THREAD

**Issue by kairusds** [revanced/revanced-patches#2560]
### Application

Twitter

### Issue

Recently Musk introduced a feature that rate limits the amount of tweets that a user can view per day.

This is just my conjecture but different Twitter clients seems to have separate rate limits when viewing tweets. For example, if you reached the view rate limit on the mobile apps you can still use the web client or Tweetdeck provided that you haven't reached the rate limits for those too yet.

### Patch

Have a randomizer or a set of existing client identifiers to change from the Settings menu

### Motivation

It makes Twitter bearable to use again without having to worry about reaching the rate limit.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Twitter currently has reasonable rate limits and they are bound to your account.

**Comment by kairusds** [comment]
Reasonable wouldn't even be the word for it since free users can only scroll past a few tweets and they will instantly hit the rate limit. Twitter Blue users on the other hand have 6,000 tweets but again, scrolling past a tweet counts as viewing it so it wouldn't even take more than 30 minutes to reach it

**Comment by kairusds** [comment]
I wouldn't really call it reasonable since it's destroying the platform right now but alright

**Comment by oSumAtrIX** [comment]
1000 posts is more than reasonable. It's a free platform.

**Comment by kairusds** [comment]
I was talking about "the amount of tweets that a user can view per day" not "the amount of tweets a user can post per day"

**Comment by oSumAtrIX** [comment]
Yes, that is at 1000 right now

**Comment by kairusds** [comment]
Apparently this bug is a self-DDoS caused by Twitter itself so this issue is irrelevant now https://sfba.social/@sysop408/110639435788921057
