### ISSUE TITLE
Infinity for Reddit patch fails

### ISSUE THREAD

**Issue by mvevitsis** [revanced/revanced-patches#2561]
### Type

Error while patching

### Bug description

Patch fails with error 

Failed to apply change - oauth -client- id : Failed to resolve
GetHTTPBasicAuthHeaderFingerprint

### Steps to reproduce

1. Try to patch infinity 

### Relevant log output

```shell
Failed to apply change - oauth -client- id : Failed to resolve
GetHTTPBasicAuthHeaderFingerprint
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by tabtomi8** [comment]
[Use this instead for changing the API key. ](https://www.reddit.com/r/Infinity_For_Reddit/comments/14c2v5x/build_your_own_apk_with_your_personal_api_key_in/) It's very easy, just follow the instructions.

**Comment by oSumAtrIX** [comment]
That is changing the API key

**Comment by mvevitsis** [comment]
Apparently others are having the same issue with the revanced patch:

https://www.reddit.com/r/Infinity_For_Reddit/comments/14o1qv2/_/

**Comment by oSumAtrIX** [comment]
Yes, you are commenting under the issue made for that

**Comment by johnconner122** [comment]
Try to patch Infinity `v5.4.2`.

**Comment by johnconner122** [comment]
Fixed in dev release.
