### ISSUE TITLE
feat: return of NSFW content in RIF after July 5th

### ISSUE THREAD

**Issue by Rerbun** [revanced/revanced-patches#2562]
### Application

Rif is fun (and hopefully other 3rd party apps)

### Issue

As of today (July 1st) we can use Rif is fun with the OAuth patch and it works perfectly fine. However it's not all over yet, according to [Reddit's statements](https://www.reddit.com/r/reddit/comments/145bram/addressing_the_community_about_changes_to_our_api/) NSFW content will be filtered from the (App) Data API after July 5th. 
I think this will mean that RIF (even with the OAuth patch) will no longer work as expected, and all NSFW content will be filtered out.

Would it be possible to get NSFW content working again after this date? Maybe some patch could already be created in advance?

### Patch

Patch that correctly fetches NSFW content as expected, even after July 5th

### Motivation

NSFW content is a big part of Reddit content both in text and visual form. It would be a shame if it could no longer be accessible through the 3rd party apps.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
OAuth apps can not see NSFW content.

**Comment by jameshilliard** [comment]
> OAuth apps can not see NSFW content.

That's true, however the GQL API should still work. The required change in infinity would apparently look like [this](https://github.com/Docile-Alligator/Infinity-For-Reddit/compare/master...KhoalaS:Infinity-For-Reddit:master), not sure how hard it would be to apply this sort of change as a patch to other apps however as it's a bit more involved than just patching the API key.

**Comment by Rerbun** [comment]
> OAuth apps can not see NSFW content.

Yes, that's why I made this issue; I'd like a patch to make it so NSFW content is still retrievable through a different method in 3rd party apps.

**Comment by oSumAtrIX** [comment]
This would require a complete rewrite for 3rd party clients to use the GQL API which is not practically achieveable. Not worth the effort. If you want to see NSFW content, use the official app.
