### ISSUE TITLE
bug (youtube-music): Failed to apply bypass-certificate-checks

### ISSUE THREAD

**Issue by KobeW50** [revanced/revanced-patches#2563]
### Type

Error while patching

### Bug description

The bypass certificate checks patch for YT Music seems to no longer be able to be applied (in the manager, v1.3.8).

This was with YTM version 6.04.52, but other users reported the same error with 6.08.50 and 6.06.52.

However, version 5.39.52 still works.

### Steps to reproduce

Use manager 1.3.8

Use YTM version 6.04.52 with the default patches. (I haven't tested other versions.)

See if the patch fails.

### Relevant log output

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing patches
Applied background-play
Failed to apply bypass-certificate-checks: Failed to resolve CheckCertificateFingerprint
Applied codecs-unlock
Applied exclusive-audio-playback
Applied hide-get-premium
Applied minimized-playback-music
Applied music-video-ads
Applied upgrade-button-remover
Applied vanced-microg-support
Repacking patched apk
Compiling resources
Writing modified dex files
Finished!
```

### Additional context

Iirc, it was working in earlier versions of the Manager. I remember testing when the suggested version for YTM was changed from 5.39.52 to All. I don't remember the manager version that this was with.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Julius8900** [comment]
It worked to me on version 6.08.50, but it seems now I have this error too.
