### ISSUE TITLE
feat: (PhonePe) Block ADS + Hide Elements

### ISSUE THREAD

**Issue by git-Hmmm** [ReVanced/revanced-patches#2566]
### Feature description

PhonePe: Indian UPI payments application
but sadly they use ads and some exra features which are barely used by upi only audience

Play Store: https://play.google.com/store/apps/details?id=com.phonepe.app

So I request the following patches:
* Hide ADS
* Navigation Bar elements modification support
* Disable: Wallet, Insurance, Credit, Wealth and Referral sections

NOTE: The following screenshot doesn't show those random ads since they are blocked with NextDNS, ads needs to be addressed as well.
![2023-12-30_12-21](https://github.com/ReVanced/revanced-patches/assets/102938585/3e5c4c70-8bab-4f39-b54b-d709a30a85b3)

### Motivation

- simplicity 
- better user experience
- lesser headache 

Currently only GPay has the one of the best UPI payments application interface which doesn't have trashy ads and extra mess.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by git-Hmmm** [comment]
I doubt if after mod the upi sdk will even work or not
and the pin screen will appear or not

but let's see
I'm extremely curious if this happens

**Comment by git-Hmmm** [comment]
Yes, I'm already utilizing nextdns to block ads, regarding banning bank account I doubt if they have enough rights to do that most they can do is ban my PhonePe account ig.

Tho, I absolutely see your point and I'm unsure if I should close the issue or not
what do you suggest?

**Comment by oSumAtrIX** [comment]
Just as @cyberboh said. This is a banking app and fulfill it's job the way it is now. The genetic motivation is insufficient here considering the difficulty for the amount of gain
