### ISSUE TITLE
feat(Google Photos): microG patch

### ISSUE THREAD

**Issue by noel-schenk** [ReVanced/revanced-patches#2567]
### Feature description

(ReVanced) MicroG works for the Google Photos app.

### Motivation

Using the Meta Quest it would be possible to load the original Google Photos app to view 360 deg photos. 
Meta has not added Google Play service support.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
https://github.com/ReVanced/revanced-patches/issues/1055
