### ISSUE TITLE
bug: Infinity for Reddit suggested version

### ISSUE THREAD

**Issue by SnakeSK** [ReVanced/revanced-patches#2569]
### Bug description

Hello,

current patches selection suggests all versions of Inifinity for Reddit is supported, whenever I try to patch anything higher than 6.2.5 I cannot login to application. I downloaded the app from APK mirror, github etc, both checkboxes are ticked, I provided my API key in the reddit_client_id_revanced.txt file, patch went successfully. Upon login the error is - Invalid request to Oauth API. I created a second key to test, redirect uri is set correctly. Nothing above 6.2.5 works

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
The latest version can be patched, for troubleshooting move to one of our support channels on one of our platforms you can find on https://revanced.app

**Comment by Aryan-Chauhan** [comment]
I patched v6.6.0.

It's working perfectly.
