### ISSUE TITLE
bug: YouTube Music Battery Drain

### ISSUE THREAD

**Issue by denismanurin** [revanced/revanced-patches#257]
### Type

Other

### Bug description

YouTube Music consumes a lot of battery. Music in the background consumes 20-30% of the CPU. The smartphone is hot at this time

### Steps to reproduce

Just use latest youtube music revanced

### Relevant log output

```shell
none
```

### Solution

none

**Comment by oSumAtrIX** [comment]
Probably because casting v2 is not disabled there.

**Comment by anil-al** [comment]
> Probably because casting v2 is not disabled there.

Could you prioritise this issue above others, since it makes the app unusable due to overheating.

**Comment by Sculas** [comment]
@oSumAtrIX Please look into this.

**Comment by Canny1913** [comment]
> @oSumAtrIX Please look into this.

microg-support refactor will take care of this too.

**Comment by oneironaut2209** [comment]
I was having this issue with YTM + Microg. Today I tried YTM root version and this issue is not present.

**Comment by yc-codes** [comment]
Any news?

**Comment by Canny1913** [comment]
> Any news?

Fixed.
