### ISSUE TITLE
feat: (YouTube) hide Like/Dislike buttons on Shorts videos

### ISSUE THREAD

**Issue by CompuGenius** [ReVanced/revanced-patches#2570]
### Feature description

Please add an option to hide the Like/Dislike buttons on Shorts videos

### Motivation

It should be implemented because:
1. There's already this feature for long-form videos
2. Some people (like myself) never use likes/dislikes and it blocks part of the videos and I sometimes accidentally click it

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
https://github.com/ReVanced/revanced-patches/issues/769

**Comment by CompuGenius** [comment]
> #769

Thanks! For some reason, that issue isn't coming up when I search, which is why I created a whole new one. Weird 🤔
