### ISSUE TITLE
Remove Unrelated Search result feature

### ISSUE THREAD

**Issue by DexfromAntarctica** [ReVanced/revanced-patches#2572]
### Feature description

I have a suggestion for a feature improvement. It would be great to have an option that filters out completely unrelated YouTube video suggestions during searches. 

It's frustrating to encounter videos like boil removals and other irrelevant content mixed in with my search results. 

Currently, I can avoid this by adding keyword after:2005 (or any year prior to YouTube's inception) to my search terms, but it's cumbersome. An automatic feature to prevent such unrelated suggestions would be highly beneficial.

### Motivation

YouTube frequently displays search results that are not only irrelevant to the searched keyword but also aggressively inappropriate and disturbing. A prime example is when searching for 'asmr'.

 While there are manual workarounds, it would be highly beneficial to have an option that automatically appends 'after:2005' to all search queries. This feature would help ensure that the results are perfect relevant and no shocking.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
The app consumes what the server sends. Without analysing the video content, you can't say its irrelevant and therefor is out of scope.

**Comment by KTibow** [comment]
I think the requester is asking for something different. They don't mean magically analyzing the content, they mean that search is injecting random content (probably in an effort to keep them engaged).
They want the search API to be patched to add `after:2005` (a filter that is in theory useless as YouTube came out in 2005), which for some reason prevents the random content from being shown.

**Comment by oSumAtrIX** [comment]
Please add examples and show how there's a difference

**Comment by KTibow** [comment]
Normally, we get stuff like "people also watched":
![image](https://github.com/ReVanced/revanced-patches/assets/10727862/1d65ec2f-3cfa-4231-ae13-e2ed9e5fcdbe)
But when we add `after: 2005`, the results don't have any/as many diversions from the search term:
<img height="1000px" src="https://github.com/ReVanced/revanced-patches/assets/10727862/5a46afcb-a9d3-4763-bbe8-21a5f1944657" />

**Comment by oSumAtrIX** [comment]
Then the patch already exists

**Comment by Aryan-Chauhan** [comment]
Name of patch?
