### ISSUE TITLE
feat(Twitter): sticky bottom-navigation bar

### ISSUE THREAD

**Issue by realDayaa** [revanced/revanced-patches#2573]
### Application

Twitter

### Issue

In the latest version of the app, when scrolling down, the bottom-navigation bar disappears and only reappears when scrolling up again.  

### Patch

The patch could be called "sticky-navbar" and would make the navbar stick to the bottom while scrolling.

### Motivation

The old sticky navigation bar was far more user-friendly and should be preserved IMO.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
It gets hidden to make room for the content you scroll down for. Scroll up if you want it back.
