### ISSUE TITLE
Aborted on start-up, but everything is right 

### ISSUE THREAD

**Issue by P13rlU** [revanced/revanced-patches#2576]
### Type

Error while patching

### Bug description

Whenever i try to patch, throws an error that it cannot find the application even though is installed 

### Steps to reproduce

Idk, just happened randomly, after youtube got strangely update even having auto-update on play store turned off

### Relevant log output

```shell
.
```

### Screenshots or videos

![Screenshot_20230703-233926](https://github.com/revanced/revanced-patches/assets/67976483/466f0865-b7d1-45cb-896d-b30d3d7e5e34)
![Screenshot_20230703-233929](https://github.com/revanced/revanced-patches/assets/67976483/a13ddc3b-5cfd-4603-8afb-ff26475eaf86)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
This is a ReVanced Manager issue

**Comment by P13rlU** [comment]
> This is a ReVanced Manager issue, open an issue in that repo

Ok!
