### ISSUE TITLE
feat(reddit): hide Discover, Create and Chat buttons on the bottom toolbar

### ISSUE THREAD

**Issue by reokyouma** [revanced/revanced-patches#2577]
### Application

Reddit Official App

### Issue

Removes unnecessary buttons that some users aren't using. Just like how you can remove the some buttons on the revanced youtube app

### Patch

Hide the Discover, Create and Chat buttons 

![image](https://github.com/revanced/revanced-patches/assets/56574142/4faf2f4d-4616-45e5-930c-5b18bd395a51)

### Motivation

To reduce the unnecessary UI that Reddit added

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
It is not unnecessary
