### ISSUE TITLE
feat: Disable autoplay of current one video in Youtube

### ISSUE THREAD

**Issue by hooddy** [revanced/revanced-patches#2579]
### Application

Youtube

### Issue

When I open video from feed or by open external url it started to play. There is no any option to disable it.

### Patch

Add option to disable this autoplayback. Maybe its open in Pause mode til i press on video pause button on screen or on added under screen button for play.

### Motivation

Coz its so convietn and useful!

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Don't see how it's convenient and/or useful

**Comment by hooddy** [comment]
I can not agree with ya guys. If think like ya so why there is pause optionm remove it at all let its play nonstop. In lotta scenarioas i need to open vid with no playback to open comments or chat.

**Comment by oSumAtrIX** [comment]
I don't see a lot of scenarios and you can still hit pause.

**Comment by hooddy** [comment]
but its realy no convient when i open vids page and its start to play. i dont need it. i need to open page and next press all i need - play, open comments etc. there is lotta options i dont need already presents but this one i don't. ok maybe im the only one so special.

**Comment by hooddy** [comment]
Regarding my request. I have a different experience using YouTube. I don't need autoplay in my phone at all. By clicking on the videos, I in first load its page to view the description, chapters, links, comments tec. At the same time, I'm almost certainly on public transport and without headphones. And in such a scenario, I have to try to click on the video so that it does not play, turn the volume to a minimum and other annoying moments for me and others. And it is very unpleasant to me that someone here decides unanimously what is needed and what is not. I don't need the whole thousand patches here, but I'm not writing anything about it.
