### ISSUE TITLE
feat: Stop YT music auto-replacing songs by allowing default mode to be set to "Video" instead of "Song"

### ISSUE THREAD

**Issue by distbit0** [ReVanced/revanced-patches#2582]
### Feature description

It should be possible in Youtube Music revanced settings to specify whether the default playback mode is "Song" or "Video", as currently it defaults to song mode regardless of what options in settings I configure.

### Motivation

Currently Youtube Music is automatically replacing custom versions of songs in playlists with the origina/official version of the song, which is very annoying as often the original version is very different to the version I intended to add. For example nightcore, sped up, reverb, base boost, cut etc.

I have however discovered that youtube music does not play the "official" version of a song if you listen to it in video mode, rather than song mode. As a result, I would very much appreciate the ability to listen to all songs in video mode as a way to avoid youtube music replacing songs for me.

If you'd like to test that what I am claiming is true, try adding the following song to a playlist: https://www.youtube.com/watch?v=O3ujn71Tjcc You will notice that it is auto-replaced with the original full version of free bird if you play it in song mode, however the correct version is played when you select video mode.

Examples of people discussing this issue elsewhere:
https://www.reddit.com/r/YoutubeMusic/comments/15vzj1h/youtube_music_will_now_replace_your_tracks/#fromHistory
https://www.reddit.com/r/YoutubeMusic/comments/16xmqhm/why_does_youtube_literally_replace_the_song_i_put/#fromHistory
https://support.google.com/youtubemusic/thread/232433309/songs-being-replaced-by-other-versions?hl=en#fromHistory

Many thanks!

### Acknowledgements

- [X] All requested information has been provided properly.
- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.

**Comment by distbit0** [comment]
I prefer the youtube music interface and layout for listening to music + its recommendation mechanism.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
