### ISSUE TITLE
Sync for Reddit patch

### ISSUE THREAD

**Issue by IndomitableAlbus** [revanced/revanced-patches#2584]
### Type

Other

### Bug description

The patch works fine but link images aren't displaying in the Sync App.

### Steps to reproduce

NA

### Relevant log output

```shell
NA
```

### Screenshots or videos

NA

### Solution

NA

### Additional context

NA

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
![Screenshot_2023-07-05-17-41-26-79_f9dbdf549e278560a5aae87a7709be13](https://github.com/revanced/revanced-patches/assets/13122796/4e890219-826c-4235-aae8-77ebcc09e068)
![Screenshot_2023-07-05-17-41-24-97_f9dbdf549e278560a5aae87a7709be13](https://github.com/revanced/revanced-patches/assets/13122796/4adeb284-2502-491c-9de7-15f6b6ac3053)
Not reproducible

**Comment by oSumAtrIX** [comment]
I don't see any link images above posts
