### ISSUE TITLE
feat (YouTube): Ability to hide text that are inside three-dot menus.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [ReVanced/revanced-patches#2586]
### Feature description

There are various three-dot menus located on the top bar throughout the UI. This feature request is to add the ability to hide some/all text from inside them. Screenshots are attached.
![Screenshot_2024-01-05-09-27-09-48_f22faf49515899f9781ec174a4d85388](https://github.com/ReVanced/revanced-patches/assets/91815107/355c1372-8f27-4d37-a53f-735b2941477b)
![Screenshot_2024-01-05-09-27-37-68_f22faf49515899f9781ec174a4d85388](https://github.com/ReVanced/revanced-patches/assets/91815107/42a865de-86e1-4740-b5d5-7b48a4dcab18)
![Screenshot_2024-01-05-09-29-56-39_f22faf49515899f9781ec174a4d85388](https://github.com/ReVanced/revanced-patches/assets/91815107/85d14f7e-dac6-4216-b268-d3d7b4216a7d)
![Screenshot_2024-01-05-09-31-07-92_f22faf49515899f9781ec174a4d85388](https://github.com/ReVanced/revanced-patches/assets/91815107/914d0915-08af-4703-bed8-5a4c9aa747ab)
![Screenshot_2024-01-05-09-32-24-46_f22faf49515899f9781ec174a4d85388](https://github.com/ReVanced/revanced-patches/assets/91815107/0f719659-d0c6-4946-a3d3-66acd649ba94)

### Motivation

This feature should be implemented because it is a personalization feature &  "Customize your app" is written as one of the features of ReVanced patches.

Another reason is:

ReVanced has already removed/hid/improved various annoying stuff of stock YT app. So, why not make it even better by adding this feature?

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Because most of these menus are used scarcely and hardly trouble usage of the app even if they were not used scarcely, adding it as a customization option hardly adds any benefit for the amount of work to implement this.
