### ISSUE TITLE
feat: POLLS on livestream

### ISSUE THREAD

**Issue by ZVONEE** [revanced/revanced-patches#2586]
### Application

Youtube Revanced

### Issue

I think it would solve that you never need to remove poll from livestreams and you would see messages that poll 

### Patch

Remove polls from livestreams

### Motivation

Everytime we go to streamer who created poll you dont see last 3 messages.

Everytime you close and open stream you must always swipe or remove poll from chat (if streamer made poll) 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
The poll does not hide the last three messages but the oldest three visible messages. You can simply dismiss the poll.

**Comment by ZVONEE** [comment]
![IMG_20230706_003834](https://github.com/revanced/revanced-patches/assets/37279254/8fc1c948-b5bd-45f3-8459-ede2f7c438e8)

For me its like this.
