### ISSUE TITLE
feat:  Swipe away videos on home feed to mark not interested 

### ISSUE THREAD

**Issue by mackdacre** [ReVanced/revanced-patches#2589]
### Feature description

I think it would be great to create a control so that in the "Home" feed, you could swipe a video left to say "Not Interested -> I've already seen it" and swipe it right to say "Not interested -> I don't like the video".

I've attached screenshots to show what the swipe would be like and then the steps of the current activity that it would produce the same result as 

<img width="660" alt="1" src="https://github.com/ReVanced/revanced-patches/assets/22719284/e33fd84c-da0a-42ad-9e08-da4e6d99c35c">
<img width="660" alt="2" src="https://github.com/ReVanced/revanced-patches/assets/22719284/7f1b850b-db55-4e7a-92ec-3b2ab60cd5c1">
<img width="660" alt="3" src="https://github.com/ReVanced/revanced-patches/assets/22719284/e61dccee-5dc3-4b0c-916b-541ce17a77d0">

### Motivation

I find myself constantly using the "Not Interested" feature on my home feed but it's sort of a pain to use it the way YouTube designed it because you have to hit the 3 dots, then hit not interested, and then tell it if it's because you've already seen it or if you just don't like it. This would make it so much easier and so much faster to tune your feed to get the stuff you wanna watch quickly.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
> constantly using the "Not Interested" feature

This is not the correct way you are supposed to use this feature. I think you should use this feature scarcely. in which case this feature would lose major use case, otherwise, you disturb the algorithm, and it doesn't work for you.

**Comment by oSumAtrIX** [comment]
You disturb the algorithm, in turn you get videos recommended that you don't want to see, and further disturb the algorithm therefore.

**Comment by Lucius-Will** [comment]
I fully support it!

I periodically notice some bullshit in my recommendations. Then I just mark the videos that I've already seen and that I'm not interested in. Then the recommendations work more adequately. Until after 1 to several months, I again do not notice any bullshit in my recommendations. And the process repeats again.

I've noticed that if I repeat this more often, the recommendations work better. But managing through 3 taps is just some kind of absurd madness.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
