### ISSUE TITLE
feat: JoeyForReddit add Ability to change API Key. (change-oauth-client-id)

### ISSUE THREAD

**Issue by Kristijan1001** [ReVanced/revanced-patches#2591]
### Application

https://play.google.com/store/apps/details?id=o.o.joey

### Issue

The app works currently but according to reddit it will probably stop in the following weeks. Need to be able to insert personal API key to continue using.

### Patch

change-oauth-client-id
Add Custom API Key Support

### Motivation

Removal of Support for 3Party Apps

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by kulmegil** [comment]
Joey is the only client with nice TTS capabilities build in.

It's the reason I chose it _amogus_ the others.

**Comment by nummer-GDD** [comment]
users of joey are starting to report that it is not working anymore. we're gonna need a patch soon to keep it usable

**Comment by cyberboh** [comment]
@Kristijan1001 The app itself is removed from playstore and not supported anymore. So, the patches is useless.

**Comment by VaiCaDep0893** [comment]
> The app itself is removed from playstore and not supported anymore. So, the patches is useless.

@cyberboh no
https://www.apkmonk.com/app/o.o.joey/

**Comment by cyberboh** [comment]
> > The app itself is removed from playstore and not supported anymore. So, the patches is useless.
> 
> @cyberboh no https://www.apkmonk.com/app/o.o.joey/

you trust leecher site? lol
he for you: https://www.reddit.com/r/JoeyForReddit/comments/14zpxy3/joey_has_been_shutdown/

**Comment by VaiCaDep0893** [comment]
> 

Nah man, that's not how it works. By changing the developer's ID to ours, we can still use the app. I can confirm because Boost, Sync, and Rif works for me. And yes, that site is safe. I have no problem patching Photomath using the apk from apkmonk.

**Comment by cyberboh** [comment]
> > 
> 
> Nah man, that's not how it works. By changing the developer's ID to ours, we can still use the app. I can confirm because Boost, Sync, and Rif works for me. And yes, that site is safe. I have no problem patching Photomath using the apk from apkmonk.

i know what the patches mean, but the app itself has been shutted down. sooner or later it will break because of reddit API always regularly updated.
keeping patches for unmaintained app just another pain.

**Comment by oSumAtrIX** [comment]
Keeping equates to patching it once, as you say, there's not gonna be any new version. Breaking changes are unlikely gonna come quickly.

**Comment by Elinron** [comment]
> Keeping equates to patching it once, as you say, there's not gonna be any new version. Breaking changes are unlikely gonna come quickly.

@oSumAtrIX  @cyberboh But this point applies to all the other discontinued reddit apps like Sync, Boost and RIF. Only Relay and Infinity will continue development in the future. Joey is a great reddit app and many people will be happy if it got a Revanced patch.

**Comment by Bceez** [comment]
I think this issue can be closed
