### ISSUE TITLE
feat: Allow translating and selecting some YouTube UI components 

### ISSUE THREAD

**Issue by kairusds** [ReVanced/revanced-patches#2591]
### Feature description

A feature that allows the text contents from these UI components of the YouTube app be always be translatable (from the translate feature of comments) and selectable, so you can copy its contents:
- Comments
- Descriptions
- About page
- Community posts

### Motivation

It's too cumbersome to open the desktop YouTube site just for copying texts or translating them, specially since the desktop site is laggy and buggy to navigate on mobile.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
https://github.com/ReVanced/revanced-patches/issues/1538
