### ISSUE TITLE
Add Removing Internet Permission to List of Universal Patches feat: 

### ISSUE THREAD

**Issue by matt873** [revanced/revanced-patches#2594]
### Application

Universal Patch

### Issue

Many apps require internet permission for displaying ads only and others require them without any specific purpose but only for home-phoning. Adding this patch would make it possible to disable Ads for many apps and also give the user control over privacy, especially for those apps that require unnecessary internet permission or the user doesn't need internet for the app.

### Patch

This patch is possible through simple editing of the AndroidManifest.xml file.

### Motivation

Ads Removal and Privacy to User.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
You can disable ads on Android in the settings.

**Comment by matt873** [comment]
But for privacy and preventing home-phoning. It would be worth adding this patch.

**Comment by matt873** [comment]
> You can disable ads on Android in the settings.

A user may want to keep default DNS for other reasons.

**Comment by oSumAtrIX** [comment]
You can disable the internet for specific apps. No need to patch apps.

**Comment by matt873** [comment]
> You can disable the internet for specific apps. No need to patch apps.

Would require root for afwall or constant running netguard VPN which also restricts users from doing other things such as using another VPN service and consuming battery.
I would like to disable internet permission for only certain apps, not all apps on my phone which is also not feasible, which I use daily and show ads or collects data such as MX player or File Manager+, etc. So this patch has practical use.

**Comment by oSumAtrIX** [comment]
![Screenshot_2023-07-08-02-59-51-82_f477f0d1f9efd6499236910aab472e51](https://github.com/revanced/revanced-patches/assets/13122796/fddb6268-2bd6-449f-b069-2c4ed2444f65)

You don't need root

**Comment by matt873** [comment]
Which ROM are you using? This option is not available in pixel stock rom or any other aosp roms except GapheneOS.

**Comment by oSumAtrIX** [comment]
I am using OxygenOS
