### ISSUE TITLE
bug: Package Conflict and Fully Remove Red on Update

### ISSUE THREAD

**Issue by sssh7710** [revanced/revanced-patches#2595]
### Type

Other

### Bug description

Package conflict encountered during re-updates

### Steps to reproduce

1. Package conflicts during installation after patching with Manager
2. Remove existing apps
3. Proceed with reinstallation
4. Crash again to check remaining apps with "SD Maid"
5. Similarly, try uninstalling and confirming
6. It won't erase... (Not in the phone application settings)

### Relevant log output

```shell
.
```

### Screenshots or videos

![Screenshot_20230708_233839_Package installer](https://github.com/revanced/revanced-patches/assets/98168192/d29a5101-7605-4337-b2c5-9e5491488046)

### Additional context

[revanced-manager_patcher_20230708233845107145.log](https://github.com/revanced/revanced-patches/files/11990885/revanced-manager_patcher_20230708233845107145.log)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
This should be opened in the repo of ReVanced Manager
