### ISSUE TITLE
feat (Sync): Ability to hide "Sync Ultra" text throughout the UI.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [ReVanced/revanced-patches#2597]
### Feature description

There are "Sync Ultra" texts written in different places of UI. So, please add the ability to hide them.
![Screenshot_2024-01-08-09-24-04-22_f9dbdf549e278560a5aae87a7709be13](https://github.com/ReVanced/revanced-patches/assets/91815107/aa20f615-5ea0-4db8-91cd-a7e403602be1)
![Screenshot_2024-01-08-09-24-38-13_f9dbdf549e278560a5aae87a7709be13](https://github.com/ReVanced/revanced-patches/assets/91815107/8bd6a155-c4dc-4d50-b2df-41121cbaa0b7)

### Motivation

1. It gives the feeling you're using an unmodified app, which you aren't. You're using an improved one.

2. Sync Ultra features aren't much alluring to me.

3. App works perfectly, UI is so organized. "Get Sync Ultra" is like a tiny ink dot on a big piece of white paper.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
There is hardly any reason to remove this as it neither obstructs any important nor repetitively accessed sections of the app.
