### ISSUE TITLE
[YouTube] Add automatic "not interested" for videos in some languages 

### ISSUE THREAD

**Issue by 111ebobo** [ReVanced/revanced-patches#2599]
### Feature description

It should automatically mark videos as "not interested" for certain criterias (also you can make just "StopRU" YouTube extension for mobile 

### Motivation

Some people don't want to see videos in certain languages or from certain countries 

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
https://github.com/ReVanced/revanced-patches/issues/1104
