### ISSUE TITLE
feat (youtube/settings): Show patch and integration versions used

### ISSUE THREAD

**Issue by KobeW50** [ReVanced/revanced-patches#2600]
### Application

YT ReVanced 

### Issue

It is difficult for the user to know which patch/integration version they have in their patched YT ReVanced.

### Patch

The settings patch would automatically put the patches and integrations info in the Miscellaneous settings (or in profile picture > Settings > About)

Ideally, it would also show the patches that were included/excluded.

This screen recording shows what it looks like in YT ReVanced Extended, which is a good reference of what it could look like.

https://github.com/revanced/revanced-patches/assets/84587632/84c3a165-691f-419a-b753-e3e0fee27ca1

### Motivation

It is useful to know what patches and integration versions that were used at the time that YT ReVanced was patched. Mainly for troubleshooting and to know if the current version is newer than your patched version.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by SodaWithoutSparkles** [comment]
I agree that the info should be in the patched itself. Afterall, those are valid information about the patched app.

**Comment by oSumAtrIX** [comment]
Information about what patches have been applied can be seen in ReVanced Manager
