### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by KIKIhadENOUGH** [ReVanced/revanced-patches#2603]
### Bug description

Hi,

My patched YouTube doesn't work. I open it and it immediately freezes, the screen becomes darker but I still can see my feed. I can't interact with anything.

Steps to reproduce : 

1.Get yourself a Honor phone with Magic OS 7.1.0. + Android 13.

2. Install YouTube 18.45.43 from APK Pure because XAPK YouTube APK  doesn't get recognize as a compiled APK file by the phone.

3. Patch it using the LTS of revanced manager and use it as normal.

4. Get a "security update" from Magic OS, the 7.1.0.242

5. Wait a day or two and there you go.

Rebooting your phone doesn't work.
Restarting the app itself doesn't work.

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by KobeW50** [comment]
https://github.com/ReVanced/revanced-patches/issues/2562
