### ISSUE TITLE
bug:(YouTube - HIde chapter in video description) Patch is broken

### ISSUE THREAD

**Issue by dekhu48** [ReVanced/revanced-patches#2604]
### Bug description

As the title says the patch is broken (The patcher applies the patch with no issue)

What it looks like 
![d8890722-e52b-4e5b-8483-def416092ade](https://github.com/ReVanced/revanced-patches/assets/97910722/7d576556-2427-4442-8664-f2f3e59ca987)

![c2932da5-dab5-431c-922b-ba9cdade9084](https://github.com/ReVanced/revanced-patches/assets/97910722/c7db9e89-d19b-43a8-be6f-7b1605535fe6)

### Additional context

What it should look like
![7f210e4b-05e3-4c5e-b0e9-c89e01703ae5](https://github.com/ReVanced/revanced-patches/assets/97910722/2583ee2f-b43b-48e6-a8fc-2ebb0729d5de)

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Follow this and report back:

![Screenshot_20240109-163158](https://github.com/ReVanced/revanced-patches/assets/13122796/4ffd06b4-9ccd-47ff-8f68-db1f0103f02c)

**Comment by dekhu48** [comment]
ok i have tested using the binary method and have come to conclusion that "HIde general components" patch is what casuing the isuue

**Comment by oSumAtrIX** [comment]
Please check which of the toggles is responsible.

**Comment by dekhu48** [comment]
i am sorry i dont understand what u mean 
if u mean what setting is broken its this one 
![c2932da5-dab5-431c-922b-ba9cdade9084](https://github.com/ReVanced/revanced-patches/assets/97910722/e410efde-324f-48cd-af04-f1f00814527c)

**Comment by oSumAtrIX** [comment]
Check the toggles other than that
