### ISSUE TITLE
bug: (YouTube - Unwanted Data Consumption in YouTube due to Video Re-download) 

### ISSUE THREAD

**Issue by ayoubelmhamdi** [ReVanced/revanced-patches#2605]
### Bug description

In the latest version of advanced YouTube, with all the default patches, we have bad behaviors, that's very dangerous for some people who have a limited internet quota. 

The problem is: when we download any video, we can watch it from the download as expected, but when we try to watch it from another place rather than the download, like Home or research... the video is pulled from the internet, so it's loaded from the internet, which eats from the quota again and again....

For me, I always use wifi to download some videos, but I don't want to download from my 4G internet again.
I think the YouTube-v18.38.44 does have these bad behaviors.

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Whatever you experience is not caused by ReVanced

**Comment by ayoubelmhamdi** [comment]
your absolutely right the problems is from YouTube itself.

The problems is coming from the data saver setting, when to prevent this bad previous behavior, it's must to turn on datasaver.
