### ISSUE TITLE
feat: Patch for a fixed domain of XDA app (XDA Forums)

### ISSUE THREAD

**Issue by giwrgosmant** [ReVanced/revanced-patches#2607]
### Feature description

I would like to suggest, if possible to create a patch to fix the domain of [XDA app](https://play.google.com/store/apps/details?id=com.xda.labs.play&hl=en_US) (package name: com.xda.labs.play)
Few months ago, XDA-[Valnet](https://www.valnetinc.com/) changed the domain from xda-developers to xdaforums and that broke the XDA app. Users cannot login/use the app since then, so it became useless. The devs of that app seems they abandoned it long ago but at least it was working fine till that change happened.
A patch for a fix would be great.
Full details: [here](https://xdaforums.com/t/petition-for-xda-fixed-modded-app.4649219/).

### Motivation

- It will make the XDA app useful and working again.
- XDA users will be able to get push notifications / communicate fast into the XDA Forums.
- More advantages of a working XDA app: [here](https://xdaforums.com/t/petition-for-xda-fixed-modded-app.4649219/).

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
As I understood this, only a domain name string change is needed?

**Comment by oSumAtrIX** [comment]
Could add a generic string transformer patch to ReVanced which would be able to transform a list of strings to another

**Comment by oSumAtrIX** [comment]
Neither login nor the app is broken:

<img width="449" alt="image" src="https://github.com/ReVanced/revanced-patches/assets/13122796/84974f9c-b410-478d-964f-9bbbe624ef49">

**Comment by oSumAtrIX** [comment]
I am locally testing my patches, and as far as I can tell, the redirect uri for the oauth has to be changed. Mind that once the client id is shut off by xda, the oauth will fail.

**Comment by oSumAtrIX** [comment]
Technically, an open-source patch is more transparent than a modded apk, but since the modded apk already satisfies the folks on your end, I'll close this; thanks.

**Comment by oSumAtrIX** [comment]
If possible, please ask the modder for more information on what changes were made to simplify the development of the patch. Reopen the issue once you have
