### ISSUE TITLE
bug: Can't login to Joey for Reddit and Sync for Reddit

### ISSUE THREAD

**Issue by alicerrrrs** [ReVanced/revanced-patches#2608]
### Bug description

Can't login to Joey for Reddit and Sync for Reddit on my new Pixel 6a (Android 14).
What I'm Using:
Pixel 6a
Android 14
ReVanced Manager: 1.18.0 with latest patch

What I did:
1. Followed all the steps by Simplified Client ID Patch Guide
URL: https://docs.google.com/document/d/1wHvqQwCYdJrQg4BKlGIVDLksPN0KpOnJWniT6PbZSrI/edit
2. Patched apps
3. Open app, tap 'add account'
4. Redirected to Reddit Login Page so I put in my info
5. Confirmed to connect the app I regisitered to my account
6. It should redirect me to the app, but it didn't.

What I get by these steps was just "{}" on screen. Screenshot below:
![Screenshot_20240110-195139](https://github.com/ReVanced/revanced-patches/assets/61745246/c1275191-a8d4-4b70-a0d1-1fb9a2d06e0f)
![Screenshot_20240110-195115](https://github.com/ReVanced/revanced-patches/assets/61745246/4a17270c-7222-4ddd-9b5f-494fcf1d63f1)

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
This is not a normal response from Reddit, quite likely an issue on their end

**Comment by SodaWithoutSparkles** [comment]
I should also add that there are already multiple users reporting this issue on the discord support channel already. First occurance of the exact same issue was at since 2024-01-10 00:30 ([link](https://discord.com/channels/952946952348270622/1135563848586379264/1194438031004925972)). 

I believe the "just `{}` on screen" issue is the key symptom.

**Comment by KobeW50** [comment]
The issue also occurs on the following Reddit clients:

* Slide
* Boost
* BaconReader
* Infinity 

The issue does not occur on Relay or RIF (Reddit is Fun).

**Comment by oSumAtrIX** [comment]
The issue occurs on Infinity.

**Comment by SodaWithoutSparkles** [comment]
Discord user `asztro` suggested the following: 

> The issue of {} error of sync reddit can be fixed if desktop version of the authorization screen can be enabled. Similar issue occured to Apollo and I found a post regarding that.

> https://www.reddit.com/r/apolloapp/comments/1931cc4/for_those_who_cant_sign_in/

Can @alicerrrrs verify that if similar steps work?

**Comment by Ike101692** [comment]
Can confirm I'm experiencing the same on this end. Unfortunetly there is no way, at least using sync, to get to the desktop version of the authorization screen. So it seems we are stuck

**Comment by KobeW50** [comment]
> Discord user `asztro` suggested the following: 
> 
> > The issue of {} error of sync reddit can be fixed if desktop version of the authorization screen can be enabled. Similar issue occured to Apollo and I found a post regarding that.
> 
> > https://www.reddit.com/r/apolloapp/comments/1931cc4/for_those_who_cant_sign_in/
> 
> Can @alicerrrrs verify that if similar steps work?

On Android, the sign-in pages for all the Reddit clients with issues are not in an in-app browser but rather a webview. I don't know if it's possible to put a webview in desktop mode.

Here is a demonstration in Infinity:

https://github.com/ReVanced/revanced-patches/assets/84587632/9e4e90f3-c1f5-4c7f-83f2-6e86360008ca

**Comment by alicerrrrs** [comment]
> This is not a normal response from Reddit, quite likely an issue on their end

As oSumAtrIX said, it was on reddit I guess.
I successfully logined with Joey and Sync at 07:30 JST.
Hope other apps are good to go too.



> > Discord user `asztro` suggested the following:
> > > The issue of {} error of sync reddit can be fixed if desktop version of the authorization screen can be enabled. Similar issue occured to Apollo and I found a post regarding that.
> > 
> > 
> > > https://www.reddit.com/r/apolloapp/comments/1931cc4/for_those_who_cant_sign_in/
> > 
> > 
> > Can @alicerrrrs verify that if similar steps work?
> 
> On Android, the sign-in pages for all the Reddit clients with issues are not in an in-app browser but rather a webview. I don't know if it's possible to put a webview in desktop mode. (Although I'm pretty sure asztro's idea would work since RIF uses the desktop login page which works.)
> 
> Here is a demonstration of me trying to somehow enable the desktop site in Infinity:
> 
>  Screen_Recording_20240110_113334_Infinity.mp4

Same situation for Joey and Sync too, can't switch to desktop mode.

**Comment by oSumAtrIX** [comment]
And so can I

**Comment by zouhair** [comment]
I just stopped caring and just use https://github.com/QuantumBadger/RedReader
