### ISSUE TITLE
bug:  Full Screen Ad For Shorts

### ISSUE THREAD

**Issue by myselflatu** [revanced/revanced-patches#2610]
### Type

Cosmetic

### Bug description

So got a shorts ad today thought of reporting.

### Steps to reproduce

Opened Revanced Got This Popup.

### Relevant log output

```shell
N A
```

### Screenshots or videos

![Screenshot_20230710-151348](https://github.com/revanced/revanced-patches/assets/40817763/bc6a7fd2-0547-4808-9aac-c23dcded012b)

### Solution

N A

### Additional context

N A

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [ ] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Fill necessary fields properly
