### ISSUE TITLE
bug(YouTube Vanced - Hide ads): Remove patch

### ISSUE THREAD

**Issue by Bceez** [ReVanced/revanced-patches#2611]
### Bug description

YouTube Vanced is discontinued and will likely completely stop working in the next few weeks or months. It is not worth it to support an application that will stop working soon. Additionally video playback doesn't work for the majority of people on YouTube Vanced anymore.

### Solution

Remove the "Hide ads" patch

### Additional context

https://revanced.app/patches?pkg=com.vanced.android.youtube

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
When you mount it, it will still continue to work. As the app doesn't update, so doesn't the patch, therefore there isn't much benefit of removing the patch

**Comment by Bceez** [comment]
The "Update your app" screen will appear in the new future and it seems like that it already started to appear to some people. See[this post](https://www.reddit.com/r/AfterVanced/comments/18zx92b/vanced_is_officially_unusable_anymore/) on Reddit

**Comment by johnconner122** [comment]
> The "Update your app" screen will appear in the new future and it seems like that it already started to appear to some people. See [this post](https://www.reddit.com/r/AfterVanced/comments/18zx92b/vanced_is_officially_unusable_anymore/) on Reddit

This activity can be modified. This might also show with version spoofing(I haven't seen it though). 

![Screenshot_2024-01-14-17-39-11-952-edit_bin mt plus](https://github.com/ReVanced/revanced-patches/assets/107796137/b1d85115-890c-46d3-80be-3e2b74481dbd)

**Comment by userunknown358** [comment]
> > The "Update your app" screen will appear in the new future and it seems like that it already started to appear to some people. See [this post](https://www.reddit.com/r/AfterVanced/comments/18zx92b/vanced_is_officially_unusable_anymore/) on Reddit
> 
> This activity can be modified. This might also show with version spoofing(I haven't seen it though).
> 
> ![Screenshot_2024-01-14-17-39-11-952-edit_bin mt plus](https://github.com/ReVanced/revanced-patches/assets/107796137/b1d85115-890c-46d3-80be-3e2b74481dbd)

Where is this located?
