### ISSUE TITLE
feat(reddit): Add removed home feed sort controls

### ISSUE THREAD

**Issue by mjtimblin** [revanced/revanced-patches#2611]
### Application

Reddit

### Issue

Reddit removed the home feed sort controls in favor of always sorting by best.

https://old.reddit.com/r/reddit/comments/zmo8hm/the_feed_read_chapter_two_take_control_of_your/

### Patch

I would like to see the removed home feed sort controls (rising, controversial, top) added to the official reddit app. I personally prefer sorting by top of last 24 hours, but all the missing sort options would be ideal.

### Motivation

The official reddit app used to have the functionality, but it was removed. With the recent killing of 3rd party apps, this was the first annoying missing feature I noticed when switching to the official app. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
I have the option to do different sorting. Not sure what you mean.

**Comment by mjtimblin** [comment]
@oSumAtrIX  What version of the app are you using? The [reddit link](https://old.reddit.com/r/reddit/comments/zmo8hm/the_feed_read_chapter_two_take_control_of_your/) I included above is a post by a reddit admin explaining the new home feed sorting methods (as of December 2022). The current version of the reddit app only lets you sort your feed by best (the default "Home" option) and "Latest". The "Popular" option does not apply to the home feed.

**Comment by oSumAtrIX** [comment]
![Screenshot_2023-07-10-18-53-51-64_b72a20be883aec8a014bd2b7c7038e87](https://github.com/revanced/revanced-patches/assets/13122796/7b5792ce-2da8-452e-bc22-df71f0337f4b)
The latest

**Comment by mjtimblin** [comment]
Exactly. Those are the same options as I have. The app is missing the options to sort the home feed by controversial, rising, and top. Those used to be options prior to December 2022.
