### ISSUE TITLE
Lightroom masking files won't download. 

### ISSUE THREAD

**Issue by paradowskidm** [ReVanced/revanced-patches#2613]
### Bug description

When trying to create a subject or sky mask you have to download the modules for first use. The download fails.  It seems you need to log in to be able to do this. When patched, you cannot log in. 

### Solution

Allow sign in and download should work. 

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Login works after patching. There is merely a patch to circumvent the requirement to.
