### ISSUE TITLE
feat: (YouTube) Profanity filter

### ISSUE THREAD

**Issue by han5enar** [ReVanced/revanced-patches#2614]
### Feature description

The profanity filter is based off a list of banned words that can be edited in the settings. When a banned word is found in the text of a video title, description, comment, etc. it gets replaced with a substitute word (Ex: dog --> cat).

Another hypothetical feature of this is it can look through the auto generated youtube subtitles on a video (if available) and automatically mutes the video for the duration that a banned word is detected. (For example, if the word "dog" is banned, when it detects that word it mutes the video and stays muted until the next non-banned word in the captions). Also, since auto generated subtitles sometimes already pre-censor words with "[ _ ]", it would just treat that as another banned word.

A problem with this is that you would have to keep the subtitles on the video at all times, but I feel like a possible solution could be to have it automatically turn on subtitles on every video, but make the subtitles completely invisible, so the filter can still see the words. Then, if you want to turn on subtitles, you could press the subtitles button in the video player and it would just change the visibility of the subtitles to be the default settings or whatever settings you had it set to. Same with turning them off; it would just make them invisible again.

If a reference is needed, the creator of the Advanced Profanity Filter chrome extension explains how this works: [APF wiki](https://github.com/FrostCo/AdvancedProfanityFilter/wiki)
![Profanity filter settings concept](https://github.com/ReVanced/revanced-patches/assets/155386429/bd873db0-c67c-4063-8698-eac3cb5f5db2)
![Profanity filter concept 5-5](https://github.com/ReVanced/revanced-patches/assets/155386429/afde6e3f-9546-428f-95dd-b268b5d5cea7)

Also, something I noticed recently, OpenAI has an AI called Whisper which can very accurately transcribe any audio you put into it. People have made some example projects with inserting a direct youtube link and getting subtitles from it using Whisper: [for example](https://app.subtitlewhisper.com/). This would solve a lot of the problems that auto generated youtube subtitles have, but it would require some extra steps to get it implemented and such. This could be an entirely separate patch on its own for better subtitles, and this patch would utilize that, but I just noticed this and I'm putting it out there as a possibility. Here's a link for [more example projects utilizing Whisper](https://github.com/openai/whisper/discussions/categories/show-and-tell?discussions_q=is%3Aopen+category%3A%22Show+and+tell%22+youtube&page=1)

Thanks
### Motivation

I feel like this feature would really be nice for people like me who just would rather not have to deal with stuff like that. I get that this might be a little too complicated for something that not enough people might utilize, but it would definitely be great if I could just watch a video without hearing the f word every .1 milliseconds. 
It could also be helpful for people wanting to show videos to their parents or younger siblings without having to worry about that. I usually just use a chrome extension to filter out videos that are a little too spicy, but on mobile that doesn't exist yet, so that's why im suggesting something like this here.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
This patch would need a hook to read the captions or use the YouTube API to retrieve it for the current video. In such a case, it could skip over the time where the word is said. How did you make your mockup imags?

**Comment by han5enar** [comment]
I wasn't really thinking of using the youtube API but rather using the text from the subtitles that are being "displayed" on screen, because with this I think it could be rigged up so that it detects the words in the client as the subtitles go on. I don't really know if that would actually be even remotely possible, but in theory it would keep the timeframe in which the words are being said.

Also i just screenshotted sections of the settings in the app and used paint.net to make the mockup images lol

**Comment by oSumAtrIX** [comment]
> Also i just screenshotted sections of the settings in the app and used paint.net to make the mockup images

Thats neat.

Regarding the implementation, using the API means an additional (unnecessary API request, but luckily, it can be asynchronous as the filter isn't usually required immediately). Resorting to a hook in the app that returns the subtitles would spare that request, but needs additional reverse engineering to find.

**Comment by han5enar** [comment]
>Resorting to a hook in the app that returns the subtitles would spare that request, but needs additional reverse engineering to find.

I see. I'm hoping that wouldn't be too difficult to do, but it would be fine without the whole video censoring thing if it gets too complicated or takes too much time to do

**Comment by ego-lay-atman-bay** [comment]
I actually support this feature request. I would love to see this implemented in some way (and I'm now gonna use that browser extension on desktop).

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!

**Comment by S3KiR0** [comment]
Someone should make this as a reality, censorship is getting ridiculous
