### ISSUE TITLE
feat: age restriction bypass 2

### ISSUE THREAD

**Issue by fillwithjoy1** [ReVanced/revanced-patches#2615]
> and we can get this feature added

@fillwithjoy1 Are you going to implement this patch?  You are more than welcome to create this patch yourself and create a pull request to merge.

Since the age restriction is applied server side, this feature will likely be very difficult or even impossible to implement as a patch.

_Originally posted by @LisoUseInAIKyrios in https://github.com/ReVanced/revanced-patches/issues/127#issuecomment-1891003735_

I don't know much about kotlin but I do understand how this works https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass which bypasses it, check it out.

**Comment by oSumAtrIX** [comment]
For discussions move to https://github.com/ReVanced/revanced-discussions/discussions
