### ISSUE TITLE
Remove Reddit Account Suspended banner 

### ISSUE THREAD

**Issue by PottiMc** [ReVanced/revanced-patches#2617]
### Feature description

Is there a way to get rid of that "Your account has been permanently suspended" like in the screenshot below?

Target application would be Reddit Extended

![Screenshot_20240115-153310~2](https://github.com/ReVanced/revanced-patches/assets/39881308/a50508f3-2162-4940-9949-aabf97f25f26)

### Motivation

The benefit is you get rid of that banner which is displayed forever and is pretty annoying.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
This is ReVanced
