### ISSUE TITLE
Bug(YouTube) Hide navigation bar not working

### ISSUE THREAD

**Issue by RaWolFoX** [ReVanced/revanced-patches#2618]
### Type

Cosmetic

### Bug description

No effect after enabling shorts component > hide navigation bar. Its not hiding navigation bar.Tried on multiple devices. 

### Steps to reproduce

1. Open shorts
2. Observe navigation bar area

### Relevant log output

```shell
Can't provide now.
```

### Additional context

YouTube version : 18.23.35
Patch version : 2.184.0
Root : no
Tested on : android 11(oppo), android 13(Samsung)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [ ] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by darkrain261** [comment]
It seems that the issue still persists with the latest version of patches 2.187.0 and Youtube version 18.23.35
