### ISSUE TITLE
bug: custom-playback-speed patch not working

### ISSUE THREAD

**Issue by TheJeterLP** [revanced/revanced-patches#262]
### Type

Error at runtime

### Bug description

So the custom-playback-speed Patch is currently not functional. The setting itself does get saved (see startup log for what values from settings get loaded)

### Steps to reproduce

Open settings, change preferred video speed, doesn't do anything

### Relevant log output

```shell
No log output
```

### Solution

Fix the custom+playback-speed patch so it uses the set value.

**Comment by TheJeterLP** [comment]
probably @bogadana can fix this easily

**Comment by bogadana** [comment]
not my patch (does it even exist?)

**Comment by Canny1913** [comment]
![Screenshot_20220731-223956_Chrome](https://user-images.githubusercontent.com/94744045/182042451-287de013-c041-488a-8f9b-7a86a76ff055.png)
:questionable:

**Comment by bogadana** [comment]
no such thing as preferred video speed in this patch

**Comment by TheJeterLP** [comment]
> no such thing as preferred video speed in this patch

I changed the title

**Comment by TheJeterLP** [comment]
> no such thing as preferred video speed in this patch

Isn't this exactly what the patch is supposed to do?

**Comment by bogadana** [comment]
nope

**Comment by bogadana** [comment]
this is what its supposed to do 
![image](https://user-images.githubusercontent.com/30848157/182042624-bc54d997-6b1f-400d-8c43-3a85efbb074d.png)

**Comment by Canny1913** [comment]
> > no such thing as preferred video speed in this patch
> 
> Isn't this exactly what the patch is supposed to do?

yeah this patch unlocks more video speeds instead of setting a preferred one

could be modified to do both

**Comment by bogadana** [comment]
the intent was to have the speeds customisable in the settings but i honestly cant care anymore

**Comment by oSumAtrIX** [comment]
@bogadana Is doing the correct thing. This way a settings page is not required. It is better to simply save it there automatically instead of having to go to the settings to change it.

**Comment by Canny1913** [comment]
> @bogadana Is doing the correct thing. This way a settings page is not required. It is better to simply save it there automatically instead of having to go to the settings to change it.

if yt speed works similarly to video quality its pretty ez to do

**Comment by TheJeterLP** [comment]
> @bogadana Is doing the correct thing. This way a settings page is not required. It is better to simply save it there automatically instead of having to go to the settings to change it. 

The patch doesn't save the last set value tho

**Comment by bogadana** [comment]
not what its intended for

**Comment by oSumAtrIX** [comment]
Does it have feature parity with Vanced is the question. If Vanced saved it in the settings this functionality should be added to the menu too. @Canny1913 saves the last selected quality too, for consistency, this can be added too and as @Canny1913 said, it should not be too difficult.

**Comment by TheJeterLP** [comment]
> Does it have feature parity with Vanced is the question. If Vanced saved it in the settings this functionality should be added to the menu too. @Canny1913 saves the last selected quality too, for consistency, this can be added too and as @Canny1913 said, it should not be too difficult.

I agree. Vanced had this feature and this should get implemented into this patch too. The setting in the revanced_prefs.xml can be removed then. Same goes to the code for that in the SettingsFragment. I can do that tomorrow if you want.

**Comment by oSumAtrIX** [comment]
I am planning on reworking the settings patch into a framework but I do not know what you all are planning to add or remove, hence I will wait for now for you to finish the remaining issues. Please @ me whenever I can start refactoring the patch into said framework.

**Comment by TheJeterLP** [comment]
> I am planning on reworking the settings patch into a framework but I do not know what you all are planning to add or remove, hence I will wait for now for you to finish the remaining issues. Please @ me whenever I can start refactoring the patch into said framework.

No, then I won't add or remove anything. Just start with your framework

**Comment by oSumAtrIX** [comment]
Alright, I will branch off the latest commit then.

**Comment by smonsec** [comment]
Any work on that, its pretty frustrating to adjust speed everytime, prefered video speed currently does nothing to make it consistent.

**Comment by Canny1913** [comment]
> Any work on that, its pretty frustrating to adjust speed everytime, prefered video speed currently does nothing to make it consistent.

I'm working on it currently.

**Comment by smonsec** [comment]
> > Any work on that, its pretty frustrating to adjust speed everytime, prefered video speed currently does nothing to make it consistent.
> 
> I'm working on it currently.

Great, more power to you.

**Comment by crazdrama** [comment]
> > Any work on that, its pretty frustrating to adjust speed everytime, prefered video speed currently does nothing to make it consistent.
> 
> I'm working on it currently.

would it be possible to add more speed steps btw 2x and 4x...like 2.25x, 2.5x, 2.75x etc??

**Comment by oSumAtrIX** [comment]
> would it be possible to add more speed steps btw 2x and 4x...like 2.25x, 2.5x, 2.75x etc??

Via patch options later on.

**Comment by Akv2021** [comment]
> > Any work on that, its pretty frustrating to adjust speed everytime, prefered video speed currently does nothing to make it consistent.
> 
> I'm working on it currently.

This is definitely a useful tweak. Is it still in progress ?

**Comment by Canny1913** [comment]
> > > Any work on that, its pretty frustrating to adjust speed everytime, prefered video speed currently does nothing to make it consistent.
> > 
> > 
> > I'm working on it currently.
> 
> This is definitely a useful tweak. Is it still in progress ?

Patch has some issues currently but yes.

**Comment by Akv2021** [comment]
> > This is definitely a useful tweak. Is it still in progress ?
> 
> Patch has some issues currently but yes.

Waiting eagerly for the fix :) Would you like to share any updates ?

**Comment by TheJeterLP** [comment]
Closed as regarding setting is not existing anymore.
