### ISSUE TITLE
feat: X/Twitter that can download video

### ISSUE THREAD

**Issue by Jheremy13th** [ReVanced/revanced-patches#2622]
### Feature description

Make it a new patch or X/twitter that can easy download the video post like Aerotwitter
![Screenshot_20240116-225341](https://github.com/ReVanced/revanced-patches/assets/45528236/65c0babd-7db4-4536-9d0c-a8242fd84660)
![Screenshot_20240116-231459](https://github.com/ReVanced/revanced-patches/assets/45528236/a540eb00-4605-41ce-abad-b1e43defa318)

### Motivation

the dev of Aerotwitter are abandon the project almost 6 month.
They have bug now that can't see quotes other people

### Acknowledgements

- [ ] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by uvzen** [comment]
Someone created revanced patches for twitter which supports downloading videos (works as if you had premium: long press on video and download), google ads patch and remove view count patch.  Can ReVanced team add this to their patch list?

**Comment by oSumAtrIX** [comment]
Patches are designed to work side by side. You can use both bundles at the same time but if @crimera wants, we can include it in our bundle.

**Comment by crimera** [comment]
It would be cool if you guys include it to the official bundle.

**Comment by oSumAtrIX** [comment]
That's cool. Most work involved in developing patches is regarded as reverse engineering, whereas implementing them takes the least amount of time. Thanks for your contribution. I'd be up to committing it here, but if you want you can open a PR and be the author of the commit.

**Comment by crimera** [comment]
I don't really have much experience in git so I will let you take over in this.

**Comment by Jheremy13th** [comment]
@crimera wait.. How to patcg it if possible to local patch this? 😅

**Comment by oSumAtrIX** [comment]
This is not a support channel, move to somewhere else

**Comment by oSumAtrIX** [comment]
@crimera Added https://github.com/ReVanced/revanced-patches/compare/884c5ea1b3cb...2c20844eaae6. The downloads patch had to be done differently so that it works on any video
