### ISSUE TITLE
feat: filter YouTube shorts by blacklisting a keyword or hashtags 

### ISSUE THREAD

**Issue by Matszwe02** [revanced/revanced-patches#2622]
### Application

YouTube

### Issue

Many YouTube videos have in their titles "wait for the end" or "#fyp", and these videos are trash 

### Patch

Allow user to be able to type in a list of keywords in a blacklist so shorts with these keywords will be ommited when loading shorts in feed 

### Motivation

YouTube shorts algorithm being crap 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
#2113
