### ISSUE TITLE
feat:(YouTube) Add reproduce next in line function 

### ISSUE THREAD

**Issue by Loya13** [revanced/revanced-patches#2623]
### Application

YouTube Revanced

### Issue

Reproduce next in line is now possible on the YouTube app for Android too! But this is a YouTube premium function 

### Patch

I would like to see this function implemented in YouTube revanced 
![IMG_20230713_031439](https://github.com/revanced/revanced-patches/assets/139411880/8fe5b58c-9eb0-4458-a773-c34a69740c1f)

### Motivation

I think it's an interesting feature to add

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
#2175
