### ISSUE TITLE
feat(patch): For official reddit app

### ISSUE THREAD

**Issue by TakiShiwa** [ReVanced/revanced-patches#2624]
### Application

Official Reddit app

### Issue

When I click on a link in the official Reddit app, it opens up an inbuilt browser within the app itself. Unfortunately, I'm required to log in again to use this browser, and even the Play Store links don't open in the actual Play Store. I'm suggesting to develop a patch that would allow the links to open in external apps or a separate browser.

### Patch

The purpose of this patch is to enhance the user experience by enabling them to open links in an external app or browser instead of being limited to the inbuilt app browser. By implementing this patch, users will have the freedom to choose their preferred app or browser for accessing the content.

### Motivation

As you may be aware, the pricing of Reddit's API has resulted in numerous developers either completely or partially shutting down their apps. This situation has led to a significant influx of users to the official Reddit app, thereby causing the issue of the inbuilt app browser. Given that we are uncertain about the extent of tracking that Reddit employs within their inbuilt browser, it becomes crucial to prioritize the development of a solution for this problem.

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
#1860

**Comment by abunasar** [comment]
Why is this closed as completed? It's not completed at all.
