### ISSUE TITLE
feat [piccoma.fr]: Allow screenshot in app

### ISSUE THREAD

**Issue by Starmania** [ReVanced/revanced-patches#2625]
### Feature description

App: com.piccomaeurope.fr (limited to France)

### Motivation

Do not block the user from taking screenshots. Also allow the user to use insecure screen.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by Starmania** [comment]
I think I can do it myself if it's ok with contributing guidelines

**Comment by oSumAtrIX** [comment]
Closing since the patch already exists for any app
