### ISSUE TITLE
feat (ytmusic): `Customizable App Name`

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [revanced/revanced-patches#2626]
### Application

YT Music

### Issue

Currently, YT Music lacks several customization features that could greatly enhance user experience and personalization within the music streaming platform. I would like to propose the implementation of several theming and customization options for YT Music, similar to the features available in the YouTube app.

### Patch

Provide the ability to customize the name of the app, similar to the YouTube app. Users should be able to change the app name to "YT Music" or "YT Music ReVanced" or any other desired name. This customization feature adds a personal touch and aligns with the user's preferences.

### Motivation

By implementing these theming and customization options, YT Music will offer users greater control over their experience and allow them to tailor the app according to their preferences. These enhancements will contribute to a more personalized and enjoyable music streaming experience overall.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by ILoveOpenSourceApplications** [comment]
> This issue should be closed in favour of a "change app name patch" for any app

Is there already such a patch request or should I open one? But even so, this change can only be used by CLI users, at least for now. Right?

**Comment by oSumAtrIX** [comment]
You can check if an issue exists for it already using search. It would be implemented via patch options.

**Comment by ILoveOpenSourceApplications** [comment]
> You can check if an issue exists for it already using search.

No
> It would be implemented via patch options.

Which would require CLI?

**Comment by oSumAtrIX** [comment]
Wym no, you can.

Patch options don't require CLI, no

**Comment by oSumAtrIX** [comment]
ReVanced Manager does not support patch options.

**Comment by ILoveOpenSourceApplications** [comment]
Yes, so is it supported via Revancify?

**Comment by oSumAtrIX** [comment]
Revancify is not from us, ask in the respective place

**Comment by ILoveOpenSourceApplications** [comment]
Then I don't see anyway for someone without a windows system to use a `change app name' patch if implemented, just like all the custom name or icon patches.

**Comment by oSumAtrIX** [comment]
The CLI works on any system, not just windows. Additionally this is a problemof ReVanced Manager, not patches.

**Comment by ILoveOpenSourceApplications** [comment]
True. It should be a feature request under ReVanced Manager.
