### ISSUE TITLE
feat (ytmusic): `Icon Customization`

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [ReVanced/revanced-patches#2627]
### Application

YT Music

### Issue

Currently, YT Music lacks several customization features that could greatly enhance user experience and personalization within the music streaming platform. I would like to propose the implementation of several theming and customization options for YT Music, similar to the features available in the YouTube app.

### Patch

Although there is currently no ReVanced music icon available, it would be beneficial to include an option to change the app icon in the future. Users can then choose from a selection of community-made icons or even upload their own icon to further personalize their YT Music experience.

### Motivation

By implementing these theming and customization options, YT Music will offer users greater control over their experience and allow them to tailor the app according to their preferences. These enhancements will contribute to a more personalized and enjoyable music streaming experience overall.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by PandoraPandorita** [comment]
I feel a universal "custom branding" feature would be doable, but yeah, yt music really needs it

**Comment by oSumAtrIX** [comment]
Moving to https://github.com/ReVanced/revanced-patches/issues/2936
