### ISSUE TITLE
bug: Sync Pro unable to log-in due to error "Please match the required type"

### ISSUE THREAD

**Issue by rktfier** [ReVanced/revanced-patches#2628]
### Bug description

Hello there, after patching Sync Pro on my new phone, I'm unable to log-in to the app due to an error message that blocks me from clicking the "Log In" button. 

Step 1# Try to login
Step 2# error message pops up.

I can swear that i got a different login screen one time with a black background but it failed due to setting the "redirect uri" to 127.0.0.1 instead of "http://redditsync/auth" and after i fixed it, it seems like i could never get the same screen again.

### Error logs

```shell
https://streamable.com/09thoa
```

### Additional context

I tried deleting the first characters of both my username and password just in case it was a input validation, same issue occurs.
I attempted to put my 2FA code with my password (<passwd>:<2fa>) but it didn't work.

I own Sync Pro on Play Store, the steps i took to patch this application is :
1# Download the app through Play Store
2# back up the APKS file
3# turn the APKS file into APK using AntiSplit-G2
4# put the file in through the ReVanced Manager
5# uninstall gplay app, install the patched version

Reason for using AntiSplit-G2:
ReVanced Manager seems to not have the ability to patch split APK files. Whenever I tried to select the app and patch it directly, my app would constantly crash without being able to see the main menu. I saw on an issue that they were able to use this and get it working again (which at the time it did also fix my issue)

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Not sure what you are doing but the oAuth application doesn't match the one that is mentioned in the patches description as your title suggests.

**Comment by rktfier** [comment]
Sorry, I couldn't understand what you meant.  My oauth application is set as "Installed App" and redirects to "http://redditsync/auth" as Spoof client patch suggests, and I've provided my client key during the patch.

**Comment by oSumAtrIX** [comment]
The bug you are showing in your recording is not caused by the patch, reload the login page

**Comment by rktfier** [comment]
I have reloaded the login page multiple times (press back, then attempt to log-in again as webview doesn't have the ability to refresh the page), I've got the same result.

**Comment by oSumAtrIX** [comment]
That page is funniky. I can reproduce it as well but solve it the way I mentioned. If that doesn't work, please move to a support channel as this is not an issue that concerns ReVanced or the client spoof patch

**Comment by rktfier** [comment]
Is your mentioned method is to refresh the page, because I don't see a way to refresh the login page inside the webview.

If it's about the oauth application, I think everything looks correct:
![image](https://github.com/ReVanced/revanced-patches/assets/75695425/3ef43ce0-ebb2-430a-9d76-7c0ae729e598)
I put the "id" under my application name as my oauth client key.

**Comment by KobeW50** [comment]
This issue comes up when the credentials are pasted into the text boxes or auto-filled. Refresh the page and enter the login credentials manually.
