### ISSUE TITLE
feat (ytmusic): `Minimized Player Color`

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [revanced/revanced-patches#2628]
### Application

YT Music

### Issue

Currently, YT Music lacks several customization features that could greatly enhance user experience and personalization within the music streaming platform. I would like to propose the implementation of several theming and customization options for YT Music, similar to the features available in the YouTube app.

### Patch

Introduce an option to customize the color of the minimized player to match the theme of the music playing in full-screen mode. This feature ensures consistency in the user interface and provides a seamless transition between different views.

### Motivation

By implementing these theming and customization options, YT Music will offer users greater control over their experience and allow them to tailor the app according to their preferences. These enhancements will contribute to a more personalized and enjoyable music streaming experience overall.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
The motivation is too overgeneralized. The feature does not bring any additional benefit. The miniplayer changes the color to the amoled background which is matching

**Comment by ILoveOpenSourceApplications** [comment]
Video showing the issue mentioned above:

https://github.com/revanced/revanced-patches/assets/117499019/b0501f91-42a7-4946-81f8-610389367685

Notice how it stays the same color as album style, then reverts to the nav bar color. By implementing this patch, that transition will be more fluid.

**Comment by ILoveOpenSourceApplications** [comment]
Considering how minimized player is something related to the full screen player, I feel it should follow the same theme as the full screen player, transitioning between both feels fluid and the user can enjoy the change in color of the album art in the minimized player as well. And if the user is someone who like minimalistic looks, they can choose not to enable this option leaving them with the black themed minimized player.

**Comment by oSumAtrIX** [comment]
Again, this is too much of a small inconvenience. If that was a valid patch request, why not request to change the button size by 2px? The issue is too insignificant.

**Comment by ILoveOpenSourceApplications** [comment]
Everything is a small inconvenience. And having to face such small inconsistencies everyday is the issue. Why add sponsorblock when the user can just skip away, it's just multiple taps. Why add hide buttons, when you can  just not touch the buttons/ just don't look at them.

**Comment by oSumAtrIX** [comment]
> I never mentioned hide ads as a small inconvenience

Here is an implicit metion from you of it:

> Everything is a small inconvenience.


SponsroBlock is not a minor inconvenience because you have to consume the video before you are able to know that it's a sponsored segment. 

> It's not like we do a polling before implementing a patch.

A patch request remains a request at the end of the day. Technically I can even stop doing that and close any request that I personally don't like, though I provide requestors the ability to reason their requests and consider them if they are reasonable. Coloring the minimized playback is too insignificant

**Comment by ILoveOpenSourceApplications** [comment]
> > I never mentioned hide ads as a small inconvenience
> 
> Here is an implicit metion from you of it:
> 
> > Everything is a small inconvenience.

I never said it specifically. When I said everything I didn't think that  ads as an app element will be considered.
> 
> SponsroBlock is not a minor inconvenience because you have to consume the video before you are able to know that it's a sponsored segment.

Most sponsored segments starts with mentioning that it's sponsored, I don't see why one needs to watch it fully to understand that it's a sponsored segment.
> 
> > It's not like we do a polling before implementing a patch.
> 
> A patch request remains a request at the end of the day. Technically I can even stop doing that and close any request that I personally don't like, though I provide requestors the ability to reason their requests and consider them if they are reasonable. Coloring the minimized playback is too insignificant

Yes and as an user I appreciate that the patch requests are being considered. But shooting it down as too insignificant can not be justified. If mass requires the same and appreciates it then it isn't insignificant.

**Comment by oSumAtrIX** [comment]
> I never said it specifically. When I said everything I didn't think that ads as an app element will be considered.

Everything means everything and everything will be considered.

> Most sponsored segments starts with mentioning that it's sponsored, I don't see why one needs to watch it fully to understand that it's a sponsored segment.

Firstival, most means not all. Second sponsorblock is able to block more than just sponsored segments.

> But shooting it down as too insignificant can not be justified.

It is justified though. I explained above why it was closed and "why" is a justification.

> If mass requires the same and appreciates it then it isn't insignificant.

I don't see mass asking for this

**Comment by ILoveOpenSourceApplications** [comment]
> I don't see mass asking for this

Wouldn't letting this patch request open can only those who wants this can show their support? If not they'll have to open their own individual patch request which can also be taken down for similar reasons.

**Comment by ILoveOpenSourceApplications** [comment]
Anyway, I feel this patch implementation would be good UI addition which YouTube should have added but hasn't and I requested for the same here. If it's not that much significant, well let the issue remain closed
