### ISSUE TITLE
feat (ytmusic): `Hide New Playlist Button`

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [revanced/revanced-patches#2630]
### Application

YT Music 

### Issue

Currently, YT Music lacks several customization features that could greatly enhance user experience and personalization within the music streaming platform. I would like to propose the implementation of several theming and customization options for YT Music, similar to the features available in the YouTube app.

### Patch

Add an option to hide the "New Playlist" button in the library section. This feature would be beneficial for users who prefer to manage their playlists in other ways and want a cleaner interface without unnecessary buttons.

### Motivation

By implementing these theming and customization options, YT Music will offer users greater control over their experience and allow them to tailor the app according to their preferences. These enhancements will contribute to a more personalized and enjoyable music streaming experience overall.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
The button doesn't obstruct any view nor is it constantly in your way when you try to use the app

**Comment by ILoveOpenSourceApplications** [comment]
> The button doesn't obstruct any view

I object against this. If the user is having multiple playlists with multiple songs in them, then this button can obstruct the song count in the playlist.

**Comment by oSumAtrIX** [comment]
Send a picture showing the issue

**Comment by ILoveOpenSourceApplications** [comment]
See how the number of songs in the playlist gets hidden due to the button.
![IMG-20230713-WA0000~3](https://github.com/revanced/revanced-patches/assets/117499019/0332ba7d-2d7f-48f5-9205-99e523f12c4c)

**Comment by oSumAtrIX** [comment]
Scroll down

**Comment by ILoveOpenSourceApplications** [comment]
> Scroll down

That's a bizzare thing to say. Most of the patches for YouTube can be avoided if the user decides to scroll down/scroll away. Then why implement patches to hide those things in the first place. `Hide watch in VR` is a very good example for this.

**Comment by ILoveOpenSourceApplications** [comment]
Then what about `hide floating microphone button`. Yes there was another microphone option present. But here also the user can add the song to playlist via various other methods. So I still don't see why it feels unnecessary.

Also if the user scrolls to see the number of songs in one playlist, it will continue to obstruct another playlist.

**Comment by oSumAtrIX** [comment]
> Then what about hide floating microphone button. 

Because many people reuqested it. It is a useless patch

**Comment by ILoveOpenSourceApplications** [comment]
> Because many people requested it. It is a useless patch

Demand and supply.

> No, you don't view the library patch to accumulate the amount of songs in a playlist. And if so, you simply scroll down.

There can be situations where if you have multiple (say 20-30) playlist and your checking your song collection in each playlist. I would say without this button that procedure would be more useful.

Also like I said before, nobody uses that playlist button as most user will be adding their tracks when listening to it via that method of add to playlist. So I don't see any particular usage to that button and any significance rather than being an obstruction to large playlist listeners.

**Comment by ILoveOpenSourceApplications** [comment]
Everything can be simply scrolled away from. It's like saying if you have a problem in life just move on. 

Also may I ask why you asked me to open these individual patch requests in the first place if you were planning to close them all as "small inconvenience" & "just scroll down".

**Comment by ILoveOpenSourceApplications** [comment]
I have no further comments. Thanks for your valuable time.
