### ISSUE TITLE
Youtube queue,

### ISSUE THREAD

**Issue by GalaxyVOID** [revanced/revanced-patches#2635]
### Application

Youtube

### Issue

![Screenshot_20230713_220903](https://github.com/revanced/revanced-patches/assets/94946192/bd978441-336c-4c4e-99ec-6e00ccc42c03)

### Patch

Make it work for free, without the need of premium, just like on desktop/website

### Motivation

We wouldn't need to make playlists just to have a queue. 

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
#1735

**Comment by GalaxyVOID** [comment]
This is a bit different since the feature is here, but it needs premium to use. The other requests requested for the feature to be implemented

**Comment by oSumAtrIX** [comment]
The requested feature is queueing. Doesn't matter the implementation
