### ISSUE TITLE
feat: Sweeping censoring of thumbnails for selected channels

### ISSUE THREAD

**Issue by spectrolit** [ReVanced/revanced-patches#2635]
### Feature description

A feature that allows users to select channels as having videos with a trigger thumbnail so that if one of the videos of that channel appears in the user's viewing history or as a search suggestion or in any other context the thumbnail of the video will be hidden. The user will have the option to edit the list of disturbing channels through the application settings and will have the option to make the list global for all accounts connected to the same device, and will also have the option to use this feature in anonymous mode without connecting with a Google account.

### Motivation

For some people this feature seems unimportant, but there are many people for whom exposure to certain images can cause serious shock and even nightmares. Imagine for a moment that you are in bed and you plan to go to sleep in a few minutes and you want to watch one last video before going to sleep and you are looking for something on YouTube and while you are scrolling through the results The search you encounter a thumbnail of a body dismembered good luck falling asleep after such a thing. This feature answers the problem that the "not interesting" feature is not available while looking at search results and it is also not available for those who have not connected with a Google/YouTube account. My feature would be a great solution for people who don't want to look at annoying thumbnails but still want the video to appear as an option.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
The trigger exists and it's called scroll down. #1899

**Comment by spectrolit** [comment]
> The trigger exists and it's done by swiping up in the feed. #1899 If you need to hide thumbnails you can do via a custom filter for all videos, just for selected hardly makes any sense

I would be happy if you send me a link that explains how to put a filter, The reason I want to block selected channels is because there are some videos that appear in the search results all the time even though they have nothing to do with my search and I have no idea how to get rid of them

**Comment by oSumAtrIX** [comment]
You can block channels on Youtube natively, apart from that refer to #1899
