### ISSUE TITLE
feat: Filter irrelevant results from search. Search is almost unusable and is NSFW, derails flow and sucks away from relevant work.

### ISSUE THREAD

**Issue by StacktraceException** [ReVanced/revanced-patches#2639]
### Feature description

This is a huge problem. because always about only 4 first results may be relevant and then there are lots of distracting results designed to suck attention away from current task.  and then a few more relevant and then another section of "watch again", "recommended for you" and/or other irrelevant crap.

I checked the custom filters page and so far found no solution anywhere for android apart from maybe using web browser (like Kiwi Browser which allows any extensions, thank the devs), with ublock or other extension instead of the app. 

Regards.

### Motivation

Search is almost unusable and is NSFW, derails flow and sucks away from relevant work. Too many traps designed to generate clicks and suck attention.  

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Patch already exists https://github.com/ReVanced/revanced-patches/pull/1/commits/55cc7f1c7722f56af6d33ea2bd09a1b99d635209

**Comment by oSumAtrIX** [comment]
The patch is not released and this issue is a duplicate of another

**Comment by oSumAtrIX** [comment]
Seems like the other issue is closed, opening this one
