### ISSUE TITLE
bug(youtube): cannot zoom to fill videos in watch later playlist 

### ISSUE THREAD

**Issue by Murabitos** [ReVanced/revanced-patches#2640]
### Type

Other

### Bug description

Title is all. Just happened during normal usage. My device is a note 20 ultra. 

### Steps to reproduce

Try to zoom in to videos that you've clicked on from your watch later playlist. You can't zoom in. 

### Relevant log output

```shell
?
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
I was able to reproduce the issue. A combination of patches may have caused this or the client spoof patch

**Comment by KobeW50** [comment]
Sometimes this happens after spoofing the app version, and clearing the app data/cache is required.

**Comment by oSumAtrIX** [comment]
Moving to #1752
