### ISSUE TITLE
Changelog for 4.0.1 missing changes as 4.0.0 was a pre-release

### ISSUE THREAD

**Issue by Shazzkid** [ReVanced/revanced-patches#2645]
### Bug description

Since 4.0.0 had the full changelog, but was just a pre-release, the latest official release, 4.0.1 is missing all the changes in the changelog from the last official release, 3.2.0.

Might be worth adding it as an amendment section to show the changelog upto 4.0.0 aswell in the 4.0.1 release. 

Edit: Just noticed you've changed 4.0.0 from pre-release to just a regular release. Although technically you released 4.0.1 before 4.0.0, so the changelog is still likely to be missed by many.  Still worth updating the changelog. 

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by Shazzkid** [comment]
Closing as you've just changed 4.0.0 from pre-release to just a regular release

**Comment by oSumAtrIX** [comment]
This is not an issue. The changelogs, as they are, now belong to their respective release and since its automatically generated we shouldn't touch it. The next version of ReVanced Manager will show changelogs in the app.
