### ISSUE TITLE
Don't add feed auto plays to watch history 

### ISSUE THREAD

**Issue by Etothetaui** [ReVanced/revanced-patches#2646]
### Application

Youtube

### Issue

When scrolling through my feed, pausing on a video makes it auto play silently. I like this because it helps me preview the video without clicking on it and watching it.

What I don't like is that this marks the video as watched and adds it to my watch history. This means it is less likely recommended to me in the future. Also it means that Google will recommend me similar things. 

I would like to leave the auto play in feed on, but for those videos that start playing silently in my feed to not be registered as watched.

### Patch

I want silent auto play in feed enabled but for the videos to not be marked as watched.

### Motivation

Other people might find that these videos marked as watched ruins their experience on YouTube.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Moving to #1752
