### ISSUE TITLE
bug: YouTube ReVanced crashes at 5:20pm EST everyday

### ISSUE THREAD

**Issue by alexsch01** [ReVanced/revanced-patches#2647]
### Type

Error at runtime

### Bug description

YouTube ReVanced crashes at around 5:20pm EST every day I use the app at that time

### Steps to reproduce

I'm just watching a video and it crashes at the time I put above.

### Relevant log output

**YouTube version: 18.23.35
ReVanced Patches version: v2.184.0
Using suggested patches**

```shell
No logs
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
This is Play Protect scanning and killing the process. Nothing that can be done except using a different package name.

**Comment by alexsch01** [comment]
> This is Play Protect scanning and killing the process. Nothing that can be done except using a different package name.

Is this Google targeting ReVanced users?
