### ISSUE TITLE
bug: [Tiktok] Downloaded images fail to embed

### ISSUE THREAD

**Issue by Aura-Dacella** [ReVanced/revanced-patches#2648]
### Bug description

Images downloaded from tiktok slideshows with watermark removed fail to embed when uploaded to discord.  

1. Verify watermark removal setting is enabled
2. Download any single slideshow image
3. Upload to discord and force close discord to see what other users will see. An image file that isn't embedded.
4. Turn off watermark remover setting and redownload the same image
5. Upload it to discord and force close
6. Image with watermark should stay embedded correctly

### Solution

Workaround: Resize image in gallery fixes embed issue on the resized image

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
This is not a downloader/ReVanced issue and instead a Discord one.
