### ISSUE TITLE
Pepper - Remove that excessive tracking on deals

### ISSUE THREAD

**Issue by Roki100** [ReVanced/revanced-patches#2648]
### Application

Pepper (they have multiple apps for different regions https://play.google.com/store/apps/dev?id=8446582273966180590)

### Issue

The deals (go to deal button) includes excessive amount of tracking redirect urls, sometimes even 4 for one deal apperantly, this is hilarious

### Patch

Bypass tracking and go to the actual deal directly

### Motivation

Privacy is a right, and such excessive tracking has to be stopped

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
What does the URL look like?

**Comment by Roki100** [comment]
> What does the URL look like?
> 

for example: https://www.pepper.pl/visit/threadmain/698744
https://www.pepper.pl/visit/threadmain/697182

**Comment by oSumAtrIX** [comment]
Is the actual link visible in the app?
