### ISSUE TITLE
feat: Reddit Sync: Patch for Reddit's new "/s/" links?

### ISSUE THREAD

**Issue by youngbab** [ReVanced/revanced-patches#2650]
### Feature description

Reddit seems to have certain links that trigger a 404 in Reddit Sync.

A post from reddit with lots of upvotes and comments experiencing the same issue.
https://www.reddit.com/r/revancedapp/comments/18wzwya/reddit_sync_patch_for_reddits_new_s_links/

Thank you in advance for any help!

### Motivation

It's completely broken half of the external or even self referenced links within Reddit itself.
Would Make Reddit Sync absolutely bug free again.

Thank you in advance for any help!

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by kieraneglin** [comment]
If anyone's interested in taking this on, I'll offer a $50 USD bounty (via PayPal) for whoever can implement this

**Comment by oSumAtrIX** [comment]
@kieraneglin I have finished the patch and would like to claim the bounty. Please DM me at osumatrix@revanced.app

https://github.com/ReVanced/revanced-patches/assets/13122796/9aa4d2f2-0425-4c40-b022-f108007ddc0e

**Comment by kieraneglin** [comment]
@oSumAtrIX wow, that was quick! Is this patch available on revanced for me to confirm?

**Comment by oSumAtrIX** [comment]
No, I have not pushed the patch yet, but sent a video for reference

**Comment by kieraneglin** [comment]
Got it. I've sent you an email to get your details, but as soon as there's a PR I can look (or similar) I will fulfill the bounty!

**Comment by kieraneglin** [comment]
Bounty fulfilled! Thank you for your good work

**Comment by youngbab** [comment]
@oSumAtrIX Thank you for the quick work! When will this likely be available in the revanced manager?

@kieraneglin Thanks so much for putting up the bounty! Wish I had mentioned the Imgur albums failing to load properly now...

**Comment by WoundedBum** [comment]
Sorry to be stupid, is the patch available? Would be so handy!

**Comment by raulvasquez** [comment]
Is this easily ported to other 3rd party Reddit clients? Specifically boost - this was requested in #478 

https://github.com/ReVanced/revanced-patches/issues/478

**Comment by patel-jeel92** [comment]
Hi is this patch available in revanced manager

**Comment by oSumAtrIX** [comment]
Yes.
