### ISSUE TITLE
bug: YouTube 18.49.37 crash after patch

### ISSUE THREAD

**Issue by yonggamer** [ReVanced/revanced-patches#2653]
### Bug description

YouTube 18.49.37 crash after patch

### Additional context

- Device Info
ReVanced Manager: 1.18.0
Model: SM-G965F
Android version: 10
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.google.android.youtube v18.49.37 (Suggested: v19.03.35)
Patches version: v4.0.1
Patches added: Default
Patches removed: Hide ads, Copy video URL, Remove viewer discretion dialog, External downloads, Disable precise seeking gesture, Seekbar tapping, Swipe controls, Disable auto captions, Hide video action buttons, Hide autoplay button, Hide captions button, Hide cast button, Navigation buttons, Hide player buttons, Hide album cards, Hide breaking news shelf, Comments, Hide crowdfunding box, Hide endscreen cards, Hide filter bar, Hide floating microphone button, Disable fullscreen ambient mode, Hide layout components, Hide info cards, Hide 'Load more' button, Player flyout menu, Disable rolling number animations, Hide seekbar, Hide Shorts components, Disable suggested video end screen, Hide timestamp, Disable player popup panels, Custom player overlay opacity, Return YouTube Dislike, Wide searchbar, Restore old seekbar thumbnails, SponsorBlock, Spoof app version, Change start page, Disable resuming Shorts on startup, Enable tablet layout, Tablet mini player, Theme, Alternative thumbnails, Announcements, Always repeat, Enable debugging, Spoof device dimensions, Bypass URL redirects, Minimized playback, Remove tracking query parameter, Disable zoom haptics, HDR auto brightness, Remember video quality, Playback speed, Restore old video quality menu, Open links externally
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Copying APK
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing patches
Applied 4 patches
Compiling patched dex files
Compiled 8 dex files
Compiling modified resources
Signing APK
Patched APK

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Please use the default settings in ReVanced Manager. Reopen the issue and send crash logs if it still occurs using logcat and grep for AndroidRuntime. Likely dupe issue
