### ISSUE TITLE
bug:(YouTube) Splash screen logo as not changed with custom branding 

### ISSUE THREAD

**Issue by xDARKxDEVILx** [ReVanced/revanced-patches#2654]
### Type

Cosmetic

### Bug description

Using YouTube version 18.23.35 and latest patches version and custom branding patch, the splash screen logo is the YouTube logo instead of the new ReVanced logo

### Steps to reproduce

Patch YouTube
Use default patches or less and include custom branding patch 

### Relevant log output

```shell
None
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [ ] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Not reproducible. Include all information about your device and all steps in a new issue
