### ISSUE TITLE
feat(YouTube): Disable push notifications limit

### ISSUE THREAD

**Issue by 111ebobo** [ReVanced/revanced-patches#2658]
### Feature description

YouTube has a notification limit, as for now the limit is 5 notifications if the sixth notification comes up it automatically closes the first one, so it will be better if you can remove this limit and I could see many of them without automatic closure (this is not a phone thing because telegram can show hundreds of notifications)

### Motivation

This feature will be important for those people who is saving notifications for opening them later

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by 111ebobo** [comment]
> This is something your phone OS and/or your launcher is doing.  It's not something that can be changed by patching an app.
> 
> Search and maybe your launcher has options for the maximum number of notifications to show.

The launcher didn't do this, because I have seen the same thing on my old phone, also how do you explain that other apps can have more notifications and not close themselves?

**Comment by 111ebobo** [comment]
> This is something your phone OS and/or your launcher is doing.  It's not something that can be changed by patching an app.
> 
> Search and maybe your launcher has options for the maximum number of notifications to show.

Also launchers do not operate the notifications

**Comment by 111ebobo** [comment]
> This is something your phone OS and/or your launcher is doing.  It's not something that can be changed by patching an app.
> 
> Search and maybe your launcher has options for the maximum number of notifications to show.

@LisoUseInAIKyrios

**Comment by 111ebobo** [comment]
> This is something your phone OS and/or your launcher is doing.  It's not something that can be changed by patching an app.
> 
> Search and maybe your launcher has options for the maximum number of notifications to show.

Also I have googled that YouTube actually does have a notification limit

**Comment by oSumAtrIX** [comment]
If this holds truth, you can still see all notifications in-app

**Comment by 111ebobo** [comment]
> If this holds truth, you can still see all notifications in-app 

But I want to save videos which i am planning to watch in the notification bar because in app it would be hard to find them because of Livestream notifications or comment related notifications

**Comment by oSumAtrIX** [comment]
I am not sure if spoofing reading the notification would have any effect in case there's actually a limit, but I'll reopen the issue just for the sake of us not knowing for now until we can say with certainty, that in fact notifications are being limited. Of course it may be likely an attempt of YouTube to animate the user opening the app.

**Comment by 111ebobo** [comment]
Quick update, it's not a limit of 5, it's closing notifications because it's keeping unread for a long time, btw it wasn't such a thing in android 4, but I don't think that os does it because other apps can show much more

**Comment by oSumAtrIX** [comment]
I am suspecting the OS killing the app in the background, I can get notifications over your limit. You will have to resolve this issue with your OS/battery optimization on your end. Reopen if clearly not the case.

**Comment by 111ebobo** [comment]
> I am suspecting the OS killing the app in the background, I can get notifications over your limit. You will have to resolve this issue with your OS/battery optimization on your end. Reopen if clearly not the case.

Look, not all notifications disappear one getting replaced by the other one also as I said, in a way worse phone with android 4.4 it doesn't happen at all, plus other apps are able to keep way more of them. Also you haven't read my previous comment where I've said that it's getting replaced after a long time (approximately 18hrs)

**Comment by 111ebobo** [comment]
> > I am suspecting the OS killing the app in the background, I can get notifications over your limit. You will have to resolve this issue with your OS/battery optimization on your end. Reopen if clearly not the case.
> 
> Look, not all notifications disappear one getting replaced by the other one also as I said, in a way worse phone with android 4.4 it doesn't happen at all, plus other apps are able to keep way more of them. Also you haven't read my previous comment where I've said that it's getting replaced after a long time (approximately 18hrs)

Because today I have got more that 5 notifications, so it closes it if it's staying for too long

**Comment by oSumAtrIX** [comment]
It doesn't matter if it didn't occur in Android 4.4. Other apps are other apps, your OS handles them differently. I've read your previous comment. My previous comment was an answer to it. Without clear evidence and proper ground to what you claim, we can't work on.

**Comment by 111ebobo** [comment]
> It doesn't matter if it didn't occur in Android 4.4. Other apps are other apps, your OS handles them differently. I've read your previous comment. My previous comment was an answer to it. Without clear evidence and proper ground to what you claim, we can't work on it.

Sorry but I can't catch that exact moment when I have many yt notifications and the oldest of them closing by itself for the new one, if the os killed the app, all of the notifications should be gone (it was happening in My Android 7 phone) but instead the oldest one is replaced by the newest one and that oldest was in status bar for 18+ hours

**Comment by oSumAtrIX** [comment]
If what you say is true, 18h is long enough for this patch to not be relevant anymore

**Comment by 111ebobo** [comment]
> If what you say is true, 18h is long enough for this patch to not be relevant anymore

But why? I want my YouTube notifications to be shown till that time when I will open them, if I didn't have internet for 2 days I want to see hundreds of notifications instead of the recent ones, for example, or I can get notification at 2 am and open and watch that video at 8 pm directly from notification instead of going into the app and look for that video there
