### ISSUE TITLE
feat: ishredder `enterprise paid unlocked`

### ISSUE THREAD

**Issue by cyberboh** [ReVanced/revanced-patches#2658]
### Application

https://play.google.com/store/apps/details?id=com.projectstar.ishredder.android.standard

### Issue

free version only offer shredd data below 100 mb and cant select all shredd methods

### Patch

unlock all paid features inside app

### Motivation

so we can use all paid featires without restrictions

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [ ] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Insufficient motivation
