### ISSUE TITLE
feat: [Youtube/Sponsorblock] Skip segments when connected to TV

### ISSUE THREAD

**Issue by JKamsker** [ReVanced/revanced-patches#2660]
### Feature description

YouTube Vanced should have the ability to skip segments on connected devices such as Apple TV, Android TV, and Firestick.

### Motivation

When YouTube Revanced is connected to the TV, SponsorBlock does not skip segments on the TV.
It would be nice if the app could skip segments on the connected device.
Installing a modded YouTube client is not an option on Apple TV devices.

### Acknowledgements

- [ ] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
https://github.com/ReVanced/revanced-patches/issues/374
