### ISSUE TITLE
feat(YouTube): Hide podcasts in the home feed

### ISSUE THREAD

**Issue by Bottomfard6127** [ReVanced/revanced-patches#2663]
### Feature description

Just a simple option to hide podcast in the home feed
![Screenshot_2024_0129_195711](https://github.com/ReVanced/revanced-patches/assets/126884197/69794475-d611-4e53-b2cc-04c549dfe140)

### Motivation

Its kinda annoying to constantly see this type of playlist in the homepage, especially when I already got used to mixes being hidden

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by Bottomfard6127** [comment]
If you want more reference on how annoying this stuff, this is the state of my home feed ever since this stuff appeared:
![Screenshot_2024_0129_201117](https://github.com/ReVanced/revanced-patches/assets/126884197/770687ca-14d5-439f-aec2-4dab1fa85e44)

**Comment by oSumAtrIX** [comment]
Since the feed consists of the same components, you'd either hide the child component too late or be unable to distinguish between other feed items. The constructed view groups by Litho contain strings visible on the screen, which could technically be used to hide the views.

**Comment by oSumAtrIX** [comment]
I was referring to strings after the views being constructed. ViewGroups are nested and flattened Yoga artifacts from what I have understood, so you do not have access to say the text without rendering the ViewGroups again, but you can access them and their children fairly granular as they resemble the same structure as the path builder string. Iirc calling toString on those views will sometimes return the string they are displaying so that would be a useful way to filter.

**Comment by Bottomfard6127** [comment]
> A proto buffer filter likely would work, but currently the custom filter does not support that. But adding support would be fairly simple.
> 
> The only question is how to present it in the settings, and figure out some kind of syntax to indicate a path _and_ the protobuffer string that appear with the path. That could be as simple as using a $ or # character to separate the parts, ie: `home_feed_whatever_path$Podcast`

Well I wouldn't mind too if the hide podcast will hide it altogether in other fields such as in any channel page or something like that, cause some people like me ever use that.

**Comment by oSumAtrIX** [comment]
Considering that, maybe a custom preference, similar to a list preference that takes two inputs, one for the path and one for strings and filters accordingly could be made later so that we don't need to use a custom string syntax.

**Comment by Bottomfard6127** [comment]
But is it possible to just outright hide podcast similar to mixes?

**Comment by Bottomfard6127** [comment]
> > But is it possible to just outright hide podcast similar to mixes?
> 
> I cannot say myself, because I cannot get any podcast mixes to show up in the home feed or search.

I see, so we will just have to wait and see?

**Comment by Bottomfard6127** [comment]
> > I see, so we will just have to wait and see?
> 
> Yes

Okay that's reassuring thanks for looking this up too

**Comment by Bottomfard6127** [comment]
Hello @LisoUseInAIKyrios I tried the custom filter string to hide the podcast mix but it didn't work, although it did hide those videos or channel names with podcast in them but the mix playlist with podcast on them is still there in the homepage

**Comment by oSumAtrIX** [comment]
I can not see any podcasts on my end, so I'll need access to an account that does. Contact me at osumatrix@revanced.app

**Comment by oSumAtrIX** [comment]
Yes, just reopen the issue once it comes up again, closing until then.
