### ISSUE TITLE
bug: X Adblock patch does not work

### ISSUE THREAD

**Issue by Pratik-193** [ReVanced/revanced-patches#2664]
### Bug description

Last patch for X does not block ads on the latest x version

### Solution

The patch should be able to block all ads

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by Bceez** [comment]
https://github.com/ReVanced/revanced-patches/issues/1733
