### ISSUE TITLE
feat: word replacement rules, remove gendering

### ISSUE THREAD

**Issue by Resa595** [ReVanced/revanced-patches#2665]
### Application

Spotify (at least German Version)

But also other apps that use „gender sensitive language“ like TikTok and Browser apps that display websites with gendering should change the words to normal language 

### Issue

In Germany and other country's gender ideological language is practiced by a few big company's and so is now part of their applications, like Spotify. Many users are quite unhappy, that Spotify changed the normal language to complicated and ugly gendering. Gendering is not part of the German language but people at the moment have no choice to turn off that political language.

### Patch

I request a patch, that changes specific words, following predefined rules in all languag data of the app and also makes the app change these words/strings, while loading text from the internet (a big part of the language data of Spotify isn't part of the app, but actually loaded from online, while loading new information). So the patched app should not display specific words and instead use other words. These rules for example could be defined in a text file, that the patch uses, to programm the new language rules for a specific language, like so: 
"german:
Apfel -> Banane
Freund*innen -> Freunde
Follower_innen -> Follower
Künstler:innen -> Künstler
HörerInnen -> Zuhörer
*innen ->
deine*m Freund*in -> deinem Freund"

The rules should follow a hierarchy, using the first listed rule, if more than one rule applies. So it should change Freund*innen to Freunde (rule 2) and not to Freund (rule 6).

Also the app should detect specific Symbols and strings in new sentences and add this sentences to the text File, so the user can define new rules for these phrases, like so:
"german
[...]
deine*m Freund*in -> deinem Freund

look for these strings:
*
_
:
/
In

found:
Entdecke eine*n neue*n Musiker*in
Deine LieblingskünstlerInnen!"

If there are no strings to look for defined in the text file, this functionality must not be a part of the app, so the app is as small and efficient as possible. The patch than should simply leave out this function, instead of looking for an empty list of strings.

If the patch works like discribed, it can also handle other word changes (not only gendering) and works for any language.

### Motivation

There are many situations, that make it helpful, to be able to change different strings displayed by an application, into other strings. 
The biggest use would be, to reestablish normal language on the phone, for people, that are anointed by political language, explicitly so called gender sensitive language, as very popular in germany at the time. I have many friends, family and colleagues, that would be very glad to use this opportunity, to change there beloved apps back to normal language. His is popular problem on country's with political language changes, to which there isn't any solution at the time. Spotify is the application most discussed in Germany considering this subject. 
The second app, that could profit from language change rules are Webbrowsers, like Chrome, as many website also use gendering. Many of my friends and I would be most thankful, if you could help us get back our native language on our Spotify and our phones.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
I don't see how removing the gender suffix changes the behaviour of the app. It may be annoying to you, but it doesn't really cause any problem or needs any patch.
