### ISSUE TITLE
bug: Youtube - Fullscreen startup ads started showing up again on 19.03.35

### ISSUE THREAD

**Issue by Domiiniik** [ReVanced/revanced-patches#2667]
### Bug description

Youtube - Fullscreen "Try Premium" startup ads started showing up again on 19.03.35 despite "Hide Fullscreen ads" toggle being on.
Screenshot for the reference:
![Screenshot_20240129_154004_YouTube](https://github.com/ReVanced/revanced-patches/assets/30195961/a6ec1517-c0cc-41bd-8bbe-fb2341a50df7)

### Solution

Fix

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Use logcat to log the path builder string that shows up when the fullscreen ad is shown following this:

<img width="383" alt="image" src="https://github.com/ReVanced/revanced-patches/assets/13122796/cbfb2a08-828a-4ef2-b987-e33623d25b4f">

**Comment by Domiiniik** [comment]
No, no toast message at all, and secondly, no i don't have a computer. : \

**Comment by oSumAtrIX** [comment]
Wrapping the event call in a new thread should solve the issue.
