### ISSUE TITLE
feat: Add a custom filter for the library menu

### ISSUE THREAD

**Issue by Spaceshiprace** [ReVanced/revanced-patches#2668]
### Feature description

Yo, I wish if there was a filter to hide some of those that I don't even find useful just like : Help & feedback, Your clips, Your movies

![Screenshot_2024-01-29-19-43-07-747_app revanced android youtube_1](https://github.com/ReVanced/revanced-patches/assets/156727749/63b520ef-54ab-4ab7-8b1d-ccfe9501bb07)

### Motivation

- some of them not aren't useful
- The library would look better without em
at the end you decide (just if you want plz)

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
https://github.com/ReVanced/revanced-patches/issues/1929

**Comment by Spaceshiprace** [comment]
sorry again, I didn't see it but I still have a question is it will be a feature any time soon ?
