### ISSUE TITLE
feat: Replace the YT startup logo with ReVanced logo

### ISSUE THREAD

**Issue by Spaceshiprace** [ReVanced/revanced-patches#2669]
### Feature description

So I find out that The Header logo replaced with ReVanced Logo And I said why not the same thing for the yt startup logo
![Screenshot_2024-01-29-20-19-56-473_app revanced android youtube_1](https://github.com/ReVanced/revanced-patches/assets/156727749/7d70c716-5a40-4de2-a555-93caab2e7066)

### Motivation

ReVanced logo looks better than yt's logo so it would be better

### Acknowledgements

- [ ] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
https://github.com/ReVanced/revanced-patches/issues/584
