### ISSUE TITLE
bug: dark black theme popup not working as expected

### ISSUE THREAD

**Issue by i6jm** [revanced/revanced-patches#267]
### Type

Other

### Bug description

When I choose the dark black theme, and I write a response to one of the clips and I want to select the words, the pop-up window appears black and I can’t see (select all-copy-paste-search..etc)

### Steps to reproduce

Choose the black theme and select the words when you reply, you will not see the words of the pop-up window 

### Relevant log output

```shell
black theme
```

### Screenshots or videos

![Screenshot_20220801_050548_app revanced android youtube](https://user-images.githubusercontent.com/57762287/182059793-3f222207-ba16-415c-ad41-54113214b691.jpg)
![Screenshot_20220801_050329_app revanced android youtube](https://user-images.githubusercontent.com/57762287/182059804-4151fdeb-8f2a-4ce1-aed5-889f3fd53796.jpg)

### Solution

The solution is to choose the white theme and this problem does not appear, also this problem is old even in YouTube Vanced, so it is there

### Additional context

Huawei P30
Android 10
EMUI 12.0

**Comment by oSumAtrIX** [comment]
I have tried in Vanced and I don't have this issue.

**Comment by i6jm** [comment]
@oSumAtrIX Is it because of the Huawei interface?
Because I was also facing this problem in Vanced, and I was surprised that it continues even in Revansed!

**Comment by i6jm** [comment]
@oSumAtrIX 
In the Android settings, If i choose black theme, I noticed that there is no problem with Revanced with dark black theme.
The problem only appears when the Android settings are in Light Theme and Revanced in dark black theme.
I hope the problem is clear to you now

**Comment by oSumAtrIX** [comment]
What is dark black theme. Send the command you run which causes the issue and the command which does not cause the issue.

**Comment by i6jm** [comment]
@oSumAtrIX 
I explained it in two videos 
https://media-upload.net/file/n7jmLiAFu94_

https://media-upload.net/file/IAgFi9B8s6xq

**Comment by oSumAtrIX** [comment]
Has this been solved?

**Comment by i6jm** [comment]
> Has this been solved?

no

**Comment by oSumAtrIX** [comment]
Did you update?

**Comment by i6jm** [comment]
> Did you update?

Yes, the problem persists even with the latest update

**Comment by ILoveOpenSourceApplications** [comment]
What about now?

**Comment by ILoveOpenSourceApplications** [comment]
Since there's no new reports and isn't showing up anymore, I believe it's fixed.
