### ISSUE TITLE
bug: (YouTube Music/MicroG support): can't share the stories to Facebook, Instagram and Snapchat)

### ISSUE THREAD

**Issue by djlivooo** [ReVanced/revanced-patches#2671]
### Bug description

I can't share songs via Instagram Stories, Facebook Stories or Snapchat. When I try to send it, the option appears, I hit that option, it loads, but does nothing. It stays there in YT Music. In the original app this error does not happen. Is there a solution?

Steps for this error:

1. Open YT Music Revanced

2. Select a song.

3. Press the "Share" option

4. Select Instagram, Facebook or Snapchat.

5. Nothing happens, the option should redirect me to Instagram Stories, Facebook Stories or Snapchat.

https://github.com/ReVanced/revanced-patches/assets/98977517/e938643f-d12c-45b1-9c4c-f1f01876196b

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
https://github.com/ReVanced/revanced-patches/issues/55

**Comment by djlivooo** [comment]
> #55

A big question, there's a solution for this?
Or for now, we have to wait?

**Comment by dhtzs** [comment]
Sharing on Instagram via patched YouTube Music aplication won't work for me either, yet it works normally when using the non-patched application.

OS: Android 13 (One UI 6.0)
Device: Galaxy S23
Youtube Music version: 6.40.52
