### ISSUE TITLE
feat: (Youtube) Feature to hide video, featured videos, thumbnails etc.

### ISSUE THREAD

**Issue by KingMahmud** [ReVanced/revanced-patches#2673]
### Feature description

This useful chrome extension needs a "revanced" version :D!

https://chromewebstore.google.com/detail/music-mode-for-youtube/abbpaepbpakcpipajigmlpnhlnbennna

Feature details, images can be found in the link above.

### Motivation

<img src="https://lh3.googleusercontent.com/HsrSUlJ6bHp6Y8Bw1F9eaxxy6NmPsvKODBkJ0mWPliZmJJoWog13jS46rY141jZfY6h8otkoH34-qyc5dwivdjcwFQ=s1280-w1280-h800">

<img src="https://lh3.googleusercontent.com/xdcs3e6VkuqHUwkOYbv-dNvO1SxLLZSZwLrLuxcWhEaujlM-OzVzQ7AGNx7Mz0x0mee_d5kypd2lWeCHO6ostMUizg=s1280-w1280-h800">

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
You can hide thumbnails with a custom filter using "thumbnails"
