### ISSUE TITLE
feat(YTMusic): SponsorBlock for podcasts

### ISSUE THREAD

**Issue by AlaskaJedi** [ReVanced/revanced-patches#2673]
### Application

YT Music

### Issue

YT music now contains 'Podcasts' which are just youtube playlists in the music app, embedded ads that would be skipped by sponsor block when watching the video in youtube are not skipped. 

### Patch

Sponsor block for yt music.  

### Motivation

It would offer a better experience when using the new podcasts feature.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Yeah, it doesn't seem worth the effort. Closing therefor.
