### ISSUE TITLE
bug: (YouTube 19.03.35) Banner ads showing with error message

### ISSUE THREAD

**Issue by cyberboh** [ReVanced/revanced-patches#2674]
### Bug description

Sometimes whenever I opening YouTube, banner ads appear with error message. The banner ads shoing randomly.
See screenshot for detail of error message

![Pics](https://github.com/ReVanced/revanced-patches/assets/99109969/8a9ab04c-e3c1-49d0-bfea-4aa949dda1d8)

### Additional context

Patched with CLI
```
java -jar revanced-cli-4.4.0-all.jar patch -p -o Install\YouTube_19.03.35-all_ReVanced.apk --options options.json -b revanced-patches-4.0.3-dev.1.jar --alias=***** --keystore-password=***** --keystore-entry-password=***** --keystore=*****.keystore -m revanced-integrations-1.2.2-dev.2.apk Apps\com.google.android.youtube-19.03.35-all.apk -i "Change header"
```

Latest Patches and Integrations stable. Tested also in dev version, still occuring.

### Acknowledgements

- [ ] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
https://github.com/ReVanced/revanced-patches/issues/2667

**Comment by leandroprz** [comment]
I'm also experiencing this issue with v19.04.37:

![Screenshot_20240220_011059](https://github.com/ReVanced/revanced-patches/assets/1398896/b4a63b75-b5f7-4837-aed8-59ce15158f9b)
