### ISSUE TITLE
bug:  Infinity for reddit subscription bug

### ISSUE THREAD

**Issue by TheWitch69** [ReVanced/revanced-patches#2678]
### Bug description

App is patched without bugs but when i install and log in Sub tab appear. Bug only on version 7.0.0, older version for now work okey
![Screenshot_20240131_084618_Infinity](https://github.com/ReVanced/revanced-patches/assets/131497172/b4e17f0b-f2ff-43ff-b815-a6ac3c03e6c0)

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
What's the last working version

**Comment by TheWitch69** [comment]
> What's the last working version

6.7.3

**Comment by oSumAtrIX** [comment]
I'll constrain the patch to that version. The app is actively being developed and I feel like the the app is being patched more to unlock the subscription than being able to use the app. The last working version will continue to work, but if you want updates, you can simply sub to Infinity or use any other patchable client

**Comment by TheWitch69** [comment]
> I'll constrain the patch to that version. The app is actively being developed and I feel like the the app is being patched more to unlock the subscription than being able to use the app. The last working version will continue to work, but if you want updates, you can simply sub to Infinity or use any other patchable client

Its ok no problem but one question. There will be no new versions for infinity in the future from revanced?

**Comment by oSumAtrIX** [comment]
Is the latest version even working properly?

**Comment by oSumAtrIX** [comment]
6.7.1 is not the latest version

**Comment by SnakeSK** [comment]
> I'll constrain the patch to that version. The app is actively being developed and I feel like the the app is being patched more to unlock the subscription than being able to use the app. The last working version will continue to work, but if you want updates, you can simply sub to Infinity or use any other patchable client

Why this hostility? The dev is adding features and closed the eyes from his app being patched and him earning money, him updating the app is no different than youtube updating the app and adding features.

And of course he will change some code that the patch wont catch, same as youtube may change something in their code and the new patch has to be created.

**Comment by oSumAtrIX** [comment]
This is not hostility. If at all, a premium unlock patch is hostile. The dev has not closed an eye to it. The patch is discontinued as per contribution guidelines protocol.

**Comment by oSumAtrIX** [comment]
I decided to bump it one more time for the sake of supporting the new version v7, once it stops working I'll discontinue the patch. bf19af99cb522f9027a4b3ae42d6258ac71758e

**Comment by SnakeSK** [comment]
Damn thats a lot of code, iam not into android development but to me it looks like he implemented checks and different activity?

Thank you for the fix

**Comment by oSumAtrIX** [comment]
No, the point of open source is to grant transparency and accept contributions and not to be taken advantage of.
