### ISSUE TITLE
Microsoft outlook mail app

### ISSUE THREAD

**Issue by binarygeek119** [ReVanced/revanced-patches#2678]
### Application

Microsoft outlook mail app 

### Issue

Ads and can't swap left to delete only archive 

### Patch

Remove ads from within app.
Allow deletion of mail by left and/or right swap

### Motivation

Love the app other then the ads and delete issue I have with it

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
You can use any other mail app that can do that
