### ISSUE TITLE
bug: Messenger v440+ Disable switching emoji to sticker

### ISSUE THREAD

**Issue by nightznero** [ReVanced/revanced-patches#2679]
### Bug description

Patch `Disable switching emoji to sticker` doesn't work on stables versions of Messenger since v440,latest working is v439.
Tested on 439(working) 440,441,442(not working). I was testing only stable versions idk how bout beta/alpha.

### Solution

properly patching or adding a note that Patch is disabled since X version

### Acknowledgements

- [ ] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
#14

**Comment by kazimmt** [comment]
@oSumAtrIX after A/B testing is over, #14 isn't the correct issue I guess.
The patch also needs to be bump
because:
![image](https://github.com/ReVanced/revanced-patches/assets/82371061/56a74bd7-6f51-4702-8abe-2a0b9e8dc692)
