### ISSUE TITLE
bug: Nyx Music Player v2.2.7

### ISSUE THREAD

**Issue by Morsmalleo** [ReVanced/revanced-patches#2681]
## <div align="center">Bug description</div>

1. I can't save edits made to the metadata/tag info of a track/song.
    - If I try updating the metadata/tag info of a song/track, a toast saying `No audio header found within <track title>`. See the screenshot titled *"No Audio Header Toast When Editing Track Info"* in the drop down menu in the screenshots section of this report for the error it throws.

    - If I try updating the metadata/tag Info for an album, I am greeted with an error telling me the 0 files were changed, see the screenshot in the drop down menu titled *"Error message when editing album info"* in the "Screenshots" section of this report for the error it throws.

2. It tells me there is no Internet connection when I'm trying update the metadata/tag info for an album or song, when there is, see the screenshot in the drop down menu titled *"No Internet Bug"* in the "Screenshots" section of this report.

3. Doesn't let me use the Equaliser

    - If I turn on Use System Equaliser and tap *"Open Default Equaliser"* nothing happens,

    - If I Turn Off *"Use System Equaliser"* and tap *"Open Default Equaliser"* the Nyx Equaliser flashes for 1 or 2 seconds and backs out back to the Settings.

    - If I switch between *"Normal"* or *"Fix"* in the *"Equaliser Mode"* option and then tap *"Use System Equaliser"* for with either option set, the same behaviour as describe above happens, the equalisers flashes for about 1 or 2 seconds and then backs out back to the Settings.

#
## <div align="center">Steps to reproduce the behavior:</div>

1. Download and Install Nyx ReVanced from the ReVanced Manager
2. Open Nyx Music Player
3. Try to open the Nyx Equaliser and/or change metadata/ tag info for tracks or albums
4. See the problem with the Equaliser opening, the no internet bug, and/or the errors when editing metadata/tag info

#
## <div align="center">Expected behavior</div>

- I should be able to successfully set edit the track or album Info and use the equaliser, without problems.

#
## <div align="center">Screenshots</div>

<div align="center">
    <details>
        <summary>"No Audio Header" Toast when Editing Track Info</summary>

![300239319-e208b112-ade6-4fc9-9056-e1c29a77b0b5](https://github.com/ReVanced/revanced-patches/assets/64344168/21ea630f-26c1-4c50-974e-8a3e13245e27)
    </details>
</div>

<div align="center">
    <details>
        <summary>Error Message When Editing Album Info</summary>

![300238970-ebb4a92c-b778-42ea-820e-a6da3bc1e53a](https://github.com/ReVanced/revanced-patches/assets/64344168/570f3dec-441f-4cb3-b0cf-0bbfb9185b47)
    </details>
</div>

<div align="center">
    <details>
        <summary>No Internet Bug</summary>

![300239053-3d09c16f-a8bd-4d8f-8a48-ad8b2d032340](https://github.com/ReVanced/revanced-patches/assets/64344168/6ce4b554-2232-4ea4-bb83-b24aa1fd4f40)
    </details>
</div>

#
## <div align="center">Smartphone:</div>
- Device: Vivo Y11S
- OS: Android 12

PS: If this is to much I'd be happy to split these issues up.

### Error logs

```shell
I didn't know this was required, if it is SOLELY required for reporting bugs, I'll get to it immediately.

However the version of the Nyx Music Player installed via ReVanced Manager is 2.7.7 (latest)
```

### Solution

None found.

### Additional context

None to give.

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
They mentioned version 2.7.7 implying they used something that isn't by us. The official website is https://revanced.app. Reopen once issues occur with our patches

**Comment by KobeW50** [comment]
> They mentioned version 2.7.7 being latest hinting they used something that isn't by us. The official website is https://revanced.app. Reopen once issues occur with our patches

They were mentioning the version of nyx. 2.7.7 is the suggested version.

![SmartSelect_20240131_090920_ReVanced Manager.jpg](https://github.com/ReVanced/revanced-patches/assets/84587632/6f0c854b-8696-4167-9313-d4278d400dbd)

**Comment by oSumAtrIX** [comment]
They're free to respond in this case

**Comment by Morsmalleo** [comment]
> > Download and Install Nyx ReVanced from the ReVanced Manager
> 
> Are you downloading an already patched app from the "manager" or are you using the [real ReVanced Manager](https://github.com/ReVanced/revanced-manager/releases/latest) and patching the app yourself?

Sorry I was very busy, I installed Nyx Music Player via the actual ReVanced Manager itself, I haven't installed any patches myself
