### ISSUE TITLE
Issue: ReVanced YT Music does not work with Android Auto

### ISSUE THREAD

**Issue by drshtmstry** [ReVanced/revanced-patches#2683]
### Bug description

![IMG20240201080630](https://github.com/ReVanced/revanced-patches/assets/155899372/e27d6af6-96af-43cb-bc93-66a72c09f5ca)
![Screenshot_2024-02-01-09-54-04-05_a85b47aaa863e3bc831e16d29c27a79c](https://github.com/ReVanced/revanced-patches/assets/155899372/34667f99-ea85-4549-9ee8-1ede57509898)

Unknown sources allowed in Developers settings of Android Auto.

### Acknowledgements

- [ ] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
https://github.com/ReVanced/revanced-patches/issues/1182
