### ISSUE TITLE
"Action" button

### ISSUE THREAD

**Issue by jezokshe** [ReVanced/revanced-patches#2684]
### Application

2.184.3

### Issue

Remove unnecessary button "remixes", without deleting the desired "share"!  There, under the player.  It's super illogical to combine such different functions.  There have been a lot of strange things like this lately... Now they are removed together if you disable revanced>buttons under the player>action buttons in the settings. 
P.S I don't know if it depends on the patch, or if the author of the build did it this way.

### Patch

Separate the visibility of the share and remix functions

### Motivation

It's logical and convenient.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
YouTube combines both buttons under the same component name. Both are removed simultaneously because there is currently no way to distinguish them.
