### ISSUE TITLE
Can you make a tv version of revanced app

### ISSUE THREAD

**Issue by boi2071** [ReVanced/revanced-patches#2686]
### Application

Youtube revanced

### Issue

Not issue request

### Patch

I dont kniw what that is

### Motivation

I dont know 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [ ] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by reisxd** [comment]
Acknowledgements not met.

**Comment by oSumAtrIX** [comment]
No. ReVanced is a dalvik patcher

**Comment by oSumAtrIX** [comment]
There is https://github.com/reisxd/TizenTube and https://github.com/yuliskov/SmartTubeNext
