### ISSUE TITLE
bug: Watch history

### ISSUE THREAD

**Issue by SuperZombi** [ReVanced/revanced-patches#2689]
### Type

Other

### Bug description

While scrolling the main page of YouTube, even if the video preview was activated for one second, it gets into the viewing history.

### Steps to reproduce

1) Open YouTube Revanced 18.25.40 on Android 14.
2) Scroll Home page

### Relevant log output

```shell
-
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
#1752
