### ISSUE TITLE
bug(Reddit): Can't log in after patching with changing the package name

### ISSUE THREAD

**Issue by seirdotexe** [ReVanced/revanced-patches#2690]
### Bug description

Once patching Reddit with the **Change package name enabled**, you can't log in on the app by any means. You get the error: **Something went wrong. Try again later.**

### Additional context

Running into this issue on Reddit 2024.05.0, 2024.04.0 and 2024.03.0 with patches 4.0.2.

### Acknowledgements

- [x] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
I am not able to reproduce, record the issue from start to end beginning with starting ReVanced Manager

**Comment by seirdotexe** [comment]
It seems to have been resolved by itself. I tried this morning and I still got the error. Reinstalled just now and it works, strange...

**Comment by seirdotexe** [comment]
Opening this again. Login breaks when enabling **Change package name**.

**Comment by seirdotexe** [comment]
> That is a known limitation.
> 
> The patch description already says this:
> 
> Appends ".revanced" to the package name by default. **Changing the package name of the app can lead to unexpected issues.**
> 
> Solution:  Do not include the patch.  It's only useful if you want to install the same app more than once.

I understand, but I'm still reporting this, as it has always worked just fine. Also, this patch resolves issues with the Play Store trying to take over the patched app when pushing updates.

**Comment by oSumAtrIX** [comment]
The patch works as intended. It changes the package name. How the app reacts to that change is not in the scope of the patch or our control.
