### ISSUE TITLE
feat: Shorts playback speed

### ISSUE THREAD

**Issue by SuperZombi** [ReVanced/revanced-patches#2690]
### Application

YouTube Revanced

### Issue

Please, add a button to change video playback speed in Shorts 

### Patch

In the right button menu in Shorts player, add a button that, when clicked, will display a pop-up window with a speed slider

### Motivation

Nowadays, the speed of content consumption is very important.  Most people use playback speed when using youtube.

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [ ] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
1570
