### ISSUE TITLE
bug: Constant 'LithoFilterPatch: Proto buffer is null' with YT 19.04.37

### ISSUE THREAD

**Issue by mad-tunes** [ReVanced/revanced-patches#2694]
### Bug description

Just updated YouTube to 19.04.37 and patched with revanced.
It's constantly showing toast messages,
'LithoFilterPatch: Proto buffer is null'.

Seems to be a flurry of them after every video that's started.

I've cleared YouTube's cache and data, but still got the same
Uninstalled YouTube and reinstalled/repatched and still get them

This is just after updating my pixel 8 to 20230205.004.B1

Is there something I'm doing wrong, or is something bust?

### Error logs

[revanced-manager_logcat_20240206033427725810.log](https://github.com/ReVanced/revanced-patches/files/14174375/revanced-manager_logcat_20240206033427725810.log)

## Solution

Uninstall ReVanced YouTube. Then re-patch YouTube version `19.03.35`

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [x] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by mad-tunes** [comment]
Sorry, i missed the mention of 'logcat | grep AndroidRuntime' and that was the only log I saw a way to get (was on my phone at about 4am).

It's a flurry of messages for each video played, not just the first one.
I just re-updated to 9.04.37, and didn't see the issue immediately.

Hid a few action buttons and they were hidden. Still no messages.

Went through a load of the options I've usually set, restarting the YT app after each..
Once I enabled 'Hide crowdfunding box' I started getting the messages again.
If I un-set 'Hide crowdfunding box' and restart the app, I still get a bunch of the toast mesages just a the app starts, and as I start each video.

I can't find how to get any useful log using 'logcat | grep AndroidRuntime' as mentioned when logging an issue..
Either making YT throw the messages and then running the command, or running the commad and then making YT throw the messages gives nothin'

Had a guess and ran 'logcat | grep youtube'... and it given a ton more. Hope this is useful?
[logcat grep youtube.txt](https://github.com/ReVanced/revanced-patches/files/14179516/logcat.grep.youtube.txt)

If not, please let me know what would be

**Comment by oSumAtrIX** [comment]
@mad-tunes  YT 9 is not a thing, there is only YT 19, please fix this wherever you mentioned it.

@LisoUseInAIKyrios The buffer may null, in such a case I believe we can simply return silently. I believe our hook is somewhere before a null check.

**Comment by oSumAtrIX** [comment]
Can you please attach a recording of the issue and showing that downloads button still shows up regardless of hiding it?

**Comment by mad-tunes** [comment]
> Debug setting is under `Misc -> Debugging -> Debug logging`
> 
> Your response is a little confusing. Let me ask again:
> 
> When the error toast start showing up, and you have a few action buttons hidden, do the action buttons show up or are they hidden?

It's confusing me a little too. When I first disabled (multiple) action buttons, they were hidden OK. When I re-checked by disabling just the Download button, it wasn't.

Just done the same again (cleared data, enabled Settings>ReVanced>Layout>Hide action buttons>Hide download button, Killed YT and re-opened it then played a video) and the Download button was hidden as it should be.
Enabled Hide like and dislike buttons, and I'm getting the toast messages again, with the like/dislike and downloads buttons all hidden.
Unset both options and the buttons show, but I'm still getting the flurry of toast mesages.
Hide them both again, and now like/dislike's hidden but download isn't. It's not doing the same over multiple passes of enabling/disabling them. It's inconsistant.

I still see no debug option(s) under Settings>ReVanced>Misc in the YT app. Am I looking in the right place?
![Screenshot_20240206-131949](https://github.com/ReVanced/revanced-patches/assets/6985934/ee53367a-1df2-4b21-842c-f593d94df834)

**Comment by oSumAtrIX** [comment]
Use the default set of patches and please attach the recording as previously requested

**Comment by mad-tunes** [comment]
With the default set of patches, I get a bunch of mesages about GMSCore missing and can't get the YT app to open, so I've been unsellecting that patch. I must hve disabled the debugging patch too, which I've just undone.

I'd rather not show my YT name and playlists etc that are shown while moving around the YT app. It's doing as I just described when hiding the buttons. I'm nto sure ow to better describe it then 'inconsistent'. Sometimes thyre hidden as they should be, sometimes they're not.

With all of the debug options set in the YT app settings, I see nothing if I run 'logcat | grep AndroidRuntime' and start YT, while the apps throwing the toast messages, or as I start a video playing.
I notice the toast messages start as soon as I open the app again though, before I've changed any options.

**Comment by oSumAtrIX** [comment]
@mad-tunes log out and please record as requested

**Comment by mad-tunes** [comment]
Thanks @LisoUseInAIKyrios 
I'll just go back to 19.03.35, which works a treat.
Before I do, if there's a way to get any useful log, please let me know how and I will.

Just out of interest, any theories about about why I might have been the first to see/report this?
I just updated to the version of YT that the manager app seemed to recommend.
My pixel 8's pretty stock except for unlocked bootloader, a couple of magisk modules to keep Wallet working and adaway.
Is the recommended version checked much before it shows in the manager app?

**Comment by mad-tunes** [comment]
I didn't love the idea of logging out of everything google, which seems to be the only way to log out of the YT app.
incognito seems fine thouh.

It just went:
Cleared YTs cache and data
Opened YT and got toast mesages right away
Hide like/dislike - like/dislike hidden
Hide download - download hidden but like/disklike shows again. video didnt start after selecting it but did after hitting pause
Hide share - share/download both show, like/dislike doesnt.
Show all three - all three show again
Hide download - download still shows

Pretty constant toast messages throughout
I killed YT between each, so you can see it from opening.

..and I get a video about 3 times the max size I can attach. Made it smaller using handbrake:
https://github.com/ReVanced/revanced-patches/assets/6985934/2ba8afe6-d57e-4576-820e-5e57d8cf9b37

Hope that's useful?

**Comment by oSumAtrIX** [comment]
It isn'removing compatibility with the version now is necessary and adding it back later. Instead, people can use the older version until this one is fixed. I can not reproduce the issue on my end, so we'll need someone or an account at which we can debug the issue.

**Comment by mad-tunes** [comment]
Done.
With default patches applied to 19.05.35, except for unselecting 'GMSCore support', I'm afraid I do see the same toast messages and the hide action buttons settings still have inconsistant results in a similar way.

**Comment by oSumAtrIX** [comment]
How about other layout components?

**Comment by mad-tunes** [comment]
The nvaigation button options seem fine. Hiding the captions and autoplay buttons seems to apply OK too.
There are a lot of layout options though, and I can't say I know what they all do exactly. I'd usually leave most at default.
Are there any specific ones you'd like checking?

**Comment by mad-tunes** [comment]
All seems fine if I don't apply the 'Hide video action buttons' patch to 19.04.37 though, so I've just added that to the 'Solution' above for anyone else who finds similar. (It's not a solution, but lets me avoid the problem when using the later YT)

**Comment by Trung0246** [comment]
I'm also able to replicate this:

1) Brand new android 14 phone
2) Downloaded the youtube apk
3) Use default patch
4) Apply patch
5) Install

**Comment by mad-tunes** [comment]
There's got to be some difference between either our phones or what we're doing with them, that leads to me and @Trung0246 finding the problem but others not.

In case it might help narrow anything down, the Pixel 8 I'm having the issue on is running these
Android build: `UQ1A.240205.004.B1`
Android security update: `5th Feb 2024`

I installed the latest security update on my Pixel 8 (from [here](https://developers.google.com/android/images#shiba)) very shortly after it was released yesterday, then installed/patched YT `19.04.37` and found the issue.
I got the APK of `19.04.37` from [here](https://www.apkmirror.com/apk/google-inc/youtube/youtube-19-04-37-release/youtube-19-04-37-android-apk-download/)

Options I'm using:
[selected_patches_2024-02-06_21_14_02.json](https://github.com/ReVanced/revanced-patches/files/14186602/selected_patches_2024-02-06_21_14_02.json)
[YouTube app saved options.txt](https://github.com/ReVanced/revanced-patches/files/14186605/YouTube.app.options.txt)
(but I do find the problem when applying default patches minus GmsCore support, and when only changing the Hide action buttons options in YT)

YT `19.03.35` works just fine for me with the options above
I'm on `1.18.0` of the ReVanced Manager app, which shows patches `4.1.0`

**Comment by Memorablenel** [comment]
![Uploading Screenshot_20240206_135953_app.revanced.android.youtube.jpg…]()

**Comment by mad-tunes** [comment]
Patches `4.2.0` look good with YT `19.04.37` to me, no toast messages and action buttons hide/show as I set.
Thank for all the great work.
