### ISSUE TITLE
bug: Infinity for Reddit crashes when i try to navigate

### ISSUE THREAD

**Issue by kyoyacchi** [ReVanced/revanced-patches#2698]
### Bug description

The app crashes when i try to view posts or  my own profile page.

https://cdn.discordapp.com/attachments/866959120233398293/1204743542262595646/screen-20240207-135650.mp4?ex=65d5d7db&is=65c362db&hm=8a5d44f0681a4aa6a808ec2d3e450f8cdb7021819a97fb3c441e41e7a8ccbdad&

I used two available patches, which are "unlock subscription" and "spoof client" (id specified)

The app's version is 7.0.0.
I downloaded and tried it from both apkmirror and github releases page, it still gives the same result 
No, i didn't restore my backup. Nothing changes even if i do that.

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
The crash is caused by the subscription patch.
