### ISSUE TITLE
bug: 19.04.37 YouTube Auto-repeat / Loop patch always active, can't disable

### ISSUE THREAD

**Issue by TheShadowRunner** [ReVanced/revanced-patches#2699]
### Bug description

Revanced YouTube 19.04.37 and the Auto-repeat" patch. 

After enabling it at Gear (settings) > Additional Settings > Loop video, it cannot be disabled.

In essence regardless of what the Loop setting is set to, videos will always loop now.

I believe this is triggered by enabling loop at least once.
After that it cannot be disabled although the toggle is in the off position.

Thanks for your support. 

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
I can not reproduce the behavior. Check for this behavior on the unpatched app.

**Comment by TheShadowRunner** [comment]
Ok I repatched without "Always repeat" patch and the toggle "loop video" now seems to be working alright. 

I guess I didn't understand the purpose of "Always repeat" as its description says "adds an option to always repeat videos when they end". To my understanding, this option added the toggle "Loop video" feature. 

It turns out this patch isn't needed for the "loop video" feature to be available and working.

It seems "Always repeat" patch does just what it's called, always repeat (and it doesn't respect the Loop video toggle here).
