### ISSUE TITLE
bug: YT ReVanced Crashed after the installing of latest recommended patch

### ISSUE THREAD

**Issue by Therockstar777** [ReVanced/revanced-patches#2700]
### Type

Other

### Bug description

After the  installation of latest recommended patch , the app crashes and error message pops up... the image of the error message is given below... { INDIA } 

### Steps to reproduce

release new recommended patch

### Relevant log output

```shell
didnt get the info
```

### Screenshots or videos

![WhatsApp Image 2023-07-26 at 20 17 59](https://github.com/ReVanced/revanced-patches/assets/127512365/c387e123-90a2-4dd2-aea3-eb4cfa2a50a5)

### Solution

release a new recommended patch 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [ ] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
No reproduction steps provided.
