### ISSUE TITLE
feat: Hide "People also watched this video" and "You might also like this" search results

### ISSUE THREAD

**Issue by ikubaysan** [ReVanced/revanced-patches#2701]
### Feature description

The "People also watched this video" and "You might also like this" search results consistently have nothing to do with my query. Instead, they may come up as trypophobia, pimple popping, animal abuse, and death videos.

I can't be the only person with the problem. Could you please implement a patch to hide these search results?
Also, I usually run YouTube in Japanese, so could you please ensure this works for other languages too aside from English?

Example of a "You might also like this" search result:
![image](https://github.com/ReVanced/revanced-patches/assets/34055986/ac81ee4b-0ce5-48f7-8795-63839d63c2e1)

I am not experienced in Android development, but I am experienced in .NET, C++, and Python development and would be happy to help in any way I can.

### Motivation

To provide the option of preventing the display of disgusting, irrelevant search suggestions.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
The patch already exists: https://github.com/ReVanced/revanced-patches/blob/501fc48c68f01a33f4ec9c09b579036b22264140/src/main/resources/addresources/values/strings.xml#L85

**Comment by ikubaysan** [comment]
I see it now, looks like it's working. Thank you so much!

**Comment by ikubaysan** [comment]
Actually, I'm still seeing "People also watched" search suggestions when I've enabled the option to hide them.

![Screenshot_20240207-184130199~2](https://github.com/ReVanced/revanced-patches/assets/34055986/e87f2559-6a46-4150-ba0a-e4dd075e3d8b)
![Screenshot_20240207-184103702~2](https://github.com/ReVanced/revanced-patches/assets/34055986/988722bb-1406-46c9-afca-3417216f1006)

**Comment by oSumAtrIX** [comment]
Please open an issue
