### ISSUE TITLE
bug: (Youtube) (Spoof app signature) - opening autoplaying muted video from home feed makes the video remain muted until reopened second time. 

### ISSUE THREAD

**Issue by Domiiniik** [ReVanced/revanced-patches#2701]
### Type

Error at runtime

### Bug description

Opening an autoplaying muted video from home feed makes the video remain muted in video Player until its closed and reopened second time when it doesnt autoplay in feed anymore.
![Uploading Screenshot_20230726_184735_YouTube.jpg…]()

### Steps to reproduce

Open Youtube home feed tab with spoof app signature patch enabled, Play any autoplaying home feed video, notice that there is No sound until the video is closed and open again when its not playing with muted Mode on feed No More.

### Relevant log output

```shell
..
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Reproduction steps are insufficient. The video always plays with sound regardless of whether the auto-playing video in the feed is muted or not.

**Comment by Domiiniik** [comment]
Here

https://github.com/ReVanced/revanced-patches/assets/30195961/4dad82ac-c0f6-4261-b777-479032f17d31

**Comment by oSumAtrIX** [comment]
Disable signature spoofing and try again
