### ISSUE TITLE
bug: (Youtube) (SponsorBlock) Skip to Highlight button shows up in video player despite "Show in seekbar" highlight button setting preference being set.

### ISSUE THREAD

**Issue by Domiiniik** [ReVanced/revanced-patches#2702]
### Type

Error at runtime

### Bug description

Skip to Highlight button shows up in video player despite "Show in seekbar" highlight button settimg preference being set.

### Steps to reproduce

..

### Relevant log output

```shell
..
```

### Screenshots or videos

https://github.com/ReVanced/revanced-patches/assets/30195961/04d6807f-6151-419b-a7d0-1fb2ff2cdeaf

### Solution

Skip to Highlight button should remain hidden if Show in seekbar option is being set for it

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
@LisoUseInAIKyrios Is the intended behaviour that the segment is always visible in the seek bar unless when completely disabled? The rest of the list options can control the visibility of the button.
