### ISSUE TITLE
bug: YouTube - "People also watched" recommendations appearing despite hide option being enabled.

### ISSUE THREAD

**Issue by ikubaysan** [ReVanced/revanced-patches#2703]
### Bug description

I have enabled the "Hide 'People also watched' recommendations" option, but I am still seeing them.

ReVanced Manager 1.18.0, patches applied today (February 7, 2024)
YouTube v19.04.37, installed today.
Android 10
ASUS Zenfone 7 Pro

![303198016-e87f2559-6a46-4150-ba0a-e4dd075e3d8b](https://github.com/ReVanced/revanced-patches/assets/34055986/fb15682b-24ee-45a3-9395-840cdb3fe24b)

![303198022-988722bb-1406-46c9-afca-3417216f1006](https://github.com/ReVanced/revanced-patches/assets/34055986/b92a1df7-ad6c-4863-aa85-7a50f1e16a3b)

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
The logs are too long, please send the relevant lines from log.txt

**Comment by ILoveOpenSourceApplications** [comment]
I actually had mentioned most of these categories in my #6 issue, the only one which I didn't come across is `Popular today`. I did want to report that the issue wasn't fixed then but didn't find myself the time to provide a feedback.

**Comment by oSumAtrIX** [comment]
Looks to be A/B as I can not see this when I search for dog. I'll need someone to give me access to an affected account. Please contact me at osumatrix@revanced.app

**Comment by ccrowles** [comment]
I'm having the same issue, "people also watched" and unrelated videos in general showing up in my search results.

Revanced Patches 5.2.0
YouTube 19.46.42
ZenFone 9, running android 14
