### ISSUE TITLE
bug(YouTube): Occasional increased loading time when using 19.04.37

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [ReVanced/revanced-patches#2704]
### Bug description

I noticed that *sometimes* there would be an abnormal buffer time even when the internet connection is fast and stable. It could happen at the start of a video, or sometimes a few minutes into a video. I suspect that there would have been an ad right there, and it takes about 5-10s, which is about the time of an ad.

 This issue only appear on 19.04.37, and would disappear when spoofed version to 19.03.35 (last version supported).

This issue shall serve as a tracking issue for future bug reports. 

**React with 👍 if you have the same issue but don't have further information to provide**

Used patches (just put it to jq): 
```
{"com.google.android.youtube":["Alternative thumbnails","Always repeat","Announcements","Bypass URL redirects","Change header","Change start page","Client spoof","Comments","Copy video URL","Custom branding","Custom player overlay opacity","Disable auto captions","Disable fullscreen ambient mode","Disable player popup panels","Disable precise seeking gesture","Disable resuming Shorts on startup","Disable suggested video end screen","Disable zoom haptics","Enable debugging","Enable slide to seek","Enable tablet layout","External downloads","GmsCore support","HDR auto brightness","Hide 'Load more' button","Hide Shorts components","Hide ads","Hide album cards","Hide autoplay button","Hide breaking news shelf","Hide captions button","Hide cast button","Hide crowdfunding box","Hide endscreen cards","Hide filter bar","Hide floating microphone button","Hide info cards","Hide layout components","Hide player buttons","Hide seekbar","Hide timestamp","Hide video action buttons","Minimized playback","Navigation buttons","Open links externally","Playback speed","Player flyout menu","Remember video quality","Remove player controls background","Remove tracking query parameter","Remove viewer discretion dialog","Restore old seekbar thumbnails","Restore old video quality menu","Return YouTube Dislike","Seekbar tapping","SponsorBlock","Spoof app version","Swipe controls","Tablet mini player","Theme","Video ads"]}
```

## Solution

Uninstall ReVanced YouTube and patch YouTube version 19.03.35.

Or, enable version spoofing and use spoof target 19.03.35 by modifying the exported settings and re-import it.

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Please attach a video of the issue and test on incognito/other accounts

**Comment by SodaWithoutSparkles** [comment]
Closing this for now because of difficulty to reproduce, maybe YouTube was just doing A/B testing a few days ago
