### ISSUE TITLE
feat: Revanced YouTube music casting

### ISSUE THREAD

**Issue by GitStudying** [ReVanced/revanced-patches#2709]
### Feature description

Currently it is not possible to cast from revanced music to chromecasts. I understand that this won't really be possible via the native functionality. I recently used grayjay and found they use fcast with fcast receiver on a Chromecast. Is it possible to add a patch to use fcast instead of the broken normal cast.

### Motivation

The feature helps cast which is used by many people on the normal revanced but does not work for the revanced music. Specifically on non root devices.
Many people use YouTube music and want it without ads but with casting which is possible with fcast as used on grayjay. However grayjay has different purposes and is not the same compared to revanced music.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
I am not sure, but it should be possible to cast your screen which fulfills the objective
