### ISSUE TITLE
bug: Search results video type bar often won't show 

### ISSUE THREAD

**Issue by GKid94** [ReVanced/revanced-patches#2710]
### Bug description

The top video type bar often won't show on search results screen
![Screenshot_2024-02-09-17-38-45-001-edit_app revanced android youtube](https://github.com/ReVanced/revanced-patches/assets/18757054/7cc66c00-d2b3-40a9-a5eb-6aa63955ab4f)
![Screenshot_2024-02-09-17-42-38-838_app revanced android youtube](https://github.com/ReVanced/revanced-patches/assets/18757054/f9eee65e-892c-4abf-9ddb-ba916a6c34db)

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
That's the behavior of YouTube
