### ISSUE TITLE
bug: Youtube - Shorts are not hidden in search results in tablet layout.

### ISSUE THREAD

**Issue by atzix** [ReVanced/revanced-patches#2713]
### Bug description

After disabling shorts features in Shorts components, they still continue to appear in the search results if the tablet layout is enabled.

Using latest patches.

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Send a picture

**Comment by atzix** [comment]
> Send a picture

![5929063702449996281_121](https://github.com/ReVanced/revanced-patches/assets/47281378/cdcd1a4d-2053-43fa-88b9-ac166184d270)
![5929063702449996280_121](https://github.com/ReVanced/revanced-patches/assets/47281378/27a7c674-362c-4bc6-bc4f-08c3afd0b92f)

**Comment by oSumAtrIX** [comment]
The component is called `inline_shorts`. Can you add that to Custom filter under Layout > Custom filter and see if that works?

**Comment by atzix** [comment]
I entered the string `inline_shorts` there and restarted the app. But it didn't work

**Comment by oSumAtrIX** [comment]
Please follow this: 
<img width="389" alt="image" src="https://github.com/ReVanced/revanced-patches/assets/13122796/5eb1aeaa-947d-46e0-a652-dad3cfc40788">

**Comment by atzix** [comment]
I followed the steps up to step 5, but I'm not sure how to continue from there. I captured the logcat output while scrolling through search results containing shorts, and I see that the names of shorts videos appear in the logs. But I don't know what are the strings of the component names and what do I type in the custom filter.

Here are some lines from the log containing the string `shorts`:

`02-12 01:26:58.117 24936 25146 D revanced: LithoFilterPatch: Searching ID: shorts_shelf.eml|eb0bfedb8d40a76a Path: shorts_shelf.eml|eb0bfedb8d40a76a|shorts_shelf.eml|eb0bfedb8d40a76a|shorts_shelf.eml|eb0bfedb8d40a76a|shorts_shelf.eml|eb0bfedb8d40a76a|CellType| BufferStrings: shorts_shelf_carousel.eml|2f2582638c3e7697❙nu|<gz❙jEo|❙shelf_header.eml|eed05856e0fd4de9❙1707697368347125317❙shorts_shelf.eml|eb0bfedb8d40a76a❙eml.shorts-shelf❙`

`02-12 01:27:02.236 24936 25147 D revanced: LithoFilterPatch: Searching ID: null Path: compact_video.eml|b47bbf1e36a53cce|CellType|thumbnail.eml|af7d9bf9f030cbe3|ContainerType|ContainerType|thumbnail_badge.eml|d1e5252ed949789f|ContainerType| BufferStrings: SHORTS❙sans-serif-medium❙yt_fill_youtube_shorts_no_triangle_white_16❙eml.timestamp❙`

`02-12 01:27:02.239 24936 25147 D revanced: LithoFilterPatch: Searching ID: null Path: compact_video.eml|b47bbf1e36a53cce|CellType|ContainerType|metadata.eml|15b183e48ad65581|metadata_content.eml|c2c6522315c3c065|ContainerType| BufferStrings: Mikey Piscopo❙sans-serif-regular❙avatar.eml|d00bf20757f77f85❙sans-serif-regular❙Expensive Amp Vs Expensive Guitar Argument #shorts❙sans-serif-regular❙eml.metadata❙`

Other strings are similar to these. And i don't see other differences with normal videos.

Log of a short and video:  [log_more_truncated.txt](https://github.com/ReVanced/revanced-patches/files/14270582/log_more_truncated.txt)
More logs while scrolling: [log_truncated.txt](https://x.com/x/x-x/files/14270238/log_truncated.txt)

**Comment by oSumAtrIX** [comment]
In custom filter you can now enter any substring from path, optionally followed by a $ and a substring of BufferStrings. The first log you sent is not what is seen in your screenshot, whereas the second and third could be. Follow the remaining step 5 and 6

**Comment by oSumAtrIX** [comment]
On a wide screen I got the same type of short under the component "inline_shorts" hidden, so we would need to add these two as filters

**Comment by atzix** [comment]
> Try using the custom filter: `^compact_video.eml$/frame0.jpg`
> 
> `/frame0.jpg` is part of the thumbnail url and is a valid filename for both Shorts and regular videos, but it appears only Shorts use that image for the search results.

Yeah, that works
