### ISSUE TITLE
feat: Force app into landscape-only mode

### ISSUE THREAD

**Issue by Green-de-la-Bean** [ReVanced/revanced-patches#2715]
### Application

YouTube

### Issue

Unlike all other video players, on the YouTube app when on an Android _tablet_, if you open a video in full screen and then rotate the device to a vertical orientation, it will change the video to be shown in that orientation. This makes watching a video in bed very annoying as you constantly have to adjust the rotation lock.

### Patch

Have the app run in a mode similar to many Android games where it will only display in landscape mode at all times. I believe this would be fairly simple to add as you could just add the line: `android:screenOrientation="landscape"` to the manifest.

### Motivation

I personally would benefit from this because I hate having to constantly change the rotation settings. I don't think it would take very long to add and would probably benefit other users of YouTube ReVanced who have it installed on a tablet device.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by NBruderman** [comment]
+1 on this one

**Comment by oSumAtrIX** [comment]
Not sure why you would "constantly change the rotation settings." You can also automate it with something like Tasker.

**Comment by Green-de-la-Bean** [comment]
I don't think telling me to get some paid app is a good solution.

**Comment by oSumAtrIX** [comment]
Why not?

**Comment by Green-de-la-Bean** [comment]
Because for other people's sake, unless they go out of their way to ask this, then they'll be stuck with an annoying interface on tablet mode. The reason you have to fiddle with rotation lock settings is because if you try to use Youtube holding the tablet in an orientation where your viewing the screen not relative to the ground (lying down for instance) then the tablet will display the video incorrectly. This means if you want to view a video in landscape but then use other apps in portrait you have to lock the screen every time you move between apps. In the short time this issue has been open, someone else has already agreed with my point of view.
I'd do it myself but I don't think ReVanced manager lets me edit the android manifest file at all.

**Comment by oSumAtrIX** [comment]
@Green-de-la-Bean The lock rotation setting on Android does this already, as explained; you can automate it using Tasker as an example

**Comment by nl255** [comment]
> @Green-de-la-Bean The lock rotation setting on Android does this already, as explained; you can automate it using Tasker as an example

Some apps, such as Freezer, ignore that setting and will auto-rotate no matter what you do.

**Comment by Fred-Vatin** [comment]
There is no issue with official YouTube in full screen on tablet, if I remember. It is expected that revanced behaves the same. Yes there are some third apps that can automate the screen orientation for specific app. But it's not the same as a built-in feature allowing to use revanced in portrait and only switch to landscape when full screen.
