### ISSUE TITLE
feat (YT Music) : add Custom Branding Heading patch.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [ReVanced/revanced-patches#2715]
### Feature description

Similar to YT ReVanced, I'm requesting to implement Custom Branding Heading patch for YT Music also.
![Screenshot_2024-03-14-06-37-10-38_d5ca8c38f86219f8d8dafdf022bf2e3b.jpg](https://github.com/ReVanced/revanced-patches/assets/91815107/5c32dbf4-7635-409b-a576-3b1bb00295f8)
![Screenshot_2024-03-14-06-38-06-92.jpg](https://github.com/ReVanced/revanced-patches/assets/91815107/c38afb8f-a1c6-4a80-8008-24a28e5d2348)

### Motivation

This feature should be implemented because ReVanced team already provides the same for YT. So, what's the reason for not getting the same benefits on YT Music? Since both apps are coming from the same company, uses same accounts & many users use both these apps on their phones, it makes sense to provide them a uniform app header design.

Explicit use case? Please keep the same mentality that you kept while writing the code for YT app custom header.

Benefits? Same benefits that one gets while using custom header on YT ReVanced.

Importance? Same as YT Revanced.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
#362
