### ISSUE TITLE
feat (YT Music): Ability to hide "Episodes for later".

### ISSUE THREAD

**Issue by Aryan-Chauhan** [ReVanced/revanced-patches#2717]
### Feature description

Kindly add the ability to hide "Episodes for Later" in Library.
![Screenshot_2024-01-28-14-51-47-55_0eaaacfb1e02f862bb18505a09b95933](https://github.com/ReVanced/revanced-patches/assets/91815107/b3f08e28-80a0-4656-a7fb-ac577a026b00)

### Motivation

Many people only use the ReVanced Music app for listening to music & never listen to podcasts. So, it will provide a better design for them.

If it's not too time-consuming, kindly look into it.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
You can simply not click on it, its the last item of the list

**Comment by oSumAtrIX** [comment]
Unless there's proper reason, no

**Comment by Aryan-Chauhan** [comment]
> Unless there's proper reason, no

The best I can do is this:

1. In earlier times, it didn't exist. This episodes for later thing is an recent addition. So, it is sticking out to me.

2. It serves no purpose for non-listeners of podcasts, which are a lot.

3. I read the homepage of ReVanced, then I read this issue created by me. Still feeling like I requested for something that makes sense.

**Comment by oSumAtrIX** [comment]
Refer to my first comment for all 3 points.
