### ISSUE TITLE
bug: strava patch blocks sign in

### ISSUE THREAD

**Issue by Dan-Crook** [ReVanced/revanced-patches#2720]
### Bug description

Using the recommended strava version 320.12.
Without patches, login works fine.  Once patched, login no longer works and only results in an error message.

Tried to login using all options:
Email login, Google login and Facebook login.

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Just tested and login works as expected.

**Comment by HomerAyuste** [comment]
I was also getting this error on a non-rooted device but only when I tried to login through Google. Using email login worked okay.

**Comment by oSumAtrIX** [comment]
Open a new issue

**Comment by Fuku856** [comment]
There were some patches that could be patched after adjusting the version.
