### ISSUE TITLE
bug: Ad blocking not working on X(Twitter)

### ISSUE THREAD

**Issue by CoolCooler0** [ReVanced/revanced-patches#2723]
### Bug description

I have been getting ads on X. The version I'm currently using are v10.27.0.
![Screenshot_20240213_103622_X](https://github.com/ReVanced/revanced-patches/assets/136742821/a863cafe-d8c5-4188-bbbe-252cce229ce2)

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
I am using 10.27 and ads are being blocked. Refresh the feed and check again

**Comment by CoolCooler0** [comment]
> I am using 10.27 and ads are being blocked. Refresh the feed and check again

I refreshed it and its gone but it comes and go's.
