### ISSUE TITLE
bug(YouTube - Return YouTube Dislike): Live likes/views counts is sometimes shown wrong

### ISSUE THREAD

**Issue by imvoldemort** [ReVanced/revanced-patches#2724]
### Bug description

Live likes/views counts displays very wierdly
![IMG_20240213_160958](https://github.com/ReVanced/revanced-patches/assets/159900453/528ee506-2bb6-42ec-bd1c-963a5f9e6ceb)
![IMG_20240213_160927](https://github.com/ReVanced/revanced-patches/assets/159900453/73a7a725-5bd0-4014-8958-a4b622a1abef)

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by imvoldemort** [comment]
No incognito mode was not on

**Comment by imvoldemort** [comment]
It happens everytime when the live count refreshes with or without incognito mode on.
Update - It doesn't happen on my second account.

**Comment by imvoldemort** [comment]
Yes, It occurs on the latest patches as well.

**Comment by oSumAtrIX** [comment]
I think this can be solved by checking the path. 

@imvoldemort Enable debugging in ReVanced > Misc settings. Then use logcat to capture logs. Filter for "Litho". Start logging right before you open the description where the issue occurs. Once finished, send the logs here.

**Comment by imvoldemort** [comment]
I don't know how to do it.

**Comment by oSumAtrIX** [comment]
There's unlimited great tutorials online how to use Logcat: https://www.google.com/search?q=how+to+use+logcat&oq=how+to+use+logcat

Please pick one and follow up with the logs.
