### ISSUE TITLE
feat(YouTube): Summarize video content

### ISSUE THREAD

**Issue by Arckay10** [ReVanced/revanced-patches#2725]
### Feature description

For long videos. There are websites for YouTube summary, you just have to past the link there. 
What it does is getting the transcript and summarize from it.  Instead of doing that separately, what if there is an option/button in the Revanced YT as patch? Or integrate them

[summarize.tech](http://summarize.tech)
[youtubesummarizer.com](https://youtubesummarizer.com)

![Screenshot_2024-02-13-17-48-25-317_com android chrome](https://github.com/ReVanced/revanced-patches/assets/100150536/eca8ca15-29a7-469d-9970-a80ba01c669a)
![Screenshot_2024-02-13-17-48-15-221_com android chrome](https://github.com/ReVanced/revanced-patches/assets/100150536/7759ad9e-f30a-438d-ac76-70d869f364fa)

### Motivation

Features would benefit those who are students who needs to watch a hour long lecture. And people who listen to a lot of podcasts but have no time.  And to some busy user who doesn't want to waste time on some videos.
This would save a lot of time and cut down a few processes.  This would be more useful in the academic sense rather than for those who use for entertainment 

### Acknowledgements

- [ ] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by Arckay10** [comment]
I'm sorry if something is not in format. I'm technologically challenged. Reddit community suggested me to request here

**Comment by oSumAtrIX** [comment]
#1132 (a button could be added that shows the summary in an alert dialog)
