### ISSUE TITLE
feat: be able to activate and deactivate the permanent loop function

### ISSUE THREAD

**Issue by Rubyurek** [ReVanced/revanced-patches#2726]
### Application

Youtube Music

### Issue

The problem is that the loop function is not permanently activated. In the vanced version it was always activated, even if you changed the song.

### Patch

A button in the app to activate/deactivate the permanent loop function or have it inserted via patch.

### Motivation

There are music listeners who like to hear a song in the loop all the time. Often there are situations where another song wants to be heard permanently, and this function would make that possible.

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [x] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
#1295
