### ISSUE TITLE
bug: Removal of the Nova Launcher Prime patch

### ISSUE THREAD

**Issue by robwainwright** [ReVanced/revanced-patches#2731]
### Type

Other

### Bug description

Hi there,

This issue isn't really a bug report but I was told I could open an issue and this seemed like the most appropriate place to do so. I can re-open elsewhere if that would be better.

I'm one of three on the Nova Launcher team although this issue isn't on behalf of or requested by our parent company.
This project includes a patch to unlock the paid Prime features of Nova Launcher without paying the usual $4.99 one-time price.

This issue is simply a humble request from one developer to another to remove the patch for our app. Even after joining a larger company, Nova Launcher is still a passion project from a very small group of dedicated people.

Thanks!

### Steps to reproduce

N/A

### Relevant log output

```shell
N/A
```

### Screenshots or videos

N/A

### Solution

I think we know my proposed solution 🙂 

### Additional context

N/A

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Thanks for reaching out. Removal is staged in branch `dev`.

**Comment by MySurmise** [comment]
Encouraging everyone using that software to support these people. 5$ is not much for something you use everyday all the time and even I, as a student, could afford it. 
Thanks for your work!

**Comment by Barusu-rem** [comment]
> Encouraging everyone using that software to support these people. 5$ is not much for something you use everyday all the time and even I, as a student, could afford it. Thanks for your work!

Further to add Nova does offer direct licenses for degoogled android devices. You only need to interact with google play to buy the app which can be done on the via google play website.

![image](https://github.com/ReVanced/revanced-patches/assets/124480833/5d18b8b5-1724-4ffc-9dd1-4368aab633f7)

https://novalauncher.com/faq

**Comment by kyodjinn** [comment]
I bought Nova Prime, but I say we keep the patch. They were bought out by a data analytics company and it was found that connections were still being made despite opting out. Not sure how much of a threat it actually is, but Nova isn't open source and over the years we've seen countless good products become untrustworthy after shady acquisitions.

**Comment by oSumAtrIX** [comment]
Being bought by a data analytics company does not justify a pro unlock patch.

**Comment by robwainwright** [comment]
> it was found that connections were still being made despite opting out.

@kyodjinn This is either completely fabricated or just a misunderstanding. Nova does not contact any Branch domains even when opted in, and analytics (which have been a thing long before the acquisition) aren't sent at all when opted out. Nova will still contact its weather API if you have search bar weather enabled and will occasionally check to see if you're on the latest update if enabled, so maybe they're what you were seeing.

Regardless, this issue isn't the place to be having this discussion. You're free to get in touch on our Discord or Nova Settings > Contact support if you have concerns.
