### ISSUE TITLE
Hide Community Posts in HomeScreen

### ISSUE THREAD

**Issue by Shane9248** [ReVanced/revanced-patches#2735]
### Application

YouTube ReVanced

### Issue

I can see community posts in Home screen in YouTube ReVanced which is annoying 

### Patch

A patch to hide all community posts from appearing in home screen would be really helpful  

![Screenshot_20230803-133102~2](https://github.com/ReVanced/revanced-patches/assets/83491863/7c57a72a-8976-4ff4-8495-ee124d94b132)
I know this already exists but this also hides community posts when u click on a specific channel to see the posts

### Motivation

This patch will give us more options 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Already exists

**Comment by Shane9248** [comment]
> Already exists, open a properly worded issue if you want to show them in specific channels. The motivation is insufficient.

can u tell me which one is it ?
