### ISSUE TITLE
feat(YouTube): Audio only YouTube - Fight addiction - YouTube as Podcast app

### ISSUE THREAD

**Issue by PierreBastiani** [ReVanced/revanced-patches#2736]
### Feature description

Target App: YouTube

The basic idea is to disable the video feed when the patch is applied.

When a video is click and played, just display the thumbnail or description.

The feature sounds like https://github.com/ReVanced/revanced-patches/issues/412, but the reason is different.

### Motivation

Why: YouTube or general streaming addiction can be hard to fight.

Use case: Someone trying to control screen time, without having to uninstall YouTube completely (YouTube can be a good learning resource, or a great podcast app)

Benefits: This feature helps to make YouTube less addictive (in the same way as disabling shorts). 

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
YouTube is a video player. Use podcasts app for podcasts.

**Comment by PierreBastiani** [comment]
> Many YT videos can be found in YT Music, and there is no video there.
> 
> Any YouTube video can be opened in YT Music by opening a url of:
> music.youtube.com/watch?v=videoid
> 
> You can also force YouTube to not show the video and only play audio, by minimizing the app then tapping the headphone icon in the mini player.
> 
> And there already exist [Chrome plugins](https://chrome.google.com/webstore/detail/audio-only-youtube/pkocpiliahoaohbolmkelakpiphnllog) that hide the video.
> 
> 
> But the bigger question is, if you are in control of patching and installing apps, then what will stop your free will from turning off the patch or using stock YouTube?
> 

Thanks for the tips !

Obviously, if you really want you could always ReEnable YouTube video stream, it's your phone after all.

But enough friction can help to control yourself.
If you have to patch the app again to enable the video, it might be enough to stop yourself.

**Comment by PierreBastiani** [comment]
> YouTube is a video player. Use podcasts app for podcasts.

Fair ! but many contents could be considered podcasts, or consumed as such but not published as podcasts. 
(Ex: Tutorials, Stories, or even most educational videos)

**Comment by oSumAtrIX** [comment]
In such a case, you can watch the content on YouTube. The feature you request is not necessary for that.

**Comment by YT-Advanced** [comment]
Uhm for this case, by using the throoting protobuf parameter, the player response will return audio only.
