### ISSUE TITLE
feat: (Tumblr): A mutuals checker patch.

### ISSUE THREAD

**Issue by VonSparq** [ReVanced/revanced-patches#2742]
### Feature description

By default Tumblr labels your mutuals (users who you follow and they follow you back) only in a few select places, this feature would allow you to see if the user is your mutual whenever their username appears which is really cute and useful.

### Motivation

It is really useful on Tumblr to see if a user is your mutual or not, some people have a lot of account they follow and it's cool to know if they follow you back at a glance. This feature would allow you to easily see it whenever you see another user's username.
This feature already exists in the desktop browser extension for Tumblr, [XKit Rewritten](https://github.com/AprilSylph/XKit-Rewritten) which is open source and also uses GPL-3.0 so you might be able to take a look how they implemented it which might make writing the patch easier.
I think this would be a very cool and great feature to implement because it's nice to see if you are mutuals with other tumblr users, it's not a very crucial or groundbreaking feature but I think it would be awesome if you could add it!

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by VonSparq** [comment]
Mutuals are very important and precious in Tumblr culture, you follow them and they follow you, it's kinda like friends on other apps. It's a cool thing to see that a friend is sharing something and not just a random account you follow.
You can have multiple blogs on tumblr, people can change their blog's names and you often follow loads of blogs so it's not always a given you remember everyone you're mutuals with by their blog's name, so this feature helps you to see at a glance which posts are made by people you care about and if you kinda remember that person it's a way to see that they're important and you can open their profile and check what you know them from.
Like I said it's not the most crucial feature to implement, it's a feature that's really nice to have on desktop and I think would make a great little addition to the app!

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
