### ISSUE TITLE
bug: YouTube Revanced doesn't open YouTube links

### ISSUE THREAD

**Issue by GKid94** [ReVanced/revanced-patches#2743]
### Bug description

YouTube links open in the original YouTube app instead of YouTube Revanced 
![Screenshot_2024-02-19-23-48-51-714_com android settings](https://github.com/ReVanced/revanced-patches/assets/18757054/0d02de83-bafe-4d9d-b5f4-4d1e3f821bae)
![Screenshot_2024-02-20-00-12-43-353_com android settings](https://github.com/ReVanced/revanced-patches/assets/18757054/2e1d11ed-b202-401c-abb2-74c154d99e70)

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
That's an issue with your OS

**Comment by GKid94** [comment]
> That's an issue with your OS



> That's an issue with your OS

It works with other apps

**Comment by oSumAtrIX** [comment]
Your OS treats different apps differently. Either way, this is not an issue with ReVanced.
