### ISSUE TITLE
feat(YouTube - Swipe controls): add ability to remember swipe brightness all the time

### ISSUE THREAD

**Issue by johnconner122** [ReVanced/revanced-patches#2744]
### Application

YouTube

### Issue

Every time I open the YouTube ReVanced, brightness is back to device default, which is annoying to change again everytime.

### Patch

This patch should allow to remember swipe brightness value with a PreferenceSwitch/TextPreference.

### Motivation

Every time I open the YouTube ReVanced, brightness is back to device default, which is annoying to change again everytime.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Already exists, toggle off "rememebr saving brightness".

**Comment by johnconner122** [comment]
It doesn't restore last brightness value?

**Comment by oSumAtrIX** [comment]
Then toggle it on

**Comment by johnconner122** [comment]
Same no effect
