### ISSUE TITLE
bug(Twitter): Unlock downloads does not work for every video

### ISSUE THREAD

**Issue by JaDerBobby** [ReVanced/revanced-patches#2745]
### Bug description

x Version 10.28.0-release.0
Patched date 13 February 2024

For unknown reasons, I cannot download every video. Size does not seem to be an issue. As a user I was not able to identify any patterns.

https://github.com/ReVanced/revanced-patches/assets/160597626/ecbe5dab-fb8b-4d72-b989-b4d88dfe98b9
https://github.com/ReVanced/revanced-patches/assets/160597626/3812086f-61b7-4d81-b4c5-0473b42f0da5

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
The download menu item was patched when you click on the video in the hamburger menu, not in the long press menu
