### ISSUE TITLE
feat: Force app language/remove specific translation

### ISSUE THREAD

**Issue by Miigon** [ReVanced/revanced-patches#2746]
### Application

Youtube, and maybe also for all apps.

### Issue

Youtube has a really annoying feature where if a translation of the video title or description is available in the app's current language, the translated version will be used.

Problem is such translations are usually produced by machine and really is unintelligible and worse than the untranslated original version.

### Patch

For YouTube: option to disable the title and description translation feature.

Or alternatively, for all apps:
Option to force the app's language, or remove specific translation files.
(Yes this can be done using android's per-app language setting, but that feature isn't supported by all phone manufacturers.)

### Motivation

It will make multilingual users' lives easier by not showing crappy and unintelligible video titles.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
#874
