### ISSUE TITLE
feat(YouTube): Hide name of chapters from the video player

### ISSUE THREAD

**Issue by Aryan-Chauhan** [ReVanced/revanced-patches#2747]
### Feature description

Kindly add the ability to hide name of chapters from the video player.
![Screenshot_2024-02-20-22-19-11-56_be4b70c267d4f8a47eddb37150f6981f](https://github.com/ReVanced/revanced-patches/assets/91815107/cfd00cb5-3304-4399-b953-530cccac7d3c)

### Motivation

1. People see it often.
2. You cannot read the full name of the chapter anyways, because of the overlay buttons. So, it's better to just hide them.

Some of my previous feature requests were rejected because "you don't see them often".
Well, name of chapters appear on nearly 70% of videos I watch.

Thanks!

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Unofficial patches, there's not this amount of overlay buttons that overlap with the chapter name.

**Comment by ILoveOpenSourceApplications** [comment]
This could be clubbed with #2178 and make a combined solution for both issues.
