### ISSUE TITLE
feat: Compatibility with Youtube for Android TV (Google TV).

### ISSUE THREAD

**Issue by HelderRocket** [ReVanced/revanced-patches#2748]
### Feature description

I have a Google TV Box: Google TV. As such it's basically Android, and while you can install YT Revanced, the interface doesn't fit the view. I think it would be nice to be able to add patches for that version of Youtube.
![image](https://github.com/ReVanced/revanced-patches/assets/104467221/2226a082-a295-4c7a-bdd2-4a58e39ab242)
![image](https://github.com/ReVanced/revanced-patches/assets/104467221/53bf9454-d6f7-4ec0-83bf-bbff46b5c813)
![image](https://github.com/ReVanced/revanced-patches/assets/104467221/e2810724-e662-4c19-9477-69a2ee6d660d)

### Motivation

Why should this function be implemented?
- To be able to conveniently use the Google TV version of YT.

What is the explicit use case?
- (I'm using a translator, and as such, I'm not entirely clear on the question) For the Android TV/Google TV platform.

What are the benefits?
- Accessibility of use for the Google TV platform.

Why is this feature important?
- Being able to also cover the YT version of Google TV.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
The Google TV version is a webview and not Dalvik code. To support the app one would have to hook into the WebView or similar. Out of scope.

**Comment by HelderRocket** [comment]
> The Google TV version is a webview and not Dalvik code. To support the app one would have to hook into the WebView or similar. Out of scope.

😮 I didn't know that.
And in that case couldn't patches be added for the normal version of YT, that would manage to adapt the interface to the view and controls?

**Comment by oSumAtrIX** [comment]
They can and you are free to implement them

**Comment by HelderRocket** [comment]
> They can and you are free to implement them

I for one would love to, but I lack the most basic knowledge to do something like this. 😞

**Comment by Julmik647** [comment]
There is an app called [SmartTube](https://smarttubeapp.github.io/).

Info for developers: beacuse YouTube TV is web app, you can make WebView app that uses [this userscripts](https://github.com/reisxd/TizenTube/tree/main/mods). It's possible and [Better Xcloud app](https://better-xcloud.github.io/android/) is an example.
