### ISSUE TITLE
feat (YT Music): Custom Icon for YT Music app.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [ReVanced/revanced-patches#2749]
### Feature description

YT ReVanced has a patch for custom branding icon.

I'm requesting the same patch for ReVanced YT Music app.

### Motivation

1. It provides a personalized feel to the app.
2. Icon is literally the first thing you see even before you start using the app, so that's a very big motivation.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by ILoveOpenSourceApplications** [comment]
#607

**Comment by KobeW50** [comment]
https://github.com/ReVanced/revanced-patches/issues/362

**Comment by Aryan-Chauhan** [comment]
Proper reason not provided for closing the issue.

**Comment by oSumAtrIX** [comment]
Acknowledgements not met.
