### ISSUE TITLE
feat(YT): Directly open ReVanced Settings when tapped on Settings icon.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [ReVanced/revanced-patches#2750]
### Feature description

In the top right corner of You tab, there is a Settings icon. So, I'm requesting for a patch that directly opens ReVanced Settings when you tap on it. If implemented, the following obstructions can be avoided:
1. General
2. Account
3. Data saving
4. Auto-play
5. Video quality preferences
6. Background and downloads
7. Watch on TV
8. Manage all history
9. Your data in YouTube
10. Privacy
11. Try experimental new features
12. Purchases and memberships
13. Billing and payments
14. Notifications
15. Connected apps
16. Live chat
17. Captions
18. Accessibility
19. About
![Screenshot_2024-02-20-23-30-58-66_f22faf49515899f9781ec174a4d85388](https://github.com/ReVanced/revanced-patches/assets/91815107/22339829-1047-45d5-aba3-a59c9100aeb4)

### Motivation

1. I have minimal coding knowledge, but this seems pretty easy for ReVanced Team to implement, since they've already implemented much more complex features in the past.
2. It will partially/fully solve these requests in the cosmetically best possible manner: #2629 , #2733 , #2504 

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
The linked issues are already solved by another PR or are closed. The motivation is insufficient.

**Comment by oSumAtrIX** [comment]
Your assumption that it's easy is wrong. Neither is it a motivation that supports that this feature should be implemented. Refer to my previous comment.

**Comment by Aryan-Chauhan** [comment]
> Your assumption that it's easy is wrong. Neither is it a motivation that supports that this feature should be implemented. Refer to my previous comment.

Okay, agreed it's not easy, plus it's time-consuming & requires efforts.

But look at the upside. ReVanced Settings are accessed frequently by new/old users alike, so won't it be super-convenient to just open them up by one-tap? In my books, yes.

Doing so will also result in an indirect benefit: All 29 redundant menus will become inaccessible/hidden.

So, two super-useful functionality will be acheived by one single patch.

You can also refer to my previous comments & issues.

**Comment by oSumAtrIX** [comment]
No, the settings are usually configured once and not touched afterwards. As I said, you scroll down once and click on ReVanced. The shortcut is not worth the effort

**Comment by Aryan-Chauhan** [comment]
@LisoUseInAIKyrios What's your opinion regarding this?

Kindly inform me if direct mentions are against the rules.

**Comment by Aryan-Chauhan** [comment]
> No, the settings are usually configured once and not touched afterwards. As I said, you scroll down once and click on ReVanced. The shortcut is not worth the effort 

Your assumption that settings are configured once and not touched afterwards, is wrong. Everyday, new users are starting to use ReVanced & it's forks on their phones.

Surely you don't believe that, if ReVanced has 100 users today, then it will remain 100 users in the future. Of course, new users will join & they will experiment with the settings.

So, this is why the shortcut is worth the effort, if not by the team, then by whoever is interested.

**Comment by Aryan-Chauhan** [comment]
> [2737](https://github.com/ReVanced/revanced-patches/pull/2737) moves the ReVanced sub-menu to the top of the settings list, removing the need to hide the stock settings (you can visually ignore the stock settings, because there is no more scrolling past them)
> 
> ![Settings](https://github.com/ReVanced/revanced-patches/assets/118716522/b4901d9a-c368-4246-9295-22ec810e97dc)
> 

Yes, that's a great PR & I'm grateful to the person who wrote the code.

But I'm insisting this issue/request shouldn't be linked to that PR. It should be treated as an standalone request.
