### ISSUE TITLE
bug: MicroG not being recognized?

### ISSUE THREAD

**Issue by ZooBuZZ** [ReVanced/revanced-patches#2751]
### Type

Error at runtime

### Bug description

Downloaded and installed latest 1.6.1 revanced manager.
Downloaded YT v18.23.35 apk.
Used the patcher with default settings (52 patches, tried many other variations too).
Tried both saving (exporting) the apk and immediate install via both root and non-root install.
New patched apk seems to install fine but on launch I always get this error:
Vanced MicroG is not installed. Please install it.

I have been using revanced for 6 months or so. Never saw this error before and I've been on the same OS (calyx OS) the entire time.  I have patched I think 3 or 4 previous versions of YT without any issues.  I've had the same version of MicroG setup and running the whole time.  I just checked, MicroG is still working for other apps and still passes all self checks.  But revanced YT seems to think I don't have MicroG installed anymore?  I did try patching without micro g as a patch, then it just crashes immediately on launch. I tried an older version of YT apk to patch, but that didn't seem to help either.  Now I tried installing my old patched revanced apk and that just crashes on load. 

### Steps to reproduce

Downloaded and installed latest 1.6.1 revanced manager.
Downloaded YT v18.23.35 apk.
Used the patcher with default settings (52 patches, tried many other variations too).
Tried both saving (exporting) the apk and immediate install via both root and non-root install.
New patched apk seems to install fine but on launch I always get this error:
Vanced MicroG is not installed. Please install it.

### Relevant log output

```shell
I'm not entirely sure if I got the right logcat here...but I think I was able to get this info? 

beginning of crash
08-04 14:37:20.103  3044  3044 E AndroidRuntime: FATAL EXCEPTION: main
08-04 14:37:20.103  3044  3044 E AndroidRuntime: Process: com.google.android.youtube, PID: 3044
08-04 14:37:20.103  3044  3044 E AndroidRuntime: java.lang.RuntimeException: Unable to instantiate application com.google.android.apps.youtube.app.YouTubeTikTokRoot_Application package com.google.android.youtube: java.lang.RuntimeException: Failed to parse XML configuration from main_shortcuts
08-04 14:37:20.103  3044  3044 E AndroidRuntime:        at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1466)
08-04 14:37:20.103  3044  3044 E AndroidRuntime:        at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1395)
08-04 14:37:20.103  3044  3044 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6732)
08-04 14:37:20.103  3044  3044 E AndroidRuntime:        at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
08-04 14:37:20.103  3044  3044 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2129)
08-04 14:37:20.103  3044  3044 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
08-04 14:37:20.103  3044  3044 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:201)
08-04 14:37:20.103  3044  3044 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:288)
08-04 14:37:20.103  3044  3044 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7884)
08-04 14:37:20.103  3044  3044 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
08-04 14:37:20.103  3044  3044 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
08-04 14:37:20.103  3044  3044 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
08-04 14:37:20.103  3044  3044 E AndroidRuntime: Caused by: java.lang.RuntimeException: Failed to parse XML configuration from main_shortcuts
```

### Additional context

Revanced:
version: 1.6.1
build: release
model: pixel 6a
android version 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
You need `Vanced MicroG` not `MicroG`. If you are using `MicroG` do not patch using `Vanced MicroG support` patch.

**Comment by Lavmint** [comment]
> You need `Vanced MicroG` not `MicroG`. If you are using `MicroG` do not patch using `Vanced MicroG support` patch.

This solution is not working. 

Current suggest version of YouTube app by RevancedManager is `18.34.44`. 
Applying `default` patches `excluding Vanced MicroG ` to this version is causes app do `exit on launch`.

**Unpatched YouTube** app works with system-wide MicroG just fine, but even minimal patching with 2 anti-ad patches will results the app not able to launch at all.
