### ISSUE TITLE
feat: More resolutions download

### ISSUE THREAD

**Issue by GKid94** [ReVanced/revanced-patches#2756]
### Application

YouTube Revanced

### Issue

Add an option to download more resolutions and mp3
![Screenshot_2023-08-05-23-33-42-225_app revanced android youtube](https://github.com/ReVanced/revanced-patches/assets/18757054/8837c345-ee97-403f-ba9d-9f85706d1e2d)

### Patch

Download video and audio

### Motivation

To download video and audio of videos

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
External downloader is available.

**Comment by GKid94** [comment]
> External downloader is available.

What's that?

**Comment by oSumAtrIX** [comment]
A patch for YouTube.

**Comment by GKid94** [comment]
> A patch for YouTube.

It doesn't work, it shows an error

**Comment by oSumAtrIX** [comment]
Open an issue in the respective patches repository

**Comment by GKid94** [comment]
> Open an issue in the respective patches repository

Can't find it

**Comment by GKid94** [comment]
> It's probably because no external downloader is installed. (User error)

Why can't I download it in Revanced?

**Comment by GKid94** [comment]
> What is the error message you are seeing?
> 
> You seem confused about how to use the feature.

![Screenshot_2023-08-07-13-52-18-059_app revanced android youtube](https://github.com/ReVanced/revanced-patches/assets/18757054/3091877e-7cb1-4d49-94f9-2db6a8e6f21c)

**Comment by GKid94** [comment]
> Do what it says.
> 
> Install [NewPipe](https://github.com/TeamNewPipe/NewPipe/)
> 
> If you need anymore help, then search the internet because installing NewPipe is outside of ReVanced.

Can you make it so that I can download in Revanced instead?

**Comment by oSumAtrIX** [comment]
The external downloader suffices. You can use any.

**Comment by GKid94** [comment]
> The external downloader suffices. You can use any.

Suffices?

**Comment by GKid94** [comment]
> 

Ok but it will be easier and will use less memory only with Revanced

**Comment by GKid94** [comment]
> The external downloader suffices. You can use any.

Ok but it will be easier and will use less memory only with Revanced

**Comment by GKid94** [comment]
> RAM is not a problem

It kind of is on phones and storage too, only Revanced uses 1GB of storage which is a lot for a app

**Comment by oSumAtrIX** [comment]
1GB is less then 1% of a typical phone storage and no ReVanced does not use 1GB, if you refer to ReVanced Manager.

**Comment by GKid94** [comment]
> 1GB is less then 1% of a typical phone storage and no ReVanced does not use 1GB, if you refer to ReVanced Manager.

![Screenshot_2023-08-09-14-49-22-248_com miui securitycenter](https://github.com/ReVanced/revanced-patches/assets/18757054/f87ad55d-b1e3-4435-9bb3-f93317489806)
![Screenshot_2023-08-09-14-49-31-179_com miui securitycenter](https://github.com/ReVanced/revanced-patches/assets/18757054/8f069f5b-f23c-4675-b437-155f8a2c7c49)
![Screenshot_2023-08-09-14-49-42-679_com android settings](https://github.com/ReVanced/revanced-patches/assets/18757054/b227d342-495c-4f5d-bd58-82507089302b)
![Screenshot_2023-08-09-14-49-48-107_com miui securitycenter](https://github.com/ReVanced/revanced-patches/assets/18757054/a5877543-3604-4a5b-8b86-5ad7f93fd9a4)

**Comment by GKid94** [comment]
> This is YouTube and not ReVanced.

It's YouTube Revanced

**Comment by oSumAtrIX** [comment]
YouTube takes this space, not ReVanced

**Comment by GKid94** [comment]
> YouTube takes this space, not ReVanced

Ok

**Comment by GKid94** [comment]
@oSumAtrIX @LisoUseInAIKyrios The Revanced player options are also missing on short videos
