### ISSUE TITLE
bug: RIF: Failed to resolve GetUserAgentFingerprint

### ISSUE THREAD

**Issue by gitgudscrubb** [ReVanced/revanced-patches#2757]
### Type

Error while patching

### Bug description

ReVanced v2.187.0
RIF v5.6.2
Patch responds with "Failed to resolve GetUserAgentFingerprint"
Manually downloaded 2.187.0-dev.10 (spoof user agent) to default device storage, with no documentation on how to implement pre-release patches 

### Steps to reproduce

1. Install ReVanced Manager and update to latest v2.187.0
2. Download RIF v5.6.2.apk
3. Install RIF (via android/native app installer)
4. ReVanced Manager > Patcher > RIF > Patch: Spoof Client > Done
5. Patch 

alternatively

1. Install ReVanced Manager and update to latest v2.187.0
2. Download RIF v5.6.2.apk
3. ReVanced Manager > Select an Application > Storage > RIF_v5.6.2.apk 
4. ReVanced Manager > Patcher > RIF > Patch: Spoof Client > Done
5. Patch 

alternatively, conduct same steps with ReVanced 2.187.0-dev.10 patch stored in default device storage

### Relevant log output

```shell
Finished! 
Failed to apply Spoof client: Failed to resolve GetUserAgentFingerprint
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Use the latest version of RiF.
