### ISSUE TITLE
feat (YouTube): Hide `Shop` tag near the more button

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [ReVanced/revanced-patches#2758]
### Feature description

There's already a patch which hides the shopping links in video description, but as a residue there's still the `Shop` tag which remains on the video. 

The `Shop` tag:

![Screenshot_20240221_185200_YouTube](https://github.com/ReVanced/revanced-patches/assets/117499019/e543a9e0-af82-441e-81fa-b8eb32e7f92d)

### Motivation

Hiding it can be a part of the `Hide Shopping Links in Video Description` patch which then removes all remains of a shopping link ever being there in the description in the first place.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
This won't happen unless we know how to modify Litho components properly. The view is flattened and not worth the effort to figure out just to hide this.

**Comment by ILoveOpenSourceApplications** [comment]
It would have been nice but if it's a task which is too difficult, I understand.

**Comment by ILoveOpenSourceApplications** [comment]
@LisoUseInAIKyrios, can the method you mentioned in this [comment](https://github.com/ReVanced/revanced-patches/issues/588#issuecomment-2056396225) be used to hide this component?
<img width="713" alt="image" src="https://github.com/ReVanced/revanced-patches/assets/117499019/7495fd9d-eb48-401f-923c-3ca0b7582c81">

**Comment by ILoveOpenSourceApplications** [comment]
Research if this method of hiding is possible or not/ if this `metadata_badge`will hide it or not?

**Comment by ILoveOpenSourceApplications** [comment]
Is this something a novice can do without any background knowledge?

**Comment by ILoveOpenSourceApplications** [comment]
> No coding skills are needed. It's a matter of trying to identify where UI components are loaded in the code and it's more time consuming than skill related.

Okay. Is there a guide which I can follow for this? If so, when I have time, I'll try giving it a shot.

**Comment by ILoveOpenSourceApplications** [comment]
Am I doing something wrong here or is this as far as I can go?
![Screenshot 2024-04-28 150306](https://github.com/ReVanced/revanced-patches/assets/117499019/2b0f8fc9-161b-41b1-b2a8-e7574d6948a4)

**Comment by ILoveOpenSourceApplications** [comment]
So that means hiding it is impossoble or possible?

**Comment by ILoveOpenSourceApplications** [comment]
> hiding using the strategy I mentioned that you quoted seems unlikely.

Ah, I see. Any new strategies available which we can try?

**Comment by ILoveOpenSourceApplications** [comment]
> Hook onto the litho code that loads/draws image from resources in the apk, and selectively hide if the image is `yt_bag_outline`.

So the normal logcat method and capture which litho has the bufferstring `yt_bag_outline` in it?

**Comment by ILoveOpenSourceApplications** [comment]
```kotlin
04-28 15:32:37.251  8481 14233 D revanced: LithoFilterPatch: Searching ID: null Path: video_metadata.eml|2989a5833b66f5b9|video_metadata_inner.eml|f705d32e61523ab9|CellType|ContainerType|ContainerType|ContainerType|video_subtitle.eml|4e63b22e4c3b9aae|TextType| BufferStrings: 3.9M views11 days agoShop...moreΓ¥Ö...moreΓ¥Ösans-serif-mediumΓ¥Ö3.9M views  11d ago   Shop  ...moreΓ¥Öyt_outline_bag_black_24Γ¥Ösans-serif-mediumΓ¥Ösans-serif-regularΓ¥Ösans-serif-regularΓ¥Ösans-serif-regularΓ¥Ösans-serif-regularΓ¥Ösans-serif-regularΓ¥Ö
```

**Comment by ILoveOpenSourceApplications** [comment]
> No, I meant adding a new patch hook where litho is loading image resources (or where those image resources are drawn to screen).

So implementing a new method for hiding such components.

**Comment by ILoveOpenSourceApplications** [comment]
Welp, it was a worth a shot.

**Comment by oSumAtrIX** [comment]
Litho seems to support accessibility options/ screen readers ,(such as the app "Developer Assistant" from Play Store):

![Screenshot_20240428-135201](https://github.com/ReVanced/revanced-patches/assets/13122796/cde90e3c-f4f1-4e2d-aced-de7974336980)

Evidently the view group has been flattened by Yoga to a view meaning that there's no way to edit it unless we figure out how using the Litho methods to edit it and trigger a rerender works.

An other method is to modify the YouTube /player response. This response should include metadata such as if the video has this Shopping stuff. It could perhaps also be returned as a Litho buffer, but all this needs more reversing.

**Comment by ILoveOpenSourceApplications** [comment]
Just saw that @inotia00 implemented a patch to hide this. 
Integrations:https://github.com/inotia00/revanced-integrations/commit/ee4f543017430d04d2fb7fc3a297035543695d6c

**Comment by ILoveOpenSourceApplications** [comment]
> Just saw that [@inotia00](https://github.com/inotia00) implemented a patch to hide this. Integrations:[inotia00/revanced-integrations@ee4f543](https://github.com/inotia00/revanced-integrations/commit/ee4f543017430d04d2fb7fc3a297035543695d6c)

@LisoUseInAIKyrios, is this an applicable solution to this issue?

**Comment by ILoveOpenSourceApplications** [comment]
Anyone?

**Comment by ILoveOpenSourceApplications** [comment]
Good thinking I guess, never know what the future holds. But, is the implementation something we can adapt and use over here as well?

**Comment by ILoveOpenSourceApplications** [comment]
Not me, I haven't reached there yet. Someone a bit more savvy needs to look into this.
