### ISSUE TITLE
The 'Custom Branding' also changes app icon when when u don't specify it to

### ISSUE THREAD

**Issue by Shane9248** [ReVanced/revanced-patches#2759]
### Bug description

![Screenshot_20240221-195803](https://github.com/ReVanced/revanced-patches/assets/83491863/568a68f6-01d0-4f1f-b3d9-09af15edf89f)

So i wanted to change the app name but wanted to keep the official yt logo ..but in the patch when u click it , it also changes the logo even when u don't specify it to 
![Screenshot_20240221-195819](https://github.com/ReVanced/revanced-patches/assets/83491863/92c8690c-4629-45d1-b4c9-bb0cd459b32b)

I don't have enough knowledge to custom change the logo 
![Screenshot_20240221-195844](https://github.com/ReVanced/revanced-patches/assets/83491863/809eeece-6d44-4bba-987c-fe4f7afa3817)

### Solution

The logo and name should be separate so that i can keep the name of something else but keep the original yt logo 

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
The default option value is set to ReVanced. If you want to keep the original logo, select it in the option

**Comment by Shane9248** [comment]
> The default option value is set to ReVanced. If you want to keep the original logo, select it in the option

![Screenshot_20240221-201254.png](https://github.com/ReVanced/revanced-patches/assets/83491863/e9a6ab8e-49ca-4aa0-9ce1-12f994437110)

as i said i don't know how to change all this.. don't have much knowledge of this...i want to only change the name to ' Youtube Revanced' i do not want to change the original logo

**Comment by oSumAtrIX** [comment]
This is not a support channel as noted in the issue template.
