### ISSUE TITLE
bug: video opened via link doesn't show fully

### ISSUE THREAD

**Issue by Girofox** [ReVanced/revanced-patches#2760]
### Bug description
When i open a youtube link, YouTube Revanced (extended version too) just shows the playing video in a miniature version in lower half. Can't go into fullscreen or make it larger, only if i switch the app and go back.
![Screenshot_20240221_212612_ReVanced Extended](https://github.com/ReVanced/revanced-patches/assets/43116061/04d357b5-f379-471f-b270-ae3fc85410d8)

### Workaround
Switch to another app and then return to YT Revanced

### Additional context

Opening YouTube links with YouTube Revanced

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Unofficial patches.
