### ISSUE TITLE
feat: Reduce the pan enabled zoom level from 1.5x to 1.0x and above.

### ISSUE THREAD

**Issue by alcatraz-zz** [ReVanced/revanced-patches#2761]
### Feature description

Today Revanced/Youtube allows for panning the video frame at zoom 1.5x or above. 

I would very much like to be able to pan the frame at all zoom levels above 1x already.

It's a feature that I miss both on my 16:10 tablet and 20:9 phone. It's impossible to adjust the frame to get important information on the screen. Sometimes important information is in two corners of a video frame and currently the only solution is to constantly zoom in and out for each damn video. If you've ever tried panning at 1.5x zoom or above it's so effortless and convenient. Only problem is that at 1.5x you can't get two corners in the frame.

![Polish_20230822_085404613](https://github.com/ReVanced/revanced-patches/assets/250045/6f85dfa5-09a4-45bc-b74a-1f6a85de8d7a)

### Motivation

Youtube today is still 99% 16:9 and a majority of devices aren't 16:9. Our only two options are black bars or cropped centered frame. Why not make the best of the situation and allow us to crop the frame the way we want it? At 1.5x zoom it's childsplay to move the frame around. Why not keep that feature for "fit to screen" zoom levels?

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
https://github.com/ReVanced/revanced-patches/issues/426
