### ISSUE TITLE
[Feature] Unlock full version of poweramp.

### ISSUE THREAD

**Issue by TeaEndsAcronyms** [ReVanced/revanced-patches#2762]
### Application

[Poweramp music player.](https://play.google.com/store/apps/details?id=com.maxmpz.audioplayer)

### Issue

Poweramp is set on a 15 day trial. I'd like to be able to use poweramp and all it's features for more than **15 days.**

### Patch

A patch to remove the trial/unlock the full version.

### Motivation

It allows people to use (in my experience) the best and most feature-rich music player.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
#1342
