### ISSUE TITLE
feat(YouTube/Theme): Material You Theme Support

### ISSUE THREAD

**Issue by kazimmt** [ReVanced/revanced-patches#2764]
### Application

Name: YouTube
Package id: com.google.android.youtube

### Issue

Current ReVanced YouTube Theme doesn't have an option to add MaterialYou

### Additional Info
#318 was closed as <i>wrong place to suggest patches.</i>
maybe this issue panel wasn't the correct place to submit patch request back then.

#616 was also closed (IDK Why)

### Note
If we make changes in current patch option like
`@android:color/black` -> `@android:color/system_neutral1_900`
&
`@android:color/white` -> `@android:color/system_neutral1_50`
It applies monet theming in few part ~~but break correct android theming.~~

### Patch

Modify `theme` patch & add an option to select Users wants amoled black or monet theme

Like an patch option where user can select
- Amoled Black = True
- MaterialYou = False

or
- Amoled Black = False
- MaterialYou = True

Here is an example which changes needed to apply pure materialYou theming in YouTube
https://github.com/inotia00/revanced-patches/tree/revanced-extended/src/main/resources/youtube/materialyou

### Motivation

Many android 12+ users prefer Monet theming over Black or Dark color.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Where and how does it break?

**Comment by kazimmt** [comment]
> Where and how does it break?

NVM, Breaking theming was my issue (i find it)
but Material You Doesn't apply to all part, like Notification & Subscription's dot (red dot)
It should also follow material theme. 
![-2147483648_-210329](https://github.com/ReVanced/revanced-patches/assets/82371061/669dece6-a6ee-4c89-894d-9540229f6cd0)

**Comment by oSumAtrIX** [comment]
Why would the notification dot change color?

**Comment by YT-Advanced** [comment]
> > Where and how does it break?
> 
> NVM, Breaking theming was my issue (i find it) but Material You Doesn't apply to all part, like Notification & Subscription's dot (red dot) It should also follow material theme. ![-2147483648_-210329](https://user-images.githubusercontent.com/82371061/259048026-669dece6-a6ee-4c89-894d-9540229f6cd0.jpg)

Keep this dot red may better

**Comment by oSumAtrIX** [comment]
Yes, red is a signal color; not sure why it should be changed, anyways the issue is invalid since material you is supported.

**Comment by kazimmt** [comment]
> Keep this dot red may better

I guess Red dot doesn't match with Material Theming.

**Comment by oSumAtrIX** [comment]
Reference the M3 spec sheet in this regard then.

**Comment by kazimmt** [comment]
> Reference the M3 spec sheet in this regard then.

https://m3.material.io/components/badges/overview

**Comment by kazimmt** [comment]
> > Reference the M3 spec sheet in this regard then.
> 
> https://m3.material.io/components/badges/overview

I guess you can re-open the issue now. Badge are not matching Monet Theming after all
