### ISSUE TITLE
feat: support for pocketcast 

### ISSUE THREAD

**Issue by Darkcast** [ReVanced/revanced-patches#2765]
### Feature description

Request patch support for pocketcast
https://play.google.com/store/apps/details?id=au.com.shiftyjelly.pocketcasts

Patches: 
remove ads that get loaded on podcasts
Remove trackers

Thanks 

### Motivation

This is the top podcast app in the play store
I would really appreciate 🙏☺️

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [ ] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
<img width="418" alt="image" src="https://github.com/ReVanced/revanced-patches/assets/13122796/855bff4f-cc14-4d73-8ba4-ea3d6f8e6474">

It is not the top podcast app in PlayStore. Insufficient motivation.
