### ISSUE TITLE
feat (YouTube): Add additional sorting methods for watching other user's playlists.

### ISSUE THREAD

**Issue by Lucius-Will** [ReVanced/revanced-patches#2767]
### Feature description

Next to the "Loop" and "Random sorting" buttons, add additional buttons with other methods of sorting videos in other users' playlists. For the viewer.

Examples of additional sorting:
"Original order" - undo all changes in the video list. Return the default order.
"Reverse list" - reverse default (or current?) order.
"By date of publication" - up/down
"By number of views" - up/down
"By number of likes" - up/down
"By number of comments" - up/down
"Other sorting methods" - less commonly used sorting methods

Perhaps there are some other ways that did not come to my mind.

![Screenshot_2024-02-24-00-31-00-974_app rvx android youtube — копия](https://github.com/ReVanced/revanced-patches/assets/161041995/e9a74ca0-acfa-4c15-9395-ee0d1279853d)

---------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------

![marked 2](https://github.com/ReVanced/revanced-patches/assets/161041995/8bf1b622-db6e-4386-a678-b4f283319cae)

### Motivation

YouTube has already made a function for the viewer to manually change the order of videos in the playlist that he is watching. And these changes are visible only to the viewer who made this re-sorting. But now the playlist can only be changed manually by dragging each video up or down the playlist. And the viewer can shuffle/random the video playback order.

![cut 1](https://github.com/ReVanced/revanced-patches/assets/161041995/d1b48241-31e0-4963-966e-4f3942fb3526)

But why not expand this functionality?

![cut 2](https://github.com/ReVanced/revanced-patches/assets/161041995/70c66f7c-0785-4c51-a1b6-6f30e1122863)

For example, it often happens that the author of a playlist keeps sorting from new videos to old ones in it. And I need to watch the videos in the order of their release. From old to new. To do this, I need to reverse the playlist. And viewers simply do not have such a basic function! This is stupid!

![cut 4](https://github.com/ReVanced/revanced-patches/assets/161041995/ba51aaee-c397-46e9-ad0a-818f58ccda11)

And there is also a lack of the ability to sort videos by date. At least by the date of publication of the video on YouTube. It would also be useful to add sorting by views, by number of likes, comments, etc.

The current sorting functionality is extremely poor. Viewers really lack different options for sorting the order of videos in other people's playlists.

Moreover, we already have a mechanism for manually sorting other people's playlists - this is an excellent preparation for creating other sorting methods. We just need to add additional sorting methods.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by Lucius-Will** [comment]
Offer your suggestions, what other sorting methods are needed.

**Comment by Lucius-Will** [comment]
> The sorting options are provided by YouTube, and the list of videos is already sorted by YT servers before the client receives it.

There are too few sorting methods from YouTube for viewers.

The viewer can change the order of the videos in the list manually. This means that the client's code already has a mechanism for changing the list for the viewer. So, we can add other client-side sorting methods using this mechanism.

We need to add at least simple sorting methods like "Reverse list".

And more complex sorting methods can be done by receiving information from the server about all the videos in the list. After that, FOR THE VIEWER to change the order of the videos in the list by an algorithm. Using this mechanism, which YouTube has made to manually change the list by the viewer.

**Comment by Lucius-Will** [comment]
> The sorting options are provided by YouTube, and the list of videos is already sorted by YT servers before the client receives it.

Does the "Random list" button also work through the server? Or is the list randomizing on the client side?

**Comment by Lucius-Will** [comment]
> You don't quite understand. There is no sorting done on the client. The client provides a sorting parameter to the server, and the server hands back a partial list of the results that is already sorted.

It's clear now. 

Maybe we could expand this part with lists, on the client-side? Maybe we should make an additional model for working with lists? Which the application would switch to, when the viewer clicks on one of the buttons with additional sorting methods?

When the viewer clicks any of the additional sorting buttons, the client switches to a different model of working with the playlist. And the application shows the viewer a notification where it says something like - "Now the application's work with this playlist has been switched to another/third-party/extended model. The app will return to the basic model when the playlist will be closed, or if you click on the <icon> button."

Next, the client receives the entire list of videos in the playlist from the server. And then the client independently changes this list on its side. If necessary, the client could also request additional information from the server about videos from the playlist, for other specific sorting methods.

**Comment by Lucius-Will** [comment]
> There are channels on YouTube with [millions of videos](https://youtube.com/@RoelVandePaar), and all 2 million videos are definitely not sent to the client so it can sort client side and then show just 10-20 videos at a time in a list. It's all done server side.

Yes, I got that part. In case of large playlists, we could set a limit. An additional model could be turned on only on playlists of no more than some size. For example, no more than 1000 videos.

**Comment by Lucius-Will** [comment]
> There are channels on YouTube with [millions of videos](https://youtube.com/@RoelVandePaar), and all 2 million videos are definitely not sent to the client so it can sort client side and then show just 10-20 videos at a time in a list. It's all done server side.

By the way, as far as I know, playlists cannot be more than 5,000 videos. I have come across this myself in practice. So the server does not need to send data about 2 million videos. Maximum 5,000.

**Comment by oSumAtrIX** [comment]
The idea exceeded it's worth to be implemented. Use a playlist manager app

**Comment by Lucius-Will** [comment]
> The idea exceeded it's worth to be implemented. Use a playlist manager app

Are there "playlist manager apps"? Interesting. Maybe it will help. What are they called?

**Comment by RobinRMC** [comment]
It could also work by fetching all of the video links, sorting them and then making a local queue that only loads the information of the first few videos, until you load more.

**Comment by Mik39907** [comment]
> > The idea exceeded it's worth to be implemented. Use a playlist manager app
> 
> Do "playlist manager apps" already exist? Which allow a viewer to sort other people's playlists for personal viewing? Interesting. Maybe it will help. What are they called?

There are a few extensions for browsers and also apparently this feature exists on smartube
