### ISSUE TITLE
bug(Twitter/X): `Hide ads` not working when searching

### ISSUE THREAD

**Issue by lluni** [ReVanced/revanced-patches#2768]
### Bug description

When searching for something, ads are not hidden as they should be:
![image](https://github.com/ReVanced/revanced-patches/assets/36239317/4d1fb660-a927-4a54-a10b-795afe71829a)

Everywhere else, the patch seems to work as expected.

Steps to reproduce:
- navigate to search tab
- search for something, e.g. `test`
- ads are displayed in the search results

Used patches:
- Hide ads
- Hide recommended users
- Unlock downloads

### Acknowledgements

- [ ] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
#286
