### ISSUE TITLE
bug: Twitch Purple AdBlock, TTV LOL don't work

### ISSUE THREAD

**Issue by girshcatt** [ReVanced/revanced-patches#2768]
### Type

Error at runtime

### Bug description

Purple AdBlock, TTV LOL don't work anymore, this is not rv patches problem, they just don't work anymore, this gives me much errors, please remove this adblocks and add alternatives

(P.S. forgot to say please bump reccomended twitch version to new 15.8.0, patches work the same as 15.4.1)

### Steps to reproduce

Patch Twitch 15.4.1 or any other version with this patches at least:
1.Settings
2.Block embedded ads

### Relevant log output

```shell
Sry, don't know how get logs(
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Why should they not work?

**Comment by oSumAtrIX** [comment]
Proxy down.

**Comment by girshcatt** [comment]
Can you add alternatives adblocks for some time and can you bump twitch reccomended version to new 15.8.0?
