### ISSUE TITLE
feat(Cashew): Add a patch to Unlock Pro 

### ISSUE THREAD

**Issue by arnobk** [ReVanced/revanced-patches#2770]
### Feature description

Add a patch to unlock pro version of this budget/finance tracker app named Cashew. 

Playstore URL: https://play.google.com/store/apps/details?id=com.budget.tracker_app

### Motivation

This app is one of the best under Budget/Finance category with great modern UI and features. The app is in active development. But the lifetime price of 20$ is a lot to afford. An `Unlock pro` patch will be greatly appreciated.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Closing according to contribution guidelines
