### ISSUE TITLE
bug(music): constrain to last working version

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [ReVanced/revanced-patches#2770]
### Type

Error while patching

### Bug description

The last working version was 6.10.52. The docs and manager claims that it supports any version, which is incorrect

### Steps to reproduce

1. Patch 6.10.52 yt music w/ default patches
2. It worked
3. Patch some newer version
4. it aborted

### Relevant log output

```shell
N/A
```

### Solution

Constrain to last working version

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by kazimmt** [comment]
Works with Current dev release
(Bcz it was patcher issue & fixed)

![image](https://github.com/ReVanced/revanced-patches/assets/82371061/bfb8f4cf-c5d8-460e-a68a-42ddbe3d4c3b)

**Comment by SodaWithoutSparkles** [comment]
If patcher makes its way to stable (in manager) quicker than patches, no actions are needed.

Otherwise, please constrain the version to not confuse ppl.

**Comment by kazimmt** [comment]
Try dev patches & integrations release.
#2732 will fix this issue

**Comment by oSumAtrIX** [comment]
Doing what this issue suggests requires two commits, one that constraints the version and one that removes them once not needed anymore, and because patcher needs a bump, waiting for that is a better idea.
