### ISSUE TITLE
feat (Reddit): auto block or hide any post from bot username

### ISSUE THREAD

**Issue by boydaihungst** [ReVanced/revanced-patches#2773]
### Feature description

Target app: com.reddit.frontpage

Feature to filter out any posts and comments with specific username use regex pattern. E.g: `/^.+-.+-\d+$/g` will block any user's posts, whose username: `anyword-anyword-12345`. They are typically name of a bot.
![Screenshot_20240226-081955_Reddit](https://github.com/ReVanced/revanced-patches/assets/38396158/de0067ef-d27c-42e5-aa59-b7cb6958ee3e)

### Motivation

With the recent Reddit API changes, so many bots are reposting old images or videos, nonsense NSFWs, and provocative words to farm karma. So this feature will reduce the times user see the bot's posts and comments.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Many users have this format of usernames. The feature is not worth blocking mostly users.
