### ISSUE TITLE
feat (YouTube): Option to make "Save video to..." popup show on the bottom

### ISSUE THREAD

**Issue by Crunchbits** [ReVanced/revanced-patches#2773]
### Application

YouTube

### Issue

"Save video to..." popup used to be aligned with the standard 3 dot menu in the bottom,  but the updated youtube layout made the design choice to move it all the way up making it much harder to reach.

<p align="center">
  <img src="https://github.com/ReVanced/revanced-patches/assets/87384615/70f1d2d8-5064-4a41-ac89-fc0d6e83e744" width="200" alt="S1">
  <img src="https://github.com/ReVanced/revanced-patches/assets/87384615/e0b82a64-203f-4e0b-9154-d4c8d6a75dd1" width="200" alt="S2">
</p>

### Patch

An option to make the "Save video to..." popup show on the bottom. 

### Motivation

I believe there are a lot of heavy users of youtube in the community who very often use playlists. This patch would help make saving/removing videos from playlist more convenient (especially for those that have tall phones).

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
This is a bug by YouTube.
