### ISSUE TITLE
feat(YT Music/Package Name): Change default package name to `app.revanced.android.youtube.music`

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [ReVanced/revanced-patches#2774]
### Feature description

The word "app" is repeated twice in the case of YT Music and it's not repeated for YouTube, resulting in an inconsistent default package name across both YouTube and YouTube Music.
For YouTube:
![Screenshot_2024-02-26-16-21-12-156_app revanced manager flutter~2](https://github.com/ReVanced/revanced-patches/assets/117499019/ee1cda47-494c-4506-84df-f255063dcff5)
For YouTube Music:
![Screenshot_2024-02-26-16-21-09-363_app revanced manager flutter~2](https://github.com/ReVanced/revanced-patches/assets/117499019/923ee94b-9631-4a5f-8515-0db27c2361be)

### Motivation

If implemented in an early stage where YT Music isn't having that many patches, the following patches which gets implemented won't have to undergo package name changes in the future. Also, as mentioned early, consistency across both YouTube apps as well.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by ILoveOpenSourceApplications** [comment]
This can be considered more of a suggestion than a feature request but since there's suggestion tag, I opted for feature request.

**Comment by oSumAtrIX** [comment]
The original package name is com.google.android.apps.youtube.music. The patch only changes the vendor to app.revanced.

**Comment by oSumAtrIX** [comment]
The patch acts consistently for all apps. Treating music differently and trimming the package name, just because it happens to have app in it, would be inconsistent.

**Comment by ILoveOpenSourceApplications** [comment]
I'm not talking specifically about any patches here, but yes it could be linked to `GMSCore support` patch, given that it's the patch which changes the package name for non-rooted users and if changed, would also need to change the default value of `Custom Package Name`.

> The patch acts consistently for all apps. Treating music differently and trimming the package name, just because it happens to have app in it, would be inconsistent.

Yes, from trimming point of view it can be considered as an extra step. Revanced removes only the vendor part from the beginning of the package, which is `com.google` for Google apps to `app.revanced`. Now instead of `app.revanced` let's say the URL was revanced.com, then the vendor names would've started with `com.revanced`, at which ponint I wouldn't have raised this suggestion as the package names would follow the same pattern as that of Google. The thing which bothers me the most is the fact that the word app is repeated twice in the package name, and changing it now would be a good decision due to the lesser number of patches. Also this pattern can be followed for any Google apps in the future which starts with `com.google.android.apps` as well, if we decide to introduce any patches for such apps.

**Comment by Ushie** [comment]
I agree it's weird, but I don't think ReVanced should do anything

You mentioned how this makes it inconsistent with YouTube, but that blame is on Google because those package names were inconsistent to begin with

ReVanced shouldn't modify the package name more than necessary, and if we do this change for cosmetic reasons, it'll break updating for many users, they'll end up with two installations of YouTube Music ReVanced

**Comment by ILoveOpenSourceApplications** [comment]
> I agree it's weird, but I don't think ReVanced should do anything

ReVanced is the only who can do something at this point.

> You mentioned how this makes it inconsistent with YouTube, but that blame is on Google because those package names were inconsistent to begin with.

Google being Google, they have multiple app packages following various naming schemes and I don't think their about to change it all now.

> ReVanced shouldn't modify the package name more than necessary, and if we do this change for cosmetic reasons, it'll break updating for many users, they'll end up with two installations of YouTube Music ReVanced

I know that the users will end up with two apps, but given we haven't updated some of our music patches to be supported to the latest version, we can provide a pop-up in manager or in the changelog saying "There's been a slight change in package name which will result in two yt music app. Please feel free to uninstall the older one." And this is necessary for those without root and those without custom package name patch.

**Comment by Ushie** [comment]
> ReVanced is the only who can do something at this point.

Even if we are, we shouldn't, it doesn't serve any purpose and in the process we'll be causing a migration for users who update, the package name represents the app's actual package name with the vendor switched out, any more changes past that are unnecessary

As for the solution you presented for ReVanced Manager, it isn't really attainable without hardcoding things which is something that ReVanced Manager doesn't do, because it's agnostic to what the patches are doing

**Comment by Ushie** [comment]
Google also knows that changing it will also serve no purpose, hence why they wouldn't change it even if they wanted to, but until Google does then this is what the package name will be, this inconsistency should be fixed on their side, not ours
