### ISSUE TITLE
bug: Watch history empty and watched videos arent saved

### ISSUE THREAD

**Issue by LostIntelligence** [ReVanced/revanced-patches#2778]
### Bug description

The watch history is empty except for shorts, watching any video does not add it to the history. Watching videos in the unpached app adds them to the history.

### Solution

Turning off Spoof app Signature fixes videos not being added to the history but any videos watched prior are still not shown in the history.

### Additional context

This issue seems to have started around the 28th of February

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by LostIntelligence** [comment]
#2779 is a better version of this issue and has more info

Closing this to avoid duplicates

**Comment by AbdulrahmanZaki** [comment]
How to turn off spoof app signature?
