### ISSUE TITLE
bug:(Youtube) youtube revanced all not in function 

### ISSUE THREAD

**Issue by susdos** [ReVanced/revanced-patches#2781]
### Bug description

all youtube revanced is not in function, youtube revanced just say is no internet connection, it happen after i close the "signature spoof" to fix the history not updating  problem  (some hour later). restart my phone or reinstall still not work. but normal youtube is 100% ok. now i can't turn on the "signature spoof" on the setting right now 

fig1. youtube revanced history page say "please check your internet connection" in chinese 
![Screenshot_2024_0229_063749](https://github.com/ReVanced/revanced-patches/assets/104917425/b7a63b93-12d6-46d2-8b9a-d746537f0696)
fig2. vanilla youtube page, you can see is function normally 
![Screenshot_2024_0229_063853](https://github.com/ReVanced/revanced-patches/assets/104917425/a29a2b47-e655-4ff9-9465-a762b6ad3c01)
fig3. setting page, you can see i cannot turn on the "signature spoof" now 
![Screenshot_2024_0229_065912](https://github.com/ReVanced/revanced-patches/assets/104917425/c1d3d048-eaf1-4998-ba61-862db1a19852)

please help me, i cannot watch youtube without adblock (this is all i known)😢😢

### Error logs

N/A

### Solution

No solution is currently available.

### Additional context

1.same as user "leantor12" give a thumbs up to this post. do not posting "I have the same issue" style comments.

2.this is my first bug report on here, please inform me if you find a issue same as my issue. 

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Relogin in microg.
