### ISSUE TITLE
feat: Playback speed overlay button

### ISSUE THREAD

**Issue by Gamerdotio** [ReVanced/revanced-patches#2782]
### Application

Youtube

### Issue

Make switching playback speed on videos easier by reducing the amount of taps required

### Patch

Create an overlay button that opens the playback speed flyout

### Motivation

Patch was in Revanced Extended and very useful for those who switch playback speeds a lot. Would be great to see in official Revanced patches

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
#1234
