### ISSUE TITLE
[Bug] TikTok patches aborted.

### ISSUE THREAD

**Issue by TeaEndsAcronyms** [ReVanced/revanced-patches#2785]
### Type

Error while patching

### Bug description

When ever I patch TikTok it aborts.

### Steps to reproduce

S1. Download TikTok.
S2. patch it.
S3. Error.

### Relevant log output

```shell
Tried this, its just blank.
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [ ] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Insufficient reproduction steps
