### ISSUE TITLE
feat: remove "enable watch history" prompt, and restore videos to homepage

### ISSUE THREAD

**Issue by TheRealAaronPrince** [ReVanced/revanced-patches#2787]
### Application

youtube

### Issue

youtube demands that the watch history be enabled to display videos on the home screen.

### Patch

disable the check for wether watch history is enabled.

enabling then re-disabling watch history returns videos to the home screen so it's definately a programmed "feature" and not a backend issue.

### Motivation

I've always kept watch history disabled as I don't want excess data collection, nor do I wish to clear the history after every video. the minimum auto clear time is 3 months. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
You can block it via any DNS blocker.

**Comment by konradmb** [comment]
@oSumAtrIX Blocking some domain would restore videos on homepage? I doubt it.

**Comment by Ushie** [comment]
Then try it, block *s.youtube.com and report back your discovering

If the watch history domain is inaccessible which means it's literally impossible to collect watch history, they definitely shouldn't block the home page

**Comment by konradmb** [comment]
W-what? I suppose it wouldn't magically make recommendations be shown again. This issue is about restoring it without re-enabling history, but I think it was closed with wrong explanation as DNS block will prevent data collection but won't do anything to titular "restore videos to homepage".

**Comment by TheRealAaronPrince** [comment]
@oSumAtrIX A DNS blocker would stop data collection, yes, but it would still require the history to be enabled for videos to be returned to the homepage. "via any dns blocker" are you suggesting I get another app to fix youtube? I thought this was the entire reason revanced existed in the first place.

**Comment by oSumAtrIX** [comment]
> the history to be enabled for videos to be returned to the homepage. 

The DNS blocker would prevent history from working; not sure how YouTube will react to that but try it, and yes, I mean a separate app.

**Comment by konradmb** [comment]
But that would stop feeding new videos to the algorithm. The recommendations would eventually get stale.

**Comment by oSumAtrIX** [comment]
...then enable watch history? What is your point?

**Comment by konradmb** [comment]
Because you've closed this issue implying that DNS block is the same. My point is blocking it in DNS is not a fix. Keeping history disabled without blocking collection would be one. I know adding such a patch is probably not easy and I don't require you to implement it, but DNS blocking is not a solution, just a workaround.

**Comment by oSumAtrIX** [comment]
The issue said:

> youtube demands that the watch history be enabled to display videos on the home screen.

OP requested a patch to allow getting suggestions while disabling history. You, on the other hand, said:

> But that would stop feeding new videos to the algorithm. The recommendations would eventually get stale.

OP wants history to be disabled, so your point doesn't make sense here.

**Comment by konradmb** [comment]
I know it doesn't make sense now, but before the recent changes "disabling" history meant only hiding it from you. It was "secretly" collected still. That's why they've changed it probably.
Judging by the title I thought that's what OP wanted - to bring back the good old days before August 8.

**Comment by Exhigh** [comment]
> Then try it, block *s.youtube.com and report back your discovering
> 
> If the watch history domain is inaccessible which means it's literally impossible to collect watch history, they definitely shouldn't block the home page

This just stops the prompt saying that the watch history needs to be enabled from showing up and no videos show up.

![photo_2023-08-20_17-35-10](https://github.com/ReVanced/revanced-patches/assets/28352755/8aed31e0-c05e-43da-97f3-d10a1719892b)

**Comment by Exhigh** [comment]
@Ushie

**Comment by Ushie** [comment]
That's horrible, yikes youtube

**Comment by Exhigh** [comment]
yep, the thing is enabling the watch history leads to my recommended feed turning into an absolute mess. Which is why i had it disabled after like watching a select few channels that i liked and then having it disabled so as to not get recommended whatever random stuff i end up watching, now well isn't it just grand.

**Comment by oSumAtrIX** [comment]
Did you enable the history in the settings and disable it via the DNS blocker?

**Comment by Exhigh** [comment]
no the history was disabled with the domain blocked being blocked. I assume enabling the watch history and blocking the domain would bring back the videos on the homepage but wouldnt alter the recommendations regardless of what you would watch

**Comment by Exhigh** [comment]
kind of like how it used to work, I would presume

**Comment by Exhigh** [comment]
> Did you enable the history in the settings and disable it via the DNS blocker?

Did as suggested above and it seems to be working as of now. Will need to keep an eye on the recommended videos, but this solution on a non-rooted device makes it so that if they have this setup, they wont be able to use a vpn unless they setup  something like a pi-hole or custom dns solution of sorts.

**Comment by kazimmt** [comment]
### Temporary Solution:
- Enable Watch History
- Watch any video (only one is enough)
- Keep atleast one video in watch history.
- Pause the history again
![](https://github.com/ReVanced/revanced-patches/assets/82371061/a1ea2b0f-41c6-42d3-a71b-c228c9c0ed02) ![](https://github.com/ReVanced/revanced-patches/assets/82371061/cfea9942-4270-4208-9b47-4fc49d3dad18)

**Comment by oSumAtrIX** [comment]
#2787

**Comment by kazimmt** [comment]
> #2787

You mention this post & closed it!
