### ISSUE TITLE
Universal hide patch.

### ISSUE THREAD

**Issue by tahirjamil** [ReVanced/revanced-patches#2788]
### Application

All Apps

### Issue

Some apps need to be hidden from home, but theres no patch

### Patch

Create universel patch that will hide that app icon

### Motivation

I dont know if its possible, but if it is then please do this.

### Acknowledgements

- [x] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Use a launcher that can hide apps.
