### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by Dhruvitt** [ReVanced/revanced-patches#2789]
### Bug description

Watch History doesn't  update but could this be a possible fix

### Solution

viewing the video doesn't update the watch history but the video preview that auto loads does seem to be updating the watch history.

### Additional context

maybe using the video preview api call might be a possible solution 
![IMG_20240301_195456](https://github.com/ReVanced/revanced-patches/assets/10249734/13c835e3-f633-4b99-8dc7-9ff489e178e0)
![IMG_20240301_195435](https://github.com/ReVanced/revanced-patches/assets/10249734/cf4131d1-918e-4cb7-aef4-54e81ba487df)

### Acknowledgements

- [ ] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
#2469

**Comment by KobeW50** [comment]
Isn't it https://github.com/ReVanced/revanced-patches/issues/2779?

Anyway, this solution is discussed in the comments there
