### ISSUE TITLE
feat: JoeyForReddit compatible with Mod Apk

### ISSUE THREAD

**Issue by SakuraSakuraSakuraChan** [ReVanced/revanced-patches#2790]
### Application

https://play.google.com/store/apps/details?id=o.o.joey (unavailable now)
https://uploadrar.com/i0ps1b0m1mwn (Mod apk file, pro feature unlocked)

### Issue

I can patch the original apk of Joey and it works perfectly, but for the Mod apk, the app FC quickly after I started it. I know the support for Mod apk is not intended(so this issue is not under bug label), but the Mod app removes ad completely, and can be a better choice for Joey's users.

### Patch

change-oauth-client-id

### Motivation

To provide more choices to users

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by vinraghav** [comment]
I use Joey for Reddit too. It's good. Idk what has been going through it. The dev has not been online in last 3 months approx. Why was it removed from the play store?

**Comment by oSumAtrIX** [comment]
You are not supposed to patch a patched app.

**Comment by SakuraSakuraSakuraChan** [comment]
> You are not supposed to patch a patched app.

That's sound reasonable, but idk why the patching for Boost Mod apk works fine

**Comment by oSumAtrIX** [comment]
Probably because the patch does not cause any issues when executed multiple times
