### ISSUE TITLE
feat: YouTube - spoof inline player rather than shorts 

### ISSUE THREAD

**Issue by Bluebotlabz** [ReVanced/revanced-patches#2795]
### Application

YouTube

### Issue

After YouTube began infinitely buffering ReVanced, the new spoof patch appears to spoof the player to be that of the YT Shorts one, which as a side-effect, stops seekbar previews from working

### Patch

I propose an alternative: instead of spoofing to YT shorts, instead, spoof to the inline player

### Motivation

The inline player NEVER receives ads, and has a fully functional seekbar with chapter images/storyboard

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Bluebotlabz** [comment]
![Screenshot_20230811-224233_YouTube](https://github.com/ReVanced/revanced-patches/assets/69104218/80e35d14-d7ca-4047-b981-5d49ad5cf276)

An image of the inline player in the official app that I'm talking about, it is visible in the home screen when you stop to view a video

**Comment by oSumAtrIX** [comment]
You can not spoof to the inline player the way currently is being spoofed, unless you know a way to.

**Comment by YT-Advanced** [comment]
Can not spoof inline player. When Youtube send video request with a paramter, it contains infomation about your video, so if we spoof inline player, it will break the video
