### ISSUE TITLE
feat: options to add little buttons on video player

### ISSUE THREAD

**Issue by BadaBingBR** [ReVanced/revanced-patches#2796]
### Feature description

![InShot_20240302_001700680_2](https://github.com/ReVanced/revanced-patches/assets/83316350/bf57c266-e30a-4a31-9176-2330d3e72cd3)
here's a mockup of what i mean

### Motivation

In revanced extended you could add or remove little buttons on the player like auto-repeat, video speed and such. i'd love to see this little feature on a future version

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
https://github.com/ReVanced/revanced-patches/issues/1620
