### ISSUE TITLE
feat: Unlock Picsart Gold

### ISSUE THREAD

**Issue by kevinr99089** [ReVanced/revanced-patches#2796]
### Application

Picsart (com.picsart.studio)

### Issue

Unlock Picsart Gold/Pro

### Patch

Unlock Premium/Gold

This would be to unlock Picsart Gold and all its features requiring payment for full use.

### Motivation

Picsart is popular, but most people who want to use it patched to get gold have to go through obscure sites. As ReVanced is safe, we can patch it ourselves in peace.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Closing according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#%EF%B8%8F-guidelines-for-requesting-or-contributing-patches). Thanks anyways.
