### ISSUE TITLE
Reddit Sync Crashes Constantly and When Downloading Media

### ISSUE THREAD

**Issue by LimitedEdiition** [ReVanced/revanced-patches#2797]
### Type

Error while patching

### Bug description

Not sure what was changed recently, but starting this week, reddit sync has begun to crash constantly. I even uninstalled the app completely, cleared cache and data, and repatched the app and it still crashes. Other 3rd party reddit apps such as Joey seem unaffected, so I am unsure as to what is causing this because everything was working fine a week ago with zero changes. I am running on Samsung OneUI 5.1. 

### Steps to reproduce

I can easily reproduce this by going to a favorited subreddit, trying to download anything. Before the video is finished downloading, Android will give an error saying the app has crashed. 

### Relevant log output

```shell
Not sure how to do this.
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by cyberboh** [comment]
The reason could be https://github.com/ReVanced/revanced-patches/issues/2591#issuecomment-1649578129

ReVanced team should remove all patches for any 3rd party reddit clients, because no reason to keeping dead apps.

**Comment by krashton1** [comment]
Managed to fix this by uninstalling patched sync. Updating revanced manager and re-patching the app.

Trying to patch the app without updating manager was causing the patch to fail. Not sure why, but Ive been using sync for 24 hours now again crash free.

**Comment by oSumAtrIX** [comment]
@cyberboh Patches for Reddit clients will not be removed just because the apps are not updated anymore.

**Comment by rktfier** [comment]
Having the same issue but instead of downloading media, Sync keeps crashing even in background repeatedly.

**Comment by oSumAtrIX** [comment]
Include crash logs in a new issue.

**Comment by rktfier** [comment]
How can i gather the crash logs?

**Comment by oSumAtrIX** [comment]
Using logcat.

**Comment by rktfier** [comment]
Via ADB?

**Comment by oSumAtrIX** [comment]
Via any measure that allows you to use logcat.
