### ISSUE TITLE
bug(YouTube - Hook Download Button): `Download this video` options in flyout menu not worked correctly

### ISSUE THREAD

**Issue by YT-Advanced** [ReVanced/revanced-patches#2798]
### Bug description

Currently, the download function of Revanced also being handled by the `Download this video` options in flyout menu. However, instead of getting the videoid in call function, this patch used the videoId from VideoInformation, which is an incorrect videoId

For better understanding, you can simply open You Tab, click the ⁝ of a video and click `Download this video`

### Solution

I have parsed the videoId from the `download_actions` method, you can check these commit:
https://github.com/YT-Advanced/ReX-patches/commit/af1f9d00548bda321f369467280f4fcf108fb675
https://github.com/YT-Advanced/ReX-integrations/commit/3693293f65bbbba0798aedf823f7195e2a797f6b

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Not sure what you mean but such a patch not exist

**Comment by YT-Advanced** [comment]
> Not sure what you mean but such a patch not exist

Ah, sorry about the unclean English.
Uhm to be easier, here is step to reproduce the bug:
- Turn on hook download button
- Open a random video
- Go back to Feed (but still keep the video playing)
- Click 3 dot button right the video to open flyout menu
- Click `Download this video`
Then download the video.

Behavior: It download the currently playing video, which is incorrect

**Comment by oSumAtrIX** [comment]
Again, we dont have such a patch.

**Comment by YT-Advanced** [comment]
I know, but for some unknown reason, the Download options from Flyout Menu also be handled by Hook Downlad button and download incorrect video. To fix it, you can check 2 commits above
