### ISSUE TITLE
feat: disable scrolling in shorts

### ISSUE THREAD

**Issue by MrVindur** [ReVanced/revanced-patches#2801]
### Application

YouTube

### Issue

Being able to click and watch a short but not being able to just scroll down for another.

### Patch

Add a patch that makes it impossible to scroll down in the shorts player after clicking on a short to watch another video.

### Motivation

Not getting stuck watching shorts for hours and just wasting your time. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
At this point, either disable shorts or learn to restrain yourself.

**Comment by MrVindur** [comment]
> At this point, either disable shorts or learn to restrain yourself.

I just randomly thought of this but okay

**Comment by MrVindur** [comment]
> At this point, either disable shorts or learn to restrain yourself.

I can't lmao

**Comment by MySurmise** [comment]
This would be a great feature, e.g. if I want to search a specific video that's only available in short format, but then not accidentally waste half an hour on the platform.
If the user should just "restrain itself" why have this short blocking feature altogether?
