### ISSUE TITLE
feat: YouTube Revanced - Patch to allow using yt-dlp inside of termux

### ISSUE THREAD

**Issue by james28909** [ReVanced/revanced-patches#2802]
### Application

YouTube Revanced

### Issue

Can't use any downloader except the built in one. 

### Patch

When the user clicks the download button on a video, it gets downloaded with yt-dlp inside termux env. 

### Motivation

A lot of people use yt-dlp. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
You need to implement the shared activity in an app and then redirect that to termux.

**Comment by james28909** [comment]
> You need to implement the shared activity in an app and then redirect that to termux.

As easy as it is for you to explain that, i must wonder why it hasn't been implemented in youtube revanced already. Why can the app not send to termux like the other built in options? Why must there be a separate app just to handle this?

**Comment by oSumAtrIX** [comment]
Why would it specifically do this exact thing? Every external downloader uses the share activity.

**Comment by james28909** [comment]
I got it working with ytdlp in termux. It was actually very easy. Termux has termux-url-opener and i was able to easily mitigate this issue. Thanks for leading me in the right direction

**Comment by BhaturaGuy** [comment]
@james28909 Can you provide the solution, if possible?
