### ISSUE TITLE
feat(Twitch): add third-party-emotes patch

### ISSUE THREAD

**Issue by girshcatt** [ReVanced/revanced-patches#2804]
### Application

Twitch

### Issue

We can't see and use third-party emotes in Twitch chat

### Patch

First we need new menu in settings with switches
Third-party emotes:
BTTV emotes (off/on)
FFZ emotes (off/on)
7TV emotes (off/on)
Emotes quality (low/medium/high)

Second what we need to see new emotes with new labels in chat emotes menu

### Motivation

Many channels nowadays support third party emotes like BTTV, FFZ, 7TV and android twitch mods like purpletv included this feature, i want to see this function as revanced patch

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by johnconner122** [comment]
Please add app name in request title like: `feat(app-name): Title`

**Comment by girshcatt** [comment]
i added

**Comment by oSumAtrIX** [comment]
#1318
