### ISSUE TITLE
RV Header issue (Patches 4.3.0)

### ISSUE THREAD

**Issue by nightznero** [ReVanced/revanced-patches#2805]
### Bug description

On Patches 4.2.0 was fine ReVanced logo as well as Bordless,since update Patches to version 4.3.0 Header patch have isdue with both options(RV + RV Bordless)
![Screenshot_20240302_210610_ReVanced Manager](https://github.com/ReVanced/revanced-patches/assets/61750641/eff2b6eb-7408-4921-85b7-1fe6c2104f8e)

### Solution

Changing header as it was right before update

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
https://github.com/ReVanced/revanced-patches/issues/2800
