### ISSUE TITLE
bug(YouTube): Watch history does not work even with latest patches 4.3.0

### ISSUE THREAD

**Issue by gp27** [ReVanced/revanced-patches#2806]
### Bug description

This is the same issue about the history of videos (expect shorts) not being recorded when client spoof is enabled.

The issue #2779 from the past few days already was closed after a bug fix was added (bcd8b48) and merged in the patches now released with version 4.3.0.

I applied the patches 4.3.0 on YouTube 19.04.37 but that did not fix the history issue.

Applied patches:
- Alternative thumbnails
- Always repeat
- Announcements
- Bypass URL redirects
- Change header
- Change start page
- Client spoof
- Comments
- Copy video URL
- Custom branding
- Custom player overlay opacity
- Disable auto captions
- Disable fullscreen ambient mode
- Disable player popup panels
- Disable precise seeking gesture
- Disable resuming Shorts on startup
- Disable rolling number animations
- Disable suggested video end screen
- Disable zoom haptics
- Enable debugging
- Enable slide to seek
- Enable tablet layout
- External downloads
- GmsCore support
- HDR auto brightness
- Hide 'Load more' button
- Hide Shorts components
- Hide ads
- Hide album cards
- Hide autoplay button
- Hide breaking news shelf

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Check the unpatched app.

**Comment by gp27** [comment]
Uninstalling and reinstalling the patched apk instead of updating it in place solved the issue.

Thanks for your help.

**Comment by Cico90** [comment]
Didn't work for me!
