### ISSUE TITLE
feat(history): Add a link to google activity before old history can be fetched

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [ReVanced/revanced-patches#2807]
### Feature description

Add a link to https://myactivity.google.com/product/youtube somewhere near history.

### Motivation

Currently new history is registered, but some previous histories are gone. Adding a link to https://myactivity.google.com/product/youtube can increase convenience to fetch old history.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
You can manually visit the link.

**Comment by SodaWithoutSparkles** [comment]
issue is that people arent good at remembering long links such as https://myactivity.google.com/product/youtube

**Comment by oSumAtrIX** [comment]
That is not a matter of ReVanced. You can Google search if it bothers you.

**Comment by Ushie** [comment]
It doesn't matter, the app isn't supposed to send you there, so what if 2 or 3 videos are missing? those videos are already irrelevant, it also has no place in the app to be put in
