### ISSUE TITLE
bug: (YouTube - spoof app signature) watch history is not saving

### ISSUE THREAD

**Issue by mbniol** [ReVanced/revanced-patches#2809]
### Bug description

Using Spoof app signature option stops watch history from saving.

YouTube v.19.04.37

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
#2469

**Comment by tozpeak** [comment]
> #2779

Can't reply there, sorry.
Is this bug still in work though? I did the 4.3.0 patch as well, but it haven't fixed the issue.
If the bug is fixed with a greater patch, it is not clear from the issue discussion.

**Comment by oSumAtrIX** [comment]
The solution section is present in the issue i linked
