### ISSUE TITLE
bug: disable-fullscreen-panels Patch stops working

### ISSUE THREAD

**Issue by TNTberry** [revanced/revanced-patches#281]
### Type

Error at runtime

### Bug description

After the installation of the app the "disable-fullscreen-panels" Patch works.
When I turn the Display off while being in the Revanced settings of YT then the App freezes when i unlock the phone again.
The App restarts itself but then the "disable-fullscreen-panels" Patch is no longer working.
To bring it back working i had to clear all App Data.

### Steps to reproduce

   1  Go into Revanced Settings
   2  Lock the Device
   3  wait 10 sek
   4  Unlock the Device

### Relevant log output

```shell
-
```

### Solution

Expected behavior:
YT should still show the old Full-screenlayout after locking the Device

EDIT:

Like in #294 I have now tested it with the the Homebutton too.  The FullScreenPanel Patch also stopped working.

**Comment by TNTberry** [comment]
The issue with the revanced settings seems to be fixed in the newer builds.(The app no longer crashes in the Revanced settings)
 but the fullscreen panels are still bugged when the app crashes.

**Bug description**
After a fresh installation of the app the "disable-fullscreen-panels" Patch works as intended.
The Patch stops working after the app has been killed for the first time.
The only way how i could bring it back working was to clear the app data.

**Steps to reproduce**
1 start revanced with fullscreen-panel patch
2 kill the app   (with force close in android settings)  
3 reopen revanced.  ->patch is no longer working

**System**
1
Samsung Galaxy S7
Linage OS 18  (Android 11)
Revanced app: non-root
2 
Galaxy Tab S2
Android 7 (StockRom)
Revanced app: non-root

**Comment by CnC-Robert** [comment]
I cannot reproduce, im also on an s7 with lineage 19.1

**Comment by TNTberry** [comment]
Tanks for your reply.
Since you weren't able to reproduce the bug I looked where the problem was and I found it.
The Problem was that since I made the first Post the Patches went to a newer Version of Youtube.
Even though I used the newest Version of Patches the YT apk staid the old one. After I changed the YT apk to the new Version, the Problem no longer occurred.
