### ISSUE TITLE
Add dearrow extension

### ISSUE THREAD

**Issue by Adarshakarki** [ReVanced/revanced-patches#2810]
### Application

It is for youtube. 

### Issue

The issue solves clickbaiting issues by replacing title and thumbnails. 

### Patch

The patch is dearrow which replaces clickbaity thumbnail and titles and created by sponsorblock developer. 
Link:https://dearrow.ajay.app/

### Motivation

Youtube is full of cringy clickbait thumbnails and titles. It will be easier for community to just get the video or tutorial they want instead of falling for clickbaits and wasting times. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Julius8900** [comment]
#1208
