### ISSUE TITLE
Custom icon selection when applying the patch to the APK

### ISSUE THREAD

**Issue by Hexaae** [ReVanced/revanced-patches#2812]
### Application

YouTube and the others...

### Issue

Talking about YouTube f.e., when patched from ReVanced Manager app you have only one option: "Custom Branding" which will replace original APK's launcher icon being patched, with default ReVanced Manager launcher icon. So basically you have only 2 choices: a) keep original APK icon, b) replace it with default ReVanced Manager icon

### Patch

Would be nice a feature to let you choose a custom icon for the APK being patched... Extending "Custom Branding" patch with an option to select a custom icon (from .png for example) would be nice.

### Motivation

Avoid using the same ReVanced Manager launcher icon for all APKs patched, hence make them easier to find in your smartphone launcher. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by johnconner122** [comment]
You can do it with cli.

**Comment by Hexaae** [comment]
I will investigate with ReVanced-CLI thanks, but a specific feature under "Custom Branding" would still be useful IMHO.

**Comment by xDARKxDEVILx** [comment]
I don't think they will implement it in flutter manager, wait for compose manager and it should be available there afaik

**Comment by Ushie** [comment]
@TheAabedKhan has completed the backend for Patch Options and is now working on the UI

**Comment by xDARKxDEVILx** [comment]
> @TheAabedKhan has completed the backend for Patch Options and is now working on the UI

In flutter manager?! Let's go
I take back what i said then lol

**Comment by Ushie** [comment]
Nevertheless, this issue can be closed as its in the correct repository, you can track https://github.com/ReVanced/revanced-manager/issues/1066 instead
