### ISSUE TITLE
bug: Autoplayed Videos from Feed in history.

### ISSUE THREAD

**Issue by fire17** [ReVanced/revanced-patches#2813]
### Bug description

Hi there :)
First of all thanks for fixing the no history bug :)
I knew it wouldn't take more than a few days. Very awesome

The only thing, now videos that start Auto playing in my feed (which I prefer not to disable)
Appear as watched videos in the history, and I have to manually remove each one of them.
I think this used to be an old bug but I think it returned

Please fix it and allowed to autoplay without adding the video to the history unless I intentionally click to open it.

Thanks a lot and all the best!

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
They don't appear unless you enabled spoofing the signature for feed videos.  Read the description of the setting

**Comment by fire17** [comment]
Hey @oSumAtrIX 

Please tell me where exactly this is, from what I found I do not have spoofing enabled

![Screenshot_20240303-123925_YouTube.jpg](https://github.com/ReVanced/revanced-patches/assets/9356048/1b9b415a-527b-482d-8845-b2230f45e535)

Or maybe I'm missing something...
Please advise

**Comment by oSumAtrIX** [comment]
This is not a support channel, move to our links at https://revanced.app
