### ISSUE TITLE
feat: Patches for Android TV Launcher

### ISSUE THREAD

**Issue by abskmj** [ReVanced/revanced-patches#2814]
### Feature description

This feature request is not related to any of the existing patches or apps. This is for a new app - Android TV Launcher https://play.google.com/store/apps/details?id=com.google.android.leanbacklauncher.

### Motivation

Recently, Google has started pushing ads and other sponsored content on the home screen of their Android TV Launcher app. The content sometimes are not even related to media. Imagine seeing an ad for new Audi car which covers half of your TV screen with audio which auto plays. There is no option in settings to disable these ads or sponsored posts.

Apart from ads and sponsored posts, other possible patches
- remove Shop, Discover, Live links on homesceen which mostly promote paid movies from play store
- remove sticky channels from home screen screen which promotes to buy movies and tv shows from playstore 
- show mobiles apps that are sideloaded
- replace all youtube features with smart tube which allows ad free youtube experience on Android TV https://github.com/yuliskov/smarttube

Related news
- https://9to5google.com/2023/03/11/google-tv-android-ads-cars/
- https://www.androidpolice.com/google-tv-ads-worse-promoting-cars/
- https://www.reddit.com/r/AndroidTV/comments/157k29q/remove_free_live_tv_from_home_sceen/

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
https://github.com/ReVanced/revanced-patches/issues/2748

**Comment by NWalker1208** [comment]
> #2748

I don't think this is referring to the same app. This issue is talking about the launcher for Google TV, whereas the other is talking about the YouTube app for Google TV.

**Comment by oSumAtrIX** [comment]
The posts OP linked as his motivation was regarding YT TV

**Comment by abskmj** [comment]
To clarify, this request is not for the youtube app on Android TV. I took off the text from the issue which might be confusing.

This to add new patches for the default launcher app on Android TV.

**Comment by oSumAtrIX** [comment]
Please attach an image

**Comment by abskmj** [comment]
I don't have one from my device, but below is a screenshot from reddit.

![image](https://github.com/ReVanced/revanced-patches/assets/29548356/f5e83420-595d-4745-9813-844f7c065bcf)

**Comment by oSumAtrIX** [comment]
Im not sure what to make out of that. The apk is less than an MB big and has no related classes to a launcher.

**Comment by abskmj** [comment]
I added a wrong link to the apk. I have corrected it now. Also, take a look at the reviews on the Playstore. Most of them are about the ads.  

APK: https://www.apkmirror.com/apk/google-inc/android-tv-home-android-tv/
Playstore: https://play.google.com/store/apps/details?id=com.google.android.tvlauncher

**Comment by abskmj** [comment]
Could you reopen this issue, since it is not a duplicate?
