### ISSUE TITLE
bug: (Youtube - Music) Recent play not showing in mini player window.

### ISSUE THREAD

**Issue by Raj3019** [ReVanced/revanced-patches#2815]
### Bug description

Currently using youtube music 6.41.58 latest version on android 13 and when i open app it doesn't show the last played music in app small player and it happens every time. When ever i play a music and pause it, close the app and then again open the app it's says below in player "Nothing is playing". I am also attaching a screenshot for better understanding of bug.

![Youtube music error](https://github.com/ReVanced/revanced-patches/assets/86660451/6da0eb74-08e5-4b55-b5a7-fa8bd0aa2523)

### Additional context

Even i had try to patch the old youtube music apk version but the issue still remains the same.

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Default behavior of YouTube Music

**Comment by Raj3019** [comment]
> Default behavior of YouTube Music

So won't able to fix ?

**Comment by blue220895** [comment]
Hi, I have the same problem. Did you manage to solve the issue?
