### ISSUE TITLE
Bad ReVanced Member Behavior on Github

### ISSUE THREAD

**Issue by fire17** [ReVanced/revanced-patches#2816]
### Bug description

I had a problem with ReVanced behavior
This is clearly a bug on your end.
Appearebtly if spoofing was on at any point in time it results in bad UI behavior, even after updating and even deletion 

I opened an issue, and while writing a follow up comment **with useful information to others**
I got locked out of my own issue
![Screenshot_20240303-125046_GitHub](https://github.com/ReVanced/revanced-patches/assets/9356048/af16c470-7fb7-4b81-b56f-db1aaa3f74d7)

You have no idea how frustrating this is @oSumAtrIX 
I was about to add a comment which could have helped someone like me, not only you prematurely close my issue, but you lock me out??
Please unlock so I can finished adding information there #2813 

@oSumAtrIX this is GitHub buddy, people here ask questions so it will be open and archived for anyone's benefit, not only were your answers the most minimalistic in terms of helpfulness, but effectively told me to fuck off and to go somewhere else with my problem. Not cool, please don't treat me and others this way.

Hope to finish that issue, please unlock it,
Thanks and all the best

**Edit - ** just because i can't guarantee that it will reopen
I'll post the rest here, at least this will be seen in the original issue as a reference. My attempted follow up was...

Just to see i thought maybe enable & disable spoofing 
And I get this message
![Screenshot_20240303-124454_YouTube.jpg](https://github.com/ReVanced/revanced-patches/assets/9356048/f0e50bc7-1d38-443a-a625-39d4ec7d0fd5) 

So maybe I had spoofing on at one point in the past and didn't clear the data.... Though I've updated and even deleted & reinstalled a bunch of times since, and never had this issue

Is there a way to backup all other* ReVanced settings so I don't have to go and change all the setting later to the way I like? It will be a pain to do manually 

Thanks
(Wtf?! Can't post to my own issue???!!!)

### Solution

Don't lock people out of their own issues and don't tell people to fuck off

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
No, this is not a support channel. It is a place of development. I have told you where to go. Now stop spamming this place.
