### ISSUE TITLE
feat: Facebook Messenger to show link previews in EU

### ISSUE THREAD

**Issue by r4ian** [ReVanced/revanced-patches#2816]
### Application

Facebook Messenger (com.facebook.orca)

### Issue

Facebook Messenger has disabled link previews for EU citizens, and no preview appears when a link is pasted in the chat at all.

https://mashable.com/article/facebook-link-previews-europe-privacy

### Patch

It should enable the link preview feature as it does worldwide except in EU. 

### Motivation

This is a great feature disabled and would make the app easier to use for everyone. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by vairag22** [comment]
They disabled it because its anti-privacy and violation of EU privacy laws. To generate link previews Facebook downloads entire contents of the shared link, this is clearly written in the article you shared. Besides this functionality is most probably disabled from the server-side.

**Comment by vairag22** [comment]
They disabled it because it is anti-privacy and violation of EU privacy laws. To generate link previews Facebook downloads entire contents of the shared link. This is clearly written in the article you shared. Besides this feature is most probably disabled from the server-side.

**Comment by r4ian** [comment]
> They disabled it because it is anti-privacy and violation of EU privacy laws. To generate link previews Facebook downloads entire contents of the shared link. This is clearly written in the article you shared. Besides this feature is most probably disabled from the server-side.

I don't mind if they download the sites I'm going to download (open) anyway and most likely has facebook tracking them either way. So if it is possible on client side to override, let the people decide.

**Comment by vairag22** [comment]
[Link preview is generated on the server-side.](https://www.mysk.blog/2020/10/25/link-previews/)

**Comment by r4ian** [comment]
> [Link preview is generated on the server-side.](https://www.mysk.blog/2020/10/25/link-previews/)

are you sure that it's not just a client side flag telling the server not to generate the preview?
