### ISSUE TITLE
Organize "patches.json" in a better format

### ISSUE THREAD

**Issue by vairag22** [ReVanced/revanced-patches#2817]
### Type

Other

### Issue description

While I was writing a script for filtering patches I noticed that [patches.json](https://raw.githubusercontent.com/ReVanced/revanced-patches/main/patches.json) is organized poorly. Patches are organized in a patch-wise manner.

This is the current format:
`[
	{
		"name": "string",
		"description": "string",
		"version": "string",
		"excluded": true,
		"dependencies": ["string"],
		"options": [
			{
				"key": "string",
				"title": "string",
				"description": "string",
				"required": true,
				"choices": ["string"]
			}
		],
		"compatiblePackages": [
			{
				"name": "string",
				"versions": ["string"]
			}
		]
	}
]`

### Solution

In my opinion, patches should be organized in an app-wise manner. This format would be better:
`{
	"supportedApp": [
		{
			"name": "string",
			"description": "string",
			"version": "string",
			"supportedAppVersions": ["string"],
			"excluded": true,
			"dependencies": ["string"],
			"options": {
				"key": "string",
				"title": "string",
				"description": "string",
				"required": true,
				"choices": ["string"]
			}
		}
	]
}`

Non-app specific patches could be given a common package name such as `patch.revanced.generic`. 

This would be user-friendly and also simplify filtering patches for both ReVanced Patcher and end-users. Patches for an app could be easily searched by: `$ cat patches.json | jq .supportedApp`

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

I apologize if I've filed this issue in the wrong template or repo.

**Comment by alexandreteles** [comment]
The retooling this would require is non-trivial. I suppose a conversation about a new format can be started once the `patches.json` file is exclusively an API representation.

**Comment by Ushie** [comment]
What would you do about duplicating the patch objects under the instance that multiple packages are supported?

**Comment by oSumAtrIX** [comment]
The JSON file is going to be deprecated once an alternative exists. It's bad practice.

**Comment by vairag22** [comment]
> The JSON file is going to be deprecated once an alternative exists. It's bad practice.

Why is it bad practice? Some documentation on patches is required, I take `patches.json` as that, documentation.

**Comment by oSumAtrIX** [comment]
It is bad practice because the intended way to read the patches is to use `PatchBundle`. The JSON file can get out of sync to the patches file you are using, it can be formatted differently, it restricts you having to read from a file, requires the patches to specify the format in how other peograms consume and read the file, when an existing method exists to read them and thus it is considered bad practice. The documentation is staged in the `docs` branch.

**Comment by vairag22** [comment]
Ok, thanks for explaining. 

You mentioned in the previous comment that JSON file is going to be deprecated. My use case is that I need to extract names of patches available for an app so I could convert them to patch ids and pass them with -i flag in revanced-cli. I use a script to do this, which gets patches from api.revanced.com but the response is basically `{"patches": [data_from_patches.json]}`. My problem is with how the data is structured, not with existence of the JSON file.

**Comment by oSumAtrIX** [comment]
Data structure concerns of the API belong in the API repository as the API is responsible for transforming and supplying this api.

**Comment by vairag22** [comment]
Okay. I'll discuss the issue there.

Thanks.
