### ISSUE TITLE
Material you 

### ISSUE THREAD

**Issue by kittenvr** [ReVanced/revanced-patches#2818]
### Application

Youtube

### Issue

This would look cool

### Patch

Change the theme of youtube to be material you

### Motivation

https://youtu.be/KgoW6R5HqSM
https://www.figma.com/community/file/1069197083803703706/YouTube-Redeisgn-with-Material-You

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Already exists using the "theme" patch.

**Comment by kittenvr** [comment]
> Already exists using the "theme" patch.

@oSumAtrIX can you show screenshot

**Comment by oSumAtrIX** [comment]
You can find steps to apply Material You colors here: #2798 using ReVanced CLI for now

**Comment by kittenvr** [comment]
> You can find steps to apply Material You colors here: #2798 using ReVanced CLI for now

i dont see it

**Comment by oSumAtrIX** [comment]
The entire YouTube app will not be rewritten to support M3 design language.

**Comment by TeaEndsAcronyms** [comment]
> The entire YouTube app will not be rewritten to support M3 design language.

I know, but I'm just telling you that's what they were talking about!

**Comment by oSumAtrIX** [comment]
I know, which is why I responded.
