### ISSUE TITLE
bug(YouTube - Spoof App Signature): Playback issues appears when opening a YouTube link with timestamp

### ISSUE THREAD

**Issue by YT-Advanced** [ReVanced/revanced-patches#2819]
#### Step to reproduce:
1. Patch with the latest version of Revanced, then make sure that Spoof Signature is turned on
2. Open a youtube link with timestamp parameter, and getting the playback issues

#### Video link for testing:
- https://youtu.be/nlarIgSvV_U?t=10
- https://www.youtube.com/watch?v=nlarIgSvV_U&t=1s
- vnd.youtube://nlarIgSvV_U?start=10

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Is the hook being called?

**Comment by YT-Advanced** [comment]
> Is the hook being called?

Which hook ? I checked today and only spoof player parameter is called, so I think my debug is incorrect 🤔

**Comment by oSumAtrIX** [comment]
Not sure what you mean, but I am referring to the hook that replaces the player parameter. Please check if it is called

**Comment by YT-Advanced** [comment]
> Not sure what you mean, but I am referring to the hook that replaces the player parameter. Please check if it is called

Ah it is called normally

**Comment by oSumAtrIX** [comment]
Then what is the screenshot supposed to show? Please send comprehensive messages from now on. You have been sending partial information in the past that are not useful on their own and require multiple questions to clarify,  just like now.

**Comment by YT-Advanced** [comment]
> Then what is the screenshot supposed to show? Please send comprehensive messages from now on. You have been sending partial information in the past that are not useful on their own and require multiple questions to clarify,  just like now.

![Screenshot_20240303-213540_Logcat Reader.jpg](https://github.com/ReVanced/revanced-patches/assets/70064328/cbffb002-36c5-4094-b202-36f83a77e3d5)

**Comment by YT-Advanced** [comment]
Also you can easily reproduce this bug by follow the guide above, aren't you ?

**Comment by oSumAtrIX** [comment]
Yes, what's the fingerprint for?

**Comment by YT-Advanced** [comment]
> Yes, what's the fingerprint for?

Ah I thought that you are referring the fingerprint that are called when open a video link

**Comment by oSumAtrIX** [comment]
The hook is being called so I am not sure what makes the video not play. The query parameter is a client side thing and has no role in the /player request.

**Comment by YT-Advanced** [comment]
> The hook is being called so I am not sure what makes the video not play. The query parameter is a client side thing and has no role in the /player request. 

After some hours of debugging, I found out that your recent changes to fix history caused playback issues.

**Comment by YT-Advanced** [comment]
@oSumAtrIX I found out that the player parameter isn't forced due to this line
<img width="207" alt="image" src="https://github.com/ReVanced/revanced-patches/assets/70064328/d00d0353-a4e6-483d-af4e-336f5a367f0a">
To solve it, just use `startsWith` or use this parameter for Clips `kAIBggM`

**Comment by TobySkarting** [comment]
Confirmed it works. Thank you.
