### ISSUE TITLE
bug: tapping on seek bar does not work

### ISSUE THREAD

**Issue by GHD95** [revanced/revanced-patches#282]
### Type

Error at runtime

### Bug description

Tapping on see bar in the RV setting does not work.

### Steps to reproduce

1 Revanced setting
2 Misc
3 Tapping on seek bar

### Relevant log output

```shell
_
```

### Solution

_

### Additional context

Yt Revanced

**Comment by oSumAtrIX** [comment]
Please explain your issue.

**Comment by GHD95** [comment]
The function described above in the Revanced settings does not work

**Comment by masterflitzer** [comment]
yes i wondered what does this patch even do because it wasn't working at all

**Comment by TheJeterLP** [comment]
> yes i wondered what does this patch even do because it wasn't working at all

Of course it's working. It's enabling to tap on the seekbar. Compare with stock YouTube.

**Comment by GHD95** [comment]
watch the video and check again
https://youtu.be/7i_zmhzg2FQ

**Comment by oSumAtrIX** [comment]
Restart the app. All settings are not being applied yet due to a bug.

**Comment by GHD95** [comment]
i tried and it doesn't work

**Comment by oSumAtrIX** [comment]
Please record the issue.

**Comment by masterflitzer** [comment]
for me i cannot tap on the bar, just swipe (like in stock yt), no matter what option i choose

**Comment by oSumAtrIX** [comment]
Please record enabling the setting, restarting the app  and then tapping on the seekbar.

**Comment by oSumAtrIX** [comment]
Did you include the patch while patching the app?

**Comment by masterflitzer** [comment]
i'm pretty sure but i experimented a bit with the patches so i will patch again to make sure

**Comment by masterflitzer** [comment]
i've repatched the app and it turns out it works (so i forgot to include the patch before), thanks anyway and sorry for wasting your time

would be good tho to only show the options that are patched in the revanced settings

**Comment by oSumAtrIX** [comment]
No problem.

> would be good tho to only show the options that are patched in the revanced settings

 This is already working in the `settings-framework` development branch and will soon be merged to upstream.

**Comment by masterflitzer** [comment]
nice i really love how revanced evolves into something even better than vanced

**Comment by TheJeterLP** [comment]
@oSumAtrIX issue should be closed

**Comment by oSumAtrIX** [comment]
This issue will auto close.

**Comment by GHD95** [comment]
Please watch the video link, I'm busy
