### ISSUE TITLE
feat: Spoof app version, add manual custom setting

### ISSUE THREAD

**Issue by pep0w** [ReVanced/revanced-patches#2820]
### Feature description

Add a setting to manually set the spoof app version target

### Motivation

It makes it far easier to change to a specific target (in case of some subtle differences between the preincluded versions and the custom target)
That way, we don't have to wait for it to be added, and then also repatch which won't work for some older versions because revanced is no longer supporting those for no apparent reason.
We do not want to update unless absolutely necessary, this way we can use the version that works best for us.

revanced extended already has this setting, but please don't say to just use that instead. We need both apps so it's much easier to use multiple accounts amongst other things. And if you think that doesn't make sense, just know this, it doesn't make sense to not include this feature request, which surely a lot of people will appreciate having.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
This has already been discussed with you https://github.com/ReVanced/revanced-patches/issues/2808#issuecomment-1975170668.
