### ISSUE TITLE
feat: custom spoof signature

### ISSUE THREAD

**Issue by pep0w** [ReVanced/revanced-patches#2821]
### Feature description

Add a setting to manually set the spoof signature

### Motivation

It makes it far easier to change the signature. Especially when the signature in use currently stops working properly, we don't have to wait for the patches to be updated, and then also repatch which won't work for some older versions because revanced is no longer supporting those for no apparent reason.
We do not want to update unless absolutely necessary, this way we can use the version that works best for us.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
This isn't a dedicated feature. In the future, either the same parameter works, or no parameter works.
