### ISSUE TITLE
feat: Hermit

### ISSUE THREAD

**Issue by sliceanddice9** [ReVanced/revanced-patches#2822]
### Application

Hermit — Lite Apps Browser/Hermit Premium — Unlocker.

### Issue

N/A

### Patch

A patch or set of patches to get direct access to **Hermit Premium — Unlocker.**

### Motivation

So that everybody can enjoy the additional perks of **Hermit Premium — Unlocker** which at the moment is behind a paywall. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Chrome can do "lite apps" natively.
