### ISSUE TITLE
feat: Ad-blocking patch for YouTube for Android TV

### ISSUE THREAD

**Issue by NWalker1208** [ReVanced/revanced-patches#2822]
### Feature description

I would like there to be an ad-blocking patch for the [YouTube for Android TV](https://play.google.com/store/apps/details?id=com.google.android.youtube.tv&hl=en_US&gl=US) app.

### Motivation

I would like to be able to block ads when watching YouTube on my Google TV/Android TV device. Apps such as SmartTube exist, but don't offer the same user experience as the official YouTube app. For example, it does not allow me to watch purchased movies, while the ReVanced app for Android does. I think offering patches for the Android TV version of YouTube could also open up the opportunity to improve casting support in the mobile version of ReVanced, as a patch could later be introduced to make casting work as expected.

### Acknowledgements

- [ ] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
https://github.com/ReVanced/revanced-patches/issues/2814

**Comment by NWalker1208** [comment]
#2748 is probably the more appropriate issue to reference. #2814 is not about the YouTube app.

**Comment by Julmik647** [comment]
The only thing that you can do at the time is to use YouTube for purcharsed movies and SmartTube for regular videos. [Purcharsed movies don't have ads](https://www.reddit.com/r/youtube/comments/nu0h1r/do_paid_for_movies_have_ads/?rdt=56479), so it shouldn't be a problem.

Info for developers:  beacuse YouTube TV is web app, you can make WebView app that uses [this userscripts](https://github.com/reisxd/TizenTube/tree/main/mods). It's possible and [Better Xcloud app](https://better-xcloud.github.io/android/) is an example.
