### ISSUE TITLE
bug: Twitter/X patch Hide recommended users dont work

### ISSUE THREAD

**Issue by BlueStarBRS** [ReVanced/revanced-patches#2825]
### Bug description

im still seeing random people that i dont wanna see
![image](https://github.com/ReVanced/revanced-patches/assets/25110093/ac572a2d-0ccf-4b66-976c-1dc88f63add4)

### Additional context

my twitter version is: 10.30.0-release.0

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Your screenshot blocks the feed. Post a proper picture of what you mean

**Comment by kazimmt** [comment]
> Your screenshot blocks the feed. Post a proper picture of what you mean

Maybe he was referring to this: https://github.com/ReVanced/revanced-patches/issues/521
