### ISSUE TITLE
feat(Youtube): add patch options to microg-support patch

### ISSUE THREAD

**Issue by girshcatt** [ReVanced/revanced-patches#2825]
### Application

Youtube

### Issue

This will give the opportunity to use microg with other package name or to use gmscore without gmscore branch

### Patch

Add patch options to microg-support patch to change microg package name

### Motivation

To use different microgs at one device or just use microg with other package name

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
This is not possible because many references are changed in the app to call the respective packages classes.
