### ISSUE TITLE
feat(SeriesGuide): Unlock X Pass / Pro

### ISSUE THREAD

**Issue by xPOGMANx** [ReVanced/revanced-patches#2826]
### Feature description

This is a request for a new patch for the currently unsupported app SeriesGuide (com.battlelancer.seriesguide)

SeriesGuide X Pass enable some additionnal features including notifications, widget, etc.

The app is open-ish source and the code that checks for X Pass is quite straightforward : https://github.com/UweTrottmann/SeriesGuide/blob/8839a18b9a444188feab15e7cd7cf5d2473a72ce/app/src/main/java/com/battlelancer/seriesguide/util/PackageTools.kt#L56-L89

I tried a couple things (creating a dummy com.battlelancer.seriesguide.x, building my own SeriesGuide with some modifications of the code) to no success because the open source does not include everything actually (some API keys are missing for instance).

So I guess a patch would be the "easiest" solution.

### Motivation

I think this should be implemented because X Pass is way too expensive for what it is ($20+).
I would enable multiple features that are qui useful for this app.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
As per contribution guidelines pro unlocking patches won't be implemented. Feel free to use the patches template repo to create your own though
