### ISSUE TITLE
feat: YouTube Overlay Buttons

### ISSUE THREAD

**Issue by Raihan-Shovo** [ReVanced/revanced-patches#2831]
### Feature description

Let me be honest, there is no overlay buttons on YouTube Revanced, and that suckes. the YouTube Revanced Extended has settings called overlay buttons which have a lot of functions and those are "show always repeat button" "show copy timestamp URL button" "Show copy video URL button" "Show external download button" "Show speed dialog button". but the revanced only has "show copy timestamp URL button" "Show copy video URL button" "Show external download button" and those are not even that great. extended overlay buttons look more pleasing and i looked into the .jar file the extended has a folder called overlaybuttons and inside it contains .png files of the icons. i don't know why the revanced doesn't have this function but i highly advice the team to add this feature to revanced youtube. this is the only function missing.

### Motivation

this overlay function makes it easier to change speed, download video from external software, makes it easier to copy URL. I think this function deserves to be added don't you think?

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by KobeW50** [comment]
For playback speed button, it is related to https://github.com/ReVanced/revanced-patches/issues/1620

For an always repeat button, it is related to https://github.com/ReVanced/revanced-patches/issues/1160 (I think)

**Comment by Raihan-Shovo** [comment]
> For playback speed button, it is related to #1620
> 
> For an always repeat button, it is related to #1160 (I think)
> 
> It is worth looking into the implementation of the always-repeat button in the ReVanced Extended fork. You tap the button to shuffle between auto-repeat and don't repeat, and you hold the button to enable auto-repeat but to pause at the end of videos.
> 
> ![SmartSelect_20240303_222002_YT Extended.jpg](https://private-user-images.githubusercontent.com/84587632/309618311-9c4f2d91-610c-481b-9c9d-4f0ad954cea0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1MjI4NzIsIm5iZiI6MTcwOTUyMjU3MiwicGF0aCI6Ii84NDU4NzYzMi8zMDk2MTgzMTEtOWM0ZjJkOTEtNjEwYy00ODFiLTljOWQtNGYwYWQ5NTRjZWEwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDAzMjI1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhYWM1YzhmYTQ1MWQ4YmRmZmM3MDQ1OWU4YzQ2NGJkMWUyZmFlNDcxODlkNWU5ZjEwYWI3ZGEzMWU4OWQ4ZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Qqfb7UY5VUnJGF3K35gGJ6suyH04_xA76ChdEL0bbtw)



> For playback speed button, it is related to #1620
> 
> For an always repeat button, it is related to #1160 (I think)
> 
> It is worth looking into the implementation of the always-repeat button in the ReVanced Extended fork. You tap the button to shuffle between auto-repeat and don't repeat, and you hold the button to enable auto-repeat but to pause at the end of videos.
> 
> ![SmartSelect_20240303_222002_YT Extended.jpg](https://private-user-images.githubusercontent.com/84587632/309618311-9c4f2d91-610c-481b-9c9d-4f0ad954cea0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1MjI4NzIsIm5iZiI6MTcwOTUyMjU3MiwicGF0aCI6Ii84NDU4NzYzMi8zMDk2MTgzMTEtOWM0ZjJkOTEtNjEwYy00ODFiLTljOWQtNGYwYWQ5NTRjZWEwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDAzMjI1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhYWM1YzhmYTQ1MWQ4YmRmZmM3MDQ1OWU4YzQ2NGJkMWUyZmFlNDcxODlkNWU5ZjEwYWI3ZGEzMWU4OWQ4ZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Qqfb7UY5VUnJGF3K35gGJ6suyH04_xA76ChdEL0bbtw)

Well kinda like that and also not 
![Screenshot_2024_0304_092715](https://github.com/ReVanced/revanced-patches/assets/142422864/f04bdddd-6324-42a8-8a84-904e3eb98eb8)
Look at the image, it has a specific section called Overlay Buttons and inside it look like this..
![Screenshot_2024_0304_092731](https://github.com/ReVanced/revanced-patches/assets/142422864/c527196d-f9d8-46a0-a4d7-dac8f4993baa)
And the revanced has 3 of them but not in a specific place.

**Comment by oSumAtrIX** [comment]
Please open two proper issues for the speed and repeat buttons instead of a paragraph of things that already mostly exist, if that issue doesn't exist yet
