### ISSUE TITLE
bug (youtube/hide mixes) Change setting to be shown by default

### ISSUE THREAD

**Issue by KobeW50** [ReVanced/revanced-patches#2835]
### Type

Error at runtime

### Bug description

Currently mixes are hidden by default when you include the patch. (I think it is the Hide Layout Components patch, but I haven't tested)

This is an issue because there are many users who use mix playlists. I usually see 1-3 posts per day on r/revancedapp regarding this.

### Steps to reproduce

Include the Hide Layout Components patch on a fresh installcand mixes will be hidden by default.

### Relevant log output

```shell
NA
```

### Solution

Change the default so that mixes are shown.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Most people likely want the playlists hidden, regardless of the minority (1-3 people per day on the sub).

**Comment by KobeW50** [comment]
> Most people likely want the playlists hidden, regardless of the minority (1-3 people per day on the sub).

It's about whether the majority of people want it hidden by default. I agree that most people likely want it hidden.

Take what you want from this poll. But ngl, earlier the first option was winning by approximately 25% but now it balanced back put.

![SmartSelect_20230817_222342_Reddit.jpg](https://github.com/ReVanced/revanced-patches/assets/84587632/7fcdc17e-589e-4a78-905e-85326a0c4222)

**Comment by oSumAtrIX** [comment]
Why did you delete the post though?

**Comment by KobeW50** [comment]
> Why did you delete the post though?

When i made the post i intended to delete it after a few hours to prevent clutter. It was just to get a basic idea of what people wanted. I deleted it when i went to bed
