### ISSUE TITLE
[YouTube] Bluetooth audio delay option

### ISSUE THREAD

**Issue by nadiration** [ReVanced/revanced-patches#2835]
### Feature description

This  feature  allows manually adjusting the audio delay when connected to Bluetooth.

### Motivation

When watching YouTube videos with Bluetooth headsets the audio is out of sync, depending on your bluetooth device the delay can sometimes be horrible.
The use case is obvious: to sync up the audio with the video.
This feature is important because in some videos it's critical for the audio to be in sync with the video.

NB: I know some [limited] phones have a native option to do this but most phones don't.

Thank you for your attention.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Isnt this an Android feature?

**Comment by oSumAtrIX** [comment]
I'm closing regardless as there's apps which can intercept the audio and add delay
