### ISSUE TITLE
feat(Tumblr): Fixes for things that the official tumblr team has broken or done poorly.

### ISSUE THREAD

**Issue by Thetheninjagummybear** [ReVanced/revanced-patches#2840]
### Application

[Tumblr](https://play.google.com/store/apps/details?id=com.tumblr&pcampaignid=web_share)

### Issue

Recent updates have made the user interface harder to use and less visually appealing. Many old navigation features have been removed or changed, causing confusion and breaking features. Nice design elements, like a blog's theme being visible in direct messages, have been inexplicably removed in favor of blander design. Ads are plentiful and annoying. There's a new feature, tumblr live, that can't be opted out of permanently. You can only snooze it for 7 days at a time. Most users do not want this feature, as it collects massive amounts of data from people who stream and watch the streams, and is flooded with bots.

### Patch

* Removal of ads, or the ability to collapse them.
* Restoration of old navigation features. Make it possible again to tap on someone's reblog and be brought to that instance of the post on their blog. Allow double-tapping to zoom in on an image, rather than double tapping to like. 
* Restoration of old layouts and design features. Put the tags button back where it used to be. Put blog themes back in the direct message window. 
* Removal of tumblr live/permanent snoozing. Hide all traces of this feature permanently on demand. 

### Motivation

Tumblr is alienating its user base and pushing people off of the site in search of profit. They're openly ignoring user feedback and making some terrible decisions. 

There are currently no good options for an alternative Tumblr client on mobile. The only way to use tumblr without these terrible new features is on a desktop browser with extensions. Mobile users should get a good experience, too.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by pixiekat** [comment]
A patch that incorporates Xkit Rewritten into the official app would be fantastic.

**Comment by oSumAtrIX** [comment]
Open issues for every of the requests.
