### ISSUE TITLE
feat: Request for a suitable patch for YouTube compatible with lower versions of Android

### ISSUE THREAD

**Issue by mahan3220** [ReVanced/revanced-patches#2841]
### Application

youtube 17.34.35

### Issue

I tried to patch YouTube version 17.34.35 (which is suitable for Android +6) with Revanced CLI, but unfortunately it didn't work , it was thrown out of the program, and even the signature of the program did not change and it was annoying to install, is this possible To the patches, add  patches for YouTube suitable for Android 6 and 7?

### Patch

Adding available options (in the version suitable for Android +8) such as / removing ads / playing in the background and ... for suitable versions of Android +6

### Motivation

Most of the Google apps are common from Android 8 to 12, but unfortunately Android 6 and 7 are exceptions

Doing this is definitely difficult and there are few users who have Android less than 10, but there are still those who use these versions.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Old versions are legacy and won't be supported. Update your system
