### ISSUE TITLE
feat(twitch): bump patches compatibility

### ISSUE THREAD

**Issue by illmatic73** [ReVanced/revanced-patches#2842]
### Application

Twitch

### Issue

Can we get Revanced patches that work with later builds of Twitch? The latest build as of right now is 15.8.0 and Twitch displays a nagging update pop-up. There currently doesn't appear to be any issue right now on the supported build of 15.4.1 with patches.

![SmartSelect_20230818_181755_Google Play Store](https://github.com/ReVanced/revanced-patches/assets/29491625/74a38fe2-fd61-49ea-ac3f-9cd2b05c9e26)

### Patch

Bump patches compatibility

### Motivation

There might be compatibility issues as new updates are relased as the build we are capped at may end being unsupported in the future.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by NewbieH4x** [comment]
Patching v15.8.0 works just fine currently.

**Comment by illmatic73** [comment]
@NewbieH4x thanks for the confirmation. I enabled experimental patches support and was able patch 15.8.0 via the manager.
