### ISSUE TITLE
bug(Youtube): Autoplay doesn't working properly

### ISSUE THREAD

**Issue by NekoZ410** [ReVanced/revanced-patches#2843]
### Bug description

When the video end, it doesn't play the next video though Autoplay option was enabled
It happen in both full screen and non-full screen mode

https://github.com/ReVanced/revanced-patches/assets/87725168/12b6a263-9525-4c0c-8b97-05604410872f

### Solution

If I minimize the player, the autoplay work as normal

https://github.com/ReVanced/revanced-patches/assets/87725168/2a912899-6953-4058-ba39-f2b276a43213

### Additional context

This bug appear on latest patches (v4.3.0)
I tried remove non-default patches, use others raw apk versions, fresh install but nothing change
Videos attached above are reproducing steps after a fresh install and used default patches

### Acknowledgements

- [ ] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
https://github.com/ReVanced/revanced-patches/issues/120
