### ISSUE TITLE
[Patch] Unlock Capcut pro.

### ISSUE THREAD

**Issue by TeaEndsAcronyms** [ReVanced/revanced-patches#2845]
### Application

[Capcut](https://play.google.com/store/apps/details?id=com.lemon.lvoverseas)

### Issue

Many effects and features are locked behind a paywall. (capcut pro) this patch would solve that and unlock all features.

### Patch

A patch to unlock Capcut pro.

### Motivation

Capcut is a good video editor. But some features that could make an edit are paywalled. This patch would unlock everything and make an edit better!

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [ ] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Theres many good video editors. Insufficient motivation.
