### ISSUE TITLE
bug: (Twitter/X) The reply menu page is blank and cannot select the reply object.

### ISSUE THREAD

**Issue by fxxgvvcc** [ReVanced/revanced-patches#2848]
### Bug description

X.apk patched with ReVanced Patches, appear cannot select the reply object in the reply menu. The reply menu page is blank and cannot select the reply object.

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
https://github.com/ReVanced/revanced-patches/issues/353
