### ISSUE TITLE
feat(spotify): add sleep timer end of queue option

### ISSUE THREAD

**Issue by D3SOX** [ReVanced/revanced-patches#2852]
### Application

Spotify

### Issue

There's no option in the app to end the sleep timer after the queue has finished playing

![image](https://github.com/ReVanced/revanced-patches/assets/24937357/a7d36869-5d8c-4e29-bb8b-b4d81b9de464)

### Patch

The sleep timer menu should have an option like "End of queue". I'm not entirely sure how feasible it is to implement this because I could imagine it being kinda complex.

### Motivation

When you want to listen to some music before going to sleep, you are forced to use one of these options.
But sometimes I know what I wanna listen to, queue these songs up, and then I'll have to guess which option is best instead of having this as an option.

I guess something like this is not that important for most people (and more of a "me problem"), so see this request as really low priority.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by 4dvyte** [comment]
Sleep timer was a part of the A/B testing feature, it is now available to everyone using the latest version of Spotify.

**Comment by D3SOX** [comment]
You have misread my request. It was not to implemented a sleep timer but add an option to end it at when the current queue ends

**Comment by 4dvyte** [comment]
> pp to end the sleep timer after the queue has finished playing



> You have misread my request. It was not to implement a sleep timer but to add an option to end it at when the current queue ends. Please reopen

there is already an option on spotify for that, it's called "Autoplay similar content", disable that. It won't play anymore songs when the queue is over.
