### ISSUE TITLE
feat: Stop shorts from looping

### ISSUE THREAD

**Issue by sekedus** [ReVanced/revanced-patches#2853]
### Application

YouTube

### Issue

It's annoying when shorts keep looping while commenting or doing other things.

### Patch

1. Pause shorts when comment
2. Disable shorts for looping
3. Limit looping to only 2 times.

### Motivation

This patch will be very useful when commenting or falling asleep because of sleepiness.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
For commenting you can tap to pause and for sleeping you should put your phone away.

**Comment by sekedus** [comment]
> for sleeping you should put your phone away

I mean, when watching shorts and falling asleep, shorts won't stop unless the cellphone battery runs out and turns off.
