### ISSUE TITLE
feat: OAuth and "Token export" patch for RedReader

### ISSUE THREAD

**Issue by MikaelaMuller** [ReVanced/revanced-patches#2855]
### Feature description

OAuth patch for a reddit client known as RedReader allows the use of user API Keys(?) iirc

"Token export" allows the user to export account information from one device to another contained in "databases" folder in RedReader 

### Motivation

RedReader is the only Reddit Client supported on Devices running OS below Android 5.0, an OAuth patch for it would be really handy especially for Older tablets (user keys can access NSFW content)

Token export is specifically for devices running Android 5 below to circumvent the issue of an outdated WebView making the regular login process impossible, i got around this issue duplicating the files stored "databases" folder on /data/data/ where RedReader's internal files are located from a newer device then transferring it to the appropriate folders on the older device. However this requires both devices to be rooted, while that may not be an issue for older devices it would be for newer ones considering rooting void warranty, makes banking apps act like a bish and stuff (screw you GCash) and also some owners of older devices would like to keep the OS untouched or it's simply not possible for them to acquire root.

By logging in on a patched version of the application on a newer device they can then export their token from the newer device to the old. This rids of the need for the devices to be rooted. 
r/androidafterlife would probably love this. 

That's all, despite statistics there's still people that use old devices.

Here's the tablet currently own: a Samsung Galaxy Tab 4 7.0 i bought in 2019 for 20 dollars. i rooted it, replaced its battery twice in two years because battery replacements for it are expensive and also crap so i just tore apart the battery and wired in a usb cable directly to where the battery would be slotted in so it runs indefinitely and applied all the tweaks i could, i had to bother xdadevelopers to scour through their now archived "DevDB" database for the best kernel for this device.
 
![IMG_20240116_234446](https://github.com/ReVanced/revanced-patches/assets/91151184/a197feeb-f40f-473f-b59d-1d1edaeb9e90)

please

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
RedReader is open source, I suggest you to open a feature request in their repository.
