### ISSUE TITLE
bug: (Youtube) Minimized playback patch breaks YouTube - Video immediately stops playing

### ISSUE THREAD

**Issue by DmacMcgreg** [ReVanced/revanced-patches#2856]
### Bug description

When using the "minimized playback" patch, youtube will immediately stop playing a video when hitting play.

Video of problem:

https://github.com/ReVanced/revanced-patches/assets/3266023/7791ef55-1f4e-4570-8606-22def9ef3946

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by DmacMcgreg** [comment]
Want to comment that I've uninstalled manager, and Youtube Revanced about 3 times, cleared data and cache on manager, and stock youtube. As soon as I unchecked Minimized Playback in the patching process, it works again. First time it has worked in about a month.

**Comment by DmacMcgreg** [comment]
Someone else having the same issue in Discord:
![CleanShot 2024-03-08 at 14 54 32@2x](https://github.com/ReVanced/revanced-patches/assets/3266023/24665967-573b-4c56-a642-6f0b0f8cd071)

**Comment by oSumAtrIX** [comment]
Please check the unpatched app. As mentioned in the issue you have linked, the problem is also observed on the unpatched app.

**Comment by DmacMcgreg** [comment]
@oSumAtrIX I've been using the unpatched app in the meantime during this past month without any issues at all, I've never seen this issue, and it showed up suddenly without installing any updates in Manager.

**Comment by DmacMcgreg** [comment]
@oSumAtrIX  I'm not following, isn't PiP only available with Youtube Premium?

**Comment by oSumAtrIX** [comment]
@DmacMcgreg Yes, PiP is only available with YouTube Premium and to test if ReVanced or YouTube breaks that feature, you have to test it on the unpatched app. As previously said, the problem is also observed on the unpatched app in the issue you have linked.

**Comment by DmacMcgreg** [comment]
@LisoUseInAIKyrios I've installed 18.49.37. First patch failed with Java out of memory exception (sorry I didnt keep the logs)
Second time I installed it, but it crashed immediately on trying to open.

@oSumAtrIX I'll try to get a trial and check...

**Comment by DmacMcgreg** [comment]
@oSumAtrIX Yes confirmed it is indeed stock PiP mode. Did anyone ever give any feedback on how to fix? Ideally without resetting the entire operating system..

**Comment by oSumAtrIX** [comment]
I suspect it is more like an issue with the OS, not YouTube, but I have no idea how the issue occurs or how it can be fixed.

**Comment by oSumAtrIX** [comment]
@LisoUseInAIKyrios The issue has been observed for a while now. The issue dates back a year to my knowledge.

**Comment by DmacMcgreg** [comment]
@cyberboh Android 14, Galaxy S 24

As soon as I got YouTube Premium to test this out, now my stock YouTube stopped working as well, and I cannot seem to fix it no matter if I disable, uninstall back to stock, etc.

Some post on reddit said it might be related to changing the android dns, and in fact I was using adguard dns. But even disabling that does not fix YouTube or Revanced.

 @LisoUseInAIKyrios no luck with any other version of YouTube patches.

**Comment by DmacMcgreg** [comment]
So I made another discovery.. In my stock youtube app, if I changed to another account, the videos play again. So there is definitely something weird happening on the backend with my account on their servers... I can still play shorts, and I can play on my computer, and TV, but just not on my android phone. And another account works perfectly with stock youtube.. will test with revanced with another account as well.

**Comment by oSumAtrIX** [comment]
That's likely A/B flags that are active on your account. You should report the bug before the deploy this on all accounts.

**Comment by DmacMcgreg** [comment]
I've been able to test on 2 other devices now, and the YouTube app works signed into my account. 
It's just my main device where it seems to be blocked. And only that account. Other accounts work fine.
So I'm thinking it's some MAC address or other specific identifier associated to my accound/device combination.

I've adb'd into the device to try to completely wipe the Youtube app, since its not possible to uninstall (only to remove the updates) and even that does not work.

Last thing to do would be a complete reformat, but I'd like to avoid that since its a massive inconvenience.

@oSumAtrIX  @cyberboh  any other ideas here?
Is there maybe a data folder somewhere on the phone to delete that has settings or data files related to youtube that don't get wiped when I adb uninstall the app itself?

Thanks again for your help. Obviously if you're busy I don't expect a reply since it's very specific to me...

**Comment by oSumAtrIX** [comment]
In case you need personal support, please move to one of our links at https://revanced.app
