### ISSUE TITLE
bug: YouTube shows ads

### ISSUE THREAD

**Issue by GKid94** [ReVanced/revanced-patches#2857]
### Type

Other

### Bug description

YouTube started showing ads in search results

### Steps to reproduce

Search something on YouTube 

### Relevant log output

```shell
/
```

### Screenshots or videos

![Screenshot_2023-08-21-23-58-00-256_app revanced android youtube](https://github.com/ReVanced/revanced-patches/assets/18757054/29a3b843-c30c-4bbd-8ba4-840bb4793c63)
![Screenshot_2023-08-21-23-58-26-969_app revanced android youtube](https://github.com/ReVanced/revanced-patches/assets/18757054/1dcfd367-7c6e-4d22-ba07-5c9f26d88f68)
![Screenshot_2023-08-21-23-59-12-558_com miui securitycenter](https://github.com/ReVanced/revanced-patches/assets/18757054/a8b11442-c30e-45ee-96e1-dc86fcf8f50d)
![Screenshot_2023-08-21-23-59-19-686_com android settings](https://github.com/ReVanced/revanced-patches/assets/18757054/a0b33d45-b6a7-4e18-8ab4-2c10af369c4d)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [ ] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Insufficient reproduction steps.

**Comment by GKid94** [comment]
> Insufficient reproduction steps. Try repatching as you might be on an old version

You can see what I searched on the screenshot

**Comment by GKid94** [comment]
@oSumAtrIX The Manager doesn't show new updates 
![Screenshot_2023-08-22-00-13-39-932_app revanced manager flutter](https://github.com/ReVanced/revanced-patches/assets/18757054/e18b695c-52dd-4245-8ae3-eabf57fe6674)
![Screenshot_2023-08-22-00-13-50-042_app revanced manager flutter](https://github.com/ReVanced/revanced-patches/assets/18757054/f0adb1fd-5a6e-417e-b78e-55b22ad8bbdd)

**Comment by oSumAtrIX** [comment]
ReVanced Manager auto-updates patches. You did not patch using the updated patches though

**Comment by GKid94** [comment]
@oSumAtrIX I reinstalled YouTube Revanced with the new patches and it doesn't show ads now, thanks
![Screenshot_2023-08-22-01-17-23-829_app revanced android youtube](https://github.com/ReVanced/revanced-patches/assets/18757054/70deac09-b24a-4656-878a-b661fe871506)
