### ISSUE TITLE
bug: Missing download option in shorts videos

### ISSUE THREAD

**Issue by GKid94** [ReVanced/revanced-patches#2858]
### Type

Other

### Bug description

The option to download video and audio are missing on shorts videos

### Steps to reproduce

Enable the external download option and open a short video

### Relevant log output

```shell
/
```

### Screenshots or videos

![Screenshot_2023-08-22-00-06-08-994_app revanced android youtube](https://github.com/ReVanced/revanced-patches/assets/18757054/65713633-d503-44fe-adb3-7a55e6c6f5e3)
![Screenshot_2023-08-22-00-06-53-120_app revanced android youtube](https://github.com/ReVanced/revanced-patches/assets/18757054/277e45f5-ece7-4a3e-a7eb-4f8b46fb27a8)
![Screenshot_2023-08-21-23-59-19-686_com android settings](https://github.com/ReVanced/revanced-patches/assets/18757054/9c7e9871-0e30-4d70-b026-9dea7403ec74)
![Screenshot_2023-08-21-23-59-12-558_com miui securitycenter](https://github.com/ReVanced/revanced-patches/assets/18757054/e9e20ae9-c8f8-4f66-863c-36a6364e2bcd)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
This is not a bug. The feature does not exist.

**Comment by GKid94** [comment]
> This is not a bug. The feature does not exist.

Then how do I download short videos?

**Comment by cyberboh** [comment]
> > This is not a bug. The feature does not exist.
> 
> Then how do I download short videos?

copy link to external downloader

**Comment by GKid94** [comment]
> > > This is not a bug. The feature does not exist.
> > 
> > 
> > Then how do I download short videos?
> 
> copy link to external downloader

Ok thanks
