### ISSUE TITLE
feat(YouTube): allow to toggle PiP mode quickly

### ISSUE THREAD

**Issue by trmdi** [ReVanced/revanced-patches#2858]
### Feature description

Add a button on the player controller to quickly toggle the PiP mode. (Picture in Picture)

### Motivation

Suppose the PiP mode is disabled. Sometimes you're watching an interesting video and want to keep your eyes on it while multitasking. Going to the settings page to toggle it can be cumbersome, so it would be nice if you could just click on a button on the player controller to toggle it.

### Acknowledgements

- [x] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
You can enable PiP and the pause the video before exiting, or closing PiP

**Comment by trmdi** [comment]
> You can enable PiP and the pause the video before exiting, or closing PiP

The problem is doing that requires too many steps.

**Comment by trmdi** [comment]
> You can enable PiP and the pause the video before exiting, or closing PiP

The problem is doing that requires too many steps. Also it doesn't solve the normal usecase when you often listen to music in the background. Just sometimes you suddenly want to enable PiP to watch a video. And then disable it.

Btw you always close Feature requests too soon. Why can't you keep it opened for a while to see if anyone else is interested in implementing it? :(

**Comment by oSumAtrIX** [comment]
It requires a single step which is pausing the video so no.

**Comment by trmdi** [comment]
> It requires a single step which is pausing the video so no.
> 
> > Why can't you keep it opened for a while to see if anyone else is interested in implementing it?
> 
> Because it likely won't be implemented by anyone due to being able to pause the video and because it pollutes the issues

Then how can you listen to music in the background mode?

**Comment by oSumAtrIX** [comment]
By clicking on the background play icon in PiP

**Comment by trmdi** [comment]
> By clicking on the background play icon in PiP

Ah I'm requesting kind of this, but it works a bit differently. This PiP always shows up when you open Youtube and hide the app. While what I want is only show PiP when I want. Thank you anyways. 👍
