### ISSUE TITLE
feat: Hide, reorder or default filter item in Subscriptions page

### ISSUE THREAD

**Issue by kazink** [ReVanced/revanced-patches#2859]
### Feature description

Hi, and thanks to all of the creators of ReVanced an patches for the great work.
I use ReVanced on my phone almost exclusively to watch long videos. For this reason the first I do after starting the app (if it has been shut down by Android) is to go the Subscriptions page, and click on the Continue watching filter category. What I would welcome is for the Continue watching category to be selected by default. Currently, it it off-screen by default, and I have to scroll to find it every time. Alternatively I would welcome an option for the filter category to be the first one on the list, or the only one on the list, whichever is easiest to implement.

In case for some reason your layout is different, and/or you don't know what I'm talking about, I can provide screenshots.

Thank you very much. 

### Motivation

I use ReVanced on my phone almost exclusively to watch long videos, and almost always from the beginning to the end. Thus naturally, when I start watching (after the app has been shut down by Android, which happens everyday, sometimes multiple times a day) I go to Subscriptions page and then tap on Continue watching filter category. It wasn't so bothersome when the category was visible by default, but a few weeks ago more categories were added in front of it, and now I have to scroll left to see it every time, which is annoying.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
The effort to swipe and click on the category is minimal. You can use the patch that changes the start page to the subscriptions page to cut corners if you have to.
