### ISSUE TITLE
Twitter: Banner ads in search

### ISSUE THREAD

**Issue by 11xjas** [ReVanced/revanced-patches#286]
### Application

Twitter

### Issue

Ads showing up in twitter search tab.

### Patch

Patch to hide banner ads in twitter search tab.

### Motivation

![Screenshot_20231001_044232_X](https://github.com/ReVanced/revanced-patches/assets/93155066/cda200c8-b764-4b6c-8b8a-d63e947a3a90)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by sinkaf** [comment]
Sponsored ads are shown in the explore section, as always.

**Comment by escape0707** [comment]
Coming from #1733, I want to say Ads in the comment section are annoying as well.

**Comment by escape0707** [comment]
@cyberboh Oh, I guess you are right. It seems that the older comment section ads are already blocked by some recent version of patches. I didn't check this.
