### ISSUE TITLE
feat: Continue last video by default

### ISSUE THREAD

**Issue by kazink** [ReVanced/revanced-patches#2860]
### Feature description

Could you please add an option to start the app with the last video that was played when the app was shut down open (could be on the player screen or minimised)? (The last video played in the app specifically, not the last video played on my YT account).

### Motivation

I use the Android app almost exclusively to watch long videos, and I almost always watch them from beginning to the end. 
After the app has been shut down by the Android system (which happens every day, sometimes multiple times a day), the app starts on the Home page, and I have to navigate to Subscriptions, then Continue watching, and find the last video I was watching among all the other videos I watched on my PC (and YT keeps there because often the ending of the actual content was before the point at which YT would consider the video watched in full). This is annoying to have to perform this procedure ever time, especially when (sometimes) the app gets shut down a few seconds after I have started playing a video.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by kazink** [comment]
> You can navigate to your watch history instead of subscriptions, and the last video is there. Two taps and the last video is opened.

Good point, but in the watch history there could be multiple videos I have watched on another device in the meantime. Scrolling sideways is still quicker than tapping multiple menus and scrolling though, so thanks for the suggestion. An option to continue watching effortlessly would be welcome anyway :)

**Comment by oSumAtrIX** [comment]
I think you should create a playlist and add the video to it if you want to watch it later again. YouTube has a "Watch later" playlist for that reason.
