### ISSUE TITLE
feat(PowerPoint): ability to edit and save documents.

### ISSUE THREAD

**Issue by DiyarD** [ReVanced/revanced-patches#2861]
### Feature description

Ability to edit and save files using Microsoft's PowerPoint app. The free version is restricted to read only, nothing else. It would be great to directly edit files in the original app as no alternative on android works properly.

### Motivation

Microsoft has a monopoly over android document processing apps (powerpoint in this case). Every single alternative processes the documents incorrectly and microsoft's free version is read-only.
![Screenshot_20240310_175954_PowerPoint](https://github.com/ReVanced/revanced-patches/assets/11034452/79c912ec-6836-4929-a520-4467769e9a86)

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
The screenshot you made is of a Desktop app. Not sure what the censoring is for: 
![image](https://github.com/ReVanced/revanced-patches/assets/13122796/0dd3abb5-f885-4b55-b7f1-76fa9a9bc22e)
****

**Comment by DiyarD** [comment]
it's samsung dex (galaxy tab's desktop mode for android.). i hid my account name..

**Comment by DiyarD** [comment]
> The screenshot you made is of a Desktop app. Not sure what the censoring is for: ![image](https://private-user-images.githubusercontent.com/13122796/311521814-0dd3abb5-f885-4b55-b7f1-76fa9a9bc22e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAwODU0NDMsIm5iZiI6MTcxMDA4NTE0MywicGF0aCI6Ii8xMzEyMjc5Ni8zMTE1MjE4MTQtMGRkM2FiYjUtZjg4NS00YjU1LWI3ZjEtNzZmYTlhOWJjMjJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEwVDE1MzkwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxYjJhMDUzMDZkMTQyMGM1YzhmNWRjMjVmNGViMDI3YWFjMTdlNGUyZTQ2NjFhMTZjMDQ3ZDc2NjRiZjQyYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7cwyCyzihGw9FkQqSzgwYQTIB1XWPKzqn0snkfEPxBw)

it's samsung dex (galaxy tab's desktop mode for android.). i hid my account name..

**Comment by oSumAtrIX** [comment]
In that case dismissing the issue as per contribution guidelines

**Comment by Julmik647** [comment]
You can try Google Slides or WPS Office instead.
