### ISSUE TITLE
feat: Option to disable reels from Instagram app

### ISSUE THREAD

**Issue by randomcloudswings** [ReVanced/revanced-patches#2864]
### Feature description

There should be option to disable reels from Instagram app

### Motivation

removing reels could help reduce distractions and prevent users from spending excessive time on the app, promoting healthier digital habits.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
https://github.com/ReVanced/revanced-patches/issues/409
