### ISSUE TITLE
bug(YouTube): previews stop loading after ~35s

### ISSUE THREAD

**Issue by trmdi** [ReVanced/revanced-patches#2865]
### Bug description

When you browse through the video list and pause at a video, the preview loads, but it stops after ~35s, the preview becomes loading forever. Something that the spoof signature patch hasn't solved?
![Screenshot_2024-03-12-08-54-44-823-edit_app revanced android youtube~2](https://github.com/ReVanced/revanced-patches/assets/11857205/9b44a12c-ef50-42a5-b01d-efad5e05a8c6)

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by KobeW50** [comment]
This is a known issue. You can enable spoofing in feeds to resolve this, but there are other side-effects of enabling that.

**Comment by trmdi** [comment]
> This is a known issue. You can enable spoofing in feeds to resolve this, but there are other side-effects of enabling that.

Ah thanks, it works.

**Comment by trmdi** [comment]
... but it will spam the History.
https://github.com/ReVanced/revanced-patches/issues/2813
