### ISSUE TITLE
feat: (YouTube) Add an option to 

### ISSUE THREAD

**Issue by ShadowOne333** [ReVanced/revanced-patches#2871]
### Application

YouTube

### Issue

Currently, when using YouTube Revanced, there's no option to get rid of the recommended Playlists or Mix that appear when visiting the Home page. 

The only options we get are "Play next in queue", "Save to library" and "Share", but there's no option to either hide or select "Not interested" so the playlist recommendation disappears from Home.

### Patch

Upon selecting the three dots for playlists / mix recommendations, an option to select either "Hide" or "Not interested" should appear. Logging into YouTube with a browser does show this option when pressing the three dots for these playslists:

![Untitled](https://github.com/ReVanced/revanced-patches/assets/13888698/3f9fe809-c2f2-492c-8657-0b534cf00801)

### Motivation

It helps to be able to clean up the recommendations that YouTube gives by default inside the Home page (and to make it look cleaner and only get proper new videos as recommendations), since more than not they like to "suggest" a bunch of videos as a full playlist or "mix".

Also, for people that like to keep their Home page clean or dumb suggestions when hiding videos, it would help further for having more proper and interesting suggestions for the end-user.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [ ] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
This sounds more like a bug by YouTube and should be reported on their end.

**Comment by KobeW50** [comment]
YT ReVanced has the option to hide all mixes. Apply the Hide Layout Components patch.

Then open YT ReVanced > profile picture > Settings > ReVanced > Layout > Hide mix playlists, ON

**Comment by johnconner122** [comment]
> This sounds more like a bug by YouTube and should be reported on their end.

I don't think it's a bug. Youtube removed this option few months ago.

**Comment by oSumAtrIX** [comment]
If they removed it, it can still be a bug. Why would it exist on desktop then?
