### ISSUE TITLE
feat: Option to turn off autoplay for playlists

### ISSUE THREAD

**Issue by Clydefrosch22** [ReVanced/revanced-patches#2871]
### Feature description

Essentially my only gripe with the youtube app is that you can't turn off playlists just going on forever.

It would be great if there could be an option to either stop autoplay altogether, or a bit more fancy, to have a counter to set like 3 and then it stops after 3 videos unless you take action. Either would be amazing.
Some podcast/music player apps also have a sleep timer where playback ends after X minutes have passed, something like that would also work.

![Unbenannt](https://github.com/ReVanced/revanced-patches/assets/21969634/f712bbc4-6245-4b83-8601-e2c40bf721a3)
An on/off switch in this general area might be good, if possible?

I dunno what can really be done on a technical level, it might be good enough if this just made the video pause at the very last second, thus preventing it from moving on? Whatever is easiest.

Any consideration is greatly appreciated, thank you.

### Motivation

I get that a playlist is technically meant to just go on, but anytime I fall asleep to something like a letsplay or a show reaction, essentially any long format content, I spend forever finding where I actually dozed off, while dozens of videos are marked as played, making it harder to find my place anytime after, as well as clogging up the history.

 I believe its also a needless waste of resources, if phones just run on potentially the whole night for no reason, servers, traffic, energy, etc. So it'd be slightly environmentally friendly

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by KobeW50** [comment]
https://github.com/ReVanced/revanced-patches/issues/1951
