### ISSUE TITLE
YouTube: Bottom bar tweaks

### ISSUE THREAD

**Issue by 111ebobo** [ReVanced/revanced-patches#2873]
### Feature description

Add an ability to move that bottom bar to upper side where it can be automatically hidden when scrolling, and add an ability to access to library stuff in that bar just by swiping like it was in the older versions. Also you can turn that bar into "hamburger" menu like in PC version 

### Motivation

1. Moving the bar to the top of the screen and auto hiding it will make more space for content to appear
2. It will make the app more customizable 

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Refer to

https://github.com/ReVanced/revanced-patches/issues/2695#issuecomment-1929399148

**Comment by 111ebobo** [comment]
> Refer to
> 
> [#2695 (comment)](https://github.com/ReVanced/revanced-patches/issues/2695#issuecomment-1929399148)

you don't need to redesign, is there a problem by moving an item into another position?

**Comment by oSumAtrIX** [comment]
Yeah, it has no benefig

**Comment by 111ebobo** [comment]
> Yeah, it has no benefit

Why, if that bar will be on top it can be made to hide the same as the bar with the search button do

**Comment by oSumAtrIX** [comment]
That can be done with a bottom bar just the same way

**Comment by 111ebobo** [comment]
> That can be done with a bottom bar just the same way

Some make this at least because it's annoying that the bar is covering part of the screen just for nothing

**Comment by 111ebobo** [comment]
Can you reopen the issue please?

**Comment by oSumAtrIX** [comment]
Open a new issue.

**Comment by 111ebobo** [comment]
> Open a new issue.

I did it
