### ISSUE TITLE
feat: (YouTube/download) disallowed download HD format anymore.

### ISSUE THREAD

**Issue by ayoubelmhamdi** [ReVanced/revanced-patches#2875]
### Feature description

we can't download the `YouTube` video using the latest version recommended, this bad breaking change of disallowed download video format for non-premium users, coming this week, with an added `1080p` but for premium users only too.

![Screenshot_2024-03-14-14-56-05-165_app revanced android youtube-edit](https://github.com/ReVanced/revanced-patches/assets/34358145/636c4edc-d6e1-47d3-9902-01cbd096d4cc)

### Motivation

YouTube without HD is not a big deal; all tutorials or programming on YouTube in `360p` video format are useless.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
This is a YouTube Premium feature. You can use the "External downloads" patch

**Comment by ayoubelmhamdi** [comment]
@oSumAtrIX 
I can't give up, i wrote another issue about it.
https://github.com/ReVanced/revanced-patches/issues/2876
