### ISSUE TITLE
feat: audio only youtube

### ISSUE THREAD

**Issue by Sharathsukash** [ReVanced/revanced-patches#2876]
### Application

YouTube

### Issue

high bandwidth consumption for streaming music videos and podcasts on YouTube(one which is not on yt music )

### Patch

The patch will work like adding a extra resolution called audio only which will disable video stream

### Motivation

It allows better streaming and distraction free music/podcast experience 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
You can minimize or turn off your phone, or use YouTube Music, no additional "resolution" is needed.
