### ISSUE TITLE
feat(YouTube): Tablet UI mode

### ISSUE THREAD

**Issue by 111ebobo** [ReVanced/revanced-patches#2877]
### Application

YouTube 

### Issue

Poor customization 

### Patch

Patch that will make the tablet UI for all devices 

### Motivation

It increases the level of customization, and tablet UI can be useful 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [ ] I have written a short but informative title.
- [ ] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Not sure how tablet UI can be useful. Insufficient motivation

**Comment by kazimmt** [comment]
@oSumAtrIX  Tablet UI (trick dpi) gives a better look compare to Regular UI
![Screenshot_20230826-175249_YouTube](https://github.com/ReVanced/revanced-patches/assets/82371061/cb237bd3-847b-4bc8-877a-18f7434b3138)
![Screenshot_20230826-175258_YouTube](https://github.com/ReVanced/revanced-patches/assets/82371061/cddfc439-1c37-4ec0-9a0a-9ea28e634b00)
![Screenshot_20230826-175309_YouTube](https://github.com/ReVanced/revanced-patches/assets/82371061/3787a29d-0a26-4d57-8bdf-1faf0c5c4950)

**Comment by kazimmt** [comment]
We can change the dpi from phone's dev setting. But it applies for all the app.

**Comment by 111ebobo** [comment]
> We can change the dpi from phone's dev setting. But it applies for all the app.
> 

But scaling can affect other apps and cause some issues like: System UI will be overlapped with camera hole

**Comment by 111ebobo** [comment]
> We can change the dpi from phone's dev setting. But it applies for all the app.
> 

But scaling can affect other apps and cause some issues like: System UI will be overlapped with camera hole
