### ISSUE TITLE
bug: (Tiktok) Can't win free coin with TikTok Revanced

### ISSUE THREAD

**Issue by jvachez** [ReVanced/revanced-patches#2877]
### Bug description

Hello !

I never win free coin in Tiktok revanced (treasure, gift).
It happens even when there are less participants than winners. So it's not a lack of luck problem.

It seems revanced users have a banned android id or something like that.

Steps to reproduce : try to win coins in Tiktok live with treasure or gift (easier than treasure because don't have to be quick). Best is trying when there are less participants than winners.

Thanks

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Or you are just unlucky.

**Comment by jvachez** [comment]
> Or you are just unlucky.

No because when there are less participants than winners I should win.

**Comment by oSumAtrIX** [comment]
In that case you will need to provide proper evidence that the issue is caused by ReVanced.
Use the minimum amount of patches and show how the unpatched app behaves differently from the patched app.

**Comment by oSumAtrIX** [comment]
The package name is not changed, but a signature check can't be ruled out yet.
