### ISSUE TITLE
Hide songs on YouTube Shorts 

### ISSUE THREAD

**Issue by everypizza1** [ReVanced/revanced-patches#2882]
### Feature description

A good feature for YouTube Revanced would be the ability to hide Shorts with a specific song. Other platforms, such as TikTok, have this feature. I'm not sure if this would be possible, but it might be similar to blocking ads.

### Motivation

It gets annoying after you are scrolling through the shorts feed for less than 5 minutes and you have heard the same song repeatedly.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
In most cases the song is not tagged correctly and shorts say "Original audio". The feature would be highly impractical.
