### ISSUE TITLE
feat: (YouTube) Add "Hide Stats for nerds" in the "Player flyout menu items"

### ISSUE THREAD

**Issue by 54m4d** [ReVanced/revanced-patches#2886]
### Application

`com.google.android.youtube`

### Issue

Hide an item in the Player flyout menu.

### Patch

This patch/addition should hide `Stats for nerds` in the `Player flyout menu`

### Motivation

All the items in the `Player flyout menu` have a toggle in the settings that hides them, except for `Stats for nerds`, so why not?

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Because it can be hidden in YouTube

**Comment by 54m4d** [comment]
Bro why are you always fast to close our issues? Are you in a hurry or something?

If you think it's in YouTube, The least you can do is to provide proof. Take a screenshot and put it here.

**Comment by oSumAtrIX** [comment]
First time seeing someone complaining about fast response time.

I don't need to proof anything, it's a Google search away.

**Comment by 54m4d** [comment]
No! that's the first thing i checked, it's off but i still see stats for nerds, that's why i asked to put the proof.

This is the behaviour i have https://github.com/ReVanced/revanced-patches/issues/358#issuecomment-1220987898

**Comment by oSumAtrIX** [comment]
![Screenshot_20230828-142046](https://github.com/ReVanced/revanced-patches/assets/13122796/54e9e134-235e-4f36-bfed-81fcf5bd16c6)

**Comment by 54m4d** [comment]
Definitely something wrong with this option. Solution: although it's off by default, turn it on, then off, after that, the behaviour of this option works as intended.

As you can read in the comment i linked, that user had the same behaviour i experienced today. I never enabled stats for nerds but i could still see it in the player flyout menu until i performed the "solution" i mentioned above.

**Comment by 54m4d** [comment]
That must have been going for so long then, but i can't tell for sure since i don't have the stock yt and probably not willing to check it either since my issue is resolved :)

All in all, it's just another reminder that good communication is key.

**Comment by johnconner122** [comment]
> I've never seen stats for nerds show up unless it's enabled in YouTube settings. It sounds like something is going wrong and it's showing the stats menu when it should not.

It happens if you switch google account.
