### ISSUE TITLE
YouTube: Bottom bar tweaks 

### ISSUE THREAD

**Issue by 111ebobo** [ReVanced/revanced-patches#2887]
### Feature description

Add an ability to move that bottom bar to upper side where it can be automatically hidden when scrolling, and add an ability to access to library stuff in that bar just by swiping like it was in the older versions. Also you can turn that bar into "hamburger" menu like in PC version 

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

### Motivation

1. Moving the bar to the top of the screen and auto hiding it will make more space for content to appear
2. It will make the app more customizable 

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
As explained previously, the bottom bar does not need to be moved to the top which also destroys accessibility through reachability: https://github.com/ReVanced/revanced-patches/issues/2873#issuecomment-1998098762

**Comment by 111ebobo** [comment]
> As explained previously, the bottom bar does not need to be moved to the top which also destroys accessibility through reachability: https://github.com/ReVanced/revanced-patches/issues/2873#issuecomment-1998098762

So what do you think about making it auto hidable or hidable in any way, also, in horizontal mode it's not that hard to reach the top?

**Comment by 111ebobo** [comment]
> > As explained previously, the bottom bar does not need to be moved to the top which also destroys accessibility through reachability: https://github.com/ReVanced/revanced-patches/issues/2873#issuecomment-1998098762
> 
> So what do you think about making it auto hidable or hidable in any way, also, in horizontal mode it's not that hard to reach the top? 

And even if it does, isn't it better for the users to choose in which way, it's comfortable for them?
