### ISSUE TITLE
bug: Sync for Reddit can't open /a/ links

### ISSUE THREAD

**Issue by wason-sonico** [ReVanced/revanced-patches#2888]
### Bug description

Similar to the new Reddit links with a "/s/" imgur added a "/a/" to their links.

This is the old version of imgur links that Sync for Reddit can open without issues:
https://imgur.com/7N5QNaz

This is the new version of imgur links that can't be opened within the app:
https://imgur.com/a/7N5QNaz

They now include /a/

### Solution

Please implement a similar solution to the /s/ for Reddit links but this will be a /a/ for imgur links.
Thanks!

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
That's not a ReVanced related bug

**Comment by wefalltomorrow** [comment]
> That's not a ReVanced related bug

But isn't it something that can be fixed via a Revanced patch like what was done for /s/ URLs on Boost, etc.?
