### ISSUE TITLE
YouTube: hide the bottom bar

### ISSUE THREAD

**Issue by 111ebobo** [ReVanced/revanced-patches#2889]
### Feature description

Add a feature that will hide the bottom bar when scrolling or add a button which will hide the bar

### Motivation

1. The point of that patches is to have more customizability for the app
2. It will give some more space for content 

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
In which scenario is more vertical space necessary?

**Comment by 111ebobo** [comment]
> In which scenario is more vertical space necessary?

In scrolling when looking for videos to watch in the feed

**Comment by oSumAtrIX** [comment]
Enough vertical space is present.

**Comment by 111ebobo** [comment]
> Enough vertical space is present. 1cm/10% more space is hardly an issue

But still that 10% is important for someone, for example I want to have more content to be visible instead of the bar which I barely use

**Comment by oSumAtrIX** [comment]
10% has almost no impact on content. The bar is used a lot to switch between subscriptions notifications, your own library or the feed. Closing therefor.

**Comment by 111ebobo** [comment]
> 10% has almost no impact on content. The bar is used a lot to switch between subscriptions notifications, your own library or the feed. Closing therefor.

1. it has a lot of impact
2. I don't think that people are using the bar that much that we need to leave that 10% of space
Please reopen the issue (it feels like you just don't want to do anything, like it wouldn't be better if people would have an ability to edit every UI element right?
