### ISSUE TITLE
YouTube: Hide bottom bar 

### ISSUE THREAD

**Issue by 111ebobo** [ReVanced/revanced-patches#2890]
### Feature description

Add a feature that will hide the bottom bar when scrolling or add a button which will hide the bottom bar 

### Motivation

1.The point of that patches is to have more customizability for the app
2. It will give some more space for content 
3. It adds many space for the content
4. That bar can be annoying for some people because it isn't used that much to stay in the UI all the time

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
1. Customization has to be reasonable. This one isnt.
2 and 3 are the same point arguing about 10% more space.
4. The app is primarily a video player where you watch videos.

**Comment by 111ebobo** [comment]
> 1. Customization has to be reasonable. This one isn't.
> 
> 2 and 3 are the same point arguing about 10% more space.
> 
> 4. The app is primarily a video player where you watch videos. 
> 
> Please stop opening the same issue again.

1. Why is it not reasonable? Because it gives an ability to remove 10% of almost useless things
2 and 3. It's almost the same to show why it's important
4. Yes it is, but it will be much better to have more space to find videos
And yes I WILL reopen am issues until it will be approved
