### ISSUE TITLE
bug: (YouTube) Shorts and Post showing infinity loading in subscription page

### ISSUE THREAD

**Issue by dushmanta05** [ReVanced/revanced-patches#2892]
### Bug description

I've hidden the shorts and post component in Revanced setting but in subscription page the shorts and post option is visible and clicking on them shows infinity loading screen.

I've attached a video reference below

https://github.com/ReVanced/revanced-patches/assets/73304098/473c4b4d-80ca-498a-80d1-097ee40fce47

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
This is not a bug currently as the patches hide the content. A feature to selectively hide them in the home or search feed could be added

**Comment by dushmanta05** [comment]
I thought the bug section would be appropriate for this issue, so I opened it under this. I would love to do this patch, but I've got no experience in Android development. But I'll give it a try, thanks.

**Comment by dushmanta05** [comment]
Cool! Thanks for the detailed explanation, I guess figuring out distinguish button is the tricky part here
