### ISSUE TITLE
feat: Improvements Needed

### ISSUE THREAD

**Issue by yogesh-hacker** [ReVanced/revanced-patches#2894]
### Feature description

I can tell you that even though ReVanced providing many features still it forget its origin(Vanced). There's a lots of features that Vanced owned but this not, here's a list...

1. Personalization:- Vanced offered beautiful experience like its personalization algorithm I don't know how but Vanced knows what content user needs and when needs. ReVanced doesn't offer this because it provides random and useless contents in my home page even though I didn't watched it.

2. Optimization:- I don't how Vanced offered better optimisation like managing app's overall life-cycle, optimised layout. But ReVanced once you close screen it losts it old state 😂.

These two are major problems... stills theres numerous but I can't say it at once...

### Motivation

I have already said earlier it can ruin user experience.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
What you likely are referring to is YouTube and as such should reach out to them

**Comment by yogesh-hacker** [comment]
I don't know that was YouTube providing recommendations or Vanced but it was so precise in Vanced, I think they used something algorithm because my genres are same but in ReVanced I don't get what I want. I know YouTube provide recommendations but Vanced done something in their application the recommendation was perfect and precise.


Still... Keeping Recommendation aside, you need to improve app optimisation instead of focusing new features, optimise old features first.

**Comment by Ushie** [comment]
Youtube ReVanced faces no issues similar to what was mentioned in the opening message, I cannot recreate losing state, are you on the latest supported version with latest patches?

**Comment by yogesh-hacker** [comment]
In case of ReVanced I always try to be updated. 

And about the issues, yes may be the issues is look nothing in your devices but matters on user devices. Test your app in low ended devices see performance and improve it, the app also careless about his life-cycles sudden stops, crashes. Activity life-cycles are not handled properly....

At the end, I was trying to show you the problems and issues, it matters for me because I am like promoter I promote your app to my clients, friends and families. I always get reports from my clients about your app...

Some of them says Buttons are not showing, app crashes while in background mode, app freezes its PiP mode there's a lots of issues they face I only pointed out important ones.

I appreciate your work, As an app developer I know how much effort it takes... Its our task to provide better applications to users.

**Comment by Ushie** [comment]
Those all sounds like issues of YouTube, not ReVanced.
