### ISSUE TITLE
Removal of No Longer Supported Patch in Revance Manager

### ISSUE THREAD

**Issue by akashsriramganapathy** [ReVanced/revanced-patches#2895]
### Issue Description:
The current version of Revance Manager includes a patch that supports Insta and Facebook paths which are no longer functional. This patch is no longer supported by the respective platforms and is causing unnecessary bloat in the software. To maintain efficiency and relevance, it is essential to remove this obsolete patch from the Revance Manager.

### Requested Action:
I kindly request the development team to prioritize the removal of the outdated Insta and Facebook paths from the Revance Manager codebase. This action will streamline the software, improve performance, and ensure that resources are allocated effectively towards supported features.

__

### Impact:
- **Improved Performance:** Removing obsolete patches will enhance the overall performance of Revance Manager.
- **Resource Optimization:** By eliminating unnecessary code, resources can be redirected towards enhancing current functionalities.
- **Relevance:** Keeping the software up-to-date with supported features ensures its relevance in the market.

### Timeline:
I understand that development priorities may vary, but I urge the team to consider this request at their earliest convenience to maintain the integrity and efficiency of Revance Manager.

Thank you for your attention to this matter.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by KobeW50** [comment]
It might help to name the patch(es) 😅

**Comment by oSumAtrIX** [comment]
Broken patches are subject to a bug issue and are to be fixed. Not removed
