### ISSUE TITLE
feat: YouTube: Hide shorts tab from trending

### ISSUE THREAD

**Issue by dib12** [ReVanced/revanced-patches#2900]
### Feature description

In trending trending tab shorts tab exist.There is no shorts video layouts though.

It will better  if u implement the home screen shorts tab in shorts tab instead of implement in navigation botton.(All in one hide shorts in one click)

Another request can you please implement the disable watermark in different patch like before.

### Motivation

For easy 

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by dib12** [comment]
Also shorts exist in channel tab
![Screenshot_20240322-141725_crDroid Home](https://github.com/ReVanced/revanced-patches/assets/61652361/2156d7d1-dc46-4a9d-8044-cb47bf59350d)
 also  exist in Channels

**Comment by oSumAtrIX** [comment]
The buttons aren't in your way like the navigation bar button. Hiding channel watermark is offtopic and already possible
