### ISSUE TITLE
Tick tick premium

### ISSUE THREAD

**Issue by LeYoucef** [ReVanced/revanced-patches#2902]
### Application

Tick tick 

### Issue

The patch will let you use premium for free

### Patch

The patch will unlock premium features 

### Motivation

Alot of people need to do list app and this one is one of the best 

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by kazimmt** [comment]
#1132
