### ISSUE TITLE
Make custom-branding keep certain aspects of the og icon to remain distinguishable

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [ReVanced/revanced-patches#2907]
### Application

Any apps that custom branding can be used 

### Issue

Custom branding will be available to all apps soon.(according to ushie) 

Currently it is already confusing enough to have 2 identical icons at the app selection menu: manager and patched youtube.

Imagine if there are 20 apps all with the same icon, and it would be a hard time finding the correct app. 

The new default icon should be easily distinguishable from all patched apps and from the orginal app, while still be familiar enough 

### Patch

Conserve certain aspects of the orginal icon to make the app more identifiable, for example, ranked from the most prefered to the least:

1. add a ReVanced badge on og icon (edit done at **client side**, should have no copyright issues)
2. extract a dominant color from the og icon and add it in the corner to the ReVanced logo
3. extract a dominant color from the og icon and use it as the ReVanced logo background 
4. make the user select a color and use as ReVanced logo background, and conserve the same color after update
5. randomly generate a color and use as ReVanced logo background, and conserve the same color after update
6. randomly generate a color and use as ReVanced logo background, but change the color each update

### Motivation

Having too many apps with the same icon is not good for user experience as it is very confusing. 

Different colors are easily identifiable 

Both patches and OG apps can exist together with the change package name patch so not changing the icon will be confusing 

Changing to the same icon will cause multiple apps to have the same icon which is also confusing

Keeping certain aspects (e.g. The color) from the orginal icon should make a much more unique icon but still be familiar and recognizable. This is a balanced decision, which is better than a random color as it is dont have any relations to the orginal app thus not familiar.

By default, if no icons are selected, it should remain distinguishable from other patched apps 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
You can select your own icon or not apply the patch. This is not a drawing application or an icon customization app

**Comment by SodaWithoutSparkles** [comment]
the issue of not applying the patch was already mentioned 

The ability of selecting your own icon does not mean it is suitable to have multiple of the same default icon. Defaults shouldnt be confusing.

**Comment by oSumAtrIX** [comment]
The default isn't confusing and the description let's you know about it. You very likely want to use the patch to change the icon of apps, and not to apply the default

**Comment by SodaWithoutSparkles** [comment]
> The default isn't confusing and the description let's you know about it. 

The defaults aint confusing until there's multiple of it. Description is much less noticeable.

> You very likely want to use the patch to change the icon of apps, and not to apply the default 

But most of the people won't modify the defaults to prevent issues. This is also recommended by the docs.

**Comment by oSumAtrIX** [comment]
> The defaults aint confusing until there's multiple of it. Description is much less noticeable. You will notice the colored icons first then the dull thin text next to it, especially when the area is crammed.

If you apply a patch without reading what it does the issue is at your end. The patch is disabled by default.

> But most of the people won't modify the defaults to prevent issues. This is also recommended by the docs.

Then they wont want to use the patch either.

> As discussed earlier on Discord, the easiest way would be to overlay a revanced icon on the og icon, which is solution 1.

Suggest a detailed implementation.

**Comment by Ushie** [comment]
The issue lies in patching apps that are already in system, such as YouTube

patching them requires changing the package name (for non-root users) as they can't install them over the ones in system, which means they will have to have both of them installed at once

Maybe ReVanced Manager can suggest disabling the original one??

**Comment by oSumAtrIX** [comment]
If you install a patched app that has a signature mismatch, ReVanced Manager can suggest to handle this case, but this is something unrelated to this issue, and an issue regarding this is already open in ReVanced Manager repository.

**Comment by Ushie** [comment]
Then this issue can be dismissed, as there no longer will be any apps with the same app name and icon

**Comment by oSumAtrIX** [comment]
YouTube can not be uninstalled though, if the package is the same and the signature mismatches, installation will only be possible by mounting.

**Comment by Ushie** [comment]
I edited my comment, please give it another read

**Comment by oSumAtrIX** [comment]
Suggesting to uninstall would be unintended. ReVanced Manager would implement this feature solely based on the assumption that it is a given thing that patched apps change package names, which is neither the case nor the task of ReVanced Manager. The branding patch is something someone can use if they'd like to brand their patched apps, including it by default, which applies the default icon; it could also simply not do anything at all and raise an exception about no branding being configured, but providing a default is better.
