### ISSUE TITLE
feat: change package name of X

### ISSUE THREAD

**Issue by shifoc** [ReVanced/revanced-patches#2909]
### Motivation

Updates won't show up on the playstore and beable to download the original app at the same time

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Changing the package name is already a patch

**Comment by shifoc** [comment]
It's annoying always having to sjip the update in the playstore. You said it's already a patch but I can't find it
![Screenshot_20240325_180224_ReVanced Manager.png](https://github.com/ReVanced/revanced-patches/assets/32818143/4def33e2-049f-46e3-b204-df91cf4387d3)

**Comment by oSumAtrIX** [comment]
Skipping updates is hardly problematic as you just click skip if at all. If you have a problem with Play Store you should report that to Google. The patch is a universal patch that's hidden behind a toggle in the settings. For support move to our links at https://revanced.app

**Comment by JapanYoshi** [comment]
The universal patch doesn’t work on my end:

When I try to install the patched X app, my phone says this app is already installed, and offers to uninstall it. However, the phone also fails to find that conflicting app because I changed the app’s package name. I’m on GrapheneOS btw.

**Comment by oSumAtrIX** [comment]
For support move to one of our links at https://revanced.app
