### ISSUE TITLE
feat(Messenger) : Remove Switch Account Limit

### ISSUE THREAD

**Issue by JeelsBoobz** [ReVanced/revanced-patches#2911]
### Application

Facebook Messenger

### Issue

Can't add account more than 5

### Patch

Need login switch account limit more than 5

### Motivation

I think some user need it

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Why would anyone need more than 5 accounts, doesn't make sense.
