### ISSUE TITLE
feat: YouTube Music: Limit pings to ad servers

### ISSUE THREAD

**Issue by NMinker** [ReVanced/revanced-patches#2912]
### Application

Youtube Music

### Issue

When I was listening to a YouTube playlist via YT Music (patched via ReVanced), I noticed after 23-30 minutes that my phone (Pixel 6 Pro) was hot (around 95 degrees). After investigating with my Pi-Hole, I noticed that Google's ad servers (googleadservers & doubleclick) were getting pinged by YouTube Music every 2 seconds.

Just played a playlist of uploaded music on the app earlier today, and noticed it was pinging the ad servers as badly.

### Patch

I would like for YouTube to not ping ad servers to not be pinged or at the very least limited (kind of like ad blocker).

### Motivation

I would like to listen to YouTube Music for longer than 20 minutes without my phone feeling hot to the touch. Not certain if anyone else is having this issue with their phone using the Patch.

I don't know if this is possible without breaking YT Music, or that this goes away after paying for Premium. But I d

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Pinging ad servers does not cause heating issues. Pixel phones heating up is an issue caused by Pixel phones.

**Comment by NMinker** [comment]
Thanks for the info.
