### ISSUE TITLE
bug: Patches for YouTube Music error on 6.45.54+

### ISSUE THREAD

**Issue by UpFromTheShadows** [ReVanced/revanced-patches#2915]
### Bug description

**Quick rundown**

Attempting to patch YouTube music on versions 6.45.54+ results in errors (logs attached in a paste bin here https://pastebin.com/AgMPtx0M)

**Steps to reproduce**

1) Download a youtube music apk with version 6.45.54 or newer
2) Patch with default patches
3) Behold the errors

### Error logs
(Manager logs): 
https://pastebin.com/AgMPtx0M

### Solution

Fixing compatibility with the latest versions or changing the recommended version to the last working version

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by feralfenrir** [comment]
Changing the GMSCore from Vanced to Revanced, I got errors not in the Background Playback module but the Shuffle Module.

Log: https://pastebin.com/swBpbRX7
