### ISSUE TITLE
bug: The application does not show dev patches

### ISSUE THREAD

**Issue by waesd** [ReVanced/revanced-patches#2917]
### Bug description

The application does not show dev patches

### Error logs

```shell
not error
```

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Thats not a bug.

**Comment by waesd** [comment]
How do I make the app appear dev patches?

**Comment by waesd** [comment]
> If you want to use dev release, you have to patch using a computer with command prompt and the CLI tools.
> 
> Currently Manager can only patch main (regular) releases.
> 
> There is talk of adding support to Manager to patch using the dev release.
 thank you bro
dev Patches appear well on rvx , but I would like to use them on revanced 
I hope they add in the future , or add feature When you click on the patch number at the top of the application, a list of all existing patch versions opens and you choose from them
