### ISSUE TITLE
feat: The sleep timer doesn't work when the screen is turned off 

### ISSUE THREAD

**Issue by ortonormal2007** [ReVanced/revanced-patches#2917]
### Application

YouTube Vanced

### Issue

The sleep timer in the application (general -> remind me to take a break) doesn't work when the phone screen is turned off.

### Patch

Set up the timer in the settings menu.
Play some video in background.
Turn off the screen.
At the designated time nothing happens: video playback continues.
The alternation should make the feature work like ot does in YouTube Vanced Original and YouTube Premium 

### Motivation

The application must be fully functional, like the premium version. And this feature is useful when a user listens to some content right before falling asleep, for example, for traffic-saving.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Thats a bug not a feature request.

**Comment by ortonormal2007** [comment]
How do I get a log output on my phone?
