### ISSUE TITLE
bug(YouTube): Sleep timer does not work when the screen is turned off

### ISSUE THREAD

**Issue by ortonormal2007** [ReVanced/revanced-patches#2918]
### Type

Error while patching

### Bug description

The sleep timer in the application (general -> remind me to take a break) doesn't work when the phone screen is turned off.

### Steps to reproduce

Set up the timer in the settings menu.
Play some video in background.
Turn off the screen.
At the designated time nothing happens: video playback continues.
The alternation should make the feature work like ot does in YouTube Vanced Original and YouTube Premium

### Relevant log output

```shell
I currently do not have access to my computer to read the logs.
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Exclude patches until the error is gone, report back which one caused it.

**Comment by ortonormal2007** [comment]
I had unchecked off all the patches except the background playback and the microg support (because I haven't root), but the sleep timer didn't work in the screen locked, as it was before.

> Exclude patches until the error is gone, report back which one caused it.

I had unchecked off all the patches except the background playback and the microg support (because I haven't root), but the sleep timer didn't work in the screen locked, as it was before.
