### ISSUE TITLE
feat: No Trackers

### ISSUE THREAD

**Issue by Brytonggg** [ReVanced/revanced-patches#2919]
### Application

Youtube revanced

### Issue

Removing trackers

### Patch

A patch where you can remove all trackers from youtube

### Motivation

The app will now have more security , faster speeds
And a better title now for user with privacy needs 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Practically not possible, it uses Google services.

**Comment by Brytonggg** [comment]
@oSumAtrIX but the invidous website has done and also piped aswell

**Comment by oSumAtrIX** [comment]
Those are not YouTube.
