### ISSUE TITLE
Duolingo's patch doesn't work

### ISSUE THREAD

**Issue by DarkSkull91** [ReVanced/revanced-patches#2920]
### Type

Error at runtime

### Bug description

I installed the latest version of Duolingo (5.118.2) and as soon as I start the app, it crashes. I use both the root and not-root installation because my OnePlus 9 Pro is rooted but the result is always the same.

### Steps to reproduce

1. Download Duolingo
2. Apply the patch from ReVanced
3. Start the application

### Relevant log output

```shell
I have any output with the command above launched in termux
```

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [x] I filled out all of the requested information in this issue properly.

**Comment by johnconner122** [comment]
#2892

**Comment by zzzzz-attachment** [comment]
not working tested today on version 5.121.4

**Comment by wywywywy** [comment]
> It's fixed on the dev release. Patch using computer and command line tools, or wait until dev becomes regular release.

Is it though? The patch has just been removed from dev https://github.com/ReVanced/revanced-patches/commit/b4b9746361b5435b9d9429ad065e53364c51904a
