### ISSUE TITLE
bug (YouTube - Hide layout components): Hide community posts does not work

### ISSUE THREAD

**Issue by Bceez** [ReVanced/revanced-patches#2920]
### Bug description

Community posts still appear when scrolling through the home or subscription feed.

The easiest way to reproduce this issue is to go to the subscriptions tab and selecting "Posts" in the filter bar.

### Solution

Adding "image_post_root.eml" to custom filters and having "Hide community posts" turned on in general layout settings solves this issue.

### Additional context

This only happens on some accounts due to A/B Testing

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by Bceez** [comment]
> What is the full log entry that contains `image_post_root.eml`?

I hope this is correct:

`03-27 10:18:43.698 16921 17118 D revanced: LithoFilterPatch: Searching ID: null Path: image_post_root.eml|50df27c267209593|CellType|image_post.eml|4a0fb346ee032001|ContainerType|ContainerType|post_engagement_toolbar.eml|8c4a95f016c2c6b0|ContainerType|post_like_dislike.eml|eb7b0c13b9c67220|ContainerType|post_dislike_button.eml|8f54d1baa8f82b0d|ImageType| BufferStrings: id.ui.backstage.dislike_buttonÔØÖDislikeÔØÖ8EiRVZ2t4blBpRER2SDl0Z0dOTTBzazFjU0F4M3pkMEFQNEFudnIgQCgBÔØÖ8EiRVZ2t4blBpRER2SDl0Z0dOTTBzazFjU0F4M3pkMEFQNEFudnIgQCgBÔØÖ^CAQaJFVna3huUGlERHZIOXRnR05NMHNrMWNTQXgzemQwQVA0QW52cjgAWhhVQzhESVU1NmpGMWV2NWM2dWJHXzJJRVE%3DÔØÖyt_outline_thumb_down_black_24ÔØÖ`

**Comment by oSumAtrIX** [comment]
Please add image_post_root to the custom filter to check if it hides the community posts

**Comment by Bceez** [comment]
Adding "image_post_root" hides all community posts but only when "Hide community posts" in YouTube ReVanced settings is turned on aswell.

Adding "image_post_root" but having "Hide community posts" disabled in YouTube ReVanced settings still loads 2 community posts when going to the subscription tab and selecting "Posts" in the filter bar.

Only turning on "Hide community posts" doesn't seem to do anything

**Comment by Bceez** [comment]
> @Bceez try to add this to custom filter
> ```
> image_post_root
> post_base_wrapper
> ```
> If i add this to filter all comunity post disappears. The toggle `Hide community posts` in settings dont work.

Seems to work perfectly
