### ISSUE TITLE
bug: Patched YouTube is stuck on splash screen

### ISSUE THREAD

**Issue by AEleven-GitHub** [ReVanced/revanced-patches#2921]
### Bug description

After updating from a previously patched version of YouTube to the most recently suggested patched version of YouTube, even while being successful, the YouTube app doesn't progress past the start screen.

### Additional context

https://www.reddit.com/r/revancedapp/s/LVMk1FDYG9

I would include more details but I don't know what to include. 

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Please add crashlogs using logcat and more details as requested in the issue template such as versions and steps
