### ISSUE TITLE
feat: (YouTube / YouTube Music): Show a tost if original app not instaled

### ISSUE THREAD

**Issue by MarcaDian** [ReVanced/revanced-patches#2922]
### Feature description

Hello, In response to this PR https://github.com/ReVanced/revanced-patches/pull/2907

After migrating to the new ReVanced GmsCore vendor, many users encountered an application crash after installing ReVanced YouTube / ReVanced YouTube Music
I propose to check for installed versions of the original YouTube and YouTube Music applications, and if they are not installed, then show a toast asking you to install it.

Here's an explanation why this happens https://github.com/ReVanced/revanced-patches/pull/2907#issuecomment-2020300362

### Motivation

This will prevent users from misunderstanding why ReVanced Youtube or/and ReVanced Youtube Music crashes without any notification.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Unless I completely forgot pushing the changes, I have added the same hook that is present on YouTube to YouTube Music as well.

**Comment by oSumAtrIX** [comment]
Yes, seems to be present: https://github.com/ReVanced/revanced-patches/blob/dev/src/main/kotlin/app/revanced/patches/shared/misc/gms/BaseGmsCoreSupportPatch.kt

The integrations should probably move to "shared", seems I forgot to do that, but in theory the same behaviour as seen on YouTube should occur in YouTube Music. If not, a bug report should be opened.
