### ISSUE TITLE
bug(Twitch): Proxy server fails for embedded ads

### ISSUE THREAD

**Issue by kazimmt** [ReVanced/revanced-patches#2924]
### Type

Error at runtime

### Bug description

Twitch has a patch to block embeded ads with TTV Lol proxy & Purple adblock proxy
But both fails.

### Steps to reproduce

- Patch twitch with Block embedded ads patch
- Install Twitch ReVanced
- Run stream

### Relevant log output

```shell
‍
```

### Screenshots or videos

![Screenshot_20230903-012305_Twitch](https://github.com/ReVanced/revanced-patches/assets/82371061/25afc6fd-095f-4d5a-adac-0fc3dff02151)
![Screenshot_20230903-012158_Twitch](https://github.com/ReVanced/revanced-patches/assets/82371061/1a4a5bc2-68c7-4e99-a9be-73eb19dfce7e)

### Solution

Change the proxy to a working one or add field so we can manually type any working server.

Refer to: https://github.com/ReVanced/revanced-patches/issues/2681

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
https://github.com/ReVanced/revanced-patches/issues/2681

**Comment by kazimmt** [comment]
Aren't both different issue?

**Comment by oSumAtrIX** [comment]
No, both issues explain that the proxy fails and suggest to add new ones
