### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by Susheatttttt** [ReVanced/revanced-patches#2927]
### Bug description

Hello, when I replie to a comment or heart a replie, the interaction is visible for me only.

### Additional context

I use the recommended version for patching.

### Acknowledgements

- [x] This issue is not a duplicate of an existing bug report.
- [ ] I have chosen an appropriate title.
- [ ] All requested information has been provided properly.

**Comment by Susheatttttt** [comment]
How can I edit the title ...

**Comment by oSumAtrIX** [comment]
Include all requested informations properly in a new issue
