### ISSUE TITLE
feat(grindr): Lack of transparency in the rejection of #2915 

### ISSUE THREAD

**Issue by Slenderman00** [ReVanced/revanced-patches#2927]
### Application

Grindr is a dating app mainly used by the LGBTQ+ community. This is a large yet fragile group, illustrated by the fact that being queer is considered illegal inn 64 countries – with the death penalty being a reality in 11 of those.

#2915 was closed due to "I've received a warning that Grindr is banned in some countries". I find the lack of transparency in this decision disturbing.

To adress these concerns:
1. Why was this warning not posted as a comment on the request?
2. Why was no issue created around this?

Furthermore, here are some other apps that are being patched that are also banned:
- grindr: Iran, Crimea, Syria, Pakistan, Cuba, North Korea, Sudan
- instagram: China, Russia, Belarus, Iran, Uganda, North Korea, Turkmenistan
- messenger: China, Bhutan, Nepal, Pakistan, Iran, North Korea, Cuba, Syria, Turkmenistan
- youtube music: China, Iran, North Korea, Sudan, South Sudan, Tajikistan
- reddit: China, Russia, Indonesia
- spotify: China, Ethiopia, Libya, Somalia, Sudan, Iran, Iraq, Myanmar, Cuba, Venezuela
- tiktok: Afghanistan, India, Somalia
- twitch: China
- twitter: China, Iran, Myanmar, North Korea, Russia, Turkmenistan, Uzbekistan
- youtube: China, Iran, North Korea, Sudan, South Sudan, Tajikistan

### Issue

-

### Patch

-

### Motivation

-

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [ ] I have written a short but informative title.
- [ ] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
The issue was not closed due what you've mentioned in this issue. Please correct this mistake.

Additionally make sure all issues are resolved in the PR and make sure to explain, why so many fingeprints are necessary, as already asked to in the PR.

**Comment by Slenderman00** [comment]
"I've received a **warning** that Grindr is banned in some countries, and even though ReVanced has no source of Grindr, merging this could affect ReVanced, too. Due to that and the complexity of the patch, I'll close this. If you intend to merge, please open an issue beforehand."

**Comment by mlnrDev** [comment]
feel free to mark this as offtopic, but Twitch isn't banned in Slovakia :) there was one incident which resulted in 1 ISP temporarily blocking access to the website

**Comment by Slenderman00** [comment]
Thank you for the correction.

**Comment by oSumAtrIX** [comment]
Regarding the questions in this issue, the warning was issued through a mail which is why there is no issue comment, previous to that I wasn't even aware of what Grindr was.  Why the sender has decided to send a mail is in their discretion

**Comment by Slenderman00** [comment]
What was this anonymous third party`s argument? it is hard to defend my stance when i can`t see the email...

**Comment by oSumAtrIX** [comment]
There was no particular argument, they just warned that it could also affect ReVanced as a whole regardless of it not having source of the original app. Again, you are looking at the wrong reason why the PR was dismissed.

**Comment by Slenderman00** [comment]
I will resolve the other issues. But i can`t resolve Grindr being banned with some refactoring. If i rewrite the patch to a sufficient degree and open a new request will it be rejected on the basis that Grindr is illegal?

**Comment by oSumAtrIX** [comment]
No, there is no particular problem with the app being banned. Make sure to clarify the complexity of the patch before working on it in a new issue as it is offtopic to the current one.

**Comment by Jucasan22** [comment]
Oh gosh this guy it's a genius
