### ISSUE TITLE
bug: streaming freezing

### ISSUE THREAD

**Issue by Danyele980** [ReVanced/revanced-patches#2930]
### Bug description

Streaming stops after about 30 seconds 

https://github.com/ReVanced/revanced-patches/assets/165220500/f9501dcd-4c18-489b-a14e-58c750c8736d

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [ ] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Provide all requested informations properly.

**Comment by Danyele980** [comment]
What did I do wrong? I can provide logcat now

**Comment by misbk** [comment]
I had the exact same issue after applying the latest ReVanced patches. The issue persisted even after updating ReVanced GmsCore to the latest version. Then, I tried removing my account from ReVanced GmsCore (in Android settings) and uninstalling ReVanced GmsCore. After a fresh install of ReVanced GmsCore and signing in, the playback seems to work properly.

**Comment by Danyele980** [comment]
> Molto probabilmente hai installato GmsCore sbagliato o stai utilizzando una vecchia app con patch.
> 
> Utilizza l'ultima versione Gms di ReVanced.

I'm using the latest version of both gms core and the patched app 
[28_03-00-31-03_255.log](https://github.com/ReVanced/revanced-patches/files/14784606/28_03-00-31-03_255.log)
