### ISSUE TITLE
feat: add option to disable other types of pop-up cards (like link cards)

### ISSUE THREAD

**Issue by daveout** [ReVanced/revanced-patches#2932]
### Application

YouTube

### Issue

Currently there's an option to disable infocards that contain text notes, but there are  still other types of distracting info cards (with links and shortcuts) that are displayed. I believe they're called video, playlist, channel and link cards. (see https://support.google.com/youtube/answer/6140493?hl=en&co=GENIE.Platform%3DDesktop)

Example 1: pop appears at 0:30 (mobile only), see screenshot:
https://www.youtube.com/watch?v=pqCVMRcj_bc
![Screenshot_20230904-075455](https://github.com/ReVanced/revanced-patches/assets/54579499/16532604-0664-4ebc-be82-66a5de163252)

Example 2: pop appears at 2:47 (mobile only), see screenshot:
https://www.youtube.com/watch?v=gvzC8MmC850
![Screenshot_20230904-075352](https://github.com/ReVanced/revanced-patches/assets/54579499/e5837397-a046-4258-a6b6-de78451f337a)

### Patch

Add option to disable other types of pop-up cards (like link cards)

### Motivation

Less distractions and annoyances. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
That is an info card, open a bug report.
