### ISSUE TITLE
bug(YouTube - hide info cards): Some info cards still show up (a/b test)

### ISSUE THREAD

**Issue by daveout** [ReVanced/revanced-patches#2933]
### Bug description

Example 1: pop-up appears at 0:30 (mobile only), see screenshot:
https://www.youtube.com/watch?v=pqCVMRcj_bc
![265442969-16532604-0664-4ebc-be82-66a5de163252](https://github.com/ReVanced/revanced-patches/assets/54579499/5f860aa9-78b7-46d1-9bb5-3318d48ec0bf)

Example 2: pop-up appears at 2:47 (mobile only), see screenshot:
https://www.youtube.com/watch?v=gvzC8MmC850
![265443271-e5837397-a046-4258-a6b6-de78451f337a](https://github.com/ReVanced/revanced-patches/assets/54579499/c2444c31-0f06-4125-8667-f22cc2bd503c)

### Steps to reproduce

see bug description above.

### Solution

fix info card visibility

**Comment by Domiiniik** [comment]
Can confirm, new bug, it used to work and remain hidden in order reVanced versions, really annoying popup

**Comment by daveout** [comment]
Yep they don't show up when in incognito mode. (both with app signature spoofing turned on and off).

**Comment by daveout** [comment]
It worked perfectly. Thank you so much!

**Comment by n1cKz1** [comment]
So i was about to create a new issue as i experienced the same thing then i found this. The component name is apparently info_card_teaser_overlay.eml
Blocking that seems to do the job

**Comment by HeroGalak** [comment]
> So i was about to create a new issue as i experienced the same thing before i found this one. The component name is apparently info_card_teaser_overlay.eml
> Blocking that seems to do the job.

Yes but it blocks also the related video panel when you swipe up in landscape

**Comment by HeroGalak** [comment]
I think I've found the component name to block only info cards.

`info_card_teaser_overlay.eml-js-canary`

**Comment by HeroGalak** [comment]
> But what is the entire log string?  The hide info cards patch can make additional specific checks that custom filter cannot.

I'm not so experienced with revanced development, but I can leave here the logs.

These are the logs when an infocard appears (no custom filtered):

`27.09 11:25:42.710 10467 16992 16992 app.revanced.android.youtube D/revanced: LithoFilterPatch: Searching ID: info_card_teaser_overlay.eml-js-canary|b5143e0565b8b42a Path: info_card_teaser_overlay.eml-js-canary|b5143e0565b8b42a|ContainerType| 27.09 11:25:42.711 10467 16992 16992 app.revanced.android.youtube D/revanced: LithoFilterPatch: Searching ID: null Path: info_card_teaser_overlay.eml-js-canary|b5143e0565b8b42a|ContainerType|ContainerType| 27.09 11:25:42.712 10467 16992 16992 app.revanced.android.youtube D/revanced: LithoFilterPatch: Searching ID: null Path: info_card_teaser_overlay.eml-js-canary|b5143e0565b8b42a|ContainerType|ContainerType|ContainerType| 27.09 11:25:42.713 10467 16992 16992 app.revanced.android.youtube D/revanced: LithoFilterPatch: Searching ID: null Path: info_card_teaser_overlay.eml-js-canary|b5143e0565b8b42a|ContainerType|ContainerType|ContainerType|TextType| 27.09 11:25:42.714 10467 16992 16992 app.revanced.android.youtube D/revanced: LithoFilterPatch: Searching ID: null Path: info_card_teaser_overlay.eml-js-canary|b5143e0565b8b42a|ContainerType|ContainerType|ContainerType| 27.09 11:25:42.715 10467 16992 16992 app.revanced.android.youtube D/revanced: LithoFilterPatch: Searching ID: null Path: info_card_teaser_overlay.eml-js-canary|b5143e0565b8b42a|ContainerType|ContainerType|ImageType| 27.09 11:25:42.719 10467 16992 16992 app.revanced.android.youtube D/revanced: LithoFilterPatch: Searching ID: null Path: info_card_teaser_overlay.eml-js-canary|b5143e0565b8b42a|ContainerType|ContainerType|ContainerType|avatar.eml|7170e708ac9dccd7|ImageType|`
