### ISSUE TITLE
Bug (youtube): The Hide chapters in video description setting also hides the chapters in expandable chips beneath videos

### ISSUE THREAD

**Issue by KobeW50** [ReVanced/revanced-patches#2935]
### Type

Error at runtime

### Bug description

When the Hide chapters in video description toggle is enabled (near the top of the layout settings) it causes the chapters to be hidden from the expandable chips beneath videos.

### Steps to reproduce

1. Go to Settings > ReVanced > Layout > Hide chapters in video description, On
2. Go to Settings > ReVanced > Layout > Hide the expandable chip under videos, Off
3. Search for a video that will have chapters in the expandable chip (such as a video from JerryRigEverything)

The chip will be empty

4. Now go to Settings > ReVanced > Layout > Hide chapters in video description, Off
5. Repeat step 3

The chip will now have contents

### Relevant log output

```shell
NA
```

### Screenshots or videos

How it should be

![VideoCapture_20230904-174037](https://github.com/ReVanced/revanced-patches/assets/84587632/7ace93ac-61da-44a8-8046-0ab4667b1a5d)

How it looks when the chapters in video descriptions are hidden

![VideoCapture_20230904-174052](https://github.com/ReVanced/revanced-patches/assets/84587632/e73b30f6-a585-4145-9169-a67d3a47f8a8)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Domiiniik** [comment]
Can confirm

**Comment by johnconner122** [comment]
Also if you hide the expandable chips, distance between videos thumbnails is more than default distance for other videos.

**Comment by oSumAtrIX** [comment]
Is this still a problem? I can not see those chapters

**Comment by KobeW50** [comment]
> Is this still a problem? I can not see those chapters

Yes, I just tested with the latest public patches

**Comment by oSumAtrIX** [comment]
Please enable debug logging and grep for `inline_expander`. Send the log output for both views.

**Comment by KobeW50** [comment]
> Please enable debug logging and grep for `inline_expander`. Send the log output for both views.

I hope I followed the instructions correctly. The logs only start immediately before opening the expandable chip.

With description chapters shown:

![logcat_10-01-2023_21-31-24.txt](https://github.com/ReVanced/revanced-patches/files/12778820/logcat_10-01-2023_21-31-24.txt)

With description chapters hidden:

![logcat_10-01-2023_21-32-34.txt](https://github.com/ReVanced/revanced-patches/files/12778825/logcat_10-01-2023_21-32-34.txt)

**Comment by oSumAtrIX** [comment]
Looks good, that can be fixed by checking for the search context

**Comment by oSumAtrIX** [comment]
@KobeW50 Please try the custom filter `expandable_metadata`. Make sure to check if it hides anything that should not be hidden. It should only hide chapters everywhere.

**Comment by KobeW50** [comment]
> @KobeW50 Please try the custom filter `expandable_metadata`. Make sure to check if it hides anything that should not be hidden. It should only hide chapters everywhere.

It hides all expandable chips under videos in feed.

It also hides the contents of this product commission notice when a video is opened

![SmartSelect_20231002_130127_YouTube.jpg](https://github.com/ReVanced/revanced-patches/assets/84587632/1d4546d6-0c3a-4905-b664-5f4fdb754c9c)

The white screenshot is how the product notice looks in stock YT

![SmartSelect_20231002_130231_YouTube.jpg](https://github.com/ReVanced/revanced-patches/assets/84587632/0138204b-19b5-4b7c-b896-45fdf5218104)

The `expandable_metadata` filter does not hide the chapters in the video description

![SmartSelect_20231002_130803.jpg](https://github.com/ReVanced/revanced-patches/assets/84587632/3149b2fe-63f0-4387-8c0a-77d9f0e4dc86)

**Comment by KobeW50** [comment]
@oSumAtrIX I made a mistake. The custom filter you gave has nothing to do with the product commission notices that I mentioned in my previous comment.

**Comment by oSumAtrIX** [comment]
Please repeat then.

**Comment by KobeW50** [comment]
> Please repeat then.

I retested, if that is what you mean.

All expandable chips under videos in feed are still hidden.

The chapters in the video descriptions are still not hidden.

**Comment by oSumAtrIX** [comment]
Yes, this was my intention. Can you log the chapters component path builder using logcat?

**Comment by KobeW50** [comment]
I don't know how

**Comment by KobeW50** [comment]
Would it be something in this log?

https://github.com/ReVanced/revanced-patches/assets/84587632/40dd8910-12d0-459a-9b60-90861ef8e859

**Comment by oSumAtrIX** [comment]
Maybe `macro_markers_carousel`?

**Comment by KobeW50** [comment]
> Maybe `macro_markers_carousel`?

This hides the chapters in description, but also hides the contents of the expandable chips

![Screenshot_20231002_211820.jpg](https://github.com/ReVanced/revanced-patches/assets/84587632/2d6f21b6-b3a0-41f7-99d1-c6cd4944465b)

**Comment by oSumAtrIX** [comment]
It is possible to prevent it from being hidden in the feed, but I'll change the patch to hide both for simplicity.

**Comment by oSumAtrIX** [comment]
![image](https://github.com/ReVanced/revanced-patches/assets/13122796/9ad81d5a-bf37-450a-906c-4169d4f51454)

Seems like both are already present. Check if turning both on works.

**Comment by oSumAtrIX** [comment]
Fixed with https://[github.com/revanced/revanced-integrations/commit/bedb02e4f6122f3dcdc106648648eec4d6a3cbe5](https://github.com/revanced/revanced-integrations/commit/bedb02e4f6122f3dcdc106648648eec4d6a3cbe5)

**Comment by KobeW50** [comment]
Thank you

**Comment by johnconner122** [comment]
> > Maybe `macro_markers_carousel`?
> 
> This hides the chapters in description, but also hides the contents of the expandable chips
> 
> ![Screenshot_20231002_211820.jpg](https://user-images.githubusercontent.com/84587632/272122016-2d6f21b6-b3a0-41f7-99d1-c6cd4944465b.jpg)

@oSumAtrIX we can check for player type, so only chapters in description are hidden.

**Comment by johnconner122** [comment]
> > > Maybe `macro_markers_carousel`?
> > 
> > 
> > This hides the chapters in description, but also hides the contents of the expandable chips
> > ![Screenshot_20231002_211820.jpg](https://user-images.githubusercontent.com/84587632/272122016-2d6f21b6-b3a0-41f7-99d1-c6cd4944465b.jpg)
> 
> @oSumAtrIX we can check for `PlayerType`, so only chapters in description are hidden.
