### ISSUE TITLE
bug: (Youtube Music: Hide "Get Music Premium" lable) patch is not hiding the label

### ISSUE THREAD

**Issue by CoolCooler0** [ReVanced/revanced-patches#2939]
### Bug description

The Youtube Music patch Hide: "Get Music Premium" label is not working. The version that is be using is the latest, v6.45.54.
![Screenshot_20240328_090254_YouTube Music](https://github.com/ReVanced/revanced-patches/assets/136742821/f167bc06-5a4d-4899-ab6b-7463d1b4c470)
![Screenshot_20240328_090259_YouTube Music](https://github.com/ReVanced/revanced-patches/assets/136742821/d8a055c2-a577-4ce5-89f5-214642dbfadf)

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
The red label is hidden as advertised
