### ISSUE TITLE
feat: YouTube Autoplay Sleep Timer

### ISSUE THREAD

**Issue by bilboswaggins69** [ReVanced/revanced-patches#2941]
### Feature description

A feature similar to Spotify, where you can have a timer after which playback is stopped. Allow the user to select how long they would like videos to automatically play.

### Motivation

This would allow videos to be played continuously without the user having to stop it manually. This would be helpful for those who use videos to fall asleep but do not want they're feed ruined.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Sleep timer exists as an external app on Play store
