### ISSUE TITLE
bug: (Youtube): Some community posts don't expand when pressing read more

### ISSUE THREAD

**Issue by JoshMayBalGitHub** [ReVanced/revanced-patches#2944]
### Bug description

For some reason, certain community posts don't expand when pressing the read more, it happens on more often on newer posts (?).

I say certain, because some past community posts seem to work just fine. I have also checked default youtube app, it's fine.

I use YT ReVanced 19.09.37 btw.

### Solution

I used tablet layout to view the bugged community posts, I have also tried hiding the `image_post_root` that seemed to hide the problematic posts, it's just that, it hides them, so I can't view them.

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
![Screenshot_20240328-160834](https://github.com/ReVanced/revanced-patches/assets/13122796/b8e35999-e3bc-42dc-b655-4a7665b41e9b)

Follow this and report back

**Comment by JoshMayBalGitHub** [comment]
It fixed itself, weird... Anyways this was already resolved a week ago, anyway.. I'll just reopen if necessary..
