### ISSUE TITLE
feat: (YouTube) Hide the feed of suggested videos under a playing video

### ISSUE THREAD

**Issue by Vebrex** [ReVanced/revanced-patches#2945]
### Feature description

Application Name: YouTube
Feature Description: An option to hide or disable the feed under a video that is being played. This feed is under the comments section. In the photo, it's in the red box.
![Feature request](https://github.com/ReVanced/revanced-patches/assets/121370666/f20e97f7-ae59-4012-82df-4747188d6736)

### Motivation

This feature would allow users limit the videos that are displayed to those from the channels they've subscribed to. This significantly reduces the time wasted in watching videos that were suggested by the algorithm, and allows users be intentional with their use of the app. Thanks a lot in advance.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Swipe down to enter fullscreen, hides the recommendations
