### ISSUE TITLE
Revanced Apps is not oppening

### ISSUE THREAD

**Issue by Walter-Correa** [ReVanced/revanced-patches#2945]
### Type

Error at runtime

### Bug description

Lastest version of YouTube Revanced and  Extended is not oppening after updating to 18.31.40.

Android, Xiaomi Poco X3 Pro

### Steps to reproduce

Just updated from Revanced Manager

### Relevant log output

```shell
Just show the apo icon in the white background and close.
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [ ] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Irreproducible steps.

**Comment by Walter-Correa** [comment]
> Irreproducible steps/ You are using the wrong version.

What??? 
So the lastest version of YouTube Revanced Extended 18.31.40 from 5 September 05 is the wrong version? 

Am I in the wrong multiverse?

**Comment by oSumAtrIX** [comment]
This is ReVanced.

**Comment by Walter-Correa** [comment]
> This is ReVanced not ReVanced extended.

So my report is insignificant just because I posted it in the wrong repository?  Anyway I downgraded to 18.30.37. Thanks!
