### ISSUE TITLE
Custom Branding issue

### ISSUE THREAD

**Issue by nightznero** [ReVanced/revanced-patches#2946]
### Bug description

Helloz,
_`Custom Branding Patch`_ doesn't work at its should.
Logo is set to normal yt and ReVanced still is applied
(Video is compressed to fit GitHub but everything is visable i guess)
https://github.com/ReVanced/revanced-patches/assets/61750641/2ac6c656-2410-453e-be48-dfda7a5dc368

### Error logs

```shell
no errors
```

### Solution

Switch to YT default icon

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [ ] All requested information has been provided properly.

**Comment by nightznero** [comment]
> In the video you picked only one option for custom branding (use stock app name), and did not pick a custom icon option.
> 
> You picked "do nothing", and instead should not include the patch at all to achieve that.

Yup,bcs there is only option to use _Revanced logo_ or _Custom Value_
So if i dont choose rv logo why rv logo is selected? For what reason no option and rv logo option results the same? o.O

**Comment by oSumAtrIX** [comment]
Because ReVanced Manager doesn't support null option values. An issue for that is open
