### ISSUE TITLE
bug(YouTube): Client spoof patch not working with 4.4.0 patches

### ISSUE THREAD

**Issue by mogzol** [ReVanced/revanced-patches#2948]
### Bug description

With the 4.4.0 patches, the client spoof patch isn't working. It might not even be applying? There is no "Spoof app signature" section in the ReVanced > Misc options.

I'm seeing this issue with both the app patched by ReVanced Manager, and the app patched with the CLI. For example, I'm using this CLI command to patch the app:

```
java -jar revanced-cli-4.5.0-all.jar patch -b revanced-patches-4.4.0.jar -m revanced-integrations-1.5.0.apk com.google.android.youtube_19.09.37.apk
```

And after installing the patched APK, the "Spoof app signature" section doesn't show up in the ReVanced settings and videos only play for 30 seconds.

If I switch back to the 4.3.0 patches, with this command:

```
java -jar revanced-cli-4.5.0-all.jar patch -b revanced-patches-4.3.0.jar -m revanced-integrations-1.4.0.apk com.google.android.youtube_19.04.37.apk
```

Then install that patched APK, the "Spoof app signature" section does show up and videos play properly.

Note that I am using the default patches in both cases, I'm not explicitly including or excluding anything.

### Solution

Downgrading back to the 4.3.0 patches fixes the issue.

### Additional context

I also tried using the 19.04.38 apk with the 4.4.0 patches and get the same issue, so it seems to be an issue with the patches and not the youtube version.

Also not sure if there are any specific error logs to include since there isn't really an error, the patch just doesn't seem to be applying/working. But let me know if there's any other information I can provide.

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
The signature spoof patch has been removed as it is not necessary anymore.

**Comment by mogzol** [comment]
> The signature spoof patch has been removed as it is not necessary anymore.

Then why do videos only play for 30 seconds?

**Comment by mogzol** [comment]
I am 

> Uninstall your old MicroG/gms and use ReVanced Gms https://github.com/ReVanced/GmsCore/releases
> 
> If you need further help use the support channels listed on http://ReVanced.app

I am using the latest ReVanced Gms, I am still getting the issue. In the Gms self-check settings the "System spoofs signature" check is failing. Should that be passing? It looks like I need a custom ROM to support it? I am on the stock ROM for my phone, I don't have root.
