### ISSUE TITLE
Video Freezing at around 50 seconds of playback

### ISSUE THREAD

**Issue by GreenDiscord** [ReVanced/revanced-patches#2950]
### Bug description

I am on the latest version of ReVanced MicroG, all patches are updated and the manager is fully updated.

I'll watch any video and my video will freeze and continue buffering, not starting to play again, I have to close the video and reopen until it happens again 50 seconds later.

I am on mobile and don't know how to get the logs from the shell, please enlighten me if you know.

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by GreenDiscord** [comment]
Sorry

**Comment by euro2** [comment]
I have the same issue. Latest YouTube, latest GMScore. All the samsung battery toggles set to disabled. Still it starts buffering to never recover. I guess at the position of an ad?

**Comment by victante** [comment]
Was happening to me too, I'm on the latest recommended version (19.09.37), latest patches, but using a GMScore fork called Micro-RE.

Installed GMScore from Revanced repositories and now it's solved!
