### ISSUE TITLE
bug: Shorts comments not showing up

### ISSUE THREAD

**Issue by Rijsouw** [ReVanced/revanced-patches#2958]
### Type

Other

### Bug description

I found it while watching shorts and the comments not showing up. There is just a black screen most of the time instead of a comment sections.

### Steps to reproduce

Manager: v1.9.5
YT version: v.18.32.39

### Relevant log output

```shell
I don't have a log output
```

### Screenshots or videos

![Screenshot_2023-09-08-13-25-41-48_64ef5fc2000c1caa954c114bb372e1d5](https://github.com/ReVanced/revanced-patches/assets/50184473/f9af1de0-0225-4530-968e-37ed40b9920a)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Exclude patches until the error is gone, report back which one caused it
