### ISSUE TITLE
feat: nzb360

### ISSUE THREAD

**Issue by aicynide** [ReVanced/revanced-patches#2961]
### Application

nzb360

### Issue

Paywall

### Patch

Unlock Premium

### Motivation

nzb360 dev is rude

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
I am rude too, not a motivation.
