### ISSUE TITLE
Disable 60fps

### ISSUE THREAD

**Issue by gjgok** [ReVanced/revanced-patches#2962]
### Application

Youtube revanced.

### Issue

Improve low spec terminal operation.

### Patch

Added the ability to disable 60fps from the YouTube video quality menu. （Example: 720p60fps → 720p）

### Motivation

Improve low spec terminal operation.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
#909
