### ISSUE TITLE
bug(youtube/ryd): Dislikes may not be visible when using non English language if compact like button is enabled

### ISSUE THREAD

**Issue by n1cKz1** [ReVanced/revanced-patches#2962]
### Bug description

Basically this https://github.com/ReVanced/revanced-patches/issues/44 but the difference is now it only occurs if compact like button is enabled

![Screenshot_2024-04-01-02-35-51-652-edit_app revanced android youtube](https://github.com/ReVanced/revanced-patches/assets/107653639/bd09cb2d-4ec4-4b50-9201-59ca18ba809c)

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by n1cKz1** [comment]
Screenshot added

> Is this when using Greek?

Yes

**Comment by 2trvl** [comment]
I use the application in English and there is also no dislike counter. The player loads immediately upon opening, but the rest of the interface can freeze for up to 3 seconds.
![SmartSelect_20240401_182724_YouTube](https://github.com/ReVanced/revanced-patches/assets/38960745/362195b0-595c-4a14-9a5c-07ee1fcebce3)
