### ISSUE TITLE
feat: unlock premium for ticktick

### ISSUE THREAD

**Issue by jellie-bean** [ReVanced/revanced-patches#2970]
### Application

Ticktick

### Issue

Currently the patches unlock some themes, but does not unlock premium 

### Patch

Ticktick premium unlock

### Motivation

Ticktick is already patchable but does not unlock premium features. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
#1132
