### ISSUE TITLE
feat: youtube Spoof app signature options

### ISSUE THREAD

**Issue by yonggamer** [ReVanced/revanced-patches#2970]
### Feature description

youtube
com.google.android.youtube 19.09.37
![1](https://github.com/ReVanced/revanced-patches/assets/24843208/472659f4-f99d-48b3-93bf-906a9aa2eba6)
![2](https://github.com/ReVanced/revanced-patches/assets/24843208/31973b93-404e-4d8b-a19e-7a7d5c7fcb00)

### Motivation

i miss it

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [ ] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Acknowledgements not met
