### ISSUE TITLE
Youtube shorts scrolling option

### ISSUE THREAD

**Issue by Cosmicshadows112** [ReVanced/revanced-patches#2971]
### Application

Youtube

### Issue

Option to turn off the youtube shorts scrolling.

### Patch

There should be a option to turn off the shorts scrolling feature but still be able to view them.

### Motivation

To stop mindless scrolling but still keep the benefits of shorts.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by KobeW50** [comment]
Dupe

https://github.com/ReVanced/revanced-patches/issues/2801
