### ISSUE TITLE
Money Theming in X.

### ISSUE THREAD

**Issue by WattsOn10** [ReVanced/revanced-patches#2972]
### Feature description

Need _Monet Theming_ in X  _**formerly Twitter**_.

### Motivation

Because it looks good.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [ ] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Insufficient motivation. #231
