### ISSUE TITLE
feat: Only recommend Videos with specific Tag

### ISSUE THREAD

**Issue by MySurmise** [ReVanced/revanced-patches#2973]
### Application

Youtube

### Issue

I get a lot of dumb and meme video recommendations and like a lot of other people want to waste less time on social media. Videos like "Lamborghini vs. largest shredder" are maybe fun to watch, but don't really provide anything meaningful.

### Patch

I would love to have a patch that enables settings with an allowlist or blocklist for either tags or video categories or both, so I can say "block all entertainment content" or "allow only educational content".

Anything more advanced like language processing of title etc. would probably be beyond the scope of a simple patch, but would of course be amazing.

### Motivation

It could save thousands of hours of mindlessly wasted time on this app if it works well and the categories of the videos are set correctly.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
That's a feature already. Use "search"

**Comment by MySurmise** [comment]
> That's a feature already. Use "search" and click don't recommend on videos you don't like.

This does not work very reliably. Youtube also will always try to push dumb/meme content onto the user because these are easier clicks. A hard coded block system would work much better.

Would a good PR be considered?

**Comment by oSumAtrIX** [comment]
No, a proper search will yield results tailored to your query. Before PRing discuss your implementation.

**Comment by MySurmise** [comment]
This is about the recommend feature, not about search.

**Comment by oSumAtrIX** [comment]
> , so I can say "block all entertainment content" or "allow only educational content".

This is fully doable using search

**Comment by MySurmise** [comment]
Yes, but I want to change recommendation, so that only videos with a specific tag get recommended. I don't want to search for a specific topic, I want general video recommendations. I know this is possible for search, but that's not what I'm after. I want to fix a problem with recommendations in the recommendation feed.

**Comment by oSumAtrIX** [comment]
Controlled by server

**Comment by MySurmise** [comment]
Yes but in the feed, couldn't you hide those videos that do not have a specific video category, like education? So it does load all videos from the server, but only displays the ones with that category?

**Comment by oSumAtrIX** [comment]
That's the same as searching for that category without straining the API

**Comment by MySurmise** [comment]
As far as I know, you can't search by category on YouTube. It's especially not possible to search for multiple specific categories, like 'Education', 'News and Politics', and 'Music'. Nor can you currently block a single category such as 'Entertainment' in the search feed. You can only search for a specific *topic* in the search bar.

This isn't about searching for a specific video *topic*, but rather the video *category* of the videos that are displayed in the recommendation feed. (For reference, see the categories listed here when clicking "Execute": https://developers.google.com/youtube/v3/docs/videoCategories/list?apix_params=%7B%22part%22%3A%5B%22snippet%22%5D%2C%22regionCode%22%3A%22us%22%7D ) There are only a few categories where the value 'assignable' is set to 'true' - I count 15. So it wouldn't strain the API too excessively when only these can be filtered for, especially because the user can control what kind of videos are displayed based on their interest.

I believe this feature would be great to have. It would allow users to waste less time on the platform by giving them more control over what is displayed in the recommendation feed and, ultimately, watched by the user. This way, users could improve the quality of their time spent on YouTube without completely avoiding it. I strongly believe that a small option menu in "Misc" would not take too much space and might save many hours wasted with useless videos.

**Comment by oSumAtrIX** [comment]
> So it wouldn't strain the API too excessively when only these can be filtered for

It would, because the feed would have to be paged until the screen is filled with videos of that category. Search is more tailored and does not strain the api. A blacklist is the same as pressing "don't recommend".

**Comment by MySurmise** [comment]
You cannot press "Don't recommend" for a whole category. The search feature is something wholly different from the recommendation feature. And if I want to block one category it would still display nearly all videos pulled from the API. So yes, a blocklist might be a cleaner alternative to an allowlist, as it does not throw away 80-90% of all pulled videos.

**Comment by oSumAtrIX** [comment]
> You cannot press "Don't recommend" for a whole category

The algo trains on what categories you like.

> blocklist might be a cleaner alternative to an allowlist

A blocklist strains the API the same way. It would need to page until the screen is filled with everything not blocked.

Use search.

**Comment by MySurmise** [comment]
The algo probably trains more on topics than on categories.
If only e.g. 2 items were allowed on the blocklist about ~85% of videos would still be displayed and if the algo does train on categories like you say this gets more and more over time, because the user would never watch the categories that aren't displayed.

And again, you cannot search for random videos within a category. You cannot block a category in search. This is a different feature.
