### ISSUE TITLE
feat: allow to run youtube without complying with don'tkillmyapp

### ISSUE THREAD

**Issue by Dev123456689** [ReVanced/revanced-patches#2973]
### Feature description

Let people just run the app without such unnecessary restrictions. Additionally recently we were forced to download the specific MicroG to run the application.

### Motivation

Don't impose unnecessary restrictions as it was working fine without it.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
The restriction is necessary.

**Comment by Dev123456689** [comment]
May I know why?

**Comment by Dev123456689** [comment]
> The restriction is necessary.

May I know WHY?

**Comment by oSumAtrIX** [comment]
If GmsCore does not run in the background, just like GMS, YouTube will fail to properly work, such as when switching accounts or playing videos or doing anything else.

**Comment by Dev123456689** [comment]
Just let people know about it so if they encounter such problem they know what to do instead of upright imposing it on them. 
I need to lock the app in the recents menu which allows it to run constantly in the background and drains my battery a lot.
