### ISSUE TITLE
feat:(photomath) support latest version

### ISSUE THREAD

**Issue by BrandonJ1728** [ReVanced/revanced-patches#2978]
### Application

Photomath

### Issue

When attempting to patch photomath it doesn't work, either app freezes or patcher stops on installing.

### Patch

To fix launch issues.

### Motivation

Photomath helps students understand and complete math problems.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
The supported versions help students understand and complete math problems as well. Insufficient motivation.
