### ISSUE TITLE
bug: YT FastForward/rewind (double tap) properly works only in zoomed mode

### ISSUE THREAD

**Issue by SuprMaks** [ReVanced/revanced-patches#2978]
### Bug description

FastForward/rewind only works in zoomed mode, almost impossible to trigger in normal view mode.
YT 19.09.37
Patches v4.5.0
Device: Samsung S7edge

https://github.com/ReVanced/revanced-patches/assets/44021907/4f34152a-e74e-4a2d-911b-26b6a76286c7

### Solution

Zoom in player

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [ ] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
The video doesnt load and no reproduction steps are provided. Fast forward works just fine.

**Comment by SuprMaks** [comment]
> The video doesnt load and no reproduction steps are provided. Fast forward works just fine.

I have added link on YT video. How can I reopen the issue?
