### ISSUE TITLE
bug: Quality Settings Don't Work for Shorts

### ISSUE THREAD

**Issue by anil-al** [revanced/revanced-patches#298]
### Type

Error at runtime

### Bug description

Neither default quality nor the good-old quality settings work for shorts. For those have 1080p at most, 480p is applied; for ones which have 720p, 360p is applied even though others are chosen.

### Steps to reproduce

Open a short.
Choose a quality option other than the current.
See the prompt "Changing default Wi-Fi quality to ..."
See the quality shown has changed to the chosen.
Neither quality is applied to the short nor the default quality is worked for other shorts.
Sometimes it even reverts back the quality shown to the default one at first. (480p/360p)

### Relevant log output

```shell
—
```

### Solution

Not found

### Additional context

Old quality settings patch is applied.
Default video quality patch is applied.

Tab S8+
YouTube Version 17.28.35

**Comment by Canny1913** [comment]
Patch is not designed to work in shorts.

**Comment by anil-al** [comment]
> Patch is not designed to work in shorts.

But like I said, quality preferences also doesn't work in shorts while it works in YouTube, so something should be interfering with quality preferences and shorts.

**Comment by oSumAtrIX** [comment]
Disable patches and report back the patch causing this issue.

**Comment by OxrxL** [comment]
> > Patch is not designed to work in shorts.
> 
> But like I said, quality preference also doesn't work in shorts while it works in YouTube, so something should be interfering with quality preferences and shorts.

There are no quality settings available for shorts. Are an exclusive of regular youtube videos.

This is the main reason behind the not working quality settings for shorts.

**Comment by JimZiii** [comment]
I had the same problem in the original vanced app and what helped me was setting the new quality settings to high instead of automatic
