### ISSUE TITLE
bug: YouTube long videos don't play after watching it for 2 or 3 minutes

### ISSUE THREAD

**Issue by somewhat69** [ReVanced/revanced-patches#2980]
### Bug description

Steps to reproduce:
1. Play a long video
2. Wait for 1 or 2 mins
3. Video keeps infinitely buffering
It always happens when I change to any long video.
Device: Nokia C3 running Android 10

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by mrjack711** [comment]
I've got the same problem.
Using YouTube v19.09.37 with latest patches.

**Comment by DisaAdalwulf** [comment]
Same problem

**Comment by oSumAtrIX** [comment]
Either you are running an outdated version, or you did not setup GmsCore properly as the app will ask you on launch

**Comment by somewhat69** [comment]
I did setup GmsCore and yeah I'm on the latest version

**Comment by DisaAdalwulf** [comment]
I got it working after going into incognito and leaving so try that maybe now I don't have the problem anymore

**Comment by somewhat69** [comment]
Ah ok will try

**Comment by somewhat69** [comment]
Yeah No luck

**Comment by DisaAdalwulf** [comment]
Darn, might have to do a reinstall of gas and youtube then

**Comment by oSumAtrIX** [comment]
If there's an issue open a new one with logs filtered by PoToken on launch of the patched app. For support move to one of our links at https://revanced.app
