### ISSUE TITLE
Feat: Automatically select one of the subscription feed filters

### ISSUE THREAD

**Issue by techexo** [ReVanced/revanced-patches#2986]
Hello,

First thanks all for your work.
I was wondering if it would be possible to create a patch that enable one of the Subscription Feed filters to be automatically selected by default.

For example, it would allow one to automatically have the "unwatched" filter selected, in order to hide already seen videos of followed creators.

Thanks!

**Comment by oSumAtrIX** [comment]
Please use the patch request template.
