### ISSUE TITLE
bug:Problems with Latest ReVanced and its microG

### ISSUE THREAD

**Issue by yogesh-hacker** [ReVanced/revanced-patches#2987]
### Bug description

_Reported By 20+ Users_

1. In latest ReVanced YouTube[19.09.37] video keeps buffering even though internet connection stable and available. After sometimes it starts buffering it can't be played again until I closes the video and replays it. Mu friends also having same problem...
2. After discontinuation of Vanced's MicroG everyone having problem with the apk size and home screen icon display. Users want it should be hidden as Vanced's MicroG and the APK size should be within 10-20MB. After installing it becomes 100MB+ that's making storage full in lower devices and draining too much CPU

### Error logs

```shell
No error
```

### Solution

1. I don't know any solution may be the ReVanced fails to keep connection alive with server.

2. Compress the apk 

### Additional context

Nothing

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
1. https://github.com/ReVanced/GmsCore/issues/35
2. Size of 35MB and not 100MB+ like you claim is due to multi arch APK, you are free to strip it down yourself. Battery drain/CPU usage is placebo until proven otherwise.

**Comment by yogesh-hacker** [comment]
Even though I am learning app development still unable understand previous conversation fully. 

Here are something I think could be done, everyone doesn't know programming... Make the GmS core or YT easy usable. I don't know why Vanced microG is unable, is it fails to work with latest YT configurations?

My GMS Core's SafetyNET was by default on, and PoToken sometimes appears and sometimes not, mean sometime plays and sometimes not. 

Another answer is, you should release microG for different architectures arm64 and others. User will download according to their requirement you could also create a app to download pre-patched apks as Vanced had. I was thinking to create myself one to provide your apks to users 😁 then thought its illigal without your permission.


At the end, Thank You 😊 You and your team providing something that others don't. I am learning Reverse Engineering, hopefully I would join you later... 

And a suggestion for you, Create patches for WhatsApp as GBWhatsapp(while others considered as virus) causes problems. If you do it I will also promote your app to others as I promoting your ReVanced YT.
