### ISSUE TITLE
bug: installation conflict

### ISSUE THREAD

**Issue by LouisAyroles** [ReVanced/revanced-patches#2989]
### Bug description

For a few days now, I've had videos that were blown up on youtube. So I decided to update to the latest version suggested by revanced. In 19.09.37. Unfortunately I couldn't install the apk once I'd built it because of conflicts. Youtube is a native application on my phone (Google Pixel 7), so I manually uninstalled youtube via ADB and pm uninstall. I now have no trace of youtube but the installation still fails for the same reason.

![image](https://github.com/ReVanced/revanced-patches/assets/46816453/c2166f86-887f-4fbc-ab88-44fb9e60ce65)

### Error logs

```shell
When I have tried to install it with ADB : 

Failure [INSTALL_FAILED_UPDATE_INCOMPATIBLE: Existing package com.google.android.youtube signatures do not match newer version; ignoring!]
```

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by Ushie** [comment]
Use the default patches, you removed a necessary patch.

**Comment by LouisAyroles** [comment]
I already have the patched app, I remove com.google.android.youtube after that.
I'm not sure to fully understand your reply.

**Comment by oSumAtrIX** [comment]
For support move to one of our links at https://revanced.app

**Comment by Ushie** [comment]
You removed the GmsCore Support patch, add it back and patch again to resolve this

You can join our Discord server to get help https://revanced.app/discord if you still can't get it
