### ISSUE TITLE
Tiktok better

### ISSUE THREAD

**Issue by Jackgawe** [ReVanced/revanced-patches#2992]
### Application

Tiktok lite

### Issue

No ads, darkmode

### Patch

No ads bruh

### Motivation

its gud

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Ushie** [comment]
Ads: https://revanced.app/patches?s=tiktok
Dark mode: https://support.tiktok.com/en/account-and-privacy/account-privacy-settings/dark-mode

**Comment by johnconner122** [comment]
> Ads: https://revanced.app/patches?s=tiktok

Patch request is for `TikTok-lite`, not Tiktok.
