### ISSUE TITLE
feat: Automatically chose a subscription filter

### ISSUE THREAD

**Issue by techexo** [ReVanced/revanced-patches#2994]
### Application

YouTube

### Issue

Subscription feed shows by default all videos. Filters allow to chose which one to display (live, continue watching, unwatched...), but we cannot chose by default which one to use. 

### Patch

The patch would allow one of the filter to be chosen as default in place of All Videos. 

### Motivation

I'm always bothered to see in my subscriptions' feed all videos that I've already watched. When following a lot of creators, it's quickly difficult to sort between what we've seen or not.
The unwatched filter already exists in the app but is hidden at the extreme right of the filters, not easily accessible.
Implementing this patch would allow one to always show only unwatched (or only live) videos by default, so that original and unseen content stands out.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Not sure what the problem is, there is a filter for unwatched and no proper motivation to set it by default
