### ISSUE TITLE
feat:  Whitelist and Blacklist Genres or Topics in YouTube ReVanced. 

### ISSUE THREAD

**Issue by IMajedI** [ReVanced/revanced-patches#2994]
### Feature description

Have you ever wanted to search something on Youtube but got distracted by the Youtube recommendation ?

Have you ever thought of a filtered/organized Youtube environment that you can choose on your own preference?

Do you want to have Control over what is being showed to your kid ?

Here i represent my solution and please share with me your thoughts and ideas so we can get the best out of it:

I would like to request a new feature for YouTube ReVanced that allows users to customize their content recommendations by whitelisting and blacklisting specified genres. This feature aims to provide users with greater control over the types of content they see in their YouTube feed and search results.

Feature Details:

1. Whitelisting Genres: Users should have the ability to whitelist specific genres or categories of content they are interested in. This means that only content from whitelisted genres will be shown in their YouTube Home feed and search results.

2. Blacklisting Genres: Conversely, users should also be able to blacklist certain genres or categories of content that they are not interested in. Content from blacklisted genres will be filtered out from their YouTube Home feed and search results.

3. Customization Options: The feature should offer granular control, allowing users to fine-tune their content preferences. This could include options to blacklist or whitelist individual genres, sub-genres, or specific keywords related to content types.

4. Impact on Recommendations: The whitelist and blacklist preferences should also influence YouTube's recommendation algorithm. Content recommendations should be tailored based on the user's specified preferences, ensuring a more personalized and relevant browsing experience.

ـــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ

There is a similar concept on the website [civitiai.](https://civitai.com/) that Only hides tag you put in. 
![image](https://github.com/ReVanced/revanced-patches/assets/138822136/e2c5798d-597a-4f88-b6c8-a055838c1cf6)

They have Also a slider with different kind of topics that if you pressed one topic only one topic that gets shown to the user. Which is not so good because as mentioned the user can only choose one topic and the topics are limited unlike the hide tags feature which you can write any tag.
![image](https://github.com/ReVanced/revanced-patches/assets/138822136/c826bee5-fb03-428a-aa78-8f20eac08c14)

### Motivation

This feature is great for everybody,

but my primary motivation for implementing this feature is to establish a secure environment for our children in alignment with parental values and beliefs. This approach ensures that our children can derive benefits and learn from their viewing experiences without concerns about exposure to unsuitable content.

Use Cases that I thought of :

1. Users who are only interested in specific genres, such as gaming or educational content, can whitelist those genres to focus solely on relevant videos.

2. Users who want to avoid certain types of content, such as reaction videos or Gaming videos, can blacklist those genres to declutter their YouTube feed and search results.

3. Users who prefer a diverse range of content can mix whitelisted and blacklisted genres according to their preferences.

4. Focused Studying: Students preparing for exams or focusing on specific academic subjects can utilize the whitelist and blacklist feature to streamline their studying experience. By whitelisting relevant educational genres and blacklisting distracting content, students can create a focused learning environment conducive to effective studying.

5. Minimizing Distractions: The feature empowers students to minimize distractions and stay on task by filtering out unrelated or irrelevant content from their YouTube feed and search results. This ensures that students can allocate their time and attention more efficiently towards their academic goals. 

6. Parental Control: Parents can utilize the whitelist and blacklist feature to manage and control the content their children are exposed to on YouTube. By whitelisting appropriate genres and blacklisting potentially harmful or inappropriate content, parents can create a safer and more age-appropriate browsing environment for their children.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
YouTube only provides tags for videos, and those tags aren't sent to the feed. For every video, a request would have to be made to fetch the tags and based on that somehow the video would have to be filtered.  Blacklist would completely strain the API as YouTube would need to send videos until the feed is full. This is unviable in terms of implementation overhead, bandwidth/API spam and the fact that keywords can be filtered already. Thanks regardless.

**Comment by IMajedI** [comment]
@oSumAtrIX i provided an approach that i thought of . there has to be an way to do it just leave it opened.

**Comment by oSumAtrIX** [comment]
Where is the approach?

**Comment by IMajedI** [comment]
@oSumAtrIX not approach sorry i meant an example that i saw in civitiai. leave it opened so maybe other devs think of a approach.

**Comment by oSumAtrIX** [comment]
Civitai implements APIs specifically for that purpose; YouTube doesn't. For that reason, no other approach will be found.

**Comment by IMajedI** [comment]
is it possible to maybe filter the results based on the title. maybe with a help with gbt and gemini ?

**Comment by oSumAtrIX** [comment]
@IMajedI Filtering by title is a feature in YouTube and its called "Search".

**Comment by IMajedI** [comment]
@oSumAtrIX i don think you read my request fully. can you leave the request open at least. maybe a other dev will think of a way to make this feature possible. you can just say it can t be done. come on man

**Comment by oSumAtrIX** [comment]
As explained previously:

>  Civitai implements APIs specifically for that purpose; YouTube doesn't. For that reason, no other approach will be found.

**Comment by IMajedI** [comment]
@oSumAtrIX you keep bringing the same idea. please stop trapping us in one way. i want to leave it open so maybe on of the devs will think of something outside of the box. as you know coding world is endless.

**Comment by IMajedI** [comment]
@oSumAtrIX @Aunali321 .I thought it was impossible???[https://imgur.com/a/d8AJFEe](url)

**Comment by oSumAtrIX** [comment]
Keyword filter does not filter genres or topics
