### ISSUE TITLE
Unlock CamScanner Premium features

### ISSUE THREAD

**Issue by HeroGalak** [ReVanced/revanced-patches#2995]
### Application

[CamScanner](https://play.google.com/store/apps/details?id=com.intsig.camscanner) 

### Issue

Title self explanatory

### Patch

Unlock all the possible features listed here:
![Screenshot_20230916_135004_CamScanner](https://github.com/ReVanced/revanced-patches/assets/69464248/9a705ba0-3043-4623-8564-f9fc3ed59f01)

### Motivation

CamScanner is one of the most used apps to scan documents on the play store. There are already some mods on the internet but they are not open source. Revanced can be the first trustworthy solution to unlock premium.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by johnconner122** [comment]
Can't MS Office Lens accomplish all these tasks?

**Comment by HeroGalak** [comment]
> Can't `MS Lens` accomplish all these tasks? 

Actually your app is better. I was so used to CamScanner that I've never searched for an alternative, thanks.
