### ISSUE TITLE
feat: allow to run with battery optimization

### ISSUE THREAD

**Issue by arthurbolsoni** [ReVanced/revanced-patches#2997]
### Feature description

An option in "misc" to ignore microg no battery optimization, with a warning message 'The application may not work properly with battery restriction, causing "X,Y,Z" problems'
This would remove the message when launching the application.

### Motivation

MicroG consumes an abundant amount of energy from the device. and the cost for changing its functionality can be chosen by the user.
It would bring more confidence to the project.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
GmsCore must run in the background in order for the app to function correctly. It does not consume abundant amount of energy like claimed.

**Comment by arthurbolsoni** [comment]
> GmsCore must run in the background in order for the app to function correctly. It does not consume abundant amount of energy like claimed.

This is exactly why there must be a button to choose to deactivate with a warning about the risks.
Currently I can't list positive points for not leaving energy consumption enabled.

**Comment by arthurbolsoni** [comment]
Please open this issue and let the discussion continue for the community choose

**Comment by oSumAtrIX** [comment]
Once you provide good reason backed by evidence why disabling battery optimization is necessary, I'll reconsider opening the discussion, until then the issue remains closed.

**Comment by arthurbolsoni** [comment]
I really don't understand why I didn't write the technical issues of the problem until now.

**Comment by arthurbolsoni** [comment]
Removing the problem battery are there any negative points to using the microg without restrictions? I just didn't find anyone saying about it in another's issue or pull request of implementation;


> The latest microg has dramatically better battery usage than the old Vanced MicroG.
> 
> On my phone MicroG (with battery optimization off) consumes less than 1% of the battery compared to all apps.
> 
> If you're really concerned then root your phone and use ReVanced without MicroG.

**Comment by arthurbolsoni** [comment]
> Removing the problem battery are there any negative points to using the microg with restrictions? I just didn't find anyone saying about it in another's issue or pull request of implementation;
> 
> > The latest microg has dramatically better battery usage than the old Vanced MicroG.
> > On my phone MicroG (with battery optimization off) consumes less than 1% of the battery compared to all apps.
> > If you're really concerned then root your phone and use ReVanced without MicroG.
