### ISSUE TITLE
Twitch Text bug

### ISSUE THREAD

**Issue by ZeyFoxOFF** [ReVanced/revanced-patches#3000]
### Type

Cosmetic

### Bug description

Twitch displays code instead of rendering

### Steps to reproduce

Just watch twitch 

### Relevant log output

```shell
No crash
```

### Screenshots or videos

![Screenshot_20230917-230629_Twitch](https://github.com/ReVanced/revanced-patches/assets/88542615/e54c536e-a7bb-4491-af9d-ff407b4281b5)
![Screenshot_20230910-212901_Twitch](https://github.com/ReVanced/revanced-patches/assets/88542615/4cc2c197-888f-495c-80f0-55832d1854ee)
![Screenshot_20230707-004415_Twitch](https://github.com/ReVanced/revanced-patches/assets/88542615/c619f13b-443b-44ff-9d79-d58fad749709)

### Solution

Idk solution 

### Additional context

In my case it was in these places 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by ZeyFoxOFF** [comment]
> Apps gone wild.
> 
> Try using unpatched twitch (same app version), and see if the bug is still present.

I looked and I don't have this text bug. Version 15.4.1

**Comment by ZeyFoxOFF** [comment]
> 16.1.0 is latest supported version and try patching that.  Although you'll have to turn on experimental mode in Manager because one of the ad blocker patches was overlooked and not version bumped (it works fine with 16.1.0).
> 
> If it still acts up with 16.1.0, try repatching and excluding patches until the issue is gone.  Report back which patch is causing the issue.
> 

Okay thanks I'll try tomorrow

**Comment by ZeyFoxOFF** [comment]
> 16.1.0 is latest supported version and try patching that.  Although you'll have to turn on experimental mode in Manager because one of the ad blocker patches was overlooked and not version bumped (it works fine with 16.1.0).
> 
> If it still acts up with 16.1.0, try repatching and excluding patches until the issue is gone.  Report back which patch is causing the issue.
> 

I tried version 16.1.0 and I still have the same text problem

**Comment by ZeyFoxOFF** [comment]
> Exclude patches until the error is gone, report back which one caused it

It's a long time to test

**Comment by oSumAtrIX** [comment]
Try [this](https://en.wikipedia.org/wiki/Binary_search_algorithm).

**Comment by ZeyFoxOFF** [comment]
> Try [this](https://en.wikipedia.org/wiki/Binary_search_algorithm).

I don't know any of this

**Comment by johnconner122** [comment]
> I don't know any of this

https://github.com/ReVanced/revanced-patches/issues/2789#issuecomment-1674687375

**Comment by ZeyFoxOFF** [comment]
I tested all plugins 1 by 1 and all of them show the test bug. I also tested to install the original apk app and no problem. I think it's at the patch level that the problem occurs and not necessarily because of the plugins

**Comment by ZeyFoxOFF** [comment]
I just tested in patch the application with the system language in English and always the same text problem

**Comment by oSumAtrIX** [comment]
Please include in a full recording:

1. Patch Twitch with no patches 
2. Show the issue
3. Uninstall and install the unpatched app
4. Show that no issue appears

**Comment by ZeyFoxOFF** [comment]
I can make that but how to patch with no patch ? We can't is? And I take 10 min to patch with my phone

**Comment by oSumAtrIX** [comment]
ReVanced CLI can do this by excluding all patches using `--exclusive`.

**Comment by ZeyFoxOFF** [comment]
Ok. You make for me ? I use twitch 16.1.0 from apkmirror

**Comment by ZeyFoxOFF** [comment]
I just did it when no patch and activate the bug is not there. So I guess all patches have this bug

**Comment by ZeyFoxOFF** [comment]
In a patched version with some patchs ?

**Comment by ZeyFoxOFF** [comment]
> Also try clearing the app data, and try using a different twitch account.

Video https://youtu.be/Y3ka2WllXrc

**Comment by oSumAtrIX** [comment]
> Please include in a full recording:
> 
> 1. Patch Twitch with no patches
> 2. Show the issue
> 3. Uninstall the patched and install the unpatched app
> 4. Show that no issue appears

Please include a full recording exactly as previously described.

**Comment by ZeyFoxOFF** [comment]
> Please include in a full recording:
> 
> 1. Patch Twitch with no patches 
> 2. Show the issue
> 3. Uninstall the patched and install the unpatched app
> 4. Show that no issue appears

Video https://youtu.be/5je3bpFvjUs

**Comment by ZeyFoxOFF** [comment]
> > Please include in a full recording:
> > 
> > 1. Patch Twitch with no patches
> > 2. Show the issue
> > 3. Uninstall the patched and install the unpatched app
> > 4. Show that no issue appears
> 
> Please include a full recording exactly as previously described.

Should it mean to do it all over again? I showed the essentials in the video
