### ISSUE TITLE
bug: Videos keep buffering and won't play 

### ISSUE THREAD

**Issue by GKid94** [ReVanced/revanced-patches#3001]
### Bug description

Videos keep buffering and stopping
![Screenshot_2024-04-07-23-45-04-547_app revanced android youtube](https://github.com/ReVanced/revanced-patches/assets/18757054/0cdfb680-a9f8-4028-ba6b-cfb56c0fa297)
![Screenshot_2024-04-08-00-04-16-497_rikka safetynetchecker](https://github.com/ReVanced/revanced-patches/assets/18757054/f31353c0-b3ff-4451-a92b-62d721175a44)
![Screenshot_2024-04-08-00-04-48-256_app revanced android gms](https://github.com/ReVanced/revanced-patches/assets/18757054/e84040b1-2717-484e-b68f-fe7582544576)
![Screenshot_2024-04-08-00-12-11-670_com android settings](https://github.com/ReVanced/revanced-patches/assets/18757054/38dec8ff-9e36-4074-9dbf-94dd94c7011d)
![Screenshot_2024-04-08-00-17-29-621_com miui securitycenter](https://github.com/ReVanced/revanced-patches/assets/18757054/22793777-1bed-4fee-9c83-b52bc4ef61e0)
![Screenshot_2024-04-08-00-19-04-752_com miui securitycenter](https://github.com/ReVanced/revanced-patches/assets/18757054/05cdc408-1ab8-4e28-ae1a-cde36fac44bd)

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Refer to https://github.com/ReVanced/revanced-discussions and comment using the comment template mentioned in the discussion.

**Comment by GKid94** [comment]
> Refer to https://github.com/ReVanced/revanced-discussions and comment using the comment template mentioned in the discussion.

It's a little complicated and I'm not on PC currently, why don't you put a log option in the app? Or can I send you the phone's debug log?

**Comment by GKid94** [comment]
> The raw debug logs include too much unrelated information (and can contain personal details).
> 
> You can use Termux to run logcat (search online for guides). Or just find a computer.

Ok
