### ISSUE TITLE
feat: shizuku support

### ISSUE THREAD

**Issue by tahirjamil** [ReVanced/revanced-patches#3002]
### Feature description

Adding a feature for shizuku installing method will be very helpfull

### Motivation

Not everyone have root access but everyone can use shizuku

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Root access is not necessary to use ReVanced Patches. For support move to our links at https://revanced.app
