### ISSUE TITLE
bug: AD Doubleclick domain added by patches

### ISSUE THREAD

**Issue by nightznero** [ReVanced/revanced-patches#3004]
### Bug description

Helloz,
Noticed after adding `Spoof SIM` & `Spoof WiFi connection` patches to whatever app,its adding Google domain  `doubleclick`
![Screenshot_20240408_181941_MT Manager](https://github.com/ReVanced/revanced-patches/assets/61750641/8c54d9a2-5c78-46da-84d4-7937a1ac432f)
Would like to know whats the point of adding that domain?
Best Regards, NIGHTZNERO.

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Both patches dont do either. Check the source.

**Comment by nightznero** [comment]
> Both patches dont do either. Check the source.

Indeed its doesn't if You say so. 
Wonder why its shows up after patched with RVM but before results are empty [https://streamable.com/ezgirf](Proof)

**Comment by oSumAtrIX** [comment]
Thats present in integrations for a different patch. All integrations are currently merged when required by a patch, but they are not being used by the patches you selected. The string is present in a blacklist for the keyword filter patch:
![image](https://github.com/ReVanced/revanced-patches/assets/13122796/53cc6c45-fa41-483c-ba0f-f6177a705bbc)
![image](https://github.com/ReVanced/revanced-patches/assets/13122796/728c88d2-e100-48d9-b4ef-c2408ecc8dce)
![image](https://github.com/ReVanced/revanced-patches/assets/13122796/9666872a-5b0a-45e7-879d-850bc89f9507)
