### ISSUE TITLE
bug(YouTube): Shorts  show in home feed when opening the app

### ISSUE THREAD

**Issue by 0frd** [ReVanced/revanced-patches#3005]
### Bug description

Shorts showup when open the app then refresh the homefeed it will disappear, close the app and open again and it will showup again and repeat

### Solution

Refresh the homefeed will make it disappear, but if you close the app it will showup again when you open the app
![Screenshot_2024-04-09-06-43-10-955_com google android youtube-edit~2](https://github.com/ReVanced/revanced-patches/assets/72485140/050b0e4f-50c4-4018-86e3-4dea0cea74f9)

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Hide shorts in feed using the "Hide Shorts components" patch

**Comment by 0frd** [comment]
> Hide shorts in feed using the "Hide Shorts components" patch

I absolutely using it

**Comment by oSumAtrIX** [comment]
Show a recording of how it's enabled and shorts still show up.

**Comment by 0frd** [comment]
> Show a recording of how it's enabled and shorts still show up.


https://github.com/ReVanced/revanced-patches/assets/72485140/85f2d9c4-cfc6-400c-a51b-8e32f318dfe4

**Comment by oSumAtrIX** [comment]
Could be caused by https://github.com/ReVanced/revanced-integrations/blob/530ba18364af63ce7d3f9421b9ac0c1462250c82/app/src/main/java/app/revanced/integrations/youtube/patches/components/ShortsFilter.java#L226.

@LisoUseInAIKyrios It could be that NavigationBar.NavigationButton.HOME.isSelected() doesn't work reliably here because the user exits the library tab.

**Comment by 0frd** [comment]
> @0frd the back button issue is fixed. Shorts displaying on startup should also be fixed but I could not reproduce the issue so I cannot verify.
> 
> You can try verifying by patching with dev release using a computer and CLI tools, or wait until dev is merged to main and patch using Manager.

Yes, confirmed its working, also problem on shorts buttons fixed
