### ISSUE TITLE
Update repository readne

### ISSUE THREAD

**Issue by KobeW50** [ReVanced/revanced-patches#3006]
### Type

Other

### Bug description

The readme in this repo has been empty and useless since the patches table was removed.

### Steps to reproduce

NA

### Relevant log output

```shell
NA
```

### Solution

Remove the readme, or make it useful. Some potential ways to make it useful are:

1. Add a link to https://revanced.app/patches for users who are accustomed to seeing the patch list in the readme
2. Add a brief explanation of what patches are.
3. Add a link to the patches development documentation https://github.com/revanced/revanced-patches/tree/docs/docs
4. Add short instructions and link to open issues and patch requests
5. Add the link to crowdin (if that makes sense. I have no clue how crowdin works)

### Additional context

I can pr when i am free. Just lmk what I should add. I assume I shpuld follow a similar template to the ReVanced Manager readme

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by KobeW50** [comment]
Im realizing now that this is a feature and not a bug

**Comment by Ushie** [comment]
There's a new README in the dev branch

**Comment by KobeW50** [comment]
Dammit I was about to check dev. Looks great, thanks
