### ISSUE TITLE
feat: Text size option 

### ISSUE THREAD

**Issue by GKid94** [ReVanced/revanced-patches#3010]
### Feature description

Add an option to increase the text and interface size for YouTube
![Screenshot_2024-04-10-16-05-31-628_app revanced android youtube](https://github.com/ReVanced/revanced-patches/assets/18757054/ce9cf7de-d6b5-4c24-a1fa-6e491aa1c81f)
![Screenshot_2024-04-10-16-05-46-049_app revanced android youtube](https://github.com/ReVanced/revanced-patches/assets/18757054/07c0e220-2aa6-41ba-b984-af69b283426f)

### Motivation

It will be easier to see and press

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by GKid94** [comment]
For example like the browser version, the text and buttons are better to see and press
![Screenshot_2024-04-10-16-07-59-934_com brave browser](https://github.com/ReVanced/revanced-patches/assets/18757054/824041f0-b9c6-4c0f-8487-febd4c170b96)
![Screenshot_2024-04-10-16-08-11-134_com brave browser](https://github.com/ReVanced/revanced-patches/assets/18757054/1da4269a-0216-4ed1-9089-0c2b4ed82cc6)

**Comment by oSumAtrIX** [comment]
You can change the font size on Android

**Comment by GKid94** [comment]
It doesnt change all text and interface

**Comment by oSumAtrIX** [comment]
Show a picture
