### ISSUE TITLE
bug(JoeyForReddit): Ads come back ~6 days after patching

### ISSUE THREAD

**Issue by Takeshi-no-uta** [ReVanced/revanced-patches#3012]
### Bug description

After patching Joey, ads are disabled as they should for about 6 days, until I get one of those Ad Personalisation pop-ups, and whatever I choose ads are now back, forcing me uninstall and repatch again.

It has been going on for a while, so it's been consistent with recent updates and on Joey's side I tried both the last version and 2.1.6.1 as that one was specifically recommended somewhere. I do have an adblock on the DNS level, if that makes any difference.
I use both disable ads and spoof client patches, and I am not rooted, on OxygenOS 14.

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
https://github.com/ReVanced/revanced-patches/issues/350

**Comment by suzukar** [comment]
JoeyForReddit version 2.1.6.5  "Ads are not hidden"
revanced-patches-4.17.0
![Image](https://github.com/user-attachments/assets/fe2cea74-0c9d-4fd0-a1a5-157c9e369deb)
