### ISSUE TITLE
feat: YandexAPI video translation

### ISSUE THREAD

**Issue by 3bagorion33** [ReVanced/revanced-patches#3014]
### Motivation

https://github.com/ilyhalight/voice-over-translation
If there is such a script for automatic translation via Yandex API in any browser, then I think this feature can be built into Revansed as well.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
https://github.com/ReVanced/revanced-patches/issues/580
