### ISSUE TITLE
feat(YouTube): Hide YouTube Playables in-app games

### ISSUE THREAD

**Issue by obosob** [ReVanced/revanced-patches#3016]
### Feature description

YouTube seems to have added a new anti-feature by the name of Playables, in-app games, for some unknown reason.

Would be great to get a patch to remove those from the feed/from the app altogether. 

### Motivation

In the same vein as hiding the shorts feed, if not even more important since at least shorts are video content that somewhat belong on a video platform.

I don't want games in YouTube, if I want a game I'd install it as an app. I'm sure many others feel the same.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Follow this and report back

![Screenshot_20240411-214147](https://github.com/ReVanced/revanced-patches/assets/13122796/0e56503a-28d0-45ce-8000-a3a934640957)

**Comment by obosob** [comment]
Strangely they stopped showing up on my main home feed since I raised this. However, I went to the more drawer and directly to the Playables section and got the following element paths and added them to the custom filter:

    horizontal_gaming_shelf.eml
    mini_game_card.eml

This does hide them if I explicitly navigate to that part of the app but as I say, even prior to creating the filter I couldn't get them to show up on my main feed all day. So I guess it's possible that the element path may differ when they're on the home feed.

Visually the `horizontal_gaming_shelf.eml` element looks visually how it appears in the home feed.

I think it'd be nice to hide the element from the drawer too to really nuke it from the app but couldn't differentiate the menu items by path. 

![Screenshot_20240411-194201~2.png](https://github.com/ReVanced/revanced-patches/assets/1075229/62dac56b-ab4e-45b3-be77-1f5171e229d6)

![Screenshot_20240412-170827.png](https://github.com/ReVanced/revanced-patches/assets/1075229/a419751e-2f99-44e3-85fc-d870ad2ea33b)

**Comment by oSumAtrIX** [comment]
Whats `mini_game_card.eml`?

**Comment by obosob** [comment]
They're these cards, I've only seen them by going directly to the Playables section and going to the browse tab. So they're not the intrusive element, blocking those is just my preference to get rid of what I can of this "feature". 

![Screenshot_20240412-224155.png](https://github.com/ReVanced/revanced-patches/assets/1075229/aec5a2f8-f05c-4700-a97d-b058998aa526)

**Comment by obosob** [comment]
I disabled the filter for a while until I saw the item again, then re-enabled it and confirmed the element was gone. It's definitely the `horizontal_gaming_shelf.eml`
