### ISSUE TITLE
bug(YouTube - Hide Shorts components): `Hide subscribe button when paused` needs renaming

### ISSUE THREAD

**Issue by n1cKz1** [ReVanced/revanced-patches#3022]
### Bug description

"Hide subscribe button when paused" needs renaming. It appears shorts_paused_state now also includes a new "Live" button which if you click it takes you to a random live broadcast, so it's every bit as useless as the subscriptions one.

Separating them is not recommended as they're both utterly useless and the subparent button component strings get updated fairly often from what I've seen so they would break and need to be updated regularly.

Also, "subscribe button" is a little confusing for various reasons. The average user will probably mix it up with the actual subscribe button when it is a whole different thing. The button itself is named subscriptions.

### Solution

It should probably be something like:

Hide subscriptions and live buttons
Subscriptions and live buttons are hidden when paused
Subscriptions and live buttons are shown when paused

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
How about "Hide buttons when paused"?

**Comment by n1cKz1** [comment]
Sounds fine as long as the button names are still mentioned in the description below. Otherwise the user might think that this setting hides literally every button when paused or something, even if that wouldn't make much sense lol

**Comment by n1cKz1** [comment]
> `Hide subscriptions and live buttons when paused` is long and will be clipped on most devices.
> 
> Maybe `Hide paused overlay buttons`?

I'm aware which is why my suggestion was to only include "when paused" in the description, but "paused overlay buttons" is more direct and probably the best one yet
