### ISSUE TITLE
bug(YouTube): Dark overlay in the player while playing a video

### ISSUE THREAD

**Issue by Hot12345** [ReVanced/revanced-patches#3025]
### Bug description

Youtube Dark overlay in the player while playing a video (on Revanced)
Version: 19.09.37
Patched: default 59 checks
Link: https://xdaforums.com/t/app-guides-unofficial-revanced-megathread.4523967/post-89448527
Fix: I need to force close the Youtube app to fix it temporary fix

![Screenshot_20240409-121636_Discord_1](https://github.com/ReVanced/revanced-patches/assets/29144713/17632d03-7ef4-456c-af4a-3a88ab006cb1)

### Error logs

```shell
No error.
```

### Solution

Workaround: 
 I need to force close the Youtube app to fix it temporary fix

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by Hot12345** [comment]
> Try this and report back which patch is causing the issue.
> 
> ![image](https://private-user-images.githubusercontent.com/13122796/312136300-77b8e48d-e9ad-4704-85a7-082233d2dbe6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxMTk5NTIsIm5iZiI6MTcxMzExOTY1MiwicGF0aCI6Ii8xMzEyMjc5Ni8zMTIxMzYzMDAtNzdiOGU0OGQtZTlhZC00NzA0LTg1YTctMDgyMjMzZDJkYmU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE0VDE4MzQxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlNTA5ZDcwMGI0NmY1ZDhjMzg0ODBmNDE2OTE0YjcyY2RiNDI4MmE4OTI1Y2IyOWRiYTI5MjRhZTg5YjhmNmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0lT8clBdPGQlWZQw7YHRFZRlD__PvhRr-5tWHOb-8G0)
> 
> Also try clearing the YT ReVanced app data, and see if that fixes it.

Do I need to build every time the app? with the disabled modules?

**Comment by Hot12345** [comment]
The difficult is that I dont know what it cause the issue to reproduce it...

**Comment by Hot12345** [comment]
> If a specific patch cannot be identified as the problem, or the problem cannot be reliably reproduced, then it's almost impossible to fix the issue.

Check. I will check it default patch checks are 59. I will start with 20 and from that point I will followup. 
report it back when I know more.

**Comment by 0xrxL** [comment]
> The difficult is that I dont know what it cause the issue to reproduce it...

It's a stock bug. It happens sometimes during seeking.

You can fix it by tapping the seeking bar again (after that, the player buttons will be shown again).

**Comment by oSumAtrIX** [comment]
Closing until evident otherwise

**Comment by 0xrxL** [comment]
> Closing until evident otherwise


https://github.com/ReVanced/revanced-patches/assets/127248639/39dcd24e-e91e-4427-a771-242f7874b437

**Comment by oSumAtrIX** [comment]
@giwrgosmant https://github.com/ReVanced/revanced-patches/issues/3025#issuecomment-2054148496 follow this
