### ISSUE TITLE
bug: Videos not loading

### ISSUE THREAD

**Issue by GKid94** [ReVanced/revanced-patches#3026]
### Type

Other

### Bug description

YouTube videos not loading

### Steps to reproduce

1) Open YouTube Revanced
2) Open a video
3) The video page and video get stuck and won't load

### Relevant log output

```shell
/
```

### Screenshots or videos

![Screenshot_2023-09-25-11-24-34-328_com android settings](https://github.com/ReVanced/revanced-patches/assets/18757054/0d975d2c-70ba-48e0-baee-045869f22326)
![Screenshot_2023-09-25-15-09-47-103_app revanced android youtube](https://github.com/ReVanced/revanced-patches/assets/18757054/9f51db0c-96df-4bb6-9da6-9a6357a3867e)
![Screenshot_2023-09-25-15-10-33-731_com miui securitycenter](https://github.com/ReVanced/revanced-patches/assets/18757054/5430b757-acbe-4763-a21d-8379ce507f66)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Exclude patches until the error is gone, report back which one caused it

**Comment by xDARKxDEVILx** [comment]
Also, it would be better if you use the new recommended version for yt
Which is 18.32.39, make sure manager is at latest version too while patching

**Comment by GKid94** [comment]
> Exclude patches until the error is gone, report back which one caused it

How do I do that?

**Comment by GKid94** [comment]
> Also, it would be better if you use the new recommended version for yt Which is 18.32.39, make sure manager is at latest version too before patching

I don't have any update
![Screenshot_2023-09-25-16-10-39-279_app revanced manager flutter](https://github.com/ReVanced/revanced-patches/assets/18757054/c7de0b60-b642-455a-8971-5b35b548823a)
![Screenshot_2023-09-25-16-10-46-867_app revanced manager flutter](https://github.com/ReVanced/revanced-patches/assets/18757054/8d9311cf-ea1d-4d04-93c0-23402b993b50)

**Comment by xDARKxDEVILx** [comment]
> > Also, it would be better if you use the new recommended version for yt Which is 18.32.39, make sure manager is at latest version too before patching
> 
> I don't have any update ![Screenshot_2023-09-25-16-10-39-279_app revanced manager flutter](https://user-images.githubusercontent.com/18757054/270368682-c7de0b60-b642-455a-8971-5b35b548823a.jpg) ![Screenshot_2023-09-25-16-10-46-867_app revanced manager flutter](https://user-images.githubusercontent.com/18757054/270368690-8d9311cf-ea1d-4d04-93c0-23402b993b50.jpg)

Yes, but patch version 18.32.39 like the manager suggestes and see if you can reproduce the issue

**Comment by GKid94** [comment]
> > > Also, it would be better if you use the new recommended version for yt Which is 18.32.39, make sure manager is at latest version too before patching
> > 
> > 
> > I don't have any update ![Screenshot_2023-09-25-16-10-39-279_app revanced manager flutter](https://user-images.githubusercontent.com/18757054/270368682-c7de0b60-b642-455a-8971-5b35b548823a.jpg) ![Screenshot_2023-09-25-16-10-46-867_app revanced manager flutter](https://user-images.githubusercontent.com/18757054/270368690-8d9311cf-ea1d-4d04-93c0-23402b993b50.jpg)
> 
> Yes, but patch version 18.32.39 like the manager suggestes and see if you can reproduce the issue

Doesn't the Manager update YouTube?

**Comment by xDARKxDEVILx** [comment]
> Doesn't the Manager update YouTube?

No, you have to install the new apk from apkmirror and select it from storage then patch it, the manager only updates itself

**Comment by GKid94** [comment]
> > Doesn't the Manager update YouTube?
> 
> No, you have to install the new apk from apkmirror and select it from storage then patch it, the manager only updates itself

Can you make the Manager so that I updates YouTube too?

**Comment by xDARKxDEVILx** [comment]
I want reply to this anymore, if you need help, then join discord from the link in manager and ask for help there in support channel

**Comment by GKid94** [comment]
It still happens with the new version
![Screenshot_2023-09-25-21-38-33-386_app revanced android youtube](https://github.com/ReVanced/revanced-patches/assets/18757054/1bd840d5-2ed5-4d78-b94b-22b8f339a3ca)

**Comment by GKid94** [comment]
![Screenshot_2023-09-25-21-40-46-782_com miui securitycenter](https://github.com/ReVanced/revanced-patches/assets/18757054/eb0df1cf-635d-4c5d-ad87-77126ec9bbc8)

**Comment by oSumAtrIX** [comment]
> > Exclude patches until the error is gone, report back which one caused it
> 
> How do I do that?

By clicking on the patch to select or deselect it. Check the ReVanced Manager docs: https://github.com/ReVanced/revanced-manager/tree/main/docs
