### ISSUE TITLE
feat: 

### ISSUE THREAD

**Issue by SteamRex25** [ReVanced/revanced-patches#3028]
### Feature description

I would like to have a patch that allows for us to have something like tampermonkey on the youtube app to allow us to install scripts

### Motivation

I believe that this should be implemented because it would allow us to extend the functionality of the app past the patches that we already have due to the nature of this patch, one use case could be to restore the old ui to a degree without having to spoof the app. 

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [ ] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Please follow the acknoledgements
