### ISSUE TITLE
feat: Swipe controls behavior like vanced

### ISSUE THREAD

**Issue by smonsec** [revanced/revanced-patches#303]
### Type

Functionality

### Issue

Step 1: Enable swipe controls.
Step 2: Play any video go to full screen.
Step 3: In non-overlay mode, swipe-up controls work normal but swipe-down gets out of the full screen.
Step 4: Tap on the screen to get overlay of playback bar and suggested video cards.
Step 3: Now Swipe up, it will again fidget with vol and brightness instead of pulling up cards(like vanced behavior) and swipe down on either side will do again fidgeting with vol and brightness instead of getting out of full screen (like vanced behavior).

### Feature

In the full-Screen, overlay gestures should work like normal(same like Vanced).

In the Fullscreen overlay, swipe up should bring up video suggestions cards instead of changing vol or brightness values, while swipe down should get us out of the full screen.

In the non-overlay Fullscreen, swip-controls should just do the normal vol and brightness controls.

### Motivation

Current swipe-controls are pretty confusing and also conflict with swipe up gesture of suggested video cards and swipe-down gesture of getting out of the Fullscreen. Vanced has this implemented pretty well, they are very clear in their functionality as described above and doesn't conflict with another.

**Comment by oSumAtrIX** [comment]
You still have access to the original swipe controls of YouTube by swiping in the middle of the screen. @shadow578 maybe horizontal scrolling can be a good option for many.

**Comment by smonsec** [comment]
> You still have access to the original swipe controls of YouTube by swiping in the middle of the screen. @shadow578 maybe horizontal scrolling can be a good option for many.

My bad, didn't used official app for years  so didn't know that :).

**Comment by yokhoe** [comment]
I do agree on the bugginess of the custom swipe gesture for brightness and volume being confused when the overlay is visible and when it isn't. Sometimes it works in whichever overlay it feels like to work in, other times, if will default to showing the suggested video cards

**Comment by oSumAtrIX** [comment]
Can you first record the issue mentioned?

**Comment by anil-al** [comment]
For that, using _press to swipe_ would be enough. Thanks to that, there won't be any overlapping. After using that, I realised of that that Vanced implementation was very bad since I always ended up changing the volume when I would like to swipe up to turn back to home screen. Otherwise, there's no function of swipe patch if we cannot use it in the full screen.

**Comment by smonsec** [comment]
I'm closing this as swipe gestures are near perfect.
