### ISSUE TITLE
bug(YouTube): "views" and "ago" strings sometimes are not displayed under video player

### ISSUE THREAD

**Issue by HeroGalak** [ReVanced/revanced-patches#3031]
### Type

Cosmetic

### Bug description

Watch title

### Steps to reproduce

I'm not able to reproduce it. It happens randomly

### Relevant log output

```shell
//
```

### Screenshots or videos

![Screenshot_20230925_174228_YouTube](https://github.com/ReVanced/revanced-patches/assets/69464248/a4832a16-b249-4fc7-a684-1db967056bf7)

### Additional context

The strings reappear momentarily during the animation when views and date vars are updating.

Using latest YT version and patches

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Exclude patches until the error is gone, report back which one caused it.
