### ISSUE TITLE
feat (youtube): Add toggle for (premium) heading patch

### ISSUE THREAD

**Issue by KobeW50** [ReVanced/revanced-patches#3034]
### Application

Youtube 

### Issue

Currently once the patch is applied it is permanently set. The only workaround to hide the premium heading is to use the wide search bar, which may not be desirable.

### Patch

A toggle within YT ReVanced settings that allows the user to switch between the premium header and the non-default header.

[inotia00](https://github.com/inotia00) has this toggle in his fork of the patches/integrations, so looking at his implementation may help with development of this.

### Motivation

This isn't important. Just QoL for a cosmetic feature. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Either use the patch or don't, there is no necessity to toggle it considering the implementation effort outweighs the necessity.
