### ISSUE TITLE
feat:  Remove `?si=` parameter from youtube sharing URL

### ISSUE THREAD

**Issue by heartlog** [ReVanced/revanced-patches#3037]
### Application

YouTube

### Issue

YouTube often appends tracking parameters like ?si to URLs for analytics and tracking purposes.These parameters don't affect the video playback itself but are used to gather data on how the link was accessed.

Removing the tracking parameters is a way to share a cleaner, more straightforward link to the video.It's a good practice for privacy-conscious users who prefer not to share unnecessary tracking data.
By sharing just the base YouTube URL, you ensure that viewers can access the video without any additional tracking information.

### Patch

As we know youtube links add some short of traking with sharing url.
ex. `https://youtu.be/2NKOlLDNknc?si=NlMp_43qqWHyOlF_`
Here, even if we remove `?si` it'll still play normally.

### Motivation

YouTube should not use tracking because it raises privacy concerns, compromises data security, limits user autonomy, creates algorithmic bubbles, and can lead to the misuse of user data. Balancing user privacy and the benefits of tracking is crucial.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by KobeW50** [comment]
I like how you expressed the motivation  for this, but its a dupe of https://github.com/ReVanced/revanced-patches/issues/2870

**Comment by heartlog** [comment]
> I like how you expressed the motivation for this, but its a dupe of #2870

sorry about that,

**Comment by heartlog** [comment]
I've found a solution to this 'si' problem: using another app to handle the work. 

"Necessity is the mother of invention," or in this case, "Necessity is the mother of a Google search (Google Play Store specific)."

I've discovered the [UrlChecker app](https://github.com/TrianguloY/UrlChecker/), which is also available on the [Play Store](https://play.google.com/store/apps/details?id=com.trianguloy.urlchecker). Here's how you can use it to accomplish this task:

1. Share the YouTube URL with this app, and it will open a pop-up menu similar to this: ![Screenshot_20230928_220028_URLCheck](https://github.com/ReVanced/revanced-patches/assets/76758776/52768772-6f82-4a8a-81f0-4ff43c3871af)

2. In the "Queries" section, cancel out the 'si' parameter.

3. The URL will then look like this: ![Screenshot_20230928_220043_URLCheck](https://github.com/ReVanced/revanced-patches/assets/76758776/a2a905e3-5e55-419c-9b0d-b4b6fcd0d800)

Now you can share that URL with anyone without the 'si' parameter! It may require 4-5 extra clicks, but you won't need to open the keyboard to manually edit the URL each time.

**Comment by oSumAtrIX** [comment]
It's faster to simply delete the query parameter from the URL

**Comment by heartlog** [comment]
@oSumAtrIX Well, Android phone don't have a physical keyboard.
anyway you can add pattern to remove that si 
In Modules-/ pattencheck-/ Advance editor
```json
  "Youtube remove si": {
    "regex": "(https?:\\\/\\\/(?:youtube\\.com\\\/watch\\?v=|youtu\\.be\\\/)([a-zA-Z0-9_-]+))(?:\\&si=[a-zA-Z0-9_-]+)?$",
    "replacement": "$1",
    "automatic": "true",
    "enabled": "true"
  }
```
It'll automatically remove the si parm.Saving clicks.
![Screenshot_20230929_074649_URLCheck](https://github.com/ReVanced/revanced-patches/assets/76758776/48b6b497-3846-44ff-871f-8fd3b6ec017f)
