### ISSUE TITLE
bug: Hide End Screens Not Working

### ISSUE THREAD

**Issue by i6jm** [revanced/revanced-patches#304]
### Type

Error at runtime

### Bug description

When you enable the option to hide end screens, and watch a video clip when is almost finished, the end screens appear

### Steps to reproduce

1-Enable the option to hide end screens
2-Play any video clip that has the end of a screen
3- When the video clip is almost finished, the end screen will appear

### Relevant log output

```shell
none
```

### Screenshots or videos

![Screenshot_20220805_134106_app revanced android youtube](https://user-images.githubusercontent.com/57762287/183064531-c1875375-601a-4282-9892-a0fe59ff4b5f.jpg)

**Comment by OxrxL** [comment]
https://github.com/revanced/revanced-patches/issues/301

**Comment by OxrxL** [comment]
Maybe related to: https://github.com/revanced/revanced-patches/issues/301
