### ISSUE TITLE
feat: Skip over redirection URLs to external links

### ISSUE THREAD

**Issue by 98xe** [ReVanced/revanced-patches#3040]
### Application

YouTube

### Issue

At the moment, opening an external link (ex. Twitter/Reddit), opens the page in the browser, rather than in the native app.

### Patch

Basically RVX's `enable-open-links-directly` patch.

### Motivation

Allows external links to opened in their native app, as they should.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by johnconner122** [comment]
> Allows external links to opened in their native app, as they should.

That's not what `enable-open-links-directly` patch does, it skips over `youtube.com/redirect`

**Comment by 98xe** [comment]
> > Allows external links to opened in their native app, as they should.
> 
> That's not what `enable-open-links-directly` patch does, it skips over `youtube.com/redirect`

Yeah, it's the `youtube.com/redirect` part that's preventing links from being opened directly in their apps.

**Comment by johnconner122** [comment]
> > > Allows external links to opened in their native app, as they should.
> > 
> > 
> > That's not what `enable-open-links-directly` patch does, it skips over `youtube.com/redirect`
> 
> Yeah, it's the `youtube.com/redirect` part that's preventing links from being opened directly in their apps.

No, its not. You can add `open-links-externally` patch to open links externally.
