### ISSUE TITLE
feat: (YouTube): Background/Popup player button in Video Player

### ISSUE THREAD

**Issue by Tanmandal** [ReVanced/revanced-patches#3042]
### Feature description

Please add ability to add a button in video player to play the video in pop-up player 
This would enable user to play only desired videos in popup player even if it is disabled

### Motivation

This feature can come in handy as many of the users like keeping background playback disabled so that pressing home button pauses the video and takes to homescreen . It would help if the user has background playback disabled but just wants that particular video to play in popup mode .

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Pausing the video has the same effect.
