### ISSUE TITLE
bug: Reddit crashes after patching

### ISSUE THREAD

**Issue by Blcktape** [ReVanced/revanced-patches#3045]
### Type

Error while patching

### Bug description

Version: 2023.37.0
After patching Reddit crashes when trying to open it.
When wiping cache and data it crashes as soon as you try to login.

### Steps to reproduce

After patching Reddit crashes when trying to open it.
When wiping cache and data it crashes as soon as you try to login.

### Relevant log output

```shell
-
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [x] I have written a short but informative title.
- [ ] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Can not reproduce with the steps provided
