### ISSUE TITLE
bug: Playback issue when open video through Google Chrome

### ISSUE THREAD

**Issue by hongcha666** [ReVanced/revanced-patches#3047]
### Bug description

Playback issue
Step1:Search YouTube video on Google Chrome
Step2:Open the link through Revanced
Step3:Watch video for a while , playback issue occur!

https://github.com/ReVanced/revanced-patches/assets/113239053/a28aec1d-2c03-4d5c-8375-1bce0596868f

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Follow this https://github.com/ReVanced/revanced-discussions/discussions/1037
