### ISSUE TITLE
feat: ( Youtube ) Ad Speedup

### ISSUE THREAD

**Issue by ChristophorusReyhan** [ReVanced/revanced-patches#3048]
### Feature description

Add a feature like this [extension](https://chromewebstore.google.com/detail/ad-speedup-skip-video-ads/pcjlckhhhmlefmobnnoolakplfppdchi) to speedup ads by 16X

### Motivation

Because Youtube put up [announcement](https://support.google.com/youtube/thread/269521462/enforcement-on-third-party-apps?hl=en) few days ago that said

> We’re strengthening our enforcement on third-party apps that violate YouTube’s [Terms of Service](https://developers.google.com/youtube/terms/api-services-terms-of-service), specifically ad-blocking apps. (...)

>  (...) We want to emphasize that our terms don’t allow third-party apps to turn off ads (...)

Since it highlights the ‘Blocking ads’ part, I think that speeding up ads doesn’t violate their Terms of Service (TOS). Please correct me if I’m wrong

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
The TOS explicitly outlines client mods of any kind.
