### ISSUE TITLE
feat: Info about how to use Custom Filter commands

### ISSUE THREAD

**Issue by calmhero** [ReVanced/revanced-patches#305]
### Application

YouTube

### Issue

I like to use Distraction Free YT on PC but Same can't be possible on Mobile, at least I thought so, (coz there's an Underrated feature present already in YT Revanced Settings, that does the work, but doesn't explain how to use it, i.e. Custom Filters.

### Patch

 What if there's a detailed Info about it's usage (below the option) ? It will be lifesaving.
It won't cause any problem for other options, because Custom Filters is already the Last one in the list. Hopefully you give Detailed Commands on how to use this great feature & help us use YouTube distraction free, according to our own will.

### Motivation

Because people can choose what they want to watch, instead of YouTube recommending endlessly to get us hooked on their platform. We can save our time & watch only what we CHOOSE to watch, and use the app Distraction Free. It will be a small addition but will make it easier.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Dev123456689** [comment]
Updated link for list of component names: ( The link 🔗 above is no longer working)
https://kazimmt.github.io/troubleshoot/yt-custom-filters/
