### ISSUE TITLE
bug: Twitter crashing

### ISSUE THREAD

**Issue by fawzynahwi** [ReVanced/revanced-patches#3051]
### Type

Error at runtime

### Bug description

Hi,
After applying patches for Twitter app it wont normal install. If I try to install with root it installs but the app crashes if I click on an image.
Uninstall Twitter before installing patched app makes Twitter crash altogether.
Please help.
I am on A13 VoltageOS

### Steps to reproduce

1-patch
2-install

### Relevant log output

```shell
Copying APK
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing patches
Dynamic color succeeded
Hide ads succeeded
Hide recommended users succeeded
Compiling modified dex files
Compiling modified resources
Signing APK
Patched
Installing patched file using nonroot method
Installing patched file using nonroot method
Installing patched file using nonroot method
Installing patched file using nonroot method
Installing patched file using nonroot method
Installing patched file using nonroot method
Installing patched file using nonroot method
Installing patched file using nonroot method
```

### Screenshots or videos

https://github.com/ReVanced/revanced-patches/assets/52822428/2dcaa6c1-9bf5-4f6e-ba70-ac8c4205db38

### Additional context

I have tried to:
1-reinstall revanced manager
2-reinstall twitter
3-uninstalling twitter before installing patched apk.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Can not reproduce a crash with the reproduction steps. Include a crash log using logcat.

**Comment by fawzynahwi** [comment]
> Can not reproduce a crash with the reproduction steps. Include a crash log using logcat.

[logcat.txt](https://github.com/ReVanced/revanced-patches/files/12775465/logcat.txt)

**Comment by oSumAtrIX** [comment]
You are patching a split APK file, you need a full APK file.

**Comment by fawzynahwi** [comment]
> You are patching a split APK file, you need a full APK file.

Do u mean I need to sideload it and not from Playstore?

**Comment by oSumAtrIX** [comment]
PlayStore provides split apk files

**Comment by fawzynahwi** [comment]
> PlayStore provides split apk files

I'll try to sideload it from APKMirror and report back.

**Comment by fawzynahwi** [comment]
> PlayStore provides split apk files

I can confirm that patching the app installed from APKMirror has solved the issue. 
Thanks for the assistance.
