### ISSUE TITLE
feat(fddb): Premium Unlock

### ISSUE THREAD

**Issue by Nzxtime** [ReVanced/revanced-patches#3053]
### Application

Fddb
https://play.google.com/store/apps/details?id=com.fddb

### Issue

Unlock Fddb Gold/Premium

### Patch

Unlock the Gold Premium Tier of the app with all its features

### Motivation

After looking a bit around I found a few unsafe sites providing unlocked mods and it would be safer if there was a revanced patch.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Closing according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#%EF%B8%8F-guidelines-for-requesting-or-contributing-patches). Thanks anyways.
