### ISSUE TITLE
feat: Adobe Acrobat `Premium`

### ISSUE THREAD

**Issue by cyberboh** [ReVanced/revanced-patches#3054]
### Application

`https://play.google.com/store/apps/details?id=com.adobe.reader&hl=en_US`

### Issue

Premium is the issue, we need to unlock it to subcribe premium features for free.

### Patch

Premium unlocked

### Motivation

Adobe Acrobat Reader is the world’s most trusted PDF reader and PDF editor. It's Swiss Knife PDF reader and editor for mobile phone. It has many features that does not own in another similiar products.
Edit PDFs, convert to another format file (doc, xls, jpg, png, ppt, etc), create PDF from any files, compress PDF and protect PDF with a password. 
All you can do just from your mobile phone or tablet.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Closing according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#%EF%B8%8F-guidelines-for-requesting-or-contributing-patches). Thanks anyways.
