### ISSUE TITLE
feat: Remove `si=` tracker id from YouTube's and YouTube Music's share link option

### ISSUE THREAD

**Issue by pcroland** [ReVanced/revanced-patches#3057]
Currently both YouTube and YouTube Music copies URLs with a tracking ID. It would be nice if I didn't have to manually remove them when sharing an URL.

### Patch

Remove from `?si=...` from the copied URLs

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
https://github.com/ReVanced/revanced-patches/issues/2870

**Comment by KobeW50** [comment]
@oSumAtrIX 
2870 appears to be specifically for YouTube. This post is also requesting for YTM.

**Comment by oSumAtrIX** [comment]
Add as a comment or add in issue description
