### ISSUE TITLE
feat(YouTube): Hide the 'Visit store' button on channel pages

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [ReVanced/revanced-patches#3058]
### Feature description

Hide the 'Visit store' button in the channel page. 
![Screenshot_20240421_175421_YouTube](https://github.com/ReVanced/revanced-patches/assets/117499019/43f39681-7aab-49ed-ba52-ed77064bede0)

### Motivation

Well, clicking it leads the user to a page full of products from the channels, so basically ad blocking. 

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Is header_store_button not a path builder string?

**Comment by ILoveOpenSourceApplications** [comment]
> Is header_store_button not a path builder string?

No, it's in the bufferstrings.

**Comment by n1cKz1** [comment]
Since this is still in dev I didn't wanna create a new issue about this: "Hide the 'Visit store' button on channel pages" is a little too long. Also, what do you think about creating a "Channel profile" subcategory in Layout settings?

**Comment by n1cKz1** [comment]
Could at least remove the "the" to shorten it a bit

> List all the different 'channel page' settings, and if there's enough then a sub-menu under 'feed' could be made.

Well currently there's 3: channel member shelf, 'for you' shelf and visit store button, also in the case #3059 gets implemented then I think 4 is more than enough

**Comment by oSumAtrIX** [comment]
If you remove "the" it won't be a proper sentence anymore.

**Comment by ILoveOpenSourceApplications** [comment]
A heads up. YouTube changed the path for 'Visit store' button. Could be an A/B test. Now it's `^page_header.eml$header_store_button` and leaves behind a black space where the button was unlike the previous one.

![Screenshot_20240611_114736_YouTube](https://github.com/ReVanced/revanced-patches/assets/117499019/7f23e8ad-cb3a-4d83-95ce-191d952b51b2)

```kotlin
06-11 11:16:42.181 16748 16748 D Extended: LithoFilterPatch: Path: page_header.eml|29bf20f8b14236d4|ContainerType|ContainerType|ContainerType|flexible_actions.eml|daf1064fca739913|ContainerType|ContainerType|ContainerType|button.eml|ebc698722222cbfe|ContainerType|
06-11 11:16:42.181 16748 16748 D Extended: LithoFilterPatch: BufferStrings: Visit storeΓ¥Ösans-serifΓ¥Öeml.header_store_buttonΓ¥ÖVisit storeΓ¥ÖUCeeFfhMcJa1kjtfZAGskOCAΓ¥ÖEgVzdG9yZfIGBBICKgA%3D"Γ¥Ö/@techlinkedΓ¥Ö
```

**Comment by ILoveOpenSourceApplications** [comment]
Aheads up. YoutUBE changed the path for 'Visit store' button. It's now `^page_header.eml$header_store_button` and leaves behind a black space where the button was unlike the previous one.

![Screenshot_20240611_114736_YouTube](https://github.com/ReVanced/revanced-patches/assets/117499019/4430b6d8-dc74-44a9-8e75-d3ceea7411b6)

```kotlin
06-11 11:28:53.736 29858 29858 D revanced: LithoFilterPatch: Searching ID: null Path: page_header.eml|29bf20f8b14236d4|ContainerType|ContainerType|ContainerType|flexible_actions.eml|daf1064fca739913|ContainerType|ContainerType|ContainerType|button.eml|ebc698722222cbfe|ContainerType| BufferStrings: Visit storeΓ¥Ösans-serifΓ¥Öeml.header_store_buttonΓ¥ÖVisit storeΓ¥ÖUCKqH_9mk1waLgBiL2vT5b9gΓ¥ÖEgVzdG9yZfIGBBICKgA%3D"Γ¥Ö/@VanossGamingΓ¥Ö
```
