### ISSUE TITLE
feat(Moneymanager):  Premium unlock

### ISSUE THREAD

**Issue by wanderlusttt** [ReVanced/revanced-patches#3059]
### Application

Money Manager: https://play.google.com/store/apps/details?id=com.realbyteapps.moneymanagerfree

### Issue

Unlock Premium feature

### Patch

Unlock the Premium Tier of the app with all its features

### Motivation

After looking a bit around I found a few unsafe sites providing unlocked mods and it would be safer if there was a revanced patch.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Closing according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#%EF%B8%8F-guidelines-for-requesting-or-contributing-patches). Thanks anyways.
