### ISSUE TITLE
Add Tubi streaming app to the project

### ISSUE THREAD

**Issue by nadiration** [revanced/revanced-patches#306]
### Type

Other

### Issue

Tubi app has ads and doesn't support offline downloading.

### Feature

Tubi is a free ad-supported streaming app. It would be great if you add patches that will remove ads and enable offline downloading (if possible).

### Motivation

Tubi seems to be a great free streaming app and it would really help everyone if the ads was removed and the movies/shows could be saved offline (if possible).

Thank you for everything.

**Comment by Canny1913** [comment]
![Screenshot_20220805-170218_Chrome](https://user-images.githubusercontent.com/94744045/183093283-2487f3e7-396a-4677-8071-917ed493a5ff.png)

**Comment by nadiration** [comment]
> ![Screenshot_20220805-170218_Chrome](https://user-images.githubusercontent.com/94744045/183093283-2487f3e7-396a-4677-8071-917ed493a5ff.png)
> 

That's a screenshot could you kindly forward me to a clickable link? Than you.

**Comment by Canny1913** [comment]
https://github.com/orgs/revanced/discussions
