### ISSUE TITLE
feat(YouTube - Comments): Hide 'Thanks' button

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [ReVanced/revanced-patches#3060]
### Feature description

Hides the thanks button near the comment box.
![Screenshot_20240421_184219_YouTube~2](https://github.com/ReVanced/revanced-patches/assets/117499019/a036f164-8cb8-44dc-aa44-ab8f8f1981b8)

### Motivation

Accidental touches can occur given its so close to the comment box and for those people whom don't plan to donate anything anyways. 

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by ILoveOpenSourceApplications** [comment]
I tried various combos but couldn't get it to hide on my end. Let me know if I should try something in particular.
```kotlin
04-21 18:42:06.064 24876 25064 D revanced: LithoFilterPatch: Searching ID: null Path: CellType|comment_thread.eml|bced764a87b9cabe|ContainerType|comment.eml|59e7c0db2c0360a5|ContainerType|ContainerType|ContainerType|ContainerType|ContainerType|ContainerType|engagement_toolbar.eml|4f8a8850372e0a50|ContainerType|engagement_heart_button.eml|db42d7eaa682ab2f|ContainerType|ContainerType| BufferStrings: heart-buttonΓ¥Ö
```

**Comment by ILoveOpenSourceApplications** [comment]
Nevermind, it'll only show up if I try to comment something and I got the relevant litho component. Adding `super_thanks_button.eml` hides the button for comments.
```kotlin
04-21 18:58:18.494 13391 13391 D revanced: LithoFilterPatch: Searching ID: null Path: comment_composer.eml-js-b|26a82fe3bb57f9|CellType|ContainerType|ContainerType|ContainerType|composer_main_action_button.eml-js-b|3cd08dec3c59206d| BufferStrings: super_thanks_button.eml|5282cdb23ee8afcfΓ¥Ö
```

**Comment by oSumAtrIX** [comment]
Send a link where this appears.

**Comment by ILoveOpenSourceApplications** [comment]
This video has it: https://youtu.be/34VZzBWBDN0

**Comment by ILoveOpenSourceApplications** [comment]
Is there anything more required for this one?

**Comment by ILoveOpenSourceApplications** [comment]
@LisoUseInAIKyrios, any holding back from this getting a PR?

**Comment by ILoveOpenSourceApplications** [comment]
I'm sure there'll be others who can test the changes, like @cyberboh or @oSumAtrIX.

**Comment by oSumAtrIX** [comment]
Should be done

**Comment by ILoveOpenSourceApplications** [comment]
> Should be done

You mean will be done?

**Comment by ILoveOpenSourceApplications** [comment]
There's no PR open/merged for this issue yet for this to be closed.

**Comment by ILoveOpenSourceApplications** [comment]
Hi @LisoUseInAIKyrios, can you PR this as well if it's not an issue. Thanks.
