### ISSUE TITLE
feat(YouTube): Hide 'Listen in Music' button in search

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [ReVanced/revanced-patches#3067]
### Feature description

There's a 'Listen in Music' button in search which shows up below mix playlists. A patch to hide it.
![Screenshot_20240422_153350_YouTube](https://github.com/ReVanced/revanced-patches/assets/117499019/43f55f00-132f-41e5-bd4f-83f68854572c)
How it looks if mix playlists is hidden:
![Screenshot_20240422_155914_YouTube](https://github.com/ReVanced/revanced-patches/assets/117499019/840b2762-3090-45ec-94b5-e28f55b70f04)

### Motivation

If the user has both ReVanced YouTube and YT Music, then tapping this button redirects the user to play store rather than the YT Music app. Also, if the user has `Hide mix playlists` on then the button just sits there out of place.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by n1cKz1** [comment]
Alternatively, changing the package name of the app this button opens would also be neat

**Comment by GKid94** [comment]
Same
![Screenshot_2024-04-28-12-35-38-409_app revanced android youtube](https://github.com/ReVanced/revanced-patches/assets/18757054/1aa38c5d-8660-4e8a-8757-5ba9658af394)
![Screenshot_2024-04-28-12-36-56-555_com miui securitycenter](https://github.com/ReVanced/revanced-patches/assets/18757054/282be732-7901-42bb-959e-75d9aa338ba2)

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!

**Comment by ILoveOpenSourceApplications** [comment]
> ```kotlin
> 04-22 15:32:22.501 22440 22440 D revanced: LithoFilterPatch: Searching ID: null Path: button_banner.eml|1adb923c2c384f48|CellType|ContainerType|ContainerType|button.eml|e4d01425197b9e68|ContainerType| BufferStrings: quantum_ic_open_in_new_white_36Γ¥ÖListen in MusicΓ¥Ösans-serifΓ¥Ö%com.google.android.apps.youtube.musicΓ¥Övnd.youtube.music://music.youtube.com/channel/UCedvOgsKFzcK3hA5taf3KoQ?syncid=102703968514377483331%7C%7C&referring_app=com.google.android.youtube-o-ytm&ybp=mgYiCiASHhIaUkRBT0FTWnpBQjRONlBTZnNPd3pBaHhZeVEYAQ%253D%253D"Γ¥Ö%com.google.android.apps.youtube.musicΓ¥Ö>com.google.android.apps.youtube.music.activities.MusicActivity"Γ¥Ö%com.google.android.apps.youtube.musicΓ¥Ö%pcampaignid=inline|youtubeads|9416164Γ¥Önmarket://details?id=com.google.android.apps.youtube.music&referrer=pcampaignid%3Dinline%7Cyoutubeads%7C9416164(Γ¥Ö
> ```

Instead of the app calling into the stock YT Music app package name, we'll have to change it to ReVanced YT Music package name which will open it in ReVanced YT Music instead of redirecting the user to play store (for those who disabled/uninstalled it).

**Comment by ILoveOpenSourceApplications** [comment]
I'm just saying my thought here, no idea whether this is possinle or not.
