### ISSUE TITLE
Cant Install because wrong signature

### ISSUE THREAD

**Issue by hypergnat** [ReVanced/revanced-patches#3069]
### Bug description

I tried to update but I cant because this Error pops out

### Error logs

```shell
INSTALLFAILED_UPDATE_INCOMPATIBLE: Existing package com.google.android.youtube signatures do not match newer version; ignoring!
```

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Thats not an issue with ReVanced. The signature of the app must match any existing app installation.
For support move to one of our links at https://revanced.app.

**Comment by hypergnat** [comment]
Any solutions? I still dont understand why my Phone cant Install the APK what I saved from the manager

**Comment by hypergnat** [comment]
I tried the thing above but none of them worked, only solution was reset my
phone, no its works. Thx the help

LisoUseInAIKyrios ***@***.***> ezt írta (időpont: 2024. ápr.
22., H 19:58):
