### ISSUE TITLE
bug:  (YT Music) Patches fails on version 6.48.51+

### ISSUE THREAD

**Issue by ciro-mota** [ReVanced/revanced-patches#3070]
### Bug description

Attempting to patch YouTube music on versions 6.48.51+ results in errors with logs attached in a pastebin below.

Steps to reproduce:

- Download a youtube music apk with version 6.48.51 or 6.47.53.
- Patch with default patches.
- Behold the errors.

### Error logs

```shell
(Manager logs):
pastebin.com/sJg1quJh
```

### Solution

Fixing compatibility with the latest versions or changing the recommended version to the last working version.

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by epikkoder** [comment]
Version 6.50.53 worked for me.

**Comment by ciro-mota** [comment]
Here the same error persists with the version +6.50.53.

**Comment by NASAModded** [comment]
I had to downgrade to 6.50.53 as 6.51.52 did also not work.
