### ISSUE TITLE
bug (YouTube): 'Download Video' option dissappears from time to time from Homefeed video menu

### ISSUE THREAD

**Issue by dishanagalawatta** [ReVanced/revanced-patches#3072]
### Bug description

'Download Video' option dissappears from time to time from Homefeed video menu
![Screenshot_20240423_020822_YouTube](https://github.com/ReVanced/revanced-patches/assets/113381719/1e583c77-3352-44cb-aed3-c36eb04a2560)

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [ ] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Not a ReVanced but. YouTube issue
