### ISSUE TITLE
(youtube / Hide get premium) Patch is missing a description

### ISSUE THREAD

**Issue by KobeW50** [ReVanced/revanced-patches#3073]
### Bug description

There is no patch description, unlike all other patches.

Also perhaps "get premium" should be capitalized and/or in quotation marks, if it an official term used by YouTube.

![SmartSelect_20231004_203312_ReVanced Manager](https://github.com/ReVanced/revanced-patches/assets/84587632/45f07dae-9601-4ff2-ad14-0c9047622c91)

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
It is not missing a description, it simply doesn't have any.

**Comment by KobeW50** [comment]
Is "get premium" a term used by YouTube? If yes, it should be in quotation marks, and if not a description is necessary.

**Comment by oSumAtrIX** [comment]
Please open an issue regarding this.

**Comment by KobeW50** [comment]
I just realized that this patch used to be within the Hide ads patch but was removed for some reason,l (possibly accidentally?) which explains why it is missing the description.

It used to be it's own patch before this issue was resolved with a commit

https://github.com/ReVanced/revanced-patches/issues/2239
