### ISSUE TITLE
Inconsistent grammar used in toggle description 

### ISSUE THREAD

**Issue by KobeW50** [ReVanced/revanced-patches#3075]
### Bug description

![SmartSelect_20231004_213927](https://github.com/ReVanced/revanced-patches/assets/84587632/4b1d700f-c72c-4417-8f70-ca4b7f04aa5f)

Issues:

1. In the toggle label, "premium" is not capitalized
2. In the toggle label "advertisement" is singular while in the description it is plural. 

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by KobeW50** [comment]
I can pr right now. I just need to know if "advertisement" should be plural or singular

**Comment by oSumAtrIX** [comment]
Sure. Rename to `Hide "YouTube Premium" advertisements"

**Comment by KobeW50** [comment]
Well i assume it's technically `Hide \"YouTube Premium\" advertisements`?

**Comment by oSumAtrIX** [comment]
\ is for escaping the string in Kotlin.

**Comment by KobeW50** [comment]
Is that a yes or no?
