### ISSUE TITLE
feat: Add Original vanced default quality setting

### ISSUE THREAD

**Issue by keatit71** [revanced/revanced-patches#308]
### Type

Functionality

### Issue

The current implementation of remembering the last quality you changed the video to works in revanced but has reduced functionality compared to original vanced since i would want to keep a default of 2k but still watch some videos on lower qualities without changing the default quality back i.e. when on bad internet or trying to save mobile data.

### Feature

The feature i want is the same or as close as default quality feature from old vanced that lets you set the quality you want rather than making the default be whatever you last changed the quality to.

### Motivation

it is irritating to me and may be to others to have to deal with setting quality changing the default rather than having a setting defining what the default quality should be.

**Comment by Canny1913** [comment]
Mobile and WI-FI qualities are already separate.

**Comment by keatit71** [comment]
removed that part then

> Mobile and WI-FI qualities are already separate.

**Comment by Joomsy** [comment]
Would like to see this as well. If I watch something in 4k, and then try to watch something in 1080p, the 1080p video will be automatically dropped to 480p for whatever reason. This doesn't happen inversely. Going from a 1080p video to a 4k video will play it in 1080p, so it seems to only remember the quality setting so long as the video you watch next is available in that resolution.

**Comment by oSumAtrIX** [comment]
A switch to allow the mentioned behaviour of the feaire has been added in the settings.
