### ISSUE TITLE
feat: (twitter) make post buttons bigger in feed

### ISSUE THREAD

**Issue by soredake** [ReVanced/revanced-patches#3080]
### Feature description

It would be nice if there is a patch to make post button bigger in feed, like they've been before musk bought twitter.

Right now, button are unnecessarily small in feed for some reason:
![Screenshot_20240423-210618](https://github.com/ReVanced/revanced-patches/assets/5204968/956fdd97-db81-430a-82fe-f4f2eded127c)

Inside the post button have normal size:
![Screenshot_20240423-211740](https://github.com/ReVanced/revanced-patches/assets/5204968/522e8b75-f306-44ef-ab90-b853074db532)

### Motivation

I hate this small buttons, it's easy to miss them because of their small size.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
They are just slightly smaller than the ones inside the post. The click area is big enough to be a problem
