### ISSUE TITLE
Google Recorder app fails to install

### ISSUE THREAD

**Issue by aleks01100001** [ReVanced/revanced-patches#3082]
### Bug description

The google recorder app fails to install

### Error logs

```shell
this error message shows up:
INSTALL _FAILED VERIFICATION_FAILURE: Integrity check
failed for file://ldata/app/vmdl509%04929.tmp
Close
```

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by KobeW50** [comment]
Mounting the patched app over the original app is required, which I believe is only possible on rooted devices.

**Comment by aleks01100001** [comment]
after reading your comment i tried installing the v1.0.27 with the manager because on that version there werent any restrictions and for the signature to be the same.
After the version was installed i tried installing the current version but the same error message appeared.

**Comment by oSumAtrIX** [comment]
You will need to mount using root as the description of the patch explains
