### ISSUE TITLE
feat(YouTube): Disable double tap to like in Shorts

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [ReVanced/revanced-patches#3085]
### Feature description

A patch to disable double tap to like feature in Shorts.

### Motivation

With the introduction of patches to hide like button in shorts, I noticed that if a user accidentally double tapped and want to remove that double tap, they'll have to go into liked videos and remove it from there. So for someone who really doesn't want to like a Short, this feature would be useful and also avoid accidental liking a Shorts as well. I found #1409, but since it was locked, I decided to open a new issue. Given ReVanced has introduced patches to pretty much remove everything that bothers a Shorts viewer, this will be the last one as well. 

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
The algorithm isn't disturbed by accidental likes. If you see yourself doing that often, enable the like/dislike button to undo it
