### ISSUE TITLE
bug: Revanced Youtube not working 

### ISSUE THREAD

**Issue by Helpiambeingattacked** [ReVanced/revanced-patches#3086]
### Bug description

Version: 19.11.43
Patched in april 21,2024 9AM
Youtube ReVamced stopped working. Probably within 6-1 hours before this post.
I guess anyone could have seen it, so no photos or video.

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [ ] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Properly provide all requested information as instructed in the issue template.
For support move to one of our links at https://revanced.app
