### ISSUE TITLE
feat(YouTube): Add an option to disable the popup regarding whitelisting of ReVanced-Gms

### ISSUE THREAD

**Issue by d-e-n-n-i-s-t** [ReVanced/revanced-patches#3092]
### Feature description

I suggest adding a toggle somewhere deep in the ReVanced settings that enables a user to disable this annoying popup that was [added](https://github.com/ReVanced/revanced-patches/pull/2958) in the last update:

![image](https://github.com/ReVanced/revanced-patches/assets/67392973/0b351e5f-c1f8-4f3d-a544-bf5a11cd9482)

Default behaivor can stay the same as it is now. It's just about adding a possibility to somehow get rid of this popup.

### Motivation

The reason for adding a toggle like that is that ReVanced-Gms doesn't actually need to be whitelisted, and therefore the user shouldn't be annoyed with a popup that prompts him to do so, **every** time the user opens the app.
The patched YouTube app in general works fine with ReVanced-Gms even being set to restricted (more restricted than the default, optimized), and even background play works up to an hour (just haven't tested it longer).
Users not wanting notifications don't need ReVanced-Gms to maintain a connection to Google for GCM.
Apps not absolutely needing to be whitelisted should not be forced to be whitelisted - it's just a matter of principle.

I get that it can resolve issues for some user, but realistically, what is to be said against a toggle that preserves the current behavior by default? Then, only users that know what they get into would actually disable the popup.

Cheers

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Whats the practical reason of disabling whitelist? Because if it is about battery, GmsCore does not consume any considerable amount.

**Comment by d-e-n-n-i-s-t** [comment]
> Whats the practical reason of disabling whitelist? Because if it is about battery, GmsCore does not consume any considerable amount.

The question should be the other way around; Whats the practical reason for **enabling** the whitelisting of ReVanced-Gms in the mentioned scenario? You know, its not that way by default.

**Comment by oSumAtrIX** [comment]
The practical reason is to prevent the app from malfunctioning in the background, even if in your limited experience, it hasn't been a problem. This goes as explained in https://github.com/microg/GmsCore/wiki/Installation

**Comment by d-e-n-n-i-s-t** [comment]
> The practical reason is to prevent the app from malfunctioning in the background, even if in your limited experience, it hasn't been a problem. This goes as explained in https://github.com/microg/GmsCore/wiki/Installation. Back to my question.

The wiki states "as it is required to keep a stable background connection". As I mentioned, for some scenarios, it's NOT required.

I already answered your question in the main post and in my first answer - it's a matter of principle. If it doesn't need to be whitelisted, one shouldn't be forced to whitelist it. Its not that complicated.

Its also not just a "limited experience". I've been using it without a single problem since its release, also for years with Vanced MicroG before, while it was being set to restricted. If there were any problems in the aforementioned scenario (no notifications needed), I would think that I **must** have encountered it, which I didnt.

**Comment by oSumAtrIX** [comment]
> The wiki states "as it is required to keep a stable background connection". As I mentioned, for some scenarios, it's NOT required.

This is half of the story. If the app stops so does apps that depend on it.

I have explained that it is a __necessity__ so arguing about principles here won't work.

**Comment by d-e-n-n-i-s-t** [comment]
> @d-e-n-n-i-s-t did you search before posting? This has been discussed too many times.
> 
> #2973
> 
> #2997
> 
> #3013
> 
> #3041
> 
> #3049
> 
> Battery optimization must be turned off for most devices, otherwise YT can randomly shutdown without any explanation.
> 
> If YT works for you without battery optimization turned off, that means MicroG is already not receiving battery optimizations and "turning off optimizations" effectively does nothing.
> 
> Everytime someone makes this same complaint, data is asked to show there is a noticable difference in battery usage with and without whitelisting. But nobody ever provides said data, because the data shows less than 1% battery and "turning off optimizations" will not make any difference.
> 
> On my device I see MicroG uses 0.1% battery usage despite using YT a lot and battery optimizations are turned off for MicroG.
> 
> You can always root your device, and never be bothered with MicroG ever again.

I searched, but searched for "popup" and "whitelist". And as far as I understand, those issues don't talk about the popup because at the point iof opening the issues, that popup wasn't even introduced yet.

**Comment by d-e-n-n-i-s-t** [comment]
> > The wiki states "as it is required to keep a stable background connection". As I mentioned, for some scenarios, it's NOT required.
> 
> This is half of the story. If the app stops so does apps that depend on it.
> 
> I have explained that it is a **necessity** so arguing about principles here won't work.

No, you haven't explained it, you just stated it. There is no evidence it really is needed in that scenario, and there can't be, because it isn't. But there's no coming through to you, maybe some other dev reads it.

**Comment by oSumAtrIX** [comment]
Since you are getting hung up on me "stating" instead of "explaining", ill make this short.

I'll be happy to add an option if there's a real reason to, but as far as I am concerned, if the app is not excluded from battery optimizations, it **can** exit in background. For that mere reason, unless there's a weighting argument against having it not excluded from battery optimizations, I'll close the issue.

**Comment by oSumAtrIX** [comment]
I won't repeat what I said, feel free to provide the information I asked above or don't bother at all

**Comment by oSumAtrIX** [comment]
Enabling optimization doesn't close the app in the background when you close YouTube. I am not sure why you are arguing when you don't even know that.
