### ISSUE TITLE
bug: The volume should be 1-2-3 instead of 10-20-30.

### ISSUE THREAD

**Issue by allahin** [ReVanced/revanced-patches#3094]
### Bug description

The volume is increased out of 100, not out of 10, and it takes too long to increase the volume. I noticed that it doesn't happen on my Samsung device, but it happens on my Xiaomi device. My device: Xiaomi Redmi Note 12 Pro.

MIUI optimization is turned off.

### Solution

I think it has something to do with Xiaomi devices.

### Additional context

![Screenshot_2024-04-27-10-50-46-464_app revanced android youtube](https://github.com/ReVanced/revanced-patches/assets/166995789/936f5305-87c9-4574-8c61-124e601a4c51)

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
That's the steps your phone reports. We could add a setting for swipe sensitivity though.

**Comment by allahin** [comment]
You'd better do it because it takes a really long time to increase the volume.
