### ISSUE TITLE
bug: YouTube Watermark won't show

### ISSUE THREAD

**Issue by GKid94** [ReVanced/revanced-patches#3096]
### Bug description

The option to hide watermark is disabled and watermark won't show
![Screenshot_2024-04-28-12-36-56-555_com miui securitycenter](https://github.com/ReVanced/revanced-patches/assets/18757054/be68bbf8-1e3c-42fe-9edf-26e379c2b60c)
![Screenshot_2024-04-28-12-40-32-279_app revanced android youtube](https://github.com/ReVanced/revanced-patches/assets/18757054/3cb599b3-23a7-4a65-b5e1-8147640be0ae)
![Screenshot_2024-04-28-12-42-20-482_app revanced android youtube](https://github.com/ReVanced/revanced-patches/assets/18757054/950a30a3-1338-4bba-9580-6f70fdd43edd)

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Just tried it and the watermark shows up correctly

**Comment by GKid94** [comment]
> Check unpatched app (of the same version)

Doesn't show

**Comment by GKid94** [comment]
> Just tried it and the watermark shows up correctly. The channel you are watching doesn't have a watermark

Doesn't show on other videos too
![Screenshot_2024-04-28-16-26-37-138_app revanced android youtube](https://github.com/ReVanced/revanced-patches/assets/18757054/98cf9d70-b79a-4d4c-ad13-e359467f012a)
