### ISSUE TITLE
feat: (YouTube add auto-repeat button)

### ISSUE THREAD

**Issue by bremaya** [ReVanced/revanced-patches#3097]
### Feature description

It would be great to add a button to enable auto-repeat in the video player, especially for checking end-of-video segments in SponsorBlock.

### Motivation

An easier way to enable auto-repeat on YouTube ReVanced.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Loop is already easily accessible from the player settings and unless you have to toggle it every second video, it's fine there
