### ISSUE TITLE
feat: publish patches to maven

### ISSUE THREAD

**Issue by Ushie** [ReVanced/revanced-patches#310]
### Feature description

ReVanced Patches should get published to Maven, so that they can be depended on by other patch bundles

### Motivation

Will allow other bundles to depend on the ReVanced Patches bundle, allowing them to use utilities, abstract patches and so on without having to write the same code and conflict when using both the official and external bundle

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
They are now being published on GH.
