### ISSUE TITLE
bug: add delay before auto playing in feeds

### ISSUE THREAD

**Issue by pwd-github** [ReVanced/revanced-patches#3101]
### Bug description

Unpatched YouTube doesn't auto play videos immediately and thus doesn't full your history with spam, i.e. everything you scroll past. ReVanced seems to remove said delay, this should be added back. 

### Solution

Add a delay before playing videos in feeds, 2-5 seconds is perfect. 

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
No delay is added by any patch.

**Comment by pwd-github** [comment]
> Update your ReVanced. The autoplay history issue was already fixed.

The patches from 5 days ago are better than the current newest patches, but this has been broken for more than a year.

**Comment by oSumAtrIX** [comment]
No it can not, because the spoof app signature patch didn't exist for a year.

**Comment by pwd-github** [comment]
> No delay is added by any patch and no autoplaying video is added to history in the first seconds.

I'm requesting a delay and perhaps you don't have it on, as scrolling the front page fills my watch history with everything I scroll past and has done so for a long time. I spend as much time deleting spam as I do watching videos.

**Comment by pwd-github** [comment]
> No it can not, because the spoof app signature patch didn't exist for a year.

Forgive me for not getting the time exactly right,the issue exists nonetheless.

**Comment by oSumAtrIX** [comment]
Record the issue, also show the patch time in ReVanced Manager in the same recording
