### ISSUE TITLE
bug: (YouTube) Enabling ads doesn't enable ads (solution depends on changing another setting)

### ISSUE THREAD

**Issue by flanter21** [ReVanced/revanced-patches#3103]
### Bug description

I was having issues enabling video ads in revanced. Note that I get a lot of ads on my phone and my laptop so I don't think its because of where I live or smthg.

**What I tried**
- Enabling all ads in revanced settings
- Reinstalling using revanced manager disabling the ads patches

### Solution

Eventually I found out that if you turn off
* Parameters → ReVanced → General Layout → Navigation buttons → Switch create with notifications
it works again.

I suggest that this setting is automatically turned off when someone disables video ads, or that the person is given a popup telling them to do so, so that they aren't confused when ads don't appear anyways.

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by kazimmt** [comment]
It's not a bug
Switch create with notifications spoofs YT to android auto version. & Android auto version doesn't have those ads.

**Comment by flanter21** [comment]
> It's not a bug Switch create with notifications spoofs YT to android auto version. & Android auto version doesn't have those ads.

It may not be a bug, but it makes the enable ads setting useless if you don't turn it off. My issue is that it isn't clear that you must turn it off. I certainly had no idea that this setting was blocking ads before a lot of trial and error. The setting description itself also doesn't mention that it blocks ads, so even if someone finds this setting, which isn't in the ads menu, they would have no idea they have to toggle it or that it has any relation to ads at all.

**Comment by oSumAtrIX** [comment]
@LisoUseInAIKyrios both patches are separate so the ads the patch can't display a dialog about the other patch since it doesn't know anything about it

**Comment by flanter21** [comment]
> @LisoUseInAIKyrios both patches are separate so the ads the patch can't display a dialog about the other patch since it doesn't know anything about it

Maybe you could change the text under “switch create with notifications” to say that it also disables video ads? That way at least it’s visible somewhere and makes the description more accurate.
