### ISSUE TITLE
bug(YouTube): Thumbnails in seekbar are those of the previous played video

### ISSUE THREAD

**Issue by HeroGalak** [ReVanced/revanced-patches#3104]
### Bug description

When seeking in a homepage video the thumbnails are those of the last played video.

![Screenshot_20231007_092444_YouTube](https://github.com/ReVanced/revanced-patches/assets/69464248/2cd712f6-2e7b-47f3-a9df-3246d3989098)

To reproduce open a video, close it, go to homepage and try seeking in another video.

### Error logs

```shell
//
```

### Additional context

Using YT 18.37.36 with patches 2.191.0 and latest manager.

### Acknowledgements

- [X] All requested information has been provided properly.
- [X] I have chosen an appropriate title.
- [X] This request is not a duplicate of an existing issue.

**Comment by HeroGalak** [comment]
> Post a video showing the reproduction steps and shows the wrong thumbnails.  I cannot reproduce the problem myself.

[Seekbar thumbnails bug](https://drive.google.com/file/d/10ts08Dmlw_8Y9lJOT4SYfh-NbdxfZf6l/view?usp=drivesdk)

**Comment by dib12** [comment]
@LisoUseInAIKyrios happening sometimes in shorts also (botton right music of a short shows previous shorts music).
I think its better to spoof all instead of incognito spoof for short
