### ISSUE TITLE
feat(patch): GMAIL

### ISSUE THREAD

**Issue by YashjitPal** [ReVanced/revanced-patches#3106]
### Feature description

patch gmail so that it can be installed without google play service requirements. Im on pc and the website for gmail is very complicated and it is very hard to use the gmail faility on pc so it would be very helpful if it doesnt require google play service and i can install the apk through WSA (Windows Subsystem forAndroid)

### Motivation

it is very hard to use gmail using the website on the browser so it would be helpful if I can install gmail on my pc using WSA but i cannot the install the normal gmail app as normal gmail or any other app as they require playservice which is ot there on WSA. i know that there are android emulators but seriously they take a lot of time to open becuase they are emultaors while WSA is just a subsystem and a tool my microsoft officially so it would be ewasier to access gmail through it. i am making this request the youtube revanced app worked on pc and didnt require me to have play service to be present on WSA while the regular gmail app required the play service thing

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Gmail is a Google app. If you remove play services, you remove the entire functionality of the app

**Comment by Ushie** [comment]
> so it would be very helpful if it doesnt require google play service and i can install the apk through WSA (Windows Subsystem forAndroid)

You can do this by using MagiskOnWSA, which adds GMS and Magisk into WSA
