### ISSUE TITLE
bug: YouTube floating player missing options 

### ISSUE THREAD

**Issue by GKid94** [ReVanced/revanced-patches#3108]
### Bug description

The floating player missing previous and next track buttons 
![Screenshot_2024-05-02-17-40-57-231_com miui bugreport](https://github.com/ReVanced/revanced-patches/assets/18757054/3961a13a-3bdf-431b-b280-09d1c3c60346)
![Screenshot_2024-05-02-18-27-12-601_com miui securitycenter](https://github.com/ReVanced/revanced-patches/assets/18757054/2d37b07d-a9e4-45d9-8540-d2cebfa9670c)

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Thats a YouTube/ your phone behavior, not a ReVanced issue
