### ISSUE TITLE
bug: `ads resources` patch restore

### ISSUE THREAD

**Issue by OxrxL** [revanced/revanced-patches#311]
### Type

Cosmetic

### Bug description

A recent posted issue claimed that some ads are still visibile on tablets (this: https://github.com/revanced/revanced-patches/issues/206)

### Steps to reproduce

...

### Relevant log output

```shell
...
```

### Solution

The best choice at the moment would be restore the resources ads patch (this: https://github.com/revanced/revanced-patches/commit/6c24ebef2fb4f0d58e369ac5bf63e4cab6ca0e80), meanwhile a better method to hide these ads will be found on bytecode.

**Comment by sir-harlekin** [comment]
Is there any more input needed from a Samsung device in use with Revanced?

**Comment by anil-al** [comment]
When will this patch be restored because in the last version of YouTube, I can say, adverts are more frequently shown on my tablet so I want to find if this will fix most of them.

**Comment by anil-al** [comment]
> Is there any more input needed from a Samsung device in use with Revanced?

They need logs, if you can add logs of when an ad shows up, don't stay back

**Comment by anil-al** [comment]
Has it been added, is it why that was closed because I didn't find this among those added with versions.

**Comment by OxrxL** [comment]
> Has it been added, is it why that was closed because I didn't find this among those added with versions.

No, it was closed because it's useless to add a resource patch instead a bytecode patch, to block ads.

Every ads must be toggled.
