### ISSUE TITLE
bug: YouTube - Low quality filmstrip

### ISSUE THREAD

**Issue by 98xe** [ReVanced/revanced-patches#3110]
### Bug description

Occurs when Spoof app signature is toggled on.

- YouTube v18.38.44
- ReVanced patches v2.193.0

![Screenshot_20231007-225058_YouTube](https://github.com/ReVanced/revanced-patches/assets/129218138/146c5e92-daf8-41cc-9941-768e07c429dc)

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by NaabKing** [comment]
I also had the same issue and i didn't know how to "fix" it until i saw this Post.

**Comment by n1cKz1** [comment]
Quality is also low on the new thumbnail preview, which is still on a/b testing i believe, but is starting to become more widespread lately
