### ISSUE TITLE
bug: Not any subscribe button on the channel

### ISSUE THREAD

**Issue by Sudip339** [ReVanced/revanced-patches#3111]
### Bug description

After patching new version there is no any subscribe button on channel. I tried uninstalling and reinstalling and rebooting the device but it still didn't work out. Screenshot on comment 

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by Sudip339** [comment]
![Screenshot_2023-10-08-13-28-20-212_app revanced android youtube](https://github.com/ReVanced/revanced-patches/assets/86889895/43c4efb6-f68c-4d65-81f5-5a1c36b04ad2)
Here is the screenshot

**Comment by Marocco2** [comment]
100% due to this: https://github.com/ReVanced/revanced-patches/commit/6c9baf22614b1be4870be684915445f7a138cf31

In Revanced - Layout - Shorts components disable Hide subscribe button

**Comment by NBruderman** [comment]
Can confirm I have it too
