### ISSUE TITLE
bug: Rif Is Fun: Needs oauth fix

### ISSUE THREAD

**Issue by makotech222** [ReVanced/revanced-patches#3113]
### Bug description

Just thought I'd bring it up. Login currently fails on latest spoof patch due to 'bad client id'. I see the other reddit clients are updated with new code, Rif likely needs the same fix.

Thanks!

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Your Reddit application or patch is setup incorrectly

**Comment by makotech222** [comment]
It was working perfectly fine last week, then all the 3rd party clients broke? The other clients all got an update except Rif. Just making a logical conclusion.

**Comment by oSumAtrIX** [comment]
The the other clients receive are unnecessary for RiF

**Comment by makotech222** [comment]
Ah you are correct. It seems it was having issues since the client-id is stored in a new file in recent updates, and it was causing issues when i patched/installed. I re-did it from scratch and its working now. Sorry for bothering.
