### ISSUE TITLE
bug: RIF Is Fun patch no longer allows login

### ISSUE THREAD

**Issue by happy-harry** [ReVanced/revanced-patches#3115]
### Bug description

After attempting to log into RIF Is Fun, the Reddit login screen redirects to the mobile version of reddit.com, instead of returning to the RIF Is Fun app.

This appears to be a new issue as of about 3 days ago, and is discussed in detail in the following Reddit thread: https://www.[reddit.com/r/revancedapp/comments/1cgki20/cant_login_to_rif_is_fun/](https://www.reddit.com/r/revancedapp/comments/1cgki20/cant_login_to_rif_is_fun/)

The patch being used is "Spoof client"

To reproduce the issue:

1. Install a patched APK of RIF Is Fun (patched using the Spoof Client" patch
2. Attempt to log into the app
3. App says "You are now logged in. You will soon be redirected, and then the Reddit Mobile website opens.

![Screenshot_20240503_110028_rif is fun](https://github.com/ReVanced/revanced-patches/assets/51464239/7737fa90-53f5-494e-8683-993dd8346580)

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by Chriskinda96** [comment]
If anyone is willing to make a patch for this, I'd like to offer a $50 bounty. If anyone else is willing to pitch in please comment as well. Thanks!

**Comment by oSumAtrIX** [comment]
Claiming, I'll reply once I have fixed it.

**Comment by oSumAtrIX** [comment]
Fixed locally with commit `b156cb1d8996c4314d59e3441c6b85d8f704cdff`. Mail me at osumatrix@revanced.app.

https://github.com/ReVanced/revanced-patches/assets/13122796/c345a3d4-1917-4543-9206-708245716a6f

**Comment by Chriskinda96** [comment]
Sent. Thank you!

**Comment by ksnaden** [comment]
Sent.  Thanks for looking into this.  Do we have to wait for this to be a part of a general patch release?

**Comment by Ushie** [comment]
Yes, but there's nothing blocking the dev branch so I'm sure the merge could be done very soon

**Comment by HeercoGrond** [comment]
It appears that this issue has resolved it itself. Using the 4.7.0 patches and the current ReVanced app, it redirects properly and allows you to use the app again.

**Comment by oSumAtrIX** [comment]
This has happened in the past with other oAuth clients as well. Reddit is breaking their own backend https://www.reddit.com/r/revancedapp/comments/1cgki20/cant_login_to_rif_is_fun/l1x9c02/
