### ISSUE TITLE
bug(YouTube): Playback does not work or stops after 8 seconds

### ISSUE THREAD

**Issue by P13rLu1** [ReVanced/revanced-patches#3117]
### Bug description

Video playback stops or buffers and does not work.  Playback works only 8 seconds or so and stops working. Uninstalling and repatching does not help 

https://github.com/ReVanced/revanced-patches/assets/156900057/21b2a63e-8daa-45fa-8541-a6a67e13928e

### Acknowledgements

- [x] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by P13rLu1** [comment]
Youtube issue, sorry guys

**Comment by oSumAtrIX** [comment]
Keeping open to mitigate spam

**Comment by P13rLu1** [comment]
> Keeping open to mitigate spam

O thanks, i read now that is a YouTube issue

**Comment by popy2k14** [comment]
Same issue here with newest patches and recommended version + revanced gmscore + disabled battery optimizations.
Everytime i am logging in, it stops playing after ~10 seconds.

Ps.: Same patched app (which is installed on my second phone, but setup a earlier) is working?
It's also the exact same phone (vendor, model) and android version.

**Comment by P13rLu1** [comment]
> Same issue here with newest patches and recommended version + revanced gmscore + disabled battery optimizations.
> Everytime i am logging in, it stops playing after ~10 seconds.
> 
> Ps.: Same patched app (which is installed on my second phone, but setup a earlier) is working!? (no playback issues)
> It's also the exact same phone (vendor, model) and android version.

That's funny because on official app, the playback goes smoothly

**Comment by raudh1** [comment]
Same issue here, youtube works fine but revanced doesnt and after ten sec it stops working. I've tried different option and solutions on internet but nothing seems to work.
