### ISSUE TITLE
feat(YouTube): Hide full screen clip and remix quick action submenu

### ISSUE THREAD

**Issue by ran-some** [ReVanced/revanced-patches#3119]
### Bug description

Action buttons are not hide properly.
Main problem in remix and clip buttons..
![Screenshot_2023-10-09-09-57-46-307_app revanced android youtube](https://github.com/ReVanced/revanced-patches/assets/126348889/98106679-1e5e-4512-95ee-c826ff7fcd66)
![Screenshot_2023-10-09-09-57-30-389_app revanced android youtube](https://github.com/ReVanced/revanced-patches/assets/126348889/1b4e9f7e-02bd-45ce-b72a-ae49ef71196e)

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [ ] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by johnconner122** [comment]
This patch doesn't hide them in fullscreen.

**Comment by KobeW50** [comment]
Those settings are only to hide the buttons below the video player in vertical mode. The player flyout settings can be found near the bottom of the layput settings if you include the patch. It will give the following options:

![Screenshot_20231009_025523.jpg](https://github.com/ReVanced/revanced-patches/assets/84587632/645430d6-d294-40ee-8e11-bd8dd0211c6f)

It appears that the 'Clip' and 'Remix' options that you see in the flyout menu are from a/b tests.

**Comment by johnconner122** [comment]
It's not a player flyout panel item, it appears when you click these 3 dots:
![Screenshot_2023-10-09-14-38-40-993-edit_app revanced android youtube](https://github.com/ReVanced/revanced-patches/assets/107796137/ed8bfd0b-55c6-4ba3-bfcb-80d9d296a1e8)

**Comment by johnconner122** [comment]
No, it's part of `quick-actions`.

**Comment by oSumAtrIX** [comment]
Considering the only actions for that button are exactly these two, disabling them has no effect. If you don't want to use them, don't use the full screen button to begin with.
