### ISSUE TITLE
"Change Package Name" patch for Gboard (very useful for Iqoo/Vivo users)

### ISSUE THREAD

**Issue by Vipin2003** [ReVanced/revanced-patches#3123]
### Feature description

This request is for adding a patch  which will allow users to detach Gboard from Play Store by using alternate package name.

Currently I'm using IQOO device. For IQOO/Vivo devices, new Gboard's suggestion strip is not optimized. Due to which it doesn't show the full email address in suggestion strip. But older version is completely optimized for them.
In newer Gboard, full address or email is not shown. It is also with long words.

If we use old Gboard with apk, then Play Store automatically updates it with other apps. And it keeps showing in the Updates tab.

And changing the package by own doesn't let the app to open. So, this method fails.

Here are screenshots for better understanding:
**Shows the email : **
![Screenshot_2024_0505_132244](https://github.com/ReVanced/revanced-patches/assets/93650504/fb337ac2-d7e8-4be5-82c8-a671cba28680)

**Doesn't show the Email : **
![Screenshot_2024_0505_132438](https://github.com/ReVanced/revanced-patches/assets/93650504/9cd7ee3a-0e27-4057-89aa-59971736af91)

So please add a package change patch for GBoard to detach it from Play Store.

### Motivation

It will be very useful for IQOO/Vivo users with Gboard users. As there is nothing which can be done by company itself. It just bitch Google's optimization with the app.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by Vipin2003** [comment]
Here, I'm not saying to optimize it....Just saying to add a package name change for it.

**Comment by oSumAtrIX** [comment]
A package name change patch exists and auto updates can be disabled in play store

**Comment by Vipin2003** [comment]
> A package name change patch exists and auto updates can be disabled in play store

And where is the package name change exists?

**Comment by oSumAtrIX** [comment]
It's a universal patch that can be shown by toggling it on in the settings of ReVanced Manager. For support, move to one of our links at https://revanced.app.

**Comment by Vipin2003** [comment]
> It's a universal patch that can be shown by toggling it on in the settings of ReVanced Manager. For support, move to one of our links at https://revanced.app.

You mean that this universal patch will work with Gboard too?

**Comment by Vipin2003** [comment]
On GitHub, there is a repo which shows a method to patch Gboard. But it also tells about 3 Keys which Google applies on Gboard. It need 1 of them to change the package and install it successfully. 
https://github.com/gkpln3/Gboard-Patched
Now can you guide me how can I do it. Or you can update the universal patch to work with Gboard too.?

**Comment by Vipin2003** [comment]
Complete Logs --

`Device Info
ReVanced Manager: 1.21.0-dev.2
Model: I2301
Android version: 14
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.google.android.inputmethod.latin v12.7.11.507749191-release-arm64-v8a (Suggested: Any)
Patches version: v4.7.0
Patches added: Change package name
Patches removed: None
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: true
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Deleting existing temporary files directory
Decoding resources
Executing patches
Applied 1 patches
Compiling patched dex files
Compiled 4 dex files
Compiling modified resources
An error occurred:
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~E-NrKxQQxSQLWbHFi9p--w==/app.revanced.manager.flutter-EcYs8vhmljzfNRBmqM_dMw==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-RRRKTU/revanced-temporary-files/patched/resources/resources.apk, --package-id, 127, --min-sdk-version, 23, --target-sdk-version, 33, --version-code, 108047722, --version-name, 12.7.11.507749191-release-arm64-v8a, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, --warn-manifest-validation, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL690614266810244811.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-RRRKTU/revanced-temporary-files/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-RRRKTU/revanced-temporary-files/apk/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-RRRKTU/revanced-temporary-files/apk/build/resources.zip]
	at brut.androlib.AaptInvoker.invokeAapt2(Unknown Source:563)
	at brut.androlib.AaptInvoker.invokeAapt(Unknown Source:104)
	at app.revanced.patcher.data.ResourceContext.get(SourceFile:0)
	at app.revanced.patcher.Patcher.get(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(Unknown Source:495)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$hTJfH-rv2j-9Y91G5H_L5jFDN6U(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda5.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~E-NrKxQQxSQLWbHFi9p--w==/app.revanced.manager.flutter-EcYs8vhmljzfNRBmqM_dMw==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-RRRKTU/revanced-temporary-files/patched/resources/resources.apk, --package-id, 127, --min-sdk-version, 23, --target-sdk-version, 33, --version-code, 108047722, --version-name, 12.7.11.507749191-release-arm64-v8a, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, --warn-manifest-validation, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL690614266810244811.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-RRRKTU/revanced-temporary-files/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-RRRKTU/revanced-temporary-files/apk/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-RRRKTU/revanced-temporary-files/apk/build/resources.zip]
	at brut.util.OS.exec(Unknown Source:75)
	at brut.androlib.AaptInvoker.invokeAapt2(Unknown Source:542)
	... 7 more `

**Comment by Vipin2003** [comment]
The famous "AppCloner" also not work. Already tried. After trying 2-3 apps like Lucky patcher, etc I came here. Isn't there anything which revanced can deal with it.

**Comment by Vipin2003** [comment]
I know that revanced is not made for that bullshit. But isn't there any way to make that universal patch compatible with the Gboard. ? As it is the last hope. Anything which can be done. That's why I shared the logs of Gboard patching. So that revanced can do something and make it compatible with more Google apps.
