### ISSUE TITLE
You tube revanced not working 

### ISSUE THREAD

**Issue by arthursanath** [ReVanced/revanced-patches#3124]
### Bug description

https://github.com/ReVanced/revanced-patches/assets/79849488/1e6a44ac-c8cf-42ec-ae97-d1d2f475979a

Things I've tried suggested by the community

1. I've tried to optout of optimation of battery in microg and restarted

the app status -nil

2. Tried to remove all play protect from Play Store status -nil

3. Tried to reinstall status-nil

4. Thought this was a you tube bug (saw a post on github) but none I've seen peps with similar issue a 1year old posts tried em all but didn't work.

Last hope this sub. My device OnePlus 12r Android 14.

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
#3117
