### ISSUE TITLE
bug: (YT Music) Song partially play before restarting and playing in full when a single song is played on loop

### ISSUE THREAD

**Issue by ajbjc** [ReVanced/revanced-patches#3125]
### Bug description

When a song is played on loop, it will play fine the first time but when it starts again, it will play the first ~0.5s of the song before restarting the song and playing it without issue until it finishes where the issue occurs again on the next loop.

Using 6.48.52 with all default patches having been successfully installed.

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Follow this and report back:

![1000010148](https://github.com/ReVanced/revanced-patches/assets/13122796/7e519707-75d5-42b9-ac85-2835ddef50fd)

**Comment by ajbjc** [comment]
Tried that, and this is very odd. I was expecting it to be the music ads patch (I started with 3 disabled, including hiding ads, and it worked fine then enabled all default patches except the video ads), yet after reinstalling with all patches to see if the hide music video ads plugin worked, the issue seems to have unexpectedly fixed itself, somehow?

**Comment by ajbjc** [comment]
Had to make a quick edit in case you closed it early because it turns out it doesn't always occur so you might think it's fine but then bugs again. It also made it difficult to test since you'd sometimes need like 10 loops to be sure, but I think I found the issue. Seems like it might be related to the hide exclusive audio playback patch.

**Comment by oSumAtrIX** [comment]
Please confirm the doubt

**Comment by ajbjc** [comment]
Well, I've tested two songs that I've looped by themselves for a while each, and none have had the bug. One was a song that I did have the bug with before (not that the bug only affects certain songs) and the other was a new song I was testing. Both loop fine and the only change I made was not enable that one plugin.

**Comment by oSumAtrIX** [comment]
There's no patch called hide exclusive audio from what I know

**Comment by ajbjc** [comment]
Meant "enable exclusive audio playback". Must've got the name slightly mixed with another patch name

**Comment by oSumAtrIX** [comment]
The patch enables what YouTube Music also does, check if your issue occurs in the unpatched app using the same version and feature on

**Comment by ajbjc** [comment]
Not sure if I can do that as I need to use revanced manager to install an older version of the app, and even if I don't use other patches, I think I still need the Gmscore support patch to be able to run it as I'm doing non-root (I don't think my phone can be rooted). As for with the feature on, I don't have premium so I can't just switch between the two, but when I load up a song (it has no video) that I used to test the bug and set it to loop just the song by itself, I also have no issue. So, not sure how much I can help with that exactly.

**Comment by oSumAtrIX** [comment]
To install the older version of the app you do not need ReVanced Manager. I can not reproduce the error on my end so I'll close this as an issue with YouTube itself, as that sounds the most likely here, until someone can provide more information.

**Comment by ajbjc** [comment]
> To install the older version of the app you do not need ReVanced Manager. I can not reproduce the error on my end so I'll close this as an issue with YouTube itself, as that sounds the most likely here, until someone can provide more information.

But how do I do that? I try to install the apk directly like any other normal apk but that doesn't work, I found a guide (for which there was only one) and it looks like you need root access to do it but from the little info I can find, it doesn't seem like I can be root my phone.

**Comment by oSumAtrIX** [comment]
For support, I recommend to move to one of our links at https://revanced.app, then coming back here

**Comment by oSumAtrIX** [comment]
What's missing now is checking the unpatched app with exclusive audio playback enabled

**Comment by ajbjc** [comment]
Can I make a discussion page to ask for someone to test it for me? The only way, as far as I know, to get the feature enabled on an unpatched version is to get premium which I don't have.

**Comment by oSumAtrIX** [comment]
Sure
