### ISSUE TITLE
feat(Tumblr): Remove ads & "sponsored posts" from feed

### ISSUE THREAD

**Issue by Wiikifox** [ReVanced/revanced-patches#3127]
### Feature description

Remove the advertisements and "sponsored posts" (ads formatted like posts) from the Tumblr app's UI for uninterrupted scrolling.
 
### Motivation

Advertisements appear every few posts. Some are ads that take up the whole screen and must be scrolled by, others are formatted as if they are posts.
The ads are often annoying or objectionable to look at (i.e. advertisements showing earwax removals).

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
The patch already exists.
