### ISSUE TITLE
bug(YouTube - Old video quality menu): Opening video quality menu shows a toast errror

### ISSUE THREAD

**Issue by eria-tarka** [ReVanced/revanced-patches#3128]
### Bug description

When playing a video and displaying the video quality menu, the new menu is displayed despite having the new menu option activated in the settings. And the error in the screenshot is shown.

Manager v1.11.2
Patches v2.193.0 All Default Patches
![Screenshot_20231009-112957](https://github.com/ReVanced/revanced-patches/assets/144094120/88979d58-1f02-46ea-bb98-8796bec6edd3)

YT: 18.38.44
Android 11

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by InakiArzalluz** [comment]
Hi, I've been experiencing the same issue and incongnito mode doesn't seem to fix it.

I've also collected the following logcat from a Youtube build that only includes: 
- Enable debugging
- Old video quality menu
- Vanced MicroG support

[OldQualityMenu.log](https://github.com/ReVanced/revanced-patches/files/12899778/OldQualityMenu.log)

_"OldVideoQualityMenuPatch: onFlyoutMenuCreate failure" appears in line 4902_

**Comment by not-programmer98** [comment]
I also have this issue, but for me after I click advanced, the app crashes and turn into black screen and i have to close it and reopen again.

**Comment by oSumAtrIX** [comment]
Include crashlogs using logcat

**Comment by not-programmer98** [comment]
> Include crashlogs using logcat

I don't know how to do this, but here's what I have. I hope it's helpful.
It's Galaxy Tab A (2016)
Android 8.1.0
This app works normally after disabling show old quality menu

**Comment by eria-tarka** [comment]
Many thanks to the user who uploaded the log, I wanted to do it myself, but I have no idea how the logs are collected. Is there a guide available to read and understand how to do it? I would greatly appreciate it, since we could contribute to improving revanced.

**Comment by not-programmer98** [comment]
> @not-programmer98 the problem is fixed on the dev release. You can patch using a computer and CLI tools, or you can wait until the fix comes to the regular release and use Manager as usual.
> 
> If you wait for the regular release, then either turn off the old quality menu or turn on app spoofing (under ReVanced -> Layout) and pick the 18.20.39 spoof target.

I reinstalled the app today using revanced manager and still have this error
