### ISSUE TITLE
bug(YouTube): "Hide subscribe button" in short components hides button under videoplayer

### ISSUE THREAD

**Issue by HeroGalak** [ReVanced/revanced-patches#3129]
### Bug description

Enable patch in short components and open a video

### Additional context

Using YT 18.38.44 latest patches and manager

### Acknowledgements

- [ ] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by HeroGalak** [comment]
I don't see the reason this issue has been closed. The info i gave are enough to reproduce the bug.

**Comment by johnconner122** [comment]
It's fixed in dev branch.

**Comment by oSumAtrIX** [comment]
It was also in main @johnconner122.
