### ISSUE TITLE
bug(YouTube - Return YouTube Dislike): Invalid video ID parsed in Litho Shorts player

### ISSUE THREAD

**Issue by aliernfrog** [ReVanced/revanced-patches#3131]
### Bug description

A new server-side change puts the video ID in buffer string after the dislike button's name, instead of its icon. Current patch does not support parsing video ID from this new buffer.

This results in RYD request returning a `400`, and dislike count not appearing until the video is voted.

### Solution

Parsing the video ID correctly.

### Additional context

New buffer string looks like this:

shorts_action_bar.eml|ff15c5e6c482074|CellType|ContainerType|ContainerType|shorts_dislike_button.eml|573ad5b1b603aca4|shorts_video_action_toggle_button.eml|32a6f63e1b9396ab|shorts_video_action_button.eml|98eec64184a1c4d2|ContainerType|ContainerType|ContainerType|ImageType| BufferStrings: enme❙sans-serif-medium❙ic_right_dislike_off_shadowed❙id.reel_dislike_button❙Bu videoyu be❙enme❙**xtY3MRjdeF0**:2Cg0KC3h0WTNNUmpkZUYwEAAYASIMCMOnlqkGEMj-gpcBKAQ%3D❙

I have highlighted the video ID (`xtY3MRjdeF0`), it is between dislike button's localized name (`Bu videoyu be❙enme`) and `:`.

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
We already extract the video id from this place, but I am not sure why it does not work until you press dislike, as the id is present in the component when not pressed dislike beforehand too.

**Comment by aliernfrog** [comment]
When the video is disliked, `:` isn't there, but video id can still be found.

enme❙sans-serif-medium❙ic_right_dislike_on_shadowed❙id.reel_dislike_toggled_button❙enmemeyi kald❙**wEZMsuG2GnY**B4Cg0KC3dFWk1zdUcyR25ZGAAgASoLCPvxmKkGELaIoQMwBA%3D%3D❙
