### ISSUE TITLE
feat: (YouTube) Add the "play next in queue" feature

### ISSUE THREAD

**Issue by fadedtoblack** [ReVanced/revanced-patches#3132]
### Feature description

![Screenshot_2024-05-07-00-50-37-34_64ef5fc2000c1caa954c114bb372e1d5](https://github.com/ReVanced/revanced-patches/assets/135118321/63a0c76d-894f-46c1-bdcb-08e9e635a0ea)
Add a "play next in queue" feature, equal to the one currently available with YouTube Premium. Much like with Spotify, you should be able to add videos to the queue, that will automatically play next.

### Motivation

Many use YouTube passively to play videos or music in the background. Having a queue like on Spotify makes it more malleable to personal, spontaneous use. For example while watching one video, one could look for videos to watch next, without having to remember it or having to add it to your watch later playlist, as it probably gets overfilled anyways. This would implement a key feature for people using YouTube to listen to music or as background noise.

### Acknowledgements

- [ ] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
#956
