### ISSUE TITLE
 Sound boost option needed.

### ISSUE THREAD

**Issue by Dim7x0** [ReVanced/revanced-patches#3132]
### Feature description

YouTube equalizes the sound level, but its level is not enough for an acceptable input signal for an Android-based amplifier.

### Motivation

YouTube has very quiet sound. I have to turn the speakers up almost to full volume. But when you download a video from YouTube, the sound is normal.

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by KobeW50** [comment]
Similar to https://github.com/ReVanced/revanced-patches/issues/930
