### ISSUE TITLE
Bug: Hiding creator watermark no longer works

### ISSUE THREAD

**Issue by NBruderman** [ReVanced/revanced-patches#3139]
### Bug description

For some reason, in the latest patch, the creator watermark re-appeard,
and stays on even when disabled in the settings. 

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Please follow this and report back:

![image](https://github.com/ReVanced/revanced-patches/assets/13122796/c6a83275-0f61-4d9f-be90-58f98666b6e3)
