### ISSUE TITLE
feat: Auto update apps in Revanced Manager

### ISSUE THREAD

**Issue by GKid94** [ReVanced/revanced-patches#3141]
### Feature description

Add an option to auto update apps in Revanced Manager so it's easier for the users

### Motivation

It will be much easier for the users

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
ReVanced Manager does not auto update apps.
