### ISSUE TITLE
bug(YouTube - Minimized playback): Shorts are getting the old buggy pip

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [ReVanced/revanced-patches#3142]
### Bug description

If the user plays shorts right after watching a video and then minimizes the app, it'll end up creating the old shorts button abomination of a pip mode which was taken out of minimized playback due to this.

![Screenshot_20231013-222433~2](https://github.com/ReVanced/revanced-patches/assets/117499019/cd165284-5547-40e4-9486-e8007fdf9aa4)

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by ILoveOpenSourceApplications** [comment]
If shorts is played straight away, it works as normal. If it's played after playing a video then it fails.
Video link:
https://www.veed.io/view/f8288caf-d78c-4302-af42-436aad80a129?sharingWidget=true&panel=

**Comment by ILoveOpenSourceApplications** [comment]
Can you recommend one? I think my previously uploaded video got corrupted. I tried uploading here but I think the size is too much for GitHub.

**Comment by ILoveOpenSourceApplications** [comment]
https://youtube.com/shorts/afU_symkIjM?feature=shared

**Comment by ILoveOpenSourceApplications** [comment]
@LisoUseInAIKyrios, I don't know how to access early integration and hence used RVX which I believe has already merged your commit (I'm not sure, you can correct me if I'm wrong). So I repeated the above steps, when playing a video and the shorts right below it, the buggy pip isn't there anymore. But if I'm playing a video and the shorts from home or searching and playing a video and the shorts from the search and minimizing, the buggy pip is still there.

**Comment by ILoveOpenSourceApplications** [comment]
> @ILoveOpenSourceApplications you can patch the dev release with CLI tools and a computer.

I decided to use CLI. Is it recommended to use thespecified version 11 or is that the only supported JDK version?

**Comment by ILoveOpenSourceApplications** [comment]
I downloaded the latest CLI v4.0.2 but it's not opening. I have the latest JDK version.

**Comment by ILoveOpenSourceApplications** [comment]
Can you provide the steps on how to use CLI (for a noob)?

**Comment by ILoveOpenSourceApplications** [comment]
https://github.com/ReVanced/revanced-patches/assets/117499019/e88aabe9-051a-4a07-a6eb-b7f510e7f82a



For compressions sake and uploading it here, I have sped up the video. Watch it in 0.5x and it should look normal. I used integrations v0.120.0-dev.5, patches v2.195.0-dev.3, cli v4.0.2 & YouTube v18.38.44.

**Comment by ILoveOpenSourceApplications** [comment]
The reproduction steps are very simple.
Step 1:  Play a video in home or from the search(MKBHD in my case).
Step 2: Either pause or minimize the video playing. Don't close the video playing.
Step 3: Play a short in home screen or from the search. 
Step 4: Minimize the app while the shorts is playing. Buggy shorts pip appears.

But after your commit [`7d02774`](https://github.com/ReVanced/revanced-integrations/commit/7d02774ea192510e692e90ae55a86e25ee321926) , this issue which was also present after playing the shorts below a video player is no longer reproducible.

**Comment by ILoveOpenSourceApplications** [comment]
> Or just live with it the way it is now. It's obscure and not a typical use case to minimize the app immediately after rapidly navigating and closing/opening different videos as shown in the reproduction video.

I did it at a fast pace to keep the video length down and hence the size as well. But the issue exist despite the quick playing and minimizing of the app.

**Comment by ILoveOpenSourceApplications** [comment]
Sometimes immediately and sometimes it'll happen slowly as well. Glad that you could reproduce it on your side as well.

**Comment by ILoveOpenSourceApplications** [comment]
But it's not completely fixed @oSumAtrIX.

**Comment by oSumAtrIX** [comment]
Please open a new issue
