### ISSUE TITLE
Videos Stop playing after few seconds

### ISSUE THREAD

**Issue by G3RGES** [ReVanced/revanced-patches#3148]
### Bug description

I'm using Youtube ReVanced version 19.11.43, and MicroG version 0.3.1.4.240913 and I'm posting this here cause I don't know whether it's a bug or something else

the problem started today and it's simply the videos don't play or they play for a few seconds and then stop 
I'v downloaded all versions of MicroG (Yes I uninstalled it and installed an older version still doesn't work) , I tried downloading different versions of Youtube Revanced (from Revanced Manager) 

I checked all permissions for MicroG and the optimization, and everything seems to be fine (in accordance to the requirements), I even rebooted the phone multiple time and still nothing changed the video plays for about 20 seconds and it stops or it doesn't play at all

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by senposage** [comment]
#3117

**Comment by eldepor** [comment]
> > close this
> > #3117
> 
> I didn't see a fix for it

Me neither, been like this for 2-3 weeks but seems a fix has not been found yet unfortunately
