### ISSUE TITLE
YouTube: Prevent the app to close notifications and ability to speedup video by holding it 

### ISSUE THREAD

**Issue by 111ebobo** [ReVanced/revanced-patches#3150]
### Feature description

1:Make the YouTube app not close notifications automatically after it counts 6 I guess. 2: Speeding up videos (in other word making videos speed in 2x) by holding video, with seeking gesture

### Motivation

1: Personally I storing notifications as reminder to watch some videos and sometimes I can leave that notification for a whole day and YouTube can close it just because it wants to show up some other notifications. 2: It's comfortable and it was a feature in older YouTube version (I don't remember what exactly)

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
YouTube does not close any notifications and 2 is still A/B, have to wait for its release.

**Comment by 111ebobo** [comment]
> YouTube does not close any notifications and 2 is still A/B, have to wait for its release.

So why are YouTube notifications closing automatically after a long time?

**Comment by oSumAtrIX** [comment]
Multiple reasons can apply such as your OS doing that or killing the apps in the background
