### ISSUE TITLE
feat: (Netflix) More options for Adjust Playback Speed.

### ISSUE THREAD

**Issue by frogjet** [ReVanced/revanced-patches#3153]
### Feature description

Currently the Netflix app allows you to select different playback speeds from 0.5x, 0.75x, 1x, 1.25x, 1.5x.

If, similar to the patches for YouTube, you could customize these values to be configurable so you could set your own desired speeds.

### Motivation

It would be great to be able to select from more options then the provided, such as 1.75x and 2x.

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
I don't see why you would need more than what Netflix offers
