### ISSUE TITLE
feat(YouTube): Add Piped instances as an alternative video player frontend

### ISSUE THREAD

**Issue by kairusds** [ReVanced/revanced-patches#3153]
### Feature description

* Use instances from https://github.com/TeamPiped/Piped/wiki/Instances (or a custom one in the Settings menu), to replace the default YouTube video player frontend like what the `Block embedded ads` Twitch revanced patch does.

### Motivation

At the moment, it'll take a long time to create a working bypass on how YouTube blocks accounts from playing videos, except on the official app for non-root users.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
The solution to fix playback issues is the same. If you want to use Piped, use NewPipe
