### ISSUE TITLE
MicroG from Vanced not work?

### ISSUE THREAD

**Issue by soursecodeblyatiful** [ReVanced/revanced-patches#3158]
### Bug description

Hello Team! MicroG from Vanced not work? Many users report errors that they have an error in the application. Where can I download or how to install the official new microg?

### Error logs

```shell
YT not work
```

### Additional context

Microg not work

### Acknowledgements

- [ ] This issue is not a duplicate of an existing bug report.
- [ ] I have chosen an appropriate title.
- [ ] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
If you used the GmsCore patch, you'll be redirected to the download page automatically on launch of the patched app
