### ISSUE TITLE
feat: Patch for lock button in video player

### ISSUE THREAD

**Issue by NR8124** [revanced/revanced-patches#316]
### Type

Functionality

### Issue

while watching the video it will help in avoiding unnecessary touches also something like kid mode

### Feature

Patch that can show  lock button in video player

### Motivation

avoiding unnecessary touches

**Comment by NR8124** [comment]
@oSumAtrIX  is this really fixed? cause i cant see any new patch regarding the feature

**Comment by oSumAtrIX** [comment]
You are not supposed to create patch suggestions here:
![image](https://user-images.githubusercontent.com/13122796/183288499-4e6c1ea2-d924-4348-b186-22496c849632.png)
