### ISSUE TITLE
feat: youtube - force old thumbnail preview

### ISSUE THREAD

**Issue by n1cKz1** [ReVanced/revanced-patches#3160]
### Feature description

YouTube has been rolling out a/b testing that also changes the thumbnail preview. It now looks like this.

![Screenshot_2023-10-18-15-04-45-701-edit_app revanced android youtube](https://github.com/ReVanced/revanced-patches/assets/107653639/4cda1e60-ca76-4ba9-9782-4ea4c9eab16d)

This patch would force the client to use the old thumbnail preview instead of the new one.

### Motivation

New preview looks meh. Thumbnails are low quality which makes it look pretty ugly while seeking. Old preview was more simple and looked way better

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
The quality is a bug, check with original YouTube

**Comment by oSumAtrIX** [comment]
Send a picture of the same frame on the unpatched app

**Comment by n1cKz1** [comment]
![Screenshot_2023-10-18-16-18-48-939_com google android youtube](https://github.com/ReVanced/revanced-patches/assets/107653639/e2158072-c88c-42ee-8167-3c723378fe17)
