### ISSUE TITLE
bug: sponsorblock not working

### ISSUE THREAD

**Issue by r0br0y7** [ReVanced/revanced-patches#3161]
### Bug description

Youtube Revanced version 18.38.44 shows a toast notification saying "SponsorBlock temporarily unavailable"

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
SponsorBlock temporarily unavailable

**Comment by r0br0y7** [comment]
Hi oSumAtrIX. what do you mean that this bug is not planned? Are other users not experiencing this? why is my post closed already?
