### ISSUE TITLE
feat: Pitch change (youtube)

### ISSUE THREAD

**Issue by acyc070** [ReVanced/revanced-patches#3162]
### Feature description

Add pitch change feature in youtube

### Motivation

Some videos may have sped-up moments that need to be slowed down or sped up, but without changing the pitch it sounds very bad, so it's worth implementing this feature

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
I don't see how changing the pitch improves anything. YouTube is a video player and not an video editor.

**Comment by acyc070** [comment]
Video Editor? The same feature was implemented in Pure Tuber and NewPipe

**Comment by acyc070** [comment]
Since when did stock YT adjust pitch when changing speed? That's right, never. Always when I set the speed to 0.25 there was some kind of scary robotic sound. Exactly that scary robotic sound means that it YT NOT changing the pitch

https://github.com/ReVanced/revanced-patches/assets/112773735/6c1d377b-0c80-4a77-8aeb-daff8b67d4a1
