### ISSUE TITLE
ReVanced YouTube issue

### ISSUE THREAD

**Issue by Ultra-01** [ReVanced/revanced-patches#3167]
### Bug description

Hi guys,

I hope you're doing great. 

So my issue is that once I open revanced youtube, first the layout looks like this:

![Screenshot_20240515_021624_YouTube](https://github.com/ReVanced/revanced-patches/assets/169716283/4370b394-0648-43b2-a22c-9f358d568e98)

Then after restarting the app it'll look normal, but I'm facing an issue whenever I paly anything whether it's YT short or regular video it stops after 9 seconds and sometimes it won't play at all, but never plays normally. 

I tried everything I know from revanced patcher and pre patched revanced apk, but all have the same issue. The only thing that worked was the old version with Vanced microg, but unfortunately I can only play shorts and everything else won't work due to outdated version. 

Device type: Samsung Galaxy S9+ Tablet. 

Looking forward for your support guys. 

Thanks.

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
The issue occurs on the unpatched version of YouTube of the same version you patch and thus isn't an issue with ReVanced.

**Comment by Ultra-01** [comment]
I tried multiple versions and disabled the original one and all have the same issue! Could you please explain more?  

Thanks.

**Comment by Ultra-01** [comment]
> @Ultra-01
> 
> > It stops after 9 seconds, and sometimes it won't play at all, but never plays normally.
> 
> #3117

Thank you.

I've seen this report, but he's not facing an issue with shorts, my issue with both and it stops playing completely.
