### ISSUE TITLE
Replace YouTube's Downloads page with external downloader's downloads page within YouTube

### ISSUE THREAD

**Issue by HauntedKnives** [ReVanced/revanced-patches#3174]
### Feature description

Replace YouTube's existing Downloads page with a page that shows all downloads of external downloader. So that we can open the downloaded videos from YouTube itself.

### Motivation

Since we can download videos from YouTube using external downloader, it would be great to also access those downloaded videos from YouTube itself. It makes accessing downloaded videos quicker and easier.

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by KobeW50** [comment]
> Not possible. Each external downloader is different 

It can work by setting a file path to retrieve videos from.

**Comment by oSumAtrIX** [comment]
Dupe of #532
