### ISSUE TITLE
bug(YouTube): Video is temporarily frozen while audio plays

### ISSUE THREAD

**Issue by julausrie** [ReVanced/revanced-patches#3179]
### Bug description

I have an problem since an week on YouTube Revanced that videos will freeze the entire application for about 20 seconds while the audio of the video continues playing. I tried turning off "spoof app signature", which actually fixes that issue but the video randomly stops playing after a while, so turning it off is not an good option.

### Solution

Fix spoof app signature

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Did you patch the app with the latest patches?

**Comment by julausrie** [comment]
@LisoUseInAIKyrios 
https://youtube.com/shorts/Pob99OZaRxQ?feature=share

**Comment by julausrie** [comment]
> Did you patch the app with the latest patches?

Yes I patched the app yesterday again to make sure, but that didnt fixed it

**Comment by julausrie** [comment]
@LisoUseInAIKyrios No, the audio keeps playing, you just need to turn your volume up because the video is a bit quiet. And after the lag it jumps to the part of the video where the audio is playing, so the video keeps playing while it freezes.

**Comment by julausrie** [comment]
@LisoUseInAIKyrios I tried it with these patches you said, but that didnt fixed it, it still freezes for some seconds while the audio keeps playing.

**Comment by julausrie** [comment]
@LisoUseInAIKyrios That actually fixed it. 18.x works too. Thanks!

**Comment by julausrie** [comment]
@LisoUseInAIKyrios It didnt changed if I had incognito mode on or with an different YouTube account without version spoofing

**Comment by julausrie** [comment]
@LisoUseInAIKyrios I just noticed that it didn't fixed it sadly, it Still happens. Just it appears only a bit less often. Guess I was only lucky that it didn't freeze while testing

**Comment by oSumAtrIX** [comment]
Enable logging under Misc > Debugging and check if logcat prints anything if you grep for "Spoof"

**Comment by julausrie** [comment]
@LisoUseInAIKyrios where are the logs saved

**Comment by GKid94** [comment]
Same problem, videos just get stuck and keep buffering 😕
![Screenshot_2023-10-23-04-27-17-045_com android settings](https://github.com/ReVanced/revanced-patches/assets/18757054/6e8c0c68-0ac3-4914-af75-00f4c8f70c48)
![Screenshot_2023-10-23-04-27-10-986_com miui securitycenter](https://github.com/ReVanced/revanced-patches/assets/18757054/e42aec96-6f78-4e7e-8e7e-d9818948982e)

**Comment by julausrie** [comment]
@LisoUseInAIKyrios I tried doing that but it says: `127|beyond2q:/storage $ adb logcat | findstr "revanced" > log.txt
/system/bin/sh: adb: inaccessible or not found
/system/bin/sh: can't create log.txt: Permission denied` 
Its pretty complicated so i dont know what to do

**Comment by julausrie** [comment]
@LisoUseInAIKyrios Okay i was successfull this time. Heres the log: 
[log.txt](https://github.com/ReVanced/revanced-patches/files/13076151/log.txt)

**Comment by julausrie** [comment]
Hmm i had debug enabled since yesterday.. The bug is also very strange. I just cant get any video to freeze again, even Videos that froze yesterday dont freeze anymore.

**Comment by oSumAtrIX** [comment]
> turning off signature spoofing fixed the issue

This is unlikely. A/B usually takes some time to turn on. Also, the spoof client patch spoofs the player request to that of someone who is not logged in, so the account should play no role.

We would need logging to determine if the hook is being called, perhaps it may not be due to some A/B changes.

**Comment by oSumAtrIX** [comment]
It is may be possible that a combo of patches causes the issue. For example tablet layout could cause RYD to fail

**Comment by oSumAtrIX** [comment]
Can you try simulating slow connection in RYD and see if the behavior is similar?

**Comment by th1nhhdk** [comment]
I have the same problem, freezes for about 11 seconds before returning to normal

- Spoof app signature doesn't fix the issue
- Same for Clearing Data and settings to default

**Comment by th1nhhdk** [comment]
> @th1nhhdk try some of the other steps including:
> 
> - turn on YouTube incognito mode
> - use a different YouTube account
> - turn on version spoofing (ReVanced -> Layout) and use `18.20.39` or older
> 
> And lastly, try uninstalling ReVanced YouTube and try patching version `18.37.36` (an older but still supported version)

- doesn't work
- nope, doesn't work
- i tried all versions, doesn't work

i'll try 18.37.36

**Comment by th1nhhdk** [comment]
> And lastly, try uninstalling ReVanced YouTube and try patching version `18.37.36` (an older but still supported version)

Oh god, it have the same problem, freezes for about 20 second

**Comment by th1nhhdk** [comment]
> @th1nhhdk if you have a computer, then patch using the previous ReVanced major release described [here](https://github.com/ReVanced/revanced-patches/issues/3179#issuecomment-1775794514) 

is there a step by step instruction? i'm kinda new to patching things

**Comment by th1nhhdk** [comment]
> I would say it might be a bug in YouTube, but you said that turning off signature spoofing fixed the issue.
> 
> If the issue comes back, then you can try patching using ReVanced CLI and use the prior release that does not fix the seekbar thumbnails. That is the only thing I can think of that might be causing the video temporarily freezing (even though I don't think it's the issue).
> 
> You'll need to use the Sept 3rd releases: https://github.com/ReVanced/revanced-patches/releases/tag/v2.190.0 https://github.com/ReVanced/revanced-integrations/releases/tag/v0.117.1 https://github.com/ReVanced/revanced-cli/releases/tag/v3.1.0
> 
> You'll also need to uninstall your existing YT ReVanced, then use CLI to patch YouTube `18.32.39` and install that (cannot install on top of existing since it's a version downgrade).
> 
> But otherwise there's no much else than can be done for now.

It works!, thanks.

**Comment by julausrie** [comment]
@th1nhhdk I havent had the issue for days now. It happened once but then never again. @LisoUseInAIKyrios Is this maybe related to an YouTube issue than Revanced, or not?

**Comment by th1nhhdk** [comment]
> Do one last step, and try patching 18.20.39 using the latest patches.
> Do one last step, and try patching 18.32.39 using the latest patches.

The problem happens with both versions
