### ISSUE TITLE
Material You theme support

### ISSUE THREAD

**Issue by BlazingFlames6073** [revanced/revanced-patches#318]
### Type

Cosmetic

### Issue

It doesn't solve any problem as this feature is only for cosmetic purposes

### Feature

Revanced YouTube would have a theme patch option like Amoled for the Material You function that google introduced with Android 12

### Motivation

The feature would only be for cosmetic purposes for people who like their installed apps to adjust to their device themes

### Additional context

Someone on Reddit seems to have already successfully implemented this a month ago and they even left instructions in their post

https://www.reddit.com/r/revancedapp/comments/vj30pn/i_modified_revanced_amoled_patch_to_use_material/

**Comment by oSumAtrIX** [comment]
wrong place to suggest patches.
