### ISSUE TITLE
feat (YT) : Overlay Button that opens up Android's Native Share Menu.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [ReVanced/revanced-patches#3181]
### Feature description

Please add an overlay button that, when clicked, opens up Android's Native Share Menu.
![Screenshot_2024-03-15-07-46-07-16_c31b32364ce19ca8fcd150a417ecce58](https://github.com/anddea/revanced-patches/assets/91815107/bb38eca3-26fa-494c-852f-cdb6315e7bf3)

### Motivation

• It will save steps/taps for opening Android's Native Share Menu.

• YT's in-built share menu lacks many sharing options, so it's an good idea to directly access the Native Share Menu where every sharing option is served to the user.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Unless you use that function very often which is the case for the majority, clicking one more button isn't any problem

**Comment by oSumAtrIX** [comment]
Sharing to WhatsApp or Telegram is possible via YouTube s share sheet.

**Comment by Aryan-Chauhan** [comment]
> Sharing to WhatsApp or Telegram is possible via YouTube s share sheet.

Telegram, Telegram X, Telegram FOSS doesn't appear there for me.

Also, NewPipe, Grayjay, Firefox doesn't appear there (using these because of playback issue in YT app).

**Comment by oSumAtrIX** [comment]
Telegram does appear:

![Screenshot_20240516-144257](https://github.com/ReVanced/revanced-patches/assets/13122796/910a802d-59a6-4465-9dd2-0b92fd4dfc97)

Anything beyond the commonly used apps, you can use the advanced menu.

**Comment by alba4k** [comment]
@oSumAtrIX I agree on the fact that this shouldn't just be dismissed as "barely useful"

I consider this way more useful than most of the existing patches. Can't there just be an option to make the existing share button open the native share menu immediately, without the extra step of clicking "more"?

kdeconnect doesnt appear in there, neither do custom telegram clients (which a lot of people who use revanced are likely also using). 

Please consider re-opening this and at least giving it some extra thought
