### ISSUE TITLE
feat: Ability to hide redundant text in You Tab.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [ReVanced/revanced-patches#3181]
### Feature description

In the You Tab, these options are redundant and  are of no use: Your videos, Downloads, Your movies, Get YouTube Premium, Time watched, Help and feedback.
![Screenshot_2023-10-22-06-26-00-92_f22faf49515899f9781ec174a4d85388](https://github.com/ReVanced/revanced-patches/assets/91815107/8739aaec-0407-43a9-ba91-f51ce8824d95)

### Motivation

For a more cleaner look.

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
It does not obstruct anything and is not worth the effort.

**Comment by oSumAtrIX** [comment]
How do you accidentally click on it? The playlists are big buttons?

**Comment by oSumAtrIX** [comment]
Refer to [this](https://github.com/ReVanced/revanced-patches/issues/3181#issuecomment-1773960650)
