### ISSUE TITLE
feat (YT) : 3 Overlay Buttons that can open up Quality Menu, Captions Menu & Save To Playlist Menu.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [ReVanced/revanced-patches#3182]
### Feature description

Kindly add 3 overlay buttons in the player UI that can open Quality Menu, Captions Menu & Save To Playlist Menu.

### Motivation

Quality Menu - Less taps & quicker quality switching.

Captions Menu - Less taps & quicker captions toggling.

Save To Playlist - I've hidden all action buttons because of inconsistent padding between them. So, Save To Playlist Menu accessible from an overlay button would be great.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
All are accessible through the player settings & saving to playlist is through action buttons.
