### ISSUE TITLE
feat: function fill the screen bring automatically

### ISSUE THREAD

**Issue by Frontline11** [ReVanced/revanced-patches#3183]
### Feature description

function fills the screen automatically, when we activate the function the screen fills completely without having to place your finger on the display and pinch , the function exists but when we activate it in settings fill the screen is only filled if we place our finger on the display and do pinch mode, that's why I ask this function to be activated and automatically the screen opens completely without doing pinch mode

### Motivation

advanced feature

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by Frontline11** [comment]
Hello SumAtrix, please bring this option to fill the screen automatically
when we activate the function and do not need to place our finger on the
display in pinch mode, when we activate this function the display itself
already fills the entire open screen, bring this to the Revanced please

Em qui., 16 de mai. de 2024 17:18, oSumAtrIX ***@***.***>
escreveu:

**Comment by ego-lay-atman-bay** [comment]
> Insufficient motivation

Here's some motivation for you.

I always watch videos in full-screen, and having the video automatically go into full screen when I tap on it is really nice. I personally use a tweaked youtube app on my ipad that has this feature, and it's really convenient.

**Comment by Ushie** [comment]
And here's some more motivation: you can do it, we're sure! don't be skeptical of yourself, you've always been able to do this kind of thing, this one is no different

**Comment by Frontline11** [comment]
Okay, I'm going to open another more specific one for motivation because
this function would be excellent for everyone, you can activate the key and
when you turn the Smartphone screen the screen is already full without
having to stretch it with your finger with the tweezers

Em sex., 17 de mai. de 2024 01:51, Ushie ***@***.***>
escreveu:

**Comment by oSumAtrIX** [comment]
The motivation does not justify why using the gesture once is such problematic

**Comment by Frontline11** [comment]
It's because the older versions 16 had this automatic option, you activated
it when you turned the smartphone, the entire screen was already filled in
version 17, which YouTube started, but in version 16 it worked, you
activated the function, turned the smartphone and the screen was filled,
there was no need put your finger on the display and do pinch mode

Em sex., 17 de mai. de 2024 07:02, oSumAtrIX ***@***.***>
escreveu:

**Comment by Frontline11** [comment]
It's because the older versions, version 16, had this automatic option, you
activated it on your smartphone, the entire screen was already filled, and
in version 17 it's not automatically filled in, as YouTube started now, but
in version 16 it worked full screen automatically, you activated the
function turned the smartphone and the screen was filled, there was no need
to put your finger on the display and do pinch mode with now you have to

Em sex., 17 de mai. de 2024 07:51, ANDROID 14 ***@***.***>
escreveu:
