### ISSUE TITLE
Fill to zoom

### ISSUE THREAD

**Issue by es419** [ReVanced/revanced-patches#3185]
### Feature description

Since    v18..30 and up fill to zoom isnt working properly.
Pls add and fix the function that does that.
Fill to zoom feature is missing for a long time

### Motivation

This feature is basic necessary youtube feature.
People want to watch videos on size that fit to their phone size and not crop.
Beside, this feature was broken for a long time and a lot of people wants it.
Also, you need to fix just one line of code... this shouldnt suppose to be hard

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
https://github.com/ReVanced/revanced-patches/issues/3183#issuecomment-2117202507
