### ISSUE TITLE
feat: (Firefox Nightly): Force Tablet Mode

### ISSUE THREAD

**Issue by devyat009** [ReVanced/revanced-patches#3190]
### Feature description

An option  to force the tablet mode. This mode is very similar to the desktop version of the app.
![Screenshot_20240518_114133_Firefox Nightly](https://github.com/ReVanced/revanced-patches/assets/91706455/49e23fa6-2988-4a42-87cb-7c4f483e8917)

### Motivation

**Why should this feature be implemented?**
- If implemented, it no longer requires the Samsung Dex for using it in non tablet devices.

**What are the Benefits:**
- Increases productivity of being able to swipe tabs more faster  (principaly good for the ones programing in the browser or multi-tasking in browser like me)
- Firefox Nightly is the few browsers with support to PC extensions  and has a good tablet mode witch behaviors like the PC

**What makes this feature important and what is the explicit use case?**
- When using mouse and keyboard in the device, unfortunately the app forces you to use the mobile layout and websites mobile version, witch is not good for such input. And website mobile versions have way less options, with tablet mode enabled you can use normaly with all the features as in the PC automatically.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Browsers are the last app you want to patch and stop updates for. There's browsers with tabs features such as Bromite or Edge

**Comment by devyat009** [comment]
> Browsers are the last app you want to patch and stop updates for. There's browsers with tabs features such as Bromite or Edge

I can understand about updating the patch for browsers. But its possible to have an universal patch to force Tablet Mode?

You mentioned two brosers, witch I tested and searched about any tabled mode to enable or install extensions normally.
**Bromite:**
- It has an to force tablet mode, but does't change the layout. If disabled its obligated to use Samsung Dex to have the tablet mode, in the flags, tablet options has no effect. As you can see in the image, it has two tabs open, but shows the usual phone layout:
![Screenshot_20240518_154602_Bromite](https://github.com/ReVanced/revanced-patches/assets/91706455/5c7a9956-bcaf-46be-8579-5ee711fbb109)

- No support to Chrome Web Store extensions.
![Screenshot_20240518_154205_Bromite](https://github.com/ReVanced/revanced-patches/assets/91706455/f9c17f8e-8a01-4a07-bef6-8e1a837ad3b6)
 
**Microsoft Edge:**
- No visible tablet mode and in flags doest exist nothing related to tablet.
- No support extensions.
Cant call extension support when you have 2 options: 
![Screenshot_20240518_154901_Edge](https://github.com/ReVanced/revanced-patches/assets/91706455/974b172a-a6f7-47ac-a9ff-b4f8d6db12f5)
Neither when in store says compatible but doest let you add:
![Screenshot_20240518_154950_Edge](https://github.com/ReVanced/revanced-patches/assets/91706455/53fd4e15-35c1-462d-ade6-5b0817f77710)

**Comment by oSumAtrIX** [comment]
Its a dedicated feature in the settings of the browser. Opera has it too. In any case, this isn't a place to discuss apps. A Chromium patch is unviable.
