### ISSUE TITLE
bug: notif wont update

### ISSUE THREAD

**Issue by luyparala** [ReVanced/revanced-patches#3194]
### Bug description

Notification on youtube wont update
![Screenshot_20240520-115140](https://github.com/ReVanced/revanced-patches/assets/111422193/6fdd5532-b68f-46d1-b671-9a1e166ac030)

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [ ] All requested information has been provided properly.

**Comment by kazimmt** [comment]
Turn on Goggle Device Registration on MicroG Settings
Remove MicroG from Battery Optimization & Enable AutoRun

**Comment by oSumAtrIX** [comment]
Provide all requested information properly
