### ISSUE TITLE
UI issues 

### ISSUE THREAD

**Issue by KKdessu** [ReVanced/revanced-patches#3194]
### Bug description

ReturnYouTubeDislikes has been having issues recently and somehow it is affecting the entire UI on both regular videos, and shorts. 
When you open a video, it starts playing, but nothing else loads in for a solid second or two, until the API timeout error pops up. After that everything loads pretty much instantly. 

### Solution

Disabling RYD seems to fix the API issues for now. 

### Additional context

Additional context: this is on Android 13, latest recommended version of YouTube with pretty much every recommended patch enabled.

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [x] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by KKdessu** [comment]
Additional context, this is on Android 13, latest recommended version of YouTube with pretty much every recommended patch enabled.

**Comment by oSumAtrIX** [comment]
RYD blocks the UI thread, which is a limitation of the patch. The timeout can only be decreased and the patch can disable itself and retry to connect at random intervals.

**Comment by KKdessu** [comment]
Noted , thanks for the response. Any way to set it to load in the background instead? I suppose that could be a suggestion for the future to look into. 
Aside that thanks for the response.

**Comment by oSumAtrIX** [comment]
It also blocks the regular player UI as the issue originates from the same hook. RYD should attempt to load RYD once and then do background checks in intervals in a different thread instead of timeouts every time a video is loaded. This way the UI will not be blocked and RYD will be available once the background thread reports that it is.

**Comment by oSumAtrIX** [comment]
> and it does not retry that video again until at least 2 minutes has passed

In my experience, the RYD patch blocked the UI for ever video when the API was down. 

> does not retry that video again until at least 2 minutes has passed.

What I mean is that it does retry in a background thread, instead of in the actual main thread, this way after X minutes, if the API is still down the UI won't be blocked.
