### ISSUE TITLE
feat: stop clicked links from directing you to a youtube.com domaine before rederecting you to the original website

### ISSUE THREAD

**Issue by KhalidSzyslak** [ReVanced/revanced-patches#320]
### Type

Functionality

### Issue

currently when you click on a link from the description of video of let's say a Twitter/twitch profile etc, it opens a YouTube.com domaine for a brief moment before it redirects you to twitter.com or whatever the original link is, this results in the link opening in the browser instead of it opening in the corresponding app which is very irritating for me at least.

### Feature

if it's possible to make it so that the original link get opened immediately that would make it so that it takes you directly to it's corresponding app

### Motivation

often you're not signed in to your Twitter/twitch etc accounts on you browser and only use the app for that, or the experience on the browser is just shit and you prefer using the app for it. opening the link on browser doesn't make any sense

**Comment by AMSAMSAMSAMS** [comment]
opening Youtube suggestion from Google search is opening the original YouTube app or PlayStore page if disabled/uninstalled...

**Comment by giejay** [comment]
For me its opening the YouTube web page after I disabled the original YouTube app. Any way to open it in Revanced?

**Comment by Indranil012** [comment]
> For me its opening the YouTube web page after I disabled the original YouTube app. Any way to open it in Revanced?

![Screenshot_20220908-195244_Settings](https://user-images.githubusercontent.com/48489074/189147456-aeb069c8-84ba-4827-998e-adf110921019.png)

**Comment by autodistries** [comment]
I know I'm opening a grave but is there any chance this would get implemented ? 
- It's tracking
- It prevents from directly opening links in-app

**Comment by oSumAtrIX** [comment]
Its tracking before you open a link anyways

**Comment by autodistries** [comment]
Yeah but still it would avoid the browser -> open in app step when opening a link

**Comment by Joshix-1** [comment]
The redirect is really annoying and useless. It wastes time and band-width.

**Comment by autodistries** [comment]
Thank you
