### ISSUE TITLE
feat: "Fix reddit share links" patch for older Relay versions

### ISSUE THREAD

**Issue by Caddy8970** [ReVanced/revanced-patches#3203]
### Feature description

Im talking about a way to open reddit's new share links (example: www.reddit.com/r/sub/s/insertfunnynumbershere) as there's no way to patch the latest Relay version that fixes this issue

### Motivation

For some reason, there's no way to patch Relay's latest versions without the manager puking errors so adding this would be nice

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Older relay versions is pointless to support. At max, the patches can be bumped to support the newer versions.

**Comment by Caddy8970** [comment]
> Older relay versions is pointless to support. At max, the patches can be bumped to support the newer versions.

Yeah, this is a better option
