### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by harshraisaxena** [ReVanced/revanced-patches#3206]
### Bug description

i just installed the ReVanced after the playback buffer issue is fixed. i can see the playback speed patch while patching the yt apk but the playback option is not available on the video. i can change the default speed but not while watching something.
steps to reproduce -
1. open yt app
2. open any video
3. open the gear icon
4. check if the playback option is visible or not
![Screenshot_2024-05-21-14-05-01-43_64ef5fc2000c1caa954c114bb372e1d5](https://github.com/ReVanced/revanced-patches/assets/59499768/d9138060-b326-4f63-a2a3-b9bc98a07340)

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
@cyberboh can you contact me at osumatrix@revanced.app? Offtopic but you have no contact methods
