### ISSUE TITLE
bug(YouTube - Spoof client): audio track flyout menu is missing

### ISSUE THREAD

**Issue by yonggamer** [ReVanced/revanced-patches#3209]
### Bug description

is missing
![Screenshot_20240521-125045](https://github.com/ReVanced/revanced-patches/assets/24843208/111ddb3e-699f-42e4-81de-816b0c385bb8)
[selected_patches_2024-05-21_12_27_34.json](https://github.com/ReVanced/revanced-patches/files/15388859/selected_patches_2024-05-21_12_27_34.json)

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Moving to https://github.com/ReVanced/revanced-patches/issues/3208
