### ISSUE TITLE
bug(YouTube - Spoof client): music is missing in description

### ISSUE THREAD

**Issue by yonggamer** [ReVanced/revanced-patches#3210]
### Bug description

[selected_patches_2024-05-21_12_27_34.json](https://github.com/ReVanced/revanced-patches/files/15389043/selected_patches_2024-05-21_12_27_34.json)
![Screenshot_20240521-131433_YouTube](https://github.com/ReVanced/revanced-patches/assets/24843208/4f3120d9-e746-4dec-a813-40dd66d7714b)

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
The music section is hidden by a patch, and not a side effect of the client spoof

**Comment by yonggamer** [comment]
what patch does hide
![Screenshot_20240521-131433_YouTube](https://github.com/ReVanced/revanced-patches/assets/24843208/4f3120d9-e746-4dec-a813-40dd66d7714b)

**Comment by kazimmt** [comment]
![image](https://github.com/ReVanced/revanced-patches/assets/82371061/0d4fe97f-304d-43e5-ba0f-5bf2645557b3)
