### ISSUE TITLE
bug: (TikTok) Don't show the auto scroll button 

### ISSUE THREAD

**Issue by khanh48** [ReVanced/revanced-patches#3213]
### Bug description

Tiktok Version: 30.8.4
In the original version, the auto scroll button is displayed. But after patch it doesn't show up anymore.

![Screenshot_20231030_155823_TikTok](https://github.com/ReVanced/revanced-patches/assets/67616753/b08fbd62-1657-4e25-87b0-9d0a46c71a3a)

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Exclude patches until the error is gone report back which one caused it

**Comment by khanh48** [comment]
Oh, I have excluded the patches and the problem is with the "Playback speed".

**Comment by khanh48** [comment]
I think the "Playback speed" patch is not necessary, because even if I uncheck this patch, the playback speed is still displayed in the selection.

**Comment by oSumAtrIX** [comment]
Please open a new issue for that
