### ISSUE TITLE
bug(YouTube - Hide keyword content): Multiple chapter previews shown in search results

### ISSUE THREAD

**Issue by KelvinCrag** [ReVanced/revanced-patches#3214]
### Bug description

When searching for videos, the search results display overlapping sections of random video thumbnails and metadata. This includes chapters and key moments being shown multiple times for a single video entry. 

### Steps to Reproduce the Bug
1. Open the YouTube mobile app an Android device.
2. Tap on the search icon. 
4. Enter the search term "nothing stick". 
5. Observe the search results, particularly the video thumbnails and metadata.

### Image
![Screenshot_20240521-212108](https://github.com/ReVanced/revanced-patches/assets/64832927/6345af13-de1a-47d9-b6b8-0c30545ba440)

### Additional context

Only happens in official Revanced Patch. It's absent on Revanced Extended.

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
The residues is a imitation part of the patch and not an unnoticed bug.

**Comment by KelvinCrag** [comment]
@LisoUseInAIKyrios But I didn't turn on that setting :(

> ![IMG_20240522_051439-COLLAGE](https://github.com/ReVanced/revanced-patches/assets/64832927/655cd0a1-7b45-42de-92c8-6cf88f1059b1)

It happens randomly. Sometimes it shows and sometimes it doesn't, like when I tried searching 'nothing stick' it didn't show again.

Like I also mentioned on the additional context, it only happens on the official Revanced, I don't know if that would be helpful.
