### ISSUE TITLE
bug: (TikTok) Autoscroll button not appearing

### ISSUE THREAD

**Issue by khanh48** [ReVanced/revanced-patches#3215]
### Bug description

When I select the "Playback speed" patch, the auto scroll button is not displayed in the options.

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [x] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by kazimmt** [comment]
https://github.com/ReVanced/revanced-patches/issues/2814 says playback button not appearing
Now you're saying auto scroll button not appearing
Kindly mention the app version too.

**Comment by khanh48** [comment]
> #2814 says playback button not appearing Now you're saying auto scroll button not appearing Kindly mention the app version too.
Tiktok version: v30.8.4

**Comment by khanh48** [comment]
> #2814 says playback button not appearing Now you're saying auto scroll button not appearing Kindly mention the app version too.

Tiktok version: v30.8.4

**Comment by kazimmt** [comment]
Look like this issue also gonna fix with #3389

**Comment by kazimmt** [comment]
Fixed in latest release

https://github.com/ReVanced/revanced-patches/releases/tag/v3.0.0
