### ISSUE TITLE
bug(YouTube): Video playback does not work

### ISSUE THREAD

**Issue by DmacMcgreg** [ReVanced/revanced-patches#3215]
### Bug description

Steps to reproduce:
- Clear Cache and Data on YouTube app
- delete Revanced Manager
- Delete GMSCore
- reinstall revanced manager from official site
- reinstall gms core when prompted
- download suggested youtube apk
- set all patches to default
- patch app, install patch
- open app, open regular video and shorts

Same issue on multiple accounts on this device. 

Please note I've been having this issue for long before most people have (since February or march)

I've tried going into Misc and switching the two toggles about spoof ios client.

The layout also seems weird, with some formatting issues to the video title cards on the main page.

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Attach the following recording:

1. Open patched YouTube
2. Go to settings and show client spoofing being enabled
3. Play a video

**Comment by DmacMcgreg** [comment]
https://github.com/ReVanced/revanced-patches/assets/3266023/95b7a215-2630-471b-8ce2-136d2c74190a

**Comment by oSumAtrIX** [comment]
Disable background play/pip. The issue is very likely caused by your OS and also occurs with pip on the unpatched app.

**Comment by DmacMcgreg** [comment]
@oSumAtrIX  I've turned off Background play under Background & downloads on main settings menu, and still the same.
Second option works, only GmsCore is selected in patches and now videos are playing.

**Comment by oSumAtrIX** [comment]
Follow this and report back:

<img width="390" alt="image" src="https://github.com/ReVanced/revanced-patches/assets/13122796/ebe78b4d-bf9f-4c67-b605-01f95e2dbc67">

**Comment by DmacMcgreg** [comment]
@oSumAtrIX Thanks, seems it was the minimized playback patch. Turned it off, and its working again. No idea why..

**Comment by oSumAtrIX** [comment]
The issue with minimized playback is reproducible on certain OS' with the unpatched app.
