### ISSUE TITLE
bug: Swipe up to full-screen 

### ISSUE THREAD

**Issue by Fearmipan** [ReVanced/revanced-patches#3216]
### Bug description

Can't swipe up to full-screen mode (landscape) 
Swipe down to minimize (back to portrait) is not working too. 

### Error logs

```shell
No log, app still running no crashing/force stop
```

### Additional context

YouTube: 19.11.43
ReVanced/revanced-patches-4.8.1.jar

### Acknowledgements

- [ ] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
#1257
