### ISSUE TITLE
feat(Youtube): Add FCast support for streaming to Android TVs

### ISSUE THREAD

**Issue by mcbyte-it** [ReVanced/revanced-patches#3216]
### Feature description

FCast is an open-source protocol that enables wireless streaming of audio and video content between devices, supporting various stream types such as DASH, HLS, and mp4.

Project repository: https://gitlab.futo.org/videostreaming/fcast

FCast allows the app (Currently Grayjay app) to stream youtube to Android TV's having the FCast Receiver app installed there.

### Motivation

Youtube Revanced does not support streaming to TV's

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
This should be used in GmsCore, otherwise too much effort to realize.
