### ISSUE TITLE
Display error in the whole app.

### ISSUE THREAD

**Issue by Ergoprett** [ReVanced/revanced-patches#3219]
### Bug description

I've got a new phone and wanted to download YouTube revanced as usual. I used the recommended version and the recommended plugins but now everything is displayed wrong. 
![Screenshot_20240522-171335](https://github.com/ReVanced/revanced-patches/assets/87259731/2feaabc2-90c3-4e8f-be9b-eab0a9a9b9d6)
![Screenshot_20240522-171253](https://github.com/ReVanced/revanced-patches/assets/87259731/f10a005f-0708-4856-9900-c3647961db47)
![Screenshot_20240522-171343](https://github.com/ReVanced/revanced-patches/assets/87259731/f15a803b-f9f9-4b76-a56e-06493e31d39b)

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Restart the app. Not a ReVanced bug.

**Comment by Ergoprett** [comment]
Well I'm really embarrassed you're completely right.
Sorry for bothering.
