### ISSUE TITLE
bug(Youtube): Dragging up in videos doesn't go full-screen

### ISSUE THREAD

**Issue by H4zh4n** [ReVanced/revanced-patches#3222]
### Bug description

When I drag the video up for it to go full screen it doesn't work. it used to work without issues in the patch before.
I have noticed that It does still work on Live streams, but on normal videos it doesn't seem to work.

# In Videos
https://github.com/ReVanced/revanced-patches/assets/47919702/9b129941-fc5d-4a33-91f0-4701527d858f

# In Live streams
https://github.com/ReVanced/revanced-patches/assets/47919702/a3cc169a-8d77-45c8-866b-71eefee47bbf

# Patches used
Everything except [`Change header`, `Theme`]

# Versions
- Patches v4.8.1
- Youtube v19.11.43

### Additional context

I did try with previous supported Youtube version of 19.09.37, was still same and dragging up didn't work.
This started happening recently couple days ago when I patched with latest [v4.8.1] available.

Much love.

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
#3208
