### ISSUE TITLE
feat: Youtube Nonstop

### ISSUE THREAD

**Issue by Yusei-StarDust** [ReVanced/revanced-patches#3223]
### Feature description

auto skip the pop-up notification "Video paused. Continue watching?"  like the namesake chrome extension.

### Motivation

the notification will interrupt the video play and it is really annoying. I think this feature will strongly enhance the user experience.

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
https://github.com/ReVanced/revanced-patches/issues/824
