### ISSUE TITLE
feat: show translated lyrics additionally in music.youtube

### ISSUE THREAD

**Issue by x3oo** [ReVanced/revanced-patches#3226]
### Feature description

It would be great value for everyone learning new languages to just show the translation. Alternating with the original lyrics.
"Du, du hast"
"You, you have"

### Motivation

Great value to everyone learning languages.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
YouTube Music is a music player and not a language learning application. For that use dedicated apps or videos on YouTube
