### ISSUE TITLE
feat: (everyday Habit Tracker) Unlock premium features

### ISSUE THREAD

**Issue by emukus** [ReVanced/revanced-patches#3229]
### Feature description

[everyday Habit Tracker](https://play.google.com/store/apps/details?id=com.everydaycheckmobile&pli=1) is a simple app for tracking daily habits visually.

The main premium features include:
* Tracking more than 3 habits (this limit is way too low)
* Reminders
* Offline mode (being able to track progress while offline)

### Motivation

The unpaid version is extremely limited to force people to sign up to the premium subscription tier.

It should at least allow users to track more than 3 habits without being forced to pay a constant subscription fee

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Violating contribution guidelines

**Comment by oSumAtrIX** [comment]
Violating contribution guidelines
