### ISSUE TITLE
bug: Chapter thumbnails not show up

### ISSUE THREAD

**Issue by emyaqin** [ReVanced/revanced-patches#3229]
### Bug description

Chapter's thumbnail doesn't show up in any video that has chapter in it. And I don't know if its a bug or feature, but some video got that bigger seekbar and its kinda ugly. I use the 1.196.0 patches with 18.38.44 YouTube app

![Screenshot_20231106-003405_YouTube](https://github.com/ReVanced/revanced-patches/assets/74818814/125374bb-82d7-4c19-a853-f8e8a5b4df8c)

![Screenshot_20231106-003443_YouTube](https://github.com/ReVanced/revanced-patches/assets/74818814/a547e5ed-0c36-46d3-8dc2-b7ff6fa1c56a)

### Acknowledgements

- [x] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Disable patches until the error is gone, report back which one caused it.

**Comment by emyaqin** [comment]
My bad, I wonder if its the bug of YouTube itself, cause I disable every patches and even install the store version, the thumbnail still not showing up

**Comment by oSumAtrIX** [comment]
Simply try on the unpatched app

**Comment by emyaqin** [comment]
I tried and the bugs still there,
