### ISSUE TITLE
bug (YouTube/`Hide playables`): Rename `Hide Playables` to `Hide playables`

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [ReVanced/revanced-patches#3232]
### Bug description

Playables being a category, doesn't seem to require a capital 'P' in the patch setting. So renaming it with a running letter 'p' would be fine.

![332039313-e1e23106-151d-4cb7-a050-d355ae9ad2ab](https://github.com/ReVanced/revanced-patches/assets/117499019/8ea6b686-7a44-4b61-a1f4-94d2576f65e5)

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Iirc Playables is a (product) name similar to "YouTube Shorts" hence why it is in capital letter.
