### ISSUE TITLE
bug: (YouTube - Disable Suggested End Screen) Patch causes strange sound issue when swiping down on video after it has ended

### ISSUE THREAD

**Issue by SameytheHedgehog** [ReVanced/revanced-patches#3234]
### Bug description

After applying the "Disable Suggested Video Endscreen" patch and watching through a video completely, when I swipe down on the video to return to my feed, YouTube makes this rather irritating popping sound that isn't there without the patch.

I have had other patches active with this, but testing with only the Vanced MicroG patch active still causes the weird sound issue.

I tried making a recording of the issue but it didn't seem to pick up the sound.

Slightly unrelated, but as I was about to record, I noticed the suggested video end screen pop up for a second or 2 and then go away.

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by webzeroacs** [comment]
https://github.com/ReVanced/revanced-patches/assets/20047139/03aaa867-06fc-417e-ae7e-0a6b3d343626

It's probably this sound. I'm experiencing it, too. Turning off "Disable Suggested End Screen" will resolve this issue.

**Comment by oSumAtrIX** [comment]
![image](https://github.com/ReVanced/revanced-patches/assets/13122796/376dec59-2f36-47bc-88f5-51ac926705ad)

I believe this may be related.

**Comment by SameytheHedgehog** [comment]
> noise.mp4
> 
> It's probably this sound. I'm experiencing it, too. Turning off "Disable Suggested End Screen" will resolve this issue. I think it's a constant "touch feedback" sound.

Yes, it's that sound exactly.

**Comment by oSumAtrIX** [comment]
one way to solve it is to somehow get the click event handler of the view and invoke it manually, or to figure out why it is being clicked so often

**Comment by oSumAtrIX** [comment]
The reason is that we do not remove the event handler. Inside the handler we simply have to remove the handler itself
