### ISSUE TITLE
Bring back the CHANNELS tab from user's page

### ISSUE THREAD

**Issue by Shane9248** [ReVanced/revanced-patches#3236]
### Bug description

The channels tab from any user has disappeared (even in official YT app)
![Screenshot_20231106-194806](https://github.com/ReVanced/revanced-patches/assets/83491863/bc9353cc-aa88-43e3-83d7-f191a231bf84)

### Solution

If possible please bring back the Channels tab back

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Simply scroll down on the user page

**Comment by yonggamer** [comment]
now it is channels and about tab and on the [website](https://www.youtube.com/@LinusTechTips/featured)
and using app version spoofing (ReVanced -> Layout -> Spoof app version) is not working

**Comment by yonggamer** [comment]
[more here](https://www.reddit.com/r/youtube/comments/17mokdn/am_i_crazy_or_has_youtube_removed_the_channels/)
