### ISSUE TITLE
bug(YouTube - Hide horizontal shelves): 'Watch it again' is not completely hidden

### ISSUE THREAD

**Issue by NichirinSword** [ReVanced/revanced-patches#3237]
### Feature description

Vertical watch history shows in home feed
![Screenshot_2024-05-27-11-43-42-15_d11ae654701a5fadb313ea6fa9a6836f](https://github.com/ReVanced/revanced-patches/assets/98078687/ccde11d5-2231-4a27-9cfe-b7e3d3f5a633)

### Motivation

Watch history in home feed is disturbing, causing clean user experience. 

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by NichirinSword** [comment]
> This looks to be a different layout YT is trying.
> 
> A patch would likely have difficulty changing this layout behavior.
> 
> Try version spoofing to an older version, and that should revert back to a different layout.

Hide horizontal shelves doesn’t hide this thing but I find out this section can be hidden from OG YT app, This section has title watch it again and 3 dot option to select not interested. That hides this thing. But in revanced this option not available, may be some other patch removes the title and 3 dot option.

**Comment by NichirinSword** [comment]
> Yes try turning off patch features until the YT option to hide shows again.
> 
> You may have to repatch and exclude patches, but just turning off ReVanced settings in app might be enough to identify what patch is interfering.

Sorry, I can't confirm which patch interfering as I already closed it from OG YT app. So, this watch history section is not visible in ReVanced or OG app anymore. I think it’s a new type of vertical carousel shelf which partially hides with existing hide carousel shelf patch.

**Comment by oSumAtrIX** [comment]
Reopen once reproducible again
