### ISSUE TITLE
bug: Patching against normal MicroG, app crashes instantly

### ISSUE THREAD

**Issue by perz1val-git** [ReVanced/revanced-patches#3241]
### Bug description

I have a device with LineageOS 21 (android 14) with microg (also called GMS Core) - no google services at all. From my understanding ReVanced GMS core has just a different package name and "some modifications" to allow it running without being installed as a system app. ReVanced manager allows changing package name for GMS Core patch.

I tried with YT Music.

I changed it to:
![Screenshot_20240528-105515_ReVanced Manager](https://github.com/ReVanced/revanced-patches/assets/57048118/f92dd105-8aa3-47d3-a154-5869b8ea2493)

Which should be the same as my microg package "com.google.android.gms"

The app crashed/closed just after being launched.

There is no indicator that it shouldn't be working, so I consider this a bug. The app patched fine and then crashed, so I guess this patches repo is the right place.

I would like to get it working or at least a clear disclaimer/explanation in ReVanced's GMS Core fork readme (seems like the best place to me) that it cannot be done (would like to know why too).

In case it can be fixed, it would be great if the normal microg was added to the select list in patch settings.

I am a dev, not an android dev, but I may give some help if you want to actually get it working. I also have a second degoogled phone that may be used for experimentation.

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
GmsCore whitelists the original signature of the app. Not a ReVanced issue

**Comment by Tun2Sucks** [comment]
try "com.mgoogle"

**Comment by weskerty** [comment]
What to do if you already have an official microG?
or is it mandatory to use the modified microg?

**Comment by oSumAtrIX** [comment]
For support, move to one of our links at https://revanced.app.

**Comment by ParzivalWolfram** [comment]
> What to do if you already have an official microG? or is it mandatory to use the modified microg?

It appears that installing the stock app, then installing the patched app with the "mount" option, works.



> For support, move to one of our links at https://revanced.app.

This is a repo under the GitHub org linked on that page, yes. If the issue is here, the user has already done that.
