### ISSUE TITLE
Add patch for jiotv to make it work on androidtv/fire stick.

### ISSUE THREAD

**Issue by THElegend5** [ReVanced/revanced-patches#3242]
### Feature description

There is no official support for android tv / fire stick for jio tv and when trying to sideload the app the app says device not supported. 

### Motivation

It would be nice to have this patch to be able to run jiotv on fire stick.

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
A Google search showed that JioTV exists for Android TV

**Comment by THElegend5** [comment]
> A Google search showed that JioTV exists for Android TV

@oSumAtrIX it doesn't all patches from xda and such don't work anymore and there jiotv+ version which is for android tv but is instead an app they use for there set top box and not the same as jiotv.

**Comment by oSumAtrIX** [comment]
What is "set top box"

**Comment by THElegend5** [comment]
> What is "set top box"

It is probably an android box provided by jio if you get it's fiber internet service in india and opt to get cable channels too which runs jio tv + and requires a jio fiber login to work.

**Comment by oSumAtrIX** [comment]
The app says it runs on Android TV

**Comment by THElegend5** [comment]
> The app says it runs on Android TV

Yeah that would be jiotv + which is a completely different app from jiotv which I am requesting a patch for. Also pinged you on discord if you would like to continue the conversation there.
