### ISSUE TITLE
bug: Reddit user posts are not showing up in Boost or Infinity

### ISSUE THREAD

**Issue by marovira** [ReVanced/revanced-patches#3244]
### Bug description

The issue is present in the following apps (both patched with latest version of patches + manager):
* Boost v1.12.12. Applied patches: Spoof client.
* Infinity for Reddit v7.1.1. Applied patches: Spoof client, Unlock subscription.

To reproduce:
1. Download any of the aforementioned apps and patch using ReVanced.
2. Sign in with a reddit account.
3. Navigate to the account's profile and open posts. See that none are shown and an error message appears.

The error message depends on the app:
* For boost, the error message reads: `Something went wrong. Check your internet connection...`
* For infinity, the error message reads: `Error loading posts. Tap to retry.`

The issue is being tracked in Infinity Docile-Alligator/Infinity-For-Reddit#1647 as it also appears with manually compiled versions.

I have attached screenshots showing the issue (profiles blurred for privacy)
![bug](https://github.com/ReVanced/revanced-patches/assets/8482308/6f8cf3de-e906-4105-ad35-aabe8fbbbed6)

### Additional context

For Infinity only, a workaround is to switch to anonymous mode, in which case posts will appear correctly. Boost presents the problem in anonymous mode.

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
This is not a bug by ReVanced

**Comment by Compleur** [comment]
I am having the same issue with Sync for Reddit. Looking at a profile's posts give the same error.
![Screenshot_20240529_134058_Sync](https://github.com/ReVanced/revanced-patches/assets/59744359/7f823bef-6c2a-40f6-af6e-3d5db54d4447)

It is not a bug by ReVanced as it appears to be a Reddit bug, however could it be patched?

**Comment by marovira** [comment]
@oSumAtrIX is there anything that can be done on ReVanced to solve this? Or is this entirely within the apps themselves?

**Comment by oSumAtrIX** [comment]
This is entirely the fault of Reddit. This isn't the first time that Reddit breaks something with user agents and reverts it again and it will likely be the case here again. If you have a problem with Reddit, please resolve that with them
