### ISSUE TITLE
bug: Youtube background play not work

### ISSUE THREAD

**Issue by chesskuo** [ReVanced/revanced-patches#3248]
### Bug description

Youtube background play not work in the 4.8.2 patch version.
when I close my screen the video will be stopped, and I turn into setting page is the same situation, the video will be stopped too.

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
#1257
