### ISSUE TITLE
bug: swipe controll

### ISSUE THREAD

**Issue by esperanzality** [ReVanced/revanced-patches#3250]
### Bug description

Sure, here is your text translated into English:

"I'm sorry for my poor English. I turned off the 'Enable full screen with swipe controls' setting, but when I swipe down on the title, it still goes into full screen (portrait mode). Is this a bug? I don't want it to go into full screen."

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [ ] I have chosen an appropriate title.
- [ ] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
This is YouTube standard behavior

**Comment by esperanzality** [comment]
Thank you.
I thought I could disable it before, but was that a misunderstanding?
