### ISSUE TITLE
feat: FreeTube Integration

### ISSUE THREAD

**Issue by Hate9** [ReVanced/revanced-patches#3251]
### Feature description

ReVanced should offer a patch which allows users to subscribe, maintain watch history, and maintain playlists entirely offline using FreeTube's `history.db`, `playlists.db`, and `profiles.db` files/formats (which are very simple: basically just json).
This could be either instead of or in addition to logging in with a real YouTube account - if in addition, the account could still be used for creating comments and such, but the db files would otherwise be where all user data is stored and fetched from.

### Motivation

I love using FreeTube on desktop, but [the android port](https://github.com/MarmadileManteater/FreeTubeAndroid) just isn't there yet. It would be a wonderful extension to ReVanced's existing features if it could be setup to, instead of or in addition to logging in with a YouTube account, use/modify data from FreeTube's `history.db`, `playlists.db`, and `profiles.db` files.
This is similar to and connected to issue #1419, but I think it includes specificity and functionality not included in that feature request, so I'm making it it's own:
- Not just subscriptions, but also history and playlists.
- Specifically suggesting FreeTube's format, as it is one which is expected to remain offline and not required to import/export with another service (like Piped or the like).
- The ability to still login, but only use YouTube's api for fetching videos, making comments, etc. would be extremely useful.

This would significantly improve privacy and user-freedom, while still allowing for maximal functionality.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
ReVanced is patching apps and not rewriting them from scratch.

**Comment by Hate9** [comment]
I... didn't suggest rewriting the app from scratch? Presumably this would just mean replacing the bits of the app that manage subscriptions and history (and playlists) - that sounds like a patch to me.

**Comment by oSumAtrIX** [comment]
Your suggestion requires rewriting the entire app.
