### ISSUE TITLE
feat: option to default to different tabs on startup, including library tab

### ISSUE THREAD

**Issue by HardDiskDog** [ReVanced/revanced-patches#3251]
### Feature description

an option in the revanced settings to choose to defaulting to the library, subscriptions, notifications, etc tabs of the app on every startup, instead of just the home tab

### Motivation

vast reduction of distractions and preventing users getting spontaneously sidetracked by their home tab or sub feed all the time

the endless algorithmic feed of new content that's at best barely possible to avoid on the modern internet is a psychologically-proven immense mental health hazard and burns away free time, particularly for those with attention disorders, autism, etc.

this is quite arguably the most important area capable of being improved by this project, and there are currently barely any options for improving this malicious aspect of youtube's design

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
https://github.com/ReVanced/revanced-patches/issues/2888

You can use shortcuts

**Comment by HardDiskDog** [comment]
there still isn't a shortcut for the library tab. the subscriptions tab is still full of distractions, and backing out of the search page from the shortcut still takes you to the home tab

**Comment by oSumAtrIX** [comment]
Add a shortcut to search and don't click on back. The home tab is not hot it can't hurt you

**Comment by HardDiskDog** [comment]
you need to click on back to get to other tabs. and did you just ignore everything i said about algorithm stuff and mental health, especially for people with common mental conditions? it's 100% undeniable psychology

honestly, why're all software devs nowadays so intensely closed-minded? do you people never think any deeper for how dependent people are on it in their daily lives now? is any design nuance too complex for you to understand beyond your kneejerk gut interpretation of the most superficial of elements of ANYTHING? and then no matter how well someone explains it, you just cover your ears and get all snarkily dismissive. i think if you tried thinking outside the box at all you'd just get an allergic reaction. you never take any design notes from any even remotely older software. revanced cant even get basic menu display design correct in the options menu

i am so sick of all of you textbook, cookie cutter idiots and you being the only defense against corporate predation. especially the ever-increasing gen z ones like you who're so blindly and willfully conditioned into constant attention-crippling distraction shit

im done. go fuck yourself

**Comment by oSumAtrIX** [comment]
Uninstall the app and focus in your metal health, as clearly this is the source of your problem
