### ISSUE TITLE
Allow equalizers on YouTube 

### ISSUE THREAD

**Issue by Joeeeeb5** [ReVanced/revanced-patches#3253]
### Feature description

Allow an equalizer app, like poweramp eq to work on youtube like it does on spotify

### Motivation

Some songs or videos are quieter than others on youtube for some reason. an equalizer would fix that

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by cyberboh** [comment]
Likely same as https://github.com/ReVanced/revanced-patches/issues/930

**Comment by oSumAtrIX** [comment]
#930 & there's eqs which work on any app. Additionally stable volume is a feature in YT

**Comment by Joeeeeb5** [comment]
Poweramp is the most advanced one yet and doesn't work even with DUMP and notification listener permissions. YouTube isn't compatible with equalizers

**Comment by oSumAtrIX** [comment]
The most advanced one yet is not Poweramp but https://github.com/ThePBone/RootlessJamesDSP which is compatible with YouTube.
