### ISSUE TITLE
bug(YouTube - Disable suggested video end screen): End screen suggestions are still shown

### ISSUE THREAD

**Issue by LisoUseInAIKyrios** [ReVanced/revanced-patches#3256]
### Bug description

End screen suggestions are now showing up.  It was previously working, but since a few days ago they've started showing again in both regular and incognito mode.

![End screen suggestions](https://github.com/ReVanced/revanced-patches/assets/118716522/eed9b310-72ed-4163-9eac-ce1dbebc9a9d)

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Is the hook being called?

**Comment by NBruderman** [comment]
Maybe its related to the spoofing? Because I don't spoof my app, and it works just fine for me, I've yet to see the endscreen since the last patches.
