### ISSUE TITLE
feat: rif is fun comments fix

### ISSUE THREAD

**Issue by aubymori** [ReVanced/revanced-patches#3256]
### Feature description

Recently, comments broke in rif is fun (and older official Reddit apps, but that's besides the point). They load fine on every official frontend (latest mobile app, new.reddit.com, sh.reddit.com, old.reddit.com), so this is most likely an API change that broke comments loading on old and unofficial apps.
![image](https://github.com/ReVanced/revanced-patches/assets/44238627/482682e2-671f-4af0-a2b4-acaeb48d9aee)
I'm suggesting a patch that would fix this, and allow us to continue using rif is fun.

### Motivation

I cannot stand the latest official app, the outlined icons are ugly and huge, and the style generally sucks. I'd much rather use the older app like I did until this bug or rif is fun, but it's way more likely that a patch for rif is fun will be made than the old official app, so I'll take what I can get.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
This has to be resolved with Reddit (or #3253)

**Comment by aubymori** [comment]
> This is a bug by Reddit and has to be resolved with them (or #3253)

Oh, I see. Sorry for the false request.
