### ISSUE TITLE
bug: (Reddit) Can't have easy access to secondary accounts

### ISSUE THREAD

**Issue by ZzPSYCHOzZ** [ReVanced/revanced-patches#3257]
[Video for better understandings](https://github.com/ReVanced/revanced-patches/assets/57847604/7ec3375a-3624-4905-96cc-a3292eaf8626)

I updated my reddit app because this I had to uninstall the old one, and with this I had to nele the login again, I did this to my main and to my secondary account, but when I was about to change back to my main account, the option of choosing it appears for a brief moment and then disappeared, not let me change accounts. 

sorry for the bad English

**Comment by oSumAtrIX** [comment]
Follow the issue template
