### ISSUE TITLE
feat: 

### ISSUE THREAD

**Issue by bmrussell** [ReVanced/revanced-patches#3260]
### Feature description

Patch request for ITVX/ ITV Hub https://www.apkmirror.com/apk/itv-plc/itv-hub/

### Motivation

remove video ads please

### Acknowledgements

- [x] I have checked all open and closed feature requests and this is not a duplicate
- [ ] I have chosen an appropriate title.
- [ ] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Acknowledgements not met
