### ISSUE TITLE
AI into Youtube

### ISSUE THREAD

**Issue by fire17** [ReVanced/revanced-patches#3262]
### Feature description

There are so many AI features that will be super helpful
Like:
Asking a question about the current video
Asking a question that finds a video
Alternative recommendation system that is more aligned to my prompt

### Motivation

We just entered the new age of LLMS
No need to wait for Google to release it
All of this could be done today

Thanks and all the best! Love ReVanced!

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Already a native feature & out of scope.
