### ISSUE TITLE
Revanced soft rebooting device

### ISSUE THREAD

**Issue by jakariyaa** [ReVanced/revanced-patches#3263]
### Bug in detail

I've been using the YouTube Revanced 19.11.43 installed (root) for several weeks and have noticed (for several times) that the app causing soft reboots in the device and then it disappears from app list. But the app data somehow persists when I install the application again. 

To be sure the culprit of the soft reboot was Revanced, I've used my phone without it and there was no such issue for that period of time. 

### Reproducing steps

Install Revanced YouTube from the manager using the mount(root) method. And keep using it. Suddenly the phone will soft reboot out of nowhere and bam! YouTube is gone!

### Used patches

Default patches except (excluding GmsCore and including Premium header)

### Solution

Patch and Install again, 
clear data, 
import Revanced settings,
Use untill happens again

### Additional context

I didn't face it in Android 13, only after upgrading. And no other apps do such thing.

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Something in your system is causing the soft boot then. The mount installation merely saves the patched file somewhere and runs the mount command to mount it over the existing installation of the app. For support, move to one of our links at https://revanced.app.

**Comment by jakariyaa** [comment]
Then why the YouTube app is gone after that reboot? (Even if I manually reboot again) And also when I was testing without the Revanced YT, why there was no soft reboot issue? (If Revanced was not causing it in the first place?)

**Comment by oSumAtrIX** [comment]
I don't know what you mean by the app is gone after reboot. Apps don't simply uninstall unless something uninstalls them. The soft reboot issues could happen due to a faulty system. There's many variables and without concrete evidence you can't pinpoint it to ReVanced which is one of the most unlikely causes. Both issues don't belong in this repository. For support, move to one of our links at https://revanced.app.
