### ISSUE TITLE
bug (YT) : Inconsistent spacing/padding between Action Buttons when `Remix`, `Clip`, `Rewards`, `Shop`, `Thanks` are hidden.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [ReVanced/revanced-patches#3268]
### Bug description

When the above mentioned action buttons are hidden, there is an issue of inconsistent padding/spacing as shown below:
![Screenshot_2024-06-01-07-58-32-01_fe557b5c831afa8eecca413bd340ebe7](https://github.com/ReVanced/revanced-patches/assets/91815107/5b5e876d-ee3c-4b6a-8d26-53fe8b4b0dcf)

### Error logs

```shell
No logs.
```

### Solution

Every action buttons should have same amount of padding/spacing with respect to it's left & right neighbour.

### Additional context

No additional context.

### Acknowledgements

- [ ] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
#1653
