### ISSUE TITLE
Twitter Video Download Features 

### ISSUE THREAD

**Issue by Karthikn341** [revanced/revanced-patches#327]
### Type

Functionality

### Issue

Because unable to download twitter videos by native..need 3rd party app..so need this feature 

### Feature

Its helps to avoid 3rd party app installation 

### Motivation

Definitely its usefull to others

**Comment by oSumAtrIX** [comment]
Wrong place to suggest features.

**Comment by Karthikn341** [comment]
> Wrong place to suggest features.

Then i suggest features, there is patches to remove ads..so i request here

**Comment by Mr-Nobody1** [comment]
I wish someone implement this
