### ISSUE TITLE
Check mark of video quality is not present 

### ISSUE THREAD

**Issue by Mohammedibrahim15** [ReVanced/revanced-patches#3270]
### Bug description

Sometimes default quality doesn't have a check mark on the selected quality so i have to check it manually
Is there a solution?
![278798012-855e161f-4691-4e14-8167-ffd78f2bee41](https://github.com/ReVanced/revanced-patches/assets/130897201/ce87f156-aabb-4149-bd96-471290cbac58)

### Error logs

```shell
.
```

### Solution

.

### Additional context

.

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Just a visual artifact. The quality is selected.
