### ISSUE TITLE
feat: apply recent fixes to "customclients" patch to infinity

### ISSUE THREAD

**Issue by soredake** [ReVanced/revanced-patches#3271]
### Feature description

Unfortunately, [this](https://github.com/ReVanced/revanced-patches/commit/495e6d65e7cbae88baa71f8334b9afcf9819deaf) [three](https://github.com/ReVanced/revanced-patches/commit/45b6a08980695ca160388bcb2e5c6e910375ff06) [commits](https://github.com/ReVanced/revanced-patches/commit/68253c0df5cda73345be60baf9ee5f0db940caf8) not included fixes for infinity, so infinity is still broken right now:
![image](https://github.com/ReVanced/revanced-patches/assets/5204968/1063255a-e7da-48ea-9ff6-e5877fc07713)

Would be nice if "customclients" patch can be updated for infinity too.

### Motivation

Right now, login in infinity is broken because of reddit changes, [revanced team fixed most of the apps](https://www.reddit.com/r/revancedapp/comments/1d4svk6/3rd_party_reddit_apps_fixed/), but unfortunately not infinity.

### Acknowledgements

- [X] I have checked all open and closed feature requests and this is not a duplicate
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by soredake** [comment]
@cyberboh I tried apk from releases (not patreon), apk from apkmirror, I cleaned manager data multiple times, result are the same.

**Comment by oSumAtrIX** [comment]
The error seen in your screenshot occurs when you setup the oAuth client incorrectly. For support, move to one of our links at https://revanced.app.

**Comment by soredake** [comment]
@oSumAtrIX I have not changed anything recently (apart from infinity version), it worked for months without a problem (redirect set to `infinity://localhost`), I've written a message to #support in discord.
