### ISSUE TITLE
bug: patched YouTube Music 6.28.52 shutdown immediately after open the app

### ISSUE THREAD

**Issue by yonggamer** [ReVanced/revanced-patches#3273]
### Bug description

patched YouTube Music 6.28.52 shutdown immediately after open the app
List used patches:
- Device Info
ReVanced Manager: 1.15.1
Build: release
Model: SM-G965F
Android version: 10
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.google.android.apps.youtube.music v6.28.52
Patches version: v2.196.0
Patches: Background play, Bypass certificate checks, Codecs unlock, Exclusive audio playback, Hide get premium, Minimized playback music, Music video ads, Remove upgrade button, Vanced MicroG support

- Settings
Allow changing patch selection: true
Version compatibility check: false
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Copying APK
Reading APK
Decoding app manifest
Loading patches
Deleting existing resource cache directory
Decoding resources
Executing patches
Background play succeeded
Bypass certificate checks succeeded
Codecs unlock succeeded
Exclusive audio playback succeeded
Hide get premium succeeded
Minimized playback music succeeded
Music video ads succeeded
Remove upgrade button succeeded
Vanced MicroG support succeeded
Compiling patched dex files
Compiled classes.dex
Compiled classes2.dex
Compiled classes3.dex
Compiled classes4.dex
Compiled classes5.dex
Compiled classes6.dex
Compiled classes7.dex
Compiled classes8.dex
Compiling modified resources
Signing APK
Patched

### Additional context

apk from https://www.apkmirror.com/apk/google-inc/youtube-music/youtube-music-6-28-52-release/youtube-music-6-28-52-android-apk-download/

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by cyberboh** [comment]
I don't have this such issue, patched with cli and all working normally

**Comment by oSumAtrIX** [comment]
Likely missing Vanced MicroG. Install it.

**Comment by yonggamer** [comment]
i have it

**Comment by oSumAtrIX** [comment]
Send crashlogs using logcat
