### ISSUE TITLE
feat (YouTube): remove product ads from the player

### ISSUE THREAD

**Issue by NBruderman** [ReVanced/revanced-patches#3274]
### Feature description

In the last few days, youtube implemented the options for channels to promote their merch under the player, while opening the description.
It can't be removed with the current patches

![Screenshot_20231116-021413~2](https://github.com/ReVanced/revanced-patches/assets/6445601/dc284097-9288-4c50-b5b4-173f2e1af957)

### Motivation

Like another ads removal patches, this will clean the app experience. 

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by johnconner122** [comment]
Litho component is `expandable_list`

**Comment by NBruderman** [comment]
> Litho component is `expandable_list`

Can confirm that after adding it to the filter list, the ads are gone.

**Comment by johnconner122** [comment]
> > Litho component is `expandable_list`
> 
> This will cause false positives

Path is starting with `expandable_list`, so may be when it's index is zero, it is used for products list. Still can't test it until we know false positives.

**Comment by oSumAtrIX** [comment]
There can be many path builder strings that start with this substring. You can test it using custom filter and grep for the prefix substring in logs
