### ISSUE TITLE
feat (Office Docs) - `Unlock Premium` with Faster App Opening in Office Docs

### ISSUE THREAD

**Issue by Vipin2003** [ReVanced/revanced-patches#3275]
### Feature description

I'm here for requesting a patch for [Office Docs](https://play.google.com/store/apps/details?id=documents.excel.word.office&hl=en_US&pli=1) which will unlock `Premium` with no-ads. And also faster app opening. I found it as a good app over Office 365 with all necessary features as other apps like LibreOffice, WPS, etc are heavy apps and takes around 1/2 gb space. It is light-weight.

I'm not going to request anything for this app but there is modified apk (I know you will understand what I mean. but not writing it directly here) available for this app over whole internet. Don't know why. 

### Motivation

Will enhance the app usage and it will be good for those who use this app and tried off with ads in the app.

BTW it will not take too much time of Developers to unlock premium as there is nothing server-sideded in this app.

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Closing according to contribution guidelines of this repo

**Comment by Vipin2003** [comment]
But it is not regarding Payment Bypass

**Comment by johnconner122** [comment]
You can open a separate issue splash screen duration reduction. I noticed it's too long, which is annoying.
