### ISSUE TITLE
feat(Office Docs) - `Splash Screen Duration Reduction`  and `Remove Ads` for OfficeDocs 

### ISSUE THREAD

**Issue by Vipin2003** [ReVanced/revanced-patches#3277]
### Feature description

I'm here for requesting a patch for [Office Docs](https://play.google.com/store/apps/details?id=documents.excel.word.office&hl=en_US&pli=1) which will remove no-ads and also reduce the time on splash screen during opening. As it takes around 10-15 seconds on splash screen.

It is also noticed by one of our revanced contributer.
https://github.com/ReVanced/revanced-patches/issues/3275#issuecomment-1814969436

### Motivation

Will enhance the app usage and it will be good for those who use this app and tried off with ads in the app.

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
This is pointless. If it could load faster it would. It does not take 15 seconds but 2 on my phond

**Comment by Vipin2003** [comment]
I don't know what is at your end. But it is there with me on my 3 homie devices. I mean it  takes too much time to load. Check here : 
![Screenshot_2023_1117_131833](https://github.com/ReVanced/revanced-patches/assets/93650504/523bcf20-be55-4d92-b920-9103984ec6fb)

**Comment by oSumAtrIX** [comment]
Looks like 7 second not 10-14 to me, regardless, check my previous comment

**Comment by Vipin2003** [comment]
> Looks like 7 second not 10-14 to me, regardless, check my previous comment

I know it was not more than 10sec..but it feels to slow. Can't it be reduced to 1-2 sec like other apps. And also annoying ads also. Here, I'm not asking to unlock premium.

**Comment by johnconner122** [comment]
It takes me around 15 secs.

**Comment by oSumAtrIX** [comment]
Report the performance issue to the vendor of the app. We are not in charge of it.
