### ISSUE TITLE
bug: Keyboard Hard-Freezes when oppening the comment reply box

### ISSUE THREAD

**Issue by Splarkszter** [ReVanced/revanced-patches#3278]
### Bug description

When oppening the comment reply box (making a comment) sometimes (constantly, but not always) the keyboard freezes, it happens with OpenBoard, it happens with Samsung Keyboard.

I'm suspecting it has to do with the "word prediction" feature.

Seems to be triggered by the comment box oppening and clossing multiple times by itself when trying to comment.

### Error logs

```shell
No error logs.
```

### Solution

No idea, more research is needed to find the exact cause of the issue.

### Additional context

<img src="https://github.com/Helium314/openboard/assets/90066319/374633cd-c582-41b6-926d-0a6fc601ced4" width=20% height=20%>

<img src="https://github.com/Helium314/openboard/assets/90066319/12e28065-6147-44ee-8c6d-fea59cfea091" width=20% height=20%>

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Exclude patches until the issue is solved, report back which one caused it

**Comment by Pamilg8** [comment]
Lately my Samsung keyboard has been freezing. Maybe not related to ReVanced🤔

**Comment by Splarkszter** [comment]
Sorry i didn't respond, i have been busy with university and didn't open GitHub for some time...

I found [this thread](https://old.reddit.com/r/AndroidHelp/comments/14k5a2o/keyboard_hangs_on_youtube_android_app_when_typing/) with a bunch of people having the same problem (I know it's revanced extended reddit but i'm using normal revanced[this repo] and we are all having the exact same issue).

**Comment by Splarkszter** [comment]
>Exclude patches until the issue is solved, report back which one caused it
Will try if i have the time, currently i can't. Sorry.

>Also try clearing the app data
I did clear data but it didn't solve the issue...

**Comment by oSumAtrIX** [comment]
Once you have time open a new issue with the new details you found
