### ISSUE TITLE
Patch request for Weather craves (la chaîne météo)

### ISSUE THREAD

**Issue by FunkyKwak** [ReVanced/revanced-patches#3279]
### Application

Weather Craves (La Chaîne Météo), by Meteo Consult
https://play.google.com/store/search?q=la+cha%C3%AEne+m%C3%A9t%C3%A9o&c=apps

### Patches
1. Remove adds
2. Unlock free pro version

### Motivation

I tried many apps, this one seems to be the more accurate (at least in my region). But there are so many adds, and more and more are coming with the updates. I would buy the app if there were a single purchase option but it's only a subscription model.

Please patch this app to remove the adds.

Another patch to unlock the pro version would be even better, to get more weather forecast models.

### Acknowledgements

- [X] I have checked all open and closed feature requests and this is not a duplicate
- [X] I have chosen an appropriate title.
- [ ] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Contribution guidelines are violated with the pro unlock patch

**Comment by FunkyKwak** [comment]
> Contribution guidelines are violated with the pro unlock patch

Hi,
Thanks for your answer.
And for the adds removal ? Could this be requested?

**Comment by oSumAtrIX** [comment]
You can use any other app or website for weather info. Given that unlocking pro is basically disabling ads I don't see why we would add a patch for such an app.

**Comment by FunkyKwak** [comment]
Thank you I didn't know this possibility : open source modified apps, looks promising. I will have a look. Because on th play store, I found only apps with adds or apps with unreliable weather sources. Thanks !
