### ISSUE TITLE
bug(Twitch): Settings missing after applying the patch

### ISSUE THREAD

**Issue by mlnrDev** [ReVanced/revanced-patches#3283]
### Bug description

Even though the `Settings` patch for Twitch claims to support versions `17.0.0` and `17.1.0`, in both of these versions, the settings are missing after applying the patch.

### Additional context

<details>
	<summary>Screenshot</summary>
	
![Screenshot_20231117-141509](https://github.com/ReVanced/revanced-patches/assets/42180891/735665af-3436-4bce-9841-12e5ad631dc1)
</details>

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by selfmusing** [comment]
>
![Screenshot_20231119-223954_Twitch](https://github.com/ReVanced/revanced-patches/assets/109387456/4882e1dc-3302-48e6-8683-dab5c80ce92a)

Yes this menu isn't showing on any version after v16.9.1 !!
