### ISSUE TITLE
feat(YouTube Music Revanced) - Patch for matching the colour of minimized player with fullscreen player

### ISSUE THREAD

**Issue by Shane9248** [ReVanced/revanced-patches#3284]
### Feature description

A patch for matching the colour of minimized player with the fullscreen player (like YouTube Music Vanced has)

![Screenshot_20231117-194838~2](https://github.com/ReVanced/revanced-patches/assets/83491863/70a575fb-db33-4b19-9328-9680bc01ddf7)
This is what is currently looks like

![Screenshot_20231117-194745~2](https://github.com/ReVanced/revanced-patches/assets/83491863/f007f850-f1d6-411d-bdf5-6785a40c9174)
This is what YouTube Vanced has and what i request 

![Screenshot_20231117-194901~2](https://github.com/ReVanced/revanced-patches/assets/83491863/68b24dfc-a478-4c75-981f-36378c5f116c)
This is the option in YouTube Music Vanced

### Motivation

I think this looks better and upto date

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
This is to nieche, there is no benefit whatsoever, closing therefor
