### ISSUE TITLE
bug: Shorts on Tablet Look like Regular Videos

### ISSUE THREAD

**Issue by LimitedEdiition** [ReVanced/revanced-patches#3288]
### Bug description

Just patched with the new YouTube apk 18.45.41, and the homepage and the shorts player seems like regular videos instead of the Norman Shorts row on my Samsung Galaxy Tab S7. I have attached an image which shows the top of my feed as a regular list of videos when they should be in the condensed shorts UI. 

https://imgur.com/a/FLjKKjr

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by LimitedEdiition** [comment]
For comparison, this is how it looks on my phone which is patched the same way. I've also double checked to see if any shorts settings are different and if tablet mode was on which it isn't. 


https://imgur.com/a/o1f5jZJ

**Comment by oSumAtrIX** [comment]
Disable/don't use patches until the issue is gone, report back which one caused it

**Comment by CyanWool** [comment]
Try going to Revanced > Layout and enabling tablet layout, I was having similar issues and that fixed it.
(Subscriptions were showing at the top of the screen instead of the side like it does on mobile not tablet and would say error 400 if you clicked on one instead of showing all subscriptions)

**Comment by LimitedEdiition** [comment]
Using the tablet mode does indeed fix it, which I am content with since it solves other issues introduced in the latest YT version like the double tap features not working and since I am using a tablet anyways. You can close this and maybe have the tablet options default to active while patching if it can identify if it's installing to a tablet device, or maybe just a warning if that's not possible.
