### ISSUE TITLE
bug(YouTube - Spoof client): Video replays unintentionally when spoofed to Android VR

### ISSUE THREAD

**Issue by MelvynEzi** [ReVanced/revanced-patches#3288]
### Bug description

Step 1: Let video end normally (seek till last seconds, do not seek until video ends)
Step 2: Lock device
Step 3: Video plays

Does not happen when not spoofing client, spoofing to Android TestSuite (in 4.8.2), and spoofing to iOS (in 4.8.3).

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
https://github.com/ReVanced/revanced-patches/issues/3208

**Comment by MelvynEzi** [comment]
> https://github.com/ReVanced/revanced-patches/issues/3208

Unable to add a comment to that issue with it locked. Would appreciate if this issue is added as a checkbox in that issue's checklist.

**Comment by oSumAtrIX** [comment]
The checkmark is unchecked to indicate its not fixed yet.

**Comment by MelvynEzi** [comment]
> The checkmark is unchecked to indicate its not fixed yet.

The specific bug reported in this issue is not in the checklist of #3208. If it was, I wouldn't have had to create this issue.

**Comment by oSumAtrIX** [comment]
![image](https://github.com/ReVanced/revanced-patches/assets/13122796/d49317b0-cb41-49f6-8db4-ce2d1ee5f7bc)

**Comment by MelvynEzi** [comment]
> ![image](https://github.com/ReVanced/revanced-patches/assets/13122796/d49317b0-cb41-49f6-8db4-ce2d1ee5f7bc)
> 

Then I do hope it's referring to the same issue. And it's not "randomly", but always. Thanks.
