### ISSUE TITLE
feat: Background live stream

### ISSUE THREAD

**Issue by 0xrxL** [ReVanced/revanced-patches#3291]
### Feature description

Currently iOS spoofing doesn't allow the background playback of a live stream.

### Motivation

All the main issues of the app has been solved, except this. Therefore, it's impossible to listen a live stream related to a specific music category and use other apps in the meanwhile.

### Acknowledgements

- [X] I have checked all open and closed feature requests and this is not a duplicate
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
#3208

**Comment by oSumAtrIX** [comment]
Perhaps it's possible to determine if the requested video is live and conditionally spoof to Android VR. Alternatively, the player response can be modified similarly to the existing patches for playback speed as well as player gesture

**Comment by 123jjck** [comment]
> Perhaps it's possible to determine if the requested video is live and conditionally spoof to Android VR.

Yes, just like inotia00 implemented it https://github.com/inotia00/revanced-patches/commit/aabf1ecb97baf5c2020f311fbc9940f31ee54926

**Comment by oSumAtrIX** [comment]
There is no such implementation like I described

**Comment by 0xrxL** [comment]
> There is no such implementation like I described

Inotia00 solution use JSON requests to determine the video type (normal or livestream) and consequently spoof the client to AndroidVR or iOS.

I don't know if it is a good solution (because AndroidVR spoof is affected by autoplay issue), but at the moment it's the only available one.
