### ISSUE TITLE
bug: Issue with `Spoof SIM country` #3116 Patch

### ISSUE THREAD

**Issue by nightznero** [ReVanced/revanced-patches#3293]
### Bug description

Helloz,
I just wanted to use new added Patch on both YT and YTM  but both with same results. As Second option `SIM ISO` works as it should that I cannot pass with `Network ISO`. I was trying diff codes with same results,with error. The main code i was testing it was 310160 (TMobile) but also was trying with AT&T and same results.

### Error logs

```shell
- Device Info
ReVanced Manager: 1.15.1
Build: release
Model: SM-G988B
Android version: 13
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.google.android.apps.youtube.music v6.28.52
Patches version: v2.197.0
Patches: Background play, Bypass certificate checks, Codecs unlock, Exclusive audio playback, Hide get premium, Minimized playback music, Music video ads, Remove upgrade button, Spoof SIM country [Network ISO Country Code: null, Sim ISO Country Code: null], Vanced MicroG support

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: true
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Copying APK
Reading APK
Decoding app manifest
Loading patches
An error occurred:
app.revanced.patcher.patch.options.PatchOptionException$ValueValidationException: The option value "311160" failed validation for networkCountryIso
	at app.revanced.patcher.patch.options.PatchOption.assertValid(PatchOption.kt:79)
	at app.revanced.patcher.patch.options.PatchOption.setValue(PatchOption.kt:44)
	at app.revanced.patcher.patch.options.PatchOptions.set(PatchOptions.kt:31)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(MainActivity.kt:281)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$DSnYi-AHJ8SA5fRWgNkdGCm5Zgw(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda4.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
```

### Solution

Fix or disable untill fix `Network ISO`

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
This is not an [ISO-3166-1 alpha-2 country code](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) equivalent of the MCC (Mobile Country Code).

**Comment by nightznero** [comment]
> This is not an [ISO-3166-1 alpha-2 country code](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) equivalent of the MCC (Mobile Country Code).

So whats the e.x code of MCC in US? 310 doesn't work while Wiki says its MCC

**Comment by oSumAtrIX** [comment]
You need the country code: 
![image](https://github.com/ReVanced/revanced-patches/assets/13122796/6f994de1-ab21-44bd-8717-88d837443972)

**Comment by nightznero** [comment]
> You need the country code: ![image](https://user-images.githubusercontent.com/13122796/284016408-6f994de1-ab21-44bd-8717-88d837443972.png)

Country Code goes to SIM ISO,not to Network? o.O or in both SIM n NETWORK `US` is the answer?
cuz from that I belive in Network should work codes 310/311/312
![Screenshot_20231118_192333_Brave](https://github.com/ReVanced/revanced-patches/assets/61750641/9c1d9d5a-20e3-4c20-ae2a-35ffb529abbb)

**Comment by oSumAtrIX** [comment]
You need the country code:

![image](https://github.com/ReVanced/revanced-patches/assets/13122796/7f455077-b5eb-4d1c-a0af-4fc443c32ae8)
