### ISSUE TITLE
bug(YouTube - Tablet mini player): Mini player buttons are hidden / broken

### ISSUE THREAD

**Issue by LisoUseInAIKyrios** [ReVanced/revanced-patches#3294]
### Bug description

Tablet mini player broke with the latest YT target and the player buttons are missing.

![mini player](https://github.com/ReVanced/revanced-patches/assets/118716522/efb01813-16b3-4d7b-b385-9809af9cbb32)

### Solution

Uninstalling ReVanced YT and patching an older version should avoid the issue until the patch is fixed up.

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
This issue also doesn't look to be caused by any other patch when I tried it locally. The tablet layout is supported by YouTube on tablets so I am wondering what caused it to break in this version. Adjusting the patch kay be necessary

**Comment by flying-night-slasher** [comment]
I have it; I thought it was a weird quirk with just me.
