### ISSUE TITLE
bug: Unable to use alternate api sources

### ISSUE THREAD

**Issue by Freaku17** [ReVanced/revanced-patches#3296]
### Bug description

The newer patches (especially Spoof Client) has messed up a lot.
So I was hoping I can go back 4 months, and use that YT version patches which worked flawlessly.

So I created the repo with those files (patches & integrations), then I input the name correctly on Revanced Manager alternative api sources.

After restarting the app, the menu shows an endless "loading" under Patches.
Unable to use it at all.

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
This is not an issue with ReVanced Patches or even ReVanced Manager. For support, move to one of our links at https://revanced.app.
