### ISSUE TITLE
Unable to check YouTube tablet viewing records

### ISSUE THREAD

**Issue by sssh7710** [ReVanced/revanced-patches#3296]
### Bug description

Like the title, the latest version of the YouTube tablet doesn't show the viewing records

### Additional context

There's a problem with the latest patch

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
No such feature called "Viewing records" is present on YouTube.

**Comment by sssh7710** [comment]
> No such feature called "Viewing records" is present on YouTube.

![SmartSelect_20231119_153525_YouTube.png](https://github.com/ReVanced/revanced-patches/assets/98168192/fd69cb94-9fbe-49ec-aa01-8bd0a3b33c08)

![SmartSelect_20231119_153533_1.png](https://github.com/ReVanced/revanced-patches/assets/98168192/dca51d00-8283-4cce-a951-1a324a569ad3)

**Comment by sssh7710** [comment]
> > No such feature called "Viewing records" is present on YouTube.
> 
> ![SmartSelect_20231119_153525_YouTube.png](https://github.com/ReVanced/revanced-patches/assets/98168192/fd69cb94-9fbe-49ec-aa01-8bd0a3b33c08)
> 
> ![SmartSelect_20231119_153533_1.png](https://github.com/ReVanced/revanced-patches/assets/98168192/dca51d00-8283-4cce-a951-1a324a569ad3)
> 
> 

The top is pure YouTube
I still have the same symptoms when I reset the app settings
There's definitely a problem with the patch

**Comment by oSumAtrIX** [comment]
Please send full screenshots. I don't understand what this shows

**Comment by sssh7710** [comment]
> Please send full screenshots. I don't understand what this shows

![Screenshot_20231120_023515_YouTube.png](https://github.com/ReVanced/revanced-patches/assets/98168192/a7044e4a-27d4-4936-bbae-a1c4b8591da9)

![Screenshot_20231120_023532.png](https://github.com/ReVanced/revanced-patches/assets/98168192/4da382e4-b841-4b58-b23b-5f39743169bd)

**Comment by oSumAtrIX** [comment]
Follow this: 

![image](https://github.com/ReVanced/revanced-patches/assets/13122796/760ddd36-17b6-458c-9716-5bc808a45626)
