### ISSUE TITLE
bug: Unpausing when turning off screen, shorts skip on pause

### ISSUE THREAD

**Issue by pep0w** [ReVanced/revanced-patches#3297]
### Bug description

I was using an older version, the one since history wasn't being recorded a few months ago (which apparently got fixed on it's own, but unfortunately I don't have that apk and can't patch it again with the older patches).
Why? Because the new version now has a different spoof and it has even more bugs.
It almost randomly unpauses (I could replicate it with 100% consistency with pausing then turning off the screen).
The shorts, instead of pausing it could just play the next one (without even swiping, and no slide animation either). Moving to the next one would play that same one again, moving back would play the one that was supposed to be paused.

I don't use the ios spoof because that one is even more limited.

### Solution

Allow patching with older patches

### Additional context

This is yet another reason to allow patching with older patches.

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
#3208
