### ISSUE TITLE
YouTube Video Locked to 1080p

### ISSUE THREAD

**Issue by LimitedEdiition** [ReVanced/revanced-patches#3298]
### Bug description

Patched today using the latest 4.9.0 and YT version 19.16.39 and max playback quality is only 1080p, even for videos that support higher resolution. On an unrelated note, playback history has not worked for a while and my account is not a brand account. 

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
I just tested a video and qualities over FHD were available, including 60fps. 
If you think this is actually a problem follow this:

![image](https://github.com/ReVanced/revanced-patches/assets/13122796/030e5509-86d2-453c-bec7-c5c0b564c8db)

**Comment by LimitedEdiition** [comment]
> @LimitedEdiition turn off iOS spoofing and it may have higher video qualities.
> 
> Playback history is probably blocked by a dns ad blocker or your yt account has history turned off.

Thanks. Turning off iOS spoofing did indeed fix both of those issues. Guess that's the solution for now.
