### ISSUE TITLE
History not working for secondary YouTube profiles

### ISSUE THREAD

**Issue by Jacinto27** [ReVanced/revanced-patches#3301]
### Bug description

View history does not support multi YouTube account for an unique Google Account. After updating to 4.9.0 history only works for one YouTube account (the primary one that is tied to the Google account signed into microG) but not the others ( YouTube allows for multiple profiles on a single Google Account).

Not a VPN or firewall issue.

Already tried reinstalling everything including microG.

Used to work before (I don't remember the patch I used before updating to 4.9.0).

### Error logs

```shell
Na
```

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by Jacinto27** [comment]
I'm not interested in updates regarding this, just informing, if possible add this to the list of patch issues and delete this issue.

Pretty please 🙏🙏🥺

**Comment by kazimmt** [comment]
#3208
#### iOS spoof
- Watch history does not work with a brand account

**Comment by Jacinto27** [comment]
I'm using Android 🤔

**Comment by kazimmt** [comment]
We all are using Android
I'm talking about Client Spoof
Check mentioned link
