### ISSUE TITLE
Expose reddit app to device assistant apps.

### ISSUE THREAD

**Issue by RamPawar7** [ReVanced/revanced-patches#3304]
### Feature description

Device assistant app called [Copy](https://play.google.com/store/apps/details?id=com.weberdo.apps.copy) is blocked by reddit from accessing the screen content as shown in the screenshot (read the toast message that shows up when activating the assistant app)

![Screenshot_20240605-010707_Reddit](https://github.com/ReVanced/revanced-patches/assets/96973076/639d8eff-679c-4381-8a29-8381eefe8ee9)

Add a patch that will cause reddit to not block device assistant apps from accessing the screen content.

### Motivation

With this patch, the above mentioned app can maybe be used to copy only certain parts of a post or comment instead of using reddit's in-built copy feature that copies the whole post/comment.

### Acknowledgements

- [X] I have checked all open and closed feature requests and this is not a duplicate
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
https://revanced.app/patches?s=screenshot

**Comment by RamPawar7** [comment]
I repatched the patched app with `Remove screenshot restriction` patch but it's still blocking the Copy app.

**Comment by oSumAtrIX** [comment]
Then `Remove screenshot restriction` needs adjustment

**Comment by RamPawar7** [comment]
I think you forgot to open this issue back up, just saying.
