### ISSUE TITLE
feat: (Youtube) Add an option to make seeking start from where I touch

### ISSUE THREAD

**Issue by ZeroTwoOne021** [ReVanced/revanced-patches#3306]
### Feature description

I just noticed that in the newer versions of Youtube, they changed it so that seeking starts from where the video currently is, and not where you touch the screen, and I hate it.

There is a workaround for this, which is enabling "Enable seekbar tapping", which will make seeking work the old way at the cost of being forced to have seekbar tapping.

Official v19.21.37: https://github.com/ReVanced/revanced-patches/assets/41229405/905973f6-b2b0-46bf-a0e4-c78e0c356419

Revanced v19.16.39 & patches v4.9.0 with "Enable seekbar tapping" enabled (I want to seek this way without seekbar tapping): https://github.com/ReVanced/revanced-patches/assets/41229405/176704d8-f13e-4d54-b7b5-955d8ec7b7ce

### Motivation

This is how seeking has always worked as far as I can remember, and it's also similar to how you'd seek in browsers. I also do not enjoy having seekbar tapping, as I'd sometimes accidentally tap on the seekbar, then have to go back to where I was and risk spoiling the video on myself.

### Acknowledgements

- [X] I have checked all open and closed feature requests and this is not a duplicate
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Don't know what the problem is with the existing seekbar tapping patch
