### ISSUE TITLE
bug: Youtube Music showing ads after UI switch

### ISSUE THREAD

**Issue by grahamgrieb** [ReVanced/revanced-patches#3307]
### Bug description

My Youtube Music switched to the new UI with the comment section(a server-side switch I believe) and now background playback does not work and ads play. Was on an older version when this happened and I upgraded 6.28.52 and I still encounter the issue.
![image](https://github.com/ReVanced/revanced-patches/assets/18386564/5822e4cf-b313-42b3-973a-4b352837d84b)

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
You seem to have incorrectly patched the app in this case

**Comment by grahamgrieb** [comment]
My app was working with the patches and then a server side switch flipped and it switched to the new UI with the comments. After that, ads started popping up with no changes in my patches.

**Comment by oSumAtrIX** [comment]
Repatch your app

**Comment by grahamgrieb** [comment]
I have tried that multiple times. It works until eventually it switches to the newer UI after a day or two with the comments added in (without me changing or updating the app).

**Comment by oSumAtrIX** [comment]
You are very likely doing something wrong, but this is not a support channel. If you need help, move to one via our links on revanced.app
