### ISSUE TITLE
feat(YouTube - Comments): Hide 'Comments by members' header

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [ReVanced/revanced-patches#3308]
### Feature description

A patch which hides the 'Comments by members' header.

![Screenshot_2024-06-07-11-52-05-721_app revanced android youtube~2](https://github.com/ReVanced/revanced-patches/assets/117499019/227bc672-5b94-4e59-baef-f702ee87b798)

### Motivation

YouTube already provides a comments filter by which the user can filter the members comments. Also, it'll make the comments section look more clean.

![Screenshot_2024-06-07-11-51-47-873_app revanced android youtube~2](https://github.com/ReVanced/revanced-patches/assets/117499019/a761521e-6c56-4671-9f8a-115367e16e01)

### Acknowledgements

- [X] I have checked all open and closed feature requests and this is not a duplicate
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by ILoveOpenSourceApplications** [comment]
The litho component to hide the header is `sponsorships_comments_header.eml`. The only issue is, as seen in the above attached screenshot, the gray separator at the bottom doesn't get hidden.

**Comment by ILoveOpenSourceApplications** [comment]
I couldn't find a separate litho for the separator only. So, the color code for that separator needs to be changed, which I don't know is possible and is just a suggestion from my end.

**Comment by oSumAtrIX** [comment]
Doesn't this only hide the header and not just the comment and thus makes it incorrectly look like it's a regular comment and not one pushed more by YouTube?

**Comment by ILoveOpenSourceApplications** [comment]
I don't think so. Just because someone decided to support a channel by becoming a member doesn't make their comment irrelevant. Also, they will still have the channel badge beside their name for users to identify that they're a channel member.

**Comment by oSumAtrIX** [comment]
Does YouTube push comments by members higher than other comments?

**Comment by ILoveOpenSourceApplications** [comment]
I'm not sure. In the screenshot attached channel, on his last 3-4 videos, there's atleast 1 'Comments by members' comment in top the first 10 comments. But it's not consistent, as there is a chance that there could be one in the top 3 comments and then there's not. So I don't think they do push it and it works similar to that of normal comments but with an extra header (which is unnecessary).

**Comment by ILoveOpenSourceApplications** [comment]
I still don't know how to link an issue to a PR. #3317 .
