### ISSUE TITLE
feat: (YouTube - Announcement): Add Options to make ReVanced Announcement can be showed manually

### ISSUE THREAD

**Issue by cyberboh** [ReVanced/revanced-patches#3311]
### Feature description

Announcements are a way for developers to reach end users to inform them of important implementations or recent changes. Currently, announcements are only shown when YouTube is newly patched or its data is cleared. It's hard to see recent changes if YouTube needs to be reinstalled.

### Motivation

This feature is important for staying updated with recent information from ReVanced. Whenever we forget, we can view announcements by pressing any toggle. This feature can be added by including a toggle button for announcements. Announcements can either be shown every time YouTube is opened or be viewed manually by pressing a button.

### Acknowledgements

- [X] I have checked all open and closed feature requests and this is not a duplicate
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Eventually, announcements will be shown on revanced.app/announcements

**Comment by oSumAtrIX** [comment]
https://github.com/ReVanced/revanced-website/pull/195
