### ISSUE TITLE
YouTube Music: Disable rotation

### ISSUE THREAD

**Issue by perz1val-git** [ReVanced/revanced-patches#3311]
### Feature description

Application: YouTube Music

Add a toggle in app to disable app rotation.

### Motivation

It is really annoying when after pulling the phone out of pocket to change currently playing track, the screen is rotated and I have to "shake it back" into the vertical layout. Adding a toggle that locks the app orientation to vertical would be a nice option for all users that use YTM just for music.

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
This is a feature on your phone

**Comment by perz1val-git** [comment]
I see only an option to disable it globally. Is it possible to set that on per app basis? Otherwise it's useless as switching it on/off constantly won't be any more convenient, which is the sole reason for modding this app.

**Comment by oSumAtrIX** [comment]
If you are running Android there is very likely a solution to your problem
