### ISSUE TITLE
feat: Patch Bundle Template with CI

### ISSUE THREAD

**Issue by Ushie** [ReVanced/revanced-patches#3315]
### Feature description

Create a Patch Bundle template repository, with necessary CI for releases with support for this https://github.com/ReVanced/revanced-manager/issues/572 format

### Motivation

With the upcoming release of ReVanced Manager v2, it's about time to prepare Patch Bundles as a concept, currently Patch Bundles need to fork this repository and (optionally) remove existing patches

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
If we create a template repository, how do we keep changes in sync?

**Comment by Ushie** [comment]
A template repository gives you the base to start, but it isn't your base if that makes sense, maintainers can keep things as is or they must manually keep up with changes

However, I've found this action https://github.com/AndreasAugustin/actions-template-sync

**Comment by Ushie** [comment]
But that action won't help you migrate your own changes, there's no way around maintainers having to keep up with updates themselves

**Comment by oSumAtrIX** [comment]
What I mean is, say we bump ReVanced Patcher, now we would commit to the template repo as well as our patches repository.

**Comment by Ushie** [comment]
That's intended, it's possible to have something like the sync action that I mentioned above but that action won't automatically migrate the patches if something about the patch structure changes, ReVanced Patcher bumps may come with necessary changes to patches

**Comment by oSumAtrIX** [comment]
This is an annoying burden. Alternatively, a project template could be comited here. This way we'd be able to update the template at the same time

**Comment by Ushie** [comment]
How would you commit a template here?

**Comment by oSumAtrIX** [comment]
On second thought, this is too complex to realize, a template repository is easier.

**Comment by oSumAtrIX** [comment]
https://github.com/ReVanced/revanced-patches-template
