### ISSUE TITLE
feat: Download in 720 and 1080p in YouTube Revanced

### ISSUE THREAD

**Issue by Aang488** [ReVanced/revanced-patches#3316]
### Feature description

Can't download videos in 720 and 1080p as they require a YouTube premium subscription. 
![IMG_20231121_204612](https://github.com/ReVanced/revanced-patches/assets/79444969/a359104e-29b9-4ccb-ae29-93d4bb807d73)

### Motivation

Sometimes one does not have an internet connection, like traveling or anything similar, so it's often needed to download videos offline. Incase of tutorials, demos and lectures, it's very important to have them offline at least in 720p to be able to see everything clearly. 360p and below don't even make sense for lectures etc.

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Already exists as the "External downloader" patch
