### ISSUE TITLE
feat (YouTube): Quick actions top margin

### ISSUE THREAD

**Issue by SaleOff** [ReVanced/revanced-patches#3318]
### Feature description

![Screenshot_2024-06-08-23-19-05-012_app rvx android youtube](https://github.com/ReVanced/revanced-patches/assets/133284637/f12c9f15-395f-4e0c-bf17-ca1507db4ac9)
![Screenshot_2024-06-08-23-19-41-545_app rvx android youtube](https://github.com/ReVanced/revanced-patches/assets/133284637/0a77c251-91a3-4a09-b2e4-fb1cdbf3d041)
I find a very cool feature of YouTube ReVanced Extended: it can enhance the seekbar to help me more easily operate in the video.  I've been waiting for this feature to come to YouTube ReVanced for a while, hope you can add it

### Motivation

Helps users easily operate when they want to fast forward the video to a certain part

### Acknowledgements

- [X] I have checked all open and closed feature requests and this is not a duplicate
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
https://github.com/ReVanced/revanced-patches/issues/2561
