### ISSUE TITLE
YT Music Quick Settings Panle Like/Unlike button missing

### ISSUE THREAD

**Issue by AARENKAY** [ReVanced/revanced-patches#3320]
### Bug description

YT Music Quick Settings Panle Music Player missing Like/Unlike button.
see the attached file

https://github.com/ReVanced/revanced-patches/assets/110279941/636307b3-017e-4c57-b9af-17e25ad2cd41

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Upstream issue by YouTube or your device
