### ISSUE TITLE
bug: Error 400 When Clicking YouTube Channels

### ISSUE THREAD

**Issue by ChrisX4Ever** [ReVanced/revanced-patches#3322]
### Bug description

I can watch videos correctly, but as soon as I click a channel to look for more videos "Error 400" appears.

### Solution

Make the channels accesible without "Error 400" showing up, please.

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Caused by the patch that overrides the UI to that of a tablet. To fix this the hook in its disabled state should not override the value to false, but pass through the original value it hooks.

**Comment by Veticia** [comment]
I had this error on my tablet. I didn't expect that I have to specifically enable tablet mode on a tablet.
