### ISSUE TITLE
Twitter / X: Hide Ads patch no longer works

### ISSUE THREAD

**Issue by tyteen4a03** [ReVanced/revanced-patches#3324]
### Bug description

On 10.16.0, the Hide Ads patch no longer work. All ads are showing.

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by tyteen4a03** [comment]
For me, all ads appear, even timeline.

**Comment by oSumAtrIX** [comment]
Can not reproduce either

**Comment by tyteen4a03** [comment]
I think I know what's happening - I enabled the Predictive Back Gesture patch which might have broken things. All working now!
