### ISSUE TITLE
bug: SponsorBlock skipping a segment at the end of a video causes the next video in a playlist to not autoplay

### ISSUE THREAD

**Issue by Xycotic01** [ReVanced/revanced-patches#3327]
### Bug description

Versions where problem is occurring: 18.45.41, 18.44.41, 18.43.45
Version where problem is not occurring: 18.37.36

Find a video that ends in a segment that is skipped by SponsorBlock. In conversations with moderators on the Discord, this video is an example: https://www.youtube.com/watch?v=ooiRBVTmIeM
Put the video in a playlist and another video after it. You want to see that the next video wont autoplay. 
I have redownloaded everything multiple times with both all of the patches and only the Vanced MicroG and SponsorBlock patches. The issue still persists and, therefore, it is likely that the SponsorBlock patch itself is the problem. 
oSum and taku are the people that I have talked to on the Discord support channel. Our conversations were held on Wed Nov 22, 2023 (my discord name is golfeethan). 
Thehe video is on the last frame before the segments are skipped by SponsorBlock. Say that the ending segments start at 15:40 and the end of the segments (the end of the video) is at 16:00. The frame shown is the one right before 15:40, but the timestamps of the video show as 16:00/16:00. The video player is frozen, not paused. Pressing the pause button wont do anything. Doubletapping to skip 10 seconds ahead or pressing the next video button will work, but when you are watching a playlist while your phone is in your pocket causes this to be an obvious problem. Even music videos that end in a nonmusic section will freeze and not autoplay. 
Obviously I am using the 18.37.36 version for now. But that version doesnt support patches such as return youtube dislike (as shown on https://revanced.app/patches?pkg=com.google.android.youtube). Having this issue fixed would be great. 

Thanks

### Solution

No solutions besides going back to an older version have been identified. 

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
This has been fixed in the latest version of the patches already
