### ISSUE TITLE
bug: Youtube ~ Hide Action buttons patch, annoying broken spacing between action items

### ISSUE THREAD

**Issue by Domiiniik** [ReVanced/revanced-patches#3333]
### Bug description

Broken spacing between action button items of certain items like remix or clip are hidden. This is really annoying and inconsistant.

### Error logs

```shell
-
```

### Solution

Fix

### Additional context

Reference:
![Screenshot_20231126_162827_YouTube](https://github.com/ReVanced/revanced-patches/assets/30195961/540d65ae-cbbb-400e-ba21-e321ebc480b0)

### Acknowledgements

- [ ] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
#2862 1195
