### ISSUE TITLE
Disable messenger lite

### ISSUE THREAD

**Issue by Joeeeeb5** [ReVanced/revanced-patches#3335]
### Feature description

Disables the messenger that is built into the Facebook app

### Motivation

The lite version is basically useless and i receive duplicate messages and calls from both the real messenger and Facebook's built in one

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
You can turn off notifications.

**Comment by Joeeeeb5** [comment]
> You can turn off notifications.

I still hear the call sound and messages get through sometimes when i'm on facebook. The messages service keeps the fb app always running and restricting it doesnt work because.. miui

**Comment by oSumAtrIX** [comment]
You should be able to disable call notifications as well
