### ISSUE TITLE
feat: Add option to filter out videos by age [YOUTUBE]

### ISSUE THREAD

**Issue by Wilk-22** [ReVanced/revanced-patches#3337]
### Feature description

Similar to keyword blocker in youtube , feture that would allow to hide videos based on age (older than, newer than)

### Motivation

Why should this feature be implemented?
- It would help in finding up to date tutorial videos or allow for showing only older videos for nostalgia (or something like that)

What is the explicit use case? / What are the benefits? / What makes this feature important?
- Finding up to date tutorials, news or any other information

### Acknowledgements

- [X] I have checked all open and closed feature requests and this is not a duplicate
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
That feature already exists in YouTube search.
