### ISSUE TITLE
bug: Youtube Music force close

### ISSUE THREAD

**Issue by alfzki** [revanced/revanced-patches#334]
### Type

Error at runtime

### Bug description

Youtube Music Revanced force close when I disable microg patch
revanced-cli 2.9.2
revanced-integrations 0.31.2
revanced-patches 2.33.2

### Steps to reproduce

1. run `revanced-cli -a Downloads/com.google.android.apps.youtube.music_5.17.51-51751240_minAPI21\(arm64-v8a\)\(nodpi\)_apkmirror.com.apk -d 192.168.100.7:39861 -o revanced-youtube-music.apk -m /usr/share/revanced/integrations.apk -b /usr/share/revanced/revanced-patches.jar -e tasteBuilder-remover -e compact-header -e music-microg-support --mount`
2.  apps get automatically launched
3. force close

### Relevant log output

```shell
~
```

**Comment by oSumAtrIX** [comment]
Include logs from logcat.

**Comment by iamrony777** [comment]
run revanced cli with `-r`
