### ISSUE TITLE
bug: Video blurriness sometimes doesn't go away

### ISSUE THREAD

**Issue by deception1359** [ReVanced/revanced-patches#3340]
### Bug description

I have encountered this situation quite a few times (8-10) without knowing the cause, clicking on the screen does not disappear, waiting more than 5 seconds also has no effect.  

I have used many versions, up to the latest version, currently 18.45.43, this situation still persists at sometime.  I was going to record a video of the error screen, but when I recorded it, it worked normally.

Hope you can fix it.

![Screenshot_20231128_215532_Youtube ReVanced](https://github.com/ReVanced/revanced-patches/assets/54271923/5dc11489-6881-478f-9c35-7bdcab7440ca)

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Using unofficial patches not by us

**Comment by deception1359** [comment]
No, I use Revanced CLI on Termux
