### ISSUE TITLE
bug: Override certificate pinning patch throws brut.common.BrutException

### ISSUE THREAD

**Issue by mitomenai** [ReVanced/revanced-patches#3341]
### Bug description

revanced-cli patch --patch-bundle revanced-patches-4.9.0.jar --include "Override certificate pinning" whatsapp.apk

Error occurs during the compilation of modified resources: 
``error: file failed to compile. brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1)``

Happens in the Android app as well as revanced-cli.

Seems to impact universal architecture apk  (anything from 2023 onward). I presume they are not supported?

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
That looks like a general issue with recompiling resources caused by either Androlib decoding the resources incorrectly, or AAPT failing to compile them again. In either way, not caused by the patch
