### ISSUE TITLE
bug: Black video 

### ISSUE THREAD

**Issue by GKid94** [ReVanced/revanced-patches#3346]
### Bug description

Video not showing only hearing audio 
![Screenshot_2024-06-14-04-33-56-314_app revanced android youtube](https://github.com/ReVanced/revanced-patches/assets/18757054/1aaeffe2-24dd-43f9-810a-ad0739618218)

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [ ] I have chosen an appropriate title.
- [ ] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
No reproduction steps are present. Add all requested information properly
