### ISSUE TITLE
Desktop Mode in Landscape for Revanced / RVX

### ISSUE THREAD

**Issue by thisisbimal** [ReVanced/revanced-patches#3348]
### Feature description

Probably, you're all aware how the desktop version of YouTube looks right.
![Screenshot 2024-06-16 174512](https://github.com/ReVanced/revanced-patches/assets/136806503/c733216e-e820-4586-a210-b1aa7c132dc6)

Second, would it be possible to follow similar UI while watching videos in YouTube in landscape mode too?? 

![image](https://github.com/ReVanced/revanced-patches/assets/136806503/39c3af86-d588-42b9-8483-34296f251055)
![image](https://github.com/ReVanced/revanced-patches/assets/136806503/23bb6d2c-333d-4f1f-a2a3-2ba201dc6e60)

For demo, this is how it would look like in mobile browser when desktop mode is enabled..

![image](https://github.com/ReVanced/revanced-patches/assets/136806503/645944fa-1468-43d5-bc45-f28635b4bcf9)

Video on top left, underneath that comments, and on the right, recommendations. Similar feature exists called "tablet mode" that tricks the DPI. But I think we can add an option like "Enable Desktop mode" instead. If such a feature can't be added, we can change the DPI to somewhere 600 DPI of the phone to somewhat achieve desktop like interface. But it changes for the whole phone. It would be better if Revanced had an option to use custom DPI's. Thanks,

### Motivation

Similar feature is somewhat available (Tablet Mode), so it shouldnt be that hard,?
Either an option to "Enable Desktop Mode" or an option to use custom DPI for the Revanced app solely.
Benefits are, sometimes users want to watch videos in landscape without going full screen, while reading comments and watching recommended videos, but YouTube only enable them in fullscreen in landscape.

### Acknowledgements

- [X] I have checked all open and closed feature requests and this is not a duplicate
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
What you are looking for is portrait mode

**Comment by thisisbimal** [comment]
> What you are looking for is portrait mode. Also this repository is ReVanced and not RVX

Huh? Portrait Mode? Wdym? I was asking if we can enable such desktop UI in landscape mode??
