### ISSUE TITLE
bug: Watch live video in background 

### ISSUE THREAD

**Issue by Movment** [ReVanced/revanced-patches#3350]
### Bug description

There is a problem, it is not possible to watch in the background a video that is live / was live

not in extended. in regular.

**note ! i turn off the picture in picture in background**

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
https://github.com/ReVanced/revanced-patches/issues/3208
