### ISSUE TITLE
bug: vanced YouTube stuttering.

### ISSUE THREAD

**Issue by qlife1146** [ReVanced/revanced-patches#3352]
### Bug description

Vanced patched YouTube has more heat and stuttering than genuine YouTube when used.
It's weird to stutter while using patched YouTube, so I used genuine YouTube again, but it definitely didn't stutter on genuine YouTube. There's a big difference when you double the speed of the video.

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by qlife1146** [comment]
with microG Services?

**Comment by oSumAtrIX** [comment]
Find out which patch causes it by selectively disabling them at patch time. You can use binary search

**Comment by oSumAtrIX** [comment]
Moved to https://github.com/ReVanced/revanced-patches/issues/3353
