### ISSUE TITLE
bug: Videos stuttering when Spoof Client Patch is enabled.

### ISSUE THREAD

**Issue by YouSummoner** [ReVanced/revanced-patches#3353]
### Bug description

1. Go to Revanced miscellaneous settings.
2. Enable the Client Spoof Patch.
3. Restart app and try to play a video.

https://github.com/ReVanced/revanced-patches/assets/107224555/e9f6be16-15ac-47a7-b8d1-0d2ef663e814

Logs:  
[logcat.log](https://github.com/user-attachments/files/15876632/logcat.log)
[event.log](https://github.com/user-attachments/files/15876636/event.log)

### Error logs

```shell
.
```

### Solution

This doesn't happen if the patch is disabled, but then the buffering problem persists, which this patch was made to solve.

### Additional context

This stuttering doesn't happen on every video, maybe due to the uploaded video's codec.
Some of the youtube channels I've faced this issue are known as (Tech Karan) and (Everything Android).

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Compare the codec used in the unpatched app and the patched app via the nerd menu in YouTube

**Comment by YouSummoner** [comment]
> Compare the codec used in the unpatched app and the patched app via the nerd menu in YouTube

Sure, here's the stats from original youtube app:
![Screenshot_20240618-020058_Precise Frame mpv Video Player](https://github.com/ReVanced/revanced-patches/assets/107224555/aa844fee-64c3-4e9d-8720-c2d7bced15de)
 And the patched app: 
![Screenshot_20240618-021227_Precise Frame mpv Video Player](https://github.com/ReVanced/revanced-patches/assets/107224555/03489d0b-9dc4-48ef-9db6-1379c47067dc)

**Comment by YouSummoner** [comment]
> Try turning off iOS spoofing (which then uses Android VR spoofing).
> 
> Also verify `Spoof device dimensions` is not enabled.

Device dimensions patch is not enabled...

**Comment by oSumAtrIX** [comment]
Apparently late versions of iOS only support avc1: https://www.reddit.com/r/AV1/comments/16uy52m/comment/k2pxbwn/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

**Comment by oSumAtrIX** [comment]
Moved to https://github.com/ReVanced/revanced-patches/issues/3208

**Comment by YouSummoner** [comment]
Realme XT

**Comment by YouSummoner** [comment]
> From what I can gather, that has a Snapdragon 712 and has hardware AVC1 support but not AV1.
> 
> I just noticed your logs show you are using a fork of ReVanced.
> 
> Check again using the latest official ReVanced, with iOS spoofing, the same video, and report back which codec is used.

Alright, I patched the app myself using the official patches(only selected the patches for ADs, spoof client and GmsCore while patching), but it's still stuttering with the spoof iOS patch enabled... here's the stats...
![Screenshot_20240618-070823_YouTube](https://github.com/ReVanced/revanced-patches/assets/107224555/59c6e0c6-7dba-45a2-a68a-9ab160d89776)

**Comment by oSumAtrIX** [comment]
The unpatched app uses avc1 whereas the patched app uses vp9, probably that's why.

**Comment by YouSummoner** [comment]
> @YouSummoner what codec is used with Android VR spoof?

Stats with Android VR spoof:
![Screenshot_20240618-075809_YouTube](https://github.com/ReVanced/revanced-patches/assets/107224555/5e327c2d-98d9-4b45-96cf-2fa976377b2c)

**Comment by oSumAtrIX** [comment]
You previously claimed:

> And yes, this issue doesn't happen with the Android VR spoof

In your latest picture it shows dropped frames though. So what now?

**Comment by YouSummoner** [comment]
I can't say about the stats, but I can confirm that no stuttering was visible to the eye while playback of the video. Though I did check again on the same video with Android VR spoof and here's the stats from that, this time it isn't showing any dropped frames.
![Screenshot_20240618-095654_YouTube](https://github.com/ReVanced/revanced-patches/assets/107224555/c2d2e2a7-dd60-4e3b-89ac-92c12c485a2e)

**Comment by GKid94** [comment]
Same on Redmi 9
![Screenshot_2024-06-22-12-46-52-095_anddea youtube](https://github.com/ReVanced/revanced-patches/assets/18757054/e54969d1-e0da-4fb9-9ba4-168eadcc2398)
![Screenshot_2024-06-22-12-54-47-531_com miui securitycenter](https://github.com/ReVanced/revanced-patches/assets/18757054/20ab1878-0f36-4449-8432-9f99faf4d907)
