### ISSUE TITLE
feat (YouTube): Shorts player media next/previous hotkey

### ISSUE THREAD

**Issue by Talafhah1** [ReVanced/revanced-patches#3354]
### Feature description

this feature would allow the Shorts player to play the next/previous video when the media next/previous buttons are pressed 

### Motivation

makes the expereince for some users better and increases accessibility 

### Acknowledgements

- [X] I have checked all open and closed feature requests and this is not a duplicate
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
For that you can use tasker
