### ISSUE TITLE
bug: Patched apps aren't able to be seen by Android Settings in order to enable high refresh rates

### ISSUE THREAD

**Issue by AngusAranda** [ReVanced/revanced-patches#3363]
### Bug description

So I've been noticing that only my YouTube app is laggy when interacting while watching a video or even generally browsing around. For a while I thought it was just some lagginess, but then I realized: my phone would lag that much. It's a OnePlus 8T. If it was lagging that much: there would be some other issue.

So then it dawned on me: let's check the settings app to see what the Display Settings say for the Refresh Rate is.

Low and behold, I only see the stock YouTube app, NOT YouTube Vanced.

And even when enabling 120Hz on the stock YouTube app, I still don't get proper 120Hz.

So I think the way patching the apps works interferes with the Android Settings app being able to properly display and enable high refresh rates.

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
That's an issue with your device. ReVanced doesn't interfere here

**Comment by AngusAranda** [comment]
> That's an issue with your device. ReVanced doesn't interfere here

You're absolutely correct.

Here's how I fixed it:

>adb shell settings put secure oplus_customize_screen_refresh_rate 0 && adb shell settings put system peak_refresh_rate 1 && adb shell settings put system min_refresh_rate 1 && adb shell settings put system user_refresh_rate 1
