### ISSUE TITLE
feat: Kick streaming app

### ISSUE THREAD

**Issue by Bigotaku** [ReVanced/revanced-patches#3370]
### Feature description

Its an alternative /ripoff of twitch.
Need all features possible that available in twitch like auto point collect, skip ads etc...

![unnamed](https://github.com/ReVanced/revanced-patches/assets/151906217/88cc36ac-476a-41d9-9d29-b2a61b35d6cf)

### Motivation

Its an alternative to twitch so many streamers are moving to it since it give better offer even if twitch is still the biggest.

### Acknowledgements

- [X] I have checked all open and closed feature requests and this is not a duplicate
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
YouTube is also an alternative to Twitch with livestreaming capabilities.

**Comment by Bigotaku** [comment]
> YouTube is also an alternative to Twitch with livestreaming capabilities.

Yes but streamers are using it since its look similar to  twitch, but ran by different people.

**Comment by oSumAtrIX** [comment]
I don't see Kick being relevant enough yet to be considered. If it turns out we can reconsider.
