### ISSUE TITLE
(YouTube) Flyouts and like/dislike buttons in Fullscreen are missing 

### ISSUE THREAD

**Issue by 111ebobo** [ReVanced/revanced-patches#3372]
### Bug description

I have tried with and without tablet layout but there is no buttons/Flyouts (I didn't disabled these things)
![Screenshot_20231205-010739](https://github.com/ReVanced/revanced-patches/assets/104251188/0c1e6c00-2162-4dee-b719-a82d3c7a0e79)
![Screenshot_20231205-010734](https://github.com/ReVanced/revanced-patches/assets/104251188/012a7d7f-3546-4a43-ae68-dbb6c848ed72)

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
![image](https://github.com/ReVanced/revanced-patches/assets/13122796/833aeb08-9b72-45a9-b984-c72980bb13ad)

They are not missing

**Comment by 111ebobo** [comment]
> ![image](https://github.com/ReVanced/revanced-patches/assets/13122796/833aeb08-9b72-45a9-b984-c72980bb13ad)
> 
> They are not missing

I have demonstrated the original client to display what elements are not showing
