### ISSUE TITLE
(YouTube) missing UI elements

### ISSUE THREAD

**Issue by 111ebobo** [ReVanced/revanced-patches#3373]
### Bug description

I have tablet mode turned on (even if I disable it it won't bring back it won't change) the bottom like/dislike buttons and Flyouts in Fullscreen mode are not appearing (I didn't disabled them) (and the screenshots are displaying what elements I don't see on modded client)
![Screenshot_20231205-010739](https://github.com/ReVanced/revanced-patches/assets/104251188/41d90696-0180-4dc7-8ae0-ef3630838d5b)
![Screenshot_20231205-010734](https://github.com/ReVanced/revanced-patches/assets/104251188/824486ec-b5db-40d6-816c-9590a078131a)

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
This is normal YouTube behaviour.

**Comment by 111ebobo** [comment]
> This is normal YouTube behaviour.

What, I showed the default client to display the missing UI elements

**Comment by oSumAtrIX** [comment]
Please record a full video showing the issue clearly. Your screenshot from the unpatched app is not the same as the patched app.

**Comment by 111ebobo** [comment]
> Please record a full video showing the issue clearly. Your screenshot from the unpatched app is not the same as the patched app.

https://drive.google.com/file/d/1rlGgFdlU75BOT9Ds9pXzKVK1yOfIdEqc/view?usp=drivesdk

**Comment by oSumAtrIX** [comment]
Follow this and report back

![Screenshot_20231121-173514](https://github.com/ReVanced/revanced-patches/assets/13122796/1aa975a1-cac3-47fa-acac-4072525632b8)

**Comment by 111ebobo** [comment]
I did it, but this issue is still there
