### ISSUE TITLE
bug:(YouTube/YouTube Music): add `is` to revanced_ryd_toast_on_connection_error_title string

### ISSUE THREAD

**Issue by girshcatt** [ReVanced/revanced-patches#3375]
### Bug description

Add is to revanced_ryd_toast_on_connection_error_title string

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
`revanced_ryd_toast_on_connection_error_titleis` is incorrect
