### ISSUE TITLE
question: Is revanced_ryd_video_likes_hidden_by_video_owner string a toast?

### ISSUE THREAD

**Issue by girshcatt** [ReVanced/revanced-patches#3376]
### Bug description

Is revanced_ryd_video_likes_hidden_by_video_owner string a toast? Also please share screenshot of example where it appears

### Additional context

Sorry for asking it here, reason i do this that only people related to creating ryd integration can answer me

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
You can find the usage of the string resource key in the integration repository.
