### ISSUE TITLE
bug(YouTube Music - Hide music ads): Patch has no description in Manager

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [ReVanced/revanced-patches#3376]
### Bug description

![Screenshot_20240624_203710~2](https://github.com/ReVanced/revanced-patches/assets/117499019/c4d95b4e-4618-4051-a6fc-220065f005f3)

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
The patch has no description

**Comment by ILoveOpenSourceApplications** [comment]
Isn't that an issue ?

**Comment by Ushie** [comment]
Not really because no further information is needed, the patch name conveys everything

**Comment by ILoveOpenSourceApplications** [comment]
Given, this patch not only hides music video ads, but songs ads and even podcast ads shouldn't the patch and it's description be more specific?

**Comment by oSumAtrIX** [comment]
In that case please open a PR or an issue with a description for the patch. The name should be adjusted

**Comment by ILoveOpenSourceApplications** [comment]
@oSumAtrIX, I recycled this issue and edited everything accordingly. Now it can be reopened.

**Comment by oSumAtrIX** [comment]
Please open a new one, the discussion is unrelated under this issue now
