### ISSUE TITLE
Update TikTok Version

### ISSUE THREAD

**Issue by Clone69420** [ReVanced/revanced-patches#3382]
### Feature description

- Support the latest version of TikTok with Revanced

### Motivation

since it didnt got any Upgrade for some time and New stuff was added

### Acknowledgements

- [X] I have checked all open and closed feature requests and this is not a duplicate
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
https://github.com/ReVanced/revanced-patches/issues/3282

**Comment by qorrymarzuki** [comment]
Please reopen this issue, as the new version (35.6.3) supports dark mode for TikTok android, which is a long waited feature that was exclusive on iOS. Also so many filters requires new TikTok version, requesting the app to be updated.
