### ISSUE TITLE
question : Default password for exported Revanced Manager signature.

### ISSUE THREAD

**Issue by vippium** [ReVanced/revanced-patches#3383]
### Bug description

Firstly sorry for opening it as a bug...Now, here is my question:
I've exported the signature as file from Revanced Manager. When I imported it, it will ask for the password. But while exporting, it doesn't show the password. Now, what is the password for that key.

I've tried so many passwords like revanced, date, etc. Default file name is : New_Key_20240623_182955

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
![Uploading image.png…]()

**Comment by vippium** [comment]
I'm also not meant to use the issue page for questions. But I just want to know the default password for the exported keystore from Revanced. Manager.
