### ISSUE TITLE
feat: Copy text in comments on YouTube app.

### ISSUE THREAD

**Issue by ChaosTeckNet** [ReVanced/revanced-patches#3387]
### Feature description

You should add a feature that lets me click on links in the YouTube app. All the time I watch shorts and they leave a link to the full video in the comments and you can't click it or copy it to paste it anywhere. Being g able to just select the text and copy it so I can paste it would also work.

### Motivation

Literally everyone would benefit from this feature. Most just give up on going to the video or link or full video in the comments because it's a big long complicated url that you can't click or copy. Sometimes I even take a screenshot and use AI or editing tools to select the text just to paste it just to watch the video. It's very annoying.

### Acknowledgements

- [X] I have checked all open and closed feature requests and this is not a duplicate
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
#1538
