### ISSUE TITLE
bug: Youtube: no background playback for Lives

### ISSUE THREAD

**Issue by TheShadowRunner** [ReVanced/revanced-patches#3388]
### Bug description

When playing any Live video on YouTube, background playback doesn't work.
Instead of playing in the background, the playback just stops.
It only impacts Live videos.

### Additional context

Android 10
Revanced 1.20.1
Patches 4.10.0
YouTube 19.16.39

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
#1257
