### ISSUE TITLE
feat: Patches to remove intrusive ads from the IMDB app

### ISSUE THREAD

**Issue by steveharsant** [ReVanced/revanced-patches#3390]
Recently, IMBDs ads have gone from intrusive to extreme, to the point of covering up to 1/4 of the screen that persists when scrolling.

A patch to remove these ads would be extremely appreciated.

Thank you!

**Comment by oSumAtrIX** [comment]
#1377

**Comment by steveharsant** [comment]
Apologies. Was on mobile. Have resubmitted using the template.
