### ISSUE TITLE
bug: Sync for Reddit Pro crash

### ISSUE THREAD

**Issue by Bamboozul** [ReVanced/revanced-patches#3391]
### Bug description

The app crashes after finishing the setup tutorial in the latest patch, v4.10.0.
Device: Samsung S24 Ultra Android 14 OneUI 6.1

### Error logs

[crash-com-laurencedawson-reddit_sync-pro-28_06-12-09-52_477.zip](https://github.com/user-attachments/files/16027904/crash-com-laurencedawson-reddit_sync-pro-28_06-12-09-52_477.zip)

### Additional context

I tested the same patch on my other device, Redmi Note 9 Pro, which runs custom AOSP ROM A14, and it works well.

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Send crash logs using Logcat. Google online how to use Logcat.

**Comment by Bamboozul** [comment]
> Send crash logs using Logcat. Google online how to use Logcat.

Updated.

**Comment by oSumAtrIX** [comment]
Looks like you patched and installed a SPLIT APK. You need a full APK. For support, move to one of our links at https://revanced.app.
