### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by pep0w** [ReVanced/revanced-patches#3394]
### Bug description

Adding to "watch later" doesn't add the video to the list. 

From the subs feed or home, I would open the 3 dots menu and select "add to watch later". Then going to the list in the library, the video is not there. If I click the "save to" button it shows the "watch later" as marked.

### Additional context

Here's the settings
```
"announcement_last_id": 13,
"copy_video_url_timestamp": false,
"custom_playback_speeds": "0.25\n0.5\n0.75\n0.8\n0.85\n0.9\n0.95\n1.0\n1.05\n1.1\n1.15\n1.2\n1.25\n1.5\n1.75\n2.0\n3.0\n4.0\n5.0",
"disable_like_subscribe_glow": true,
"disable_resuming_shorts_player": true,
"disable_suggested_video_end_screen": true,
"external_downloader_action_button": true,
"hide_attributes_section": true,
"hide_cast_button": false,
"hide_download_button": true,
"hide_player_buttons": true,
"hide_quick_actions": true,
"hide_related_videos": true,
"hide_report_button": true,
"hide_shorts_button": false,
"hide_shorts_location_label": true,
"hide_shorts_sound_button": true,
"remember_playback_speed_last_selected": false,
"seekbar_custom_color": true,
"slide_to_seek": true,
"spoof_app_version": true,
"spoof_client_use_ios": false,
"swipe_brightness": false,
"swipe_volume": false,
"video_quality_default_wifi": 480,
"ryd_enabled": false,
"sb_enabled": false
```

### Acknowledgements

- [ ] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Follow this: 
<img width="390" alt="image" src="https://github.com/ReVanced/revanced-patches/assets/13122796/2e8c714f-8252-40ca-9088-8632860b0cf4">

and use a proper title.
