### ISSUE TITLE
feat(Twitch): Support newer versions of Twitch

### ISSUE THREAD

**Issue by LizenzFass78851** [ReVanced/revanced-patches#3395]
### Feature description

- Evolved existing patches to support newer versions of Twitch

### Motivation

- The patches support Twitch in general but currently do not support versions newer than 16.9.1. 
- I think that Twitch should also be given attention in addition to YouTube in order to make it compatible with newer versions as well.
- With the support of newer versions of Twitch, it is also fully compatible with newer Android versions (should the case arise that Android has advanced several versions over time and therefore the Twitch app is partially or completely incompatible with an older version of Twitch).
- And with the support of newer versions of Twitch, Twitch-side bug fixes and other things may be fixed so that the user experience is improved. (Example: sometime after version 17.0 or newer, dark mode was introduced)

### Acknowledgements

- [X] I have checked all open and closed feature requests and this is not a duplicate
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Dark mode is present in the current patchable version. Reopen if there's a good reason to update

**Comment by Starcr0ss** [comment]
The current twitch version no longer can view Twitch Stories. I feel this is a good reason to dedicate resources to updating twitch

**Comment by oSumAtrIX** [comment]
Twitch is a streaming platform. Stories are hardly a good reason to update
