### ISSUE TITLE
feat:(reddit) Remove all "Suggest"-types of posts from home feed

### ISSUE THREAD

**Issue by mario-g98** [ReVanced/revanced-patches#3396]
### Feature description

Remove all "Suggested", "Popular in your country", "Because you visited this community before" posts from home feed.

### Motivation

I don't think I need to explain why, these posts are as bad as ads.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Tracking in https://github.com/ReVanced/revanced-patches/issues/2580. Add as a comment
