### ISSUE TITLE
feat: YouTube - Add patch option to `auto-expand description` in YouTube

### ISSUE THREAD

**Issue by Vipin2003** [ReVanced/revanced-patches#3398]
### Feature description

There should be a patch option to enable the auto-expand description in YouTube. Like we have to click on more button every time we open description box. So, this patch will force more button to be clicked automatically whenever user opens the description box.

### Motivation

This patch will help users to open and read the full description without clicking on 'more' button again and again every time user opens description box.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Unnecessary, simply click onlpen

**Comment by Vipin2003** [comment]
> Unnecessary, simply click open

I think you misunderstood that... Check this video.

https://github.com/ReVanced/revanced-patches/assets/93650504/1cea2c77-9739-43f1-8a1e-5cb8b8a2a917

After opening description, the collapsed description should maximize.
