### ISSUE TITLE
bug (Boost): Reddit doesn't redirect back into the app when logging in

### ISSUE THREAD

**Issue by KobeW50** [ReVanced/revanced-patches#3403]
### Bug description

When you log in to a patched Boost app it will not redirect from the Reddit login page back into the app. Therefore it is impossible to log in.

**Steps to reproduce:**

1. Download a [Boost v 1.12.12 APK](https://www.apkmirror.com/apk/ruben-mayayo/boost-for-reddit/boost-for-reddit-1-12-12-release/boost-for-reddit-1-12-12-android-apk-download/)

2. Create a client ID, and patch the APK using the client ID.

3. Install and log in to the patched app.

https://github.com/ReVanced/revanced-patches/assets/84587632/cf03f007-0ebc-47d7-875d-e84a1a3e21e8

### Additional context

This issue is just an updated version of https://github.com/ReVanced/revanced-patches/issues/3130, which I was asked to reopen.

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by givyaway** [comment]
Same problem for me using Boost 1.12.12 and Revanced 1.17.1. In the meantime of finding a solution, is there any workaround that could be applied?

**Comment by KobeW50** [comment]
@oSumAtrIX will this be closed when https://github.com/ReVanced/revanced-patches/releases/tag/v3.1.0-dev.1 is merged to main?
