### ISSUE TITLE
feat: patch android app for Windy.com - Weather Forecast ( DIFFERENT from WindyAPP which is already patched )

### ISSUE THREAD

**Issue by 40ZqTYY4ag3tAO4hdlxR1** [ReVanced/revanced-patches#3405]
### Feature description

Patch for com.windyty.android 

- https://play.google.com/store/apps/details?id=com.windyty.android
- https://www.apkmirror.com/apk/windyty-se/
- windy.com

**Not sure if premium features are locked on device or server-side** 

Some **relevant** Premium features 

1. 1-hour forecast step
2. 10-day forecast outlook
3. 12-hour loop for Radar and Satellite

### Motivation

Windy.com https://play.google.com/store/apps/details?id=com.windyty.android while seems similar to the already patched WindyAPP , is different.

It has more forecast models, built in to it. Different forecast models from local agencies with high accuracy for your area.
Users are allowed to switch between models, and **compare forecasts** between all models for their location.

Partial list of available models
- ECMWF 9km
- UKV 2km
- GFS 22km
- Icon-D2 2.2km
- Icon-EU 7km
- Icon 13km
- NEMS 4km
- AROME 2.5km
- HRRR 3km
- HRDPS 2.5km
- NAM 5km
- MSM 5km
- ACCESS 12km
- Meteoblue

Example of ability to compare models https://www.windy.com/multimodel/54.150/-4.478?54.262,-2.686,7  ( similar data but different layout is available inside the android app )

### Acknowledgements

- [X] I have checked all open and closed feature requests and this is not a duplicate
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Not adhering contribution guidelines
