### ISSUE TITLE
feat: TuneIn radio patch support

### ISSUE THREAD

**Issue by bosseyed** [ReVanced/revanced-patches#3410]
### Feature description

Remove Ads from the start of radio streams

### Motivation

Ads have become very intrusive when listening and changing stations on tunein, especally as android auto seems to only support this radio app in the uk.

### Acknowledgements

- [X] I have checked all open and closed feature requests and this is not a duplicate
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Simply use another radio app, not sure what the problem with that is
