### ISSUE TITLE
feat: Twitter snippets: show/hide different post types, image and video (HQ) download, gallery view

### ISSUE THREAD

**Issue by G-D-B-9-9** [ReVanced/revanced-patches#3411]
### Feature description

feat: Twitter snippets: show/hide different post types, image and video (HQ) download, gallery view. Hide/show gif/image/video/text/link/repost/liked/commented etc.

For twitter media timeline view think of tumblr (archive) / tumbex views that allow people to organize content for quick view instead of scrolling 

### Motivation

Twitter is messy and noisy and a bit all over. People would be able to customize their experience.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Some of the features you mentioned have open issues. Split the issue

**Comment by G-D-B-9-9** [comment]
> Some of the features you mentioned have open issues. Split the issue

Open issues? Open issues are yt-premium and lrmobile pro too. By a tool through ms-platform. Is it an open issue that people download a lot from TikTok? Maybe ppl at Revanced aren't interested of Twitter? Which is btw going to have big changes coming. Elon is taking something from every major social app and website (even from reddit and tumblr) and mixing it together as X :D which is going to be similar to wechat.

**Comment by G-D-B-9-9** [comment]
X/Twitter needs more patches from ppl who knows what the site/app needs.
