### ISSUE TITLE
bug(YouTube - Disable auto captions): Shorts subtitles do not work

### ISSUE THREAD

**Issue by EtiLB7** [ReVanced/revanced-patches#3416]
### Bug description

Subtitle in shorts simply doesn't work.

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by 0xrxL** [comment]
> For now, turn off `Player -> Disable auto captions`
> 
> If the patch is enabled it breaks the Shorts captions menu.

It shouldn't be needed for shorts (auto-captions exists only on normal player...I believe), so you can use the check for shorts clips inside integrations. 👍

**Comment by 0xrxL** [comment]
UPDATE: I added a check to disable patch on shorts player, and I can confirm it works flawlessly on my test build.

✌️
