### ISSUE TITLE
bug: Patches install for YT Music without root or vanced microg

### ISSUE THREAD

**Issue by mm12** [ReVanced/revanced-patches#3417]
### Bug description

The patches for YT Music are applied without root or vanced microg. The app can be installed. However, it will immediately crash when opened, with no indication to the user of vanced microg being missing.

### Solution

Throe an error if Microg is absent and the phone has not been rooted, in order to let the user know to install it. 

### Additional context

I came from a previous device and had forgotten to install microg

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
If the patch is absent an error cant be thrown
