### ISSUE TITLE
Remove internet access for an app

### ISSUE THREAD

**Issue by shifoc** [ReVanced/revanced-patches#342]
### Application

Every application

### Issue

It should remove the internet permission of an app

### Patch

Remove the internet permission from an app

### Motivation

It would help protect the privacy of people for apps that shouldn't have internet access

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by jmangel** [comment]
I would love this patch
