### ISSUE TITLE
feat: Strava version bump to enabled the Dark mode feature.

### ISSUE THREAD

**Issue by CoolCooler0** [ReVanced/revanced-patches#3425]
### Feature description

Bump version compatibility to the latest to use Dark Mode.

### Motivation

My motivation for this Dark mode. Strava has added Dark mode to their latest versions. Dark mode is the best lol.

### Acknowledgements

- [X] I have checked all open and closed feature requests and this is not a duplicate
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
The pro unlock patch wont get updates anymore according to https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md
