### ISSUE TITLE
ProtonVPN

### ISSUE THREAD

**Issue by hfir8484** [ReVanced/revanced-patches#3429]
### Feature description

Hello! ProtonVPN has 5 free servers for a free account. These free servers are located in Poland, USA, Japan, Romania and the Netherlands. 

But I noticed that when logging into the application, the VPN connects to the Mauritania server. You cannot connect to it with a free account, but if you log in for an account, this option is available. Yesterday, when I wanted to connect to a free VPN server, I was connected to the Mauritania server, which is not available in the free version. I logged into my account for the first time, I think I found a bug

I think it is possible to make a mod that will connect to the Mauritania server without a paid subscription. This server is used to bypass blocks during authorization where the site is blocked

### Motivation

Free additional server.
Idea for mod.

### Acknowledgements

- [X] I have checked all open and closed feature requests and this is not a duplicate
- [ ] I have chosen an appropriate title.
- [ ] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#%EF%B8%8F-guidelines-for-requesting-or-contributing-patches

Also thats likels controlled server side
