### ISSUE TITLE
Unable to submit segments: status: 400 bad request

### ISSUE THREAD

**Issue by rahaaatul** [revanced/revanced-patches#343]
### Type

SponsorBlock: New Segment Adding

### Bug description

Every time I try to submit a sponsor block segment, I get 400 bad request error.

### Steps to reproduce

- Add a segment, eg. sponsor.
- Submit.

### Screen recording

https://user-images.githubusercontent.com/86149861/184818537-f4989967-e030-48d7-aced-768fb9f3f82f.mp4

**Comment by Titivoot** [comment]
Check unique user id in sponsorblock settings

**Comment by rahaaatul** [comment]
> Check unique user id in sponsorblock settings

```
cbccbc7382a649aba4d7fb212026c46a0fff199a606442c28a0f4bf1ff4d715b5c9ab72d93584bb9b33cf18d66634d8d
```

**Comment by Titivoot** [comment]
If you have a unique user id, you need to request submit permission first. it's not bug

**Comment by Titivoot** [comment]
https://discord.gg/sponsorblock

#please-allow-me-to-submit

**Comment by EatVanced** [comment]
#289

**Comment by rahaaatul** [comment]
Thank you @Titivoot & @EatVanced.
I didn't know, I have to do this before I could submit. I submitted my id there.

**Comment by mchangrh** [comment]
> Check unique user id in sponsorblock settings

this is your **private** ID and allows others to impersonate you. 

### __***NEVER SHARE THIS UNDER ANY CIRCUMSTANCE***__

-----

@rahaaatul your SponsorBlock account has been disabled since you have compromised your private ID. 

Please generate a new privateID (36 random characters), make sure to back it up and do not share it

**Comment by rahaaatul** [comment]
>> Please generate a new privateID (36 random characters), make sure to back it up and do not share it

How do I generate new privateID?

**Comment by mchangrh** [comment]
any password generator will do, keep it alphanumeric to be safe and 36 characters long

**Comment by rahaaatul** [comment]
> any password generator will do, keep it alphanumeric to be safe and 36 characters long

Are you sure it's 36 characters long? I think it's more than that.
