### ISSUE TITLE
Keyword Filter not accounting for description 

### ISSUE THREAD

**Issue by Fern-Leaves** [ReVanced/revanced-patches#3432]
### Bug description

The Keyword Filter only checks the video title for keywords and phrases, ignoring the description, it should not do this, it should also check the description and filter videos with the keywords or phrases in the description.

### Solution

make the thing that searches video names for keywords also search video descriptions.

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
The description is loaded with the video and not in any video feed. This is not a bug.
