### ISSUE TITLE
Filter keywords in video description

### ISSUE THREAD

**Issue by Fern-Leaves** [ReVanced/revanced-patches#3433]
### Feature description

I feel the keyword filtering system should crawl the descriptions of the videos in the feed, in order filter out videos that have the keywords in the video description, not just the title, this could be toggleable because it may make the feed take longer to load, idk.

### Motivation

oftentimes people don't include the specific details of what I'm trying to filter out in the title, in order to make the title less cluttered, so they include it in the description instead, so that the algorithm still knows what the video is about and can recommend it accordingly.  I'd like to be able to take advantage of this to filter out videos with my keywords in their descriptions as well.

### Acknowledgements

- [X] I have checked all open and closed feature requests and this is not a duplicate
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Making an additional request per feed item is not efficient enough for a niche case like the description. The current filter is extensive enough
