### ISSUE TITLE
feat: Remove Youtube music videos from "My supermix" playlist

### ISSUE THREAD

**Issue by user716253** [ReVanced/revanced-patches#3436]
### Feature description

In Youtube music there is a playlist called "My supermix" which Youtube creates for you based on your music taste. I have noticed that with Yt premium you can listen to it with just the audio files of the music. But with the free version it mixes music videos in it.

So basically is it possible to remove music videos from this playlist with Revanced? 

Photo added with red circles being music videos and yellow circles being audio files.
![Screenshot_20240712_190924_YouTube Music](https://github.com/user-attachments/assets/2b25e7d0-f4e6-4d93-acf0-1fdf1b72c722)

### Motivation

This is a frustrating issue as in some music videos there are parts with no music or other background noice. 
This feature is a big deal imo since I don't most people who use Yt music want to listen to music videos. That's what youtube is for.

### Acknowledgements

- [X] I have checked all open and closed feature requests and this is not a duplicate
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
No, exclusive audio is behind premium
