### ISSUE TITLE
feat(YouTube): don't autoplay opened urls / clicked videos

### ISSUE THREAD

**Issue by repparw** [ReVanced/revanced-patches#3439]
### Feature description

I don't think there's currently a way (if there is and someone can point me to it thx)
When opening a video it would start paused and you would need to press play, so it doesn't interrupt the video that was already playing (be it casting or in device)

### Motivation

So if you open a link you can see what video it is without interrupting

### Acknowledgements

- [X] I have checked all open and closed feature requests and this is not a duplicate
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
YouTube embeds links on many platforms. If it doesn't, then just watch your video til the end and then click the link.

**Comment by repparw** [comment]
I mean if someone passes a link without waiting for the thumbnail to generate for example
