### ISSUE TITLE
feat: GmsCore Support Custom Value for rooted phone using microG GmsCore

### ISSUE THREAD

**Issue by Clueninja** [ReVanced/revanced-patches#3443]
### Feature description

I have a rooted phone (CarbonROM) with the latest microG Support enabled, I have everything ticked in the microG Self-Check section. How do I use youtube revanced with this instead of the default 'app.revanced' gms client.

### Motivation

So I dont have to install another GmsCore app.

### Acknowledgements

- [X] I have checked all open and closed feature requests and this is not a duplicate
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Your only option is to install the patched app by mounting because preinstalled GMS whitelists signatures of apps. For support, move to one of our links at https://revanced.app.
