### ISSUE TITLE
feat: Search channel

### ISSUE THREAD

**Issue by Spaceshiprace** [ReVanced/revanced-patches#3444]
### Feature description

its on yt web version but not on the app
![348415761-a6eb9d9a-efed-4d8d-bbad-24409079012a](https://github.com/user-attachments/assets/cef10b70-ac0c-4377-8114-d7e95f28fc95)

### Motivation

It makes it easy to search for a video in a specific channel

### Acknowledgements

- [X] I have checked all open and closed feature requests and this is not a duplicate
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Would require modifying lots of litho code, so yeah. Itll be probably added soon by yt if its already in the web version

**Comment by usamac** [comment]
Dang this has always been my number one gripe about the mobile version! Can't stand how the only search is for all of yt.. I use it on a browser regularly. Stinks this can't be patched
