### ISSUE TITLE
bug: YouTube makes GBoard hang

### ISSUE THREAD

**Issue by kscholty** [ReVanced/revanced-patches#3446]
### Bug description

I got high problems when typing comments under Android with the GBoard keyboard. 
Most of the time the Keyboard opens but does not accept input. It also can't be closed. Even closing the YouTube app leaves the keyboard open and frozen. 
It usually accepts input after some time, but it can take minutes.
Funnily it sometimes works flawlessly, unfortunately rarely.
I'm using a Galaxy S9+ with Android 10 and One UI 2.5

### Additional context

Seems #15 reported something similar but has not been taken into account.

### Acknowledgements

- [ ] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
https://github.com/ReVanced/revanced-patches/issues/105#issuecomment-1873645258

**Comment by kscholty** [comment]
Wow. Seems I'm too stupid to search. Sorry for bothering you.
