### ISSUE TITLE
bug: 3 Dots not registering in Youtube

### ISSUE THREAD

**Issue by sm-csgo** [revanced/revanced-patches#345]
### Bug description

The 3 Dots in ui is not registering clicks sometimes

### Steps to reproduce

Step 1: Turn on the App
Step 2: Scroll through ui
Step 3: Try to click the 3 Dots (After some videos it will not work properly)

### Relevant log output

```shell
issue
```

**Comment by voldemort8h** [comment]
@oSumAtrIX Please delete this issue.

**Comment by voldemort8h** [comment]
@oSumAtrIX please delete this issue.
