### ISSUE TITLE
HDR unexpectedly back again

### ISSUE THREAD

**Issue by 0xrxL** [ReVanced/revanced-patches#3452]
### Bug description

Since client spoofing becomes a reality, the more stable spoof (iOS) didn't show HDR on quality menu...until now at least:

In short: I applied a patch to enable [OPUS codec](https://github.com/inotia00/revanced-patches/tree/revanced-extended/src/main/kotlin/app/revanced/patches/shared/opus), created by @inotia00, and I unexpectedly noticed that HDR videos are played as expected:

![Screenshot_20240718_205722](https://github.com/user-attachments/assets/f8634c2f-847e-4704-8a47-5788cb4a6e38)

Oh...and these are my client model infos:

![Screenshot_20240718_205550_Samsung Internet Beta](https://github.com/user-attachments/assets/bb94babb-85a8-4b8b-8cb2-5b38494fd504)

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
What fixes it is the header and not the patch

**Comment by 0xrxL** [comment]
I don't know how HDR has been fixed on my side, so I posted the patch as a possible fix along with the client information I'm using.

**Comment by oSumAtrIX** [comment]
As previously explained it can be fixed by using the expected IOS header in the player request. But there is no known way to change the header just for that request

**Comment by 0xrxL** [comment]
> As previously explained it can be fixed by using the expected IOS header in the player request. But there is no known way to change the header just for that request

It's already fixed for me, as I previously described.

Maybe you can try to check if it is fixed on your side too, with above infos. 🤷‍♂️

**Comment by zainarbani** [comment]
Your device support AV1 decoding?

**Comment by 0xrxL** [comment]
> Your device support HWA AV1 decoding?

Yeah, but before now I wasn't able to enable HDR on videos.

For this reason I thought there is something of useful, that can be applied to stock ReVanced too.

**Comment by zainarbani** [comment]
Thats actually bit strange since HDR video shouldn't be available unless you change the user-agent, 
Can you show the stat for nerd when playing HDR videos?

**Comment by 0xrxL** [comment]
> Thats actually bit strange since HDR video shouldn't be available unless you change the user-agent, Can you show the stat for nerd when playing HDR videos?

I changed the user agent a month ago and only now I got HDR.

Maybe it's due to the new user agent I used?

Anyway you'll find my screenshots [here](https://github.com/inotia00/ReVanced_Extended/issues/2261)

**Comment by zainarbani** [comment]
I try with iOS 15/16 and yeah only iOS 17 got HDR/AV1 format, youtube maybe changes something. 

Prev test with iOS 15 is [here](https://github.com/ReVanced/revanced-patches/pull/3220#issuecomment-2126979925)

Im not iPhone user, but at least iPhone 12 up should support HDR right?

**Comment by 0xrxL** [comment]
> Im not iPhone user, but at least iPhone 12 up should support HDR right?

HDR is available starting from iPhone X, yeah, but I guess that codec wasn't aligned to a one compatible with Android...until now, with the new YouTube changes.

Therefore, user agent patch could become the next to be implemented.

**Comment by 0xrxL** [comment]
https://github.com/ReVanced/revanced-patches/pull/3468
