### ISSUE TITLE
feat: YouTube: share link without notifying creator.

### ISSUE THREAD

**Issue by erydactyl** [ReVanced/revanced-patches#3454]
### Feature description

Allow the option to disable notifying creators when you copy the URL of their video.

### Motivation

This feature would be useful for privacy purposes.

### Acknowledgements

- [X] I have checked all open and closed feature requests and this is not a duplicate
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
I've never heard of sharing links notifying creators.
