### ISSUE TITLE
feat: option to disable swipe feature (up and down) in the full screen mode of Youtube videos

### ISSUE THREAD

**Issue by eldon922** [ReVanced/revanced-patches#3458]
### Feature description

When we are watching video in full screen, in the latest update of Youtube we can swipe up and down to exit full screen mode. It would be nice to have an option to disable it, either the swipe up or down, but especially the swipe up because i always accidentally exit full screen mode if i hold my tablet with my finger on the screen. 

### Motivation

Often, people accidentally exit full screen by holding their device with their finger on the screen. 

### Acknowledgements

- [x] I have checked all open and closed feature requests and this is not a duplicate
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
https://support.google.com/youtube/answer/14001626?hl=en
