### ISSUE TITLE
bug: Tiktok cannot follow anyone; enable darkmode

### ISSUE THREAD

**Issue by CrazyWolf13** [ReVanced/revanced-patches#3460]
### Bug description

Hi
When using tiktok by revanced, I cannot follow anyone, and every account has 0likes and 0 followers, searched on reddit and seems more common on revanced, also on web I cannot follow anyone so my account probably got shadowbanned.

contacted tt support and waiting for their response, which will most likely be suspicious activity.

Also could we **update to a more recent tiktok app version**, so android users can **FINALLY** enjoy **dark mode** tiktok?
Seems like a recent tiktok update finally enabled that.

### Error logs

```shell
don't think I can add anything here -_-
```

### Solution

Possibly spoofing more?
I saw once a PR that spoofed more of the tiktok app, but the user cancelled it: https://github.com/ReVanced/revanced-patches-template/pull/577

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
https://github.com/ReVanced/revanced-patches/issues/2928
https://github.com/ReVanced/revanced-patches/issues/3282

<img width="361" alt="image" src="https://github.com/user-attachments/assets/4656138d-73b0-4a08-9d91-783ea47d94dc">

**Comment by Muramasa95** [comment]
I think this is not a Revanced issue, I had the same issue and looked it online other people had it as well. 
I thought it was from TikTok Revanced, so I tried creating an account from the web but I had the same problem.
Eventually, the issue is gone by itself, I think a month or two.

**Comment by CrazyWolf13** [comment]
> I think this is not a Revanced issue, I had the same issue and looked it online other people had it as well. 
> I thought it was from TikTok Revanced, so I tried creating an account from the web but I had the same problem.
> Eventually, the issue is gone by itself, I think a month or two.

Yeah it's so called shadowbanning, but seems like revanced users get targeted quite frequently.

Also I have been receiving ads since some weeks even though I have the ad blocker option turned on and latest version recommendedq.

**Comment by CrazyWolf13** [comment]
The linked PR points to a PR that fixes a broken link in the docs, sure that that is the PR that fixes bytecode?

And no I just worked for me, but I patch via PC.

**Comment by oSumAtrIX** [comment]
Typo, here's the correct PR: https://github.com/ReVanced/revanced-patches/pull/3490. Trying it out requires checking out a couple of branches everywhere, so it's best to wait until it's merged & then test if that fixes the issues. I think what happens is that the invalid bytecode is gracefully handled but the patches don't work as expected then, on my end it crashes (without the fix from the PR) 🤷

**Comment by CrazyWolf13** [comment]
> Typo, here's the correct PR: https://github.com/ReVanced/revanced-patches/pull/3490. Trying it out requires checking out a couple of branches everywhere, so it's best to wait until it's merged & then test if that fixes the issues. I think what happens is that the invalid bytecode is gracefully handled but the patches don't work as expected then, on my end it crashes (without the fix from the PR) 🤷

Oh I see thanks, no I did not really experience crashes, just when clicking on an account and then playing their videos instead of for-you page I got one ad every 2 videos lol.

Feel free to ping me on any tiktok related thing that needs testing. Happy to help!
