### ISSUE TITLE
Script for ReVanced

### ISSUE THREAD

**Issue by Vendetta2** [ReVanced/revanced-patches#3465]
### Feature description

This [script](https://github.com/ilyhalight/voice-over-translation) can translate video on YouTube in real time by Yandex.

### Motivation

This script can help many people

### Acknowledgements

- [ ] I have checked all open and closed feature requests and this is not a duplicate
- [ ] I have chosen an appropriate title.
- [ ] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
This is not a proper motivation & https://github.com/ReVanced/revanced-patches/issues/3280

<img width="414" alt="image" src="https://github.com/user-attachments/assets/8a6f29fa-5fe9-4be7-b280-bc48e7aeedc1">
