### ISSUE TITLE
`Hide NavBar in Shorts` keeps working even if you exit the Shorts Player.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [ReVanced/revanced-patches#3467]
### Bug description

When you cold-start your app, this is what you will get:

![Screenshot_2024-07-24-15-41-41-24_f22faf49515899f9781ec174a4d85388](https://github.com/user-attachments/assets/48c76e73-4005-4162-ae65-506a15673af8)

Now, open any Short from your Home Tab or Subscriptions Tab. Play 2-3 Shorts. Now press the back button and this is what you will get:

![Screenshot_2024-07-24-15-42-02-74_f22faf49515899f9781ec174a4d85388](https://github.com/user-attachments/assets/c4ff1306-98a2-4c85-9acb-4e7f8eb272ab)

As you can see, NavBar is still hidden, even when you've exited the Shorts Player. So, kindly fix it.

### Error logs

```shell
No logs.
```

### Solution

`Hide NavBar in Shorts` should work properly.

### Additional context

No additional context.

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Caused by/same issue as https://github.com/ReVanced/revanced-patches/issues/3349
