### ISSUE TITLE
feat (Youtube): Prevent videos from watch later playlist showing up on home feed

### ISSUE THREAD

**Issue by HomerAyuste** [ReVanced/revanced-patches#3473]
### Feature description

This feature would not show any videos from the "watch later playlist" (such as one shown below) from showing up on the home feed. 
![Screenshot_20240726_160021_YouTube](https://github.com/user-attachments/assets/e111f885-6792-4863-a7fd-31ff4a353e1b)

### Motivation

Some users might not want to see videos from the watch later playlist on their home feed. It would make for a better home feed for users who don't want it "bloated" with these videos showing up on their feed.

### Acknowledgements

- [X] I have checked all open and closed feature requests and this is not a duplicate
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by HomerAyuste** [comment]
> Try adding a keyword filter of `From your Watch later playlist` (copy paste this exact string)

I just tried this. It removes the `From your Watch later playlist` label but not the videos themselves (which is more of what I was going for).

**Comment by oSumAtrIX** [comment]
Pretty sure you can click on not interested -> Already seen and the algorithm adapts to not showing you videos from your history.
