### ISSUE TITLE
Warn that custom branding doesn't work with mounting

### ISSUE THREAD

**Issue by xparadoxical** [ReVanced/revanced-patches#3476]
### Feature description

Add `(non-root only)` to the patch description

### Motivation

#3475, https://github.com/ReVanced/revanced-patches/issues/3374#issuecomment-2186351911, better to warn before spending a few minutes and being disappointed.

### Acknowledgements

- [X] I have checked all open and closed feature requests and this is not a duplicate
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Installation methods are a concept of the apps applying the patches, not the patches themselves.

**Comment by xparadoxical** [comment]
Then the app could say something in a popup when it's applying a patch that will not work in the specific configuration due to a limitation. The popup would be shown when selecting the "mount" method, or trying to proceed to patching. The lack of communication of this fact *is* an open issue, and it shouldn't be ignored by closing. You could at least suggest anything about tackling this lol

**Comment by oSumAtrIX** [comment]
Apps applying patches are agnostic towards them. They can't take into account one specific patch.

**Comment by xparadoxical** [comment]
So then the patch using its way of rebranding, that has limitations, should warn it will not work when mounting

**Comment by oSumAtrIX** [comment]
Installation is a concept of the apps and not patches. I have already told you this in my initial comment.

**Comment by xparadoxical** [comment]
This is closely tied to the combination of an installation type and the patch 🤷‍♂️
