### ISSUE TITLE
Bug(YouTube): Subscription keyword filters do not work

### ISSUE THREAD

**Issue by goooglefc** [ReVanced/revanced-patches#3479]
### Bug description

![Screenshot_2024-07-28-06-28-51-457_app revanced android youtube~2](https://github.com/user-attachments/assets/a9e0ef1d-1d92-4aff-bcd4-bc9db83c0518)

When I click on videos filter, all the live streams should be hidden from the subscription feed but that's not happening. The problem started few days ago.
Also, keyword filtering on Subscriptions feed is not working from last 2 days. 

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by goooglefc** [comment]
> For keyword filtering, try using a different YT account and try turning on version spoofing. It's probably a new layout for the subscription tab.
> 
> The `All`, `Today`, etc filters are a YT feature and whatever is going wrong there is probably YT bug or is new behavior.

Keyword filtering works with a different account. Is there any way to make it work with the account i am using?

**Comment by goooglefc** [comment]
> Did you try version spoofing?
> 
> If you enabled debug logging in `Misc` and collect the logs using adb, the keyword filter feature could be updated to use the new layout. Search for [guides](https://sodawithoutsparkles.github.io/revanced-troubleshooting-guide/04-adb-install/) on how to help setup and use adb with a computer, then follow the debugging step [here](https://github.com/revanced/revanced-integrations?tab=readme-ov-file#-how-to-use-debugging) to collect the logs

Tried Version spoofing but no help.
I checked on revanced extended and everything seems to be working fine there. Subscription filters as well as keyword filters.

**Comment by oSumAtrIX** [comment]
Follow the instructions in the second paragraph.

**Comment by goooglefc** [comment]
> @goooglefc try adding the custom filter: `video_lockup_with_attachment.eml$keyword` Where `keyword` is one of your filters (it is case sensitive).
> 
> Then check if videos with that keyword are hidden in the subscription feed.

Yes it does work that way.
However I have about 30+ filter words.

**Comment by goooglefc** [comment]
> It's [fixed](https://github.com/ReVanced/revanced-integrations/commit/2f2eeea5a722b6b7053eb2825d16fa37938b4e9e) on dev release. Patch using command line tools, or wait until dev is merged to main and patch as usual with Manager.

Ok, will wait.
The adb thing a bit too complicated for me.
