### ISSUE TITLE
bug(YouTube): "Hide Playables" does not work

### ISSUE THREAD

**Issue by MewtwoFanz** [ReVanced/revanced-patches#3484]
### Bug description

The "Hide playables" button does not do anything. I tried re enabling it and still it did not hide playables in the app. 

### Solution

Make the "Hide playables button actually work. 

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by MewtwoFanz** [comment]
OK, I don't know how, I don't know why, but I managed to fix it. I changed the spoof version and then, went back no spoof version, and it fixed itself somehow.

**Comment by oSumAtrIX** [comment]
a/b. Closing until someone can provide the requested info above.
