### ISSUE TITLE
Exiting Revanced for bit then re entering causes app to say im not connected to the internet

### ISSUE THREAD

**Issue by MewtwoFanz** [ReVanced/revanced-patches#3488]
### Bug description

I cannot safely exit the app then re enter without it saying you're not connected to the internet. I cannot fix it without restarting my phone. 

### Solution

Just make it so it won't disconnect when I exit and later re enter the app

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
https://github.com/ReVanced/revanced-patches/issues/2587
