### ISSUE TITLE
feat(YouTube): Allow users to choose localization

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [ReVanced/revanced-patches#3496]
### Feature description

Add a setting to allow users to choose different localization/languages for ReVanced settings

### Motivation

- Some users may want to use English to communicate to supporters/others
- It may be hard to understand the options when translations were not done properly
- (cont.) To fix the translations, translators need to use English with context in the app 
- Multi-lingual users might not want the default localization. Especially when the languages has multiple variants, like Chinese
- (cont.) When the language has multiple variants, users may want to use another localization as it might be better translated
- Some bugs might only appear in a certain language, and it may be needed to revert to English to test

### Acknowledgements

- [X] I have checked all open and closed feature requests and this is not a duplicate
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
YouTube has a setting in General to change the app language. Does that toggle our localized setting languages too?

**Comment by SodaWithoutSparkles** [comment]
Users may want to disable just ReVanced's translations because of the following reasons:

- Some users may want to use English to communicate to supporters/others
- Multi-lingual users might not want the default localization. Especially when the languages has multiple variants, like Chinese
- (cont.) When the language has multiple variants, users may want to use another localization as it might be better translated

And disabling translations in the whole app, or changing the whole app's translations is not ideal for the above cases.

**Comment by oSumAtrIX** [comment]
- Supporters or similar is nothing related to the patches. This is something others have to figure out themselves
- If they do not want the default localization, they can change the app language
- Just translating specific parts of the app does not make sense. YouTube for sure also has translations which aren't ideal but you can not change them separately either.

The translations changing when the app language is changed makes sense.

**Comment by SodaWithoutSparkles** [comment]
YouTube's translations are more refined because they are a global corporation which have the resources to hire loads of people to translate and proof-read. 

ReVanced however is not. ReVanced translations are done by volunteers which may not be familiar with the app's design. We don't have the resources to do so.

Certain parts of ReVanced menu are also not translated (because the translations are missing) which looks strange. YouTube however doesn't have these kinds of issues.

**Comment by SodaWithoutSparkles** [comment]
Yes they do need to be fixed. But the release cycle is long. Incomplete translations should be treated as alphas and users should be able to disable them.

In the meantime users should be able to opt-out

**Comment by oSumAtrIX** [comment]
The release cycle isn't long or at least as long it would take to release the requested change. Unless any issue is filed regarding the problematic strings theres no call to fix them and right now there's no issue mentioning your claimed problems and thus everything is a-ok as is. If theres issues with strings, you can open discussions regarding them on translate.revanced.app.

**Comment by oSumAtrIX** [comment]
It's not forced, the same way YouTube doesn't.
