### ISSUE TITLE
(bug/YouTube) : "Remind me to take a break" feature doesn't work when video is playing in background

### ISSUE THREAD

**Issue by sam352** [ReVanced/revanced-patches#3501]
### Bug description

There is a YouTube feature called "Remind me to take a break" which stops your video after an amount of minutes you decided before (in my case 30 minutes).

This feature can be found in settings -> general -> Remind me to take a break

It's really usefull for me because i'm sleeping with my headphones and YT video in background so it stops itself after 30 minutes, so i can fall asleep with my headphones

This feature used to work but since few month, it only works when the app is displayed and you are actively watching videos, it doesn't work when videos are playing in background anymore.

Could you fix this please ? 

Thank you very much.

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
This bug is present on the unpatched app
