### ISSUE TITLE
bug(RIF / reddit is fun): Redgifs no longer play sounds in RIF

### ISSUE THREAD

**Issue by LEARJS** [ReVanced/revanced-patches#3502]
### Bug description

In the past week or so, Redgifs links no longer play sounds inside RIF, the speaker icon is grayed out. When opening these links in any external browser the sound is available. The same thing happening with both "redgifs" and "v3.redgifs". 
There are 2 things that I noticed: 
- Super old redgifs links that were posted/cached years ago were mostly unaffected, while newly created/posted links from the past 1-2 years were affected. 
- You can tell that a link contain sound when Redgifs logo appear somewhere in the upper left corner like this: 
<img src="https://github.com/user-attachments/assets/77ea089c-66e3-4be8-a812-137a760eac70" width="500">

I've already tested this issue on different devices and it's the same throughout. Hopefully this can be an easy fix. 

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
This is not a bug caused by ReVanced. RIF is discontinued.
