### ISSUE TITLE
feat: Google maps features 

### ISSUE THREAD

**Issue by weirdal3333** [revanced/revanced-patches#351]
### Type

Functionality

### Issue

A lot of Google maps features get enabled/disabled randomly whenever Google updates their app.

Things like media playback controls and different types of navigation... Can you make things toggleable in the app?

### Feature

Bring back Media controls that Google turns off on some devices.

### Motivation

Google doesn't think about consumers. Revanced YouTube Music works with the Google maps media playback controls.

### Additional context

https://support.google.com/maps/thread/137898548/how-can-i-enable-media-playback-control-in-google-maps

**Comment by oSumAtrIX** [comment]
Wrong place to submit suggestions
