### ISSUE TITLE
bug: YouTube history broken again?

### ISSUE THREAD

**Issue by ProTechnomancy** [ReVanced/revanced-patches#3510]
### Bug description

I remember a similar bug a few months ago. If is only me encountering it now I'll uninstall/reinstall everything.

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
https://github.com/ReVanced/revanced-patches/issues/3208
