### ISSUE TITLE
feat(Google Search): Always use default browser, not Chrome

### ISSUE THREAD

**Issue by aubymori-backup** [ReVanced/revanced-patches#3511]
### Feature description

If your device has Google Chrome installed and you have gone through the first run setup for Chrome, the Google Search app will always open links in a Chrome view, and not your default browser. The proposed patch would disable the functionality and always use your default browser (and possibly use the in-app view instead of opening the app separately?).

### Motivation

I use Mozilla Firefox Nightly on my phone, and I have uBlock Origin installed. It is frustrating to have the Google app open links in a browser that does not support extensions whatsoever, and causes me to be bombarded with apps until I invoke the menu to manually open the site in Firefox. As well, it is annoying because Chrome is not my browser of choice and therefore I am not signed into my accounts on it.

### Acknowledgements

- [X] I have checked all open and closed feature requests and this is not a duplicate
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
You can disable chrome.
