### ISSUE TITLE
Download Playlist

### ISSUE THREAD

**Issue by kittenvr** [ReVanced/revanced-patches#3512]
### Feature description

A feature that adds a button to download a whole playlist like watch later externally

### Motivation

It would be more convenient then to download the videos one by one

### Acknowledgements

- [X] I have checked all open and closed feature requests and this is not a duplicate
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
You can share a playlist and then download it that way via any external downloader.

**Comment by kittenvr** [comment]
> You can share a playlist and then download it that way via any external downloader.

@oSumAtrIX you can't share watch later

**Comment by oSumAtrIX** [comment]
use a custom playlist as a watch later playlist

**Comment by kittenvr** [comment]
> use a custom playlist as a watch later playlist

Then I would need to put all my videos from watch later to another playlist

**Comment by kittenvr** [comment]
And other playlist doesn't gave remove watched videos

**Comment by kittenvr** [comment]
@oSumAtrIX

**Comment by 7Grn** [comment]
> > You can share a playlist and then download it that way via any external downloader.
> 
> @/oSumAtrIX you can't share watch later
https://github.com/ReVanced/revanced-patches/issues/3512#issuecomment-2272160014

just use <https://www.youtube.com/playlist?list=WL>
as long as you register the cookie for the account you want to use with Seal/YTDLnis, you can download Watch Later
