### ISSUE TITLE
bug(YouTube): Push notifications do not work

### ISSUE THREAD

**Issue by biglisy** [ReVanced/revanced-patches#3521]
### Bug description

Since patching Youtube with the latest 4.12.0 patches, no push notifications are received. Tried reinstalling MicroG and making sure everything was setup correctly, but nothing.

Revanced Manager 1.21.1

Youtube 19.16.39

List of patches: 
    "Alternative thumbnails",
    "Always repeat",
    "Announcements",
    "Bypass URL redirects",
    "Bypass image region restrictions",
    "Change start page",
    "Comments",
    "Copy video URL",
    "Custom branding",
    "Custom player overlay opacity",
    "Disable auto captions",
    "Disable fullscreen ambient mode",
    "Disable player popup panels",
    "Disable precise seeking gesture",
    "Disable resuming Shorts on startup",
    "Disable rolling number animations",
    "Disable suggested video end screen",
    "Disable zoom haptics",
    "Downloads",
    "Enable tablet layout",
    "GmsCore support",
    "Hide Shorts components",
    "Hide ads",
    "Hide album cards",
    "Hide autoplay button",
    "Hide captions button",
    "Hide cast button",
    "Hide crowdfunding box",
    "Hide endscreen cards",
    "Hide filter bar",
    "Hide floating microphone button",
    "Hide info cards",
    "Hide layout components",
    "Hide player buttons",
    "Hide seekbar",
    "Hide timestamp",
    "Hide video action buttons",
    "Miniplayer",
    "Navigation buttons",
    "Open links externally",
    "Playback speed",
    "Player flyout menu",
    "Remember video quality",
    "Remove background playback restrictions",
    "Remove tracking query parameter",
    "Remove viewer discretion dialog",
    "Restore old seekbar thumbnails",
    "Restore old video quality menu",
    "Return YouTube Dislike",
    "Seekbar tapping",
    "SponsorBlock",
    "Spoof app version",
    "Spoof client",
    "Spoof device dimensions",
    "Swipe controls",
    "Theme",
    "Video ads",
    "Wide searchbar"

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by biglisy** [comment]
> Does stock YT show push notifications?
> 
> I don't see how any patches can cause this. It's probably something that needs changing in your MicroG settings, or in your device settings, or needs changing in your YT account.

I haven't actually tried stock, silly me. Should I try with the same version that i use patched? 19.16.39 that is, or the latest one?

And I don't know how, but I have updated it with the new patches on both of my devices, tablet and phone and both stopped receiving any notification from Youtube alone since then. Tried reinstalling MicroG and Youtube but nothing.

I'll try to see stock.

**Comment by biglisy** [comment]
> Does stock YT show push notifications?
> 
> I don't see how any patches can cause this. It's probably something that needs changing in your MicroG settings, or in your device settings, or needs changing in your YT account.

Ok I tested stock same version as the patched one and notifications come through. But that's weird, it's worked normally until couple days ago without any changes to settings, only repatched. MicroG says everything is ok in the self check. 

But just to be sure, could you point me to a more recent MicroG to use? I find a lot of different versions or different branded ones I'm kinda lost.

**Comment by biglisy** [comment]
> The most recent is from April this year:
> 
> https://github.com/ReVanced/GmsCore/releases

Installed that (had an older version), then reinstalled patched Youtube and notifications don't come through.

MicroG shows everything is looking good. my Google acc is in there, device registered, Youtube app registered. 

😔

**Comment by biglisy** [comment]
I think I may have found the problem, with the recent update of the Revanced Manager, when I patch Youtube it's showing that I just installed regular Youtube installed, which is disabled. Previously it was showing as Revanced Youtube with its own icon and package name. I tried completely removing the stock Youtube via adb, but it still won't show that I just installed Revanced Youtube. it's not in the list of patched apps, as shown in the screenshot below:

![Screenshot_2024-08-09-23-20-35-67_a85b47aaa863e3bc831e16d29c27a79c](https://github.com/user-attachments/assets/0a159da3-087e-4f11-b7ba-185003198afb)
![Screenshot_2024-08-09-23-23-30-07_a85b47aaa863e3bc831e16d29c27a79c](https://github.com/user-attachments/assets/c5b4cb11-4add-4573-ac7d-92b05b499237)

**Comment by biglisy** [comment]
Yup, went back on Manager 1.20.1 and it installs as expected, showing it as Youtube Revanced and notifications come through again.

**Comment by Marocco2** [comment]
I can confirm the exact same issue here.
MicroG shows that messages are indeed received but no notification is appearing

![Screenshot_20240810-212141](https://github.com/user-attachments/assets/1348aba4-0aff-4196-af11-021279e0c44a)

Tried both reinstalls, doesn't fix. It's happened for the first time on 4.12.0

**Comment by SusStew** [comment]
Exact same issue, the above workaround by downgrading the manager doesn't seem to fix notifications.

**Comment by biglisy** [comment]
> Exact same issue, the above workaround by downgrading the manager doesn't seem to fix notifications.

Actually same, I mistook the notifications for Youtube's but it was actually Youtube Studio.

There seems to be currently no way to get back notifications working on Youtube.

**Comment by nowster** [comment]
Same problem here. GMSCore is receiving the pushes but the intents don't seem to be getting to the right app and triggering a notification.

**Comment by biglisy** [comment]
> Same problem here. GMSCore is receiving the pushes but the intents don't seem to be getting to the right app and triggering a notification.

It seems to be an issue with the gms core support patch that was recently updated. Patching the app through CLI with older patches makes notification works, so waiting for a fix via patches update.

**Comment by oSumAtrIX** [comment]
The issue was introduced in 1.12.0.dev.5. The relevant commit changed some code regarding GmsCore
