### ISSUE TITLE
(Craigslist) Remove Play Integrity check

### ISSUE THREAD

**Issue by snappyapple632** [ReVanced/revanced-patches#3523]
### Feature description

App Name: Craigslist

Requested feature: Remove Play Integrity checks.

Remove the Play Integrity checks that prevent rooted users from reading posts within the app.

### Motivation

Play Integrity is an unnecessary measure for the majority of end users using the app, as those using Craiglist for malicious purposes typically use other methods that do not require the Craigslist app. Rooted users are unable to use the app for its intended purpose unless they are using patches to circumvent device integrity checks.

### Acknowledgements

- [X] I have checked all open and closed feature requests and this is not a duplicate
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
The entire purpose is to exactly prevent this patch
