### ISSUE TITLE
bug: No permanent Autoplay on/off button for YouTube when listening to music

### ISSUE THREAD

**Issue by kriki200** [ReVanced/revanced-patches#3527]
### Bug description

The Autoplay on/off works fine on normal videos, but is hidden on music videos, unless you disable autoplay on a normal video before. It would be nice, if we could have it permenantly up there, as for example listening to songs before bed you can't make it so it doesn't auto play the next one, if you don't want to turn it off afterwards.

This is probably as intended by YouTube, but is annoying.

Normal video:

![453582132_762326905889250_4999963009653700500_n](https://github.com/user-attachments/assets/3d38714d-be89-4914-8ff2-7f76e773bbe2)

Song:

![452625754_1926699864444250_3626811997598410958_n](https://github.com/user-attachments/assets/eff07e7c-60d7-495d-b471-a9dcaff4ac19)

### Solution

Permenant Autoplay on/off button, even on songs.

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Thats hidden by a patch and can be enabled in the settings. For support, move to one of our links at https://revanced.app.

**Comment by kriki200** [comment]
If you mean this one:

![Screenshot_20240811-202010_YouTube](https://github.com/user-attachments/assets/9753fd2d-47be-4efe-adff-99cfd62cba7d)

I already disabled it in the settings, but it only works for non music videos, all the music videos are still withouth the button unless you disabled the Autoplay on a normal video (then it appears, but hides again if autoplay is enabled).

I went through the settings and there was no other opition, if it is could you point me to it?

Sorry for reopening the issue if there is another setting for it.

**Comment by kriki200** [comment]
@oSumAtrIX I got told on xda to mention you.

Apparently the autoplay on/off button is always hidden if your on a playlist (music videos automatically trigger them). I was wondering if there was a way to make it persistant, also available when on a playlist.
