### ISSUE TITLE
bug: Forced auto captions are disabled won't work in YouTube shorts

### ISSUE THREAD

**Issue by Bakchxd** [ReVanced/revanced-patches#3529]
### Bug description

In YouTube **shorts
![Screenshot_20240812-080248](https://github.com/user-attachments/assets/9f5df271-10c9-490a-a7db-5333882242f3)
** Forced auto captions are disabled won't work in YouTube shorts

### Additional context

Sometimes the issue won't exist at all for an entire viewing session.

I have had this issue for several weeks now, and even existed after updating to to versions later than 19.16.39 when they were supported

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Unofficial patches

**Comment by Bakchxd** [comment]
what 🤌? 
so in officials patch no bug like this. 
i patch in rvx_v19.16.39-patches_v4.12.1
