### ISSUE TITLE
feat(McDonald's): Remove Play Integrity check

### ISSUE THREAD

**Issue by kalex3** [ReVanced/revanced-patches#3535]
### Feature description

Package name: com.mcdonalds.mobileapp
Requested feature: remove Play Integrity checks

### Motivation

The McDonald's app doesn't work on GrapheneOS, since [it requires you to pass the Play Integrity check](https://discuss.grapheneos.org/d/9123-the-mcdonalds-app-doesnt-work).
I don't really understand why this is necessary. Even my banking apps worked flawlessly without Play Integrity. This is the only app I couldn't get to work on Graphene.
When I saw [this patch for the SwissID app](https://github.com/ReVanced/revanced-patches/pull/3478), I had a glimpse of hope: could the same be done for the McDonald's app?

### Acknowledgements

- [X] I have checked all open and closed feature requests and this is not a duplicate
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
The point of play Integrity is exactly to prevent this patch
