### ISSUE TITLE
feat(Google Photos): Add Google Pixel Phone patch

### ISSUE THREAD

**Issue by SubZero5** [ReVanced/revanced-patches#3536]
### Feature description

Pixelify-Google-Photos is a patch that imitates a Google Pixel device to Google Photos so that it can enable unlimited photos and videos backup.

### Motivation

I wish revanced could patch the Google Photos app so that the device does look like a Google Pixel device so it can do unlimited photos and videos backup. 

### Acknowledgements

- [X] I have checked all open and closed feature requests and this is not a duplicate
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by kairusds** [comment]
This might actually piss off Google.

**Comment by steel101** [comment]
I see a branch with it in dev mode how can you try it out do I have to use cli or can you change branch in manger app
