### ISSUE TITLE
bug: Videos watched in ReVanced don't get added to the history

### ISSUE THREAD

**Issue by Szaamaan** [ReVanced/revanced-patches#3538]
### Bug description

Watching a video via ReVanced doesn't cause the YouTube history to be updated with that video.

Steps:
- Check ReVanced history
- Watch any new video
- Check history again (after refreshing)
- Watched video doesn't show in the history
- Additionally check the same account from a PC to ensure it's not a client-side refresh issue - history is also not updated there

I'm using the default patch selection + Custom Header + Custom Branding. To be sure I've just updated both ReVanced manager (1.21.2) and the patched YouTube (19.16.39) with the patches listed previously (4.12.0). This was just prior to making this bug report, so `Wed Aug 14 08:39:46 2024 UTC`.

### Error logs

```shell
N/A
```

### Additional context

I don't think this is the same thing as https://github.com/ReVanced/revanced-patches/issues/2779

After all, this is a fairly old issue and I've updated the app with the latest patches...

### Acknowledgements

- [ ] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
https://github.com/ReVanced/revanced-patches/issues/3208
