### ISSUE TITLE
bug: (SoundCloud) playback history not save

### ISSUE THREAD

**Issue by KaaaooS** [ReVanced/revanced-patches#3539]
### Bug description

I listen a song but i go to search the song in playback history and not appears

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [ ] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Try the unpatched app

**Comment by KaaaooS** [comment]
> Try the unpatched app

But works hide apps and thats features with unpatched app??

**Comment by oSumAtrIX** [comment]
Please check if the history works on the unpatched app. Hide ads isn't at question right now.

**Comment by KaaaooS** [comment]
> Please check if the history works on the unpatched app. Hide ads isn't at question right now.

Yes,normal app works the playback history,save my last song

**Comment by oSumAtrIX** [comment]
Test one patch and check if history is working

**Comment by KaaaooS** [comment]
> Test one patch and check if history is working

Now is working

**Comment by KaaaooS** [comment]
Stay happens,the history not save and the song desapears,in normal app works but in the patch app not

**Comment by KaaaooS** [comment]
> @KaaaooS what patches did you include?
> 
> Did you include `disable telemetry`? If so try excluding it.

I disable telemetry and happens too

**Comment by oSumAtrIX** [comment]
Send a full recording showinng how it works in the patched app but not after you patch it with hide ads.

**Comment by KaaaooS** [comment]
> Send a full recording showinng how it works in the patched app but not after you patch it with hide ads.

After a force close and reinstall another one excluding disable telemetry,now save the song in the history, need a long time tobappears in the list,like 1 min more less but appears
