### ISSUE TITLE
bug (RIF / reddit is fun): imgur links in RIF yields to error. Can't open imgur links

### ISSUE THREAD

**Issue by Kantotero** [ReVanced/revanced-patches#354]
### Type

Error at runtime

### Bug description

Revanced Manager Version: 1.9.5
App: RIF is fun
Rif Version: 5.6.22

Opening imgur album links in RIF  leads to errors when RIF attempts to load the images in its embedded imgur viewer.

### Steps to reproduce

Step 1: open an imgur link from a comment. 
Step 2: get imgur error in RIF's embedded imgur viewer

### Relevant log output

```shell
Can't export log on RIF. No in-app settings
```

### Screenshots or videos

![Screenshot_20230826-073650_rif_is_fun](https://github.com/ReVanced/revanced-patches/assets/125627064/447d5d4a-1fa9-45fe-935f-6f09f46cc780)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by ubiquitous-lei** [comment]
Is there any update to this yet?

**Comment by AngelouDi** [comment]
Is anybody looking into this?

**Comment by realDayaa** [comment]
IIRC this happens because the original imgur api key expired. We would probably need to create/supply our own key for patching.

**Comment by kimsey0** [comment]
As a workaround, you can go to Settings > Browser > External browser URLs and add a rule for domain `imgur.com`, disable _Include subdomains_, and enable _Never in RIF_. Then you'll just see Imgur links in the in-app browser.

**Comment by oSumAtrIX** [comment]
Seems like the key is expired. This is not a ReVanced bug.

**Comment by kimsey0** [comment]
Has anyone been able to locate the Imgur key? In can't really find it in the APK. If we can locate it, we can patch it.
