### ISSUE TITLE
feat: Being able to open Revanced from Google Chrome

### ISSUE THREAD

**Issue by giejay** [revanced/revanced-patches#355]
### Type

Functionality

### Issue

Currently, when opening links after searching on for example Google, the link will direct you to the mobile website.

### Feature

It would be nice if the link would direct you to the Revanced app instead. I checked the app settings and the set as default is set correctly including all YouTube hosts, but is does not work.

### Motivation

It would be very convenient to have this feature because this would greatly reduce the time of needing to open Revanced manually again.

### Additional context

Non rooted Samsung S21

**Comment by oSumAtrIX** [comment]
This is a setting in your phone, change it to open YouTube links in the app you want.
