### ISSUE TITLE
bug: YouTube: selecting videos in incognito mode automaticlly plays mix playlist

### ISSUE THREAD

**Issue by hl2jeep** [ReVanced/revanced-patches#3557]
### Bug description

Opening some videos and music videos in incognito mode causes a mix playlist to be automatically played without me wanting it to do so.

### Additional context

https://github.com/user-attachments/assets/d7b306cf-2fbd-4613-92fe-fcc7258547b4

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Not a bug, nor caused by ReVanced.
