### ISSUE TITLE
bug: video playback stops after unlocking phone

### ISSUE THREAD

**Issue by jonas-hurst** [revanced/revanced-patches#356]
### Type

Error at runtime

### Bug description

playing a video, locking and then unlocking the phone causes the video playback to stop in incognito mode

### Steps to reproduce

1. Start Youtube Revanced
2. Enable incognito mode
3. play a video
4. lock phone
5. unlock phone

Expected behavior: Video playback continues
Observed behavior: Video playback stops

### Relevant log output

```shell
not available
```

### Additional context

youtube: v17.31.36
cli: v2.9.3
patches: v2.36.2

**Comment by jonas-hurst** [comment]
Can no longer be reproduced --> closing issue
I will keep an eye for this issue in the upcoming updates and potentially reopen this issue.

youtube: v17.32.35
cli: v2.9.3
patches: v2.42.0

**Comment by um488** [comment]
I got the same issue on 17.32.35 with latest patches. And I can reproduce this on all versions by changing any entry in revanced settings (preferably in layout or ads sub-menus) after fresh install.

**Comment by jonas-hurst** [comment]
Hmm, interesting. Yes I can reproduce like this so I will reopen the issue.
