### ISSUE TITLE
feat: Hide suggested videos below the player

### ISSUE THREAD

**Issue by DidierLoiseau** [ReVanced/revanced-patches#3560]
### Feature description

When not in full screen, below the player you have 1 comment and then an infinite scrolling list of video suggestions. I would like to hide these.

### Motivation

These video suggestions try to keep the user involved and make them consume more content. It plays on the user’s addiction, making it more difficult to leave. Hiding those suggestions would give back more control to the user in their choice of content.

It is also impossible to avoid them currently, because you will always see them when starting a video (before entering full screen) and after the video if you want to go back to e.g. your subscription.

Previous requests: this feature was originally requested in a comment of #981, and later requested in #1734, but at the time it was possible to hide the suggested videos with a filter (albeit not an ideal solution, since it strained the API). Anyway, it appears that workaround does not work anymore.

### Acknowledgements

- [X] I have checked all open and closed feature requests and this is not a duplicate
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
You can enter horizontal or vertical fullscreen on YouTube effectively hiding suggested videos which is fine to do at the beginning of the video.
