### ISSUE TITLE
bug: YouTube Music runs at 100% cpu even when closed. 

### ISSUE THREAD

**Issue by johanno** [ReVanced/revanced-patches#3561]
### Bug description

I noticed my Fairphone 4 to draw too much power recently.

After running top via adb shell I could see that yt music was running at 100% cpu most of the time.

I hadn't updated the app in months and the issue was relatively recent, so I guess youtube changed sth. On their servers to make yt music revanced ping constantly.

I updated to the newest version of yt music and patched it. But only after a few days my phone ran again with yt music at 100%

### Solution

Figure out what yt music is doing when it runs at 100% cpu. And fix it. 

### Additional context

I am a software developer and know how to do some stuff with adb, but I don't know how to debug yt music with revanced. 

The issue does not appear directly after installation. It takes several days to occur. 

Since top shows me up to 400% cpu usage I guess it is a single core process which is the issue. 

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
![1000016668](https://github.com/user-attachments/assets/12c683dc-e2a6-4565-9244-3ba705b0dbe8)

**Comment by pcwizard7** [comment]
Can you post the temporary fix? or what was last known good version to stay on?

thanks

**Comment by oSumAtrIX** [comment]
Please follow my previous message.

**Comment by oSumAtrIX** [comment]
Closing until the requested info is provided

**Comment by johanno** [comment]
Ok i updated the issue with a logcat from when I killed the app and the background service from when I start it and it run back up to over 100 cpu usage. But I don't think anything in there seems to be the reason. I will try out to find the patch responsible, however this will take for ever since the issue only occurs days after installation.

**Comment by johanno** [comment]
> You can try restricting battery usage for YT Music (go to app info -> battery -> change from 'optimized' to 'restricted').
> 
> But this may interfere with background playback so have to try and see.
> 
> Can also try patching older versions of YT Music. You will need to turn off version compatibility checks in Manager, and some patches may fail to patch so try a few older versions. Also need to uninstall any existing patched YT Music versions in between installs since it's a downgrade.

I might use the restricted option as a workaround. But for now I want to figure out what is causing this issue.

Since this issue was even on a at least 1 Year old version of patched youtube music, but the issue itself only occurred a few months ago. I don't think going back a few versions will help. I am  not even sure what kind of thing could cause a process to hang like that in the background.

**Comment by johanno** [comment]
Ok I can now confirm that the issue lies within the official youtube music app. After running for at least a few hours (sometimes 6-15) the version 7.03.52 will somehow run at 100% cpu for no reason. Closing the app will keep the process alive. Why this also appeared in a way older version I don't know.
