### ISSUE TITLE
bug(YT music): can't play audio

### ISSUE THREAD

**Issue by wlUnUlw** [ReVanced/revanced-patches#3562]
### Bug description

https://github.com/user-attachments/assets/ebcdf812-d5c2-4a6a-a6c7-e47dd7c5d518
YT music play for less than a sec then stop as in record.  

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Issue with your device/youtube music. Disable Pip

**Comment by wlUnUlw** [comment]
Wdym? Is there another solution to fix it since disable pip not working
