### ISSUE TITLE
bug: YT history not working

### ISSUE THREAD

**Issue by Valour549** [ReVanced/revanced-patches#3571]
### Bug description

• Android 13. Non-brand YT account.
• Latest version of revanced manager 1.21.2
• Latest version of revanced patch 4.13.3
• Patched YT to the recommended 19.16.39 (all patches applied)
• Installed and disabled battery optimization for revanced GMScore 0.3.1.4
• Logged into my Google account and made sure my YT history is on.
• My history works fine on the YT webpage or official YT app, just not revanced YT.

### Acknowledgements

- [ ] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
https://github.com/ReVanced/revanced-patches/issues/3208 

<img width="403" alt="image" src="https://github.com/user-attachments/assets/6052eeea-2d64-4703-87ba-c6422048b887">

**Comment by Valour549** [comment]
I did check the other bug post but it seems to be about iOS spoofing and history not working on brand accounts.

**Comment by Valour549** [comment]
Sorry I have no idea what Android VR spoof is or how to add it.

**Comment by Valour549** [comment]
Got it, I'll keep an eye on that thread. Thanks for all the help.

**Comment by toine512** [comment]
If you've never activated Google+, your Youtube account got converted to a brand account tied to your GMail address. (You should have 2 Youtube accounts available. One is your Gmail address, the other is the one you really use.)
So I just discovered I have a brand account.
