### ISSUE TITLE
feat: Alltrails `com.alltrails.alltrails` features/patches

### ISSUE THREAD

**Issue by jo-chemla** [ReVanced/revanced-patches#3583]
### Feature description

It would be great to implement some patches for Alltrails `com.alltrails.alltrails` ([playstore link](https://play.google.com/store/apps/details?id=com.alltrails.alltrails)). The below features are restricted but available in the app

- Remove ads
- 3d map Preview 
- Offline maps
- Live position sharing 
- Off track alerts 

### Motivation

Alltrails is among the most used apps for hiking/cycling, for preparing and following tracks. These features are often very useful, and already implemented. 

### Acknowledgements

- [X] I have checked all open and closed feature requests and this is not a duplicate
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
There are countless alternative apps that you can use without these limitations

**Comment by jo-chemla** [comment]
Hi, thanks for getting back so quickly. I'm a self-hoster and heavy oss advocate, but there are no alternative - that I know of - with a design as slick as alltrails, especially for multi-day bikepacking/cycling itinerary preparation, great community content recommendation/exploration, and sharing.

OrganicMapps/OsmAnd are made to explore a map or get directions for a simple trip, not the easiest tools to import tracks from a shared community repository. The 3d viewer feature is otherwise only available at the moment on fatmap, which will soon be discontinued following strava acquisition, and is important to plan safest mountain routes. Komoot has a good deal of these features and could be another alternative to create patches for.

But these remarks are propably more relevant to a dedicated reddit thread regarding the best android apps for route planning. Thanks again for the feedback!
