### ISSUE TITLE
feat(YouTube): Add short to playlist

### ISSUE THREAD

**Issue by RobinRMC** [ReVanced/revanced-patches#3587]
### Feature description

YouTube doesn't show you the option to add a short to a playlist, while this is possible when you play it in the normal player.

I think that it would be great if the button to add a video to a playlist would also show in shorts.

### Motivation

---

**`Why should this feature be implemented?`**

It allows users to add shorts to playlists.

---

**`What is the explicit use case?`**

Whenever a user wants to add a short to a playlist, it would allow them to do so.

---

**`What are the benefits?`**

It makes it possible to easily add shorts to playlists.

---

**`What makes this feature important?`**

There is currently no easy way to add shorts to playlists. A button to do this would solve this issue.

---

### Acknowledgements

- [X] I have checked all open and closed feature requests and this is not a duplicate
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
https://support.google.com/youtube/answer/57792?hl=en&co=GENIE.Platform%3DAndroid#zippy=%2Cyoutube-app

**Comment by RobinRMC** [comment]
It seems like they have indeed added the feature.
