### ISSUE TITLE
bug: Gesture volume goes up to 150 on poco f6 pro

### ISSUE THREAD

**Issue by Youngei402tw** [ReVanced/revanced-patches#3595]
### Bug description

the issue is metioned in https://github.com/revanced/revanced-patches/issues/1646, however the pushed commit to solve the issue was wrongly refered, the pushed commit is about twitter, but it refered a youtube issue

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
This is correct behavior. Your phone reports 150 steps

**Comment by Youngei402tw** [comment]
no plans on making a fix for it?
