### ISSUE TITLE
bug: Ambient Mode permanently enabled

### ISSUE THREAD

**Issue by 0xrxL** [ReVanced/revanced-patches#3596]
### Bug description

A recent A/B test on YouTube removed the ambient mode toggle, but this however left the feature permanently enabled.

### Solution

I assume that default preference value can be set to false instead always true (also on fresh installations).

### Additional context

Other stock users can reproduce this: https://www.reddit.com/r/youtube/comments/1f429ut/need_help_with_ambient_mode/

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Pretty sure a bug. Why would YouTube remove the toggle
