### ISSUE TITLE
feat(YouTube): Force static color over "ambient mode" in the player

### ISSUE THREAD

**Issue by kairusds** [ReVanced/revanced-patches#3599]
### Feature description

Add a patch to override YouTube's always on ambient mode with a static color.

### Motivation

The YouTube app used to have an ambient mode option in the additional settings section but for some reason, it's gone now and I can't disable it.

### Acknowledgements

- [X] I have checked all open and closed feature requests and this is not a duplicate
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by kairusds** [comment]
> This might be a bug with YT.
> 
> Try copying your ReVanced settings (under Misc menu), clear the ReVanced YT app data, then check if ambient mode is still on. (then import your settings again).

That's what I did before opening this feature request. The imported settings is from a patched 19.09.37 on another device, imported into my current device which has 19.16.39.

**Comment by 0xrxL** [comment]
> Check the latest unpatched app, and see if it has ambient mode forced on with no way to turn off.

In my case also stock version is affected...and it's really annoying.

**Comment by oSumAtrIX** [comment]
I am pretty sure this is just a temporal bug. The official docs still mention a toggle. If issue remains we can reconsider this request

**Comment by kairusds** [comment]
> For anyone who doesn't know, turning on battery saver also turns off ambient mode.

Considering that I use a chinese rom, that will just prevent me from getting push notifications.

**Comment by kairusds** [comment]
> I am pretty sure this is just a temporal bug. The official docs still mention a toggle. If issue remains we can reconsider this request

The issue seems to be gone on the latest vanilla YouTube version v.19.34.42 and the ambient mode option has also been removed.

**Comment by 0xrxL** [comment]
> > I am pretty sure this is just a temporal bug. The official docs still mention a toggle. If issue remains we can reconsider this request
> 
> The issue seems to be gone on the latest vanilla YouTube version v.19.34.42 and the ambient mode option has also been removed.

The issue is related to the modded version: the button is missing on both vanilla and modded but, on the modded one, the ambient mode is forcely enabled from the start (after a clean installation).

I can reproduce this behaviour also on my personal client, based on 19.35.34 version.

At this point I think this bug should be patched in some way.

**Comment by 0xrxL** [comment]
> I don't have ambient mode forced enabled, but I had it turned off before the feature was removed.
> 
> If it only shows up with the patched app for some users, but does not show up with unpatched `19.16.39`, then it must be caused by one of the patches.

In fact it's weird that ambient mode is enabled by default only on patched version.

Probably it's a matter of a flag dependent from Play Services (which are setting up differently on MicroG).

**Comment by 0xrxL** [comment]
> What about using a different account, or using incognito mode, or a clean patched install but no user accounts in MicroG?

Same thing, unfortunately.

Anyway some seconds ago the toggle re-appeared again. 🤷‍♂️
