### ISSUE TITLE
feat(patch): Sort Videos in a playlist by length

### ISSUE THREAD

**Issue by AirInAField** [ReVanced/revanced-patches#3611]
### Feature description

A choice from a drop down menu that allows you to sort your playlist by length, either by longest videos first  or shortest video first.

### Motivation

Some people my feel their experience improved by going for shorter or longer videos first depending on their situation at the time.

If I had a short period of time where I wanted to watch something I may not want to scroll through my playlist to find an appropriately lengthed video.

It should improve the user experience to add in this functionality by providing a new option for playlist optimization.

### Acknowledgements

- [X] I have checked all open and closed feature requests and this is not a duplicate
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
That is such a very specific request that I don't think it makes sense as a feature for everyone. You can sort the playlists yourself already or use external tools. Thanks anyways.
