### ISSUE TITLE
feat(Universal): Add `Implement Monet` patch for Universal

### ISSUE THREAD

**Issue by vippium** [ReVanced/revanced-patches#3612]
### Feature description

This patch will add a `Monet Icon` by understanding the icon color science. There can be 2 sub-components or sub-settings for the monet icon. 1. Applying Dark color on the main text/icon and light as background.
2.Applying Light on main text/icon and dark as background.

### Motivation

This patch will allow old apps to have monet icon support for A12 or later, whose developers are not implementing monet support for it and for those whose development is discontinued.

This will also remove the dependency on apps which forces users to buy premium for using `Monet icon` support for apps, like AppClønÉr

### Acknowledgements

- [X] I have checked all open and closed feature requests and this is not a duplicate
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
How do you make an icon follow the colors?

**Comment by vippium** [comment]
It will just use the themed color gor that:

/* Rules for sizing the icon. */
.material-icons.md-18 { font-size: 18px; }
.material-icons.md-24 { font-size: 24px; }
.material-icons.md-36 { font-size: 36px; }
.material-icons.md-48 { font-size: 48px; }

/* Rules for using icons as black on a light background. */
.material-icons.md-dark { color: rgba(0, 0, 0, 0.54); }
.material-icons.md-dark.md-inactive { color: rgba(0, 0, 0, 0.26); }

/* Rules for using icons as white on a dark background. */
.material-icons.md-light { color: rgba(255, 255, 255, 1); }
.material-icons.md-light.md-inactive { color: rgba(255, 255, 255, 0.3); }

**Comment by oSumAtrIX** [comment]
These are for web. I am talking about Android icons

**Comment by vippium** [comment]
So, there is different method for android. Mmm...Can we check out the method of AppCloner of creating monet icons.?

**Comment by oSumAtrIX** [comment]
The Android documentation should include how to support M3 icons

**Comment by vippium** [comment]
Here I got the way how to add Monet support, but it may be little complicated as it need a generation of a monochrome icon from the original one. If somehow this can be done with the help of patcher, then it may be easy.

https://medium.com/@akshaynighot73/add-themed-icon-support-for-your-android-app-d1745cf0862f

**Comment by oSumAtrIX** [comment]
Is there a programmatic way of doing this. If not, what interaction from the user is necessary. Those can be asked via patch options.

**Comment by vippium** [comment]
After little-bit checking, I haven't found it yet. But I got an app i.e. Lena Adaptive which have support of so many apps with money. So, if it can be possible to take the icon from that and apply it with the patcher. 
I know it can be done with changing the icon pack. But not every UI give support to alternate icon pack. So, just checking the icon for that app from there and add it in the patched one. 

If I found any programmatic way or any other way to do with patcher for it, I'll update it.

**Comment by oSumAtrIX** [comment]
>  So, if it can be possible to take the icon from that and apply it with the patcher.

A patch can read another apk via the patcher inside a patch just fine, but that's not really an elegant solution. What manual input is necessary if not possible programatically.

**Comment by vippium** [comment]
Closing it right now. I'll open it after a proper research and solution when I have enough time from my busy schedule.

**Comment by vippium** [comment]
What if we introduce this in this way. Like, if the app uses two image `ic_launcher_background' and `ic_launcher_foreground` to generate its app icon. Then, generating a b/w image with `ic_launcher_foreground` image. And, then passing the monochrome icon value in both `ic_launcher.xml` and `ic_launcher_round.xml` and any other required file.

OR, if the app don't generates its app icon with these two icon files and uses any static full icon image file, then having an sub-option for that. In that sub-option, user have to provide an image file with b/w with no background (i.e. transparent). Then using that file which'll add that file as `ic_launcher_monochrome`, same as `ic_launcher` and passing the value for `monochrome` in `ic_launcher.xml`.

**Comment by vippium** [comment]
I got a working way by which it is possible to get this patch workable.

There are `ic_launcher` xmls in `res/mipmap-anydpi-v26` folder, which are mainly and compulsory for icon rendering. Now from here what the patch will do is to add `monochrome` element in all the `ic_launcher` xmls (mainly `ic_launcher` and `ic_launcher_round`). It'll copy the `foreground` element values by default.

But if user want to use any specific monochrome icon, he can pick any png/webp/xml file. Patcher will copy the file in drawable folder and calls out the file path in `ic_launcher` xmls under `monochrome` element.

And for users understanding, we can simply add a description for this patch and a link to the sample monochrome image. So that user can understand what image he want to use if he wants his own monochrome icon to be displayed.
