### ISSUE TITLE
bug: Instagram ads still appear 

### ISSUE THREAD

**Issue by hk-licious707** [ReVanced/revanced-patches#3614]
### Bug description

Suggested post ans reels appear on the home feeds. Tested on Instagram 346.0.0.45.104 and  346.1.0.46.104. 
To reproduce:
1. Uninstall revanced instagram if exist
2. Download and patch Instagram with above version
3. Install it and see the suggested post and reels appear.

### Solution

Update the Hide ads patch to support instagram 346.x and upcoming version

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Try older versions. Do the patches even succeed?

**Comment by turturel** [comment]
@hk-licious707 there is a diference between **ads** and **suggested stuff**. The patch's goal is to remove ads, whereas suggested stuff can be muted (30 days at a time) using Instagram's own settings (Hamburger menu -> Suggested content -> Snooze suggested posts)

**Comment by oSumAtrIX** [comment]
This is true
