### ISSUE TITLE
bug: TikTok 32.5.3 crashes on startup

### ISSUE THREAD

**Issue by Keith94** [ReVanced/revanced-patches#3617]
### Bug description

1. Patch TikTok 32.5.3 apk. All patches installed
2. Try to launch it

Result: TikTok app keeps crashing. Happens on pixel 6 and pixel 8

### Solution

See below for partial solution

### Additional context

It's working with the following patches:

Download
Feed Filter
Fix Google login
Settings
Show Seek bar

The application loads and works fine, but opening the settings menu still crashes the app.

https://www.reddit.com/r/revancedapp/comments/1ephxzj/tiktok_3253_crashes_on_opening/

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by spilla7** [comment]
Same issue here. Pixel 7a

Patched APK worked for months. The a few days ago it went to black screen and the crashed. I've cleared storage and cache. I've also tried uninstalling and reinstalling. 

Official tiktok app works fine.

**Comment by ha2ked** [comment]
Having the same issue here's the [log](https://bin.mkr.pw/~66d8c8b8632ce757b6264dbb)

**Comment by AstraxCZ** [comment]
Same here
