### ISSUE TITLE
feat(YouTube): Hide "Play next in queue" option

### ISSUE THREAD

**Issue by bigyihsuan** [ReVanced/revanced-patches#3618]
### Feature description

I want to be able to hide the Premium-only "Play next in queue" option in the context menu that appears when you tap the triple-dot icon on a video:

<a href="https://github.com/user-attachments/assets/9746942f-45b4-47d3-9ee2-91e3583736c9"><img src="https://github.com/user-attachments/assets/9746942f-45b4-47d3-9ee2-91e3583736c9" height="698"></a>

### Motivation

I frequently use the Watch Later feature of YouTube, which means frequently opening the context menu to choose the "Save to Watch Later" option, which used to be the first/top option. However, since YouTube added their Premium-only queue, it shows the new "Play next in queue" option, which is the new first/top option. This leads to me frequently mis-clicking the queue option. Then, since I do not have Premium, the YouTube app boots me to a "you must get Premium for this feature" screen that is impossible to back out of, unless you press the back icon in the top left.

Hiding the option would help prevent the wasted time of mis-clicking the queue option, then having to back out of the "you must get Premium" screen. In addition, hiding the option would help people with a similar usage pattern to me to add videos to their Watch Layer playlist faster.

### Acknowledgements

- [X] I have checked all open and closed feature requests and this is not a duplicate
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
https://github.com/ReVanced/revanced-patches/issues/959
