### ISSUE TITLE
feat: Add Download button options

### ISSUE THREAD

**Issue by Lucky-069** [revanced/revanced-patches#362]
### Type

Functionality

### Issue

There's no current download option. One has to use external downloaders which is a lot of hassle. 

### Feature

Initia00 has already made the overlay button patch, in his repo and it's function. The settings can be turned on and off within the misc settings of revanced. It would be great if either the download patch can have newpipe, powertube and ymusic! So users can select as per their preference. Or perhaps idk if the process could be automated but manually I just had to enter the package name within the class.dex and replace the name in resources.arsc so. If the cli could give a prompt to enter package name and app name(since the manual way of doing it is similar) perhaps users can choose the apps they want the download overlay button to be linked to! Either this or you can just give the three options mentioned above since those are popular. I mentioned ymusic because newpipe doesn't offers a lot of download option and ymusic can also download yt music aswell videos which newpipe can't. So it makes sense having a ymusic option too. 

### Motivation

Because this feature can be very handy, wherein the users won't have to jump back and forth to download videos and can simply download any video or audio with one tap on download button. 

### Additional context

P.S. Apologies if the request seems bit confusing, but I think it's how i wanted it to be!

**Comment by reisxd** [comment]
This isn't the place to post suggestions, please use discussions. And also, this is a dupe (too lazy to find).

**Comment by Lucky-069** [comment]
Well this isn't particularly a discussion thing. It's a feature request obviously, because the download patch hasn't been included or merged!

**Comment by reisxd** [comment]
> Well this isn't particularly a discussion thing. It's a feature request obviously, because the download patch hasn't been included or merged!

And it's the wrong place to do. Again, please use the discussions feature in the future.

**Comment by oSumAtrIX** [comment]
![Screenshot_2022-08-20-13-06-29-62_3aea4af51f236e4932235fdada7d1643](https://user-images.githubusercontent.com/13122796/185743112-8aebda90-137e-491a-9e40-88aa04b2c82f.jpg)
