### ISSUE TITLE
Youtube Revanced not playing videos

### ISSUE THREAD

**Issue by Jan-Bober** [ReVanced/revanced-patches#3621]
### Bug description

My youtube doesn't play youtube videos, but shorts work as normal. I tried reinstalling it, repatching it and it didn't work. I also tried it without logging in. Spoof client also doesn't work. There is play/pause button byt after clicking it doesn't play 
I tried diffrent variations of installed patches and with only GMScore support it didnt work. Without it after clicking install it tries to update Youtube(which is disabled). Everything stopped working about a month ago. I also tried version patched by my friend (which works on his phone) and it also doesn't work. 

Phone: Samsung S23 
Android: 14 
Youtube: 19.16.39
Build number UP1A.231005.007.S911BXXS6CXFE

![Screenshot_20240904_084201_YouTube](https://github.com/user-attachments/assets/269acad0-0839-4a9d-a06f-4c9e9666c53f)

### Additional context

I don't know why but on Google Messages when I wan't to turn on RCS chats it says it isn't available on my device 

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
https://github.com/ReVanced/revanced-patches/issues/3215
