### ISSUE TITLE
feat: 17.41.37 version deletion request 

### ISSUE THREAD

**Issue by AsphaltKoreaWiki** [ReVanced/revanced-patches#3623]
### Motivation

The reason for the request is almost the same as 17.33.42.

### Acknowledgements

- [X] I have checked all open and closed feature requests and this is not a duplicate
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Not sure why we would delete anything when it makes no difference
