### ISSUE TITLE
feat: Add patch to allow YT (not music) on Android Auto

### ISSUE THREAD

**Issue by mniak** [ReVanced/revanced-patches#3624]
### Feature description

Allow the normal YouTube (not YT Music) to appear in the Android Auto menu.

I usually listen to some videos while driving, even if not watching, or to some songs that are not on YT music or any other platform.

### Motivation

Use case: listen to some videos while driving, even if not watching, or to some songs that are not on YT music or any other platform.

A lot of people looks for this kind of feature and try to use Carstream or Fermata Auto.

### Acknowledgements

- [X] I have checked all open and closed feature requests and this is not a duplicate
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
The certificate patch is made for that

**Comment by KobeW50** [comment]
> The certificate patch is made for that

The Bypass certificate checks patch is only for YT Music. This request is for YouTube. Forgive me if I am misunderstanding

**Comment by oSumAtrIX** [comment]
Apps not appearing is an issue on Android Autos end, a patch doesn't fix that
