### ISSUE TITLE
bug: playlists hidden by `general-ads` patch

### ISSUE THREAD

**Issue by HeroGalak** [revanced/revanced-patches#363]
### Type

Cosmetic

### Bug description

In YouTube 17.32.35 beta playlists are not visible

### Steps to reproduce

Compile with latest revaced files and open the playlist tab

### Relevant log output

```shell
#
```

### Screenshots or videos

Bug screenshot:
![Screenshot_20220819-201658_YouTube](https://user-images.githubusercontent.com/69464248/185738739-cd2307b1-dfb1-4a10-a749-fea702a9c1ca.jpg)

**Comment by oSumAtrIX** [comment]
Please disable patches until the error is gone, report back which one causes this.

**Comment by TheJeterLP** [comment]
Don't use a beta version.

**Comment by HeroGalak** [comment]
> Don't use a beta version.

There is only the beta of v17.32.35 on apkmirror

**Comment by TheJeterLP** [comment]
> > Don't use a beta version.
> 
> There is only the beta of v17.32.35 on apkmirror

My bad yes you're right. The one who used that version to bump the YouTube version made that mistake. Anyways, I'm using that version and cannot reproduce your issue

**Comment by oSumAtrIX** [comment]
Please don't forget [this](https://github.com/revanced/revanced-patches/issues/363#issuecomment-1221294808). I assume it will be the general-ads patch.

**Comment by TheJeterLP** [comment]
> Please don't forget [this](https://github.com/revanced/revanced-patches/issues/363#issuecomment-1221294808). I assume it will be the general-ads patch.

I have all patches enabled and can't reproduce. Including general ads.

**Comment by shivanshkverma** [comment]
> Please disable patches until the error is gone, report back which one causes this.

https://photos.app.goo.gl/NkyatZ7HdQ9eoYRe6

Tried it multiple times, for me it's the Remove general ads.

**Comment by HeroGalak** [comment]
I built YT 17.36.37 with manager then I tried the same apk on a Galaxy A10 (Android 11) and a Galaxy A52s 5G (Android 12).

On the A10 all the playlists were visible  while on the A52s the bug was still there.

Hope this is helpful to fix the issue.

**Comment by TheJeterLP** [comment]
> I built YT 17.36.37 with manager then I tried the same apk on a Galaxy A10 (Android 11) and a Galaxy A52s 5G (Android 12).
> 
> On the A10 all the playlists were visible  while on the A52s the bug was still there.
> 
> Hope this is helpful to fix the issue.

Revanced doesn't modify that playlist view at all

**Comment by oSumAtrIX** [comment]
General ads could be faulty and remove it via the litho componenent filter.

**Comment by TheJeterLP** [comment]
> General ads could be faulty and remove it via the litho componenent filter.

But only on one device? I'm guessing A/B

**Comment by whatevenisthat** [comment]
I've been having this problem but I noticed that disabling the "Hide suggestions" option in Ads settings makes it so my playlists are visible again.

**Comment by HeroGalak** [comment]
Tested [the apk](https://github.com/revanced/revanced-patches/issues/363#issuecomment-1251082857) on A52s with "Hide suggestions" setting disabled and playlists are visible.

_Screenshot A52s (Android 12) with "Hide suggestions" disabled:_
![image](https://user-images.githubusercontent.com/69464248/191265658-173c0b31-d1dd-4fdc-a954-3063249cf40a.png)

It seems that YouTube (after v17.29.34) shows playlists in different ways depending on the Android version. So when YTR is on Android 11 "Hide suggestions" setting doesn't affect playlists, while on Android 12 the patch wrongly detects the new playlists section and removes it.

_Screenshot A10 (Android 11) with "Hide suggestions" enabled:_
![WhatsApp Image 2022-09-20 at 15 20 48](https://user-images.githubusercontent.com/69464248/191269477-60356118-66c4-49f8-a359-a05b603ce37e.jpeg)

**Comment by TheJeterLP** [comment]
> It seems that YouTube (after v17.29.34) shows playlists in different ways depending on the Android version. So when YTR is on Android 11 "Hide suggestions" setting doesn't affect playlists, while on Android 12 the patch wrongly detects the new playlists section and removes it.

Im on the latest YouTube version and on Android 12 and it doesnt remove the section for me, thats weird. That needs to be looked further into 100%

**Comment by SpL1Ne** [comment]
If it's help, Android 9, Nokia 8. Have same issue where playlists from `add to playlist` menu are not showing if `Remove general ads` is enabled. Using recommended YT v17.36.37 from apkmirror.

**Comment by HeroGalak** [comment]
Built v17.38.35 and v17.36.37 with manager v0.0.27 and playlists are finally visible (even with hide suggestions enabled).
