### ISSUE TITLE
bug: Unable to add video to queue

### ISSUE THREAD

**Issue by ndbiaw** [ReVanced/revanced-patches#3631]
### Bug description

With new YouTube update, currently can't add videos to queue, need premium to do that

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Correct, you need premium.

**Comment by ndbiaw** [comment]
> Correct, you need premium.

afaik queue is client side, still not planned? thanks
