### ISSUE TITLE
bug: Cannot login to RIF (Reddit is fun) but can make new account and log in to that

### ISSUE THREAD

**Issue by robturner45** [ReVanced/revanced-patches#3639]
### Bug description

It's bizarre, its saying my email/uname and password are wrong, they're not. And I've tried typing them manually and that doesn't work either. I figure it has to be connected to the previous issue https://github.com/ReVanced/revanced-patches/issues/3115

It also disappears the accept cookies banner before I can click accept or deny but I don't know if that's usual behaviour. I should have backed up the reddit settings before I reinstalled my phone. I have done everything right I promise.

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by robturner45** [comment]
It also doesn't work when you try to log in with mobile. I've set it up right because I can see posts I just can't login.

**Comment by robturner45** [comment]
Issue seems to have resolved itself bizarrely.

**Comment by FunkeDope** [comment]
I just tried to use the official reddit app and am getting the exact same issue with it, so I'm going to assume they changed or broke something on their end. I'm able to sign in on Chrome on my PIxel, as well as desktop with no issues. WiFi vs LTE/5G doesn't seem to make any difference either.
I think it may have something to do with the user agent, but I'm not sure. The fact that I'm on a fully stock Pixel with Android 14 and the official app is not working is leading me to believe this is not a revanced issue. 
I'll keep messing with it. Reddit really botched this.

**Comment by robturner45** [comment]
Yeh I think it must be a case of it works when it wants to and you've just
gotta get lucky!

**Comment by FunkeDope** [comment]
Ok quick update. It randomly worked today after trying an additional 10-15 times lol. Here is what I did:

- Uninstall every reddit related app.
- On desktop, use the NEW reddit webUI to reset your password and sign out of all other devices. 
- WAIT. Like, 6+ hour or more. Then I was able to finally log into the the official Reddit app on mobile correctly.
- WAIT. I was able to log into RIF but kept getting the "You Boke Reddit" page, so still not working.
- Re-Patched the APK with the original API key I've been using for a year+ (I had made like 7 new ones in testing)
- Just keep trying. It just randomly worked on the 7th attempt to log in.

¯\_(ツ)_/¯

**Comment by oSumAtrIX** [comment]
1, 5 are definitely not needed. 3, 4 are unlikely needed.

**Comment by FunkeDope** [comment]
> 1, 5 are definitely not needed. 3, 4 are unlikely needed.

Well I don't have time to set this up and look at the logcat logs, but some contributor should see what the actual issue is, because your post on Reddit said its the user agent, which it's clearly not. It should have just worked the first time with the old api key on the new device otherwise.

**Comment by CDejoEcobee** [comment]
Looks like the issue still exists, weirdly, my old phone still allows me to log in no issue, unsure on what version of the patch it is though.

But I also had re-patched that one, so it might be something related to android itself rather than the patch

**Comment by heyitsj0n** [comment]
Any advice on this issue? Things I've tried-

Restoring app and data from swift backup (This restores a legacy acct which doesnt work)
Repatching with the latest version of Revanced Manager.
Repatching with Revancify. (option 8 isn't available on the current version, and it wouldn't accept either version of rif apk)
Making a new Developer User Auth Token ID for Reddit.
Linking my Apple Acct with my reddit account, and trying to sign in with that.
Changing my password.
Using an older version of RIF apk, which the latest version always worked for me before.
Try patching RIF golden Platinum apk.
Try create new acct from patched RIF app. (this works, and lets me log in. But then trying to add my real acct fails with same error)
linking my real acct to my phone number, and signing in through that: (Failed: Server error)
Emailing reddit support (Doubt they will help, they can probably see what I'm trying to do...)



Long Live the King! (RIF)👑

**Comment by book915** [comment]
@heyitsj0n I tried everything that you did about 5 days ago and nothing worked, so I just switched to Boost (pretty nice alternative) and tried logging in to RIF once every day until it worked today! 

So like others said just keep trying and it will probably eventually let you in.

**Comment by zhaobenny** [comment]
> Try create new acct from patched RIF app. (this works, and lets me log in. But then trying to add my real acct fails with same error)

My RIF was doing the same behaviour with signing in.

Using a VPN and trying to log in using my real account worked. (Probably some kind of ban for my IP/account combination)

**Comment by heyitsj0n** [comment]
Ok great! Looks like just waiting 3 days and drying again fixed it for me!
But thanks for the suggestion. I will try VPN next time!


Sent from my iPhone

-DJ Jon

775-772-0052

*DJsInReno.com <http://DJsInReno.com>*





* <http://DJsInReno.com>*

**Comment by book915** [comment]
> > [@heyitsj0n](https://github.com/heyitsj0n) I just switched to Boost (pretty nice alternative) and tried logging in to RIF once every day until it worked today!
> 
> Sorry what is Boost? I just started getting the same error with my alt account...

[Boost](https://boostforreddit.com/) is just another Reddit client that you can patch with ReVanced, it was pretty decent while my RIF was dead. [This page](https://github.com/KobeW50/ReVanced-Documentation/blob/main/Reddit-Client-ID-Guide.md) has a list of other alternatives, and [RedReader](https://play.google.com/store/apps/details?id=org.quantumbadger.redreader&hl=en-US) is another one I used that doesn't need any patch since they got an exception from Reddit.

**Comment by FunkeDope** [comment]
> > I was having this issue as well, it would just say "invalid login" even though I was typing my username and password right. Found a [reddit thread](https://www.reddit.com/r/revancedapp/comments/1m69k6g/revanced_patched_rif_no_longer_accepting_log_in/nckfmop/) with a bunch of people saying they used a VPN to connect from Manchester UK and that worked for me, no other changes.
> 
> I just tried this and it worked. I had tried VPN to France with no dice, but Manchester worked first try. Thanks!

Lmao, I just tried after completely giving up on this. Worked instantly with Manchester set in Proton. Wtf?? Thanks!!
