### ISSUE TITLE
feat: (Google Messages) - Some suggested and required patches for Google Messages

### ISSUE THREAD

**Issue by vippium** [ReVanced/revanced-patches#3648]
### Feature description

As Google Messages is now the default messaging app. People are use-to to it. But Google is also providing ads to it, which is annoying. Here are some patches which can be done:
1. **Remove Ads** - This patch will remove ads from the Google Messages to provide a clean experience to users. It also need to remove analytics which send data to Google servers.
2. **Restore `View Messages by category` option** - as this is very useful feature which Google removed by giving a illogical answer regarding this. They introduced filters in place of that. This feature help users to categorize their messages very easily.
3. **OneUI-styled UI** - This will enable the OneUI (Samsung exclusive feature) swipe down from home screen feature. It make GMessages to use one handedly. Here is the [module](https://github.com/assembleDebug/OneUI.GoogleMessages) which is only currently available for root users.

### Motivation

This will enhance the user-experience with the Google Messages. And also, users will able to use 'Samsung exclusive Slide down to main screen feature.

### Acknowledgements

- [X] I have checked all open and closed feature requests and this is not a duplicate
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Where are ads? Categories are server sided, i don't know how else you would distinguish them. Open request**per** feature.

**Comment by vippium** [comment]
> Where are ads?
These are RCS based Ads. When we use RCS feature, they pop-out as a Message.
![image](https://github.com/user-attachments/assets/92a9136c-8157-429a-a406-440b99343fee)

> Categories are server sided
It was. Google removed it. But GAppsMod restored it. It was only available for Root (as usual). The feature is known as Message Organization.



> Open request **per** feature.
Am I that much trained 🤔 will have to take time for that.

**Comment by KobeW50** [comment]
> Am I that much trained 🤔 If I have that much experience, then why I open a FR issue
>
>Why don't you try to open a PR. I already mentioned the feature sources.

oSumAtrix is talking about feature requests. Not PRs

**Comment by vippium** [comment]
> > Am I that much trained 🤔 If I have that much experience, then why I open a FR issue
> > Why don't you try to open a PR. I already mentioned the feature sources.
> 
> oSumAtrix is talking about feature requests. Not PRs

Ohh...I see. I'll do it soon.
