### ISSUE TITLE
feat: Comments Removal doesn't work on new (Material You?) UI.

### ISSUE THREAD

**Issue by i1itione** [revanced/revanced-patches#365]
### Type

Functionality

### Issue

The comments removal feature works very well on old UI, but I found it doesn't work on new UI currently.
I tried doing clear data of youtube app, but it seems that my account always use new UI. (server side?)

![P_20220820001](https://user-images.githubusercontent.com/21694907/185761605-6599b917-b622-4345-8a7c-073ea9c014e3.jpg)

### Feature

Add support to remove comments of new UI.

### Motivation

It works on old UI.

**Comment by oSumAtrIX** [comment]
There is no comment removal yet.

**Comment by TheJeterLP** [comment]
> There is no comment removal yet.

There is and can be activated in the settings.

**Comment by i1itione** [comment]
> > There is no comment removal yet.
> 
> There is and can be activated in the settings.

Yes, but it doesn't work on the Material You UI version of comments currently.
