### ISSUE TITLE
bug: Check environment patch fails on Android 8

### ISSUE THREAD

**Issue by oSumAtrIX** [ReVanced/revanced-patches#3654]
### Bug description

`Check environment` patch fails. See log below.

### Error logs

```shell
An error occurred:
java.lang.NoSuchFieldError: No static field ODM_SKU of type Ljava/lang/String; in class Landroid/os/Build; or its superclasses (declaration of 'android.os.Build' appears in /system/framework/framework.jar!classes2.dex)
	at app.revanced.patches.shared.misc.checks.BaseCheckEnvironmentPatch.setPatchInfo$setBuildInfo(BaseCheckEnvironmentPatch.kt:68)
	at app.revanced.patches.shared.misc.checks.BaseCheckEnvironmentPatch.setPatchInfo(BaseCheckEnvironmentPatch.kt:84)
	at app.revanced.patches.shared.misc.checks.BaseCheckEnvironmentPatch.execute(BaseCheckEnvironmentPatch.kt:44)
```

### Solution

Older versions probably don't have that field.

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by Frosty-J** [comment]
Can confirm. The installation works on some devices such as Galaxy A04s but not others such as [Fire Tablet](https://github.com/user-attachments/files/17051161/kindle.log) and [Mechen MP3 player](https://github.com/user-attachments/files/17051169/mp3.log), based on Android versions 11 and 9 respectively.

**Comment by Frosty-J** [comment]
This appears to have fixed it! It hasn't finished installing the new patches yet but it's got past that hurdle.
