### ISSUE TITLE
feat(GMessages): Patch to `Remove RCS-Based Ads`in Google Messages.

### ISSUE THREAD

**Issue by vippium** [ReVanced/revanced-patches#3661]
### Feature description

This patch will allow users to use RCS feature without having spam messages like ads in google messages. These ads can be disabled or removed by disabling RCS feature completely. But disabling RCS is very annoying. So bypassing it while having RCS enabled.

Ads examples: [Available on Old Issue](https://github.com/ReVanced/revanced-patches/issues/3648#issuecomment-2355875492)

### Motivation

This will remove the ads from the Google Messages. Helping users to have a clean experience in that. Google is continuously bombarding ads in their apps. By which users are very frustrated.

### Acknowledgements

- [X] I have checked all open and closed feature requests and this is not a duplicate
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Where is the programmatic indication that the message you screenshotted is an ad?

**Comment by vippium** [comment]
> Where is the programmatic indication that the message you screenshotted is an ad?

After switching off the RCS, it gets removed. Now, what you will call it. [TOI](https://timesofindia.indiatimes.com/gadgets-news/google-messages-filled-with-spammy-ads-here-are-four-ways-to-get-rid-of-them/amp_etphotostory/105994275.cms) also pointed this in that article.

**Comment by oSumAtrIX** [comment]
Turning off RCS turns of all RCS messages and does not help with distinguishing that an RCS message is an ad or not. Your plugin request requires scanning the content. Not feasible.

**Comment by vippium** [comment]
There must be a solution for this too...I'll look for that and will take it here.
