### ISSUE TITLE
feat: Spotify kids OR explicit content locking

### ISSUE THREAD

**Issue by Est86** [ReVanced/revanced-patches#3662]
### Feature description

Feature request: Spotify Kids, OR explicit content locking.

### Motivation

to remove explicit content for kids usage.

### Acknowledgements

- [X] I have checked all open and closed feature requests and this is not a duplicate
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by emadellaloggia** [comment]
install this
https://mega.co.nz/#!B31G2LaZ!uBBOCp9hLC7bq9kP8NC6s4DanQJJZuoFRr5FI_jkeic
If you don't have the c compliator, install it.(gcc or clang)

**Comment by oSumAtrIX** [comment]
That would require scanning the content. Not possible
