### ISSUE TITLE
bug(YouTube): Screen Orientation Issue

### ISSUE THREAD

**Issue by tz-shuhag** [ReVanced/revanced-patches#3664]
### Bug description

When Switching back from fullscreen to normal the youtube ui becomes ladscape.

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by tz-shuhag** [comment]
> Installed unpatched 19.16.39 and try to reproduce with that.  It's probably a bug in YouTube.

I have tested in unpatched youtube (v19.16.39) and the bug doesn't seem to appear in official app. Maybe it's a revanced patch related issue.

**Comment by oSumAtrIX** [comment]
Its a per video thing or rather the aspect ratio. Not a bug
