### ISSUE TITLE
feat: YouTube: Hide Search Bar Cast Button

### ISSUE THREAD

**Issue by Immortalin** [ReVanced/revanced-patches#3669]
### Feature description

There is a cast button next to the search bar which currently does not have the option to be hidden

### Motivation

There is a hide cast button feature for the player, allowing hiding in the search bar would provide parity to the other feature.

### Acknowledgements

- [X] I have checked all open and closed feature requests and this is not a duplicate
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
I don't see any cast button

**Comment by Immortalin** [comment]
It's the video camera icon
