### ISSUE TITLE
feat: Remove Shorts Live feeds from History

### ISSUE THREAD

**Issue by AVellucci** [ReVanced/revanced-patches#3675]
### Feature description

while in YT Revanced. if Shorts feature is enabled Youtube will track all history of everything you scroll past, even if you're there for less than a second. Currently youtube will consider any Live streams in shorts player as you watching the full live stream. If it's possible to play with what counts as "watched" it would be cool to be able to not have these be tracked unless you actually sit there and watch them, or for the history of them to be removed "automagically" if a setting is enabled (in case some people actually want them in their history)

### Motivation

This would clean up all users watch histories and maybe help "fix" recommendations since you won't have random videos/livestreams added to you YT history, especially since those have such a random category which could add people to categories they do not ever want to be on, all because they scrolled past it in Shorts.

### Acknowledgements

- [X] I have checked all open and closed feature requests and this is not a duplicate
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
The watch history is barely affected from live shorts. You come across one very rarely. Recommendations aren't affected and won't change just by deleting the live shorts from the history. YouTube tracks how long you watch something. That is what affects it.
