### ISSUE TITLE
bug:YouTube  long press speed up not working

### ISSUE THREAD

**Issue by KEVIN970712** [ReVanced/revanced-patches#3676]
### Bug description

After my test,you must turn on spoof video stream to use this feature.But it seems only 1x speed?

### Additional context

https://github.com/user-attachments/assets/e684e559-b12d-42a8-9ee4-968eec3c99c1

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Long press to speed up works just fine. Nit enough information provided. Follow the issue template

**Comment by KEVIN970712** [comment]
> Long press to speed up works just fine. Nit enough information provided. Follow the issue template properly

This time looks more clearly.In the first play I used 2x in the setting,and the second play I long press to speed up,but it looks different than the first time it was played.

https://github.com/user-attachments/assets/88cc5624-f8ec-4881-af93-37e9a5d61df4

**Comment by oSumAtrIX** [comment]
https://github.com/ReVanced/revanced-patches/issues/3516
