### ISSUE TITLE
feat: (Google Maps): Remove Regional Restrictions on SIM

### ISSUE THREAD

**Issue by Death777** [ReVanced/revanced-patches#3686]
### Feature description

For undisclosed reasons, Google Maps blocks access to all location photos and reviews when it detects that a user is using a Chinese SIM card. This issue has been noted by other users as well, as seen in this discussion: [Google Maps support thread](https://support.google.com/maps/thread/236949239/mobile-phones-with-chinese-sim-cards-cannot-view-map-photos-and-reviews?hl=en).
or
https://www.reddit.com/r/chinalife/comments/ok4zu4/why_does_google_maps_in_china_have_all_reviews/

It would be beneficial to introduce a patch to remove these regional restrictions and provide unrestricted access to Google Maps content for users with Chinese SIM cards.

### Motivation

This restriction is problematic because it is tied to the SIM card rather than the user's actual physical location. As a result, even when users are traveling abroad, they are unable to access essential Google Maps features, such as viewing photos or reading reviews to assess the quality of businesses and attractions. Although removing or disabling the SIM card can bypass the restriction, it is an inconvenient and temporary solution.

This restriction may around political and regional censorship, limiting access to information based solely on the SIM card's country of origin. It would be beneficial to introduce a patch to remove these restrictions, ensuring that all users can access Google Maps content regardless of their SIM card or location.

### Acknowledgements

- [X] I have checked all open and closed feature requests and this is not a duplicate
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by Death777** [comment]
> There already is a universal spoof sim patch, and it was originally created specifically for Google maps.
> 
> But you'll need to root your phone to use the patch with Google maps, since there is no MicroG patch for Google maps.

Thanks for the update, i tried to patch the google maps apk downloaded from apk pure and select only spoof SIM patch. It was success on patching but failed on install say "installation conflict". I tried delete but still the same. would you suggest how can i proceed? I'm already rooted.

![Screenshot](https://github.com/user-attachments/assets/2031885c-0835-4dda-9ead-58b2e6a18aba)

**Comment by oSumAtrIX** [comment]
> But you'll need to root your phone to use the patch with Google maps, since there is no MicroG patch for Google maps.
