### ISSUE TITLE
Hiding community posts in feed hides them everywhere in the app

### ISSUE THREAD

**Issue by Sarreos** [ReVanced/revanced-patches#3689]
### Bug description

As the title says, when you hide community posts in the feed they not only disappear from the feed but from everywhere else eg. from the community section on someone's profile.

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
These are also feeds

**Comment by logoffon** [comment]
> These are also feeds

And? Are there not any separate codes for them?
