### ISSUE TITLE
feat(grindr): Lack of transparency in the rejection of #2915 

### ISSUE THREAD

**Issue by Slenderman00** [ReVanced/revanced-patches#369]
### Application

Grindr is a dating app mainly used by the LGBTQ+ community. This is a large yet fragile group, illustrated by the fact that being queer is considered illegal inn 64 countries – with the death penalty being a reality in 11 of those.

ReVanced/revanced-patches#2915 was closed due to "I've received a warning that Grindr is banned in some countries". I find the lack of transparency in this decision disturbing.

To adress these concerns:
1. Why was this warning not posted as a comment on the request?
2. Why was no issue created around this?

Furthermore, here are some other apps that are being patched that are also banned:
- grindr: Iran, Crimea, Syria, Pakistan, Cuba, North Korea, Sudan
- instagram: China, Russia, Belarus, Iran, Uganda, North Korea, Turkmenistan
- messenger: China, Bhutan, Nepal, Pakistan, Iran, North Korea, Cuba, Syria, Turkmenistan
- youtube music: China, Iran, North Korea, Sudan, South Sudan, Tajikistan
- reddit: China, Russia, Indonesia
- spotify: China, Ethiopia, Libya, Somalia, Sudan, Iran, Iraq, Myanmar, Cuba, Venezuela
- tiktok: Afghanistan, India, Somalia
- twitch: China
- twitter: China, Iran, Myanmar, North Korea, Russia, Turkmenistan, Uzbekistan
- youtube: China, Iran, North Korea, Sudan, South Sudan, Tajikistan

### Issue

-

### Patch

-

### Motivation

-

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [ ] I have written a short but informative title.
- [ ] I filled out all of the requested information in this issue properly.

**Comment by thwwy** [comment]
This has been transferred from another repo, so I cannot find the original PR. Does anyone have it?

**Comment by oSumAtrIX** [comment]
https://github.com/ReVanced/revanced-patches-template/pulls?q=sort%3Aupdated-desc+is%3Apr+grindr
