### ISSUE TITLE
feat:(YouTube)Add an option to remove opening animation.

### ISSUE THREAD

**Issue by KEVIN970712** [ReVanced/revanced-patches#3700]
### Motivation

save my time and speed up open YouTube app speed.
![Screenshot_20240927_104811_YouTube](https://github.com/user-attachments/assets/7c4a3af3-abd3-490e-8744-67b743a616a9)

### Acknowledgements

- [X] I have checked all open and closed feature requests and this is not a duplicate
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
The speed doesn't change
