### ISSUE TITLE
feat: Google Photos Revanced Icon

### ISSUE THREAD

**Issue by lvprelvpre** [ReVanced/revanced-patches#3705]
### Feature description

Is it possible to get a Google Photos Revanced Icon option?  Similar to how the Youtube app has the option for the Revanced Icon?  Otherwise, they are both the same and next to each other.  

Thanks!

### Motivation

You guys do a great job!  Not a pressing issue, but would be a nice addition to make it easier to differentiate between the two apps.

### Acknowledgements

- [X] I have checked all open and closed feature requests and this is not a duplicate
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
https://github.com/ReVanced/revanced-patches/issues/362

**Comment by lvprelvpre** [comment]
> #362

Google Photos is a system app on some phones, so it can't be removed.  It would be nice to tell the difference between them.  

Most of the other apps are user installed apps, so you can just have the custom version installed.
