### ISSUE TITLE
bug: Patching TikTok gets stuck at "Compiling patched dex files" 

### ISSUE THREAD

**Issue by NMBlanco** [ReVanced/revanced-patches#3706]
### Bug description

When I try to patch TikTok 36.5.4 using Revanced Manager, it gets stuck at "Compiling patched dex files".
The app also crashes after showing this for about 1 minute.

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by NMBlanco** [comment]
Can we have a little insight on why this issue get's closed as "not planned"? The patching fails for other people too.

**Comment by oSumAtrIX** [comment]
Because it's a duplicate and the acknowledgement was not met.
