### ISSUE TITLE
feat: Google Camera compatbility with Google Photos Revanced

### ISSUE THREAD

**Issue by FordCorn** [ReVanced/revanced-patches#3708]
### Feature description

When on Google Camera and attempting to click the photos icon to check your photos in the bottom left, the app prompts to install Google Photos even when Google Photos Revanced is available. Google Camera app is com.google.android.GoogleCamera, and it should look for app.revanced.android.photos instead of the normal Google Photos app.

### Motivation

Being able to click the photos button from Google Camera is a useful feature, I would love a patch to make it compatible with Google Photos Revanced.

### Acknowledgements

- [X] I have checked all open and closed feature requests and this is not a duplicate
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Not possible. It hardcodes the official package. You can use the change package name patch to change it back to the original package, but you'll need to get rid of your current install of it somehow. Out of scope.
