### ISSUE TITLE
Custom Branding Patch for YouTube Music

### ISSUE THREAD

**Issue by Shane9248** [ReVanced/revanced-patches#3716]
### Feature description

A **Custom Branding Patch** for YouTube Music just like it exists for YouTube would make the both the PlayStore and Revanced app recognizable 

![Screenshot_20240929-202313](https://github.com/user-attachments/assets/bdf19aea-5e76-4785-bdf4-07f227823dc6)

![Screenshot_20240929-202214.png](https://github.com/user-attachments/assets/ac6d1ff0-9a3c-45c7-b14f-8089618cacb0)

![Screenshot_20240929-202317.png](https://github.com/user-attachments/assets/e797953e-fa68-4844-abf0-2546f9519a76)

### Motivation

It makes finding the app u are looking for easy between the two

### Acknowledgements

- [X] I have checked all open and closed feature requests and this is not a duplicate
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
#362
