### ISSUE TITLE
bug: TikTok menu icon not opening

### ISSUE THREAD

**Issue by AykhanUV** [ReVanced/revanced-patches#3718]
### Bug description

When i patch tiktok using any version in some of them the menu button won't do anything and in some it crashes the app

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Please send crashlogs using logcat. Google how to do that.

**Comment by AykhanUV** [comment]
I am sorry i realized that i was using older patches. Issue is fixed now
