### ISSUE TITLE
Codec overight and other settings not visible in 2.41.0

### ISSUE THREAD

**Issue by koko115** [revanced/revanced-patches#373]
### Type

Other

### Bug description

Codec overight and other settings not visible in 2.41.0

![Screenshot_20220822-123138](https://user-images.githubusercontent.com/24860056/185900794-caa978f6-4111-4481-ab47-8a45a94ec925.jpg)

### Steps to reproduce

In revanced settings

### Relevant log output

```shell
No log
```

**Comment by oSumAtrIX** [comment]
There is no codec override patch.
