### ISSUE TITLE
feat(WEBTOON): Ad blocker for Display Ads

### ISSUE THREAD

**Issue by 5h1b** [ReVanced/revanced-patches#3730]
### Feature description

Ad blocker for WEBTOON, removes Display Ads (e.g. Main-Mid, In-Viewer, User Profile, and Full Screen Video.)

*Images taken from https://www.webtoons.com/en/advertising/product?sub-menu=DISPLAY_ADS , ignore the desktop.
Main-Mid
![MAIN-MID](https://github.com/user-attachments/assets/1a0fd9bc-99cd-4c63-acda-d40248cff331)
In-Viewer
![IN-VIEWER](https://github.com/user-attachments/assets/7ccb7a40-23c1-4a83-aefa-0f13d574ed46)
User Profile
![USER PROFILE](https://github.com/user-attachments/assets/7035c072-2c5b-4c23-bfb8-74cee9da574c)
Full Screen Video (may break some functionality, if removed.)
![FULL SCREEN VIDEO](https://github.com/user-attachments/assets/7d27b91f-cddb-45d0-905a-e29f120e689e)

WEBTOON (com.naver.linewebtoon)

### Motivation

For people (like me) to read without alot of ads.
Blocks Display Ads from certain parts of the app.
Better reading experience/Viewer experience.
A ad free experience is best/ads makes Viewer experience bad/discomfortable.

### Acknowledgements

- [X] I have checked all open and closed feature requests and this is not a duplicate
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Theres apps for that without ads.

**Comment by 5h1b** [comment]
> Theres apps for that without ads.

Sorry to ask, but what about creators that only really publish there work on WEBTOON? How would I read those without ads?

**Comment by oSumAtrIX** [comment]
Most likely reuploaded by others on other places.

**Comment by nullnominal** [comment]
this would ideally be in revanced because going to another site is not an option.
