### ISSUE TITLE
bug: Like count not appearing at all on YouTube

### ISSUE THREAD

**Issue by Chuterix** [ReVanced/revanced-patches#3741]
### Bug description

This occurs on all videos. Disabling Return YouTube dislike does not help. In addition, view count isn't there either.

![Image](https://github.com/user-attachments/assets/8634875c-f82b-4e94-9b7c-40eabb2ced43)
![Image](https://github.com/user-attachments/assets/09a3f62f-9427-4d67-ab49-14682f8140bf)

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by YT-Advanced** [comment]
Uhm spoof app version to 18.48.39

**Comment by oSumAtrIX** [comment]
Follow and report back 

![Image](https://github.com/user-attachments/assets/82e532f7-315f-44ce-b5fb-42ea5d0671a2)

**Comment by zainarbani** [comment]
I think non patched app also affected: https://www.reddit.com/r/youtube/s/mVWypEmF6i

**Comment by oSumAtrIX** [comment]
Reopen once the requested info is provided.

**Comment by Chuterix** [comment]
Original app and repatched app works (repatched app is the Inside Edition app)

![Image](https://github.com/user-attachments/assets/80d4c24f-4ec6-460a-951c-678f5af207a5)
![Image](https://github.com/user-attachments/assets/aad05357-d1c4-4613-a2e3-59e447977edb)
![Image](https://github.com/user-attachments/assets/0d4404a6-68a2-42fc-9571-7628f15d0f7e)
![Image](https://github.com/user-attachments/assets/5e55cd0c-7a65-4b5c-94c1-59f39e380887)

**Comment by oSumAtrIX** [comment]
Are you using the same version as the patched app? If so, proceed with step 2 from my previous comment.
