### ISSUE TITLE
bug: Keyboard freezes when trying to comment 😭

### ISSUE THREAD

**Issue by ghpk** [ReVanced/revanced-patches#3746]
### Bug description

Hi,
Off late I am facing an issue in
https://github.com/j-hc/revanced-magisk-module/releases/download/20220965/youtube-revanced-magisk-v19.16.39-all.zip

Whenever I try to post a comment on a video,
My keyboard would freeze for few minutes as soon as I type the first alphabet.

This happens on multiple keyboards I've already tried.
Be it Gboard, SwiftKey, xproree or some name like this.

Few months back this was not an issue, but it's now happening everytime I try to comment.

I either need to open phone settings and force stop the keyboard app or wait a few minutes to make the stuck keyboard go away from screen.

My device is certainly an old one but I have never faced this on any of 100+ Apps I have on the same phone.

Using OnePlus 5T, 6GB/64GB
Stock Android 10
Rooted
Magisk
8+ GB free space
Cache cleaned almost every day using a root capable App.

Hope you can test and fix the issue please.

Many Thanks in advance 👍🏼

### Solution

Unable to find a fix on my own.

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by ghpk** [comment]
Can you please share what's unofficial tools in the App you have published so many updates too.

Please forgive me for having partial knowledge 🙏🏼

**Comment by oSumAtrIX** [comment]
Either ReVanced Manager or ReVanced CLI is official. For support, move to one of our links at https://revanced.app.

**Comment by ghpk** [comment]
Ok sure 👍🏼,
Thanks for your time and efforts 🙏🏼

**Comment by ghpk** [comment]
Thanks, I'll check it out.
