### ISSUE TITLE
bug: likes and dislikes doesn't appear (bug)

### ISSUE THREAD

**Issue by Emill777YT** [ReVanced/revanced-patches#3747]
### Bug description

Hi everyone, I have and issue with YouTube ReVanced app (version 19.16.39). When I installed the app all was perfect, only that the YouTube shorts button below between "home" and "subscription" button was not there but it was not a problem for me I could use the app normally without that and then I turned off the "spoof version" button and the YouTube likes and dislikes disappeared I only could see the like and dislikes image without numbers and that, after I was to YouTube ReVanced telegram group and I sent it was happening to me and a person called "muku" helped to me and he said that I had to turn on the spoof version option and then when I did it the numbers appears again but I was next to 4 or 5 days using YouTube ReVanced with that (I didn't want to use the YouTube normal app because I don't wanted to see ads and for the "return dislike API"), I want y'all solve it please because if muku had not said that to me I was with that annoying bug right now.

### Solution

You have to gonna: settings --> ReVanced option (generally it appears on the top, I mean the first option generally is for ReVanced) --> general layout --> scroll to down and then --> click on the "spoof app version" button and turn it on, it automatically/default will be on "17.33.42" version (you have to restart the app after generally it will appear a dialog box saying to you that you have to restart the app so you have to click on "restart" and it will restart for you) it is an older version of youtube and it's rare for me, so then I click on the last option "spoof app version target" and I select the "18.33.40" version that say "Restore RYD (Return YouTube Dislike) API on shorts incognito mode" and then it will be solved for you and you will see the numbers in likes and dislikes (for clickbait and fake videos that are a They are a waste of our time, YouTube should to bring that option again it's annoying have to see those videos that waste our time we have to thank to YouTube ReVanced and Return YouTube Dislike api that helps to we to don't waste our time anymore with ads and fake/clickbait/useless videos, so you only have to see the dislikes and you will realize that that video is a sh1t and you will close that video and will be easier search another video that be a good video 😀.

Greetings from Dominican in the USA person (I already have 1 year here). Good morning/afternoon/evening/night/early morning however your country/state is 👋❤️ I hope it help to you all ;).

### Additional context

Before: ![Image](https://github.com/user-attachments/assets/e78b528c-68f3-4deb-aa80-66e1457e0c0c)

After: ![Image](https://github.com/user-attachments/assets/7ea706e0-d304-44c5-8c38-5d2333aecb64)

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Follow this and report back:

![Image](https://github.com/user-attachments/assets/5b40c260-fc9e-4f84-a7d3-75937d192319)

**Comment by furquim87** [comment]
> Follow this and report back:
> 
> ![Image](https://github.com/user-attachments/assets/5b40c260-fc9e-4f84-a7d3-75937d192319)

I'm facing the same issue, and decided to check if it happens on the stock YouTube app. Here are a few observations:

1. Not only the dislikes are gone, but so are the Views and Upload date that appear when opening the detailed description.

2. While it happens in both ReVanced and the stock YouTube app in 19.16.39, clearing the app data for YouTube will temporarily restore the dislikes, but upon closing and opening the app again, the dislikes will disappear again. I believe this has something to do with the fact that upon first launching the app after clearing it's data, the app will revert to it's older layout.

3. Upon updating the YouTube app to it's latest version (19.39.37), this doesn't happen again.

**Comment by oSumAtrIX** [comment]
So its an issue with old yt versions. This has to be reported to YouTube as they support that version.

**Comment by furquim87** [comment]
> So its an issue with old yt versions. This has to be reported to YouTube as they support that version.

Most likely, although after testing the latest version, downgrading to 19.16.39, and patching the app again with the patch "Spoof App Version" enabled, the dislikes, date and views are there again, but I can't find the Spoof App Version option in General Layout > Spoof App Version.
