### ISSUE TITLE
Duolingo's patch doesn't work

### ISSUE THREAD

**Issue by DarkSkull91** [ReVanced/revanced-patches#375]
### Type

Error at runtime

### Bug description

I installed the latest version of Duolingo (5.118.2) and as soon as I start the app, it crashes. I use both the root and not-root installation because my OnePlus 9 Pro is rooted but the result is always the same.

### Steps to reproduce

1. Download Duolingo
2. Apply the patch from ReVanced
3. Start the application

### Relevant log output

```shell
I have any output with the command above launched in termux
```

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [x] I filled out all of the requested information in this issue properly.

**Comment by yokonzo** [comment]
Still having this problem as of July 17th 2024 can anyone confirm it's still not working
