### ISSUE TITLE
feat(YouTube): Opus codec can be enabled with iOS

### ISSUE THREAD

**Issue by 0xrxL** [ReVanced/revanced-patches#3756]
### Bug description

I recently upgraded device info of streaming spoofing patch on my personal client (base version 19.41 with only iOS option), from iPhone 15 Max to 16 Max with iOS 18, and now I noticed that Opus codec is unlocked:

![Image](https://github.com/user-attachments/assets/834e49c9-fe1f-4fec-a40d-9d49fe149883)

So I guess that this [issue](https://github.com/ReVanced/revanced-patches/issues/3663) can be unlisted from side effects.

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
This is an A/B test by YouTube.

**Comment by 0xrxL** [comment]
> This is an A/B test by YouTube.

So it's not related to iPhone 16 spoofing?

**Comment by oSumAtrIX** [comment]
I don't know, all I know is that they are currently A/B testing it

**Comment by 0xrxL** [comment]
> I don't know, all I know is that they are currently A/B testing it

Weird anyway, because I'm currently use a totally new account (due to the litho obfuscation on my main account) created 2 days ago. 🤷‍♂️

**Comment by oSumAtrIX** [comment]
A/B tests aren't just enabled for old accounts

**Comment by 0xrxL** [comment]
> A/B tests aren't just enabled for old accounts

This could means a more wide range of accounts with enabled feature.

**Comment by oSumAtrIX** [comment]
Well, eventually it'll be rolled out for everyone

**Comment by 0xrxL** [comment]
Someone has received this at the end?

**Comment by oSumAtrIX** [comment]
The client could replace the current ios client as it does not come with any drawbacks and possibly OPUS
