### ISSUE TITLE
bug: <show/hide switch not working>

### ISSUE THREAD

**Issue by Blu3NTV** [revanced/revanced-patches#376]
### Type

Error at runtime

### Bug description

Some show/hide switches dont work on version 17.32.39 like the shorts and autoplay buttons

### Steps to reproduce

Trying to switch on/off shorts/autoplay button will keep them activated no matter what option is selected

### Relevant log output

```shell
N/A
```

### Solution

N/A

### Additional context

N/A

**Comment by oSumAtrIX** [comment]
Irreproducible on the latest supported version.
