### ISSUE TITLE
feat: Remove enhanced bitrate quality

### ISSUE THREAD

**Issue by 0xrxL** [ReVanced/revanced-patches#3760]
### Feature description

Despite spoofing stream patch is enabled by default on iOS, this feature is still available on some video, like [this](https://youtu.be/G3OO3_oCfyg?feature=shared).

![Image](https://github.com/user-attachments/assets/f3bef601-b626-4f0c-a991-fbfd9844f33c)

### Motivation

As unavailable feature for free users, and due to the fact that could annoy users, because take more space and make quality panel more higher, should be a good idea to remove it.

### Acknowledgements

- [x] I have checked all open and closed feature requests and this is not a duplicate
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
The added space does not obstruct the user or at least not long enough for the motivation to be reasonable.

**Comment by vippium** [comment]
It was there for most of the users.

**Comment by oSumAtrIX** [comment]
Might as well add this side effect to the settings description

**Comment by npninjayt1** [comment]
It is not showing even after turning off.![Image](https://github.com/user-attachments/assets/77d1a7cf-1cd5-4d38-b902-2547e619b140)
![Image](https://github.com/user-attachments/assets/d4a1e50e-d6ec-47ee-a0f7-384a9d448858)
![Image](https://github.com/user-attachments/assets/b2fa7f93-18d0-4a00-a3c4-fe0c7cc64e5b)

**Comment by oSumAtrIX** [comment]
Follow this:

![Image](https://github.com/user-attachments/assets/8fea9688-3bee-4dca-843d-1eed4a8c0985)

**Comment by npninjayt1** [comment]
> Follow this:
> 
> ![Image](https://github.com/user-attachments/assets/8fea9688-3bee-4dca-843d-1eed4a8c0985)

Sorry brother, it is just hidden, not removed.![Image](https://github.com/user-attachments/assets/3da5e7ae-d85b-48e8-8d8f-14072e47ab0c)

**Comment by oSumAtrIX** [comment]
Unofficial patches are not supported here.
