### ISSUE TITLE
feat(YouTube): Hide automatic search highlights/links

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [ReVanced/revanced-patches#3764]
### Feature description

Removes the automatic search keyword detection (blue words) and the ability to tap on it. 

![Image](https://github.com/user-attachments/assets/37d0c609-2c79-41c4-97e1-abdc20665af5)

### Motivation

1. The highlight is arbitrary, some noun changes and others don't w/o obvious reasons. 
2. The term isnt always accurate. It may break the sentence in unexpected ways similar to a random punctuation inserted incorrectly
3. It adds unnecessary lengths to the sentence with the 🔍 icon. This may break carefully formatted text. For example, people deliberately put spoilers at line 4 to make it appear only when you tap "read all", and the phrase "spoiler alert" at line 3. but this "feature" might break the spoiler alert by shifting it to line 4 and you now have an unexpected spoiler.
4. It might interfere with the "double-tap to like comment" behavior

There are also posts on reddit on this issue:
- https://www.reddit.com/r/revancedapp/s/crTMgp4aud

### Acknowledgements

- [x] I have checked all open and closed feature requests and this is not a duplicate
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Not sure what this issue is supposed to be, I already argued with you on Discord about the exact same points.

The highlight is not arbitrary. I don't know what you mean by noun changing. The sentence is unchanged. The length is hardly an issue. It sums up to the length of a word, and not a book. Such formatting is unintended at best. YouTube does not have a spoiler feature. I'd like to see how it "breaks" according to you.  You can double tap everywhere else on the comment, it hardly prevents you from doing so

**Comment by oSumAtrIX** [comment]
It is likely parsed to some model where you'd probably have to null some field that has that metadata. Hiding comments just for that would be arbitrary.

**Comment by KobeW50** [comment]
> But it likely will be very difficult to show the comment and only removing the search links and search icons.

inotia00 is working on a patch to remove the highlighted link while keeping the comment. He explains his implementation in this GitHub issue: https://github.com/inotia00/ReVanced_Extended/issues/2435

**Comment by kasperbjerby** [comment]
> Not sure what this issue is supposed to be, I already argued with you on Discord about the exact same points.
> 
> The highlight is not arbitrary. I don't know what you mean by noun changing. The sentence is unchanged. The length is hardly an issue. It sums up to the length of a word, and not a book. Such formatting is unintended at best. YouTube does not have a spoiler feature. I'd like to see how it "breaks" according to you.  You can double tap everywhere else on the comment, it hardly prevents you from doing so.
> 
> The feature seems useful to look up keywords. If you got a good reason besides the ones we already talked about or if you got a good follow up, I'll reopen

What a useless respons.. We are many that just find it annoying, we dont have to convince you it's a bad feature and all we want is a option to turn it off, who made you the gatekeeper of feature request that are and are not allowed?
