### ISSUE TITLE
feat (YT) : Ability to hide `Recommended Playlists` shown at the bottom of playlists.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [ReVanced/revanced-patches#3765]
### Feature description

When you open a playlist from search results, then scroll all the way down, there is a `Recommended Playlists` section.

This feature request is to add the ability to hide it.

Playlist link: https://youtube.com/playlist?list=PL-_HauNKjNPu2dxYiqJaJBwSu0jheV6hv

![Image](https://github.com/user-attachments/assets/0659cefa-888a-47e2-9193-350697c477fc)

### Motivation

They are just some random playlists recommended by YouTube. I'm seeing them very often & realized they are of no use to me.

So, ability to hide them would be appreciated.

### Acknowledgements

- [x] I have checked all open and closed feature requests and this is not a duplicate
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
They are at the bottom and don't obstruct the playlist. You can follow this:

![Image](https://github.com/user-attachments/assets/c67d5e21-61a1-42cb-984c-889f3bebccf5)

If it is easily hideable, sure, otherwise not worth the effort.

**Comment by Aryan-Chauhan** [comment]
Using horizontal_tile_shelf as custom filter is hiding it, but I'm not sure what else this custom filter hides.

**Comment by oSumAtrIX** [comment]
Check for unique strings in the buffer as well as a unique path builder string
