### ISSUE TITLE
bug: (YouTube)Too many Binders sent to SYSTEM

### ISSUE THREAD

**Issue by MarGar12** [ReVanced/revanced-patches#3768]
### Bug description

YouTube Revanced just closes (no crash dialog) randomly every few minutes from the latest upcoming release patches

Patch list I used is the default

### Error logs

1728785291.762  1000  2078  2359 I ActivityManager: Killing 15635:app.revanced.android.youtube/u0a605 (adj 0): Too many Binders sent to SYSTEM
1728785291.776 10496  2859  2964 V WindowManagerShell: Transition requested (#663): android.os.BinderProxy@e397912 TransitionRequestInfo { type = CLOSE, triggerTask = TaskInfo{userId=0 taskId=793 displayId=0 isRunning=true baseIntent=Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=app.revanced.android.youtube/com.google.android.youtube.app.honeycomb.Shell$HomeActivity } baseActivity=ComponentInfo{app.revanced.android.youtube/com.google.android.apps.youtube.app.watchwhile.MainActivity} topActivity=ComponentInfo{app.revanced.android.youtube/com.google.android.apps.youtube.app.watchwhile.MainActivity} origActivity=ComponentInfo{app.revanced.android.youtube/com.google.android.youtube.app.honeycomb.Shell$HomeActivity} realActivity=ComponentInfo{app.revanced.android.youtube/com.google.android.apps.youtube.app.application.Shell_HomeActivity} numActivities=1 lastActiveTime=72865272 supportsMultiWindow=true resizeMode=1 isResizeable=true minWidth=-1 minHeight=-1 defaultMinSize=220 token=WCT{android.window.IWindowContainerToken$Stub$Proxy@74838e3} topActivityType=1 pictureInPictureParams=PictureInPictureParams( aspectRatio=9/16 expandedAspectRatio=null sourceRectHint=Rect(0, 256 - 1220, 2424) hasSetActions=true hasSetCloseAction=false isAutoPipEnabled=false isSeamlessResizeEnabled=true title=null subtitle=null isLaunchIntoPip=false) shouldDockBigOverlays=false launchIntoPipHostTaskId=-1 lastParentTaskIdBeforePip=-1 displayCutoutSafeInsets=null topActivityInfo=ActivityInfo{da792e0 com.google.android.apps.youtube.app.watchwhile.InternalMainActivity} launchCookies=[android.os.BinderProxy@95b1297] positionInParent=Point(0, 0) parentTaskId=-1 isFocused=true isVisible=true isVisibleRequested=true isSleeping=false locusId=null displayAreaFeatureId=1 isTopActivityTransparent=false appCompatTaskInfo=AppCompatTaskInfo { topActivityInSizeCompat=false topActivityEligibleForLetterboxEducation= false isLetterboxDoubleTapEnabled= false topActivityEligibleForUserAspectRatioButton= false topActivityBoundsLetterboxed= false isFromLetterboxDoubleTap= false topActivityLetterboxVerticalPosition= -1 topActivityLetterboxHorizontalPosition= -1 topActivityLetterboxWidth=1220 topActivityLetterboxHeight=2712 isUserFullscreenOverrideEnabled=false isSystemFullscreenOverrideEnabled=false cameraCompatControlState=hidden}}, pipTask = null, remoteTransition = null, displayChange = null, flags = 0, debugId = 663 }
1728785291.773  1000  2078  2359 W ActivityTaskManager: Force removing ActivityRecord{e0dde u0 app.revanced.android.youtube/com.google.android.apps.youtube.app.watchwhile.InternalMainActivity t793}: app died, no saved state
1728785291.846  1000  2078  2278 V WindowManager: Sent Transition (#663) createdAt=10-13 10:08:11.774 via request=TransitionRequestInfo { type = CLOSE, triggerTask = TaskInfo{userId=0 taskId=793 displayId=0 isRunning=true baseIntent=Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=app.revanced.android.youtube/com.google.android.youtube.app.honeycomb.Shell$HomeActivity } baseActivity=ComponentInfo{app.revanced.android.youtube/com.google.android.apps.youtube.app.watchwhile.MainActivity} topActivity=ComponentInfo{app.revanced.android.youtube/com.google.android.apps.youtube.app.watchwhile.MainActivity} origActivity=ComponentInfo{app.revanced.android.youtube/com.google.android.youtube.app.honeycomb.Shell$HomeActivity} realActivity=ComponentInfo{app.revanced.android.youtube/com.google.android.apps.youtube.app.application.Shell_HomeActivity} numActivities=1 lastActiveTime=72865272 supportsMultiWindow=true resizeMode=1 isResizeable=true minWidth=-1 minHeight=-1 defaultMinSize=220 token=WCT{RemoteToken{8ebe604 Task{51bb7e6 #793 type=standard A=10605:app.revanced.android.youtube}}} topActivityType=1 pictureInPictureParams=PictureInPictureParams( aspectRatio=9/16 expandedAspectRatio=null sourceRectHint=Rect(0, 256 - 1220, 2424) hasSetActions=true hasSetCloseAction=false isAutoPipEnabled=false isSeamlessResizeEnabled=true title=null subtitle=null isLaunchIntoPip=false) shouldDockBigOverlays=false launchIntoPipHostTaskId=-1 lastParentTaskIdBeforePip=-1 displayCutoutSafeInsets=null topActivityInfo=ActivityInfo{888fdd5 com.google.android.apps.youtube.app.watchwhile.InternalMainActivity} launchCookies=[android.os.BinderProxy@53120e7] positionInParent=Point(0, 0) parentTaskId=-1 isFocused=true isVisible=true isVisibleRequested=true isSleeping=false locusId=null displayAreaFeatureId=1 isTopActivityTransparent=false appCompatTaskInfo=AppCompatTaskInfo { topActivityInSizeCompat=false topActivityEligibleForLetterboxEducation= false isLetterboxDoubleTapEnabled= false topActivityEligibleForUserAspectRatioButton= false topActivityBoundsLetterboxed= false isFromLetterboxDoubleTap= false topActivityLetterboxVerticalPosition= -1 topActivityLetterboxHorizontalPosition= -1 topActivityLetterboxWidth=1220 topActivityLetterboxHeight=2712 isUserFullscreenOverrideEnabled=false isSystemFullscreenOverrideEnabled=false cameraCompatControlState=hidden}}, pipTask = null, remoteTransition = null, displayChange = null, flags = 0, debugId = 663 }
1728785291.846  1000  2078  2278 V WindowManager:         {WCT{RemoteToken{8ebe604 Task{51bb7e6 #793 type=standard A=10605:app.revanced.android.youtube}}} m=CLOSE f=NONE leash=Surface(name=Task=793)/@0x2b7e696 sb=Rect(0, 0 - 1220, 2712) eb=Rect(0, 0 - 1220, 2712) d=0},
1728785291.858  1000  2078  3837 I MediaSessionStack: removeSession | record: app.revanced.android.youtube/YouTube playerlib/27 (userId=0)
1728785291.858  1000  2078  3745 I ImeTracker: app.revanced.android.youtube:8f16e1a3: onRequestHide at ORIGIN_SERVER reason HIDE_REMOVE_CLIENT fromUser false
1728785291.858  1000  2078  3745 I ImeTracker: app.revanced.android.youtube:8f16e1a3: onCancelled at PHASE_SERVER_SHOULD_HIDE
1728785291.858  1000  2078  2759 D ConnectivityService: releasing NetworkRequest [ REQUEST id=4240, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10605 RequestorUid: 10605 RequestorPkg: app.revanced.android.youtube UnderlyingNetworks: Null] ] (release request)
1728785291.858  1000  2078  3837 D MediaSessionService: destroySessionLocked: record=app.revanced.android.youtube/YouTube playerlib/27 (userId=0)
1728785291.858  1000  2078  2759 D ConnectivityService: releasing NetworkRequest [ REQUEST id=4242, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10605 RequestorUid: 10605 RequestorPkg: app.revanced.android.youtube UnderlyingNetworks: Null] ] (release request)
1728785291.859  1000  2078  2759 D ConnectivityService: releasing NetworkRequest [ REQUEST id=4251, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10605 RequestorUid: 10605 RequestorPkg: app.revanced.android.youtube UnderlyingNetworks: Null] ] (release request)
1728785291.859  1002  2979  2979 I MediaPlayerList: onMediaKeyEventSessionChanged: packageName=app.revanced.android.youtube
1728785291.859  1000  2078  2759 D ConnectivityService: releasing NetworkRequest [ REQUEST id=4249, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10605 RequestorUid: 10605 RequestorPkg: app.revanced.android.youtube UnderlyingNetworks: Null] ] (release request)
1728785291.859  1002  2979  2979 W MediaPlayerList: app.revanced.android.youtube is already the active player
1728785291.859  1000  2078  2759 D ConnectivityService: releasing NetworkRequest [ REQUEST id=4244, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10605 RequestorUid: 10605 RequestorPkg: app.revanced.android.youtube UnderlyingNetworks: Null] ] (release request)
1728785291.861  1000  2078  2226 I WindowManager: WIN DEATH: Window{ac5d6f7 u0 app.revanced.android.youtube/com.google.android.apps.youtube.app.watchwhile.InternalMainActivity}
1728785291.860  1000  2078  3763 V ActivityManager: Got obituary of 15635:app.revanced.android.youtube
1728785291.862  1002  2979  2979 W AudioMediaPlayerWrapper: The session was destroyed app.revanced.android.youtube
1728785291.862  1000  2078  2226 W InputManager-JNI: Input channel object 'ac5d6f7 app.revanced.android.youtube/com.google.android.apps.youtube.app.watchwhile.InternalMainActivity (client)' was disposed without first being removed with the input manager!
1728785291.863  1000  2078  2226 V WindowManager: Loading animations: layout params pkg=app.revanced.android.youtube resId=0x1030308
1728785291.907  1000  2078  2284 W WindowManager: Failed to deliver inset control state change to w=Window{ac5d6f7 u0 app.revanced.android.youtube/com.google.android.apps.youtube.app.watchwhile.InternalMainActivity EXITING}
1728785292.625  1000  2078  3837 W WindowManager: Exception thrown during dispatchAppVisibility Window{ac5d6f7 u0 app.revanced.android.youtube/com.google.android.apps.youtube.app.watchwhile.InternalMainActivity EXITING}
1728785297.729 10425  5224  5224 D HotseatPredictionController: } targetComponent=ComponentInfo{app.revanced.android.youtube/com.google.android.youtube.app.honeycomb.Shell$HomeActivity} screen=-1 cell(-1,-1) span(1,1) minSpan(1,1) rank=0 user=UserHandle{0} title=YouTube), WorkspaceItemInfo(id=-1 type=APP container=# com.android.launcher3.logger.LauncherAtom$ContainerInfo@19f79dd

### Additional context

It closes once every 5-30 minutes when using YT Revanced normally, this never happens on the stable patches

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Uncheck patches using binary search and isolate the patch that causes it. Start with only the GmsCore support and spoof video stream patch.

**Comment by oSumAtrIX** [comment]
Please provide the requested info in my initial comment

**Comment by MarGar12** [comment]
What do I do from your initial comment? I uncheck all the patches and then what next?

**Comment by oSumAtrIX** [comment]
Here's more instructions:

![Image](https://github.com/user-attachments/assets/ce07ddf3-56d5-44d2-a359-3d0069746c71)

The link in the screenshot: https://en.wikipedia.org/wiki/Binary_search_algorithm

**Comment by MarGar12** [comment]
Alright thank you! I'll try to provide information tomorrow since ill be heading to sleep now

**Comment by oSumAtrIX** [comment]
Could be because the GmsCore support patch isn't renaming: https://github.com/ReVanced/GmsCore/blob/9d3ef3f11f30223a2e09e2f5800c61aad05b7222/play-services-cast/core/src/main/AndroidManifest.xml#L18

**Comment by oSumAtrIX** [comment]
That exception is either unrelated or should now be fixed. The patches are updated. Try patching again.

**Comment by MarGar12** [comment]
Issue Fixed! Thanks!! :3

**Comment by oSumAtrIX** [comment]
I am still reproducing log spam, this time another:

```
10-16 04:02:20.245 23110 23110 E YT.MDX.CastSdkClient: Caused by: ovl: No acceptable module com.google.android.gms.cast.framework.dynamite found. Local version is 0 and remote version is 0.
10-16 04:02:20.245 23110 23110 E YT.MDX.CastSdkClient:  at ovp.e(PG:785)
10-16 04:02:20.245 23110 23110 E YT.MDX.CastSdkClient:  at oim.a(PG:5)
10-16 04:02:20.245 23110 23110 E YT.MDX.CastSdkClient:  ... 11 more
10-16 04:02:20.245 23110 23140 W GmsClient: IGmsServiceBroker.getService failed
10-16 04:02:20.245 23110 23140 W GmsClient: java.lang.IllegalArgumentException: Service not supported: 161
10-16 04:02:20.245 23110 23140 W GmsClient:     at android.os.Parcel.createExceptionOrNull(Parcel.java:3015)
10-16 04:02:20.245 23110 23140 W GmsClient:     at android.os.Parcel.createException(Parcel.java:2995)
10-16 04:02:20.245 23110 23140 W GmsClient:     at android.os.Parcel.readException(Parcel.java:2978)
10-16 04:02:20.245 23110 23140 W GmsClient:     at android.os.Parcel.readException(Parcel.java:2920)
10-16 04:02:20.245 23110 23140 W GmsClient:     at osd.B(PG:221)
10-16 04:02:20.245 23110 23140 W GmsClient:     at com.google.android.apps.youtube.embeddedplayer.service.ui.player.remoteloaded.a.run(PG:230)
10-16 04:02:20.245 23110 23140 W GmsClient:     at android.os.Handler.handleCallback(Handler.java:942)
10-16 04:02:20.245 23110 23140 W GmsClient:     at android.os.Handler.dispatchMessage(Handler.java:99)
10-16 04:02:20.245 23110 23140 W GmsClient:     at android.os.Looper.loopOnce(Looper.java:201)
10-16 04:02:20.245 23110 23140 W GmsClient:     at android.os.Looper.loop(Looper.java:288)
10-16 04:02:20.245 23110 23140 W GmsClient:     at android.os.HandlerThread.run(HandlerThread.java:67)
10-16 04:02:20.245 23110 23110 W YT.MDX.acbk: CastAppId for type 0 not found. Defaulting to mainCastAppId.
10-16 04:02:20.245 19045 20932 D GmsServiceBroker: Service not supported: GetServiceRequest[UNKNOWN(161), packageName="app.revanced.android.youtube", gmsVersion=241702000, scopes=[], extras=Bundle[EMPTY_PARCEL], defaultFeatures=[], apiFeatures=[Feature[client_side_logging,1], Feature[cxless_client_minimal,1], Feature[cxless_caf_control,1], Feature[module_flag_control,1], Feature[discovery_hint_supply,1], Feature[relay_casting_set_active_account,1], Feature[analytics_proto_enum_translation,1], Feature[integer_to_integer_map,1], Feature[relay_casting_set_remote_casting_mode,1], Feature[get_relay_access_token,1], Feature[get_cast_settings,1], Feature[set_bundle_setting,1], Feature[get_client_updated_info,1]], supportsConnectionInfo=true]
10-16 04:02:20.245 23110 23140 W GmsClient: IGmsServiceBroker.getService failed
1
```

wondering if this has some relation with claims from users regarding battery usage.

**Comment by oSumAtrIX** [comment]
You can check if you reproduce it, too, as well as on the latest normal patches release.

**Comment by oSumAtrIX** [comment]
No. Are they being spammed in the logs or appear in the regular patches

**Comment by MarGar12** [comment]
> You can check if you reproduce it, too, as well as on the latest normal patches release.

I get these errors too on my end on dev patches, haven't tested normal patches yet though and it doesn't really seem to spam logs :p

**Comment by oSumAtrIX** [comment]
Should be unrelated then

**Comment by oSumAtrIX** [comment]
Quite surely placebo

**Comment by oSumAtrIX** [comment]
How about using the new rvp patches

**Comment by oSumAtrIX** [comment]
I am not sure, but this may be related and somewhat concerning? haha
![Image](https://github.com/user-attachments/assets/cfed3737-74c7-4d81-8b6b-45c08d832c4a)

**Comment by oSumAtrIX** [comment]
Can you reproduce the log on main patches.

**Comment by oSumAtrIX** [comment]
Can you send a 5s log of the spam

**Comment by oSumAtrIX** [comment]
Please continue testing, it may be sporadic.

**Comment by midnightvibez** [comment]
Sorry I am not tech savvy, may I know which patch of youtube should I download to fix this high battery and ram use issue.

**Comment by midnightvibez** [comment]
> Use the latest patches. There was an issue where the litho patch didn't override a value correctly and could cause high memory usage. That was fixed in a patch release from a month or two ago.

I am using still youtube is using 80% battery. Idk why this is happening to majority of people. Hope it gets resolved soon.
