### ISSUE TITLE
bug: (Instagram) "Open supported links" functionality broken by patch

### ISSUE THREAD

**Issue by Vandino86** [ReVanced/revanced-patches#3776]
### Bug description

When Instagram is installed normally via Google Play, "App info" --> Defaults --> "Set as default" --> enabling "Open supported links" will grant me access to the "Supported web addresses" menu (also in the "Set as default" menu) which looks like this (the last 4 entries were disabled by default):

 ![Image](https://github.com/user-attachments/assets/8fd61c09-d6af-44f4-947e-0351cdfafeea)

I downloaded an APK of Instagram and was able to patch it with the "Hide ads" patch (currently the only available patch for IG) and install it without error. However, the same "Supported web addresses" menu looks like this with "Open supported links" enabled:

![Image](https://github.com/user-attachments/assets/2f2d9066-0c32-487c-8364-fe5ba06cdefb)

^All of these entries were disabled by default. However, "www.instagram.com" always disables itself. Every time I enable it, back out of the "Supported web addresses" menu, and then go back into it, it's disabled again. None of the other entries have this issue: when I enable them, they stay enabled. Same with the 4 entries in the same menu when using the version of Instagram straight from Google Play. As a result, I can't open "www.instagram.com" links using ReVanced Instagram; they just open up in my default browser (Cromite) instead.

For a workaround attempt, I copied and pasted a "www.instagram.com" link into Samsung Notes and got rid of the "www." portion so that it'll open in ReVanced Instagram instead of Cromite (ex. https://www.instagram.com/p/C1u8aRpy4t7/ --> https://instagram.com/p/C1u8aRpy4t7/), but tapping on the "instagram.com" link simply opens ReVanced Instagram without actually going to the post that the link is meant to go to.

I've patched and installed versions 352.1.0.41.100 & 353.0.0.46.90 (both arm64-v8a, 360-480 dpi) and they both have the same issue.

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Install the unpatched app and see if it makes a difference.

**Comment by Vandino86** [comment]
> Install the unpatched app and see if it makes a difference.

Do you mean installing the unpatched APK instead of installing straight from Google Play? I tried that for a bit and the "Supported web addresses" menu looked the same as Google Play-installed IG, though I didn't test opening links.

**Comment by oSumAtrIX** [comment]
Do that as well as debug sign the Instagram APK (Using https://github.com/patrickfav/uber-apk-signer/releases/tag/v1.3.0 for example, lookup how to use this online) and test again.

**Comment by Vandino86** [comment]
> Do that as well as debug sign the Instagram APK (Using https://github.com/patrickfav/uber-apk-signer/releases/tag/v1.3.0 for example, lookup how to use this online) and test again.

"www.instagram.com" links work in unpatched IG 353.0.0.46.90 (installed via the APK saved on my phone).

I ran that program on my Windows 10 PC and I was able to resign both my unpatched and patched IG 353.0.0.46.90 APKs, but I'm not sure which one you want me to install and use (unpatched or patched).

**Comment by oSumAtrIX** [comment]
Try both then?

**Comment by Vandino86** [comment]
> Try both then?

I just tried the debug-signed version of the unpatched IG APK and then the debug-signed version of the ReVanced patched IG APK and they both have the same issues as non-debug-signed ReVanced IG: "www.instagram.com" is always disabled and links don't actually open to the post.

So I guess this is a signing issue rather than a ReVanced patching issue?

**Comment by oSumAtrIX** [comment]
Yep. Probably a limitation on Androids end.

**Comment by neekless** [comment]
> I just tried the debug-signed version of the unpatched IG APK and then the debug-signed version of the ReVanced patched IG APK and they both have the same issues as non-debug-signed ReVanced IG: "www.instagram.com" is always disabled and links don't actually open to the post.
> 
> So I guess this is a signing issue rather than a ReVanced patching issue?

> Yep. Probably a limitation on Androids end.

@Vandino86 @oSumAtrIX 
This might be caused by something in newer instagram versions or the patch not being 100% compatible with newer versions. I was also experiencing this issue until I went to patch version 350.1.0.46.93 and links open the app perfectly fine. I'm not sure from which version the issue started. If I have time I will patch each version going up from 350.1.0.46.93 and find out which version started to break this.

**Comment by neekless** [comment]
I think it's safe to assume that it breaks from 351 onwards.

Since merely signing with debug keys breaks it, it's safe to assume it's not the fault of the patch, but I wonder if instagram is detecting it somehow in 351+ and if a patch could be made to disable that detection.

Not being able to open instagram links that my friends sent me through messaging apps is a pain.

**Comment by oSumAtrIX** [comment]
Perhaps caused by https://developer.android.com/training/app-links/verify-android-applinks
