### ISSUE TITLE
bug(Instagram): 'Change version code' breaks compilation 

### ISSUE THREAD

**Issue by Aqqly** [ReVanced/revanced-patches#3780]
### Bug description

When applying the 'Change version code' universal patch to Instagram, it breaks at compilation.

I've tried all kinds of versions, ranging from very old ones (333.0.0.42.91) to the very latest (353.1.0.47.90). All the same behavior.

The app patched with only 'Hide ads'  keeps popping up in Play Store updates and I'm trying to prevent that. Hence why 'Change version code' is quite essential.

### Error logs

Reading APK
Decoding app manifest
Loading patches
Deleting existing temporary files directory
Decoding resources
Executing patches
Applied 2 patches
Compiling patched dex files
Compiled 16 dex files
Compiling modified resources
An error occurred:
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~Y-mrw2BeJycGF7EHfReGHg==/app.revanced.manager.flutter-iguKLWAC84cIZauAreNp2A==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/files/patcher/tmp-VZWBHC/revanced-temporary-files/apk/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/files/patcher/tmp-VZWBHC/revanced-temporary-files/apk/build/resources.zip]
	at brut.androlib.AaptInvoker.invokeAapt2(Unknown Source:144)
	at brut.androlib.AaptInvoker.invokeAapt(Unknown Source:106)
	at app.revanced.patcher.data.ResourceContext.get(SourceFile:0)
	at app.revanced.patcher.Patcher.get(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$35(Unknown Source:495)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$t9VOe3aFJZkCMY59Ya4Pcinu-pA(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda6.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~Y-mrw2BeJycGF7EHfReGHg==/app.revanced.manager.flutter-iguKLWAC84cIZauAreNp2A==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/files/patcher/tmp-VZWBHC/revanced-temporary-files/apk/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/files/patcher/tmp-VZWBHC/revanced-temporary-files/apk/build/resources.zip]
	at brut.util.OS.exec(Unknown Source:75)
	at brut.androlib.AaptInvoker.invokeAapt2(Unknown Source:122)
	... 7 more
Something went wrong:
PathNotFoundException: Cannot copy file to '/data/user/0/app.revanced.manager.flutter/files/lastPatchedApp.apk', path = '/data/user/0/app.revanced.manager.flutter/files/patcher/tmp-VZWBHC/out.apk' (OS Error: No such file or directory, errno = 2)

### Solution

That the bug gets fixed/the issue gets looked at by the relevant devs.

### Additional context

- Device Info
ReVanced Manager: 1.22.0
Model: Pixel 8 Pro
Android version: 15
Supported architectures: arm64-v8a
Root permissions: No

- Patch Info
App: com.instagram.android v352.1.0.41.100 (Suggested: Any)
Patches version: v4.16.0
Patches added: Change version code
Patches removed: None
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: true
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

![Image](https://github.com/user-attachments/assets/a0a6913a-929a-4ce8-a9d7-4afb47dfe398)
![Image](https://github.com/user-attachments/assets/87094714-d270-4a0d-8d50-8e63b6af7291)

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Resource patching is not possibe due to AAPT failing. Thats why the patch is also disabled by default .

**Comment by Aqqly** [comment]
> Resource patching is not possibe due to AAPT failing. Thats why the patch is also disabled by default .

@oSumAtrIX Surely there must be something that can be done, right? I'm just an average user reporting the issue, but I noticed that it _does_ work with all other apps that can be patched..

**Comment by oSumAtrIX** [comment]
No. The issue originates from AAPT in androlib library from ApkTool outside of ReVanced's reach or matter.

**Comment by Aqqly** [comment]
@cyberboh I don't get what you mean. I did try it with the appropriate dpi APKs, but it still pops up in the Play Store wanting to update. Every single time when there's a newer version. 'Change version code' fixed this for the other patched apps that showed the same behavior..
