### ISSUE TITLE
Video Doorbell ( Reolink) Help

### ISSUE THREAD

**Issue by bensmithgb53** [ReVanced/revanced-patches#3781]
### Feature description

Video Doorbell Reolink app

When someone rings the doorbell, the app only sends a brief pop-up notification with a 2-second sound, similar to when you receive a message on Facebook Messenger (photo number 1). It doesn’t function like a normal doorbell.

However, if the app is open, you receive a proper ringing notification with options to answer or end the call, which works as expected (photo number 2). But this only happens when the app is open and active. Reolink hasn't addressed this issue and won't fix it.

Could you help? If the code that triggers the ringing notification when the app is open (photo number 2), move the code  to where the code for the 2-second sound notification is (phone number 1), it should allow both the ringing notification and the 2-second sound with the pop-up to work even when my phone is locked![Image](https://github.com/user-attachments/assets/97bd9cf8-acf9-4ebd-8d5d-70026de72508)
![Image](https://github.com/user-attachments/assets/aa4221e5-6bdb-4a91-8b12-83f86ad07bb5)

### Motivation

Please could you help 🙏  I have missed so many people at my door.

### Acknowledgements

- [x] I have checked all open and closed feature requests and this is not a duplicate
- [x] I have chosen an appropriate title.
- [ ] All requested information has been provided properly.

**Comment by bensmithgb53** [comment]
> For the time it would take to try and fix this with a patch, the time would be better spent buying a different door bell 😭
> 
> I would contact the manufacturer of the app and ask them. They made it and they have the source code.

Is this only good doorbell out there that does 24/7 recording continuous and no monthly fee. Use to have Ring but price kept going up.

**Comment by oSumAtrIX** [comment]
You can use tasker and trigger an alarm when that notification is sent

**Comment by bensmithgb53** [comment]
> You can use tasker and trigger an alarm when that notification is sent

This will drain my battery alot. What if making it so notification sound is longer to I know its there.

**Comment by oSumAtrIX** [comment]
No it wont.

**Comment by bensmithgb53** [comment]
> > But tasker will keep continuously running in the background waiting for reolink notification
> 
> No it won't. Notifications are pushed to Tasker when they occur. It's not polling or otherwise needlessly checking for notifications.

I will have a look into this.

**Comment by bensmithgb53** [comment]
> > But tasker will keep continuously running in the background waiting for reolink notification
> 
> No it won't. Notifications are pushed to Tasker when they occur. It's not polling or otherwise needlessly checking for notifications.

Do you have a video please how to set this up?
