### ISSUE TITLE
feat (YouTube): Store search and watch history locally

### ISSUE THREAD

**Issue by FixItKit** [ReVanced/revanced-patches#3783]
### Feature description

There should be a patch for YouTube that enables storing search and watch history locally.

### Motivation

Your search and watch history are added to your Google account. Enabling this patch would store search and watch history locally.

Benefits:
- More privacy
- Less data usage

**Comment by oSumAtrIX** [comment]
You can use a Google account

**Comment by oSumAtrIX** [comment]
The amount saved is equivalent to the comment you just posted, it's not a reason
