### ISSUE TITLE
bug: Revanced soft rebooting device

### ISSUE THREAD

**Issue by iliqiliev** [ReVanced/revanced-patches#3784]
### Bug description

As mention in #3263.

The issue here is dismissed but exactly the same thing happens on my device - LineageOS 21 (Android 14) with root and mount installs.
Both Youtube and Infinity for Reddit (the only 2 applications installed with ReVanced) "uninstalled themselves" after the soft reboot.

This cannot be a coincidence.

First time it happened was a month ago, then I reinstalled the 2 apps but it happened twice in the last 2 days.

Another strange thing is that when installing the vanilla YouTube app, after a manual reboot it is replaced by "Audio Track" app with the default android app icon that just crashes on launch.
There is also an notification on the AoD about it crashing. 

I am stumped.

### Error logs

None

### Acknowledgements

- [ ] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
The issue is related to how mounting works. It belongs in the library repository that handles that. I think an issue for this is already open therr
