### ISSUE TITLE
feat: Add an option to remove google photo update pop-up

### ISSUE THREAD

**Issue by KEVIN970712** [ReVanced/revanced-patches#3788]
### Motivation

![Image](https://github.com/user-attachments/assets/7aa466f6-346b-4eb0-a0bf-8d36a7d61af6)
It really annoy me,i don't want to update.

### Acknowledgements

- [x] I have checked all open and closed feature requests and this is not a duplicate
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Update the app.
