### ISSUE TITLE
feat(YouTube/YT Music): Steps to decrease battery drain

### ISSUE THREAD

**Issue by 0xrxL** [ReVanced/revanced-patches#3793]
### Feature description

The following commit: https://github.com/inotia00/revanced-patches/commit/f999aead6bdfd8040a5fdbd9f380c0dc6f79a5bc

is the result of a research done between me and @inotia00, about the anomalous battery consumption by the YouTube and YouTube music apps.

Now both shouldn't drain battery anymore for some users.

### Motivation

This feature request aims to align (or even decrease) the consumption of both apps to their stock versions, so as not to create problems.

### Acknowledgements

- [x] I have checked all open and closed feature requests and this is not a duplicate
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by 0xrxL** [comment]
YouTube behaviour after commit  ---> Use time: 40 minutes; Battery use: 3%

**Comment by oSumAtrIX** [comment]
Explain the changes you linked

**Comment by 0xrxL** [comment]
> Explain the changes you linked

Some libraries (including Primes, which sometimes causes the app to force close) not yet included in MicroG, have been blocked to prevent excessive consumption of device resources.

However, I believe that the libraries in question have to do with Google telemetry or in any case the app logs, because their absence does not change the functionality of the app.

P.S: Not all users can experience the aforementioned problems, this convinces me even more that these libraries are a part of telemetry or logs.

**Comment by oSumAtrIX** [comment]
> which sometimes causes the app to force close

What's the basis on this

> not yet included in MicroG, have been blocked to prevent excessive consumption of device resources

YouTube runs fine with upstream GmsCore. I don't see any excessive consumption either. So how do you know?

**Comment by 0xrxL** [comment]
> > which sometimes causes the app to force close
> 
> What's the basis on this

For example: YouTube crash on my side, if I don't apply ```Primes``` patches.

> > not yet included in MicroG, have been blocked to prevent excessive consumption of device resources
> 
> YouTube runs fine with upstream GmsCore. I don't see any excessive consumption either. So how do you know?

This is your experience about YouTube usage, can you confirm that all users could share this as well?

Inotia can reproduce another behaviour, and some users on reddit too. 🤷‍♂️

**Comment by 0xrxL** [comment]
Another example: https://www.reddit.com/r/revancedapp/comments/1duor8m/youtube_revanced_draining_battery/

**Comment by oSumAtrIX** [comment]
> For example: YouTube crash on my side, if I don't apply Primes patches.

Not in my or anyone elses case.


> This is your experience about YouTube usage, can you confirm that all users could share this as well?

So is yours. I'll reopen when you add understandable proof/evidence of what the patches change exactly, how it affects battery life and why battery would differ with the patch. Otherwise baseless assumptions so far
