### ISSUE TITLE
bug(YouTube - Spoof app version): If patching 19.34+, version spoofing to 18.x or lower breaks the Shorts player buttons

### ISSUE THREAD

**Issue by LisoUseInAIKyrios** [ReVanced/revanced-patches#3801]
### Bug description

If using 19.34 and version spoofing is enabled, then all overlay buttons in the Shorts player are hidden.

Excluding all patches except `GmsCore support` and `Spoof app version` does not fix the issue.

It's also not an issue with old and new app data getting confused, as manually changing spoof app version to default on with a fresh install does not fix it.

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by AsphaltKoreaWiki** [comment]
What is the spoofed version?

**Comment by AsphaltKoreaWiki** [comment]
Does it work well at 18.38.45?
