### ISSUE TITLE
bug(YouTube - Playback speed): Custom playback speeds, remember playback speed does not work

### ISSUE THREAD

**Issue by LisoUseInAIKyrios** [ReVanced/revanced-patches#3808]
### New playback speed menu
19.34+ has an a/b test for a new playback speed menu.

It has 0.05x increments similar to the default ReVanced custom speeds of 0.90/0.95/1.05/1.1, but can also adjust by 0.05 increments from any present.

The max speed is still limited to 2.0.

**Custom playback speeds do not show in the new speed menu.** Although the player overlay speed button does work correctly.
 
![Image](https://github.com/user-attachments/assets/3db4f2d9-f244-4b64-aac1-eceddac150e9)

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
I think this is fine to remove the patch. Anything above 2x is hardly useful and the precise speed slider is precise enough. On a related note, the speed entries are sent with the /player response from what I have yeen. Unless that changed, the response can be modified

**Comment by oSumAtrIX** [comment]
> The higher speeds only show if a default speed over 2.0x is used, and then it allows going up to 8.0x.

Default speed as in via the ReVanced patch? Then officially there's no speed higher than 2? Why would YT make it premium when it doesn't officially exist.

**Comment by oSumAtrIX** [comment]
It is possible that this isn't controlled by a feature flag, instead by the response in the player (or next) request. The response may include instructions to toggle on this UI. I have seen JS been mentioned in Litho logs too so maybe YouTube integrates it into SSR.

**Comment by someonewithpc** [comment]
> Anything above 2x is hardly useful

I strongly disagree. I use anywhere between 2.5 and 3.75 regularly, depending on the video
