### ISSUE TITLE
bug: Sync for Reddit v19.0.22 "This APK has been modified and might be unsafe"

### ISSUE THREAD

**Issue by emb531** [ReVanced/revanced-patches#3811]
### Bug description

Sync for Reddit version 19.0.22 - successfully patched using only Disable ads and Spoof client options, completes and installs as normal, but received below error when opening the app.  Unable to proceed past message. 

Pixel 9 Pro running Android 15

![Image](https://github.com/user-attachments/assets/d84de9fa-abec-4181-957f-9f50200eea5b)

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Use the latest version of Sync.

**Comment by emb531** [comment]
I still much prefer the app before the major redesign, this was the latest version of that configuration.  Any possible to chance to somehow make it work?  It does work as root Mounted just not a regular install.

**Comment by oSumAtrIX** [comment]
The new version can be tuned to look almost like the old one. No plan to support old versions therefore.

**Comment by emb531** [comment]
Fair enough, thanks for the work either way.
