### ISSUE TITLE
feat: patches for ibisPaint X (jp.ne.ibis.ibispaintx.app)?

### ISSUE THREAD

**Issue by pressRtowin** [ReVanced/revanced-patches#3812]
### Feature description

Would love to see some patches for this app. One of the best options available for Android now that Photoshop Fix/Mix is dead (and Photoshop Express is trash). Obviously some server side stuff probably can't be unlocked (like the extra cloud storage), but maybe ads can be hidden, and some other paywalled features unlocked?

### Motivation

Photoshop Fix/Mix were killed by Adobe, and not very many good alternative options remain for serious photo editing on mobile devices. Lightroom is one of the few other good tools, and it's great for certain things, but it lacks several key features for more precise editing. This app provides many essential tools for anyone interested in photography and photo editing.

### Acknowledgements

- [x] I have checked all open and closed feature requests and this is not a duplicate
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Some patches? You're not mentioning which
