### ISSUE TITLE
bug: `autorepeat` patch malfunctioning

### ISSUE THREAD

**Issue by lbchX** [revanced/revanced-patches#382]
### Type

Other

### Bug description

I realised that on my phone (Mi 10 Lite 5g) Youtube ReVanced continues 
playing the same video, after its duration stops!

### Steps to reproduce

1. I chose a video
2. I played it till the end
3. Video plays again
4. Even with "disabled autorepeat"

### Relevant log output

```shell
Youtube continues playing video after its duration stops!
```

### Additional context

_No response_[
![IMG_20220823_232911](https://user-images.githubusercontent.com/40717931/186259473-754a9260-13da-4563-9a26-767367acfe53.jpg)
](url)

**Comment by TheJeterLP** [comment]
The setting is not autoplaying. It's autorepeat

**Comment by TheJeterLP** [comment]
![Screenshot_2022-08-23-22-20-00-90_64ef5fc2000c1caa954c114bb372e1d5.jpg](https://user-images.githubusercontent.com/3790121/186257885-c0c69a2e-b475-4c34-a5a3-1d82aa1206ee.jpg)
Disable this.

**Comment by lbchX** [comment]
> ![Screenshot_2022-08-23-22-20-00-90_64ef5fc2000c1caa954c114bb372e1d5.jpg](https://user-images.githubusercontent.com/3790121/186257885-c0c69a2e-b475-4c34-a5a3-1d82aa1206ee.jpg) Disable this.

Sorry wrong translation :)

**Comment by TheJeterLP** [comment]
> Sorry wrong translation :)
Still, send screenshot of that setting

**Comment by oSumAtrIX** [comment]
Restart the app after changing the setting and it should work afterward.

**Comment by lbchX** [comment]
> Restart the app after changing the setting and it should work afterward.

Same problem, nothing changed!

**Comment by oSumAtrIX** [comment]
I can not reproduce, include the command you used.

**Comment by TheJeterLP** [comment]
> > Restart the app after changing the setting and it should work afterward.
> 
> Same problem, nothing changed! 

Try to clear app data and try again.

**Comment by lbchX** [comment]
> > > Restart the app after changing the setting and it should work afterward.
> > 
> > 
> > Same problem, nothing changed!
> 
> Try to clear app data and try again.

I did it, but nothing happens!

**Comment by oSumAtrIX** [comment]
Please do [this](https://github.com/revanced/revanced-patches/issues/382#issuecomment-1224861639) and record the issue.

**Comment by TheJeterLP** [comment]
@oSumAtrIX look at the screenshot he provided. He used the wrong setting.

**Comment by TheJeterLP** [comment]
> > > > Restart the app after changing the setting and it should work afterward.
> > > 
> > > 
> > > Same problem, nothing changed!
> > 
> > Try to clear app data and try again.
> 
> I did it, but nothing happens!

You change the wrong setting. Open settings->revanced settings->miscellaneous->autorepeat. Disable that.

**Comment by oSumAtrIX** [comment]
Autorepeat is the correct setting though, he toggled it.

**Comment by TheJeterLP** [comment]
> Autorepeat is the correct setting though, he toggled it.

No he did not. He toggled youtubes setting, not the one from revanced.

**Comment by oSumAtrIX** [comment]
Gotcha, well case closed lol

**Comment by TheJeterLP** [comment]
> Gotcha, well case closed lol

Patch still needs to be rewritten so it remembers the last used value. I don't know how to do that tho.

**Comment by oSumAtrIX** [comment]
For me it remembers the setting, what do you exactly mean?

**Comment by lbchX** [comment]
> > Autorepeat is the correct setting though, he toggled it.
> 
> No he did not. He toggled youtubes setting, not the one from revanced.

Yes, he is right!Sorry for the inconvenience, just checked it!
Thank you very much both of you for the info :D

**Comment by TheJeterLP** [comment]
> For me it remembers the setting, what do you exactly mean?

So the patch should function like the video quality patch. So when a user enables auto-repeat in YouTube player controls, it saves that value and applies it to the next video.

**Comment by oSumAtrIX** [comment]
That makes sense, in that case, we have to somehow hook when the setting in the flyout changes, please open a QoL issue for this.

**Comment by TheJeterLP** [comment]
> That makes sense, in that case, we have to somehow hook when the setting in the flyout changes, please open a QoL issue for this.

QoL?

**Comment by Canny1913** [comment]
Quality of Life

**Comment by TheJeterLP** [comment]
> That makes sense, in that case, we have to somehow hook when the setting in the flyout changes, please open a QoL issue for this.

Done. See #383
