### ISSUE TITLE
bug(YouTube - Spoof app version): Spoof target 17.33.42 no longer works

### ISSUE THREAD

**Issue by LisoUseInAIKyrios** [ReVanced/revanced-patches#3824]
### Bug description

Previously the spoof target 17.33 gave the older layout where the player has native action buttons.

But now that no longer works, and the player shows the current Litho action buttons.

It's not an issue with the app data, as manually setting version spoofing to default on with a fresh install and it still shows the new player layout.

Also tried patching the oldest supported target (18.38.44), and when spoofing it still shows the litho player buttons.

The target should be removed as it no longer provides any difference with 17.41.37

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by AsphaltKoreaWiki** [comment]
The only difference is that the top thumbnail does not appear on the playlist screen.
