### ISSUE TITLE
bug(YouTube - Hide layout components): 'Hide gray separator' does not do anything

### ISSUE THREAD

**Issue by LisoUseInAIKyrios** [ReVanced/revanced-patches#3826]
### Bug description

`Hide gray separator` seems obsolete and the setting no longer seems to do anything

When spoofing to an old version the separators can show in the library and a few other places, but the hide setting does not seem to hide anything there either.

The code for this is:
```
        final var graySeparator = new StringFilterGroup(
                Settings.HIDE_GRAY_SEPARATOR,
                "cell_divider" // layout residue (gray line above the buttoned ad),
        );
```

The component `cell_divider` does appear in the litho logs, but it now appears to be blank space or some other non visible element because there is no visual change when this is hidden or not.

&nbsp;
&nbsp;
Is this setting still relevant?  Should it be removed?

If this still shows up, then the setting description should be updated to describe exactly where.

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by kazimmt** [comment]
It still removes some empty spaces Between Title 1 & Thumbnail 2

**Comment by oSumAtrIX** [comment]
Have you checked light mode for the separator?

**Comment by kazimmt** [comment]
I've checked in light mode also (Tho my one is monet)
Need to re-check
I guess they changed the color but still Seperator presents. Maybe not gray

**Comment by kazimmt** [comment]
![Image](https://github.com/user-attachments/assets/80b19e7e-3c96-419c-a78d-e992adde5752)

Even on stock android, it's just empty space 😧

**Comment by 0xrxL** [comment]
19.43.34 - Dark Mode

cell_divider is still here

![Image](https://github.com/user-attachments/assets/22ebe5df-8e92-4a45-9b11-c7b9f2c8e69c)

**Comment by oSumAtrIX** [comment]
That's negligible. The divider was particularly ugly in the feed. It can be removed

**Comment by 0xrxL** [comment]
> That's negligible. The divider was particularly ugly in the feed. It can be removed

In fact I just unlocked it in My Tab (the unique view where it's visible...at this point).

**Comment by oSumAtrIX** [comment]
I don't know what a My Tab is. It's not relevant if it's used in such hidden places

**Comment by ILoveOpenSourceApplications** [comment]
I saw it in two more areas in search. Just wanted to point that.

One on top of channel profiles.
![Image](https://github.com/user-attachments/assets/01ea87ef-101c-4a59-a358-d3f16688849a)

Second on top of the search result categories.
![Image](https://github.com/user-attachments/assets/40470f0f-e7c4-41c0-b7e7-c6b69487264c)

**Comment by kazimmt** [comment]
The one in search result is also different
These are official cards i guess
[Image](https://github.com/user-attachments/assets/7ab87f83-1e7b-4a28-b6f7-2c519dd63f4f)
![Image](https://github.com/user-attachments/assets/89dbc1f1-f120-4d08-8525-2f9772a743f0)

**Comment by kazimmt** [comment]
@LisoUseInAIKyrios Going to revert the commit or not?

**Comment by ILoveOpenSourceApplications** [comment]
While custom filters can be powerful, the `Hide gray separators` setting offers a simple solution for users who want a cleaner interface. Even if its use cases are limited, it's a convenient option for those who prefer a minimalist look. Plus, we can never be sure what future YouTube might do (#spooky).
