### ISSUE TITLE
feat: YouTube: Search Comment

### ISSUE THREAD

**Issue by Rachitidk** [ReVanced/revanced-patches#3837]
### Feature description

1) Search comment like offered by `https://ytcomment.kmcat.uk/`
2) Sort if possible
3) Hide comments with specific keywords if possible.

### Motivation

1) There are many movies, manga recap channel which doesn't post the name in description as well as comment, helpful in finding name provided by other user.
2) Also useful in finding comments by different user or a specific comment.
3) Comment about someone asking for solution to some problem that you where also facing, and later when you find the solution, you can answer him.
4) Disscusion about a particular time/scenario in the video.
5) YouTube is showing different comment during for the specific time in video, in preview comment during video, but it hide when you open comment box.
6) Hide comments by bots, explicit comments.

### Acknowledgements

- [x] I have checked all open and closed feature requests and this is not a duplicate
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
You can use the site you just linked. YouTube is a video player app, not a comment finder utility tool.
