### ISSUE TITLE
bug(Twitter / X): Cannot post or retweet

### ISSUE THREAD

**Issue by miltonjsvidal** [ReVanced/revanced-patches#3838]
### Bug description

The app won’t let me tweet or quote a tweet since I updated it. I’ve tried uninstalling and reinstalling, downloading the APK, and patching it again, but it still doesn’t allow me to tweet.

### Version of ReVanced Manager and version & name of app you are patching

Revance manager v1.22.0
X 10.48.0-release.0

### Installation method

Regular

### ReVanced Manager logs

"com.twitter.android": [
    "Change link sharing domain",
    "Dynamic color",
    "Hide ads",
    "Hide recommended users",
    "Hide view count",
    "Sanitize sharing links",
    "Unlock downloads",
    "Override certificate pinning",
    "Remove share targets",
    "Spoof Wi-Fi connection"

### Patch logs

Change link sharing domain
Dynamic color
Hide ads
Hide recommended users
Hide view count
Sanitize sharing links
Unlock downloads0
Override certificate pinning
Remove share targets
Spoof Wi-Fi connection

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [ ] I have chosen an appropriate title.
- [x] All requested information has been provided properly.
- [x] The bug is only related to ReVanced Manager.

**Comment by oSumAtrIX** [comment]
Reopen once the requested info above is provided
