### ISSUE TITLE
feat: [Youtube] Subscription Groups

### ISSUE THREAD

**Issue by Akv2021** [ReVanced/revanced-patches#3839]
### Feature description

Youtube app has a subscriptions tab which shows all the videos from all subscribed channels. 
However, there is no way to filter videos from channels in a particular category. 
The category can be interest/topic based and helps to focus on what the user wants to watch. 

### Motivation

- On PC this can be achieved by pockettube extension. Newpipe android app also supports grouping subscriptions.
- This saves users from scrolling through all the videos when looking only for a particular category (which is covered by multiple channels) OR has a large subscription list hence saving time.
- This feature was removed from youtube back in 2015 and never added back.

### Acknowledgements

- [x] I have checked all open and closed feature requests and this is not a duplicate
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
For that alternative apps exist that use the RSS feed. Alternatively you can create brand accounts and create sub groups that way
