### ISSUE TITLE
bug: YouTube screen off background play suddenly stopped working

### ISSUE THREAD

**Issue by ATaylor5596** [ReVanced/revanced-patches#3844]
### Bug description

There seems to be either a bug or combination of settings that cause background play to not function. Whenever using screen off background play, the app will crash and restart after a few minutes of listening. Both the current supported version 19.34.42 and the suggested version 19.16.39 both have this issue and it just recently started happening about a month ago. In addition, it seems shorts are broken for some reason, all interaction buttons are hidden, likes, comments etc all gone. Even in the settings with everything set to show and restarting it's still gone.

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Background optimization needs to be disabled for GmsCore as well as YouTube (or either, test yourself)
