### ISSUE TITLE
bug: Youtube history not working regardless of iOS or Android spoof selection.

### ISSUE THREAD

**Issue by BSiddharth** [ReVanced/revanced-patches#3845]
### Bug description

Youtube content watched in the patched app does not show up in the history. After checking out #3571 and #3208 I tried switching my spoof client but the YouTube watch history problem still remains. I have also tried reinstalling (with default patches) and 1/5 times it starts working only to fail after 5 minutes.  

### Additional context

I also need to log out and log in again the revanced gms every month to solve the never ending grey shimmer screen, which also affects the yt music app.

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by BSiddharth** [comment]
![Image](https://github.com/user-attachments/assets/e9ce1616-735e-4c0a-920f-6264df256c26)
How do I check the patch version? 19.16.39 is the yt app version I guess and last I patched was 18th sep (whatever latest patch version was at that time.)

**Comment by BSiddharth** [comment]
@LisoUseInAIKyrios Thanks. Its 4.13.3.

**Comment by oSumAtrIX** [comment]
Repatch to latest version.

**Comment by BSiddharth** [comment]
> you might block `s.youtube.com` url in your adblocker or using DNS that block it

Hmm. That doesn't explain why it would work temporarily after some fresh installs. Also, if I remember it correctly, patched app does show a banner if it detects domain being blocked. I will confirm this again tho.

**Comment by BSiddharth** [comment]
> Repatch to latest version.

Nope, still not working. Also my bad should have updated to the latest patch first before reporting. I have been facing this issue for quite some time (was just not irritated enough and close to my computer at the same time to report it) and have gone through patch updates before too. 

Also tried switching default spoof client again but still problem exists.

**Comment by oSumAtrIX** [comment]
Follow the second paragraph of https://github.com/ReVanced/revanced-patches/issues/3845#issuecomment-2447656464

**Comment by oSumAtrIX** [comment]
Follow this:

![Image](https://github.com/user-attachments/assets/c89e24fd-ca4d-4652-9747-8f058334dd56)

**Comment by BSiddharth** [comment]
> For now, with just the GMS core support patch enabled, history also works (I guess that's the closest I can go to unpatched).

After trying this out, I reinstalled with the default patches to get rid of the ads (which I already tried, after I updated to the latest patches previously in this thread) and for some reason it is working fine now. Why I don't know, but well if it's not broken :}

Thank you all for your time tho.

**Comment by BSiddharth** [comment]
Ehh it stopped working after a day or so :)

**Comment by oSumAtrIX** [comment]
Refer to this in a new issue https://github.com/ReVanced/revanced-patches/issues/3845#issuecomment-2447741163
