### ISSUE TITLE
feat: Share GmsCore support patch to all apps

### ISSUE THREAD

**Issue by UnrealKaraulov** [ReVanced/revanced-patches#3848]
### Feature description

'GmsCore support' patch for Chrome, Gmail and other apps to use it with ReVanced microG for Huawei phone.

### Motivation

Huawei phones google services alternative if phone not have 'signature spoofing' feature in firmware.

### Acknowledgements

- [x] All requested information has been provided properly.
- [x] I have chosen an appropriate title.
- [ ] I have checked all open and closed feature requests and this is not a duplicate

**Comment by oSumAtrIX** [comment]
https://github.com/ReVanced/revanced-patches/issues/1583
