### ISSUE TITLE
feat(YouTube): Disable `Swipe up for next video` overlay

### ISSUE THREAD

**Issue by Kuddus73** [ReVanced/revanced-patches#3853]
### Feature description

https://github.com/user-attachments/assets/79ed2f94-61ca-4c3c-aa89-1dfb0e1dc71d

### Motivation

From time to time that annoying overlay appears which disrupts completely the whole seamless and immersive binging of Shorts.

### Acknowledgements

- [x] I have checked all open and closed feature requests and this is not a duplicate
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Thats a bug by YouTube, report it to them. It should not show up.

**Comment by federicogith** [comment]
> It should not show up.

I've been using ReVanced for a while now and over the years, regardless of the YouTube version, I have encountered and still encounter that annoying overlap every now and then

@oSumAtrIX I too would greatly appreciate it if you would consider this feature request
