### ISSUE TITLE
bug(YouTube): Likes and dislikes are missing

### ISSUE THREAD

**Issue by ADlludu** [ReVanced/revanced-patches#3855]
There are no likes/dislikes count shown after restarting the app a few times. I had reinstalled the app to try to fix this and it worked for like the first few launches, after i launched it again after like an hour both likes and dislike counts disappeared again. Edit: weirdly enough this is not an issue on shorts likes/dislikes are visible there, but for normal videos the likes/dislikes are not visible even in the discription.

**Comment by ADlludu** [comment]
Thanks it seems to be working for now. I'll keep an eye out for a few hours to see if the issue persists.

**Comment by oSumAtrIX** [comment]
The issue happens on the unpatched app with the same version. If you think otherwise [follow this and report back](https://i.imgur.com/wTvWZMC.png)
