### ISSUE TITLE
feat: chatGPT: work without google dependencies

### ISSUE THREAD

**Issue by b4n6-b4n6** [ReVanced/revanced-patches#3857]
### Feature description

Currently chatGPT app will crash or error on my de-googled calyxos and stock pixel without google play store installed

### Motivation

I want to use chatGPT app on de-googled phone / phone without google play store

### Acknowledgements

- [x] I have checked all open and closed feature requests and this is not a duplicate
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
You can use the web app.

**Comment by b4n6-b4n6** [comment]
> You can use the web app.

I'm sorry, but I'm not seeing how the web version experience can come even close

**Comment by oSumAtrIX** [comment]
Its a chat app, you'll survive

**Comment by oSumAtrIX** [comment]
iirc chatgpt also uses play integrity
