### ISSUE TITLE
bug: youtube bar with "home,subscribtion,etc..." bugged in the new patches v-20

### ISSUE THREAD

**Issue by SaherMaged** [ReVanced/revanced-patches#3861]
### Bug description

after watching a short and backing up to close it said bar dissappears and must either reopen revanced or open a video to make it appear

### Solution

either reopen revanced or open a video to make it appear

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
The issue occurs in main branch as well. It is not caused by patches v20.

**Comment by SaherMaged** [comment]
I have been using main patches for 4 months never seen this bug untill the new patches

**Comment by oSumAtrIX** [comment]
Follow these steps using the latest normal release of ReVanced Manager and show how the issue does not occur:

![Image](https://github.com/user-attachments/assets/fe54f2c8-10a4-4fab-9125-4c5af2aead8f)

(Enter and exit shorts)

**Comment by SaherMaged** [comment]
> Turn off Shorts 'hide navigation bar'.
> 
> The feature also has some other minor issues such as the nav bar appearing after opening the comments or video description.

It is turned off

**Comment by SaherMaged** [comment]
So on the normal patches I have not encountered the issue

**Comment by oSumAtrIX** [comment]
![Image](https://github.com/user-attachments/assets/51cb5d9a-302d-4b8b-9b13-f52110f5e7e5)
