### ISSUE TITLE
bug(YouTube): 'Custom branding' and 'Change header' does not fully applied

### ISSUE THREAD

**Issue by cyberboh** [ReVanced/revanced-patches#3865]
### Bug description

So, i built the patches myself, using dev branch as source and from the commit https://github.com/ReVanced/revanced-patches/commit/d36ede0330b2dd446a9db5da494d8b3f3ab34848 then updated to the commit https://github.com/ReVanced/revanced-patches/commit/7ccfa57a6f2cde2b606b1228d6b9c06899c144ca
Built successfull and i patched YT 19.43.41 using this command:

`java -jar revanced-cli-5.0.0-dev.8-all.jar patch -p patches-5.0.0-dev.1.rvp --keystore-entry-alias=alias --keystore-password=password --keystore-entry-password=password --keystore=revanced.keystore -e "Custom branding" -OappName=YouTube -e "Change header" -Oheader=premium*header Apps\com.google.android.youtube-19.43.41-all.apk -o Install\YouTube_19.43.41-all_ReVanced.apk`

All patches applied, no errors occured. App name also changed to YouTube, but it is still using default YouTube logo. Also, it still using default YouTube header.

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
The quotes are not necessary as the CLI parser parses the value entirely as a string since there's no space or quotation. The CLI parser does parse the options also correctly, so this may be an issue with the patches.

**Comment by oSumAtrIX** [comment]
Though, the patch seems to work as expected:

![Image](https://github.com/user-attachments/assets/80eb71e4-395c-4c84-9169-719ad61775d1)

**Comment by oSumAtrIX** [comment]
The patch changed the assets for me just fine.

**Comment by oSumAtrIX** [comment]
The logo was changed by the patch:


![Image](https://github.com/user-attachments/assets/b4b2dd5b-c91b-40dd-b507-c6e074504994)

I have not tested if it appears though when installed. Perhaps this is a new change by YouTube and there are new paths that need to be patched as well.

**Comment by oSumAtrIX** [comment]
The patch does need adjustment to support these. They also seem to have a specific scaling which is annoying as I am not sure what factor for the scale is used.

**Comment by oSumAtrIX** [comment]
Actually, I think this file can be copied to the new path:

![Image](https://github.com/user-attachments/assets/83c33a34-e0d3-436e-b592-7fddad128d55)
