### ISSUE TITLE
bug: Videos stop after 10 seconds

### ISSUE THREAD

**Issue by LeonardasLeo** [ReVanced/revanced-patches#3873]
### Bug description

Would love to use Anddea or Rufusin, but on both any video stops playing after 10 seconds.

Phone used is Galaxy S23, android 14

Its not the internet, since revanced is working (but not Anddea or Rufusin) fine and also been tested in multiple networks

https://github.com/user-attachments/assets/41a8ce08-f693-4cfc-819d-1dc307ff2fa0

### Acknowledgements

- [ ] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Unofficial patches are not supported.
