### ISSUE TITLE
bug: Messenger Failing to Send/Receive Messages Due to MQTT Error

### ISSUE THREAD

**Issue by emmandesu** [ReVanced/revanced-patches#3877]
### Bug description

Messenger version: Version 484.0.0.0.64 (326804008)

The Messenger app is encountering an error within its MQTT client library, potentially affecting message delivery and app functionality. The error log indicates a failure with MCCLogErrorWithTrace(324) and error code C 1 in the msgr.msys component. This might be related to network connectivity, server-side issues, or a bug within the MQTT client library.

### Error logs

```shell
1731157579.211 10337 25330  7772 E msgr.msys: E[C 1]MCCLogErrorWithTrace(324)=>121/195/1546/1
```

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Not sure what this has to do with ReVanced.
