### ISSUE TITLE
bug(Youtube): LG Wing, Second Screen video controls not displaying

### ISSUE THREAD

**Issue by Mati822456** [ReVanced/revanced-patches#3878]
### Bug description

On the LG Wing, the feature to use the second screen for video controls is not functioning as expected.

**Steps to Reproduce:**
1. Open YouTube on the main screen.
2. Play any video.
3. Rotate the screen to activate the second display.
4. The video controls do not appear or respond on the second screen.

**Additional Notes:**
In the unpatched version, everything works as expected, and video controls are displayed and functional on the second screen.

### Additional context

- Device Info
ReVanced Manager: 1.22.0
Model: LM-F100
Android version: 13
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.google.android.youtube v19.16.39 (Suggested: 19.16.39)
Patches version: v4.17.0
Patches added: Default
Patches removed: None
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing temporary files directory
Decoding resources
Executing patches
Applied 60 patches
Compiling patched dex files
Compiled 9 dex files
Compiling modified resources
Aligning APK
Signing APK
Patched APK

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by Mati822456** [comment]
I tested the unpatched version 19.16.39, and it works perfectly with the second screen functionality.

I've now tried patching version 19.34.42, but I encountered the same issue.

Could this be an issue with the LG Wing, where it requires the default YouTube app to recognize and enable second screen support?

**Comment by Mati822456** [comment]
Unfortunately, after repatching with only `GmsCore support`, the issue persisted. It seems that **rooting the device** will be necessary in my case to enable the second screen functionality.

**Comment by oSumAtrIX** [comment]
Screenshot the video controls you are referring to.

**Comment by Mati822456** [comment]
![Image](https://github.com/user-attachments/assets/eacb9dcf-7cf5-41aa-aa5a-36764a99ddbe)

**Comment by Mati822456** [comment]
As far as I've noticed, this UI only appears on the unpatched YouTube app and on Netflix.

**Comment by oSumAtrIX** [comment]
If the UI appears on other apps, its not a YouTube specific thing which we can fix.
