### ISSUE TITLE
feat: patches from Lucky Patcher?

### ISSUE THREAD

**Issue by yonggamer** [ReVanced/revanced-patches#3886]
### Feature description

can these patches [CustomPatches.zip](https://github.com/user-attachments/files/17692788/CustomPatches.zip) [Download.zip](https://github.com/user-attachments/files/17692789/Download.zip) from Lucky Patcher be imported here?

### Motivation

broading what apps can be patched

### Acknowledgements

- [x] I have checked all open and closed feature requests and this is not a duplicate
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
No
