### ISSUE TITLE
bug: YouTube Music fails to patch

### ISSUE THREAD

**Issue by decipher3114** [ReVanced/revanced-patches#3893]
### Bug description

[patch_log.txt](https://github.com/user-attachments/files/17702968/patch_log.txt)

Here is the log file with all details

### Error logs

```shell

```

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [ ] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Please fill everything in the proper fields.
![Image](https://github.com/user-attachments/assets/3b55a1a7-6c3d-4647-abb7-8c86f7b2086a)
