### ISSUE TITLE
bug(YouTube - Change header): Original header is shown

### ISSUE THREAD

**Issue by 0101sumit** [ReVanced/revanced-patches#3902]
### Bug description

![Image](https://github.com/user-attachments/assets/8cfc3fad-dc6f-4756-8e3c-9709d16b454f)
![Image](https://github.com/user-attachments/assets/a05a9e38-0467-406d-bc9f-29d2b5332e5b)
![Image](https://github.com/user-attachments/assets/3a5c2b82-0210-4308-8b35-26bce465327a)
I'm patched youtube with "Change header"- "premium header" option. But when it patches it not showing YouTube Premium, shows default YouTube. Please fix this problem.

### Error logs

```shell

```

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Then it probably needs the same treatment as the custom branding patch

**Comment by kazimmt** [comment]
@LisoUseInAIKyrios on latest dev release `-Oheader=premium*header` didn't worked for me
Can you confirm it please

**Comment by SangeethSujith** [comment]
What if i want to set premium header using cli command
