### ISSUE TITLE
feat:  support patches for YouTube for Fire TV 23.5.r1.v245.0

### ISSUE THREAD

**Issue by gauravsaini** [ReVanced/revanced-patches#3908]
### Motivation

Support firestick youtube app

### Acknowledgements

- [x] I have checked all open and closed feature requests and this is not a duplicate
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Too nieche. Use the YouTube app or alternative TV apps

**Comment by gauravsaini** [comment]
Make a YouTube howto video , and I can try myself. Firestick has a reddit so can't just say it's niche

**Comment by Julmik647** [comment]
There is app called [SmartTube](https://smarttubeapp.github.io/) that works on Android-based Fire TVs and Firesticks.

**Comment by Mobasheera** [comment]
> There is app called [SmartTube](https://smarttubeapp.github.io/) that works on Android-based Fire TVs and Firesticks.

Correct, but SmartTube doesnt support voice search at all. It would be much better If there was an option of Youtube Revanced for Amazon FireTV
