### ISSUE TITLE
bug: (Youtube - Hide Cast Button): The patch has disappeared in the new version.

### ISSUE THREAD

**Issue by Theylanh** [ReVanced/revanced-patches#3912]
### Bug description

I have been using ReVanced without GmsCore and always disabled this patch to be able to stream content to the TV. The patch has disappeared with the new version and if I try to activate the button using the ReVanced options, it still does not appear in the player.

### Error logs

```shell

```

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
The patch was merged into `Hide player overlay buttons`.
