### ISSUE TITLE
bug: closing in-app browser stops video playback

### ISSUE THREAD

**Issue by jonas-hurst** [revanced/revanced-patches#392]
### Type

Error at runtime

### Bug description

Closing the in-app browser in incognito mode stops video playback

### Steps to reproduce

1. Start Youtube Revanced
2. enter incognito mode (click circle in upper right corner -> activate incognito mode )
3. start video playback
4. click a link (for example from video description) -> link opens in in-app web browser, video continues playing in background
5. close web browser (x-button in top left corner or back button)

Expected result: video continues playing
Actual result: video playback is stopped, video closes

### Relevant log output

```shell
n.a.
```

### Additional context

Maybe related to https://github.com/revanced/revanced-patches/issues/356 

youtube: v17.32.35
cli: v2.9.3
patches: v2.42.0

**Comment by thelocs** [comment]
Same here, v17.33.42

**Comment by oSumAtrIX** [comment]
Dupe of #356.
