### ISSUE TITLE
bug: Infinity for reddit Can't select Spoof client

### ISSUE THREAD

**Issue by iamthekings5** [ReVanced/revanced-patches#3923]
### Bug description

When attempting to patch Infinity 7.4.0 I am unable to select the Spoof client option. I tried with an old apk 7.3.4 and had the same error, but I have successfully patched this version in the past. This suggests this bug came about after updating revanced.

Here is a screenshot of the bug:
![Image](https://github.com/user-attachments/assets/19561540-5e7e-445d-91ed-4567ceb7707b)

### Error logs

```shell

```

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Use the latest version of ReVanced Manager. The option can be set just fine. Try clearing data too.

**Comment by KobeW50** [comment]
@oSumAtrIX The bug occurs in v1.23.2

https://github.com/user-attachments/assets/8a5adf24-e64f-41a3-adc6-f315755c46ce

When the spoof client patch option is set to null, it gives the error (which does not have an appropriate warning) and even when the patch option is set, the Spoof client patch cannot be selected until another patch is selected or deselected. 

Also the error message is missing punctuation. Should I open a bug report in the revanced-manager repository?

**Comment by iamthekings5** [comment]
@oSumAtrIX I am on latest version of revanced.

**Comment by oSumAtrIX** [comment]
What if you click here:
![Image](https://github.com/user-attachments/assets/80b0a26e-6492-45d8-9205-55977fb388ea)

**Comment by iamthekings5** [comment]
Issue resolved, thank you for your help.

**Comment by Sommergoldhaehnchen** [comment]
Issue is raised again.
When patching with latest patch version v5.13.0 and latest manager version v1.23.3 within the patch selection, the patch 'spoof client' is not selectable as there is a error message (see attached). So, patching is not possible.
The correct OAuth client ID was set and saved.

![Image](https://github.com/user-attachments/assets/3d5c64d2-8a17-4099-b198-86c443960955)

**Comment by Sommergoldhaehnchen** [comment]
> [@Sommergoldhaehnchen](https://github.com/Sommergoldhaehnchen) it is a bug in revanced manager
> 
> [ReVanced/revanced-manager#2321](https://github.com/ReVanced/revanced-manager/issues/2321)

Ok, thanks. Hopefully it's going to be fixed soon.
