### ISSUE TITLE
feat(Office Reader): Patch to remove coffee icon which is used to enable premium for some days

### ISSUE THREAD

**Issue by vippium** [ReVanced/revanced-patches#3926]
### Feature description

This patch is for [Office Reader by nTools](https://play.google.com/store/apps/details?id=net.sjava.officereader). This patch will remove the coffee icon on home screen which is used to enable Premium for 2-3 days. This patch will remove it permanently.

### Motivation

This will remove the annoying coffee and premium buy buttons from the main screen.

### Acknowledgements

- [x] I have checked all open and closed feature requests and this is not a duplicate
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Way too minuscule of a problem
