### ISSUE TITLE
The "Disable related video in quick actions" setting doesnt work

### ISSUE THREAD

**Issue by Sickhead01** [ReVanced/revanced-patches#3929]
### Bug description

It's not a new issue. It's been this way since forever. I have the toggles enabled yet when i swipe up the related videos still come up.
![Image](https://github.com/user-attachments/assets/99dd51d2-f279-46fc-b955-6adb0ca4497d)
![Image](https://github.com/user-attachments/assets/05c8003b-f5f9-4e5f-930b-c36e9ee08fb9)

### Error logs

```shell

```

### Additional context

Using Pixel 7

Patched Youtube version 19.43.41. it was the same in 19.16.39 AND all the versions before we were restricted to 10.16.39 for so long (which shows how long with has been an issue)

The have also be multiple post on reddit of other people with the same issue

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
The quick actions are the actions while playing the video in fullscreen. The related videos are shown at the end of the video while it is playing.

**Comment by Sickhead01** [comment]
Then add the feature to disable it entirely. It's annoying when trying to turn up the volume by swiping and it comes up. The other patches like RVX get ride of it entirely with that same toggle
