### ISSUE TITLE
feat: (YouTube - Channel blacklist/whitelist): Community driven whitelists and black lists

### ISSUE THREAD

**Issue by akoerner** [ReVanced/revanced-patches#3949]
### Feature description
Add the ability to specify channel/content whitelists or blacklists via text file or url pointing to a git repository list. The blacklist or whitelists are line delimited text files specifying content to allow or block within the feed. With community driven white lists i could imagine community curated lists  with references to channels involving specific topics such as physics or mathematics for example.  In the revanced settings this white list could be specified ether by a file or pointing to a url. Then content from the whitelist would be shown in the feed. Similarly, a blacklist could be specified that would prevent certain channels or content from showing up on the feed. 
The user could curate a list or the community could curate a list. It would be interesting to be able to block or filter content based off of titles, video length, or other meta data perhaps also supporting regular expressions.

Black list example:
```txt
# This is a comment
SomeChannel
AnotherChannel

# Blank lines are allowed but ignored
TestChannel

# Regular expressions (indicated by regex:)
regex:^.*\Nova$
regex:^Test\..*$

# Filtering on regular expressions for advanced matching
video_title=regex:^.*hello$ description="Block any video with the word hello from showing in the feed"

# Filtering on specific meta data, with the default being the channel name
video_title="Hello World"

```
 
### Motivation
There is a lot of AI generated garbage, misinformation and disinformation on YouTube. It would be nice to have more filtering and blocking capability in the revanced to increase the quality of your feed. 

### Acknowledgements

- [x] I have checked all open and closed feature requests and this is not a duplicate
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Filters aren't like ads that need constant updates. You can just copy paste a list you like over and use it.

**Comment by MurzNN** [comment]
The whitelist feature for YouTube is very useful to limit what young kids can watch. For example, I want to limit my kids to watching only a couple of specific channels, and fully hide access to other channels.

Yes, there is a separate YouTube Kids app, but it is not available in my current country (Armenia) and it misses all the ReVanced patches, so it's not a working option for me.

I researched other solutions and found a [SkyTube](https://github.com/SkyTubeTeam/SkyTube) app that already provides a whitelist feature! But other features of this app and a lot of bugs are not enough to replace the YouTube app.
