### ISSUE TITLE
Default Playback Speed

### ISSUE THREAD

**Issue by RedCoal27** [revanced/revanced-patches#395]
### Type

Functionality

### Issue

When using vanced, I have set 1.5x  default speed for video to watch more video in the same time windows. This was removed in revanced.

### Feature

Adding a way to set custom playback speed, maybe the same way like custom default video quality.

### Motivation

I know that i'm not the only one to use this feature and it could be quickly to add this option.

**Comment by oSumAtrIX** [comment]
Wrong place for suggestions, this has been suggested already.
