### ISSUE TITLE
bug: Setting default start page on youtube fails when closing app with back-navigation.

### ISSUE THREAD

**Issue by angryluck** [ReVanced/revanced-patches#3951]
### Bug description

For the newest RevancedPatch (Youtube version 19.43.41), when the app is closed by doing back-navigation (on most android phones done by pulling from the side of the screen, or by pressing the left-pointing triangle if using 3-button navigation), then Youtube opens in the Home tab.

Steps to reproduce:
1. Make sure you have YouTube patched with the "Change start page" patch
2. In the settings ReVanced > General layout > Set start page, change the startpage (to anything other than 'Default')
3. Restart the app to apply the change
4. Repeatedly press the 'back' button until YouTube closes (either the left-most button when using 3-button navigation on an androidphone, otherwise pulling the screen from the left)
5. Open app again

Expected result: The start page is whatever you set it to in step 2.
Actual result: The start page is the home-page.

Note that the new start page is launched correctly if the app is closed manually instead (opening the list of open applications, and swiping it away there).

### Error logs

```shell

```

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Exiting the app using the back gesture does not close the app. Instead, you go back to the home feed and minimize the app. The next launch will resume the last activity.
