### ISSUE TITLE
bug: YT music : time to have an update

### ISSUE THREAD

**Issue by DebakantPradhan** [ReVanced/revanced-patches#3963]
### Bug description

YT music : time to have an update. There is a banner in yt music to update to latest version. ![Image](https://github.com/user-attachments/assets/1ccec66f-7f14-4ae8-835f-8aa27c55e709)

It's currently working fine.But i am just creating this issue just to prepare before the disaster. So basically we need the latest version of the YouTube with all the same patches. 

### Error logs

```shell

```

### Solution

I don't know much but just every patch should work fine in just a new apk. Just adjust as needed. No feature is broken currently. 

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
There is no "app" update. Its on a per patch basis.

**Comment by DebakantPradhan** [comment]
> There is no "app" update. Its on a per patch basis.

Will it stop working if not updated. If it will stop please make necessary changes. 
Thanks a lot for all the things you offer. 🙏🏻😌
