### ISSUE TITLE
bug(YouTube - Spoof app version): Opening the You / Library tab crashes the app

### ISSUE THREAD

**Issue by Zakawer** [ReVanced/revanced-patches#3969]
### Bug description

With ReVanced Patches 5.0.2 applied to a YouTube 19.43.41 APK (current recommended version of the YouTube app), there's a potentially nasty bug that if triggered, cannot be reversed without either reinstalling and re-patching YouTube ReVanced, or clearing the storage. Here's how to activate and replicate the bug 
1. Apply ReVanced Patches 5.0.2 to a YouTube 19.43.41 APK using ReVanced Manager, including the "Spoof app version" patch
2. Go to the ReVanced settings, and select "General layout"
3. Enable "Spoof app version" and restart the app
4. Tap the "You" or "Library" button

You should see the app crash.

### Error logs

```shell

```

### Solution

Until it can be fixed by the ReVanced team directly, I do not recommend enabling "Spoof app version".

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Refer to the warning when toggling spoofing version.
