### ISSUE TITLE
bug: youtube music support version 7.28.51

### ISSUE THREAD

**Issue by 0101sumit** [ReVanced/revanced-patches#3971]
### Bug description

![Image](https://github.com/user-attachments/assets/6696343a-fe73-4ecb-8e71-dd623520f9be)
Please update youtube music 

### Error logs

```shell

```

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Thats not a bug

**Comment by 0101sumit** [comment]
By mistakely I clicked bug reported. I'm sorry.
Can you update youtube music
