### ISSUE TITLE
feat: Update TikTok version

### ISSUE THREAD

**Issue by AykhanUV** [ReVanced/revanced-patches#3975]
### Feature description

Can u update tiktok version to latest one?

### Motivation

It has a new feature i think called streak pet

### Acknowledgements

- [x] I have checked all open and closed feature requests and this is not a duplicate
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Updates are on a per patch basis
