### ISSUE TITLE
bug (YouTube): Comments tap to quote A/B test

### ISSUE THREAD

**Issue by 0xrxL** [ReVanced/revanced-patches#3986]
### Bug description

Starting from 19.47+ (at least in my case) the older one tap to quote a comment has been replaced by double tap to like the comment (such on shorts).

P.S: This should be related to the other A/B test that enable shorts scrolling on normal video player.

### Error logs

```shell

```

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
This is not a bug.
