### ISSUE TITLE
feat (YouTube): Re-enable one tap to quote a comment

### ISSUE THREAD

**Issue by 0xrxL** [ReVanced/revanced-patches#3987]
### Feature description

Starting from 19.47+ (at least in my case) the older one tap to quote a comment has been replaced by double tap to like the comment (such on shorts).

P.S: This should be related to the other A/B test that enable shorts scrolling on normal video player.

### Motivation

Not being able to quote comments by tapping on their entire section, instead on a small and poorly visible icon, is less convenient and also a habit that many (myself included) have, since before the ReVanced project existed.

### Acknowledgements

- [x] I have checked all open and closed feature requests and this is not a duplicate
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
You can single tap to reply to a comment or click the decently sized, and not small or poorly visible icon like you describe, button to directly reply.
