### ISSUE TITLE
bug: Hold video to set temporary 2x speed does not work

### ISSUE THREAD

**Issue by th1nhhdk** [ReVanced/revanced-patches#3989]
### Bug description

- When the video is playing you can press and hold that video for it to go 2x speed, after updating revanced it does not work anymore, it shows 2x icon but still the same speed
- It's Default patches 5.1.0

### Error logs

```shell

```

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
#3330

**Comment by th1nhhdk** [comment]
I'm using 1x, also before updating revamced it works normally

**Comment by th1nhhdk** [comment]
Sorry, have to fast forward video because of GitHub limitation
https://github.com/user-attachments/assets/e4262769-b268-4699-a4ec-90e076b530d2

Even when turning custom playback speed menu off the bug still happens, please reopen the issue

**Comment by th1nhhdk** [comment]
Just downgraded to Patches 5.0.2, the bug doesn't happen

**Comment by th1nhhdk** [comment]
> @th1nhhdk Your issue just duplicate of other same issue, just see linked issue that osum said above.

their issue is
> When the Playback speed patch is included, if you select any playback speed other than 1x, Hold to 2x speed doesn't work. The 2x >> overlay will appear but the video won't play at 2x.

Mine happens at 1x playback speed too, and only happens in 5.1.0, back in 5.0.2 the bug does not happen, so I believe it's a different bug
