### ISSUE TITLE
feat: (YouTube) Hide watched videos

### ISSUE THREAD

**Issue by jameslee0623** [ReVanced/revanced-patches#3997]
### Feature description

Hide watched videos with adjustable watched percentage threshold.

### Motivation

Mobile device has very limited screen space. We don't want to waste it on watched videos. It's a good idea to use Subscriptions as an inbox of new videos, and "watched" videos were "read". Some browser extension implements this feature, ex: https://jbscript.dev/control-panel-for-youtube

### Acknowledgements

- [x] I have checked all open and closed feature requests and this is not a duplicate
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
You can already adjust your recommendation based on videos you already watched. Click on "..." and select don't recommend.

**Comment by jameslee0623** [comment]
Sorry, let me clarify. I mean, automatically hide videos (for the outlay viewing only, not affect the recommending algorithm) after you watched them in your subscriptions feed. All the videos you subscribed should be the things you are interested, just for space-saving for other contents (videos you haven't watched), hide those you watched from the subscriptions feed automatically.
