### ISSUE TITLE
bug: picture in picture is applied even though this setting is turned off

### ISSUE THREAD

**Issue by NetanelMosheCohen** [ReVanced/revanced-patches#3998]
### Bug description

Platform - Android version 9
Version - 19..45.38 (currently latest)

Scenario:
1. Go to settings -> General -> picture in picture. Disable this setting.
2. Open a video and then back to the previous screen.

Expected result - The opened video player should be docked to the bottom
Actual result - The opened video player is floating even though "picture in picture" setting is disabled.

![Image](https://github.com/user-attachments/assets/886b967d-ded8-426a-9333-adeb09565ced)

### Error logs

```shell

```

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
This is not PiP. This is a miniplayer.

**Comment by NetanelMosheCohen** [comment]
@oSumAtrIX Sorry you are right, is there a way to make it docked as it was in older versions?

**Comment by NetanelMosheCohen** [comment]
Great, thanks a lot for the quick response!
