### ISSUE TITLE
feat:

### ISSUE THREAD

**Issue by mastertrivia** [ReVanced/revanced-patches#4003]
### Feature description

Title :- regarding "video quality" and "video speed" overlay button (small buttons on the player just above the progress bar)

Have a look on the attached screenshot

Both the features are not present on the advanced application and are very useful and useful. 

Subject: Feature Request for Enhanced User Experience

Dear Developer,

I hope this message finds you well. I am writing to request the addition of two crucial features to enhance the usability and user experience of the video player. While the application is already advanced and highly functional, these small but significant enhancements can take it to the next level:

1. Overlay Speed Button: Although the speed adjustment button can be enabled from revanced setting s, it currently does not display the playback speed on the overlay (it's just a button only).. Adding this functionality, similar to the NewPipe application, would provide users with instant feedback on playback speed without needing to access additional 3 dot menus.

2. Overlay Quality Button:

Currently, adjusting video quality requires navigating through the three-dot menu, which feels cumbersome...and is the only way to do so.

An overlay button that shows and allows adjustments to video quality directly from the player screen would significantly improve the user experience. This button should:

• Display the current quality.
• Allow quick adjustments with minimal clicks.

### Motivation

Why These Features Are Necessary ?? 

• Enhanced User Convenience:
Direct access to playback speed and video quality saves time and reduces interruptions, m![Image](https://github.com/user-attachments/assets/285ce588-414f-46e1-925d-30815aa7fa6d)
aking the app more user-friendly... 

• Improved Accessibility:

Quick-access overlay buttons cater to users who prioritize efficiency and seamless navigation in their media consumption experience.

Your attention to detail and commitment to providing an exceptional user experience are highly appreciated. I firmly believe that incorporating these features will further solidify the app’s reputation as a market leader.

Thank you for considering my suggestions. I look forward to seeing these enhancements in a future update!

### Acknowledgements

- [x] I have checked all open and closed feature requests and this is not a duplicate
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
A speed button already exists.
