### ISSUE TITLE
feat: ability to permanent dismiss the MicroG battery optimization warning

### ISSUE THREAD

**Issue by eiqnepm** [ReVanced/revanced-patches#4004]
### Feature description

Please may a dismiss button and a do not show again checkbox be added to the MicroG battery optimization warning?

![Image](https://github.com/user-attachments/assets/58adb531-fbd0-46b1-9a94-161be455343a)

### Motivation

I've never had issues with having MicroG optimized by my OS and would prefer to let my OS do what it needs to do to save battery.

### Acknowledgements

- [x] I have checked all open and closed feature requests and this is not a duplicate
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Refer to https://github.com/ReVanced/GmsCore/issues/158
