### ISSUE TITLE
Request: YT Short icon

### ISSUE THREAD

**Issue by Fearmipan** [ReVanced/revanced-patches#4005]
### Feature description

Please add circle background in YT short action button. 
(like YT short in browner). 

![Image](https://github.com/user-attachments/assets/40f12bff-cb64-4847-82d6-c92229d75c77)

Button with utline icon is annoying in bright/white short content. 

### Motivation

For better user experience!

### Acknowledgements

- [x] I have checked all open and closed feature requests and this is not a duplicate
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
The motivation does not make sense. This obstructs the video more
