### ISSUE TITLE
feat: microg support in google recorder app

### ISSUE THREAD

**Issue by atuy1219** [ReVanced/revanced-patches#4018]
### Motivation

google recorder app will be available for non-root.

### Acknowledgements

- [x] I have checked all open and closed feature requests and this is not a duplicate
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Iirc the recorder app is protected with pairip. Without bypassing that, it wont work
