### ISSUE TITLE
feat: Tiktok and Device Fingerprints

### ISSUE THREAD

**Issue by iwantgirlfriend** [ReVanced/revanced-patches#4021]
### Feature description

Hello everyone. I want to ask a question, is it possible to remove device fingerprints in patches? or substitution for random values? Tiktok collects a lot of data about the device and combines it into one whole in order to identify all accounts through one device that were logged in. This may be IMEI data, MAC Address, SIM card data and other data that does not change after resetting the device to factory settings. It would be nice to have a patch for this and change the Revanced settings to random values in order to maintain confidentiality about the device.

![Image](https://github.com/user-attachments/assets/e07b6acd-b6c6-4d52-b092-79b7b9f3331d)

### Motivation

This adds privacy and the user does not need to get root access to change device data or buy a new phone.

### Acknowledgements

- [x] I have checked all open and closed feature requests and this is not a duplicate
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
The main point is their data intelligence server side, not client side, what you watch and follow
