### ISSUE TITLE
bug: YouTube audio track unavailable

### ISSUE THREAD

**Issue by RoasterWow** [ReVanced/revanced-patches#4023]
### Bug description

Hello,

I'm experiencing an issue with the YouTube 19.46.42 app (recommended for the 19.46.40 patches). After applying the patches, the option to select audio tracks, which is available for multilingual videos like [this video] (https://youtu.be/bn0Kh9c4Zv4) has disappeared.

In the ReVanced settings, I can see that the "Hide audio tracks" option is disabled, indicating that audio track selection should be available. 
![Image](https://github.com/user-attachments/assets/a7e857e9-f1ff-4f7e-9c07-7da3c9c063f9)

However, in the player this feature is missing when using the patched app, while it appears as expected on the regular YouTube app. Enabling and disabling this option didn't fix the issue.

Original YouTube: the video has the option. 
![Image](https://github.com/user-attachments/assets/8c9eeb9d-34c3-4229-8d01-3e4ac0a3b11b)

Patched app: no audio track selection. 
![Image](https://github.com/user-attachments/assets/dceed89a-5bb9-493b-9ab4-61b2ba23c257)

Any help in resolving this would be appreciated.

Thanks!

### Error logs

```shell

```

### Acknowledgements

- [ ] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
https://github.com/ReVanced/revanced-patches/issues?q=sort%3Aupdated-desc%20is%3Aissue%20audio%20track
