### ISSUE TITLE
feat: Threads (Disable "For you" Tab) just keep Following

### ISSUE THREAD

**Issue by Be2iz** [ReVanced/revanced-patches#4024]
### Feature description

Meta Platforms Inc, the algorithm for the [Threads app](https://www.threads.net/) is sucks. It's better to get rid of it!

![Image](https://github.com/user-attachments/assets/957dca5b-841a-4d2e-a65a-3d78932dd261)

### Motivation

Nothing more than personal preference.

### Acknowledgements

- [x] I have checked all open and closed feature requests and this is not a duplicate
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Just swipe to following?
