### ISSUE TITLE
bug: hide videos recommendations at end of the video in full screen mode

### ISSUE THREAD

**Issue by sunnygrande** [ReVanced/revanced-patches#4027]
### Bug description

Whenever i play any video in full screen mode at the end of video i get few video recommendations. This video's are shown after suggested video at the end of video ![Image](https://github.com/user-attachments/assets/64841f62-099d-467c-b523-2ab4c69afc67)

### Error logs

```shell

```

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Thats not a bug, thats how youtube works.

**Comment by oSumAtrIX** [comment]
Nearly everything is possible
