### ISSUE TITLE
feat: hide youtube recommendations in full screen mode at the end of video

### ISSUE THREAD

**Issue by sunnygrande** [ReVanced/revanced-patches#4028]
### Feature description

I was able to hide "suggested video" by disabling "suggested video end screen" inside the player category.

Similarly, being able to hide video recommendations after suggested video will be much appreciated as it is very distracting.

![Image](https://github.com/user-attachments/assets/5f22c497-c2f9-44c2-b588-54483041246b)

### Motivation

I believe disabling suggested video feature was provided to avoid distractions. Similarly being able to hide these video recommendations will be much appreciated 

![Image](https://github.com/user-attachments/assets/0caa1554-d83d-47c1-8358-bfb4c49e493f)

It's important to defeat the algorithm to stay productive. 

### Acknowledgements

- [x] I have checked all open and closed feature requests and this is not a duplicate
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
https://github.com/ReVanced/revanced-patches/issues/849
