### ISSUE TITLE
feat: Xodo PDF Viewer Patch

### ISSUE THREAD

**Issue by tEctutoRIt** [ReVanced/revanced-patches#4032]
### Feature description

I would like to request patches for the Xodo PDF Viewer app. Xodo is a feature-rich PDF viewer and editor used by many for its excellent performance and tools. However, certain aspects of the app could be improved through patches to enhance the user experience.

Requested Patches:

1. Ad Removal:

2. Premium Branding and Logo Removal:

### Motivation

These patches would significantly enhance the user experience for those relying on Xodo as their primary PDF viewer/editor. Removing ads improves usability and respects user privacy, while eliminating premium branding aligns with creating a seamless, annoyance free interface.

### Acknowledgements

- [x] I have checked all open and closed feature requests and this is not a duplicate
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Simply use an ad free PDF editor. There's plenty out there

**Comment by nightznero** [comment]
> I do respect your opinion, and I understand your perspective. However, I believe Xodo stands out because of its unique combination of features, an intuitive interface, and an all-in-one package that any other PDF editors don’t offer.
> 
> That said, I appreciate your response and the time taken to review my request. Thank you for not considering it!

Search for Balatan relases, Xodo Balatan mod and ull find it. I would RV team focus on adds that are not widly shared by diff mods but stick to apps that really need to be "unlocked" bcs noone yet didn't done that before
