### ISSUE TITLE
feat(YouTube): Disable auto-dubbed audio tracks (use original language as default audio)

### ISSUE THREAD

**Issue by rodrigoswz** [ReVanced/revanced-patches#4033]
### Feature description

YouTube has an annoying feature enabled by default called Auto-dubbed. When enabled by the creator upon upload, the video's audio will be dubbed into the user account's default language. 

More info about this feature:
https://support.google.com/youtube/answer/15569972?hl=en

Video sample with this feature enabled and no option to disable:
https://youtu.be/NHUTmP9Tr2A

![Image](https://github.com/user-attachments/assets/a5a7e589-1b47-4a0a-856e-cbb2a3c9b12a)

![Image](https://github.com/user-attachments/assets/11542052-3a77-4f53-af07-5cca88414f6f)

![Image](https://github.com/user-attachments/assets/9cb0067d-b536-40a8-bc40-aebdda76ab1a)

### Motivation

The first problem is that this is enabled by default for the user, so they need to manually disable it after the video starts. 

~~And the second problem is that sometimes the subtitle/audio track option is not available for this dubbed video, so you are basically forced to watch the video with the generic audio.~~ edit: Changing to iOS spoofing fixes the missing audio track menu

### Acknowledgements

- [x] I have checked all open and closed feature requests and this is not a duplicate
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by rodrigoswz** [comment]
Btw my YouTube app is with English (US) defined as default language. But as my Google Account is from Brazil, the auto-dubbed is enabled by default anyway.

**Comment by oSumAtrIX** [comment]
This issue is about disabling dubbing not hiding the description component

**Comment by Otimpt** [comment]
I'm having the same thing related to auto-dubbed but when I disable `Video streams spoofing' and the audio track menu appears, I know about the side effects of `Video streams spoofing' but I've always used the ios client and the audio track menu was appearing until some time ago, plus it doesn't have written in the side effects that the audio track menu is missing.

**Comment by rodrigoswz** [comment]
> For me, the above video is dubbed in English. If so, then is the language from the creator is English?

Yes, the original audio from this creator is English.

> @rodrigoswz does stock YouTube have this same behavior?

Yes, same behavior with stock YouTube.

> Also try repatching with the latest release as it fixes an issue of spoofing using the wrong language for some situations.

Done, repatched with 5.2.2 but what was reported in this issue still persists.
-
I noticed two more points:

1. The video title is also translated to the system language if the YouTube app is using it. Even if I select the original audio, the title is still translated.

2. If I choose the original audio track (on stock YouTube or ReVanced one using iOS spoofing), any other auto-dubbed videos will follow the chosen audio track.

But if I close the app and open it again, dubbing is selected as default again.

**Comment by marianmargraf** [comment]
I can confirm the same behavior as mentioned in the previous post running 5.2.2.

My location, system and app are using German language. 
Certain videos that use the new auto dub feature behave like this:

Without spoof video, YouTube Revanced will use the video's original audio stream. For the videos I tested this issue with, that's English. This is the behavior I want and expect. Latest stock unpatched YouTube v19.47.41 behaves exactly like this.

With iOS spoof:
Revanced will start playing the German auto dub with ai voice.
Switching to the English original audio stream works. Restarting Revanced defaults back to German auto dub (bad).

With android VR spoof:
The German ai auto dub is used by default, with no way to switch back to the original English audio stream. 

Simply keeping the audio stream to the videos original language should be the default, with the option to switch it via YouTubes UI (if supported by the video spoof method).

**Comment by Karthik-Subbu** [comment]
@LisoUseInAIKyrios 

Is it possible to fetch original audio language code from the captions and substitute in the language parameter of spoof video streams? and possibly retain the video title also in original language ?

Inspiration: https://github.com/yt-dlp/yt-dlp/commit/ff9b0e071ffae5543cc309e6f9e647ac51e5846e

 In this way, we can maintain only two options in audio language under spoof streams: 1. Original 2. App language or Device default.

**Comment by f1nalspace** [comment]
Happens to me as well. I previously has set my language to english and then all content was suddenly auto-translated to english - even though the videos was recorded in my native language german. Reversing by setting to german helped neither and resulted in all english content to be translated. Even the video title is auto-translated which is extremely misleading, including spelling errors!

This is the worst kind of feature ever!

Please revert back to the old behavior, never auto-translating anything and the user decides itself if they want to switch to another audio and/or subtitle language.

I want to watch all content in its native language always, if its english, then english, if it is german than german, even japanese should stay japanese and i can enable subtitles if i want.

**Comment by P0liak** [comment]
Sorry to open it again but for french audio tracks the issue is still there (they have a shitty ai dubbed voice track, with only english listed as available tracks, nobody made a single comment about the videos being in english in the comments section so yeah)

**Comment by seiferflo** [comment]
This nonsense dubbing just happened to today on all French videos (ai translated to english). This is insane. I tried many settings but nothing changes and YT Rev doesn't offer the option to change the audio language of the video (spoofing activated or not). Would be great if someone can look at it. Many thanks for your consideration.

**Comment by kyryl-bogach** [comment]
Thank you @LisoUseInAIKyrios ❤

**Comment by Veniman8000** [comment]
YouTube adding AI Voice dubbing and AI translations was the biggest mistake to add to the platform, especially if you know the related languages but bad translations and AI voices being rubbed into your face and worsening the experience overall.

**Comment by NielsGx** [comment]
This video will always use the AI dub version, regardless of settings : https://youtube.com/shorts/IatsVEsB340

Interestingly, the audio track menu is NOT here for this video specifically 🤔
