### ISSUE TITLE
feat: (Boost) Fix redgifs with no audio

### ISSUE THREAD

**Issue by trlef19** [ReVanced/revanced-patches#4035]
### Feature description

Redgifs dont seem to have audio anymore on boost and on some other reddit apps.

### Motivation

gifs with audio work again

### Acknowledgements

- [x] I have checked all open and closed feature requests and this is not a duplicate
- [x] I have chosen an appropriate title.
- [ ] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
This is not a motivation. Use another reddit client that works
