### ISSUE TITLE
bug: (Youtube - PiP): Won't allow background play or PiP except for LIVE videos only

### ISSUE THREAD

**Issue by Chrisjan-png** [ReVanced/revanced-patches#4036]
### Bug description

Latest Revanced Patches to YT (youtube-revanced_v19.46.42-patches_v5.2.0) wont let background playback/PiP to work. 
Display over other apps is already allowed.
Picture-in-picture is also allowed as well.
The control panel banner in the notifications area won't also show up when playing a video on the app (both on regular and LIVE videos*).

*Heres the odd thing that I noticed, when you would play LIVE videos (e.g lofi hip hop radio beats to relax/study to) it does allow the PiP to work. But on shorts or regular videos it just simply wont allow to play in PiP or very rarely gives a message overlay over the video saying that "This can't be played in the background".
I cannot reproduce the "This can't be played in the background" as it comes very rarely- but it does happen.

The older revanced patched version (youtube-revanced_v19.16.39-patches_v4.17.0) before I updated worked fine out of the box btw.
Already tried spoofing app versions, video streams, clearing cache, uninstalling, repatching, reinstalling about 7 times already.
Patching v19.16.39 with default v5.2.0 patches didnt fixed it.
Repatching 19.46.42 with default v5.2.0 patches didnt either.

[video_2024-12-04_18-51-34.zip](https://github.com/user-attachments/files/18007146/video_2024-12-04_18-51-34.zip)
![Image](https://github.com/user-attachments/assets/c55750bf-c0d1-4462-a08a-a26dcf7e5f10)

### Error logs

```shell

```

### Additional context

_logs during patching_

- Device Info
ReVanced Manager: 1.23.2
Model: Infinix X6810
Android version: 11
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.google.android.youtube v19.46.42 (Suggested: 19.46.42)
Patches version: v5.2.0
Patches added: Change header [Header: premium*header]
Patches removed: Disable precise seeking gesture, Seekbar thumbnails, Swipe controls, Hide video action buttons, Navigation buttons, Hide player overlay buttons, Hide endscreen cards, Disable fullscreen ambient mode, Hide layout components, Hide info cards, Hide player flyout menu items, Disable rolling number animations, Hide seekbar, Hide Shorts components, Disable suggested video end screen, Hide timestamp, Custom player overlay opacity, Wide searchbar, Shorts autoplay, Spoof app version, Enable tablet layout, Theme, Alternative thumbnails, Bypass image region restrictions, Announcements, Remove background playback restrictions, Spoof device dimensions, Check watch history domain name resolution, Restore old video quality menu
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: false
Show universal patches: false
Patches source: revanced/revanced-patches

- Logs
Reading APK
Decoding app manifest
Loading patches
Deleting existing temporary files directory
Decoding resources
Initializing lookup maps
Executing patches
Applied 24 patches
Compiling modified resources
Aligning APK
Signing APK
Patched APK

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
![Image](https://github.com/user-attachments/assets/c41aa0c8-b991-4402-817d-08f8549d69d5)

**Comment by Chrisjan-png** [comment]
Oh that is mildly embarassing but anyways- Awesome!! thanks for the quick response!
