### ISSUE TITLE
bug: YTM Update pop-up

### ISSUE THREAD

**Issue by nightznero** [ReVanced/revanced-patches#4040]
### Bug description

I was updated my YTM from v7.03.52 with RVP v4.15.0 to (YTM same version) RVP v5.2.1 and now i got inside the app popup with information that my version is old and requires to update. Before since today there wasn't  any popup
![Image](https://github.com/user-attachments/assets/2d06a5f7-4c11-478c-b7e6-1675beb4ad02)

### Error logs

```shell

```

### Solution

1.Changing suggested version to newer
2.Disabling this popup
3.Support still older versions

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by nightznero** [comment]
App works fine(for now as tested) its just popup that app requires update but there is no need to update,its Cosmetic

**Comment by nightznero** [comment]
> Just update it, do repatch again with latest version available. Simple.

For some reason suggested version is lowe e.x `Permanente Shuffle` doesn't work. Im not going above suggested version,the reason why i post issue with it. If this version is not fine anymore it should be suggested or stopped supported ┐(-。-;)┌

**Comment by nightznero** [comment]
> [@nightznero](https://github.com/nightznero) `Permanent shuffle` was constrained to last working version caused it does not work with latest YTM available. You can ignore version checking in manager and use latest YTM available (for now 7.29.51) it will work.

Shuffle was working on RV v4.15.0.
I know how to change versions,i belive there are a lot newbies that needs advices and its nice n kind from You but i no need help here but on fixing issues inside the patch,as mentioned before i gave 3solutions to fix it. I think(maybe wrong) not only me uses older versions of YTM
To test,debug,fix i can use RVX that requires polish,but RV is solid project and i m using Stable/suggeted version to have the lowers bugs as possible and have free mind when using them

**Comment by oSumAtrIX** [comment]
This is not a bug
