### ISSUE TITLE
bug: YouTube builds large amounts of `volleyCache`. Possible `Automatic Downloads` issue in regions where the feature is unavailable

### ISSUE THREAD

**Issue by antoniu200** [ReVanced/revanced-patches#4053]
### Bug description

Hello,

As mentioned by the title, `/data/data/com.google.android.youtube/cache/glide_disk_cache/volleyCache` stores all thumbnails and images that the YouTube app loads. This can be tested by trying to chown `volleyCache` to root, instead of YouTube'd UID: the app then refuses to load any account images and video thumbnails.

Here's a sample file (suggest using a Hex Editor to analyse):
[-2067148910.zip](https://github.com/user-attachments/files/18038613/-2067148910.zip)

To **reproduce the bug**, just use the app for a few hours and then check the cache size, preferrably the actual `volleyCache` folder.

**The bug is not tied to ReVanced, nor its patches** (could my issue fall in the feature request category? idk). I have notified YouTube's team many times before over this, but the results can be seen.

Other users have also been complaining about YouTube building large caches for a while ([1](https://www.reddit.com/r/youtube/comments/1ao96be/tf_youtube_is_literally_taking_6gb_of_a_space/), [2](https://www.reddit.com/r/AndroidQuestions/comments/5pan1f/huge_amount_of_cached_data_youtube_app/), [3](https://www.reddit.com/r/Vanced/comments/o6alfh/other_psa_remember_to_clear_your_cache/), [4](https://www.reddit.com/r/AndroidQuestions/comments/zk5480/hidden_cache_of_the_youtube_app/)). Some users report this issue is due to **Automatic Downloads**, but I (and other people around me) do not have that option in the app's Settings ([Screenshot_20241206-154937](https://github.com/user-attachments/assets/157b9cf9-ad2b-40f5-b73e-9de299c02825)). YouTube also stores configuration files inside the cache, which means that, if **root-less** users were to clear the cache of YouTube, they lose their configuration (double tap to skip 5 / 10 / 15 secs, things the like), which makes the bug all the more annoying.

Is it possible that, even in regions where Automatic Downloads is "unavailable", this setting remains enabled by default, but the toggle for it simply does not appear in settings (hence cannot be turned off)?

How could I debug this further? I would like to try and build a patch for this (but probably won't be able to keep it up-to-date).

### Error logs

```shell
No error logs.
```

### Solution

The best **root-based** solution that I could come up with is to write some script that is executed at boot (Magisk schedulers are fairly complex and only work intermittently) and clears the aforementioned folder. However, YouTube builds that folder so aggressively that it would probably already contain 300 MB of files by the end of a day (of course, depending on app usage; but most people use YouTube more than I do, so the statement stands pretty well).

Best possible solution? Realistically, it depends what the actual root cause is.

If this is indeed a bug, make the app load the thumbnails, images, etc. without actually saving them to the internal storage first. Then stop writing to `glide_disk_cache/volleyCache`, possibly?

If this is a "feature" (Automatic Downloads on by default), make its toggle available at all times, and switch it to disabled by default in regions where it is unavailable.

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
I am not sure why this is a bug report. You mention yourself this is not related to ReVanced.
