### ISSUE TITLE
bug: youtube timed comments sometime not showing

### ISSUE THREAD

**Issue by Sub123945** [ReVanced/revanced-patches#4054]
### Bug description

![Image](https://github.com/user-attachments/assets/5b1b6284-93e5-46c8-8fdb-b15bf7ea2c27)
YouTube ReVanced timed comments sometimes not showing 
Patch version 5.2.2

### Error logs

```shell

```

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by Sub123945** [comment]
Yes I'm checked orginal app their is no issue

**Comment by oSumAtrIX** [comment]
Follow this and report back:

![Image](https://github.com/user-attachments/assets/701da3af-7eef-46c2-b501-4bb7b554510d)

**Comment by Sub123945** [comment]
I don't know how to do this.
