### ISSUE TITLE
bug: TikTok: SIM spoof patch triggers an ID verification that fails during login

### ISSUE THREAD

**Issue by 54m4d** [ReVanced/revanced-patches#4071]
### Bug description

Basically, When the SIM spoof patch is applied, TikTok prompts users to verify their identity after entering their password by sending a one-time code via email. While this verification step itself isn't an issue, the real problem arises when the code is never received by the user, making it impossible to log in.

The inability to receive the code is related to the inclusion of the SIM spoof patch, which appears to cause issues. When the patch is not included, the user can log in with just a password, without needing any verification.

There are no patching errors.

Galaxy device. Android 14

<details>
<summary>App Info</summary>
<img src=https://github.com/user-attachments/assets/b29e1dca-12d4-41ed-abbb-bd1bd8138d29>
</details>

### Error logs

```shell
N/A
```

### Solution

N/A

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
I just patched using SIM spoof and logged in. Include a video that shows how without the patch login works, but with fails, in one go.

**Comment by 54m4d** [comment]
@oSumAtrIX 

<details>
<summary>No SIM Spoof</summary>

[](https://github.com/user-attachments/assets/18859fdf-4e62-4172-a94f-2412b06c911a)
</details>


<details>
<summary>SIM Spoof</summary>

[](https://github.com/user-attachments/assets/074a7a61-83fc-429b-b16d-1dc0e63ff856)
</details>

Here, the 6-digit code at the end is never received, so it's impossible to log in. (I don't have any issues receiving emails)

I also noticed another issue which is not related to the SIM spoof patch, but I just want to side mention it, I'm not able to follow any account, the follow doesn't count at all, which makes patching this app not worth it. Not replicated in the stock app.

Are you aware of any possible fixes to these issues?

Thanks!

**Comment by 54m4d** [comment]
> Have you tried logging in using an install without the sim spoof spoof patch, then reinstalling with sim spoof? Your user data should keep you logged in, unless TikTok is logging out when detecting.

Yes, I have already tried that as a workaround and it works. But that should be the last resort.

> The [spoof sim setting](https://github.com/ReVanced/revanced-patches/blob/02edf0ca9e2ff7f4dd7df14d77d7521e36e18dc6/extensions/tiktok/src/main/java/app/revanced/extension/tiktok/settings/Settings.java#L22) probably should be changed to default off, and that might be enough to resolve this since it could be turned on after logging in.

That's a good point.

**Comment by 54m4d** [comment]
Maybe it's worth making the sim spoof setting come off as default. But actually the real issue is the fact that the user is unable to follow any accounts, even if all the patches worked perfectly, it's a huge drawback.

**Comment by 54m4d** [comment]
[728db1c](https://github.com/ReVanced/revanced-patches/pull/4084/commits/728db1cb7f1b5c2b4e3cd48485f212e07836cb6b) Tested and I can confirm that it resolves the issue.

An unrelated: When navigating to `Security & Permissions`, tapping on either `Security alerts` or `Manage devices` does not open anything, this is regardless of SIM spoof.

Unreproducible in stock app.
