### ISSUE TITLE
bug: (YouTube Music): Root does not work.

### ISSUE THREAD

**Issue by Theylanh** [ReVanced/revanced-patches#4077]
### Bug description

Youtube Music without GmsCore support has stopped working after the 5.3.0 update

### Error logs

```shell

```

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [ ] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Provide all requested informations properly in a new issue.
