### ISSUE TITLE
bug: watch on tv/link with tv code lost ability to enter code

### ISSUE THREAD

**Issue by kinghat** [ReVanced/revanced-patches#4082]
### Bug description

on youtube version `19.46.42-patches_v5.3.0`, using the default patches, you cannot enter any digits. it works fine on `19.43.41-patches_v5.0.0`. linking youtube app is smarttube on atv:

> Version: 1.23.2
Android Version: 15
Supported Archs: arm64-v8a, armeabi-v7a, armeabi

![Image](https://github.com/user-attachments/assets/41c7c536-c2bb-4e86-b73f-a7d8f1d972cf)

### Error logs

```shell

```

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
[Follow and report back ](https://i.imgur.com/wTvWZMC.png)

**Comment by kinghat** [comment]
> [Follow and report back ](https://i.imgur.com/wTvWZMC.png)

regular version of the app works fine. did half the patches then the other half and the same thing. since you cant patch with no patches i tried with only "custom branding" and "gmscore support" and still the same issue.

**Comment by oSumAtrIX** [comment]
Reopen the issue once the requested video is attac hed, using same version of the app you patch.

**Comment by kinghat** [comment]
> Did you try using unpatched `19.46.42`?

 unpactched `19.46.42` works fine.

> You can also try turning off the version checks in Manager and patching 19.47.53. It's not a recommended version yet but it patches and seems to work just fine.

ill try this.

**Comment by kinghat** [comment]
> You could continue to patch `19.43.41` with whatever is the latest patches, that also works.

> Try patching 19.43.41 with the latest patches. You'll need to uninstall the existing patched YT.

doing this works for `19.43.41` but the "open videos fullscreen" fails to patch.

**Comment by NBruderman** [comment]
I'm using YouTube as a system app with no GMSCore needed and no spoofing, and still have this bug. I can't enter the code.

**Comment by NBruderman** [comment]
> Anyone with this issue can turn off the version check requirement and try patching 19.49 or 19.50. Both patch correctly and work.

I patched with 19.50.40, and the issue still persists.
