### ISSUE TITLE
bug(YouTube - Playback speed): Default playback speed randomly resets to 1.0x

### ISSUE THREAD

**Issue by Billymaysere** [ReVanced/revanced-patches#4083]
### Bug description

Playback speed will change to 1x sometimes when pausing or double tap seeking even though I have it set to 2x.  

19.46.42 default patches

### Error logs

```shell

```

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
> Turn on debugging in Misc settings

This is missing

**Comment by oSumAtrIX** [comment]
Closing until the requested logs are provided
