### ISSUE TITLE
bug(YouTube - Spoof video streams): Age restricted videos fail to play

### ISSUE THREAD

**Issue by Sub123945** [ReVanced/revanced-patches#4089]
### Bug description

https://github.com/user-attachments/assets/2496cf8f-3dc8-4eb3-8a80-07fc7c66dba0
![Image](https://github.com/user-attachments/assets/69bf62bd-bcd8-48bb-aea6-8d142a6783bd)
All videos are properly playing but sensitive content not playing 

### Error logs

```shell

```

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
I am not able to reproduce. Logs would be needed. Enable Misc > First toggle and capture logs using logcat: `logcat | grep Spoof`

**Comment by oSumAtrIX** [comment]
For age restricted videos, only VR can be used. And VR is authorized as the logged in user. This should not fail and it doesn't in my case.

**Comment by oSumAtrIX** [comment]
Is the VR request authorized?

**Comment by oSumAtrIX** [comment]
That is quite odd. For unspooled requests I don't think hl is removed.

**Comment by Karthik-Subbu** [comment]
I am able to play the video with 19.16.39. However playback fails with 19.47.53.

**Comment by Karthik-Subbu** [comment]
> I can reproduce the issue on 19.16.39 with the latest patches.
> 
> @Karthik-Subbu You must be using old patches with 19.16.39 (did you patch yourself using the Manager at ReVanced.app?)
> 

Yeah, patched using ReVanced manager 1.23.2 download from official GitHub repository. Patch version 5.3.0. No issues in video playback for  

https://youtu.be/wHDh_ruJ8Ug

**Comment by Karthik-Subbu** [comment]
@LisoUseInAIKyrios: client name field "Android VR" is struck down while releasing 5.3.0 dev 3. Is this a desired change? FYI: I have another phone which runs 19.47.53 but patch version is 5.2.3. No playback issues.

**Comment by Karthik-Subbu** [comment]
> What do you mean struck down?

> What do you mean struck down?

Never mind. That change is not related to this issue.  I misunderstood. I am still surprised why the playback didn't fail in 19.16.39 for me.
