### ISSUE TITLE
bug: YouTube ReVanced crashes when booting

### ISSUE THREAD

**Issue by Bastian2024** [ReVanced/revanced-patches#4100]
### Bug description

When i start the app patched with ReVanced on my Samsung Galaxy a05, the app crashes when boots, even with the default patches, crashes, i need help to work propelly

https://github.com/user-attachments/assets/d5a4bc8a-20df-4a75-9818-54749d218a1d

I have used the original patches as for now

### Error logs

```shell

```

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Send the crashlog (using logcat: `logcat | grep AndroidRuntime`) and the patch log from ReVanced Manager.

**Comment by Bastian2024** [comment]
> [@Bastian2024](https://github.com/Bastian2024) Did you installed correct ReVanced MicroG GmsCore here https://github.com/ReVanced/GmsCore/releases ?

Yes, i have downloaded the Default one instead of the Huawei one

**Comment by Bastian2024** [comment]
> > > [@Bastian2024](https://github.com/Bastian2024) Did you installed correct ReVanced MicroG GmsCore here https://github.com/ReVanced/GmsCore/releases ?
> > 
> > 
> > Yes, i have downloaded the Default one instead of the Huawei one
> 
> Oohh...then do what Osum said above

Where?

**Comment by Bastian2024** [comment]
> > Send the crashlog (using logcat: `logcat | grep AndroidRuntime`) and the patch log from ReVanced Manager.
> 
> Above before me [#4100 (comment)](https://github.com/ReVanced/revanced-patches/issues/4100#issuecomment-2533082116)

But doesn't work on Termux

**Comment by oSumAtrIX** [comment]
For support move to one of the links at https://revanced.app. Reopen the issue once the requested info is provided.

**Comment by Bastian2024** [comment]
@oSumAtrIX how i can do it

**Comment by Bastian2024** [comment]
@oSumAtrIX why aren't you responding??

**Comment by oSumAtrIX** [comment]
I already told you above to move for support. This is not a place for support.
