### ISSUE TITLE
bug(YouTube Music): `Bypass certificate checks` patch fails on YT Music v7.31.51

### ISSUE THREAD

**Issue by Rajeshsahoo12** [ReVanced/revanced-patches#4102]
### Bug description

My machine is running with WINDOWS 10. I have tried to patch YT MUSIC v7.31.51 apk with below mentioned command. Have used exclusively disabling of `"Hide category bar"`

I am using latest cli version `revanced-cli-5.0.0-all.jar` & `patches-5.3.0.rvp`

`java -Xmx1024M -jar revanced-cli-5.0.0-all.jar patch -p patches-5.3.0.rvp YouTubeMusic7.31.51.apk -o YouTubeMusicRevanced7.31.51.apk -e "Hide category bar"`

But encountered with terminal log saying `Bypass certificate checks` cannot be applied. And remaining patches gets applied. The base apk gets patched.

Where as on `https://revanced.app/patches?pkg=com.google.android.apps.youtube.music` for this patch `Bypass certificate checks` is says to have any version of YT MUSIC.

![Image](https://github.com/user-attachments/assets/3a2b08f7-da65-4fd7-a0dd-b2fd57d5e9f8)

### Error logs

```shell
https://pastebin.com/BNdhxPvM
```

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by Rajeshsahoo12** [comment]
> ### Bug description
> My machine is running with WINDOWS 10. I have tried to patch YT MUSIC v7.31.51 apk with below mentioned command. Have used exclusively disabling of `"Hide category bar"`
> 
> I am using latest cli version `revanced-cli-5.0.0-all.jar` & `patches-5.3.0.rvp`
> 
> `java -Xmx1024M -jar revanced-cli-5.0.0-all.jar patch -p patches-5.3.0.rvp YouTubeMusic7.31.51.apk -o YouTubeMusicRevanced7.31.51.apk -e "Hide category bar"`
> 
> But encountered with terminal log saying `Bypass certificate checks` cannot be applied. And remaining patches gets applied. The base apk gets patched.
> 
> Where as on `https://revanced.app/patches?pkg=com.google.android.apps.youtube.music` for this patch `Bypass certificate checks` is says to have any version of YT MUSIC.
> 
> ![Image](https://github.com/user-attachments/assets/3a2b08f7-da65-4fd7-a0dd-b2fd57d5e9f8)
> 
> ### Error logs
> https://pastebin.com/BNdhxPvM
> ### Solution
> _No response_
> 
> ### Additional context
> _No response_
> 
> ### Acknowledgements
> * [x]  I have checked all open and closed bug reports and this is not a duplicate.[x]  I have chosen an appropriate title.[x]  All requested information has been provided properly.

With same cli version `revanced-cli-5.0.0-all.jar` & patches version `patches-5.3.0.rvp` YT MUSIC v7.29.51 works with `Bypass certificate checks` with no issues.

**Comment by Rajeshsahoo12** [comment]
> Can set that patch to recommend version v7.29.51 and leave the rest unrestricted.
> 
> That'll also set an overall recommended version which is good because otherwise every month or two this same situation happens again (latest yt music fails to patch)

True that is too fine. But on `YT MUSIC v7.29.51` I have observed that when I click on track to play, it takes very much time to stream the track.

And I have checked my internet connection, it is working fine. I have ISP speeds upto `600 Mbps`

And the same behavior for track loading to play is with `YT MUSIC v7.31.51` without using patch `Bypass certificate checks`

For `YT MUSIC v7.29.51` I used only `-e "Hide category bar"` & with `YT MUSIC v7.31.51` I used only `-e "Hide category bar"` `-d "Bypass certificate checks"`

And in both version, tracks play fine & next track too gets played in the queue. Only the load behavior is strange. 

Will be trying any recent version lower than `YT MUSIC v7.29.51`


Thanks

**Comment by Rajeshsahoo12** [comment]
> > ...it takes very much time to stream the track.
> 
> Might caused by `Spoof video stream` patch, disable it and try repatch then check.

Have tried with both version of `YT MUSIC v7.29.52` & `YT MUSIC v7.29.51` with disabling `Spoof video streams` patch.

Still the same behaviour.

**Comment by Rajeshsahoo12** [comment]
> > ...it takes very much time to stream the track.
> 
> Might caused by `Spoof video stream` patch, disable it and try repatch then check.

Now I have patch with patches version `patches-5.2.3.rvp` & cli version `revanced-cli-5.0.0-all.jar` for `YT MUSIC v7.29.52` with below cmd.

`java -Xmx1024M -jar revanced-cli-5.0.0-all.jar patch -p patches-5.2.3.rvp YouTubeMusic7.29.52.apk -o YouTubeMusicRevanced7.29.52.apk -e "Hide category bar"`

And voila problem is fixed. So, I think the patch version `patches-5.3.0.rvp` is creating issue.

**Comment by Rajeshsahoo12** [comment]
> > ...it takes very much time to stream the track.
> 
> Might caused by `Spoof video stream` patch, disable it and try repatch then check.

Now I have patch with patches version `patches-5.2.3.rvp` & cli version `revanced-cli-5.0.0-all.jar` for `YT MUSIC v7.31.51` with below cmd.


`java -Xmx1024M -jar revanced-cli-5.0.0-all.jar patch -p patches-5.2.3.rvp YouTubeMusic7.31.51.apk -o YouTubeMusicRevanced7.31.51.apk -e "Hide category bar" -d "Bypass certificate checks"`

And this version too working fine with no issues of track loading for long time.

So, final tested version from my end of `YT MUSIC` `v7.31.51` & `v7.29.52` with below cmd using `patches-5.2.3.rvp` patches & `revanced-cli-5.0.0-all.jar` cli

Both works fine. 

`YT MUSIC v7.29.52` = `java -Xmx1024M -jar revanced-cli-5.0.0-all.jar patch -p patches-5.2.3.rvp YouTubeMusic7.29.52.apk -o YouTubeMusicRevanced7.29.52.apk -e "Hide category bar"`

`YT MUSIC v7.31.51` = `java -Xmx1024M -jar revanced-cli-5.0.0-all.jar patch -p patches-5.2.3.rvp YouTubeMusic7.31.51.apk -o YouTubeMusicRevanced7.31.51.apk -e "Hide category bar" -d "Bypass certificate checks"`



Thanks

**Comment by Rajeshsahoo12** [comment]
> [@Rajeshsahoo12](https://github.com/Rajeshsahoo12) try patching 7.29.52 with the latest dev release.
> 
> Patches 5.3 changed a spoof parameter (the language code), and 5.4 changes YT Music to use the prior logic (no language code).

Sure dev. Let me dwnlod the latest patches release. And update the results.


Thanks

**Comment by Rajeshsahoo12** [comment]
> [@Rajeshsahoo12](https://github.com/Rajeshsahoo12) try patching 7.29.52 with the latest dev release.
> 
> Patches 5.3 changed a spoof parameter (the language code), and 5.4 changes YT Music to use the prior logic (no language code).

As said, I have patched the version of `YT MUSIC v7.29.52` using patches version `patches-5.4.0-dev.8.rvp`. Application patching is fine. No errors on terminal log.

Terminal log = https://pastebin.com/1FEGcTiT

Cmd used for patching = `java -Xmx1024M -jar revanced-cli-5.0.0-all.jar patch -p patches-5.4.0-dev.8.rvp YouTubeMusic7.29.52.apk -o YouTubeMusicRevanced[DEV]7.29.52.apk`


But the behavior for playing track is same. It takes time to load very much.


Thanks.

**Comment by Rajeshsahoo12** [comment]
> It makes no sense why YT Music would work better with 5.2.3 and worse with 5.4. For YT Music there effectively is no difference between those two versions.
> 
> Some users say YT Music acts up at times and acts ok other times.

Ohhhhh. If there is not variation in patches. Then it is better to patch the YT MUSIC version `7.31.51` & `7.29.52`. Using below cmds based on patch version `patches-5.2.3.rvp` as per below cmds.

`YT MUSIC v7.29.52` = `java -Xmx1024M -jar revanced-cli-5.0.0-all.jar patch -p patches-5.2.3.rvp YouTubeMusic7.29.52.apk -o YouTubeMusicRevanced7.29.52.apk -e "Hide category bar"`

`YT MUSIC v7.31.51` = `java -Xmx1024M -jar revanced-cli-5.0.0-all.jar patch -p patches-5.2.3.rvp YouTubeMusic7.31.51.apk -o YouTubeMusicRevanced7.31.51.apk -e "Hide category bar" -d "Bypass certificate checks"`


So, ryt now the version `7.29.52` is target version which can be used. And no issues in track steaming. And all the patches are working.


Thanks

**Comment by oSumAtrIX** [comment]
@LisoUseInAIKyrios from what I saw, playback failed for some in specific networks. It is likely an issue with A/B tests. Further investigation such as logs are needed

**Comment by Rajeshsahoo12** [comment]
> [@LisoUseInAIKyrios](https://github.com/LisoUseInAIKyrios) from what I saw, playback failed for some in specific networks. It is likely an issue with A/B tests. Further investigation such as logs are needed

@oSumAtrIX If u can guide, I can provide the log. When patching application on PC.

**Comment by oSumAtrIX** [comment]
Logs can be captured via logcat. CTRL+F the issues for logcat in this repo for instructions

**Comment by Karthik-Subbu** [comment]
But, do patches for yt music support debug logging yet?

**Comment by feralfenrir** [comment]
> Can set that patch to recommend version v7.29.51 and leave the rest unrestricted.
> 
> That'll also set an overall recommended version which is good because otherwise every month or two this same situation happens again (latest yt music fails to patch)

I was able to successfully patch v7.29.52 too using ReVanced Manager on a Pixel 7 Pro.

It's just the latest v7.31.51 that throws the error for Bypass Certificate Check patch.
