### ISSUE TITLE
feat(YouTube): Hide YouTube featured section

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [ReVanced/revanced-patches#4111]
### Feature description

YouTube has this random recommendation that pop ups in home feed at times. Adding `brand_video_singleton.eml` should probably do it, as the section don't appear very often.

![Image](https://github.com/user-attachments/assets/69370ff5-91c3-458d-8644-f1b310eedf1f)

### Motivation

It's either some content from YouTube's end or some promotion based content, also from YouTube. So it's better off hidden.

### Acknowledgements

- [x] I have checked all open and closed feature requests and this is not a duplicate
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by ILoveOpenSourceApplications** [comment]
Assumption made based on this.
```kotlin
12-13 00:58:19.149 16921 16921 D revanced: LithoFilterPatch: Searching ID: null Path: brand_video_singleton.eml|a2338bd59f2748a2|CellType|brand_promo_base.eml|c30e69acb8a6b839|ContainerType| BufferStrings: brand-promo-base-container-transition❙flexible_button.eml|24e539e5d128fe35❙brand_promo_base_button_transition_key❙button.eml|713fd10bcb423d23❙video_lockup_brand_video_singleton❙video_lockup.eml|9a58ef0afe85e2e4❙header_layout.eml|d7f521d4105fa2d2❙brand_promo.view❙Featured - Hit Pause. Beware of incomplete facts, understand the full information. - Before you believe any information, know a little more about it - Hit Pause. Beware of incomplete facts, understand the full information. ❙ 32 seconds ❙ Go to channel ❙ YouTube India Spotlight - 821K views - 2 months ago ❙ play video❙$67642dc8-0000-2371-a1ac-582429c745e0
```

**Comment by oSumAtrIX** [comment]
Looks about right

**Comment by ILoveOpenSourceApplications** [comment]
I think this can be added simply to the ads filter and perhaps not a dedicated patch?

**Comment by ILoveOpenSourceApplications** [comment]
If we are going with a dedicated toggle then `Hide featured recommendation` maybe? But is that needed? Why not add it to `Hide general ads` and be done with it?

**Comment by oSumAtrIX** [comment]
I think it makes sense to combine all ad toggles into one video and one other ads toggle. You wouldn't need anything in between

**Comment by ILoveOpenSourceApplications** [comment]
> Maybe `Hide featured promotions`?

I'm fine with this.

> I think it makes sense to combine all ad toggles into one video and one other ads toggle. 

I'm confused? So, two toggles, one hiding video ads and the other hiding general UI ads?
