### ISSUE TITLE
feat: original audio for youtube

### ISSUE THREAD

**Issue by yonggamer** [ReVanced/revanced-patches#4112]
### Feature description

i want a option for original
![Image](https://github.com/user-attachments/assets/aa8d4f82-6da4-4e48-a241-c473a90bd348)

### Motivation

original sound better

### Acknowledgements

- [x] I have checked all open and closed feature requests and this is not a duplicate
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
App language is the original/default behaviour.
