### ISSUE TITLE
bug: yt music spoof video patch breaks app

### ISSUE THREAD

**Issue by smtgpm** [ReVanced/revanced-patches#4120]
### Bug description

Yt music 7.29.52 armv8
Android 12
Root

So whenever I patch YT music with the spoof video stream patch, the patch succeeds but the app is broken. I have tried both Mount and regular install, and in both cases once the app is patched, it shuts down as soon as I try to open it.
If I unselect that patch, everything works well

### Error logs

```shell

```

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Send crashlogs using logcat by filtering for "AndroidRuntime". Check online how to use logcat

**Comment by 306bobby-android** [comment]
Not author but here's crash log

https://paste.crdroid.net/4VfU76

**Comment by oSumAtrIX** [comment]
Make storage space and repatch.

**Comment by smtgpm** [comment]
I do not use gmscore support:

Selected app
YouTube Music 7.29.52
com.google.android.apps.youtube.music

Selected patches (8)

    Bypass certificate checks
    Enable exclusive audio playback
    Hide 'Get Music Premium' label
    Hide category bar
    Hide music video ads
    Remove background playback restrictions
    Remove upgrade button
    Spoof video streams

And it's when using the spoof video patch that yt music fails to load.

I have been running logcat on temux and fetching only AndroidRuntime but nothing shows. Not sure if I'm doing something wrong, here is a screencam
https://github.com/user-attachments/assets/76830e43-8368-440b-824e-cd374e5ee983

**Comment by smtgpm** [comment]
Aah OK I did now know that, good to know. Sorry for my mistake then

**Comment by 306bobby-android** [comment]
> Is playback failing with root install and `Spoof video stream` is _not_ included?
> 
> If so there is no bug here. Spoof stream is for non root install.

Works fine with root mount and no inclusion


Also didn't realize this was for non-root.
