### ISSUE TITLE
bug: YouTube: Default miniplayer is minimal type in place of default type

### ISSUE THREAD

**Issue by Karthik-Subbu** [ReVanced/revanced-patches#4121]
### Bug description

YouTube version 19.46.42, patch version 5.4.0

As the default mini player design in stock youtube recent versions is now similar to pip, the same player is expected in patched YouTube also. However after first launch of the app after patching the mini player type is found to be minimal type (a small docked miniplayer) which is not expected because setting says default but observed player is minimal. When user changes mini player type, by tapping the same default option again , now player type changes similar to pip. 

Steps to reproduce the issue:

If miniplayer settings is not changed after patching, you can observe minimal mini player appears as default 

If user has already changed the setting, clear the app data and observe the result.

### Error logs

```shell
Not applicable.
```

### Solution

The default mini player type before user changes the setting has to be corrected according to youtube version that is being patched.

For e.g 19.16.39 docked style

Latest version: pip style

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
The new YouTube Miniplayer is buggy and users were complaining to us about it.
