### ISSUE TITLE
bug:RVX Music isn't working as expected (the songs doesn't play)

### ISSUE THREAD

**Issue by nitinkhatri4** [ReVanced/revanced-patches#4126]
### Bug description

RVX music and YouTube music revanced from andeaa both are not working as expected.
Tried restarting the device, installing it again but none worked. For now YouTube music (the third one with black logo) is working but it's not as handy as RVX music. In RVX music, it almost takes a minute or two to play a song and if skipped to a timestamp then it stops right there, takes upto 2-3 minute more and continue playing from that timestamp.

Another thing which bothers is that as one starts the RVX music and tap on a song/music, the pause/play button turn into reload icon (screenshot attached).[![Image](https://github.com/user-attachments/assets/d0e42a7f-c7a0-4d0e-b003-3311dc65a2e1)

### Error logs

```shell

```

### Solution

Ain't there no solution apart from playing the songs.

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Unofficial patches are not supported

**Comment by nitinkhatri4** [comment]
bro i downloaded it from revanced.net apk. how's that unofficial.

**Comment by oSumAtrIX** [comment]
You fell for counterfeit. revanced.app
