### ISSUE TITLE
feat: Google Dialer: Pixel device features

### ISSUE THREAD

**Issue by sumitpai22** [ReVanced/revanced-patches#4128]
### Feature description

- I recently saw some people using Call Screening for their calls. After some research, I found that this is a feature of Stock Google Dialer of Pixel device. 
- I also saw people using Visual Voicemail and Silent Call Recording every calls. 

- These features are available in USA for Pixel devices. 
- If there would be a patch, we can spoof this and use it in non pixel and unsupported countries. 

~ Main focus - Call Screening to block unwanted calls. 
~ Also, I saw an app which needs root but can make these features work... 
(reffer screenshot) 
And here's the link for the GitHub: [https://github.com/jacopotediosi/GAppsMod?tab=readme-ov-file](url)![Image](https://github.com/user-attachments/assets/cb255115-11f5-427c-b09d-850aedc3251e)

### Motivation

This feature should be there to avoid unnecessary calls and disturbance during work or other activities. 
This will not only boost productivity but also be a fun new feature for non pixel devices. 

### Acknowledgements

- [x] I have checked all open and closed feature requests and this is not a duplicate
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by validcube** [comment]
Spoofing device to Pixel could work but this feature is impossible without setting Google Dialer as a system app, as it relies on `CAPTURE_AUDIO_OUTPUT` permission—which isn't available to any application except the system—to capture incoming audio.

So Google Dialer must be pre-installed before you can start recording calls.

**Comment by oSumAtrIX** [comment]
This would in addition only work on mount installs at max because there is PairIP protection in the app
