### ISSUE TITLE
bug: YouTube video zoom feature not working

### ISSUE THREAD

**Issue by Sub123945** [ReVanced/revanced-patches#4129]
YouTube video zoom not working 
![Image](https://github.com/user-attachments/assets/32e5854d-5d39-482b-8387-5e47b1b3d473)
### Bug description

https://github.com/user-attachments/assets/dcc71698-8961-4ba2-83f8-103aef3b0bf7

### Error logs

```shell

```

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
[Follow and report back ](https://i.imgur.com/wTvWZMC.png)

**Comment by Karthik-Subbu** [comment]
For me  pinch to  Zoom works properly.

**Comment by Sub123945** [comment]
Now it's working
