### ISSUE TITLE
bug: Videos in the YouTube subscription tab play automatically when you scroll through them and pause for a second in the video.

### ISSUE THREAD

**Issue by MinionAttack** [ReVanced/revanced-patches#4145]
### Bug description

In the Home tab you can scroll through the videos, and even if you stop on it, it does not start automatically. 

However, for several versions now, the videos in the subscriptions tab, autoplay the second you stop on it while scrolling.

### Error logs

```shell
The application is patched without errors.
```

### Solution

Apply the same behaviour as the Home tab, where even if you stop on the video while scrolling it does not start automatically.

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Find the and report back:

![cause](https://github.com/user-attachments/assets/3d5b9064-74c9-4767-9a53-37f143cf9dc9)

**Comment by MinionAttack** [comment]
Ok, it seems that the setting "Playback in feeds" which had the options "Always On", "Wifi-Only", "Off" has been removed and that may explain the behaviuor:

[https://www.reddit.com/r/youtube/comments/1gfk8wr/playback_in_feed_setting_gone/?sort=new](https://www.reddit.com/r/youtube/comments/1gfk8wr/playback_in_feed_setting_gone/?sort=new)

[https://www.reddit.com/r/youtube/comments/1gcjouu/are_you_kidding_me/?sort=new](https://www.reddit.com/r/youtube/comments/1gcjouu/are_you_kidding_me/?sort=new)

But I have found a workaround: "General layout" > "Enable table layout" solves it (for now)!
