### ISSUE TITLE
feat(Sync for Reddit): Open YouTube links in YouTube Revanced

### ISSUE THREAD

**Issue by rifqire** [ReVanced/revanced-patches#4149]
### Feature description

Open YouTube links ([youtube.com](youtube.com) and [youtu.be](youtu.be)) in YouTube Revanced: `app.revanced.android.youtube` or maybe other package name if the user used the change package name patch other than the default.

### Motivation

I wanted to open YouTube links that are usually found in the comments, as well as the post itself, but it asks me to download the official YouTube app. I have to type the title manually or open in my browser which is kinda annoying.

### Examples:

![Image](https://github.com/user-attachments/assets/180bb917-069a-469e-975a-470934588e95)
![Image](https://github.com/user-attachments/assets/b25a8eca-b29a-45e8-b0b5-854a6da1471d)
![Image](https://github.com/user-attachments/assets/890f3da0-483b-4f8a-92cc-fd9afaf09a5c)

### Warning to get the official YouTube app:

![Image](https://github.com/user-attachments/assets/5dabb285-6fea-45a8-995f-dd19575fd4c6)

### Acknowledgements

- [x] I have checked all open and closed feature requests and this is not a duplicate
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Links are handled by the OS and as such are configurable for every app in the app settings.

**Comment by rifqire** [comment]
I already changed the default links for both apps but Sync still asks me to download the official YouTube app. Note that Sync's options are Reddit domains, as well as Gfycat and Imgur (no YouTube).
My device is Xiaomi 13T, Android 14, HyperOS 1.0.8.0.

![Image](https://github.com/user-attachments/assets/196f499e-0597-4167-ab90-b66e4bd8e972)
![Image](https://github.com/user-attachments/assets/be951916-708b-4ac8-8a92-fb87e94b0475)
