### ISSUE TITLE
bug: <Not able to minimise video in app..>

### ISSUE THREAD

**Issue by Kalpataru6** [revanced/revanced-patches#416]
### Type

Other

### Bug description

After watching video more than 2-3hour the bug appears.. You can't minimise the video in the app(not talking about pip).. If i minimise by tapping phone's back button (or swiping back) i can't swipe to maximize it either.. I specifically excluded swipe-controls patch disable-fullscreen-panels.. 

### Steps to reproduce

Watch video for more than 2-3 hour and try to minimise video in the app

### Relevant log output

```shell
I don't have logs
```

### Screenshots or videos

https://media.discordapp.net/attachments/952946952348270626/1014622442410496102/Abc.mp4

**Comment by oSumAtrIX** [comment]
Please exclude patches until the error is gone and try to find the patch causing this bug, report back which one it is.
