### ISSUE TITLE
feat:

### ISSUE THREAD

**Issue by bkkappvip** [ReVanced/revanced-patches#4174]
### Feature description

I want to be able to change the name on the settings page to my own.![Image](https://github.com/user-attachments/assets/e256b2bf-9c4d-4aa4-9496-b5234d35fb33)

### Motivation

You will be able to create your own brand.

### Acknowledgements

- [x] I have checked all open and closed feature requests and this is not a duplicate
- [ ] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by YT-Advanced** [comment]
> You will be able to create your own brand.

U want to provide Revanced prebuilt apk under your brand ?
