### ISSUE TITLE
bug: Player - Hide channel bar setting also hides channel bar in shorts

### ISSUE THREAD

**Issue by sdsucks** [ReVanced/revanced-patches#4203]
### Bug description

there are two [Hide channel bar] options,
one in [Player], the other in [Shorts - Shorts player]

if i enable [Player - Hide channel bar](ie. subscriptions carousel), it also hides the channel bar(channel name) in shorts player even if [Shorts - Shorts player - Hide channel bar] option is turned off

### Error logs

```shell

```

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by ILoveOpenSourceApplications** [comment]
Resolved by #4205?
