### ISSUE TITLE
feat (YouTube): Show the total number of downloads in the "Downloads" Section of "You" tab

### ISSUE THREAD

**Issue by UMA1R-01** [ReVanced/revanced-patches#4204]
### Feature description

I’d like to request a feature for the YouTube patch to display the total number of downloaded videos in the "Downloads" section in the "You" tab in the app. This feature was officially available in YouTube just a few versions ago, providing users with a quick overview of their downloads. However, it was removed in one of the recent releases.
The absence of this feature makes it difficult to keep track of the total number of downloaded videos at a glance.

### Motivation

The ability to see the total number of downloaded videos at a glance simplifies content management, especially for those with large offline libraries. Without this feature, users are left to manually count or open a downloaded video to keep track of their downloads, which is inconvenient.

### Acknowledgements

- [x] I have checked all open and closed feature requests and this is not a duplicate
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
I don't see how the count "simplifies content management". The motivation is insufficient.
