### ISSUE TITLE
feat: Spoof app version to get og #FF0000 YouTube red

### ISSUE THREAD

**Issue by MrHuaweiFan** [ReVanced/revanced-patches#4208]
### Feature description

The Spoof app version patch currently restores the old shorts icons (that option is very good, please don't remove it), but it would be also good an option to restore the old YouTube red color (now it's more magenta) for the Seekbar, icon, header, etc..

Preferably being able to select only those two, maintaining the other new ui and icon changes introduced in the recent updates.
Thanks

### Motivation

I like the new YouTube ui, except for the new miniplayer and shorts icons (both can be reverted) and the new #FF0033 magenta color, that I think is very annoying (I've already used custom icon, header and Seekbar, but some parts remain being magenta, like the livestream banner (see photo)
![Image](https://github.com/user-attachments/assets/1530eece-a6c4-4982-a9de-4b5f37ca3a38)

### Acknowledgements

- [x] I have checked all open and closed feature requests and this is not a duplicate
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
The color difference is nearly invisible to the eye and patching it is basically unreasonable.

**Comment by MrHuaweiFan** [comment]
:/
