### ISSUE TITLE
feat: Add a dark mode to TikTok

### ISSUE THREAD

**Issue by Gontier-Julien** [revanced/revanced-patches#421]
### Type

Cosmetic

### Issue

TikTok on Android doesn't have a dark mode.

### Feature

Add a toggle to make TikTok use a dark mode in the settings.

### Motivation

There is a long history of users using TikTok wanting to have a dark mode, but TikTok seem lazy to impliment a dark mode on Android, even tho they have one on Iphone.

**Comment by oSumAtrIX** [comment]
Wrong place to suggest patches. Use the discussions.

**Comment by Gontier-Julien** [comment]
My bad didn't know it ^^'
