### ISSUE TITLE
feat: Make TikTok save it video to it own folder

### ISSUE THREAD

**Issue by Gontier-Julien** [revanced/revanced-patches#422]
### Type

Functionality

### Issue

TikTok when downloading videos, save them in the Camera folder.
This poses multiple issues and annoyance.

### Feature

Make a patch that change TikTok saving location from the Camera folder to it own folder.

ex: Save them to `Movies/TikTok` instead of `DCIM/Camera`

### Motivation

TikTok saving it videos to the Camera folder is annoying, clutter the Camera folder of TikTok videos and make backup localy and/or to the cloud difficult by cluttering the Camera folder.

**Comment by oSumAtrIX** [comment]
Please create patch suggestions in the discussions.
