### ISSUE TITLE
YouTube bug: seekbar view not working

### ISSUE THREAD

**Issue by Sub123945** [ReVanced/revanced-patches#4241]
### Bug description

YouTube videos preview from seekbar is not working.
Patches 5.8.0![Image](https://github.com/user-attachments/assets/55c6b2a6-d22c-49a3-aa50-99c3c5dcd009)
ReVanced-https://github.com/user-attachments/assets/c78ea43d-17c1-471f-886d-e1f957b5a34f
Orginal youtube-https://github.com/user-attachments/assets/6df4bfec-5d90-443f-b240-f8f4c3d142f9

### Error logs

```shell

```

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Wait ~100ms before seeking. This is likely caused by the video still loading

**Comment by Sub123945** [comment]
> Wait ~100ms before seeking. This is likely caused by the video still loading

No video is fully loaded

**Comment by Sub123945** [comment]
This video is full loaded but still preview not working https://github.com/user-attachments/assets/a86318e0-b957-4fbb-b25e-01b8f228cad9

**Comment by oSumAtrIX** [comment]
Did you change any settings

**Comment by Sub123945** [comment]
> Did you change any settings

No

**Comment by Sub123945** [comment]
> Did you change any settings

![Image](https://github.com/user-attachments/assets/36983bd5-053a-446d-b202-f8bf13595d7c)

**Comment by oSumAtrIX** [comment]
Export your settings under Misc> Export

**Comment by Sub123945** [comment]
> Export your settings under Misc> Export

"bypass_image_region_restrictions": true,
"copy_video_url_timestamp": false,
"custom_playback_speeds": "0.25\n0.5\n0.75\n1.0\n1.25\n1.5\n1.75\n2.0",
"disable_fullscreen_ambient_mode": false,
"disable_precise_seeking_gesture": false,
"disable_suggested_video_end_screen": true,
"disable_zoom_haptics": false,
"gradient_loading_screen": true,
"hide_autoplay_button": false,
"hide_cast_button": false,
"hide_chapters_section": false,
"hide_chips_shelf": false,
"hide_clip_button": false,
"hide_comments_create_a_short_button": false,
"hide_comments_timestamp_and_emoji_buttons": false,
"hide_create_button": false,
"hide_emergency_box": false,
"hide_endscreen_cards": true,
"hide_expandable_chip": false,
"hide_feed_survey": false,
"hide_floating_microphone_button": false,
"hide_image_shelf": false,
"hide_latest_posts_ads": false,
"hide_mix_playlists": false,
"hide_movies_section": false,
"hide_notify_me_button": false,
"hide_paid_promotion_label": false,
"hide_playables": false,
"hide_player_flyout_help": false,
"hide_player_flyout_more_info": false,
"hide_player_flyout_watch_in_vr": false,
"hide_podcast_section": false,
"hide_remix_button": false,
"hide_self_sponsor_ads": false,
"hide_shorts_button": false,
"hide_shorts_history": true,
"hide_shorts_home": true,
"hide_shorts_search": true,
"hide_shorts_subscriptions": true,
"hide_show_more_button": false,
"hide_timed_reactions": false,
"hide_transcript_section": false,
"miniplayer_hide_subtext": true,
"miniplayer_type": "modern_1",
"playback_speed_default": 1,
"restore_old_video_quality_menu": false,
"seekbar_thumbnails_high_quality": true,
"spoof_video_streams_client_type": "ios_unplugged",
"swipe_change_video": true,
"switch_create_with_notifications_button": false,
"video_quality_default_mobile": 1080,
"video_quality_default_wifi": 1080,
"ryd_toast_on_connection_error": false,
"sb_auto_hide_skip_button": false,
"sb_filler": "seekbar-only",
"sb_highlight": "seekbar-only",
"sb_interaction": "skip",
"sb_intro": "skip",
"sb_local_time_saved_milliseconds": 244042,
"sb_local_time_saved_number_segments": 16,
"sb_music_offtopic": "skip",
"sb_outro": "skip",
"sb_preview": "skip",
"sb_selfpromo": "skip",
"sb_sponsor": "skip",
"sb_toast_on_connection_error": false,
"sb_toast_on_skip": false,
"sb_video_length_without_segments": false

**Comment by oSumAtrIX** [comment]
> You have high quality thumbnails enabled. They can be very slow to load.
> 
> Turn the setting off.

The thumbnails don't seem to load at all with the switch on

**Comment by Sub123945** [comment]
> You have high quality thumbnails enabled. They can be very slow to load.
> 
> Turn the setting off.

Oh thanks now preview is working
