### ISSUE TITLE
bug: Flickering app

### ISSUE THREAD

**Issue by Cheesy1576** [ReVanced/revanced-patches#4244]
### Bug description

After applying patch 5.8.0 to YouTube and changing the language of ReVanced specific text the app stars flickering constantly *EPILEPSY WARNING* https://github.com/user-attachments/assets/bd728652-8f49-4843-ab77-3dd51d8cb02a

### Error logs

```shell

```

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [ ] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
[Follow and report back in a new issue](https://i.imgur.com/wTvWZMC.png)
