### ISSUE TITLE
bug: <auto rotation on app bricked after use of developer "sensor off" tool >

### ISSUE THREAD

**Issue by Throwingthethum** [revanced/revanced-patches#425]
### Type

Other

### Bug description

I found this bug when I use the sensor off shortcut that can be found in developer options 

The bug is that  when I open the app with sensor on after that even when I trun off "sensor off" setting the autorotation get fucked 

### Steps to reproduce

Using: device A71 running Android 12
Using revanced version: 17.33.42

First: I opened the app with (sensor off) on then I opened a video on full screen.

Second i closed the revanced app then turned off (sensors off) quick till then I reopened the revanced app then played a video in full screen  landscape, after that the auto rotation (full screen videos) for the app did not rotate  when I rotate my phone.

### Relevant log output

```shell
Non
```

### Solution

I have found 1 solution that works but it is very anyoing because I have to clear the data (not the cache clearing the cache does nothing)  for the app. This seems to fix it FOR THE TIME BEING but if I open the app with the sensor off the autorotation (for full screen videos ) full get bugged again

**Comment by oSumAtrIX** [comment]
Can you reproduce this behaviour on the unpatched app?

**Comment by Throwingthethum** [comment]
The unpatched app? Buy that you mean normal YouTube I installed the app and built my version through trumix

**Comment by Throwingthethum** [comment]
Accidentally closed this as completed (•‿•)

**Comment by Throwingthethum** [comment]
Ops

**Comment by oSumAtrIX** [comment]
Did you check if the error happens on the unpatched application?

**Comment by Throwingthethum** [comment]
No I will try on the unpatched application and report back quickly

**Comment by Throwingthethum** [comment]
This does not occur on official YouTube but, it does occur on unpatched  revanced as it did not allow me to down without a patch I chose oled theme.

**Comment by Throwingthethum** [comment]
I am going to make another post because this seems to happen even if you don't use the sensor off shortcut
