### ISSUE TITLE
feat: Pan zoomed in videos

### ISSUE THREAD

**Issue by alcatraz-zz** [ReVanced/revanced-patches#426]
### Application

Hey fellas

When watching videos zoomed in it would be great to allow panning the frame. Sometimes the cropped area only misses a tiny portion of important information so that it doesn't require a zoom out. Just a simple pan would have been fine. Also on an oled display I'm trying to refrain from having black bars to even out the wear.

Thanks!

### Issue

Lost cropped area 

### Patch

Allow panning, left/right or up/down depending on ar of video and display.

### Motivation

Reduce burn in. Utilize entire screens even when important info is being cropped.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by alcatraz-zz** [comment]
I didn't see this feat req still open. I'll just append the motivation I wrote in another ticket.

Feature description
Today Revanced/Youtube allows for panning the video frame at zoom 1.5x or above.

I would very much like to be able to pan the frame at all zoom levels above 1x already.

It's a feature that I miss both on my 16:10 tablet and 20:9 phone. It's impossible to adjust the frame to get important information on the screen. Sometimes important information is in two corners of a video frame and currently the only solution is to constantly zoom in and out for each damn video. If you've ever tried panning at 1.5x zoom or above it's so effortless and convenient. Only problem is that at 1.5x you can't get two corners in the frame.

Motivation
Youtube today is still 99% 16:9 and a majority of devices aren't 16:9. Our only two options are black bars or cropped centered frame. Why not make the best of the situation and allow us to crop the frame the way we want it? At 1.5x zoom it's childsplay to move the frame around. Why not keep that feature for "fit to screen" zoom levels?

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
