### ISSUE TITLE
bug: <autorotation does not work for landscape videos >

### ISSUE THREAD

**Issue by Throwingthethum** [revanced/revanced-patches#426]
### Type

Other

### Bug description

I have already make a report about this because I thought it was me but this bug : when you go into full screen landscape video the autorotation on the 2 options does not work 

### Steps to reproduce

I am using a71 with Android 12 
Using the revanced verson  of 17.33.42

After 30 mins of using the app normally the the auto rotation seems to be completely broken for landscape videos 

### Relevant log output

```shell
Non
```

### Solution

A sulotion has been clearing data (not cache that does nothing) but the problem comes back after 20-40 minutes of use

**Comment by Throwingthethum** [comment]
Btw it seems to be a verson issue I rolled back to 17.31.36 
And this works amazing (for now idk about the future)

**Comment by Hyzian** [comment]
> Btw it seems to be a verson issue I rolled back to 17.31.36 
> And this works amazing (for now idk about the future)

did you as an older version of cli/patches as well? or did you just downgrade the youtube version?

**Comment by Throwingthethum** [comment]
Only downgrade the YouTube version

**Comment by Hyzian** [comment]
im having this problem in the official youtube app as well. seems like its a youtube problem
