### ISSUE TITLE
Premium unlock for telegram app

### ISSUE THREAD

**Issue by Mr-Nobody1** [revanced/revanced-patches#427]
### Type

Functionality

### Issue

It has so many features that are limited to premium users

### Feature

Animated pfp
Unlimited download speed
More channels joins
And many more

### Motivation

It has a lot of potential and it will help many ppl out there using telegram

**Comment by reisxd** [comment]
Wrong place to create feature requests (use discussions in revanced/revanced-suggestions) and I don't they're possible because it's server sided.

**Comment by PandoraHayami** [comment]
Also, isn't the Android app Open Source? It shouldn't need a full-on byte code patch.
