### ISSUE TITLE
Newest release couldn't build

### ISSUE THREAD

**Issue by DraakjeYoblama** [revanced/revanced-patches#43]
I tried to build revanced.apk (non-root) with revanced-patches v1.8.2 and revanced-cli v1.4.5, but it refused to build.
I switched to v1.8.1 and v1.4.2 which did work.

Not sure if this is something on my end or not, so I mentioned it here just to be sure.

**Comment by Sculas** [comment]
Duplicate of revanced/revanced-cli#39
