### ISSUE TITLE
bug: Auto play doesn't work if the auto play button is not enabled

### ISSUE THREAD

**Issue by ASDosjani** [revanced/revanced-patches#430]
### Type

Other

### Bug description

Title says it all.

### Steps to reproduce

Turn off auto play button.
Enable auto play.

### Relevant log output

```shell
I don't have.
```

**Comment by oSumAtrIX** [comment]
Autoplay is disabled if you disable the autoplay button.

**Comment by ASDosjani** [comment]
> Autoplay is disabled if you disable the autoplay button.

Than why the autoplay switcb is available in settings if I disable the button? It doesn't make sense.

**Comment by oSumAtrIX** [comment]
Both are separate patches, thats why.

**Comment by ASDosjani** [comment]
> Both are separate patches, thats why.

Can't these patches be combined?

**Comment by oSumAtrIX** [comment]
One disables the button and it's functionality of auto playing, the other makes it enabled by default, so if the button were disabled, how would you want to disable auto play?

**Comment by ASDosjani** [comment]
> One disables the button and it's functionality of auto playing, the other makes it enabled by default, so if the button were disabled, how would you want to disable auto play?

In the default YouTube settings.
3rd option in settings. That's what I'm talking about the whole time.

**Comment by oSumAtrIX** [comment]
Responsible code for this: https://github.com/revanced/revanced-patches/blob/217c7864d90b88810bba7fc95053d1edff7d7244/src/main/kotlin/app/revanced/patches/youtube/layout/autoplaybutton/patch/HideAutoplayButtonPatch.kt#L78

Getting rid of it would allow autoplayback even when the button is hidden.

**Comment by ASDosjani** [comment]
Yes, but at least you could change it in the settings. I think most people doesn't use the button but the autoplay is useful when listening to music. I'm not familiar with this code so I can't make the fix.

**Comment by ILoveOpenSourceApplications** [comment]
This is a very confusing issue. And with the option to toggle autoplay switch on/off present in the ReVanced settings, please try to ignore the autoplay setting by YouTube. Closing it now.
