### ISSUE TITLE
[Patch] Unlock Capcut pro.

### ISSUE THREAD

**Issue by ghost** [ReVanced/revanced-patches#435]
### Application

[Capcut](https://play.google.com/store/apps/details?id=com.lemon.lvoverseas)

### Issue

Many effects and features are locked behind a paywall. (capcut pro) this patch would solve that and unlock all features.

### Patch

A patch to unlock Capcut pro.

### Motivation

Capcut is a good video editor. But some features that could make an edit are paywalled. This patch would unlock everything and make an edit better!

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [ ] I filled out all of the requested information in this issue properly.

**Comment by trmdi** [comment]
> Theres many good video editors. Insufficient motivation.

But Capcut is the best one. Do you know anything else better?

**Comment by oSumAtrIX** [comment]
That's my personal opinion, you can find plenty editors online, this isn't a place to discuss them.

**Comment by trmdi** [comment]
> That's my personal opinion, you can find plenty editors online, this isn't a place to discuss them.

So will you reopen this issue and try patching it or will you lock the issue as usual?

**Comment by oSumAtrIX** [comment]
> Note Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches. Good motivation has to be provided for a request to be accepted.

> To maintain a high-quality and ethical collection of patches, the following guidelines for requesting or contributing patches are effective as of September 14, 2023. Any patches present prior to this date are unaffected by this change.
