### ISSUE TITLE
Bring a channel blocking setting. And particular Word (Yt search and recommendation)  blocking setting.

### ISSUE THREAD

**Issue by Priyanshuyad** [revanced/revanced-patches#436]
### Type

Functionality

### Issue

Unnecessary Channels are  **Addictions or Distractions**

Bring a new setting  in revanced app.
 
(Upcoming update ) 

### Feature

It's work like parent blocking setting. 
![IMG_20220907_114032](https://user-images.githubusercontent.com/113005991/188801861-86c1665c-ae22-4ac8-b329-6cff4956adb1.jpg)
![IMG_20220907_114016](https://user-images.githubusercontent.com/113005991/188801883-a2b489bd-d054-43e7-91ff-0c195686c52a.jpg)

2. **Add setting**
-      Channel blocking
-      Word blocking 

YouTube Brave browser feature
- Elements blocking system also available in brave 
-

  
    

### Motivation

It,s very **importance** **for** **students** for any yt particular channel distractions.
Etc, (Any channel auto recommendation video distractions or search results)

**Comment by reisxd** [comment]
Not the place to make suggestions. Please make a discussion in revanced/revanced-suggestions. Also, possible dupe.
