### ISSUE TITLE
bug(YouTube): Combine multiple patches into `Hide Layout Components`

### ISSUE THREAD

**Issue by KobeW50** [ReVanced/revanced-patches#443]
### Type

Cosmetic

### Bug description

Currently, many YT patches are similar in nature to the Hide Layout Components patch, which is confusing.

### Steps to reproduce

Look at the patch list for YT.

### Relevant log output

```shell
NA
```

### Solution

Combine several of the similar patches into the Hide Layout Components patch.

Patches to consider adding are:

1. Hide album cards

2. Hide breaking news shelf

3. Hide crowdfunding box

4. Hide filter bar

5. Hide Load more button
 
Edit: There are probably others considering that this issue is several months old. Search the patches for "Hide" and pretty much all of the potentially relevant ones will appear.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by ILoveOpenSourceApplications** [comment]
@LisoUseInAIKyrios, now that `Hide 'Load more' button` and 'Hide horizontal shelves` has already been moved into layout components. How about the rest mentioned here? @KobeW50, any more suggestions from your end as well?

**Comment by KobeW50** [comment]
> KobeW50, any more suggestions from your end as well?

Here's an updated list of patches that can be considered: 

![SmartSelect_20240417_154046_ReVanced Manager](https://github.com/ReVanced/revanced-patches/assets/84587632/db8f2557-d902-4699-82d5-f79792b817a2)

These all only hide one or two simple elements and don't need to be a standalone patch. Maybe the `Hide cast button`, `Hide autoplay button` and `Hide captions button` patches should be packaged together with the `Hide player buttons` patch instead of the `Hide layout components` patch.

I encourage whoever takes on this task to look through the patches themselves to make sure there aren't other patches that I missed. (I also don't know if there are patches that are applicable in the dev branch).

**Comment by UfukUstali** [comment]
While I do agree with the general sentiment here depending on the implementation this may end up taking away some amount of freedom from users. 

A specific example I have of this is the current state of the `Hide Horizontal Shelves`, which doesn't seem to allow enabling Continue Watching without also enabling Breaking News or vice versa.

I am just getting started with this repo and if it seems like I am not aware of a feature which can get me the above explained result please let me know.

**Comment by oSumAtrIX** [comment]
The patches come with in-app options.

**Comment by UfukUstali** [comment]
> The patches come with in-app options.

![Screenshot_20240430_004201_YouTube.jpg](https://github.com/ReVanced/revanced-patches/assets/93888971/2930b0c4-63e0-493c-8d7a-c2f35d9a66ed)

I am aware of this but as can be seen in the image I provided `Hide Horizontal Shelves` doesn't seem to allow such granular control (as I described above) over what is enabled and what is not.
