### ISSUE TITLE
feat: Spotify

### ISSUE THREAD

**Issue by 2latemc** [revanced/revanced-patches#450]
### Type

Functionality

### Issue

Add the same thing for spotify (Downloads, no ads, & subtitles). I know that you already have yt music

### Feature

-

### Motivation

Spotify is really famous

**Comment by reisxd** [comment]
Not the place to make feature requests, please make an discussion in revanced-suggestion. Also, possible dupe.

**Comment by GioPan04** [comment]
Should this be reopened? As requested [here](https://github.com/orgs/revanced/discussions/589), requests for patches have to be done here.

**Comment by oSumAtrIX** [comment]
Open a new issue with the new template.
