### ISSUE TITLE
Disable custom-branding for YouTube Music

### ISSUE THREAD

**Issue by AMSAMSAMSAMS** [revanced/revanced-patches#451]
### Type

Cosmetic

### Issue

The app name is crazy long: YouTube Music ReVanced...

### Feature

Patched switch to disable custom-branding on YT Music so it just using the normal name.

### Motivation

YouTube Music is already long name, doesn't need more word in it.

**Comment by oSumAtrIX** [comment]
Use `-e` to exclude the patch or change the name in the options file.

**Comment by Canny1913** [comment]
custom-branding for YTM doesnt exist at all.

**Comment by AMSAMSAMSAMS** [comment]
> custom-branding for YTM doesnt exist at all. The name is hardcoded into MicroG patch.

not....


> Use `-e` to exclude the patch or change the name in the options file.

which one for YT Music?

**Comment by Toby222** [comment]
The hard-coded name is right [here](https://github.dev/revanced/revanced-patches/blob/main/src/main/kotlin/app/revanced/patches/music/misc/microg/shared/Constants.kt#L5), and then applied [here](https://github.com/revanced/revanced-patches/blob/main/src/main/kotlin/app/revanced/patches/music/misc/microg/patch/resource/MusicMicroGResourcePatch.kt#L28-L30)

**Comment by AMSAMSAMSAMS** [comment]
> The hard-coded name is right [here](https://github.dev/revanced/revanced-patches/blob/main/src/main/kotlin/app/revanced/patches/music/misc/microg/shared/Constants.kt#L5), and then applied [here](https://github.com/revanced/revanced-patches/blob/main/src/main/kotlin/app/revanced/patches/music/misc/microg/patch/resource/MusicMicroGResourcePatch.kt#L28-L30) (read: it's hardcoded and it wouldn't be hard to fix)

then it would be nice to make switch for it so it can be toggled like the main YouTube app...

**Comment by Toby222** [comment]
@oSumAtrIX can you re-open, or comment?
