### ISSUE TITLE
An option to disable 60 FPS in YT Revanced

### ISSUE THREAD

**Issue by TheGreySquare** [revanced/revanced-patches#458]
### Type

Functionality

### Issue

Please, if possible, add an option to disable 60 FPS on a 720p and higher videos in YT Revanced.

### Feature

It could've been achieved like it was in YT Vanced. There was a "Codec settings" menu, where you could set the codec preferences from a different phone model, which will disable 60 FPS on a videos and will just keep 30 FPS (Setting phone model to SM-T250 there, for example, disables 60 FPS). 
Screenshots of this menu in Vanced:
![Screenshot_20220910-174714_YouTube~2](https://user-images.githubusercontent.com/47947180/189517729-42190ca5-27a0-43e8-8d1e-5b8247470a5f.png)
![Screenshot_20220911-103341_YouTube](https://user-images.githubusercontent.com/47947180/189517733-8b47f2b9-907a-4f18-abe7-2e37cab85897.png)

### Motivation

It would be useful, for example, when the user gets poor cellular reception and it would just be easier on a data plan without switching to lower quality (480p). Data Saving mode in YT settings, unfortunately, doesn't help here (it keeps 60 FPS on a videos).

**Comment by reisxd** [comment]
This is not the place to suggest features, please use GitHub Discussions.
