### ISSUE TITLE
refactor: convert app icons programmatically

### ISSUE THREAD

**Issue by Sculas** [revanced/revanced-patches#466]
This would allow a user to just select an icon, pass it to the `custom-branding` patch via patch options, and then it would convert the single icon to the many dimensions needed. The way we have it right now is very bad and makes the option quite unusable.

We'll have to make a separate repo for shared imaging/graphics between Java and Android. We can then use this in our Androlib fork and in the patches.

Resources:
- https://mvnrepository.com/artifact/com.google.android/android/4.1.1.4

**Comment by decipher3114** [comment]
but that is not possible. Bcz rounded icon has a background, while the foreground is only icon, no bg.


![Image](https://user-images.githubusercontent.com/84389932/190048931-8fb89123-1640-4723-b2a2-481ef60363b9.png)

Creating these with single icon using a program is not a good idea.

**Comment by Sculas** [comment]
Oh, you're right. Didn't think about that. Yeah, that's going to be a problem.

**Comment by pungorandras** [comment]
I think it can be helpful: https://github.com/romannurik/AndroidAssetStudio

**Comment by ILoveOpenSourceApplications** [comment]
This shouldn't be here right?

**Comment by oSumAtrIX** [comment]
It is not feasible easily, closing for that reason
