### ISSUE TITLE
bug: background playback disabled when mini player is also disabled

### ISSUE THREAD

**Issue by grantlee77** [revanced/revanced-patches#468]
### Type

Other

### Bug description

Title says it all.
It worked fine in revanced 17.31.xx.

### Steps to reproduce

1. Disable mini player 8n revanced settings
2.  Background Playback option in youtube settings is now hidden. Background playback is disabled.

### Relevant log output

```shell
/
```

**Comment by oSumAtrIX** [comment]
Not reproducible, disabling mini player does not affect background playback.

**Comment by grantlee77** [comment]
Thank you for your feedback. I gave it another shot.

I just rebuilt revanced 17.33.42 and installed if freshly.
By default, mini player is enabled and so is background playback.
If I disable mini player, background playback gets disabled as well.

**Comment by oSumAtrIX** [comment]
https://user-images.githubusercontent.com/13122796/189691811-51c5f5e1-acc9-4cfc-883c-d4700bb0bd84.mp4

**Comment by oSumAtrIX** [comment]
Please record your issue.

**Comment by grantlee77** [comment]
Well, I don't know what I did, bit it's now fixed and I can't reproduce the original behavior.
Issue is closed I guess.
Thanks for your concern.
