### ISSUE TITLE
bug(YouTube): Hide Breaking News does not work

### ISSUE THREAD

**Issue by adanvdo** [ReVanced/revanced-patches#469]
### Type

Other

### Bug description

in the MigroG version, the "Hide breaking news" patch is no longer working and the breaking news section is being displayed although the setting to hide it is enabled.  I have uninstalled and installed a freshly patched version of 18.23.35 but the issue persists.

### Steps to reproduce

1. Patch the 18.23.35 apk with the Hide breaking news patch included.
2. Enable the Hide breaking news setting
3. Restart the app
4. The Breaking News section is still displayed

### Relevant log output

```shell
Manager logs do not appear relevant.
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
The patch doesn't break anything, so removing and then adding it may be unnecessary. I am unable to make a fix as I am not seeing that breaking news.
