### ISSUE TITLE
Youtube Downloader API

### ISSUE THREAD

**Issue by F1R3W4LL404** [revanced/revanced-patches#471]
### Type

Functionality

### Issue

Button to download occupies another application

### Feature

I have an api made in php to download audio and video for youtube, is there any way to implement the api to the button to download videos?

I can publish the api code if you need it.

To use it you only have to send the data by post or get with the following variables

example video:
http://52.150.21.182/index.php?youtube_url=https://www.youtube.com/watch?v=0BIaDVnYp2A&ab_channel=BackgroundMusicWithoutLimitations&format=video (also mp4)

example audio:
http://52.150.21.182/index.php?youtube_url=https://www.youtube.com/watch?v=0BIaDVnYp2A&ab_channel=BackgroundMusicWithoutLimitations&format=audio (also mp3)

### Motivation

have a better application

**Comment by oSumAtrIX** [comment]
If you check the integrations code, you will see that the button launches the "share" intent. Create a dummy application with that intent and implement the code to reach that URL.
