### ISSUE TITLE
feat: Add a light video player for low-end devices

### ISSUE THREAD

**Issue by johnconner122** [revanced/revanced-patches#472]
### Type

Other

### Issue

I have a low-end phone with 2GB of RAM. It sometimes freezes the video while minimizing or maximizing the video, especially, in higher resolution. Sometimes video takes longer to load or video player initializes slowly.

### Feature

With efficient video player, video will load faster.

### Motivation

convenience for low-end phones.

**Comment by HaiziIzzudin** [comment]
The video codec may be the culprit. I wish there is patches to... yknow... choose default video codec. H264 is very light to decode, especially for low ends.

**Comment by oSumAtrIX** [comment]
Theres not much ReVanced can do about it. The issue is a low end device, also wrong place to suggest patches.
