### ISSUE TITLE
feat(patch): twitter: hide promoted tweets in replies

### ISSUE THREAD

**Issue by nerd** [revanced/revanced-patches#481]
### Application

twitter (com.twitter.android)

### Issue

promoted tweets can interrupt the replies section of the tweet details view

### Patch

remove/hide promoted tweets from appearing in the replies

### Motivation

promoted tweets are already removed from the timeline, it follows that they should be removed everywhere. this helps keep me and others from seeing advertisements

**Comment by Osahashi** [comment]
I don't mean to be annoying, but could someone take care of this? Would be really great.

**Comment by ILoveOpenSourceApplications** [comment]
Isn't this resolved with hide-promoted-ads patch?
