### ISSUE TITLE
bug: YouTube Music crashes on startup

### ISSUE THREAD

**Issue by basilioss** [revanced/revanced-patches#483]
### Type

Error at runtime

### Bug description

If I try to open YouTube Music, it runs for one second and crashes. Disabling "Codecs unlocked" +  "Tastebuilder Remover" patches does not help.

### Steps to reproduce

1. Download YouTube Music
2. Open ReVanced Manager
3. Patches > Select application > YouTube Music > Select patches > Default selection > Done > Patch
4. Install
5. Open

### Relevant log output

```shell
See additional context
```

### Additional context

ReVanced Manager Version: 0.0.5
Installation Type: Non-root
Android Version: 11
Arch: armeabi-v7a
Log: [revanced-manager_logcat_20220915111527682299.log](https://github.com/revanced/revanced-patches/files/9573931/revanced-manager_logcat_20220915111527682299.log)

**Comment by oSumAtrIX** [comment]
Please follow the guide in the official documentation.
