### ISSUE TITLE
feat(patch): YouTube shorts: normal YouTube video option

### ISSUE THREAD

**Issue by acoustic-git-tar** [revanced/revanced-patches#490]
### Application

YouTube 

### Issue

I (and likely others) really dislike the Shorts UI for Shorts videos. 

### Patch

With patch enabled, YouTube Shorts videos should become normal videos and behave identically as such. 

### Motivation

Increases consistency between videos and lets users have access to most of ReVanced tools. Also would allow for background and pop-up play.

**Comment by Ben-Kaniobi** [comment]
Hint for the devs:

If you change the URL of any Short from `https://youtube.com/shorts/<ID>` to `https://youtube.com/watch/<ID>` then the YouTube app will already open it like a normal video. So maybe the patch is just something like replacing all the `/shorts/` URLS with `/watch/`. I don't know anything about how these patches are implemented, so I can't say if this is something simple or not.

**Comment by oSumAtrIX** [comment]
#969

**Comment by KyleBroflowski** [comment]
@oSumAtrIX   I still cannot see the patch in revanced manager. Was this really closed as completed? If so, could you tell me what the option is called?

**Comment by Ushie** [comment]
> @oSumAtrIX I still cannot see the patch in revanced manager. Was this really closed as completed? If so, could you tell me what the option is called?

Your issue is a duplicate, oSumAtrIX redirected you to the other issue to follow it

**Comment by KyleBroflowski** [comment]
@Ushie Thanks. I hope it gets implimented soon
