### ISSUE TITLE
feat(patch): arktube downloader for YT

### ISSUE THREAD

**Issue by dracinn** [revanced/revanced-patches#493]
### Application

YouTube 

### Issue

Arktube downloads.

### Patch

I'd like to see support for Arktube directly like with Newpipe.

### Motivation

I believe it's a more versatile downloader.

**Comment by Sculas** [comment]
Please fix the issue title.

**Comment by oSumAtrIX** [comment]
Already possible, simply change the package name from NewPipe's to Arktube's in the settings.
