### ISSUE TITLE
Original share icon in Tweets

### ISSUE THREAD

**Issue by harshil21** [revanced/revanced-patches#498]
### Application

Twitter

### Issue

Recently, Twitter users in India started seeing a new share "icon" -- the WhatsApp icon. See [this tweet](https://twitter.com/TwitterIndia/status/1567864204358557696?t=_J2Kv3TTz5xdkVngBwPehw&s=19).

### Patch

Patch should simply replace the WhatsApp icon with the actual share icon.

### Motivation

This icon does not look good and is confusing to users.(since it opens up the same share menu). Also this appears even if you don't have WhatsApp.

**Comment by nikhilbadyal** [comment]
It's not even released yet and just an experiment and you already want to patch it.

**Comment by harshil21** [comment]
well looks like they reverted this, so closing.
