### ISSUE TITLE
bug: Trying to comment on Note 9 results in keyboard getting stuck open.

### ISSUE THREAD

**Issue by KaidenLarsen** [ReVanced/revanced-patches#50]
### Bug description

- Using the Galaxy Note 9 Android 10
- when you go to leave a comment on a video, short or livestream the keyboard gets stuck open with no way to close it other than waiting an unknown amount of time, never over a couple minutes. You can try to type but nothing will appear, the keyboard seems to lag a lot and it is difficult to write the comment as there is no visual response on the app. I once got it to work by pausing the video but can't since replicate it. 
- Here is a video showcasing the bug, when I try to open the keyboard I am typing there is just no visual feedback, however the phone does vibrate.
https://youtu.be/FYVhoLLYuiA?si=UUdMvpYefRl-a-Zj
-Selected patches: 
[selected_patches_2023-12-01_14_05_13.json](https://github.com/ReVanced/revanced-patches/files/13531124/selected_patches_2023-12-01_14_05_13.json)

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
It was already known that the issue is not caused by ReVanced as r/YouTube was reporting this issue.

**Comment by oSumAtrIX** [comment]
I don't see any ground truth to 19.02.39 solving this. We'll eventually bump.

**Comment by memphismc** [comment]
can confirm this also happens on S9+, using youtube patched by revanced manager 1.19.3, are there any fixes to this comment freezing bs?
