### ISSUE TITLE
bug: <Stuttering in YT Music>

### ISSUE THREAD

**Issue by snilex1** [revanced/revanced-patches#503]
### Type

Other

### Bug description

In versions newer than 5.17.51 when switching to the background mode there is a second stutter, a small thing, but not nice.

### Steps to reproduce

Install last patched version YT Music and watch

### Relevant log output

```shell
none
```

**Comment by oSumAtrIX** [comment]
I can not reproduce this. When i leave the app, it continue to play the song without stopping.

**Comment by snilex1** [comment]
The delay is only a second

**Comment by oSumAtrIX** [comment]
I do not notice any delay.

**Comment by snilex1** [comment]
Try another device, another person even had this problem on an emulator.

**Comment by EatVanced** [comment]
From discord, seems like it affects song only, stock works fine, I can't fine which patch caused this.

https://cdn.discordapp.com/attachments/1020300607606759525/1020316399178108969/Screenrecorder-2022-09-16-15-52-38-991.mp4

https://cdn.discordapp.com/attachments/1020300607606759525/1020315977730244608/Record_2022-09-16-19-50-14.mp4

**Comment by akajj21** [comment]
After using YT music for a few songs. I get a notification asking if I'm still watching video. When I hit yes it'll play for another few songs and ask again. Not sure if this is a bug or not

**Comment by ILoveOpenSourceApplications** [comment]
Cannot replicate this issue. Probably something to do with the device settings. Hence closing it now.
