### ISSUE TITLE
feat(Spotify): 

### ISSUE THREAD

**Issue by snilex1** [revanced/revanced-patches#504]
### Application

Spotify

### Issue

Ads in spotify

### Patch

Ads in spotify

### Motivation

Good music

**Comment by sawankumarbundelkhandi** [comment]
duplicate of https://github.com/revanced/revanced-patches/issues/450

**Comment by sawankumarbundelkhandi** [comment]
@oSumAtrIX  one of the two https://github.com/revanced/revanced-patches/issues/450 or https://github.com/revanced/revanced-patches/issues/504 should be kept open as the request for new patches are now maintained in the here only instead of the org discussion.
