### ISSUE TITLE
bug: youtube logo not changing 

### ISSUE THREAD

**Issue by Fosssil** [revanced/revanced-patches#507]
### Type

Cosmetic

### Bug description

I use YouTube revanced version 17.33.42 patched using revanced patcher but youtube revanced is not changing to youtube logo ( default ). 

### Steps to reproduce

Sorry IDK

### Relevant log output

```shell
Sorry IDK
```

### Screenshots or videos

![Screenshot_2022-09-17-01-33-44-048_com miui home](https://user-images.githubusercontent.com/38956299/190723995-e5c06a56-4b48-4e39-b665-cec9d5dd08fa.png)

**Comment by reisxd** [comment]
Don't include the custom-branding patch, not a bug.

**Comment by Fosssil** [comment]
> Don't include the custom-branding patch, not a bug.

But in some early patches it worked when we selected it 🤔.

**Comment by oSumAtrIX** [comment]
Please include reproduction steps.
