### ISSUE TITLE
bug: YouTube Crashes After Patching

### ISSUE THREAD

**Issue by anil-al** [revanced/revanced-patches#510]
### Type

Error at runtime

### Bug description

Versions newer than 17.33... crashes when its opening. Tested with 17.35... and 17.36... and probably with 17.34... I don't remember the last fine clearly. I couldn't find the reason behind it. Tried excluding theme and/or client spoof patch(es). YouTube Music app works just fine.

### Steps to reproduce

Patch YouTube app with experimental mode with versions higher than 17.33...
Open the app.
It crashes immediately.

### Relevant log output

```shell
-
```

### Additional context

Android 12
Samsung X800.

**Comment by oSumAtrIX** [comment]
The option is called `experimental` for a reason.

**Comment by anil-al** [comment]
> The option is called `experimental` for a reason.

Yes and no. I have never experienced something like that and the reason behind opening this issue was clearly to let you know that patching isn't healthily applicable for new versions and you will face with it, too when you try to support higher versions. So, no, it's not completed.

**Comment by oSumAtrIX** [comment]
There's a reason why pathches target specific versions, there's no need to let us know that unsupported versions don't work because they are unsupported.

**Comment by anil-al** [comment]
> There's a reason why pathches target specific versions, there's no need to let us know that unsupported versions don't work because they are unsupported.

But these are newer versions and they will have to be supported at some point and ReVanced is 3-4 version behind, Google Play version is 17.36.37. so, why isn't it a need to know something that has to be fixed so it can be worked through beforehand?

**Comment by neekless** [comment]
> > There's a reason why pathches target specific versions, there's no need to let us know that unsupported versions don't work because they are unsupported.
> 
> But these are newer versions and they will have to be supported at some point and ReVanced is 3-4 version behind, Google Play version is 17.36.37. so, why isn't it a need to know something that has to be fixed so it can be worked through beforehand?

Because they already know there are newer versions on Google play, they don't need you to tell them. They will update the patches when they are ready.
