### ISSUE TITLE
bug: Auto rotation doesnt work in player

### ISSUE THREAD

**Issue by LithRakoon** [revanced/revanced-patches#517]
### Type

Error at runtime

### Bug description

In the normal youtube app when "portrait mode" is enabled videos will still automaticly rotate when you turn your phone 180 degrees.
With revanced this does NOT work as now when you rotate your phone it will instead give you the rotate button at the bottom of the screen instead of rotating automaticly.

### Steps to reproduce

Step 1: Phone is on portrait mode
Step 2: Open video in revanced youtube
Step 3: Rotate phone 180 Degrees

See that video player doesnt rotate automaticly

### Relevant log output

```shell
N/A
```

### Screenshots or videos

Proof of the bug:
https://cdn.discordapp.com/attachments/1020672306776915978/1020676123715178566/Screen_Recording_20220917-143951.mp4

ALL THESE PICTURES ARE TAKEN IN REVANCED YOUTUBE NOT NORMAL YOUTUBE APP:

When it started working again:
https://cdn.discordapp.com/attachments/1020672306776915978/1020704900679745606/Screenshot_20220917-161817.jpg

"custom player" in question (auto rotate does not work):
https://cdn.discordapp.com/attachments/1020672306776915978/1020705185288421417/Screenshot_20220917-163729_YouTube.jpg

### Additional context

This issue seems from my limeted testing to be the fault of the customer UI player thats in place when using revanced
as when i disabled every patch that had something to do with the player and the "Custom branding" Patch the custom player would dissapear and the auto rotate would work

**Comment by oSumAtrIX** [comment]
https://user-images.githubusercontent.com/13122796/190863650-4b464974-02f1-4404-aa01-1f1f1d0f2661.mp4

**Comment by oSumAtrIX** [comment]
Can not reproduce.

**Comment by LithRakoon** [comment]
hello could you show me if you really have "portrait mode" enabled and you dont have "auto rotate" enabled and please try 180 degrees not 90

**Comment by LithRakoon** [comment]
update after some more testing this bug seems to be quite random?
i reinstalled revanced youtube with all the patches installed excluding "swipe gestures" and "disable fullscreen"
and then i got the normal player and the auto rotation worked again
patches:
![image](https://user-images.githubusercontent.com/41258148/190864238-0485b149-0bcf-4749-a304-b56604ae3b97.png)
and the player as you can see is the normal one:
![image](https://user-images.githubusercontent.com/41258148/190864251-47589b12-0dd8-47ff-b9e9-688ea54010c5.png)

confused i deleted the app and reinstalled vanced with the exact same patches again and then i got the custom player again and auto rotation stopped working again
custom player:
![image](https://user-images.githubusercontent.com/41258148/190864282-a3b94232-1ede-423b-b65a-4becc4b3d43a.png)

**Comment by oSumAtrIX** [comment]
This is a YouTube thing. YouTube updated their player to the one with the controls with a transparent background. If portrait mode is disabled on my phone, neither regular YouTube nor the patched app rotate when rotating the phone, expectedly, because portrait mode is enabled.
