### ISSUE TITLE
feat(patch): bring back auto-rotate with portrait mode

### ISSUE THREAD

**Issue by LithRakoon** [revanced/revanced-patches#519]
### Application

youtube

### Issue

#

### Patch

On the youtube app the player used to automaticly rotate when you rotated your phone even when "portrait mode" was enabled.
they now have removed that functionalitly.

"make player rotate even when portraite mode is enabled"

### Motivation

from looking through the discord im not the only one jarred by this new update to the player removing a functionality that i was used to.
examples:
https://discord.com/channels/952946952348270622/952946952348270626/1020448058707816469
https://discord.com/channels/952946952348270622/952946952348270626/1020389660314320996
https://discord.com/channels/952946952348270622/952946952348270626/1020314638476394526

it is also way more convienient to just rotate your phone and the player too without having to enable and reenable the "auto rotation" setting everytime you wanna watch something on youtube

**Comment by JimZiii** [comment]
I noticed this myself yesterday and was about to request it myself 👍

**Comment by rohan2000github** [comment]
And make it toggleable in settings.

**Comment by JimZiii** [comment]
Not sure if they intentionally fixed it since it's still open, but it's now working again

**Comment by oSumAtrIX** [comment]
Fixed on Googles side.
