### ISSUE TITLE
feat(patch): advanced pip mode

### ISSUE THREAD

**Issue by MuhannadYT** [revanced/revanced-patches#522]
### Application

Youtube and vanced if possible

### Issue

One some android phones (huawei p30 pro in this example) have a bad picture in picture mode. Where the size can't be changed or moved to the edges
Here is an example
[https://streamable.com/nxjjrp](https://streamable.com/nxjjrp) 

### Patch

This patch would make picture in picture mode use the "draw over other apps" permission. Which would allow the frame to be moved a lot more freely. 

### Motivation

This patch improves people's experience by making pip mode more usable. Also if someone has android 7 this might work on it as well.

**Comment by oSumAtrIX** [comment]
PIP is an Android API, there is no way to force PIP to behave differently without modifying the Android OS

**Comment by MuhannadYT** [comment]
> PIP is an Android API, there is no way to force PIP to behave differently without modifying the Android OS

Some 3rd party youtube apps use the draw over other apps permission like this
[https://streamable.com/0i4by7](https://streamable.com/0i4by7)
which does not require using the api

**Comment by oSumAtrIX** [comment]
That would require a complete modification of the existing PIP and YouTube code, this will likely never be done.
