### ISSUE TITLE
Copy link and Copy link with timestamp

### ISSUE THREAD

**Issue by Black-StellarSpectrum** [revanced/revanced-patches#531]
### Application

Youtube 

### Issue

No way to copy link with timestamp

### Patch

It'd be nice to directly copy a link to timestamp to share a particular part of the video if possible.
Like long pressing share will share link with timestamp!

### Motivation

Old YouTube Vanced

**Comment by NewtonChutney** [comment]
Ohh moderators!! Please please pleeeaasseee prioritize this patch!  🥺🥺🥺

**Comment by sawankumarbundelkhandi** [comment]
@oSumAtrIX I think this issue can be closed as it's already addressed by https://github.com/revanced/revanced-patches/pull/1402 with a button on video player to copy with timestamp.
