### ISSUE TITLE
feat: Support for Sync for Lemmy

### ISSUE THREAD

**Issue by tabtomi8** [ReVanced/revanced-patches#539]
### Application

Sync for Lemmy

### Issue

Currently there isn't support for it, can't patch it. 

### Patch

- Disable ads
- ~~Unlock Pro~~

### Motivation

For now Sync is the only good Lemmy app, other apps are not as good as Sync, they're buggy and slow. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by edgerunnergit** [comment]
Any updates on this?

**Comment by Bceez** [comment]
This has been implemented. Issue can be closed
