### ISSUE TITLE
bug: YouTube interface with lag

### ISSUE THREAD

**Issue by jhonnyn5** [revanced/revanced-patches#541]
### Type

Error at runtime

### Bug description

The interface has a lot of lag, and don't say it's because of the 60 fps screen.  The official vanced app is not that slow. "Theme" patch is buggy

### Steps to reproduce

Apply Theme patch

### Relevant log output

```shell
Noone
```

### Solution

Without that patch app runs better

**Comment by oSumAtrIX** [comment]
If you look at the source code of the theme patch you will notice that it merely changes color. Disable all patches and reproduce this issue.

**Comment by jhonnyn5** [comment]
> If you look at the source code of the theme patch you will notice that it merely changes color. Disable all patches and reproduce this issue.

I tried but if only apply this patch youtube crashes am i cant open it. I dont know if is patches or manager. But héroes is a list of pacthes that I amplíen
- client spoof
- custom video buffer
- Enable debugging
- general ads
- microg support
- premium heading
- return youtube dislike button
- video ads
Without theme patch th app runs very well and I am on android 12 one ui 4.1, youtube version 17.36.37

**Comment by oSumAtrIX** [comment]
@jhonnyn5 
> Without theme patch th app runs very well and I am on android 12 one ui 4.1, youtube version 17.36.37

Please record the following in one go:
1. Patch the app without the theme patch
2. Show it doesnt cause any issues
3. Patch the app with the theme patch
4. Show it causes issues

**Comment by jhonnyn5** [comment]
> @jhonnyn5
> 
> > Without theme patch th app runs very well and I am on android 12 one ui 4.1, youtube version 17.36.37
> 
> Please record the following in one go:
> 
> 1. Patch the app without the theme patch
> 2. Show it doesnt cause any issues
> 3. Patch the app with the theme patch
> 4. Show it causes issues


https://user-images.githubusercontent.com/87892929/191139947-f56a2c68-1706-4355-82f7-5bfab90f35d4.mp4

It may not be very noticeable but the feel on the device is heavy.  Although in one part it is clearly seen how I play the video and it does not come on until several moments later.

**Comment by oSumAtrIX** [comment]
Please do as the steps suggest.

**Comment by OxrxL** [comment]
> > @jhonnyn5
> > > Without theme patch th app runs very well and I am on android 12 one ui 4.1, youtube version 17.36.37
> > 
> > 
> > Please record the following in one go:
> > 
> > 1. Patch the app without the theme patch
> > 2. Show it doesnt cause any issues
> > 3. Patch the app with the theme patch
> > 4. Show it causes issues
> 
>  video-1-1_zjkcMcpt.mp4 
> It may not be very noticeable but the feel on the device is heavy. Although in one part it is clearly seen how I play the video and it does not come on until several moments later.

Try to disable return youtube dislike.

**Comment by Ultrasonic1209** [comment]
> > > @jhonnyn5
> > > > Without theme patch th app runs very well and I am on android 12 one ui 4.1, youtube version 17.36.37
> > > 
> > > 
> > > Please record the following in one go:
> > > 
> > > 1. Patch the app without the theme patch
> > > 2. Show it doesnt cause any issues
> > > 3. Patch the app with the theme patch
> > > 4. Show it causes issues
> > 
> > 
> > video-1-1_zjkcMcpt.mp4
> > It may not be very noticeable but the feel on the device is heavy. Although in one part it is clearly seen how I play the video and it does not come on until several moments later.
> 
> Try to disable return youtube dislike.

It does seem Return YouTube Dislike and the "Theme" patch is causing issues for me on my phone (Samsung Galaxy S21+)
The two main symptoms are >2 seconds of lag upon loading a video (which also blocks system buttons such as the volume control, despite the video itself playing immediately). The other bug is where the player controls never hide once you tap to show them and tapping them again doesn't make it disappear, either.

**Comment by oSumAtrIX** [comment]
@Ultrasonic1209 https://github.com/revanced/revanced-patches/issues/541#issuecomment-1251570594
