### ISSUE TITLE
bug: <title>Can't see video duration

### ISSUE THREAD

**Issue by ghost** [revanced/revanced-patches#548]
### Type

Cosmetic

### Bug description

In any version of ReVanced in the dark mode, the duration of the videos is not visible.

### Steps to reproduce

On the main page of the application, if the dark theme is enabled, the duration of the videos is not visible

### Relevant log output

```shell
Missing
```

### Screenshots or videos

![26417585](https://user-images.githubusercontent.com/113991433/191252955-3d1a84e9-c632-49cb-8f03-0970128b20c2.jpg)

### Solution

Not found

**Comment by oSumAtrIX** [comment]
Is the video even playing?

**Comment by xiaomist** [comment]
> Is the video even playing?

yes

**Comment by oSumAtrIX** [comment]
Can you please record the issue when you have dark theme enabled and when dark the disabled?

**Comment by xiaomist** [comment]
Unfortunately I can't catch this bug. It appears quite rarely.

**Comment by oSumAtrIX** [comment]
If it happens, simply record it.
