### ISSUE TITLE
feat(patch): Video quality settings like in Youtube Vanced

### ISSUE THREAD

**Issue by xiaomist** [revanced/revanced-patches#551]
### Application

Youtube

### Issue

The inability to adjust the video quality separately for wifi and mobile Internet in the Revanced settings.

### Patch

Add separate video quality control for wifi and mobile internet

### Motivation

Nostalgia for Youtube Vanced

**Comment by oSumAtrIX** [comment]
It automatically applies if you change the quality of videos.
