### ISSUE TITLE
Instagram

### ISSUE THREAD

**Issue by Fertanima** [revanced/revanced-patches#553]
### Application

I want to patch Instagram too. It's not possible. Why?

### Issue

Instagram

### Patch

I would like to patch Instagram.

### Motivation

.

**Comment by Aunali321** [comment]
Instagram is made in React Native which patcher can't patch yet.

**Comment by Fertanima** [comment]
Why?

**Comment by Fertanima** [comment]
Confused if possible as soon as possible

**Comment by Fertanima** [comment]
It may not be possible?

**Comment by Aunali321** [comment]
It wont be.

**Comment by Aunali321** [comment]
Yupp.

**Comment by Fertanima** [comment]
What is the percent chance of it being possible?

**Comment by Fertanima** [comment]
😭

**Comment by Aunali321** [comment]
Currently, none.
