### ISSUE TITLE
feat(patch): Force AV1 Codec

### ISSUE THREAD

**Issue by Jowat97** [revanced/revanced-patches#554]
### Application

YouTube (com.google.android.youtube)

### Issue

Hey there, Vanced YouTube offered the possibility to force VP9 Codec. However, nowadays AV1, the succeeder of VP9 is supported by YouTube, as well as by lot of smartphone processors. Those, without hardware decoding, can support software decoding. It can deliver better quality with lower bitrate (file size). Unfortunately, the original YouTube App only delivers AV1 codec to certain smartphones on certain videos in certain regions, which is absolutely intransparent and confusing.

### Patch

Force AV1 Codec for YouTube Videos, if available.

### Motivation

You would have better quality with less data volume consumption.

**Comment by oSumAtrIX** [comment]
This feature was removed due to causingctoo many issues, almost every support automatically uses the vp9 codec anyways.

**Comment by Canny1913** [comment]
> This feature was removed due to causingctoo many issues, almost every support automatically uses the vp9 codec anyways.

Dude i think you read it wrong.

**Comment by Jowat97** [comment]
@oSumAtrIX 

Yeah, it is for sure not be easy to handle. However, may it make sense to let this issue open as a long term goal?
SmartTubeNext supports to choose the codec for every video & audio manually (avc, vp9, av1): https://github.com/yuliskov/SmartTubeNext

Maybe it may also helps to bring that function to ReVanced. Just think it would be sad to stay with VP9. I compared many videos and codecs on YouTube and VP9 has in most cases the worst quality. For everything up to 1080p avc deliver better video quality and for everything above FHD av1 deliver (way) better quality. VP9 will only do one thing, reduce the server costs of YouTube.

Greets!

**Comment by Jowat97** [comment]
> This feature was removed due to causingctoo many issues, almost every support automatically uses the vp9 codec anyways.

Yeah, it is for sure not be easy to handle. However, may it make sense to let this issue open as a long term goal?
SmartTubeNext supports to choose the codec for every video & audio manually (avc, vp9, av1): https://github.com/yuliskov/SmartTubeNext

Maybe it may also helps to bring that function to ReVanced. Just think it would be sad to stay with VP9. I compared many videos and codecs on YouTube and VP9 has in most cases the worst quality. For everything up to 1080p avc deliver better video quality and also better performance and for everything above FHD av1 deliver (way) better quality. VP9 will only do one thing, reduce the server costs of Google.

And what do you mean by it was removed? There was never an av1 force patch for YouTube, at least not on Android (except for SmartTubeNext).

Greets!

**Comment by masterflitzer** [comment]
vp9 certainly isn't the worst codec, av1 > vp9 > avc for everything above 1080p

**Comment by Jowat97** [comment]
> vp9 certainly isn't the worst codec, av1 > vp9 > avc for everything above 1080p

This is not true at all, since everything above FHD will only be contributed in VP9 or AV1. There is no

**Comment by Jowat97** [comment]
#

**Comment by Jowat97** [comment]
> vp9 certainly isn't the worst codec, av1 > vp9 > avc for everything above 1080p

This is not true at all. Everything above FHD is only available in AV1 or VP9 obviously. AVC is not intended for 4K content.

**Comment by masterflitzer** [comment]
> > vp9 certainly isn't the worst codec, av1 > vp9 > avc for everything above 1080p
> 
> This is not true at all. Everything above FHD is only available in AV1 or VP9 obviously. AVC is not intended for 4K content. 

yeah I know YouTube doesn't do it but avc supports up to 8k theoretically 

still vp9 has far better visual quality than avc in higher resolutions (including 1080p)

also saying vp9 is only good for googles servers is not true at all, vp9 is very efficient and a good tradeoff between quality and computing power needed for decoding

av1 is an amazing codec but is very heavy to de-/encode

**Comment by NebelNidas** [comment]
While on this topic, I want to note that h.264 also has a purpose, as it should consume the least amount of battery

**Comment by masterflitzer** [comment]
yes of course h.264 ist still great and relevant, i didn't want to say otherwise, i just felt vp9 was getting bashed for no reason even though it's superior to h.264 in quality and efficiency

**Comment by oSumAtrIX** [comment]
Closing in favour of #909.
