### ISSUE TITLE
bug: Reset playback speed to 1.0x

### ISSUE THREAD

**Issue by xiaomist** [revanced/revanced-patches#556]
### Type

Other

### Bug description

If you start any video and select a playback speed of 0.75x and then close it and restart the same video, then the playback speed is reset to 1.0x (default playback speed)

### Steps to reproduce

Step. 1 Launch Youtube Revanced. 
Step 2. Play any video.
Step 3. Select a playback speed of 0.75x from the pop-up menu.
Step 4.Close and then restart the video

### Relevant log output

```shell
Missing
```

### Screenshots or videos

https://user-images.githubusercontent.com/113991433/191331811-cc7b394c-f5de-4f9f-a387-74eb101ed972.mp4

### Solution

Not found

**Comment by oSumAtrIX** [comment]
Default behaviour of YouTube, not a bug.
