### ISSUE TITLE
bug: Dark Mode doesn't apply to Revaced Settings

### ISSUE THREAD

**Issue by ghost** [revanced/revanced-patches#558]
### Type

Cosmetic

### Bug description

if you enable a dark theme in the application settings, then in the Revanced settings the theme will still be light. However, if you enable the dark theme in the smartphone settings, then in the Revanced settings the theme will also be dark.

### Steps to reproduce

Step 1. Launch Youtube Revanced
Step. 2. Go to Application Settings.
Step. 3. Enable dark theme in app settings
Step 4. Then go to Revanced settings

### Relevant log output

```shell
Missing
```

### Screenshots or videos

https://user-images.githubusercontent.com/113991433/191345377-87e597d5-910c-4714-bbd7-a00809252704.mp4

https://user-images.githubusercontent.com/113991433/191346373-6d10a1d6-5c33-4785-a962-34f1587f4a7e.mp4

### Solution

Not found

**Comment by Joomsy** [comment]
Switch from dark to light, then back to dark. After that, force close the app and it should fix it. This problem has existed for a while now, and it only happens after updating the app.
