### ISSUE TITLE
feat(patch): patch to hide endscreen on youtube app

### ISSUE THREAD

**Issue by woddyrock** [revanced/revanced-patches#566]
### Application

Youtube app

### Issue

Don't you hate when you are watching a music video or a movie clip and the climax part is blocked by those stupid intrusive end screen cards?

### Patch

request a patch to hide YouTube endscreen so you don't miss the climax part.

### Motivation

request to add an option to hide all end-screens from YouTube so your favorite scene won't be blocked!

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by johnconner122** [comment]
@oSumAtrIX 
it is implemented in following fork and working perfectly. Please port it to official revanced patches:

- https://github.com/inotia00/revanced-patches/blob/cf9f7ef2f04c36328e2597f5546b78aaa0154284/src/main/kotlin/app/revanced/patches/youtube/ad/general/bytecode/patch/GeneralBytecodeAdsPatch.kt#L136

**Comment by oSumAtrIX** [comment]
A separate for this is already open but needs a fair amount of refactoring.

**Comment by sawankumarbundelkhandi** [comment]
@oSumAtrIX isn't this completed with the patch `hide-endscreen-cards`? Am I missing anything?
