### ISSUE TITLE
excluding hide-cast-button patch still hides the cast button

### ISSUE THREAD

**Issue by JuliusDer** [revanced/revanced-patches#57]
in youtube vanced the cast button did only fail on chromecast but worked for example on lg tvs so i would like to leave the cast button enabled

Building revanced i get the message
```INFORMATION: Skipping hide-cast-button: Explicitly excluded```
but the button is still missing

**Comment by Itroublve** [comment]
> is there a reason why vanced could cast to lg tvs for example and revanced no longer can?

Vanced (non root) never could do that?

**Comment by TheJeterLP** [comment]
> is there a reason why vanced could cast to lg tvs for example and revanced no longer can?

No in my opinion there's no reason for that. The patch was just made a dependency. It's not actually needed as a dependency. You could open a PR to change that?

**Comment by TheJeterLP** [comment]
> https://en.m.wikipedia.org/wiki/Coupling_(computer_programming)
> 
> The idea of a dependency is that it is actually needed.

Well, who made it a dependency on ReVanced then?

**Comment by Aunali321** [comment]
I can make the PR if it's not really needed.

**Comment by TheJeterLP** [comment]
> I can make the PR if it's not really needed. 

Try it out :) Remove the dependecy in the microg patch and build it without hide-cast-button

**Comment by oSumAtrIX** [comment]
> > https://en.m.wikipedia.org/wiki/Coupling_(computer_programming)
> > The idea of a dependency is that it is actually needed.
> 
> Well, who made it a dependency on ReVanced then?

Its not about who made it but why it was made.
