### ISSUE TITLE
feat(YTMusic): SponsorBlock for podcasts

### ISSUE THREAD

**Issue by AlaskaJedi** [ReVanced/revanced-patches#573]
### Application

YT Music

### Issue

YT music now contains 'Podcasts' which are just youtube playlists in the music app, embedded ads that would be skipped by sponsor block when watching the video in youtube are not skipped. 

### Patch

Sponsor block for yt music.  

### Motivation

It would offer a better experience when using the new podcasts feature.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Bazoogle** [comment]
> Considering the user can just open YouTube and get SponsorBlock for the same podcasts, all of this work would result in adding a lot of code complexity for a minimal return.

I disagree with this conclusion, personally. Podcasts are generally going to be listened to while driving, jogging, or just doing any other activity likely where you aren't holding your phone, and the music control buttons are entirely different in YT vs YT Music. YT Music allows you to skip ahead 30 seconds and back 10 seconds with the next and previous song buttons, which can make the world of a difference when you're doing any of the above activities. If you're working out, or doing chores, or driving, being able to utitlize a bluetooth devices music controls makes a huge difference. If it were a YT video, you'd have to open the app and double tap the video to skip ahead or back, or drag the time seeker. Which wouldn't be fun to do if your hands were wet from washing dishes, for example.

I do think trying to keep it as DRY as possible would be ideal, especially if it's the same thing. It would minimize the work and maximize the users experience. While I don't know for sure, I have a feeling even a lot of the settings interface could be copied over from YT to save time as well, and could allow for other features to be integrated if desired in the future.

If this could be re-evaluated as a possible feature request, I know a lot of people would be very grateful, myself included.
