### ISSUE TITLE
Sponsor-block player buttons are visible by default

### ISSUE THREAD

**Issue by HeroGalak** [revanced/revanced-patches#575]
### Type

Cosmetic

### Bug description

SB player buttons are visible by default and don't work.

### Steps to reproduce

Patch YT 17.36.37 with manager

### Relevant log output

```shell
//
```

### Screenshots or videos

(in settings SB buttons are disabled)
![Screenshot_20220921-185250_YouTube](https://user-images.githubusercontent.com/69464248/191565357-d2da4da2-9349-47ac-b748-412c548f40d1.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by OxrxL** [comment]
Fixed: https://github.com/revanced/revanced-patches/pull/579
