### ISSUE TITLE
feat(YouTube): Enable/disable "slide left or right to seek" feature

### ISSUE THREAD

**Issue by LisoUseInAIKyrios** [ReVanced/revanced-patches#581]
### Application

YouTube

### Issue

The feature has been in testing for the last 2 years, and it's still handed out to some users and not used for everyone else.  It would be great if the feature could be enabled/disabled in app.

![Screenshot_2023-07-18-11-32-09-839_app revanced android youtube](https://github.com/ReVanced/revanced-patches/assets/18757054/3a0693ce-f1b5-439b-9124-38f23169aa35)

### Patch

Option to turn on/off the "swipe left and right to seek" feature.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
I think this is now possible by replacing the functionality
