### ISSUE TITLE
feat(patch): Sleep timer for YouTube and/or YouTube Music

### ISSUE THREAD

**Issue by hoang-himself** [revanced/revanced-patches#583]
### Application

YouTube
YouTube Vanced
YouTube Music

### Issue

With background playback, YouTube clients can be used as music players, making sleep timer an essential feature.

### Patch

Add a button to set a sleep timer, ideally with a choice to set a timer and let a track play until it ends.

### Motivation

With background playback, YouTube clients can be used as music players, making sleep timer an essential feature.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by souravdas142** [comment]
`Remind me to take a brake` and `Remind me when its bed time` under `Settings->General` is not helping ?

**Comment by hoang-himself** [comment]
@souravdas142 My use case is more like I enable auto play then go to sleep. The descriptions from the features you mentioned make them sound like they only show the reminder if the phone screen is on.
I haven't tried them yet, but I would love to have a quick access button on the player.

**Comment by souravdas142** [comment]
@hoang-himself  

> them sound like they only show the reminder if the phone screen is on

Yes, music is not stopping. I didn't try them ever. Sorry my bad.

And yes its most needed feature I also feel. 
**If its possible to implement please need to do by someone.**

**Comment by Fertanima** [comment]
The functions you mentioned are in the YouTube settings.

**Comment by Fertanima** [comment]
![Screenshot_20220923-152712_YouTube](https://user-images.githubusercontent.com/112704336/191950743-d623e8ab-62d2-4566-8e2b-19ea2e288d8b.jpg)

**Comment by hoang-himself** [comment]
@Fertanima I am aware of this feature, I'm gonna try them again.
My point is to have background playback stop after an interval.

**Comment by souravdas142** [comment]
@Fertanima  but they didn't work while screen is turned off and some videos or songs are playing in background.

but if your screen is on, then they worked. So like while listening songs or audio stories in this scenarios we need this patch to ne implemented

**Comment by ortonormal2007** [comment]
Undoubtedly, such patch is fascinating! I'd like to see this feature in the nearest update 💖

**Comment by hoang-himself** [comment]
[This](https://github.com/inotia00/revanced-patches/commit/22498750e7b8835eba8882a3c9b52d8fa31995f7) is pretty much what I'm looking for.

**Comment by oSumAtrIX** [comment]
This is a native feature by YouTube and not required to be patched.

**Comment by ortonormal2007** [comment]
It doesn't work while the screen is off.

**Comment by hoang-himself** [comment]
> This is a native feature by YouTube and not required to be patched.

Can you elaborate?

**Comment by Masamune3210** [comment]
its already a feature in the normal youtube app, you don't have to patch it in

**Comment by atlasyonatan** [comment]
for anyone that does't get how to achieve this with normal yt app:
https://support.google.com/youtube/answer/9884905?hl=en&co=GENIE.Platform%3DAndroid

it's not technically a sleep timer but can be used for that purpose
