### ISSUE TITLE
bug: patches not working on YouTube v17.37.35

### ISSUE THREAD

**Issue by ranasrule** [revanced/revanced-patches#587]
### Type

Error while patching

### Bug description

None of the patches seem to be working on YouTube v17.37.35

### Steps to reproduce

. 

### Relevant log output

```shell
.
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Canny1913** [comment]
1) Unsupported version.
2) You didn't complete the tasks as specified.
3) You didn't provide any information.
