### ISSUE TITLE
Account not detect in Youtube 

### ISSUE THREAD

**Issue by Khairulikhsn** [revanced/revanced-patches#60]
success build for Youtube v17.23.35 for root version with this command 
`java -jar revanced-cli-1.11.0-all.jar -a YouTube_17.23.35.apk -c -d a3e399cd -o revanced.apk -b revanced-patches-1.10.4.jar -m integrations_v0.14.0.apk -e amoled -e microg-support -e disable-shorts-button`

but my account not detect in youtube app.

i use:
- revanced-cli-1.11.0-all.jar
- revanced-patches-1.10.4.jar
- integrations_v0.14.0.apk
- YouTube_17.23.35.apk
- Root

output:
> java -jar revanced-cli-1.11.0-all.jar -a YouTube_17.23.35.apk -c -d a3e399cd -o revanced.apk -b revanced-patches-1.10.4.jar -m integrations_v0.14.0.apk -e amoled -e microg-support -e disable-shorts-button
INFO: Deleting existing resource cache directory
INFO: Decoding resources
INFO: Reading dex files
INFO: Merging integrations_v0.14.0.apk
INFO: Skipping amoled: Explicitly excluded
INFO: Skipping disable-shorts-button: Explicitly excluded
INFO: Skipping microg-support: Explicitly excluded
WARNING: Skipping background-play: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
WARNING: Skipping exclusive-audio-playback: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
WARNING: Skipping codecs-unlock: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
WARNING: Skipping upgrade-button-remover: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
WARNING: Skipping tasteBuilder-remover: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
INFO: seekbar-tapping succeeded
INFO: general-ads succeeded
INFO: video-ads succeeded
INFO: custom-branding succeeded
INFO: premium-heading succeeded
INFO: minimized-playback succeeded
INFO: disable-fullscreen-panels succeeded
INFO: old-quality-layout succeeded
INFO: disable-create-button succeeded
INFO: hide-cast-button succeeded
INFO: Compiling resources
INFO: Writing modified dex files
INFO: Writing dex file classes3.dex
INFO: Writing dex file classes.dex
INFO: Writing dex file classes2.dex
INFO: Writing dex file classes4.dex
INFO: Writing dex file classes6.dex
INFO: Writing dex file classes5.dex
INFO: Writing dex file classes8.dex
INFO: Writing dex file classes7.dex
INFO: Writing resources
INFO: Aligning revanced_raw.apk
INFO: Signing revanced_aligned.apk
INFO: Found existing keystore: revanced
INFO: Copying revanced_signed.apk to revanced.apk
INFO: Installing without mounting
INFO: Finished

**Comment by DanGLES3** [comment]
> success build for Youtube v17.23.35 for root version with this command `java -jar revanced-cli-1.11.0-all.jar -a YouTube_17.23.35.apk -c -d a3e399cd -o revanced.apk -b revanced-patches-1.10.4.jar -m integrations_v0.14.0.apk -e amoled -e microg-support -e disable-shorts-button`
> 
> but my account not detect in youtube app.
> 
> i use:
> 
> * revanced-cli-1.11.0-all.jar
> * revanced-patches-1.10.4.jar
> * integrations_v0.14.0.apk
> * YouTube_17.23.35.apk
> * Root
> 
> output:
> 
> > java -jar revanced-cli-1.11.0-all.jar -a YouTube_17.23.35.apk -c -d a3e399cd -o revanced.apk -b revanced-patches-1.10.4.jar -m integrations_v0.14.0.apk -e amoled -e microg-support -e disable-shorts-button
> > INFO: Deleting existing resource cache directory
> > INFO: Decoding resources
> > INFO: Reading dex files
> > INFO: Merging integrations_v0.14.0.apk
> > INFO: Skipping amoled: Explicitly excluded
> > INFO: Skipping disable-shorts-button: Explicitly excluded
> > INFO: Skipping microg-support: Explicitly excluded
> > WARNING: Skipping background-play: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
> > WARNING: Skipping exclusive-audio-playback: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
> > WARNING: Skipping codecs-unlock: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
> > WARNING: Skipping upgrade-button-remover: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
> > WARNING: Skipping tasteBuilder-remover: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
> > INFO: seekbar-tapping succeeded
> > INFO: general-ads succeeded
> > INFO: video-ads succeeded
> > INFO: custom-branding succeeded
> > INFO: premium-heading succeeded
> > INFO: minimized-playback succeeded
> > INFO: disable-fullscreen-panels succeeded
> > INFO: old-quality-layout succeeded
> > INFO: disable-create-button succeeded
> > INFO: hide-cast-button succeeded
> > INFO: Compiling resources
> > INFO: Writing modified dex files
> > INFO: Writing dex file classes3.dex
> > INFO: Writing dex file classes.dex
> > INFO: Writing dex file classes2.dex
> > INFO: Writing dex file classes4.dex
> > INFO: Writing dex file classes6.dex
> > INFO: Writing dex file classes5.dex
> > INFO: Writing dex file classes8.dex
> > INFO: Writing dex file classes7.dex
> > INFO: Writing resources
> > INFO: Aligning revanced_raw.apk
> > INFO: Signing revanced_aligned.apk
> > INFO: Found existing keystore: revanced
> > INFO: Copying revanced_signed.apk to revanced.apk
> > INFO: Installing without mounting
> > INFO: Finished

That's because the patcher will default to install rather than mount (which is the method needed for the root install) you need to specify --mount in the build commands for the root version to work

**Comment by Khairulikhsn** [comment]
> 

i try it but get this

> java -jar revanced-cli-1.11.0-all.jar -a YouTube_17.23.35.apk -c -d a3e399cd -o revanced.apk -b revanced-patches-1.10.4.jar -m integrations_v0.14.0.apk -e amoled -e microg-support -e disable-shorts-button --mount
INFO: Decoding resources
INFO: Reading dex files
INFO: Merging integrations_v0.14.0.apk
INFO: Skipping amoled: Explicitly excluded
INFO: Skipping disable-shorts-button: Explicitly excluded
INFO: Skipping microg-support: Explicitly excluded
WARNING: Skipping background-play: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
WARNING: Skipping exclusive-audio-playback: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
WARNING: Skipping codecs-unlock: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
WARNING: Skipping upgrade-button-remover: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
WARNING: Skipping tasteBuilder-remover: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
INFO: seekbar-tapping succeeded
INFO: general-ads succeeded
INFO: video-ads succeeded
INFO: custom-branding succeeded
INFO: premium-heading succeeded
INFO: minimized-playback succeeded
INFO: disable-fullscreen-panels succeeded
INFO: old-quality-layout succeeded
INFO: disable-create-button succeeded
INFO: hide-cast-button succeeded
INFO: Compiling resources
INFO: Writing modified dex files
INFO: Writing dex file classes.dex
INFO: Writing dex file classes2.dex
INFO: Writing dex file classes3.dex
INFO: Writing dex file classes4.dex
INFO: Writing dex file classes8.dex
INFO: Writing dex file classes5.dex
INFO: Writing dex file classes7.dex
INFO: Writing dex file classes6.dex
INFO: Writing resources
INFO: Installing by mounting
06-24 10:40:18.083 11750 11750 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
06-24 10:40:18.087 11750 11750 I AndroidRuntime: Using default boot image
06-24 10:40:18.087 11750 11750 I AndroidRuntime: Leaving lock profiling enabled
06-24 10:40:18.175 11750 11750 D AndroidRuntime: Calling main entry com.android.commands.content.Content
06-24 10:40:18.189 11750 11750 D AndroidRuntime: Shutting down VM
06-24 10:40:18.567 11861 11861 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
06-24 10:40:18.570 11861 11861 I AndroidRuntime: Using default boot image
06-24 10:40:18.570 11861 11861 I AndroidRuntime: Leaving lock profiling enabled
06-24 10:40:18.672 11861 11861 D AndroidRuntime: Calling main entry com.android.commands.content.Content
06-24 10:40:18.689 11861 11861 D AndroidRuntime: Shutting down VM
06-24 10:40:19.616 11965 11965 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
06-24 10:40:19.618 11965 11965 I AndroidRuntime: Using default boot image
06-24 10:40:19.618 11965 11965 I AndroidRuntime: Leaving lock profiling enabled
06-24 10:40:19.701 11965 11965 D AndroidRuntime: Calling main entry com.android.commands.content.Content
06-24 10:40:19.715 11965 11965 D AndroidRuntime: Shutting down VM
06-24 10:40:20.687 12002 12002 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
06-24 10:40:20.689 12002 12002 I AndroidRuntime: Using default boot image
06-24 10:40:20.689 12002 12002 I AndroidRuntime: Leaving lock profiling enabled
06-24 10:40:20.799 12002 12002 D AndroidRuntime: Calling main entry com.android.commands.content.Content
06-24 10:40:20.816 12002 12002 D AndroidRuntime: Shutting down VM

and this looping until now

> 06-24 10:40:18.083 11750 11750 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
06-24 10:40:18.087 11750 11750 I AndroidRuntime: Using default boot image
06-24 10:40:18.087 11750 11750 I AndroidRuntime: Leaving lock profiling enabled
06-24 10:40:18.175 11750 11750 D AndroidRuntime: Calling main entry com.android.commands.content.Content
06-24 10:40:18.189 11750 11750 D AndroidRuntime: Shutting down VM

**Comment by DanGLES3** [comment]
> > 
> 
> i try it but get this
> 
> > java -jar revanced-cli-1.11.0-all.jar -a YouTube_17.23.35.apk -c -d a3e399cd -o revanced.apk -b revanced-patches-1.10.4.jar -m integrations_v0.14.0.apk -e amoled -e microg-support -e disable-shorts-button --mount
> > INFO: Decoding resources
> > INFO: Reading dex files
> > INFO: Merging integrations_v0.14.0.apk
> > INFO: Skipping amoled: Explicitly excluded
> > INFO: Skipping disable-shorts-button: Explicitly excluded
> > INFO: Skipping microg-support: Explicitly excluded
> > WARNING: Skipping background-play: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
> > WARNING: Skipping exclusive-audio-playback: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
> > WARNING: Skipping codecs-unlock: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
> > WARNING: Skipping upgrade-button-remover: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
> > WARNING: Skipping tasteBuilder-remover: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
> > INFO: seekbar-tapping succeeded
> > INFO: general-ads succeeded
> > INFO: video-ads succeeded
> > INFO: custom-branding succeeded
> > INFO: premium-heading succeeded
> > INFO: minimized-playback succeeded
> > INFO: disable-fullscreen-panels succeeded
> > INFO: old-quality-layout succeeded
> > INFO: disable-create-button succeeded
> > INFO: hide-cast-button succeeded
> > INFO: Compiling resources
> > INFO: Writing modified dex files
> > INFO: Writing dex file classes.dex
> > INFO: Writing dex file classes2.dex
> > INFO: Writing dex file classes3.dex
> > INFO: Writing dex file classes4.dex
> > INFO: Writing dex file classes8.dex
> > INFO: Writing dex file classes5.dex
> > INFO: Writing dex file classes7.dex
> > INFO: Writing dex file classes6.dex
> > INFO: Writing resources
> > INFO: Installing by mounting
> > 06-24 10:40:18.083 11750 11750 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
> > 06-24 10:40:18.087 11750 11750 I AndroidRuntime: Using default boot image
> > 06-24 10:40:18.087 11750 11750 I AndroidRuntime: Leaving lock profiling enabled
> > 06-24 10:40:18.175 11750 11750 D AndroidRuntime: Calling main entry com.android.commands.content.Content
> > 06-24 10:40:18.189 11750 11750 D AndroidRuntime: Shutting down VM
> > 06-24 10:40:18.567 11861 11861 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
> > 06-24 10:40:18.570 11861 11861 I AndroidRuntime: Using default boot image
> > 06-24 10:40:18.570 11861 11861 I AndroidRuntime: Leaving lock profiling enabled
> > 06-24 10:40:18.672 11861 11861 D AndroidRuntime: Calling main entry com.android.commands.content.Content
> > 06-24 10:40:18.689 11861 11861 D AndroidRuntime: Shutting down VM
> > 06-24 10:40:19.616 11965 11965 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
> > 06-24 10:40:19.618 11965 11965 I AndroidRuntime: Using default boot image
> > 06-24 10:40:19.618 11965 11965 I AndroidRuntime: Leaving lock profiling enabled
> > 06-24 10:40:19.701 11965 11965 D AndroidRuntime: Calling main entry com.android.commands.content.Content
> > 06-24 10:40:19.715 11965 11965 D AndroidRuntime: Shutting down VM
> > 06-24 10:40:20.687 12002 12002 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
> > 06-24 10:40:20.689 12002 12002 I AndroidRuntime: Using default boot image
> > 06-24 10:40:20.689 12002 12002 I AndroidRuntime: Leaving lock profiling enabled
> > 06-24 10:40:20.799 12002 12002 D AndroidRuntime: Calling main entry com.android.commands.content.Content
> > 06-24 10:40:20.816 12002 12002 D AndroidRuntime: Shutting down VM
> 
> and this looping until now
> 
> > 06-24 10:40:18.083 11750 11750 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
> > 06-24 10:40:18.087 11750 11750 I AndroidRuntime: Using default boot image
> > 06-24 10:40:18.087 11750 11750 I AndroidRuntime: Leaving lock profiling enabled
> > 06-24 10:40:18.175 11750 11750 D AndroidRuntime: Calling main entry com.android.commands.content.Content
> > 06-24 10:40:18.189 11750 11750 D AndroidRuntime: Shutting down VM

Make sure to check if the shell process has root access on Magisk

**Comment by Apihplays** [comment]
from my view , if the looping still continue , ctrl+c it . then open your normal youtube app , play some video , if not ads starting . then it is worked !🗿

**Comment by Khairulikhsn** [comment]
> from my view , if the looping still continue , ctrl+c it . then open your normal youtube app , play some video , if no ads starting . then it is worked !🗿

is worked, thanks
