### ISSUE TITLE
feat (YT Music/`Enable Old Minimized Player`): Enables the Old Swipe To Dismiss Minimized Player 

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [ReVanced/revanced-patches#601]
### Application

YT Music

### Issue

Recently, YouTube Music removed the ability to swipe down on the minimized player to stop playing music in its latest versions. This feature was highly appreciated by users as it provided a convenient and intuitive way to control playback without needing to expand the player or navigate to a different screen. Removing this feature has caused frustration and inconvenience for many users.

### Patch

A patch that brings back the swipe down gesture to stop playing music on the minimized player. This feature was widely appreciated and integrated well with the overall user experience. By reinstating this functionality, YouTube Music can enhance user satisfaction, improve ease of use, and align with user expectations.

### Motivation

1) Improved User Experience: The swipe down gesture to stop playing music offered a seamless and effortless user experience. It allowed users to quickly and easily pause or stop playback without the need for additional taps or navigating to different screens.

2) Intuitive and Familiar Interaction: The swipe down gesture is a widely recognized and natural action in mobile interfaces. Users have become accustomed to using this gesture for various purposes across different applications. By removing this feature, YouTube Music has deviated from the expected behavior and disrupted the user's muscle memory.

3) Minimized Player Control: The minimized player is designed to provide users with a non-intrusive way to control their music while simultaneously browsing or using other apps. The swipe down gesture to stop playback was a crucial functionality within this context. Users could effortlessly stop music without interrupting their current activity.

4) Accessibility Considerations: The swipe down gesture was especially valuable for users with accessibility needs. It provided a simple and accessible way to pause or stop music without requiring precise tapping or navigation. Removing this feature limits the accessibility options for such users.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
