### ISSUE TITLE
feat (YT Music/`Amoled Black Theme`): Forces Amoled Black Theme throughout the YT Music UI

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [ReVanced/revanced-patches#609]
### Application

YT Music 

### Issue

Currently, YT Music lacks several customization features that could greatly enhance user experience and personalization within the music streaming platform. I would like to propose the implementation of several theming and customization options for YT Music, similar to the features available in the YouTube app.

### Patch

Currently, YT Music features elements in gray color. It would be great to have an option to change these elements to black, creating an overall black theme. This will provide a sleek and visually appealing interface for users who prefer darker themes.

### Motivation

By implementing these theming and customization options, YT Music will offer users greater control over their experience and allow them to tailor the app according to their preferences. These enhancements will contribute to a more personalized and enjoyable music streaming experience overall.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!

**Comment by ILoveOpenSourceApplications** [comment]
@LisoUseInAIKyrios, can we implement [patches/src/main/kotlin/app/revanced/patches/music/general/amoled/AmoledPatch.kt](https://github.com/inotia00/revanced-patches/blob/2b0f12cb9eff3ab0f66fdbe65e9482c29383befd/patches/src/main/kotlin/app/revanced/patches/music/general/amoled/AmoledPatch.kt)? Or more simply, if I were to PR this do we need any changes or is it good as is? He has also separated the navigation bar theme into a different patch [extensions/shared/src/main/java/app/revanced/extension/music/patches/navigation/NavigationPatch.java](https://github.com/inotia00/revanced-patches/blob/2b0f12cb9eff3ab0f66fdbe65e9482c29383befd/extensions/shared/src/main/java/app/revanced/extension/music/patches/navigation/NavigationPatch.java#L15-#L23). So, if we're to combine it all to a single AMOLED theme patch would it be too much or be something simple?

**Comment by ILoveOpenSourceApplications** [comment]
Understandable. But can you look at the code and give your opinion? Is it fine as is or will it have to be refactored a lot?

**Comment by oSumAtrIX** [comment]
Instead of duplicating patches, the Theme patch should be abstracted to support YT Music.

**Comment by ILoveOpenSourceApplications** [comment]
Adapt YouTube's theme patch [patches/src/main/kotlin/app/revanced/patches/youtube/layout/theme/ThemePatch.kt](https://github.com/ReVanced/revanced-patches/blob/979565e7b599414754d3887d3b625698be164844/patches/src/main/kotlin/app/revanced/patches/youtube/layout/theme/ThemePatch.kt) TO support Music as well? Is it easily achievable?
