### ISSUE TITLE
feat(patch): Remove “My Mix” Suggestions

### ISSUE THREAD

**Issue by anil-al** [revanced/revanced-patches#611]
### Application

YouTube

### Issue

When it comes to recommendations, YouTube is very aggressive about suggesting things. Even you watch just one video once or you listen music videos much, you will be recommended related videos under the name “My Mix” and the only way to get rid of these is to delete those videos from “Watch History”.
![Screenshot_20220924_180308](https://user-images.githubusercontent.com/101948963/192105084-15233847-055e-4f2d-ab67-82ec1ca4fb1f.png)
![Screenshot_20220924_182145](https://user-images.githubusercontent.com/101948963/192105964-f75c18f3-8d3b-4aad-9fc8-511c75a7e4a7.png)

### Patch

A patch removing “My Mix”es from “Home” tab and “Video Player” page

### Motivation

YouTube's aggressive recommendation policy and unrelated suggestions. It is inconvenient to delete videos from history every single time.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by svgPhoenix** [comment]
Came here to suggest the same thing
