### ISSUE TITLE
Video ads are showing

### ISSUE THREAD

**Issue by Dhrubaof2002** [revanced/revanced-patches#612]
### Type

Other

### Bug description

Unskippable video ads are showing

### Steps to reproduce

![Screenshot_2022-09-24-22-14-35-530_app revanced manager flutter](https://user-images.githubusercontent.com/64865031/192109842-ae07b8d7-5d4e-4fa0-b62b-96bc12cbc9db.jpg)

### Relevant log output

```shell
.
```

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Dhrubaof2002** [comment]
Why are you closing this issue?

**Comment by oSumAtrIX** [comment]
Acknowledgements not met
