### ISSUE TITLE
bug: Getting 2 unskippable ads before some videos

### ISSUE THREAD

**Issue by Impulse666** [revanced/revanced-patches#613]
### Type

Other

### Bug description

The Video Ads patch for Youtube is not currently patching the new 2 unskippable ads that play before **some** videos. This issue was reproduced by me and some other users from ReVanced subreddit.

After some testing, it seems like this issue happens only on some Google Accounts, which explains why many people do not experience this, yet. However there's a possibility this might expanded to them as well in the near future.

### Steps to reproduce

I tried patching multiple different versions of:
- ReVanced Builder (by reisxd) both on Termux and Win10;
- ReVanced Manager Alpha;
- ReVanced CLI with the prebuilt packages (multiple versions of the patches + youtube apk).

I also tried different combinations of patches and made sure the Ads settings in-app were correctly set.

All this on 2 different devices (1 tablet and 1 smartphone) from different brands with different android versions.

### Relevant log output

```shell
No logs available.
```

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Impulse666** [comment]
Seems like someone else just posted the same issue some minutes before I did:
https://github.com/revanced/revanced-patches/issues/612

**Comment by Dhrubaof2002** [comment]
Why are you completing this issue?oSumAtrlx

**Comment by Impulse666** [comment]
> Why are you completing this issue?oSumAtrlx

Right?
An explanation would be appreciated since we took the time to come here and create an issue to help the developers.

**Comment by oSumAtrIX** [comment]
Acknowledgements not met.

**Comment by Impulse666** [comment]
Thank you, I see it now. 
Duplicate of https://github.com/revanced/revanced-patches/issues/40
