### ISSUE TITLE
bug: Can not exit the app by pressing back button or using the back gesture.

### ISSUE THREAD

**Issue by ANi1XO** [revanced/revanced-patches#615]
### Type

Error at runtime

### Bug description

usually to exit the app, i just swipe back (gesture). but on revanced patch 2.69.0 when i try to exit the app this way, nothing happens at all. only way i can exit the app now is by pressing home button (swipe up gesture). i can see several users are also getting this bug.
Im on youtube version 17.36.37 cli v2.11.2 patches v2.69.0 (same issue can be seen on patch 2.60.0)

### Steps to reproduce

open app
Open revanced settings
Open layout settings
Change anything in layout settings that will prompt a restart.
Once the app restarts the bug is introduced and pressing back to exit app will stop working.

### Relevant log output

```shell
Null
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by webzeroacs** [comment]
This is a known issue. I think Remove general ads is the problem. If you change this part to general ads are shown, the back button will exit well. If you turn off Remove general ads, there will be Home ads and ads under the video.

**Comment by killerlearner** [comment]
Yeah check #599

**Comment by rewqazxv** [comment]
Pull-to-refresh also doesn't work when you can't exit, caused by Remove general ads too

**Comment by ANi1XO** [comment]
With patch 2.81.0, there is a way to circumvent this bug. Do a fresh install, go to settings, change settings to your desire,

**Comment by SodaWithoutSparkles** [comment]
Can reproduce the issue. My current method of exiting is to open recent tasks and kill the app

**Comment by Kalpataru6** [comment]
Yeah.. 3 button nevigation's back button also don't exist the app .
