### ISSUE TITLE
feat(patch): YouTube Music for Android auto 

### ISSUE THREAD

**Issue by OmerET8** [revanced/revanced-patches#619]
### Application

YouTube Music for Android auto 

### Issue

In Android Auto only the "now playing"  screen is working, and you can control the app only using the Google Assistant. But all the other UI elements are not working (song selection, explore, library)

### Patch

Bring usability to the app for non premium users.

### Motivation

This patch would be valuable to people who want to listen to music in their car.

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by fobi87** [comment]
same problem here witn new android auto coolwalk.

**Comment by oSumAtrIX** [comment]
Dupe of https://github.com/revanced/revanced-patches/issues/305
