### ISSUE TITLE
No history of search showing when not loged in in revanced.

### ISSUE THREAD

**Issue by EXAM454** [revanced/revanced-patches#62]
When revanced in not loged in with google acocunt ,no rearch history is showing. But with playstore apk search history is showing when not logged in.

**Comment by oSumAtrIX** [comment]
Can not reproduce. Build from source and disable patches until the error disappears then open a detailed issue.

**Comment by gosndka** [comment]
> Can not reproduce. Build from source and disable patches until the error disappears then open a detailed issue.

I also face the same issue, since I can't view my search history even though I have turned off the pause search history function.

**Comment by oSumAtrIX** [comment]
Disable system adblockers such as adaway.

**Comment by gosndka** [comment]
> Disable system adblockers such as adaway.

what? I have no such thing on my phone
