### ISSUE TITLE
feat(patch): ReactNative

### ISSUE THREAD

**Issue by rihaq** [revanced/revanced-patches#622]
### Application

facebook, instagram, whatsapp and facebook messenger 

### Issue

Advertisement 

### Patch

Alternative of Whatsaero & Instander

### Motivation

No trustable mod exist for facebook

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Aunali321** [comment]
Not possible. Revanced Patcher doesn't support patching React Native apps (Only Dalvik).

**Comment by rihaq** [comment]
> Not possible. 

Opened this issue for a reason

**Comment by Aunali321** [comment]
No it will not be implemented for a long time. maybe never.

**Comment by Aunali321** [comment]
@oSumAtrIX close the issue.
