### ISSUE TITLE
Info-cards (not endcards) are hidden all the time

### ISSUE THREAD

**Issue by Hokyps** [revanced/revanced-patches#623]
### Type

Cosmetic

### Bug description

It doesn't matter if I turn on or off the toggle "Show-infocards" they aren't visible anyways. 

### Steps to reproduce

Just try playing any video with info-cards like this one: https://youtu.be/qiVqicC8sIA 

### Relevant log output

```shell
Don't know how to get one.
```

### Screenshots or videos

![Screenshot_20220924-173935_YouTube](https://user-images.githubusercontent.com/111386632/192156810-9a12ec3b-bd69-4362-ae05-cdce334ca5bd.jpg)

![Screenshot_20220924-174309_YouTube](https://user-images.githubusercontent.com/111386632/192156825-ca7de907-0070-43fb-804f-afcfb7a61d04.jpg)

![Screenshot_20220924-175709](https://user-images.githubusercontent.com/111386632/192156831-2c55062a-4b9c-4483-a9f6-abdd48ce14ae.jpg)

### Solution

Excluding the patch "Hide infocards suggestions" while building the apk fixes the problem. 

### Additional context

Build my Revanced with Revanced builder.
Youtube version: 17.36.37
Cli: 2.11.2
Patches: 2.69.1
Integrations: 0.42.2

### Acknowledgements

- [x] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by SodaWithoutSparkles** [comment]
can reproduce the issue. Did the maintainer of the patch forgot something?

**Comment by furquim87** [comment]
I'm getting a similar issue as well, although a bit different: the info cards do show up here, but they disappear a split second after showing up. They also seem to have a problem with full screen panels, as they won't show whenever I enable them. I'm using j-hc build, but the same issue happens when building via the official ReVanced Manager.

**Comment by Hokyps** [comment]
> I'm getting a similar issue as well, although a bit different: the info cards do show up here, but they disappear a split second after showing up. They also seem to have a problem with full screen panels, as they won't show whenever I enable them, unless I enter full screen mode, open one of the panels and close it. I'm using j-hc build, but the same issue happens when building via the official ReVanced Manager.

You could try patching the app again without including the infocard patch.

**Comment by johnconner122** [comment]
Please close the issue if fixed.
