### ISSUE TITLE
Seeing ads in youtube shorts 

### ISSUE THREAD

**Issue by vasile-coste** [revanced/revanced-patches#624]
### Type

Other

### Bug description

I was browsing the shorts tab on YouTube and while scrolling trough videos, ads are appearing between videos

### Steps to reproduce

Open youtube app, 
Go to shorts section, 
Go trough videos
Ads are popping(but they can be skipped)

### Relevant log output

```shell
-
```

### Screenshots or videos

![Screenshot_20220925-225316_YouTube](https://user-images.githubusercontent.com/17108452/192163005-7d5cd270-6d78-44d9-989a-ab2bde8c4b21.jpg)

### Additional context

Samsing s10e 
Android 12
Youtube 17.36.37
Patch version 2.68.0

### Acknowledgements

- [x] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
There is no ad removal patch for shorts.
