### ISSUE TITLE
bug: Long pressing save button does not show list of playlists

### ISSUE THREAD

**Issue by AhsanShahBukhari** [revanced/revanced-patches#625]
### Type

Other

### Bug description

There's a "save" button under playing video when tapped, saves the video to "watch later" playlist. 
![Screenshot_2022-09-26-01-23-15-01-01](https://user-images.githubusercontent.com/28642548/192165173-31139f19-0457-48f7-8464-1ab0f5e59481.jpeg)
This button however, when long pressed, should prompt the list of your playlists for you to choose a playlist to add the video to. Here's is the screenshot of normal YouTube app doing that:
![Screenshot_2022-09-26-01-10-52-01](https://user-images.githubusercontent.com/28642548/192165331-557dea97-26f0-4326-944e-d8ede2019459.jpeg)

This isn't happening in REVANCED App and the prompt is missing the list of playlists and only has "new playlist" and "done" buttons. Below is the screenshot of REVANCED bug:
![Screenshot_2022-09-26-01-23-15-01](https://user-images.githubusercontent.com/28642548/192165429-2604cf19-e0b7-4776-86e9-0b5ac5b79c0a.jpeg)

### Steps to reproduce

1. Open REVANCED App
2. Long press "save" button

### Relevant log output

```shell
Couldn't find the log file. Here's five basic info that might or might not help:
LG G7 model: LM-G710ULM
Android 8.0.0
Patched YouTube version: v17.36.37
Using revanced manager.
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by vuongvan** [comment]
I'm having the same problem on Youtube 17.41.37 with latest patch 2.100.0.

Command i used:
`java -jar temp/revanced-cli.jar -c -a temp/youtube-stock-v17.41.37-all.apk -o build/revanced-v17.41.37-p2.100.0.apk -b temp/revanced-patches-2.100.0.jar --keystore=ks.keystore -e custom-branding -e premium-heading -e theme -e hide-shorts-button -e hide-create-button -m temp/app-release-unsigned-v0.64.0.apk`
