### ISSUE TITLE
feat(patch): Netflix full HD playback for Widevine L3 devices

### ISSUE THREAD

**Issue by PolicyPuma4** [revanced/revanced-patches#639]
### Application

Netflix.

### Issue

People that prefer to use custom Android ROMs on their older devices that lose support from their manufacturer often are forced to give up Widevine L1 when the unlock their bootloader. When Netflix detects you don't have Widevine L1 it will only allow SD playback. There used to be modded APKs going around that would bypass this issue however it's been long since I've seen one that I'd trust. Given ReVanced is an open source client sided APK patcher I couldn't think of anything I'd trust more.

### Patch

Force allowing HD playback on Widevine L3 devices. Currently Netflix limits you to SD on none Widevine L1 devices.

### Motivation

I myself would love to not have to choose between an outdated official ROM with Widevine L1 and a custom up-to-date community maintained one without. Just search `unlocked bootloader widevine l1 netflix` on your favorite search engine and you'll see how many people face this issue and how many request for ways to fix it.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Widevine is implemented natively and thus out of the scope of ReVanced.
