### ISSUE TITLE
Fully decode litho

### ISSUE THREAD

**Issue by OxrxL** [revanced/revanced-patches#64]
This is an idea thought about, while talking to @oSumAtrIX, to replace the current ad blocking solution.

In practice: avoid that litho views are added starting from the root tree.

This should be useful to convert shorts videos to normal videos too.

**Comment by oSumAtrIX** [comment]
What do you mean by root tree.

**Comment by OxrxL** [comment]
> What do you mean by root tree.

The array list where views are stored.

**Comment by oSumAtrIX** [comment]
Can you link to that array list.

**Comment by OxrxL** [comment]
> Can you link to that array list.

I posted this as an issue, because I don't know where to find this list.
