### ISSUE TITLE
feat(patch): Disable Youtube's automatic thumbnail previews

### ISSUE THREAD

**Issue by sameyepatch** [revanced/revanced-patches#642]
### Application

Youtube

### Issue

Automatic "thumbnail" previews. They sometimes affect history and suggestions (as far as I know).

### Patch

The patch should disable thumbnail previews or provide an option to disable them.

### Motivation

Saving data and potentially preventing unwanted suggestions in the recommended feed.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by bogadana** [comment]
settings -> general -> playback in feeds -> off
