### ISSUE TITLE
feat(patch): 

### ISSUE THREAD

**Issue by Hacked1209** [revanced/revanced-patches#659]
### Application

This is for spotify

### Issue

This is a patch request for spotify

### Patch

Pls make a patch for Spotify enabling all premium features like download no ads and unlimited skips

### Motivation

This is very important as not all of us have money to buy premium but we like spotify

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
#450
