### ISSUE TITLE
VP9 settings removal

### ISSUE THREAD

**Issue by OxrxL** [revanced/revanced-patches#66]
After having a new conversation with @oSumAtrIX, we concluded that a toggle in Revanced settings is not needed because VP9 codec is enabled by default (and not because of the deprecation, as I wrongly wrote earlier).

So @TheJeterLP, like said before, you could remove the relative toggle from integrations.

**Comment by TheJeterLP** [comment]
> After having a new conversation with @oSumAtrIX, we concluded that a toggle in Revanced settings is not needed because VP9 codec is enabled by default (and not because of the deprecation, as I wrongly wrote earlier).
> 
> So @TheJeterLP, like said before, you could remove the relative toggle from integrations.

Alright, I will do that tomorrow then

**Comment by oSumAtrIX** [comment]
Before removing anything from the integrations we should first come to the point where we check for VP9. Before that we can not be sure.

**Comment by TheJeterLP** [comment]
> Before removing anything from the integrations we should first come to the point where we check for VP9. Before that we can not be sure.

Well, then I'll wait till you're sure.

**Comment by TheJeterLP** [comment]
Since there are still phones wo are not using VP9 by default, this is invalid.
