### ISSUE TITLE
bug: full screen = crash every time 

### ISSUE THREAD

**Issue by ballo** [revanced/revanced-patches#660]
### Type

Error at runtime

### Bug description

No matter what version of ReVanced I install from apk or patch using the manager, going full screen (via the full screen button or rotating the phone) immediately causes the app to crash 100% of the time.

### Steps to reproduce

1: make the video go full screen
2: there is no step 2

### Relevant log output

```shell
I looked online how to do this and came up empty. I don't see an option for this anywhere.
```

### Additional context

This is on a Samsung S8 running Android 9. It is impooto root this phone 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
https://user-images.githubusercontent.com/13122796/192914464-079e82f9-8863-4c63-952e-ee25e5d19a31.mp4

**Comment by ballo** [comment]
I don't know what the point of this reply is. If I click the full screen button or rotate it crashes 100% of the time.
