### ISSUE TITLE
bug: SponsorBlock- New Segment adding doesn't work

### ISSUE THREAD

**Issue by hridoysarkar050** [revanced/revanced-patches#663]
### Type

Error at runtime

### Bug description

While submitting a new segment using Sponsorblock, segment is not submitted. 

### Steps to reproduce

Open ReVanced app. 
Add a new segment. It fails. 

### Relevant log output

```shell
Not applicable
```

### Additional context

YouTube ReVanced version 16.36.37 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
In the SponsorBlock settings, did you add your user id?

**Comment by SodaWithoutSparkles** [comment]
Cannot reproduce the issue. Did you join the discord server and link your public ID? did you have a private ID under settings > sponsorblock > private user ID? Did you try again? The sponsorblock server frequently experience downtime, and its status can be checked [here](https://status.sponsor.ajay.app/)
