### ISSUE TITLE
(patch): Default Video Quality 

### ISSUE THREAD

**Issue by zatchbell04** [revanced/revanced-patches#664]
### Application

Hey Developers,I want to give a suggestion about adding default video quality in wifi and network in revanced settings.This is also available in vanced youtube.Revanced settings has similar features but if possible give us a option as 144p,360p,480p etc..
![Document 20_1](https://user-images.githubusercontent.com/71206003/192961704-3c5dcf57-1a3f-4882-ae02-55f73c72ce35.jpg)
![Document 20_2](https://user-images.githubusercontent.com/71206003/192962251-dd23f72a-6672-43ee-942d-0aecaeca6c10.jpg)

### Issue

No issue just a request 

### Patch

Using the patch revanced should give all available quality of video and we can set them to default for all video.This will help minimise the need of data.Thank you

### Motivation

I know that all developer are busy making revanced stable and providing this great app patches.You all are doing a great work which is very hard.I am not saying that this patch must be made but if you feel that revanced need this pls consider this request.Thank you for making this app and if I waste your time then I apologise.Please consider this and if I am wrong pls teach me about how to do it and tell me what I do wrong.Thank you

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by bogadana** [comment]
already exists with `remember-video-quality` patch

**Comment by zatchbell04** [comment]
Thanku

**Comment by zatchbell04** [comment]
Thanku

**Comment by johnconner122** [comment]
Default video quality is implemented in inotia00's fork, we just have to implement it:
https://github.com/inotia00/

**Comment by zatchbell04** [comment]
> Default video quality is implemented in inotia00's fork, we just have to port it: https://github.com/inotia00/

I will try.Thanku

**Comment by Canny1913** [comment]
default-video-quality existed in revanced but it was replaced with remember-video-quality.

**Comment by zatchbell04** [comment]
> default-video-quality existed in revanced but it was replaced with remember-video-quality.

I got it👍
