### ISSUE TITLE
feat(patch): Support 2.5X Playback Speed for YouTube

### ISSUE THREAD

**Issue by metacrab** [revanced/revanced-patches#671]
### Application

YouTube

### Issue

Currently the only supported YouTube playback speeds are 0.25, 0.5, 0.75, 1.0, 1.25, 1.5, 1.75, 2.0, 3.0, 4.0 and 5.0 (as per screenshot below).

It is not possible at the moment to watch videos on any other speed. On desktop I watch most videos at 2.5X speed.

![Screenshot_20220929-200037](https://user-images.githubusercontent.com/3057958/193122493-ff78dee9-aff2-4a53-83d9-199e7a76e5a2.jpg)

### Patch

As a quick fix, support for 2.5X speed increment should be added. The jump from 2 to 3 is vast. After 3, smaller increments become less important. I would guest almost nobody is watching at 4X or 5X speed. 

Long term, the increment jumps and min/max range could be customisable by the user, so if they have a preferred speed they can add it to the list, as well as remove speeds they never use. 

For a quick but broader fix, you could consider adding 0.25 increments for at least 2 through 3. 

### Motivation

On desktop, my chrome plugin lets me watch YouTube videos at 2.5X speed. Revanced only allows me to watch at 2X or 3X. I checked the code and it should be a simple change (though I don't understand the language / workflow well enough to open a PR). 2.5X is a popular sweet spot for playback speed that should be included, especially since it's so easy to add.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
This is already possible: https://github.com/revanced/revanced-patches/blob/1581bef4d1a6ee61f26050df81ab8b48f6d346b4/src/main/kotlin/app/revanced/patches/youtube/misc/customplaybackspeed/patch/CustomPlaybackSpeedPatch.kt#L187-L197
