### ISSUE TITLE
Make a patch for TikTok to work in restricted countries

### ISSUE THREAD

**Issue by mahdi921** [revanced/revanced-patches#675]
### Application

TikTok

### Issue

In some countries like Iran and India, access to TikTok is restricted by government. The issue is that TikTok somehow recognizes the device is in those countries and won't work even with vpn connection.
On the other hand when I remove any simcards and connect to a wifi with vpn, the application works without a problem. 
In the past, I was able to use app cloner to prevent TikTok from accessing sim and cell info by hiding them, but not without some problems showing up.
Now the app won't work after cloning.
The most ironic thing is that we can access tiktok through its website with vpn connection.
I have done everything suggested by google search to resolve the issue. NONE works.

### Patch

The patch should prevent the app from recognizing any of the simcard info and simcard country and/or anything related to help the app work in restricted countries

### Motivation

TikTok had many users from Iran and India. It would be good news for them to again access their accounts and their content or even use the app without a problem.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
I think it does by IP, for that you need a vpn.

**Comment by mahdi921** [comment]
VPN won't work in this case. About revoking permissions, there's nothing in android settings as I have searched every corner of it. It can't be done without some tinkering the system or the app.
I thought maybe a patch could help to go around this issue. 
It's so ridiculous.

**Comment by oSumAtrIX** [comment]
Isn't Android meant to opt in for permissions for apps? I can see a setting to disable access to APIs for apps on OxygenOS.

**Comment by mahdi921** [comment]
Yeah right. That's true for some custom roms. But what about stock roms. Stock roms don't have this luxury as they are made to be luxurious. And most people don't even know what custom rom is.
I and many people are looking forward for a workaround to solve this issue. Nevertheless, in Iran we are in the process of changing the government, so the workaround isn't going to be needed in the future. However, it would be good for the people with non-changing governments with restricted access to get a workaround.
But in any case thank you for bringing back and continuing revanced.
