### ISSUE TITLE
feat(patch): Update patches for `org.totschnig.myexpenses` to target current version (3.6.0.1)

### ISSUE THREAD

**Issue by ykis-0-0** [ReVanced/revanced-patches#677]
### Application

Package Name - `org.totschnig.myexpenses`
Google Play Link - https://play.google.com/store/apps/details?id=org.totschnig.myexpenses
GitHub Repo - https://github.com/mtotschnig/MyExpenses

### Issue

Following ReVanced/revanced-patches-template#1348, commit f68c87b0edc88e80ef2f3110f75be86236dffdb7 have made no attempt to address the cause of patch failure, which is a change on upstream.
What that commit does is only putting a cap for Target Version of the patch.

And since, Target Version for this package has stalled at 3.4.9,
while the newest version is now 3.6.0.1 in [Google Play](https://play.google.com/store/apps/details?id=org.totschnig.myexpenses) and 3.6.0 in [F-Droid](https://f-droid.org/packages/org.totschnig.myexpenses/).

Therefore, a catch-up would be desirable.

### Patch

Referring to Original Patch Request (#1113, ReVanced/revanced-patches#1120),

* Having `unlock-pro` patch properly function on Version 3.6.0

### Level of difficulties
From ReVanced/revanced-patches-template#1709,
> Editing of the code via patches should be easier as the application is open source on GitHub

### Status quo:
The patch is, may I say, pretty outdated. The version this patch targets (3.4.9) isn't even available on the internet anymore.
As a user of this patch (Thanks UA-Archiver for the request and FineFindus for the patch!), I would really like to see this patch get updated, and have tried to (I'm not skilled enough to find the right place to patch though).

On the other side, if making the patch catch up to the current version isn't possible, I'd say it'll be better off to delist / pull down this patch to avoid confusion.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Bceez** [comment]
I think this issue should be closed
