### ISSUE TITLE
feat: reddit sync imgur client id and client secrets key swap

### ISSUE THREAD

**Issue by Rihcus** [ReVanced/revanced-patches#682]
### Application

Reddit Sync

### Issue

Allow uploading to imgur after June 30th and fix current issues with viewing imgur albums in app

### Patch

Ability to swap client id and client secret in reddit sync app

### Motivation

Preserver imgur functionality in the long run

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
I think this is resolved now.

**Comment by nick-77** [comment]
I'm facing the exact same issue with image uploads from sync for reddit

Should I open a new issue?
