### ISSUE TITLE
feat(patch): Allow users to use Android's forced dark mode on TikTok

### ISSUE THREAD

**Issue by m4heshd** [revanced/revanced-patches#685]
### Application

TikTok

### Issue

We were able to use Android's forced dark mode on TikTok till recently. It was working really well on it too. Couldn't see a couple of icons but that was more than fine. Unfortunately, the company deliberately disabled the ability to use that feature in a recent update. The application is unbearably bright, they won't provide a dark mode and also took away the effortless workaround for that.

### Patch

Simply the ability to enable forced dark mode on TikTok for Android.

### Motivation

I think a majority of TikTok users use the app right before bed and it is literally burning your eyes. There's no way around this.

### Acknowledgements

- [x] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by mexon86** [comment]
why just force dark mode ? are we cant get theme patch for tiktok like it can just remove light mode and just make it black turn every white thing to black

**Comment by m4heshd** [comment]
@mexon86 It's too much work for the devs. I've made dark mode patches in the past and trust me it's excruciating work to both create it and keep it up-to-date. Forced (dynamic) dark mode has improved so much with time. We hardly need dedicated dark modes anymore.

**Comment by mexon86** [comment]
i use darq app for apps that dont have dark mode but force dark mode is also mess with other uis of phone for me and it still show dark status bar icon they not visible so is it hard to implement force dark mode style thing to app itself that it just revert white to dark automaticly ?

**Comment by m4heshd** [comment]
DarQ is the reason why I suggested this. I don't use DarQ anymore because OxygenOS and MIUI got this feature natively. But I still use DarQ on custom roms.

**Comment by RedCard1nal** [comment]
Is this still happening? Or is it even possible?

**Comment by oSumAtrIX** [comment]
#1061

**Comment by m4heshd** [comment]
@oSumAtrIX Why did you keep the new duplicate issue and close the original older issue? 🤔

**Comment by oSumAtrIX** [comment]
Newer issues might have more up-to-date information or supersede the old issue with more or better information. In this case it didn't matter which one is closed.

**Comment by m4heshd** [comment]
@oSumAtrIX Oh, noted. Too bad because this issue is much more descriptive and direct towards the goal. This is a request that asks for a "simple" revert of the system's native functionality where it's overridden by the application. I understand the devs of this project might not use this particular app, so tried to be as much descriptive as possible to guide the devs toward the right path. The new issue is much more vague and oversimplified. It straight-up asks for a theme. Being an experienced dev myself, I know that's not something you could pull out of a can.

That's all. I was left a bit confused and here was my explanation of why. _(also got way too excited at first, because in the mail, it looked like this issue was closed by a PR)_ ✌🏽

**Comment by oSumAtrIX** [comment]
The goal is the same; both issues want a dark mode, and this issue simply wants to achieve it the wrong way, Android's forced dark mode is not really the right approach.
