### ISSUE TITLE
bug: TikTok and Spotify invalid dex magic value.

### ISSUE THREAD

**Issue by SCP-017** [revanced/revanced-patches#690]
### Type

Error while patching

### Bug description

Like what I said in the title.

### Steps to reproduce

Patching Spotify or TikTok.

### Relevant log output

```shell
https://github.com/SCP-017/debug/actions/runs/3163237805/jobs/5150601534
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by SCP-017** [comment]
All the available patches are applied for both.

TikTok Version : 26.3.4
Spotify Version : 8.7.68.568

**Comment by reisxd** [comment]
Looks like your code is broken, not revanced-patches.

**Comment by oSumAtrIX** [comment]
Please use official ways on how to use ReVanced.
