### ISSUE TITLE
bug: History button disappears when "Remove general ads" is enabled

### ISSUE THREAD

**Issue by Zazazasu** [revanced/revanced-patches#691]
### Type

Error at runtime

### Bug description

The area above history that lets you tap it and open your full history disappears when hiding of general ads is enabled.

### Steps to reproduce

1. Enable Remove general ads

### Relevant log output

```shell
NA
```

### Additional context

Version 17.36.37 MicroG installed using manager

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by coolman3289** [comment]
I second this

**Comment by coolman3289** [comment]
@johnconner122 how do I do that? The manager has not been updated, how do I apply patches without manager?

**Comment by Ushie** [comment]
> @johnconner122 how do I do that? The manager has not been updated, how do I apply patches without manager?

The manager should automatically start using latest patches

**Comment by coolman3289** [comment]
@Ushie even if it was not updated? So I just repatch?

**Comment by Ushie** [comment]
> @Ushie even if it was not updated? So I just repatch?

Yep, I believe patches are only cached for 6 hours so, maybe try clearing Manager's cache/data before testing

**Comment by johnconner122** [comment]
Follow the official documentation to patch Youtube manually:
https://github.com/revanced/revanced-documentation

**Comment by coolman3289** [comment]
@johnconner122 is what ushie saying t correct too?

**Comment by johnconner122** [comment]
> @johnconner122 is what ushie saying t correct too?

I don't know, I don't use revanced manager.
