### ISSUE TITLE
The name of the application.

### ISSUE THREAD

**Issue by Bilingest** [revanced/revanced-patches#695]
### Application

YouTube

### Issue

ReVanced the name of the app.Remove the word YouTube.It's so cool.

### Patch

Changing the name of the application.

### Motivation

It's not right to have the word YouTube there.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Already implemented.
