### ISSUE TITLE
The logo at the entrance

### ISSUE THREAD

**Issue by ghost** [revanced/revanced-patches#696]
### Application

YouTube

### Issue

Resolve logo in entry with ReVanced logo.

### Patch

![Screenshot_20221002-072811_YouTube](https://user-images.githubusercontent.com/114754527/193436603-71c73579-432e-41d9-86d5-ea802610d3a2.jpg)

### Motivation

It's wrong to have the YouTube logo there.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by mexon86** [comment]
i love the youtube logo animation if revanced will have that kind of animation then ok but just having revanced logo not animated is not good

**Comment by PandoraHayami** [comment]
I think this is the splash screen, and I feel that the custom branding patch should be able to change it, if not, another patch for it.

**Comment by PandoraHayami** [comment]
https://user-images.githubusercontent.com/79670265/195232868-7310eb26-27ba-4872-bdf2-f8d9d2503538.mp4



A video demonstrating the issue.
