### ISSUE TITLE
feat:  Ignore audio focus  so people can listen to livestreams in the background while watchin other stuff on another app.

### ISSUE THREAD

**Issue by eixan** [ReVanced/revanced-patches#702]
### Application

Youtube

### Issue

Listeing to a podcast in the background while watching a movie  will cause the podcast to stop.

### Patch

The term in Android is "audio focus". Make it so revanced doesn't request audio focus.

### Motivation

 Allow video/audio from another to play while a persons listening to a livestream on revanced in the background. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by indrastorms** [comment]
> > Audio focus is claimed by the foreground apps
> 
> Here'a a guide for apps to request audio. In this case pokemon-go https://www.xda-developers.com/pokemon-go-audio-focus/
> 
> doesn't work on my phone so it would be nice if Vanced could do it by default
> 
> Mplayer also has a ignore audio focus setting

This solution worked on my device. Thanks for the link
@oSumAtrIX  revanced should implement this
Device: motorola g73, android 14
