### ISSUE TITLE
Video buttons are not centered

### ISSUE THREAD

**Issue by HeroGalak** [revanced/revanced-patches#710]
### Type

Cosmetic

### Bug description

When hide-video-buttons patch is enabled, the visible buttons are not horizontally centered.

### Steps to reproduce

Include hide-video-buttons patch in YT and hide create, clip, thanks and download buttons.

### Relevant log output

```shell
//
```

### Screenshots or videos

Buttons are slightly shifted to the left:
![Screenshot_20221003_160710](https://user-images.githubusercontent.com/69464248/193600059-a39e6d0d-9db5-4f6a-9973-9d7e271e8586.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
This is because the buttons are aligned to the left by YouTube.
