### ISSUE TITLE
bug: YouTube video not playing if started by intent from other app

### ISSUE THREAD

**Issue by Bonoboo** [revanced/revanced-patches#712]
### Type

Error at runtime

### Bug description

Problem for sure caused only by patch "[Disable Shorts On Startup](https://github.com/revanced/revanced-patches/blob/main/src/main/kotlin/app/revanced/patches/youtube/layout/startupshortsreset/patch/DisableShortsOnStartupPatch.kt)" (@OxrxL). Also it's gone if turn it off in settings.

Applied by ReVanced Manager 0.0.28 on YouTube 17.36.37

### Steps to reproduce

1. Apply patch "Disable Shorts On Startup"
2. Make sure it enabled in Settings > ReVanced > Layout > Disable shorts player at app startup
3. Open YouTube app
4. Swipe it out from "Recents" (i.e. close) - it's important
5. Tap on video link in any app like browser (log below starts from this point)
6. Observe "Main" tab instead expected video playing

### Relevant log output
[logcat_revanced_DisableShortsOnStartupPatch.txt](https://github.com/revanced/revanced-patches/files/9698883/logcat_revanced_DisableShortsOnStartupPatch.txt)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by OxrxL** [comment]
@oSumAtrIX can you reproduce this?

**Comment by oSumAtrIX** [comment]
@OxrxL yes, reproducible.

**Comment by OxrxL** [comment]
I'll give it a look asap.

**Comment by OxrxL** [comment]
@Bonoboo Fixed

**Comment by Bonoboo** [comment]
@OxrxL, _huge_ thanks for so quick fix.
