### ISSUE TITLE
Question about patches

### ISSUE THREAD

**Issue by KweezyPlay** [revanced/revanced-patches#72]
why do not use Craftbukkit-like patches?

**Comment by TheJeterLP** [comment]
What are craftbukkit like patches?

**Comment by oSumAtrIX** [comment]
Probably mixins, they are unpractical in our case due to dalvik byte code & limitations, since we depend on our fingerprint system.

**Comment by Sculas** [comment]
@TheJeterLP @oSumAtrIX They mean `.patch` files, which are just diffs. Most likely smali diffs in that case.

**Comment by TheJeterLP** [comment]
> @TheJeterLP @oSumAtrIX They mean `.patch` files, which are just diffs. Most likely smali diffs in that case.

oh okay, well that makes no sense with YouTube then because of the obfuscation.
