### ISSUE TITLE
feat(patch): Block Flash messages in Google Messages app

### ISSUE THREAD

**Issue by johnconner122** [revanced/revanced-patches#720]
### Application

Google Messages

### Issue

Flash messages are irritating. Need a patch!

### Patch

There should be a patch to block flash messages in 'Google Messages'.

### Motivation

Users will be benefitted from blocking flash messages, as they interrupt playing games or doing something else.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
What is a flash message?

**Comment by johnconner122** [comment]
![image](https://user-images.githubusercontent.com/107796137/193820265-b04d6268-5c75-4f11-8297-32d7563dce6e.png)

**Comment by oSumAtrIX** [comment]
Thats not from Google Messages, you have malware, please revise what you have installed on your phone.

**Comment by johnconner122** [comment]
I know that's not google messages, it's just a screenshot how flash message looks like

**Comment by oSumAtrIX** [comment]
You can disable notifications from any app in your phone's settings.
