### ISSUE TITLE
feat(patch): copy link button on player

### ISSUE THREAD

**Issue by kevin01523** [revanced/revanced-patches#722]
### Application

YouTube

### Issue

able to copy youtube links or yotube links with timestamp

### Patch

a feature of able to copy links or copy links with timestamp option on player on the youtube app.basically a button on the video player itself if you click it the clipboard will have a youtube link on it or a youtube link with a timestamp

### Motivation

it restores a legacy feature contained on the old vanced app and it enables users to share the video or the video with a timestamp easier

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by sawankumarbundelkhandi** [comment]
duplicate of https://github.com/revanced/revanced-patches/issues/531
