### ISSUE TITLE
feat(patch): Add a download button for Twitter videos

### ISSUE THREAD

**Issue by CanerKaraca23** [ReVanced/revanced-patches#729]
### Application

Twitter

### Issue

This patch will give us a chance to download videos directly from Twitter.

### Patch

I'd like to see a download button on Twitter videos.

### Motivation

People will be able to download videos from Twitter.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by SodaWithoutSparkles** [comment]
I am quite sure that yt-dlp can handle it, from memory.

I will try to see if seal can handle it as well.

**Comment by oSumAtrIX** [comment]
Closing in favour of #3254
