### ISSUE TITLE
bug: <Spotify crashing immediatly if one is trying to open the settings with the theme patch>

### ISSUE THREAD

**Issue by skridofly** [revanced/revanced-patches#732]
### Type

Error at runtime

### Bug description

Patched Spotify v8.7.72.546 with the theme patch v0.0.1 and installed it as root and tried to acces my Settings. 
It without a delay crashed the app

### Steps to reproduce

1. Patch Spotify with the theme patch
2. Open the settings

### Relevant log output

```shell
no log available
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
You need the full apk currently or have to mount the base apk.
