### ISSUE TITLE
bug: custom-playback-speed: Speeds faster than 2.0x are reset to 2.0x

### ISSUE THREAD

**Issue by philklc** [revanced/revanced-patches#736]
### Type

Other

### Bug description

YouTube remembers video playback speeds when playing videos. Play a video at 2x speed and other videos you play will also be at 2x speed.

### Steps to reproduce

Client: YouTube 17.36.37, patch version 2.81.0

1. Play a video
2. Set its playback speed to a speed higher than 2.0
3. Play another video
4. Observe that the speed is lowered to 2.0, instead of the previously selected speed

### Relevant log output

```shell
n/a
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by ajmz** [comment]
If the playback speed is set to 2.0 or below, the next video can be kept unchanged, but if the playback speed exceeds 2.0, the next video will be slowed down to 2.0 by default.

**Comment by Canny1913** [comment]
Expected behavior.

**Comment by crazdrama** [comment]
could probably be fixed with the default playback speed setting...is there any update on this feature to set default playback speed or is the feature dropped from plans for revanced??

**Comment by smonsec** [comment]
I have seen it going back to 1x so many times. Playback speed remember patch was requested, and I think someone is working on it too.

**Comment by ajmz** [comment]
> If the playback speed is set to 2.0 or below, the next video can be kept unchanged, but if the playback speed exceeds 2.0, the next video will be slowed down to 2.0 by default.

---

Revanced-patches V2.82.0 issue:

If the Preferred video speed in "ReVanced settings - Video settings" is set to 2.0 or below, the speed of the video stays the same as it plays.
But if the Preferred video speed exceeds 2.0, Revanced-patches V2.82.0, the video starts playing at the same speed as the Preferred video speed, but after a while, it suddenly slows down to 2.0.

**Comment by oSumAtrIX** [comment]
Should be fixed with https://github.com/revanced/revanced-integrations/commit/eea37a9bada6c843275236fa232bfe497d178b17.
