### ISSUE TITLE
premium-heading patch fails

### ISSUE THREAD

**Issue by shivanshkverma** [revanced/revanced-patches#74]
![image](https://user-images.githubusercontent.com/15206857/176344280-949ea275-ad4b-4e60-9d94-6dcb26fd5d0e.png)
Patch 2.1.0
CLI: 2.0.4
Integrations: 0.17.0
Youtube: 17.24.35
Variant: Non-root
Used .apk (full, not extracted from .apkm)
Command used: `java -jar revanced-cli.jar -a youtube.apk -m app-release-unsigned.apk -o revanced.apk -d [DEVICEID] -b revanced-patches.jar`
Java: ZuluJDK 17

**Comment by Canny1913** [comment]
Please patch a full APK. Not base.apk

**Comment by shivanshkverma** [comment]
> Please patch a full APK. Not base.apk

That's what I did. It was full apk.

**Comment by Canny1913** [comment]
Can you provide which command did you use?

**Comment by shivanshkverma** [comment]
> Can you provide which command did you use?

`java -jar revanced-cli.jar -a youtube.apk -m app-release-unsigned.apk -o revanced.apk -d [DEVICEID] -b revanced-patches.jar`

**Comment by Canny1913** [comment]
Java version?

**Comment by shivanshkverma** [comment]
> Java version?

ZuluJDK 17

**Comment by Itroublve** [comment]
Where did you get the YouTube apk, because it seems there's a problem with it.

**Comment by shivanshkverma** [comment]
> Where did you get the YouTube apk, because it seems there's a problem with it.

That's weird, I downloaded it from ApkMirror...

**Comment by Itroublve** [comment]
> > Where did you get the YouTube apk, because it seems there's a problem with it.
> 
> That's weird, I downloaded it from ApkMirror... And that too two times. I will probably try again.

Try with 17.24.34 as that's what I last succeeded with.

**Comment by shivanshkverma** [comment]
> > > Where did you get the YouTube apk, because it seems there's a problem with it.
> > 
> > 
> > That's weird, I downloaded it from ApkMirror... And that too two times. I will probably try again.
> 
> Try with 17.24.34 as that's what I last succeeded with.

Well then if it's a problem with .35 version, it's an issue because patch's compatibility files say that it supports .35 version.

**Comment by Itroublve** [comment]
Actually it seems there actually might be a problem with the latest patches. Give me a moment.

**Comment by Itroublve** [comment]
> > > > Where did you get the YouTube apk, because it seems there's a problem with it.
> > > 
> > > 
> > > That's weird, I downloaded it from ApkMirror... And that too two times. I will probably try again.
> > 
> > 
> > Try with 17.24.34 as that's what I last succeeded with.
> 
> Well then if it's a problem with .35 version, it's an issue because patch's compatibility files say that it supports .35 version.

I've not tried .35 so I cannot tell you, 
![image](https://user-images.githubusercontent.com/51215044/176373004-a274a187-8d6c-4992-a906-1b1b20158515.png)
but it does seem to work for me on 17.24.35 as well.

**Comment by shivanshkverma** [comment]
> > > > > Where did you get the YouTube apk, because it seems there's a problem with it.
> > > > 
> > > > 
> > > > That's weird, I downloaded it from ApkMirror... And that too two times. I will probably try again.
> > > 
> > > 
> > > Try with 17.24.34 as that's what I last succeeded with.
> > 
> > 
> > Well then if it's a problem with .35 version, it's an issue because patch's compatibility files say that it supports .35 version.
> 
> I tried ![image](https://user-images.githubusercontent.com/51215044/176373004-a274a187-8d6c-4992-a906-1b1b20158515.png) and it does seem to work for me on 17.24.35 as well.

Did you try not-root?

**Comment by Itroublve** [comment]
> > > > > > Where did you get the YouTube apk, because it seems there's a problem with it.
> > > > > 
> > > > > 
> > > > > That's weird, I downloaded it from ApkMirror... And that too two times. I will probably try again.
> > > > 
> > > > 
> > > > Try with 17.24.34 as that's what I last succeeded with.
> > > 
> > > 
> > > Well then if it's a problem with .35 version, it's an issue because patch's compatibility files say that it supports .35 version.
> > 
> > 
> > I tried ![image](https://user-images.githubusercontent.com/51215044/176373004-a274a187-8d6c-4992-a906-1b1b20158515.png) and it does seem to work for me on 17.24.35 as well.
> 
> Did you try not-root?

yes obv, the premium heading patch isn't supported on the root variant.

**Comment by shivanshkverma** [comment]
> > > > > > > Where did you get the YouTube apk, because it seems there's a problem with it.
> > > > > > 
> > > > > > 
> > > > > > That's weird, I downloaded it from ApkMirror... And that too two times. I will probably try again.
> > > > > 
> > > > > 
> > > > > Try with 17.24.34 as that's what I last succeeded with.
> > > > 
> > > > 
> > > > Well then if it's a problem with .35 version, it's an issue because patch's compatibility files say that it supports .35 version.
> > > 
> > > 
> > > I tried ![image](https://user-images.githubusercontent.com/51215044/176373004-a274a187-8d6c-4992-a906-1b1b20158515.png) and it does seem to work for me on 17.24.35 as well.
> > 
> > 
> > Did you try not-root?
> 
> yes obv, the premium heading patch isn't supported on the root variant.

Aah okay well then it's problem on my side probably. Will just close the issue.

**Comment by Aunali321** [comment]
It works for .35, i tested it before pushing PR. I am using .35 and it's working for me.
![Uploading Screenshot_2022-06-29-12-36-15-426_app.revanced.android.youtube.jpg…]()
