### ISSUE TITLE
feat(patch): Remove ads from google maps

### ISSUE THREAD

**Issue by shadoxxhd** [ReVanced/revanced-patches#740]
### Application

Google Maps

### Issue

Ads appearing when searching for places, or in the map.

### Patch

Remove all ads (and ideally block any related network request).

### Motivation

Ads waste valuable time and attention, and Google Maps is probably one of the most used apps on Android.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Closing therefor.

**Comment by shadoxxhd** [comment]
Adguard DNS hasn't always been enough to prevent these ads from showing up.
Also, wouldn't it be possible to reuse the ad/microg patches from YouTube? And also apply them to other google apps that would benefit from patching (eg. Gmail)?
