### ISSUE TITLE
bug: Inconsistencies in patch name/description 

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [ReVanced/revanced-patches#740]
### Type

Cosmetic

### Bug description

For most `hide-whatever-patches`, their description startes with "hides whatever" according to the their respective patch names. But this is not followed throughout, like in the case of `hide-ads`, the description is "Removes general ads." and for `hide-player-buttons` and `hide-video-action-buttons` the descriptions are "Adds the option to hide video player previous and next buttons." and "Adds the options to hide action buttons under a video."
Then there's `enable-debugging` and it's description is "Adds debugging options." whereas `minimized-playback` description is "Enables minimized and background playback."
There are other cases as well which I won't be listing here. But if needed I can go through and list them, but I hope what I meant is clear.

### Steps to reproduce

Open the manager and select the YouTube apk and go through the patch list.

### Relevant log output

```shell
Nil
```

### Solution

Follow a more consistent naming scheme and description for patches as long as it does something similar to an existing patch.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by KobeW50** [comment]
@ILoveOpenSourceApplications I opened a [pull request](https://github.com/ReVanced/revanced-patches/pull/2519/) in which I reworded many patch descriptions. If you have time, please look over it and provide feedback and suggestions if necessary. Thanks!
