### ISSUE TITLE
feat(patch): Unlock App Cloner's premium features

### ISSUE THREAD

**Issue by johnconner122** [ReVanced/revanced-patches#741]
### Application

App Cloner (com.applisto.appcloner)
https://appcloner.app/

### Issue

Most of useful features are paid.

### Patch

Create a patch which will unlock premium features of app cloner

### Motivation

It is very handy appliction. It is very much needed. It'll be great service to people.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Closing according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#%EF%B8%8F-guidelines-for-requesting-or-contributing-patches). Thanks anyways.
