### ISSUE TITLE
Remember quality patch does not remember the quality

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [revanced/revanced-patches#743]
### Type

Error at runtime

### Bug description

Remember quality patch does not remember the quality. The usual pop-up saying it "remembered quality for WiFi" is missing

### Steps to reproduce

1. Patch YT ver 17.36.37 with patches shown in the screenshot below
2. play any video
3. change the resolution to 144p
4. observe that the pop-up is missing
5. play another video
6. observe that the quality is not 144p

### Relevant log output

```shell
no log
```

### Screenshots or videos

![Screenshot_2022-10-09-12-51-17-145_app revanced manager flutter](https://user-images.githubusercontent.com/64138578/194738688-289cd634-53c5-4526-9bea-eed5d99acef2.jpg)

### Additional context

1. If able, please use another menu under revanced setting (like vanced always did) to make it clear which quality you have selected
2. I know theres a similar issue, but this issue is about the old quality menu, the other does not
3. I have a screen record but cannot upload. I will try to add it somewhere

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by SodaWithoutSparkles** [comment]
The video was muted to reduce file-size and prevent copy-right issues
https://user-images.githubusercontent.com/64138578/194739092-e99ac0c5-2997-4a35-82fd-3b7151db2a1c.mp4

**Comment by naftali100** [comment]
To save the resolution across all videos you need to turn *off* the setting, revanced settings->misc->remember current video quality

**Comment by SodaWithoutSparkles** [comment]
Wait, is that setting **on** by default? Who thought of the genious idea of this confusing naming?

Should I close this issue and report another one on confusing enable/disable state or edit this one?

**Comment by SodaWithoutSparkles** [comment]
new issue opened at #744
