### ISSUE TITLE
Toggle switches and default behaviours for settings are confusing

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [revanced/revanced-patches#744]
### Type

Cosmetic

### Bug description

When patching, some patches are included but does not enable by default in Revanced youtube. Examples include tablet mini-player and remember quality. 

In Revanced YT settings, the toggle switches are confusing. Examples include "Remember quality" settings under misc. have to be turned **off** to remember quality, unlike what the title suggest.

### Steps to reproduce

1. Include all patches except debug, auto-repeat, wide search bar
2. Patch YT 17.36.37 with manager 0.0.30
3. Observe that the default behaviour is not as expected like what the bug description said

### Relevant log output

```shell
N/A
```

### Solution

Functions that are added using patches should be enabled by default unless they will significantly affect UX. Examples include:

- Tablet mini-player
- Remember quality
- Swipe control?
- (more will be added later)

But those which significantly affect UX like removing like/dislikes button should be not enabled

-----
All toggles should be respecting what the title said, like the "remember video quality" toggle mentioned above. It should be toggled **on** to remember video quality
All toggles under revanced settings > ads and layout should be configured to be "toggled on to remove something". Some examples are:

- show info cards → hide info cards
- show autoplay button → hide autoplay button
- show cast button → hide cast button
- show fullscreen panel → hide fullscreen panel
- show create button → hide create button
- show shorts button → hide shorts button
- show branding watermark → hide branding watermark

Ofc the button toggle state should be changed accordingly

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Give a suggestion for the remember selected quality toggle.

**Comment by SodaWithoutSparkles** [comment]
I now understand the reason behind the default choices of enable/disable certain patches. In such case having an option to export settings would be better. 

-----

But that does not solve the "confusing toggle title" thing. Remember quality should be toggled **on** to enable the function, not **off**. 

I dont think by default enabling remember quality is changing the behaviour heavily tho, but anyway, thats just a side quest.

I still thinks the wording of the toggle title should be changed such that "Toggle on everything means removing everything" or "Toggle on everything means show everything". Currently its all over the place which is not quite user friendly.

**Comment by oSumAtrIX** [comment]
I was referring to tablet mini player, other toggles need to be normalized in behaviour, the remember quality toggle serves a different purpose. Toggle it on, and it will remember the current settings and never switch the quality even if you change it in the flyout, toggle it off and it will remember the quality until you change it in the flyout, basically semi persistent, which is why the toggle is named how it is named. Can you suggest a better name?

**Comment by SodaWithoutSparkles** [comment]
> Toggle it on, and it will remember the current settings and never switch the quality even if you change it in the flyout, toggle it off and it will remember the quality until you change it in the flyout, basically semi persistent, which is why the toggle is named how it is named. Can you suggest a better name?

Oh I understand the reason behind the naming. If able, I would prefer the quality selection of the old vanced method, giving a menu to choose instead of having to switch networks and config. It would be even better if we could somehow prefer VP9 or not prefer AV01 codec, since some device does not support AV01 hardware decode.

A better method if we dont have the old vanced way would be leave the remember quality toggle under misc default off. When the user changes the quality, the toast notification pops up to tell users that it had remembered the selection, and advice user that it could be locked. The toggle could be called "Lock current remember quality preference" and have a description reminding users of the current preference, something like this:

> **Lock current remember quality preference**
> Switching quality [will/will not] affect the global preference. Currently [1080p] for WiFi and ...

But I still prefer the this way:
> Default WiFi quality: 1080p
> Default cellular quality: 720p
> Preferred video coded: VP9

**Comment by sawankumarbundelkhandi** [comment]
> A better method if we dont have the old vanced way would be leave the remember quality toggle under misc default off. When the user changes the quality, the toast notification pops up to tell users that it had remembered the selection, and advice user that it could be locked. The toggle could be called "Lock current remember quality preference" and have a description reminding users of the current preference, something like this:
> 
> >

It's WIP here - https://github.com/revanced/revanced-patches/pull/723/files

**Comment by SodaWithoutSparkles** [comment]
For reference, the above PR was closed and moved here.
https://github.com/revanced/revanced-patches/pull/826

**Comment by SodaWithoutSparkles** [comment]
@oSumAtrIX Maybe this normalization treatment should also be applied to the layout tab. Toggle on to modify default behaviour and vice versa. Including but not limited to:

- Show auto-play button
- Show cast button
- Show full-screen panels
- Show create button
- Show shorts button
- Show branding watermark

**Comment by karl-pae** [comment]
For " remember current video quality"

it should save user preference when the toggle is ON

it should not save user preference when the toggle is OFF.

Currently, the behaviour of the toggle is exactly opposite. 

1. Turn Off the toggle

2. set the video quality (1080)

3. There's a pop up that preference has been saved. 
(Changed default quality for WiFi to 1080)

4. It saves my preference for next video

Actually this should occur when the toggle is turned ON. 🤦‍♂️

Should it remember video quality preference? Yes or No ? 

Toggle ON - Yes

Toggle Off - No

**Comment by SodaWithoutSparkles** [comment]
> it should save user preference when the toggle is ON
> 
> it should not save user preference when the toggle is OFF.

Thats why I said change it to "Lock current quality selection preference" would be better. It sounds like a lock to the config that would otherwise be changed everytime you change the quality.

That said, the old vanced quality selection menu is WIP, but I hope we could rank quality preference instead of setting one and let it fallback, as said in #909.

**Comment by oSumAtrIX** [comment]
The toggle is not controlling what you say. It either locks or unlocks the current quality from being changed at all as explained in the switch description.

**Comment by oSumAtrIX** [comment]
@SodaWithoutSparkles I am still thinking about merging #909 at all. It is a regression in UX. You have to visit the settings to select a quality, while with the current one, the native quality selection works __as intended__: Select a quality - videos start playing in that quality. Change it to another, will start to play videos in the new quality. Want to remember the selected quality and only change it once for specific videos? Enable the switch for ths behaviour.

**Comment by SodaWithoutSparkles** [comment]
I think you are misunderstanding something here. What I mean in #909 is add options in the **existing** quality selection screen. From only selecting 1080p60 now, to having 3 options for 1080p60, and if available another 3 for 1080p30. User dont need to go to settings to change the quality for _a_ video, just have more options to choose.

Or you are talking about PR #826?

What I was thinking on ordering or ranking quality preference menu could be like: 

**Prefered video qualities, automatically falls back to the next if not available**
1. 1080p60, VP9+HDR 
2. 1080p60, VP9
3. 1080p30, AVC
4. 720p60, VP9
5. 720p30, AVC

**Lock order [ True | False ]**
_The highest prefered quality [ will | will not ] change when you select new quality in player_

**Comment by oSumAtrIX** [comment]
@SodaWithoutSparkles off topic, I am responding in relation to this issue. Please open or use an issue dedicated for what you mean.

**Comment by oSumAtrIX** [comment]
@karl-pae Switch on means lock the quality/don't change it further more.

**Comment by karl-pae** [comment]
@oSumAtrIX 

I understood completely. I agree when it's ON it is locked. That is Case 2.

I would request you to change the title & description a little bit.. if possible.

**Comment by oSumAtrIX** [comment]
Please suggest one.

**Comment by karl-pae** [comment]
[ Remember Default Video Quality ]

Toggle is ON
Description should be "The current video quality will not be set as default for new video"

Toggle is OFF
Description should be "The current video quality will be set as default for new video"

Also the pop up says 

Changing **Default** Wi-Fi Quality

**Comment by oSumAtrIX** [comment]
Default is the wrong word as you highlighted it. So in the switch description it would be wrong too.

**Comment by karl-pae** [comment]
I think, toggle for this is not a good UX it should be replaced with vanced settings.

Why ?

After fresh install of revanced YT app, 
- toggle is OFF (by default)
- play video
- select quality 720
- Goto settings 
- toggle ON 
- Settings saved/locked.

Now user want to lock 1080:
- Goto settings 
- toggle OFF
- Play video
- Select quality 1080
- Exit video
- Goto settings
- Toggle ON
- Settings saved/locked


--- Vanced settings ---
User don't need to play video just to lock quality

- Goto settings
- Change quality
- Settings saved/locked 

similar vanced setting is also used in Newpipe.

Vanced settings ::

![Screenshot_2022-11-03-13-35-56-91_7a4090f09f6554852d748ee9fd6f40d3~2.jpg](https://user-images.githubusercontent.com/83178186/199672496-03a181c6-0ebd-4a7a-9070-2d5252837867.jpg)


Newpipe settings ::
![Screenshot_2022-11-03-13-36-07-82_ee8807d2de22f1831269d80920e33a3b~3.jpg](https://user-images.githubusercontent.com/83178186/199672576-2de8faf2-5c7b-4854-98f7-3bdc71eb65c5.jpg)

**Comment by oSumAtrIX** [comment]
It is less often the case, that you want to change a locked quality. If you do it often, disable the lock once and „remember“ the quality.

**Comment by karl-pae** [comment]
I don't have a problem with toggle but just to set one setting, the user has to go here and there.

**Comment by oSumAtrIX** [comment]
The user would require to go to the settings in either way. As previously said, you can remember instead of locking if you change it often, as simple as that.

**Comment by Meganium97** [comment]
I don't get how to set quality to "auto". Sometimes I want to save battery and other times I want to view a video in full quality, but I set it to not remember quality in misc settings, and it's now just stuck on 720p. No matter what I do, with the exception of toggling the misc setting and manually changing the stored quality setting, it always starts the video on 720p. I just don't understand.

**Comment by oSumAtrIX** [comment]
Disable the old quality layout patch and set it to auto in the flyout menu.

**Comment by Meganium97** [comment]
Surprisingly doesn't work. I don't get the popup saying it universally changes quality to auto.

**Comment by oSumAtrIX** [comment]
https://user-images.githubusercontent.com/13122796/205517008-5e210d80-8940-4646-ac6e-c281b434625a.mp4


Does for me.

**Comment by Meganium97** [comment]
I meant that selecting auto set it to auto but doesn't set every video to auto.

**Comment by oSumAtrIX** [comment]
Exclude the patch to remember the video quality.

**Comment by oSumAtrIX** [comment]
Open a new issue and list every switch which needs to be fixed.
