### ISSUE TITLE
bug: YT revanced crashes when pressing subtitle button in incognito mode

### ISSUE THREAD

**Issue by jonas-hurst** [revanced/revanced-patches#745]
### Type

Error at runtime

### Bug description

When pushing the subtitle options button in incognito mode,  YT revanced app crashes

### Steps to reproduce

1. Open YT revanced
2. Enable incognito mode
3. play any video
4. press settings button in upper right corner in video player (the gear icon)
5. press the menu item for subtitles
-> App crashes

### Relevant log output

```shell
n.a.
```

### Solution

workaround: using the cc button in upper right corner of video player works

### Additional context

YT: 17.36.37
cli: 2.14.0
patches: 2.81.2
intgrations: 0.51.0

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by SodaWithoutSparkles** [comment]
Can reproduce using YT 17.36.37 manager 0.0.30. Interestingly using subtitle button next to the gear icon wont crash

https://user-images.githubusercontent.com/64138578/194756748-498a889e-6912-41cf-95f1-3ee557d121f5.mp4

_the pop-up window is MIUI asking for logs to investigate when an app crashed._

I can preview the logs its trying to send before sending it. Therefore I copied the logs and posted it here. I did not send to MIUI tho.

```
java.lang.IllegalStateException: Fragment kko{a6cc24e} (671a5c8a-1043-4d0d-bfd3-f7ceba821c4e tag=SUBTITLE_MENU_BOTTOM_SHEET_FRAGMENT) not attached to a context.
	at bp.nW(PG:2)
	at bj.pB(PG:2)
	at bj.ng(PG:3)
	at kkp.ng(PG:1)
	at bp.mB(PG:1)
	at mfy.e(PG:3)
	at mfy.g(PG:201)
	at ch.H(PG:4)
	at ch.av(PG:113)
	at ch.ax(PG:11)
	at ch.ah(PG:8)
	at bf.run(PG:78)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8290)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:577)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)

```

I think the app is obfuscated so it might have limited use.

**Comment by oSumAtrIX** [comment]
https://user-images.githubusercontent.com/13122796/194764188-3985da46-5af6-448e-939b-d1637ecb32ad.mp4

I can not reproduce this.

**Comment by jonas-hurst** [comment]
I use LG-V30 running Android 9, if that is in any way relevant

**Comment by SodaWithoutSparkles** [comment]
@oSumAtrIX use incognito

**Comment by OxrxL** [comment]
Cannot reproduce...neither in incognito.

**Comment by SodaWithoutSparkles** [comment]
Cannot reproduce anymore. I think it is fixed, as of: 

- patch 2.97.0
- YT 17.41.37
- manager 0.0.36
