### ISSUE TITLE
feat(patch): hide menu items in video control menu

### ISSUE THREAD

**Issue by jonas-hurst** [ReVanced/revanced-patches#746]
### Application

Youtube

### Issue

The video controls menu has lots of menu items. The menu feels cluttered and confusing. Most people dont use lots of the options in the menu.

Just so that we are on the same page:
by video controls menu I mean the menu that opens when the little gear icon in the upper right corner of the video player is pushed. The one where I can change video quality, playback speed etc.

### Patch

I like how I can declutter the action buttons underneath a video with the `hide-video-buttons` patch and adjust what buttons I see to my personal taste.
In similar fashion, this patch could provide settings to individually enable/disable items in the video controls menu, so that users only see the menu items that are relevant to them.

### Motivation

I believe, most people dont use lots of the buttons in the video controls menu. They therefore do not need to be displayed to them.
I am talking about buttons such as: (I hope I translated the button titles correctly to english).
- Repeat video
- Report video
- Help and Feedback
- More of [`channel name`]
- Audio track
- Watch in VR
- Stats for nerds

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by SodaWithoutSparkles** [comment]
imo the stats for nerds item should not be hidden by default, i.e. when the user enables the function in YouTube general settings, it should be there.

The feature is used to debug playback issues like lagging or buffering by providing stats on video res, format, network speed, viewport size etc.
