### ISSUE TITLE
bug: YT buffering resets screen brightness

### ISSUE THREAD

**Issue by jonas-hurst** [revanced/revanced-patches#749]
### Type

Cosmetic

### Bug description

If you change screen brightness via swipe controls, and then the video buffers, brightness is reset to what it was in the beginning

### Steps to reproduce

1. open YT revanced
2. enable swipe-controls for brightness
4. play any video
5. change screen brightness via swiping gesture (e.g. form 10% to 100% to make it obvious)
6. somehow get the video to buffer after playback has already started (e.g. thorugh slow internet speed, or double-tap right side of screen to skip to unbuffered part of video)

-> screen brightness will revert to how it was before step 4
-> when buffering is complete, brightness stays on this level

### Relevant log output

```shell
n.a.
```

### Solution

Keep screen brightness adjusted while video is buffering (circle is spinning) and when playback resumes

### Additional context

Not really a critical bug in my opinion, just documenting for the sake of completeness. Simply set brightness anew once buffering is completed and video playback resumes.
But it is kinda annoying to do this again and again if you are on a slow connection speed.

YT: 17.36.37
cli: 2.14.0
patches: 2.81.2
intgrations: 0.51.0

### Acknowledgements

- [x] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by SodaWithoutSparkles** [comment]
Cannot reproduce. I have set the brightness from 2x% to 100%, then disabled wifi and cellular to force it to buffer. after buffering for 5 seconds I enabled wifi and cellular again, the video resumes with 100% brightness. Did I mess up by swiping down the notification bar to disable network access?

**Comment by jonas-hurst** [comment]
New finding: Must be in incognito mode for this to occur
It happens when I fast-forward (e.g. through double-tapping right side of screen) to a section of the video that is not yet buffered.

**Comment by SodaWithoutSparkles** [comment]
still cannot reproduce. maybe my network is too fast. I have to disable wifi for it to work but it might be interfering

**Comment by udoxi** [comment]
Facing same problem, brightness resets automatically while watching video on Fullscreen...

**Comment by udoxi** [comment]
Please acknowledge the bug of YouTube videos brightness reset with little buffer in Fullscreen, and plz patch the problem... It's being there for a week...

**Comment by jonas-hurst** [comment]
Update: this has nothing to do with incognito mode. Or buffering...
It seems like this occurs when a mid-video advertisement is supposed to play.

**Comment by SodaWithoutSparkles** [comment]
could it be related in any way, shape or form to #549?

**Comment by lillyay** [comment]
I was using YouTube Vanced which i patched earlier and everything was fine, but when i used latest patch to experience latest patches, annoying screen brightness reset with sudden loading started... though i have a good internet speed. Please solve this bug.

**Comment by SodaWithoutSparkles** [comment]
@lillyay I suppose u mean revanced.

I remember I have read somewhere, either github issues or reddit comments, that the new video ads patch was supposed to fix something but caused a few buffers on where the an ad is supposed to play. Since an ad is technically another video, is this causing issues?

**Comment by lillyay** [comment]
@SodaWithoutSparkles may be but I'm not sure...

**Comment by saifkhan9187** [comment]
Faced the same issue also with the latest patch.

**Comment by jonas-hurst** [comment]
fixed, as of v2.83.1
