### ISSUE TITLE
feat(patch): Donate box removal.

### ISSUE THREAD

**Issue by TheKingFireS** [revanced/revanced-patches#750]
### Application

For YouTube.

### Issue

Nothing issues, just add new patch.

### Patch

Red: I want remove this donate box.
Blue: you can remove another useless green box if you want.
![image](https://user-images.githubusercontent.com/71936968/194758919-226f2b1a-3f64-481f-8e7a-0de95d611e4e.png)

### Motivation

To have clean UI

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Can you send a sample YouTube link where this appears?

**Comment by TheKingFireS** [comment]
@oSumAtrIX https://youtu.be/gsi2Pn13BgI
(No, i am not fan of him, just a test)

**Comment by OxrxL** [comment]
https://github.com/inotia00/revanced-patches/commit/9131b0fb04c8a2f6bff7a10c1b6fdd23a1b4e441
