### ISSUE TITLE
Home Page Ads

### ISSUE THREAD

**Issue by jojobozo** [revanced/revanced-patches#751]
### Type

Cosmetic

### Bug description

On the homepage and on the videos, there are these ads

### Steps to reproduce

Just open the app

### Relevant log output

```shell
No logs
```

### Screenshots or videos

![Screenshot_20221010-013414~2](https://user-images.githubusercontent.com/98482700/194784690-9b5441d3-0a17-4026-8113-11e56099c288.png)

### Additional context

I have this for almost 1 month. I didn't have this problem before and when I use the incognito mode, I don't have ads. I use the latest btw

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by zpar-ky** [comment]
had same, I updated patches for 2.81.8+ and they're gone.

**Comment by jojobozo** [comment]
> had same, I updated patches for 2.81.8+ and they're gone.

Not fixed for me

**Comment by oSumAtrIX** [comment]
Fixed.
