### ISSUE TITLE
Don't be YouTube.

### ISSUE THREAD

**Issue by Nizami20052022** [revanced/revanced-patches#754]
### Application

YouTube

### Issue

The About section of YouTube, the word in search history and YouTube video download features should be removed, and the interface of the application should be strongly changed.

### Patch

The app may be different from YouTube but simpler and easier.

### Motivation

It reduces the possibility of application closing

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [ ] I have written a short but informative title.
- [ ] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
We are not YouTube.

**Comment by Nizami20052022** [comment]
Remove these features.

**Comment by reisxd** [comment]
I don't think you're serious... 


Well, if you are, my condolences.

**Comment by SodaWithoutSparkles** [comment]
You know, the chances of they actually having legal grounds are pretty low. Revanced is **not** distributing or modifying Google's IP here, they just provide the tools to do so. Technically its you that is modifying Google's code. 

You could be sued, but the chances of Google actually suing you is quite low. The cost-benefit ratio in suing an individual is too low to be worth it. 

Also, how are they going to sue **You**? They have to have your real name, and Google cannot assure the name you have given them is real. We may even live in places with very different laws so good luck. 

Even nintendo cannot sue developers of cartage modding tools. So you dont need to worry too much.

**Comment by Nizami20052022** [comment]
This app is no different from Vanced.

**Comment by Nizami20052022** [comment]
50% chance of closing

**Comment by Aunali321** [comment]
ReVanced is a patcher just like lucky patcher but open source and superior. Why isn't lucky patcher still banned after all these years? Because it's legal.
