### ISSUE TITLE
bug: Twitter crashes with Dynamic Color patch

### ISSUE THREAD

**Issue by Aakodal** [revanced/revanced-patches#758]
### Type

Error at runtime

### Bug description

After patching Twitter with Dynamic Color through the manager and installing it with root, timeline appears correctly for a moment with Material You, however if you try to click on anyone's profile or wait several seconds you'll crash immediately.
Only Dynamic Color has been applied.
Installation without root results in immediate crash, without even timeline appearing.

### Steps to reproduce

1. Patch Twitter with Dynamic Color patch through the manager
2. Install it with root
3. (Optionnally) clear cache
4. Open Twitter
5. Try to go on anyone's profile, or wait a moment

### Relevant log output

```shell
N/a
```

### Additional context

Twitter version: 9.62.0-release.0
Android 12 (LineageOS 19.1)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by TorchedSammy** [comment]
if you are patching twitter installed from play store it will not work since it is a split apk (from what i have seen) so you have to download and patch the non bundle apk from a site like apkmirror

i have all 3 patches for twitter and it works

**Comment by naloder** [comment]
look like the patch broken in the new version

**Comment by z411** [comment]
Same here. In Play Store it crashes when trying to log in and in APK it crashes at open. What's the latest version the patch worked with?

**Comment by z411** [comment]
@TorchedSammy which version are you using?

**Comment by ILoveOpenSourceApplications** [comment]
Closing this issue as it's no longer an issue.
