### ISSUE TITLE
feat(patch): Optionally add timestamp to apk version

### ISSUE THREAD

**Issue by SinTan1729** [revanced/revanced-patches#763]
### Application

YouTube

### Issue

Often, the patches are updated even though the base YouTube apk is the same. So, when I build the app, the newly built apk has the same version as the old one. I'm using a build script that checks for updates regularly, builds new apps and pushes it to a self hosted fdroid repo. The problem I'm facing is that while new builds are indeed detected, I can't update to them since the version code is the same.

### Patch

Optional patch for adding a time-stamp to apk version on each build.

### Motivation

I think this is a setup that many might consider using. It's pretty robust, except from this issue. Maybe this can be fixed by changing the version manually using Android SDK, but I think this is a feature that'll come in handy for many.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Changing the package version can lead to unexpected behavior, YouTube for example does A/B based on it, the manager could store, when you patched an app.
