### ISSUE TITLE
Back and restore settings 

### ISSUE THREAD

**Issue by venkat2305** [revanced/revanced-patches#764]
### Application

Revanced YouTube 

### Issue

Won't have to change the settings to our preferences after every single update 

### Patch

Now , if we want to update we have to uninstall the app and settings are not saved. So, for saving settings can you add a backup/restore settings option? 

### Motivation

It's convenient 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
You do not have to uninstall patched apps to update them, the same signing keystore is used both in the ReVanced Manager or CLI.

**Comment by venkat2305** [comment]
> You do not have to uninstall patched apps to update them, the same signing keystore is used both in the ReVanced Manager or CLI.

It would be nice if sponsorblock settings were also saved. is it being saved now?
