### ISSUE TITLE
Feat(patch): Add youtube.com's AV1 Options 

### ISSUE THREAD

**Issue by AlecMcCutcheon** [revanced/revanced-patches#773]
### Application

Youtube Revanced

### Issue

Lack of AV1 options in the youtube app and in the youtube Revanced app

### Patch

On the YouTube website in settings under, playback and performance there is now AV1 Settings. AV1 allows for better stream quality with lower bandwidth requirements so I would just like to see those options in the app

### Motivation

better stream quality with lower bandwidth requirements

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by ashishkotnala29** [comment]
Are you even aware of hardware requirements for AV1? There aren't many smartphones with AV1 hardware accelerated decoding capabilities and if that task is done on CPU (software decoding) then it'll probably be a choppy mess.

**Comment by AlecMcCutcheon** [comment]
I tryed used the software decoding on a 5 year old laptop with low end specs and it was butter smooth. Also, you can open youtube in a browser on your smartphone and view the desktop mode of the site and turn it on and it's butter smooth. I do have an s10+ so maybe it's worse on cheaper phones but all I'm asking for is the option so the user can make that choice

**Comment by AlecMcCutcheon** [comment]
> Are you even aware of hardware requirements for AV1? There aren't many smartphones with AV1 hardware accelerated decoding capabilities and if that task is done on CPU (software decoding) then it'll probably be a choppy mess.

I tried the software decoding on a 5 year old laptop with low end specs and it was butter smooth. Also, you can open youtube in a browser on your smartphone and view the desktop mode of the site and turn it on and it's butter smooth. I do have an s10+ so maybe it's worse on cheaper phones but all I'm asking for is the option so the user can make that choice

**Comment by oSumAtrIX** [comment]
Closing in favour of #909.
