### ISSUE TITLE
bug: TikTok randomly crashes

### ISSUE THREAD

**Issue by St3ph32** [revanced/revanced-patches#775]
### Type

Error at runtime

### Bug description

When scrolling through the TikTok, sometimes it just crashes right before the after scrolling a video. I've not noticed a reason and I have no idea on how to reproduce. It just happens randomly. Sometimes it happens pretty often and some other times it happens after 30 minutes...

### Steps to reproduce

1. Scroll through TikTok.

### Relevant log output

```shell
None.
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Please include logs and disable patches until the error ia gone, report back which patch causes the error.

**Comment by N0nd** [comment]
Re-TikTok [Version 26.5.2]
Patched Date : 13102022
crashes and works unstable on android 9 OxygenOS same problem

interestingly, it works fine on android 11-12 miui


> Please include logs and disable patches until the error ia gone, report back which patch causes the error.

**Comment by St3ph32** [comment]
> > Please include logs and disable patches until the error ia gone, report back which patch causes the error.
> 
> Re-TikTok [Version 26.5.2]
> Patched Date : 13102022
> crashes and works unstable on android 9 OxygenOS same problem
> sometimes the video starts over
> 
> interestingly, it works fine on android 11-12 miui
> 
> 
> 
> 
> 

I use Android 12 Realme UI 3.0

**Comment by N0nd** [comment]
> I use Android 12 Realme UI 3.0

oh, yes, after looking through a little tiktok, I caught a crash on miui 13 android 12, so the problem is massive. general

**Comment by St3ph32** [comment]
> Please include logs and disable patches until the error ia gone, report back which patch causes the error.

I tried all the patches one by one, but the crashes were still pretty random. Maybe I did encounter some more problems with the "TikTok Seekbar" patch. I hope someone can help us understand the exact problem to fix it.

**Comment by jajube** [comment]
Here's the trace. Crashes for me randomly in TikTok 26.7.5 with only seekbar patch enabled. 

> FATAL EXCEPTION: main
Process: com.zhiliaoapp.musically, PID: 11817
java.lang.NullPointerException: Attempt to write to field 'int com.ss.android.ugc.aweme.feed.model.VideoControl.showProgressBar' on a null object reference
	at com.ss.android.ugc.aweme.feed.model.Aweme.getVideoControl(SourceFile:1)
	at X.4iY.onPlayProgressChange(SourceFile:50790530)
	at X.4oN.onPlayProgressChange(SourceFile:50462727)
	at X.4q4.run(SourceFile:196625)
	at android.os.Handler.handleCallback(Unknown Source:2)
	at android.os.Handler.dispatchMessage(Unknown Source:4)
	at android.os.Looper.loopOnce(Unknown Source:176)
	at android.os.Looper.loop(Unknown Source:76)
	at android.app.ActivityThread.main(Unknown Source:138)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:306)

Sometimes tiktok shows a poll asking what do you felt watching the previous video/live.
![Like this.](https://user-images.githubusercontent.com/17009744/201547603-0552e0da-d8aa-43ca-8dfc-f6d80ebaa96b.jpg). It crashed right after I tried to swipe in this screen.

**Comment by CubergDev** [comment]
Can relate, happened to me month ago. After some testing, I found out that this happens on certain accounts (I have 5 account, 2 of them have same issues). All the problems gone in stock tt app, but if it works on some accounts on Revanced tt, then it not likely to be app integrity/signature issue.
Also, when downgrading to Tiktok Revanced , for example 26.7.6 , it works on all accounts for a certain amount of time
So it should be fixable, right?
