### ISSUE TITLE
feat(patch): Reddit in-app weblinks can't be disabled

### ISSUE THREAD

**Issue by PrissyPineapple** [revanced/revanced-patches#780]
### Application

Reddit

### Issue

All links are opened inside the Reddit app with no way to force an external browser.

### Patch

There used to be a toggle in settings that would force all links to be opened outside of reddit, but as of the latest version, this toggle has been removed.

The patch should bring the toggle back, or else enable external browser support.

### Motivation

Browsers like Firefox and DuckDuckGo have tools for privacy and ad-blocking that can't be used when reddit handles the links. This also prevents saving a webpage on your bookmarks or modifying the webpage with dev tools.

Maybe the toggle will be added again, but it seems like a simple enough fix that it should be incorporated into revanced.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by SodaWithoutSparkles** [comment]
Already available in stock reddit app:

![Screenshot_2022-10-30-13-52-05-093-edit_com.reddit.frontpage.jpg](https://user-images.githubusercontent.com/64138578/198864627-e7d7a992-8872-48e7-b3a7-5a679e1a1cca.jpg)

**Comment by PrissyPineapple** [comment]
> Already available in stock reddit app:
> 
> ![Screenshot_2022-10-30-13-52-05-093-edit_com.reddit.frontpage.jpg](https://user-images.githubusercontent.com/64138578/198864627-e7d7a992-8872-48e7-b3a7-5a679e1a1cca.jpg)

iOS or Android? Also what version?

This is not on my reddit app

**Comment by PrissyPineapple** [comment]
![Screenshot_20221030-082232~2](https://user-images.githubusercontent.com/68925884/198878257-093c3f67-9613-4612-adef-cfe32a85063a.png)

**Comment by SodaWithoutSparkles** [comment]
2022.37.0. Reddit avatar > settings > **scroll down**

**Comment by PrissyPineapple** [comment]
Yeah, that's an older version.

If you read my post, I say "There used to be a toggle in settings that would force all links to be opened outside of reddit, but as of the latest version, this toggle has been removed."

**Comment by SodaWithoutSparkles** [comment]
Can you check which version was it removed?
