### ISSUE TITLE
Patch Request :  Amoled Theme doesn't work in "Chapters" Tab in YT Revanced

### ISSUE THREAD

**Issue by Vipin2003** [revanced/revanced-patches#784]
### Application

YouTube Revanced

### Issue

@
![Screenshot_20221014-065043](https://user-images.githubusercontent.com/93650504/195740761-ae0cd189-49a7-4e13-a3d5-4814d2c60507.png)

The background of "Chapters" tab is always dark, even after selecting amoled. This should be Dark in Dark Theme and Pure black in "Amoled" Theme. Attached both Screenshot for better understanding.

![Screenshot_20221014-065000](https://user-images.githubusercontent.com/93650504/195741993-7d7e9357-9d72-4457-b150-4e77aa3bbe2f.png)

### Patch

This patch should make the "Chapters" Tab background Pure black (Amoled) like the "Playlist" tab instead of "Dark" in Amoled YT.

### Motivation

This patch will inhance the look of YT a more perfect with different themes.
Thanks

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by kazimmt** [comment]
@OxrxL bro can you fix it?

**Comment by Vipin2003** [comment]
And 1 thing more that @OxrxL has implemented is "Hide caption Button" from player. There is a bug that after disabling the caption btn, it leaves a blank space in player instead of pushing/shifting the enabled icons to the right. Here is Screenshot:

![Screenshot_20221014-103349~2](https://user-images.githubusercontent.com/93650504/195766736-4e3cce9f-c077-4e1a-bcb0-64a82a237a5b.png)

**Comment by OxrxL** [comment]
I will investigate.
