### ISSUE TITLE
bug: microg-support: Manual root installation startup/playback crash with built-in GMS

### ISSUE THREAD

**Issue by Fantazstic** [revanced/revanced-patches#792]
### Type

Error at runtime

### Bug description

Running ReVanced after manual root installation (`microg-support` excluded, install via SAI/file explorer/built-in APM), the app will open but immediately close. This happens if there is no account signed in at the time of app opening.

Alternatively, if you've used the unpatched APK to log in to an account beforehand, then install the patched APK over the top, you can delay the crash which will then only happen when you try to play a video. After this crash, you receive a message "Couldn't sign in" and cannot play videos from this point. This is probably expired account credentials related, as we have logged in on the unpatched version with different signatures.

### Steps to reproduce

1. Patch APKMirror 17.34.35 APK using revanced-builder/CLI
2. Transfer patched APK to device
3. Install via SAI/file explorer/built-in APM
4. Open app
5. Observe immediate crash or crash when playing videos

### Relevant log output

```shell
N/A
```

### Solution

It seems that excluding `microg-support` results in some unwanted changes to the account management of the app. This is highlighted by the accounts section being empty (as well as the crashes when not signed in), while the unpatched APK allows choosing between accounts, as I presume the link to built-in GMS was established successfully while the app is open for a short amount of time.

Ideally, excluding this patch should make no change to account management. This would allow us to open the sign in menu and view accounts added to the device using built-in GMS.

Delaying the crashes to allow enough time to login would be another solution, but it is more difficult/messy and is less likely to work considering device and installation.

### Additional context

I'm running Android 7.1, therefore I cannot use ReVanced Manager nor the latest APK version. Instead, I use revanced-builder (PC method) and the latest version displayed in the Play Store (17.34.35). I know that all the patches work for this version through testing on higher Android versions, but regardless I have confirmed that the only cause of the issue is including/excluding `microg-support` individually.

I believe this is a known issue on Discord, but has not been added as an issue to Github yet, so tracking is publicly not known. This issue will enable public discussion to progress towards fixing the final breaking issue with root installs.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
If you exclude the MicroG support patch, you are forced to mount the patched application to bypass measurements of GMS. You can not use SAI and install the app regularely without applying the MicroG patch as it is mandatory if you want to install the app instead of mounting it.
