### ISSUE TITLE
bug: Share Button Missing From Videos With Chat if Create, Clip, etc. Are Hidden

### ISSUE THREAD

**Issue by Joomsy** [revanced/revanced-patches#793]
### Type

Cosmetic

### Bug description

Apologies for the long title, but this bug only appears under videos that have a chat. Whether it be a premiered video or a stream, the share button will be missing if "Hide create, clip, and thanks buttons" is enabled.

### Steps to reproduce

Enable the patch, and go to any video with a chat. The share button that's usually between the download and chat buttons will not be present.

### Relevant log output

```shell
N/A
```

### Screenshots or videos

Patch disabled:
![Screenshot_20221015-113250](https://user-images.githubusercontent.com/103767404/195997896-a428a2aa-c371-4091-bee3-5589e3a60388.png)

Patch enabled:
![Screenshot_20221015-113131](https://user-images.githubusercontent.com/103767404/195997901-ab73cb81-7c59-4403-b85c-ec74470de810.png)

### Additional context

Patches 2.82.0
CLI 2.14.0
Integrations 0.52.0

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
#737
