### ISSUE TITLE
enable sorting video with less recent feat(patch): 

### ISSUE THREAD

**Issue by naxil** [revanced/revanced-patches#794]
### Application

Revanced sort video

### Issue

sort videos from oldest to newest

### Patch

sort videos from oldest to newest

### Motivation

discover the birth of a YouTube channel especially when the channel hosts hundreds of videos

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
#33

**Comment by binbohrawa** [comment]
> #33
I don't know why did you mark this as completed, while knowing that you marked it wrong place to post in the other repo,
please re-open this so the devs can see it and maybe make this patch available

**Comment by naxil** [comment]
but this patch has been implemented? I don't see this option. there is only "recent uploads" and "popular". pity I don't know if there is an option in the search bar to view the first video ..
