### ISSUE TITLE
Feature Request: Add patches for 'Truecaller' app

### ISSUE THREAD

**Issue by sayyid5416** [ReVanced/revanced-patches#808]
### Application

True Caller app
Google play link: [here](https://play.google.com/store/apps/details?id=com.truecaller)

### Issue

Many patches could be made to solve these issues:
- There are too many prompts in this app to buy their premium service, It starts feeling like spam.
- So many ads popup in app.
- There are many sections which could be classified as complete clutter.

### Patch

Same as I described above.

### Motivation

- This app is vary popular.
- These patches will help a lot of app users.
- This app is enjoying its monopoly and doing as it feels right, which makes this app too much spammy for their premium service.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gouenji-shuuya** [comment]
> The app has no monopoly, there's infinite similar apps.

This app has a monopoly in India.
