### ISSUE TITLE
feat(patch): Force playback speed to every video.

### ISSUE THREAD

**Issue by SupLiCatinG** [revanced/revanced-patches#811]
### Application

Youtube ReVanced

### Issue

When i change video it defaults playback speed to 1x

### Patch

It forces playback speed to user specified value.

### Motivation

It was already available on vanced. So it would be nice with revanced too.

### Acknowledgements

- [x] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Jowat97** [comment]
@oSumAtrIX Why is it marked as not planed? Vanced had this feature and was used by many many people. And here are dozens of people creating tickets and issues for this topic. Are there any reasons not to implement this feature?

**Comment by SupLiCatinG** [comment]
Definetly, i'm getting sick because of that. I need to apply speed everytime when i want to change video.

**Comment by Jowat97** [comment]
> Definetly, i'm getting sick because of that. I need to apply speed everytime when i want to change video.

Yes, totally agree. Don't understand why this feature wasn't implemented till yet, since it was one of the major functions of YouTube vanced.

@oSumAtrIX Is any help needed to implement this function?

**Comment by oSumAtrIX** [comment]
Closed because Acknowledgements not met.

**Comment by Jowat97** [comment]
@oSumAtrIX Can you maybe specific what exactly you mean? Of course we acknowledge the work. I already created a ticket once, asking politely for this functions and offered to help to implement it.

**Comment by oSumAtrIX** [comment]
![Screenshot_2022-10-22-13-57-50-35_3aea4af51f236e4932235fdada7d1643](https://user-images.githubusercontent.com/13122796/197337721-54ebb4c3-a5af-4f62-ab3b-0ba596698e74.jpg)

**Comment by oSumAtrIX** [comment]
I'll open this issue in favour of closing the discussion so it is moved here.

**Comment by crazdrama** [comment]
im sry but can somebody tell me wht the status of this feature request is??? ive gone through previous posts and saw tht similar issue was closed as not planned...please give some clarity as to whether this feature will be implemented or not

**Comment by Bluscream** [comment]
This is much needed? Why cant anyone make this

**Comment by iznawh** [comment]
Can we PLEASE get this!!

**Comment by Jowat97** [comment]
@oSumAtrIX About 3 weeks ago you wrote that this feature can't be implemented right now, since you have other more prioritized tasks.

So, is it somehow possible to help to get this feature? Actually, it could directly taken from original vanced. We can provide help, support, code submission and testing. We could also help to finish the other tasks, which you have prioritized over this.

People asking for months for this feature, so I guess we can count on massive contribution.

**Comment by oSumAtrIX** [comment]
It is not easy to help, because developing a patch usually is not collaborative. Vanced's implementation is different from what it will be on ReVanced, both in the implementation and usage. The behavior will be similar to the `remember-video-quality` patch with a switch to lock to the current speed. Additionally the implementation of the code has to be refactored from the ground up as just porting over Vanced's implementation will cause implications with readabity and maintainability in the future.

**Comment by Jowat97** [comment]
> It is not easy to help, because developing a patch usually is not collaborative. Vanced's implementation is different from what it will be on ReVanced, both in the implementation and usage. The behavior will be similar to the `remember-video-quality` patch with a switch to lock to the current speed. Additionally the implementation of the code has to be refactored from the ground up as just porting over Vanced's implementation will cause implications with readabity and maintainability in the future.

Okay, I understand. Wouldn't it be possibly just to take the Vanced Version for now until the new one is there? So people wouldn't have to wait for more months and could use an existing patch already.

**Comment by oSumAtrIX** [comment]
We have to expect the current or better code quality, otherwise it will cause implications with readabity and maintainability in the future as previously said.

**Comment by Jowat97** [comment]
> We have to expect the current or better code quality, otherwise it will cause implications with readabity and maintainability in the future as previously said.

Got it, SNT has exactly the same feature. A playback speed remember option, which can be toggled on and off, just as it is planned to be implemented in ReVanced. https://github.com/yuliskov/SmartTubeNext
Could it maybe taken from there? So there wouldn't be need to done from the scratch. If any help or testing is needed, feel free to ask. Many helping hands available here.

**Comment by oSumAtrIX** [comment]
https://github.com/revanced/revanced-integrations/commit/eea37a9bada6c843275236fa232bfe497d178b17
