### ISSUE TITLE
bug: <YT Music Revanced>

### ISSUE THREAD

**Issue by DEVESH1676** [revanced/revanced-patches#815]
### Type

Error while patching

### Bug description

There is a patch called "download" in YT Music Revanced. After clicking it and patching it, I was unable to download any of the songs I wanted.

### Steps to reproduce

**Step 1:** Open the patched or YT Music Revanced.
**Step 2:** Simply search a song.
**Step 3:** Click the three dots in the right top corner.
**Step 4:** Click the "download" option.

### Relevant log output

```shell
Sorry I didn't get any log output of this
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
It is for YouTube.

**Comment by DEVESH1676** [comment]
It is for both YouTube and YouTube Music...but I want download for YouTube Music....

**Comment by oSumAtrIX** [comment]
It is only for YouTube music, you can't select the `downloads` patch for YouTube Music.

**Comment by DEVESH1676** [comment]
> It is only for YouTube music, you can't select the `downloads` patch for YouTube Music.

Ok...so `download` patch is gonna come for YT Music ?
