### ISSUE TITLE
Getting Video Ads on YouTube 

### ISSUE THREAD

**Issue by YouSummoner** [revanced/revanced-patches#819]
### Type

Error at runtime

### Bug description

I'm getting video ads on YouTube after the latest patch update v2.83.2

### Steps to reproduce

1. Patch YouTube with v2.83.2 from manager
2. Open YouTube
3. Play a video 

### Relevant log output

```shell
--------- beginning of main
10-20 19:18:36.454 29873 29873 E manager.flutter: Not starting debugger since process cannot load the jdwp agent.
10-20 19:18:36.456 29873 29873 D ProcessState: Binder ioctl to enable oneway spam detection failed: Invalid argument
10-20 19:18:36.493 29873 29873 D CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10443; state: ENABLED
10-20 19:18:36.588 29873 29873 V GraphicsEnvironment: ANGLE Developer option for 'app.revanced.manager.flutter' set to: 'default'
10-20 19:18:36.589 29873 29873 V GraphicsEnvironment: ANGLE GameManagerService for app.revanced.manager.flutter: false
10-20 19:18:36.663 29873 29873 W manager.flutter: type=1400 audit(0.0:1085): avc: denied { read } for name="max_map_count" dev="proc" ino=3337882 scontext=u:r:untrusted_app:s0:c187,c257,c512,c768 tcontext=u:object_r:proc_max_map_count:s0 tclass=file permissive=0 app=app.revanced.manager.flutter
10-20 19:18:36.676 29873 29873 I AdrenoGLES-0: QUALCOMM build                   : 5af5ff1, Iff02ff076a
10-20 19:18:36.676 29873 29873 I AdrenoGLES-0: Build Date                       : 01/05/21
10-20 19:18:36.676 29873 29873 I AdrenoGLES-0: OpenGL ES Shader Compiler Version: EV031.32.02.06
10-20 19:18:36.676 29873 29873 I AdrenoGLES-0: Local Branch                     : mybrancheb4f33c0-fd8a-f1f2-ab18-5cb90179c3d8
10-20 19:18:36.676 29873 29873 I AdrenoGLES-0: Remote Branch                    : quic/gfx-adreno.lnx.1.0.r114-rel
10-20 19:18:36.676 29873 29873 I AdrenoGLES-0: Remote Branch                    : NONE
10-20 19:18:36.676 29873 29873 I AdrenoGLES-0: Reconstruct Branch               : NOTHING
10-20 19:18:36.676 29873 29873 I AdrenoGLES-0: Build Config                     : S P 10.0.7 AArch64
10-20 19:18:36.676 29873 29873 I AdrenoGLES-0: Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
10-20 19:18:36.683 29873 29873 I AdrenoGLES-0: PFP: 0x016ee190, ME: 0x00000000
10-20 19:18:36.803 29873 29892 D hw-ProcessState: Binder ioctl to enable oneway spam detection failed: Invalid argument
10-20 19:18:36.818 29873 29897 I flutter : ReVanced API: Using CronetEngine + true
10-20 19:18:36.819 29873 29897 I flutter : ReVanced API: Using CronetEngine + true
10-20 19:18:36.842 29873 29911 W SQLiteLog: (28) double-quoted string literal: "0B1FF185ABD2EC1F352F76FABC54C393"
10-20 19:18:36.842 29873 29911 W SQLiteLog: (28) double-quoted string literal: "22D1CC376C54BE531C0A569AA1492CA8"
10-20 19:18:37.190 29873 29897 I flutter : dynamic_color: Core palette detected.
10-20 19:18:37.242 29873 29898 I Gralloc4: mapper 4.x is not supported
10-20 19:18:37.243 29873 29898 W Gralloc3: mapper 3.x is not supported
10-20 19:18:37.247 29873 29911 W SQLiteLog: (28) double-quoted string literal: "8384255B7F11AA240121190919F1B9E3"
10-20 19:18:37.247 29873 29911 W SQLiteLog: (28) double-quoted string literal: "22D1CC376C54BE531C0A569AA1492CA8"
10-20 19:18:37.251 29873 29898 W Gralloc4: allocator 4.x is not supported
10-20 19:18:37.252 29873 29898 W Gralloc3: allocator 3.x is not supported
10-20 19:18:37.254 29873 29898 I Gralloc2: Adding additional valid usage bits: 0x0
10-20 19:18:37.308 29873 29898 E BLASTBufferQueue: [SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity]#1](f:0,a:0) rejecting buffer:active_size=1080x2340, requested_size=1080x2340 buffer{size=1080x2298 transform=0}
10-20 19:18:37.419 29927 29927 W sh      : type=1400 audit(0.0:1086): avc: denied { read } for name="/" dev="sda11" ino=2 scontext=u:r:untrusted_app:s0:c187,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
10-20 19:18:37.431 29927 29927 W sh      : type=1400 audit(0.0:1087): avc: denied { read } for name="/" dev="sda11" ino=2 scontext=u:r:untrusted_app:s0:c187,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
10-20 19:18:37.447 29927 29927 W sh      : type=1400 audit(0.0:1088): avc: denied { read } for name="/" dev="sda11" ino=2 scontext=u:r:untrusted_app:s0:c187,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
10-20 19:18:37.459 29927 29927 W sh      : type=1400 audit(0.0:1089): avc: denied { read } for name="/" dev="sda11" ino=2 scontext=u:r:untrusted_app:s0:c187,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
10-20 19:18:37.491 29927 29927 W sh      : type=1400 audit(0.0:1090): avc: denied { read } for name="/" dev="sda11" ino=2 scontext=u:r:untrusted_app:s0:c187,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
10-20 19:18:37.515 29927 29927 W sh      : type=1400 audit(0.0:1091): avc: denied { read } for name="/" dev="sda11" ino=2 scontext=u:r:untrusted_app:s0:c187,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
10-20 19:18:37.527 29927 29927 W sh      : type=1400 audit(0.0:1092): avc: denied { read } for name="/" dev="sda11" ino=2 scontext=u:r:untrusted_app:s0:c187,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
10-20 19:18:38.463 29927 29927 W sh      : type=1400 audit(0.0:1097): avc: denied { read } for name="/" dev="sda11" ino=2 scontext=u:r:untrusted_app:s0:c187,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
10-20 19:18:38.491 29927 29927 W sh      : type=1400 audit(0.0:1098): avc: denied { read } for name="/" dev="sda11" ino=2 scontext=u:r:untrusted_app:s0:c187,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
10-20 19:18:38.507 29927 29927 W sh      : type=1400 audit(0.0:1099): avc: denied { read } for name="/" dev="sda11" ino=2 scontext=u:r:untrusted_app:s0:c187,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
10-20 19:18:38.519 29927 29927 W sh      : type=1400 audit(0.0:1100): avc: denied { read } for name="/" dev="sda11" ino=2 scontext=u:r:untrusted_app:s0:c187,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
10-20 19:18:38.531 29927 29927 W sh      : type=1400 audit(0.0:1101): avc: denied { read } for name="/" dev="sda11" ino=2 scontext=u:r:untrusted_app:s0:c187,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
10-20 19:18:38.800 29873 29911 W SQLiteLog: (28) double-quoted string literal: "484091CDFBF54C9C82180F6C7CC4C586"
10-20 19:18:38.800 29873 29911 W SQLiteLog: (28) double-quoted string literal: "091BFE9B52D3E2EF6B11652EB2B23312"
10-20 19:18:38.807 29873 29911 W SQLiteLog: (28) double-quoted string literal: "484091CDFBF54C9C82180F6C7CC4C586"
10-20 19:18:38.808 29873 29911 W SQLiteLog: (28) double-quoted string literal: "C23528AD206B8585FB35385B2EE99ABA"
```

### Screenshots or videos

![Screenshot_20221020-191827_YouTube](https://user-images.githubusercontent.com/107224555/196968140-4f8be18a-b319-4940-8ff8-9f2f9be0f621.png)
![Screenshot_20221020-191911_YouTube.png](https://user-images.githubusercontent.com/107224555/196968614-f1c6fc48-efc7-4213-889a-68d1b2157360.png)

### Solution

None

### Additional context

This wasn't happening until the latest patch update by the way.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by daniel3xxx** [comment]
I can confirm this too. Error while applying the video ads patch.

**Comment by oSumAtrIX** [comment]
Please record patching the app.

**Comment by YouSummoner** [comment]
> Please record patching the app
Patching Logs###

Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing all patches
Executing 'resource-mapping' of type: resource
Executing 'integrations' of type: bytecode
Skipping 'integrations' because it has already been applied
Executing 'locale-config-fix' of type: resource
Skipping 'resource-mapping' because it has already been applied
Executing 'settings-resource-patch' of type: resource
Executing 'settings' of type: bytecode
Skipping 'locale-config-fix' because it has already been applied
Executing 'general-resource-ads' of type: resource
Executing 'general-ads' of type: bytecode
[success] general-ads
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'hide-infocard-suggestions' of type: bytecode
[success] hide-infocard-suggestions
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'video-ads' of type: bytecode
[error] video-ads:kotlin.Unit
Skipping 'locale-config-fix' because it has already been applied
Executing 'bottom-controls-resource-patch' of type: resource
Skipping 'locale-config-fix' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'downloads-resource-patch' of type: resource
Skipping 'resource-mapping' because it has already been applied
Executing 'player-controls-bytecode-patch' of type: bytecode
Skipping 'integrations' because it has already been applied
Executing 'video-id-hook' of type: bytecode
Executing 'downloads' of type: bytecode
[success] downloads
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'seekbar-tapping' of type: bytecode
[success] seekbar-tapping
Skipping 'integrations' because it has already been applied
Skipping 'integrations' because it has already been applied
Executing 'player-type-hook' of type: bytecode
Skipping 'settings' because it has already been applied
Executing 'swipe-controls-resource-patch' of type: resource
Executing 'swipe-controls' of type: bytecode
[success] swipe-controls
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'disable-auto-captions' of type: bytecode
[success] disable-auto-captions
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Skipping 'resource-mapping' because it has already been applied
Executing 'hide-autoplay-button' of type: bytecode
[success] hide-autoplay-button
Skipping 'locale-config-fix' because it has already been applied
Executing 'premium-heading' of type: resource
[success] premium-heading
Skipping 'resource-mapping' because it has already been applied
Skipping 'general-ads' because it has already been applied
Executing 'hide-video-buttons' of type: resource
[success] hide-video-buttons
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'disable-fullscreen-panels' of type: bytecode
[success] disable-fullscreen-panels
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'hide-time-and-seekbar' of type: bytecode
[success] hide-time-and-seekbar
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'old-quality-layout' of type: bytecode
[success] old-quality-layout
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Skipping 'resource-mapping' because it has already been applied
Executing 'hide-email-address' of type: bytecode
[success] hide-email-address
Skipping 'integrations' because it has already been applied
Skipping 'resource-mapping' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'hide-create-button' of type: bytecode
[success] hide-create-button
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'hide-shorts-button' of type: bytecode
[error] hide-shorts-button:kotlin.Unit
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'disable-auto-player-popup-panels' of type: bytecode
[success] disable-auto-player-popup-panels
Skipping 'integrations' because it has already been applied
Skipping 'video-id-hook' because it has already been applied
Skipping 'locale-config-fix' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'return-youtube-dislike-resource-patch' of type: resource
Executing 'return-youtube-dislike' of type: bytecode
[success] return-youtube-dislike
Skipping 'player-controls-bytecode-patch' because it has already been applied
Skipping 'integrations' because it has already been applied
Skipping 'locale-config-fix' because it has already been applied
Skipping 'settings' because it has already been applied
Skipping 'resource-mapping' because it has already been applied
Executing 'sponsorblock-resource-patch' of type: resource
Skipping 'video-id-hook' because it has already been applied
Executing 'sponsorblock' of type: bytecode
[success] sponsorblock
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'disable-startup-shorts-player' of type: bytecode
[success] disable-startup-shorts-player
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'tablet-mini-player' of type: bytecode
[success] tablet-mini-player
Executing 'comment-filter-bar-theme' of type: bytecode
Skipping 'locale-config-fix' because it has already been applied
Executing 'theme' of type: resource
[success] theme
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'hide-watermark' of type: bytecode
[success] hide-watermark
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'enable-wide-searchbar' of type: bytecode
[success] enable-wide-searchbar
Skipping 'integrations' because it has already been applied
Executing 'always-autorepeat' of type: bytecode
[success] always-autorepeat
Executing 'client-spoof' of type: bytecode
[success] client-spoof
Skipping 'integrations' because it has already been applied
Skipping 'resource-mapping' because it has already been applied
Executing 'custom-playback-speed' of type: bytecode
[success] custom-playback-speed
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'enable-debugging' of type: resource
[success] enable-debugging
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'hdr-auto-brightness' of type: bytecode
[success] hdr-auto-brightness
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'minimized-playback' of type: bytecode
[success] minimized-playback
Skipping 'integrations' because it has already been applied
Skipping 'video-id-hook' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'remember-video-quality' of type: bytecode
[success] remember-video-quality
Skipping 'settings' because it has already been applied
[success] settings
Skipping 'settings' because it has already been applied
Executing 'custom-video-buffer' of type: bytecode
[success] custom-video-buffer
Repacking patched apk
Compiling resources
Creating new dex file
Writing modified dex files
Finished!

**Comment by YouSummoner** [comment]
> > Please record patching the app
> Patching Logs###
> 
> Initializing installer
> Creating working directory
> Copying original apk
> Unpacking input apk
> Reading dex files
> Decoding AndroidManifest.xml only, because resources are not needed
> Merging integrations
> Deleting existing resource cache directory
> Decoding resources
> Executing all patches
> Executing 'resource-mapping' of type: resource
> Executing 'integrations' of type: bytecode
> Skipping 'integrations' because it has already been applied
> Executing 'locale-config-fix' of type: resource
> Skipping 'resource-mapping' because it has already been applied
> Executing 'settings-resource-patch' of type: resource
> Executing 'settings' of type: bytecode
> Skipping 'locale-config-fix' because it has already been applied
> Executing 'general-resource-ads' of type: resource
> Executing 'general-ads' of type: bytecode
> [success] general-ads
> Skipping 'integrations' because it has already been applied
> Skipping 'settings' because it has already been applied
> Executing 'hide-infocard-suggestions' of type: bytecode
> [success] hide-infocard-suggestions
> Skipping 'integrations' because it has already been applied
> Skipping 'settings' because it has already been applied
> Executing 'video-ads' of type: bytecode
> [error] video-ads:kotlin.Unit
> Skipping 'locale-config-fix' because it has already been applied
> Executing 'bottom-controls-resource-patch' of type: resource
> Skipping 'locale-config-fix' because it has already been applied
> Skipping 'settings' because it has already been applied
> Executing 'downloads-resource-patch' of type: resource
> Skipping 'resource-mapping' because it has already been applied
> Executing 'player-controls-bytecode-patch' of type: bytecode
> Skipping 'integrations' because it has already been applied
> Executing 'video-id-hook' of type: bytecode
> Executing 'downloads' of type: bytecode
> [success] downloads
> Skipping 'integrations' because it has already been applied
> Skipping 'settings' because it has already been applied
> Executing 'seekbar-tapping' of type: bytecode
> [success] seekbar-tapping
> Skipping 'integrations' because it has already been applied
> Skipping 'integrations' because it has already been applied
> Executing 'player-type-hook' of type: bytecode
> Skipping 'settings' because it has already been applied
> Executing 'swipe-controls-resource-patch' of type: resource
> Executing 'swipe-controls' of type: bytecode
> [success] swipe-controls
> Skipping 'integrations' because it has already been applied
> Skipping 'settings' because it has already been applied
> Executing 'disable-auto-captions' of type: bytecode
> [success] disable-auto-captions
> Skipping 'integrations' because it has already been applied
> Skipping 'settings' because it has already been applied
> Skipping 'resource-mapping' because it has already been applied
> Executing 'hide-autoplay-button' of type: bytecode
> [success] hide-autoplay-button
> Skipping 'locale-config-fix' because it has already been applied
> Executing 'premium-heading' of type: resource
> [success] premium-heading
> Skipping 'resource-mapping' because it has already been applied
> Skipping 'general-ads' because it has already been applied
> Executing 'hide-video-buttons' of type: resource
> [success] hide-video-buttons
> Skipping 'integrations' because it has already been applied
> Skipping 'settings' because it has already been applied
> Executing 'disable-fullscreen-panels' of type: bytecode
> [success] disable-fullscreen-panels
> Skipping 'integrations' because it has already been applied
> Skipping 'settings' because it has already been applied
> Executing 'hide-time-and-seekbar' of type: bytecode
> [success] hide-time-and-seekbar
> Skipping 'integrations' because it has already been applied
> Skipping 'settings' because it has already been applied
> Executing 'old-quality-layout' of type: bytecode
> [success] old-quality-layout
> Skipping 'integrations' because it has already been applied
> Skipping 'settings' because it has already been applied
> Skipping 'resource-mapping' because it has already been applied
> Executing 'hide-email-address' of type: bytecode
> [success] hide-email-address
> Skipping 'integrations' because it has already been applied
> Skipping 'resource-mapping' because it has already been applied
> Skipping 'settings' because it has already been applied
> Executing 'hide-create-button' of type: bytecode
> [success] hide-create-button
> Skipping 'integrations' because it has already been applied
> Skipping 'settings' because it has already been applied
> Executing 'hide-shorts-button' of type: bytecode
> [error] hide-shorts-button:kotlin.Unit
> Skipping 'integrations' because it has already been applied
> Skipping 'settings' because it has already been applied
> Executing 'disable-auto-player-popup-panels' of type: bytecode
> [success] disable-auto-player-popup-panels
> Skipping 'integrations' because it has already been applied
> Skipping 'video-id-hook' because it has already been applied
> Skipping 'locale-config-fix' because it has already been applied
> Skipping 'settings' because it has already been applied
> Executing 'return-youtube-dislike-resource-patch' of type: resource
> Executing 'return-youtube-dislike' of type: bytecode
> [success] return-youtube-dislike
> Skipping 'player-controls-bytecode-patch' because it has already been applied
> Skipping 'integrations' because it has already been applied
> Skipping 'locale-config-fix' because it has already been applied
> Skipping 'settings' because it has already been applied
> Skipping 'resource-mapping' because it has already been applied
> Executing 'sponsorblock-resource-patch' of type: resource
> Skipping 'video-id-hook' because it has already been applied
> Executing 'sponsorblock' of type: bytecode
> [success] sponsorblock
> Skipping 'integrations' because it has already been applied
> Skipping 'settings' because it has already been applied
> Executing 'disable-startup-shorts-player' of type: bytecode
> [success] disable-startup-shorts-player
> Skipping 'integrations' because it has already been applied
> Skipping 'settings' because it has already been applied
> Executing 'tablet-mini-player' of type: bytecode
> [success] tablet-mini-player
> Executing 'comment-filter-bar-theme' of type: bytecode
> Skipping 'locale-config-fix' because it has already been applied
> Executing 'theme' of type: resource
> [success] theme
> Skipping 'integrations' because it has already been applied
> Skipping 'settings' because it has already been applied
> Executing 'hide-watermark' of type: bytecode
> [success] hide-watermark
> Skipping 'integrations' because it has already been applied
> Skipping 'settings' because it has already been applied
> Executing 'enable-wide-searchbar' of type: bytecode
> [success] enable-wide-searchbar
> Skipping 'integrations' because it has already been applied
> Executing 'always-autorepeat' of type: bytecode
> [success] always-autorepeat
> Executing 'client-spoof' of type: bytecode
> [success] client-spoof
> Skipping 'integrations' because it has already been applied
> Skipping 'resource-mapping' because it has already been applied
> Executing 'custom-playback-speed' of type: bytecode
> [success] custom-playback-speed
> Skipping 'integrations' because it has already been applied
> Skipping 'settings' because it has already been applied
> Executing 'enable-debugging' of type: resource
> [success] enable-debugging
> Skipping 'integrations' because it has already been applied
> Skipping 'settings' because it has already been applied
> Executing 'hdr-auto-brightness' of type: bytecode
> [success] hdr-auto-brightness
> Skipping 'integrations' because it has already been applied
> Skipping 'settings' because it has already been applied
> Executing 'minimized-playback' of type: bytecode
> [success] minimized-playback
> Skipping 'integrations' because it has already been applied
> Skipping 'video-id-hook' because it has already been applied
> Skipping 'settings' because it has already been applied
> Executing 'remember-video-quality' of type: bytecode
> [success] remember-video-quality
> Skipping 'settings' because it has already been applied
> [success] settings
> Skipping 'settings' because it has already been applied
> Executing 'custom-video-buffer' of type: bytecode
> [success] custom-video-buffer
> Repacking patched apk
> Compiling resources
> Creating new dex file
> Writing modified dex files
> Finished!

You can see the error at
Executing 'video-ads' of type: bytecode
[error] video-ads:kotlin.Unit

**Comment by oSumAtrIX** [comment]
A recording, not a screenshot.

**Comment by YouSummoner** [comment]
> A recording, not a screenshot.

Recording of the patching process?

**Comment by OxrxL** [comment]
https://github.com/revanced/revanced-patches/commit/666248ae65d1ee84d1a278714c0dcd2528c5dd14

**Comment by YouSummoner** [comment]
No, it still gives the exact same error messages while patching video ads and hide shorts button, fix needed ASAP 🥲

**Comment by YouSummoner** [comment]
> https://github.com/revanced/revanced-patches/commit/666248ae65d1ee84d1a278714c0dcd2528c5dd14

Still same error...

**Comment by YouSummoner** [comment]
> > https://github.com/revanced/revanced-patches/commit/666248ae65d1ee84d1a278714c0dcd2528c5dd14
> 
> Still same error... On v2.85.0

**Comment by oSumAtrIX** [comment]
@YouSummoner record the patch process, only include the `video-ads` patch.
