### ISSUE TITLE
Make Splash Screen Background Black.

### ISSUE THREAD

**Issue by AdishSagarawat** [revanced/revanced-patches#82]
![image](https://user-images.githubusercontent.com/69076256/176658584-d8eee465-0770-4cca-a3d0-8e7f53fbf5aa.png)

See, its grey.

**Comment by AdishSagarawat** [comment]
Still Grey

**Comment by TheJeterLP** [comment]
> Still Grey

Yes, Issue is still open.

**Comment by OxrxL** [comment]
> ![image](https://user-images.githubusercontent.com/69076256/176658584-d8eee465-0770-4cca-a3d0-8e7f53fbf5aa.png)
> 
> See, its grey.

Done (on my custom client). Will come on ReVanced after main features implementation.

https://user-images.githubusercontent.com/108184954/183548731-51d98575-fbac-4e6a-b9dc-c6e093cfe8e9.mp4
