### ISSUE TITLE
Youtube Revanced crashes after login with microg

### ISSUE THREAD

**Issue by anxiouslelimo** [revanced/revanced-patches#833]
### Type

Error at runtime

### Bug description

Built revanced youtube using revanced-builder. Installed microg and then youtube apks. After login with microg revanced crashes at startup. Uninstalling microg, clearing youtube storage also did not help. 

However revanced worked before login with microg. 

 Patches version - 2.85.1
 Youtube version - 17.36.37

### Steps to reproduce

1. Build using revanced-builder.
2. Install microg
3. Install revanced youtube
4. Login with microg

### Relevant log output

```shell
NA
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [ ] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Please use official tools and provide logs.

**Comment by anxiouslelimo** [comment]
On a note tried without hide create button patch. Now it works. Updating on #825 .
