### ISSUE TITLE
Disable/not prioritize AV1 codec

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [revanced/revanced-patches#834]
### Application

Youtube

### Issue

Some devices handle AV1 poorly. For example, combined with faster playback speed patch, my device drops to about 9 fps for AV1 for anything more than 2x but can still process 2k60 VP9 up to 5x

### Patch

1. Not select AV1 by default
2. Use VP9 when playback speed > 2x
3. Completely disable AV1
4. Selection of differnet codec in quality tab

Any of the above is fine, ordered by preference, smaller number is better

### Motivation

AV1 is more resource intensive. Although it is more compressed, it needs more CPU resources, which might translate to more battery drain. 

Although most of the device can handle AV1 in default settings, with the faster playback speed patch this might not be the case.

Google is also pushing AV1 to reduce their bandwidth cost. With more and more videos using AV1, the aforementioned issues might be more serious.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
RE: #66

**Comment by SodaWithoutSparkles** [comment]
VP9 is _enabled_ by default, but not _prioritized_

**Comment by outusuke** [comment]
if possible add patch for other formats like AVC codec (H.264)

**Comment by SodaWithoutSparkles** [comment]
> if possible add patch for other formats like AVC codec (H.264)

Its not possible if theres no H264 codec available on the YT server. I dont think they had it, you could use yt-dlp to check formats.

**Comment by outusuke** [comment]
> > if possible add patch for other formats like AVC codec (H.264)
> 
> Its not possible if theres no H264 codec available on the YT server. I dont think they had it, you could use yt-dlp to check formats.

H264 is mp4 format, all videos on youtube have this format along with webm and av1.
If this functionality is not possible to implement, I ask that at least the patch to force 30 fps instead of 60

**Comment by oSumAtrIX** [comment]
Closing in favour of #909.
