### ISSUE TITLE
[TikTok] can't login with google on patched app

### ISSUE THREAD

**Issue by letruxux** [revanced/revanced-patches#839]
### Type

Other

### Bug description

When i try to login with Google, it lets me select the account and then it doesn't do stuff

### Steps to reproduce

1. install the patched version of tiktok
2. login with Google

### Relevant log output

```shell
no logs
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Because the signature doesn't match anymore the Google API does not allow you to login, use Email login.
