### ISSUE TITLE
YT: Layout Change Bug: Video Buttons: ReturnYouTubeDislike dislike count doesn't work

### ISSUE THREAD

**Issue by autodistries** [revanced/revanced-patches#847]
# **Application**

YouTube

# **Issue**

The layout change makes the dislike count not shown despite using `return-youtibe-dislike`
![](https://i.redd.it/ar8mqb1k8uv91.jpg)
App version: 17.40.35

# **Patch**

The patch to modify would be `return-youtube-dislike`

# **Motivation**

It is not possible anymore to see the dislike count

# **Acknowledgements**

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X]   I have written a short but informative title.
- [X]   I filled out all of the requested information in this issue properly.

**Comment by autodistries** [comment]
I'm sorry for not finding a way to add the `change-required` label

**Comment by oSumAtrIX** [comment]
Fixed.
