### ISSUE TITLE
feat(patch): Facebook Lite AdFree

### ISSUE THREAD

**Issue by iSmokeMid69** [revanced/revanced-patches#848]
### Application

Facebook Lite

### Issue

Remove Sponsor Post,Ads

### Patch

Remove Ads

### Motivation

Facebook Has A Lot Of Users

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
React Native apps can't be patched.
