### ISSUE TITLE
feat(youtubemusic): hide "Try YouTube Music Premium" promo ad

### ISSUE THREAD

**Issue by Julius8900** [ReVanced/revanced-patches#854]
### Application

YouTube Music

### Issue

There is a fullscreen ad for trying YouTube Music Premium when I open the app. You can see it in the screenshot below. I patched using recommended patches + the "compact-header" patch.
![Screenshot_2023-05-28-18-54-06-793_app revanced android apps youtube music](https://github.com/revanced/revanced-patches/assets/124190185/63e9a896-c649-4316-809f-81329943feb3)

Here is also the patching log:
[revanced-manager_patcher_20230528185704446061.log](https://github.com/revanced/revanced-patches/files/11585051/revanced-manager_patcher_20230528185704446061.log)

### Patch

The patch hides the ad

### Motivation

Because an identical patch was done for the normal YouTube app too.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Moving to https://github.com/ReVanced/revanced-patches/issues/3032
