### ISSUE TITLE
feat(patch): preferred video quality over wifi and cellular

### ISSUE THREAD

**Issue by Gamerdotio** [revanced/revanced-patches#868]
### Application

Youtube

### Issue

Preferred video quality over Wi-Fi and cellular from vanced with proper quality selection ![Screenshot_20221024-192326_YouTube](https://user-images.githubusercontent.com/95888753/198033933-a41e6683-1c1b-4f23-8aff-412dc28aaedb.jpg)

### Patch

Introduce this option into revanced

### Motivation

This would save time by not needing to switch the quality when switching between wifi and cellular and would provide more accurate quality selection over Youtube's built in setting
![Screenshot_20221026-091717_YouTube](https://user-images.githubusercontent.com/95888753/198035979-eebc51c5-973f-4a83-a3a7-3b9214faec22.jpg)

### Acknowledgements

- [x] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Canny1913** [comment]
This is already implemented in `remember-video-quality` patch.

**Comment by SpacEagle17** [comment]
I have enabled the patch `remember-video-quality` but I don't have this menu.
![image](https://user-images.githubusercontent.com/46494907/198608470-2852090a-61d5-492b-9b3b-d294c2b7f929.png)

**Comment by Canny1913** [comment]
> I have enabled the patch `remember-video-quality` but I don't have this menu. ![image](https://user-images.githubusercontent.com/46494907/198608470-2852090a-61d5-492b-9b3b-d294c2b7f929.png)

Please read the patch description.

**Comment by SpacEagle17** [comment]
I am not sure if I understand correctly, the description does not mention anything about having more control over video quality on wifi or celular and I also don't have that option but you mentioned that this patch does indeed also implement this feature.
![Screenshot_2022-10-28-15-39-42-585_com android chrome](https://user-images.githubusercontent.com/46494907/198617922-648a5aa4-31aa-4fff-ad57-02511b0ae72f.png)
![Screenshot_2022-10-28-15-38-12-706_com android chrome](https://user-images.githubusercontent.com/46494907/198617982-526724f6-bae2-4aab-a15c-04945be8cb47.png)

**Comment by oSumAtrIX** [comment]
The description of the patch says how it works @SpacEagle17. Please try and see, it's faster than waiting for a response.

**Comment by SpacEagle17** [comment]
![Screenshot_2022-10-28-15-54-02-062_com android chrome](https://user-images.githubusercontent.com/46494907/198625799-00a47b04-1487-4244-b53a-3578ce6b6be0.png)
I only see this in the description, am I not seeing something?

**Comment by oSumAtrIX** [comment]
No, thats the correct one.

**Comment by SpacEagle17** [comment]
But that does not mention anything about video quality preferences on wifi or celular.

**Comment by oSumAtrIX** [comment]
As previously mentioned:
> Please try and see, it's faster than waiting for a response.

**Comment by SpacEagle17** [comment]
I am not sure what I should try? The menu to select the preferred video quality over wifi or cellular does not exist, or at least not the one where you can specify a specific quality, only the built-in one by YouTube which says automatic, higher quality or data saver. Maybe I am also looking in the wrong place, but I went through all menus afaik.

**Comment by oSumAtrIX** [comment]
The quality menu flyout is natively available by YouTube in the video player settings menu.

**Comment by SpacEagle17** [comment]
![Screenshot_2022-10-28-16-12-06-609_app.revanced.android.youtube.png](https://user-images.githubusercontent.com/46494907/198636266-f762b970-d69c-42db-a587-90af61d064e0.png)
I don't see anything more than this

**Comment by oSumAtrIX** [comment]
The description of the related patch explains.

**Comment by SpacEagle17** [comment]
I am very sorry, but I don't think that I can follow.

**Comment by Ushie** [comment]
The patch will remember the selected quality without having to manually set it each time, you set it once and it will stay the same until you change it yourself

The patch description doesn't really explain the usage of the patch, there's a few buzz words like "flyout" that even I don't understand ("in video quality selector" might be the better way to say it) , I might open a PR to improve wording a little bit later

**Comment by SpacEagle17** [comment]
Ah thank you! So it remembers the quality you have set it while using wifi separately to the quality you have set it last time using cellular? So if I have set it to 1080p while on wifi it will always be 1080p while using wifi and if I have set it to 480p while using cellular it will automatically switch to 480p when using cellular?

**Comment by Ushie** [comment]
Exactly that!

**Comment by SpacEagle17** [comment]
Well thanks for explaining! The description was a bit unclear hehe
