### ISSUE TITLE
feat(patch): Auto dark mode in video

### ISSUE THREAD

**Issue by kastentop2005** [revanced/revanced-patches#871]
### Application

YouTube 

### Issue

Changing to dark mode on video page while whatching it

### Patch

Because YouTube has just released their new ambient UI and because it only works in dark mode, it would be a great option to automatically switch to it while video is playing

### Motivation

For design enjoyers it is must have

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [ ] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
That would flash you at night if you go out of the video, not a good idea.
