### ISSUE TITLE
bug: Hide Crowdfundings patch doesn't work/ doesn't do anything)

### ISSUE THREAD

**Issue by Domiiniik** [revanced/revanced-patches#879]
### Type

Cosmetic

### Bug description

Crowdfundings are still shown

### Steps to reproduce

Try to enable crowdfundings patch and see a video which contains crowdfunding (the professional videos for instance)

### Relevant log output

```shell
-
```

### Screenshots or videos

Title

### Solution

Title

### Additional context

Title

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by OxrxL** [comment]
It works for me on this video: https://youtu.be/gsi2Pn13BgI

**Before**
<img width="194" alt="Immagine 2022-10-28 012157" src="https://user-images.githubusercontent.com/108184954/198415871-2e3d53c9-7ef9-4963-839d-419ba6d1af1c.png">

**After**
<img width="191" alt="Immagine 2022-10-28 012104" src="https://user-images.githubusercontent.com/108184954/198415902-019ce0fc-8d1a-4940-a9ec-ee80bc27237b.png">

**Comment by Domiiniik** [comment]
It seems to work now in 17.41.37, but it didnt in older versions, weird.

**Comment by OxrxL** [comment]
> It seems to work now in 17.41.37, but it didnt in older versions, weird.

Well...maybe was just a temporary problem.

**Comment by Matty003** [comment]
I've never seen crowdfunding box after enabling it's **toggle**. Although, i clear revanced data after every version update.

**Comment by ILoveOpenSourceApplications** [comment]
Sounds like this issue doesn't exist anymore. Closing for now.
