### ISSUE TITLE
bug: selecting text in comment will spawn big white block

### ISSUE THREAD

**Issue by AMSAMSAMSAMS** [revanced/revanced-patches#882]
### Type

Cosmetic

### Bug description

This happened since Vanced era, dunno what caused it.

### Steps to reproduce

Just type anything in comment, don't send.
Instead just long press to select & BOOM!

### Relevant log output

```shell
NO LOG as this is cosmetic.
```

### Screenshots or videos

![Screenshot_20221027-172517_YouTube](https://user-images.githubusercontent.com/110509194/198487073-1e69bd80-c0c0-4cb2-a504-4bf8474c7256.jpg)

### Acknowledgements

- [x] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by AMSAMSAMSAMS** [comment]
Worse it duplicated on the video section & undismissable....

**Comment by OxrxL** [comment]
Can't be fixed unfortunately.

**Comment by oSumAtrIX** [comment]
> Can't be fixed unfortunately.

Why?

**Comment by oSumAtrIX** [comment]
Did you include the `theme` patch?

**Comment by Crescendo-BLYAT** [comment]
> Did you include the `theme` patch?

nope... I excluded `theme` patch...

**Comment by oSumAtrIX** [comment]
This is an issue with your Android OS. Disable it forcing theming on the patched app.

**Comment by SodaWithoutSparkles** [comment]
I cannot reproduce this

**Comment by AMSAMSAMSAMS** [comment]
> This is an issue with your Android OS. Disable it forcing theming on the patched app.

Samsung S20FE - OneUI 4.1 - Android 12 - not rooted - no OS theme applied.
So I just enable the ReVanced theme to fix it?

**Comment by anil-al** [comment]
It also happens to me. Android 10, Oppo A5 2020; Android 12L, Tab S8+. I blocks writing and you have to touch a random button on keyboard for it going away.

**Comment by oSumAtrIX** [comment]
> EDIT: Nope, ommiting **-e theme** (thus enabling the default theme) doesn't fix anything.

As I said, it is not an issue with ReVanced, you force override dark mode on your device. Disable it for the patched app and it should work.
