### ISSUE TITLE
feat(patch): Add Truecaller To ReVanced Patches

### ISSUE THREAD

**Issue by LegendarySpinx** [ReVanced/revanced-patches#884]
### Application

Hi there,
I request you to add Truecaller to ReVanced Patches.

For help you can contact @iam_ajeethk on Telegram.

### Issue

Please add Truecaller to ReVanced Patches 

### Patch

No Ads, amoled theme , premium and gold features working.

### Motivation

One of the most popular phone app.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by PandoraHayami** [comment]
Patches are maintained by the community, if you want to see it, wait for someone who knows how to do it and likes the app to do it, pay someone for it, or do it yourself? :D

**Comment by SodaWithoutSparkles** [comment]
> One of the most popular phone app

Off topic, but I havent heard of that at all. Where are you from? 

-----

I have a faint memory of not being able to install phone apps other than the system default ones since android 13. Dont quote me on that. If so, does these patches still worth the time to make, given it cannot be used on newer phones?

**Comment by AdishSagarawat** [comment]
Am from India

https://play.google.com/store/apps/details?id=com.truecaller

Is one of the most used app in India and has over 1B downloads.

**Comment by ILoveOpenSourceApplications** [comment]
#1536

**Comment by oSumAtrIX** [comment]
Please separate this issue for every feature request. Closing according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#%EF%B8%8F-guidelines-for-requesting-or-contributing-patches). Thanks anyways.
