### ISSUE TITLE
bug: Error applying patches

### ISSUE THREAD

**Issue by gosndka** [revanced/revanced-patches#887]
### Type

Error while patching

### Bug description

Hello, I found out that I can't apply patches to the old version of youtube 17.34.36. I am well aware of the discontinued support for android 7. As I got an ad on my home feed, I tried to apply the new patches and got those errors. I apologize in advance for wasting your time. I hope someone can help me out.

### Steps to reproduce

Step1: Download the required files like revanced patches, revanced cli and revanced integrations
Step2: Download youtube v17.34.36
Step3: Apply the patches

### Relevant log output

```shell
The log file is attached as below
```

### Additional context

[logs.txt](https://github.com/revanced/revanced-patches/files/9887835/logs.txt)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Parsa307** [comment]
this version it's not supported 😔 because of that it happens

**Comment by Tomodoro** [comment]
I was going to open an issue until I found yours. I can confirm this happens with Youtube v17.33.42 too, checking my logs against yours the same message repeats for every failed patch:

`depends on 'settings' but the following error was raised: 'settings' did not succeed previously`

I thought that maybe the support for older versions was removed, but the `settings` patch has as Target Version `all`.

**Comment by PandoraHayami** [comment]
I'm having the same issue with 17.33.42.

**Comment by Canny1913** [comment]
Is this issue still active?

**Comment by ILoveOpenSourceApplications** [comment]
In hopes that this is an issue related to a old versions, can't this be closed now?

**Comment by oSumAtrIX** [comment]
The issue is offtopic to this repository.
