### ISSUE TITLE
feat(patch): 

### ISSUE THREAD

**Issue by mickey66092** [revanced/revanced-patches#892]
### Application

Revanced youtube

### Issue

When i have 1 of my fingers in the player window it activates the "hold & swipe time seek" function.  Super annoying when watching something and it activates and pops up and or swipe accidentally.

### Patch

Idk if it was intergrated in the "press to swipe gestrure" patch in the swipe controls section, but anyways disabling or activiting it doesnt change it. Would be nice if the patch gets added or fixed if its that one in the section i mentioned. Atleast a toggleable option for it.

### Motivation

Its rlly a annoying thing while watching, so making a toggleable option for it so it can be disabled is a huge annoyance removal for mobile users.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [ ] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
How is it a "huge annoyance", simply don't hold 1 of your finger on the screen.

**Comment by mickey66092** [comment]
> How is it a "huge annoyance", simply don't hold 1 of your finger on the screen.

Yea sure dude, try to hold the phone with 1 hand comfy while watching in bed without touching the screen🤷‍♂️ "simply dont hold youre screen with one finger" is an equivalent in this case as "then dont watch to ads when they come up" or something else. But whatever lol

**Comment by oSumAtrIX** [comment]
If I watch a video, I generally do not want a finger in front of the video, which is why I hold the phone on the side. Problem solved.

**Comment by mickey66092** [comment]
Who says i dont have my phone in full screen in landscape mode and holding on the side? Second when you have it in fullscreen it has black bars on the side not enough for putting fingers infront of the video. Third thing, why having that "feature" if you could tap on the left or right and scroll on the seekbar? Kinda useless, especially if you dont need/want it and cant turn it off nowhere.
