### ISSUE TITLE
The performance of ReVanced is very poor

### ISSUE THREAD

**Issue by Nizami20052022** [revanced/revanced-patches#895]
### Type

Other

### Bug description

I patched the latest version of supported YouTube in the manager and ReVanced runs hard and opens late.But I patched YouTube version 17.01.35 and ReVanced worked perfectly.Also, the size of the ReVanced application has increased to 199 MB

### Steps to reproduce

1.Patch YouTube
2.Open ReVanced
3.Lag opening and after opening, the video opens late, up and down movement is not working well. The app is not working stably.

### Relevant log output

```shell
.
```

### Screenshots or videos

There is no need for that.

### Solution

I dont know

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by reisxd** [comment]
> But I patched YouTube version 17.01.35 and ReVanced worked perfectly

That's impossible.

> Lag opening and after opening, the video opens late, up and down movement is not working well. The app is not working stably.

Disable the `enable-debugging` patch.

**Comment by Nizami20052022** [comment]
How?

**Comment by reisxd** [comment]
> How should I do it?

You don't select the patch in Manager and exclude it by passing the argument `-e enable-debugging` in CLI.

**Comment by Nizami20052022** [comment]
But why do ReVanced and ReVanced manager applications take up so much space in the device's memory?

**Comment by oSumAtrIX** [comment]
Unrelated/Offtopic.
