### ISSUE TITLE
RYT Sponsorblock patch "About" section overflows

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [revanced/revanced-patches#898]
### Type

Cosmetic

### Bug description

The "About" sections in Sponsorblock patch overflows

### Steps to reproduce

1. Patch YT 17.41.37 with patch version 2.97.0 and manager 0.0.36, with at least microG and sponsorblock patch
2. Install and open the app
3. Open RYT settings > sponsorblock
4. Scroll to bottom
5. Observe overflow issue at the very bottom

### Relevant log output

```shell
N/A
```

### Screenshots or videos

![Screenshot_2022-10-29-16-47-57-604-edit_app revanced android youtube](https://user-images.githubusercontent.com/64138578/198822729-7a197d69-4143-4799-9b46-d7927468e659.jpg)

### Solution

Allow the text to warp around and use another row

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by SodaWithoutSparkles** [comment]
@oSumAtrIX Is that you?

**Comment by oSumAtrIX** [comment]
It overflows because it is long.

**Comment by SodaWithoutSparkles** [comment]
Well, if you dont care then okay...

Maybe add another row/entry? like: 

```
integration by ...
recoded by ...
```

instead of:
 ```
intergration by ..., recoded by ...
```

**Comment by oSumAtrIX** [comment]
That page is subject to be recoded entirely at some point already, that would include fixing minor issues such as this one.

**Comment by SodaWithoutSparkles** [comment]
wouldn't it make sense to reopen this issue until recoded?

**Comment by oSumAtrIX** [comment]
Instead an issue about a full rewrite should be opened.

**Comment by SodaWithoutSparkles** [comment]
okay. Which issue was that? I would like to subscribe to that to follow the progress

**Comment by oSumAtrIX** [comment]
It should be opened as previously mentioned.
