### ISSUE TITLE
bug: Patched Messenger can't co-exist with Facebook app, due to permission conflicts

### ISSUE THREAD

**Issue by n1cKz1** [ReVanced/revanced-patches#901]
### Type

Other

### Bug description

While trying to install a patched Messenger apk, i had to uninstall Facebook for it to successfully install, otherwise i'd get the "App was not installed" error. Logs below.

### Steps to reproduce

1. Have Facebook (com.facebook.katana) installed.
2. Try to install Messenger ReVanced. It will fail to install unless you uninstall Facebook.

### Relevant log output

```shell
This is what I got after trying to install with SAI:

INSTALL_FAILED_DUPLICATE_PERMISSION:
Package com.facebook.orca attempting to redeclare permission com.facebook.receiver.permission.ACCESS already owned by com.facebook.katana
```

### Additional context

While there isn't anything wrong with the patched Messenger itself, these 2 apps usually go hand-in-hand, so I thought it best to report it. Is there anything that can be done about this?

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by BobbyWibowo** [comment]
This issue appears to still exist. I was trying to install a patched Messenger earlier today, and I got the same error:
```
$ adb install .\messenger-revanced_v439.0.0.29.119-patches_v3.1.0.apk
Performing Streamed Install
adb: failed to install .\messenger-revanced_v439.0.0.29.119-patches_v3.1.0.apk: Failure [INSTALL_FAILED_DUPLICATE_PERMISSION: Package com.facebook.orca attempting to redeclare permission com.facebook.receiver.permission.ACCESS already owned by com.facebook.katana]
```
Patched using ReVanced Manager 1.18.0 with patches 3.1.0 (merely copied the patched APK to PC during investigation)

cc. @oSumAtrIX

**Comment by n1cKz1** [comment]
Just use MRVPatcher to install Facebook for now until the issue is solved

**Comment by oSumAtrIX** [comment]
https://github.com/ReVanced/revanced-patches/issues/1063
