### ISSUE TITLE
bug: <If You Press Home Button And Back Button In Youtube This Happens Dislike It's Not Showing>

### ISSUE THREAD

**Issue by Parsa307** [revanced/revanced-patches#902]
### Type

Other

### Bug description

If You Press Home Button Dislike And Back Button It's Not Showing

### Steps to reproduce

1- I Pressed Home Button And Back Button In Youtube Revanced And The Dislike It's Not Showing

### Relevant log output

```shell
I Don't Have Any Logs
```

### Solution

1- Don't Press Back Button And Home Button

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by SodaWithoutSparkles** [comment]
@Parsa307 Possible similar issue: #901
