### ISSUE TITLE
feat(patch): A patch to set Accepted-language/Preferred Language on Samsung Internet

### ISSUE THREAD

**Issue by trmdi** [ReVanced/revanced-patches#906]
### Application

Samsung Internet.

### Issue

It does not let the user change the Preferred language like other browsers so some websites would be displayed in wrong languages.

### Patch

This patch should add a new setting that let the user change it.

### Motivation

This is a really good browser with the best dark mode on Android.
Besides the dark mode, it's also very lightweight compared to Firefox and its video player supports touch screen much better than FF...

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Julmik647** [comment]
> > > > Firefox, Kiwi and many more
> > > 
> > > 
> > > I tried all of them. Not better. Probably you haven't used Samsung Internet. Give it a try you will love it.
> > 
> > 
> > Edge and Opera have Accounts for Synchronization of other devices. I actually use Opera Browser, Norway is known for Strict Privacy laws unlike Microsoft which is a US Company.
> 
> Edge doesn't have the dark mode and adblocker. Opera's built-in adblocker is too bad compared to Samsung Internet's Adguard.

You can use full Adguard version that works on entire device.
