### ISSUE TITLE
Add Custom Branding to YouTube Music

### ISSUE THREAD

**Issue by HauntedKnives** [revanced/revanced-patches#913]
### Application

YouTube Music

### Issue

Add Custom Branding to YouTube Music

### Patch

Hi,
It would be great to ad custom branding to YouTube Music.
Thank you

### Motivation

It would be great to ad custom branding to YouTube Music. The default name 'YouTube Music ReVanced' is a long name. It is better to add an option to change the name.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by FineFindus** [comment]
Hey,
If there is nobody else working on it and no blocking issues, 
I would like to try and do this.

**Comment by ILoveOpenSourceAppications** [comment]
Yes please. Similar to YouTube app patch, one which allows the ReVanced icon and name and another which gives default icon and name of YT Music.

**Comment by introversialscalpel** [comment]
Yes please! much needed.

**Comment by ILoveOpenSourceAppications** [comment]
Can't the name be kept just to YT Music and not YT Music ReVanced?

**Comment by ILoveOpenSourceAppications** [comment]
Remove ReVanced from YT Music ReVanced and add a custom naming option for those who require the name would be better.

**Comment by theolike** [comment]
Why was this closed as completed?  I can't find where this functionality was added.

**Comment by ILoveOpenSourceApplications** [comment]
A duplicate issue was opened which is #1567 and hence this was closed.
