### ISSUE TITLE
bug: Youtube "Comments" patch still shows comments even when everything's hidden

### ISSUE THREAD

**Issue by ante2103** [revanced/revanced-patches#914]
### Type

Cosmetic

### Bug description

Hi so when patching youtube with version 17.41.37 with "comments" patch it still shows comments despite being "hidden" in settings

### Steps to reproduce

1. Patch youtube 17.41.37 with "comments" patch
2. Set it to "hidden" in youtube settings

### Relevant log output

```shell
N/A
```

### Screenshots or videos

![Screenshot_20221030-143851_YouTube](https://user-images.githubusercontent.com/92825684/198881615-e6ef1c3a-5b29-4218-9c61-171a7feb9954.jpg)
![Screenshot_20221030-143858_YouTube](https://user-images.githubusercontent.com/92825684/198881624-31bb7534-d4bc-41c0-87cf-3f444967eb85.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by OxrxL** [comment]
Fixed and merged: https://github.com/revanced/revanced-integrations/commit/d28d65734e46e77db3a9cce2b1f323b593fc1a46

**Comment by ante2103** [comment]
@OxrxL so should I repatch it or?

**Comment by OxrxL** [comment]
> @OxrxL so should I repatch it or?

Yes.
