### ISSUE TITLE
Function completely remove comments from screen is not working in new layout

### ISSUE THREAD

**Issue by Frontline11** [revanced/revanced-patches#917]
### Type

Error at runtime

### Bug description

I did several tests and this function is not working in Layout Nova is not removing the comments from the screen the function still appears

### Steps to reproduce

![Screenshot_20221029-195531_YouTube](https://user-images.githubusercontent.com/101657790/198890907-aba3dc91-309a-42aa-86e5-18ecc0ea8753.jpg)

### Relevant log output

```shell
no logs
```

### Screenshots or videos

![Screenshot_20221029-195541_YouTube](https://user-images.githubusercontent.com/101657790/198890722-892e7972-03ce-4a70-96fe-2f7cd9611844.jpg)

### Solution

I really want you to fix this bug

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
You are using outdated patches.
