### ISSUE TITLE
bug: Dark mode messed up in Shorts comments

### ISSUE THREAD

**Issue by Xandar-YT** [revanced/revanced-patches#922]
### Type

Cosmetic

### Bug description

When you try to write a new comment in YouTube Shorts, it's messed up in dark mode. It's white background with white text which is almost unreadable. It should be dark background with white text.

### Steps to reproduce

1. Open YouTube shorts

2. Open comments

3. Try to write a new comment

### Relevant log output

```shell
Not needed, purely cosmetic
```

### Screenshots or videos

![Screenshot_2022-10-30-19-20-06-187_app revanced android youtube](https://user-images.githubusercontent.com/84316546/198895292-13402274-360c-4491-885b-3dbf4d5fa943.jpg)

### Solution

Fix the coloring 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by SodaWithoutSparkles** [comment]
> ![Screenshot_2022-10-30-19-20-06-187_app revanced android youtube](https://user-images.githubusercontent.com/84316546/198895292-13402274-360c-4491-885b-3dbf4d5fa943.jpg)

Yes, I can. 
Anyway, does this regularly happen or its just some of the times? I have disabled shorts.

**Comment by Xandar-YT** [comment]
It happens every time. And I didn't disable shorts because I like to watch
the non-cringe ones.

**Comment by george-emerald** [comment]
Will this ever be addressed?

**Comment by Ushie** [comment]
> Will this ever be addressed?

This is what this GitHub issue is for

**Comment by OxrxL** [comment]
> ### Type
> Cosmetic
> 
> ### Bug description
> When you try to write a new comment in YouTube Shorts, it's messed up in dark mode. It's white background with white text which is almost unreadable. It should be dark background with white text.
> 
> ### Steps to reproduce
> 1. Open YouTube shorts
> 2. Open comments
> 3. Try to write a new comment
> 
> ### Relevant log output
> ```shell
> Not needed, purely cosmetic
> ```
> 
> ### Screenshots or videos
> ![Screenshot_2022-10-30-19-20-06-187_app revanced android youtube](https://user-images.githubusercontent.com/84316546/198895292-13402274-360c-4491-885b-3dbf4d5fa943.jpg)
> 
> ### Solution
> Fix the coloring
> 
> ### Additional context
> _No response_
> 
> ### Acknowledgements
> * [x]  I have searched the existing issues and this is a new and no duplicate or related to another open issue.
> * [x]  I have written a short but informative title.
> * [x]  I filled out all of the requested information in this issue properly.

After the fix:

![Screenshot_20221113_044934](https://user-images.githubusercontent.com/108184954/201504735-ae518a2c-5d08-41db-8cc7-6abd08cc1457.png)

**Comment by Xandar-YT** [comment]
Thanks for fixing this!

**Comment by oSumAtrIX** [comment]
Reopened due to https://github.com/revanced/revanced-integrations/pull/210. A fix might be related to #1045.

**Comment by george-emerald** [comment]
So this is fixed? Do I have to build the APK myself or will downloading from the site work?

**Comment by george-emerald** [comment]
@oSumAtrIX can you please tell me how I can update to this? Do I download the apk in the release and it'll update the YouTube app? Or are some extra steps required?
