### ISSUE TITLE
add x2 speed button option in player overlayfeat(patch): 

### ISSUE THREAD

**Issue by nochlab1** [revanced/revanced-patches#927]
### Application

Youtube

### Issue

Some channels i want different speeds 

### Patch

 think there is enough space for another button on player overlay and it would be really nice as its the option i toggle the most
and preferred speed wouldn't help as it depends on the channel if I want a higher speed or not

### Motivation

ts the option i toggle the most and preferred speed wouldn't help as it depends on the channel if I want a higher speed or not

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Bluscream** [comment]
I have made an automagic (alternative to tasker) patch for this

**Comment by akvabhi** [comment]
> I have made an automagic (alternative to tasker) patch for this

possible to share the same ?

**Comment by nochlab1** [comment]
> > possible to share the same ?
> 
> sure thing, i've dropped it as a gist: https://gist.github.com/Bluscream/737e49e848ec14f7b52189a30d11b9ef (requires [Automagic](https://automagic4android.com/))

is it possible to send instructions how to use?
thanks

**Comment by oSumAtrIX** [comment]
Closing in favour of #1234.
