### ISSUE TITLE
feat(docs): Add a single recommended version for apps

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [ReVanced/revanced-patches#931]
### Application

this repo's documentation.

### Issue

The multiple "target version" is very confusing to new users, they cannot comprehend which version they should use, especially when the "target version" is different between patches of the same application.

The term "target version" seems to be targeted towards patch maintainers to make sure their patches work on that version, but not towards users who want to patch.

### Patch

Add recommended/suggested version to the README. The recommended version should be the latest version that is the most compatible with the most patches. The exact location for the version is yet to be decided.

### Motivation

The multiple "target version" is very confusing to new users, they cannot comprehend which version they should use, especially when the "target version" is different between patches of the same application.

The term "target version" seems to be targeted towards patch maintainers to make sure their patches work on that version, but not towards users who want to patch.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by SodaWithoutSparkles** [comment]
Closed this issue as it was partially implemented by both manager and website.

**Comment by Ushie** [comment]
for a moment I thought you had triage perms
