### ISSUE TITLE
darkmode

### ISSUE THREAD

**Issue by anyz0** [revanced/revanced-patches#943]
### Type

Cosmetic

### Bug description

darkmode changed to black why? I've been disabled (-e theme)

### Steps to reproduce

.

### Relevant log output

```shell
.
```

### Screenshots or videos

.

### Solution

.

### Additional context

.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Freepony** [comment]
Same here. After installing 2.100.2 the bug is still in effect. The dark theme works only in Revanced options including SponsorBlock and Return Youtube Dislike. General Youtube options, home screen and everything else are on a black background.

**Comment by K3LS0** [comment]
Same problem here. Both on root and non-root install. The app is in "grey" theme on first launch, and turns to "black" theme after restarting the app. App version 17.41.37, patch version 2.100.3 on on Pixel 6 Android 13.

**Comment by oSumAtrIX** [comment]
Please attach a recording of the issue.

**Comment by K3LS0** [comment]
Here's a video of the issue. When I wipe the app data, the theme goes back to grey again, but restarting still forces black theme.

https://user-images.githubusercontent.com/94309910/199261497-8a9de78b-8c77-461f-b9a6-473704e37839.mp4

**Comment by nibir34** [comment]
This is the updated UI of YouTube app. Not a bug I guess.

**Comment by kazimmt** [comment]
This is YouTube New UI
It close to Black (Not Actual Black neither Dark)

**Comment by gwolf2u** [comment]
confirmed
this is the new dark mode (more black)

**Comment by BrandonH28** [comment]
thanks for the info. so is it some kinda 'bug' on YouTube's end that it's not as dark at first, but then gets blacker when it's relaunched? cause that little glitch is what made me think it was the patch
