### ISSUE TITLE
feat(patch): Enable copying

### ISSUE THREAD

**Issue by Vojtak42** [revanced/revanced-patches#944]
### Application

Youtube

### Issue

As I am not natively english speaking, I sometimes come across word that I don't know, so I could copy it and paste it in translator.

### Patch

Possibility to copy in revanced youtube.

### Motivation

I think I am not the only one who would appreciate it.

### Acknowledgements

- [x] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by rohan2000github** [comment]
For this i suggest u to use Google lens

**Comment by lord-jashin** [comment]
I hope revanced team takes this request seriously. Closing issues as not planned will stop others from bringing it up ever

**Comment by Canny1913** [comment]
We do take issues seriously. We only close issues that doesn't meet acknowledgements.

**Comment by ILoveOpenSourceApplications** [comment]
#1350

**Comment by SodaWithoutSparkles** [comment]
@ILoveOpenSourceApplications maybe closing as not planned would be better? This issue has not been fixed, but transferred

**Comment by ILoveOpenSourceApplications** [comment]
Duplicate of #1350
