### ISSUE TITLE
bug: YouTube minimized playback renders cropped part of the app screen

### ISSUE THREAD

**Issue by nikita488** [revanced/revanced-patches#947]
### Type

Cosmetic

### Bug description

When I installed the patched version 17.41.37 with the default patch set and switched to picture-in-picture mode, the video appears as it should, but then after closing and opening the app for a day, it started to display a cropped part of the app in this mode, and you you can see not the video itself, but the number of likes, comments section, etc. I can't get it to display the video again without reinstalling.
It worked fine when I used version 17.34.36.

### Steps to reproduce

1. Open any video using YouTube ReVanced
2. Switch to picture-in-picture mode
3. See the error
4. Repeat above steps a few more times if it didn't happen

### Relevant log output

```shell
Not needed i guess
```

### Screenshots or videos

![image](https://user-images.githubusercontent.com/6237881/199105029-a5b0193b-90c5-4e75-aff3-c8d0fda976dd.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
https://user-images.githubusercontent.com/13122796/199106785-df253f0e-0890-4889-bd6c-f53de45c8327.mp4

**Comment by oSumAtrIX** [comment]
Please check, if this also happens on the unpatched app.

**Comment by nikita488** [comment]
Well, the pip mode never worked for me in the original YouTube app, that's why i started using Vanced back in the days and now ReVanced, so not sure how to check that sadly. This is the video preview of what's happening right now:

https://user-images.githubusercontent.com/6237881/199111373-bd93b75a-fed8-438b-921d-2a5cc887c3ad.mp4

**Comment by oSumAtrIX** [comment]
For now, we need to see if this an actual issue with ReVanced. For that we need someone who can repro this issue on the patched app and unpatched app.

**Comment by nikita488** [comment]
Just got YouTube Premium and installed original YT, and after many attempts to reproduce it i finally did it, seems like original app bug. Sorry!
