### ISSUE TITLE
bug: Youtube download button patch still shows premium prompt

### ISSUE THREAD

**Issue by justastranger** [revanced/revanced-patches#948]
### Type

Error at runtime

### Bug description

The download button patch adds the download button, but prompts you to either accept their free trial of premium (which requires a cc) or cancel the download attempt. From what I've been able to ascertain, the download button should try to launch a different app or bring up the share menu or something.

### Steps to reproduce

Step 1. Install the download button patch.
Step 2. Pick a video.
Step 3. Press the download button.

### Relevant log output

```shell
N/A
```

### Screenshots or videos

![Screenshot_20221031-171332](https://user-images.githubusercontent.com/6827479/199120565-8c22df71-fc22-4238-a127-83ed55de9bc5.png)

### Additional context

Using the latest recommended version of youtube, patched today

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
You need premium to use it.

**Comment by justastranger** [comment]
So what's the point of the patch then?

**Comment by oSumAtrIX** [comment]
As previously mentioned:

> The download button patch adds an impossible to not notice button on the player.

**Comment by justastranger** [comment]
That is indeed the functionality, but what's the *point*?

**Comment by oSumAtrIX** [comment]
Not sure wym, the point of the downloads patch is to download content off the app

**Comment by justastranger** [comment]
If you have premium. The point of the other patches is so you *don't* need premium to enjoy features (like the ad removal) or to get features that even premium doesn't offer (like sponsorblock). Adding yet another functionally worthless download button (for 90% of people) is pretty much pointless.

**Comment by oSumAtrIX** [comment]
The downloads patch does not add another yet functionally worthless download button. You can use the patch to download videos without any premium subscription.

**Comment by justastranger** [comment]
> You can use the patch to download videos without any premium subscription.

> [You need premium to use it.](https://github.com/revanced/revanced-patches/issues/948#issuecomment-1297771777)

🤔

**Comment by oSumAtrIX** [comment]
That refers to the button you questioned. I am talking about the button, the patch adds.

**Comment by justastranger** [comment]
Then I mislabeled this issue as there is only one patch containing the word "download", the regular downloads patch that is 100% installed during the taking of the screenshot in the OP.

**Comment by oSumAtrIX** [comment]
![Screenshot_2022-10-31-23-59-51-86_3aea4af51f236e4932235fdada7d1643](https://user-images.githubusercontent.com/13122796/199125641-c9864789-2fe3-474f-a4f1-1b4a4c43d7e1.jpg)

**Comment by justastranger** [comment]
So what, the main button doesn't work but the one added to the player does? And that's not confusing to you?

**Comment by justastranger** [comment]
Should seriously make both buttons do the same thing, can't be that difficult when there's already one functional button

**Comment by Sculas** [comment]
I myself was quite confused as well as to why the patch adds another button instead of replacing the existing one (its on-click listener). But oh well, that's up to the patch developer.

**Comment by oSumAtrIX** [comment]
> So what, the main button doesn't work but the one added to the player does? And that's not confusing to you?

The main button is for premium users, for when you download to the YouTube library, the downloads patch on the other hand adds the functionality to download to your storage.

**Comment by oSumAtrIX** [comment]
@Sculas 
> I myself was quite confused as well as to why the patch adds another button instead of replacing the existing one (its on-click listener). But oh well, that's up to the patch developer.

Because the button is a litho component it is not as easy as you think, ideally the patch would hook the event listener. Hiding the download button is already possible though.

**Comment by Sculas** [comment]
> Because the button is a litho component it is not as easy as you think, ideally the patch would hook the event listener. Hiding the download button is already possible though.

@oSumAtrIX Maybe auto-hide the Premium download button if the user doesn't have Premium? Sounds like a good solution to me. Of course this should be a setting as well.

**Comment by oSumAtrIX** [comment]
Hiding is controlled by the `hide-action-buttons` patch. By preference, the downloads button is visible by default and can be disabled in the settings. There are several users, who might want to download to storage but also use the native downloads option from YouTube.
