### ISSUE TITLE
bug: SponsorBlock userID not generated

### ISSUE THREAD

**Issue by mchangrh** [revanced/revanced-patches#949]
### Type

Other

### Bug description

On initial install, the SponsorBlock privateID is not generated, which returns error 400 bad request when voting or submitting new segments

### Steps to reproduce

1. Install YouTube with SponsorBlock Patch
2. Settings -> SponsorBlock
3. Your private user id
4. UserID should be pre-filled with random characters but is empty

### Relevant log output

```shell
-
```

### Solution

The PrivateID should be generated if it is empty with a random 36 alphanumeric string if it is empty

Or the actual error content returned by the API which specifies that the UserID is missing should be displayed so the user can take action on it.

### Additional context

The current workaround seems to be:
1. generate a random 36 character string [my personal preference](https://mchangrh.github.io/sb-idgen/)
2. Navigate to the SponsorBlock settings -> Import/ Export Settings
3. Manually populate the `userID` key in the json to the random string

**Comment by oSumAtrIX** [comment]
#663.
