### ISSUE TITLE
bug: The icon of Youtube Revanced looks aliased

### ISSUE THREAD

**Issue by trmdi** [revanced/revanced-patches#951]
### Type

Cosmetic

### Bug description

The icon need some improvement.

### Steps to reproduce

.

### Relevant log output

```shell
.
```

### Screenshots or videos

![IMG_20221101_211856](https://user-images.githubusercontent.com/11857205/199255298-cf2f3026-c3ec-4164-a714-7787cc73d74e.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by SCP-017** [comment]
I don't see what's wrong with the icon.

**Comment by trmdi** [comment]
> I don't see what's wrong with the icon.

You don't see it's aliased/jagged... ?

**Comment by SodaWithoutSparkles** [comment]
Did you mean the icon looks low-res?

**Comment by trmdi** [comment]
> Did you mean the icon looks low-res?

Kind of this. Do you also see it's aliased/jagged?

**Comment by floppyD** [comment]
I noticed this too, I don't think it was like this a few versions ago.
![IMG_20221103_122330](https://user-images.githubusercontent.com/29208110/199762506-c31b5b7e-db7e-4c2b-b32a-8c5cb26c192c.jpg)

**Comment by gergthewerg** [comment]
I have the same issue, but for me it looks slightly worse when its in the edge panel with the apps

**Comment by Matty003** [comment]
It's solved with latest (v2.106.1) patches version.

**Comment by trmdi** [comment]
> It's solved with latest (v2.106.1) patches version.

Can confirm.
