### ISSUE TITLE
bug: Video restarts from the beginning every time

### ISSUE THREAD

**Issue by QuantumGoddess** [revanced/revanced-patches#958]
### Type

Other

### Bug description

Selecting a video that you have already watched halfway through (ie videos with a red bar showing any progress) will always start from the beginning of the video, instead of remembering the progress and continuing. 

### Steps to reproduce

Step 1. Select any YouTube video. Step 2. Watch it partway through. Step 3. Exit the app. Step 4. Start the video again. Step 5. The video will restart instead of continuing.

### Relevant log output

```shell
.
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Cypher-Emm** [comment]
Never faced this issue. Every video plays from where i left off. Are u using an adblocker?
Have u checked whether watch  history is  getting saved or not.
Whitelist s.youtube.com in adblocker and check

**Comment by oSumAtrIX** [comment]
That is caused by the switch you enabled to fix video ads.

**Comment by QuantumGoddess** [comment]
I messed around with the settings, and it seems like turning on 'fix video playback issues' causes this to happen. If I turn the setting off, it works normally.

**Comment by razza-guhl** [comment]
> 

Thank you! Turning off the option fixed the issue for me too

**Comment by MoShahid23** [comment]
@oSumAtrIX any idea if or when there may be a better solution to the playback issue? Also just wanted to say thank you for all your hard work.
