### ISSUE TITLE
feat(patch): Old Video Layout

### ISSUE THREAD

**Issue by kairusds** [revanced/revanced-patches#975]
### Application

YouTube

### Issue

This patch can solve the issue with Return YouTube Dislike and the buttons being hard to press due to their small size.

### Patch

The layout for the "Your videos" menu on YouTube 17.36.37(as shown on the image below) seems to be using the old layout and I want to ask if it's possible to force all videos to use this UI instead of the new one.

![IMG_20221104_214157](https://user-images.githubusercontent.com/32636532/199988694-47568929-30ee-4429-ac11-bb9b949fa139.jpg)

### Motivation

This is useful for people who prefer the old layout and it'll be helpful for preventing the Return YouTube Dislike patch from breaking in the future.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by TNTberry** [comment]
I would also like this feature

**Comment by ILoveOpenSourceApplications** [comment]
#1449
