### ISSUE TITLE
Add option for permanet playback speed and gradual speed options

### ISSUE THREAD

**Issue by Fooftilly** [revanced/revanced-patches#98]
So, just like there was an option in Vanced to make playback speed permanent to 2x or lower, there should be an option for this in ReVanced too. Also, while 2x, 3x, 4x... speed are useful, something like gradual speed control would be nice (I, for example, watch Youtube at 2.7x speed and I would like to be able to change speed in increments of 0.05 or 0.10 like in VLC).

**Comment by bogadana** [comment]
custom speeds will be implemented once settings come around. for now you can manually change the array in integrations

**Comment by wongcheehong** [comment]
@bogadana I saw settings patch has been released. Is custom speed possible now?
