### ISSUE TITLE
A black triangle covers the bottom-right part of thumbnail

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [revanced/revanced-patches#980]
### Type

Cosmetic

### Bug description

When browsing the home feed, theres a black triangle covering the bottom-right part of thumbnail occasionally

### Steps to reproduce

1. Patch with all patch except wide search bar and debug
2. browse the home feed until this happens, it will usually appear in the first 100 videos

### Relevant log output

```shell
N/A
```

### Screenshots or videos

![IMG_20221105_134142](https://user-images.githubusercontent.com/64138578/200104444-b25fb198-30d1-4ebd-9db4-02fdebf9f7af.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Include proper reproduction steps after narrowing down which patch causes it by disabling them. Start with the patch `general-ads`  and `theme`.

**Comment by SodaWithoutSparkles** [comment]
I have just narrowed down a bit: the triangle always appears of theres a black bar telling you that this video is in your watch later, or others who watch X's video also watches this.

**Comment by oSumAtrIX** [comment]
I am talking about which patch caused it.

**Comment by johnconner122** [comment]
It is a YouTube bug not revanced

**Comment by SodaWithoutSparkles** [comment]
It seems that it was solved now
