### ISSUE TITLE
feat(patch): Youtube Hide recommended videos

### ISSUE THREAD

**Issue by mangoepic** [ReVanced/revanced-patches#981]
### Application

Youtube

### Issue

Like the Unhooked Chrome extension it should give the option to disable the home feed or maybe even recommended videos etc per option.

### Patch

Options to
 - Disable startpage (remove from bottom toolbar)
 - Disable recommended videos
 - Shorts? not sure if already has a patch
 - Other things maybe inspired by Unhooked

### Motivation

Reasoning for this is to help make YouTube less addictive and a more deliberate tool of choice.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by thevenusbhatia** [comment]
> .

can you give me the custom filter to hide the Home Feed on YouTube??

**Comment by matt873** [comment]
> This is highly dangerous as it strains the API.

Any plans to implement a better way to hide related videos?

**Comment by Hentuloo** [comment]
> > can you give me the custom filter to hide the Home Feed on YouTube??
> 
> You can already hide the home button on the navigation bar. Look under the hide navigation buttons menu.
> 
> ![Hide navigation buttons](https://private-user-images.githubusercontent.com/118716522/307046932-38ee82d7-88a6-4ac9-8a81-0b4ba6daf196.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1MDQ4MjIsIm5iZiI6MTcxNTUwNDUyMiwicGF0aCI6Ii8xMTg3MTY1MjIvMzA3MDQ2OTMyLTM4ZWU4MmQ3LTg4YTYtNGFjOS04YTgxLTBiNGJhNmRhZjE5Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMlQwOTAyMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZDJiODY1MWMyYmZhMWY5NzQ5Yjk0MGFiZGRkZTdhMTgwZmY1NzQ1MTU0YTlhNjFiZDQ4ODU2OTc1N2IxMWE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.oRcfZc_061UbWVRzh4vUn3vNuI2_9PmS6qntF_xWO-8)

This feature is very useful for me. Thanks!

However, I've encountered another 'issue.' I would like to completely restrict access to the home view.

I have it set so that the default screen is the library, but when I click the back button, the application shows me the Home view. Is there perhaps a way to block the return to the previous screen? Or any other approach that will prevent access to Home?

**Comment by InsaneCoder69** [comment]
> > I have it set so that the default screen is the library, but when I click the back button, the application shows me the Home view. Is there perhaps a way to block the return to the previous screen? Or any other approach that will prevent access to Home?
> 
> Use a different start page with `General > Change start page` and the back button will navigate back to that page.

Tbh the best way to hide every from home feed is,

Step 1 : Filter the hide feed with "views" 
Step 2 : Disable Community posts in home feed
Step 3 : Disable Shorts from home feed ( shorts > disable shorts home feed).

Worked for me.

**Comment by LisoUseInAIKyrios** [comment]
It's worth pointing out that "open videos fullscreen portrait" hides the player suggested videos, comments, and everything not related to the video itself.
