### ISSUE TITLE
feat(patch): Material You icon support for YouTube Revanced

### ISSUE THREAD

**Issue by ItzDatMC** [revanced/revanced-patches#985]
### Application

YouTube ReVanced

### Issue

The improperly themed icons when used with Themed icons on Android 12/13. 
![image](https://user-images.githubusercontent.com/33323458/200182943-92e8eac4-24f1-4486-9309-2df37db02992.png)

### Patch

A patch that makes the app work with Themed icons option for Android 12/13 like the stock YouTube app. 
![image](https://user-images.githubusercontent.com/33323458/200183068-2335f103-cfdf-46c9-ad9b-792192dafd13.png)

### Motivation

A more uniformity home screen and it matches with other apps that support Material You theming. 
Pixel Launcher users (which has no custom icon pack support) can enjoy the look & feel of the Themed icons feature. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by ILoveOpenSourceAppications** [comment]
Does this issue still exist? Can't this be closed of not?
