### ISSUE TITLE
bug: SponsorBlock Skips Random Sections of Shorts

### ISSUE THREAD

**Issue by george-emerald** [revanced/revanced-patches#986]
### Type

Error at runtime

### Bug description

SponsorBlock skips random sections of shorts for no reason making them unwatchable. I have confirmed that this is a client bug in the SponsorBlock repo. Shorts don't have sponsored segments or intros so nothing should be skipped.

### Steps to reproduce

1. Play shorts.
2. Stumble upon an affected one.
3. Notice how random sections are skipped (either as Sponsored or as Self-Promotion most likely).

### Relevant log output

```shell
Not sure how to access the log. But even if I did, I'm not sure any output would be relevant.
```

### Solution

Disable SponsorBlock for shorts.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Please attach an example short.

**Comment by george-emerald** [comment]
It's hard to stumble upon it, since it doesn't happen recently. It could also be related to other videos you're watching. For example, it could only happen if you're watching a video that has an early sponsored segment and that's transferred to the short.

It shouldn't happen at all, however. Shorts don't have anything that SponsorBlock should block so they should be an exception. It's pretty easy to make SponsorBlock not run on videos that are shorts-length.

Also, this isn't a question.

**Comment by oSumAtrIX** [comment]
Shorts can very well have segments which could be skipped by SponsorBlock. Please add a short when you find one.

**Comment by george-emerald** [comment]
I found one here. I haven't watched any normal video so we can rule out carry over. It doesn't have any sponsored content. The start is just skipped for no reason at all.

https://youtube.com/shorts/BZ0c6K2ejfE?feature=share

**Comment by george-emerald** [comment]
It skips part of the video here as well, where there's no sponsor or anything similar.

https://youtube.com/shorts/KK4o10Digtg?feature=share

**Comment by george-emerald** [comment]
Shorts aren't long enough to add sponsors, self-promotions or reminders which are the only categories set to be skipped automatically. So, I'm not sure what you're referring to. No such segments that SponsorBlock could skip are ever present.

**Comment by oSumAtrIX** [comment]
https://user-images.githubusercontent.com/13122796/201331173-edfe0279-08a1-400e-a6ad-6ce056949061.mp4

**Comment by oSumAtrIX** [comment]
It is not skipping for me. Disable all patches and record the issie with the patch causing the issue.

**Comment by george-emerald** [comment]
The video you opened skips much later than what you showed in your recording. Did you watch the whole video? The first one I linked is the one that skips at the start of it.

**Comment by george-emerald** [comment]
I just made a recording showing it being slipped later in the video, but for some reason it's not letting me upload it.

**Comment by oSumAtrIX** [comment]
It does not skip the video:
https://user-images.githubusercontent.com/13122796/201333099-018151cb-7eb1-4307-abcc-9b01c2e30afb.mp4

The first video also does not skip.

**Comment by george-emerald** [comment]
Uploading Screen_Recording_20221111_133830.mp4…

**Comment by george-emerald** [comment]
Hmmm OK. The APK I used wasn't taken from your official site, so I'll try reinstalling with your APK to see if that fixes the issue.

**Comment by george-emerald** [comment]
That fixed it. It was a problem with the APK I downloaded, sorry for taking up your time.

**Comment by george-emerald** [comment]
Actually SponsorBlock isn't working at all now that I reinstalled with your APK. Which is why nothing was skipped. I'll wait for it to start working and get back to you. Do you know why it could be not working at all? Should I delete all data before uninstalling or something?

**Comment by oSumAtrIX** [comment]
SponsorBlock is currently down.

**Comment by george-emerald** [comment]
OK, I'll let you know if this issue persists when it's back up. If it doesn't, I'll let you know and close it.

**Comment by george-emerald** [comment]
SponsorBlock is back up and the bug is gone. Looks like it was the APK I had.
