### ISSUE TITLE
bug: Weird UI Issue in Revanced

### ISSUE THREAD

**Issue by Matty003** [revanced/revanced-patches#991]
### Type

Cosmetic

### Bug description

I have seen this **weird** UI issue ( or maybe feature? ) that after getting all YouTube `default` hints, we generally see the **tabs** (Videos, Playlists, Community, etc.) containing `bar` **slides** **below** the YouTube channel's default **view** as shown below.

### Steps to reproduce

I've shown how to reproduce this issue in the `video` below.

### Relevant log output

```shell
None.
```

### Screenshots or videos

https://user-images.githubusercontent.com/109008434/200243685-8afb4ebe-e895-42ac-9c5b-f2e300dd59de.mp4

### Solution

Maybe stop this behaviour to default as it was like forever ?

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
There's no difference in the recording you sent with the unpatched YouTube client.

**Comment by Matty003** [comment]
> There's no difference in the recording you sent with the unpatched YouTube client.

Okay. Thanks mate 👍
