### ISSUE TITLE
feat(patch): Make Gapps to use Vanced MicroG

### ISSUE THREAD

**Issue by cheadrian** [revanced/revanced-patches#998]
### Application

Google Maps, Google News, Google Play, GMail and others apps made by Google.

### Issue

Huawei don't support native Gapps anymore, so this way it could enable it's users to use, at least, some of the Google Apps native on device.

### Patch

Simple patch other Google apps to use Vanced MicroG, like in the case of the Youtube.

### Motivation

Lack of GMS for Huawei.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Install MicroG.

**Comment by cheadrian** [comment]
MicroG doesn't work as it requires more permissions than the stock OS can provide to access Google Accounts. You can't sign in in the apps using MicroG.
